### ISSUE TITLE
Android Video Display Not Rendering

### ISSUE THREAD

**Issue by zabbott** [RenderHeads/UnityPlugin-AVProVideo#100]
**Describe the bug**
I have been using AVProVideo for a while now, and just got hit with a bug in which the videos I play through the Mediaplayer component in conjunction with the Display UGUI component don't render on android devices. I tried this with your default demo scene in an otherwise empty project and had the same issue. Further information: Audio is playing! I can hear everything, but no visuals. 

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.7 on my actual project and demo scene as well as 2019.1.7
 - AVPro Video version: 1.9.17b
 - Operating system version: as far as I can tell any android but confirmed on Android Version 9 
 - Device model: Samsung S9 as well as a few others that I don't have the specific information on.
 - Video specs (resolution, frame-rate, codec, file size): 
Resolution: 1024 x 1024
Frame Rate 30 fps
Codec AV Codec H.264
Filesize 3.49 mb

**To Reproduce**
1. Sorry this isn't super detailed, but I just set up the Media Player and the UGui Component and get no video playing on builds. Works fine in editor. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Would it be possible to post the logcat output?

**Comment by zabbott** [comment]
Here it is. Let me know if its the right format or if there's anything else you need. First time using Logcat output. This was built to my android s9 and is an empty unity project save your guys package, and I'm using you 04_Demo_UGui scene. Audio is playing but the attached image is all that appears
![Screenshot For Github](https://user-images.githubusercontent.com/10633372/60531661-16ffe100-9cc1-11e9-963d-90ceec07f5c6.png)

[Logcat.pdf](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3351148/Logcat.pdf)

**Comment by RenderHeadsSte** [comment]
Thanks.  Do you have an issue playing back in other ways, or is it just via UGUI?

**Comment by RenderHeadsSte** [comment]
Here is the interesting line in your logcat:

2019/07/02 11:56:27.863 21122 21139 Info Unity: [AVProVideo] Initialising AVPro Video (script
v1.9.17 plugin v1.9.17) on Adreno (TM) 630/Vulkan 1.1.66 [512.331.0] (MT True) on Android

AVPro does not currently support Vulkan.  Try setting the Graphics API to OpenGLES3.  Find this under:

Build Settings->Player Settings->Other Settings->Rendering

It may be set to auto currently, just un-tick this ('Auto Graphics API') and remove Vulkan from the list that appears.

**Comment by zabbott** [comment]
We are up and running! Thank you so much! Hadn't ever played with Graphics API settings too much so would have never thought to look at that. Thanks!
