### ISSUE TITLE
Crash due to video texture over-release in UnityGfxDeviceWorker

### ISSUE THREAD

**Issue by Zachzx0** [RenderHeads/UnityPlugin-AVProVideo#1000]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  core Edition 2.1.8
 - Operating system version:  IOS,15.0.2 (19A404)
 - Device model:  iPhone 11
 - Video specs (resolution, frame-rate, codec, file size): 

I got these crashes when i pause a playlist-video and then i modify its videoItems , jump to the Zero Index.

Just in IOS ,i ve no idea
**Screenshots**
![image](https://user-images.githubusercontent.com/41116914/140638872-dabb4d9f-cc80-4f4b-bed9-6bde3fde8fbc.png)
![image](https://user-images.githubusercontent.com/41116914/140638888-8489cf60-95dd-488d-b2ed-b15a600ca9ac.png)

**Comment by kahnivore** [comment]
Hi there, 

Could you please provide some more information:

1. What exactly do you mean by crash?
2. When you say it only happens in iOS, does it not happen in the editor? Are you on a Mac?
3. Have you tried any other devices besides the iPhone 11? 
4. Have you tried upgrading to the latest version of AVPro Video? 
5. What do you mean by modifying the playlist? Could we see a code snippet? 

Thanks.

**Comment by Zachzx0** [comment]
> Hi there,
> 
> Could you please provide some more information:
> 
> 1. What exactly do you mean by crash?
> 2. When you say it only happens in iOS, does it not happen in the editor? Are you on a Mac?
> 3. Have you tried any other devices besides the iPhone 11?
> 4. Have you tried upgrading to the latest version of AVPro Video?
> 5. What do you mean by modifying the playlist? Could we see a code snippet?
> 
> Thanks.

1、The crashes I mean that is process is killed by os

2、 It dosent happened in the win-Editor & android ，but ios. i `ve not got a Mac

3、it happened also on ip 11 pro max .

4、i `ll try it tommorow，and will give you an answer

5、sorry ，i can not give a snippet to you.I can describe:

when i playback a list of videos.I try Clear the _Playlist.Items_ (_type:MediaItem_) first and then Create(_new_) some MediaItem-type object, fill the _playlist.Items_.
And then , I will Call _playlist.JumpToItem(0)_ for playing list from the first.
finally, Call the _play()_ function.

Before it crashed , i execused the snippet repeatly with three different video-lists in a very short time.

**Comment by MorrisRH** [comment]
I suspect the is the same as issue #853 
It's being worked on and we hope to have a solution soon

**Comment by MorrisRH** [comment]
A fix will be in the next release

**Comment by Zachzx0** [comment]
> A fix will be in the next release

Wooooww! 
thx for your help!

**Comment by AndrewRH** [comment]
@Zachzx0 AVPro Video 2.2.4 has just been released and should resolve the issue you reported.  Thanks,

**Comment by Zachzx0** [comment]
> @Zachzx0 AVPro Video 2.2.4 has just been released and should resolve the issue you reported. Thanks,

Got it . I will try replace this sdk today .
