### ISSUE TITLE
Adaptive resolution doesn't seem to work properly with multi-bitrate HLS playlist.m3u8

### ISSUE THREAD

**Issue by ondevChrisD** [RenderHeads/UnityPlugin-AVProVideo#1001]
**Describe the issue**
The adaptive resolution doesn't seem to work properly with multi-bitrate HLS playlist.m3u8
It works fine on the Unity Editor (set to build for iOS).
All options and special settings are been removed for the purpose of a clean test.

In Unity editor, the resolution starts with 480x480 and goes up to 3840x3840.
with an available bandwidth speed of 90 Mbps on the macbook. 

In iPhones, the resolution starts with 480x480 and goes up to 960x960.
with an available bandwidth speed of 85 Mbps on the iPhone device. 

**Your Setup (please complete the following information):**
 - Unity version: 2021.1.21f1
 - AVPro Video version: 2.2.3 ultra build 979, Ultra Paid version.
 - Operating system version: MacOs 12.0.1
 - Device model: iPhone 6s+, iPhone 7, iPhone X pro max and iPhone 13 pro max.
 - Video specs (resolution, frame-rate, codec, file size): 
 
#EXT-X-STREAM-INF:BANDWIDTH=985600,RESOLUTION=480x480,CODECS="avc1.64001f,mp4a.40.2"
vid-480p/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1900800,RESOLUTION=960x960,CODECS="avc1.640032,mp4a.40.2"
vid-960p/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3578300,RESOLUTION=1920x1920,CODECS="avc1.64003c,mp4a.40.2"
vid-1920p/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=13961200,RESOLUTION=3840x3840,CODECS="avc1.64003e,mp4a.40.2"
vid-3840p/index.m3u8

**To Reproduce**
1. Just Play the below HLS Url with AVPro on a real iPhone device.
HLS URL is sent to  unitysupport@renderheads.com 

**Screenshots**
https://www.dropbox.com/s/0jf81o8pi5toktr/IMG_9219.jpg

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
This is being handled via keeping currently

**Comment by AndrewRH** [comment]
@ondevChrisD AVPro Video 2.2.4 has just been released and should resolve the issue you reported.  Thanks,
