### ISSUE TITLE
When does a source error occur?

### ISSUE THREAD

**Issue by wjstk37** [RenderHeads/UnityPlugin-AVProVideo#1004]
If the m3u8 video is streamed for more than 1 hour, the video is stopped along with the error log below.

What are the cases where this problem occurs?

11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: Playback error
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:   com.google.android.exoplr2avp.ExoPlaybackException: Source error
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at com.google.android.exoplr2avp.n.handleMessage(ExoPlayerImplInternal.java:580)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:226)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:313)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplr2avp.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at com.google.android.exoplr2avp.source.hls.playlist.b$a.a(DefaultHlsPlaylistTracker.java:718)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at com.google.android.exoplr2avp.source.hls.playlist.b$a.a(DefaultHlsPlaylistTracker.java:560)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at com.google.android.exoplr2avp.source.hls.playlist.b$a.a(DefaultHlsPlaylistTracker.java:488)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at com.google.android.exoplr2avp.upstream.Loader$c.handleMessage(Loader.java:483)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:106)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal:       ... 3 more

**Comment by RenderHeadsSte** [comment]
Can you please provide all the information asked for in the issues template, including, if possible, a link to the video you are seeing this issue with.
