### ISSUE TITLE
How to get EventType.FinishedPlaying more than once?

### ISSUE THREAD

**Issue by ImmotionPeterL** [RenderHeads/UnityPlugin-AVProVideo#1005]
I'm listening for EventType.FinishedPlaying and then displaying to the user some UI. From this UI the user can select to re-watch the video, however, once the video finishes again EventType.FinishedPlaying isn't called.. and I'm expecting it to be.

When the video finishes, I do 
```
mediaPlayer.Control.Stop();
mediaPlayer.Control.Rewind();
```

So that the video is in the correct state to be played if the user chooses to watch the same video. Do I have to do something else to get it in the correct state for EventType.FinishedPlaying to be called every time the video finishes? Shouldn't this be called every time the end of the video is reached?

**Comment by kahnivore** [comment]
1. Which platform are you on? 
2. And which version of AVPro Video? 
3. Does it change anything if you call Pause() instead of Stop()?
4. Is your Media Player set to loop?

**Comment by ImmotionPeterL** [comment]
1- It only seems to be an issue in the editor (both Windows and Mac). Works ok on Android and iOS.
2- v2.2.3.
3- I'll check.
4- No, I don't want the player to auto loop, as the user may not want to rewatch - we display some UI when the video finishes allowing them to re-watch, choose a different video, or exit.

**Comment by kahnivore** [comment]
Perhaps you could send a slightly larger code snippet so we can try to reproduce it?
