### ISSUE TITLE
App crashing when using Exoplayer video API

### ISSUE THREAD

**Issue by TWVRdev2** [RenderHeads/UnityPlugin-AVProVideo#1006]
**Describe the issue**
I am trying to stream through an URL on Android. When changing the Video API to ExoPlayer, I receive the attached error message. I am only able to build when deleting the specified file: guava-27.1-android. However, when installed on the device, the app crashes immediately. (as seen on the video).

**Your Setup**
 - Unity version: Unity 2020.3.19f1
 - AVPro Video version: AVPro Video Ultra 2.2.3 
 - Operating system version: Windows 10 Home 21H1
 - Device model: Samsung Galaxy Tab S5e

**To Reproduce**
1. Import AV Pro Video
2. Set Video API to Exo Player
3. Build for Android

**Logs**
[Error message.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7504923/Error.message.txt)
**Videos**
https://user-images.githubusercontent.com/73333922/140930131-3e8808b1-316f-47fb-8183-3b4ee4110312.mp4

**Comment by kahnivore** [comment]
It sounds like you might have two guava files i.e. one from another plugin - can you check the version of the other? Perhaps a mismatch in versions is causing this? 

Can't seem to play the attached video you've sent. Can you provide a [full logcat](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs) that might point us to more clues about the crash? 

Have you tried on any other devices?

**Comment by kahnivore** [comment]
Closing due to lack of response
