### ISSUE TITLE
360 stereoscopic videos flickers when moving the head on Oculus Quest 2

### ISSUE THREAD

**Issue by AntonioStissi** [RenderHeads/UnityPlugin-AVProVideo#1007]
I am having problem with 360 stereoscopic videos when building my player for Oculus Quest 2. In particular what happens is that the image flicker between Left on both eyes, Right on both eyes and Stereo when i move my head. The app works perfectly on the Pico G2 (which is 3dof). I noticed that on Quest the player works as intended if i remove the positional tracking (but doing that messed up the rig and the controllers and it is not really an option for us). Is there any specific setting that i have to use in order to have proper stereo videos playing on 6dof headsets?

Thanks,
Antonio

This is my setup:

Unity version: 2020.3.13
AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.3 (core)
Operating system versions:  Android for OculusQuest
Device model: Pico VR / Oculus / smartphones
Video specs (resolution, frame-rate, codec, file size): 4k 360 video ( 3840 x 1920 ) H.264

**Comment by RenderHeadsSte** [comment]
Do you have the AVPRo Video 'UpdateMultiPassStereo' component in your scene and hooked up to your camera?

**Comment by AntonioStissi** [comment]
Hi, thanks for the reply. Indeed using UpdateMultiPassStereo and targeting the center eye camera works. I also found that using multi-view render from the Oculus plugin settings fixes it and it's probably even better for performance

**Comment by tap2k** [comment]
Im having this bug too, specifically on a Quest Pro, and Multiview isnt fixing it. Any ideas?
