### ISSUE TITLE
Loading audio track from separate file

### ISSUE THREAD

**Issue by skibitsky** [RenderHeads/UnityPlugin-AVProVideo#1008]
Hello,

Is it possible to load audio track from a separate file? We have a few long videos in our app. To save disk space we are thinking about moving localized audio tracks outisde of video containers to distribute them via addressable system.

I've read documentation and tried trial version, but it seems like the only way to achieve that is to use Unity's Timeline to play audio as a separate track. I wonder if there is a better solution?

**Comment by kahnivore** [comment]
Hi, 

Could you provide some more context? Not sure if you mean you want to have a single video file and separate the audio from it from within the plugin, or if you'd like to just find a way to keep a video track and audio track in sync?

**Comment by skibitsky** [comment]
Yes, I want to have a single video file (without sound) and multiple audio files. One video and one audio would be played at a time. The reason for having multiple audio files is to deliver specific localized audio track depending on the locale chosen by player. 
Is there a way to achieve this with AVPro Video plugin?

**Comment by kahnivore** [comment]
Right, I see. 

You could use two separate Media Players - one for the audio and one for the video, and play them at the same time. 

There wouldn't be anything keeping them in sync, so it likely wouldn't be as good as if you had them wrapped in a single container. Although, keeping two media player's in sync is a feature we'd like to add. 

Could you try this and see if it works for you? 

We have a [free trial](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases) you can test with.

**Comment by AndrewRH** [comment]
Or you could embed the audio tracks into the video and switch between them?

**Comment by skibitsky** [comment]
@AndrewRH we would like to keep the size of video files small. Adding audio tracks for each locale would increase a size of cache on player's devices. 

I like the 2-players idea suggested by @kahnivore. Will give it a try. 

Thank you 🙏
