### ISSUE TITLE
Is it possible to keep AVProVideo videos private?

### ISSUE THREAD

**Issue by LukeFarrer** [RenderHeads/UnityPlugin-AVProVideo#1009]
Currently we are storing video files in the StreamingAssets folder for playback with AVProVideo using Unity.
This makes them publicly visible on Android and Windows and we would rather have them private if possible.
We could put them on the web but again they are totally public and can be viewed and played back independently of the App.
Do you have any suggestions on keeping the videos private, or, at least, not immediately visible?

Thanks

Luke

**Comment by kahnivore** [comment]
There are a few options. Please see our documentation on content protection [here ](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-core.html#file-offset) and [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html). 

Does this help?

**Comment by LukeFarrer** [comment]
Just what I was looking for. Thanks for the very fast response, much appreciated. Luke
