### ISSUE TITLE
ExoPlayer 2.16.0

### ISSUE THREAD

**Issue by SecretTonto** [RenderHeads/UnityPlugin-AVProVideo#1010]
**Describe the issue**
If you do Live Streaming for a long time, you will stop. (Play it for more than 30 minutes.)

After checking, it seems that the phenomenon has been modified in ExoPlayer 2.15.1.
(Fix bug where the player would get stuck if all download attempts fail and would not raise an error to the application (#9390).)

So AVPro needs the version of ExoPlayer 2.15.1.

Do you have any plans to update the version of ExoPlayer to 2.15.1?

If you don't have an update plan yet, please guide us if there is a way to update the version of ExoPlayer on your own.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.15f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.3
 - Operating system version: Android OS 10, 11
 - Device model: Galaxy Z Fold3 5G_SM-F926N (11.0.0)_5G / Galaxy S21 5G_SM-G991N (12.0.0)_5G
 - Video specs (resolution, frame-rate, codec, file size): 1080P, 7.5mbps

**Logs**
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: Playback error
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: com.google.android.exoplr2avp.ExoPlaybackException: Source error
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.n.handleMessage(ExoPlayerImplInternal.java:580)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at android.os.Handler.dispatchMessage(Handler.java:102)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at android.os.Looper.loopOnce(Looper.java:226)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at android.os.Looper.loop(Looper.java:313)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at android.os.HandlerThread.run(HandlerThread.java:67)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: Caused by: com.google.android.exoplr2avp.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.source.hls.playlist.b$a.a(DefaultHlsPlaylistTracker.java:718)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.source.hls.playlist.b$a.a(DefaultHlsPlaylistTracker.java:560)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.source.hls.playlist.b$a.a(DefaultHlsPlaylistTracker.java:488)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.upstream.Loader$c.handleMessage(Loader.java:483)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: at android.os.Handler.dispatchMessage(Handler.java:106)
11-04 12:34:57.007 25143 26095 E ExoPlayerImplInternal: ... 3 more
11-04 12:34:57.007 966 966 E SurfaceFlinger: Attempt to set frame rate on an unrecognized IGraphicBufferProducer

**Videos**
https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Comment by kahnivore** [comment]
We're working on updating to 2.16.0 currently. 

Can't give an exact time estimate but will let you know when we know.

**Comment by SecretTonto** [comment]
Is there any way to update ExoPlayer on its own before AVPro is updated?

**Comment by RenderHeadsSte** [comment]
Extremely unlikely and definitely not this time. I have updated AVPro Video to ExoPlayer 2.16.0 in our internal codebase and so, all being well, it will be updated in the next release.

**Comment by SecretTonto** [comment]
Yes, I'll be waiting.

**Comment by SecretTonto** [comment]
Can I know if there's an update plan?

We are currently serving the app with AVPro 2.2.3 version. There is an issue where streaming stops, so I want to find a solution.

**Comment by AndrewRH** [comment]
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,

**Comment by SecretTonto** [comment]
@AndrewRH 
I tested it by applying AVPro 2.3.0.
However, there is still a playback error, and the issue of stopping the video is being reproduced.
Is there a way to solve it?
