### ISSUE TITLE
Switching video resolutions - Error: Loading failed

### ISSUE THREAD

**Issue by aracid** [RenderHeads/UnityPlugin-AVProVideo#1012]
Switching videos with different codecs / resolutions causes 

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Your Setup (please complete the following information):**
 - Unity version: 2020.4.22f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: Windows 10
 - Device model:  Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 

Load a video and then using this line of c# - to swap out to a different video which has different codec/resolution.

videoMPlayerOnProjector.OpenMedia(PathToMovie, MediaPathType.AbsolutePathOrURL), autoPlay: autoPlay);

The video isn't the same format as it goes from 
3840x3804 
to 
4096x4096

To work around this I try destroy the player and recreate the player, 
videoMPlayerOnProjector = videoProjectionSphere.AddComponent<MediaPlayer>();
The player Control seems to return Null and methods like this no longer seem to work.
videoMPlayerOnProjector.Control.Stop();

**Videos**

These are the two video's I use

https://iwte-terrarium-dev-media.s3.amazonaws.com/experiences/d2AemwxbB0XulkGCRHUA_9fd5fffddcb315f2131abf7e65b1761c.mp4

https://iwte-terrarium-dev-media.s3.amazonaws.com/experiences/d2AemwxbB0XulkGCRHUA_9e5d1fc59235a5193611447b519b294d.mp4

Is there a better way to achieve this as I'm not always sure that my videos will always have the same resolution?

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

Thanks in advance

**Comment by kahnivore** [comment]
Which version of AVPro Video are you using? 

Does this error happen in both the editor and on the Quest 2? 

Does the second video play without error if you play it first?

**Comment by aracid** [comment]
Hi there

AVpro 2.2.3 Ultra

Both editor and quest seem to fail to load.

Yup , both video's work fine on their own.
Thanks again

**Comment by RenderHeadsSte** [comment]
Did you resolve this issue @aracid ?

**Comment by aracid** [comment]
Hi RenderheadsSte

I think so, 
I started with a demo scene and found that just switching between video's using C# works so its likely that there's something odd going on in my scene, so I figured I'd close the ticket.

Thanks again
