### ISSUE TITLE
Audio when played on Android with Output Mode "Unity" ends early

### ISSUE THREAD

**Issue by ChrisBool** [RenderHeads/UnityPlugin-AVProVideo#1013]
**Describe the issue**
When playing Audio (not tested yet with Video) on Android with the Audio Output Mode set to "Unity", the Audio stops playing prematurely.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.7f1
 - AVPro Video version : Initially occured with 2.1.3 ultra, reproduced (see project in mail) with AVPro Video v2.2.3 (native plugin v2.2.2f1-trial)
 - Operating system version: Android 10 on both tested devices
 - Device model: Oculus Quest 1 & reproduced on Fairphone 3
 - Audio Specs: MP3, MPEG Audio Layer 1/2 (mpga), Stereo 48000 Hz, 32 Bits per Sample, 192 kb/s

**To Reproduce**
1. Open Unity project sent to you via Mail
2. Open the "SampleScene"
3. Build to Android
4. Press the Buttons and hear how the Play via Unity stops early for the Media Player with OutputMode Unity
5. The Panels on the left and right show the "player.Control.IsFinished" for both Media Players as noted, respectively. These seem to be active for the same exact amount of time

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Will be mailed to the supplied address.

**Comment by kahnivore** [comment]
Thanks for sending a project. We'll get back to you once we've had a look.

**Comment by AndrewRH** [comment]
Sounds like an issue we had on Windows too...basically where the media player would stop but there would still be pending audio in the buffer to process.  I think either were flushing the data instead of draining the buffer....might be something similar, but no idea whether Exoplayer can send a signal that means you can continue to drain the existing audio data...

**Comment by RenderHeadsSte** [comment]
I think it is a combination of two problems leading to this issue.

1) As @AndrewRH says - I think at an Android plugin level we can flag when this happens (there is a callback function named 'onQueueEndOfStream' in the audio processor)

2) In the above mentioned function we have been calling a flush.  I spotted this just last week and removed it.  Hopefully it will be in the next release, but certainly the one after.  Whether this will be enough on it's own without (1) I do not know

**Comment by ChrisBool** [comment]
Thanks for the quick response.

Is there an estimate regarding the release date?

**Comment by RenderHeadsSte** [comment]
(2) is already addressed in our current codebase and hopefully will make the next build.  (1) will require an internal discussion around how to expose it.  I am hopeful that (2) will mean your problem is largely/completely addressed.
