### ISSUE TITLE
button UI does not click when running in VR (e.g. steamVR)

### ISSUE THREAD

**Issue by kimhyunjin2628** [RenderHeads/UnityPlugin-AVProVideo#1015]
button UI does not click when running in VR (e.g. steamVR)
![질문1](https://user-images.githubusercontent.com/54582019/142011402-3b5a22a4-89f4-414e-ae57-65845dc48b10.PNG)

Is there anything I need to set up when using it in VR?

**Comment by kahnivore** [comment]
You'd need to set up some kind of input system. If you have a look at the MediaPlayerUI script you'll see it's set up for mouse events - you can adjust accordingly.
