### ISSUE TITLE
Device volume is zero, but playing sound.

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1016]
**Preconditions.**
- AVPro set to playing in the background.
- Set the device volume to **zero**.

**Below is the procedure to reproduce the issue situation.**
1. Playing video in my app.
2. Go to background(home).
3. Open the camera application.
4. Take a picture.

 - Unity version: 2019.4.15f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.15
 - Operating system version: 14.2, 15.1
 - Device model: iPhone 11, iPhone Xs

Video link:
https://drive.google.com/file/d/1RK1DukG8G_LJqknmCvN1SoAtIH6lt_pG/view?usp=sharing

**Comment by AndrewRH** [comment]
I recommend upgrading to the latest version of the plugin - I believe that issue has been fixed.

Let us know if that helps you?

Thanks,

**Comment by MorrisRH** [comment]
Cannot reproduce this with an iPhone X, iOS 14.8 using the latest version of AVPro Video.

I'm not even sure what could cause it, the plugin does not interact with the system volume or modify the applications audio session.

What do you mean by "AVPro set to playing in the background"?

**Comment by dw8869** [comment]
@MorrisRH 

```
Pause Media On App Pause = false
Play Media On App Unpause = false
```

**Comment by dw8869** [comment]
@AndrewRH @MorrisRH 
I updated it to AVPro 2.2.4. but this issue reproduce.
