### ISSUE TITLE
UWP - Unable to load video via direct path 

### ISSUE THREAD

**Issue by StormbirdsStudio** [RenderHeads/UnityPlugin-AVProVideo#1018]
**Describe the issue**
Using your sample Demo_MediaPlayer we are unable to load a video from a direct path on UWP. We have tried both WinRT and Media foundation with no luck. This method of loading videos works on other platforms just not UWP. 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.22f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.3 Core
 - Operating system version: Windows 10 - 19043.1348
 - Device model: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz, 16.0 GB 
 - Video specs (resolution, frame-rate, codec, file size): 1280x720, 30FPS, MP4, 574kb

**To Reproduce**
1. Import AVPro Core into a fresh Unity 3D Project
2. Open the Demo_MediaPlayer Sceen
3. On the Media Player gameobject. In Setting->Source change the Media Source to Path and specify a path e.g C:/Users/myusername/Videos/Outro.mp4 
4. Save the scene
5. Go to Project Settings-Player->Publishing Settings->Capabilities and tick them all. Set supported device families to Desktop. 
6. Open Build Settings and add the Demo_MediaPlayer scene to the scene list
7. Switch to Universal Windows Platform
8. Set Target Device to PC, Architecture to x64, Build Type to D3D Project, Build Configuration to Debug
9. Build the Visual Studio project
10. Open project in Visual Studio and run under x64 arcitecture
11. Notice video does not load

**Logs**
The thread 0x3b90 has exited with code 0 (0x0).
'UWPTest.exe' (Win32): Unloaded 'C:\Windows\System32\CoreMessaging.dll'
onecoreuap\base\appmodel\statemanager\winrt\lib\windows.storage.applicationdatafactory.server.cpp(235)\Windows.Storage.ApplicationData.dll!00007FFF7C998433: (caller: 00007FFF7C9A8B63) ReturnHr(1) tid(4f48) 8000000B The operation attempted to access data outside the valid range
    Msg:[User S-1-5-21-4124953411-3187828836-3769691013-1001] 
Logging to C:/Users/npalf/AppData/Local/Packages/Template3D_pzq3xp76mxafg/TempState/UnityPlayer.log
[0.068941 / 0.078887] - Initializing Unity runtime
Loading native plugins
  Loading AVProVideo.dll
  Loading Audio360.dll
  Loading AVProVideoWinRT.dll
Module information:
 Built with Compiler Ver '192528614'
 Built from '2020.3/staging' branch
 Version is '2020.3.22f1 (e1a7f79fd887)'
 Debug build
 Application type 'D3D'
[0.000913 / 0.147347] - AppCallbacks::SetCoreWindowEvents
[0.006417 / 0.154080] - AppCallbacks::InitializeD3DWindow
[0.160547 / 0.160547] - OnActivated event.
[0.006940 / 0.167487] - OnVisibilityChanged event - Visible.
[0.027928 / 0.195416] - OnWindowActivated event - CodeActivated.
 OS 'Windows 10 (10.0.19041) 64bit'
PlayerConnection initialized from D:/Dev/Unity/Projects/UWPTest/Builds/UWP/build/bin/x64/Debug/AppX/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55076
Multi-casting "[IP] 192.168.68.116 [Port] 55076 [Flags] 2 [Guid] 2497592773 [EditorId] 4083731829 [Version] 1048832 [Id] UWPPlayerX64(LAPTOP-PALF-DEV) [Debug] 0 [PackageName] Template3D_pzq3xp76mxafg [ProjectName] UWPTest" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55076]
PlayerConnection already initialized - listening to [0.0.0.0:55076]
'UWPTest.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
onecore\windows\directx\database\helperlibrary\lib\directxdatabasehelper.cpp(383)\dxgi.dll!00007FFFA5BCA6B7: (caller: 00007FFFA5BC88D6) ReturnHr(1) tid(4f48) 80070005 Access is denied.
'UWPTest.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvdm.inf_amd64_b1996f0d09e49357\nvdlistx.dll'
[1.287305 / 1.384297] - Initialize
[Subsystems] Discovering subsystems at path D:/Dev/Unity/Projects/UWPTest/Builds/UWP/build/bin/x64/Debug/AppX/Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
'UWPTest.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvdm.inf_amd64_b1996f0d09e49357\nvdlistx.dll'
'UWPTest.exe' (Win32): Unloaded 'C:\Windows\System32\shell32.dll'
'UWPTest.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA Corporation\Ansel\NvCameraWhitelisting64.dll'
The thread 0x4164 has exited with code 0 (0x0).
Successfully created d3d11 device with debug flag.
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1050 Ti (ID=0x1c8c)
    Vendor:   
    VRAM:     4018 MB
'UWPTest.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA Corporation\Ansel\NvCameraWhitelisting64.dll'
Initialize engine version: 2020.3.22f1 (e1a7f79fd887)
[AudioManager] InitNormal(tryDeviceDefaults = false, preferredOutputType = FMOD_OUTPUTTYPE_AUTODETECT) attempt with hardAudioDisable: false
[AudioManager] Setting output to FMOD_OUTPUTTYPE_AUTODETECT
[AudioManager] InitNormal succeeded with output "FMOD_OUTPUTTYPE_WASAPI". Driver name is "SMS27B750V (2- NVIDIA High Definition Audio)". Speaker mode is "FMOD_SPEAKERMODE_STEREO"
The thread 0x316c has exited with code 0 (0x0).
The thread 0x708c has exited with code 0 (0x0).
'UWPTest.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA Corporation\Ansel\NvCameraWhitelisting64.dll'
[0.000452 / 2.295181] - AppCallbacks::SetupInputEvents
onecoreuap\drivers\mobilepc\sensors\convergence\common\pnpmanager\pnpmanager.cpp(637)\Windows.Devices.Sensors.dll!00007FFF2E62881D: (caller: 00007FFF2E62896F) Exception(1) tid(4ca0) 80070490 Element not found.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: wil::ResultException at memory location 0x00000017BE9FCDA0.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
The thread 0x7080 has exited with code 0 (0x0).
onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\internal\simpleorientation.cpp(127)\Windows.Devices.Sensors.dll!00007FFF2E61F4A0: (caller: 00007FFF2E583FCD) Exception(2) tid(4ca0) 80070490 Element not found.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: wil::ResultException at memory location 0x00000017BE9FCFF0.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\internal\sensorserver.cpp(74)\Windows.Devices.Sensors.dll!00007FFF2E582E23: (caller: 00007FFF2E5FEF42) ReturnHr(1) tid(4ca0) 80070490 Element not found.
onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\lib\simpleorientationsensor.cpp(111)\Windows.Devices.Sensors.dll!00007FFF2E5FF015: (caller: 00007FFF2E5FC6BD) ReturnHr(2) tid(4ca0) 80070490 Element not found.
[0.029202 / 2.324542] - AppCallbacks::SetupOrientationSensorEvents
[0.090384 / 2.358859] - AppCallbacks::Load
[2.163779 / 2.359194] - Starting first scene loading
The following GlobalManagers were stripped from the build (Either because they're not used or not supported on this platform):
  ClusterInputManager
  UnityConnectSettings
Begin showing splash screen.
[2.015127 / 4.374322] - Finishing first scene loading
UnloadTime: 4.551600 ms
[0.100322 / 4.474643] - First level loaded
End showing splash screen.
[0.531338 / 5.005981] - PerformUpdateAndRender started
onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\internal\viewpositiontrackerinternal.cpp(269)\Windows.Devices.Sensors.dll!00007FFF2E622DC9: (caller: 00007FFF2E623347) Exception(3) tid(4f48) 80070490 Element not found.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: wil::ResultException at memory location 0x00000017BEBFC810.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFFA7944F69 (KernelBase.dll) in UWPTest.exe: WinRT originate error - 0x8001010E : 'The application called an interface that was marshalled for a different thread.'.
onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\internal\viewpositiontrackerinternal.cpp(143)\Windows.Devices.Sensors.dll!00007FFF2E6243D0: (caller: 00007FFF2E623C8B) Exception(4) tid(4f48) 8001010E The application called an interface that was marshalled for a different thread.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: wil::ResultException at memory location 0x00000017BEBFC810.
The thread 0x372c has exited with code 0 (0x0).
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\internal\sensor.cpp(184)\Windows.Devices.Sensors.dll!00007FFF2E5837FD: (caller: 00007FFF2E583FCD) Exception(5) tid(4f48) 80070490 Element not found.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: wil::ResultException at memory location 0x00000017BEBFCBD0.
Exception thrown at 0x00007FFFA7944F69 in UWPTest.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
onecoreuap\drivers\mobilepc\sensors\convergence\api\winrt\public\internal\sensorserver.cpp(74)\Windows.Devices.Sensors.dll!00007FFF2E582E23: (caller: 00007FFF2E5CDA61) ReturnHr(3) tid(4f48) 80070490 Element not found.
[AVProVideo] Initialising AVPro Video v2.2.3 (native plugin v2.2.2f1-core) on NVIDIA GeForce GTX 1050 Ti/Direct3D 11.0 [level 11.1] (MT False) on MetroPlayerX64
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
RenderHeads.Media.AVProVideo.MediaPlayer:Start()

[AVProVideo] Opening C:/Users/myusername/Videos/Outro.mp4 (offset 0) with API WinRT
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(Boolean)
RenderHeads.Media.AVProVideo.MediaPlayer:Start()

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
And if you load the video from StreamingAssets on UWP does that work?

It could be a file permissions thing - UWP is a lot more locked down than normal Windows desktop apps...

**Comment by StormbirdsStudio** [comment]
Thanks for the response.

If I add the video to the streaming assets folder and then use Path relative to Streaming Assets the video does play. 

However that is not a solution for the project we are working on. Our application depends on users being able to import videos from their machine.

**Comment by StormbirdsStudio** [comment]
Hello,
Just wondering if there was any news on this issue? 

This is the last major issue we have to solve before we launch our title on UWP. 

Thanks

**Comment by AndrewRH** [comment]
Hmm, does this help:
https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions

Thanks,
