### ISSUE TITLE
I don't know why a warning message appears when attaching a video to a URL

### ISSUE THREAD

**Issue by kimhyunjin2628** [RenderHeads/UnityPlugin-AVProVideo#1019]
**Question**

I don't know why a warning message appears when attaching a video to a URL

![경고](https://user-images.githubusercontent.com/54582019/142645485-6a844202-1b1b-4fcb-b1b0-5e966067796a.PNG)

**Comment by AndrewRH** [comment]
Because you have your build platform set to Android and you have a URL that starts with 'http' instead of 'https'

Does that make sense?

Thanks,
