### ISSUE TITLE
Mac will crash in Editor.

### ISSUE THREAD

**Issue by Imagine-Leo** [RenderHeads/UnityPlugin-AVProVideo#102]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.5
 - AVPro Video version: 1.9.12
 - Operating system version: 10.14.5
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): normal 1920*1080

**To Reproduce**
1. when i play a scene that play a video in editor it will crash immediately.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Hi
I'm sorry to hear you're having trouble.
A fix for the crash with Unity 2019 was released a couple of versions back (1.9.12). Please upgrade to the latest version.
Thanks!

**Comment by shahbazIOSDEV** [comment]
Still Crash On Unity2019.2.17f1

**Comment by MorrisRH** [comment]
Hi @shahbazIOSDEV
The latest version of AVPro Video (1.10.1) is working fine with the Unity editor (version 2019.2.17f1) on mac. If you could open a new issue and provide as much information as possible we will be happy to investigate.
