### ISSUE TITLE
Setting autoProgress to True on Mac means GetTexture() is never valid

### ISSUE THREAD

**Issue by VOX-Neil** [RenderHeads/UnityPlugin-AVProVideo#1020]
**Describe the issue**
If you use the PlaylistMediaPlayer to load a video but not play it, TextureProducer.GetTexture() is never valid if autoProgress is set to True.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.22f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.4 Core
 - Operating system version: Windows 11

**To Reproduce**
I have sent an example project

This works fine on PC whether AutoProgress is set or not.  On Mac, it only works if AutoProgress is set to False.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
A fix for this will be available in the next release.

**Comment by AndrewRH** [comment]
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,
