### ISSUE TITLE
Can't play live streaming rtsp format url

### ISSUE THREAD

**Issue by kimhyunjin2628** [RenderHeads/UnityPlugin-AVProVideo#1021]
**Question**
Can't play live streaming rtsp format url
I am trying to build on android

How can I play it correctly?

![질문1](https://user-images.githubusercontent.com/54582019/142719215-a6956666-3402-4a42-bddd-9c48dc8c9f82.PNG)

![질문2](https://user-images.githubusercontent.com/54582019/142719220-cfa49eb2-6802-4e39-9c13-945d72c15ff5.PNG)

**Comment by kahnivore** [comment]
Hi there, 

Could you provide more details please? What Unity version and AVPro Video versions are you using? 

The screenshot of the error you've posted seems to be in the editor, have you tested the build on your Android device? 

Are you using headers? 

Have you tested your stream elsewhere? Does it play in something like VLC for example?

**Comment by kimhyunjin2628** [comment]
> 안녕하세요,
> 
> 더 자세한 정보를 제공해 주시겠습니까? 어떤 Unity 버전과 AVPro 비디오 버전을 사용하고 있습니까?
> 
> 게시한 오류의 스크린샷이 편집기에 있는 것 같습니다. Android 장치에서 빌드를 테스트했습니까?
> 
> 헤더를 사용하고 있습니까?
> 
> 다른 곳에서 스트림을 테스트했습니까? 예를 들어 VLC와 같은 것에서 재생됩니까?


Unity 2019.2.14f,  avPro Video -Ultra Edition Version 2.2.4 -18 November2021 Android Fixed * Fixed
It doesn't even play in the Unity editor.
It doesn't even run on VLC devices, the build platform is Android
Download VRPro, no scripts, no headers

**Comment by AndrewRH** [comment]
RTSP has very limited supported on Windows.  You can find the list of supported protocol here:
https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html#streaming-formats

On Windows if you want to use RTSP then I recommend installing LAV Filters and using the DirectShow API.

Thanks,
