### ISSUE TITLE
I am trying to update from trial version to Android core edition however the watermark still appears. I have tried everything possible, deleted all the files and re-imported but yet the watermark is still there. I am not willing to re-do all the work that I have done and the deadline for this is in a few hours.. I am using Unity 2019.4.18f

### ISSUE THREAD

**Issue by dibaje** [RenderHeads/UnityPlugin-AVProVideo#1022]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi there,

Have you followed these [upgrade steps](https://www.renderheads.com/content/docs/AVProVideo/articles/install.html#upgrade-steps)? 

Are you using source control? If so it might be worthwhile closing those processes before upgrading.

**Comment by AndrewRH** [comment]
Yes what @kahnivore  said, also [see here](https://www.renderheads.com/content/docs/AVProVideo/articles/install.html#installation--watermark-troubleshooting)

**Comment by kahnivore** [comment]
Closing due to lack of response
