### ISSUE TITLE
Can you add support for x86 64 bit CPUs on Android?

### ISSUE THREAD

**Issue by paulIVRE** [RenderHeads/UnityPlugin-AVProVideo#1025]
**Is your feature request related to a problem? Please describe.**
We want to use AVPro on Chromebook. We are running our app in Android mode on Chromebook. Most Chrome books use x86 64 bit processors. Your plugin doesn't support this architecture.

**Describe the solution you'd like**
Add x86 64 bit plugin support for Android

**Describe alternatives you've considered**
None so far

**Additional context**

**Comment by kahnivore** [comment]
Unity doesn't support x86_64bit for Android, so it's not possible for us to add support for it.

**Comment by paulIVRE** [comment]
Unity support x86_64 bit Android but only for Chromebook. You can read about it here: https://blog.unity.com/technology/build-and-port-for-chrome-os . It would be great if you could support this as the user base of Chromebooks is increasing rapidly at the moment. Originally support was only in Unity 2021.2 but they have recently back-ported support to 2019.4.31

**Comment by AndrewRH** [comment]
@paulIVRE 
I see, that's interesting!
Well perhaps we can add support for it then.  We're not sure whether our complex Android plugin will work on Chrome-OS though, and don't currently have a device to test on...

The plugin does have x86 32-bit support, so please you try to make a build of this type only and see whether that works on your Chrome-OS device.  If it doesn't work then we'll have to look at why before embarking on adding x86 64-bit support.  If it does work then that's a good sign and something we can start to look into.

When you test it, please do test making a build with the MediaPlayer > Platform Specific > Android > Video API option set to "ExoPlayer" (default) and then another build with it set to "MediaPlayer" so we can know whether or not both of these paths work.

Thanks,

**Comment by paulIVRE** [comment]
Thanks for getting back to me so quickly. There are 64 bit ARM based Chromebooks and we have been using AVPro with no problem on these, so hopefully this means there won't be too much problem on X86s. Unfortunately I only have a 64 bit x86 Chromebook so can't test the 32 bit version.

**Comment by AndrewRH** [comment]
Thanks hmmm, isn't 64-bit x86 backwardly compatible with 32-bit?

**Comment by paulIVRE** [comment]
You're right about the 32 bit compatibility. Unfortunately though when I tried out one of your demos, it didn't work. I tried both the "MediaPlayer" & "ExoPlayer" paths. The Arm 64 bit version worked okay with both paths.

**Comment by AndrewRH** [comment]
Hmmm, I guess that indicates that your device is using an ARM processor and not x86.  If you're able to get hold of an x86 Chrome-OS machine and test the x86 32-bit build with our plugin that would be great.

**Comment by paulIVRE** [comment]
Ok I've found out that it actually does work on X86 chrome books. The trouble I had was that I was using 2019.4.32 and you have a build script that disables X86 support for unity versions past 2019.3. I tried both paths and it was ok.

**Comment by AndrewRH** [comment]
That's great... well I think then we should be able to add x86 64-bit support

**Comment by paulIVRE** [comment]
Cool, that's excellent news, thanks!

**Comment by AndrewRH** [comment]
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,
