### ISSUE TITLE
HasAudio() incorrectly reported on videos 30s and up on iOS

### ISSUE THREAD

**Issue by janakitti** [RenderHeads/UnityPlugin-AVProVideo#1026]
**Describe the issue**
On iOS, videos that are 30s or longer will be reported to have no audio track even though there exists and audio track on the file. This behaviour is not present when the video is played on Android or any other platform.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.19
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Core 2.2.1
 - Operating system version: iOS 15.1
 - Device model: 2020 iPhone SE
 - Video specs (resolution, frame-rate, codec, file size): This is an example of one of the videos that this bug was experienced with. The bug is not specific to just these video specs.
   - File type: mp4
   - Resolution: 654x480
   - Size: 7.4 MB
   - Video format: H.264
   - Audio format: AAC, 48000 Hz
   - Audio channels: Stereo (L R)
   - Encoded FPS: 29,97
   - Color primaries: SMPTE-C

**To Reproduce**
1. Load a video with an audio track 30s or longer on iOS app and observe that `MediaPlayer.Info.HasAudio()` is false

**Comment by MorrisRH** [comment]
Unable to reproduce this using a 30 minute long mp4 both locally and streamed on an iPad Pro running iOS 14.8.1, with Unity 2020.3.23f1 and AVProVideo 2.2.4 Trial.

If you can, provide us with a video where this is happening for you. Please send it to unitysupport@renderheads.com citing this issue in the subject.

**Comment by janakitti** [comment]
Hi, it turns out this particular behaviour with videos over 30s long is caused by a setup in our application. Sorry about that.
