### ISSUE TITLE
Over under 360 video dropping frames after a couple seconds of playback on Quest 2.

### ISSUE THREAD

**Issue by amcveyreality** [RenderHeads/UnityPlugin-AVProVideo#1027]
**Describe the issue**
Using the AVPro plugin for Unity I've been testing video playback of our over under 360 4k footage in a Quest 2. I am loading the Media Reference via an absolute path to the persistent data path on the Quest 2. The video begins playing well however after about 10 seconds of playback it begins to drop frames. This indicates to me that its most likely a ram issue of some sort but there is also the watermark popping around and I'm wondering if that might have any influence on things in some capacity. On top of this I see in your documentation it recommends to utilize the OES shaders for android devices, however those don't seem to work on the Quest 2 (it only shows black but the audio does play). Is getting these shaders working the key to improving playback? Would the removal of the watermark upon purchase help at all? Thanks!

**Your Setup (please complete the following information):**
 - Unity version: Unity 2020.3.12f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro version 2.2.3(trial)
 - Operating system version: Windows 10 Pro OS build 19043.1348 
 - Device model: Quest 2 
 - Video specs (resolution, frame-rate, codec, file size): 3840x3840, 30fps, H.264, 1.27 gigs

**To Reproduce**
1. Add XR Interaction toolkit to Android Device targeted Unity (ensure XR plugin management is enable and oculus plugin provider is checked).
2. Import AVPro Trial Package
3. Create new scene in Unity and add XR Rig as well as MediaPlayer, Sphere-ApplyToMesh, and UpdateMultiPassStereo (these last three are pulled from the 360 example scene provided with the trial) to scene hierarchy.
4. Create Media references in Unity and ensure that said media is also present on the Quest 2's local storage.
5. Point media player at Media reference.
6. Build to quest and witness playback issues.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi there, 

OES doesn't work in the trial edition as we have no way to watermark it. It would certainly help performance. 

The removal of the watermark would make a slight difference but probably not very noticeably.

Have you tried building our Demo_360 scene with the sample video included? Wondering how much difference that makes to your playback. 

Would you be able to share the media you are using? We could try test it this side using OES. 

You can send to unitysupport@renderheads.com if it's sensitive (please include "#1027" in the subject line)

**Comment by amcveyreality** [comment]
Oh I didn't realize that OES wasn't included in the trial! That would have
saved me some fiddling. I was able to use the example 360 scene just fine,
no issues there. We are attempting to push it a bit with our footage in
that it is 4k over under and the bitrate is quite high at 115mbps. I have
permission to send you a couple minutes of our footage. I'll fire that off
to the email you provided. Thanks!

**Comment by amcveyreality** [comment]
Have y'all had a chance to mess with the footage I sent along?

**Comment by RenderHeadsSte** [comment]
Looking at this now @amcveyreality

**Comment by RenderHeadsSte** [comment]
I get a solid 72fps with the test video you sent on Quest2 using our Demo 360 scene in Unity 2020.3.12 with the latest trial version. There is the occasional frame spike (into the 50fps region) that looks like garbage collection.  As your video is only 29.97fps this should not cause any visible issues.

**Comment by amcveyreality** [comment]
Thank you very much! We will continue with our purchase!
