### ISSUE TITLE
MediaPlayer spams console with error logs in every update if internet connection is not enabled

### ISSUE THREAD

**Issue by christianYS** [RenderHeads/UnityPlugin-AVProVideo#1031]
**Describe the issue**
When starting a video without internet connection, the MediaPlayer component spams the console with error logs for every update.
```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
```
The message is coming from **MediaPlayer.UpdateErrors()** method.
It's desirable that error logs are logged only once, if the state does not change with the update. 

<img width="1045" alt="Screenshot 2021-11-26 at 11 32 37" src="https://user-images.githubusercontent.com/25147502/143558990-91e7a195-a171-4fd7-bba5-b69b05135e5b.png">

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.19f
 - AVPro Video version: 2.2.4 Enterprise
 - Operating system version: MacOS 11.6

**To Reproduce**
1. Disable internet connection
2. Start a scene with a video

**Comment by christianYS** [comment]
I should add that the issue reproduces when the video is fetched from a URL

**Comment by MorrisRH** [comment]
This issue isn't limited to macOS but has been fixed for macOS, iOS and tvOS.

**Comment by AndrewRH** [comment]
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,
