### ISSUE TITLE
Seek/SeekFast seems dependent on Max Playback Speed on iOS

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProVideo#1032]
**Describe the issue**
Both Seek and SeekFast's time seems to be multiplied by the playback speed, whereas previously it was not.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.21f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.4 core
 - Operating system version: iOS 15
 - Device model: iPhone 12
 - Video specs (resolution, frame-rate, codec, file size): 30fps, 1080p, h264, 600mb 

**To Reproduce**
1. Set Platform Specific > iOS > Max Playback Rate = 4
2. Run MediaPlayer.Control.SeekFast(10)
3. Notice: time is set to 40 seconds instead of 10

**Workaround**
Use `m_MediaPlayer.SeekFast(seconds / m_MediaPlayer.PlatformOptionsIOS.maximumPlaybackRate)`

**Comment by MorrisRH** [comment]
Well internally they are dependant on max playback rate but it's not something you should be aware of.
Will get this fixed for the next release.

**Comment by AndrewRH** [comment]
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,

**Comment by artoonie** [comment]
Thank you, I've confirmed it works.

I'll also note (to add some keywords for future people searching the Issues) that another side-effect was that `SeekToFrameRelative` wasn't working as expected. This has also been fixed in the latest release.
