### ISSUE TITLE
[iOS] Struggling to fix "Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources"

### ISSUE THREAD

**Issue by ImmotionPeterL** [RenderHeads/UnityPlugin-AVProVideo#1034]
**Describe the issue**
I'm inconsistently getting the error "Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources" on some iOS devices.

The error is constantly spammed, even after _mediaPlayer.Control.CloseMedia();_ is called.

I can do a build for iPhone 11, get the error, go back to Unity and rebuild without changing anything, and the error will go away. However, this past week I'm constantly getting the error on iPhone XR and cannot get rid of it. 
The video that is not working on iPhone XR works without problem on iPhone 8 and 11, from the same builds.

The videos are streamed, I send a request to the server for a URL to the video, it returns it and I give that to the AVPro media play to open. It's an m3u8 file.

Looking through the logs for this post, I found the following error

`2021-12-01 10:14:36.242780+0000 Vodiac[98998:16411053] [Player] failed to load resource, provide a decryption key or a key server url and/or a key server auth token
`
There is no encryption. I am unable to find anything else about this error Googling it - I assume it's from AVPro?

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.20
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.4 Ultra
 - Operating system version: iOS 15
 - Device model: iPhone XR (also observed on iPhone 11, but less often)
 - Video specs (resolution, frame-rate, codec, file size): 
Resolution: 2880x1440
Frame-rate: 30
Codec: h264
File size: various

 - XCode version: 13.1

**Logs**

> 2021-12-01 10:14:27.226245+0000 Vodiac[98998:16411053] Built from '2020.3/staging' branch, Version '2020.3.20f1 (41c4e627c95f)', Build type 'Development', Scripting Backend 'il2cpp'
> 
> 2021-12-01 10:14:27.227248+0000 Vodiac[98998:16411053] MemoryManager: Using 'Default' Allocator.
> 
> -> applicationDidFinishLaunching()
> 
> PlayerConnection initialized from /private/var/containers/Bundle/Application//Data (debug = 0)
> 
> PlayerConnection initialized network socket : 0.0.0.0 55000
> 
> Multi-casting "[IP] 10.241.9.201 [Port] 55000 [Flags] 2 [Guid] 3661418224 [EditorId] 3756662119 [Version] 1048832 [Id] iPhonePlayer(iPhonewash):56000 [Debug] 0 [PackageName] iPhonePlayer [ProjectName] Vodiac" to [225.0.0.222vod:54997]...
> 
> Started listening to [0.0.0.0:55000]
> 
> PlayerConnection already initialized - listening to [0.0.0.0:55000]
> 
> Loading player data from /private/var/containers/Bundle/Application//Data/data.unity3d
> 
> 2021-12-01 10:14:27.727217+0000 Vodiac[98998:16411053] Writing analzed variants.
> 
> -> applicationDidBecomeActive()
> 
> [Subsystems] Discovering subsystems at path /private/var/containers/Bundle/Application//Vodiac.app/Data/UnitySubsystems
> 
> [Subsystems] No descriptors matched for  examples in UnitySubsystems/cardboard_api/UnitySubsystemsManifest.json.
> 
> [Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/cardboard_api/UnitySubsystemsManifest.json
> 
> [Subsystems] 1 'displays' descriptors matched in UnitySubsystems/cardboard_api/UnitySubsystemsManifest.json
> 
> [Subsystems] No descriptors matched for  meshings in UnitySubsystems/cardboard_api/UnitySubsystemsManifest.json.
> 
> GfxDevice: creating device client; threaded=1
> 
> Initializing Metal device caps: Apple A12 GPU
> 
> Initialize engine version: 2020.3.20f1 (41c4e627c95f)
> 
> XRGeneral Settings awakening...
> 
> UnityEngine.XR.Management.XRGeneralSettings:Awake()
> 
> 
> 
> Cardboard not initialized, use InitCardboard() or InitCardboardInput()
> 
> Google.XR.Cardboard.XRLoaderImmotion:Initialize()
> 
> UnityEngine.XR.Management.XRManagerSettings:InitializeLoaderSync()
> 
> UnityEngine.XR.Management.XRGeneralSettings:InitXRSDK()
> 
> 
> 
> UnloadTime: 0.746042 ms
> 
> 
> 
> 2021-12-01 10:14:28.658747+0000 Vodiac[98998:16411053] Reachability Flag Status: -R ------- networkStatusForFlags
> 
> 2021-12-01 10:14:28.752689+0000 Vodiac[98998:16411053] Reachability Flag Status: -R ------- networkStatusForFlags
> 
> Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
> 
> 2021-12-01 10:14:28.817186+0000 Vodiac[98998:16411053] Unbalanced calls to begin/end appearance transitions for <UnityViewControllerStoryboard: 0x102b1f380>.
> 
> 2021-12-01 10:14:28.817795+0000 Vodiac[98998:16411053] Unbalanced calls to begin/end appearance transitions for <UnityPortraitOnlyViewController: 0x102b932c0>.
> 
> UnloadTime: 0.740125 ms
> 
> System memory in use before: 40.8 MB.
> 
> System memory in use after: 41.0 MB.
> 
> 
> 
> Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 3266.
> 
> Total: 1.942750 ms (FindLiveObjects: 0.203542 ms CreateObjectMapping: 0.096875 ms MarkObjects: 1.627333 ms  DeleteObjects: 0.014250 ms)
> 
> 
> 
> No pending purchases found.
> 
> SaveData:LoadPendingPurchases()
> 
> PurchaseManager:GetPendingPurchases()
> 
> PurchaseManager:Start()
> 
> 
> 
> No pending purchases in saved list.
> 
> PurchaseManager:Start()
> 
> 
> 
> No pending transactions with the store, clearing pending list
> 
> PurchaseManager:CheckPendingPurchases()
> 
> 
> 
> 2021-12-01 10:14:29.374980+0000 Vodiac[98998:16411053] [Plugin] 🔹 AVProVideo version 2.2.4-ultra build 1023 on iPhone XR running iOS 15.0.2
> 
> 2021-12-01 10:14:29.519846+0000 Vodiac[98998:16411053] [AssetCache] restoring pending downloads...
> 
> [AVProVideo] Initialising AVPro Video v2.2.4 (native plugin v2.2.4-ultra build 1023) on Apple A12 GPU/Metal (MT True) on IPhonePlayer
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Start()
> 
> 
> 
> 2021-12-01 10:14:29.661890+0000 Vodiac[98998:16411053] Reachability Flag Status: -R ------- networkStatusForFlags
> 
> 2021-12-01 10:14:29.662085+0000 Vodiac[98998:16411053] Reachability Flag Status: -R ------- networkStatusForFlags
> 
> 2021-12-01 10:14:30.273972+0000 Vodiac[98998:16411300] [NativePlugins] Load store products finished successfully.
> 
> --- Store initialized successfully. ---
> 
> PurchaseManager:OnInitializeStoreComplete(BillingServicesInitializeStoreResult, Error)
> 
> VoxelBusters.CoreLibrary.EventCallback`1:Invoke(TResult, Error)
> 
> System.Action:Invoke()
> 
> VoxelBusters.CoreLibrary.CallbackDispatcher:LateUpdate()
> 
> 
> 
> Total products fetched: 0
> 
> PurchaseManager:OnInitializeStoreComplete(BillingServicesInitializeStoreResult, Error)
> 
> VoxelBusters.CoreLibrary.EventCallback`1:Invoke(TResult, Error)
> 
> System.Action:Invoke()
> 
> VoxelBusters.CoreLibrary.CallbackDispatcher:LateUpdate()
> 
> 
> 
> Below are the available products:
> 
> PurchaseManager:OnInitializeStoreComplete(BillingServicesInitializeStoreResult, Error)
> 
> VoxelBusters.CoreLibrary.EventCallback`1:Invoke(TResult, Error)
> 
> System.Action:Invoke()
> 
> VoxelBusters.CoreLibrary.CallbackDispatcher:LateUpdate()
> 
> 
> 
> Total invalid products: 1
> 
> PurchaseManager:OnInitializeStoreComplete(BillingServicesInitializeStoreResult, Error)
> 
> VoxelBusters.CoreLibrary.EventCallback`1:Invoke(TResult, Error)
> 
> System.Action:Invoke()
> 
> VoxelBusters.CoreLibrary.CallbackDispatcher:LateUpdate()
> 
> 
> 
> Here are the invalid product ids:
> 
> PurchaseManager:OnInitializeStoreComplete(BillingServicesInitializeStoreResult, Error)
> 
> VoxelBusters.CoreLibrary.EventCallback`1:Invoke(TResult, Error)
> 
> System.Action:Invoke()
> 
> VoxelBusters.CoreLibrary.CallbackDispatcher:LateUpdate()
> 
> PurchaseManager:OnInitializeStoreComplete(BillingServicesInitializeStoreResult, Error)
> 
> VoxelBusters.CoreLibrary.EventCallback`1:Invoke(TResult, Error)
> 
> System.Action:Invoke()
> 
> VoxelBusters.CoreLibrary.CallbackDispatcher:LateUpdate()
> 
> 
> 
> ------
> 
> PurchaseManager:OnInitializeStoreComplete(BillingServicesInitializeStoreResult, Error)
> 
> VoxelBusters.CoreLibrary.EventCallback`1:Invoke(TResult, Error)
> 
> System.Action:Invoke()
> 
> VoxelBusters.CoreLibrary.CallbackDispatcher:LateUpdate()
> 
> 
> 
> No pending transactions with the store, clearing pending list
> 
> PurchaseManager:CheckPendingPurchases()
> 
> DisplayVideoDetails:SetVideoDetails(Video, Boolean)
> 
> System.Action:Invoke()
> 
> Immotion.UI.SelectableEventController:InvokeClick(Boolean)
> 
> DG.Tweening.TweenCallback:Invoke()
> 
> DG.Tweening.Tween:OnTweenCallback(TweenCallback, Tween)
> 
> DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode)
> 
> DG.Tweening.Core.TweenManager:Update(Tween, Single, Single, Boolean)
> 
> DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single)
> 
> DG.Tweening.Core.DOTweenComponent:Update()
> 
> 
> 
> [AVProVideo] Opening <URLREMOVED> (offset 0) with API 
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
> 
> VideoSceneManager:StartXR()
> 
> System.Action`1:Invoke(T)
> 
> DG.Tweening.TweenCallback:Invoke()
> 
> DG.Tweening.Tween:OnTweenCallback(TweenCallback, Tween)
> 
> DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode)
> 
> DG.Tweening.Core.TweenManager:Update(Tween, Single, Single, Boolean)
> 
> DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single)
> 
> DG.Tweening.Core.DOTweenComponent:Update()
> 
> 
> 
> 2021-12-01 10:14:35.713933+0000 Vodiac[98998:16411053] [Assert] -[UIApplication setStatusBarOrientation:] and -[UIApplication setStatusBarOrientation:animated:] API have been deprecated on iOS 8.0 and are no-ops on iOS 13.0
> 
> 2021-12-01 10:14:36.174598+0000 Vodiac[98998:16411053] [Player] asset duration is 115.05 seconds
> 
> 2021-12-01 10:14:36.174749+0000 Vodiac[98998:16411053] [Player] creating 3 player items
> 
> 2021-12-01 10:14:36.183291+0000 Vodiac[98998:16411053] [Player] asset is compatible with AirPlay
> 
> 2021-12-01 10:14:36.185690+0000 Vodiac[98998:16411053] [Player] asset has 1 audio tracks
> 
> 2021-12-01 10:14:36.204377+0000 Vodiac[98998:16411053] [/Users/jballoffet/CardboardOpenSourceSDK/sdk/unity/xr_unity_plugin/cardboard_display_api.cc : 388] Configured Metal as Graphics API.
> 
> 2021-12-01 10:14:36.204474+0000 Vodiac[98998:16411053] [/Users/jballoffet/CardboardOpenSourceSDK/sdk/unity/xr_unity_plugin/cardboard_input_api.cc : 144] Configured viewport orientation as landscape left.
> 
> 2021-12-01 10:14:36.205251+0000 Vodiac[98998:16411053] [/Users/jballoffet/CardboardOpenSourceSDK/sdk/unity/xr_unity_plugin/cardboard_display_api.cc : 276] SetWidgetParams parameter i=2, out of bounds (size=1)
> 
> [Subsystems] Loading plugin cardboard_api for subsystem CardboardInput...
> 
> [Subsystems] Cardboard successfully registered Provider for CardboardDisplay
> 
> [XR] [CardboardXrMain]: Display subsystem successfully loaded.
> 
> [Subsystems] Cardboard successfully registered Provider for CardboardInput
> 
> [Subsystems] Cardboard successfully registered Provider for CardboardDisplay
> 
> [XR] [CardboardXrMain]: Input subsystem successfully loaded.
> 
> [XR] [CardboardXrInputProvider]: Lifecycle initialized
> 
> 2021-12-01 10:14:36.211456+0000 Vodiac[98998:16411053] [Player] player status is ready to play
> 
> [XR] [CardboardXrInputProvider]: Lifecycle started
> 
> 2021-12-01 10:14:36.242780+0000 Vodiac[98998:16411053] [Player] failed to load resource, provide a decryption key or a key server url and/or a key server auth token
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> some error LoadFailed
> 
> VideoPlayerManager:HandleVideoEvent(MediaPlayer, EventType, ErrorCode)
> 
> UnityEngine.Events.UnityAction`3:Invoke(T0, T1, T2)
> 
> UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> Video has an error: LoadFailed
> 
> VideoPlayerManager:HandleError(ErrorCode)
> 
> VideoPlayerManager:HandleVideoEvent(MediaPlayer, EventType, ErrorCode)
> 
> UnityEngine.Events.UnityAction`3:Invoke(T0, T1, T2)
> 
> UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> 2021-12-01 10:14:36.299425+0000 Vodiac[98998:16411053] [Assert] -[UIApplication setStatusBarOrientation:] and -[UIApplication setStatusBarOrientation:animated:] API have been deprecated on iOS 8.0 and are no-ops on iOS 13.0
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()

**Comment by kahnivore** [comment]
Just to confirm, you're getting the error on all three devices, but the video is only failing to play on one of the devices? 

Could you share your stream with us? You can send to unitysupport@renderheads.com with "#1034" in the subject line if you can't share it publicly. 

Can you reproduce this issue in our Demo_MediaPlayer scene?

**Comment by ImmotionPeterL** [comment]
The error occurs on all 3 devices. When it happens the video does not play. On the iPhone 11 and 8 a rebuild gets rid of the error (though can come back in another build), on iPhone XR it won't go away.

Using the demo scene, in a very quick test - from two test builds, the first build everything was ok. Going back into Unity, changing nothing just building, the video did not work and the same error was observered.

Email sent.

> 2021-12-01 17:29:48.187224+0000 Vodiac[99739:16539666] [Player] asset duration is 115.05 seconds
> 
> 2021-12-01 17:29:48.187252+0000 Vodiac[99739:16539666] [Player] creating 3 player items
> 
> 2021-12-01 17:29:48.188154+0000 Vodiac[99739:16539666] [Player] asset is compatible with AirPlay
> 
> 2021-12-01 17:29:48.188235+0000 Vodiac[99739:16539666] [Player] asset has 1 audio tracks
> 
> 2021-12-01 17:29:48.191433+0000 Vodiac[99739:16539666] Unbalanced calls to begin/end appearance transitions for <UnityViewControllerStoryboard: 0x1027229e0>.
> 
> 2021-12-01 17:29:48.191734+0000 Vodiac[99739:16539666] Unbalanced calls to begin/end appearance transitions for <UnityPortraitOnlyViewController: 0x102721f50>.
> 
> 2021-12-01 17:29:48.197682+0000 Vodiac[99739:16539666] [Player] player status is ready to play
> 
> 2021-12-01 17:29:48.241253+0000 Vodiac[99739:16539666] [Player] failed to load resource, provide a decryption key or a key server url and/or a key server auth token
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()
> 
> 
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
> 
> RenderHeads.Media.AVProVideo.MediaPlayer:Update()

**Comment by MorrisRH** [comment]
Your manifest has an error in it, the second entry starts ``hhttps://``, this is leading to the error.
The message about encryption is slightly misleading so we've improved on that.

**Comment by ImmotionPeterL** [comment]
Sorry, I don't know which manifest you mean or where to find it.

**Comment by MorrisRH** [comment]
The m3u8 file linked from the URL you sent.
