### ISSUE TITLE
Can one package a video in an Addressables bundle in Unity?

### ISSUE THREAD

**Issue by LukeFarrer** [RenderHeads/UnityPlugin-AVProVideo#1037]
We are creating a project that has multiple scenes with lots of textures and videos.
The textures are packaged using the Unity Addressables package and stored remotely on Google Cloud. We create a separate .bundle file for each scene, which contains the geometry and the textures for that scene.
For each scene, we load the textures dynamically from the cloud and then release them (release the handle) when the scene is unloaded.
It would be nice to do something similar with the videos.
Right now, we are placing all of the videos into the main StreamingAssets folder. The problem was this is that the main .apk is getting bigger and bigger. It would be much better if we could also package the videos into the appropriate scene bundles, load them for each scene, and then release them when unloading the scene.
Can this be done with AVProVideo?

Version of AVProVideo: current (2.2.3)
Platform: Android (Quest 2, VR)
Unity version: 2019.4.11f1

**Comment by LukeFarrer** [comment]
We are creating a project that has multiple scenes with lots of textures and videos.
The textures are packaged using the Unity Addressables package.
For each scene, we load the textures dynamically and then release them (release the handle) when the scene is unloaded.
It would be nice to do something similar with the videos.
Right now, we are placing all of the videos into the main StreamingAssets folder. The problem was this is that the main .apk is getting bigger and bigger. It would be much better if we could also package the videos into the bundles, load them for each scene, and then release them when unloading the scene.
Can this be done with AVProVideo?

**Comment by kahnivore** [comment]
Hi, 

Not really - we can only play videos from files or streaming URLs. 

Would saving to local storage not be a solution for you?

**Comment by RenderHeadsSte** [comment]
We will be closing this issue soon due to lack of response
