### ISSUE TITLE
Can't Temporarily Deactivate Apply to Mesh

### ISSUE THREAD

**Issue by visualmusicdesign** [RenderHeads/UnityPlugin-AVProVideo#1038]
**Describe the issue**
I have not been able to successfully temporarily deactivate Apply to Mesh.  I am trying to temporarily deactivate it during video seeking for various reasons.

It seems that once the link is set up between the MediaPlayer and the Mesh Renderer, it's impossible to stop the Media Player from sending frames to the Mesh.

Here is what I've tried:

- Disabling the Apply to Mesh component

- ApplyToMesh.TexturePropertyName = "_SpareTex" (non-used extra texture in shader);

- ApplyToMesh.MaterialIndex = 5;

- ApplyToMesh.MeshRenderer = null;

- ApplyToMesh.ForceUpdate();

After all those code lines, the Media Player still sends frames to the Mesh - quite frustrating.

Could you please provide some way to temporarily deactivate the Apply to Mesh component during runtime?

Thank you

**Your Setup (please complete the following information):**
 - Unity version: 2021.2.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.2.2 Core
 - Operating system version:  MacOS 12.0
 - Device model:  MacBook Pro M1 2021
 - Video specs (resolution, frame-rate, codec, file size): 720p H.264 

**To Reproduce**
1. Create an Apply to Mesh and a MediaPlayer - link the MediaPlayer to a MeshRenderer with Apply to Mesh
2. Attempt to stop the MediaPlayer from sending frames to the MeshRenderer during runtime

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Could we get some more detail about your reasons for trying to do this?

**Comment by visualmusicdesign** [comment]
It’s quite complicated - I began typing it out but I’d really rather not explain it all unless you really need me to.  The long and short of it is that I need to seek away from a frame and back to the same frame without the user knowing.  

I’m really just asking for a way to undo whatever Apply to Mesh did when it awoke / started.

**Comment by kahnivore** [comment]
Thanks, we're looking into this

**Comment by visualmusicdesign** [comment]
Hello,
I know it's been the holidays and don't want to push - just wanted to bump this issue in the hopes that there might be a relatively simple fix?

Would very much appreciate, Thank you.

**Comment by kahnivore** [comment]
Hi there, 

We are currently testing a workaround for this. 

Thank you for your patience!

**Comment by AndrewRH** [comment]
@visualmusicdesign thanks for reporting this, the issue has now been fixed and will be in the next release
