### ISSUE TITLE
Sound isn't spatialized on 360 Video (Oculus Quest, Pico)

### ISSUE THREAD

**Issue by LeoPaulB2B** [RenderHeads/UnityPlugin-AVProVideo#1045]
Hello all,

Problem description:

I followed guideline from https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html
but my sound isn't spatialized, only stereo.

Have I missed any parameter in my project or maybe my video isn't good ?

Thank you

Device (which devices are you having the issue with - model, OS version number):

Oculus Quest 1 & 2, Pico

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

Got this scan from Handbrake software :

Input #0, matroska,webm, from 'R:\WORK_ARCHIVE\CARE - FILES\files\Videos\CARE_SEQ01.mkv':
  Metadata:
    FB360           : <fb360>
                    :   <audio>
                    :     <encoder_metadata name="FB360 Encoder" version="3.3.3" osName="Windows 10" is64bit="yes"
                    :                       git_commit_date="20200402" git_hash="a0e6e0451b36+">
                    :       <ffmpeg_version>ffmpeg version 3.2 Copyright (c) 2000-2016 the FFmpeg developers
                    : built with gcc 7.2.0 (GCC)
                    : configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopenjpeg
                    : libavutil      55. 34.100 / 55. 34.100
                    : libavcodec     57. 64.100 / 57. 64.100
                    : libavformat    57. 56.100 / 57. 56.100
                    : libavdevice    57.  1.100 / 57.  1.100
                    : libavfilter     6. 65.100 /  6. 65.100
                    : libswscale      4.  2.100 /  4.  2.100
                    : libswresample   2.  3.100 /  2.  3.100
                    : libpostproc    54.  1.100 / 54.  1.100
                    : </ffmpeg_version>
                    :       <mp4box_version>MP4Box - GPAC version 0.8.0-rev1-gc1990d5c-master
                    : (c) Telecom ParisTech 2000-2018 - Licence LGPL v2
                    : GPAC Configuration: (static configuration file)
                    : Features: GPAC_64_BITS GPAC_MEMORY_TRACKING GPAC_HAS_SSL GPAC_HAS_SPIDERMONKEY GPAC_HAS_JPEG GPAC_HAS_PNG
                    : </mp4box_version>
                    :       <python_version>Python 2.7.16
                    : </python_version>
                    :       <spatial sample_rate="48000" bit_depth="32" format="tbe_8" channel_map="0 2 1 6 7 4 5 3"/>
                    :       <headlocked sample_rate="48000" bit_depth="32"/>
                    :     </encoder_metadata>
                    :   </audio>
                    : </fb360>
                    :
    MAJOR_BRAND     : mp42
    MINOR_VERSION   : 0
    COMPATIBLE_BRANDS: mp42mp41
    ENCODER         : Lavf57.56.100
  Duration: 00:04:51.11, start: -0.007000, bitrate: 60421 kb/s
  Stream #0:0(eng): Video: hevc (Main), yuv420p(tv, bt709), 3840x3840 [SAR 1:1 DAR 1:1], 30 fps, 30 tbr, 1k tbn, 30 tbc (default)
    Metadata:
      HANDLER_NAME    : Alias Data Handler
      ENCODER         : HEVC Coding
      SPHERICAL-VIDEO : <?xml version="1.0"?>
                      : <rdf:SphericalVideo xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:GSpherical="http://ns.google.com/videos/1.0/spherical/">
                      :   <GSpherical:Spherical>true</GSpherical:Spherical>
                      :   <GSpherical:Stitched>true</GSpherical:Stitched>
                      :   <GSpherical:StitchingSoftware>Facebook 360 Spatial Workstation</GSpherical:StitchingSoftware>
                      :   <GSpherical:ProjectionType>equirectangular</GSpherical:ProjectionType>
                      :   <GSpherical:StereoMode>top-bottom</GSpherical:StereoMode>
                      : </rdf:SphericalVideo>
      DURATION        : 00:04:51.107000000
  Stream #0:1: Audio: opus, 48000 Hz, 10 channels, fltp
    Metadata:
      FB360           : <fb360>
                      :   <audio>
                      :     <AudioChannelConfiguration
                      :       schemeIdUri="tag:facebook.com,2016-08-16:fb360:audio:channel_layout"
                      :       value="tbe_8.2" />
                      :   </audio>
                      : </fb360>
      DURATION        : 00:04:51.001000000
[12:18:36] scan: decoding previews for title 1
[12:18:36] scan: audio 0x1: opus, rate=48000Hz, bitrate=1 Unknown (Opus)
[12:18:43] scan: 10 previews, 3840x3840, 30.000 fps, autocrop = 138/226/276/914, aspect 1.00:1, PAR 1:1, color profile: 1-1-1
[12:18:43] libhb: scan thread found 1 valid title(s)

System Information:

AVPro Video: v2.3.0 (plugin v2.3.0f1-ultra)
Target Platform: Android
Unity: v2020.3.1f1

**Comment by RenderHeadsSte** [comment]
Did you set the 'Audio Output' on the MediaPlayer component to 'Facebook 360 Audio' ?  Did you also set the correct channel mode?  This needs to be done at initialisation time.  We do not currently support these values changing after the player has been initialised (on Android).

**Comment by LeoPaulB2B** [comment]
Yes to both. Its set up in inspector Facebook 360 Audio and TBE_8_2

**Comment by RenderHeadsSte** [comment]
Is it possible to share your video?  You can email it over to [unitysupport@renderheads.com](unitysupport@renderheads.com) with the subject line #1045 if you require to keep it private.

We always use this FB360 video for our internal testing:  [https://bit.ly/3DWairN](https://bit.ly/3DWairN)

Maybe you could give that a try?

**Comment by LeoPaulB2B** [comment]
I tested your video. Spatialization is fine with yours ! Maybe its from my file then. I'll email it to you then, thank you

**Comment by LeoPaulB2B** [comment]
When you said it needs to be done at initialisation time, is it also possible in an Awake() method ?

**Comment by RenderHeadsSte** [comment]
If you look in the AndroidMediaPlayer class you will see where it is passed down to the plug-in, when calling the InitialisePlayer function. Values need to be set correctly before that fires.

**Comment by RenderHeadsSte** [comment]
@LeoPaulB2B

Upcoming in the next release...

Audio subsystem and FB360 channel arrangement can now be changed on a MediaPlayer object between video opening.  So you can change and open a new video, or define the values after initialisation, but prior to opening the video.
