### ISSUE TITLE
A phenomenon in which the sound of the live stream image is released when the camera is taken after lowering the sound of the device after playing the live stream in IOS and then moving the background.

### ISSUE THREAD

**Issue by varunitestudio** [RenderHeads/UnityPlugin-AVProVideo#1047]
A phenomenon in which the sound of the live stream image is released when the camera is taken after lowering the sound of the device after playing the live stream in IOS and then moving the background.

For the test at Demo,
1. AVPro 2.3.0 Import
2. Uncheck PauseMediaOnAppPause, PlayMediaOnAppUnpause in the Events item.
3. If you go to BackGound after building, the video stops and you can't test it.

**Your Setup (please complete the following information):**
 - Unity version: Unity 2019.4.15f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.3.0
 - Operating system version: ios14.6
 - Device model: iPhone 12 mini
 - Video specs (resolution, frame-rate, codec, file size): https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

What should I do?

**Comment by SecretTonto** [comment]
@AndrewRH
Do you have any plans to revise this issue?

**Comment by varunitestudio** [comment]
@AndrewRH 
May I know how this issue is going?

**Comment by kahnivore** [comment]
Hi @varunitestudio 

Sorry this issue got overlooked. Have you tried with the latest version and are you still having problems? 

If so, could we get a bit more clarity about what you mean by the sound being 'released'? Not 100% certain what the problem is. 

Also, which audio output mode are you using?

**Comment by varunitestudio** [comment]
Hi @kahnivore 
Thank you for your reply.
It currently occurs in AVPro 2.4.0.
1. Play live streaming on AVPro.
2. Lower the volume of the iPhone to a minimum.
3. Launch the camera app and press the Shoot button.
4. I can hear the live streaming video.

The audio output mode uses Unity.

**Comment by kahnivore** [comment]
Thanks for the clarification. Does the same thing happen with the audio mode set to system direct?

**Comment by varunitestudio** [comment]
I was mistaken.
The current audio mode uses System Direct.
Do I need to modify it to Unity and test it?

**Comment by Chris-RH** [comment]
Hi @varunitestudio, its certainly worth a try to see if that resolves the issue.

**Comment by varunitestudio** [comment]
@kahnivore @Chris-RH 
The same bug occurs even when the test is modified to Unity.

If you shut down the camera app, the sound disappears.

**Comment by kahnivore** [comment]
Sorry @varunitestudio that was a bit misleading - HLS can only output audio via system, not Unity - so it's defaulting to system regardless. We suspect this might be a system issue and not something we're causing with our player. There might however be something we can do to mitigate it. We'll update here once we've had a chance to look into this further.
