### ISSUE TITLE
Trying to understand if this will fulfill playback requirements

### ISSUE THREAD

**Issue by TexelStudios** [RenderHeads/UnityPlugin-AVProVideo#1048]
Hi — sorry, this isn't an issue, but it's also not a non-technical question, so I didn't know how to categorize it.

Can you confirm if your plugin will allow me to:

- seamlessly loop video content from 1080p to 2160p of any duration (my understanding is that making every frame a keyframe is necessary to have truly seamless looping)

- at specific frames/keyframes, trigger an audio file (my understanding is that an audio track within the video will interfere with the seamless looping as described above, so I'm wondering about syncing an external audio file during video playback — like having a bass drum hit on every 15th frame/keyframe to go along with a 30fps video)

- "chain together" those loops in specific sequences to create a longer seamless loop (my understanding is that a playlist can do this)

- take that playlist/chained loop and randomize the order of the individual loops played within that, through some sort of programming (with an array or something similar)

I appreciate your time and assistance!

**Comment by AndrewRH** [comment]
Hi,

> seamlessly loop video content from 1080p to 2160p of any duration (my understanding is that making every frame a keyframe is necessary to have truly seamless looping)

Yes and no... seamless looping can vary based on the platform and the way the media is encoded.  I believe that currently our best seamless looping is on the macOS and iOS platforms.   On Windows the looping can be seamless (or very close to it), but that generally requires the video to be keyframes-only (for h264/hevc), or using a codec such as Hap which is designed for this.   And yes, not having audio will also help to make the playback seamless.   Seamless playback though is not the focus of the plugin so we recommend testing it.

> at specific frames/keyframes, trigger an audio file (my understanding is that an audio track within the video will interfere with the seamless looping as described above, so I'm wondering about syncing an external audio file during video playback — like having a bass drum hit on every 15th frame/keyframe to go along with a 30fps video)

Yes you can monitor which frame is displayed and then trigger something based on that

> "chain together" those loops in specific sequences to create a longer seamless loop (my understanding is that a playlist can do this)

Yes that Playlist component can do this, but it may not be 100% perfectly seamless, but it should be very close.

> take that playlist/chained loop and randomize the order of the individual loops played within that, through some sort of programming (with an array or something similar)

Yes the list of media can be adjusted on the fly in the ``PlaylistMediaPlayer`` component

Other than that, I recommend testing your requirements with the free trial version to see if it suits your needs.

Hope that helps to answer some of your questions.

Thanks,
