### ISSUE TITLE
Not able to access MediaPlayer script Play() method

### ISSUE THREAD

**Issue by syedali1621** [RenderHeads/UnityPlugin-AVProVideo#105]
I want to run Play() method of media player script from other script but media player script is inaccessible. I am able to access my own written other scripts but when i try to access media player script to run its play() method it's inaccessible. Please let me know how can i access it ?

Thank you

**Comment by AndrewRH** [comment]
I don't think this is a bug - sounds like a usage issue.  
Check out this:
https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html

Unity has certain requirements for script build orders related to accessing other scripts.  They've also introduced assembly definition files (asmdef) that could be causing this if used incorrectly.  I think it will just be that your script is being compiled into a different assembly.  See the link above, hopefully that will solve it.

**Comment by syedali1621** [comment]
Yes this is not a bug i mistakenly selected bug.
and now i solved this problem by calling using RenderHeads.Media.AVProVideo;
now i am able to call media player play() method.

Thank you
