### ISSUE TITLE
Restart Video from Beginning after Target Reacquired

### ISSUE THREAD

**Issue by eklnyc** [RenderHeads/UnityPlugin-AVProVideo#1050]
**Describe the issue**
Using earlier versions of Unity (2019.1.14, Vuforia 9.6.4 (might have been 9.7.5), and AVPro 1.11.4, I was able to have a video in an AR environment disappear when the target was lost and restart FROM THE BEGINNING when the target was reacquired (e,g., when the phone/tablet was handed from one user to another) with code that follows. If I try to attach that code to the Image Target in my present configuration (see below), I get the following three  error messages:

1.
Assets\VideoControllerAVPro.cs(7,52): error CS0246: The type or namespace name 'ITrackableEventHandler' could not be found (are you missing a using directive or an assembly reference?)

2.
Assets\VideoControllerAVPro.cs(51,28): error CS0426: The type name 'Status' does not exist in the type 'TrackableBehaviour'

3.
Assets\VideoControllerAVPro.cs(52,28): error CS0426: The type name 'Status' does not exist in the type 'TrackableBehaviour'

The ImageTarget Inspector has DefaultObserverEventHandler in it but not TrackableEventHandler. And I realize that TrackableBehavious is being deprecated but have not been able to modify the script accordingly. Even if I add DefaultTrackableEventHandler (which is in the TargetManager Inspector of my earlier project) into the ImageTarget Inspector and then add a script with the code below, I get the same error messages. (At present, I have removed DefaultTrackableEventHandler and the offending script.) I suspect that I need to change some of the code in the early lines of the script but am new to C# and could use some assistance to make this work. 

+++
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Vuforia;

public class VideoControllerAVPro : MonoBehaviour, ITrackableEventHandler
{
    private TrackableBehaviour mTrackableBehaviour;
    private RenderHeads.Media.AVProVideo.MediaPlayer videoPlayer;

    // Start is called before the first frame update
    void Start()
    {
        mTrackableBehaviour = GetComponent<TrackableBehaviour>();
        if (mTrackableBehaviour)
            mTrackableBehaviour.RegisterTrackableEventHandler(this);

        videoPlayer = GetComponent<RenderHeads.Media.AVProVideo.MediaPlayer>();
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnTrackingFound()
    {
        Debug.Log("OnTrackingFound");
        if(videoPlayer)
        {
            //videoPlayer.frame = 0;
            videoPlayer.Rewind(false);
            videoPlayer.Play();
        }

    }
    private void OnTrackingLost()
    {
        Debug.Log("OnTrackingLost");
        if (videoPlayer)
        {
            videoPlayer.Stop();
            videoPlayer.Rewind(false);
           // videoPlayer.frame = 0;
        }
    }

    public void OnTrackableStateChanged(
        TrackableBehaviour.Status previousStatus,
        TrackableBehaviour.Status newStatus)
    {
        if (newStatus == TrackableBehaviour.Status.DETECTED ||
            newStatus == TrackableBehaviour.Status.TRACKED ||
            newStatus == TrackableBehaviour.Status.EXTENDED_TRACKED)
        {
            OnTrackingFound();
        }
        else if (previousStatus == TrackableBehaviour.Status.TRACKED &&
                 newStatus == TrackableBehaviour.Status.NO_POSE)
        {
            OnTrackingLost();
        }
        else
        {
            OnTrackingLost();
        }
    }
}
+++

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.23
 - Vuforia version: 10.3.2
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.3.0 (trial/Android)
 - Operating system version: Windows 11
 - Device model: Samsung Galaxy S21 5g
 - Video specs (resolution - 1082x720, frame-rate - 29.97, codec - H.264, mp4 file size - 155 mB - about 2:30): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
These error messages have nothing to do with AVPro Video, they are related to Vuforia change in API.

The first one I googled and found that you have to change

`public class VideoControllerAVPro : MonoBehavior, ITrackableEventHandler`

to:

`public class VideoControllerAVPro : DefaultTrackableEventHandler`

I will not go into the rest as they are not related to our product and I'm afraid I am not a Vuforia expert.

Thanks,

**Comment by eklnyc** [comment]
Thank you Andrew. I will try your suggestion and pursue other avenues.  / One other question related to your comment on Vuforia. Would Unity MARS be more suitable? I am in the middle of a 45-day trial of it but have not found it to be particularly useful. Your (brief) opinion would be helpful.

**Comment by kahnivore** [comment]
The AR SDK you choose will depend on your needs and is not really something we can give advice on. 

Closing this issue as it is not related to AVPro Video but feel free to open a new one if you have any issues with our plugin at any point.

Thanks!
