### ISSUE TITLE
Dose it support "AssetBundle" or "AddressableAsset"?

### ISSUE THREAD

**Issue by stevekim0417** [RenderHeads/UnityPlugin-AVProVideo#1051]
**Is your feature request related to a problem? Please describe.**
I have a lot of video files to be downloaded from Addressable Asset Server.  It is a video clip. 

**Describe the solution you'd like**
transform VideoClip to MediaReference. 

**Describe alternatives you've considered**

**Additional context**

**Comment by AndrewRH** [comment]
VideoClip / Addressables / Assetbundles are not supported
