### ISSUE TITLE
Can change the path in runtime? 

### ISSUE THREAD

**Issue by DeveloperMOA** [RenderHeads/UnityPlugin-AVProVideo#1055]
**Describe the issue**
It is not an error as such but I need to know if I can change the path at runtime. I need to make a playback menu and I have some buttons that will help me to call the new video to play or it is necessary to put a player for each video that I want to play and it is only a matter of hiding and showing them. THX

**Comment by kahnivore** [comment]
Yes you can. See our [loading media](https://www.renderheads.com/content/docs/AVProVideo/articles/usage-loading-media.html#scripting) page for more info. We also offer a [free trial version](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases) if you would like to test your use case. 

Thanks!

**Comment by DeveloperMOA** [comment]
@kahnivore Thanks a lot! I already bought the plugin and I am testing it but when using the reference scripts it asks me for a namespace or am I missing something at the time of implementation?

here is the error I have:
error CS0246: The type or namespace name 'MediaReference' could not be found (are you missing a using directive or an assembly reference?)

**Comment by kahnivore** [comment]
Are you using using RenderHeads.Media.AVProVideo?

**Comment by DeveloperMOA** [comment]
Yes, I am using using RenderHeads.Media.AVProVideo

I show you what I have in code, I just want that when I press a key it changes the source of the video.

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RenderHeads.Media.AVProVideo;



public class ChangeVideoPath : MonoBehaviour
{
   public void Update()
   {
       if(Input.GetKeyDown(KeyCode.A))
       {
         bool isOpening = mediaPlayer.OpenMedia(new MediaPath("my new path",MediaPathType.AbsolutePathOrURL), autoPlay:true);
       }
   }
}

**Comment by kahnivore** [comment]
It looks like you're missing a reference to the MediaPlayer component. 

E.g. [SerializeField] MediaPlayer mediaPlayer; Then you'll need to assign the MediaPlayer in the inspector of this script object. 

Does that help?

**Comment by DeveloperMOA** [comment]
THX, works like a charm!!!
