### ISSUE TITLE
Adaptive Video Not Working on Quest 1

### ISSUE THREAD

**Issue by KGartner-HoppinDev** [RenderHeads/UnityPlugin-AVProVideo#1056]
Streaming an adaptive HLS video it is stuck at the lowest bitrate version even when have good internet connection. Will not go to a higher bitrate. While on Oculus Quest V2 we have no issue of the video adapt to the proper quality. 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.3f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  Core
 - Device model: Oculus Quest 1
 - Video specs (resolution, frame-rate, codec, file size): 
 Stereo: 3840x3840 h264 30fps
 Mono: 5760x2880 h264 30fps

**To Reproduce**
1. Stream video on Oculus 1

**Comment by kahnivore** [comment]
Could you share your stream with us so we could take a look? You're welcome to send to unitysupport@renderheads.com if it's private - please include "1056" in the subject line if you do. 

Thanks!

**Comment by KGartner-HoppinDev** [comment]
Hi Any update on this issue? thanks

**Comment by nblais-Hoppin** [comment]
Hi, thank you for looking into this issue, should you need us to provide more info, please do let us know.
Any eta on this ticket moving out of triage?
Best regards,

**Comment by RenderHeadsSte** [comment]
We are still waiting for a stream url to be shared.  I believe you sent a single manifest file only.  We require a URL to the stream in order to reproduce and investigate.

**Comment by RenderHeadsSte** [comment]
Have you tried another known good HLS stream?

https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

**Comment by nblais-Hoppin** [comment]
Hi, 

Thank you very much for your quick follow-up, much appreciated! 

Apologies for the missing stream URL, we'll see that it gets to you in the right format. We'll also test the m3u8 you provided to see how it behaves in our environment.

Best,

**Comment by RenderHeadsSte** [comment]
I first tested your stream in the native ExoPlayer demo.  This performs exactly the same as AVPro Video.  I am seeing your stream only get up to the '12mbit' stream on a Xiaomi Mi10T phone

I think the issue is your manifest.  It looks like you are trying to trick the player to play higher bitrate streams?  ExoPlayer limits which adaptation is played on more than just a provided value.  If it cannot buffer, it chops back.

No sure why you are seeing it work on Quest2 though.  Are you seeing it get up to the 75Mbit stream?  I never see more than 12 here on whatever device I test on.

**Comment by nblais-Hoppin** [comment]
Thanks a lot for all the info!

We'll continue our investigation taking into account your tests results and see what we can find. We'll keep you posted.

Best,

**Comment by Renaud-Hoppin** [comment]
Hello @RenderHeadsSte, 
We have tried to play our video on a HLS webplayer, and it adapts well up to 75mbps: 
[Webplayer link here](http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html#%7B%22engine%22%3Atrue%2C%22stvod%22%3Atrue%2C%22ncweb%22%3Atrue%2C%22url%22%3A%22https%3A%2F%2Fd1cboy98ginn6g.cloudfront.net%2Fe%2F61b2501a3952d60009ddcc72%2Fs%2F61b2501e683f5c6a750ae79f%2Fq1%2Fmaster_manifest.m3u8%22%2C%22thumb%22%3A%22http%3A%2F%2Fcdnbakmi.kaltura.com%2Fp%2F243342%2Fsp%2F24334200%2Fthumbnail%2Fentry_id%2F1_sf5ovm7u%2Fversion%2F100003%2Fwidth%2F640%22%2C%22hlsLiveSegmentBuffer%22%3A-1%2C%22hlsInitialBufferTime%22%3A-1%2C%22hlsExpandedBufferTime%22%3A-1%2C%22hlsMaxBufferTime%22%3A-1%2C%22hlsLogs%22%3Atrue%2C%22dvr%22%3Afalse%7D)

We can see by the watermark used on the video image, and by the **played segment** showed below the video that our manifest is correct, and adapts up to 75mbps. 

I also tried with another video, this one going only up to 24mbps.
[Webplayer link here](http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html#%7B%22engine%22%3Atrue%2C%22stvod%22%3Atrue%2C%22ncweb%22%3Atrue%2C%22url%22%3A%22https%3A%2F%2Fd1cboy98ginn6g.cloudfront.net%2Fe%2F61f981eb95430c00096186b4%2Fs%2F61f981ef801d1c37d8009f71%2Fq1%2Fmaster_manifest.m3u8%22%2C%22thumb%22%3A%22http%3A%2F%2Fcdnbakmi.kaltura.com%2Fp%2F243342%2Fsp%2F24334200%2Fthumbnail%2Fentry_id%2F1_sf5ovm7u%2Fversion%2F100003%2Fwidth%2F640%22%2C%22hlsLiveSegmentBuffer%22%3A-1%2C%22hlsInitialBufferTime%22%3A-1%2C%22hlsExpandedBufferTime%22%3A-1%2C%22hlsMaxBufferTime%22%3A-1%2C%22hlsLogs%22%3Atrue%2C%22dvr%22%3Afalse%7D)

For this video, we also can see that it can go up without any problem to 24mbps on the webplayer. 

For both these videos, on Oculus Quest 1, using AVPro, the videos are always stuck at 6mpbs. 
On Quest 2, we see the video go up to 75mbps without any problem. (We can see it by using watermarked files in our video) 

It seems the manifest is not the issue. Any other idea what the problem might be?

Thanks!

**Comment by RenderHeadsSte** [comment]
As I said in my last post.  I think the issue is in your manifest or stream.  I have been to our office and picked up a Quest 1 (I have been isolating so was not able to get one before).  The logcat shows this output when trying to play your stream on the Quest 1:

![image](https://user-images.githubusercontent.com/46531149/153466766-8698ee4d-6199-4b69-b228-007db586af61.png)

Something in there the Q1 does not like.

**Comment by RenderHeadsSte** [comment]
For comparison, this is what I see on the Quest 2...all tracks supported:

![image](https://user-images.githubusercontent.com/46531149/153475362-b811bc6e-b8f0-435d-9f3d-d22e6e938399.png)

**Comment by Renaud-Hoppin** [comment]
Hi, we are looking to see if it is not an issue related to the video codecs we are using. We will get back with an update soon. Thanks.

**Comment by kahnivore** [comment]
Closing as it has been some time. Feel free to reopen with an update. 

Thanks!
