### ISSUE TITLE
play rtsp on android crash 

### ISSUE THREAD

**Issue by yingnierxiao** [RenderHeads/UnityPlugin-AVProVideo#1057]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version:  2021.2
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.2.3
 - Operating system version: Mac osx m1 max
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. play rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

 Build fingerprint: 'google/sdk_gphone_arm64/emulator_arm64:11/RSR1.210722.002/7602718:userdebug/dev-keys'
01-09 23:14:05.797  5757  5757 F DEBUG   : Revision: '0'
01-09 23:14:05.797  5757  5757 F DEBUG   : ABI: 'arm64'
01-09 23:14:05.797  5757  5757 F DEBUG   : Timestamp: 2022-01-09 23:14:05+0800
01-09 23:14:05.797  5757  5757 F DEBUG   : pid: 5673, tid: 5701, name: UnityMain  >>> com.DefaultCompany.Car360 <<<
01-09 23:14:05.797  5757  5757 F DEBUG   : uid: 10167
01-09 23:14:05.797  5757  5757 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
01-09 23:14:05.797  5757  5757 F DEBUG   : Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI CallStaticIntMethodV called with pending exception java.lang.IllegalStateException: Unsupported type: 3
01-09 23:14:05.797  5757  5757 F DEBUG   :   at com.google.android.exoplr2avp.source.MediaSource com.renderheads.AVPro.Video.Player_ExoPlayer.BuildMediaSource(java.lang.String, long, java.lang.String, boolean, java.util.List) (Player_ExoPlayer.java:322)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at boolean com.renderheads.AVPro.Video.Player_ExoPlayer.OpenVideoFromFileInternal(java.lang.String, long, java.lang.String, int) (Player_ExoPlayer.java:250)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at void com.renderheads.AVPro.Video.Player_ExoPlayer.PlayerRenderUpdate() (Player_ExoPlayer.java:54)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at void com.renderheads.AVPro.Video.Player_Base.Update() (Player_Base.java:12)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at boolean com.unity3d.player.UnityPlayer.access$600(com.unity3d.player.UnityPlayer) ((null):-1)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at boolean com.unity3d.player.UnityPlayer$g$1.handleMessage(android.os.Message) ((null):-1)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at void android.os.Looper.loop() (Looper.java:223)
01-09 23:14:05.797  5757  5757 F DEBUG   :   at void com.unity3d.player.UnityPlayer$g.run() ((null):-1)
01-09 23:14:05.797  5757  5757 F DEBUG   : 
01-09 23:14:05.797  5757  5757 F DEBUG   :     in call to CallStaticIntMethodV
01-09 23:14:05.797  5757  5757 F DEBUG   :     from boolean com.unity3d.player.UnityPlayer.nativeRender()'
01-09 23:14:05.797  5757  5757 F DEBUG   :     x0  0000000000000000  x1  0000000000001645  x2  0000000000000006  x3  00000070d036afc0
01-09 23:14:05.797  5757  5757 F DEBUG   :     x4  2f2f2f2f2f2f1f62  x5  2f2f2f2f2f2f1f62  x6  2f2f2f2f2f2f1f62  x7  7f7f7f7f7f7f7f7f
01-09 23:14:05.797  5757  5757 F DEBUG   :     x8  00000000000000f0  x9  3e0a442e9e7cf63e  x10 0000000000000000  x11 ffffffc0fffffbdf
01-09 23:14:05.797  5757  5757 F DEBUG   :     x12 0000000000000001  x13 00000000000005b5  x14 002e40d25d977900  x15 0000000029aaaaab
01-09 23:14:05.797  5757  5757 F DEBUG   :     x16 00000073d187ec80  x17 00000073d18603f0  x18 0000007040aeb578  x19 0000000000001629
01-09 23:14:05.797  5757  5757 F DEBUG   :     x20 0000000000001645  x21 00000000ffffffff  x22 0000000000000002  x23 0000000000000002
01-09 23:14:05.797  5757  5757 F DEBUG   :     x24 00000070d036b268  x25 00000073d0851530  x26 00000073d2db986c  x27 000000713d9ec000
01-09 23:14:05.797  5757  5757 F DEBUG   :     x28 000000713d9ed000  x29 00000070d036b040
01-09 23:14:05.797  5757  5757 F DEBUG   :     lr  00000073d1813e20  sp  00000070d036afa0  pc  00000073d1813e4c  pst 0000000000001000
01-09 23:14:05.861  5757  5757 F DEBUG   : backtrace:
01-09 23:14:05.861  5757  5757 F DEBUG   :       #00 pc 000000000004de4c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: ac8f7173c886715a2f2fec67246e21da)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #01 pc 000000000055d030  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2308) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #02 pc 0000000000013978  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76) (BuildId: 7f81cc97d60164bfae3b52a2cd822f20)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #03 pc 0000000000012fa4  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+320) (BuildId: 7f81cc97d60164bfae3b52a2cd822f20)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #04 pc 00000000003851cc  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+2572) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #05 pc 0000000000385244  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+108) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #06 pc 0000000000376f28  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+144) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #07 pc 0000000000375a40  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+3108) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #08 pc 00000000003746a0  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+612) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #09 pc 000000000035c254  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::FindClass(_JNIEnv*, char const*)+692) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #10 pc 0000000000303564  /data/app/~~wOGtXowN9uI0MTV-v0Ce0g==/com.DefaultCompany.Car360-lH76vfGPnX368kURTS8ygQ==/lib/arm64/libunity.so (BuildId: 4f68e462970d74a9b8a76b7c5c42e712058c0a0c)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #11 pc 000000000031828c  /data/app/~~wOGtXowN9uI0MTV-v0Ce0g==/com.DefaultCompany.Car360-lH76vfGPnX368kURTS8ygQ==/lib/arm64/libunity.so (BuildId: 4f68e462970d74a9b8a76b7c5c42e712058c0a0c)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #12 pc 000000000013ced4  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.860  5757  5757 W crash_dump64: type=1400 audit(0.0:120): avc: denied { search } for name="0" dev="tmpfs" ino=10214 scontext=u:r:crash_dump:s0:c167,c256,c512,c768 tcontext=u:object_r:mnt_user_file:s0 tclass=dir permissive=0 app=com.DefaultCompany.Car360
01-09 23:14:05.861  5757  5757 F DEBUG   :       #13 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #14 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #15 pc 0000000000318330  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #16 pc 000000000030e65c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #17 pc 000000000067eb70  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+576) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #18 pc 000000000012d914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #19 pc 0000000000270458  [anon:dalvik-classes.dex extracted in memory from /data/app/~~wOGtXowN9uI0MTV-v0Ce0g==/com.DefaultCompany.Car360-lH76vfGPnX368kURTS8ygQ==/base.apk] (com.unity3d.player.UnityPlayer.access$600)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #20 pc 000000000067f6f0  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+1224) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #21 pc 000000000012d994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #22 pc 000000000026fa58  [anon:dalvik-classes.dex extracted in memory from /data/app/~~wOGtXowN9uI0MTV-v0Ce0g==/com.DefaultCompany.Car360-lH76vfGPnX368kURTS8ygQ==/base.apk] (com.unity3d.player.UnityPlayer$g$1.handleMessage+300)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #23 pc 0000000000305c58  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8100235316906539105)+268) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #24 pc 000000000066b1fc  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #25 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #26 pc 00000000006384d8  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+136) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #27 pc 000000000063b9fc  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+1516) (BuildId: 339e94a38e629aea381d1192e0258d731e293228)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #28 pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #29 pc 00000000001a8a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #30 pc 0000000000318330  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #31 pc 000000000030e65c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #32 pc 000000000067f44c  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+548) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #33 pc 000000000012d994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #34 pc 000000000026fe8c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~wOGtXowN9uI0MTV-v0Ce0g==/com.DefaultCompany.Car360-lH76vfGPnX368kURTS8ygQ==/base.apk] (com.unity3d.player.UnityPlayer$g.run+40)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #35 pc 0000000000305c58  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8100235316906539105)+268) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #36 pc 000000000066b1fc  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #37 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #38 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #39 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #40 pc 0000000000554c6c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #41 pc 00000000005a4008  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308) (BuildId: b628ec1e4df42966356fcd82bcb1136d)
01-09 23:14:05.861  5757  5757 F DEBUG   :       #42 pc 00000000000af8c8  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: ac8f7173c886715a2f2fec67246e21da)
01-09 23:14:05.862  5757  5757 F DEBUG   :       #43 pc 000000000004fe08  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ac8f7173c886715a2f2fec67246e21da)
01-09 23:14:05.888     0     0 D logd    : logdr: UID=10167 GID=10167 PID=5757 n tail=50 logMask=8 pid=5673 start=0ns timeout=0ns
01-09 23:14:05.888     0     0 D logd    : logdr: UID=10167 GID=10167 PID=5757 n tail=50 logMask=1 pid=5673 start=0ns timeout=0ns
01-09 23:14:05.912     0     0 D logd    : logdr: UID=10167 GID=10167 PID=5757 n tail=0 logMask=8 pid=5673 start=0ns timeout=0ns
01-09 23:14:05.912     0     0 D logd    : logdr: UID=10167 GID=10167 PID=5757 n tail=0 logMask=1 pid=5673 start=0ns timeout=0ns
01-09 23:14:05.860  5757  5757 I chatty  : uid=10167(com.DefaultCompany.Car360) crash_dump64 identical 2 lines
01-09 23:14:05.860  5757  5757 W crash_dump64: type=1400 audit(0.0:123): avc: denied { search } for name="0" dev="tmpfs" ino=10214 scontext=u:r:crash_dump:s0:c167,c256,c512,c768 tcontext=u:object_r:mnt_user_file:s0 tclass=dir permissive=0 app=com.DefaultCompany.Car360

**Comment by kahnivore** [comment]
Which Android device are you targeting?
