### ISSUE TITLE
Buffer not growing with playback rate over 1x when playing HLS videos

### ISSUE THREAD

**Issue by CMonterde** [RenderHeads/UnityPlugin-AVProVideo#1058]
When playing HLS videos with variable playback rate, the buffer stop growing when playback rate go over 1x.

If the playback rate is over 1x enough time to consume the current buffer the video pauses, buffer a bit, play again a bit, pauses, buffer a bit, ... .

When the playback rate is back to 1 or lower the buffer start growing again.

The problem trigger with a small increase of the playback rate, for example at 1.1x.

Unity 2020.3.13f1
OS: Windows 10, (1909 Compilation 18363.1916)
Plugin AVPro version: 2.3.0f1-ultra
Platform: windows standalone, using WinRT API,
Video format: HLS in mp4 format with 3 streams and 6 seconds chunks

**Comment by kahnivore** [comment]
Any chance we could get your stream to test with? You can send to unitysupport@renderheads.com with "1058" in the subject line or feel free to share here. 

We don't have any control over buffering behaviour on Windows, so there might not be much we can do to fix this issue. However, the streams I've tested with are all playing fine at 1.1x - 2.5x for example, so it would be useful to see why your stream is behaving differently.

**Comment by kahnivore** [comment]
Thanks for sending the streams. I still don't seem to have issues with playback rates under 2.5x. It seems mostly likely to be a Microsoft bug, where adjusting playback rate constantly can confuse the buffering system. 

Have you tried downloading the media first? Does this make a difference? 

I expect this is not an option, but using a Mac instead could be a workaround.

**Comment by AndrewRH** [comment]
This appears to be a limitation of Windows Media Foundation, so we aren't able to fix this.  We've added this to our 'known issues' documentation
