### ISSUE TITLE
Can't achieve 60fps

### ISSUE THREAD

**Issue by CraWea** [RenderHeads/UnityPlugin-AVProVideo#106]
**Describe the bug**
Attempting to play video files with 60fps maxes out at around 45fps (as reported in the Preview tab).
I have tried various video files (listed below), setting up new blank Unity projects using 3D and LWRP VR template, and also the Resample option (as suggested by Andrew). Even when I downscaled the video down to 128x144 I didn't see any improvement, which suggests that the source of the bottleneck is unrelated.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.5f1
 - AVPro Video version: 1.9.17 trail
 - Operating system version: Windows 10 (Version 10.0.17763 Build 17763)
 - Device model: i7-3770, GTX1060, Oculus Rift
 - Video specs (resolution, frame-rate, codec, file size):
    Some video files I have tested:
    - .mp4 h265 1280x1440 59.94 VBR 7Mbps (208MB file size)
    - .mp4 h264 128x144 59.94fps VBR 7Mbps Baseline 5.2 (36MB file size) 
    - .mkv h264 1920x1080 60fps High 4.2 (26MB file size - see download link below)

**To Reproduce**
1. Download this test file: https://drive.google.com/file/d/0BwxFVkl63-lETTVtaVV0LUVRZ1k/view?usp=sharing
2. Create new project in Unity 2019.1.5f1 (tried templates 3D and LWRP VR)
3. Create plane, and attach a new material with AVPro Unlit Opaque shader
4. Add and setup MediaPlayer and Apply To Material script
5. (Optionally, move the camera so that the plane displaying the video is not in the frustum and not rendered to the screen)
6. Look at the frame rate in the Preview tab of the MediaPlayer

**Screenshots**
![image](https://user-images.githubusercontent.com/8692159/60676154-b19d2300-9e6d-11e9-8024-dd9808536205.png)

**Videos**
https://drive.google.com/file/d/0BwxFVkl63-lETTVtaVV0LUVRZ1k/view?usp=sharing

**Comment by AndrewRH** [comment]
Having the MediaPlayer component open in the Inspector window in the Unity editor adds to the overhead quite a lot.  You should rather use the DebugOverlay component which will render the FPS into the Game window, and not have the MediaPlayer component selected.  That should improve the frame-rate?

**Comment by CraWea** [comment]
Indeed, you are correct: 
With the Preview tab open: ~45fps (~30fps in my LWRP scene)
With the Preview tab closed: ~58.5fps (60fps source)
The performance didn't seem to be impacted by the MediaPlayer component being open in inspector - it was just a matter of the Preview tab being maximized/minimized. 
Anyway, thanks for your help:)

**Comment by AndrewRH** [comment]
Yeah, we haven't figured out a way to update the Inspector tab without affecting performance.  You can also get some more perf if you run the app in exclusive fullscreen mode (in player settings).  
I'll close this ticket now.
Thanks,
