### ISSUE TITLE
How to set MediaPath url in MediaPlayer dynamically?

### ISSUE THREAD

**Issue by thesanketkale** [RenderHeads/UnityPlugin-AVProVideo#1060]
I want to set MediaPath to a url value obtained from a remote server. But the MediaPath variable in the MediaPlayer script is internal hence I cannot set it from a custom Monobehaviour. How do I set this media path of the video player dynamically from a script?

P.S. Asking it here as I couldn't find any documentation related to doing this.

**Comment by christianYS** [comment]
You want to set the MediaPath for loading a video? In this case, you need to call `MediaPlayer.OpenMedia()` passing in the video's url.
Examples are at https://www.renderheads.com/content/docs/AVProVideo/articles/usage-loading-media.html#scripting

**Comment by kahnivore** [comment]
@thesanketkale please let us know if our example above isn't clear, we are always open to improving our documentation.

**Comment by thesanketkale** [comment]
> You want to set the MediaPath for loading a video? In this case, you need to call `MediaPlayer.OpenMedia()` passing in the video's url. Examples are at https://www.renderheads.com/content/docs/AVProVideo/articles/usage-loading-media.html#scripting

Yes, this is it. Maybe, I was looking for a setter method for MediaPath in the docs, hence couldn't reach here. :)
Thanks for the quick tip.

**Comment by thesanketkale** [comment]
> @thesanketkale please let us know if our example above isn't clear, we are always open to improving our documentation.

The page explains it quite clearly. You docs are simple, clear and precise and the search works quite well (if we know what to search) :)
Keep it up, thank you!
