### ISSUE TITLE
Windows 7 crash 

### ISSUE THREAD

**Issue by beedulgi** [RenderHeads/UnityPlugin-AVProVideo#1062]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 20.3.23.f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): core
 - Operating system version: window7
 - Device model: pc
 - Video specs (resolution, frame-rate, codec, file size): 768x860, 30fps, .avi, 537mb

**To Reproduce**
1.빌드 후에 단지 비디오 플레이

**Logs** (System Information)
------------------
System Information
------------------
Time of this report: 1/12/2022, 10:13:13
       Machine name: SYSYSTEM
   Operating System: Windows 7 Ultimate K 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_gdr.130801-1533)
           Language: Korean (Regional Setting: Korean)
System Manufacturer: LG Electronics
       System Model: B55PV.AS5A11D
               BIOS: BIOS Date: 05/23/12 21:13:18 Ver: 04.06.05
          Processor: Intel(R) Pentium(R) CPU G620 @ 2.60GHz (2 CPUs), ~2.6GHz
             Memory: 4096MB RAM
Available OS Memory: 3990MB RAM
          Page File: 796MB used, 4216MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 32bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
          Card name: NVIDIA GeForce G210 
       Manufacturer: NVIDIA
          Chip type: GeForce G210
           DAC type: Integrated RAMDAC
         Device Key: Enum\PCI\VEN_10DE&DEV_0A60&SUBSYS_8086144D&REV_A2
     Display Memory: 2205 MB
   Dedicated Memory: 466 MB
      Shared Memory: 1739 MB
       Current Mode: 768 x 1280 (32 bit) (60Hz)
       Monitor Name: 일반 PnP 모니터
      Monitor Model: WV320FHD
         Monitor Id: XXX0000
        Native Mode: 1366 x 768(p) (59.790Hz)
        Output Type: HD15
        Driver Name: nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um
Driver File Version: 9.18.0013.1422 (English)
     Driver Version: 9.18.13.1422
        DDI Version: 10.1
       Driver Model: WDDM 1.1
  Driver Attributes: Final Retail
   Driver Date/Size: 3/15/2013 14:53:06, 17990800 bytes
        WHQL Logo'd: Yes
    WHQL Date Stamp: 
  Device Identifier: {D7B71E3E-4920-11CF-7372-8BA01FC2C435}
          Vendor ID: 0x10DE
          Device ID: 0x0A60
          SubSys ID: 0x8086144D
        Revision ID: 0x00A2
 Driver Strong Name: oem33.inf:NVIDIA_SetA_Devices.NTamd64.6.1:Section002:9.18.13.1422:pci\ven_10de&dev_0a60
     Rank Of Driver: 00E02001
        Video Accel: ModeMPEG2_A ModeMPEG2_C ModeVC1_C ModeWMV9_C 
   Deinterlace Caps: {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_PixelAdaptive 
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_BOBVerticalStretch 
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(UYVY,UYVY) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_PixelAdaptive 
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(UYVY,UYVY) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(UYVY,UYVY) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(UYVY,UYVY) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_BOBVerticalStretch 
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(YV12,0x32315659) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_PixelAdaptive 
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(YV12,0x32315659) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YV12,0x32315659) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YV12,0x32315659) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_BOBVerticalStretch 
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(NV12,0x3231564e) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_PixelAdaptive 
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(NV12,0x3231564e) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(NV12,0x3231564e) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(NV12,0x3231564e) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY DeinterlaceTech_BOBVerticalStretch 
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(IMC1,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(IMC1,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC1,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC1,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(IMC2,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(IMC2,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC2,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC2,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(IMC3,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(IMC3,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC3,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC3,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(IMC4,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(IMC4,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC4,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC4,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(S340,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(S340,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(S340,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(S340,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {6CB69578-7617-4637-91E5-1C02DB810285}: Format(In/Out)=(S342,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB}: Format(In/Out)=(S342,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(S342,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(S342,UNKNOWN) Frames(Prev/Fwd/Back)=(0,0,0) Caps=
       D3D9 Overlay: Supported
            DXVA-HD: Supported
       DDraw Status: Enabled
         D3D Status: Enabled
         AGP Status: Enabled

**Videos**
[If applicable, add a copy of your video or the URL](https://drive.google.com/file/d/1wXR3LioJOvFeqMih_kTd6qmnbDu51EB1/view?usp=sharing)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Which version number of AVPro Video are you using?

**Comment by beedulgi** [comment]
use Core Windows Edition

**Comment by beedulgi** [comment]
> 어떤 버전의 AVPro 비디오를 사용하고 있습니까?

코어 윈도우 에디션 사용

**Comment by beedulgi** [comment]
> Which version number of Core Windows?

Version 2.3.1 - 20 December 2021

**Comment by kahnivore** [comment]
Thanks. Does the crash happen if you build the Demo_MediaPlayer scene without editing it? 

Does it happen immediately after opening the application?

**Comment by beedulgi** [comment]
> 감사 해요. Demo_MediaPlayer 장면을 편집하지 않고 빌드하면 충돌이 발생합니까?
> no demos & docs folder import 

> 응용 프로그램을 연 직후에 발생합니까?
> yes

**Comment by AndrewRH** [comment]
I see that the video is in Hap format.

Could you share the crash log files please?

Also - I assume it's using DirectShow to do the decoding.  If not - please try switch the Video API to DirectShow (in MediaPlayer > Platform Specific > Windows).  See if that works.

Another thing you could try, is switching your graphics API to D3D9 (in Player Settings > Other > Automatic Windows Graphics API), just to see if that fixes it.

Thanks,

**Comment by beedulgi** [comment]
[Player.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7903739/Player.log)

use DirectShow option
D3D9 not found in Unity version: 20.3.23.f1

**Comment by AndrewRH** [comment]
Thanks for the log.  Could you please email unitysupport@renderheads.com mentioning this issue number (#1062) and we will email back a DEBUG build of the DLL.  This will generate a more detailed crash log, which you can share here so we can find the problem.

Thanks,

**Comment by beedulgi** [comment]
editor error 16..

[AVProVideo] No MediaReference specified
UnityEngine.Debug:LogError (object,UnityEngine.Object)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:401)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:369)
RenderHeads.Media.AVProVideo.MediaPlayer:Start () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:323)

[AVProVideo] No file path specified
UnityEngine.Debug:LogError (object,UnityEngine.Object)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:483)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:369)
RenderHeads.Media.AVProVideo.MediaPlayer:Start () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:323)


...

**Comment by beedulgi** [comment]
Playback is possible when using the debug plugin. but... It does not play when using for distribution. What's wrong..?

**Comment by beedulgi** [comment]
Playback is possible when using the debug plugin. but... It does not play when using for release. What's wrong..?

**Comment by kahnivore** [comment]
Could you please share the crash log from the debug build?

**Comment by beedulgi** [comment]
> Could you please share the crash log from the debug build?

debug build no crash

**Comment by AndrewRH** [comment]
that's strange

> > Could you please share the crash log from the debug build?
> 
> debug build no crash

how strange...
could you try upgrading to the latest version of AVPro Video (Version 2.3.3) to see if that helps?

Thanks,

**Comment by beedulgi** [comment]
debug version is 2.3.3, the update has already been made

**Comment by beedulgi** [comment]
Any solution?

**Comment by beedulgi** [comment]
debug 2.3.3 dll no crash,  official 2.3.3 dll crash

**Comment by beedulgi** [comment]
Do you have the codec I need?

**Comment by kahnivore** [comment]
What do you mean by 'the codec you need'? Not sure how the debug build didn't crash, but the official did.

**Comment by beedulgi** [comment]
ask for a refund
