### ISSUE TITLE
[2.2.3] Android caching support always returning false 

### ISSUE THREAD

**Issue by sbabski** [RenderHeads/UnityPlugin-AVProVideo#1063]
I am trying to add caching support for external streamed videos on for an experience on Oculus Quest 2. Calling `mediaPlayer.Cache.IsMediaCachingSupported` always returns false - I've tested on-device on both the Quest and an Android phone. 

Despite this, calling `mediaPlayer.Cache.AddMediaToCache` causes the expected behavior: progress increasing from 0 to 1 and a `CachedMediaStatus` of `Caching` followed by `Cached`. However, after opening this cached media, calling `mediaPlayer.Cache.IsMediaCached` also always returns false.

I'm not sure whether there are any additional setup I have to do to get caching to be supported, or whether this is an issue of the cache working as expected, but `IsMediaCachingSupported` and `IsMediaCached` reporting incorrect values.

The project uses external m3u8 videos like the following: https://media.tripp.com/hls/CE_Increased_Buffer/CE_Test_Increased_Buffer.m3u8
I have also tested with the following external mp4 video link: https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

 - Unity version: v2019.4.31f1 WindowsEditor
 - AVPro Video version: v2.2.3 (plugin v2.2.2f1-ultra)
 - Operating system version: tested on both Android 8 and Android 10
 - Device model: tested on both Galaxy S9 and Oculus Quest 2

**Comment by kahnivore** [comment]
This has now been fixed and will be in the next release, thanks!

**Comment by sbabski** [comment]
Thanks for the quick response!

Quick question for clarification - were those `mediaPlayer.Cache.IsMediaCached` and `mediaPlayer.Cache.IsMediaCachingSupported` values returning false incorrectly, or was the cached file actually not being used?

Also, when is the next version slated for release?

**Comment by kahnivore** [comment]
The values were returning false incorrectly. 

No exact date on release but we're hoping to get it out next week!

**Comment by RenderHeadsSte** [comment]
New release hopefully before the end of the week.

**Comment by sbabski** [comment]
Thanks for the fix! I tested with the new release and `mediaPlayer.Cache.IsMediaCachingSupported` is now returning true, as expected. 

However, I'm still running into the issue of `mediaPlayer.Cache.IsMediaCached` returning false when the piece of media in question is open, playing, and has a status of `CachedMediaStatus.Cached`. I'm still using the same specs and videos as above, and the Media Source of the Media Player is `Absolute Path Or URL`.

**Comment by sbabski** [comment]
Is there an expected release date for a fix for this?

**Comment by jasonleeasbahr** [comment]
Hi @AndrewRH, does this mean that AVPro Ultra has dropped support caching on Android?

**Comment by RenderHeadsSte** [comment]
No, caching is very much supported on Android.  Apologies for the slow response to your issue.

It appears that the method you refer to (IsMediaCached()) has not been filled in on any supporting platform.  Strange.  We will need to look into why it was left there in the interface.

To check if a video is cached you can use:

CachedMediaStatus GetCachedMediaStatus(string url, ref float progress)

The return you will get it is an enum that will tell you if the video is not cached, caching, cached, or failed.
