### ISSUE TITLE
How can I buy the license in Unity store, and get prior version of download, like v2.1.1? Or can I use the newest version license to activate the v2.1.1 trial version of AVProvideo plugin? 

### ISSUE THREAD

**Issue by sololi123** [RenderHeads/UnityPlugin-AVProVideo#1064]
**Question**
How can I buy the license in Unity store, and get prior version of download, like v2.1.1? Or can I use the newest version license to activate the v2.1.1 trial version of AVProvideo plugin?

**Comment by kahnivore** [comment]
Hi @sololi123 

Why exactly do you want 2.1.1? 

We do sometimes accommodate sending older versions to users with a valid Unity invoice, but prefer to find solutions to keep users up to date.

**Comment by kahnivore** [comment]
Closing due to lack of response.
