### ISSUE TITLE
Files seem to be installed all over the place in differnet folders

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#1065]
Hello,

Im using one version of your AVProVideo in my Unity project and i want to switch to an earlier version of your video player.

However your product files seem to be installed all over the place with different names and libraries in different folders scattered everywhere, how will i know which files to delete and which ones to keep. I cant tell which files are yours and which files belong to other plugins.

Would it be a good idea for you to keep all your files under a single root folder, and then create other folders under that?

Thanks

**Comment by kahnivore** [comment]
The AVPro Video files should all be contained in Assets -> AVPro Video. 

Which version of AVPro Video are you using and what reason do you have for switching to an earlier release?
