### ISSUE TITLE
Need old version of AVProVideo

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#1066]
Hello,

Im trying to find the TRIAL Unity package for an old version 1.11.4t (scripts V1.10.1) of AVPro Video.

Can someone give me a link to that please?

Thanks

**Comment by kahnivore** [comment]
You can find the package for 1.11.4 trial [here](UnityPlugin-AVProVideo-v1.11.4-Trial.unitypackage). 

See all releases [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases?page=1).
