### ISSUE TITLE
Player crashes if given  URL to mp4 video where the URL doesnt end in .mp4

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#1067]
**Describe the issue**
Player crashes if i give it a URL to a mp4 video where the URL doesnt end in .mp4

**Your Setup (please complete the following information):**
 - Unity version: 2020.3
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): latest trial from your website
 - Operating system version: Oculus
 - Device model: quest 2
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. play an mp4 video at a URL that doesnt end in .mp4
2. 
3.

**Comment by kahnivore** [comment]
You need to reference a direct path to the video. If the path is incorrect, it should error, not crash. 

Could you share the URL you are testing with?
