### ISSUE TITLE
[2.3.1] No implementation found for void com.renderheads.AVPro.Video.Manager.nativeDestroy()

### ISSUE THREAD

**Issue by ClaineLe** [RenderHeads/UnityPlugin-AVProVideo#1069]
软件：Unity2020.3.12f1
平台：Android
版本：AVPro Video - Core Edition (核心版) v2.3.1
使用接口：mediaPlayer.ForceDispose()后，出现异常报错。报错如下：
AndroidLogcat：
No implementation found for void com.renderheads.AVPro.Video.Manager.nativeDestroy(int) (tried Java_com_renderheads_AVPro_Video_Manager_nativeDestroy and Java_com_renderheads_AVPro_Video_Manager_nativeDestroy__I)

但是，使用2.1.5版本，进行Demo测试，一切正常。
请求官方反馈一下。

GOOGLE TRANSLATE (by RenderHeads):

Software: Unity2020.3.12f1
Platform: Android
Version: AVPro Video - Core Edition (Core Edition) v2.3.1
After using the interface: mediaPlayer.ForceDispose(), an exception error occurs. The error is as follows:
AndroidLogcat:
No implementation found for void com.renderheads.AVPro.Video.Manager.nativeDestroy(int) (tried Java_com_renderheads_AVPro_Video_Manager_nativeDestroy and Java_com_renderheads_AVPro_Video_Manager_nativeDestroy__I)

However, using version 2.1.5, for Demo testing, everything works fine.
Ask for official feedback.

**Comment by pumpkye** [comment]
MediaPlay.OnDestroy() also make this problem

2.2.4 is fine

**Comment by kahnivore** [comment]
@RenderHeadsSte is this still an issue (see #1044)

**Comment by RenderHeadsSte** [comment]
#1044 has a fix offered in the next release (> v2.3.1)

**Comment by RenderHeadsSte** [comment]
Please report bugs in English @ClaineLe, else we will have to rely on google translate, which may lead to important details being lost.

**Comment by pumpkye** [comment]
The translation is correct

**Comment by ClaineLe** [comment]
> Please report bugs in English @ClaineLe, else we will have to rely on google translate, which may lead to important details being lost.
----------------------------------------------------------------------------------------------------------------------------
What I want to express:
So when is the next time?
Because the project will be released in the near future, if it is too late, the historical version will be used.（Such as: v2.1.5）
Then a new question arises, where can the historical version be downloaded?
----------------------------------------------------------------------------------------------------------------------------
Great, if a new version is released in the near future, my problem will be solved. thanks.
I just bought the AVPro yesterday, so no previous version.

**Comment by ClaineLe** [comment]
> 
3Q, old brother

**Comment by ClaineLe** [comment]
> The translation is correct

3Q, old brother

**Comment by ClaineLe** [comment]
> The translation is correct

thanks

**Comment by kahnivore** [comment]
Are you having this problem with version 2.3.1?

**Comment by ClaineLe** [comment]
> Are you having this problem with version 2.3.1?

yes。

**Comment by kahnivore** [comment]
2.3.2 has been released. 

Please let us know if this solves your issue. 

Thanks.

**Comment by pumpkye** [comment]
2.3.2 crash when destroy MediaPlayer
![crash](https://user-images.githubusercontent.com/51112737/150515714-574a9da8-fd3b-4e2c-aa4f-9a6242d8897c.png)

**Comment by RenderHeadsSte** [comment]
Reproduced and fixed.  Apologies.

**Comment by pumpkye** [comment]
> @pumpkye v2.3.3 has just been released. The above issue is hopefully addressed now. Do let us know.

It works fine
