### ISSUE TITLE
Mipmaps on Android

### ISSUE THREAD

**Issue by rarild** [RenderHeads/UnityPlugin-AVProVideo#107]
There is already a checkbox option to generate mipmaps on Windows. I'm looking for something similar for Android.

**Comment by asierras** [comment]
Any news about this? Thank you!

**Comment by AndrewRH** [comment]
We may add this natively on Android, but soon we plan to have a 'resolver' feature which will include mip-map generation support on all platforms.

**Comment by ts01022171** [comment]
Hi, Is this solved?

**Comment by Chris-RH** [comment]
No, this enhancement is not supported yet.

**Comment by ts01022171** [comment]
Is this feature in the current plan?

**Comment by Chris-RH** [comment]
Its not on our current roadmap.  Its the type of feature that might be
added if enough people request it or if we might find it useful for
something that we are working on.

**Comment by MorrisRH** [comment]
Support for generating mipmaps has been added and will make it into the next release (version 3.1.3).

**Comment by Chris-RH** [comment]
AVPro Video version 3.1.3 has been released.
