### ISSUE TITLE
Upgrading from singe-platform edition 

### ISSUE THREAD

**Issue by Angellourido** [RenderHeads/UnityPlugin-AVProVideo#1072]
**I have the core androide edition and I would like to buy the windows edition, I see that there is a core edition  for 357.33 E* but as already pay the core edition how I can buy the coreedition with the good price ?
Thanks*

**Comment by kahnivore** [comment]
Hi @Angellourido 

We would recommend upgrading from the Core Android edition to the Full Core edition, which includes the Windows edition. We have an [upgrade path](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#upgrade-paths) set up for this so you will not repay for the portion you already spent on the Android edition. 

Please note you must be logged in with the same user and organisation that owns the AVPro Video to receive this discount automatically on the Asset Store. 

Thanks!

**Comment by Angellourido** [comment]
Thanks I just upgraded to core edition

I have one problem is that I lost the connection of the videos on the scene... It's like the path is not good,

I don't understand what happen.

I put my videos in the external folder the same as usual in the android headset  Oculus Quest  en data/company/files

Ssmetjing in the pc but in the game view the videos didn't appear

It's like the link was lost

The path is the same

Path related to streaming assets folder

Thanks for your help

**Comment by kahnivore** [comment]
Hard to say with more information. Is the path working on the headset but not on your PC? 

If the media is in streaming assets it will be a different path to the external storage of your Quest. 

Could you take a screenshot of your path settings on the MediaPlayer?
