### ISSUE TITLE
[iOS] Video texture paused when scrolling swift UI 

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1073]
Our project is using UAAL. (Unity3D + Native)
Video texture paused when scrolling Swift UI.

 - Unity version: 2019.4.15f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.3.1
 - Operating system version: iOS 14.6
 - Device model: iPhone 12
 - Video specs (resolution, frame-rate, codec, file size): 

Video :
https://drive.google.com/file/d/1kj3t7MDaB2jOme9g5HSBNL4ZXsDKITXC/view?usp=sharing

**Comment by dw8869** [comment]
AppleMediaPlayer.cs
_state.status.HasUpdatedTexture() value is false when scrolling.

**Comment by MorrisRH** [comment]
Think I know what is causing this and have added a fix for it. I have no reproducible instance though so might have this wrong. If you're able, could you share your project or a minimal project that reproduces it? If so, please send it to unitysupport@renderheads.com using the topic of this issue as the subject.

**Comment by dw8869** [comment]
@AndrewRH

**Comment by AndrewRH** [comment]
2.4.0 has been released and includes a fix for this issue

**Comment by dw8869** [comment]
@AndrewRH 
Thanks, this issue is not reproduced.
