### ISSUE TITLE
[android] Investigate adding FFmpeg extension 

### ISSUE THREAD

**Issue by 3493000** [RenderHeads/UnityPlugin-AVProVideo#1076]
How can I use an extended codec such as ffmpeg to parse AC3 format audio？
No matter whether I check the Prefer Software Decoder option or not, there is no effect, but the sound can be parsed under the windows unity editor.

![image](https://user-images.githubusercontent.com/43593494/150923600-c1737779-30e0-4c43-8746-69ecb5e9a095.png)

Unity version: v2020.3.181f1 WindowsEditor
AVPro Video version: v2.3.1 (plugin v2.3.0f1-core)
Operating system version:Android 10
Device model: SHARK KLE-A0
Video specs

**Comment by 3493000** [comment]
![image](https://user-images.githubusercontent.com/43593494/150924257-0212f0a6-e1fa-4ab0-abf0-558a6fefedd7.png)
I compiled and integrated the two decoder aar packages of vp9 and opus into the unity plugin folder. It seems that the apk that I typed has no effect.
![image](https://user-images.githubusercontent.com/43593494/150924595-4b5b83b0-6bd5-441c-a162-cb0ff1294aaf.png)

**Comment by 3493000** [comment]
@nathanlance @AndrewRH @RichRH @ShaneRH

**Comment by kahnivore** [comment]
Hi @3493000 

AC3 is not supported by any Exoplayer extensions, except FFmpeg. We currently have no way of adding this, although would be something useful to look into.

**Comment by MorrisRH** [comment]
Closing this issue as ee have no plans to integrate ffmpeg into the plugin due to issues with licensing.
