### ISSUE TITLE
Unable to playback 8k video on iPhone 12

### ISSUE THREAD

**Issue by mypanora** [RenderHeads/UnityPlugin-AVProVideo#1079]
**Describe the issue**
Using AVPRO, I am testing a video on demand with the WOWZA streaming engine. Everything works fine on Android, but it does not on ios. It gets me error messages.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3..25f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.3 ultra
 - Operating system version: ios
 - Device model: ipone 12
 - Video specs (resolution, frame-rate, codec, file size): 8K, H264, AAC, 7 GByte

**To Reproduce**
1. Using the script below, play the video from the URL below.

2. Script : avProPlayer.OpenMedia(new MediaPath(_url, MediaPathType.AbsolutePathOrURL), autoPlay: true);
avProPlayer.Control.Seek(0);

3. Video URL : https://d3envcwdbtioa2.cloudfront.net/vodcdn/_definst_/mp4:preview_13.mp4/playlist.m3u8

**Logs**
See the screenshot shown below.

**Screenshots**
<img width="1401" alt="screen save" src="https://user-images.githubusercontent.com/98515368/151319328-d5fb5a72-3de0-4f08-ba44-7bd4fffe7fae.png">

**Videos**
https://d3envcwdbtioa2.cloudfront.net/vodcdn/_definst_/mp4:preview_13.mp4/playlist.m3u8

**Comment by kahnivore** [comment]
Seems like 8K H264 is beyond the capabilities of the hardware decoder of an iPhone 12 - the stream plays fine on an iPhone 13 Pro.
