### ISSUE TITLE
MAGIC LEAP : ERRORS

### ISSUE THREAD

**Issue by ViewerReady** [RenderHeads/UnityPlugin-AVProVideo#108]
We are running into issues while trying to make an alpha layer mp4 using AVPRO.  Right now the example mp4 it only shows the AVPRO logo (im assuming that is an error) additionally it only renders in the left eye which is a problem we’ve also seen with JMO’s TOONY COLORS PRO, and a particle fx asset pack, the fix for those was that shader needed to work with single pass rendering and the developers sent us a fix.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.0f2
 - AVPro Video version: up to date
 - Operating system version: Windows 10, and Mac OS 10.14.3
 - Device model: Magic Leap Creator Edition (headset)
 - Video specs (resolution, frame-rate, codec, file size): 512x1024 (top bottom) and 1024x512 (side by side)

**To Reproduce**

**Logs**
n/a

**Screenshots**
n/a

**Videos**
n/a

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi @ViewerReady 

AVPro Video does not support the Magic Leap device.

Thanks,

**Comment by AndrewRH** [comment]
This issue will be closed soon if there is no further activity
