### ISSUE TITLE
DllNotFoundException: AVProVideo

### ISSUE THREAD

**Issue by amogh-altoura** [RenderHeads/UnityPlugin-AVProVideo#1080]
**Describe the issue**
 We are getting DllNotFoundException: AVProVideo when trying to play video from local storage in Mac platform.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.21f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 1.11.6
 - Operating system version: macOS Big Slur
 - Device model: MacBook Bro (Mid 2014)
 - Video specs (resolution, frame-rate, codec, file size): mp4, 10 mb

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Are you getting any xcode errors?

**Comment by amogh-altoura** [comment]
@kahnivore  The platform is not iOS. It is for MacOS.
No errors while building for Mac.

**Comment by MorrisRH** [comment]
Check to see if the quarantine flag has been set on the plugin bundle.
You can do this using the terminal. cd to the folder containing the bundle then type:
```xattr AVProVideo.bundle```

If you see ```com.apple.quarantine``` in the output then the macOS gatekeeper has quarantined it and it won't be loaded (usually caused by downloading or copying from a network share).

You can remove it with the following command:
```xattr -d com.apple.quarantine AVProVideo.bundle```

**Comment by amogh-altoura** [comment]
com.apple.quarantine was not there in the output.

**Comment by MorrisRH** [comment]
This is probably a code signing issue then. Version 1 of AVPro Video was never notarised as this was not required when we released it. We fully notarise version 2.x of the plugin to prevent this kind of issue and would recommend that you upgrade to 2.x as we no longer support version 1.

Unity provides documentation for code signing here: https://docs.unity3d.com/2021.2/Documentation/Manual/macos-building.html#code-signing

And Apple has some documentation here: https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html and here: https://developer.apple.com/library/archive/technotes/tn2206/_index.html

As Unity has to code sign an application it has built you may be able to take advantage of this. Build an application (use one of our demo scenes as an example), then replace the plugin in your project with the one from inside the build application and restart Unity. If this has worked you should no longer see DllNotFound exceptions being thrown.
