### ISSUE TITLE
AVPro Video: Adding AVPRO_PACKAGE_TIMELINE to player defines results in errors

### ISSUE THREAD

**Issue by Sp1d3rbite** [RenderHeads/UnityPlugin-AVProVideo#1081]
I am having the exact same issues with the 2.3.3 version of AVPro as the issue from the url below.
The 'fix' files are identical with the ones in the 2.3.3 version so those files did not solve the resulting errors.

[Link to issue #591](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/591)

**Comment by kahnivore** [comment]
What Unity version are you using?

**Comment by AndrewRH** [comment]
Could you paste the errors you're seeing?

**Comment by AndrewRH** [comment]
Hmm I just followed the install steps listed [here](https://www.renderheads.com/content/docs/AVProVideo/articles/component-timeline-playables.html), and it worked fine for me - no errors...

**Comment by Sp1d3rbite** [comment]
Thank you, I got it figured out and was just about to post it!
It was indeed step 3 of the install steps you posted Andrew.
I was unaware that the project I was in was using that extension so I hadn't looked there.

It might be handy to either move it up on the page or put a hint to it in the FAQ or troubleshooting part of the documentation.
