### ISSUE TITLE
Problem when building in Oculus quest 2 

### ISSUE THREAD

**Issue by SouheilHous** [RenderHeads/UnityPlugin-AVProVideo#1085]
Hello everyone , Im trying the last trail version of AVPro with Oculus quest 2 and I have a problem .
Currently Im getting a link of live streaming from youtube link then playing it with the AVPro path/Url solution media player .
all work in the editor but in the Oculus quest 2 the game run but the screen remains blank . and nothing appears also I hear nothing from the game itself . so either there is an error in getting data or the plugin did not run at all .
Currently here is the details and what I did :
I use unity 2020.3.25
I use Oculus quest 2
I try to build with this settings like you advice everyone :
![image](https://user-images.githubusercontent.com/53268382/151857221-bc03f908-598f-4587-a0f6-b30c0378dcb2.png)I have the plugins installed and also I modified the grade file like in description
Stil I have those errors in the device log

AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager

java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager

![image](https://user-images.githubusercontent.com/53268382/151857186-2277f4ec-55c9-4336-af6e-5770fc57d553.png)
Im not sure about the main problem here but I would really appreciate if there is a solution for this
thank you everyone .

**Comment by kahnivore** [comment]
Which version of AVPro Video are you using?

**Comment by SouheilHous** [comment]
> 
I think its this version : 
AVPro Video v2.3.3 - 21 January 2022

**Comment by kahnivore** [comment]
Could you provide a [full logcat](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs)? Seems like the plugin has not loaded. 

Also, are you using Minify?

**Comment by SouheilHous** [comment]
No I dont think so Im using only simple path streaming service HSL one . 
![image](https://user-images.githubusercontent.com/53268382/151955785-32f6a5fb-2c01-4a61-91ab-de6a769ecba1.png)
![image](https://user-images.githubusercontent.com/53268382/151955821-3b8ec605-ae56-4e1c-8cba-53ca7d6e3733.png)
what I do is just I set the link after I get it from YouTube and then play the video . 
![image](https://user-images.githubusercontent.com/53268382/151956190-38b917da-e343-4e50-8d47-b6cc3100abdd.png)
in editor all work fine the video play but in android I have those errors . 
I will use the Full logcal later and send you the log then !

**Comment by RenderHeadsSte** [comment]
Is that an HLS video stream you are trying to play?  If your video URL does not end in the m3u8 extension, then you will likely have to force the file format.

**Comment by RenderHeadsSte** [comment]
Oh, I see 'index.m3u8' at the top of your screen shot.  Can you send the full URL to the video please?

**Comment by SouheilHous** [comment]
Im really sorry for the Delayed reply so here is the link that I use as live stream and it work in the editor : 
https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1643844245/ei/Nb76Ye_aE6aUvcAP_b2H2AM/ip/153.156.171.234/id/HpdO5Kq3o7Y.3/source/yt_live_broadcast/requiressl/yes/hfr/1/playlist_duration/30/manifest_duration/30/maudio/1/vprv/1/go/1/nvgoi/1/keepalive/yes/fexp/24001373%2C24007246/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cplaylist_duration%2Cmanifest_duration%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AOq0QJ8wRgIhAJxS7zhry4JEidNE31J5wCYfU4s6HaKqPbBk2xgQGLvjAiEA1pb9tqxj-EJgyVfX-YiGVbvcsjLxc1WjqKVGGGpSPUY%3D/file/index.m3u8
also here is the log from oculus log tool 
[odh_logs_2022-02-02 17.16.01.281.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7988703/odh_logs_2022-02-02.17.16.01.281.txt)

and here is the log from mLogcat : 
[OculusLogCAt.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7988701/OculusLogCAt.txt)

**Comment by SouheilHous** [comment]
> Oh, I see 'index.m3u8' at the top of your screen shot. Can you send the full URL to the video please?

any idea why this happens please ? sorry I did reply late

**Comment by SouheilHous** [comment]
> Oh, I see 'index.m3u8' at the top of your screen shot. Can you send the full URL to the video please?

@RenderHeadsSte @kahnivore  , any solution please for this

**Comment by SouheilHous** [comment]
@RenderHeadsSte @kahnivore  , sorry to ask again , can you guide me on this please ?

**Comment by SouheilHous** [comment]
Im panning to get the asset but I need to choose soon

**Comment by RenderHeadsSte** [comment]
The URL you have provided does not work.  I get a 403 error.

> Also, are you using Minify?

Can you answer this please?

Have you tried a known working HLS stream?  https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8

**Comment by SouheilHous** [comment]
@RenderHeadsSte  I just found the minify was on on release yes and here is the new link , better test it soon : 
https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1644602898/ei/slEGYsyQENWcvcAP_aSsYA/ip/175.177.46.122/id/HpdO5Kq3o7Y.3/source/yt_live_broadcast/requiressl/yes/hfr/1/playlist_duration/30/manifest_duration/30/maudio/1/vprv/1/go/1/pacing/0/nvgoi/1/keepalive/yes/fexp/24001373%2C24007246/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cplaylist_duration%2Cmanifest_duration%2Cmaudio%2Cvprv%2Cgo%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIgDY3Nl-PoAN8E5pClvAJhQH24_kymJv0VFZTVvVk9o7gCIQCIDSWj6msbdocwcEwfcD7imxuPqaSXT3mDTeEgh19bEQ%3D%3D/file/index.m3u8
otherwise will try now without minifiy

**Comment by SouheilHous** [comment]
I tried exoplayer but the m3u8 videos are not working also in that asset

**Comment by kahnivore** [comment]
Please see the notes in our docs on [how to use Minify with AVPro Video.](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#proguard-minify)

**Comment by RenderHeadsSte** [comment]
It will be minify.  As @kahnivore says, see the notes.  Do let us know if this sorts the problem for you :)

**Comment by SouheilHous** [comment]
Finally It works , we can call this closed , thank you both really it works fine and I didnt check minify just now so that was the problem !!

**Comment by RenderHeadsSte** [comment]
Great to hear.  Thanks for updating us.  Best of luck with your project.
