### ISSUE TITLE
Positional Audio not working on Mac OSX or iOS when the MediaPlayer source is HLS stream

### ISSUE THREAD

**Issue by ngz82** [RenderHeads/UnityPlugin-AVProVideo#1086]
**Describe the issue**
We have setup a number of Audio Output components throughout our scene along with Audio Sources, these are attached to 3D models of Speakers to represent real world positional audio. 
On scene load the Media Player is instantiated and the references are set within the Audio Output components.
The Media Player loads the URI of an adaptive bitrate stream (either video+audio or just audio only).
Everything works as it should in Editor/Windows (and I suspect Android from previous tests) , however both in Editor on Mac OSX and iOS builds the audio behaves like System Direct, there is no volume change when moving closer and farther from the audio sources.
If I take the original source video (before it was encoded to HLS format) and use it in the StreamingAssets folder locally on the Mac Editor and iOS builds everything behaves as it should.

I have tested with both our own content and also standard HLS test videos from https://players.akamai.com/players/hlsjs e.g Big Buck Bunny.
The Audio Output components are having the Media Player assigned at run time on Scene load. 

**Your Setup (please complete the following information):**
 - Unity version: **2019.4.33f1**
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  **Core 2.3.3**
 - Operating system version: **OSX 11.3.1 and iOS 15.2**
 - Device model: **Macbook Air (M1, 2020) , iPhone SE 2020** 
 - Video specs (resolution, frame-rate, codec, file size):  **4082x2160, H264, AAC, 35.3Mb** - Works fine when loaded locally as source MP4, fails when the same content (re-encoded for HLS via FFMPEG is played).

**To Reproduce**
1.  Setup a number of Audio Output / Audio Sources attached to Gameobjects throughout a scene, Set  Spatial Blend to 3D and check Supports Positional Audio
2. Load any HLS stream with AAC audio.
3. Move the Audio Listener around the scene towards the Audio Sources and observe there is no change at all in Editor on OSX and on iOS builds. 

**Logs**
Nothing of note in the logs however I did note that the Audio Output component shows the below in the Media Audio section:
Local File (works):
**Media Audio**
Channels: 2
FrontLeft, FrontRight
Buffered: 42ms

and on the HLS stream when it fails:
**Media Audio**
Channels: 0 
Unspecified
Buffered: NaNms

This is what lead me to try various different content I could find online but it didn't seem to help.

**Comment by kahnivore** [comment]
Thanks for the detailed report. We will look into this soon.

**Comment by MorrisRH** [comment]
I'm afraid we cannot route audio from HLS through to Unity. This is a limitation of Apple's AVFoundation framework so there is nothing we can do about this at this time.

**Comment by ngz82** [comment]
Thanks for getting back to me so quickly.

Can you elaborate any further about this limitation?
Does the issue lie in the ability to route HLS streamed audio into Unity or
something else?

In our particular case we are not so much concerned about mapping unique
channels to audio output/sources etc (even though that would be nice), it
really is ultimately adjusting the volume based off distance to the audio
source.
Without knowing the complexities under the hood I would have thought if the
audio is routed to Unity then adjusting the volume according to the world
space position of the audio listener would be achievable?

P.s. I didn't see anything about this in the docs, if it's not in there I'm
sure it would help others to add a note about this limitation as we spent
considerable time trying to make it work, thinking it was something on our
end.

Thanks for your help and the great product you have built.

**Comment by MorrisRH** [comment]
We use MTAudioProcessingTap to extract the audio and route it through to Unity. This in turn requires using AVAudioMix and attaching it to the current player item. Sadly this is where the process breaks down as AVAudioMix does not support HLS media. The documentation for AVAudioMix states the following (available [here](https://developer.apple.com/documentation/avfoundation/avplayeritem/1388037-audiomix)):
>An audio mix can only be used with file-based media and is not supported for use with media served using HTTP Live Streaming.

**Comment by ngz82** [comment]
Thanks for the explanation :)

Out of interest do you expect HLS streamed positional audio to work in
WebGL? I know you don't officially support it anymore, just interested to
know in theory ( outside of the usual WebGL limitations) if you think it
may work before we embark on testing it out.
Thanks again!

**Comment by MorrisRH** [comment]
I'm afraid the WebGL plugin has no support for playing audio through Unity.
