### ISSUE TITLE
How to play video on specific mesh

### ISSUE THREAD

**Issue by syedali1621** [RenderHeads/UnityPlugin-AVProVideo#109]
I want to play avpro media player video on vuforia image target i am trying to play video on vuforia image target mesh or on 2d texture but facing problems can you please help me ?
i want AR video play look like below.
https://youtu.be/buhkl1Glxzk

Thank you

**Comment by AndrewRH** [comment]
Hi,
Please take a look at the 3DMapping demo scene.  It uses the ApplyToMesh/ApplyToMaterial components to apply a video to a mesh.
Thanks,

**Comment by syedali1621** [comment]
it helped me thank you.
