### ISSUE TITLE
Multiple video playback issues in one MediaPlayer on Android

### ISSUE THREAD

**Issue by micromang** [RenderHeads/UnityPlugin-AVProVideo#1090]
**Describe the issue**
I tested the trial version before purchasing this asset for my project, then I found an issue.
I played videos through a single MediaPlayer in the Android environment. First, one video is played in MediaPlayer, and then the video is closed during play and another video is played. At this time, intermittently, the frame screen of the previous video appears in an instant, and then the second video is played. (I tested it several times, play-switching between the two videos.)
I tested on two builds: Windows standalone and Android builds. There is no problem in the Unity Editor and Windows standalone, the problem only occurs in Android builds. This happens regardless of whether the Video API is Exo Player or Media Player.
Could this problem occur when opening and playing multiple videos sequentially in one MediaPlayer in an Android environment?

**Your Setup (please complete the following information):**
 - Unity version: **2020.3.24f1**
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): **2.3.3 trial**
 - Operating system version: **Windows10**
 - Device model: **bluestacks5 (Android emulator for PC)**
 - Video specs (resolution, frame-rate, codec, file size): **mp4 /1560x720 (or 1280x720) / 30fps / 50 ~ 180MB**

**To Reproduce**
1. Open media A from StreamingAsset path (call MediaPlayer.OpenMedia(/*media A file path*/))
2. Close media A. (by MediaPlayer.CloseMedia())
3. Open media B from StreamingAsset path (call MediaPlayer.OpenMedia(/*media B file path*/)

**Comment by kahnivore** [comment]
Have you tried this on an Android device? Or just the emulator?

**Comment by micromang** [comment]
@kahnivore Hi, currently, there is no Android device for testing, so I only tested it on an emulator.

**Comment by kahnivore** [comment]
Not sure re emulator but seems to work fine on Redmi Note 9T. 

Does the same issue occur if you just set the MediaPlayer to open the next video without closing the first one? 

Does the issue occur in the PlaylistMediaPlayer Demo? (This would be switching between two MediaPlayers)

**Comment by micromang** [comment]
> Does the same issue occur if you just set the MediaPlayer to open the next video without closing the first one?

Yes, the same occurs.


> Does the issue occur in the PlaylistMediaPlayer Demo? (This would be switching between two MediaPlayers)
 
I ran the PlaylistMediaPlayer Demo with transitions turned off in the same environment. Yes, the same thing happens. Even the way the two players switch is slow, the problem is more clearly visible.

**Comment by micromang** [comment]
@kahnivore The problem was only with the emulator. I tested it on some Android devices, it did not occur. :)

**Comment by kahnivore** [comment]
Thanks for letting us know. We will look into Bluestacks5 and see if this is something we can resolve easily.
