### ISSUE TITLE
1061 issue was closed and created again.

### ISSUE THREAD

**Issue by SecretTonto** [RenderHeads/UnityPlugin-AVProVideo#1091]
Describe the issue
1061 issue was closed and created again.
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1061
@kahnivore 
As I told you last time, I added a reproduction video and a full log.

Spec
Unity version: 2019.4.15f1
AVPro Video version (number and edition (core): 2.3.1
Operating system version: Android OS 10, 11
Device model: Galaxy Z Fold3 5G_SM-F926N (11.0.0)_5G / Galaxy S21 5G_SM-G991N (12.0.0)_5G

Logs
https://drive.google.com/file/d/1kWbk47tpkiQlJhsN6TbOg0nur-Nxw8_0/view?usp=sharing

Videos
https://drive.google.com/file/d/1bwGPiGsgjMz-Sp8Tpp2qGpRXkRZ9jHgv/view?usp=sharing

**Comment by kahnivore** [comment]
Closing this to continue correspondence on original issue
