### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/SimpleExoPlayer$VideoListener;

### ISSUE THREAD

**Issue by vincentbylmh** [RenderHeads/UnityPlugin-AVProVideo#1096]
use avpro plugin to play video in android emulator，play fail，error is java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/SimpleExoPlayer$VideoListener;
hope someone else can help me

**Comment by kahnivore** [comment]
Which emulator are you using? Does the error occur when using one of the demo scenes? 

Also, does the error occur when building to an Android device?

**Comment by vincentbylmh** [comment]
> 
thanks,I have solved this problem.
packaging problem when building to an android platform

**Comment by kahnivore** [comment]
Glad you've solved it. What do you mean by packaging problem?

**Comment by vincentbylmh** [comment]
> Glad you've solved it. What do you mean by packaging problem?
when building to an apk occur some error, i fix the build errors。

**Comment by HeQuanLi** [comment]
> > 
> 
> thanks,I have solved this problem. packaging problem when building to an android platform

Hello, how did you solve it? I also encountered the same problem
