### ISSUE TITLE
[Android] OES shader with alpha packing support

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [RenderHeads/UnityPlugin-AVProVideo#1097]
**Is your feature request related to a problem? Please describe.**
The project I'm working on is heavily video-centered, but it is in 2D and pretty much only consists of UIs. It would be nice to get the OES speed boost. There only seems to be an OES shader with alpha packing support that can be applied to regular meshes. However, there isn't one for the UI.

**Describe the solution you'd like**
Add a UI shader utilizing the OES path on Android, with alpha packing support.

**Describe alternatives you've considered**
I thought about making a custom shader for this, but this really feels like it should be included in the package.

**Additional context**

**Comment by Ste-RH** [comment]
This enhancement has been added to AVPro Video v2.5.2
