### ISSUE TITLE
[MacOS] Buffering settings don't have effect

### ISSUE THREAD

**Issue by christianYS** [RenderHeads/UnityPlugin-AVProVideo#1098]
**Describe the issue**
MacOS specific platform options "**Preferred forward buffer duration**" and "**Play without buffering**" seem to not have any effect.
Over bad internet connection, or under the MacOS network link conditioner, the videos stall until some undetermined amount of frames have been buffered.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.19
 - AVPro Video version: 2.4.0 enterprise
 - Operating system version: MacOS 12.1
 - Device model: MacBook Pro (16-inch, 2021) with chip Apple M1 Pro
 - Video specs: H.264 .mp4 video downloaded from URL (https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_10MB.mp4)

**To Reproduce**
1. Import AvPro package and open Demo_MediaPlayer scene
2. Set one or both of the following MacOS settings in the MediaPlayer component:
    a.  Preferred forward buffer duration to some value > 0 (for example: 2)
    b. Play without buffering to ON
3. Use a video url of approximately 10Mb size (see above for the link)
4. Enable the Network Link Conditioner to a slow setting (I used 4Mbps)
5. Play

Here's a screen recording. 
https://user-images.githubusercontent.com/25147502/153322339-018fba64-8737-4ed1-ac5f-3fca80918860.mp4
I made an overlay that just prints some debug info on top of the video. You can see that the video is stalled until it buffers 6 seconds, regardless of the settings set in MediaPlayer. Repeating the experiment from a build results in the same outcome. On request I can send the demo project.

**Comment by MorrisRH** [comment]
I'm still investigating but it does look like those settings only affect HLS media. Unfortunately Apple's documentation doesn't explicitly state what media types the settings apply to so this is all based on my own observations.

**Comment by christianYS** [comment]
Thanks for looking into this. Can I ask what native API is used to load the video? We're noticing a suspiciously high rate of **stalled** events even when downloading videos with a fast wifi network, so I'm trying to nail down what is causing the slowdown. 
Does the native API use byte-range requests to download a non-HSL video?
