### ISSUE TITLE
MediaPlayer is not rendering properly the 360 degree video on Windows 10

### ISSUE THREAD

**Issue by lpmourato** [RenderHeads/UnityPlugin-AVProVideo#1099]
**Describe the issue**
The windows application its playing 360 degree video with leg/delay/latency.

**Your Setup (please complete the following information):**
 - Unity version: Unity 2018.4.36f1 (64-bit)
 - AVPro Video version 2.4.0 core
 - Operating system version: Windows 10
 - Device model: Dell inspirion (Core i5)
 - Video specs GeForce 820M 
 - All the videos are available locally

**To Reproduce**
1. I have an application that plays 360 degree videos. And its possible to move to next video.
2. I'm sharing the same MediaPlayer (RenderHeads.Media.AVProVideo) to play the videos.
3. To play next video, I do:
`videoPlayer.OpenMedia(new MediaPath(path,
                                MediaPathType.AbsolutePathOrURL), autoPlay: true);`
4. I was using the AVPro demo version 2.3.x and it was working good. The issue started after upgrade my license to Core Edition.
5. If only play the video by setting up directly in the MediaPlayer gameobject in Unity, it plays with good quality, but, if I do the step 3,  the video gets odd like it was been streamed. 
6. If I revert my plugin the the demo version, it works as well.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Do you perhaps have a screenshot/video that demonstrates the issue?

Do you have mipmaps enabled?

**Comment by lpmourato** [comment]
The issue was my fault!
I created another gameobject that had another mediaplayer that was opening the same media.
Sorry about that.
