### ISSUE TITLE
How to change video from 3d to 2d?

### ISSUE THREAD

**Issue by xuyuefeng** [RenderHeads/UnityPlugin-AVProVideo#110]
I am trying to make a player which can change 3d video to 2d on Oculus go. 
I used two different spheres(the normal sphere 360 and sphere 360 OES).And i made a script to control whitch the sphere would play the video and here is the snipped pictures and my code.
![2dSphere](https://user-images.githubusercontent.com/47591937/60778946-e2ce6980-a173-11e9-9405-c39feb853738.PNG)
![3dsphere](https://user-images.githubusercontent.com/47591937/60778948-e2ce6980-a173-11e9-8256-1679a7863cc5.PNG)
![mediaplayer1](https://user-images.githubusercontent.com/47591937/60778949-e2ce6980-a173-11e9-80be-6a29317a6735.PNG)
![mediaplayer2](https://user-images.githubusercontent.com/47591937/60778950-e3670000-a173-11e9-89b7-090788cc3302.PNG)
![mediaplayer3](https://user-images.githubusercontent.com/47591937/60778951-e3670000-a173-11e9-9370-3f989d2ee287.PNG)

private void UIon()//all of the UI appeare
		{
				mediaPlayer2d.PlatformOptionsAndroid.useFastOesPath=false;
				Sphere3.SetActive(false);
				Sphere2.SetActive(true);
			
		}

private void UIoff( )//all of the UI disappear
		{
			
			mediaPlayer2d.PlatformOptionsAndroid.useFastOesPath=true;
			Sphere2.SetActive(false);
			Sphere3.SetActive(true);
		}

P.S
I found when I ticked "use fast OES path" before building the 3d worked but 2d failed. when I didnt tick,2d worked but 3d failed

**Comment by RenderHeadsSte** [comment]
I don't think this is an AVPro Video issue per se.
