### ISSUE TITLE
No sound on iOS

### ISSUE THREAD

**Issue by mypanora** [RenderHeads/UnityPlugin-AVProVideo#1102]
**Describe the issue**
Streaming works fine on Android, but no sound on iOS.

**Your Setup (please complete the following information):**
 - Unity version:  2020.3.26f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.3 ultra
 - Operating system version: iOS 15.0.1
 - Device model: iPhone 12
 - Video specs (resolution, frame-rate, codec, file size): 
    - Video reolution : 7680 x 3840
    - Video Frame-rate : 29.97
    - Video codec : HVC1
    - File Size : 800MB
    - Audio codec : AAC
    - Audio Channel : 2
    - Sample rate : 48000

**To Reproduce**
1. Play the video from the URL on iOS.

https://d3envcwdbtioa2.cloudfront.net/vodcdn/_definst_/mp4:8k_01_sungsan_h264_4k.mp4/playlist.m3u8

![configuration](https://user-images.githubusercontent.com/98515368/153830336-7ccbc87d-bb6e-407c-aefb-ee5c1b2f8de1.png)

**Comment by MorrisRH** [comment]
Audio is playing fine here using our Demo_MediaPlayer scene, devices tested:
- iPhone 13 Pro, iOS 15.3
- iPad Pro (10.5"), iOS 15.3
- iPhone X, iOS 14.81.1

**Comment by mypanora** [comment]
Thank you for the feedback. 
I tested it with your Demo_MediaPlayer scene, and the audio was playing fine also. However, I still get no sound when it comes to video streaming via HLS. It seems that Avpro plays audio from a media file stored in the internal storage well but not the one on a remote server. Audio is playing fine with the default media player of iOS, but AVpro gives no sound from video streaming via HLS. 
Thoughts?

**Comment by MorrisRH** [comment]
I'm not sure I understand.
I tested the stream you provided with our Demo_MediaPlayer scene and the audio from the stream played back correctly.
The only reasons I can think of for you not hearing audio would be due to the player either being muted, having it's volume level set to 0, or you've redirected audio output to another device (e.g. bluetooth speaker, headphones, etc.).

**Comment by mypanora** [comment]
My player is not muted. No audio device is connected to the phone, neither.
I do not think it is iPhone 12 making no audio, but I will see if I can get the audio with one of the devices you tested with.

**Comment by MorrisRH** [comment]
I'm not sure it would make any difference but the video specs you pasted didn't match the specs of the video you linked, which are:
- Video resolution : 3840x2160
- Video Frame-rate : 29.97
- Video codec : h264 (High)
- Audio codec : ac3
- Audio Channel : 6
- Sample rate : 48000

It could be that your device doesn't support the ac3 audio codec, so it would be worth re-encoding it as 2 channel aac to see if that works.
