### ISSUE TITLE
android project unable to play 4k with native videoplayer

### ISSUE THREAD

**Issue by mranderson02005** [RenderHeads/UnityPlugin-AVProVideo#1103]
**Describe the issue**
Using the native android player, the only one capable of producing on screen 4k video from what I can tell, is unable to play any 4k video file, h265 codec in mkv or mp4 containers. They play in the exoplayer but it can not display 4k on screen.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): latest trial core android
 - Operating system version: mac 12.1
 - Device model: macbook pro m1
 - Video specs (resolution, frame-rate, codec, file size): 3840x2160, 24fps, h265, 600gb

**To Reproduce**
1. sample or own avpro project
2. set local path to video file
3. set to native android videoplayer

**Logs**
If applicable, add error logs to help explain your problem.
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of main
2022/02/14 23:41:26.947 10659 10659 Info Zygote seccomp disabled by setenforce 0
2022/02/14 23:41:26.955 10659 10659 Warn otherviewPlaye Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2022/02/14 23:41:27.082 10659 10659 Info Mono JNI_OnLoad called
2022/02/14 23:41:27.085 10659 10659 Debug OpenGLRenderer Skia GL Pipeline
2022/02/14 23:41:27.156 10659 10659 Error gralloc ioctl c0044901 failed with code -1: Invalid argument
2022/02/14 23:41:27.156 10659 10659 Info gralloc ddebug, pair (share_fd=44, user_hnd=1, ion_client=46)
2022/02/14 23:41:27.187 10659 10675 Info Unity MemoryManager: Using 'Dynamic Heap' Allocator.
2022/02/14 23:41:27.212 10659 10659 Info gralloc ddebug, pair (share_fd=51, user_hnd=2, ion_client=46)
2022/02/14 23:41:27.219 10659 10675 Info Unity SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 4, Memory = 3709mb
2022/02/14 23:41:27.219 10659 10675 Info Unity SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf), 0 little (mask: 0x0)
2022/02/14 23:41:27.221 10659 10675 Info Unity ApplicationInfo com.Designlab.AnotherviewPlayer version 0.1 build e4bad789-bd52-4f2f-a1bc-050352d59791
2022/02/14 23:41:27.221 10659 10675 Info Unity Built from '2020.3/staging' branch, Version '2020.3.28f1 (f5400f52e03f)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
2022/02/14 23:41:27.298 10659 10659 Info gralloc ddebug, pair (share_fd=55, user_hnd=3, ion_client=46)
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of system
2022/02/14 23:41:27.369 10659 10675 Error SchedPolicy set_timerslack_ns write failed: Operation not permitted
2022/02/14 23:41:27.395 10659 10675 Info Unity Company Name: Designlab
2022/02/14 23:41:27.395 10659 10675 Info Unity Product Name: AnotherviewPlayer
2022/02/14 23:41:27.404 10659 10675 Info ConfigStore android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2022/02/14 23:41:27.404 10659 10675 Info ConfigStore android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2022/02/14 23:41:27.409 10659 10675 Debug mali_winsys EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
2022/02/14 23:41:27.425 10659 10675 Debug Unity  GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer
2022/02/14 23:41:27.425 10659 10675 Debug Unity  GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_
2022/02/14 23:41:27.425 10659 10675 Debug Unity box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array
2022/02/14 23:41:27.459 10659 10713 Info SwappyDisplayManager Starting looper thread
2022/02/14 23:41:27.495 10659 10716 Warn AudioTrack Use of stream types is deprecated for operations other than volume control
2022/02/14 23:41:27.495 10659 10716 Warn AudioTrack See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2022/02/14 23:41:27.772 10659 10675 Info MONO Getting locale
2022/02/14 23:41:27.772 10659 10675 Info Mono Locale en-US
2022/02/14 23:41:28.206 10659 10675 Verbose MediaRouter Adding route: RouteInfo{ name=Tablet, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2022/02/14 23:41:28.209 10659 10675 Verbose MediaRouter Audio routes updated: AudioRoutesInfo{ type=HDMI }, a2dp=false
2022/02/14 23:41:28.209 10659 10675 Verbose MediaRouter Selecting route: RouteInfo{ name=HDMI, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2022/02/14 23:41:28.316 10659 10709 Info gralloc ddebug, pair (share_fd=75, user_hnd=4, ion_client=46)
2022/02/14 23:41:28.324 10659 10709 Info gralloc ddebug, pair (share_fd=77, user_hnd=5, ion_client=46)
2022/02/14 23:41:28.380 10659 10709 Info gralloc ddebug, pair (share_fd=79, user_hnd=6, ion_client=46)
2022/02/14 23:41:27.370 10659 10675 Info chatty uid=10070(com.Designlab.AnotherviewPlayer) UnityMain identical 14 lines
2022/02/14 23:41:27.370 10659 10675 Error SchedPolicy set_timerslack_ns write failed: Operation not permitted
2022/02/14 23:41:30.694 10659 10675 Debug AVProVideo UnityPluginLoad CALLED
2022/02/14 23:41:30.769 10659 10675 Debug AVProVideo nativeInit : g_iCallDetailsReferenceCount = 1
2022/02/14 23:41:30.849 10659 10675 Info Unity s_Interface UnityEngine.AndroidJavaObject
2022/02/14 23:41:30.877 10659 10675 Info Unity m_Video UnityEngine.AndroidJavaObject
2022/02/14 23:41:30.912 10659 10675 Info Unity [AVProVideo] Creating player 0
2022/02/14 23:41:31.096 10659 10675 Info Unity [AVProVideo] Initialising AVPro Video v2.4.0 (native plugin v2.3.3f1-trial) on Mali-G31/OpenGL ES 3.2 v1.r16p0-01rel0-32c0b2f.d08033f57c40e4bf4f36fa180299b593 (MT True) on Android
2022/02/14 23:41:31.121 10659 10675 Info Unity [AVProVideo] Opening /storage/622F5F9C4C71A481/Android/data/com.Designlab.AnotherviewPlayer/files/forest.mp4 (offset 0) with API MediaPlayer
2022/02/14 23:41:32.322 10659 10671 Warn IMediaDeathNotifier media server died
2022/02/14 23:41:32.322 10659 10671 Error MediaPlayerNative error (100, 0)
2022/02/14 23:41:32.343 10659 10675 Error MediaPlayerNative start called in state 0, mPlayer(0xe66c3580)
2022/02/14 23:41:32.343 10659 10675 Error MediaPlayerNative error (-38, 0)
2022/02/14 23:41:32.345 10659 10659 Verbose MediaRouter onRestoreRoute() : route=RouteInfo{ name=HDMI, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2022/02/14 23:41:32.345 10659 10659 Verbose MediaRouter Selecting route: RouteInfo{ name=HDMI, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2022/02/14 23:41:32.370 10659 10675 Error MediaPlayer Error (100,0)
2022/02/14 23:41:32.370 10659 10675 Error MediaPlayer Error (-38,0)
2022/02/14 23:41:32.373 10659 10659 Verbose MediaRouter onRestoreRoute() : route=RouteInfo{ name=HDMI, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2022/02/14 23:41:32.374 10659 10659 Verbose MediaRouter Selecting route: RouteInfo{ name=HDMI, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
2022/02/14 23:41:32.399 10659 10675 Info Unity [AVProVideo] Using playback path: MediaPlayer NonOES (3840x2160@0.00)
2022/02/14 23:41:32.420 10659 10675 Info Unity [AVProVideo] Texture ID: 23
2022/02/14 23:41:32.421 10659 10675 Error Unity [AVProVideo] Error: Decode failed.  Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources. On Android this is generally due to the hardware not having enough resources to decode the video. Most Android devices can only handle a maximum of one 4K video at once.
2022/02/14 23:41:32.675 10659 10668 Warn System A resource failed to call end. 
2022/02/14 23:44:20.485 10659 10675 Error MediaPlayerNative pause called in state 0, mPlayer(0xe66c3580)
2022/02/14 23:44:20.486 10659 10675 Error MediaPlayerNative error (-38, 0)
2022/02/14 23:44:20.486 10659 10675 Info Unity [AVProVideo] OnApplicationPause: pausing video
2022/02/14 23:44:20.529 10659 10716 Debug AudioTrack stop() called with 4156416 frames delivered
2022/02/14 23:44:20.534 10659 10675 Error MediaPlayer Error (-38,0)
2022/02/14 23:44:20.542 10659 10659 Info gralloc ddebug, free share_fd=51, user_hnd=0x2, ion client=46
2022/02/14 23:44:20.542 10659 10659 Info gralloc ddebug, free share_fd=55, user_hnd=0x3, ion client=46
2022/02/14 23:44:20.543 10659 10659 Info gralloc ddebug, free share_fd=44, user_hnd=0x1, ion client=46
2022/02/14 23:44:21.302 10659 10751 Warn AudioSystem AudioFlinger server died!
2022/02/14 23:44:21.303 10659 10672 Warn AudioSystem AudioPolicyService server died!

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by mranderson02005** [comment]
I should mention the target device is an hardkernel odroid c4 running android pie. I have played 2 4k videos at the same time on this device using a native videoplayer and it has usb 3.0 for connectivity.

**Comment by RenderHeadsSte** [comment]
What do you mean by 'native android videoplayer' ?

**Comment by mranderson02005** [comment]
I hope I am saying this right, but it is the video player built into android, as documented in the developer section of android. The "handheld" function of unity seems to be able to use this?

**Comment by RenderHeadsSte** [comment]
Sorry, I edited my last comment just as you were replying...

**Comment by mranderson02005** [comment]
oh yes, as to my experiment to try and get 4k from avpro video I selected the mediaplayer instead of exoplayer. And that was unable to play the video in 4k in any format.

**Comment by mranderson02005** [comment]
I am able to use Screen.SetResolution (3820, 2160, true); and set the device resolution to 4k but the video remains in hd (even tho it is decoding the 4k as seen in the bottom right of the screen) This is when using exoplayer.

**Comment by mranderson02005** [comment]
still not working ;)
