### ISSUE TITLE
Missing parameter in documentation ffmpeg command

### ISSUE THREAD

**Issue by thbc** [RenderHeads/UnityPlugin-AVProVideo#1104]
Hey guys, 
just letting you know that there is missing the "-i" parameter before "video.mp4" in this section in your documentation: [Alternative steps for encoding manually](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html#alternative-steps-for-encoding-manually)
which leads to ffmpeg asking whether a file should be overwritten.

great plugin btw!

**Comment by kahnivore** [comment]
Thanks for letting us know!

@AndrewRH to update docs

**Comment by AndrewRH** [comment]
thanks @thbc !

**Comment by AndrewRH** [comment]
Fixed :-)
