### ISSUE TITLE
Looping video is not seamless in unity AVPro Media Player

### ISSUE THREAD

**Issue by MattCoalman** [RenderHeads/UnityPlugin-AVProVideo#1106]
I am trying to use the loop option on a AVPro Media Player, with a small (6sec, 25MB) perfectly looped video, but there is a small "freeze" when looping.

My code is very simple:

```
public MediaPlayer avMediaPlayer1 = null;

void Start()
{
    avMediaPlayer1.OpenMedia(new MediaPath("c:\\path\\video.mp4", MediaPathType.AbsolutePathOrURL), false);
    avMediaPlayer1.Control.SetLooping(true);
    avMediaPlayer1.Control.Play();
}
```
I have tested for instance with [this video](https://www.videvo.net/video/glowing-purple-grid-lines-tracking-in/393674/)
There is always a stutter (or quick freeze) when looping. 

What am I doing wrong?

**Some info** : 
PC with I7 processor
Windows 10
NVMe drive
GTX1050
Unity 2020
AVPro Media Player Trial

Thanks a lot.

**Comment by kahnivore** [comment]
This video plays back with the same pause in VLC, doesn't seem like an AVPro Video issue

**Comment by MattCoalman** [comment]
> Try encoding the video as keyframes only and making sure the audio track is removed.

Ok, the re-encoding with the `keyframe-only` (or in my case `Keyframe every 1 frame`) option did the trick.
Maybe it should be in a documentation?
Thanks a lot !
