### ISSUE TITLE
[Windows] Media Foundation does not play HAP videos

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProVideo#1107]
Windows Media Foundation player fails on HAP videos with this generic error:

```
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1255)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:683)

```

Have tried videos of a variety of formats and all fail the same way.  HAP videos created via ffmpeg:

`ffmpeg.exe -y -i "video.mp4" -vf yadif=deint=interlaced  -c:v hap   "video-hap.mov" `

Tested on versions:
2.0.9f1-ultra
2.3.2f1-ultra

Unity: Unity 2019.4.35f1
OS: Win10/11

**Comment by v2k** [comment]
Looks like this works with 2.3.2f1-ultra - did not see the "Use Hap" option.  Is this not supported in 2.09?

**Comment by kahnivore** [comment]
There were many performance improvements to the HAP decoder made after 2.0.9, including the 'Use Hap' option - [see 2.0.10 release notes](https://www.renderheads.com/content/docs/AVProVideo/versions/2.0.10.html).
