### ISSUE TITLE
[Windows] AudioOutput does not work with Direct Show player

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProVideo#1109]
Playing videos with the DirectShow player does not allow AudioOutput to capture the audio stream with Audio Output set to Unity.  The request will always exit early from AudioOutputManager with channels at 0:

```
public void RequestAudio(AudioOutput outputComponent, MediaPlayer mediaPlayer, float[] audioData, int audioChannelCount, int channelMask, AudioOutput.AudioOutputMode audioOutputMode, bool supportPositionalAudio) {
    if (mediaPlayer == null || mediaPlayer.Control == null || !mediaPlayer.Control.IsPlaying()) {
        if (supportPositionalAudio) {
            ZeroAudio(audioData, 0);
        }
        return;
    }

    int channels = mediaPlayer.Control.GetAudioChannelCount();
    if (channels <= 0) {
        if (supportPositionalAudio) {
            ZeroAudio(audioData, 0);
        }
        return;
    }
...
```

With MediaFoundation:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/608250/154741141-89576f30-4831-4ea9-8d06-2219a7ca541a.png">

With Direct Show:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/608250/154741192-333d12ae-146a-4a82-8da9-84c7b6b1418b.png">

Unity version: 2019.4.35f1
AVPro Video version: 2.0.9 ultra and  2.2.3 ultra
Operating system version: Win10/11
Video specs: various videos

**To Reproduce**
1. With Audio Output set to Unity and Video API set to DirectShow, attach an AudioOutput component to the video player
2. Play a video with the MediaPlayer
3. Look at the audio bars in the AudioOutput component

**Comment by kahnivore** [comment]
We unfortunately don't support Unity audio output with Media Foundation

**Comment by v2k** [comment]
Would be nice to have some feedback or error log in this case.
