### ISSUE TITLE
Video should always play from initial point

### ISSUE THREAD

**Issue by syedali1621** [RenderHeads/UnityPlugin-AVProVideo#111]
I am calling media player script below method to play video and stop() method to stop video i just want video to always play from start  when ever i stop video it is playing from last point where i stopped it.
public void Play()
		{
			if (m_Control != null && m_Control.CanPlay())
			{
				m_Control.Play();

				// Mark this event as done because it's irrelevant once playback starts
				m_EventFired_ReadyToPlay = true;
			}
			else
			{
				// Can't play, perhaps it's still loading?  Queuing play using m_AutoStart to play after loading
				m_AutoStart = true;
				m_AutoStartTriggered = false;
			}
		}

**Comment by syedali1621** [comment]
Can you please let me know which method is saving video last play point i need to stop it i want player to start video every time from beginning ?

**Comment by syedali1621** [comment]
Please answer as soon as possible this is the only issue i need to solve then avpro player will be ready for me to implement on my project. When video always play from beginning then i will purchase avpro player because i need to complete my project as soon as possible.

**Comment by RenderHeadsSte** [comment]
Thanks for you interest in using AVProVideo.

Please accept my apologies in taking a few days to reply to you.  I hope we can guide you towards achieving what you require.

Before calling m_Control.Play(), call m_Control.Rewind() ...that will rewind the video to it's start point before the play action is executed.

Do let us know if this achieves what you require.
