### ISSUE TITLE
Subtitles not showing using WinRT 

### ISSUE THREAD

**Issue by kakusato** [RenderHeads/UnityPlugin-AVProVideo#1110]
**Describe the issue**
Videos in HLS format will not play SRT subtitles file.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.28f1
 - AVPro Video version 2.4 trial: 
 - Operating system version: Windows11

**Comment by kahnivore** [comment]
Not sure what you mean - SRT files are loaded externally. See our docs on [subtitles](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-subtitles.html).

**Comment by kakusato** [comment]
Does not work when the Video API is WinRT.
If the Video API is Media Foundaition, it will work.
A screenshot of the configuration is attached.

![screen-shot01](https://user-images.githubusercontent.com/12974873/155198197-2b752bf0-3b72-4780-b724-38c768a947e8.png)

**Comment by kahnivore** [comment]
Could you send your srt file please?

**Comment by kakusato** [comment]
I will send you the SRT file.
If the file extension is srt, it cannot be uploaded, so upload it as txt.

[subtitles.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8126915/subtitles.txt)

**Comment by kahnivore** [comment]
Interesting. Do you get any error messages in the console when using WinRT (that aren't there when using Media Foundation)?

**Comment by kahnivore** [comment]
Thanks for reporting, this will be fixed in the next release

**Comment by kakusato** [comment]
Thanks for the confirmation. Bug fix, looking forward to it. Take care of Corona.

**Comment by AndrewRH** [comment]
@kakusato 
You can fix it yourself by editing WindowsRtMediaPlayer.cs and adding ``UpdateSubtitles();`` to line 505: 

![image](https://user-images.githubusercontent.com/5418126/155758141-89eff89d-6935-4a7d-bd05-d4e0ba505298.png)

Thanks,

**Comment by AndrewRH** [comment]
Version 2.4.1 of AVPro Video has been released and contains a fix for this issue. Thanks for your feedback and patience :)
