### ISSUE TITLE
[Android] Memory leak Unity 2021.2.7 on Android (Oculus Quest 2)

### ISSUE THREAD

**Issue by pavelk0508** [RenderHeads/UnityPlugin-AVProVideo#1112]
Hello!
We use the latest version of your asset for Unity (AVPro Video - Ultra Edition). There was a problem with a memory leak on Android. The problem is that after downloading the video using the OpenMedia method, the video is downloading. After calling the CloseMedia method, RAM consumption does not normalize (the memory leak is ~300 MB).
I hope for speedy feedback and a possible solution.
Thanks! 

 - Unity 2021.2.7: 
 - AVPro Video Ultra 2.4.0
 - Android 10 
 - Oculus Quest 2: 
 - 8k 30 fps 30 mbps (codec h.264)
 - Player  - ExoPlayer

1. Create MediaPlayer
2. Call OpenMedia method
3. Call CloseMedia method

Screenshot description:
1. 3530s – player object created;
2. 3570s-3580s - the OpenMedia function was called;
3. 3580s – the CloseMedia function is called.

![image](https://user-images.githubusercontent.com/42943374/154980002-74860923-c45f-498f-a0a6-f4b73ef96add.png)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Struggling to reproduce this. Would you be able to send a sample reproducible project to unitysupport@renderheads.com? 

Thanks.

**Comment by pavelk0508** [comment]
@kahnivore Hello, I sent a test project, there is a leak there too

**Comment by RenderHeadsSte** [comment]
The project you sent does not look like it contains anything other than a blank Unity project with the AVPro Video package imported.

I have added a script to open, wait, close, wait...repeat.  After 200 cycles I call close and dispose of the media player.  Here is the results.  I have added a red horizontal line that shows post disposal memory looks to be what it was at the first play.  It does look like memory creeps up over the course of the test, but not on each open/close.  According to the profiler, approx 7meg creep happened over the 30 minute.  But, again, after the dispose all memory was returned.

![image](https://user-images.githubusercontent.com/46531149/157497694-f217d3f5-012e-4c70-9a59-7a50786648d4.png)

**Comment by pavelk0508** [comment]
@RenderHeadsSte And is it possible to unload memory instantly, and not after a period of time?

**Comment by RenderHeadsSte** [comment]
Call force dispose on the mediaplayer object...

	mediaPlayer.ForceDispose();
	mediaPlayer = null;

...and then call for some garbage collection

	System.GC.Collect();

**Comment by pavelk0508** [comment]
@RenderHeadsSte today I tested the ForceDispose method and it turned out that just when the CloseMedia function is called, memory is released, but after a while. If you call the ForceDispose method, it is not released

**Comment by pavelk0508** [comment]
@RenderHeadsSte Is there another way to free memory immediately without destroying the player?

**Comment by RenderHeadsSte** [comment]
What memory are you talking about freeing?  If you have a player alive, it needs memory.  All you can do is call the garbage collector to action.

**Comment by pavelk0508** [comment]
@RenderHeadsSte  After calling the CloseMedia method, the memory is freed, but after a while. Is it possible to speed up memory unloading when calling the CloseMedia method?

**Comment by pavelk0508** [comment]
@RenderHeadsSte @kahnivore Hi! Do you have any ideas?

**Comment by RenderHeadsSte** [comment]
Are you calling for garbage collection to happen?  If so, the only other thing to try is call:

GC.WaitForPendingFinalizers()

...before GC.Collect()

**Comment by pavelk0508** [comment]
@RenderHeadsSte I tried the GC method. Memory is not released after calling GC.WaitForPendingFinalizers() and GC.Collect(). Are there any other ways?

**Comment by RenderHeadsSte** [comment]
None that I am aware of.  See [here](https://stackoverflow.com/questions/4257372/how-to-force-garbage-collector-to-run) for discussion on forcing garbage collection.

**Comment by pavelk0508** [comment]
@RenderHeadsSte Each media player instance creates an instance inside the Java class. Is it possible to force the memory to be unloaded by a method from a Java class? Because it doesn't happen right away. There is a case - there are several video panoramas that switch between each other upon completion. On the Oculus Quest, the memory does not have time to unload, which causes a crash with Exception.OutOfMemory. Tried GC.Collect and ForceDispose, still doesn't help. So far, one solution is used - to use fewer panoramas or reduce the resolution and bitrate, but this is not an option.

**Comment by RenderHeadsSte** [comment]
Whilst trying to force garbage collection in the java layer might motivate the system to clean up sooner, it is in no way guaranteed.  It is very much a none-deterministic system.  As it cannot be guaranteed you will likely find yourself with the same problem on occasion, and so it is not really a 'fix'.  It sounds like you are just asking too much of the hardware on this occasion.
