### ISSUE TITLE
Can we stream videos with ambisonic sounds on AVPro? 

### ISSUE THREAD

**Issue by Renaud-Hoppin** [RenderHeads/UnityPlugin-AVProVideo#1115]
Hello, 

We want to stream HLS video into our app using AVPro, on Oculus Quest 1 and Oculus Quest 2. We want the audio of the video to play in ambisonic. 

- Is it possible to stream HLS(.m3u8) video with ambisonic audio using AVPro?
- Is this audio format supported: 
4 channels 48khz (mp4)

- Here is our setup: 
Unity version: 2020.3.3f1
AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core
Device model: Oculus Quest 1 and Oculus Quest 2 
Our current video and audio files are currently .mp4 playing in HLS (.m3u8)

Thanks,

**Comment by kahnivore** [comment]
Hi there,

We support ambisonic audio but currently only using an MKV container and Opus codec.

Note that this is a feature of our Ultra edition only. 

See [our documentation](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html) on this.

**Comment by Renaud-Hoppin** [comment]
Hello @kahnivore, 

The documentation mentions that: 
''The video files must be using a MKV file container and audio must be using the Opus codec encoded with Facebook Audio 360 tools.''

However, it seems that the Facebook 360 Tools are now deprecated:
https://facebookincubator.github.io/facebook-360-spatial-workstation/

And Facebook will no longer provide support for these tools. 
Is there any other solution you suggest to have ambisonic audio with AVPro? 

Thanks,
