### ISSUE TITLE
[android]java.lang.IllegalStateException

### ISSUE THREAD

**Issue by 1901g** [RenderHeads/UnityPlugin-AVProVideo#1116]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.12f1.590.2
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Core 2.4.0
 - Operating system version: android 10
 - Device model: Redmi K20 Pro Premium Edition

**Logs**
    Thread Name: 'Thread-12750'
    Back traces starts.
    java.lang.IllegalStateException
	    at android.media.MediaPlayer._reset(Native Method)
	    at android.media.MediaPlayer.reset(MediaPlayer.java:2208)
	    at com.renderheads.AVPro.Video.Player_MediaPlayer$1.run(Player_MediaPlayer.java:1)
	    at java.lang.Thread.run(Thread.java:919)
    Back traces ends.

**Comment by kahnivore** [comment]
Could you give us a better description of this issue so we can try reproduce it? 

Thanks

**Comment by kahnivore** [comment]
Closing due to lack of response. Feel free to reopen if the problem persists.
