### ISSUE TITLE
Legacy Version upgrading support

### ISSUE THREAD

**Issue by songqiaoluckyvr** [RenderHeads/UnityPlugin-AVProVideo#1117]
We are experiencing the **D3D not supported format** error with the Avprovideo version we are using.
seems to upgrade to 1.9.17 can fix the issue and since our product is on live we don't want to risk upgrading to 2.X
what would be the way to upgrade the legacy 1.X version to a sightly newer one? 

 - Unity version: 2020.3 LTS
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 1.9.7 UTLRA
 - Operating system version: WIN10
 - Device model: WINDOWS STANDALONE/ANDROID
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by AndrewRH** [comment]
it should be pretty safe to upgrade to 1.9.17.....I don't think much changed except for bug fixes

**Comment by songqiaoluckyvr** [comment]
Thank you for the reply!
May I ask where are we able to get the old ultra version that we are
looking for?
Or the free trial version with work if we have a license?
Thanks again!

**Comment by songqiaoluckyvr** [comment]
Tried to replace our old version with the trial version in the GitHub repo, it doesn't work with watermarks on our video content.

**Comment by AndrewRH** [comment]
If you bought the 1.x AVPro Video from the Unity Asset Store, then you will still be able to download it from there using your account.

**Comment by songqiaoluckyvr** [comment]
Thank you for the reply!
I can only see 2.4.0 the latest version in the asset store, not sure where to toggle different versions. Helps appreciated!

**Comment by kahnivore** [comment]
You'll need look in the list of assets that you own on the Asset Store (navigate to 'My Assets' from the dropdown next to your username at the top right-hand corner)- there should be an option to download AVPro Video 1.x there if you have a license for it.

Does that help?

**Comment by songqiaoluckyvr** [comment]
thank you, that's all I see from asset store, the asset is not purchased from my account I just a got assigned the seat with it from my company. would it help if the seat set back to who purchased it?
![Capture](https://user-images.githubusercontent.com/98339060/156223717-b8a0c4a0-b29b-4b53-b134-3ad4263a91a2.PNG)

**Comment by kahnivore** [comment]
Version 1.x is a separate asset to 2.x. It seems your seat is for 2.x, not 1.x. We can provide you with version 1.11.7 if you send your Unity pdf invoice to unitysupport@renderheads.com. Please include this issue number (#1117) in the subject line).
