### ISSUE TITLE
FPS stays low until AVPro plays first video (Quest 2)

### ISSUE THREAD

**Issue by suwas-subvrsive** [RenderHeads/UnityPlugin-AVProVideo#1118]
FPS stays low until AVPro plays first video (Quest 2). Frame rate jumps by about 5 frames per sec as soon as AVPro plays the first video and stays there throughout the session. 

 - Unity version: 2021.1.24f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video - Core Edition 2.3.3
 - Operating system version: Android 
 - Device model: Quest 2

**Logs**
[log - 64 FPS.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8136446/log.-.64.FPS.txt)
[log - 72 FPS.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8136447/log.-.72.FPS.txt)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Would it be possible to share a recording of this so we can see what you mean? 

Is this reproducible in our demo scene? 

Have you tried upgrading to 2.4.0?

**Comment by suwas-subvrsive** [comment]
- Not sure if a recording will be any useful since there's no visual difference. It's just ~5 FPS difference. But it does definitely shoot up by 5FPS as soon as the first video starts playing.
- The FPS difference is not noticeable on the Demo scenes since they are so light in the first place
- I haven't but I'll try that.


From further digging and investigation...I think having the videos (500 MB total size of all videos) in the streaming assets folder might be the reason. I'll be doing some more troubleshooting today. But it still doesn't make sense why starting to play those videos might increase the FPS??

**Comment by AndrewRH** [comment]
Why is this a problem?  I though higher FPS was a good thing? :)

Seriously though, I wonder if it could be because video playback is working the GPU harder, so it transitions into a higher power level?  Perhaps you could display the CPU and GPU level modes and monitor what happens to them?

**Comment by suwas-subvrsive** [comment]
Before we start playing the AVPro video: 
- CPU Level: 4
- GPU Level: 4
- FPS: ~65
- Stale Frames: ~18
- CPU Util: ~25
- GPU Util: ~99

After first AVPro video starts playing:
- CPU Level: 2
- GPU Level: 4
- FPS: ~72
- Stale Frames: ~0
- CPU Util: ~25
- GPU Util: ~99

**Comment by suwas-subvrsive** [comment]
I'm still troubleshooting. @AndrewRH @kahnivore Did you guys have any insight/ suggestions?

**Comment by suwas-subvrsive** [comment]
@AndrewRH @kahnivore Just checking in to see it you have any updates here or any idea what could be happening here?

**Comment by suwas-subvrsive** [comment]
Checking in to see if there are any updates here. Thanks.

**Comment by Chris-RH** [comment]
Hi, is this still a problem?

**Comment by suwas-subvrsive** [comment]
@Chris-RH Thanks for following up on this. I haven't updated the AVPro plugin since this post on Feb 24th because we're in the final release phase of the project. So yea this is still happening. I'm using a hotfix for now wherein I play a small video without audio on awake in every scene. Did you guys figure it out and push a fix in the updated version?

**Comment by Chris-RH** [comment]
Hi @suwas-subvrsive 
Have you tried the above to see if it helps?

**Comment by suwas-subvrsive** [comment]
We haven't tried this yet in our troubleshooting so far.

**Comment by Chris-RH** [comment]
Closed due to lack of response. Please reopen this if there are further issues
