### ISSUE TITLE
Videos not playing on iOS with Apple Silicon

### ISSUE THREAD

**Issue by FedericoVRN** [RenderHeads/UnityPlugin-AVProVideo#1119]
**Describe the issue**
Hi :)
Like the title says: Videos not playing on iOS with Apple Silicon.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.16
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.0
 - Operating system version: iOS 15.2.1
 - Device model: iPad Pro 11 inches 3rd gen M1, iPhone X iOS

**Comment by kahnivore** [comment]
Which videos aren't playing? Could you try our Demo_MediaPlayer scene with the video samples we have included? 

Do you have any error logs you could share? 

Would also be a good idea to update to the latest plugin version 2.4.0.

**Comment by FedericoVRN** [comment]
Well, my team just informed me that now the videos are working :p
Sorry for bothering you and thanks for your quick answer.
Have a nice weekend! 🙋‍♀️
