### ISSUE TITLE
AVPro Android version - ARM64 support does not appear to be working in my build

### ISSUE THREAD

**Issue by falldeaf** [RenderHeads/UnityPlugin-AVProVideo#112]
**Describe the bug**
AVPro does not play streaming video when I build to IL2CPP and include the ARM64 architecture. I'm building to an Android app bundle, and if I uncheck ARM64 video plays fine, when I check it, it no longers plays.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.13f1
 - AVPro Video version: 1.10.0 (Android only version)
 - Operating system version: Android 9
 - Device model: Pixel 1
 - Video specs (resolution, frame-rate, codec, file size): mp4, 1366x684, 29.7 (streaming from Vimeo)

**To Reproduce**
1. Build to a Google App bundle using IL2CPP with ARM64 support
2. Play a streaming URL

**Logs**
07-08 20:05:45.494  7317  7341 E Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: com.RenderHeads.AVProVideo.AVProMobileVideo
07-08 20:05:45.494  7317  7341 E Unity   : java.lang.NoClassDefFoundError: com.RenderHeads.AVProVideo.AVProMobileVideo
07-08 20:05:45.494  7317  7341 E Unity   :      at java.lang.Class.classForName(Native Method)
07-08 20:05:45.494  7317  7341 E Unity   :      at java.lang.Class.forName(Class.java:453)
07-08 20:05:45.494  7317  7341 E Unity   :      at java.lang.Class.forName(Class.java:378)
07-08 20:05:45.494  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-08 20:05:45.494  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
07-08 20:05:45.494  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
07-08 20:05:45.494  7317  7341 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:395)
07-08 20:05:45.494  7317  7341 E Unity   :      at android.os.Looper.loop(Looper.java:160)
07-08 20:05:45.494  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
07-08 20:05:45.494  7317  7341 E Unity   : Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Gannett.Campfire-mqXRNpKPZGh0wBX5M5uoYw==/base.apk", zip file "/data/app/com.Gannett.Campfire-mqXRNpKPZGh0wBX5M5uoYw==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.Gannett.Campfire-mqXRNpKPZGh0wBX5M5uoYw==/lib/arm64, /data/app/com.Ga
07-08 20:05:45.505  7317  7341 E Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: com.RenderHeads.AVProVideo.AVProMobileVideo
07-08 20:05:45.505  7317  7341 E Unity   : java.lang.NoClassDefFoundError: com.RenderHeads.AVProVideo.AVProMobileVideo
07-08 20:05:45.505  7317  7341 E Unity   :      at java.lang.Class.classForName(Native Method)
07-08 20:05:45.505  7317  7341 E Unity   :      at java.lang.Class.forName(Class.java:453)
07-08 20:05:45.505  7317  7341 E Unity   :      at java.lang.Class.forName(Class.java:378)
07-08 20:05:45.505  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-08 20:05:45.505  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
07-08 20:05:45.505  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
07-08 20:05:45.505  7317  7341 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:395)
07-08 20:05:45.505  7317  7341 E Unity   :      at android.os.Looper.loop(Looper.java:160)
07-08 20:05:45.505  7317  7341 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
07-08 20:05:45.505  7317  7341 E Unity   : Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.Gannett.Campfire-mqXRNpKPZGh0wBX5M5uoYw==/base.apk", zip file "/data/app/com.Gannett.Campfire-mqXRNpKPZGh0wBX5M5uoYw==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.Gannett.Campfire-mqXRNpKPZGh0wBX5M5uoYw==/lib/arm64, /data/app/com.Ga
07-08 20:05:45.510  7317  7341 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
07-08 20:05:45.510  7317  7341 E Unity   :   at sphere_control.Update () [0x00000] in <00000000000000000000000000000000>:0
07-08 20:05:45.510  7317  7341 E Unity   :
07-08 20:05:45.510  7317  7341 E Unity   : (Filename: currently not available on il2cpp Line: -1)
07-08 20:05:45.510  7317  7341 E Unity   :
07-08 20:05:45.860  7317  7341 E Unity   : NullReferenceException: Object reference not set to an instance of an object.
07-08 20:05:45.860  7317  7341 E Unity   :   at sphere_control.Update () [0x00000] in <00000000000000000000000000000000>:0

**Videos**
https://player.vimeo.com/external/343711445.hd.mp4?s=50c4668c6b2557a487890db42ea1d1a06c3fa9db&profile_id=174 (Not the exact video but same site (Vimeo), codec, etc.

**Comment by falldeaf** [comment]
I saw this closed bug report (https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/81) that seemed like it might be similar but even after upgrading to the latest AVPro version it didn't solve the issue

**Comment by RenderHeadsSte** [comment]
Can you check the arm64 plugin files are flagged for (platform) Android and (CPU) ARM64 ?

There are 5 of them (listed below) and they live under the folder: Plugins/Android/libs/arm64-v8a/

libAudio360.so
libAudio360-JNI.so
libAVProLocal.so
libopus.so
libopusJNI.so

**Comment by falldeaf** [comment]
Hey thanks for responding! Yup, that was the problem!! I went in and set each of those files in the arm64 dir to go to android and video now works as expected. Thanks so much for your help!

**Comment by falldeaf** [comment]
Solution correctly identified and solved, thanks again for the help and the fast response time.

**Comment by lvchy** [comment]
I Have The Same Issue . Please Help Me. I just buy this avpro . But It can not work on my android phone.

**Comment by lvchy** [comment]
Unity Version 2018.4.21f1 , When I build with mono,only not work with arm64 and il2cpp,it works fine . But when i check il2cpp and arm64,it show the same not find class exception . I have check the arm64-v8a/ folder ,it has those .so files

**Comment by lvchy** [comment]
--------- beginning of main
07-14 17:00:32.665 31497 31534 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 7408mb
07-14 17:00:32.665 31497 31534 I Unity   : SystemInfo ARM big.LITTLE configuration: 2 big (mask: 0xc0), 6 little (mask: 0x3f)
07-14 17:00:32.665 31497 31534 I Unity   : ApplicationInfo com.fun.avfun version 0.1 build ab561455-cc31-47c4-8cb5-9ea182331bf5
07-14 17:00:32.665 31497 31534 I Unity   : Built from '2018.4/staging' branch, Version '2018.4.21f1 (fd3915227633)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
07-14 17:00:32.763 31497 31534 D Unity   :  GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_EXT_texture_compression_astc_decode_mode GL_EXT_texture_compression_astc_decode_mode_rgb9e5 GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer
07-14 17:00:32.763 31497 31534 D Unity   :  GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_
07-14 17:00:32.763 31497 31534 D Unity   : box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture_buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_EGL_image_array GL_EXT_texture_filter_anisotropic GL_HUAWEI_smart_cache
07-14 17:00:34.944 31497 31534 E Unity   : AndroidJavaException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fun.avfun-hcv1nrciykK74YlFzaoKJw==/base.apk"],nativeLibraryDirectories=[/data/app/com.fun.avfun-hcv1nrciykK74YlFzaoKJw==/lib/arm64, /data/app/com.fun.avfun-hcv1nrciykK74YlFzaoKJw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]] couldn't find "libAVProLocal.so"
07-14 17:00:34.944 31497 31534 E Unity   : java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fun.avfun-hcv1nrciykK74YlFzaoKJw==/base.apk"],nativeLibraryDirectories=[/data/app/com.fun.avfun-hcv1nrciykK74YlFzaoKJw==/lib/arm64, /data/app/com.fun.avfun-hcv1nrciykK74YlFzaoKJw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]] couldn't find "libAVProLocal.so"
07-14 17:00:34.944 31497 31534 E Unity   :      at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
07-14 17:00:34.944 31497 31534 E Unity   :      at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
07-14 17:00:34.944 31497 31534 E Unity   :      at java.lang.System.loadLibrary(System.java:1668)
07-14 17:00:34.944 31497 31534 E Unity   :      at com.RenderHeads.AVProVideo.AVProMobileVideo.

**Comment by lvchy** [comment]
What happen when I select arm64 and il2cpp, build with the demo scene 04_Demo_uGui . It worked on mono
