### ISSUE TITLE
RTSP live stream giving " Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources."

### ISSUE THREAD

**Issue by brianmlatimer** [RenderHeads/UnityPlugin-AVProVideo#1120]
**Describe the issue**
I want to view this live stream "rtsp://rtsp.stream/pattern" but when putting it into the URL and running, it gives me the error in the title. It seems to be for any rtsp stream.
I can confirm that this stream does work, so its not like the stream is down.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.15f2
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.4.1 Trial (Latest)
 - Operating system version: Android 10
 - Device model:
 - Video specs (resolution, frame-rate, codec, file size): 320x240@30.00

**To Reproduce**
1. Download the trial
2. Open Media Player demo scene
3. change url to rtsp://rtsp.stream/pattern and run

**Screenshots**
![image](https://user-images.githubusercontent.com/57278983/156066082-66f60ee9-4a2c-42eb-add8-9ceb2ff987c2.png)
![image](https://user-images.githubusercontent.com/57278983/156066447-378f4341-bb6a-4c1a-93ac-36bb98b8e6e1.png)

**Comment by kahnivore** [comment]
It looks like you're getting this error in the editor, have you tested a build on your device?

**Comment by brianmlatimer** [comment]
Yes, doesn't work there either.

**Comment by kahnivore** [comment]
Could you share your stream with us please?

**Comment by AndrewRH** [comment]
that stream works for me in Windows...@kahnivore perhaps you could test on Android?

**Comment by kahnivore** [comment]
@AndrewRH strange, it doesn't seem to play on my test device  but can't see any errors in the logcat either

**Comment by RenderHeadsSte** [comment]
@brianmlatimer Coming in the next release of AVPRo Video (v2.5.0) is the ability to playback RTSP streams using the ExoPlayer API path.  I have tested your stream URL and it works using ExoPlayer.  We hope to release this version later this week.
