### ISSUE TITLE
FinishedPlaying event does not fire in certain HLS video

### ISSUE THREAD

**Issue by kakusato** [RenderHeads/UnityPlugin-AVProVideo#1122]
**Describe the issue**
The first one will fire.
It does not fire after rewinding a little after the video finishes playing.
MP4 is no problem.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.28f1
 - AVPro Video version: 2.4.1trial
 - Operating system version: Windows11

**Comment by kahnivore** [comment]
Could you provide a little more detail here so that we can try reproduce this? How far back are you seeking, perhaps you could share a code sample?

Thanks

**Comment by kakusato** [comment]
using UnityEngine;
using RenderHeads.Media.AVProVideo;

public class EventTest : MonoBehaviour
{

    public MediaPlayer MediaPlayer;

    void Start()
    {
        if (MediaPlayer) MediaPlayer.Events.AddListener(OnVideoEvent);
    }

    public void OnVideoEvent(MediaPlayer mp, MediaPlayerEvent.EventType et, ErrorCode errorCode)
    {
        Debug.Log(et);
    }

 }

It is difficult to explain, so I uploaded a video.
https://youtu.be/UmeULdRZbh4

1. MP4, 1st playback fires.
2. Rewind a little.
3. MP4, second playback also fires.

1. HLS, first playback fires.
2. Rewind a little.
3. HLS, second playback does not fire.

**Comment by kahnivore** [comment]
Tested with both an MP4 and an HLS stream, both behave in the same way - i.e. fire the finished playing event when it ends and then again after rewinding a little. 

Could you perhaps share the stream you're testing with? You can send to unitysupport@renderheads.com if it's private (please include the issue number (1122) in the subject line.

**Comment by kakusato** [comment]
The project file is uploaded below.

https://drive.google.com/file/d/1gTlIvwtevA983F822YWkwJqHUSK04kT1/view?usp=sharing

**Comment by kahnivore** [comment]
Sorry, I accidentally deleted the project file before realising it would contain the trial version and not the licensed plugin. Could you reshare? Also noticed access was still required.

**Comment by kakusato** [comment]
I'm sorry. I will post it again.

https://drive.google.com/file/d/1gTlIvwtevA983F822YWkwJqHUSK04kT1/view?usp=sharing

**Comment by kakusato** [comment]
What happened after that?

**Comment by kahnivore** [comment]
Interesting, it does seem to occur with your stream (i.e. not firing the finished playing event a second time after rewinding a little). We need to investigate why this is happening and will get back to you.

**Comment by kakusato** [comment]
Shared with.

https://drive.google.com/file/d/1gTlIvwtevA983F822YWkwJqHUSK04kT1/view?usp=sharing

**Comment by AndrewRH** [comment]
Thanks, we have reproduced and fixed the issue.

Updated script is attached here:
[MediaPlayer_Events.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8804854/MediaPlayer_Events.zip)

This fix will go into the next release 2.5.2

Thanks for reporting this!

**Comment by Chris-RH** [comment]
Hi @kakusato 
Version 2.5.2 has been released, so please let us know if the update has fixed the problem, thank you :)
Kind regards,
Chris

**Comment by Chris-RH** [comment]
Please reopen if this is still a problem

**Comment by sieutungbi** [comment]
@Chris-RH I can confirm, the bug still happend in 2.5.7 ultra version, in my case it's does not fire StartedSeeking and FinishedSeeking, or maybe anything else, when i seek the video (streaming m3u8) on android, i only see event started, stalled, unstalled. in IOS it work fine.
