### ISSUE TITLE
Cant' get AvPro video to work with High Sierra (opnegl)

### ISSUE THREAD

**Issue by filipzaw** [RenderHeads/UnityPlugin-AVProVideo#1125]
Problem description:

Warning     :  OpenGL not supported 
Video          :  AVpro video dllnotfoundException

avpro isn't working at all on highsirre macbooks it say the above I have followed those  steps
and it didn't fix it :
If you just want standalone builds to be able to run on older versions of macOS, you need to do the following:

Make sure you're using Unity 2019 or later
Make sure the iOS Build Support module is installed
In the Build Settings dialog, make sure "Create Xcode Project" is checked
In the Player Settings inspector:
In the Other Settings section
Add AVPROVIDEO_SUPPORT_MACOSX_10_14_3_AND_OLDER to "Scripting Define Symbols"
Build the project
Check that "Always Embed Swift Standard Libraries" is set to "YES" in the main target's build settings.

Device (which devices are you having the issue with - model, OS version number):

Macbook 13 inch early 2011,macOs High Sierra version 10.13.6

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: v2.4.1 (plugin v2.4.1f1-trial)
Target Platform: Standalone
Unity: v2020.3.23f1 WindowsEditor
OS: Desktop - System Product Name (System manufacturer) - Windows 10  (10.0.19043) 64bit - English
CPU: AMD Ryzen 7 2700X Eight-Core Processor  - 16 threads - 16304KB
GPU: NVIDIA GeForce GTX 960 - NVIDIA - Direct3D 11.0 [level 11.1] - 4053KB - 16384

**Comment by MorrisRH** [comment]
OpenGL is not supported for macOS targets. Please see the documentation [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-macos.html)
