### ISSUE TITLE
Intermittent playback issue with DirectShow

### ISSUE THREAD

**Issue by TecsiAron** [RenderHeads/UnityPlugin-AVProVideo#1128]
**Describe the issue**
Video sometimes fails to play on Windows using DirectShow

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.29f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.4.1 Ultra
 - Operating system version: Windows 11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 1280x720@24.00 36MB

**To Reproduce**
The problem seems completely random. Sometimes the video fails to start. 
The sequence of events when it fails is: MetaDataReady, ReadyToPlay, Started, ResolutionChanged, Staled, and it stays Stalled no matter what I do.
The settings of the player are: DirectShow with everything unchecked, Audio Output set to System Direct. (The problem also occurs with Unity sound). Need to use DirectShow with no hardware decoding for maximum compatibility.
The video is encoded with Handbrake.
The video is loaded from the filesystem with MediaPathType.RelativeToProjectFolder tough problem also occurs in Demo_MediaPlayer if i use the editor to Browse for the media file.
Code opening the video is:
```
private MediaPlayer video;

....

video = gameObject.GetComponent<MediaPlayer>();

....

video.OpenMedia(new MediaPath(".\\Video\\" + path, MediaPathType.RelativeToProjectFolder), false);
```
Have LAVFilters version 0.76.1(latest) also tried with 0.56.2. LAVFilters are set to be the default decoder for h.264 both x86 and x64
Settings Prefered Filters to:
1. LAV Video Decoder
2. LAV Audio Decoder

Seems to resolve the issue, but due to the random nature of the issue, I can't be sure if the problem is solved, or if it's just being temperamental.
**Logs**
Logs offer no usable information.

**Screenshots**

**Videos**
https://edituraedu.ro/uploads/cap1part2.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Sorry for the slow response. Unfortunately don't have a Windows 11 machine to test on currently - does the issue happen with our sample videos/demo scenes as well?

**Comment by TecsiAron** [comment]
Hey, thanks for the response.
Some more test results:
With the sample, video problem does not occur (Fresh start to Unity)
With the sample video, after playing back our video problem occurs as described in my original post.
This time around I tested on Windows 10.
I'm reasonably sure that setting the preferred decoders as to LAV and nothing else seems to resolve the problem.

**Comment by Chris-RH** [comment]
Hi @TecsiAron, I'm just checking, is this problem now fixed for you by setting preferred decoder to LAV or have you had any further issues?

**Comment by TecsiAron** [comment]
The issue is fixed by setting the preferred decoder to LAV. 
Would prefer not to do that because at some point I'd like to deprecate LAV as a requirement as we slowly raise our system requirements to versions of Windows that support mp4 natively.
