### ISSUE TITLE
Avoid Unity Texture Compression

### ISSUE THREAD

**Issue by bailingoh** [RenderHeads/UnityPlugin-AVProVideo#1129]
May I ask if we can use AV Pro to avoid unity texture compression. Right now our videos are very much pixelated.

https://user-images.githubusercontent.com/63493259/158605453-dec1722c-b3a0-4756-8b75-1589ba97faef.mp4

?

**Comment by AndrewRH** [comment]
I guess so... AVPro Video doesn't recompress the videos, so it should be fine.

You could try the free trial version and test it for yourself.

Does that answer your question?

Thanks,

**Comment by bailingoh** [comment]
Hi, how do i find the free trial? Thank you

**Comment by kahnivore** [comment]
Hiya, you can find the trial version [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases). 

Let us know if that helps.
