### ISSUE TITLE
Can buffer time be set through setting or script?

### ISSUE THREAD

**Issue by 952067477** [RenderHeads/UnityPlugin-AVProVideo#113]
Hi!
How to set buffer time of AVPro? I have a request to make the firstframe of video display as soon as it possible.

**Your Setup (please complete the following information):**
 - Unity version: Unity2017.4.21LTS
 - AVPro Video version: AVPro Video_1.8.7
 - Operating system version:  Windows PC64bit
 - Device model: xiaomi8
 - Video specs (resolution, frame-rate, codec, file size): 
208*1024, 30000kbps, h264, 100M

**Comment by RenderHeadsSte** [comment]
@952067477 Apologies, I am not sure what you are asking for help with.  Could you provide more information?

- What platform are you using - xiaomi 8 phone, so Android?
- Is this is on Android, what API path are you using (MediaPlayer or ExoPlayer) ?
- Where are you loading your video from - local, remote (is it streamed) ?

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.
