### ISSUE TITLE
java.lang.NullPointerException-Android

### ISSUE THREAD

**Issue by joywater** [RenderHeads/UnityPlugin-AVProVideo#1130]
java.lang.NullPointerException

Attempt to invoke virtual method 'void android.media.MediaPlayer.reset()' on a null object reference

解析原始
1
com.renderheads.AVPro.Video.Player_MediaPlayer$1.run(Player_MediaPlayer.java:1)
2
java.lang.Thread.run(Thread.java:919)

**Comment by RenderHeadsSte** [comment]
In order to be able to offer support we require all the requested information outlined in the template when you open an issue.
