### ISSUE TITLE
video can't play 

### ISSUE THREAD

**Issue by rikensonaniNB** [RenderHeads/UnityPlugin-AVProVideo#1131]
**Describe the issue**
i am using latest package and i am trying to play video with url in android but i am getting this error 
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources

**Comment by RenderHeadsSte** [comment]
In order to be able to offer support we require all the requested information outlined in the template when you open an issue.

**Comment by rikensonaniNB** [comment]
i am using latest ultra package and i am trying to play video with url on windows or android but i am getting this error and my video is can't playing please check and find any issue then let me know

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources

hear is my video url

https://s3-congnito-file-upload-demo.s3.ap-southeast-1.amazonaws.com/3021.014pickedMedia1.mov

i think mov file not support on windows and android. so can we have other format file convert to supported format file?

**Comment by kahnivore** [comment]
MOV is not supported on Android. See [supported formats](https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html). We have also put together these [encoding notes](https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html) which could be useful for you. 

Let us know if this helps.

**Comment by rikensonaniNB** [comment]
also i am checking supported formats and encoding notes i see MOV is not supported on android. but can you add features to any other not supported file Auto convert into supported format and play this media file?

**Comment by kahnivore** [comment]
Converting format is not a feature of AVPro Video. If you need something to auto-convert and play on all devices Unity Video Player might be your best bet.
