### ISSUE TITLE
[Windows] Interlaced video stuttering with MediaFoundation

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProVideo#1132]
Playing an interlaced video with MediaFoundation stutters.

We have been using DirectShow which has been robust.  However, because of the lack of Unity Audio support, we're forced to switch to MediaFoundation.  We are noticing issues with other codecs, but primarily are concerned with getting HAP to work.

 - Unity version: 2019.4.36f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.4.1f1-ultra
 - Operating system version: Windows 10/11
 - Video specs (resolution, frame-rate, codec, file size): HAP 1920x1080 59.94i

1. Load the demo scene Demo_MediaPlayer
2. Set video player engine to MediaFoundation
3. Play video and observe choppiness
4. Set video player engine to DirectShow
5. Play video and observe that it is smooth

** Sample videos **

https://www.dropbox.com/s/l0lm4fjxn90gtnv/Creek%20Rise-1080i2997%20-%20HAP.mov?dl=0 
HAP loads, stutters

https://www.dropbox.com/s/y0idg05gfhjkyyk/Creek%20Rise-1080i30.mp4?dl=0 
AVC - loads, very choppy

**Comment by v2k** [comment]
An observation with a 1920x1080@29.97i video:

DirectShow plays smoothly at 29-30 FPS
MediaFoundation is choppy at 25-27 FPS

**Comment by Chris-RH** [comment]
Hi @v2k, 
Unfortunately, as you have seen, interlaced videos will not play smoothly in windows unless you are using Directshow.  Are you able to deinterlace your video?

**Comment by v2k** [comment]
No, and we need media foundation for audio extraction.  

I think that HAP sample that fails above might actually be de-interlaced from the interlaced source. 

Are you running into difficulty solving interlaced video playback?

**Comment by kahnivore** [comment]
@v2k interlaced videos will report framerate at half the playback rate, because interlaced doubles the frame rate and has half the scan lines per frame. Interlaced videos being choppy on Media Foundation and WinRT is a known issue and is unfortunately not something we can fix.

**Comment by v2k** [comment]
That first sample video is deinterlaced, shouldn't it playback smoothly?

**Comment by kahnivore** [comment]
Hi @v2k 

If I increase parallel/preroll frame count it seems to play back more smoothly using Media Foundation. If I test it in VLC it looks similarly jittery in the highest-motion section of the video, which suggests perhaps there aren't enough frames/video information for smooth playback/not really a problem with the player. Do you have any other footage to test with? Perhaps at 60fps?

**Comment by kahnivore** [comment]
Closing due to lack of response, feel free to reopen if needed
