### ISSUE TITLE
Bug by seek

### ISSUE THREAD

**Issue by Georgeswearl** [RenderHeads/UnityPlugin-AVProVideo#1138]
**Describe the issue**
We use AVPro in our unity app to show VR videos. We use the latest version of AVPro 2.4.1. We have encountered the following problem.

The Steam version of our app runs on PC.
When watching an 8K video from a stream (from CDN), the user tries to fast forward. The video switches to the desired point. After buffering, the video continues to play for 1 second. After that, a freeze occurs and the FPS drops for another 1-2 seconds. And only after that it is reproduced normally in normal mode.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.32 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.4.1
 - Operating system version: Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 8K, HEVC

**To Reproduce**
1. Launch any video stream in 8K quality
2. Fast forward the video anywhere
3. Buffering will start
4. After successful buffering, the video will start playing from the current point
4. But after a second, the video will stop (no buffering occurs). This is our problem
5. After another second, the video continues to play without problems.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
@Georgeswearl 
Do any of those suggestions help?

**Comment by Georgeswearl** [comment]
We test videos with your decoding requirements. Not finished yet, but as soon as there are results, I will definitely let you know. Thank you.

**Comment by Chris-RH** [comment]
Are there any issues when you stream it through something like VLC?
