### ISSUE TITLE
AVPRO audio is not heard from UnityAudioLisner（android）

### ISSUE THREAD

**Issue by M1033** [RenderHeads/UnityPlugin-AVProVideo#1140]
Hi,

I'm currently using a trial version of AVPRO.

I have a question about building to Android.
MediaPlayer audio cannot be played in Unity Audio Lisner.
Can this be resolved by purchasing the retail version?
I'll buy the supported version as soon as I find a solution, so please let me know.

Thank you so much for making a wonderful asset.

**Comment by kahnivore** [comment]
Hi there, thanks for your support!  

Have you tried out our Demo_MediaPlayer scene? Perhaps you're missing an [Audio Output component](https://www.renderheads.com/content/docs/AVProVideo/articles/component-audio-output.html)?

**Comment by M1033** [comment]
Thanks for the support. As you wrote, I didn't have enough Audio Output components.
I bought an Android output version.

**Comment by kahnivore** [comment]
Thanks for your response, is this issue resolved for you?

**Comment by M1033** [comment]
I'm sorry. Now that it's resolved, close the ticket.
