### ISSUE TITLE
WebGL + dash: exception thrown when approaching end of video

### ISSUE THREAD

**Issue by ArturAtMental** [RenderHeads/UnityPlugin-AVProVideo#1141]
**Describe the issue**
This is a continuation of https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/404. We are also hitting this error when a stream nears the end. On our end, it causes a significant delay between the video visibly ending and the application getting notified. 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.18f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core 2.4.1
 - Operating system version: WebGL on latest Chrome & Firefox
 - Device model: WebGL on latest Chrome & Firefox
 - Video specs (resolution, frame-rate, codec, file size): 1080p dash stream
Using DashJS version 4.3.0 (DashJS V2.x seemed to not load the content)

**To Reproduce**
1. Play 2 videos in a row: play, reach the end, dispose of the player, create a new player and play 2nd video
2. 2nd video quite consistently exhibits 5-10 second delay followed by exception error in the console
3. No specific video, any 2 videos exhibit the issue

**Logs**

**Console log message after 1st video finishes:**

Debug.js:169 [38757][StreamProcessor][video] Adjusting buffering time 17.259999999999998 because of gap in the manifest. Adjusting time by -0.3399990000000024 
S @ Debug.js:169
_ @ Debug.js:132
se @ StreamProcessor.js:456
ae @ StreamProcessor.js:406
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
L @ ScheduleController.js:179
setTimeout (async)
M @ ScheduleController.js:102
B @ ScheduleController.js:371
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
Ee @ BufferController.js:1011
Q @ BufferController.js:312
(anonymous) @ BufferController.js:250
Promise.then (async)
z @ BufferController.js:249
V @ BufferController.js:210
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
v @ FragmentController.js:154
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
_ @ FragmentModel.js:284
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
r @ FragmentLoader.js:92
success @ FragmentLoader.js:119
onload @ HTTPLoader.js:224
load (async)
load @ XHRLoader.js:82
P @ HTTPLoader.js:303
load @ HTTPLoader.js:349
load @ URLLoader.js:67
load @ FragmentLoader.js:101
(anonymous) @ FragmentModel.js:219
executeRequest @ FragmentModel.js:207
ie @ StreamProcessor.js:380
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
L @ ScheduleController.js:168
setTimeout (async)
M @ ScheduleController.js:102
(anonymous) @ StreamProcessor.js:311
Promise.then (async)
(anonymous) @ StreamProcessor.js:305
Promise.then (async)
(anonymous) @ StreamProcessor.js:282
prepareInnerPeriodPlaybackSeeking @ StreamProcessor.js:269
(anonymous) @ StreamController.js:548
(anonymous) @ StreamController.js:547
ye @ StreamController.js:492
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
te @ PlaybackController.js:522
seeking (async)
(anonymous) @ VideoModel.js:110
v @ VideoModel.js:413
setCurrentTime @ VideoModel.js:94
le @ PlaybackController.js:580
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
(anonymous) @ StreamController.js:817
setInterval (async)
e @ StreamController.js:815
(anonymous) @ StreamController.js:259
Promise.then (async)
(anonymous) @ StreamController.js:257
oe @ StreamController.js:212
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
attemptSync @ TimeSyncController.js:159
(anonymous) @ StreamController.js:1191
Promise.then (async)
Ue @ StreamController.js:1189
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
I @ ManifestUpdater.js:222
N @ ManifestUpdater.js:243
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
m @ ManifestLoader.js:89
(anonymous) @ EventBus.js:124
trigger @ EventBus.js:124
g @ XlinkController.js:193
h @ XlinkController.js:128
g @ XlinkController.js:189
h @ XlinkController.js:128
resolveManifestOnLoad @ XlinkController.js:103
success @ ManifestLoader.js:199
onload @ HTTPLoader.js:224
load (async)
load @ XHRLoader.js:82
P @ HTTPLoader.js:303
load @ HTTPLoader.js:349
load @ URLLoader.js:67
load @ ManifestLoader.js:113
load @ StreamController.js:1339
Me @ MediaPlayer.js:2217
Ie @ MediaPlayer.js:1770
initialize @ MediaPlayer.js:367
_AVPPlayerInsertVideoElement @ WebGL.framework.js.gz:2
[...]

**Exception logged when reaching end of 2nd video:**

Debug.js:169 [84747][SourceBufferSink][video] getAllBufferRanges exception: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source. 

S | @ | Debug.js:169
-- | -- | --
  | E | @ | Debug.js:128
  | getAllBufferRanges | @ | SourceBufferSink.js:275
  | ne | @ | BufferController.js:589
  | (anonymous) | @ | BufferController.js:646
  | re | @ | BufferController.js:660
  | J | @ | BufferController.js:575
  | (anonymous) | @ | EventBus.js:124
  | trigger | @ | EventBus.js:124
  | re | @ | PlaybackController.js:535
  | timeupdate (async) |   |  
  | _AVPPlayerClose | @ | WebGL.framework.js.gz:2

[...]

**Screenshots**
Available privately upon request

**Videos**
Available privately upon request

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Available privately upon request

**Comment by Chris-RH** [comment]
Thankyou, we will look into this.

**Comment by Chris-RH** [comment]
Hi @ArturAtMental 
1. How does it run in the editor?
2. Do you get the exact same error message for both Chrome and FireFox?
3. Have you tried it on Microsoft Edge?
4. Have you tested it with the browser versions here: https://www.renderheads.com/content/docs/AVProVideo/articles/platform-webgl.html#troubleshooting
5. Have you tested it with a stream from a different source?

**Comment by Chris-RH** [comment]
Hi @ArturAtMental,
Would you please be able to post some of your code with regards to: 
end of video/close player/open new player/play video
Thanks

**Comment by ArturAtMental** [comment]
Hi,

I am not able to send the code or give you access to the code base, unfortunately. We've switched away from using AVPro but would be glad to try it again if there's a chance this could get fixed. If you could email me directly, or find and connect with me on Linked In, I could maybe find a way to help you repro the issue. 

Best,

A.

**Comment by Chris-RH** [comment]
Hi,
We don't officially support WebGL, so I'm glad that you've been able to find something else to meet your needs.  Best of luck for your future endeavors.
Kind regards,
Chris
