### ISSUE TITLE
Which edition should I purchase if target platform is WebGL?

### ISSUE THREAD

**Issue by bodinmon** [RenderHeads/UnityPlugin-AVProVideo#1143]
Hi,

I'm finding the solution to play .m3u8 hls video for our WebGL project. 
(yes, I'm aware that it not officially support)
after I downloaded a trial version for testing with my project, It's working as I expected. so I decide to purchase a full version.

I see that there's Core, Windows, Android, Mac edition available to purchase. Which one is suit my need? 

If I puchase Core-Windows edition, Is it able to play .m3u8 as same as in a trial version?

Thanks in advance & Best regards,
Bodin

**Comment by kahnivore** [comment]
Yeah, the Core Windows Edition should suit your needs. If you ever need any of the [Ultra Edition features](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions) at a later stage you can always upgrade at that time. 

Does that help?

**Comment by bodinmon** [comment]
> 

Perfect! 
Thank you very much for your reply.
