### ISSUE TITLE
Problem with basic authentication for HoloLens

### ISSUE THREAD

**Issue by cpollok-benntec** [RenderHeads/UnityPlugin-AVProVideo#1145]
**Question**
Hello,
I was wondering if the asset supports showing the HoloLens livestream via accessible via the API URL:
https://<IP_ADDRESS>/api/holographic/stream/live.mp4 

I tried using the Trial Version and put the URL as the source and added a custom HTTP header (for authentication) under the Windows platform settings in the Media Player component of the Demo_MediaPlayer scene. But when trying to either press the Load button or entering Play Mode, I get an error message ("[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.") or just nothing happens (aside from the log that the URL is being opened.)
I am also wondering if and how this would handle the certificate stuff, since the API is only accessible via https.

Please let me know if it's possible to stream the HoloLens' view (normal camera and holograms) to Unity.
(In the end I want to use this on Android. So if this is a problem, let me know.)

Thank you.

**Comment by kahnivore** [comment]
Hi there, 

I'm not sure we've tried live streaming from HoloLens, but don't see why this wouldn't be possible. 

Are you testing this on Windows? If so, perhaps you could change the API from Media Foundation to WinRT - which has better streaming performance and compatibility for livestreams (as noted [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#windows)). HTTP headers are only supported (on Windows) using the WinRT API, so suspect this has something to do with your issue - see [content protection](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html). 

Note that support differs per platform, although livestreams and HTTP headers are supported on Android as well.

**Comment by cpollok-benntec** [comment]
Hi,
thanks for getting back so quickly.
I now tried the following: Create a new 3D project, switch to Android Build Target and set the custom HTTP header under the Platform Specific settings for Windows and Android.
When I hit the Load button or enter the Play mode I get the same error message. The stream is working fine in a browser, however.

**Comment by kahnivore** [comment]
Great, re WinRT. Will wait to hear from you re your Android target device.

**Comment by cpollok-benntec** [comment]
So, in logcat I get an error from the Exoplayer. Seems to be regarding the SSL connection. I will just copy all the messages from the application below. But since it does not really format well, I will list the main trace:

- Playback error
- com.google.android.exoplr2avp.ExoPlaybackException: Source error
- Caused by: com.google.android.exoplr2avp.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
- Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
- Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
- Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.




2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal Playback error
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal   com.google.android.exoplr2avp.ExoPlaybackException: Source error
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at android.os.Handler.dispatchMessage(Handler.java:102)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at android.os.Looper.loopOnce(Looper.java:226)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at android.os.Looper.loop(Looper.java:313)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at android.os.HandlerThread.run(HandlerThread.java:67)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal   Caused by: com.google.android.exoplr2avp.upstream.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:365)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.upstream.StatsDataSource.open(StatsDataSource.java:84)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:409)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at java.lang.Thread.run(Thread.java:920)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal   Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:858)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:731)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:241)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:636)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:533)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.google.android.exoplr2avp.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:359)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       ... 7 more
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal   Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:255)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       ... 29 more
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal   Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2022.04.06 10:48:45.443 10374 10506 Error ExoPlayerImplInternal       ... 42 more

**Comment by kahnivore** [comment]
Are you sure you set the headers in the  Android specific options? Did you set internet access to 'require' in player settings?

**Comment by cpollok-benntec** [comment]
Yes to both. I just checked again. Does the asset require actual internet access? Because the Android device will only ever be in a local Wifi network.
I added a Custom header "AUTHORIZATION" with "Basic <base64-encoded credentials>" under both the Windows and Android sections.

**Comment by kahnivore** [comment]
Have you not specified the username and password? See [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html#custom-http-headers)

**Comment by cpollok-benntec** [comment]
Strange.. I thought I typed "Basic <base64-encoded credentials> in the previous comment...
Anyway, yes I did. But only encoded, not in cleartext.
Tried that now as well. Same errors.

**Comment by Chris-RH** [comment]
Hi, are you still having a problem with this?

**Comment by Ste-RH** [comment]
We shall be closing this issue soon due to a lack of response (@cpollok-benntec)

**Comment by cpollok-benntec** [comment]
Hi, just to get back to you: We have opted for another approach to our problem (completely different, so no streaming anymore).
This was done in part because we could not get it working with AVProVideo. So the problem is still there.

**Comment by Ste-RH** [comment]
Closing issue.  Hopefully if this is a problem for another developer in the future we can get some more info, test scenarios, re-open, fix.
