### ISSUE TITLE
[iOS] When playback of Loop Video URL is finished, seek again from the middle and then play

### ISSUE THREAD

**Issue by Smaet** [RenderHeads/UnityPlugin-AVProVideo#1148]
**Describe the issue**

 - When #Loop Video URL is played, it is played again after searching in the middle at the end of the play, but I have checked the log where it is suspected, but the cause is unknown, I checked it by recording the log on the **Seek** side and the **Video Event** side.
 - If it doesn't happen after a certain amount of repetition, it stops again and repeats from the beginning, and the phenomenon occurs

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.32f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.4.1
 - Operating system version:  iOS
 - Device model: iPhone 13(iOS 15.1.1), iPhoneXS(iOS 15.4), iPhone 12Pro(iOS 15.1), iPhone 13mmini(iOS 15.2)
 - Video specs (resolution, frame-rate, codec, file size): https://f58054c8a1fe41578a1ca586b0186763.azureedge.net/a74d8786-1b2d-43af-bb58-b5cb28a1c8a6/104dc218-9a4b-4542-9fde-f2e2dfbc.ism/manifest(audio-only=false,format=m3u8-aapl-v3).m3u8#loop

**Comment by Chris-RH** [comment]
Sorry, I'm not sure that I understand the issue.  
1. Is this a continuation of #1147? If so we can close this and continue there. 
2. Do you mean that the video doesn't automatically loop at the end, but will loop if you rewind it first?

**Comment by Smaet** [comment]
> Sorry, I'm not sure that I understand the issue.
> 
> 1. Is this a continuation of [[iOS] When playing Loop Video URL, the loop does not loop and pauses when playback ends #1147](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1147)? If so we can close this and continue there.
> 2. Do you mean that the video doesn't automatically loop at the end, but will loop if you rewind it first?

1. i think so
2. It is true that the video is looped at the end, but sometimes it is paused or played in the middle.

**Comment by Chris-RH** [comment]
Hi @Smaet,
In the mediaplayer, is playback set to loop?
