### ISSUE TITLE
How to change the initial skybox color?

### ISSUE THREAD

**Issue by parandham03** [RenderHeads/UnityPlugin-AVProVideo#1149]
Problem description:

Before loading the video on skybox, the skybox is in grey colour. If I replay the video the skybox is in black colour.
Is it possible to keep one colour all the time?

Device (which devices are you having the issue with - model, OS version number):

Device: Oculus Quest

System Information:

AVPro Video: v2.4.1 (plugin v2.4.1f1-core)
Target Platform: Android
Unity: v2019.2.13f1 WindowsEditor

**Comment by Chris-RH** [comment]
Hi,
Setting the default skybox is pretty straight forward.

1. (Main Menu) Assets -> Create -> Material
2. Set this material to whatever colour you want
3. In the Shader option at the top of the Material panel select one of the Skybox options
4. (Main Menu) Window ->Rendering ->Lighting 
5. Go to the Environment tab
6. Drag your new material to the Skybox Material option
7. Now you should easily be able to alter your initial skybox pretty easily

Let me know if this helps

**Comment by parandham03** [comment]
Hi,
Yes, I have followed the above steps. I applied "AVProVideo/Skybox/Sphere" material. In this case, before loading the video, the skybox is grey in colour. Is it possible to change that grey colour?

**Comment by Chris-RH** [comment]
Hi, yes I see what you mean there. 

What you need to do is change the default texture. In the DisplayComponents demo, for example you would do the following:
If you got to the properties of Skybox-ApplytoMaterial - In the ApplytoMaterial section, under Display it says Default Texture.  This defaults to grey if none are selected, so what you can do is choose a new texture to put here instead.

To create a new texture, you can open any art software (MS Paint is fine!). For a plain colour a 50x50 pixel canvas is fine. Fill it with whatever colour you'd like and save it as a .PNG file.  Save it to wherever you keep your unity textures.  Then just drag it to the Default Texture box as above.

Has this helped at all?

**Comment by Chris-RH** [comment]
Hi @parandham03, I'm just checking in to see if this solution is working for you?
