### ISSUE TITLE
MediaPlayer.Control is null on iOS

### ISSUE THREAD

**Issue by paatz04** [RenderHeads/UnityPlugin-AVProVideo#115]
On iOS MediaPlayer.Control is null - and it stays null when for example:

   while (videoPlayer == null || videoPlayer.Control == null || !videoPlayer.Control.CanPlay())
            yield return new WaitForSeconds(0.2f);

 - Unity version: 2019.1.8f
 - AVPro Video version: 1.10
 - Operating system version: iOS 12
 - Device model:  iPhone SE
 - Video specs (resolution, frame-rate, codec, file size): 1080p H264 mp4 25-30fps

**To Reproduce**
1. Video Player is on auto load
2. Load new scene at runtime
3. MediaPlayer.control remains null
4. Can't call Play() or start the playback

It works when the scene is build directly without transitioning scene before -

**Comment by MorrisRH** [comment]
For MediaPlayer.Control to remain null suggests Start hasn't been called on the MediaPlayer instance. Can you confirm that the object the media player is attached to is enabled and Start is being called?

**Comment by paatz04** [comment]
Thank you - I badly assumed/thought Load was command that gets the playback engine up and running. It works now !
