### ISSUE TITLE
Video fails to play from Vimeo

### ISSUE THREAD

**Issue by francescocalculli** [RenderHeads/UnityPlugin-AVProVideo#1153]
**Describe the issue**
When I try to stream a video from Vimeo to AVPro using VimeoSDK, I get the following error on some videos:

"[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug: LogError (object) "

I have tried to do various researches and to apply the various proposed solutions but to no avail. What could be the problem?

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.29f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): core
 - Operating system version: 
 - Device model: Windows 10

**Logs**
```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1255)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:683)
```

**Videos**
[https://vimeo.com/684338210](https://vimeo.com/684338210)

**Comment by Chris-RH** [comment]
1. What are the specs of the video?
2. Have you managed to play any other smaller videos from vimeo?
3. Have you followed this suggested setup? https://github.com/vimeo/vimeo-unity-sdk#streaming-with-avpro-video-and-vimeo

**Comment by francescocalculli** [comment]
> Ciao, grazie per il tuo messaggio, ho solo alcune domande.
> 
> 1. Quali sono le specifiche del video?
> 2. Sei riuscito a riprodurre altri video più piccoli da vimeo?
> 3. Hai seguito questa configurazione suggerita? https://github.com/vimeo/vimeo-unity-sdk#streaming-with-avpro-video-and-vimeo

1. The video is streaming from vimeo. When it was loaded it was a 1920x1080 222mb mp4.
2. Yes, some videos work, some don't. For example this works https://vimeo.com/619845074
3. Yes

The problem is that up to a few weeks all the videos worked ... And nothing has been changed

**Comment by AndrewRH** [comment]
I would ask Vimeo for assistance.  Their Unity plugin hasn't been updated in years, so there's a chance it's no longer totally compatible.
