### ISSUE TITLE
Solved! Black screen in Quest 2 \ Obsolete API with AVPro 1.11.3 \ Unity 2019.4.3f1

### ISSUE THREAD

**Issue by mvmvm** [RenderHeads/UnityPlugin-AVProVideo#1154]
Hello everyone, when i open a year ago-project after reinstalling windows in unity 2019.4.3, when building for Quest2, such errors about obsollete API come out, each time is about different scripts
while in unity it works as it should, in quest 2 the application starts and shows background picture, but videos are not played
I tried to change the version of both unity and visual studio, it didn’t help

It looks like the problem is in the player or other assets (I tried an older version of oculus integration pack, but it didn’t help, other errors come out)

how can you get around this problem, you need to get the result in a short time, and then spend time learning the new version. thanks!

 - Unity version:  2019.4.3f1
 - AVPro Video version 1.11.3 ultra
 - Operating system version: Win 10
 - Device model: Quest 2 v39

![photo1650332785](https://user-images.githubusercontent.com/72887338/163903784-ca9071ad-5d52-4f83-8eda-86f49f350391.jpeg)

**Comment by Chris-RH** [comment]
Hi, Have you tried reinstalling the plugin?

**Comment by kahnivore** [comment]
It would also be worthwhile to upgrade your project to the latest version of 1.x (1.11.7) to see if the problem still persists in that version.

**Comment by mvmvm** [comment]
So, the solution is simply add this string to Android Manifest file after <application

android:requestLegacyExternalStorage="true" 

you can ignore yellow warnings in Unity about obsolete API in AVPro and Oculus Packages

____

If your app targets Android 10 (API level 29) or lower, you can temporarily opt out of scoped storage in your production app. If you target Android 10, however, you need to set the value of requestLegacyExternalStorage to true in your app's manifest file:

https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage

**Comment by Chris-RH** [comment]
Thanks for the update :)
