### ISSUE TITLE
Video Playing with Watermark on Oculus Quest 2

### ISSUE THREAD

**Issue by CaseyManning** [RenderHeads/UnityPlugin-AVProVideo#1155]
**Describe the issue**
The paid android version of the plugin plays videos with a watermark when deployed to Oculus Quest 2

**Your Setup:**
 - Unity version: 2020.3.27f1
 - AVPro Video version: script v1.11.7, plugin v1.11.6t, Android version
 - Operating system version: Built on Windows 10, deployed to Android version 10
 - Device model: Oculus Quest 2, system version 26242800497100000
 - Video specs (resolution, frame-rate, codec, file size): 4096x2048 MP4 video, 174MB, 18 seconds

**Logs**
attached file: [UnityBuildLogs.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8517799/UnityBuildLogs.txt)

**Plugin Invoice Number:** IN010000382372

**Comment by Chris-RH** [comment]
Hi Casey,

It looks like the android version hasn't updated properly and it is still using the trial version.  Could you try deleting the whole of the  Android plugin folder files (\Assets\Plugins\Android\) and re-importing just the Android package please?
Delete everything in the image below:
![androidv1](https://user-images.githubusercontent.com/102963025/164192460-35b68289-4ce4-4a45-a60b-c2b082425ece.png)

Please let us know if that helps.
Kind regards,
Chris

**Comment by CaseyManning** [comment]
Hi Chris,

Thanks for the response. I deleted all the files in \Assets\Plugins\Android and re-imported just the android folder from the package manager as described. However, now the video does not play at all, and I instead get the following error:

> Autoconnected Player AndroidJavaException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.VirtualHumanInteractionLab.VirtualBecomesReality-i_IdGtIdv-LYLfNUuu-UGg==/base.apk"],nativeLibraryDirectories=[/data/app/com.VirtualHumanInteractionLab.VirtualBecomesReality-i_IdGtIdv-LYLfNUuu-UGg==/lib/arm64, /data/app/com.VirtualHumanInteractionLab.VirtualBecomesReality-i_IdGtIdv-LYLfNUuu-UGg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libAVProLocal.so"

**Comment by Chris-RH** [comment]
hmm, that doesn't sound right.  Have you followed the upgrade steps?  https://www.renderheads.com/content/docs/AVProVideo/articles/install.html#upgrade-steps

Is the android version that you purchased definitely version 1 like your trial pack?
