### ISSUE TITLE
Video not playing on Android

### ISSUE THREAD

**Issue by DaveXR** [RenderHeads/UnityPlugin-AVProVideo#1156]
**Describe the issue**
We are using Pico Neo G2 and Pico Neo 3 devices, Unity 2019.1.12 with AVPro to play 360 degree videos in headsets. This works in most cases, but we're looking at a few headsets that have problems. It may be corrupt files, or it may be threading/timing???
https://github.com/google/ExoPlayer/issues/4738

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.12
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): enteprise
 - Operating system version: 8.1
 - Device model: Pico Neo G2
 - Video specs (resolution, frame-rate, codec, file size): various

**To Reproduce**
Spurious. Just start video playing.

**Logs**
{"@t":"2022-04-20T20:50:59.191","@mt":"AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners()' on a null object reference, External Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners()' on a null object reference\ncom.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:681)\ncom.google.android.exoplayer2.ExoPlayerImpl.stop(ExoPlayerImpl.java:358)\ncom.google.android.exoplayer2.SimpleExoPlayer.stop(SimpleExoPlayer.java:777)\ncom.google.android.exoplayer2.SimpleExoPlayer.stop(SimpleExoPlayer.java:772)\ncom.RenderHeads.AVProVideo.AVProVideoExoPlayer._stop(AVProVideoExoPlayer.java:843)\ncom.RenderHeads.AVProVideo.AVProVideoExoPlayer.CloseVideoOnPlayer(AVProVideoExoPlayer.java:394)\ncom.RenderHeads.AVProVideo.AVProVideoPlayer.CloseVideo(AVProVideoPlayer.java:408)\ncom.unity3d.player.UnityPlayer.nativeRender(Native Method)\ncom.unity3d.player.UnityPlayer.c(Unknown Source:0)\ncom.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:88)\nandroid.os.Handler.dispatchMessage(Handler.java:102)\nandroid.os.Looper.loop(Looper.java:164)\ncom.unity3d.player.UnityPlayer$e.run(Unknown Source:20)\nUnityEngine.AndroidJNISafe.CheckException () (at <38e8064b9da648b081580a64b9f8f73e>:0)\nUnityEngine.AndroidJNISafe.CallVoidMethod (System.IntPtr obj, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <38e8064b9da648b081580a64b9f8f73e>:0)\nUnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) (at <38e8064b9da648b081580a64b9f8f73e>:0)\nUnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args) (at <38e8064b9da648b081580a64b9f8f73e>:0)\nRenderHeads.Media.AVProVideo.AndroidMediaPlayer.CloseVideo () (at <4065a214fb0e4ed483ecb212dc991748>:0)\nRenderHeads.Media.AVProVideo.MediaPlayer.CloseVideo () (at <4065a214fb0e4ed483ecb212dc991748>:0)\nRenderHeads.Media.AVProVideo.MediaPlayer.OpenVideoFromFile () (at <4065a214fb0e4ed483ecb212dc991748>:0)\nRenderHeads.Media.AVProVideo.MediaPlayer.OpenVideoFromFile (RenderHeads.Media.AVProVideo.MediaPlayer+FileLocation location, System.String path, System.Boolean autoPlay) (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Presentation.VideoPlayerBehaviour.LoadVideo (System.String videoUri, System.Boolean looping) (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Controllers.VideoPlayerController.LoadVideo (System.String videoUri, System.Collections.Generic.Dictionary`2[TKey,TValue] subtitleAssets, System.Boolean looping) (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Controllers.ClipController.InitializePlayer (System.String baseClipPath) (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Controllers.FullClipMaker.MakeClip (myapp.Player.Model.ClipData data, myapp.Player.Model.API api, myapp.Player.Model.ClipState clipState, System.String baseClipPath) (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Controllers.ActivityController.PlayCurrentClip () (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Controllers.ActivityController.StartActivity () (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Controllers.ActivityController.OnSceneLoaded (System.String sceneName) (at <4065a214fb0e4ed483ecb212dc991748>:0)\nmyapp.Player.Presentation.ActivityBaseBehaviour.SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <4065a214fb0e4ed483ecb212dc991748>:0)\nUnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <38e8064b9da648b081580a64b9f8f73e>:0)\n","logger":"com.myapp.player.core.PlayerCore","@l":"ERROR","stacktrace":"java.lang.Exception: AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners()' on a null object reference\n\tat com.myapp.player.core.PlayerCore.externalLog(PlayerCore.java:477)\n\tat com.unity3d.player.UnityPlayer.nativeRender(Native Method)\n\tat com.unity3d.player.UnityPlayer.c(Unknown Source:0)\n\tat com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:88)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)\n"}

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Do you have 'minify' enabled in your project settings?  If so, see notes on that [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html).

**Comment by DaveXR** [comment]
No, that's not it. It works most of the time, and on most headsets. So it's
not getting stripped out. The spurious nature of the problem seems like
some sort of timing issue, and I found that post about ExoPlayer and
threads, maybe it's something about how AvPro calls ExoPlayer?

**Comment by kahnivore** [comment]
Have you found any way to reproduce it? i.e. specific devices or specific videos that cause the issue? (I know you said it's spurious but just to double check there aren't any more clues).

**Comment by RenderHeadsSte** [comment]
Some more thoughts/questions on this issue.

Are you calling open or close on anything but the main thread, or maybe from the AVPro Video events system?

Have you tried to reproduce the issue using one of the supplied AVPro Video demo scenes as the base?

**Comment by Chris-RH** [comment]
Hi @DaveXR,
We've just released an new version of AVPro Video, which is updated to use ExoPlayer v2.17.1.  Could you try updating to this and seeing if it helps? Also, have you tried any of the above ways to reproduce it?  We'd love an update from you to see if we can fix this.
Kind regards,
Chris

**Comment by Ste-RH** [comment]
FYI @DaveXR.  We have released AVPro Video v2.5.0, which uses the updated ExoPlayer v2.17.1

**Comment by Chris-RH** [comment]
Hi @DaveXR, 
Have you had a chance to upgrade to the latest version of AVPro, with the updated version of ExoPlayer?  Also, have you tried any of the above ways to reproduce it? 
We should be receiving some Pico devices within the next week, so would be able to do a bit more testing.
We'd love an update from you to see if we can fix this.
Kind regards,
Chris

**Comment by Chris-RH** [comment]
Hi @DaveXR 
Are you still having problems with this or can I close the issue?

**Comment by DaveXR** [comment]
Hi, the issue seems to have gone away with other code changes we made and
is no longer reproducible. We will be upgrading to the latest AVPro in a
few months.
Thanks!

**Comment by Chris-RH** [comment]
Awesome, glad to hear it! :D
