### ISSUE TITLE
Pico playing 3D Stereo Video Produce double shadow phenomenon

### ISSUE THREAD

**Issue by wangyin1111** [RenderHeads/UnityPlugin-AVProVideo#1157]
我使用PicoNeo3做为终端设备播放视频，发现在播放3D立体视频(左右视频)的时候，影像边缘会出现重影，就像在电影院中裸眼观看3D视频是一样的情况，我该如何解决这个问题呢？ 
我使用的SDK是最新试用版 ：AVPro 视频 v2.4.1 - 2022 年 2 月 26 日
以上应用使用Unity2020.3开发
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
I use PicoNeo3 as the terminal device to play the video, and find that when PLAYING the 3D stereo video (left and right video), the image edge will be double, just like watching the 3D video in the cinema with naked eyes. How should I solve this problem?
The SDK I am using is the latest trial version: AVPro Video V2.4.1 - Feb 26, 2022
The above applications are developed using Unity2020.3

**Comment by kahnivore** [comment]
Do you have the [update multipass stereo component](https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html) included in your scene? 

Have you tested your video in the 360 stereo demo scene?

**Comment by neonm3** [comment]
I had similar issue with Pico, but I'm on legacy 2019.2.15f1 and G2 4K. I fixed it by changing function within UpdateMultiStereoPass script:

		private static bool IsMultiPassVrEnabled()
		{
			return true;
		}
		
Seems Pico SDK doesn't set up XRSettings for stereo rendering as expected. @kahnivore  you might want to address that on your side.

**Comment by wangyin1111** [comment]
> 您的场景中是否包含[更新的多通道立体声组件？](https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html)
> 
> 您是否在 360 度立体演示场景中测试过您的视频？

No, because my video is flat stereo video (left and right format), SO I just use demo-mediaplarer scene to play, and set Media Reference/Media Hints/Alpha Packing to Left Right.

**Comment by wangyin1111** [comment]
> 
I feel that we have the same problem, but the problem is not solved after I adjust it according to your method. The display effect is still the same as before

**Comment by kahnivore** [comment]
@wangyin1111 could you share your media so that we can test it please?

**Comment by kahnivore** [comment]
@neonm3 thanks for the note on this

**Comment by Chris-RH** [comment]
Hi @wangyin1111, 
If this is still a problem, could you send us a copy of the file you are trying to play, please?  Email  [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com). Please include the issue number (1157) in the subject

**Comment by Chris-RH** [comment]
Hi @wangyin1111,
If this is still a problem, could you send us a copy of the file you are trying to play, please? Email [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com). Please include the issue number (1157) in the subject

**Comment by Ste-RH** [comment]
> > 
> 
> I feel that we have the same problem, but the problem is not solved after I adjust it according to your method. The display effect is still the same as before

You still need the UpdateMultiPassStereo component in your scene if you are playing back a stereo video even if it is on a flat plane.  You also need to use the correct AVPro Video shader.  This is the one I am using to test her.:

![image](https://user-images.githubusercontent.com/46531149/169055185-bf70fe50-543d-4e7e-af84-9ed90cd3c78b.png)

I have a Pico Neo 2 in hand now and I am using the AVPro Video 360 demo scene with just a shader change to the above.  I have also tried changing the sphere mesh to a plane.  I tick the following option to ensure the left/right stereo rendering is working correctly:

![image](https://user-images.githubusercontent.com/46531149/169056055-1fed463f-9ecb-4c73-8254-df6a3ba09e97.png)

I get the exact correct result I expect.

One final note.  I am using the 'Unity XR Platform SDK (Legacy)' Pico SDK (https://developer.pico-interactive.com/sdk/index?id=8&device_id=1&platform_id=1).  Is that the one you are using?  Or are you using the newer one (that is for the Neo 3 only)?

**Comment by Ste-RH** [comment]
We have some shader changes coming in the next version that address some fringe stereo playback issues.  I hope these have a positive effect on the issue you are seeing.

**Comment by Ste-RH** [comment]
AVPro Video v2.5.2 has been released. Extra information has been added to the documentation. You can find that [here](https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html).

I am closing this issue due to lack of response.  Please do update us or re-open the issue should it still be a problem for you.
