### ISSUE TITLE
Ios 	How to play Negative Rates on ios?

### ISSUE THREAD

**Issue by isbyfen** [RenderHeads/UnityPlugin-AVProVideo#1158]
How to play Negative Rates on ios?
What media sources are supported?

**Comment by kahnivore** [comment]
Sorry, what exactly do you mean?

**Comment by isbyfen** [comment]
![image](https://user-images.githubusercontent.com/103488158/164681290-043c1ac6-f769-46be-b668-c80d795f727d.png)

**Comment by isbyfen** [comment]
i want playback rate=-1 on ios

**Comment by kahnivore** [comment]
Thanks for the clarification. 

All supported media should be fine when played at a rate of -1 locally - streaming media however might present some unexpected behaviour.

**Comment by isbyfen** [comment]
When  playback rate=-1, the video is stuck and cannot be played smoothly. 
When  playback rate=-1,What media sources  can be played as smoothly like playback rate=1?

**Comment by kahnivore** [comment]
Could you share your media with us so we can test it? As said above, it should work if it's being played locally.

**Comment by isbyfen** [comment]
![image](https://user-images.githubusercontent.com/103488158/164684052-f1959d66-f447-4901-9f05-b36d9d765254.png)
None of them can.

**Comment by kahnivore** [comment]
You'll need to encode media specifically for playing in reverse as explained [here ](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-seeking-playbackrate.html#optimal-encoding).

**Comment by isbyfen** [comment]
Can playback rate=-1 and playback rate=-1 play smoothly when I change the playback rate at any time?

**Comment by Chris-RH** [comment]
Could you try encoding the media with the following:

ffmpeg -i input.mp4 -c:v libx264 -g 12 -bf 2 -c:a copy output.mp4

**Comment by isbyfen** [comment]
Ok, I'll try



发自我的iPhone


------------------ Original ------------------
From: Chris-RH ***@***.***&gt;
Date: Fri,Apr 22,2022 6:20 PM
To: RenderHeads/UnityPlugin-AVProVideo ***@***.***&gt;
Cc: isbyfen ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [RenderHeads/UnityPlugin-AVProVideo] Ios  How to play NegativeRates on ios? (Issue #1158)
