### ISSUE TITLE
Video Plays on editor but doesnt play with exported to Windows

### ISSUE THREAD

**Issue by icochea1** [RenderHeads/UnityPlugin-AVProVideo#1159]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: Unity 2020.3.11f1
 - AVPro Video version: AVPro Video - Core Windows Edition Latest Version
 - Operating system version: Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 
What am I doing wrong? It works perfectly on Editor but it doesnt work outside editor. It does work outside editor with the demo videos but not with mine which is only 10MB heavy and mp4.

**Comment by kahnivore** [comment]
Hi @icochea1 

Where are you storing your video that isn't playing? The video cannot be played from the /Assets folder unless it is in Streaming Assets. 

Please see [these notes](https://www.renderheads.com/content/docs/AVProVideo/articles/faq.html) on how to troubleshoot this. If you don't find your answer here, please send over your media for us to take a look. 

Thanks!

**Comment by Chris-RH** [comment]
Closing due to lack of response, feel free to reopen if needed
