### ISSUE TITLE
Facebook 360 Audio not Spatial

### ISSUE THREAD

**Issue by ferdinandhartke** [RenderHeads/UnityPlugin-AVProVideo#1160]
**Describe the issue**
Spatial Aoudio playback of First order Ambix is not working. While Playback I Hear the W Channel on the Left Ear and the X Channel on The Right ear. Moving the Head Changes nothing. But I am not sure if it should work in the first Place, becausue I am just using the Core Version.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.33.f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core Android
 - Operating system version:  Android 
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): Stereoscopic 5760x5760 mkv with 4 channel Opus Audio. 30fps

**To Reproduce**
1.  Open 360 Stereo Demo Scene
2. Set Head Transform to Main Camera
3. Create MKV with FFMPEG commands from the Documentation. (ffmpeg -y -i input.mov -c:v copy -sample_fmt s16 -acodec libopus -mapping_family 255 output.mkv)
4. [optional] Check that there are 4 Audio Channels present in your video with Audacity or Audition
5. Prepare Media Reference an load Video file to device
6. Set Those Settings in Media Player 
![grafik](https://user-images.githubusercontent.com/33265468/165068293-eac2da00-5d4d-47da-8033-8928deb52b24.png)

7. Build And Run
8. Watch Video with Track1 left and Track 2 right. Track 3 and 4 are missing.

I have tried Many settings regarding the Audio Output, but nothings seems to Influence the Listenig experience. 

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @ferdinandhartke 
Yes, spatial audio is a feature of the Ultra Edition
https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions

**Comment by ferdinandhartke** [comment]
Thank you, but is there a to retreive all four Audio Channels when I set "Audio Output" "Unity" or is the Core Edition limited to Stereo (or two-channel) Playback?

**Comment by RenderHeadsSte** [comment]
At the moment...audio piping of FB360 audio to Unity is not supported in any edition of AVPro Video
