### ISSUE TITLE
3D audio doesn't work with WinRT API and sometimes crashes Unity

### ISSUE THREAD

**Issue by cprenoveau-illogika** [RenderHeads/UnityPlugin-AVProVideo#1161]
**Describe the issue**
When selecting WinRT API, 3D audio no longer works. As a side note, Unity will sometimes crash with a Runtime Error when exiting play mode.

Unity version: 2020.3.26
AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.4.1-trial
Operating system version: Windows 10
Device model: PC
Video specs (resolution, frame-rate, codec, file size): 1280x720 24fps mp4 150mb

**To Reproduce**
Open AVProVideo/Demos/Scenes/Demo_MediaPlayer
Select MediaPlayer and set media source to path: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
Select WinRT API from Platform Specific->Windows
Check Support Positional Audio from Audio Output
Set Spatial Blend of Audio Source to 1

**Screenshots**
![image](https://user-images.githubusercontent.com/98769382/165117882-3879a958-ba8f-43c9-9499-d69afc67b6be.png)

**Comment by Chris-RH** [comment]
Hi @cprenoveau-illogika,
Unfortunately Positional Output can't be done using WinRT as it doesn't allow you to pipe the audio back to Unity for playback for the Audio Output component.  This is not something that we can change. It can only be done with Media Foundation.
See: https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---windows
