### ISSUE TITLE
MOV File not supported in android 

### ISSUE THREAD

**Issue by rikensonaniNB** [RenderHeads/UnityPlugin-AVProVideo#1163]
**Question**
We are uploading .mov file to AWS server and trying to play it on android device but .mov not support in android. we are using ultrapackage of AVPro.so if there is any possibility we can paly .mov file than please update.

**Comment by Chris-RH** [comment]
Hi @rikensonaniNB,
Unfortunately .MOV is not currently supported on android, so you would need to convert the files as there is nothing that we can do about that.
https://exoplayer.dev/supported-formats.html

**Comment by rikensonaniNB** [comment]
thank you 
any option available on AvPro to convert .MOV file to MP4 file?

**Comment by Chris-RH** [comment]
Hi @rikensonaniNB, 
I'm afraid that AvPro is for decoding only.  You would need to use something like FFmpeg to do that first.
https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html#fmpeg-basics

**Comment by rikensonaniNB** [comment]
if any decoding using FFmpeg example available the please share with me.
thank you for support

**Comment by Chris-RH** [comment]
Hi, the efficacy of ffmpeg depends a lot on the files that you are using (codecs used etc) and what you are looking for in your output.
You could try this:  ffmpeg -i input.mov -vcodec copy -acodec copy output.mp4

**Comment by rikensonaniNB** [comment]
ok let me try
thank you for support
