### ISSUE TITLE
I bought Android version of player for 200 dollars, but I still have watermark and "Purchase full version" button

### ISSUE THREAD

**Issue by semyhran** [RenderHeads/UnityPlugin-AVProVideo#1164]
**Question**

**Comment by Chris-RH** [comment]
Hi @semyhran ,
Have you followed the upgrade instructions here: https://www.renderheads.com/content/docs/AVProVideo/articles/install.html ?

**Comment by kahnivore** [comment]
Also note that Android-only edition will still show a watermark on non-Android devices, i.e. in the editor, but will be removed from Android builds.
