### ISSUE TITLE
Pico G2 Pro / 4K - 3D videos with URP not working

### ISSUE THREAD

**Issue by ennio-inflight** [RenderHeads/UnityPlugin-AVProVideo#1165]
Hello, we had AVPro working perfectly fine with our project with the latest pico SDK (Legacy) and without URP. The problem started to appear when we decided to move to URP, suddenly the 3D videos stopped working, it just looks like the image constantly switches between left and right eye depending on how you move your head.
To make this work before URP we had to do a manual change on the UpdateMultiPassStereo.cs so it ignores the IsMultiPassVrEnabled since this seems to not be working with Pico Plugin. In URP we still have this change.

Do you know which is the reason that makes this not work properly?

My setup:
 - Unity version: 2020.3.18f1
 - AVPro Video version:  2.4.1 Ultra Edition
 - Device model: Pico G2 Pro / 4K

**Comment by Chris-RH** [comment]
Hi @ennio-inflight, I'm sorry that you are having problems

1. Have you tried the Demo_360Stereo with your device?
2. Are you able to test it with a different headset?
3. What are the specs for your videos?

**Comment by ennio-inflight** [comment]
Hi @Chris-RH, thanks for the reply.
1. We don't have the AVPro demos in the current build, we can try later today, and I'll tell you something ASAP.
2. No, since we only use pico for this product in particular there is no use case for us in that sense.
3. We tried all our videos and none of the 3D ones work as expected (TOP_BOTTOM nor LEFT_RIGHT). For example one of them is the Big Buck Bunny free example from their website which is:
resolution: 1920x2160
frame-rate: 60 FPS
codec: H264 - MPEG-4 AVC
file size: 490 MB

Just to mention, as I forgot to say in the first comment, once the migration to URP was done, I double-check that the Material had the proper shader applied to it and yes, everything is right. With the Debug Tint enabled you can see in the headset how it constantly changes between red and green for both eyes instead of just having one color tint per eye.

Thanks again and if you need more information just ask and we will try to respond as soon as possible!

**Comment by Chris-RH** [comment]
Great thanks.
Could you also please try adding the "'Tracked Pose Driver" component and see if that helps? Thank you

**Comment by ennio-inflight** [comment]
Just checked and we already have a Tracked Pose Driver, so with that, we have the same result.
With this settings if it helps:
![image](https://user-images.githubusercontent.com/28703581/166462583-d3819bfc-cdef-47dd-9f25-6da070eef345.png)

**Comment by RenderHeadsSte** [comment]
We have reproduced what you are seeing on a Quest 2 using our 360 stereo demo scene.

**Comment by RenderHeadsSte** [comment]
Possible fix...

In the 'UpdateMultiPassStereo' script...

If you change the:

private void LateUpdate()

...to the Update():

private void Update()

...that fixes things here.

**Comment by RenderHeadsSte** [comment]
Possible fix @ennio-inflight ...

In the 'UpdateMultiPassStereo' script...

If you change the:

private void LateUpdate()

...to just an Update()  (i.e. remove the Late):

private void Update()

...that fixes things here.

**Comment by ennio-inflight** [comment]
Hi @RenderHeadsSte I tried to rename the LateUpdate to Update as you suggested but sadly it still happens at my side...

**Comment by RenderHeadsSte** [comment]
Hmm. Ok. Must have been something else I changed along the way in conjunction with that. Let me work back a bit and get back to you. The important thing I found was that in that LateUpdate function the view matrix was never changing. In the shader that is one of the main components used to determine which eye is being rendered for each vertex/pixel.

**Comment by RenderHeadsSte** [comment]
Do you have the 'UpdateMultiPassStereo' component in your scene @ennio-inflight ? (and have it hooked up to your camera)

**Comment by ennio-inflight** [comment]
Hi @RenderHeadsSte I just wanted to provide more information regarding the issue:
- Yes, (I just saw your last comment) I have the UpdateMultiPassStereo in my scene, but I cannot attach the camera from the editor, in our product the camera does not exists in that scene, it is already there and the scene containing the player and everything needed is being loaded dynamically. I attach the camera to the component via scripting. Do you think that can be causing the issue? it is weird since without URP that was working just fine.
- With the LateUpdate->Update change, I tried the Demo Scene, making a build just with that scene available and it renders properly each eye (tested with the debug tint). This is very odd since it looks like it works in the demo scene but not in my scene as it was before the URP.

Let me explain the main differences between the example and our product setup in case you can see something that I'm missing:
- The first difference is that the demo is a 360 3D video and the problem I'm reproducing is with a normal 3D video (the big buck bunny with topdown that I explained before) So for my plane object I'm using the AVProVideo/Unlit/Opaque (texture+color+fog+stereo support) Shader.
- As I mentioned above, I attach the camera to the UpdateMultiPassStereo in runtime, since my XRRig is being carried along with the experience by additive scenes. Just to remember, this was working properly before URP so I don't know if it really has something to do.
- The media is also loaded dynamically with the OpenMedia function. I also set the stereo via script with the MediaHints.

Do you think any of this can be the main reason the LateUpdate->Update fix is not working for my scene but it is in the demo?

**Comment by RenderHeadsSte** [comment]
Ahh, oki...I have been under the impression you were using the InsideSphere shader.  I will switch shader.

**Comment by ennio-inflight** [comment]
Hi @RenderHeadsSte, how is it going? did you manage to reproduce the error with the other shader?

**Comment by RenderHeadsSte** [comment]
I did reproduce it.  It is very strange that the fix we found works in one setup (using the 360 shader) and not in the other. 
 I did manage to find a solution, but it is far from perfect and we are looking into a better solution.

The problem is that the TrackedPoseDriver component appears to actually only update the attached camera at render time and not (as it states) at update time as well (depending on settings in the component).  The solution I found worked was to action the UpdateMultiPassStereo 'update' on a pre render event.  I will attach a modified script that should work as, at least, a temporary solution.  Please note that this updated component MUST be attached to the camera GO (as should the TrackedPoseDriver I believe).

Grab the modified version here: [UpdateMultiPassStereo.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8650636/UpdateMultiPassStereo.zip)

![image](https://user-images.githubusercontent.com/46531149/167387659-05611e3a-e451-41ee-aeab-16bd2a12e42e.png)

**Comment by ennio-inflight** [comment]
Thanks @RenderHeadsSte I'll try this as soon as possible today!

**Comment by ennio-inflight** [comment]
Hi again @RenderHeadsSte, I did try everything as you said but sadly it only makes the flickering faster regardless of the movement, maybe the fix does not work in a 3DoF headset as Pico G2 and it works for you in Oculus with 6DoF.
Thank you again for all your help, I don't know how long it will take you guys to find a new/better solution for this case but I'll keep an eye on the updates so we can upgrade our product to URP.

**Comment by ennio-inflight** [comment]
This is a small fragment of the log taken directly from the device's Logcat.
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8653172/log.txt)

**Comment by RenderHeadsSte** [comment]
That shows that the camera view matrix and position is being updated, and therefore the shader is getting the correct values.  This is used to determine if we are rendering the left or right eye.  So unless the built in Unity shader variable '_WorldSpaceCameraPos' is incorrect...!?  As that is the only other variable used along side the above...

Maybe I could send you an APK to test on the Pico?

**Comment by RenderHeadsSte** [comment]
I have sent you an email with a link to a test APK @ennio-inflight

**Comment by ennio-inflight** [comment]
Hi @Ste-RH, sorry for taking time to answer. I'll try the APK as soon as possible.

**Comment by ennio-inflight** [comment]
Hi and sorry again for this late response, I did install the app on my pico device, but I cannot run it. It crashes un launch. I think that it must be built with the Legacy Pico SDK plugin and Unity XR to make it work there...

**Comment by Ste-RH** [comment]
I have a Pico G2 4K on it's way to me this week.  Will investigate when I get it in hand.

**Comment by Ste-RH** [comment]
I have a Pico Neo 2 in hand and it works exactly as I would expect with zero changes to the AVPro Video package.  So maybe the issue is limited to the G2 4K?  I should be getting one of those in hand before the end of the week so will feedback again when I have it.

**Comment by ennio-inflight** [comment]
hum... maybe it is related to the G2, I have a NEO as well so I can do some tests in there. I'll keep you updated, thanks again for all your help @Ste-RH

**Comment by dalkia** [comment]
Hi! Jumping in into the issue, since I'm having the same problem using Unity 2020.3.23 and URP.

Downloading the latest AVPro package on Package Manager,  just replacing the UpdateMultiPassStereo.cs with the one provided in the zip,  and using the Demo_360Stereo scene, I have the flickering problem on an Oculus Quest 2.

Is there something that I'm missing?

Thanks!

**Comment by Ste-RH** [comment]
@dalkia Did you move the UpdateMultiPassStereo component onto the camera GameObject?

**Comment by Ste-RH** [comment]
@dalkia Did you move the UpdateMultiPassStereo component onto the camera GameObject?

For completeness, on a Quest2, you probably want the 'IsMultiPasVrEnabled' to:

![image](https://user-images.githubusercontent.com/46531149/170028104-53708922-82a5-4230-8576-ac094bf7f251.png)

**Comment by Ste-RH** [comment]
Think we might have tracked down the issue.  A question along with a shader update to test...

1) @ennio-inflight Can you tell me what your 'Main Camera -> Environment -> Background Type' is set to?

2) @ennio-inflight @dalkia Can you replace the following shader with the one I am attaching and see if the problem is solved? (note that you will still need to use the updated UpdateMultiPassStereo script posted previously in this issue thread)

[AVProVideo.cginc.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8764288/AVProVideo.cginc.zip)

Please do let me know the results as I really want to know if this is a Pico issue or a Unity bug!

**Comment by dalkia** [comment]
Hey @Ste-RH !

I updated the MultiPassVrEnabled method, but it kept not working.

Nonetheless, using the shader, and combining it with the UpdateMultiPassStereo, it now works! Both in Unity and the Quest 2.

Thank you so much for your help

**Comment by ennio-inflight** [comment]
Hi @Ste-RH, we are using "Skybox" as our Background Type. Just saw the message, I'll try the shader and tell you something!

**Comment by ennio-inflight** [comment]
Hi again @Ste-RH, it worked! with your shader and the UpdateMultiPassStereo script it finally worked on PICO G2 Pro/4K.
Thank you again for all your help!! Just one question, this will be added future versions? or it is better that I keep track of these changes if I want to update AVPro.

**Comment by Ste-RH** [comment]
Good news that we are on the right path!

We are looking at a more rounded solution and this _should_ be included in the next version.  I will let you know.

Thanks for your feedback.

**Comment by Ste-RH** [comment]
@ennio-inflight @dalkia

Would you be able to test this shader change?  It is a straight copy over the top of the existing one found in: \Assets\AVProVideo\Runtime\Shaders\

[AVProVideo.cginc.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8778138/AVProVideo.cginc.zip)

**Comment by ennio-inflight** [comment]
Sorry @Ste-RH I was out since Thursday. I'll try the shader later today and let you know!

**Comment by ennio-inflight** [comment]
I had to double-check because something was weird with the new shader. In my device, with the new shader both eyes render the same eye, so there is no 3D effect. With the shader you sent 6 days ago it works as expected. I hope this helps you guys. Maybe (unity_StereoEyeIndex == 0) does not work properly in Pico G2 headsets...

**Comment by Ste-RH** [comment]
@ennio-inflight 

Are you able to add this logging to a Pico G2 4K build and paste the output for me please?

```
string output = "XR supportedDevices = ";
foreach( string str in UnityEngine.XR.XRSettings.supportedDevices )   { output += str + ","; }
output += " | ";

List<UnityEngine.XR.InputDevice> inputDevices = new List<UnityEngine.XR.InputDevice>();
UnityEngine.XR.InputDevices.GetDevices(inputDevices);
foreach (UnityEngine.XR.InputDevice device in inputDevices ) { output += device.name + ","; }

Debug.Log( output );

```

**Comment by Ste-RH** [comment]
@ennio-inflight Can you add the following to your UpdateMultiPassStereo.cs script please and report what the log output is please?

        void Start()
        {
            LogXRDeviceDetails();
        }

        private void LogXRDeviceDetails()
        {
            string logOutput = "[AVProVideo] XR Device details: UnityEngine.XR.XRSettings.loadedDeviceName = " + UnityEngine.XR.XRSettings.loadedDeviceName + " | supportedDevices = ";

            string[] aSupportedDevices = UnityEngine.XR.XRSettings.supportedDevices;
            int iNumSupportedDevices = aSupportedDevices.Length;
            for( int i = 0; i < iNumSupportedDevices; ++i )
            {
                logOutput += aSupportedDevices[ i ];
                if( i < ( iNumSupportedDevices - 1 ) )
                {
                    logOutput += ", ";
                }
            }


            List<UnityEngine.XR.InputDevice> inputDevices = new List<UnityEngine.XR.InputDevice>();
            UnityEngine.XR.InputDevices.GetDevices( inputDevices );
            int iNumDevices = inputDevices.Count;
            if( iNumDevices > 0 )
            {
                logOutput += " | XR Devices = ";

                for ( int i = 0; i < iNumDevices; ++i )
                {
                    logOutput += inputDevices[ i ].name;
                    if( i < ( iNumDevices -1 ) )
                    {
                        logOutput += ", ";
                    }
                }
            }

            UnityEngine.XR.InputDevice headDevice = UnityEngine.XR.InputDevices.GetDeviceAtXRNode( UnityEngine.XR.XRNode.Head );
            if( headDevice != null )
            {
                logOutput += " | headDevice name = " + headDevice.name + ", manufacturer = " + headDevice.manufacturer;
            }

            Debug.Log( logOutput );
        }

**Comment by ennio-inflight** [comment]
Hey @Ste-RH, we are in the middle of a spike at the company, as soon as we finish I'll add that log and send you the results, sorry for the inconvenience. I'll try today, but if I can't I'll try tomorrow first thing!

**Comment by Ste-RH** [comment]
Thanks @ennio-inflight.  We are likely to release a new build today with a 'best guess' fix.  Pretty confident it will work for you :)

**Comment by dalkia** [comment]
Hey @Ste-RH! Do you need assistance testing something on Quest 2?

**Comment by Ste-RH** [comment]
Thanks for the offer @dalkia , but I have a Quest 2 in hand.

**Comment by ennio-inflight** [comment]
@Ste-RH @Chris-RH I manage to get some time to try this. I'm attaching here the log:
`06-08 09:54:29.536  3220  3242 I Unity   : [AVProVideo] XR Device details: UnityEngine.XR.XRSettings.loadedDeviceName = PicoXR Display | supportedDevices = oculus input, oculus display, PicoXR Input, PicoXR Display | XR Devices = Pico G2 | headDevice name = Pico G2, manufacturer =`
Manufacturer is empty, it is not like I forgot to copy it hehehehe

**Comment by Ste-RH** [comment]
Thanks @ennio-inflight 

AVPro Video v2.5.2 has been released.  Extra information has been added to the documentation.  You can find that [here](https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html).

Please let us know if your issue has been addressed @ennio-inflight @dalkia

**Comment by ennio-inflight** [comment]
Thank you again for all the work guys. We are going to organize a new release using the new version of AVPro. I'll keep you updated!

**Comment by ennio-inflight** [comment]
Hi again guys, I just wanted to let you know that we are going to release a new version of our product with URP and AVPro with the 3D working as expected 🎉 
Thank you for all the support. I hope you have a lovely day!
Cheers!

**Comment by Chris-RH** [comment]
Thank you so much for the update! I'm so glad that we could help :) Have a great day :)
