### ISSUE TITLE
Android - Load video path for second time cause media player broken

### ISSUE THREAD

**Issue by Remon8399** [RenderHeads/UnityPlugin-AVProVideo#1166]
**Describe the issue**
Setup OpenMedia on load button with no auto play, when load the video for first time it will working well as usual, but if user didn't play the video manually and load video for second time, the MediaPlayer component won't working and there no video will show up. I do create empty project and import only AVPro plugin, and able to use Demo Scene to reproduce the issue.

Link for project: https://drive.google.com/file/d/1FgwI6Njw6CUDKCnAaHduyGwiObvmj9A4/view?usp=sharing
Link for apk: https://drive.google.com/file/d/1ZxI-EtOXW_9ps_Kao8BfU2hSRB2R-uIe/view?usp=sharing

**Your Setup (please complete the following information):**
 - Unity version: Unity 2020.3.29f1 (64-bit)
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): UnityPlugin-AVProVideo-v2.4.1-Trial
 - Operating system version: Android 11
 - Device model: Asus Rog Phone 5
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
MediaPlayer component load video url for first time with no autoplay (working)
- If user play the video manually, and load the video for second time (working)
- If user doesn't play the video manually, and load the video for second time (not working and broken)

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @Remon8399 , we're looking into this for you.

**Comment by RenderHeadsSte** [comment]
A fix will be offered for this issue in the next build (v2.5.0) which we hope to release in the coming days.

**Comment by RenderHeadsSte** [comment]
@Remon8399 we have published a new build with the fix in.  Please do let us know if this addresses the issue.

**Comment by Remon8399** [comment]
Thanks, its working now
