### ISSUE TITLE
[MacOS] AvPro crashes on MacOs with intel chip, when built with XCode 13.3.1

### ISSUE THREAD

**Issue by christianYS** [RenderHeads/UnityPlugin-AVProVideo#1167]
**Describe the issue**
Builds made with Xcode 13.3.1 with IL2CPP scripting backend crash immediately when trying to play any video on Macbooks with intel chip.
The issue can be reproduced using the vanilla free trial unitypackage
***
**The same build works without issues when played on a Macbook with Apple Silicon chip**
***

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.19f1
 - AVPro Video version: 2.4.1 (enterprise and trial)
 - Operating system version: MacOS Monterey 12.3.1
 - Device model: Macbook Pro 16-inch 2019;
    - Processor 2,3 GHz 8-core Intel Core i9
    - Memory: 16GB
    - Graphics: Intel UHD Graphics 630
 - Xcode version: 13.3.1  (13EE500a)
 - Video specs: The file played in the Demo_MediaPlayer scene
<img width="270" alt="mac_version" src="https://user-images.githubusercontent.com/25147502/166424328-e13c881d-8cd4-4e28-ac24-78adcf231951.png">

**To Reproduce**
1. Create a new Unity project
2. Import the AvPro unitypackage version 2.4.1 (free trial)
3. Build Demo_MediaPlayer scene. Target platform: MacOS; Architecture: Intel 64 bit + Apple Silicon; Scripting backend: IL2CPP

**Logs**
[AvProCrash-2022-05-03-110022.ips.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/8609110/AvProCrash-2022-05-03-110022.ips.txt)

**Screenshots**
<img width="400" alt="Screenshot 2022-05-03 at 11 26 22" src="https://user-images.githubusercontent.com/25147502/166424005-6fefa4e1-2099-4b55-8bb3-e41811c1e54b.png">
<img width="400" alt="Screenshot 2022-05-03 at 11 26 38" src="https://user-images.githubusercontent.com/25147502/166424015-6c73328e-1739-48e7-9f68-dffcb2a19df1.png">

**Comment by MorrisRH** [comment]
Fixed, it was caused by an alignment issue passing data between Unity and the plugin.

**Comment by RenderHeadsSte** [comment]
@christianYS have published a new build with the fix in.  Please do let us know if this addresses the issue.
