### ISSUE TITLE
Multiple console errors when utilizing Timeline Playables

### ISSUE THREAD

**Issue by jessekirbs** [RenderHeads/UnityPlugin-AVProVideo#1174]
I follow the Timeline Playables documentation:

1. Add the Timeline package to your project from the Package Manager.
2. Add the Timeline package assembly Unity.Timeline to the _AVProVideo.Extensions.Timeline assembly definition references.
3. Add AVPRO_PACKAGE_TIMELINE to your player Preprocessor Defines to enable the scripts to be compiled.

And receive multiple console errors:

```
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlAsset.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlBehaviour.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlMixerBehaviour.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(19,41): error CS0246: The type or namespace name 'TrackAsset' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(17,3): error CS0246: The type or namespace name 'TrackClipTypeAttribute' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(17,3): error CS0246: The type or namespace name 'TrackClipType' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(18,3): error CS0246: The type or namespace name 'TrackBindingTypeAttribute' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(18,3): error CS0246: The type or namespace name 'TrackBindingType' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(21,28): error CS0115: 'MediaPlayerControlTrack.CreateTrackMixer(PlayableGraph, GameObject, int)': no suitable method found to override
```

Setup:
Unity 2020.3.30.f1
AVPro Video 2.5.0
MacOS Monterey

To reproduce:

1. Add the Timeline package to your project from the Package Manager.
2. Add the Timeline package assembly Unity.Timeline to the _AVProVideo.Extensions.Timeline assembly definition references.
3. Add AVPRO_PACKAGE_TIMELINE to your player Preprocessor Defines to enable the scripts to be compiled.

Thank you!

**Comment by MorrisRH** [comment]
I was unable to reproduce this with:
- Unity 2020.3.34f1
- AVPro Video 2.5.0 Trial
- macOS Monterey 12.3.1

**Comment by AndrewRH** [comment]
@jessekirbs  perhaps try the answer here to regenerate your project files?
https://stackoverflow.com/questions/63636944/unity-type-or-namespace-name-inputsystem-does-not-exist-in-the-namespace-unit

**Comment by jessekirbs** [comment]
@MorrisRH @AndrewRH I got it working. During the 'Add the Timeline package assembly Unity.Timeline to the _AVProVideo.Extensions.Timeline assembly definition references.' I didn't realize you had to scroll down and hit 'Apply' when adding these references, since I've never had to do that step before. Very sorry for the dumb mistake and I appreciate the support. Might be a good idea to add in docs that you should hit 'Apply' after adding the reference, just in case there are more dumb-dumbs like me out there. Thanks, ya'll!

**Comment by Chris-RH** [comment]
Easy mistake to make, we'll look into adding that to the docs! :) Thanks for letting us know :)
