### ISSUE TITLE
Streaming video from Google Drive

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1176]
Problem description:

I am trying to stream video from Google Drive. The video file is fully accessible to anyone
with the link but everytime I try it gives me a loading error. Is there a way to stream from
google drive or is there a better hosting service that should be used inorder to use the 
streaming features? I did read the section on Streaming on the documentation and tried the
example videos and thought it was a great feature.

Device (which devices are you having the issue with - model, OS version number):

Windows 11

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

Here is a link https://drive.google.com/file/d/1s1H_icdSI42OntfITvO8aJx7yPflBzcD/view?usp=sharing

System Information:

AVPro Video: v2.1.8 (plugin v2.1.8f1-ultra)
Target Platform: Standalone
Unity: v2019.4.16f1 WindowsEditor
OS: Desktop - B550M DS3H AC (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 threads - 32691KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10077KB - 16384

**Comment by kahnivore** [comment]
Hi @Gurwar 

Google Drive isn't really designed for streaming video and AVPro Video cannot play such links, the same goes for Dropbox. 

There are plenty of other hosting services that we do support, such as AWS S3.

Does that help?
