### ISSUE TITLE
[Android] Bugs when setting a audio/text track on HLS video

### ISSUE THREAD

**Issue by christianYS** [RenderHeads/UnityPlugin-AVProVideo#1178]
**Describe the issue**
HLS audio and text tracks aren't set properly on Android using the `.SetActiveAudioTrack()` and `.SetActiveTextTrack()` API.
See the attached video demonstration at the end and the reproduction steps for details.
I will also send you an email with a demo project that exposes the 2 bugs I've found.
Please note that the issues don't reproduce on other platforms. Tested on MacOS, Windows and iOS.
Also, the HLS video plays fine on other HLS-capable video players

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.19f
 - AVPro Video version 2.5.0 Enterprise/Trial
 - Operating system version: Android 12
 - Device model: Pixel 3
 - Built with: Macbook pro 2021 (chip M1), Monterey 12.3.1
 - Video: https://d1b3g720av9q27.cloudfront.net/ys_videos_hls_1200/main/guitar/0/5ec382c4387fd6a1905b2f94/HLS/master_multilang.m3u8

### To Reproduce
1. Load the vanilla AvPro free trial project
2. Set build Platform to Android
3. Load the video url as MediaReference. Configure the MediaPlayer to AutoOpen and AutoPlay
4. Set Video API to ExoPlayer

**Bug 1: Audio track switches to default after setting a text track (and vice versa)**
5. Build & Run for Android
6. Press the "Gear" option button and select any language different than English
7. Observe that the language changes
8. Now select a subtitle track different than English
9. Notice that the text track changes, and audio track is reset to English
10. Now select another audio language
11. Notice that the audio language changes but the subtitles are reset to English

**Bug 2: Audio/Text tracks cannot be set if "Preferred Maximum Resolution" is set to something** 
5. On Android specific MediaPlayer settings, set "Preferred Maximum Resolution" to something different than the default value, for example "1080p"
6. 5. Build & Run for Android
6. Press the "Gear" option button and try to select any audio or subtitle track
7. Notice that neither audio nor text tracks are set.

**Video showcasing the bug**
https://mega.nz/file/CpgkiLyL#LHtEWQNpq5gEa1uXTRCly457F3qPC-kcbiWXa1YsVy0

**Comment by Chris-RH** [comment]
Hi @christianYS, thank you for your thorough report. We will look out for your email.

**Comment by Ste-RH** [comment]
Issue reproduced and a code fix applied.  Hotfix sent to @christianYS to verify desired behaviour is now achieved.  Pending feedback, this will be fixed in v2.5.1.

**Comment by christianYS** [comment]
@Ste-RH Yes, I can confirm that the hotfix works! Awesome job at delivering the fix so quickly, I'm impressed! 🎉

**Comment by Chris-RH** [comment]
V2.5.1 had just been released :)

**Comment by Ste-RH** [comment]
Closing this issue now.  Please do re-open it if you find any knock-on issues.
