### ISSUE TITLE
[Bug?] Inconsistent MediaPlayer.Events on different platforms when opening media

### ISSUE THREAD

**Issue by christianYS** [RenderHeads/UnityPlugin-AVProVideo#1179]
### Describe the issue
I'd expect the events sent through `MediaPlayer.Events` to be somewhat consistent between platforms. Instead, I've noticed a discrepancy in the order of events fired upon starting a video. Especially, the events **MetaDataReady**, **ReadyToPlay**, **FirstFrameReady**, **Started** don't seem to be consistent when opening a media when calling `mediaPlayer.OpenMedia(mediaPath, autoPlay: false)`. In addition, the events don't seem to be consistent even on the same platform when playing different media type (HLS or MP4). [In the documentation](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-events.html) is not explicitly specified what are the differences between platforms. Below I've reported the observed order of events for each platform and media type. 

### Questions
1. What is the expected order for the events [MetaDataReady, ReadyToPlay, FirstFrameReady, Started] on Android, iOS, MacOS, Windows? 
2. Is it expected that **MetadataReady** is not firing on iOS and MacOS when playing HLS videos?
3. What is the most reliable event for safely render the UI and start reproducing the video?
   a. Android it's the only platform where **ReadyToPlay** happens before **MetaDataReady**. And can potentially result in issues when rendering UI, because information like video length is not available, so only for Android I need to wait for both events to arrive.
4. Is it expected that **FirstFrameReady** can happen after **Started**? (observed in Windows)

### Your Setup
 - Unity version: 2020.3.19f
 - AVPro Video version: 2.5.0 Enterprise
 - Devices and operating systems:
    - MacOS Monterey 12.3.1 - Macbook Pro 2021 (M1 chip)
    - Android 12 - Pixel 3
    - iOS 15.3.1 - iPhone 12
    - Windows 11 - Parallels VM running on the same Macbook above
 - Video specs: 
     - HLS: https://d1b3g720av9q27.cloudfront.net/ys_videos_hls_1200/main/guitar/0/5ec382c4387fd6a1905b2f94/HLS/master_multilang.m3u8
     - MP4: https://d3mzlbmn9ukddk.cloudfront.net/tasks/video/cbbc0d3a-4dde-4b0b-8258-934dafa456a2.mp4

### Reproduction
- Setup a scene with a basic MediaPlayer (for example, the Demo_MediaPlayer scene), making sure to disable AutoOpen and AutoPlay
- Add two buttons in the UI: LOAD and PLAY
   - Pressing LOAD calls `mediaPlayer.OpenMedia(mediaPath, autoPlay: false)` where `mediaPath` is a URL pointing to one of the videos listed above
   - Pressing PLAY calls `mediaPlayer.Play()`
- Add a listener to `MediaPlayer.Events` which logs all the received events (I filtered only the relevant ones)

### Logs
```
Android  (ExoPlayer Api, System Direct Audio)

HLS
ReadyToPlay --> MetaDataReady --> FirstFrameReady --> PLAY() --> Started

MP4
ReadyToPlay --> MetaDataReady --> FirstFrameReady --> PLAY() --> Started
```
```
iOS  (System Direct Audio)

HLS
ReadyToPlay --> FirstFrameReady --> PLAY() --> Started

MP4
MetaDataReady --> ReadyToPlay --> FirstFrameReady --> PLAY() --> Started
```
```
MacOS (System Direct Audio)

HLS
ReadyToPlay --> FirstFrameReady --> PLAY() --> Started

MP4
MetaDataReady --> ReadyToPlay --> FirstFrameReady --> PLAY() --> Started
```
```
Windows (MediaFoundation API, SystemDirect Audio)

HLS - RUN 1
MetaDataReady --> ReadyToPlay --> PLAY() --> Started --> FirstFrameReady

HLS - RUN 2
MetaDataReady --> ReadyToPlay --> FirstFrameReady --> PLAY() --> Started

MP4
MetaDataReady --> ReadyToPlay --> FirstFrameReady --> PLAY() --> Started
```

**Comment by Ste-RH** [comment]
Looking into (3a)...

The different ordering on Android is due to ReadyToPlay being dependant on internal plugin variables.  Some of these variables are used to determine MetaDataReady, but c# comes into play as a few of those variables are actually gathered c# side (that are updated from the plugin).  Hence there is a frame delay observed between the ReadyToPlay and MetaDataReady.

I have refactored the nature of the code such that MetaDataReady is done internally to the plugin only now.

The result is that MetaDataReady fires before ReadyToPlay on Android for both HLS and MP4.

This change will be released in v2.5.1 (aim is to release this towards the end of the week).  If you desire it before then just let me know and I will fire over an Enterprise v2.5.0f2.

**Comment by Ste-RH** [comment]
Full answer list:

1. This is platform dependant.  Platforms should be in the same order though.
2. We think there might be a misalignment in what 'MetaDataReady' is between Apple platforms and Windows/Android.  We are looking into this.
3. FirstFrameReady.  Before that there is no guarantee there will be anything rendered.
a). See message above.
4. Yes (on Windows) if you don't wait for FirstFrameReady before you call 'play'.

**Comment by christianYS** [comment]
Thank you for looking into this.
I will wait for the official release of v2.5.1

**Comment by Chris-RH** [comment]
V2.5.1 had just been released :)
