### ISSUE TITLE
[Question] Explain ResolutionChanged event

### ISSUE THREAD

**Issue by christianYS** [RenderHeads/UnityPlugin-AVProVideo#1183]
In the [Events documentation page](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-events.html), `ResolutionChanged` is described as
```
Triggered when a non-looping video has finished playing (not triggered when looping is enabled)
```
which is clearly incorrect. In addition, I have noticed that when ResolutionChanged is fired,  sometimes the value of `player.Info.GetVideoHeight()` is 0. It happens usually when spamming the seek bar. See the attached video that showcases it (look at the number to the right side of the arrow "-->")

Your Setup
- Unity version: 2020.3.19f
- AVPro Video version: 2.5.0 Enterprise
- MacOS Monterey 12.3.1 - Macbook Pro 2021 (M1 chip)

https://user-images.githubusercontent.com/25147502/169493634-5cc72e04-2bf3-4feb-87a2-7ca27a421f2f.mp4

**Comment by Chris-RH** [comment]
Thanks, we'll take a look at the docs. I think something has gone wrong when inserting information.

If the HLS stream includes a non-visual rendition for low bitrates, 0 is completely valid.  Is this causing any issues in your build or is it just something that you noticed?

**Comment by christianYS** [comment]
The HLS stream I've played doesn't have non-visual renditions. [Here's the link](https://d1b3g720av9q27.cloudfront.net/ys_videos_hls_1200/main/guitar/0/5eccc42bce608800c30b00ce/HLS/master_en.m3u8).
The behaviour doesn't cause problems, it is something that I noticed while collecting analytics data, and I wanted to understand why this is happening

**Comment by Chris-RH** [comment]
Sure, no problem.
So, particularly when you are spamming the seek bar, you can get the player into a position where it’s switched from the current resolution but hasn’t yet picked the next one, so you get 0 for a frame.  It might be caused by the fact that it updates the width and height from the video track change and not the actual texture change. I hope that helps.

**Comment by christianYS** [comment]
Thank you for your answer, it is helpful

**Comment by Chris-RH** [comment]
Glad I could help. A curious mind is great! :)
