### ISSUE TITLE
AVProUltra 2.5.0 fails to build on Unity Cloud Build on iOS

### ISSUE THREAD

**Issue by baseclock** [RenderHeads/UnityPlugin-AVProVideo#1184]
**Describe the issue**
It appears we cannot build AVPro Ultra on Unity Cloud build on iOS. It seems UCB is lacking the latest version of XCode to do that. We will be in contact with Unity to upgrade, however we thing you may need to know about that as well.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.32
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.0 Ultra
 - Operating system version: iOS
 - Device model: All iOS
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Make a branch with a project with AVPro 2.5.0 Ultra 
2. Make a Cloud Build configuration with an iOS target for that branch
3. Try to build and observe failure

**Screenshots**
![image](https://user-images.githubusercontent.com/106071977/169794250-e0982b40-b301-4ab6-9da7-39d631dfe1cd.png)

**Comment by Chris-RH** [comment]
Hi @baseclock 
Please could you try updating to version 2.5.1, as we recently fixed a problem with xcode and unity cloud build. Thank you.
