### ISSUE TITLE
GetSpectrumData doesn't work

### ISSUE THREAD

**Issue by HallCai** [RenderHeads/UnityPlugin-AVProVideo#1185]
Problem description:

GetSpectrumData doesn't work

Device (which devices are you having the issue with - model, OS version number):

any phone

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

any

System Information:

AVPro Video: v2.5.1 (plugin v2.5.1f1-core)
Target Platform: Android
Unity: v2021.3.1f1c1 WindowsEditor
OS: Desktop - System Product Name (System manufacturer) - Windows 10  (10.0.19042) 64bit - ChineseSimplified
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 12 threads - 16227KB
GPU: Intel(R) UHD Graphics 630 - Intel - Direct3D 11.0 [level 11.1] - 8113KB - 16384

**Comment by Chris-RH** [comment]
Hi @HallCai,

Are you using positional audio at all?

Could you show me what code you are using for GetSpectrumDate please?

**Comment by HallCai** [comment]
I created a new project, use official demo.Use Demo_MediaPlayer scenes. On Android phones, the audio wave line doesn't jump.I see that GetSpectrumDate gets 0.  then I create new scene, used the Unity  Video Player plug-in to get the GetSpectrumDate is not 0.

**Comment by HallCai** [comment]
in MediaPlayer- Setting -Platform Specific- Android, Change the Audio Output property to Unity to fix this
