### ISSUE TITLE
[2.5.1] Issue of closing media when another video started playing

### ISSUE THREAD

**Issue by PremiumArts** [RenderHeads/UnityPlugin-AVProVideo#1186]
**Describe the issue**

We have a problem that when we have around 20 video player in same scene that we only want only one videoplayer being played on the same time.
When the 1st player is playing then we tried to open and play the 2nd player and close the media of first player at the same time, both UI for showing video shows the 2nd player’s video.
We don’t want all of those video being loaded at the same time which will cause the memory problems.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.19f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.1 Core Edition
 - Operating system version: OSX 12.3.1 iOS 15.4.1
 - Device model: iPad/iPhone
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1.Create 2 Media Player and 2 AVPro uGUI in the scene and set the reference for them.
2.Make a script to attach an event to the 2nd Player that if it’s status became Started, call CloseMedia() on 1st Player
2.Play a web hosted mp4 video on 1st Player.
3.Play another web hosted mp4 video on 2nd Player.
4.2nd video are playing at both AVPro uGUI.
5.Both Unity Editor running on OSX and the built app on iPhone/iPad devices will reproduce this issue.

Here is how we manage to implement it by calling the AVPro Video API.
VideoA.mediaPlayer.OpenMedia(urlA);
VideoA.mediaPlayer.Play();
VideoB.media.Player.OpenMedia(urlB);
OnVideoB.mediaPlayer.Started()=>VideoA.mediaPlayer.CloseMedia();

After above operations, the UI for VideoA showing the VideoB’s video and keeps playing. The UI for showing VideoB’s video looks fine.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
Reference to the project sent to below email

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Chris-RH** [comment]
Hi, thankyou for the emailed project, we will look into this.

**Comment by MorrisRH** [comment]
A fix for this issue will be in the next release.

**Comment by PremiumArts** [comment]
Thanks @MorrisRH 
Do you have any date information about the next release?

**Comment by Chris-RH** [comment]
Hi @PremiumArts 
Version 2.5.2 has been released, so please let us know if the update has fixed the problem, thank you :)
Kind regards,
Chris

**Comment by Chris-RH** [comment]
Please reopen if this is still an issue
