### ISSUE TITLE
How to play uncompressed videos (RGBA/YUV)?

### ISSUE THREAD

**Issue by rumblecoder** [RenderHeads/UnityPlugin-AVProVideo#1188]
According to your list of supported video codecs AVProVideo can play uncompressed RGBA/YUV videos (at least on Windows). I checked the code and the documentation in detail but I could not find any hints how to use this feature.

I already tried to play a AVI-File encoded with huffyuv using FFMPEG but Unity gives me an error: [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

Could you please provide some information how I can play such files? Thank you in advance.

**Comment by rumblecoder** [comment]
Ok, now it works. But I needed to install additional codecs (e.g. K-Lite Codec Pack). Thanks for your help.

**Comment by Chris-RH** [comment]
Awesome, I'm glad its working now :)

**Comment by AndrewRH** [comment]
@rumblecoder  BTW, the LAVFilters codec pack is the one I would recommend.  

Best of luck,
