### ISSUE TITLE
Getting video seconds from Mediaplayer

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1189]
Problem description:

How would you suggest getting the total video in seconds from the media player. I tried
doing this using the information in the basemediaplayer but it returned 0 for seconds. Any
suggestions would be greatly appreciated.

Windows 11

I am running this application on Windows and Android for Oculus.

System Information:

AVPro Video: v2.5.0 (plugin v2.5.0f1-ultra)
Target Platform: Standalone
Unity: v2019.4.16f1 WindowsEditor
OS: Desktop - B550M DS3H AC (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 threads - 32691KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10077KB - 16384

**Comment by Chris-RH** [comment]
Hi @Gurwar,
Try this: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-seeking-playbackrate.html#seeking

**Comment by Gurwar** [comment]
Hey @Chris-RH ,

I tried using the Info object to get the maxframes and maxduration as well but both functions return 0. 
![image](https://user-images.githubusercontent.com/43031012/170290704-ff068d11-f073-4c74-86e6-8f15e4ff271a.png)
![image](https://user-images.githubusercontent.com/43031012/170290766-d8b7e1da-a2dc-4d27-98e8-526a24125364.png)

**Comment by kahnivore** [comment]
Hi @Gurwar 

Have you checked that the video is loaded before you check the duration? 

You might want to wait to check the info until the [isMetaDataReady ](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-events.html) event has fired. 

If this still does not work - could you send us a video of yours to test with?

**Comment by Gurwar** [comment]
@kahnivore Thanks that worked. You can close this thread.
