### ISSUE TITLE
What is the correct way to clear texture after video has finished?

### ISSUE THREAD

**Issue by ImmotionPeterL** [RenderHeads/UnityPlugin-AVProVideo#1192]
Our product allows users to watch many different videos in 360, a user can select a video.. watch it and then select another video. After selecting a second video, for (approximately) 1 frame the last frame of the previous video is displayed. This happens on Android, it doesn't happen in the editor... unsure if it happens on iOS.

What's the correct way to clear/ blank this out? Is there a method in the API to clear it? Or is it a case of having to get the material for each sphere we use and set the colour black?

**Comment by Chris-RH** [comment]
Which version of AVPro Video and Unity are you using?

**Comment by ImmotionPeterL** [comment]
AVPro is 2.2.4
Unity is 2020.3.25

**Comment by Chris-RH** [comment]
1. Upgrade to the latest version of AVPro Video as there have been a few android updates since 2.2.4
2. Try exoplayer
3. Try enabling OES

**Comment by ImmotionPeterL** [comment]
The issue doesn't happen when using Exoplayer. Will need to test for a while before deciding to stick with Exoplayer, we were using Mediaplayer because at the start of development Exoplayer was sometimes resulting in a black video - I've updated to 2.5.1, hopefully that doesn't happen any more.

**Comment by Chris-RH** [comment]
Great, let us know how it goes :)

**Comment by Chris-RH** [comment]
Please reopen if this is still an issue
