### ISSUE TITLE
Video playback fails on IL2CPP Quest build

### ISSUE THREAD

**Issue by Kron0** [RenderHeads/UnityPlugin-AVProVideo#1193]
Problem description:

Oculus App Lab requires an arm64 build, but when switching to IL2CPP backend 
videos no longer work on quest 2 device

Device (which devices are you having the issue with - model, OS version number):

Quest 2

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

HLS MP4 video streams, but applies to all video

System Information:

AVPro Video: v2.5.1 (plugin v2.5.1f1-ultra)
Target Platform: Android
Unity: v2021.2.3f1 WindowsEditor
OS: Desktop - MS-7B18 (Micro-Star International Co., Ltd.) - Windows 10  (10.0.18363) 64bit - English
CPU: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz - 16 threads - 65470KB
GPU: NVIDIA GeForce RTX 2080 SUPER - NVIDIA - Direct3D 11.0 [level 11.1] - 8010KB - 16384

**Comment by Chris-RH** [comment]
1. Does it still play in the editor?
2. Does the application crash or just the video not play?
3. Is the video blank? Is it buffering? Is there audio?
4. Are you using mediaplayer or exoplayer?
5. Do you have any error logs?

**Comment by Ste-RH** [comment]
Additional question:

8. Are you using OES rendering mode/shader?

I have fired up a fresh project in Unity 2021.2.3f1 using AVPro Ultra and the AVPro 360 Demo scene (just the default none OES).  Building in IL2CPP I get video playback without issue.

**Comment by AndrewRH** [comment]
@Ste-RH confirm that's an ARM64-only build?

**Comment by Ste-RH** [comment]
> @Ste-RH confirm that's an ARM64-only build?

I can confirm:

I/Unity: Built from '2021.2/staging' branch, Version '2021.2.3f1 (32358a8527b4)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'

![image](https://user-images.githubusercontent.com/46531149/171186809-b170b4d9-d0e7-49bc-8900-c84dcd15d875.png)

**Comment by Kron0** [comment]
> 

On quest with Oculus plugin?

**Comment by Kron0** [comment]
@Ste-RH Did it work on quest 2 and with which version of the oculus plugin?

**Comment by Kron0** [comment]
Hi, yeah we are using some quite old Oculus code and I can't find which sdk it is exactly. I was also able to spin up a working stereo video player using the latest Avpro version that runs on Quest 2 with il2cpp. I'll update as soon as I can find more information, but I'm not seeing anything in the logs that looks helpful

**Comment by Ste-RH** [comment]
Ok, we will await more information.  Or you could email over a project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com?subject=Issue&nbsp;#1193).  Or send a full log here for us to take a look at in case we can spot something amiss.

**Comment by Chris-RH** [comment]
Hi @Kron0,
Are you still having problems with this? It would be helpful if you could email over a project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com?subject=Issue%C2%A0%231193) or send a full log here. Thank you

**Comment by Chris-RH** [comment]
Closing this for now due to lack of response from OP, please reopen if this is still an issue for you
