### ISSUE TITLE
DX12 Unity 2022.1.2f1 Crash

### ISSUE THREAD

**Issue by VRS3DGuru2** [RenderHeads/UnityPlugin-AVProVideo#1195]
Problem description:

Unity Editor Crashes on HDRP pipeline as soon as playback with AVPro begins to render. 
Issue happens regardless of what shader or type of video is being played.
Using DirectX 12.

Device (which devices are you having the issue with - model, OS version number):

Windows 10, current OS

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):
Have tried multiple videos, codecs, render settings, etc.
System Information:

AVPro Video: v2.5.1 (plugin v2.5.1f1-ultra)
Target Platform: Standalone
Unity: v2022.1.2f1 WindowsEditor
OS: Desktop - HP Z6 G4 Workstation (HP) - Windows 10  (10.0.19042) 64bit - English
CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz - 48 threads - 96983KB
GPU: NVIDIA Quadro RTX 6000 - NVIDIA - Direct3D 12 [level 12.1] - 24276KB - 16384

**Comment by Chris-RH** [comment]
Hi @VRS3DGuru2 
1. How does it react with a fresh HDRP unity project running one of the AVPro demo scenes?
2. What do you see here when you get the crash? Task Manager -> Performance -> GPU Decode
3. Are there any error messages at all?

**Comment by VRS3DGuru2** [comment]
rolling back to direct11 solves the crash, however the rest of my scenes require directx 12 render features.  there are crash logs.

-Tony W

-Tony

Sent from my Verizon, Samsung Galaxy smartphone personal email account.
________________________________

**Comment by Chris-RH** [comment]
Hi @VRS3DGuru2,
I've tested it in 2022.1.2 and it crashed as described.
I've also tested it in it works in 2020.3.29 and it works fine. I'm going to try a few other versions.

**Comment by VRS3DGuru2** [comment]
We actually have our most critical project in 2022.1.3f1 tech stream due to needs upon XR interactions and other libraries that are version locked in 2021.3.4

we have had to temporarily roll it down to DX11 for AVPro to work.

Is there any idea, recommendations or other things that we can try or help you test?

do you know of it is a shader or the decoder interfaces?

-Tony

Sent from my Verizon, Samsung Galaxy smartphone personal email account.
________________________________

**Comment by Chris-RH** [comment]
Sure, that's understandable.  We are looking into compatibility with Unity 2022 and DX12.

**Comment by RichRH** [comment]
Hi @VRS3DGuru2,

We reproduced and fixed the above issue which is available in the just released v2.5.2 - hope that helps.

Cheers,
