### ISSUE TITLE
[2.5.1] GetDurationMs() (AVPro 1.x) and GetDuration() (AVPro 2.5.1) return wrong value on Android

### ISSUE THREAD

**Issue by PedroRossa** [RenderHeads/UnityPlugin-AVProVideo#1201]
I need to get the duration of live streaming to apply some logic.
On Editor works, but when I build to Android, I'm stuck, because it always returns the current value of the live streaming and STOP to send an updated value.
(In the editor I receive the Infinity value as described in the documentation).
I Tried to get the value in different events, On buffering finish, MetaDataReady, and Started, and it's always the same problem, receiving only the current value of the live stream. Even if I try to get it again after some seconds, I receive the same value repeated.
Eg.: GetDuration() = 1200;
Wait 10 seconds
GetDuration() = 1200;

Unity version: 2020.3.23f1
AVPro Video version (number and edition (trial/core/ultra/enterprise)): Version 1.11.7 AND AvPro 2.5.1 Trial
Operating system version: Windows
Device model: Windows Editor and Android (Redmi note 9S with android 11)
Video specs (resolution, frame-rate, codec, file size): testing this link
https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Comment by Ste-RH** [comment]
On Android v2.5.1 I get 'Infinity' reported back for that stream.  I am just reporting/printing it back in a MonoBehaviour Update().

**Comment by Ste-RH** [comment]
Ahh, yeah, If I grab the duration prior to the video being in the 'ready' state, then I get zero back and not infinity.  This is because the player does not know it is a 'live stream' prior to this point.  I will look into seeing if there is a way to set that earlier and thus report back infinity earlier in the GetDuration() call.

**Comment by Ste-RH** [comment]
I have managed to get the live flag (internal to the Android plugin) a bit earlier. Also the duration variable as well is now set a little earlier.  This should help your issue.  It cannot be set any earlier (reliably) than I am doing in this change.  This fix will be in the next release (v2.5.2) which we are preparing now for release later today.  As we no longer support AVPro Video v1, we are not able to back-port this.

**Comment by Ste-RH** [comment]
AVPro Video v2.5.2 has been released.  Please let us know if your issue has been addressed @PedroRossa

**Comment by PedroRossa** [comment]
Thnks for the response.
I updated to AVPro 2.5.2 Trial
And still receiving the same value for a Live streaming link

To test, I Add on Update this piece of code:

` Debug.LogError($"DURATION: {_mediaPlayer.Info.GetDuration()}");
        if (float.IsInfinity((float)_mediaPlayer.Info.GetDuration()))
        {
            Debug.LogError("IS INFINITY");
        }
        else
        {
            Debug.LogError(RBXR_Helper.TimerFormatted((float)_mediaPlayer.Info.GetDuration() * 1000));
        }`

**Comment by Ste-RH** [comment]
It probably won't matter, but GetDuration() returns a double...so you should be checking `double.IsInfinity( duration )`

What happens if you check continuously?  It is impossible to set the live flag any sooner that we are in the plugin now.  The data simply is not there until the point we are now doing it.  But what is a little strange is that the duration you are getting back is not set until after the live flag is set!

**Comment by Ste-RH** [comment]
With your code added to a generic monobehaviour I get the following log output:

![image](https://user-images.githubusercontent.com/46531149/173094924-0cfd50ba-ad70-471b-bd5a-72f7f1ffd30a.png)

**Comment by Ste-RH** [comment]
With your code added to the update of a generic monobehaviour I get the following log output:

![image](https://user-images.githubusercontent.com/46531149/173095204-1db2363d-0abd-49ff-800d-121109796695.png)

**Comment by PedroRossa** [comment]
I still receive a fixed value for the GetDuration() method.
And yes, I put the code on update.
And is a very weird behavior right?

On editor works properly.
But on Android devices (I tested on Android 11 Redmi 9s and Samsung A20) occurs the same.
I receive the value of the current state of the live streaming, and after that, any call to the GetDuration() still returns exactly the same value every frame.

**Comment by Ste-RH** [comment]
Yes. Very strange.

Can you send over a full logcat output please?

**Comment by Ste-RH** [comment]
Bump @PedroRossa

**Comment by Chris-RH** [comment]
Are you still having issues with this @PedroRossa? Could you send over the full logcat output if you are please? :)

**Comment by Ste-RH** [comment]
Closing due to lack of response.
