### ISSUE TITLE
Max file size for local video playback and download for Quest 2

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1202]
Problem description:

I am working on an application for the Quest 2 that may require users to download video files
to their device and use AV Pro to stream it from a local file. This file would not be in the streaming assets
directory of the APK but a directory native to the Quest itself. Do you guys have any suggestions on video
quality, file size, codecs which would play the videos using this method without causing the application to 
crash?

Device (which devices are you having the issue with - model, OS version number):

Quest 2 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

I am running this application on Android for the Quest 2.

System Information:

AVPro Video: v2.5.0 (plugin v2.5.0f1-ultra)
Target Platform: Android
Unity: v2019.4.16f1 WindowsEditor
OS: Desktop - B550M DS3H AC (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 threads - 32691KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10077KB - 16384

**Comment by Chris-RH** [comment]
Hi @Gurwar 

Maximum file size would be 10gb (https://creator.oculus.com/media-studio/documentation/video-spec/)
Max resolutions
3D-360:
5760x5760 30fps H264 H265
4096x4096 60fps H264 H265
5760x5760 60fps ---- H265

360 / 3D-180:
8192x4096 30fps H264 H265
5760x2880 60fps H264 H265
8192x4096 60fps ---- H265
(https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/?locale=en_GB)
