### ISSUE TITLE
[2.4.1]UWP App Certification Error with Audio360.dll

### ISSUE THREAD

**Issue by sjy9137** [RenderHeads/UnityPlugin-AVProVideo#1206]
I'm getting errors due to Audio360.dll when building a Universal Windows build and running the Windows App Certification Kit.
The output is as follows:

Error Found: The supported APIs test detected the following errors:
API CoInitialize in ole32.dll is not supported for this application type. Audio360.dll calls this API.
API PropVariantToInt64 in propsys.dll is not supported for this application type. Audio360.dll calls this API.

I'm using Unity 2019.4.251 with AVPro version 2.4.1 on WIndows 10.

So I tried to solve this problem and tried to solve it by referring to rink.(https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/951)

I deleted the Audio360.dll (In UWP folder)
![image](https://user-images.githubusercontent.com/11624882/173813247-53af7770-51d9-45fc-846f-2c79a5b80b13.png)

And i build a Universal Windows build and running the Windows App Certification Kit but occurred another problem.

Error Found: The supported APIs test detected the following errors:
The API TBE_CreateAudioEngine in audio360.dll is not supported for this app type. AVProVideo.dll calls this API.
API TBE_CreateAudioFormatDecoderFromHeader in audio360.dll is not supported for this app type. AVProVideo.dll calls this API.
The API TBE_DestroyAudioEngine in audio360.dll is not supported for this app type. AVProVideo.dll calls this API.

I want to solve this problem. 

thank

**Comment by Chris-RH** [comment]
If you use Windows App Certification Kit and you get error messages related to the Audio360.dll then you can simply delete this DLL if you are not using the Facebook Audio 360 feature.

**Comment by sjy9137** [comment]
Oh, ha 
I deleted AVProVideo.dll in UWP folder.
I can passed  Windows App Certification Kit.
Thank you your reply.
