### ISSUE TITLE
PlaylistMediaPlayer with a particular video is not triggering the FirstFrameReady event on iOS and MacOS

### ISSUE THREAD

**Issue by Crambror** [RenderHeads/UnityPlugin-AVProVideo#1207]
**Describe the issue**

On iOS and MacOS we have a particular video that although can be played (in unity editor using MediaPlayer inspector controls) does not trigger the FirstFrameReady event like all our other videos. From what I see this event is used by PlaylistMediaPlayer to toggle between its 2 MediaPlayer. We also use this event to know when we can perform a seek and retrieve a thumbnail. 

Note that this does work correctly on PC, in addition all of our other videos run on all platforms with no problems.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.2 Core
 - Operating system version: MacOS 12.3.1
 - Device model: MacBook Pro M1 Max
 - Video specs (resolution, frame-rate, codec, file size): problem video is 1280x720, H.264, AAC, 870KB

**To Reproduce**
1. Add the provided video to the MediaPlaylistPlayer playlist
2. Trigger the item to play using MediaPlaylistPlayer.JumpToItem
3. Notice that you will never receive the FirstFrameRead event, note that the MediaPlaylistPlayer is waiting for that event to toggle between MediaPlayer

**Videos**
https://user-images.githubusercontent.com/107559607/173839467-e166a1b0-9707-4cd8-95c6-7afc2e74a239.mp4

**Comment by MorrisRH** [comment]
The first frame of that video is at 0.023000s so it won't be available until Play has been called, hence FirstFrameReady not being triggered. There's not much we can do about this as that's just how the underlying player from the OS works.
The quick solution would be to re-encode your video with the first frame at 0s.

**Comment by Crambror** [comment]
Many thanks for your feedback, I wasn't aware of that offset to the first frame. Unfortunately we're working with user generated content so we won't always be able to control this. However, you have given me some insight into what's happened now so at least I can try and find a way to catch and possibly work around.

**Comment by christianYS** [comment]
I'll send you the media

**Comment by christianYS** [comment]
sent

**Comment by MorrisRH** [comment]
@Crambror we're going to see if we can match windows and android in this and produce a frame when the video track is delayed as with your example video.
@christianYS I think your issue is separate so if you want to make a new issue or we can continue via email

**Comment by MorrisRH** [comment]
Videos such as the one provided above will now generate frames from the start of playback which in turn will cause the FirstFrameReady event to be triggered.

**Comment by Crambror** [comment]
That's great news, many thanks for the quick handling of this issue. I look forward to trying the new version when released!

**Comment by Ste-RH** [comment]
@Crambror AVPro Video v2.5.3 has just been released.  Please do let us know/close the issue if this fixes the issue for you.

**Comment by Crambror** [comment]
Confirm fix for us.
