### ISSUE TITLE
HLS can't change custom header

### ISSUE THREAD

**Issue by sjy9137** [RenderHeads/UnityPlugin-AVProVideo#1208]
I'm using Unity 2019.4.251 with AVPro version 2.4.1 on WIndows 10.

I want to change HLS streaming header.

So i fixed like this code.
=> MediaPlayers.GetCurrentPlatformOptions().httpHeaders.Add("MyHlsUriToken", "1234567890");

But it was not work.

This image capture HLS streaming data by fiddler tool.

![image](https://user-images.githubusercontent.com/11624882/174054129-3fd54314-2397-4923-a3f1-40781c493b74.png)

I can't find "MyHlsUriToken" Header in HLS streaming data.

Why did not work 'httpHeaders.Add' this function.

I want to solve this problem.

Finally the reason I want to change HLS streaming header is to change User-Agent Value in header.

thanks.

**Comment by Chris-RH** [comment]
Hi @sjy9137 ,  
You haven't said which edition of AVProVideo you are using.  Is it trial/core/ultra? Custom HTTP Headers are only a feature in the Ultra edition.
Further information on Custom Headers and scripting thereof is here: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html#custom-http-headers

**Comment by sjy9137** [comment]
Oh thanks your reply.

I used Avpro Ultra Edition.
I found this problem to solve.

When i switch WinRT in VideoAPI it was worked.

I used this code.
MediaPlayers.GetCurrentPlatformOptions().httpHeaders.Add("User-Agent", "(string)");

Thank you :)
