### ISSUE TITLE
The video will be stuck with a few milliseconds when changing the playback speed

### ISSUE THREAD

**Issue by spjiangjunling** [RenderHeads/UnityPlugin-AVProVideo#121]
The problem is that the video scene jitter is happened when I adjust a playback speed to another, even from 1.1 to 1.2. This phenomenon destroys the user experiments and the video scene can not be flexble and continue  played. 
How to solve this problem ? I need your kindly help. Thank you.

**Describe the bug**
Changing the playback speed  will lead to the video scene jitter, which is obviously observed by users.  

**My Setup**
 - Unity version: 5.5.2f1 (32-bit)
 - AVPro Video version: AVPro Video 1.9.4
 - Operating system version: win10
 - Device model: asus D640MB-I7C00008
 - Video specs : resolution: 3840*1920 360 video, frame-rate: 30fps, file size: 1.04 GB

**To Reproduce**
1. The tested video demo is  08_Demo_360SphereVideo.

2.  Using the “SetPlayBackReat(b)” function, 

3. The playback speed is changed  by the "SetPlayBackReat(b)" function,  b value includes 0,0.2,0.5,1,1.5,2,3 etc.  When I adjust  b value from one to anther,   the video scene jitter is always happened.

**description**
 I adjust the video play speed  by the speed of the bike (the video playback speed includes x1, x2 and x3, , and the playback speed is controlled by the "SetPlayBackReat(b)" function. ).  When the "b" is not changed, the video plays smoothly. However, when the parameter "b" in "SetPlayBackReat(b)" is changed, the video seems to pause for a few frames (or it can be said that the video is stuck with a few milliseconds and then continue to play. These few milliseconds can be caught by the eyes).  What caused this problem? Could you  give me some good suggestions to help us solve this problem, or is there any other better way to change the video playback speed  to avoid this video scene jitter ?

**Comment by spjiangjunling** [comment]
The problem is that the vido scene jitter is happened when I adjust a playback speed to another, even from 1.1 to 1.2. This phenomenon destroys the user experiments and the vido scene can not be flexble and continue  played. 
How to solve this problem ? I need your kindly help. Thank you.

**Comment by AndrewRH** [comment]
Take a look at section 4.13 of the PDF documentation about Seeking/Playback rate, it goes into a lot of detail about this.
Essentially though, if you want to make changing playback rate fast, you need to encode your video to allow for this.  Most videos are highly compressed to favour small file size, and not fast rate change.  You can simplify the video encoding to make this faster.  You could also encode your videos in a format like Hap which would give very fast rate changing (but large file sizes).
Does that help?

**Comment by AndrewRH** [comment]
Closing this as on Windows this is just the native behaviour, but it can be improved by changing encoding.  Other platforms seem to be able to transition playback rates more smoothly.
