### ISSUE TITLE
AudioSource Audio Mixer Group usage?

### ISSUE THREAD

**Issue by VOX-Neil** [RenderHeads/UnityPlugin-AVProVideo#1210]
If a media player is set to using Unity's audiosource component, is there a way to use the output mixer group somehow?
I want to be able to effect the audio during playback.

 - Unity version: 2020.3 LTS
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.5.2 (core)
 - Operating system version: Windows 11

**Comment by AndrewRH** [comment]
![image](https://user-images.githubusercontent.com/5418126/174648053-029f02e8-b7c5-43a0-a0e4-e0837c0f883c.png)

**Comment by VOX-Neil** [comment]
Thank you for responding so quickly.
My issue was that I was using Win RT as the video API. As described in the documentation, I should be using Media Foundation.
Thanks.
