### ISSUE TITLE
Streaming MPEGTS Video Received via UDP

### ISSUE THREAD

**Issue by adilmahsan** [RenderHeads/UnityPlugin-AVProVideo#1211]
**Describe the issue**
Hi,

I'm trying to use AVPro to stream a video via UDP.

The video stream is generated as FFmpeg in mpegts format with mpeg2video encoder. The bitrate is 800 kbps, the keyframe interval is 2, and the resolution is 1024 x 576.

I would like to stream this video in Unity using AVPro. I took the Demo_MediaPlayer scene and adjusted the address to the URL at which the video is being streamed as shown in the image below:

![image](https://user-images.githubusercontent.com/27216313/174840240-3a05ee9c-0ae1-41e7-bd69-3f1525442639.png)

However, when i try to run this, the streaming fails and i get the following error:

![image](https://user-images.githubusercontent.com/27216313/174840404-d8b5b760-160c-4abe-bf20-d31efba1f102.png)

Loading failed. File not found, codec not supported...

I can playback this video using the VLC player, but I can't do it using the AVPro player.

My question was, does AVPro support this functionality? Or is it not meant to be used this way.

Thank you.

Best Regards
Adil Ahsan

**Setup:**
 - Unity version: 2021.2.0f1
 - AVPro Video version: trial
 - Operating system version: Windows 10
 - Video specs (resolution, frame-rate, codec, file size): mpegts

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by Chris-RH** [comment]
Did you check that  MediaPlayer Component > Windows > Video API is set to DirectShow?

**Comment by Chris-RH** [comment]
Are you still having difficulty with this @adilmahsan?
Did you check that MediaPlayer Component > Windows > Video API is set to DirectShow?

**Comment by adilmahsan** [comment]
> I'm sorry to hear that you are unwell. I got covid last month and felt dreadful. Rest up and get back to us when you are feeling better :)

Hey Chris. :)

Thanks for your supportive message. I really appreciate it. :)

And thanks for the wishes, I'm doing much better now and back to work. :)

And also, glad to know that you've recovered and it's behind you now. :)

Regarding the setting, yeah I just tried that, setting Windows -> Video API to Direct Show. It didn't help. I still get the message [AVProVideo] Failed to open udp://127.0.0.1:8899.

Note that I have tested this with the VLC Player and the VLC Plugin, and it worked there, but we were hoping to implement it with the AVPro player because the VLC Player plugin is still in beta version and not yet mature, and the AVPro player looks much nicer, like a fully developed product.

Thanks Chris. :)

**Comment by seowen1** [comment]
I am also experiencing this exact same issue. I've tried the methods described here and no luck.

Would appreciate some clarification whether this is supported or not?

**Comment by Chris-RH** [comment]
Honestly, UDP/RTSP is not something we have much experience of, but that doesn't mean that it can't work.

Do you know whether the stream generator is using RTSP?
Could you change the video API to Media Foundation and try changing the URL from udp:// to rtsp:// or even rtspu:// and see if that helps?
Could you also make sure that Unity isn't being blocked by your firewall?

**Comment by seowen1** [comment]
The stream is valid and working by testing with VLC, and no Unity is not blocked by our firewall.

I've tried what you suggested and still nothing.

**Comment by Chris-RH** [comment]
Hmm, I'm not sure what else to suggest other than converting it to something that is known to be supported https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html

**Comment by adilmahsan** [comment]
> Could you change the video API to Media Foundation and try changing the URL from udp:// to rtsp:// or even rtspu:// and see if that helps?

Hi Chris,

Thanks for your reply.

I tried replacing udp with rtsp, but I couldn't generate the stream from OBS Studio. It was generating an error, "Starting the output failed."

And I don't think it's blocked by firewall, because I can stream it via VLC player plugin.

Thanks for your help and suggestions Chris. I appreciate your effort. :)

**Comment by itisystems** [comment]
Any chance there's been an update on this issue? We're trying to get a udp stream to play via AVPro for Windows. Just wondering if there's some combination of Video API (DirectShow, WinRT, Media Foundation) + external downloadable decoders (LAV filters) we could use to get UDP streaming to work on Unity.
