### ISSUE TITLE
video 5760x2880 60 FPS not read on pico G2 4K

### ISSUE THREAD

**Issue by Suboceana** [RenderHeads/UnityPlugin-AVProVideo#1216]
**video 5760x2880 60 FPS not read on pico G2 4K**

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.35
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): ultra
 - Operating system version: android 
 - Device model: PICO G2 4K
 - Video specs (resolution, frame-rate, codec, file size): 5760x2880 60fps H264

**To Reproduce**
1. Video is always black when it try to read it with AvPro Player
2. the video can be read by pico video player

https://immersiontools-my.sharepoint.com/:v:/g/personal/roland_toullec_immersion_tools/EbhN-KrejlNDkarRZwTWKlEBxyh6zEHms1TpgH7KuMXP3A?e=SMRT3o

**Comment by Chris-RH** [comment]
Hi @Suboceana, I'm sorry that you are having problems

60FPS is very high at that resolution. 30 FPS is recommended 
(https://headjack.io/knowledge-base/best-video-resolution-for-pico-headsets/)

Have you tried playing the default AVPro Video 360 demo scene in a new blank project, just to get it working with your headset?

Also, please make sure that you have the latest version of AVPro Video installed :)

**Comment by Chris-RH** [comment]
Hi, @Suboceana 
Has this helped?

**Comment by Chris-RH** [comment]
Closed due to lack of response, please re-open if this is still an issue.
