### ISSUE TITLE
How to play videos in AssetBundle

### ISSUE THREAD

**Issue by szl-zhanghao** [RenderHeads/UnityPlugin-AVProVideo#1217]
**How to play videos in AssetBundle？ **

**Comment by Chris-RH** [comment]
Hi @szl-zhanghao 

Unfortunately we don't support opening videos from within asset bundles.  There is currently no way we can do this.

**Comment by szl-zhanghao** [comment]
OK, thank you. Will this function be added in the future?

**Comment by Chris-RH** [comment]
No, it isn't on the roadmap.
There are some workarounds that others have found though.
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/222
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/272

**Comment by szl-zhanghao** [comment]
Thank you very much.
