### ISSUE TITLE
Crash on Android when resolution limit is enabled (and a fix for it!)

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [RenderHeads/UnityPlugin-AVProVideo#1218]
**Describe the issue**
On Android, when Preferred Maximum Resolution is set, the game crashes. 

After some investigation, I determined the issue is caused by a typo in `AndroidMediaPlayer.cs` line 950:
`/*bool bSetMaxResolutionAndBitrate =*/ m_Video.Call<bool>("SetPreferredVideoResolutionAndBirate", (int)(vPreferredVideo.x), (int)(vPreferredVideo.y), iNewBitrate);`

The word "Bitrate" is spelt incorrectly in `SetPreferredVideoResolutionAndBirate`. Changing the called method name to `SetPreferredVideoResolutionAndBitrate` fixes the issue 😅

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.3
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.5.1 Ultra
 - Operating system version: Android 12
 - Device model: Pixel 6 Pro
 - Video specs (resolution, frame-rate, codec, file size): RTMP stream with up to 1080p, h265

**Logs**
I forgot to save them, but the basic gist is something like `Method "SetPreferredVideoResolutionAndBirate" is not found`

**Comment by Chris-RH** [comment]
Thankyou, well spotted! I'll pass this on to our dev team :)

**Comment by Ste-RH** [comment]
v2.5.4 has been released and should address this
