### ISSUE TITLE
Media Player Looping option was not active

### ISSUE THREAD

**Issue by junpa** [RenderHeads/UnityPlugin-AVProVideo#1221]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version:   2021.3.2f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  Core 2.5.3
 - Operating system version: iOS 15.5
 - Device model: 12.9 iPad Pro(5th Generation)
 - Video specs (resolution, frame-rate, codec, file size):  720 x 720 / 30 fps / - / 1.91MB

**To Reproduce**
1. I using Window version avpro 
2. and need iOS version, so I bought avpro core version 
(https://assetstore.unity.com/packages/tools/video/avpro-video-core-edition-181844)
4.  iPhone looping option was active correctly
5. but in Ipad and Editor looping was not active
6. just playing once in iPad and Editor

etc
1. in Hierarchy inactive Media player attached to GameObject obsered bug (ex inactive -> active mediaplayer looping was not active but from firsttime mediaplayer attached active GameObject was looping correctly   )

2. in iPhone13 has not that bug but iPhone12 has that bug ...

**Comment by Chris-RH** [comment]
Hi @junpa,
I'm sorry that you are having problems.

1. Just to confirm, by "not active" do you mean that the button was greyed out or that it was ticked but not working?
2. Have you tried using the demo scene media player on these devices?
3. Had it been working properly in the editor when you just had the Windows version?
4. What's it like when you build to Windows now?
5. What type of file is it?
6. Is it just this specific file you are having problems with or is it all video files?

**Comment by Chris-RH** [comment]
Hi @junpa 
Are you still having problems?

**Comment by Chris-RH** [comment]
Closed due to lack of response.  Please re open if this is still an issue.
