### ISSUE TITLE
NotchLC transparent videos have red-blue channel swapped randomly

### ISSUE THREAD

**Issue by marcseibert** [RenderHeads/UnityPlugin-AVProVideo#1228]
### Problem description:

Sometimes our videos (NotchLC codec with transparency) are tinted blue. The blue tint is visible in the
MediaPlayer Component aswell as the displayed Texture on the screen.

We can't find any real pattern to when the texture turns blue. The MediaPlayer doesn't
throw any Exception Events.

### Device (which devices are you having the issue with - model, OS version number):

Desktop, Windows 10.1

### Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):
In the photo you can see 3 NotchLC encoded videos with transparency displayed using a DisplayuGUI component.
The screenshot has been blurred and cut to protect the data of our customer.

The first two videos are ok but the third video is tinted blue.
[Problem Example Screenshot](https://ixtenda.sharepoint.com/:i:/s/iXtenda/EeI-Fn6qC6BApPuKZFwQygABhpMgnoBUafRcdMTxtjrPsg?e=JfEAja)

There are approximately 9 Videos Loaded in Full HD resolution encoded in NotchLC.
The Probelm also occurs when loading a single video only.

### System Information:

AVPro Video: v2.5.3 (plugin v2.5.3f2-ultra)
Target Platform: Standalone
Unity: v2021.2.9f1 WindowsEditor
OS: Desktop - To Be Filled By O.E.M. (To Be Filled By O.E.M.) - Windows 10  (10.0.19043) 64bit - English
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 12 threads - 32687KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10078KB - 16384

**Comment by Chris-RH** [comment]
Hi @marcseibert,

1. Is it the same video that you are having difficulty with or is it random?
2. Are all of your drivers up to date?
3. How do they all play in a different mediaplayer?
4. Could you give a bit more detail about the videos files please?  File container etc
5. What are your CPU and GPU usage like when playing these?

**Comment by AndrewRH** [comment]
I think we've identified the issue.  We will test more on Monday to confirm.

**Comment by marcseibert** [comment]
@AndrewRH Thanks for looking into the issue so quickly!
@Chris-RH for completeness reasons:

**1. Is it the same video that you are having difficulty with or is it random?**
No, we have multiple videos (all encoded in NotchLC). Sometimes the videos load correctly and sometimes they don't.

**2. Are all of your drivers up to date?**
Yes.

**3. How do they all play in a different mediaplayer?**
Each DisplayuGUI has a separate MediaPlayer each loading a different video file.

**4. Could you give a bit more detail about the videos files please? File container etc**
Length: 10s
Frame size: 1920 x 1080 (width x height)
Data rate: 89674kbps
Frame rate: 25 frames/second
Size: 106MB

**5. What are your CPU and GPU usage like when playing these?**
When running in editor mode the CPU usage averages around 40% utilization and GPU around 35%.

**Comment by Ste-RH** [comment]
@marcseibert AVPro Video v2.5.5 has been released.  Please do let us know if this version fixes the issue for you.

**Comment by Chris-RH** [comment]
Please reopen if this is still an issue.
