### ISSUE TITLE
What's IOSurface ？The MediaPlayer had been destroyed all， but IOSurface left in memory，taking 40 MB？Cannot release these？

### ISSUE THREAD

**Issue by defchen** [RenderHeads/UnityPlugin-AVProVideo#123]
**Describe the bug**
MediaPlayer had been destroyed all， but IOSurface left inmemory，taking 40 MB？Cannot release these？

**Your Setup (please complete the following information):**
 - Unity version: 2017.4
 - AVPro Video version: 1.7.3
 - Operating system version: 
 - Device model: IOS
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 
![image](https://user-images.githubusercontent.com/1761985/61516023-9702a680-aa36-11e9-8126-2f96629d715d.png)

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Version 1.7.4 of AVProVideo is incredibly old. Many improvements to the handling of memory have been made since it was released. Please upgrade to the latest version 1.10.0.
