### ISSUE TITLE
Framework problems when building on XCode 13

### ISSUE THREAD

**Issue by BaptisteDev09** [RenderHeads/UnityPlugin-AVProVideo#1232]
**Describe the issue**
I wanted to try if my project was working correctly on IOS (it was working on IOS about a year ago) and so I've built my unity project on Xcode (v13.4.1) and I got framework issues (conf screenshots). The problem seems to be related to the AVPlayer. But when I look at the settings everything looks fine except that I don't have the AVProVideo.framework (like mentioned [[here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html)](url)).

**Your Setup (please complete the following information):**
 - Unity version: v2020.3.34
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 1.11.7 (core edition I think)
 - Operating system version: Mac OS Monterey (12.4)
 - Device model: Iphone 13 pro

**To Reproduce**
1. Create a mobile project
2. Import AVPro v1.11.7
3. Build IOS, import to Xcode, plug a mobile and try to build on the device

<img width="451" alt="ScreenShot_1" src="https://user-images.githubusercontent.com/77831201/179173939-cb1a12fe-9404-4fff-b3eb-96c04e2a5aef.png">
<img width="632" alt="ScreenShot_2" src="https://user-images.githubusercontent.com/77831201/179173947-ddff98da-7134-4bf1-a060-49dde9a90769.png">
<img width="374" alt="ScreenShot_3" src="https://user-images.githubusercontent.com/77831201/179173950-88811e0b-87a0-4b0b-bf5f-e273ac20eb66.png">

**Comment by Chris-RH** [comment]
Hi @BaptisteDev09 
The documentation that you are looking at is for AVPro Video Version 2.  Version 1 has no  AVProVideo.framework, the files that you have there are correct.
It looks to me like either the plugin didn't get imported properly in Unity or they failed to copy over correctly into your Xcode project.  You should try closing Unity, opening Unity and then immediately try importing the AVPro Video package again. Hopefully it should then upgrade correctly. If that still fails, then try removing AVPro Video manually and then reimporting it.

**Comment by BaptisteDev09** [comment]
Hello @Chris-RH,

I've re-imported the plugins folder from the asset and it did the trick, thank you for your quick answer. I should have thought of that before posting an issue here :)

I'll close this issue as it has been fixed !

Cheers

**Comment by Chris-RH** [comment]
Awesome, thank you for letting me know :)
