### ISSUE TITLE
How to save the buffered url video to the local. I don't need to reload online the next time I need to watch it again

### ISSUE THREAD

**Issue by qq294716498** [RenderHeads/UnityPlugin-AVProVideo#1233]
How to save the buffered url video to the local.
I don't need to reload online the next time I need to watch it again

**Comment by AndrewRH** [comment]
Take a look here:
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-caching.html

**Comment by qq294716498** [comment]
Caching is not currently supported on Windows

**Comment by Chris-RH** [comment]
Yes, its currently restricted to Android and iOS.

**Comment by qq294716498** [comment]
My environment is Windows, I need to play a lot of videos, I hope I can save server traffic, is there a solution?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月18日(星期一) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] How to save the buffered url video to the local. I don&#39;t need to reload online the next time I need to watch it again (Issue #1233)





 
Yes, its currently restricted to Android and iOS.

**Comment by Chris-RH** [comment]
There isn't a huge amount that you can do.  What sort of files are they?
Have you encoded them with faststart?
Are you using Media Foundation?
