### ISSUE TITLE
Incorrect current frame number on Android when using MediaPlayer API

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProVideo#1234]
**Describe the issue**
`GetCurrentTimeFrames` always returns 0 on Android, which also causes `SeekToFrameRelative` to fail.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.5 core
 - Operating system version: Android 11
 - Device model: Google Pixel 2
 - Video specs (resolution, frame-rate, codec, file size): 1080p, 30fps, h264, 600mb

**To Reproduce**
While the video is playing or paused, `m_MediaPlayer.Control.GetCurrentTimeFrames` always returns 0

**Workaround**
Use `m_MediaPlayer.Control.GetCurrentTime() * m_MediaPlayer.Info.GetVideoFrameRate()`, which is not accurate but is a fine approximation.

**Comment by Chris-RH** [comment]
Hi @artoonie,
What code are you using? Are you using the workarounds as a straight replacement?

**Comment by AndrewRH** [comment]
That's strange... ``GetCurrentTimeFrames()`` basically does the same thing, ie GetCurrentTime() * GetVideoFrameRate() but with some nuances to make it accurate... so I'm not sure why it's not working for you...

**Comment by artoonie** [comment]
It is possible that `GetVideoFrameRate` is 0 when paused - let me test more and let you know what I find.

I ended up not using the workaround above - I need to `SeekToFrameRelative(3)` to step forward, so I'm using `Seek(currentTime + 0.1f)` now which does work fine.

**Comment by Ste-RH** [comment]
> Do you need an example video that has this 0fps framerate?

Yes please. Also. Are you using the ExpPlayer or MediaPlayer API path?

**Comment by Ste-RH** [comment]
Ahh, MediaPlayer.  Yeah, oki.  That makes sense now.

There are a number of methods to obtain the video encoded framerate, and it appears the 'more optimal' method is not 100% reliable.  I will revert back to the method that appears to be a bit better.  Expect this change in v2.5.6 which we hope to release this week.

**Comment by Ste-RH** [comment]
Bit of additional.

The Android MediaPlayer APIs return the frame rate as an integer value, and ExoPlayer reports it back as a float.  For your video I get 30 from MediaPlayer, and 30.22109 from ExoPlayer.  This will potentially result in an incorrect 'current frame' value.  If you can use ExoPlayer, I would.

**Comment by artoonie** [comment]
I have in my notes that ExoPlayer was braking one of my shaders, but I'm not sure which - I tried to reproduce, but I'm getting `AndroidJavaException: java.lang.NoClassDefFoundError: com.google.android.exoplr2avp.audio.AudioCapabilities`. I'm sure I could work through each of these issues, but MediaPlayer works out-of-the-box for me.

**Comment by Ste-RH** [comment]
Better MediaPlayer source video framerate support coming in v2.5.6.  Hope to get this released tomorrow.

**Comment by AndrewRH** [comment]
> 

That sounds like a different issue - perhaps you could open a new issue with details about this.  Also you could try disabling any stripping/proguard options in Unity player settings.

Thanks,

**Comment by Chris-RH** [comment]
Version 2.5.6 has been released, please let us know if this has solved your problem.

**Comment by Chris-RH** [comment]
Please reopen if this is still an issue
