### ISSUE TITLE
NotchLC Videos appear pixelated in DX11

### ISSUE THREAD

**Issue by marcseibert** [RenderHeads/UnityPlugin-AVProVideo#1235]
**Problem description:**

Videos encoded in NotchLC have a much lower resolution when loaded through the AVPro MediaPlayer (AVPRo Ultra Version 2.5.5) than when opened using QuickTime.

Changing the "Visual" settings (e.g. changing the filter method to bilinear) has no influence on the result.

AVPro Preview:
<img width="333" alt="preview_avpro" src="https://user-images.githubusercontent.com/31168028/179502858-3001f0df-8d00-4f72-a2e0-46925df9cdd2.png">

QuickTime Preview:
<img width="302" alt="preview_quicktime" src="https://user-images.githubusercontent.com/31168028/179502867-7d69d238-b70a-42d5-a847-b35e3d660e90.png">

**Device (which devices are you having the issue with - model, OS version number):**

Desktop, Windows 10

**Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):**

The said video has a resolution of 720x405 with 25 frames/second and is encoded using NotchLC with transparency.
![InkedAVPro_General_Settings](https://user-images.githubusercontent.com/31168028/179503436-3d25cd32-76dc-4297-bc1a-41a8096b6db3.jpg)
<img width="508" alt="AVPro_Platform_Specific_Settings" src="https://user-images.githubusercontent.com/31168028/179502899-7c847590-bac4-476b-9ee9-a56b05220000.png">

**System Information:**

AVPro Video: v2.5.5 (plugin v2.5.5f1-ultra)
Target Platform: Standalone
Unity: v2021.2.9f1 WindowsEditor
OS: Desktop - To Be Filled By O.E.M. (To Be Filled By O.E.M.) - Windows 10  (10.0.19043) 64bit - English
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz - 12 threads - 32687KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10078KB - 16384

**Comment by Chris-RH** [comment]
Hi @marcseibert,

The preview in the editor will be downscaled. Could you please try rendering it to see what the output is?

Would you also be able to send your video to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) so that we could get a better look at what is going on? Please included the issue number in the subject line.

**Comment by marcseibert** [comment]
Here is the same guy rendered using a "DisplayUGUI Component".
<img width="165" alt="rendered" src="https://user-images.githubusercontent.com/31168028/179512992-ae1b41ad-6c6c-4933-accd-41cb1659681a.png">

I also send the video file to unitysupport@renderheads.com.

**Comment by AndrewRH** [comment]
Problem not present in the DX12 path...

**Comment by Chris-RH** [comment]
Version 2.5.6 has been released, please let us know if this has solved your problem.

**Comment by Chris-RH** [comment]
Please reopen if this is still an issue
