### ISSUE TITLE
the "_segmentsProgress" did'nt work in IOS

### ISSUE THREAD

**Issue by sieutungbi** [RenderHeads/UnityPlugin-AVProVideo#1239]
Problem description:

in IOS,when i slide the silder to seek video, the "_segmentsProgress" in MediaPlayerUI.cs 
(we use like the demo scene) did'nt work, the segments progess did not follow the handle, 
but when i let go the handle it did seek video. it happen on ios but work fine on android with
same setup.

Device : ios 14/15

Media: streaming m3u8

**Comment by Chris-RH** [comment]
The latest update has just been released. Please let us know if the problem is not fixed :)
