### ISSUE TITLE
The size of Map of AVProMobileVideo is 256，but never clear the map cache？It would be limited by creating  and destroying in one life of the app 

### ISSUE THREAD

**Issue by defchen** [RenderHeads/UnityPlugin-AVProVideo#124]
**Describe the bug**

**The size of Map of AVProMobileVideo is 256，but never clear the map cache when a player was deinitialised . It would be limited by creating  and destroying in one life of the app . Also, the java object AVProVideoPlayer had been cached in the map without releasing the memory .**

**Your Setup (please complete the following information):**
 - Unity version: 2017.4
 - AVPro Video version: 1.7.3
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Version 1.7.4 of AVProVideo is incredibly old.  Please upgrade to the latest version 1.10.0 as many improvements and fixes have been made since the build you are using.

**Comment by defchen** [comment]
Thanks, i'll do it.
