### ISSUE TITLE
blank display in iPhone12 

### ISSUE THREAD

**Issue by mura303** [RenderHeads/UnityPlugin-AVProVideo#1240]
When I use iPhone 12, the following issue happens. 

- Videos don't show up while audio is okey.
- In the loop play mode, videos show up in the second loop.

I was able to reproduce the issue with Demos/Scenes/Demo_MediaPlayer.unity.

In addition, when I use iPhone 7 plus, this issue doesn't happen.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.4f1
 - AVPro Video version : AVPro Video - Core Edition Version 2.5.6
 - Operating system version: iOS 15.5
 - Device model: iPhone 12
 - Video specs (resolution, frame-rate, codec, file size): I used RenderHeads-1080p30-H264.mp4 in your demo

**To Reproduce**
1. build Demo_MediaPlayer.unity 
2. run on iPhone 12

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Unable to reproduce this, tried with the following:
- Unity 2021.3.5f1
- Xcode 13.4.1
- AVPro Video Core 2.5.6
- iPhone 13 Pro running iOS 15.5
- iPhone X running iOS 14.8.1
- iPad Pro (10.5-inch) running iPadOS 15.5

It's possible this is specific to iPhone 12's but that seems quite unlikely. Unfortunately I don't have access to one to test against.

You could try enabling "Use single player item" in the iOS specific section of the media player settings as this causes looping to be handled a bit differently. I'd be interested in knowing if this works for you.

Are you using the default Unity project settings or have these been modified somehow?

**Comment by mura303** [comment]
I tried enabling "Use single player item".
The result was the same as before.

I tried to reproduce it with iPhone Xr running iOS 15.5, and it worked fine ( it doesn't reproduce the issue).
