### ISSUE TITLE
Hap / Hap Alpha not loading

### ISSUE THREAD

**Issue by paulorenanmelo** [RenderHeads/UnityPlugin-AVProVideo#1241]
**Describe the issue**
Hap videos are not loading. Using the provided Demo_MediaPlayer scene and assigning the hap video file, it logs an error, and the player remains black/blank.

**Your Setup (please complete the following information):**
 - Unity version:  2021.3.6f1
 - AVPro Video version: 2.5.6 ultra edition 
 - Operating system version: Windows 10.0.19042
 - Device model: Dell workstation (Intel Xeon W-2275, 64GB ram, lots of free disk space, Nvidia RTX 3080)
 - Video specs (resolution, frame-rate, codec, file size): any .mov hap video, see various samples in links below on their github

**To Reproduce**
1. Open a unity project, import avpro ultra edition
2. Download videos (links below)
3. Place the video in StreamingAssets
4. Open Demo_MediaPlayer scene and assign the test video to the MediaReference linked in the MediaPlayer component in the scene
5. Play in the editor - and see console for error

**Error Log**
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> UnityEngine.Debug:LogError (object)
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1277)
> RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:705)

**Screenshots**
It works on media player classic, as per screenshot
![avpro not playing hap videos](https://user-images.githubusercontent.com/5646288/181237814-3859cf74-bb2a-4710-90d2-66a23d119b13.PNG)

**Videos**
https://s3.amazonaws.com/vidvox/hap/Hap_Test_Odd_Dimensions.zip 

Alternatively, if link above doesn't work, check their github and download "Odd Dimensions"
https://github.com/Vidvox/hap

Even normal resolution videos without alpha are not loading either. Please download all samples from their github page
https://s3.amazonaws.com/vidvox/hap/Hap_Test_FFmpeg.zip

**Comment by Chris-RH** [comment]
Hi @paulorenanmelo 

In the Media Player component
Visual -> Platform Specific -> Windows
Make sure the Video API is set to Media Foundation and that you have ticked the "Use Hap/NotchLC" box

![hap](https://user-images.githubusercontent.com/102963025/181247138-feb638e9-1307-45c0-a7ac-66f0e8622408.png)

**Comment by paulorenanmelo** [comment]
Thanks Chris! That works like a charm.
My bad.
So much to do I didn't look for the existence of such toggle.

I can confirm both hap alpha and hap Q alpha working.

**Comment by Chris-RH** [comment]
Ah, its easy to overlook a small checkbox.  
Awesome, I'm glad that its got sorted so quickly :)
