### ISSUE TITLE
[iOS] How to record with sound in HLS Video?

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1242]
I want record using AVProMovieCapture.

According to the document,
``
Unity: Audio is played by Unity via the AudioOutput component. HLS media is not supported and will continue to playback in system direct mode regardless of the chosen audio mode.
``

How to record with sound in HLS Video?

**Comment by Chris-RH** [comment]
Hi @dw8869 
I'm afraid that it is just not possible to capture audio from an HLS stream in Unity.

**Comment by dw8869** [comment]
@Chris-RH 
Which problem makes it difficult to implement?
Can we use the api in near future?

**Comment by Chris-RH** [comment]
This is a limitation of Apple's AVFoundation framework so there is nothing we can do about this at this time.  We use MTAudioProcessingTap to extract the audio and route it through to Unity. This in turn requires using AVAudioMix and attaching it to the current player item. Sadly this is where the process breaks down as AVAudioMix does not support HLS media.
The documentation for AVAudioMix states the following (available [here](https://developer.apple.com/documentation/avfoundation/avplayeritem/1388037-audiomix)):

"An audio mix can only be used with file-based media and is not supported for use with media served using HTTP Live Streaming."



In theory, you might be able to record from your speakers to an external microphone, but in practice the sound quality would probably not be very good and it would be effected by external sounds.
