### ISSUE TITLE
double tonemapping

### ISSUE THREAD

**Issue by HenrikH96** [RenderHeads/UnityPlugin-AVProVideo#1244]
We use AVPro to create a detailed and realistic VR experience with 360 degree videos together with real-time elements in unity.

We encountered the problem that we then tone map the videos twice. We use the ACES tonemapper from the postprocess stack. We render the videos offline and also use the ACES tonemapper, which means that our videos in VR receive double tonemapping.
Is there a recommended solution for this?
We counteracted the problem with our own shader by trying to calculate aces out of the video. We're also not entirely sure why the texture needs gamma correction after encoding. 

Any hints or tips ?
Henrik

**Comment by Chris-RH** [comment]
I'm afraid I don't have any advice other than not to tonemap the video.  Tonemapping is very much all or nothing, so it can't really be done selectively.
