### ISSUE TITLE
UpdateMultiPassStereoRender.cs won't compile for tvOS

### ISSUE THREAD

**Issue by acgourley** [RenderHeads/UnityPlugin-AVProVideo#1248]
**Describe the issue**
Compile error when importing AVPro 2 into a tvOS project

**Your Setup (please complete the following information):**
 - Unity version: 2021.3
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core 2.5.2
 - Operating system version: tvOS
 - Device model: Apple TV

**Logs**
The type name 'InputDevices' could not be found in the namespace 'UnityEngine.XR'. This type has been forwarded to assembly 'UnityEngine.XRModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'XR' in the Package Manager window to fix this error.

I suspect you intend people to not import this file. Which we could do! But I wanted to put this on your radar in case you'd rather wrap it in a preprocessor check for a XR supported platform.

**Comment by Chris-RH** [comment]
Hi @acgourley,
Thank you for bringing that to our attention. We'll look into what we can do about that. :)

**Comment by MorrisRH** [comment]
This has been fixed and will make it into the next release

**Comment by Chris-RH** [comment]
This has hopefully been fixed now with the release of version 2.6.0.
