### ISSUE TITLE
Output texture overly Exposed

### ISSUE THREAD

**Issue by nickhudson4** [RenderHeads/UnityPlugin-AVProVideo#1249]
https://user-images.githubusercontent.com/44004215/183121056-74a89d34-2359-41f5-b80a-080b79dc3aa8.mp4

Output texture is overly exposed. Texture is being grabbed like so 
```
public Texture Texture
        {
            get 
            { 
                Texture resamplerTex = _player.FrameResampler == null || _player.FrameResampler.OutputTexture == null ? null : _player.FrameResampler.OutputTexture[0];
                return (_player.UseResampler ? resamplerTex : _player.TextureProducer.GetTexture(0));
            }
        }
```

Note that this is a direct reference to the texture and does not involve any shaders. It appears to be an issue with Gamma, which you are correcting with the shader.

**Comment by Chris-RH** [comment]
Hi @nickhudson4 

Are you using a gamma or linear colour space?
How are you rendering the texture?  Is it onto a lit or an unlit surface?

**Comment by nickhudson4** [comment]
This is a direct texture reference. No shaders involved.  I am pulling the the exact texture generated by your asset to be placed on UIimages, to create sprites, etc. 

For our app it is important that we can use the output texture directly. Similar to the way you can with the Unity Videoplayer.

**Comment by Chris-RH** [comment]
Have you tried using the Resolve to RenderTexture component?
https://www.renderheads.com/content/docs/AVProVideo/articles/component-resolve-to-rendertexture.html

**Comment by Chris-RH** [comment]
You could also try disabling hardware decoding.

**Comment by KeeleyYu** [comment]
@nickhudson4 
hi, I have met this problem too. The problem is not only over exposed, but also the texture is inverted upside-down. Have you solved it? @Chris-RH Or any other alternative ways?
Cause the ResolveToRenderTexture strill remains some bugs that I reported last few days. (#1363) And I have to bind the MediaPlayer to ResolveToRenderTexture component in the scripts instead of in editor inspector for some reason.

**Comment by nickhudson4** [comment]
@KeeleyYu The raw incoming texture requires a vertical flip and gamma correction. If their resolve to render texture is buggy for you, you can create your own. Create a material with a shader that performs the flip and gamma correction. Then use Graphics.Blit(SourceTexture, ResolvedTexture, material). Where SourceTexture is the fliped texture, ResolvedTexture is the new texture, and material is the resolve material you created.

**Comment by KeeleyYu** [comment]
@nickhudson4 Thanks a lot! I will have a try. :)

**Comment by dr-formalyst** [comment]
What works for me is to use Helper.GetReadableTexture() function:
`var texture = Helper.GetReadableTexture(_mediaPlayer.TextureProducer.GetTexture(),
    _mediaPlayer.TextureProducer.RequiresVerticalFlip(),
    Helper.GetOrientation(_mediaPlayer.Info.GetTextureTransform()), null);`

Then in the shader / shader graph or vfx graph where I use that texture, I need to raise color to the power of 2.2 (which is what AVProVideo shader does, see AVProVideo.cginc include).
