### ISSUE TITLE
Cannot access instance field boolean  m_bShowPosterFrame

### ISSUE THREAD

**Issue by defchen** [RenderHeads/UnityPlugin-AVProVideo#125]
**Describe the bug**
### **java.lang.VerifyError. Verifier rejected class com.RenderHeads.AVProVideo.AVProMobileVideo. com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean) failed to verify. com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean).  cannot access instance field boolean com.RenderHeads.AVProVideo.AVProVideoPlayer.m_bShowPosterFrame from object of type Unresolved Reference.** 

**m_bShowPosterFrame is a protected variable,  how could it be accessed ?**

**Your Setup (please complete the following information):**
 - Unity version: 2017.4
 - AVPro Video version: 1.10.0
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
We introduced a change in version 1.10.0 that sees the ExoPlayer API path always produce a poster frame.  The variable you reference therefore only has an effect when using the MediaPlayer API path.  The only way the variable should be set is the MediaPlayer object in the inspector, or via c# instantiation of a MediaPlayer object before Initialise() is called:

myMediaPlayer.PlatformOptionsAndroid.showPosterFrame = true;

You can also change this after creation by using the function in the AndroidMediaPlayer class:

public void SetOptions(bool useFastOesPath, bool showPosterFrame)

Note, again, this will have no effect when using the ExoPlayer API path as a poster frame is created by default.

**Comment by RenderHeadsSte** [comment]
@defchen We do not support de-compiling of source code.  This option is controlled at c# level in unity.  This post will now be removed.
