### ISSUE TITLE
Stereo360 - Videos are flipped on Android 

### ISSUE THREAD

**Issue by developerarticipate** [RenderHeads/UnityPlugin-AVProVideo#1251]
**Describe the issue**
I'm trying to test the stereo360 feature in the plugin for android devices in the demo scene: Demo_360Stereo. It is working fine in the editor but when I build to Android the video is flipped and the Sphere have turned 90 degrees. 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.31f1
 - AVPro Video version (2.3.0f1-trial): 
 - Operating system version: Android
 - Device model: One Plus 9 pro
 - Video specs (resolution, frame-rate, codec, file size): 
mp4, 10mb 

**To Reproduce**
1. Build the scene Demo_360Stereo to an Android phone

**Comment by Chris-RH** [comment]
Hi, sorry yes we are having issues with our gyroscope. We are looking into a fix for it.
