### ISSUE TITLE
AES-128 HLS playback with overrideDecryptionKey doesn't work on IOS

### ISSUE THREAD

**Issue by changzhouxiaoqinglong** [RenderHeads/UnityPlugin-AVProVideo#1252]
I know overrideDecriptionKey feature isn't currently supported on Android ,But I also failed the test on ios.

 Setup :
 - Unity version: 2020.3.29f1c1
 - AVPro Video version : AVPro Video v2.5.7Trial
 - Operating system version: Windows 10.
 - Device model: IPAD

 Reproduce：
Use ffmpeg to create an encrypted HLS video.  Put all generated files in the StreamingAssets folder.

Plays back correctly on Windows:
media.PlatformOptionsWindows.videoApi = Windows.VideoApi.WinRT;
media.PlatformOptionsWindows.keyAuth.overrideDecryptionKey = mybytes;
media.OpenMedia(MediaPathType.RelativeToStreamingAssetsFolder, myMediaPath, true);

On IOS nothing plays:
media.PlatformOptionsIOS.keyAuth.overrideDecryptionKey = mybytes;
media.OpenMedia(MediaPathType.RelativeToStreamingAssetsFolder, myMediaPath, true);

[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.

My project is in offline mode and all my video resources are local.
IF overrideDecriptionKey feature isn't currently supported on IOS ,how can i protect my videos in the StreamingAssets folder. (I know i can use File Offset on Android  append video to a dummy file)

**Comment by MorrisRH** [comment]
Hey @changzhouxiaoqinglong, playing HLS videos out of the StreamingAssets folder is not supported on iOS.
