### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.renderheads.AVPro.Video.Manager" flutter_unity_widget

### ISSUE THREAD

**Issue by decvim** [RenderHeads/UnityPlugin-AVProVideo#1254]
Unable to load the library causing playback failure

1. UnityPlugin-AVProVideo-v2.5.7-Trial.unitypackage
2. Unity 2020.3.29f1
3. flutter_unity_widget-2022.1.7+1.tar.gz
4. Android Studio Chipmunk | 2021.2.1 Patch 1

gradleTemplate add:android.enableDexingArtifactTransform=false
proguard-user add: 
-keep class com.renderheads.AVPro.Video.** { *; }
-keep class com.google.android.exoplr2avp.** { *; }
-keep class com.twobigears.audio360.** { *; }
-keep class com.renderheads.AVPro.Video.** { *; }
-keep class com.google.android.exoplr2avp.** { *; }
-keep class com.twobigears.audio360.** { *; }

---------------------------------

**Logs**
E/Unity   (13805): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.renderheads.AVPro.Video.Manager" on path: DexPathList[[zip file "/data/app/~~GAY5Q9Ohqg9dZOhLL6wLIw==/com.xraph.plugin.flutter_unity_widget_example-_tl0S7e5bufRVYB8kz0yUA==/base.apk"],nativeLibraryDirectories=[/data/app/~~GAY5Q9Ohqg9dZOhLL6wLIw==/com.xraph.plugin.flutter_unity_widget_example-_tl0S7e5bufRVYB8kz0yUA==/lib/arm64, /data/app/~~

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @decvim, have you got minify enabled? If so, then you need to follow this information: https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#proguard-minify

![minify](https://user-images.githubusercontent.com/102963025/184307637-c15c84ad-b9b3-45da-b319-a0fd28d2896e.png)

**Comment by Chris-RH** [comment]
It is most likely to be an issue caused by flutter.

**Comment by decvim** [comment]
Yes, follow the instructions to delete ARM64, the problem is still the same. @Chris-RH

**Comment by decvim** [comment]
Regarding the release Settings, there is no reduction in compression and the release is in DEBUG mode.

**Comment by Chris-RH** [comment]
1. What is the min/target SDK?
2. Have you run flutter clean?
3. Have you double checked Flutter SDK Path from Android Studio - https://tppr.me/qn6dP
4. Is that your full error log?
5. What are your gradle settings?

**Comment by decvim** [comment]
Here is the full log:

V/MediaRouter(15561): Selecting route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=system types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
I/IL2CPP  (15561): Locale zh-Hans-CN
D/CompatibilityChangeReporter(15561): Compat change id reported: 147600208; UID 10611; state: ENABLED
I/Unity   (15561): scene = 4
I/Unity   (15561): UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
I/Unity   (15561): UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
I/Unity   (15561): UnityEngine.Logger:Log(LogType, Object)
I/Unity   (15561): UnityEngine.Debug:Log(Object)
I/Unity   (15561): SceneLoader:LoadScene(Int32)
I/Unity   (15561): UnityEngine.Events.UnityAction`1:Invoke(T0)
I/Unity   (15561): UnityEngine.Events.InvokableCall`1:Invoke(T1)
I/Unity   (15561): UnityEngine.Events.CachedInvokableCall`1:Invoke(Object[])
I/Unity   (15561): UnityEngine.Events.UnityEvent:Invoke()
I/Unity   (15561): UnityEngine.UI.Button:Press()
I/Unity   (15561): UnityEngine.UI.Button:OnPointerClick(PointerEventData)
I/Unity   (15561): UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
I/Unity   (15561): UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
I/Unity   (15561): UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
I/Unity   (15561): UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
I/Unity   (15561): UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
I/Unity   (15561): UnityEngine.EventSystems.StandaloneInputModule:Process()
I/Unity   (15561): UnityEngine.EventSystems
I/flutter (15561): Received scene loaded from unity: Demo_MediaPlayer
I/flutter (15561): Received scene loaded from unity buildIndex: 4
I/flutter (15561): Received scene loaded from unity: Demo_MediaPlayer
I/flutter (15561): Received scene loaded from unity buildIndex: 4
I/flutter (15561): Received scene loaded from unity: Demo_MediaPlayer
I/flutter (15561): Received scene loaded from unity buildIndex: 4
I/flutter (15561): Received scene loaded from unity: Demo_MediaPlayer
I/flutter (15561): Received scene loaded from unity buildIndex: 4
E/Unity   (15561): AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
E/Unity   (15561): java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
E/Unity   (15561): 	at java.lang.Class.classForName(Native Method)
E/Unity   (15561): 	at java.lang.Class.forName(Class.java:454)
E/Unity   (15561): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
E/Unity   (15561): 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
E/Unity   (15561): 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
E/Unity   (15561): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Unity   (15561): 	at android.os.Looper.loop(Looper.java:223)
E/Unity   (15561): 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
E/Unity   (15561): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.renderheads.AVPro.Video.Manager" on path: DexPathList[[zip file "/data/app/~~H-y6Mbgo7J-p_RmgEz4T9w==/com.xraph.plugin.flutter_unity_widget_example-B28WR46fsAwVazWcHeH4xg==/base.apk"],nativeLibraryDirectories=[/data/app/~~H-y6Mbgo7J-p_RmgEz4T9w==/com.xraph.plugin.flutter_unity_widget_example-B28WR46fsAwVazWcHeH4xg==/lib/arm64, /data/app/~~
D/FlutterUnityController(15561): this controller disposed
D/FlutterUnityController(15561): Attaching unity to view
I/Adreno  (15561): DequeueBuffer: dequeueBuffer failed
I/CustomUnityPlayer(15561): onDetachedFromWindow
D/FlutterUnityController(15561): Attaching unity to view

**Comment by decvim** [comment]
This is the key screenshot

https://tppr.me/vYRSd
https://tppr.me/JPfaT
https://tppr.me/vHjlX
https://tppr.me/GNJ1
https://tppr.me/TPMki
https://tppr.me/2qwQI
https://tppr.me/ONrDu
https://tppr.me/NIrxr
https://tppr.me/Ru354
https://tppr.me/8nCDk
https://tppr.me/icZBq

**Comment by decvim** [comment]
After repeated testing, it won't play after flutterSDK3.0,

**Comment by Chris-RH** [comment]
Sorry, I can't access most of those the screenshots.
What is the min/target SDK?
Have you run flutter clean and rebuild?

This does seem to be an issue with flutter
https://stackoverflow.com/questions/43435658/didnt-find-class-on-path-dexpathlist
https://developer.android.com/studio/build/multidex.html#mdex-gradle

**Comment by decvim** [comment]
It seemed to be the problem with Flutter, 
and after repeated testing,Return to the video player that came with Unity, normal.Enterprise projects spend a lot of time on AvPro and are hopeful

Hope, hope to solve the problem

-------------------------------------------------
android {
    compileSdkVersion 30
    buildToolsVersion '30.0.2'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 30
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        versionCode 1
        versionName '0.1'
        consumerProguardFiles 'proguard-unity.txt', 'proguard-user.txt'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.ress', '.resource', '.obb']
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    packagingOptions {
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
    }
}
--------------------------------------
build:
1，flutter pub get
2，flutter clean
3，flutter build apk--debug
--------------------------------------
------
https://pub.dev/packages/flutter_unity_widget/versions
Hopefully, you will download the tests from this link and only need to configure them，

**Comment by Chris-RH** [comment]
Hi @decvim,

Have you made sure Player Setting > Publishing Setting > Minify and make sure Release is not checked?

Make sure all the correct files are in your proguard
https://developer.android.com/studio/build/multidex#keep

Also, you may need to add "-dontobfuscate" at the end of your keep class list

**Comment by decvim** [comment]
![屏幕截图 2022-08-17 111826](https://user-images.githubusercontent.com/62234672/185027428-a9bb607e-e00c-431b-abf0-eca3c7559402.png)
![屏幕截图 2022-08-17 112059](https://user-images.githubusercontent.com/62234672/185027640-a48be5ae-1367-49be-b367-7a760446d308.png)

Thank you for your careful explanation，I can't spend time on problems these days. Abandon the use of AvPro plug-ins. I'm sorry

**Comment by decvim** [comment]
Yes, considering the reliability of avproVideo and cross-platform support for the project, I hope to realize playback in this project. Thank you very much!


  *   Looking forward to your sample results ！！


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Ste ***@***.***>
发送时间: 2022年10月27日 PM 7:43
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.renderheads.AVPro.Video.Manager" (Issue #1254)


@decvim<https://github.com/decvim> we received an email from you today with a project in. Does this mean you still require support? Because you closed this issue in August.

―

**Comment by decvim** [comment]
Sample address：
https://drive.google.com/file/d/1CbYCw86DMVDwwbeFh_Q-RosqL0MkXXb4/view?usp=sharing

**Comment by Ste-RH** [comment]
@decvim I am struggling to get anything to even build.  Can you write down the steps I need to perform please?

**Comment by decvim** [comment]
1) Install flutter_SDK.

2) Download Drat_sdk.

3) Configure the environment variable jdk.

4) Install Android studio and download the Android SDK.

5) Download flutter_unity_widget,

6) \flutter_unity_widget-2022.2.0\example\unity\DemoApp, open the directory project.

7) Download UnityPlugin-AVProVideo-v2.6.5-Trial.unitypackage, add DemoApp, and set the call video playback scene.

8) Build the Android project with the flutter Select button.

9) Use Android studio to open flutter_unity_widget to build apk

**Comment by decvim** [comment]
[https://drive.google.com/file/d/1CbYCw86DMVDwwbeFh_Q-RosqL0MkXXb4/view?usp=share_link](url) [sample for reference](javascript:;)

**Comment by Ste-RH** [comment]
I just need steps to get what you sent over building.

I downloaded 'flutter_windows_3.3.6-stable', opened '\flutter_unity_widget-2022.2.0\example\android\' in AndroidStudio, but on syncing I get the odd error: 'Caused by: Assertion failed:'

**Comment by decvim** [comment]
Open the sample premises I provided
1）\flutter_unity_widget-2022.2.0\example\unity\DemoApp, open the directory project，build
2）Android studio and Download relevant plug-ins： flutter， dart。

**Comment by decvim** [comment]
![屏幕截图 2022-11-01 112153](https://user-images.githubusercontent.com/62234672/199153182-32ac997c-4401-4dc0-af13-2c2ea8ad63f2.png)

**Comment by decvim** [comment]
If this project cannot be successfully built, you can try to recreate the sample, save time, thank you.

**Comment by Ste-RH** [comment]
I still get:

Caused by: Assertion failed: 

In Android Studio when I try to sync

**Comment by decvim** [comment]
be shocked at，Is flutter calling unity？ We don't see the flutter splash screen。
![屏幕截图 2022-11-02 104305](https://user-images.githubusercontent.com/62234672/199383122-15b92160-e447-4131-9d39-12435d269e59.png)

**Comment by Ste-RH** [comment]
I followed your steps and that is what I got.  Please provide accurate steps.

**Comment by decvim** [comment]
Here is the flowchart:
![1](https://user-images.githubusercontent.com/62234672/199469628-7f266584-709d-4f5d-875e-53f3165ddc0d.png)
![2](https://user-images.githubusercontent.com/62234672/199469651-9892a7aa-fd54-45d1-8b51-97cd5851bb64.png)
![3](https://user-images.githubusercontent.com/62234672/199469688-abfaa5e6-418b-4c44-9c69-77fa01c475fb.png)
![4](https://user-images.githubusercontent.com/62234672/199469717-ddf59659-baa8-4955-96b1-a9fff96e053c.png)
![5](https://user-images.githubusercontent.com/62234672/199469760-7e3b85c1-cba4-4e07-a0b2-1b9faf214141.png)

**Comment by decvim** [comment]
Greetings from the feeling! 
 
I'm sorry!  I didn't express myself clearly. 
 
unity is embedded into the flutter project and I need help with the flutter platform on how to successfully play AVProVideo. 
 
It was nice to see your results, however, as seen in the video, the unity project was not running on the flutter platform.

**Comment by Ste-RH** [comment]
Following what you posted, I am at this stage...but no way to build/run?

![image](https://user-images.githubusercontent.com/46531149/199491830-914b6cc0-2398-48ae-924d-c276485b5d12.png)

**Comment by Ste-RH** [comment]
For future reference, you need to:

- point Android Studio to the dart and flutter SDKs

![image](https://user-images.githubusercontent.com/46531149/199492732-a274e495-4ef7-424e-a583-0fefe28d037d.png)

![image](https://user-images.githubusercontent.com/46531149/199492815-36136582-242c-439d-b2ce-711c00c8b241.png)

**Comment by Ste-RH** [comment]
@decvim when I run 'main.dart' I am presented with the following:

![image](https://user-images.githubusercontent.com/46531149/199493791-a82cc646-effb-47b7-996b-7ec8724d011a.png)

**Comment by decvim** [comment]
Please refer to the following tags
![6](https://user-images.githubusercontent.com/62234672/199641632-297cba7e-cfc4-44a1-9fb4-b341f9b465c0.png)
![7](https://user-images.githubuserconte
![8](https://user-images.githubusercontent.com/62234672/199641650-19450f17-ec08-43e7-b48d-8b5de444d06c.png)
nt.com/62234672/199641639-3e
![9](https://user-images.githubusercontent.com/62234672/199641662-e5b13938-ad0a-4332-997c-18db26cef423.png)
118328-8098-469f-9392-65dd6a165cfd.png)

**Our project still brings you trouble.  You can try to rebuild the sample to speed up the localization of _AVProVideo_ problems.**

**Comment by decvim** [comment]
Please refer to the following tags

![6](https://user-images.githubusercontent.com/62234672/199641908-c13b0674-0f38-42c7-b48a-1b59bdccc66a.png)
![7](https://user-images.githubusercontent.com/62234672/199641919-1e65557f-5802-4249-8a57-40deefd087a6.png)
![8](https://user-images.githubusercontent.com/62234672/199641929-8401e1fe-ce08-496a-9b05-d00c2abdeace.png)
![9](https://user-images.githubusercontent.com/62234672/199641935-6a0c891f-95e0-4e19-a551-5c52c7bea37f.png)


Our project still brings you trouble.  You can try to rebuild the sample to speed up the localization of AVProVideo problems.

**Comment by decvim** [comment]
sample : 
https://pub.dev/packages/flutter_unity_widget

**Comment by Ste-RH** [comment]
I have it working here.  Not sure where or why, but a bunch of JAR libs are not making it into the gradle build script (for the unity part).  Adding these in manually means I get playback of the video.  Here is what I added:

![image](https://user-images.githubusercontent.com/46531149/199690581-299e0314-44dc-4d58-a6d7-603749afacb2.png)

NOTE: This is a debug build...so you might need some additions to the proguard file for a release build - I will attempt to check this now.

**Comment by decvim** [comment]
I never thought of that, unityLibrary/build.gradle, dependencies .

Let me try to run it

**Comment by decvim** [comment]
It worked out perfectly. Everything went well.Thank you very much for your patient answer

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

**Comment by Chris-RH** [comment]
Awesome!  Thanks for the update :D
