### ISSUE TITLE
VR) I want to change the STEREO FISHEYE to equirectangular projection.

### ISSUE THREAD

**Issue by WSVR** [RenderHeads/UnityPlugin-AVProVideo#1255]
HI .
I want to change the STEREO FISHEYE image to equirectangular projection. (180 3D SIDE BY SIDE)
https://i0.wp.com/360rumors.com/wp-content/uploads/2021/10/canon-workflow.jpg?w=830&ssl=1

The video is 180 DEGREE S3D. 
As far as I know, it would be possible to make a shader and apply it, can someone tell me how to make it?

 And DEOVR seems to have this function. i want to do this

 thank.

**Comment by Chris-RH** [comment]
Hi @WSVR,
I'm afraid that is out of the scope of AVPro support.  There are probably some tutorials available online with such information.
