### ISSUE TITLE
Play protected/encrypted HLS videos in WebGL

### ISSUE THREAD

**Issue by bgalerani94** [RenderHeads/UnityPlugin-AVProVideo#1256]
**Describe the issue**
I cannot find a way to set the requests' headers in order to play protected and encrypted videos while using WebGL.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.5f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  AVPro Video v2.5.7 - 28 July 2022 - Trial
 - Operating system version: WebGL with any browser
 - Device model: Any browser

**To Reproduce**
1. Try playing a protected/encrypted video

**Logs**
`GET https://***.m3u8 403`

`_AVPPlayerInsertVideoElement	@	WebGL.framework.js:1484
$WebGLMediaPlayer_AVPPlayerInsertVideoElement_m3B9E524441A61D38EEEBF43E660D705AF10E88E2	@	WebGL.wasm:0xbab5e8
$WebGLMediaPlayer_OpenVideoFromFile_mB8B3FD2A052BAD378D40F60244A9EEBDBD1BAC74	@	WebGL.wasm:0xbab93b
$MediaPlayer_OpenVideoFromFile_m5F2E5D1D9005417DB45402DF0724FBDC1A95399D	@	WebGL.wasm:0xbb92b1
$MediaPlayer_OpenVideoFromFile_m02FB47B479D4E69BA30C1AF88036F113D40F96B5	@	WebGL.wasm:0xbb9dbc
$VideoPlayer_LoadMedia_m0C1EAA4F5BE4918933CC462F1D3AD883DD822081	@	WebGL.wasm:0xbbcd44
$RoomUiController_U3COnEnableU3Eb__14_0_m561744D76F5AD496FFD574A289741B1BF3FB7A1D	@	WebGL.wasm:0xc88f95
$RoomController_GoneToSmartboard_mF817F247A8ABF4DBB64DC19627CF70E9C6B18FAA	@	WebGL.wasm:0xc88033
$RuntimeInvoker_TrueVoid_t4861ACF8F4594C3437BB48B6E56783494B843915(void (*)(), MethodInfo const*, void*, void**, void*)	@	WebGL.wasm:0x1ba4f19
$il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**)`

**Comment by Chris-RH** [comment]
Hi @bgalerani94,

We don't officially support WebGL, but here is a guide that might help you: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl
