### ISSUE TITLE
Xcode sandbox = TRUE stopping HSL stream?

### ISSUE THREAD

**Issue by BlueDonutStudios** [RenderHeads/UnityPlugin-AVProVideo#1257]
I don't think this is actually a bug, more advice. When building the Mac version of our unity app which has AVProVideo streaming, the video works fine. However, when submitting the xcode project to test flight for Mac, I must use sandbox and set that to true. The app goes to testflight, installs fine and runs. The only thing is the AVProVideo doesn't start playing the stream. It does show the thumnail. Is there a setting I need for entitlement to access the internet that is blocking this rather than there being a problem with the AVProVideo bundle? Any help would be greatly appreciated.

**Comment by Chris-RH** [comment]
Have you looked here: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#macos--ios--tvos

**Comment by BlueDonutStudios** [comment]
Ah @Chris-RH - Chris - thanks. No I've not. Thank you! I will read through that then have another go and report back. Thanks for getting back to me so quickly!

**Comment by Chris-RH** [comment]
no problem, let me know how you get on

**Comment by BlueDonutStudios** [comment]
Ok Success. But not using the settings in Unity. When you set the build platform for Mac there are no options to set the http (also you should not be using http it should be https). So this is all in the Entitlement in the xCode build if you use Xcode to submit to the Appstore. There is an excellent article here for how to setup App Sandbox for Mac. This will be needed to allow network connections for streaming or other network activity.
Here is the article: 
[Article](https://developer.apple.com/documentation/xcode/configuring-the-macos-app-sandbox)
This is in Xcode. So select the build target, then got to Editor>Add Capability and then select App sandbox. Then set App Entitlement for Inbound/Outbound connections as needed.
Also make sure that you set App Sandbox to true in the signing and capabilities otherwise you will get a fail on the upload to TestFlight.

So this is working nicely for us now.
Many thanks,
Marcus @BlueDonutStudios

**Comment by Chris-RH** [comment]
Awesome, thanks for the info :)
