### ISSUE TITLE
Audio track name is not populated

### ISSUE THREAD

**Issue by dawidchyrzynski** [RenderHeads/UnityPlugin-AVProVideo#1258]
**Describe the issue**
Audio tracks returned by the `MediaPlayer.AudioTracks.GetAudioTracks()` have empty name regardless of the metadata. It applies to both MediaPlayer and ExoPlayer.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.29f1
 - AVPro Video version: 2.5.7 ultra
 - Operating system version: Android 8.1
 - Device model: Pico G2
 - Video specs (resolution, frame-rate, codec, file size): H264, 3840x3840, 4 audio tracks (mp3)

**To Reproduce**
1. Open video file that contains multiple audio streams. Each audio stream should have `title` and `language` set
2. Call `MediaPlayer.AudioTracks.GetAudioTracks()` method. It returns proper amount of audio tracks but `name` property of each is empty.

**Comment by Chris-RH** [comment]
Does it work in the editor?

**Comment by dawidchyrzynski** [comment]
The editor (macOS Monterey) shows the list of tracks but the title is missing.

<img width="561" alt="Screenshot 2022-08-18 at 11 07 26" src="https://user-images.githubusercontent.com/7567202/185356898-46f0298e-f29e-4230-9fd4-2be80f1b8ddf.png">

Here is the metadata of the mp4 file:

<img width="928" alt="Screenshot 2022-08-18 at 11 09 04" src="https://user-images.githubusercontent.com/7567202/185357248-871ac272-adb4-4f05-9aed-8c37ab4772da.png">

VLC and MediaInfo apps are listing audio tracks properly with the title and language.

<img width="349" alt="Screenshot 2022-08-18 at 11 11 42" src="https://user-images.githubusercontent.com/7567202/185357784-952a481f-f2f3-4703-bff8-53b72c3649a5.png">

I have also noticed that "AudioTrack.Language" property is also empty on Android. See screenshots below. The first one shows C# implementation (printing audio tracks), the second shows the result.

<img width="960" alt="Screenshot 2022-08-18 at 11 13 04" src="https://user-images.githubusercontent.com/7567202/185358079-cd36f0b2-d5ca-421a-8bfd-89937d7a644f.png">

<img width="404" alt="Screenshot 2022-08-18 at 11 13 17" src="https://user-images.githubusercontent.com/7567202/185358130-17316f3c-0c26-436e-ad3d-7729920cd1be.png">

**Comment by Chris-RH** [comment]
OK, thank you for the clarification. Our Android dev is back from holiday
next week, so we will look into it further then.

**Comment by Ste-RH** [comment]
@dawidchyrzynski Is it possible to to send over the video you are seeing this with?  You can email it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com?subject=Issue%201258). Thanks!

**Comment by dawidchyrzynski** [comment]
@Ste-RH Done

**Comment by Ste-RH** [comment]
No fix possible for this issue currently due to API limitations
