### ISSUE TITLE
iOS with VoiceOver activated does not display videos

### ISSUE THREAD

**Issue by rtrn1337** [RenderHeads/UnityPlugin-AVProVideo#1259]
When Voice Over is activated, no videos are displayed. They are played but not displayed visually. If a player is set to loop, the first pass is not shown. Only when the second loop starts the videos become visible.
public bool HasValidTexture() returns false cause _mediaPlayer.TextureProducer and _mediaPlayer.TextureProducer.GetTexture() seems to be null in DisplayUGUI.cs.
 
 - Unity version: 2021.3.2f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core 2.5.7
 - Operating system version: iOS 15.6
 - Device model: iPhone 12 Pro 128GB
 - Video specs (resolution, frame-rate, codec, file size): https://rh-testmedia.s3-eu-west-1.amazonaws.com/Samples/BigBuckBunny-360p30-H264.mp4

**To Reproduce**
1. Create empty Unity URP Project with version 2021.3.2f1
2. Import AVPro Core 2.5.7 Package
3. Open the Demo Scene "Demo_MediaPlayer" 
4. Set Media Player to the media file (downloaded to StreamingAsset folder)
5. Create more than one VideoPlayer at the same Canvas
6. Build the project to an iOS device
7. Before starting the App activate VoiceOver in the iOS settings
8. Run the build via Xcode

**Additional Info**
It seems to be a problem with the AppleMediaPlayer.cs. The FirstFrameReady event is triggered immediately without Voice Over. But if Voice Over is activated, the event is only called after the first loop.

**Comment by Chris-RH** [comment]
Thank you for reporting this.  Our iOS dev is on leave at the moment, but will look into this when he gets back.

**Comment by MorrisRH** [comment]
We've reproduced this issue and a fix will make it into the next release.
