### ISSUE TITLE
 AVProPlayer try to access a private value , triggering a java Exception

### ISSUE THREAD

**Issue by defchen** [RenderHeads/UnityPlugin-AVProVideo#126]
**Describe the bug**
 AVProPlayer try to access a private value , triggering a java Exception 

**Your Setup (please complete the following information):**
 - Unity version: 2017.4
 - AVPro Video version:1.10.0 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

We had to delete the thread because we do not support decompiling of our native plugins.

Did you not receive an email with the reply to the last thread?  @RenderHeadsSte replied with some helpful advice.

Did we misunderstand?  It seems like you're decompiling the native plugin and trying to use it directly.

**Comment by defchen** [comment]
Because there exists an exception, it's dangerous and urgent for an online product. we need to know how does a newest AVPro version  throw an exception. we need to control the risk of this exception. decompiling is not the aim, we have already bought the product.

**Comment by defchen** [comment]
Decompiling is not the aim, cause of that we have already bought the
product. We just want to know why. Because there exists an exception, it's
dangerous and urgent for an online product. we need to know how does a
newest AVPro version throw an exception. we need to control the risk of
this exception.

Andrew <notifications@github.com> 于2019年7月24日周三 下午11:52写道：
