### ISSUE TITLE
Attempting to open an HLS m3u8 file with missing chunks causes freeze

### ISSUE THREAD

**Issue by rossstyants** [RenderHeads/UnityPlugin-AVProVideo#1260]
We are testing with an m3u8 where all the chunks are missing (index files are there) - at the point where I call MediaPlayer.OpenMedia(url...) - there is a huge 5 minutes ish freeze in Unity editor (DirectShow) - but also apparent on android. -
Is there anyway for me determine before calling OpenMedia whether or not this is a valid m3u8 - or are there some settings that would make OpenMedia just quickly return an error state?
Or is it possible to call OpenMedia asynchronously?
Thanks

**Comment by Chris-RH** [comment]
1. Is this in Windows or Mac editor? 
2. Have you tried Media Foundation?
3. Do you get the same result with the test streams: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#test-streams

**Comment by rossstyants** [comment]
Hey thanks for the quick response - this is in windows editor using DirectShow - I thought it was doing the same thing on the Quest but actually it's not - on the Quest the error is quickly caught and a loading failed error is returned. Will have a go with the test streams on editor soon thanks.

**Comment by Chris-RH** [comment]
Thanks, let us know how that goes please :)

**Comment by Chris-RH** [comment]
Closed due to lack of response

**Comment by Chris-RH** [comment]
Great thanks.
 let me know the results please :)
