### ISSUE TITLE
GLSL Shader with OES Rendering - Position Locked ? 

### ISSUE THREAD

**Issue by FlorianJullien** [RenderHeads/UnityPlugin-AVProVideo#1262]
**I am trying to change the position of a mesh that is rendering a 360Video (or flat - I use both in project) in update using camera position**
I am using OES Rendering on Android to render videos on Meshes using `Apply To Mesh` Script. This Mesh uses the `AVProVideo-Unlit-AndroidOES shader` and I am having an issue re-positioning the Mesh. The mesh is a sphere and the behaviour wanted is a basic follow of the Sphere center with the camera.
The position is set basically via a script : `gameobject.transform.position = cam.position;` in Update. 
There are no problems of rendering : the video loads and displays as wanted. 
The Question is : Is the position of the rendering locked in the Shader ? 

**My setup**
 - Unity version: 2020.3.33
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.5.7 Core Edition 
 - Operating system version: Windows 10
 - Device model: Tested on Galaxy s10+ (Android 12), Galaxy A20 (Android 11), Redmi Note Pro 8 (Android 10)
 - Video specs (resolution, frame-rate, codec, file size): most of the videos are 4k, 30fps, around 60-70MB, mp4, from 1 to 4  min duration

**Possible Lead**
I guess it has something to do with this line on the Shader but I am afraid I can't go further on this without help ! 
![image](https://user-images.githubusercontent.com/85178681/185173411-61ef1d86-c0ff-460a-a1ac-ac7d906ee748.png)

Thank you for your answers !

**Comment by Ste-RH** [comment]
The calculated transform of the hierarchy, including the spheres gameobject transform, should still be concatenated in.  Are you seeing an issue here?

**Comment by Ste-RH** [comment]
Closing due to lack of response.  Please re-open if this is still an issue.
