### ISSUE TITLE
Crashes when used in conjunction with ReShade

### ISSUE THREAD

**Issue by GenesisAria** [RenderHeads/UnityPlugin-AVProVideo#1263]
When ReShade is present, AVPro crashes and fails to playback video.

 - Unity version: **2019.4.31f1**
 - AVPro Video version: **Unsure, probably most recent**
 - Operating system version: **Windows 10/11**
 - Hardware irrespective.
 - Video specs (resolution, frame-rate, codec, file size):   **Any**

Not entirely sure the extent of scenarios which cause this, don't know how to implement AVPro myself, so i cannot test this in a bench environment.  An example case is using the stream players (avpro) in vrchat, they result in playback error, which they are scripted to reattempt, and it happens indefinitely.  It does not matter what the video content is, and i suspect this happens in any application environment where reshade and avpro are both present. Have tested against many versions of reshade.  Have also confirmed with others that have same issue, confirming it happens on completely different hardware.

**Comment by Chris-RH** [comment]
Hi @GenesisAria 

Would you be able to provide some logs so that we can see what is happenning?

**Comment by GenesisAria** [comment]
I'm not sure exactly what logs i'd provide... Any logs i know of in the case that affects me most (vrchat), as they don't provide any relevant information to technical issues within the plugins.  All that exists in the game's log is a generic message stating the decode failed.

**Comment by Chris-RH** [comment]
I'm not sure what we can do about them using a 3rd party post-processing injector in your finished app? Reshade can change be configured to change a number of things.  
Do you know what they are trying to achieve with it?
