### ISSUE TITLE
Using unity to export to webgl, under IOS browser, can you change the path at runtime and support automatic playback?

### ISSUE THREAD

**Issue by milan-hwj** [RenderHeads/UnityPlugin-AVProVideo#1264]
**Describe the issue**
Using unity to export to webgl, under IOS browser, can you change the path at runtime and support automatic playback?

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.31
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.7

Modify the video path at runtime through the following code:
```
mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, "...", true);
```
After calling this method, avpro will control the browser to create a video tag, and will not complete the path switching by modifying the SRC attribute of the original video tag.   

In the IOS browser, the new video tag needs to be triggered by the user's click. This means that when playing multiple videos using 'openmedia', the user needs to click each time to continue playing, and the video list cannot be played automatically.

**Comment by Chris-RH** [comment]
Our iOS dev is on holiday at the moment and will have a look at this next week.
