### ISSUE TITLE
TextureFrameCount is zero on Windows.

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1265]
- Unity version: 2020.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.7
 - Operating system version: Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): https://mediapocams2-koct1.streaming.media.azure.net/8b9e67e4-5d16-45d1-8e50-6fd057ec4c63/b5af24d8-4e63-40bd-8053-dc19aca0.ism/manifest(audio-only=false,format=m3u8-aapl-v3).m3u8#loop

TextureFrameCount is zero on Windows.
I received the FirstFrameReady event, but the texture is black.

**Comment by dw8869** [comment]
![captured](https://user-images.githubusercontent.com/64513117/185845007-243f2266-76e5-402e-99c7-968523352bf7.png)

**Comment by Chris-RH** [comment]
Hi @dw8869,

Could you show me what code you have written to implement this please?
Have you tried playing this just in our default media player demo scene?

**Comment by dw8869** [comment]
@Chris-RH 
The screenshot above was reproduced in the `Demo_MediaPlayer` scene.

```
Auto Open = true
Auto Play = false
Other options = default
```

**Comment by Chris-RH** [comment]
I've tested this on my Windows 10 machine using Unity 2020.3.37 and 2021.3.6, DX11, AVPro 2.5.7.  
I have opened a new project each time, with just AVPro Video.  I entered your URL provided and the only change I made was to untick "Autoplay".  I get this: 
![1265](https://user-images.githubusercontent.com/102963025/185906664-b24e5278-fa22-4ea8-abc2-e21701f5e457.jpg)

**Comment by dw8869** [comment]
This issue is not always reproduced.
Our application can not use "AutoPlay".

It can occur by repeatedly clicking the `Load` button `Close` button on the inspector.

**Comment by Ste-RH** [comment]
Just for clarity.  This is only a problem in the inspector?  You get the texture as expected in your actual application, yeah?

**Comment by dw8869** [comment]
@Ste-RH 
This issue also occurs with built applications.

**Comment by Chris-RH** [comment]
I am very very occasionally getting no FirstFrameReady firing, which in turn will obviously not have a texture.
I cannot repeat this in other m3u8 streams that I have available.

1. What are the different versions of your video?
2. Do you have any that are audio only?

**Comment by dw8869** [comment]
1. I didn't understand the question. This is the only video i have.
2. No, i don't have.

**Comment by Chris-RH** [comment]
Just to let you know, we are still looking into this for you :)

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this issue has not been fixed for you.
