### ISSUE TITLE
Video Loop not working

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [RenderHeads/UnityPlugin-AVProVideo#1268]
**Describe the issue**
When I open a video by scripts (using `OpenMedia`) the Loop command seems to not working (also under Editor)..

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.8f1
 - AVPro Video - Core Edition  2.5.7
 - Operating system version: macOS 12.5.1
 - Device model: iPhoneSE / MacBook Pro 2019
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080 / Timecode, AAC H.264 / 5.7MB

**To Reproduce**
1. Write a script opening a video
2. add `mediaPlayer.Loop = true`
3. run

**Videos**
https://user-images.githubusercontent.com/63807677/186162526-11540b4f-9e5c-4532-8331-4ab9be837e95.mp4

Thanks in advance
Eric

**Comment by Chris-RH** [comment]
Hi @EricBeetsOfficial-Opuscope,

mediaPlayer.IsLooping() 

In the mediaplayer component you can also set playback to loop
https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#main

**Comment by vlisk** [comment]
avpro version 2.5.7, 
iphone 13 pro
ios version is 15.6.1

description:
media playback loop is not not work, it present stop at last frame

**Comment by vlisk** [comment]
any one can help?

**Comment by Chris-RH** [comment]
Hi @vlisk 
Did you try either of the above suggestions?

**Comment by EricBeetsOfficial-Opuscope** [comment]
> Hi @EricBeetsOfficial-Opuscope,
> 
> mediaPlayer.IsLooping()
> 
> In the mediaplayer component you can also set playback to loop https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#main

I also tried that .. It seems when we use an async code (based on UniTask) it does not work (with sync code, it seems to work..).
I will try to prepare a script to show it ..

**Comment by vlisk** [comment]
@Chris-RH  i am try mediaPlayer=true,but not work, i use below method when finsh event fired
   mediaPlayer.Control.SeekFast(0);
   mediaPlayer.Control.Play();
it work ，but i do not think it is the best method

**Comment by Chris-RH** [comment]
We'll look into the code for this, thank you.

**Comment by MorrisRH** [comment]
The bug is caused when the looping toggle in the media player inspector is unchecked. You can work around it for now by making sure that looping is enabled before calling OpenMedia and then disabling it before you start playback.

We're working on a fix which should make it into the next release.

**Comment by MorrisRH** [comment]
This issue has now been fixed and the fix will be available in the next release.

**Comment by vlisk** [comment]
@MorrisRH we buy at unity assetstore,how could we get the new release with bug fixed!!

**Comment by Ste-RH** [comment]
We ware aiming to send out a new release later today @vlisk .  You will be able to download the update, once released, via the Unity ecosystem.

**Comment by Chris-RH** [comment]
Version 2.6.1 has been released. Please let us know if the issue has not been fixed for you.
