### ISSUE TITLE
Crash when playing video with WinRT on Windows 10

### ISSUE THREAD

**Issue by christianYS** [RenderHeads/UnityPlugin-AVProVideo#1269]
**Describe the issue**
We received a crash report from a user on a Lenovo laptop running Windows 10. The app crashes every time a video is played with WinRT video api. 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.34
 - AVPro Video version: 2.5.3 Enterprise
 - Operating system version: Windows 10
 - Video specs: MP4 encoded with H264, 560p [https://d3mzlbmn9ukddk.cloudfront.net/tasks/video/6dec0efb-735e-4784-aece-cd21831660b7.mp4](https://d3mzlbmn9ukddk.cloudfront.net/tasks/video/6dec0efb-735e-4784-aece-cd21831660b7.mp4)

**Logs**
[crashlog.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9402949/crashlog.txt)

**Comment by Chris-RH** [comment]
Hi @christianYS

This is strange.  I've just done a quick check using our demo media player scene (win10, dx11,unity 2020.3.37 and avpro 2.5.3) and it seems to run as expected using WinRT api.
Do you have any further details as to which lenovo laptop they are using? I'm wondering whether it is a hardware thing? memory perhaps?

**Comment by christianYS** [comment]
We also have verified in-house that the video plays as expected in Windows. I expect that the issue might be specific to the user's machine. It might be that it's using some old hardware and/or outdated drivers. 
I have requested more information from the user, and also to update the graphics drivers. But also wanted to hear your informed opinion on how we should prevent cases of hard crashes like this

```
0x65052BCA (AVProVideoWinRT) GetRenderEventFunc_FreeTextures
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 65048224)
0x65048224 (AVProVideoWinRT) (function-name not available)
0x65052570 (AVProVideoWinRT) OnRenderEvent_UpdateAllTextures
```

**Comment by Chris-RH** [comment]
Have you had any updates from the user?
At this moment we don't really have sufficient information to go on re: crash cause/prevention.

**Comment by Chris-RH** [comment]
Closed due to lack of information
