### ISSUE TITLE
Android: SetPlaybackRate fails if video is playing on MediaPlayer

### ISSUE THREAD

**Issue by artoonie** [RenderHeads/UnityPlugin-AVProVideo#1274]
**Describe the issue**
`SetPlaybackRate` throws exception if changing while video is playing

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.7f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.5 Core
 - Operating system version: Android 11
 - Device model: Pixel 2
 - Video specs (resolution, frame-rate, codec, file size): 1080, h264, 600mb

**To Reproduce**
1. Play a video (using `MediaPlayer`, not `ExoPlayer`)
2. Change Playback Rate
3. Note an exception, as pasted below:

**Logs**
```
08-29 11:12:21.078 14779 14857 E Unity   : AndroidJavaException: java.lang.IllegalArgumentException                                                                                              
08-29 11:12:21.078 14779 14857 E Unity   : java.lang.IllegalArgumentException                                                                                                                    
08-29 11:12:21.078 14779 14857 E Unity   :      at android.media.MediaPlayer.setPlaybackParams(Native Method)                                                                                    
08-29 11:12:21.078 14779 14857 E Unity   :      at com.renderheads.AVPro.Video.Player_MediaPlayer.SetPlaybackRate(Player_MediaPlayer.java:28)                                                    
08-29 11:12:21.078 14779 14857 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)                                                                                    
08-29 11:12:21.078 14779 14857 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)                                                                                   
08-29 11:12:21.078 14779 14857 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)                                                                           
08-29 11:12:21.078 14779 14857 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)                                                                                          
08-29 11:12:21.078 14779 14857 E Unity   :      at android.os.Looper.loop(Looper.java:223)                                                                                                       
08-29 11:12:21.078 14779 14857 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)                                                                                       
08-29 11:12:21.078 14779 14857 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0                                                   
08-29 11:12:21.078 14779 14857 E Unity   :   at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0           
08-29 11:12:21.078 14779 14857 E Unity   :   at RenderHeads.Media.AVProVideo.AndroidMediaPlayer.SetPlaybackRate (System.Single rate) [0x00000] in <00000000000000000000000000000000>:0
```

**Workaround**
Pause / SetPlaybackRate / Resume works fine

(side note: Not sure if this happens with ExoPlayer too. It doesn't work out of the box; I get `AndroidJavaException: java.lang.NoClassDefFoundError: com.google.android.exoplr2avp.audio.AudioCapabilities` and haven't investigated further.)

**Comment by Ste-RH** [comment]
I cannot reproduce this here on a Xiaomi Mi 10T running Android 11.  I am using the Big Buck Bunny video we include with the asset.  I tried both MediaPlayer and ExoPlayer API paths.  Both work exactly as I would expect.

According to the documentation (https://developer.android.com/reference/android/media/MediaPlayer#setPlaybackParams(android.media.PlaybackParams) ...an IllegalArgumentException will be thrown if the 'params is not supported'.  Not sure why this would be the case.

Have you tried different (our sample) videos and other devices @artoonie ?

**Comment by artoonie** [comment]
Ah, I see what went wrong - it seems that on Android (at least on MediaPlayer), 4x is the max speed that can play. This behavior occurs when changing speed to 8x or higher.

I suppose one minor feature request would be to propagate that IllegalArgumentException through C# to the caller, so when playbackspeed is set to an invalid value (in this case, 8x), an exception is thrown. Or perhaps to limit playback speed or document this in some other way.

I'll close this out for now; lmk if you want me to create a separate report for the minor feature request above.

**Comment by Ste-RH** [comment]
I cannot find any lower/upper limits, so have added a try/catch around the parameter setting code as a failsafe.  Thanks for reporting the issue @artoonie.
