### ISSUE TITLE
DLL not found on Windows after importing project from MacOS

### ISSUE THREAD

**Issue by GabrielReisESilva** [RenderHeads/UnityPlugin-AVProVideo#128]
Hello,
I've being working on my project on Mac for the past month and it was working perfectly, 
but now I need to import to Windows. I cloned my repo on a Windows machine,
but when I try playing it, it shows errors:

[AVProVideo] Failed to load DLL. AVProVideo
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:GetPluginVersion() (at Assets/AVProVideo/Scripts/Editor/MediaPlayerEditor.cs:1186)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:IsTrialVersion() (at Assets/AVProVideo/Scripts/Editor/MediaPlayerEditor.cs:187)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnEnable() (at Assets/AVProVideo/Scripts/Editor/MediaPlayerEditor.cs:195)

and

[AVProVideo] Not supported on this platform WindowsEditor System Product Name (System manufacturer) Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz Windows 10  (10.0.0) 64bit.  Using null media player!
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:CreatePlatformMediaPlayer() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1619)
RenderHeads.Media.AVProVideo.MediaPlayer:Initialise() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:467)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile(FileLocation, String, Boolean) (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:541)
Timeline.TimelineScreen:PlayVideo(String) (at Assets/Scripts/TimelineScreen.cs:135)

**Comment by AndrewRH** [comment]
Can you confirm that the two DLL files are there?  They are usually in the /AVProVideo/Plugins/x86 and /AVProVideo/Plugins/x86_64 folders.
It's possible that if you used a version control system that the files were not included.

Also, if you click on the DLL files, in Unity it will have an option for which platform and architecture they are set to.  Ensure they are set to the correct archecture (eg 32/64-bit) for both Editor and Standalone applications.   These details are usually storred in the .meta files, but if these are deleted or corrupted then you may have to reset these.

Hope that helps?

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.

**Comment by josette-seitz** [comment]
I was also having this issue and noticed I didn't import Plugins folder with x86 and x86_64. Once I imported those missing folders, I was good to go! Thanks guys. This saved a lot of headache.
