### ISSUE TITLE
Unable to open file from https url on Quest 2

### ISSUE THREAD

**Issue by tap2k** [RenderHeads/UnityPlugin-AVProVideo#1282]
**Describe the issue**
AVProVideo not opening videos from URL on Meta Quest 2

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.3f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.4 core
 - Operating system version: Android
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 192x960, 360, hl264, 17mb

**To Reproduce**
1. set up media player
2. try to load media from https url
3. mediaplayer calls internalopenmedia, but no error message is logged, and no GET request is performed on server
4. I am able to open the same file without issue in the editor
5. I am using nginx as a web server

**Logs**
2022/09/01 15:41:53.516 20959 20980 Info Unity [AVProVideo] Opening https://mvc.represent.org/strapi/uploads/temple_small_2162c17d51.mp4 (offset 0) with API ExoPlayer
2022/09/01 15:41:53.516 20959 20980 Info Unity RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()

**Screenshots**

**Videos**
https://mvc.represent.org/strapi/uploads/temple_small_2162c17d51.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Can you:

- Try updating to the latest version of AVPro Video
- Send over a full logcat output

**Comment by tap2k** [comment]
Yes that worked. Was an old version. Thanks
