### ISSUE TITLE
Can't play live streaming videos

### ISSUE THREAD

**Issue by mecadiego113** [RenderHeads/UnityPlugin-AVProVideo#1287]
We recently purchased this awesome AVProVideo asset to play video streamings in Unity.

Our current problem is that we cannot play standard HTTP videos from URL (like http://192.168.1.1:8080). We used to be able to do that with other plugins or assets for Unity like the Universal Media Player (which I think uses VLC libraries).
Is there any way to play this kind of realtime streaming videos comming from HTTP/HTTPS URLs?

Thank you!

**Comment by MorrisRH** [comment]
HTTP(S) URLs are fully supported across all platforms so I'm not sure why this isn't working for you. What kind of media are you trying to playback? (HLS or mp4).

We use local network URLs all the time here for testing so something like ```http://192.168.1.1:8080/path/to/video.mp4``` will definitely work. If it's not working for you then I would suggest either your server setup is incorrect or you have a firewall blocking access.

Can you provide an example URL that is not working?

HTTPS will require that the certificate is valid which may be problematic, self-signed certificates are unlikely to work.

**Comment by Chris-RH** [comment]
Can you provide a bit more information please @mecadiego113 ?

**Comment by Chris-RH** [comment]
@mecadiego113 
Android can be funny about http.  Https is absolutely fine.  
Perhaps try the solution offered in here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/510
If that does not work, it is most likely your server setup.

**Comment by Chris-RH** [comment]
Closed due to lack of response
