### ISSUE TITLE
Resolve To RenderTexture doesn't work on Android

### ISSUE THREAD

**Issue by rhduwe** [RenderHeads/UnityPlugin-AVProVideo#1289]
**Description**
The component doesn't seem to work on android at all and there is no distinct error message. I've played around with resolve flags and RT settings but nothing seems to change the result. 
I've sent you a repro project, please take a look. I've setup a couple of control displays, so I could be sure that the media player itself and the render texture work in isolation. 
I've tested (though not rigorously) on two AVPro versions, standard and URP pipelines and two devices. 

**Setup:**
 - Unity version: 2021.3.7f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.5.7 core / 2.6.2 Trial
 - Operating system version: WIndows 10 / Android arm64-v8a
 - Device model: POCO M3, Oculus Quest 2

**To Reproduce**
1. Create a new empty project in unity
2. Import AVPro and add a media player with any video
3. Add a Resolve To RenderTexture component and create a render texture
4. Add a display with material referencing the render texture
5. Build for android

Expected behaviour: video displays properly both in playmode and android build
Actual result: video displays in playmode, but not on the device

**Comment by Ste-RH** [comment]
Thanks for reporting this issue @rhduwe.

It appears to be a regression issue when we added Android OES support.

As a temporary fix, if you are not using OES, you can overwrite the attached shader (found in: \Assets\AVProVideo\Runtime\Shaders\Resources\)

[AVProVideo-Internal-Resolve.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9548410/AVProVideo-Internal-Resolve.zip)

We will look into fixing this issue for the next release of AVPro Video.

**Comment by Ste-RH** [comment]
Or, alternatively...you can leave the shader alone and enable the OES flag in the MediaPlayer component Android options.

**Comment by Ste-RH** [comment]
A fix for this will be in the next release (v2.6.3).

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this issue has not been fixed for you.

**Comment by rhduwe** [comment]
Yes, the 2.6.3 version works fine. Thanks for the quick response and alternative solutions.
