### ISSUE TITLE
How to integrate third party decoding libraries?

### ISSUE THREAD

**Issue by linxin2020** [RenderHeads/UnityPlugin-AVProVideo#129]
We are using your AV PRO player for our mobile app now,
some android phones display black screens in 4k video playback.
It is estimated that some mobile phone system does not support 4K decoding.
Is it possible to integrate third party decoding libraries(for example, ffmpeg)?

**Comment by RenderHeadsSte** [comment]
Have you tried using the ExoPlayer API path and checking the 'Prefer Software Decoder' option?

**Comment by linxin2020** [comment]
@RenderHeadsSte 
This method has been tested and it doesn't work.
In addition, we also tried to set the PlatformOptionsAndroid.preferSoftwareDecoder. 
The results are the same.

**Comment by AndrewRH** [comment]
We don't play on adding support for FFMPEG or other 3rd party decoding libraries.

The above issue is probably related to the hardware just not being able to decode the video - but software fallback would be so slow, so a better solution should be used (eg HLS).
