### ISSUE TITLE
Oculus Quest 2 Apply to Mesh stereo not working

### ISSUE THREAD

**Issue by angelaumenta** [RenderHeads/UnityPlugin-AVProVideo#1292]
**Describe the issue**
Hello, I have a video (transparent, alpha top/bottom, stereo left/right), already set up in Media player. 
video on Apply to Mesh (both materials, Unlit Transparent and Transparent... Android OES Only)
When build and running in Oculus Quest 2,  not rendering in stereo. (works in play mode)

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.6f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Version 2.6.2 - September 08, 2022 - Core Edition
 - Operating system version: Android
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Media Player component with video (transparent, alpha top/bottom, stereo left/right)
2. Plane with Apply to mesh
3. Already Updated Multi Pass Stereo on central EYE Anchor tested

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
https://aumenta.s3.eu-west-1.amazonaws.com/idibell/benvinguda_cat.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Do you have the AVPro Video 'UpdateMultiPassStereo' component in your scene and hooked up to your camera?

**Comment by angelaumenta** [comment]
Yes
[image: image.png]

Missatge de Chris-RH ***@***.***> del dia dc., 14 de set.
2022 a les 12:56:

**Comment by Ste-RH** [comment]
Does this happen with OES disabled? (with the shader changed accordingly)

Are you using SRP or UDP?

**Comment by angelaumenta** [comment]
> Does this happen with OES disabled? (with the shader changed accordingly)
> Tried with both (Unlit Transparent and Transparent... Android OES Only)
> Are you using SRP or UDP?
> Not sure (how to check ?)
> Are you using Multiview or Multipass?
Multipass

**Comment by angelaumenta** [comment]
![Captura](https://user-images.githubusercontent.com/113450833/190144820-e5ea1b2d-7dce-4be1-8f55-9b0dd3bb3f15.PNG)

**Comment by angelaumenta** [comment]
![Captura2](https://user-images.githubusercontent.com/113450833/190145714-62759332-9f67-45ba-9d64-60acadee53ed.PNG)

**Comment by Ste-RH** [comment]
I think it will be the quickest solution if you can send over a simple project showing the issue.  Please email it to [unitysupport@renderheads.com](unitysupport@renderheads.com?subject=Issue-1292)

**Comment by angelaumenta** [comment]
Done :
https://aumenta.s3.eu-west-1.amazonaws.com/idibell/Unity/IDIBELL_VR_v2_20220915.rar

Missatge de Ste Butcher ***@***.***> del dia dc., 14 de set.
2022 a les 13:53:

**Comment by Ste-RH** [comment]
@angelaumenta I cannot find/see the UpdateMultiPassStereo component in your scene (Scene_01)

Adding this component, and using the correct shader and I have stereo working as it should on an Oculus 2.  These are the only two changes I made to your project.  Here are screenshots of the changes:

![image](https://user-images.githubusercontent.com/46531149/190672475-46e9a7ff-ea4a-4052-8c6d-5c23fdbc620a.png)

![image](https://user-images.githubusercontent.com/46531149/190672352-b222a606-9feb-436a-8fad-86778e6a1733.png)

Note that the 'Stereo Debug Tinting' being enabled will shade the left and right eye green/red respectively.  It is only enabled to check stereo is working correctly, and should naturally be disabled for your final project.

**Comment by angelaumenta** [comment]
It Works ... PERFECT !! Thanks a lot for your quick reply.

**Comment by Chris-RH** [comment]
Great, thanks for letting us know :)
