### ISSUE TITLE
Cannot build Addressable with AVProVideo in project

### ISSUE THREAD

**Issue by l0th3r** [RenderHeads/UnityPlugin-AVProVideo#1294]
**Describe the issue**
Im am not currently using AVProVideo in my addressable or anything.
I just use it in the project for other uses.
And I am not trying to uses videos in addressable, both are not related.
AVProVideo dependencies are in the `Build In Data` group.
I checked assemblies définitions, and the project build correctly other than the addressables.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.5f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 1.11.7
 - Operating system version: Windows 11 Pro 21H2

**To Reproduce**
1. Import AVProVideo and Addressable packages
2. Create Addressable groups other than `Default` and assign at least one asset as Addressable
3. Try to build Addressable

**Logs**
`Assets\AVProVideo\Scripts\Editor\DisplayUGUIEditor.cs(33,11): error CS0246: The type or namespace name 'SerializedProperty' could not be found (are you missing a using directive or an assembly reference?)`

**Screenshots**
![image](https://user-images.githubusercontent.com/58365407/190368313-2a253a50-4d92-4133-9ddb-2ec3d51d7c04.png)

**Comment by Chris-RH** [comment]
Hi @l0th3r,

We don't have much experience of Addressables (seeing as we don't use them), but have you tried this:
https://stackoverflow.com/questions/71803437/the-type-or-namespace-name-asyncoperationhandle-could-not-be-found

**Comment by l0th3r** [comment]
After some tests, my project does not build. I think it's more due to dependencies than Addressables.
I must have a problem in my assemblies definitions, the AVProVideo Editor script seem not to be imported correctly since the error logs only concern those files.

This is my current assemblie definition: 
![image](https://user-images.githubusercontent.com/58365407/190378277-a74601a6-e2bd-432d-9dad-1db1b0533756.png)

Do you know if I am missing something for me to not have errors with the `AVProVideo/Scripts/Editor` scripts ?

**Comment by Chris-RH** [comment]
It could be a lot of things. 1.11.7 is depreciated and has not been tested with Windows 11 or Unity 2021x.  Are you using D3D11 or 12?

Have you tried reimporting the asset?
Have you tried building it in a fresh project with just AVPro Video?

**Comment by l0th3r** [comment]
I have tried to build a empty project with just AVProVideo and I have the same problem. I have tried to re-import the `.unitypackage` file and I have the same issues.

I found a temporary solution, when importing the package, no `asmdef` file was present in it. I decided not to create one and it work. The problem is that I was creating an asmdef file for AVPro for architecture purposes.

With the assemblies gone, it build fine.

**Comment by Chris-RH** [comment]
Which version of 1.11.7 are you using?

**Comment by l0th3r** [comment]
The release note in the documentation is dated the 13th of November 2020.

![image](https://user-images.githubusercontent.com/58365407/190439848-633ce22a-ad65-418f-9a32-9a7e07ec3ff6.png)

**Comment by Chris-RH** [comment]
Well its good for us to know that it can work under Windows 11.  I presume you are using D3D11?

https://stackoverflow.com/questions/40064746/the-type-or-namespace-name-unityeditor-could-not-be-found
https://docs.unity3d.com/ScriptReference/SerializedProperty.html
https://docs.unity3d.com/ScriptReference/MenuItem.html

asmrefs are a newer way to define editor only code, the Editor special folder is the old way. They don't intermix.
Any child directories will be included by the asmref. The Editor special folder will be ignored if it is included in the asmref. You should either move the Editor folder so it is not inside of an asmref or add another asmref inside of the Editor folder and set it to be Editor only.
