### ISSUE TITLE
The app hangs during a long video play that is 6 minutes and 37 seconds on Android.

### ISSUE THREAD

**Issue by han4198** [RenderHeads/UnityPlugin-AVProVideo#1295]
**Describe the issue**
Hi.
I often use AVPro Video - Core Edition.
But there's a problem.
In iOS, the URL path video is played until the end without any problems
But on Android, long videos are not played until the end, but the app itself stops and app crashes.
I don’t' know the reason.
It was something that couldn't be checked on GitHub Problem site.
The app hangs during a url path video play that is 6 minutes and 37 seconds on Android.
I sent an email to unitysupport@renderheads.com with details. Please check and reply.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.36f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.3.1(plugin v2.3.0f1-core)
 - Operating system version: Android 9
 - Device model: Galaxy S8 edge
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by Chris-RH** [comment]
2.3.1 is nearly a year old, have you tried updating to the newest version?

**Comment by han4198** [comment]
> 2.3.1 is nearly a year old, have you tried updating to the newest version?
> 
> Could you try and get a full logcat when this happens: https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs
> 
> Does it happen with one particular file or any video that you are streaming for that long? Have you tried one of our test streams? The first one is 12 minutes long: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#test-streams


Thank you for your answer.
I updated the version of AV Pro to the latest version and it works well.
I want to know the cause, but the work went well.
I wonder why the url video was cut off in the middle of the 2.3.1 version.

**Comment by Chris-RH** [comment]
Hi, thanks for the update, I'm glad its working for you now.
There have been several updates since 2.3.1, including newer version of exoplayer, so it could have been caused by a number of things.
