### ISSUE TITLE
Incorrect byte range requests

### ISSUE THREAD

**Issue by mevlme44** [RenderHeads/UnityPlugin-AVProVideo#1296]
I have a server that streams video using HLS. The server supports range requests, but often when trying to play a video, either empty or incorrect range requests are received. Please tell me where I went wrong.

 - Unity 2019.4.30f1
 - AVPro Video - Core Edition Version 2.6.2
 - Windows 10 Pro x64: 
 - PC, Intel(R) Core(TM) i5-10600K, NVIDIA GeForce GTX 1650, 32Gb Ram.
 - 1280x720, 25 fps, h264, 26.48 Mb

**To Reproduce**
1. Paste video url to Media Player and click to load with autoplay.

**Logs**
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Screenshots**
Incoming range requests to the server
![1](https://user-images.githubusercontent.com/56146140/190856005-3083495a-a057-49d5-98f2-86791f49c31e.png)

**Videos**
https://ytp.inreal.online/2/getVideo/th4Czv1j3F8

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Hey @mevlme44, I', not sure what the issue is, those range requests look valid.

**Comment by Chris-RH** [comment]
Hi @mevlme44 

I've tried it on my Windows 10 machine using Unity 2019.4.0 and 2021.3.36, and AVPro Video 2.6.2.  It works fine in Media Foundation, Direct Show and WinRT APIs, though it does take about 10-15 seconds to load.  
Have you tried it under the different Video APIs?
https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---windows

**Comment by mevlme44** [comment]
@Chris-RH @MorrisRH , thanks for the answer. The problem is in the long loading of the video and the interruption of playback. I sent the server code to the mail. In the browser, the video loads instantly and plays without delay, but in Unity it's not so good.

**Comment by MorrisRH** [comment]
The video you linked is not HLS, it's a webm format video. I suspect that windows is unable to play it as a progressive download and is choosing to download the whole file before playback starts. 
I would recommend that you put it in an mp4 container with faststart enabled and re-encode the audio as aac for maximum compatibility. You can use the following ffmpeg command to achieve this:
```
ffmpeg -i th4Czv1j3F8.webm -c:v copy -c:a aac -movflags faststart th4Czv1j3F8.mp4
```

**Comment by Chris-RH** [comment]
Have you had any success with that @mevlme44 ?

**Comment by mevlme44** [comment]
It looks like I really made a mistake in the video encoding. Thanks
