### ISSUE TITLE
Hap / Notch Videos larger than 8192px

### ISSUE THREAD

**Issue by johannesklaer** [RenderHeads/UnityPlugin-AVProVideo#1297]
Hi, I bought the AVPro Ultra Edition and try to play a video which has a pixel size larger than 8192 pixels. It seems that AVPro neither plays Hap Videos nor Notch Videos that size. The Video Size is 12000 x 2304. In both cases the Error Message is:

[AVProVideo] Error: Loading failed File not found, codec not supported, video resolution too high or insufficient system resources. (By the way this error message is somewhat unclear, could be everything actually).

The videos were encoded with After Effects 22 / Media Encoder (latest). 

Unity 2021.3.2f1
AVPro Video 2.6.2 plugin v2.6.0f1-ultra
Windows 11 / RTX 3080

Does anybody know any other decent codec which plays files up to 15360 Pixel ( dual 8k actually). I tried H264 and HEVC but those clip at 8192 Pixel. Unity should support it, textures (and Rendertextures) can be up to 16384px.

Thanks

Johannes

**Comment by Ste-RH** [comment]
This is a known issue. Please see notes on it [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/2.6.2).

We will be looking to address this hopefully by the end of this week for a new release.

If you need a fix urgently, we can send you v2.5.7 which is the last version that did not have this issue. Please [email](mailto:unitysupport@renderheads.com?subject=HAP-Issue)  over your Unity Asset Store PDF invoice so we can provide the previous version.

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this issue has not been fixed for you.

**Comment by johannesklaer** [comment]
Hi Chris,

It seems that its working with the custom Mov parser. Great, thanks. We do have a little issue, a strange error which says „Invalid AABB in AABB“. It has to do with the Display UGUI, if I switch off No Default Display its gone, but the Mediaplayer icon is shown, which we don’t want. 
We use Unity 2021.3.2f1 on Windows 11.

Best regards

Johannes

**Comment by Chris-RH** [comment]
Hi Johannes,

Has this just started with 2.6.3?

**Comment by johannesklaer** [comment]
Hi Chris,No, we had that from the beginning.RegardsJohannesJohannes KlaerKlaerMediaDaudetstr.28a81245 München+49 89 5500 6705+49 171 5731 222Am 27.09.2022 um 11:46 schrieb Chris-RH ***@***.***>:﻿
Hi Johannes,
Has this just started with 2.6.3?

**Comment by Chris-RH** [comment]
Invalid AAB/AABB tends to be caused by bad transform values.

Have you tried replacing the GO that the Display UGUI component is on (and/or all hierarchy up to that point)?
Can you reproduce the error in a new project with the demo scene?

**Comment by johannesklaer** [comment]
Yes, ist fixed now with 2.6.3, I can play HAP Videos up to 16384 pixels in width. I have to use the Custom MOV Parser. Videos are encoded with After Effects 22.

**Comment by Chris-RH** [comment]
OK, thanks for the update
