### ISSUE TITLE
No sound when Unity output is selected

### ISSUE THREAD

**Issue by Krajca** [RenderHeads/UnityPlugin-AVProVideo#1298]
Problem description:

Everything works fine as long as the output is set to "System Direct", but when "Unity" is selected, audio does not work.

I'm using the AudioOutput component with "multiple channels - everything" selected.

Device (which devices are you having the issue with - model, OS version number):

PC - win10; android - Quest2

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

I want 1 video only but tested on multiple similar ones: 1080p, .mp4, h264 and h265. Your BigBuckBunny sample video also doesn't work.

System Information:

AVPro Video: v2.6.2 (plugin v2.6.0f1-core)
Target Platform: Standalone
Unity: v2020.3.20f1 WindowsEditor
OS: Desktop - MS-7984 (MSI) - Windows 10  (10.0.19044) 64bit - English
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 8 threads - 65495KB
GPU: NVIDIA GeForce GTX 1080 Ti - NVIDIA - Direct3D 11.0 [level 11.1] - 11128KB - 16384

**Comment by Krajca** [comment]
In the meantime, I backtracked and reimport the whole package (before it was updated from I think 2.4).
The test scene is indeed working as intended. And based on this I was able to make my own working setup.
So probably this was the issue.

The only minor issue I found was the multi-editing of the AudioOutput component - it resets channels to the same value.

**Comment by Ste-RH** [comment]
So you reimported AVPro Video v2.6.2, jiggled some bits in your scene/project, and all is good now?

**Comment by Ste-RH** [comment]
Closing due to lack of response (and think the issue is addressed).

**Comment by Krajca** [comment]
I'm sorry for the lack of response. I was testing it more on other devices and forgot.

It seems everything is working fine now.
