### ISSUE TITLE
.MKV container not supported, Black screen & MediaPlayer shrink issue 

### ISSUE THREAD

**Issue by RojanStha** [RenderHeads/UnityPlugin-AVProVideo#1299]
Unity Version:-2021.3.4f1, 2021.3.9f1 (tried on both)
AvPro Version:-2.6.2 Ultra Edition
Other Assets Used: Unity Google CardBoard For VR(https://developers.google.com/cardboard/develop/unity/quickstart)
Min/Target SDK: 24/31
Progaurd minification: disable

Working on 360 Mkv video player for VR(using cardboard),
the status is audio is playing properly but the video MediaPlayer has some issue.

while checking the setting USE OES Rendering -> the screen is black and the audio is working
while Unchecking the setting USE OES Rendering -> the media player view is shrink 

![rn_image_picker_lib_temp_cfeb820e-d5b0-4245-b5fe-8cc536d13752](https://user-images.githubusercontent.com/29281308/191063400-11e96204-b390-4c14-b990-0f785337ed8f.jpg)

**Comment by Chris-RH** [comment]
Hi @RojanStha,

Have you added the Update Multi-Pass Stereo component on your camera?
Which shader are you using on your mesh?
Which graphics API are you using? Exolayer or Mediplayer?
Have you correctly set which packing you are using?
Could you send us a screenshot of your component settings?
 
See also:
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-arvrxr.html

**Comment by Chris-RH** [comment]
It should have a black background, that's how its designed to look with the Cardboard SDK.
https://www.reddit.com/r/GoogleCardboard/comments/3naioq/black_border_vs_full_screen/
