### ISSUE TITLE
Which veresion should i buy for webgl ?

### ISSUE THREAD

**Issue by Sandrik8** [RenderHeads/UnityPlugin-AVProVideo#1301]
Right now free trial demo works in WebGL M3U8 format , which asset store version should I buy for it ?

**Comment by Chris-RH** [comment]
Hi @Sandrik8 

We don't officially support WebGL, but I'm happy that it is working for you as required.  Have you tested it on all the platforms that you need it for?
Any asset store version should work, it just depends on your target platform.
https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions

**Comment by Sandrik8** [comment]
So my target platform is webgl, so which version should I buy to remove watermark ?

**Comment by Chris-RH** [comment]
If you're using Windows, then I'd go with that version :)

**Comment by Sandrik8** [comment]
which one? @Chris-RH

**Comment by Chris-RH** [comment]
https://assetstore.unity.com/packages/tools/video/avpro-video-core-windows-edition-184291
