### ISSUE TITLE
Possible to Preload Videos?

### ISSUE THREAD

**Issue by jjenningsags** [RenderHeads/UnityPlugin-AVProVideo#1304]
We are currently evaluating AVPro for Unity to see if it could be a potential candidate for a project we are currently developing.

Our project requires pre-loading many simultaneous videos to prepare them to play at any given moment to prevent any buffering gaps or lag. However, when testing the plugin with hardware decoding enabled we have been unable to preload/open more than 30ish videos at a time, even though there is still plenty of VRAM available to be utilized. What we assume could be happening is that the loading of videos is limited by the GPU decoding resources – even if the videos are only loaded and not actively playing/decoding; we noticed that the number of videos actively playing/decoding is equivalent to the number of videos that can be pre-loaded which is what led to this assumption. 

Our questions:
-	Are separate mediaplayer components with preloaded/pre-opened videos indeed limited by the decoding resources?
-	Is there a way to bypass this limitation and have multiple mediaplayer components have their video media preloaded?

At most we expect to only have 6 videos actively playing at any given moment, but have potentially 100 videos preloaded.

**Comment by Chris-RH** [comment]
Hi @jjenningsags,

Which platform(s) are you intending on using?
What device(s) are you using? specs?
What are the specs of the videos that you are using? How are they encoded?

**Comment by jjenningsags** [comment]
Platform: Windows 10

Target Device:
CPU: Intel I3 - 4 core
GPU: Nvidia T1000 4GB 
RAM: 16 GB

Video:
Codec: H264 - MPEG-4 AVC (part 10) (avc1_ 
Resolution: 1920x1080p
FrameRate: 24 fps
Bitrate: 2862 kbps

The length of the videos vary between 5 seconds - 3 minutes, with most of the videos being short <20 second clips.

**Comment by Chris-RH** [comment]
Along with resources required to decode videos (such as GPU memory), there are only a set number of hardware decoder units on GPUs.  When you open a video, most/all APIs will allocate such resources in order to start playback as soon as requested.


One possible work around, would be to use software decoding.  This would likely reduce the requirement on hardware based resources.  Software decoding tends to allow more videos to be opened than hardware decoding, though this will eventually bottleneck due to other resources.
You would just need to go into the Windows Specific options and untick "hardware decoding"
https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---windows

**Comment by jjenningsags** [comment]
So it eats up the hardware decoder units even if the video is loaded and not actively playing? With the Unity Videoplayer component we are able to prepare/load up to 60 videos and are only limited by VRAM - once our VRAM fills up the Videoplayer component is no longer able to load any additional videos. However, with the AVPRO mediaplayer we notice that we are only able to open/load around 30 videos which is half that of the Unity Videoplayer. We are using Unity 2021, so the Unity Videoplayer is also utilizing hardware decoding so I would've expected to see roughly the same amount of loaded videos for both components if the decoder units was the limiting factor. Is the AVPRO mediaplayer locking hardware decoder units by the loaded videos even if they paused?

**Comment by Ste-RH** [comment]
What version of AVPro Video are you using?

**Comment by jjenningsags** [comment]
We were using 2.6.2. I just tried with the trial version of 2.6.3, but seems like the same thing is happening when 30 or so mediaplayer components are instantiated with Auto-Open set to true and Auto-Play set to False, that it then fails to load anymore videos with the error:

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by Chris-RH** [comment]
I'm wondering if you perhaps would benefit from streamlining your loading system.  Is it really the case that you need to preload that many videos?
So if you start with video A, will the user need to be able to play any of videos B-Z, or from that point will they only be moving to video B, C, D or E? Does that make sense?

**Comment by jjenningsags** [comment]
> I'm wondering if you perhaps would benefit from streamlining your loading system. Is it really the case that you need to preload that many videos? So if you start with video A, will the user need to be able to play any of videos B-Z, or from that point will they only be moving to video B, C, D or E? Does that make sense?

It is necessary for us to preload the videos. Due to the nature of our applications, we can not have any performance lag from loading videos at runtime - even a few frames of lag could throw off the intention of the application and is unacceptable. Playing of the videos needs to occur instantaneously without any buffering to the first frame and the videos which can be played can happen at a moments notice without any pre-determination that the videos will eventually play. They are not sequential and are triggered via callbacks that can occur at any time during the application's lifetime. The videos are also synchronized with the timing of external Image Sprites, so if the first frame of the video is off by a few frames the external Sprites will not line up with the playing of the video and will be visible before the Video is actually rendering its first frame.

Videos A-Z can be played at any moment and there is no way to know when a video needs to be played until it is time to play them, as the callbacks that would trigger them are based on a random probability.

**Comment by Chris-RH** [comment]
Could you have a look at your task manager performance tab while running your application to see if the how CPU, GPU and memory are looking as you add each mediaplayer? I would specifically be interested to see how it looks around the time that it won't load further videos.
