### ISSUE TITLE
[2.6.3] Incorrect date returned on HLS video on Mac / iOS through mediaPlayer.Control.GetProgramDateTime() API

### ISSUE THREAD

**Issue by flogavel** [RenderHeads/UnityPlugin-AVProVideo#1305]
**Describe the issue**
Cannot get value of HLS live streaming's through mediaPlayer.Control.GetProgramDateTime() API.
This method sometimes returns the correct value, and sometimes returns 2001/01/01.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.4
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.3, ultra edition
 - Operating system version: MacOS 12.5.1 & iOS 15.6.1 (also tested on other macs and other iphones)
 - Device model: Macbook Pro & iPhone 12
 - Video specs (resolution, frame-rate, codec, file size): any resolution, HLS streaming

**To Reproduce**
1. Open attached zip folder
2. Unzip it, and open in Unity
3. Open the sample Demo_MediaPlayer scene, where we changed the video to our video stream
4. Press play, and look at the logs given by the script attached to the MediaPlayer gameobject.
5. Exit play mode, and play again. (reproduce several times until you get different results)

**Logs**
Debug.Log(mediaPlayer.Control.GetProgramDateTime()); 
// -> sometimes returns the correct value (2021-12-10-...), sometimes returns 2001-01-01

**Screenshots**
<img width="1512" alt="Screenshot 2022-09-27 at 15 07 23" src="https://user-images.githubusercontent.com/36621758/192536247-0c54afaa-c286-4147-87ca-ef7da77ee8b7.png">

**Comment by MorrisRH** [comment]
Hey @flogavel 
Can you send any project files to unitysupport@renderheads.com mentioning this issue in the email's subject.
Thanks!

**Comment by MorrisRH** [comment]
Hey @flogavel 
GetProgramDateTime is only valid for live HLS streams and not VOD. The example stream you sent is complete so no longer qualifies as being live. I'm afraid this is a limitation of Apple's APIs and not something we have any control over.

**Comment by flogavel** [comment]
We also tried on a live stream, I'm sending you the link via mail as a reponse to yesterday's mail

**Comment by MorrisRH** [comment]
Thanks for sending on the live stream, I was able to reproduce the issue and a fix will make it into the next release.

**Comment by flogavel** [comment]
Awesome thanks !

**Comment by guerwan** [comment]
Thanks @MorrisRH! Do you have an ETA for the next release?

**Comment by MorrisRH** [comment]
Should be end of the week or early next week at the latest

**Comment by Chris-RH** [comment]
The latest version is out. Please let us know if the issue has not been fixed for you.

**Comment by flogavel** [comment]
Issue seems to be fixed, thanks a lot !
