### ISSUE TITLE
Preview collection of videos as thumbnails by selecting random frame from each respective video during runtime.

### ISSUE THREAD

**Issue by gregklw** [RenderHeads/UnityPlugin-AVProVideo#1306]
Hello.

I am trying to create a row of images that, when selected, will display whatever video that it's associated with. Currrently I am trying to figure out a way to preload and preview those videos by rendering a random frame onto each image of each respective video. So by the time a user enters the scene, they should see the images with a random frame render as the display for each image.

I was wondering if there were any built-in functions I could look at that would accomplish this?

I'm trying to do this ultimately for iOS devices.

**Comment by Chris-RH** [comment]
Hi, you could try calling this:
Texture frame = mediaPlayer.ExtractFrame(10.0);
That would extract a frame at time 10s
