### ISSUE TITLE
"Loading Failed" for single .TS file (or custom .M3U) loaded over HTTP, works fine in VLC

### ISSUE THREAD

**Issue by bphillips09** [RenderHeads/UnityPlugin-AVProVideo#1309]
**Describe the issue**
Hi, I'm trying to stream a live .ts file that has no segments. I have tried directly loading both the .ts URL and an M3U file with the contents:

```
#EXTM3U
#EXTINF:-1,
http://server:port/file.ts
```
Either loading the .ts file directly or the M3U8 file directly in VLC work great, but in AVPro it produces the error: `[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.3f1 (Rosetta)
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v2.6.3 Trial
 - Operating system version: macOS Monterey 12.4
 - Device model: MacBook Pro, M1 Max
 - Video specs (resolution, frame-rate, codec, file size): (According to VLC:) 1920x1080@60, H264 - MPEG-4 AVC

**To Reproduce**
1. New Unity Project
2. Load directly a streaming .ts file or M3U file pointing to that file
3. Observe error

**Logs**
`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

**Screenshots**

**Videos**

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by yuhe0925** [comment]
I too see the error message just once, now i have same problem the loading HLS stream is working in the editor but not in a ios build, however the connection just hanging, and never see the message again

**Comment by MorrisRH** [comment]
Hey @bphillips09,
I just tried a quick test with a random ts file over http here and it worked fine so not sure why it's failing for you. Not sure what you mean by a live ts file, are you able to share a link?
