### ISSUE TITLE
Videos sometimes not looping seamlessly on macOS builds

### ISSUE THREAD

**Issue by Gabana** [RenderHeads/UnityPlugin-AVProVideo#1312]
In macOS builds, I sometimes see videos not looping seamlessly. Is this a known issue? 

We (my team) know that seamless looping requires special handling in macOS and we have used AVFoundation directly to handle it.

This is the AVFoundation class we used: [AVPlayerLooper](https://developer.apple.com/documentation/avfoundation/avplayerlooper)

A working example from an iOS app:
https://github.com/tobyspark/ORBIT-Camera/blob/master/ORBIT%20Camera/VideoViewCell.swift#L28

```
    let playerItem = AVPlayerItem(url: videoURL)
    let queuePlayer = AVQueuePlayer()
    looper = AVPlayerLooper(player: queuePlayer, templateItem: playerItem)
    playerLayer.player = queuePlayer // This uses the player in a UI layer. AVProVideo would extract frames from th

```

**Comment by MorrisRH** [comment]
Looping is tricky for sure. Make sure you don't have "Use single player item" enabled in the platform specific settings of the MediaPlayer inspector as this will force the player to seek to the beginning when looping.

Unfortunately we're unable to use AVPlayerLooper as it doesn't fit with how we need to extract textures for passing up to Unity. We are using an AVQueuePlayer instance under the hood though.

What kind of media are you playing back? If HLS then network conditions can cause the looping to not be as smooth as you'd like.

**Comment by Gabana** [comment]
Hi Morris, thanks for the quick reply. Is there a way to set that parameter via C#? I can´t see it in PlatformOptionsMacOSX

**Comment by MorrisRH** [comment]
It's one of the ```OptionsApple.Flags```, ```UseSinglePlayerItem```. It defaults to off so if you haven't changed it in the inspector I wouldn't worry. If you do want to set it then you'll need to do it before the media player's Start method is called as currently there is no support for updating it after the internal player has been created.

**Comment by Gabana** [comment]
Hi @MorrisRH i checked and made sure we don´t have "Use single player item" enabled. Unfortunately we are still having the same problem... is there anything else we could try to get this fixed?

Thanks!

**Comment by MorrisRH** [comment]
Hard to say without a bit more information.
What kind of media are you playing back? (local or streamed, mp4 or HLS)
What's the resolution and duration of the media?
Does it contain audio and are you using the Unity audio output mode?
Would you be able to share a link for the media you're playing? (you can send this to unitysupport@renderheads.com)
Do you think this has been broken by a recent update or has always been problematic?

**Comment by Chris-RH** [comment]
@Gabana 

Could you provide a bit more information please.
What kind of media are you playing back? (local or streamed, mp4 or HLS)
What's the resolution and duration of the media?
Does it contain audio and are you using the Unity audio output mode?
Would you be able to share a link for the media you're playing? (you can send this to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com))
Do you think this has been broken by a recent update or has always been problematic?

**Comment by Gabana** [comment]
Hi @Chris-RH 

Sorry for the slow reply.
I am playing a local mp4 file. Resolution is 1920x1080 and the duration is 2sec. I also test with another local mp4 that is 1280x720 and is 5 sec long. Both videos attached 
The video does not contain any audio and we are not using the Unity audio output mode
I think it has always been problematic as some users have reported it before we realised about it.

[VideosToTest.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9747709/VideosToTest.zip)

**Comment by MorrisRH** [comment]
Thanks for the test videos, we'll investigate.

**Comment by MorrisRH** [comment]
The 5s video you sent has an audio track that is fractionally longer than the video track which would explain why it doesn't loop so well.

**Comment by Gabana** [comment]
Thanks for reporting. Are you able to reproduce the issue with that video?

**Comment by Chris-RH** [comment]
With such short files, you might be better off stitching them together to form a longer loop, if that makes sense?

**Comment by tobyspark** [comment]
Morris – Thanks for your reply, and apologies for my delay here. I’m the person at Volta who has experience with AVFoundation. I started writing a reply, and in doing so established that this issue had progressed into test project territory. We’ve got past the initial premise that we had missed some setting or you had missed an platform-specific implementation quirk. And then events intervened.

You will be glad to know we can’t reproduce the issue in a test project. We have, however, got some insight on the nature of our issue. So a more precise statement may be can’t reproduce the issue in a test project, yet.

Here is a (frankly insane) video. What you’re seeing is that when I hit apple-space and the Spotlight search window is visible, videos play and loop seamlessly. When it isn’t visible, they don’t.

https://user-images.githubusercontent.com/197773/195841492-d4ff687b-fc80-4cc5-b2a7-b0a23a858231.mov

To me, this looks like the [Cocoa runloop](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/RunLoopManagement/RunLoopManagement.html) behind AVFoundation is not running properly.

Have you seen anything like this before, or have any insight that might help us track this down?

**Comment by MorrisRH** [comment]
Well that certainly raises some questions. Is this a Unity test scene or something separate? Would you be able to share your test scene? If so, please send it (or a link to it) to unitysupport@renderheads.com with this issue as the subject.

**Comment by MorrisRH** [comment]
Is run in background enabled in the Unity player settings?
