### ISSUE TITLE
Android - Audio out of sync when using Unity audio output with a looping video

### ISSUE THREAD

**Issue by joseph-o3h** [RenderHeads/UnityPlugin-AVProVideo#1313]
**Describe the issue**
When using a looping video player on Android with the audio output set to Unity, the audio track loops before the video track, causing the two to desynchronize after the first loop. Does not occur with system audio output and with Unity audio on macOS/iOS.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.2 ultra (Also reproduced on 2.4.0)
 - Operating system version: Android 12/13
 - Device model: Samsung Galaxy S21 Ultra, Google Pixel 6
 - Video specs (resolution, frame-rate, codec, file size): 1080x1920, 30 FPS, H.264 + AAC audio, 32.6 MB

**To Reproduce**
Build the sample project (sent by email) for Android and run. Observe the audio getting out of sync when the video player reaches the end of the video and loops.

**Videos**
Video is in streaming assets in the sample project.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @joseph-o3h,

Thank you for emailing your project file, that was helpful.
I looked at the test media that you provided and found that the video length was 11s 84ms while the audio length was 11s 29ms, which may be causing the loop sync issues.  We are looking into how Android treats this.

**Comment by Ste-RH** [comment]
I think we have found the issue.  A fix will be incoming in the next release of AVPro Video.  If you need a fix sooner @joseph-o3h then please email me over your Unity invoice PDF and I will arrange to get you over an f2 build package.

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this has not fixed the issue for you.

**Comment by joseph-o3h** [comment]
Still seeing this on 2.6.7

**Comment by Chris-RH** [comment]
@joseph-o3h,

Was it working for you in version 2.6.5 and has it since regressed or has it not been fixed at all? 
Is it still the same Android device?

**Comment by joseph-o3h** [comment]
We upgraded directly from 2.6.2 to 2.6.7 so don't know if it is a regression. Same device and same video file.

**Comment by Ste-RH** [comment]
Ok, more changes have gone in to try and address this issue.  I will include these in the next release.

**Comment by joseph-o3h** [comment]
It has been fixed in 2.7.1, but we have also found a similar issue with seeking. It can be reproduced by attaching this script to the media player
```csharp
using System;
using UnityEngine;
using System.Collections;
using RenderHeads.Media.AVProVideo;

public class SeekVideo : MonoBehaviour
{
    [SerializeField]
    private MediaPlayer mediaPlayer;

    public void Start()
    {
        StartCoroutine(DoSeek());

        IEnumerator DoSeek()
        {
            yield return new WaitForSeconds(4f);
            mediaPlayer.Control.Seek(5.91326492927655);
        }
    }
}
```
The seek time is important here - it only happens with certain seek times.

**Comment by Ste-RH** [comment]
Yeah, I see that.  Odd that I do not see it when seeking with the scrub bar in our Demo scene.  This one is gonna need some deeper diving.  I will schedule in some time to look deeper and get back to you on here when I have something to report.

**Comment by Ste-RH** [comment]
@joseph-o3h I have sent you a plugin set to test via the unitysupport ticketing system

**Comment by Chris-RH** [comment]
@joseph-o3h Did that help?

**Comment by joseph-o3h** [comment]
It didn't, I can still see it with the test plugin that you sent me.

**Comment by JuanObiJuan** [comment]
I comment already in the IOS issue but here maybe it makes more sense:
- On Android (Oculus Quest VR headset)
- While playing a video (normal 2D video with a standar stereo audio track multiplexed on the video)
- If you remove the headset and put it back again the audio is delayed

**Comment by Ste-RH** [comment]
A small change coming in the next version _might_ have an impact on this issue.
