### ISSUE TITLE
Unable to record audio of the video rendered on 3D mesh using third party plugins like NatCorder

### ISSUE THREAD

**Issue by thesanketkale** [RenderHeads/UnityPlugin-AVProVideo#1314]
**Describe the issue**
I want to record game play along with the video played on a 3D mesh in the game play. I am able to record the video rendered on a 3D mesh, but I am unable to record the audio coming from the video player. I am using a third party plugin called NatCorder for recording the game play in which I am recording the output of main camera and audio listener attached to the main camera. The audio coming from the audio sources in the game play is recorded, but the audio coming from the video is not.

**Your Setup (please complete the following information):**
 - Unity version: 2021.1.28f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core 2.6.4
 - Operating system version: Windows
 - Device model: Xiomi Poco X3 Pro, Oneplus Nord 2
 - Video specs (resolution, frame-rate, codec, file size): MP4, 100 MB

**To Reproduce**
1. Put Media player on a 3D cube and place it in the scene
2. Record camera and audio listener output of main camera and create a video
3. The newly recorded video does not have the audio output of the video played on the 3D cube

**Comment by Chris-RH** [comment]
I'm not sure that we can advice you on how to use 3rd party products. I have no idea how Natcorder works.
Is the Audio output setting on the Mediaplayer component set to Unity?
Do you have the Audio Output component attached to the Mediaplayer component?
https://www.renderheads.com/content/docs/AVProVideo/articles/component-audio-output.html

**Comment by thesanketkale** [comment]
> I'm not sure that we can advice you on how to use 3rd party products. I have no idea how Natcorder works. Is the Audio output setting on the Mediaplayer component set to Unity? Do you have the Audio Output component attached to the Mediaplayer component? https://www.renderheads.com/content/docs/AVProVideo/articles/component-audio-output.html

I set the audio output mode to VideoAudioOutputMode.Direct, could that be the cause of this issue? 
If I set it to VideoAudioOutputMode.AudioSource, would that send the audio to audio listener on the main camera?

The plugin in my case records the audio listener output directly. Now, the media player didn't seem to send the audio output to the listener and hence the audio didn't turn up in the recorded video.

**Comment by thesanketkale** [comment]
> I'm not sure that we can advice you on how to use 3rd party products. I have no idea how Natcorder works. Is the Audio output setting on the Mediaplayer component set to Unity? Do you have the Audio Output component attached to the Mediaplayer component? https://www.renderheads.com/content/docs/AVProVideo/articles/component-audio-output.html

The plugin records audio from AudioListener set on the main camera. The game audio and other realtime audio sources all get recorded in the output video except for the audio output of MediaPlayer.

I tried the Audio output componnent but still no change in the output.

![image](https://user-images.githubusercontent.com/36810188/193556492-6951ab09-6e48-4215-9906-ece81e1594d8.png)

Am I using it correctly?
How do I get the media player to output audio to Audio listener set on the main camera?

**Comment by Ste-RH** [comment]
Maybe you could trial our capture asset? You can find more details on the AVPro MovieCapture asset [here](https://renderheads.com/products/avpro-movie-capture/).

**Comment by thesanketkale** [comment]
> Maybe you could trial our capture asset? You can find more details on the AVPro MovieCapture asset [here](https://renderheads.com/products/avpro-movie-capture/).

Looks promising, will try it later this week. But I still need to solve this bug in an ongoing project that uses both NatCorder and AVPro video player. How can I get the audio output to unity's audio listener?

I also need to use 3D spatial audio for dopler effect like audio output from the media player. Is that possible with the current version of AVPro Core?

**Comment by MorrisRH** [comment]
Make sure you have "Audio Output" set to "Unity" in the platform specific settings for the media player, documentation for this is available [here](https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---windows)

**Comment by thesanketkale** [comment]
> Make sure you have "Audio Output" set to "Unity" in the platform specific settings for the media player, documentation for this is available [here](https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---windows)

Awesome, this made it work. Thanks a ton for the tip!

So, for future reference, I made it work by adding the audio output component to the game object holding media player and ApplyToMesh component. After that I set the individual audio output mode to Unity in the main settings of the media player. And lastly, I changed the spatial blend value of the audio source added by audio output component to 1 for spatial sound from the video.

Thanks @Chris-RH and @MorrisRH for helping me figure this out.

**Comment by thesanketkale** [comment]
Hey umm, I am seeing a weird issue adding AudioOutput at runtime from a script in an iOS device. This somehow works on android devices, but on iOS devices throws a null reference exception while assigning media player to the audio output component. 

`private void SetupVideoPlayer(GameObject targetMesh, string videoClipUrl)
{
	MediaPlayer videoPlayer = targetMesh.GetComponent<MediaPlayer>();
	if (!videoPlayer)
	{
		videoPlayer = targetMesh.AddComponent<MediaPlayer>();
	}
	videoPlayer.Loop = true;
	videoPlayer.AutoOpen = true;
	videoPlayer.AutoStart = true;
	videoPlayer.PlaybackRate = 1;

	videoPlayer.AudioVolume = 1;
	videoPlayer.AudioMuted = false;

	videoPlayer.PlatformOptionsAndroid.audioOutput = Android.AudioOutput.Unity;
	videoPlayer.PlatformOptionsIOS.audioMode = MediaPlayer.OptionsApple.AudioMode.Unity;
	videoPlayer.PlatformOptionsWindows.audioOutput = Windows.AudioOutput.Unity;
	AudioOutput audioOutput = targetMesh.GetComponent<AudioOutput>();
	if (!audioOutput)
	{
		audioOutput = targetMesh.AddComponent<AudioOutput>();
	}
	audioOutput.Player = videoPlayer;
	AudioSource audioSource = targetMesh.GetComponent<AudioSource>();
	if (audioSource)
	{
		audioSource.spatialBlend = 1;
	}
	
	ApplyToMesh applyToMesh = targetMesh.GetComponent<ApplyToMesh>();
	if (!applyToMesh)
	{
		applyToMesh = targetMesh.AddComponent<ApplyToMesh>();
	}
	applyToMesh.DefaultTexture = Texture2D.blackTexture;
	applyToMesh.MeshRenderer = targetMesh.GetComponent<MeshRenderer>();

	applyToMesh.Offset = Vector2.zero;
	applyToMesh.Scale = Vector2.one;
	applyToMesh.Player = videoPlayer;
	videoPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, videoClipUrl, videoPlayer.AutoStart);
}`

Is it allowed to add the audio output component to a game object and assign the media player to the component at runtime? I want to add a media player, audio output and apply to mesh component to a runtime generated game object and stream a video. What am I missing in this utility?

FYI, this is working fine in android and iOS devices both, if I remove the part of adding audio output component.

**Comment by MorrisRH** [comment]
Hey @thesanketkale, a fix for this will make it into the next release. You can apply the fix to the current version by changing line 82 of AudioOutput.cs to the following:
```csharp
MediaPlayer.OptionsApple options = (MediaPlayer.OptionsApple)newPlayer.GetCurrentPlatformOptions();
```

**Comment by thesanketkale** [comment]
> Hey @thesanketkale, a fix for this will make it into the next release. You can apply the fix to the current version by changing line 82 of AudioOutput.cs to the following:
> 
> ```cs
> MediaPlayer.OptionsApple options = (MediaPlayer.OptionsApple)newPlayer.GetCurrentPlatformOptions();
> ```

Hey @MorrisRH, thanks for the prompt response. This solved the NRE, but now there is another issue in the iOS device video player. 

If I setup the video player using my above mentioned method, the audio output component is disabled by default and as a result no sound comes from the video player after setup. If I manually enable the audio output component from the inspector window, it plays the sound, but somehow does not work automatically by adding the AudioOutput component to the 3D object. Is this an expected behavior?

Again FYI, this works fine in Android but not in iOS devices in the same project after using the same method of adding the components at runtime.

**Comment by MorrisRH** [comment]
Yeah, as part of the fix the code has been wrapped in a null check, feel free to do the same your end.
Did you see a warning in the log about using the player with Unity as the audio output mode?

**Comment by thesanketkale** [comment]
> Yeah, as part of the fix the code has been wrapped in a null check, feel free to do the same your end. Did you see a warning in the log about using the player with Unity as the audio output mode?

Yes, I get below warning in the console window:

> [AVProVideo] Unity audio output is not supported when 'Audio Output Mode' is not set to 'Unity' in the MediaPlayer platform options
UnityEngine.Debug:LogWarning (object)
RenderHeads.Media.AVProVideo.AudioOutput:ChangeMediaPlayer (RenderHeads.Media.AVProVideo.MediaPlayer) (at Assets/AVProVideo/Runtime/Scripts/Components/AudioOutput.cs:89)
RenderHeads.Media.AVProVideo.AudioOutput:set_Player (RenderHeads.Media.AVProVideo.MediaPlayer) (at Assets/AVProVideo/Runtime/Scripts/Components/AudioOutput.cs:33)
UnityMobileGame.GamePlay.Vues.UnityMobileGameVideoPlayerManager:SetupAVProVideoPlayer (UnityMobileGame.Components.UnityMobileGameVideoPlayer) (at Assets/Scripts/GamePlay/VuePlayer/UnityMobileGameVideoPlayerManager.cs:234)
UnityMobileGame.GamePlay.Vues.UnityMobileGameVideoPlayerManager:Start () (at Assets/Scripts/GamePlay/VuePlayer/UnityMobileGameVideoPlayerManager.cs:33)

But I am setting the audio output to Unity for iOS platform before adding the audio output in my script. Like below:

`videoPlayer.PlatformOptionsAndroid.audioOutput = Android.AudioOutput.Unity;
videoPlayer.PlatformOptionsIOS.audioMode = MediaPlayer.OptionsApple.AudioMode.Unity;
videoPlayer.PlatformOptionsWindows.audioOutput = Windows.AudioOutput.Unity;
AudioOutput audioOutput = targetMesh.GetComponent<AudioOutput>();
if (!audioOutput)
{
audioOutput = targetMesh.AddComponent<AudioOutput>();
}
audioOutput.Player = videoPlayer;`

What am I missing here?

**Comment by MorrisRH** [comment]
That looks like an issue our end, most platform options should be configurable prior to calling OpenMedia. I'll investigate.

**Comment by MorrisRH** [comment]
A fix for this will be in the next release. You will now be able to change the audio output mode after player creation up until you call OpenMedia at which point it will be locked in.

**Comment by thesanketkale** [comment]
> A fix for this will be in the next release. You will now be able to change the audio output mode after player creation up until you call OpenMedia at which point it will be locked in.

Hi @MorrisRH, thanks for the update. Can I get a beta build with this fix to confirm if the fix works with my use case? 

P.S. - If you have tested my method of adding AudioOutput at runtime in iOS device along with the fix and can confirm me its working, I will ok with that too.

**Comment by Chris-RH** [comment]
Sorry, we won't have time to send a beta today, but the next version should be out tomorrow.

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this has not fixed the issue for you.

**Comment by thesanketkale** [comment]
> The latest version has been released, please let us know if this has not fixed the issue for you.

Hi @Chris-RH, I tried the latest version of Core Edition 2.6.5 from the Unity Asset Store and I am still unable to hear audio from the AVPro video player when added from a script that adds AudioOutput at runtime in an iOS project. It works in Android but not iOS just as in the previous version. I have put a demo project at below URL for your debugging:

https://drive.google.com/file/d/1antSw9tjYN3-a9R-IIVNdWyYt5BS_YoG/view?usp=sharing

It just has a script that adds a MediaPlayer, AudioOutput, and ApplyToMesh at runtime for playing video on a Quad in iOS device. What I am doing wrong in the below snippet for setting up the MediaPlayer?

`private void SetupAVProVideoPlayer(string videoUrl)
{
	MediaPlayer videoPlayer = targetRenderer.GetComponent<MediaPlayer>();
	if (!videoPlayer)
	{
		videoPlayer = targetRenderer.gameObject.AddComponent<MediaPlayer>();
	}
	videoPlayer.Loop = true;
	videoPlayer.AutoOpen = true;
	videoPlayer.AutoStart = true;
	videoPlayer.PlaybackRate = 1;

	videoPlayer.AudioVolume = 1;
	videoPlayer.AudioMuted = false;

	videoPlayer.PlatformOptionsAndroid.audioOutput = Android.AudioOutput.Unity;
	videoPlayer.PlatformOptionsIOS.audioMode = MediaPlayer.OptionsApple.AudioMode.Unity;
	videoPlayer.PlatformOptionsWindows.audioOutput = Windows.AudioOutput.Unity;
	AudioOutput audioOutput = targetRenderer.GetComponent<AudioOutput>();
	if (!audioOutput)
	{
		audioOutput = targetRenderer.gameObject.AddComponent<AudioOutput>();
	}
	audioOutput.Player = videoPlayer;
	AudioSource audioSource = targetRenderer.GetComponent<AudioSource>();
	if (audioSource)
	{
		audioSource.spatialBlend = 1;
	}

	ApplyToMesh applyToMesh = targetRenderer.GetComponent<ApplyToMesh>();
	if (!applyToMesh)
	{
		applyToMesh = targetRenderer.gameObject.AddComponent<ApplyToMesh>();
	}
	applyToMesh.DefaultTexture = Texture2D.blackTexture;
	applyToMesh.MeshRenderer = targetRenderer;

	applyToMesh.Offset = Vector2.zero;
	applyToMesh.Scale = Vector2.one;
	applyToMesh.Player = videoPlayer;
	videoPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, videoUrl, videoPlayer.AutoStart);
}`

**Comment by MorrisRH** [comment]
Hey @thesanketkale, this is working fine for me here. I'm using the following script (based on what you previously pasted):
```sharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RenderHeads.Media.AVProVideo;

public class Issue1314 : MonoBehaviour
{
	// Start is called before the first frame update
	void Start()
	{
		string path = "file:///" + Application.streamingAssetsPath + "/AVProVideoSamples/RenderHeads-1080p30-H264.mp4";
		SetupVideoPlayer(gameObject, path);
	}

	// Update is called once per frame
	void Update()
	{
		
	}

	private void SetupVideoPlayer(GameObject targetMesh, string videoClipUrl)
	{
		MediaPlayer videoPlayer = targetMesh.GetComponent<MediaPlayer>();
		if (!videoPlayer)
		{
			videoPlayer = targetMesh.AddComponent<MediaPlayer>();
		}
		
		videoPlayer.Loop = true;
		videoPlayer.AutoOpen = true;
		videoPlayer.AutoStart = true;
		videoPlayer.PlaybackRate = 1;

		videoPlayer.AudioVolume = 1;
		videoPlayer.AudioMuted = false;

		videoPlayer.PlatformOptionsAndroid.audioOutput = Android.AudioOutput.Unity;
		videoPlayer.PlatformOptionsMacOSX.audioMode = MediaPlayer.OptionsApple.AudioMode.Unity;
		videoPlayer.PlatformOptionsIOS.audioMode = MediaPlayer.OptionsApple.AudioMode.Unity;
		videoPlayer.PlatformOptionsWindows.audioOutput = Windows.AudioOutput.Unity;
		AudioOutput audioOutput = targetMesh.GetComponent<AudioOutput>();
		if (!audioOutput)
		{
			audioOutput = targetMesh.AddComponent<AudioOutput>();
		}
		audioOutput.Player = videoPlayer;
		AudioSource audioSource = targetMesh.GetComponent<AudioSource>();
		if (audioSource)
		{
			audioSource.spatialBlend = 1;
		}
		
		ApplyToMesh applyToMesh = targetMesh.GetComponent<ApplyToMesh>();
		if (!applyToMesh)
		{
			applyToMesh = targetMesh.AddComponent<ApplyToMesh>();
		}
		applyToMesh.DefaultTexture = Texture2D.blackTexture;
		applyToMesh.MeshRenderer = targetMesh.GetComponent<MeshRenderer>();

		applyToMesh.Offset = Vector2.zero;
		applyToMesh.Scale = Vector2.one;
		applyToMesh.Player = videoPlayer;
		videoPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, videoClipUrl, videoPlayer.AutoStart);
	}
}
```

I'm using:
- Unity 2021.3.11f1
- iPhone X running iOS 14.8.1
- built with Xcode 14.0.1

What kind of media are you trying to playback? This will only work with mp4 files and not HLS media.

**Comment by thesanketkale** [comment]
> videoPlayer.PlatformOptionsMacOSX.audioMode = MediaPlayer.OptionsApple.AudioMode.Unity;

Ahh, my bad. I missed setting audio mode to Unity for MacOSX and was testing it in Unity Editor on MacOS. I added that and it works now with the latest version of AVPro(v2.6.5). Thanks for all your help with this issue @MorrisRH and @Chris-RH. I will mark it closed now.

**Comment by thesanketkale** [comment]
Also, just out of curiosity, why won't this work with HLS media? Though I am using mp4 right now, we do have it in our roadmap to convert these videos to HLS for better streaming. Will the media player be able to stream HLS video on a mesh renderer?

**Comment by MorrisRH** [comment]
The problem with HLS is that Apple provide no way for us to access the audio output so there is no way for us to route the audio through to unity. 
Everything will work, just the audio will be output directly from the media.

**Comment by thesanketkale** [comment]
> The problem with HLS is that Apple provide no way for us to access the audio output so there is no way for us to route the audio through to unity. Everything will work, just the audio will be output directly from the media.

Ohh, ok. Thanks for the heads up.
