### ISSUE TITLE
My Video Can 't Play On Use Custom Https Header with referer header (WinRt)

### ISSUE THREAD

**Issue by RestartXu** [RenderHeads/UnityPlugin-AVProVideo#1319]
My Video Can 't Play On Use Custom Https Header with referer header (WinRt),My  WebSite need Referer Header to verify legitimacy. But I found two different requests in  my website. There is one request with a referer header,an one request that Avpro defaults to without a referer header.
 - Unity version: 2020.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AvPro 2.6.4 trial
 - window10

**Comment by Chris-RH** [comment]
Have you read our page on content protection? https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html.
This is only supported for adaptive media (HLS/DASH).

Are you using a script for this, and if so could you share it? 
If there is anything confidential, you can send it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)? Please included the issue number in the subject line.
