### ISSUE TITLE
Playing video from Timeline

### ISSUE THREAD

**Issue by cmanzione** [RenderHeads/UnityPlugin-AVProVideo#132]
Hello!

I have an activation element added in a Unity Timeline with a video that is in the scene using AVPro for Windows. I thought the timeline would start the video playing but the video just starts playing when I start the scene.

How can I get an AVPro video to start playing using a Timeline?

**Comment by AndrewRH** [comment]
The MediaPlayer has options to Auto Open + Auto Start (play) - so perhaps it is using these to start playback as soon as the object is created.  Try disabling the Auto Start option.  Then you would need something to call MediaPlayer.Play().   Or perhaps have the MediaPlayer component disabled to start with, and the activation element would cause it to load and play.

Does that helps?  Otherwise, could you provide more details?  I'm not familiar with the Timeline/activation element.

Thanks,

**Comment by cmanzione** [comment]
Hey Andrew,

Thanks for your fast reply.

I've tried activating the AVPro video in the timeline using the AutoStart, AutoOpen, as well as using an animation track and control track. Nothing seems to be working. 

What it seems like is happening is that the video starts playing in the scene regardless of any of these options and regardless if the object is active in the scene or not.

The timeline can control activation, animation, playable objects and control tracks as listed here: 
https://docs.unity3d.com/Manual/TimelineOverview.html

Do you know how you would start playing a AVpro clip using something like ontrigger.enter   I think something like this might easily be added to the timeline. I wish there was a way to have AVpro wait to play the clip.

again thanks for your time
Chris

**Comment by cmanzione** [comment]
Okay just to close this thread I'm going to post how I worked around this. I never got it to work directly in the Timeline.

1) Make a trigger object (cube) and add the VideoTrigger script that comes with AVPro. (AVProVideo>Demos>Scripts>Scriptlets>VideoTrigger) Also, make sure to check "is trigger" on this object.

2) Drag the Media Player object you want to control into the VideoTrigger script you just added to the trigger object

3) In the timeline, I animated another cube tagged as "player" to move into the trigger zone to start the video and to move out to stop the video.

This script starts and stops+resets the video upon moving in and out of a trigger zone. You also have to make sure to uncheck AutoPlay on the videos Media Player so the video doesn't start playing when you start the scene.

**Comment by AndrewRH** [comment]
This feature is now in version 2.0 BETA release

**Comment by brianchasalow-unity** [comment]
this feature appears to crash on Unity 2020.2.0f1, Timeline package 1.5.2. 
Couldn't see an obvious crash report, but did see this:

Start ondemand import (priority ImportantBackground): Assets/AVProVideo (Guid(597403ecd468c0b4ca3cd930c172072d) Importer(815301076,1909f56bfc062723c751e8b465ee728b))
NullReferenceException: Object reference not set to an instance of an object
  at UnityEditor.Timeline.TrackExtensions.ContainsTimelineMarkerTrack (System.Collections.Generic.IEnumerable`1[T] tracks, UnityEngine.Timeline.TimelineAsset asset) [0x00000] /Library/PackageCache/com.unity.timeline@1.5.1-pre.3/Editor/Extensions/TrackExtensions.cs:513

So I imagine something is up with the timeline integration. My workaround for now is to avoid using Timeline integration altogether, and just use an activation track with OnEnable / OnDisable / Update methods to serve as proxy controls for a MediaPlayer.

**Comment by brianchasalow-unity** [comment]
btw, having stripped out Timeline integration, we're still seeing hard-to-repro crashes on a Mac, so this may be related to updating to the latest version of AVPro Ultra (we did not see these crashes previously) and not solely tied to Timeline. Or, it could be both Timeline integration + AVPro Video separately have issues :-)

**Comment by AndrewRH** [comment]
@brianchasalow-unity  okay thanks for letting us know.  We did recently fix some bugs in macOS so it may work better with the latest version (2.0.6).

Thanks,

**Comment by AndrewRH** [comment]
> this feature appears to crash on Unity 2020.2.0f1, Timeline package 1.5.2.
> Couldn't see an obvious crash report, but did see this:
> 
> Start ondemand import (priority ImportantBackground): Assets/AVProVideo (Guid(597403ecd468c0b4ca3cd930c172072d) Importer(815301076,1909f56bfc062723c751e8b465ee728b))
> NullReferenceException: Object reference not set to an instance of an object
> at UnityEditor.Timeline.TrackExtensions.ContainsTimelineMarkerTrack (System.Collections.Generic.IEnumerable`1[T] tracks, UnityEngine.Timeline.TimelineAsset asset) [0x00000] /Library/PackageCache/com.unity.timeline@1.5.1-pre.3/Editor/Extensions/TrackExtensions.cs:513
> 
> So I imagine something is up with the timeline integration. My workaround for now is to avoid using Timeline integration altogether, and just use an activation track with OnEnable / OnDisable / Update methods to serve as proxy controls for a MediaPlayer.

I just tested the timeline integration with 1.5.2 and it worked fine.  I see in the log it mentions 1.5.1-pre3 in the cache, so it might just be unity getting confused with older cached versions..

I will close this issue for now but please do open another issue if you have any problems.

Thanks,
