### ISSUE TITLE
HLS 4K Issue - 360 Video

### ISSUE THREAD

**Issue by DaneDonaldson98** [RenderHeads/UnityPlugin-AVProVideo#1321]
Good Afternoon,

I'm currently using this Extension to run a HLS (M3U8) link from AWS, which when using 1080p videos was absolutely fine. Upon trying to same with 4K (3840 x 2160), i'm hit with an Error telling me the resolution is too high/ link is not found. Testing the link in VLS Player I know it's a working HLS, and was just wondering if there's any specific settings that need to be configured in order for a higher resolution to be allowed to run?

Note: I tested with a 4 second 4K Video, and it worked, however anything over 9 seconds results in the above error or a blank display. 

Thanks in advance.
![Screenshot 2022-10-07 at 16 05 59](https://user-images.githubusercontent.com/105784140/194585913-964dc2f7-c54e-4d9d-96b7-2cd4f18ce858.png)

![Screenshot 2022-10-07 at 16 01 05](https://user-images.githubusercontent.com/105784140/194584947-38e865dd-e5a9-4dc9-90f8-23ea220672d7.png)

**Comment by Ste-RH** [comment]
You find the root cause of the issue @DaneDonaldson98 ?

**Comment by DaneDonaldson98** [comment]
> 

No unfortunately, I figured it was a poorly written question, so closed the issue to find a better way to write it.

From further tests, it seems that the HLS Player is making my 360 videos grainy looking, regardless of what quality I use.
