### ISSUE TITLE
Loading video without path location (for WebGL)

### ISSUE THREAD

**Issue by AP432** [RenderHeads/UnityPlugin-AVProVideo#1322]
I'm developing a WebGL application that opens the file browser, selects a video file then plays it through the AVPro Media Player. 
I'm having trouble with getting the video to load to the MediaPlayer due to the nature of WebGL builds - being that I can't get the path location of the video files due to the security barriers. AVPro MediaPlayer seems to work primarily off the path location when loading a video into it. 
Is there an alternative function available that would load the selected media straight into the MediaPlayer?
There is 'videoPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, link);' which relies on a pathway (that I can't access). Is there an alternative function or work around that is possible for WebGL?

**Comment by MorrisRH** [comment]
We just use the html <video> tag under the hood so are subject to the very same security restrictions.

**Comment by AP432** [comment]
Does this solve the issue?

**Comment by MorrisRH** [comment]
No, just pointing out that there is little we can do about this as it is how modern html works. 
For WebGL we required a valid URL in order to open a video, this should start with one of "http://", "https://" or "file:///".

**Comment by AP432** [comment]
So, if I have a local file that I want to load into the MediaPlayer (via the WebGL build) what is the way to do that?

**Comment by MorrisRH** [comment]
You would need to use something like this on Windows:
```
file:///c/path/to/the/file/to/play.mp4
```

**Comment by AP432** [comment]
...and I cannot get that location 'in-game' due to the WebGL restrictions. 
Is there any workarounds to this? loading strings to a JSON file then reading them off the WebGL side?

**Comment by Chris-RH** [comment]
You could certainly try and see  if that works
