### ISSUE TITLE
HLS Quality Issue (WebGL)

### ISSUE THREAD

**Issue by DaneDonaldson98** [RenderHeads/UnityPlugin-AVProVideo#1323]
Good Morning,

i wrote an issue last week, but after some testing figured it was best to come back and re-write my query. I'm currently using the HLS Player for a 360 Video Experience, however the videos are displaying in low quality. I've created an M3U8 playlist containing only 1080p and 4k outputs so those resolutions are forced, however nothing changes within the Unity Editor.

Wasn't sure if there was a setting that had to be toggled, or a way to stop the player from decaying the resolution? I imagine it's doing it to allow for smoother videos, but i'd rather have the buffer and higher quality than no buffer and lower quality.

I saw in a post from a couple years ago that a feature was being added to force high quality from the get-go, however can't find anything recent on this feature.

P.S. I'm developing on a MacBook Pro 2016 if this helps.

Thanks in advance!

**Comment by MorrisRH** [comment]
On macOS (and iOS/tvOS) you can set the ```Preferred Maximum Resolution``` to the resolution you want and it will enabled. By default macOS won't playback streams at a higher resolution than the display supports.

For WebGL no such option exists as browser support for HLS is a bit fragmented (it's native with Safari, and I'm pretty sure the other browsers require the HLS.js library).

It's worth noting that the editor is not using WebGL for its rendering in WebGL mode, just using the platform player with the WebGL settings so will be subject to the native platform limitations.

**Comment by DaneDonaldson98** [comment]
> worth noting that the editor is not using WebGL for its rende

I appreciate this reply, very informative. As for the video output in itself being low quality when being fed 1080p/4K HLS Links, is this just something the extension is doing to increase playback performance?

**Comment by MorrisRH** [comment]
By low-quality I take it you mean the 1080p stream?
The behaviour of macOS is not to play streams with a higher resolution than the display, it's not something we're doing in the plugin causing this. The work around is to force the preferred maximum resolution (as I mentioned previously), however this will not guarantee 4k playback as the system may decide the 1080p stream provides the better user experience (by reducing the chance of stalling for example).
