### ISSUE TITLE
The AVPro Ultra edition has a rendering problem with 360 video

### ISSUE THREAD

**Issue by RojanStha** [RenderHeads/UnityPlugin-AVProVideo#1325]
The AVPro Ultra edition has a rendering problem with 360 video , screen shrinks at some angle and isn't properly playing. I've included the APK link and screenshots and submitted them to the support email. Please take a look and let me know the problem. If there is anything missing from our end, please let me know. 

Setup
 - Unity version: 2021.3.9f1
 - AVPro Video version (number and ultra): Version 2.6.2  And Ultra Edition 
 - Operating system version: Windows
 - Device model: Android OS 11,12 
 - Video specs : (3040 *1920, 30.000300, Opus, 453mb)

![SM A505F 9_30_2022 11_03_14 PM](https://user-images.githubusercontent.com/29281308/194997121-f852d481-29e1-4ee7-b40a-a383d34c19c9.png)

![Current Media Information 9_30_2022 10_56_59 PM](https://user-images.githubusercontent.com/29281308/194997143-23e8d7ff-1535-4c56-bb02-7083a6078d53.png)
![Current Media Information 9_30_2022 11_06_47 PM](https://user-images.githubusercontent.com/29281308/194997156-a55d83e1-9371-42d0-8347-0cd7d35a9cfb.png)

**Comment by Ste-RH** [comment]
I have replied to you over the unitysupport@renderheads.com channel as I did not want to publicly share a video of your video without permission.

Essentially I cannot reproduce this issue.  Here are the steps I took:

1) New project using Unity 2021.3.9f1
2) Imported AVPro Video v2.6.2 (Ultra edition)
3) Added Google Cardboard package via git (https://developers.google.com/cardboard/develop/unity/quickstart) and setup as described
4) Opened the AVPro Video 'Demo_360Stereo' scene
5) Set the media player component to load your output.mkv video
6) Added the 'tracked pose driver' component to the 'Main Camera' game object
7) Build and run on a Xiaomi Mi 10T

The output was exactly as I would expect (as can be seen in this screen shot:

![image](https://user-images.githubusercontent.com/46531149/195071608-c4564ca4-9be9-453b-9466-380ee0505e1b.png)

**Comment by RojanStha** [comment]
We started a new project from scratch and discovered that the problem was caused by Shader and the Audio output in channel mode.
We resolved the problem but discovered a new one: the 360 3D sound effect front/back could be heard, but the left/right is unclear.

Setup:
Sphere-Apply-ToMesh
Shader: AVProVideo/VR/insideSphere Unlit(stereo+fog)

Audio
Enable focus: Checked
Head Transform: Main Camera
Focus Transform:Main Camera

Platform Specific/Android
Audio Output: Facebook Audio 360
Channel Mode: (AMBIX_4) 4 Channel of first order ambiX

**Comment by Ste-RH** [comment]
So the original issue is fixed?

Now you have an FB360 audio issue?

Please ensure you have the following set correctly:

- 'Head Transform' set on the MediaPlayer component

![image](https://user-images.githubusercontent.com/46531149/195121299-42c1bf08-7747-45d8-a1f4-379c22cb8ca3.png)

- 'Audio Output' set to 'Facebook Audio 360'
- 'Channel Mode' set correctly for the video asset (yours looks like it wants to be set to AMBIX_4

![image](https://user-images.githubusercontent.com/46531149/195121451-21179cfb-2d46-416d-a5d7-77c18e959250.png)


We use this video to [test](https://bit.ly/3rJ2GWa) FB360 audio (it is TBE_8_2 : 8 + 2 channels : 10 channels).  Please test this file to ensure your issue is not the audio in your video asset.

**Comment by RojanStha** [comment]
Yes the original issue is solved, Thank you for the response.

But, the audio problem is still there. The sound feels monaural rather than stereo. if the speaker is to the listener's right, the sound is heard in both ears rather than the right (it suppose to hear little close and loud on right ear).

the provided 10 channels audio is also feels same.

![image_2022_10_12T08_22_33_398Z](https://user-images.githubusercontent.com/29281308/195290670-a88d877a-6e08-4562-a2b9-5140dd00b2b0.png)

**Comment by Ste-RH** [comment]
If the 10 channel one is not working for you, then there is a problem with your set-up as it works perfectly here.  That said, I have to use headphones to really hear/test though!

I suggest you try the Demo_360Stereo scene we include and make the changes I outline above to rule out your project scene being the issue.

**Comment by RojanStha** [comment]
i replied on your email unitysupport@, please confirm and reply soon as soon possible.

**Comment by RojanStha** [comment]
Got that, thanks
@Ste-RH how to change the Facebook  Audio 360 channel mode from script?

**Comment by Chris-RH** [comment]
Hi @RojanStha,

There is some scripting information here: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html

**Comment by RojanStha** [comment]
Got it thanks, the issue is now solved.

**Comment by Ste-RH** [comment]
Just a little more on this @RojanStha.  You MUST have your audio/channel-mapping set BEFORE calling OpenMedia(...).  Changing it after will have no effect.
