### ISSUE TITLE
Issue building IOS with cloud build after latest Update

### ISSUE THREAD

**Issue by Pellelle** [RenderHeads/UnityPlugin-AVProVideo#1326]
**Describe the issue**
After updating to the latest version of AvPro, the IOS cloud builds have been failing. The exact error reads:

> ld: '/BUILD_PATH/removed_project_name/temp20221010-6451-9gk89a/Frameworks/Plugins/AVProVideo/Runtime/Plugins/iOS/AVProVideo.framework/AVProVideo' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/BUILD_PATH/removed_project_name/temp20221010-6451-9gk89a/Frameworks/Plugins/AVProVideo/Runtime/Plugins/iOS/AVProVideo.framework/AVProVideo' for architecture arm64

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.11f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.4 core
 - Operating system version: IOS
 - Device model: Cloud build
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Create a project containing Avpro video
2. Build for IOS using cloudbuild 3. 

**Logs**
> ld: '/BUILD_PATH/removed_project_name/temp20221010-6451-9gk89a/Frameworks/Plugins/AVProVideo/Runtime/Plugins/iOS/AVProVideo.framework/AVProVideo' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/BUILD_PATH/removed_project_name/temp20221010-6451-9gk89a/Frameworks/Plugins/AVProVideo/Runtime/Plugins/iOS/AVProVideo.framework/AVProVideo' for architecture arm64

**Comment by Chris-RH** [comment]
Which version of iOS and Xcode are you using?
Have you enabled all the bitcode settings in the build settings?

**Comment by MorrisRH** [comment]
Apologies. We'll get this fixed for the next release.

**Comment by Pellelle** [comment]
Thanks for the quick reply. Do you know when this release will be? Then I can decide whether I should roll back a version or not.

**Comment by MorrisRH** [comment]
It should be before the end of the week.

**Comment by Pellelle** [comment]
Thanks!
