### ISSUE TITLE
360 Stereo Image Viewer

### ISSUE THREAD

**Issue by mbzworld** [RenderHeads/UnityPlugin-AVProVideo#1327]
Your video player plugin is probably the best out there. It'd really be great if your plugin can be also an image viewer for 360 stereoscopic images as well.

**Comment by Chris-RH** [comment]
Hi @mbzworld 
The asset can play Stereoscopic Videos (https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html).
Two different options that you could try for still images:
Convert stereoscopic image to a single frame of video and set autoopen to enabled and autoplay to disabled.  Thus you can play it as a stereoscopic video and look around in 360 degree.
or
Use the correct stereo shader and feed in their own texture(s).

**Comment by mbzworld** [comment]
Hi Chris,
Thanks for the quick response.

I prefer the second approach. Would you please provide a code sample for an over-under 360 image?

**Comment by Ste-RH** [comment]
This is quite an easy thing to implement.  No code sample should be required as it will largely be down to what your project is trying to achieve/where you will be obtaining the stereoscopic images from.

Instead, I will post some screen shots of how to set up an example.  I am using the Demo_360Stereo scene we provide in the asset as a basis

1) Create a material and set:
          - the shader on it to 'AVProVideo/VR/InsideSphere Unlit (stereo+fog)'
          - 'Stereo Mode' to 'Top_Bottom'
          - select 'Texture' to your stereoscopic texture (I will post up my test one below)
2) On the 'Sphere-ApplyToMesh' game object:
         - remove the 'Apply To Mesh' component
         - on the 'Mesh Renderer' component, sert the material to the material created in step (1)
3) Make sure you have your XR settings set according to platform/device
4) You might need to add the 'Tracked Pose Driver' component to the 'Main Camera'
4) Build and run

![image](https://user-images.githubusercontent.com/46531149/195402872-e0bcc004-c327-4755-81ca-150bedcffd95.png)

![image](https://user-images.githubusercontent.com/46531149/195403039-1c8bd374-fb03-4193-881c-b07fc106ff26.png)

![image](https://user-images.githubusercontent.com/46531149/195402949-6bfdb190-e180-40df-b809-87c7b0dc612b.png)

**Comment by mbzworld** [comment]
That's very helpful!
Thank you so much for taking the time to respond to my request.

**Comment by Ste-RH** [comment]
You are very welcome @mbzworld.  Good luck with your project.
