### ISSUE TITLE
Xcode 13.4.1 > Build error with Bitcode enabled

### ISSUE THREAD

**Issue by BlueDonutStudios** [RenderHeads/UnityPlugin-AVProVideo#1328]
Hi Support,
I have an issue when building a Unity project in Xcode 13,4.1. It errors on the iOS plugin in the Framework regarding the Bitcode:

**"Frameworks/_Plugins/AVProVideo/Runtime/Plugins/iOS/AVProVideo.framework/AVProVideo' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file"**

Is there an issue with our version of the plugin or does it need to be re-downloaded from you?

Many thanks,
Marcus

**Comment by Chris-RH** [comment]
Hi @BlueDonutStudios,
This is a known issue with the latest version of AVPro and we are hoping to have a new version out towards the end of the week to rectify the problem.
(https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1326)

**Comment by BlueDonutStudios** [comment]
Hi Chris,
Thanks for getting back to me so quickly. Ok, thanks for the update. Good luck with the fix! :-)

**Comment by Chris-RH** [comment]
No problem :) Because this is a duplicate issue, I'm going to close this. The other thread will remain open until the fix is out.
