### ISSUE TITLE
Loading Media into MediaReference

### ISSUE THREAD

**Issue by AP432** [RenderHeads/UnityPlugin-AVProVideo#1329]
I'm currently using WebGL with the MediaPlayer & having some issues when selecting a file 'in-game' to load into the Player. This is because the MediaPlayer requires a file path (which isn't accessible through WebGL).

I'm wondering if there is an alternative method I could use, I'm thinking if I were to create an empty MediaReference and directly load the video file into that reference upon selection (as opposed to needing the string path of the file). I am able to do this with images within my application but when using video (with AVPro) it seems to only work off of the pathway.

Is there a load Method within the MediaReference API that could allow me to do this?

E.g. I select the file, the file is loaded into the empty MediaReference.

Appreciate any help with this

**Comment by Chris-RH** [comment]
Hi @AP432 
We don't really support WebGL platform.
I'm not really sure if that would work.  Here is some info about loading a file to MediaReference
https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-reference.html
