### ISSUE TITLE
Play video sometimes do not work

### ISSUE THREAD

**Issue by hanklord** [RenderHeads/UnityPlugin-AVProVideo#133]
**Describe the bug**
Hi All, I met a problem about playing video (AVPro version: 1.9.8 and 1.10.0) on Win10
I use following code to play a video
`mediaPlayer.OpenVideoFromFile(FileLocation.RelativeToProjectFolder, "file path");`
`mediaPlayer.Stop();`
`mediaPlayer.Rewind(true);`
`mediaPlayer.Play();`
but "sometimes" the video doesn't be played, and can not wait Control.IsFinished() turning to be true, screen keep showing the default texture image

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.22f1(64bit)
 - AVPro Video version: 1.9.8 and 1.10.0
 - Operating system version: Win10 (build 17134)
 - Device model: I7-6700, GTX1080 (VRAM 8G), 16G
 - Video specs (resolution, frame-rate, codec, file size): 
resolution: 1820x1024
frame-rate: 29.970
codec: H.264
file size: 23.0MB
[more info](https://drive.google.com/file/d/12Wp6OcGqCM0m2dt1yNsbiF5sJGO4a9H4/view?usp=sharing)

**To Reproduce**
1. following above code
2. Cant 100% to reproduce, because it is occasional

**Comment by AndrewRH** [comment]
Thanks for reporting this.  We will try to replicate it.

Is there any particular reason you need to call the API methods like this?

When the video is loaded if you dont' have Auto STart enabled, then it will not play, and it will already be rewound.  If you just want the video to play you can set the 3rd parameter of OpenVideoFromFile() to true.

**Comment by hanklord** [comment]
I Call  OpenVideoFromFile() to make sure opening the right video
According to our game logic the same media player will open different
videos every time.
Now, I try a method to avoid this problem (I read this issue
<https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/24>), and use
the method post by petermauger <https://github.com/petermauger>
(I think my problem is very similar to this issue)

Rewind(true);
while(Control.IsSeeking())
{
    yeild return null
}
Play();

I need to test for a long time to see if this problem still exists, because
this problem is occasional.

Thanks for your reply,
If AVPro team has any fixed pls let me know

Andrew <notifications@github.com> 於 2019年8月1日 週四 下午4:51寫道：

**Comment by hanklord** [comment]
More information, the video not played when I call Play()
After a while (about 3~5 sec) the video show up (from beginning)

HANKLORD <hanklord.com@gmail.com> 於 2019年8月1日 週四 下午5:04寫道：
