### ISSUE TITLE
Mac Unity 2021.3.3.f1c1 Flashback

### ISSUE THREAD

**Issue by JohnConstine** [RenderHeads/UnityPlugin-AVProVideo#1331]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.3.f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: IOS
 - Device model:  Mac unity editor
 - Video specs (resolution, frame-rate, codec, file size): nothing

**To Reproduce**

Hello gentlemen, when I use it on the Unity editor, click the object with it, and the editor will flash back.

**Comment by Chris-RH** [comment]
Hi @JohnConstine,
I'm not quite sure what you mean. Please could you provide reproduction steps and screenshots/a video might be helpful.

**Comment by JohnConstine** [comment]
thank you  sir， i fixed it。update it just  OK

**Comment by Chris-RH** [comment]
Great, thanks for letting us know :)
