### ISSUE TITLE
Frame index is not consistent

### ISSUE THREAD

**Issue by cecarlsen** [RenderHeads/UnityPlugin-AVProVideo#1332]
**Describe the issue**
The actual frame displayed and the frame index that you can deduct from the values provided by AVProVideo does not always match up. This is extremely important in my case because I am unpacking each frame using frame index specific metadata.

**Your Setup (please complete the following information):**
 - Unity version: 2022.1.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.4 Ultra.
 - Operating system version: Windows 10.
 - Device model: RTX 3070
 - Video specs (resolution, frame-rate, codec, file size): 4K, tried both frame rates of 25, 29.97 and 30, HAP, 73mb.

**To Reproduce**
1. Download test package from here [redacted] (also send to support email)
2. Run the scene "VideoPlayerFrameIndexConsistency".
3. Pause the Editor at random times and you will see that the index in the video and the index computed are not matching.

**Screenshots**
![FrameIndexInconsistencyAVProMedia](https://user-images.githubusercontent.com/34234131/195855953-1d985e15-2b9e-4278-adac-996995371159.png)

*Forum posts*
https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-98#post-8320803
https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-98#post-8390547

**Comment by Chris-RH** [comment]
Hi @cecarlsen,
If you use Directshow video API, it is more accurate the MediaFoundation.

**Comment by cecarlsen** [comment]
I am already using DirectShow. I need accurate, not "more accurate".

**Comment by Ste-RH** [comment]
We believe this is a rounding error.  Whilst we investigate, you can make the following adjustment in Helper.cs that should provide you with a 1:1 relationship.  Do let us know.

![image](https://user-images.githubusercontent.com/46531149/197581140-6c76147b-5cff-4c94-8e01-c75a200f132c.png)

**Comment by cecarlsen** [comment]
Thanks for getting back @Ste-RH unfortunately it does not help. I am testing using the test project I send you. Unity 2020.1.11.f1.

**Comment by Ste-RH** [comment]
Using the editor to pause is not a reliable way to test.

Instead I added video pausing/playing to your AVProVideoMediaPlayerController class:

	void Update()
	{
		if (Input.GetKeyUp(KeyCode.Q))
		{
			_player.Pause();
		}
		if (Input.GetKeyUp(KeyCode.P))
		{
			_player.Play();
		}
	}

**Comment by cecarlsen** [comment]
Aha! I see. It actually works. + 0.01 ... who would have known! Thank you =)
