### ISSUE TITLE
Playback m3u8 video

### ISSUE THREAD

**Issue by Sheonito** [RenderHeads/UnityPlugin-AVProVideo#1334]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.33f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.4v
 - Operating system version: Desktop - 90JL001DKR (LENOVO) - Windows 10  (10.0.19044) 64bit - Korean
 - Device model: PC(Windows)
 - Video specs (resolution, frame-rate, codec, file size): m3u8 video

**To Reproduce**
1. mediaPlayer.OpenMedia() with m3u8 video path like "mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, path, false);"
2. mediaPlayer.Play()
3. The video is not adaptive

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
https://metalive.s3.ap-northeast-2.amazonaws.com/video_sources/lottevideo/v_car_3_1.m3u8

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @Sheonito 

The url that you supplied only seems to have one rendition of the video?  You need to create multiple renditions for it to be adaptive.  
Here is a nice guide:
https://www.tothenew.com/blog/apple-http-live-streaming-hls/
Some more info:
https://www.tothenew.com/blog/adaptive-video-streaming-hls/
https://developer.apple.com/streaming/
