### ISSUE TITLE
HLS (m3u8) video streaming with subtitles bug

### ISSUE THREAD

**Issue by Serraya** [RenderHeads/UnityPlugin-AVProVideo#1335]
**Describe the issue**
HLS (m3u8) video URL works fine when it’s streamed from Akamai.
Url Example: https://12vod-adaptive.akamaized.net/...
But HLS (m3u8) video streaming stops after preloading 1-2 minutes when subtitles are streamed as well in case of VideoCDN service usage and subtitles aren't loading.
URL Example: https://skyfire.vimeocdn.com/...
Videos are hosted on Vimeo.

The only difference is the streaming source. All other settings in Unity or AVPro plugin are the same.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.10f1 and 2021.3.7f1
 - AVPro Video version: 2.6.4 trial, 2.5.7 core
 - Operating system version: macOS

**To Reproduce**
1. Open video from skyfire.vimeocdn in MediaPlayer
2. Enable subtitles
3. Rewind the video to the unbuffered area
4. Video will stop loading until you reload it completely

**Comment by Chris-RH** [comment]
Could you post the full url please? 
I have read about there being issues with vimeo and subtitles before, so it could be a vimeo issue? Could you try hosting your videos elsewhere?

**Comment by Serraya** [comment]
Sent full url to unitysupport@renderheads.com.

**Comment by Chris-RH** [comment]
AWS S3 is good for streaming.
I'm not sure that the skyfire link even has subtitles?

**Comment by Serraya** [comment]
It looks like media player recognize subtitles but they are empty.
![image](https://user-images.githubusercontent.com/24528127/196206019-78673105-8fa1-4c2c-8b03-6bd0038d5bfd.png)

**Comment by Chris-RH** [comment]
Yes, I think there is something wrong with it, as I've tried it in other media players and they are not seeing it.

**Comment by Serraya** [comment]
Somehow as of now, Vimeo videos provide an Akamai URL instead of Skyfire. So I can't even get Skyfire URL anymore.

**Comment by Chris-RH** [comment]
Oh, that's odd.  Though maybe not a bad thing seeing as it didn't appear to work as intended.
