### ISSUE TITLE
Video file encryption and decryption

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1336]
Problem description:

I am working on an application for the Quest 2 that may require users to download video files
to their device and use AV Pro to stream it from a local file. This file would not be in the streaming assets
directory of the APK but a directory native to the Quest itself. Do you guys have any suggestions on video
encryption and decyption? So far the videos we use are accessible to users and this leaves the application
unsafe. Is there any technique within the asset itself to solve this problem or will I need to look at a third party?
crash?

Device (which devices are you having the issue with - model, OS version number):

Quest 2, PC

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

I am running this application on Android and PCVR for the Quest 2 

System Information:

AVPro Video: v2.5.0 (plugin v2.5.0f1-ultra)
Target Platform: Android
Unity: v2021.3.8f1 WindowsEditor
OS: Desktop - B550M DS3H AC (Gigabyte Technology Co., Ltd.) - Windows 11  (10.0.22621) 64bit - English
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 threads - 32691KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10077KB - 16384

**Comment by Chris-RH** [comment]
Hi @Gurwar 

There are a couple of options for content protect: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html
File Offset might suit your needs?
