### ISSUE TITLE
Black outline in transparent videos

### ISSUE THREAD

**Issue by danielok1993** [RenderHeads/UnityPlugin-AVProVideo#1338]
**Describe the issue**
I have cut a video into two pieces with DaVinci Resolve, with intent to put another video in between the two pieces. When I add the two videos to the scene using Display UGUI I get a black overlay around the edge of the transparent video. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.21f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Ultra Edition v. 2.5.7
 - Operating system version: Windows 11 Home
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size):  1920x1080, 23.976, MPEG-4, Top-Bottom transparency

**Screenshots**
![image](https://user-images.githubusercontent.com/4477850/196501043-b297066a-0d4e-433b-bd76-f737090fe925.png)

**Comment by Chris-RH** [comment]
Are you able to send us a copy of the video or a reproducible scene to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)?
