### ISSUE TITLE
AVPro 2.6.5 - HAP video has Error: Loading failed on lower end hardware

### ISSUE THREAD

**Issue by drinsley** [RenderHeads/UnityPlugin-AVProVideo#1339]
Loading the Demo_MediaPlayer from AVPro 2.6.5 with a large 1.42gb HAP clip causes a Error:Loading failed error. Pressing play crashes Unity.

 - Unity version: 2021.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.6.5
 - Operating system version: Windows 10 Pro 64-bit (10.0 19044)
 - Device model: i7-3820 CPU, 8192mb ram, NVIDIA GeForce GTX 1050 Ti
 - Video specs: 1920x1080, 59.94fps, Hap, 1.43gb

**To Reproduce**
Load up trial version AVPRo 2.6.5
Load up Demo_MediaPlayer
Set Source>Media Source> to path
Select the video
Set to Media Foundation, Use Hap/NotchLLC ON
Press Load
get error
`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1399)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:827)
RenderHeads.Media.AVProVideo.MediaPlayer:EditorUpdate () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:783)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:373)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
`

If you press pllay it crashes, I emailed the crash log, mov and dxdiag info

**Comment by v2k** [comment]
This was with HAP video.

Going back we found that:

- v1.11.1: direct show works; media foundation does not load/play (but does not crash)
- v2.0+: crash Unity on load in Editor media foundation/direct show (same results with v2.0.9 and v2.6.5)

In the editor, just loading the video on the video player will cause the crash.

**Comment by Chris-RH** [comment]
Have you enabled "Use Custom MOV Parser"?

**Comment by drinsley** [comment]
Yes it crashes even when I enable "Use Custom MOV Parser"

**Comment by Chris-RH** [comment]
Are you testing this just in editor or in build too?
HAP decoding occurs in the GPU. I have the same graphics card and it runs fine on my machine.
My CPU is a i5-7400, so nothing fancy.  There is a lot going on in Unity editor that a lower end CPU may not be able to handle, and that might be where your issue is.  Just build and run, see if it works for you?

**Comment by drinsley** [comment]
Doesn't work in build either. 
I did some windows updates, now I'm on Windows 22H2. So now when I play it doesn't crash but give the same error:

`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1399)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:827)

`

**Comment by Ste-RH** [comment]
Have you tested on another PC?

**Comment by drinsley** [comment]
It works on another PC, just not on the low end one

Works with:
i7-10700, NVIDIA RTX A4000
Win 10 pro 64-bit
Same video: 1920x1080, 59.94fps, Hap, 1.43gb

Do you want to connect to the system and check it out?

**Comment by Ste-RH** [comment]
Can you try something a little less taxing?  So we can rule out it being a blanket problem.

Give this a try: [BigBuckBunny-360p30-HAP.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9919619/BigBuckBunny-360p30-HAP.zip)

**Comment by Ste-RH** [comment]
I have also re-encoded your video using the Jokyo HAP encoder, and re-encoded it at 30fps.  I will email you the links.

**Comment by drinsley** [comment]
With your BigBuckBunny-360p30-HAP clip, it crashes in editor and in build.

**Comment by Chris-RH** [comment]
@drinsley 
Does the clip play in other media players on that PC?

**Comment by drinsley** [comment]
BigBuckBunny-HAP clip only plays with VLC v3.0.17.4
When I right click open-with VLC it says that 'Oooops:VLC media player just crashed'. Then it opens the file and plays it. 
If I drag the file into VLC it plays fine.

It doesn't play with MPC-HC, Quicktime, WMP

**Comment by Chris-RH** [comment]
Sorry for the late reply, I've been away. 
Does it not play at all with the others, or does it play audio-only?

**Comment by drinsley** [comment]
The BigBuckBunny-HAP clip in MPC-HC, Quicktime, WMP plays audio-only

**Comment by Chris-RH** [comment]
OK, so when it does manage to play, how is your system performance looking?

**Comment by drinsley** [comment]
When I play it on VLC it doesn't take much, here are the increases.
CPU 3% to 5%
Mem 4.3gb 54% to 4.4gb 56%
GPU 2% to 10%

**Comment by Ste-RH** [comment]
We made some improvements in v2.7.0 towards HAP performance on lower graded PC hardware.  This _might_ help with this issue.

**Comment by Ste-RH** [comment]
We made some improvements in v2.7.0 towards HAP performance on lower graded PC hardware. This might help with this issue @drinsley

**Comment by drinsley** [comment]
Unfortunately same issue as the original.

Updated to v2.7.1 on the same machine and still reproduced the original bug.
