### ISSUE TITLE
 iPhone 8 happened a crash

### ISSUE THREAD

**Issue by defchen** [RenderHeads/UnityPlugin-AVProVideo#134]
**Describe the bug**
 iPhone 8 happened a crash which's stacks in the shot below.

![image](https://user-images.githubusercontent.com/1761985/62296220-3a28d680-b4a1-11e9-984b-ba9d37e0f845.png)

**Your Setup (please complete the following information):**
 - Unity version: 2017.4
 - AVPro Video version: 1.10.0
 - Operating system version: iOS
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by syedali1621** [comment]
Crush for me also on iPhone 7 plus and iphone xs max. To play video i am calling play() method of mediaplayer script and to stop video i am calling stop() method of media player script. When i play one video and stop it work okay but when i play 3 videos and stop all 3 videos and then run 4th video then app crush i think app is not releasing memory when stop.
let me know is there any function to release memory so i can call it after stop() method ?

**Comment by AndrewRH** [comment]
@defchen could you explain more about the circumstances that cause the crash - how many videos are you loading, what are the specs of the video (resolution, codec, frame-rate), does it happen every time, which version of iOS is your device running?  Are you able to replicate this using the demo scenes?

**Comment by AndrewRH** [comment]
@syedali1621 it would be useful to know more details - AVPro Video version, Unity version, video specs, device specs etc...Thanks,

**Comment by syedali1621** [comment]
unity 2018.3.1f1 and avpro latest ios version i recently bought. My app contain total 40 videos which are stored on aws cloud and i am calling each video URL with header using avpro player and yes i am using demo scene mapping 3d of avpro. and i am testing it on ios 12.3 and 12.4.

**Comment by syedali1621** [comment]
app is using too much memory that is a reason i got crush and sometimes it do not play videos.
i check on xcode it is using 102% cpu, 506.5 MB RAM energy impact is very high.
do you have any light weight version of avpro or can you tell me is there any method in avpro to release memory after each video play stop ?

**Comment by defchen** [comment]
my situation is that a MediaPlayer was paused but not closed in background. Meanwhile the another new MediaPlayer was being opened and playing. Then I needed to play a new video.This MediaPlayer which was playing was being Destroyed with creating a new MediaPlayer to play another video after then, and so on as such operations.  if i speed up the opreration, the crash happened.

**Comment by AndrewRH** [comment]
Hmm that's strange - for now could you try reusing the MediaPlayer instead of destroying+creating it?

**Comment by MorrisRH** [comment]
@defchen I believe the crash issue you're seeing has been fixed as of version 1.10.1 (issue SEGV_ACCERR ios crashes happened lots when we upgraded to 1.10.0 #182 also reported by yourself).

@syedali1621 If you still think there is an issue related to memory, could you create a new issue for this and we will be happy to investigate.
