### ISSUE TITLE
WebGL unable to load HLS stream when built from Unity Cloud Build

### ISSUE THREAD

**Issue by DevinLFL** [RenderHeads/UnityPlugin-AVProVideo#1340]
**Describe the issue**
Builds created via Unity Cloud Build fail to include hls.min.js in the TemplateData folder or reference it in the index.html

We get this error upon trying to open the build in Chrome, Brave, and Edge (so far what we've tested)

Uncaught ReferenceError: Hls is not defined at _AVPPlayerInsertVideoElement

Builds created locally via the editor work no problem. WebGL takes forever to build though and it would be ideal if we had CD working via unity cloud build.

I've also tried manually uploading hls.min.js to the TemplateData folder and editting the html in the index.html to reference 
<script src="TemplateData/hls.min.js"></script> which unfortunately didn't work

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.10f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.5 ultra
 - Operating system version: Unity Cloud Build WebGL macOS
 - Device model: Browsers
 - Video specs (resolution, frame-rate, codec, file size): m3u8 live stream (works via local builds)

**To Reproduce**
1. Create unity project with AVpro media player streaming m3u8 from IVS feed
2. Build via Unity Cloud build
3. Host files and attempt to run the unity app

**Screenshots**
![image](https://user-images.githubusercontent.com/92753490/196583862-72beec9c-cf97-43e8-aac8-3e1ab55c9bf9.png)

![image](https://user-images.githubusercontent.com/92753490/196584673-1a7c0478-3260-4ba7-b95f-ffe07dfa06e0.png)

**Comment by Chris-RH** [comment]
Which browser(s) are you testing on?
Have you read our sections on WebGL?
https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html#webgl
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl
Can you provide a full error log?

**Comment by MorrisRH** [comment]
I'm not sure I understand the issue.
Adding hls.js is a post-build step so not something unity cloud build would be doing anyway.

**Comment by DevinLFL** [comment]
Apologies, this may not be a you guys problem. It seems UCB isn't respecting the template we have setup in the project settings. I may have not edited the index.html properly either. I'm going to dig into to this some more this afternoon. If only these cloud builds didn't take 35 minutes each. 
 
<img width="856" alt="image (1)" src="https://user-images.githubusercontent.com/92753490/196767443-e689d371-cf46-4a54-a717-51dc3ef762a3.png">
