### ISSUE TITLE
ReadPixels Issue

### ISSUE THREAD

**Issue by dalkia** [RenderHeads/UnityPlugin-AVProVideo#1343]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**

Hello AVPro team! I have a doubt regarding the availability of the generated AVPro texture.

Im trying to copy the resultant texture to one of my own. The following code works just fine on Standalone builds; since they support the Graphics.CopyTexture function. 

![image](https://user-images.githubusercontent.com/1999557/197015738-b4cd3a3b-2058-4a95-8ddc-5517415d360a.png)

Nonetheless, Graphics.CopyTexture does not work in WebGL. And Im trying to find a way around the function, but it looks like the ReadPixels() function is not available for the AVPro texture. Is there some way I can read and then set this data?

I know this way generates way too much allocation. Do you know any other way to do it?

Thank you so much!

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Maybe this helper function we include might work in WebGL?

`public static Texture2D GetReadableTexture(Texture inputTexture, bool requiresVerticalFlip, Orientation ori, Texture2D targetTexture = null)`

Find it in the `Helper` class (\Assets\AVProVideo\Runtime\Scripts\Internal\Helper.cs)

Something like this:

Helper.GetReadableTexture( _mediaPlayer.TextureProducer.GetTexture(), _mediaPlayer.TextureProducer.RequiresVerticalFlip(), Helper.GetOrientation(_mediaPlayer.Info.GetTextureTransform()), videoTexture);

**Comment by dalkia** [comment]
Hey @Ste-RH! 

Yeah, that one works. But I see that inside the Helper it's generating a RenderTexture, which ends up taking up its toll on performance. Unfortunately, this is not an option I can take.

Do you know if it's possible to copy using the RawData of the textures? Or the pointers maybe? I'm thinking that maybe thats what `Graphics.CopyTexture` does under the hood.

Or any other idea comes to mind?

**Comment by dalkia** [comment]
BTW, to let you know, copying the texture this way removes the watermark =O

**Comment by Ste-RH** [comment]
Ahh. Right. So you want the frame texture CPU side?

I think you have two options in that case.

- keep the texture on the GPU and use Graphics.Blit with a custom shader to do what you desire

- use [AsyncGPUReadback](https://docs.unity3d.com/ScriptReference/Rendering.AsyncGPUReadback.html) so as not to stall the main thread. You won’t have frames immediately is the drawback.

**Comment by dalkia** [comment]
Hi @Ste-RH !

Okay, I ll try out your suggestions and circle back here :). Thanks!!
