### ISSUE TITLE
masking opposite eye

### ISSUE THREAD

**Issue by morrisOssoVR** [RenderHeads/UnityPlugin-AVProVideo#1344]
**Question**
I am using AVPro to view stereo video on two screens in a scene, to replicate a special viewer but I need the opposite screen masked.  IE: I want the left eye to only see the left eye screen and the right eye to only see the right eye scene.

Is this something built in or would we have to come up with a solution?

**Comment by morrisOssoVR** [comment]
Yes were both here.  I will let you and him finish then.  

Thanks

**Comment by Ste-RH** [comment]
I can forward on the email to you as well if that helps

**Comment by morrisOssoVR** [comment]
sure

**Comment by Ste-RH** [comment]
Is your address morris@ ?

**Comment by morrisOssoVR** [comment]
morris@ossovr.com

**Comment by Chris-RH** [comment]
Closing this due to being in touch via email
