### ISSUE TITLE
Audio tracks limit

### ISSUE THREAD

**Issue by dawidchyrzynski** [RenderHeads/UnityPlugin-AVProVideo#1347]
**Describe the issue**
There seems to be a limit of 5 tracks the library supports. I have a video file with 5 audio tracks and the 5th audio track is missing on the list of audio tracks.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.11f1
 - AVPro Video version:  AvPro Ultra 2.6.5
 - Operating system version: Android 8.1
 - Device model: Pico G2
 - Video specs (resolution, frame-rate, codec, file size): H264, 3840x3840, 5 audio tracks (mp3)

**To Reproduce**
1. Load a video with at least 5 audio tracks and get the number of tracks as follows `mediaPlayer.AudioTracks.GetAudioTracks().Count`. It will return 4 instead of 5.

**Logs**
There is one error log when the media is opened `MM_OSAL : VIDEO_FMT_STREAM_AUDIO:m_trackCount OVERFLOW 5`

**Side note**
It works fine in the editor (macOS). All audio tracks are listed.

**Comment by Chris-RH** [comment]
Hi @dawidchyrzynski, 

Have you tried other video files with multiple audio tracks?
Have you tried other android devices?
Could you post a copy of the video or email it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)?
Could you supply a full logcat?

**Comment by dawidchyrzynski** [comment]
1. MediaPlayer
2. Same issue with other video files.
3. Yes, Pico Neo with Android 10 - same issue.
4. Done.
5. Is there any specific configuration needed to get AvPro logs? It doesn't seem to log anything in the logcat.

**Comment by Chris-RH** [comment]
I would try using exoplayer and see if that helps.
https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs
Are you using Android Studio to get the logcat or something else?

**Comment by Ste-RH** [comment]
Thanks for sending over the video @dawidchyrzynski.

Have you tried any none-Pico devices?  Just ran our Demo_MediaPlayer scene with your video and I am getting 5 audio tracks reported.

Just sorting out a Pico Neo 2 to test on here...

**Comment by dawidchyrzynski** [comment]
@Chris-RH Exoplayer is not an option. It lags terribly on Pico G2 with better-quality videos. I'm using adb logcat CLI.

@Ste-RH Our app supports only Pico devices. Maybe it has something to do with the way how we instantiate the media player. The object is created dynamically at runtime as follows:

```c#
var playerObj = new GameObject("MediaPlayer", typeof(MediaPlayer));
playerObj.transform.SetParent(xrRigObject.transform);
var player = playerObj.GetComponent<MediaPlayer>();

player.Loop = false;
player.AutoOpen = false;
player.AutoStart = false;
player.AudioHeadTransform = Camera.main.transform;
player.FallbackMediaHints.stereoPacking = StereoPacking.TopBottom;
player.PlatformOptionsAndroid.videoApi = Android.VideoApi.MediaPlayer;
player.PlatformOptionsAndroid.audioOutput = Android.AudioOutput.System;
player.PlatformOptionsAndroid.useFastOesPath = true;

ApplyToMesh material = d_sphereObject.GetComponent<ApplyToMesh>();
material.Player = player;

player.OpenMedia(MediaPathType.AbsolutePathOrURL, "...", false);

// once the media is loaded:
player.Play();
```

**Comment by Ste-RH** [comment]
Ahh, right.  Sorry...missed that you are not using ExoPlayer.  My report above was using the ExoPlayer path, not MediaPlayer.  I have reproduced it now here.  Will investigate.

**Comment by Ste-RH** [comment]
MediaPlayer appears limited to 5 tracks.

I tried:

- 1 video and 5 audio.  Only 4 audio show up with the single video

- 5 video and 11 audio.  Just the 5 video show up and 0 audio

There is only one method to obtain track information ([getTrackInfo()](https://developer.android.com/reference/android/media/MediaPlayer#getTrackInfo())) and this is what is returning back only 5 tracks.

As this appears a limitation of the Android API, we cannot offer a fix.

**Comment by dawidchyrzynski** [comment]
@Ste-RH Would it be possible to load an audio file from a separate file (like SRT side loading)?

**Comment by Ste-RH** [comment]
> @Ste-RH Would it be possible to load an audio file from a separate file (like SRT side loading)?

Not in conjunction with the video (such that you would be able to reliably sync audio to picture).
