### ISSUE TITLE
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources. UnityEngine.Debug:LogError (object)

### ISSUE THREAD

**Issue by FarhanIshfaq** [RenderHeads/UnityPlugin-AVProVideo#1349]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.33
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version:  trail
 - Device model:  windows 10 hp with graphic card
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @FarhanIshfaq,
We do need more information from you to be able to help. Specifically:
The specs of the video you are trying to play (resolution, framerate, codec, file size etc)
Which Video  API you are using (Media Foundation, DirectShow or WinRT)
It would be helpful if you could attach a copy of the file you are trying to play here, or email it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)? if you would prefer (with issue #1349 in the subject line)

**Comment by Chris-RH** [comment]
Closed due to lack of reply
