### ISSUE TITLE
Equi Angular Cubemap support

### ISSUE THREAD

**Issue by ThomasVROwl** [RenderHeads/UnityPlugin-AVProVideo#135]
Youtube uses Equi Angular Cubemap (EAC) for their VR videos. The format looks like this:

![image](https://user-images.githubusercontent.com/53605147/62360582-65e7a300-b519-11e9-89c6-0898fdb63fd1.png)

I have tried to make a sphere mesh with a uv map that maps the EAC texture to a sphere. That way I could play the video while still using the AV Pro OES shaders. Unfortunatly, it seems almost impossible to play videos using this sphere mesh without seeing the seams.

I would like an option to play EAC videos, both mono and stereo, using AV Pros OES shaders.

**Comment by AndrewRH** [comment]
Here is a shader we found: https://github.com/hakanai/EACSkyboxShader

Someone could integrate this into a custom OES shader using our existing shaders as reference.

We currently have no plans to integrate this natively as it's a bit of an edge case.

**Comment by Chris-RH** [comment]
Closed because there doesn't seem to be much interest in this anymore

**Comment by kpbg** [comment]
There is interest actually as this seems to be gaining some traction. 

Any chance the Equi Angular Cubemap support can be reconsidered? I just bought the Ulta asset and I hoped the option is already in place.
