### ISSUE TITLE
playing the video on Mac M1 chip has weird playback issue

### ISSUE THREAD

**Issue by abhishekm-altoura** [RenderHeads/UnityPlugin-AVProVideo#1350]
We are having an issue while playing the video only for the Mac M1 chip. . Video is being played when the app moves to the background. While playing the video we are getting the status as unknown and are even not able to get the logs. Please help us to resolve this issue.

 - Unity version: 2020.3.21f1
 - AVPro Video version (Version 2.6.4 and core edition ): 
 - Mac OSX: 
 - Device model: Mac Book Air M1 2020 
 -  All video
 

**Logs**
[VideoLogs.pdf](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9879123/VideoLogs.pdf)

**Comment by Chris-RH** [comment]
Hi @abhishekm-altoura 

It says in the logs that you are using AVPro version 2.5.7, could you update to the latest version please.
Are you using the demo mediaplayer scene?

**Comment by abhishekm-altoura** [comment]
Hi @Chris-RH 

 I tried the 2.5.7 also but the same issue. It works in the demo MediaPlayer scene but doesn't work in our project tried many things to see what is going wrong nothing worked as the last resort checking here in case I can get any help.

**Comment by Chris-RH** [comment]
1. What sort of media are you trying to play? resolution, framerate, codec etc?
2. Are you playing it locally or streaming? If so, how?
3. Does that file play using the demo scene?
4. Will it play in editor?
5. Will it play on that device using other software?
6. Have you tested it on other devices?

**Comment by Chris-RH** [comment]
So to confirm, the issue is only within your app, when playing in a build on the mac M1?

**Comment by abhishekm-altoura** [comment]
yes the issue is only within our app and that too only m1 version of the mac.other mac it works.

**Comment by Chris-RH** [comment]
We can't really go any further with this unless we have a project file to test in-house.  Please email to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com), thank you.

**Comment by Chris-RH** [comment]
Closed due to lack of response.
