### ISSUE TITLE
How do I use Media foundation to play 8k videos

### ISSUE THREAD

**Issue by yyt1216** [RenderHeads/UnityPlugin-AVProVideo#1351]
I used pr to change BigBuckBunny-360p30-H264.mp4 to h265. Cannot play using media foundation.It can be played using direct show, but I don't want to use it, it's slow.
I am trying to do LAN multi-machine video synchronization with unity, do you have any good suggestions

**Comment by Chris-RH** [comment]
Which platform are you using?
If it is Windows 10, then it isn't natively supported and you need to download the HEVC codec from the Microsoft store.
https://apps.microsoft.com/store/detail/hevc-video-extensions/9NMZLZ57R3T7?hl=en-us&gl=us
