### ISSUE TITLE
Can't Set playback rate in Playlist Media Player

### ISSUE THREAD

**Issue by MAXDUTOR** [RenderHeads/UnityPlugin-AVProVideo#1353]
//Problem description:

Can't Set playback rate in Playlist Media Player m3u8 video format. I use a simple button event >playlistMediaPlayer.PlaybackRate

Media

1 video on playlist 1080p m3u8 video 
url- "https://live.med.cmu.ac.th/s3/_definst_/vod/interactive/mp4:C3_Part_4_Imaging_of_hemorrhagic_stroke.mp4/playlist.m3u8"

System Information:

AVPro Video: v2.5.3 (plugin v2.5.3f2-core)
Target Platform: WebGL
Unity: v2019.4.40f1 WindowsEditor
OS: Desktop - Precision 3630 Tower (Dell Inc.) - Windows 11  (10.0.22621) 64bit - Thai
CPU: Intel(R) Xeon(R) E-2174G CPU @ 3.80GHz - 8 threads - 65367KB
GPU: NVIDIA Quadro P4000 - NVIDIA - Direct3D 11.0 [level 11.1] - 8089KB - 16384

**Comment by Chris-RH** [comment]
Hi @MAXDUTOR,

You can change the playbackrate in the media player component
