### ISSUE TITLE
Easily switch between platforms

### ISSUE THREAD

**Issue by davidbardos** [RenderHeads/UnityPlugin-AVProVideo#1354]
Hey,

We are working on a multi platform project (windows / android) and every time we switch the platfprm we have to erase the AVPro plugin from the project and import another AVPro plugin in order to not having the watermark.
Is there a way to switch platform without having to delete the plugin and import the other one?

Thanks,
David Bardos

**Comment by Chris-RH** [comment]
Hi @davidbardos,

Am I correct in thinking that you have the Android Core and Windows Core versions?
Have you followed this guide: https://www.renderheads.com/content/docs/AVProVideo/articles/install.html#installing-multiple-single-platform-packages

**Comment by davidbardos** [comment]
You are very correct sir! I have been using AVPro for years and always for one platform at a time, did not do the obvious thing: checking the manual. Thank you for your quick answer and sorry for bothering you with this.

**Comment by Chris-RH** [comment]
No problem at all, we are here to help :)
