### ISSUE TITLE
RTSP freezing after brief period

### ISSUE THREAD

**Issue by panchaia-af** [RenderHeads/UnityPlugin-AVProVideo#1355]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
With AVPro Video Core Android (paid, not trial) running on a tablet and accepting a stream from an NVR. Connection is over WLAN with no internet connection and with fixed IPs. All other elements are disabled, so it's just this running in isolation. Exoplayer, pointing at an RTSP URL. RTSP feed shows a live clock, allowing easy identification of frozen video.

RTSP feed starts and displays correctly. After a few minutes of operation, the RTSP feed freezes on a single frame. With a second client simultaneously viewing the stream, the stream itself continues. This does not happen on other apps running on the same tablet, just anything on Unity using AVPro Video.

**Your Setup (please complete the following information):**
 - Unity version:  2022.1. 21
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.5
 - Operating system version: Windows 10 for development, running on android.
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 960x576, ~1140, H.264+

**To Reproduce**
1. Start streaming from RTSP source
2. Wait a few minutes
3. Confirm if video continues to be displayed

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @panchaia-af,

1. Are you able to provide a full logcat?
2. Have you tested it using other android devices?
3. Is the RTSP stream unicast or multicast?
4. What hardware are you using (NVR, tablet etc)?
5. What frequency is your LAN?
6. Distance between device and WAP?

**Comment by panchaia-af** [comment]
Hi Chris-RH, apologies for the slow response.

1. I've attached the output of logcat, running from just before the program finished to after it had failed in this way.
2. The same behaviour is seen on the one other Android device I've tested it with.
3. A second RTSP stream was tried. This was over a different WLAN since it's a source from the internet rather than on a LAN.
Also, note that the first test was done on the WLAN intended to be used, which has no internet connection. This appears to play.
4. The RTSP stream is unicast
5. The NVR is a HIKVISION HILOOK DVR-104G-F1, the tablet is an Oukitel RT1 4GB running Android 11.
6. The LAN has both 2.4GHz and 5GHz networks, both show the same effect
7. The error occurs a few inches from the WAP and 10 feet away, with the device static.

[cap.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/9934672/cap.txt)

**Comment by Chris-RH** [comment]
closed due to lack of reply.

**Comment by panchaia-af** [comment]
Hi Chris,
Sorry for the late response. Even with just the plugin in an otherwise blank project it would fail. The problem turned out to be two RTSP sources that were both providing somehow-bad data!

AVProVideo is working reliably with a third, good, source.

I am not sure what the difference is between how VLC and the like process the stream and how AVPro does, but some part of the plugin seems to not like the sources I had. I will experiment more in future and report back to you if I find anything.

Thanks,
panchaia-af
________________________________

**Comment by Chris-RH** [comment]
Brilliant, it would be great to know how they differ, thank you :)
