### ISSUE TITLE
guava-31.1-android conflict with other plugins

### ISSUE THREAD

**Issue by LinNaiHao** [RenderHeads/UnityPlugin-AVProVideo#1356]
我们在使用您的工具的时候，在打包的时候发现guava-31.1-android会和其他的插件冲突。我们其他插件包含了Gamebase\AdMob\Singular等。我们没法快速定位到和哪个插件的哪个文件冲突了。
我们的解决方案是：
1、移除您插件内的guava-31.1-android
2、使用[unity-jar-resolver](https://github.com/googlesamples/unity-jar-resolver)为您的插件引用 guava-31.1-android
不知道您知不知道unity-jar-resolver，我觉得可以用这个工具解决这些冲突问题。
----------------------------------
When we use your tool, we found that guava-31.1-android will conflict with other plugins when packaging. Our other plugins include Gamebase\AdMob\Singular etc. We can't quickly locate which file conflicts with which plugin.
Our solutions are:
1. Remove guava-31.1-android from your plugin
2. Use [unity-jar-resolver](https://github.com/googlesamples/unity-jar-resolver) to reference guava-31.1-android for your plugin
I don't know if you know unity-jar-resolver, but I think you can use this tool to resolve these conflicts.

**Comment by Chris-RH** [comment]
Hi @LinNaiHao,

Yes, this is a known conflict (#630 #950 ). Guava-31-1android is required for ExoPlayer API.
That looks like an interesting tool, thanks for the link.
