### ISSUE TITLE
Video loading does not finish

### ISSUE THREAD

**Issue by JackM36** [RenderHeads/UnityPlugin-AVProVideo#136]
Sometimes videos seem to not be able to finish loading. I have not noticed a specific pattern, but if I try to play a video 10 times, 2 of those are going to fail due to the video not being loaded. 

I basically do this whenever a video has to be played:
`player.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, videoFullPath, false);`

And then wait for the **FirstFrameReady** event to fire
```
case MediaPlayerEvent.EventType.FirstFrameReady:
                    player.Play();
                    break;
```
Well, sometimes the **FirstFrameReady** event will never be fired. I am not sure if the problem is the event not being fired, or the video not being loaded.

It seems random. It doesn't seem to be video-specific or anything. If I try to call **OpenVideoFromFile** again chances are it is going to load successfully.
Any ideas where the problem is?

The problem was mostly observed on Oculus Go (Exoplayer).

 - Unity version: 2018.3.5
 - AVPro Video version: 1.9.7

**Comment by AndrewRH** [comment]
Hi,
Please try upgrading to the latest version of the plugin (1.10.0) as many issues such as this have been fixed.
Does that help?

**Comment by OldMontana** [comment]
We've been experiencing the same thing. We have separate audio files being played through the FB Audio 360 plugin, and about 20-30% of the time, the audio will start playing but the video never loads. We'll try upgrading the plugin and will report back.

**Comment by JackM36** [comment]
I updated the plugin. I did not encounter the issue yet. Not sure if it was just luck, but it seems to be fixed now. I will report back if I encounter it again.

@OldMontana Is it also fixed for you?
