### ISSUE TITLE
Memory unloading issue and memory leak issue in AVPro 2.6.5

### ISSUE THREAD

**Issue by ciperpugazhenthi** [RenderHeads/UnityPlugin-AVProVideo#1360]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

We are trying to integrate an AR module as an library package into native Application from unity. We use the AVPro for playing a video from URL. The beginning all the datas are been loaded and set in the scene, URL is loaded and media player is enabled and URL passed everything runs fine in the beginning stage when we are unloading the unity scene i.e going back to native app interface all memory is not being released but when using unity Video player component and all dynamically loaded memories are released and i can get back the memory. We have tried to destroy the avpro mediaplayer and other avpro references from scene no improvements still the memory leak issue is not solved. Tried closing the mediaplayer,  stopping the media player and i have used EndOpenChunkedVideoFromBuffer() to release the video buffer memory i believe. i have attached the code snippet of unloading avpro below you can check..We face the issue in iOS only in all iOS versions. Trying to release the cached video url using RemoveMediaFromCache(url) but nullreference is throwing. Kindly help us to solve this memory leak issue thank in advance 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.9
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.5
 - Operating system version: mac OS 12.6
 - Device model: iOS all versions (above iOS 12)
 - Video specs (resolution, frame-rate, codec, file size):  .mp4 file

**To Reproduce**
1. Try to unload the module and check for memory leak
2. Call functions from avpro to release memory caches

**Screenshots**
Method used to clear the AVPro media player references
![Clear all media reference](https://user-images.githubusercontent.com/25650662/199956408-6fb74493-c375-48f6-b337-8ce96586ff6d.png)

The below screen shot is will show the memory usage graph when using unity video player
![Unity VideoPLayer](https://user-images.githubusercontent.com/25650662/199956172-ea7464f0-b143-4a8d-b7a4-28bdcba6adf3.png)

The below screen shot is will show the memory usage graph when using AVPro Media Player
![using AVPro MediaPlayer](https://user-images.githubusercontent.com/25650662/199956212-f0dc479f-099b-42a3-8ad1-0a8a649ec572.png)

By screen shot comparison Unity Video player releases more memory than AVPro Media player

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Please provide all the information requested @ciperpugazhenthi

**Comment by ciperpugazhenthi** [comment]
Yeah just now updated the issue @Ste-RH

**Comment by MorrisRH** [comment]
Are you using the media caching API? See the documentation [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-caching.html). If not then ```RemoveMediaFromCache``` will not be helpful to you.

There are some memory related fixes going in for another issue with version 2.6.6 which we will be releasing shortly. Please update to this version when it's available and let us know if you're still seeing the problem.

**Comment by Chris-RH** [comment]
Have you tried the above and also updated to version 2.6.6?

**Comment by ciperpugazhenthi** [comment]
> 

@MorrisRH Yes i have updated by Current AVPro package with new 2.6.6 i which it was throwing an error and i'm unable to use it

**Comment by MorrisRH** [comment]
@ciperpugazhenthi please provide details of the error otherwise there is nothing further we can do

**Comment by Chris-RH** [comment]
Closed due to lack of information.  Please reopen if you can provide further information.
