### ISSUE TITLE
Unable to play HLS streams with unsupported subtitle tracks

### ISSUE THREAD

**Issue by micahrollinsmlb** [RenderHeads/UnityPlugin-AVProVideo#1361]
When we attempt to load an HLS stream that contains an unsupported subtitle track, we receive the standard "Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources." When we try to load the same HLS stream using ExoPlayer directly, it will play the supported tracks and simply ignore the subtitle track. Ideally, AVPro would behave the same way.

**Your Setup (please complete the following information):**
 - 2019.4.14f1
 - AVPro Video 2.6.5 Ultra
 - Windows 10
 - Video specs: 3840x2160, 30 fps, MPEG-H Part2/HEVC (H.265) (hvc1)

**To Reproduce**
1. Attempt to load video

**Videos**
Sample video: https://vr-assets.mlb.com/AWS/DEV/8d6bff48-033c-47e9-a8fa-c8aed75accb8/camA.m3u8

**Comment by Ste-RH** [comment]
Windows 10 does not come with an HEVC codec. You need to download one from the windows store. If you have not done this, you can find many guides on the process, such as [this](https://www.howtogeek.com/680690/how-to-install-free-hevc-codecs-on-windows-10-for-h.265-video/amp/)  one.

**Comment by Ste-RH** [comment]
So you are getting the error playing back the video in Windows or on an Android device?

**Comment by micahrollinsmlb** [comment]
I get the error playing back in Windows. On Android we use ExoPlayer directly, and it does not have this problem.

**Comment by micahrollinsmlb** [comment]
My apologies, I didn't see this comment about the HEVC codec until just now.

I do have the HEVC codec installed on my PC. I verified that the problem was the subtitle track (Codec: dfxp) by removing the subtitle track with ffmpeg. Once I removed the subtitle track, I was able to play the video using AVPro.

Cheers!
Micah Rollins
________________________________

**Comment by Ste-RH** [comment]
Yeah, it's odd.  Not sure there is much we can do about it.  The Windows API's all seem to hate that format and refuse to simply ignore it.  Sorry, I don't think there is much we can do about this one and recommend removal (as you have done), or use a different format.

**Comment by micahrollinsmlb** [comment]
Oh that's really interesting. Do you know if there is a codec that I can install that would allow those Windows APIs to load the subtitle track? My google searches came up empty, but perhaps you have heard of something?

Thank you!

**Comment by Chris-RH** [comment]
I've had a look and can't find anything.  As above, I would recommend removal or using a different format.

**Comment by micahrollinsmlb** [comment]
Thank you!
