### ISSUE TITLE
Do we have an IOS ambisonic player or plugin? if yes please let me know.

### ISSUE THREAD

**Issue by RojanStha** [RenderHeads/UnityPlugin-AVProVideo#1362]

**Comment by Chris-RH** [comment]
Hi @RojanStha 

We have nothing in the plugin that specifically supports ambisonics on iOS.  However, iOS does support ambisonics with the use of capable hardware (such as Airpod Pro/Max), so in theory a video with an ambisonic audio track should work.  Unfortunately we don't have the hardware to hand, so cannot test that in house.
You are more than welcome to test it with our free, fully-featured, watermarked trial version: https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases
