### ISSUE TITLE
Android video not playing. Cannot open fileform obb

### ISSUE THREAD

**Issue by CapSparkle** [RenderHeads/UnityPlugin-AVProVideo#1364]
**Describe the issue**
When i try to play one video, which specs are described down, i catch error: (i can't type it here because it was only on my device screen, but i remember it): 
It says like: AVProVideo error Load cannot find file or wrong codec, or wrong resolution or too expensive to play

I already played this video successfully with unity built-in player (on android) - so it is definetly not wrong codec, not too expensive.
And in UnityEditor it works without any problems.

SETUP:
- Unity 2021.3.11f1
 - AVPro Video ultra 2.6.5
 - Windows 11 21H2 (unity editor); Android 12 (target device)
 - Samsung Galaxy Tab A8 
 - Video specs (1920x1080, 25 framerate, MP4 H.264 codec, 78 Mb): 

**To Reproduce**
No override check set for android:
![image](https://user-images.githubusercontent.com/25351821/201335769-5f396729-fb4d-42d0-9345-e03ac21381c1.png)

Than i made MediaReference by just selecting it lying in my assets folder
Than in runtime i set this Reference to MediaPlayer field, Load and Play
![image](https://user-images.githubusercontent.com/25351821/201336213-6da43c07-c48b-4f6f-9cfc-486152c1d761.png)
`mediaPlayer.OpenMedia(mediaReferences[index], autoPlay: false);`
...
`if(eventType == MediaPlayerEvent.EventType.ReadyToPlay ||`
         `   eventType == MediaPlayerEvent.EventType.FirstFrameReady)`
   `     {`
    `            mediaPlayer.Play();`
             `   meshRenderer.enabled = true;`
         `   }`
  I use Apply To Mesh component. I tried the following shaders for this mesh and didn't find any differences - just black screen:
  
![image](https://user-images.githubusercontent.com/25351821/201336702-1a3a93cb-ab03-4544-9446-05b715254b3b.png)

Maybe i need to specify some specific render textures for this material? But if it is why error is: Cannot find?
Maybe i have to place video on which MediaReference refers in some specific folder? I already set external permission in build settings.

Thank you in advance!

**Comment by CapSparkle** [comment]
I caught something interesting
![image](https://user-images.githubusercontent.com/25351821/201339677-43c101ec-9a65-48bc-8e66-aa26edff9143.png)

**Comment by CapSparkle** [comment]
okaaaay, this is definetly not a directory, but this is what MediaReference has to refer to...
What don't i understand?

![image](https://user-images.githubusercontent.com/25351821/201343273-c578e74d-bd69-4e11-8bd5-732552947c1c.png)

**Comment by Chris-RH** [comment]
Have you tried extracting to persistentdatapath?
If you are using Exoplayer API could you try switching to Android Mediaplayer API?

**Comment by CapSparkle** [comment]
What you mean extracting to persistentdatapath? Just manualy put it in this folder and than refer to this? Now i don't - it is definetly not a variant because of user experience. Or maybe i can do it automatically by script? Tell me how, please.

Okay, wil try to switch to Mediaplayer API.

**Comment by CapSparkle** [comment]
I get over this error with next code:
`BetterStreamingAssets.Initialize();

            byte[] myvideo= BetterStreamingAssets.ReadAllBytes("videos/myvideo.mp4");
       

            string folderPath = Application.persistentDataPath + "/videos";
            Directory.CreateDirectory(folderPath);

            using (FileStream fs = File.Create(folderPath + "/myvideo.mp4"))
            {
                fs.Write(myvideo, 0, myvideo.Length);
            }`
            
            
           There is no errors i catch in unity android and nor in AndroidLogCat, but MediaPlayer just shows me this - flipped over picrute of what my device sees (it is AR app)
           
           
![arhRY9AFbP5NJNTlcHh1pb7APck2tbxvnGOANw-5W8y-0uLCwIsqXETcBKaFknpXkf9AWKfH1SwuVGLgrpBRt_2Y](https://user-images.githubusercontent.com/25351821/201476178-e0a1bbaa-7136-4901-a91f-bec7465184a8.jpg)
As you can see - there is screen with "Apply to mesh" component

**Comment by CapSparkle** [comment]
I choose this shader instead of upper one. It helped. Thank you. 

![image](https://user-images.githubusercontent.com/25351821/201477724-c52c8461-4276-4401-8600-d5758cb6a21d.png)

But i am curious what this error mean? Doeas it mean some lack of perfomance? I use h.264 codec  because i thougth it will be definetly nicely supported on android. Tell me please what does it mean.

![image](https://user-images.githubusercontent.com/25351821/201477748-7821dee4-d34f-42c5-b7b9-879db92f3688.png)

**Comment by Ste-RH** [comment]
Playback from videos in OBB _should_ work just fine using ExoPlayer.  If you require this and are seeing an issue still, we will happily look into the issue.

**Comment by CapSparkle** [comment]
> Playback from videos in OBB _should_ work just fine using ExoPlayer. If you require this and are seeing an issue still, we will happily look into the issue.

I didn't find a way to play videos from OBB with ExoPlayer, but i already satisfied with persistenDataPath way to store
