### ISSUE TITLE
Video with multiple audio tracks causes choppy audio when played through Unity on macOS/iOS

### ISSUE THREAD

**Issue by joseph-o3h** [RenderHeads/UnityPlugin-AVProVideo#1367]
**Describe the issue**

When a video with two audio tracks is played on iOS and macOS with the audio mode set to Unity the audio playback is choppy. This happens even when a single audio track is selected by calling `mediaPlayer.AudioTracks.SetActiveAudioTrack(...)`.

This does not occur with the audio mode set to System Direct.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.9
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.2 ultra
 - Operating system version: macOS 12.6, iOS 15.7
 - Device model: MacBook Pro 16-inch 2019 and iPhone 11 Pro
 - Video specs (resolution, frame-rate, codec, file size): 944x2048, 30 FPS, H.264 + AAC audio (2 tracks), 18.4 MB

**To Reproduce**
Run the sample project sent by email in play mode in the macOS editor (select the scene `SampleScene`) or build and run on an iOS device.

**Videos**
Video is in streaming assets in the sample project.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by joseph-o3h** [comment]
Is it possible to make `SetActiveAudioTrack` always play the selected track regardless of the enabled flags, or does the native API not allow this?

**Comment by MorrisRH** [comment]
It's an interesting issue. QuickTime player plays only the first audio track, but the QuickLook player mangles the two tracks in the same way as AVPro Video does. I'm looking for a solution but having two enabled audio tracks breaks how the OS reports the number of audio tracks in the asset.

**Comment by MorrisRH** [comment]
Hey @joseph-o3h, version 2.6.7 has just been released which includes a fix for this issue.
