### ISSUE TITLE
Android build running in oculus rift causing error: AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager

### ISSUE THREAD

**Issue by Elly2018** [RenderHeads/UnityPlugin-AVProVideo#1368]
ADB logcat record is here
[logcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/10026892/logcat.txt)

AvPro version: 2.6.4
Unity version: 2020.3.17f1 Personal
Build confing: 
  Backend: Mono
  Api level: .NET.4
  Target arch: ARMx7
  Minimum Api level: Android 7.1 (Level 25)
  Target Api level: Android 10.0 (Level 29)

After the error message i realized all the AvPro related components are null
Because loading library failed

This is what i saw:

11-16 14:05:16.534 18382 18405 D AVProVideo: UnityPluginLoad CALLED
11-16 14:05:16.611 18382 18405 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
11-16 14:05:16.611 18382 18405 E Unity   : java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
11-16 14:05:16.611 18382 18405 E Unity   :      at java.lang.Class.classForName(Native Method)
11-16 14:05:16.611 18382 18405 E Unity   :      at java.lang.Class.forName(Class.java:454)
11-16 14:05:16.611 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-16 14:05:16.611 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
11-16 14:05:16.611 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
11-16 14:05:16.611 18382 18405 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:105)
11-16 14:05:16.611 18382 18405 E Unity   :      at android.os.Looper.loop(Looper.java:227)
11-16 14:05:16.611 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
11-16 14:05:16.611 18382 18405 E Unity   : Caused by: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
11-16 14:05:16.611 18382 18405 E Unity   :      ... 8 more
11-16 14:05:16.611 18382 18405 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00096] in <d21e055bfb244463b7cf4d29f8901369>:0
11-16 14:05:16.611 18382 18405 E Unity   :   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x0000c] in <d21e055bfb244463b7cf4d29f8901369>:0
11-16 14:05:16.611 18382 18405 E Unity   :   at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args)
11-16 14:05:16.619 18382 18405 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
11-16 14:05:16.619 18382 18405 E Unity   : java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
11-16 14:05:16.619 18382 18405 E Unity   :      at java.lang.Class.classForName(Native Method)
11-16 14:05:16.619 18382 18405 E Unity   :      at java.lang.Class.forName(Class.java:454)
11-16 14:05:16.619 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-16 14:05:16.619 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
11-16 14:05:16.619 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
11-16 14:05:16.619 18382 18405 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:105)
11-16 14:05:16.619 18382 18405 E Unity   :      at android.os.Looper.loop(Looper.java:227)
11-16 14:05:16.619 18382 18405 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
11-16 14:05:16.619 18382 18405 E Unity   : Caused by: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
11-16 14:05:16.619 18382 18405 E Unity   :      ... 8 more

**Comment by Chris-RH** [comment]
What are your proguard/minify settings?
What are your gradle settings?

https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#javalangclassnotfoundexception--javalangnosuchmethoderror

**Comment by Elly2018** [comment]
![Capture](https://user-images.githubusercontent.com/34325707/202596069-f858ce14-cf78-4e85-8836-e415e260cf7f.PNG)
This is my player setting

AndroidManifest.xml
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.unity3d.player"
    xmlns:tools="http://schemas.android.com/tools"
    android:targetSandboxVersion="1">
  <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
  <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
  <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
                 android:maxSdkVersion="32" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                 android:maxSdkVersion="29" />
  <uses-permission android:name="android.permission.INTERNET" />
    <application android:usesCleartextTraffic="true" >
        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:theme="@style/UnityThemeSelector">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
        </activity>
    </application>
</manifest>

LanucherManifest.xml
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.unity3d.player"
    xmlns:tools="http://schemas.android.com/tools"
    android:installLocation="preferExternal">
    <supports-screens
        android:smallScreens="true"
        android:normalScreens="true"
        android:largeScreens="true"
        android:xlargeScreens="true"
        android:anyDensity="true"/>

    <application android:extractNativeLibs="true"
                 android:label="@string/app_name"
                 android:icon="@mipmap/app_icon"/>
</manifest>

I'm not sure where to find gradle settings...

**Comment by Elly2018** [comment]
I solved this issue by downgrading to 2.5.1 Ultra edition.
Everything seems to work just fine. I guess it's some bug in 2.6.x ?

**Comment by Chris-RH** [comment]
If you use Android [minify options](https://developer.android.com/studio/build/shrink-code#keep-code), AVPro Video will be stripped out and will not work. The following options need to be added to your proguard configuration file (in Player Settings > Android > Publishing Settings > Build > Custom Proguard File) to prevent AVPro Video classes from being removed:

-keep class com.renderheads.AVPro.Video.** { *; }
-keep class com.google.android.exoplr2avp.** { *; }
-keep class com.twobigears.audio360.** { *; }
The above is included in /Assets/AVProVideo/Runtime/Plugins/Android/proguard-avprovideo.txt

When using Unity 2020.1 and above it has been seen that the build process overly optimises which causes issues in the ExoPlayer library. To overcome this issue, you will need to add a custom gradle property. In Player Settings|Publisher Settings, enable the Custom Gradle Properties Template option. The template is found at: /Assets/Plugins/Android/gradleTemplate.properties and it should be edited adding the following line to the end of the file: android.enableDexingArtifactTransform=false (This should have been done automatically, but you might want to check).

**Comment by Chris-RH** [comment]
closed due to lack of reply
