### ISSUE TITLE
Seek does not Seek when trying to set it on a second mediaplayer to match

### ISSUE THREAD

**Issue by iiidefektiii** [RenderHeads/UnityPlugin-AVProVideo#137]
**Describe the bug**
I have a scene with 2 media players. I have the first one set to play a video. I then try to set the second mediaplayer to match the first mediaplayer. Setting the video and playing it is working but when trying to match the play head. When I set the seek(using GetCurrentTimeMs from the first and Seek() and passing the mediaplayer1 Time in ms it will not match the fist unless it is within a coroutine and wait about 0.1 seconds. Without the coroutine it just starts mediaplayer 2 from the beginning. 

**Your Setup (please complete the following information):**
 - Unity version: 2018.3
 - AVPro Video version: 1.10.0
 - Operating system version: Windows 10
 - Device model: PC
 - Video specs (resolution, frame-rate, codec, file size): 1280x720

**To Reproduce**
1. Create new project
2. import AVpro for windows
3. create a setup where you have 2 media players and 2 UGUI each playing to a different one.
4. GetCurrentTimeMs of mediaplayer 1 and set Seek of mediaplayer 2 with result of mediaplayer 1 Time.

**Comment by AndrewRH** [comment]
Hmm..i'm not sure why that would be happening, unless perhaps you're trying to seek while the video is still loading.
We have a demo script called PlaybackSync.cs that syncs mutliple players to a master player.   Perhaps you could try that script?

Does that help?

**Comment by iiidefektiii** [comment]
Ill take a look.

**Comment by iiidefektiii** [comment]
So i was able to figure out a better way using that script to change between mediaplayers and works alot better now. Now my issues is even though I am doing something similar to the IsVideoLoaded function to determine whether it is or not, I still get a white flash (my background of the camera is white). Any tricks on waiting till the video is loaded so i dont get that quick flash?

**Comment by iiidefektiii** [comment]
Figured it out. Closing
