### ISSUE TITLE
Audio desync with HTTP progressive mp4 h264/aac playback

### ISSUE THREAD

**Issue by hiinaspace** [RenderHeads/UnityPlugin-AVProVideo#1370]
I'm trying to play back progressive mp4 h264/aac files encoded using ffmpeg with pretty vanilla settings, served over HTTP with nginx. Other players, e.g. mpv, vlc, or the native video player in Firefox/chromium can play these files fine.

However, AVPro, using MediaFoundation on Windows, in the trial demo scene with no modified AVPro settings, has a lot of trouble playing these same files, with stuttery, broken playback and audio desync. Strangely, the playback is even worse when my HTTP server is proxied through CloudFlare.

example file (straight from nginx): https://c.hiina.space/dandy01.mp4
example file (through cloudflare): https://file.hiina.space/dandy01.mp4

When I look at my nginx logs, I notice that AVPro makes a ton of very tiny HTTP Range requests for the underlying file, over 10 a second. The ranges vary but seem to be powers of 2, e.g. 8192 bytes, 16384 bytes, 32768 bytes:

```
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 458196 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 1228244 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 966100 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 196052 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 589268 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 16384 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 8192 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 24576 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 16384 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 16384 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 24576 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:17 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 24576 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:18 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 40960 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
[19/Nov/2022:17:50:18 -0700] "GET /dandy01.mp4?a HTTP/1.1" 206 146900 "-" "NSPlayer/12.00.19041.2251 WMFSDK/12.00.19041.2251"
```

Nginx does a decent job of serving those requests with a fast connection, but Cloudflare requests the entire file first and serve the range requests itself; this results in pretty bad latencies initially (up to a few seconds), which really breaks AVPro's HTTP buffering strategy.

On other mp4 files, AVPro buffers fine, with single requests or range requests to the end of the files. However, I can still reproduce the bad buffering, relatively consistently with higher bitrate/higher resolution, and slower connection speeds. And again these files play back fine in other media players, so I think it's something wrong with AVPro specifically.

Any idea what about my example files is tripping up AVPro? The obvious settings are correct, e.g. `-movflags +faststart`.

**Your Setup:**
 - Unity version: 2019.4.31f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): trial v2.6.5
 - Operating system version: Windows 10
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, h264, 2.5M maxrate

**Comment by Chris-RH** [comment]
In the Media Foundation options, have you tried enabling the "use low latency" option?
Otherwise I would try playing in DirectShow Video API

**Comment by hiinaspace** [comment]
I tried the enabling the MediaFoundation low-latency option in the trial player, and didn't see much change in buffering behavior. I still see the small powers of 2 range requests with the direct nginx serving path, and the CloudFlare-proxied version is still unplayable.

DirectShow doesn't seem to handle streaming at all, instead just requesting the entire file:

```
 [23/Nov/2022:10:41:46 -0700] "GET /dandy01.mp4?d HTTP/1.1" 200 557309885 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)"
```

if you try to scrub, the player just freezes.

**Comment by hiinaspace** [comment]
I've tried videos encoded with similar settings hosted on backblaze b2 accessed through cloudflare, which has some sort of in-datacenter peering setup. The playback is unfortunately equally as stuttery, with desynced audio. I don't have a good way to see the HTTP requests the player is making (mitmproxy would work I guess but haven't tried), but I suspect they're a similar pattern. I haven't tried CF's own video transcoding service because it's expensive.

Does AVPro control the HTTP buffering behavior at all for MediaFoundation, or does it essentially just pass in the URL? If there's some sort of VFS layer in between, I can picture a situation where MF is making power of 2 read() calls that would work fine on a local disk but result in the HTTP request spam. If there's another MediaFoundation-based video player I try to replicate the buffer behavior on, then that at least narrows the search space.

At this point I've tried a lot of different h264/aac encoding lore that's out on the internet for progressive streaming, but have yet to find a smoking gun for what causes MediaFoundation to make such tiny range requests. Which, FWIW, is a symptom rather than the disease of poor playback. If AVPro/MF made tiny requests but still kept playing the video with properly synchronized audio, I wouldn't have noticed.

**Comment by Chris-RH** [comment]
It looks like streaming videos is prohibited for basic Cloudflare accounts, unless its a proper paid Stream account.
https://www.cloudflare.com/terms/ section 2.8  So they may be throttling it if they see more traffic than they would expect for just HTML.

**Comment by hiinaspace** [comment]
Okay, but proxied videos play back fine on other video players, so I doubt they're doing any specific throttling.

To remove CF from the equation here, I added this block to my nginx config to throttle the response byte rate based on query parameter:

```
     if ($arg_slow) {
        limit_rate $arg_slow;
     }
```

e.g. https://c.hiina.space/dandy01.mp4?slow=400k is limited to 400kBps. This also plays back fine in firefox, albeit with some buffering pauses. In the avpro trial demo scene, that same url plays back ok, but the audio desyncs and remains ~1 second ahead of the (stuttery) video playback. The buffering pauses are noticeably longer too.

FWIW I also found https://github.com/microsoft/media-foundation which has sample MediaFoundation players. changing https://github.com/microsoft/media-foundation/blob/master/samples/MediaEngineUWPSample/src/App.cpp#L18 to my url and running, it also plays back fine. Some buffering delays, but audio remains synchronized throughout. MediaFoundation does make the same small power-of-two range requests. So avpro is likely just passthrough there.

For completeness, I tried switching the AVPro windows audio output from "Unity" to "System Direct". However, the audio still desyncs from the video playback, worse than the MediaFoundation sample. Maybe a bit better than the unity audio output path, but hard to tell.

Since the buffering behavior is just MediaFoundation (and might not be configurable), the actual issue here is AVPro's audio desync if the underlying media stream has buffering pauses for any reason (bandwidth throttling, CF throttling, etc). I'll change the issue description to reflect that.

And thus, is there any configuration in AVPro that can fix the audio desync? I'll keep trying to find encoding settings that are more paletable wrt buffering, but again, these are videos that work fine in other media players (including MediaFoundation sample). So this is AVPro's problem.

**Comment by Chris-RH** [comment]
It plays fine on my PC using DirectShow in the editor.

Have you tried the video from a completely different server?

How do you find these test streams are playing?
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#test-streams

**Comment by Chris-RH** [comment]
Closed due to lack of reply
