### ISSUE TITLE
FantasyStereoFB360.mkv and HansVoice_FB360_H264_Opus.mkv not playing

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#1372]
**Describe the issue**
Trying to play FantasyStereoFB360.mkv and HansVoice_FB360_H264_Opus.mkv results in:
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.12f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.6 Ultra
 - Operating system version: Windows 10 x64
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Create a new project, open the AVProVideo Demo_360Stereo scene
2. Copy the FantasyStereoFB360.mkv or HansVoice_FB360_H264_Opus to the StreamingAssets folder and create a MediaReference for it
3. Assign the MediaReference to the MediaPlayer, set Windows Audio Output to Facebook Audio 360, Channel Mode to TBE_8_2 and click Load
4. Same error occurs when trying to play these files in Windows and Android builds.

**Logs**
[AVProVideo] Initialising AVPro Video v2.6.5 (native plugin v2.6.3f1-ultra) on Emulated GPU running OpenGL ES 3.0/OpenGL ES 3.0 [emulated] (MT True) on WindowsEditor
[AVProVideo] Opening D:/Dev/Unity Projects/Test-AVPro-01/Assets/StreamingAssets\AVProVideoSamples/FantasyStereoFB360.mkv (offset 0) with API MediaFoundation
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by Chris-RH** [comment]
Hi @RuudvanReenen,

Try DirectShow or WinRT Video API for Windows

**Comment by RuudvanReenen** [comment]
Thanks! DirectShow and WinRT play the file indeed, but there's no audio.
Windows Audio Output is set to Facebook Audio 360 and Channel Mode is set to TBE_8_2.

I'm using these files to try to get ambisonic sounds to work.

**Comment by RuudvanReenen** [comment]
Fixed by removing a leftover Audio360.dll in the Assets\Plugins\x64 from an earlier version of AVPro Video and then reimporting the latest version of AVPro Video.
