### ISSUE TITLE
Plugin functions (.jar and .aar)

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1374]
Problem description:

I am a little confused as to how the aar files and jar files are being used in this project. I can see the dlls and so files being imported with dllimport, but can't seem to find the aar and jar functions. I wanted to include some more functions from the library but want to make sure I am looking in the right project for reference.
I have cross referenced some of the functions in exoplayer, but they do not seem to link up. Can someone point me in the right direction?

Device (which devices are you having the issue with - model, OS version number):

Quest 2 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

I am running this application on Android for the Quest 2.

System Information:

AVPro Video: v2.6.6 (plugin v2.6.3f1-ultra)
Target Platform: Android
Unity: v2021.3.8f1 WindowsEditor
OS: Desktop - B550M DS3H AC (Gigabyte Technology Co., Ltd.) - Windows 11  (10.0.22621) 64bit - English
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 threads - 32691KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10067KB - 16384

**Comment by Ste-RH** [comment]
I am afraid I do not understand what you are asking here.

You should not be concerned with the plugin files and their internals.  Every functionality you require is accessibly via the c# layer in Unity.

**Comment by Gurwar** [comment]
@Ste-RH The project that I am working on requires additional functions from exoplayer (open media from buffer for example). Could you give me a hand to locate existing functions that have been imported into AVPro so I can import the new ones I'll need as well?

**Comment by Ste-RH** [comment]
Our asset does not work like that.  Only a finite feature set exists, is supported.

What is the feature you are requiring?  Playing back a video held in memory?  If so, that is something on our list of enhancements.  Unfortunately at this time, however, I am afraid we cannot commit to a date for it's inclusion.

**Comment by Gurwar** [comment]
Is it possible to get access to a version of AV Pro that might have this feature available? My team is interested in using this feature on Android as well as using it on MediaFoundation on Windows.

By the way, the package I was looking for was com.renderheads.AVPro.Video.Manager.
