### ISSUE TITLE
iOS Build Crash  | AVPro Ultra Edition

### ISSUE THREAD

**Issue by RojanStha** [RenderHeads/UnityPlugin-AVProVideo#1375]
**Describe the issue**
I have integrated the AVPro build on  the native IOS application and when i build the application on device the application is crashing and showing some error.

 - Unity version: 2021.3.9f1
 - AVPro Video version : 2.6.6 (Ultra Edition)
 - Operating system version: Mac OS Ventura
 - Xcode Version: 14.0
 - IOS Version :16.0

i have tried the : 
- Always Embed Swift Standard Libraries -> Yes
- AVProVideo.framework -> Embed & Sign
- Updated the latest AVPro Version and Rebuild the Application

****Log***
Library not loaded: @rpath/AVProVideo.framework/AVProVideo
  Referenced from: <1B2DB347-505F-35C1-B1D1-CD95C9ADA52F> /private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/AVProVideo.framework/AVProVideo' (errno=2), '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/UnityFramework.framework/Frameworks/AVProVideo.framework/AVProVideo' (errno=2), '/usr/lib/swift/AVProVideo.framework/AVProVideo' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AVProVideo.framework/AVProVideo' (errno=2), '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/AVProVideo.framework/AVProVideo' (errno=2), '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B261815285
dyld config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libBacktraceRecording.dylib:/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by Chris-RH** [comment]
closed due to lack of response, please reopen if this is still an issue

**Comment by RojanStha** [comment]
i followed same as https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/869 this issue but now working, there is no AVProFramework is showing on my native application target. please let me know my unity version is:2021.3.9f and Xcode version is:14.0 mac os:13.0.1
