### ISSUE TITLE
exoplr2avp.PlaybackException required for desugaring of try-with-resources is not found.

### ISSUE THREAD

**Issue by nightyan** [RenderHeads/UnityPlugin-AVProVideo#1376]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I got next build error. But success with google's exoplayer(form https://github.com/google/ExoPlayer.git) replace avpro's exoplayer.

> Transform artifact exoplayer-core-.aar (:exoplayer-core:) with DexingWithClasspathTransform
C:\Users\xxx\.gradle\caches\transforms-2\files-2.1\6253deaed2132f36ca157069f4fe9463\jetified-exoplayer-core-runtime.jar: D8: com.android.tools.r8.errors.b: Class or interface com.google.android.exoplr2avp.PlaybackException required for desugaring of try-with-resources is not found.

> Task :mergeDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeDexDebug'.
> Could not resolve all files for configuration ':debugRuntimeClasspath'.
   > Failed to transform exoplayer-core-.aar (:exoplayer-core:) to match attributes {artifactType=android-dex, dexing-enable-desugaring=true, dexing-incremental-desugaring-v2=false, dexing-is-debuggable=true, dexing-min-sdk=17, org.gradle.status=integration, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: C:\Users\xxx\.gradle\caches\transforms-2\files-2.1\6253deaed2132f36ca157069f4fe9463\jetified-exoplayer-core-runtime.jar.
         > Error while dexing.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.35f1
 - AVPro Video version (2.6.6 and edition (core)): 
 - Operating system version: 
 - Device model: android
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
I do not quite understand.

Replacing the version of ExoPlayer that comes with AVPro Video will not work as we change the package name to avoid conflicts with other assets using ExoPlayer. Is that what you are doing to get the error? If not, and you are getting it with the asset files provided in the AVPro Video package…can you produce the issue in a new project?
