### ISSUE TITLE
Android OES Error

### ISSUE THREAD

**Issue by JuanObiJuan** [RenderHeads/UnityPlugin-AVProVideo#1377]
**Describe the issue**
The MediaPLayer gives an error when I try to use Android OES

![image](https://user-images.githubusercontent.com/1729541/203763089-7c43fc21-4d46-461e-a59b-cc999593c404.png)

And the configuration is already in multipass for android and desktop (oculus link)

![image](https://user-images.githubusercontent.com/1729541/203763478-8c10b0c7-db8b-4137-81dd-e24ba3f50ed1.png)

![image](https://user-images.githubusercontent.com/1729541/203763684-24b1fec2-7256-4188-b698-4af7921061f0.png)

Setup:
 - Unity version: 2020.3.41f1 LTS
 - AVPro Video: v2.6.5 (plugin v2.6.3f1-ultra) 
 - Operating system version: Windows 10
 - Device model: Oculus Quest 2

**To Reproduce**
1. Set Multipass render
2. Enable OES

**Comment by Chris-RH** [comment]
Have you added the Update Multipass Stereo component?
https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html
Have you selected the correct shaders?
https://www.renderheads.com/content/docs/AVProVideo/articles/usage-shaders.html

**Comment by JuanObiJuan** [comment]
Yes:
- I added the compoent to the center Eye camera 
- Im using a material withthe shader AVProVideo/VR/InsideSphereUnlit(stereo+color) - Android OES ONLY

**Comment by Chris-RH** [comment]
Your multi-pass settings seem to be in the windows tab, not the android tab

**Comment by Chris-RH** [comment]
Did that help?

**Comment by Chris-RH** [comment]
closed due to lack of response
