### ISSUE TITLE
Update Multi-Pass Stereo script on OVRCameraRig and different scenes

### ISSUE THREAD

**Issue by JuanObiJuan** [RenderHeads/UnityPlugin-AVProVideo#1378]
I have the default OVRCameraRig form the oculus integration and the documentation says I should put the UPdate Multi-Pass Stereo script on the camera. And I have a couple of questions.

- This Rig is made with three cameras, Left, Center and Righ Eye. Should I put the script on the center Eye?

- Is there a problem if the camera and the rest of the components (mediaplayer, sphere, ... ) are loaded addinially in a separate scene? LIke you see in this screenshot:

![image](https://user-images.githubusercontent.com/1729541/203766260-ab845b8f-869c-4992-844b-49fb9057d67a.png)

**Comment by Chris-RH** [comment]
It should go on the CentralEyeAnchor
