### ISSUE TITLE
More specific Error message

### ISSUE THREAD

**Issue by JuanObiJuan** [RenderHeads/UnityPlugin-AVProVideo#1379]
When the video fails the message is:
[AVProVideo] Error: Loading failed, FIle not found, codec not supported, video resolution too high or insufficient system resources.

It would help me a lot not to put all cases in the same error and to know a bit more, why.

I can image that some cases are harder to identify, specially with external players but at least, "file not found" can be checked and it would help us a bit more.

Regarding the others, it would be amazing to know when the codec is not suported or when there are not enough resources separetly.

Amazing Player!

**Comment by Chris-RH** [comment]
We don't get enough specific feedback from the Video APIs to be able to give a more helpful error report I'm afraid. 

If there is a specific video/device that you are having issues with, please let us know.
