### ISSUE TITLE
Multiple HAP video with uncompressed audio plays slow and distorted

### ISSUE THREAD

**Issue by jeroenvandervelden** [RenderHeads/UnityPlugin-AVProVideo#138]
**Describe the bug**
Playback multiple HAP movies containing uncompressed audio gives slow down of movie playback and gives distorted sound. The more HAP movies containing uncompressed audio I start, the more all playback slows down and audio distorts. Unity FPS does NOT drop, performance is no issue. 
In UnityEditor, the MediaPlayer Component displays a smooth but very slowed down playback position in the Preview Pane (so the native playback engine actually slows down).

Strange 1: When encoding the HAP movie using MPEG_Streamclip on Mac, there's no problem. When using FFMPEG / AfterCodecs / Disguise-Adobe-HAP plugin, it gives the problems.

Strange 2: Using for example AAC as audio codec solves it.

NOTE: Uncompressed wav TWOS or SOWT difference between FFMPEG and MPEG_Streamclip encoded file is not the problem, manually replacing SOWT audio stream in ffmpeg by TWOS (make it same as MPEG_Streamclip) doesn't solve it.

**Your Setup (please complete the following information):**
 - Unity 2019.1/2019.2
 - AVPro Video 1.10.0 (and previous versions)
 - Windows 10 v1809 and v1903
 - Razer Blade RTX2070 2019 / i7 8750h / Realtek Audio
   OR
 - Windows 10 desktop machine / i5 / GTX1070
 - Video specs: 1920 x 1080 @ 50 / 3840 x 2160 @ 50 / .... all in .mov HAP

**To Reproduce**
1. Encode video containing audio using AfterCodecs or FFMPEG or Disguise-Adobe-HAP plugin to .mov HAP with uncompressed audio codec
2. Modify "05_Demo_Multiple" example to set videoAPI to DirectShow
3. Run the example, "Add Video" multiple times

**Videos**
Screengrab video explaining the problem:
https://drive.google.com/open?id=1muXbRX4muZGE6YdbGfvKIeRSPD4GLiLG
Source video **hap_ffmpeg_problem.mov**
https://drive.google.com/open?id=1ujEMZrE-4V-0rs9msGfDG89Fyt6LNh8Y
Source video **hap_mpegstreamclip_okay**
https://drive.google.com/open?id=19esLVrXNheI4KIkyZurKQAyVRp_mbxOt

**Comment by AndrewRH** [comment]
Thanks for reporting this.  This is a very strange one indeed....Good to have it documented at least.  I'll see about replicating it.

**Comment by n1ckfg** [comment]
I can replicate this on Windows 1809 and Unity 2018.4.8, trying Hap encoding with both AfterCodecs and Zeranoe ffmpeg. PCM audio has heavy distortion, AAC audio does not. I can also offer something interesting--I'm testing this project on two PCs, one with AMD CPU, one with Intel CPU. Only the AMD exhibits the crackling problem with PCM audio--the Intel is OK with either PCM or AAC.

**Comment by jeroenvandervelden** [comment]
That's odd.. My systems are all intel..

**Comment by AndrewRH** [comment]
@n1ckfg if you encode to AVI instead of MOV does that make any difference?

It's good to know about these issues - hopefully most people can use AAC as a workaround...

**Comment by n1ckfg** [comment]
I seem to recall encoding Hap AVIs before, but I forget with what tool--I'm using AfterCodecs and ffmpeg, and I think both of them only do MOVs. Yup, encoding ffmpeg with AAC is my workaround for now.

**Comment by n1ckfg** [comment]
Update, have now encountered the PCM issue on an Intel machine now, a quad i5 6500...so it's not an AMD thing specifically.
