### ISSUE TITLE
execution error on android

### ISSUE THREAD

**Issue by showstop** [RenderHeads/UnityPlugin-AVProVideo#1380]
Problem description:

they say libAVProVideo2Native.so file not found error.

2022/11/26 13:43:11.511 31975 29333 Error Unity AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libAVProVideo2Native.so" not found

Device (which devices are you having the issue with - model, OS version number):

sa,sung SM-N986N (version 11.0)

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

https://media-out.vogoplay.com/vod-origin/mp4:291_1609325986707.mp4/playlist.m3u8

System Information:

AVPro Video: v2.4.1 (plugin vUnknown)
Target Platform: Android
Unity: v2020.3.26f1 OSXEditor
OS: Desktop - MacBookPro18,2 - Mac OS X 13.0.1 - English
CPU: Apple M1 Max - 10 threads - 32768KB
GPU: Apple M1 Max - Apple - Metal - 21845KB - 16384

**Comment by Chris-RH** [comment]
Version 2.4.1 is 9 months old, please can you update to the latest version 2.6.6

**Comment by Chris-RH** [comment]
Closed due to lack of response
