### ISSUE TITLE
How to get the name of the video being played

### ISSUE THREAD

**Issue by sunjunjie1104** [RenderHeads/UnityPlugin-AVProVideo#1383]
How to get the name of the video being played

**Comment by Chris-RH** [comment]
GetActiveVideoTrack().DisplayName

https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.BaseMediaPlayer.html#RenderHeads_Media_AVProVideo_BaseMediaPlayer_GetActiveVideoTrack

**Comment by sunjunjie1104** [comment]
> GetActiveVideoTrack().DisplayName
> 
> https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.BaseMediaPlayer.html#RenderHeads_Media_AVProVideo_BaseMediaPlayer_GetActiveVideoTrack



> GetActiveVideoTrack().DisplayName
> 
> https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.BaseMediaPlayer.html#RenderHeads_Media_AVProVideo_BaseMediaPlayer_GetActiveVideoTrack

GetComponent<MediaPlayer>().GetActiveVideoTrack().DisplayName    Prompt error!!! what is wrong with me?

**Comment by Chris-RH** [comment]
What error are you receiving? Which platform are you using?

**Comment by MorrisRH** [comment]
Track information won't be available until after the media has been loaded. You can use ReadyToPlay or FirstFrameReady events to signal when the media is ready to be interrogated. For example:
```csharp
public class Example : MonoBehaviour
{
	public MediaPlayer _mediaPlayer;

	private void OnMediaPlayerEvent(MediaPlayer mediaPlayer, MediaPlayerEvent.EventType eventType, ErrorCode errorCode)
	{
		switch (eventType)
		{
			case MediaPlayerEvent.EventType.FirstFrameReady:
				string name = GetComponent<MediaPlayer>().VideoTracks.GetActiveVideoTrack().DisplayName;	
				Debug.Log("video track name is " + name);
				break;
			default:
				break;
		}
	}

	void Start()
	{
		if (_mediaPlayer == null)
		{
			_mediaPlayer = GetComponent<MediaPlayer>();
		}
		if (_mediaPlayer == null)
		{
			return;
		}

		_mediaPlayer.Events.AddListener(OnMediaPlayerEvent);
		_mediaPlayer.OpenMedia(new MediaPath("file:///path/to/media.mp4", MediaPathType.AbsolutePathOrURL));
	}
}
```

**Comment by sunjunjie1104** [comment]
Thank you for your patience to answer, after I use your method, what is printed out is not the name of the video but (Track 0 (en)
UnityEngine.MonoBehaviour:print (object))
