### ISSUE TITLE
AVPro Video - Core Android Edition - Watermark problem

### ISSUE THREAD

**Issue by ichaparro** [RenderHeads/UnityPlugin-AVProVideo#1384]
Hi.
I write to you, in order to get your support.

I've have been testing your trial unity package to view 360 and 180 videos with the watermark of course, but yesterday night I finally decided to purchase for you product and I got  the "AVPro Video - Core Android Edition", but when I import again the new purchased package, "watermark" and "Purchase" option into the "AVPro Video - Media Player" GameObjet continuous appearing.

For your information I'm working with Unity 2021.3 in Windows 11 and I play my project using Steam.

Finally, like I spent 200€ on this package, I'm very worried about it.
- Maybe I got the wrong package version?
- Maybe I should use the "AVPro Video - Core windows Edition"?
- or "AVPro Video - Core Core Edition"?
- If I make a mistake with the version, is there any option to refund money to get the correct version?

![AVPro Watermark problem](https://user-images.githubusercontent.com/1534333/204515583-41a1bb0f-d08f-48cf-834a-dd9b2875abf4.png)
I will be waiting for your reply asap.
So thanks very much guys for your time and support.

Regards.

**Comment by Chris-RH** [comment]
I've responded to your email :)
