### ISSUE TITLE
Watermarked plugin

### ISSUE THREAD

**Issue by vandershop** [RenderHeads/UnityPlugin-AVProVideo#1385]
Hi, 

I've bought a core android and ios plugin version from the asset store.

But when I import both from the package manager, I see the box of trial watermarked in the video player settings.

How I can solve it ?

There is a way to edit the material of play pause button with one with rounded border ?

**Comment by Chris-RH** [comment]
If you use one of the platform specific Core editions (eg AVPro Video - Core Windows Edition) then you will not see the watermark on the platform you purchased for, but you will see the watermark on the other platforms. 
For example if you purchased AVPro Video - Core Android Edition then you will still see the watermark in the Unity editor as this is running on Windows/macOS, but the videos played back when you deploy to your Android device will be watermark-free.

**Comment by vandershop** [comment]
yes i've switched between android and ios, but in the side column I steel see the watermark banner and in the player too. I tried with an empty project too.

What about material components ?

**Comment by Chris-RH** [comment]
So you if you run just the demo mediaplayer scene and you build it on an apk for your android device, you are still seeing the watermark over the video on your android device?

**Comment by vandershop** [comment]
now reimporting the plugin and building it is working fine.

About the materials i would like only to male borders round to play and pause is  it possible ?

**Comment by Chris-RH** [comment]
Its up to you to create your own buttons. There are plenty of Unity tutorials around :)
