### ISSUE TITLE
android hls play crash

### ISSUE THREAD

**Issue by ogurishun** [RenderHeads/UnityPlugin-AVProVideo#1386]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.21
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): ULTRA EDITION
 - Operating system version: android 11
 - Device model: sony xperia 1...
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. play hls crash

**Logs**
11-30 23:19:25.025  7157  7299 E CrashReport: # CRASH STACK: 
11-30 23:19:25.025  7157  7299 E CrashReport: java.lang.AbstractMethodError: abstract method "void com.google.android.exoplr2avp.extractor.TrackOutput.sampleData(com.google.android.exoplr2avp.util.ParsableByteArray, int)"
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.extractor.ts.H264Reader.consume(H264Reader.java:130)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.extractor.ts.PesReader.consume(PesReader.java:144)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.extractor.ts.TsExtractor.read(TsExtractor.java:386)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:473)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:412)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-30 23:19:25.025  7157  7299 E CrashReport: 	at java.lang.Thread.run(Thread.java:818)

**Comment by Ste-RH** [comment]
Most likely the same as #580

**Comment by ogurishun** [comment]
The problem has been solved. Thank you very much，十分感谢
