### ISSUE TITLE
Rotate 360 video sphere with ambisonic audio

### ISSUE THREAD

**Issue by JuanObiJuan** [RenderHeads/UnityPlugin-AVProVideo#1387]
Hi renderheads. 

Im a ultra plugin user and in the project Im working we are planing to play 360 steroscopic videos with embeded (muxed) ambisonic audio on oculus quest. As far as I now there is nothing I need to do extra to make everything play if those are in the right format, the question comes now about redirectioning the forward direction of the video. We want to rotate the sphere in Y axis to correct the forward direction but what can I do to rotate the also the audio drirectionality playing from the ambisonic video?

**Comment by JuanObiJuan** [comment]
I realise now that the recomended audio format is facebook audio TBE but the main question remains the same.

**Comment by Chris-RH** [comment]
The settings are located under the Audio section of the MediaPlayer component. The “Head Transform” field must be set to the transform that represents the player's head so that rotation and positional changes affect the audio rendering. Usually this is the main camera.
