### ISSUE TITLE
Open HAP video file results in CPU spike

### ISSUE THREAD

**Issue by jeroenvandervelden** [RenderHeads/UnityPlugin-AVProVideo#139]
**Describe the bug**
Opening a video file creates a CPU spike, visible in other currently rurning videos in the scene or any running Unity realtime animations.

The "Native.OpenSource()" call in WindowsMediaPlayer.OpenVideoFromFile() creates the high CPU spike.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1 / 2019.2
 - AVPro Video version: 1.10.0
 - Operating system version: Windows 10 64-bit
 - Device model: Razer Blade RTX2070 2019
 - Video specs (resolution, frame-rate, codec, file size): .mov HAP 3840x2160p60 or 1920x1080p50 or comparable

**To Reproduce**
1. Open 05_Demo_Multiple
2. Change SampleApp to create new MediaPlayers with videoAPI as DirectShow
3. Change SampleApp video-path to a HAP file
4. Run example and add several videos after each-other

**Screenshots**
Screenshot of Profiler including the traced down 'guilty' function:
![AVProVideo_OpenSource_CPUspike](https://user-images.githubusercontent.com/6519131/62466478-b1a48180-b791-11e9-9c30-872d87bf824c.png)

**Comment by AndrewRH** [comment]
Hi Jeroen, thanks for reporting these two issues.
This one is because our DirectShow code just runs on the main thread, so loading blocks the thread.  We can either move all of the processing to a second thread, or actually add Hap support for Media Foundation.  I think we're hoping to do the second one, but I'm not sure when we'll get to it.  I'm going to change this from a bug to an enhancement.

**Comment by jeroenvandervelden** [comment]
Hi @AndrewRH, any news on solution 2 - adding HAP to MediaFoundation?

**Comment by fingerx** [comment]
Hi @AndrewRH, any news on solution 2 - adding HAP to MediaFoundation?

**Comment by yMiecie** [comment]
Hi @AndrewRH , We are facing the same issue. Any news on solution 2 - adding HAP to MediaFoundation?

**Comment by AndrewRH** [comment]
Yes AVPro Video 2.0 will feature Hap support via Media Foundation, which will get rid the spike during loading, and should give better playback performance too

**Comment by fingerx** [comment]
hello, i have same issue. i want to know avpro video 2.0 released time@AndrewRH

**Comment by AndrewRH** [comment]
This is now ready in 2.0 which will be released soon
