### ISSUE TITLE
AVPro MediaPlayer Preview causes Unity Editor to hang when using HDRP and DX12

### ISSUE THREAD

**Issue by rainbow-milk** [RenderHeads/UnityPlugin-AVProVideo#1390]
**Issue**
When adding a AVPro Media Player component to a gameObject and loading media to play - Unity Editor hangs on Toolbar.paint.  

**Setup**
 - Unity version: present in 2022.1.3f and 2022.1.23f
 - RenderPipeline : HDRP + DX12
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  Enterprise - found in 5.2.5, repros in 2.6.6
 - Operating system version: Windows 10
 - Device model: repros on multiple Dev windows workstations.
 - Video specs (resolution, frame-rate, codec, file size):  - so far any video tested. .mov+ mp4
 - NOTE:  Second AVPro log message below says media not supported or too large BUT video being loaded IS supported / plays in other AVPro scenarios. 

**To Reproduce**
1. Open Unity and Create new Scene.
2. Add empty game object to Scene.
3. Add AVPro Media Player component to GameObject. 
4. Use file browser icon below preview area to select a file. 
5. Press Play for media Playback preview in the inspector window.

Expected Result: Media file begins preview playback in inspector window.
Result:  Unity Editor Hangs Indefinitely.

**Logs**
Error Logs from Loading Video file: 
[AVProVideo] Opening C:/Users/obscura/Desktop/PortaslQA_H265_FED180.mov (offset 0) with API MediaFoundation
0x00007ff6727bf9fd (Unity) StackWalker::GetCurrentCallstack
0x00007ff6727c66f9 (Unity) StackWalker::ShowCallstack
0x00007ff673761943 (Unity) GetStacktrace
0x00007ff673e17ea3 (Unity) DebugStringToFile
0x00007ff671899966 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000001254c3c83f3 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x000001254c3c830b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x000001254c40a091 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object,UnityEngine.Object)
0x000001254c409f6d (Mono JIT Code) UnityEngine.Debug:Log (object,UnityEngine.Object)
0x0000012550fe9fb3 (Mono JIT Code) [Helper.cs:189] RenderHeads.Media.AVProVideo.Helper:LogInfo (string,UnityEngine.Object) 
0x0000012550fea723 (Mono JIT Code) [MediaPlayer.cs:582] RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia () 
0x0000012550fe79bb (Mono JIT Code) [MediaPlayer.cs:509] RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) 
0x0000012550fe794b (Mono JIT Code) [MediaPlayer.cs:488] RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (RenderHeads.Media.AVProVideo.MediaPathType,string,bool) 
0x0000012550fe78cb (Mono JIT Code) [MediaPlayer.cs:479] RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (RenderHeads.Media.AVProVideo.MediaPath,bool) 
0x0000012550fe6403 (Mono JIT Code) [RecentMenu.cs:153] RenderHeads.Media.AVProVideo.Editor.RecentMenu:Callback_Browse (object) 
0x000001254dd43823 (Mono JIT Code) UnityEditor.GenericMenu:CatchMenu (object,string[],int)
0x000001254dd4370e (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void__this___object_object_int (object,intptr,intptr,intptr)
0x00007ffec30f0384 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ffec302eb34 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ffec302eccc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff6726e3f14 (Unity) scripting_method_invoke
0x00007ff6726c3864 (Unity) ScriptingInvocation::Invoke
0x00007ff67319150d (Unity) CustomPopupMenuInterface::Execute
0x00007ff673118143 (Unity) MenuController::ExecuteMenuItem
0x00007ff673781194 (Unity) ShowDelayedContextMenu
0x00007ff673791f1e (Unity) GUIView::OnInputEvent
0x00007ff6731d10c5 (Unity) GUIView::ProcessInputEvent
0x00007ff67378ab9d (Unity) GUIView::DoPaint
0x00007ff673793fcc (Unity) GUIView::RepaintAll
0x00007ff673300c6a (Unity) Application::TickTimer
0x00007ff67376759a (Unity) MainMessageLoop
0x00007ff67376c3b4 (Unity) WinMain
0x00007ff674ae448e (Unity) __scrt_common_main_seh
0x00007fff508c7974 (KERNEL32) BaseThreadInitThunk
0x00007fff5266a371 (ntdll) RtlUserThreadStart

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
0x00007ff6727bf9fd (Unity) StackWalker::GetCurrentCallstack
0x00007ff6727c66f9 (Unity) StackWalker::ShowCallstack
0x00007ff673761943 (Unity) GetStacktrace
0x00007ff673e17ea3 (Unity) DebugStringToFile
0x00007ff671899966 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000001254c3c83f3 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x000001254c3c830b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x000001254c3c8050 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x00000125414ba505 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x00000125414b266b (Mono JIT Code) [MediaPlayer.cs:1413] RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () 
0x0000012550fbaab3 (Mono JIT Code) [MediaPlayer.cs:828] RenderHeads.Media.AVProVideo.MediaPlayer:Update () 
0x0000012550fbe29b (Mono JIT Code) [MediaPlayer.cs:784] RenderHeads.Media.AVProVideo.MediaPlayer:EditorUpdate () 
0x0000012550fbde9b (Mono JIT Code) [MediaPlayerEditor.cs:373] RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI () 
0x000001254dde3114 (Mono JIT Code) UnityEditor.UIElements.InspectorElement/<>c__DisplayClass62_0:<CreateIMGUIInspectorFromEditor>b__0 ()
0x000001219c759c5f (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool)
0x000001219c758f5b (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:DoMeasure (single,UnityEngine.UIElements.VisualElement/MeasureMode,single,UnityEngine.UIElements.VisualElement/MeasureMode)
0x000001219c73fc86 (Mono JIT Code) UnityEngine.UIElements.VisualElement:Measure (UnityEngine.Yoga.YogaNode,single,UnityEngine.Yoga.YogaMeasureMode,single,UnityEngine.Yoga.YogaMeasureMode)
0x000001219c73f993 (Mono JIT Code) UnityEngine.UIElements.VisualElement:<AssignMeasureFunction>b__259_0 (UnityEngine.Yoga.YogaNode,single,UnityEngine.Yoga.YogaMeasureMode,single,UnityEngine.Yoga.YogaMeasureMode)
0x000001219c73fa7b (Mono JIT Code) (wrapper delegate-invoke) <Module>:invoke_YogaSize_YogaNode_single_YogaMeasureMode_single_YogaMeasureMode (UnityEngine.Yoga.YogaNode,single,UnityEngine.Yoga.YogaMeasureMode,single,UnityEngine.Yoga.YogaMeasureMode)
0x000001219c73f890 (Mono JIT Code) UnityEngine.Yoga.YogaNode:MeasureInternal (UnityEngine.Yoga.YogaNode,single,UnityEngine.Yoga.YogaMeasureMode,single,UnityEngine.Yoga.YogaMeasureMode)
0x000001219c73f5eb (Mono JIT Code) UnityEngine.Yoga.Native:YGNodeMeasureInvoke (UnityEngine.Yoga.YogaNode,single,UnityEngine.Yoga.YogaMeasureMode,single,UnityEngine.Yoga.YogaMeasureMode,intptr)
0x000001219c73f6ff (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_single_int_single_int_intptr (object,intptr,intptr,intptr)
0x00007ffec30f0384 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ffec302eb34 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ffec302eccc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff6726e3f14 (Unity) scripting_method_invoke
0x00007ff6726c3864 (Unity) ScriptingInvocation::Invoke
0x00007ff6726be485 (Unity) ScriptingInvocation::Invoke<void>
0x00007ff6727e5afe (Unity) Scripting::UnityEngine::Yoga::NativeProxy::YgNodeMeasureInvoke
0x00007ff672d0ca7e (Unity) YogaCallback::YogaMeasureWrapper
0x00007ff672d22aeb (Unity) YGNodeWithMeasureFuncSetMeasuredDimensions
0x00007ff672d22e0d (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d20e0d (Unity) YGNodeComputeFlexBasisForChild
0x00007ff672d236ee (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d20e0d (Unity) YGNodeComputeFlexBasisForChild
0x00007ff672d236ee (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d20e0d (Unity) YGNodeComputeFlexBasisForChild
0x00007ff672d236ee (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d20e0d (Unity) YGNodeComputeFlexBasisForChild
0x00007ff672d236ee (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d20e0d (Unity) YGNodeComputeFlexBasisForChild
0x00007ff672d236ee (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d256e5 (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d256e5 (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d256e5 (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d256e5 (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d20370 (Unity) YGNodeAbsoluteLayoutChild
0x00007ff672d26799 (Unity) YGNodelayoutImpl
0x00007ff672d1fc09 (Unity) YGLayoutNodeInternal
0x00007ff672d27ba4 (Unity) YGNodeCalculateLayout
0x00007ff671abfe2e (Unity) Native_CUSTOM_YGNodeCalculateLayout
0x000001219c73f4ca (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Yoga.Native:YGNodeCalculateLayout (intptr,single,single,UnityEngine.Yoga.YogaDirection)
0x000001219c73f263 (Mono JIT Code) UnityEngine.Yoga.YogaNode:CalculateLayout (single,single)
0x000001219c73edc3 (Mono JIT Code) UnityEngine.UIElements.UIRLayoutUpdater:Update ()
0x00000124d10775fe (Mono JIT Code) UnityEngine.UIElements.VisualTreeUpdater:UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase)
0x00000124d10774cb (Mono JIT Code) UnityEngine.UIElements.Panel:UpdateForRepaint ()
0x00000124d107586b (Mono JIT Code) UnityEngine.UIElements.Panel:Repaint (UnityEngine.Event)
0x00000124d10749dc (Mono JIT Code) UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel)
0x00000124d1074683 (Mono JIT Code) UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&)
0x00000124d107443f (Mono JIT Code) UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr)
0x00000124d107435b (Mono JIT Code) UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr)
0x00000124d10741bd (Mono JIT Code) UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
0x00000124d1074276 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_int_intptr_intptr& (object,intptr,intptr,intptr)
0x00007ffec30f0384 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ffec302eb34 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ffec302eccc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff6726e3f14 (Unity) scripting_method_invoke
0x00007ff6726c3864 (Unity) ScriptingInvocation::Invoke
0x00007ff6726be485 (Unity) ScriptingInvocation::Invoke<void>
0x00007ff6728096ba (Unity) Scripting::UnityEngine::GUIUtilityProxy::ProcessEvent
0x00007ff6731d12b8 (Unity) GUIView::ProcessRetainedMode
0x00007ff673791ff3 (Unity) GUIView::OnInputEvent
0x00007ff6731d10c5 (Unity) GUIView::ProcessInputEvent
0x00007ff67378ab9d (Unity) GUIView::DoPaint
0x00007ff673793fcc (Unity) GUIView::RepaintAll
0x00007ff673302c8e (Unity) PlayerLoopController::UpdateScene
0x00007ff673300bf2 (Unity) Application::TickTimer
0x00007ff67376759a (Unity) MainMessageLoop
0x00007ff67376c3b4 (Unity) WinMain
0x00007ff674ae448e (Unity) __scrt_common_main_seh
0x00007fff508c7974 (KERNEL32) BaseThreadInitThunk
0x00007fff5266a371 (ntdll) RtlUserThreadStart

**Screenshots**
![image](https://user-images.githubusercontent.com/28524536/205748850-b0056428-a4bc-40af-836f-9f6f61551e57.png)
Unity Paint  Message that Hangs indefinitely.

**Comment by Chris-RH** [comment]
What are the specs of videos that you are testing? resolution, frame-rate, codec, file size

**Comment by rainbow-milk** [comment]
@Chris-RH after further testing it seems the problem is possibly related to HDRP + DX12.   When the blank 3d template from unity is used to create the empty project the media player doesnt hang,  when the project gets upgraded to use the HDRP and DX12 the media play causes unity to hang

**Comment by Chris-RH** [comment]
Thank you for the added information, we are looking into this.

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this has not fixed the issue for you.
