### ISSUE TITLE
Opening the Menu on VR Devices causes disabled Media Players to play Media on App resume

### ISSUE THREAD

**Issue by ChrisBool** [RenderHeads/UnityPlugin-AVProVideo#1391]
**Describe the issue**

When the MediaPlayer is disabled and "PlayMediaOnAppUnpause" set to false, pausing and resuming the App in VR devices in a specific way causes audio files to resume playing anyways. The "MediaPlayer.Control.IsPlaying" also returns false, despite the audio playing.

**Your Setup (please complete the following information):**
 - Unity version: Tested in 2021.2.7f1 and 2021.2.19f1
 - AVPro Video version: Occured with 2.6.4, reproduced with 2.6.6 (native plugin v2.6.3f1) trial in testproject
 - Operating system version: Android 10
 - Device model: Quest 1, Pico Neo 3
 - Video specs (resolution, frame-rate, codec, file size): It happens with almost all **audio** files we had, ogg, wav and mp3. Therefore, I do not think this has to do with the media codec. Supplied file in repro project sent to you is a standard 128kbps mp3

**To Reproduce**

See project I will be sending you, or:

1. Load Audio in a Media Player
2. While Audio is playing, disable media player and set PlayMediaOnAppUnpause to false
3. Press "Home" Button on designated VR device to summon the overlay
4. Resume the app -> audio starts playing despite MediaPlayer not being active and PlayMediaOnAppUnpause being set to false

**Videos**

https://user-images.githubusercontent.com/22763799/205986277-039349c4-2af3-40f0-974e-e9ba4d394346.mp4

The video of the bug is also included in the project I will be sending your way.

**Comment by Ste-RH** [comment]
Is this not as simple as making sure the component and GO are active?  We can adjust this line to achieve that:

![image](https://user-images.githubusercontent.com/46531149/206422202-2c960ca1-8889-4bb5-8660-2c3772b03187.png)

Does that give you the behaviour you think correct?

**Comment by Chris-RH** [comment]
Has this helped at all @ChrisBool ?

**Comment by ChrisBool** [comment]
Thanks for the swift response! I tested it in our Application on the Pico Neo 3 and the Quest 1 and with your change it now works as expected.
Now my final question would be whether you are planning on changing this for future releases or if I need to make this manual adjustment whenever we update AVPro.

**Comment by Ste-RH** [comment]
No, no need for you to track and maintain that change.

I have already made the change to our repo, along with fixing up a few warnings that have come in under Unity 2022.2.0f1. These will be in the next release of AVPro Video.

**Comment by Chris-RH** [comment]
The latest version has been released, please let us know if this has not fixed the issue for you.
