### ISSUE TITLE
Version 2.6.7 appears to be incompatible with Unity 2022.2.0f1 on Windows

### ISSUE THREAD

**Issue by ewout-create** [RenderHeads/UnityPlugin-AVProVideo#1393]
**Describe the issue**
When creating a new project or updating an existing project in Unity 2022.2.0f1 with AVPro Video - Ultra Edition 2.6.7. A compiler error appears `Assets\AVProVideo\Editor\Scripts\Components\MediaPlayerEditor_Source.cs(254,12): error CS0023: Operator '!' cannot be applied to operand of type 'InsecureHttpOption'`. Which doesn't happen with version 2.6.6 nor with Unity version 2021.3.15f1. I haven't tested this on Windows 10.

**Your Setup (please complete the following information):**
 - Unity version: 2022.2.0f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra Edition 2.6.7
 - Operating system version: Windows 11 Pro 22H2

**To Reproduce**
1. Create a new project.
2. Add AVPro Video Ultra Edition 2.6.7 package through package manager.
3. Look in console and see the error message.

**Comment by Ste-RH** [comment]
Currently only have access to Windows 10.  Will check that first.

**Comment by Ste-RH** [comment]
![image](https://user-images.githubusercontent.com/46531149/206733203-153887cd-7c50-4f93-9e03-8e54b7054920.png)

That whole block is only applicable for iOS and tvOS, and only a warning.  I would think you are safe to comment out the block of code to enable you to continue your development and we will address it in the next release.
