### ISSUE TITLE
IOS Build Crash Issue | Unity IOS into Native IOS | Library not loaded: @rpath/AVProVideo.framework/AVProVideo

### ISSUE THREAD

**Issue by RojanStha** [RenderHeads/UnityPlugin-AVProVideo#1395]
Describe the issue
I have integrated the AVPro build on the native IOS application and when i build the application on device the application is crashing and showing some error.

Unity version: 2021.3.9f1
AVPro Video version : 2.6.6 (Ultra Edition)
Operating system version: Mac OS Ventura
Xcode Version: 14.0
IOS Version :16.0
i have tried the :

Always Embed Swift Standard Libraries -> Yes
AVProVideo.framework -> Embed & Sign
Updated the latest AVPro Version and Rebuild the Application

Tried  all this methods: https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html

![Screenshot 2022-12-13 at 12 38 01 PM](https://user-images.githubusercontent.com/29281308/207246923-f0bff600-259f-488c-b957-af2e03e293da.png)
![Screenshot 2022-12-13 at 12 38 09 PM](https://user-images.githubusercontent.com/29281308/207246935-df77b7eb-b298-4808-9e90-2f47df0c0c28.png)

******Log********
Library not loaded: @rpath/AVProVideo.framework/AVProVideo
Referenced from: <1B2DB347-505F-35C1-B1D1-CD95C9ADA52F> /private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/UnityFramework.framework/UnityFramework
Reason: tried: '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/AVProVideo.framework/AVProVideo' (errno=2), '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/UnityFramework.framework/Frameworks/AVProVideo.framework/AVProVideo' (errno=2), '/usr/lib/swift/AVProVideo.framework/AVProVideo' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/AVProVideo.framework/AVProVideo' (errno=2), '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B2618152858C/Orchestra QA.app/Frameworks/AVProVideo.framework/AVProVideo' (errno=2), '/private/var/containers/Bundle/Application/513C38A2-5514-4B02-89D2-B261815285
dyld config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libBacktraceRecording.dylib:/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by RojanStha** [comment]
> Hey @RojanStha,
> 
> I can see from the logs that the framework doesn't appear to have been copied into your app, errno=2 means file not found. I can see nothing wrong from the screen shots you posted though. Is there anything reported during Unity's build process or in the Xcode build log that might offer some insight?
> 
> You say you updated to the latest version of AVPro Video, was this working with a previous release?

The only change i noticed was,  after updating the latest version of Avpro i was not  able to build the android build  directly from my mac book.
The build log from unity :
![Screenshot 2022-12-14 at 9 02 50 AM](https://user-images.githubusercontent.com/29281308/207496912-90feeb6d-e6d1-48d6-bfce-2dbf1c970d41.png)

**Comment by MorrisRH** [comment]
Hey @RojanStha 

Sorry, it wasn't clear that you were using unity as a library. I think the solution is to mark ```AVProVideo.framework``` as ```Do Not Embed``` in both ```Unity-iPhone``` and ```UnityFramework``` and to add ```AVProVideo.framework``` to your native app with it set to ```Embed & Sign```.

Because we have no knowledge of your setup during Unity's build process there is no way we can automate this.

If this does work for you please let us know, that way we can update our documentation to include this specific use case.

**Comment by RojanStha** [comment]
i found the issue and the issue was solved, you can close this ticket thank you
