### ISSUE TITLE
Video cannot be played

### ISSUE THREAD

**Issue by PremiumArts** [RenderHeads/UnityPlugin-AVProVideo#1398]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
With specific device, it cannot play the video in Demo scene.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): core 2.6.6
 - Operating system version: Android 12
 - Device model: Moto g32
 - Site Ref: [Device Site](https://www.motorola.com/we/smartphones-moto-g-32/p)
 - Video specs (resolution, frame-rate, codec, file size): Sample-Local-MP4-Cones-360Stereo
 - Tested scene: Demo_360Stereo, Demo_MediaPlayer

**To Reproduce**
1. Import AVPro Video Core Edition to a new unity project
2. Build the project with demo scene
3. Install the APK to device

**Logs**
[error_log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/10226354/error_log.txt)

**Screenshots**
-

**Videos**
-

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

Please advise.
Let me know if any information is needed.

**Comment by PremiumArts** [comment]
Sorry, I uploaded a wrong error log file.
I have reuploaded a new one.
Please have a look

**Comment by PremiumArts** [comment]
Thank you the reply.

I tried for "BigBuckBunny-360p30-H264" and "Sample-Local-MP4-RenderHeads".
These 2 are able to play.

With "Prefer Software Decoder" on, it is also not able to play for "Sample-Local-MP4-Cones-360Stereo"

I have also check on the video of "BigBuckBunny-360p30-H264" and "Sample-Local-MP4-Cones-360Stereo".
I do not found any obvious different between 2 files, the codec is same and format is also same.
Just get confused what will be the reasons that make the video play fail.

**Comment by Ste-RH** [comment]
Closing as this is just the video exceeding the devices capabilities

**Comment by PremiumArts** [comment]
Thanks you for the reply.
Let me ask for some follow questions.

Is there any way we can know the upper limit of the resolution/frame rate/bitrate/profile that the device can support?
Or I need to create test data to test the combination 1 by 1?

Also, since other devices can play high resolution video without problem, what is the best practice in selecting the video play in different device?
Should we prepare 2 different mp4 video? Or, AVPro Video library have some functions to detect which video should used to play?

**Comment by Chris-RH** [comment]
Hi,

Sadly there isn't a helpful table somewhere that lists devices and their max supported playback specs.  You need to search for the device and see what GPU it has, and then search for the GPU and hope that someone has put up the relevant information.

For example, the device site that you linked above says that your device uses "Snapdragon® 680 4G processor with 2.4G Hz octa-core Kryo™ 265 CPU, 1115 MHz Adreno™ 610 GPU", the specs of which can be found here: https://www.qualcomm.com/products/application/smartphones/snapdragon-6-series-mobile-platforms/snapdragon-680-4g-mobile-platform
That tells us: 
Resolution: Up to 1080p @ 60 fps
Codecs: H.264 (Advanced Video Coding (AVC)), VP9, VP8, H.265 (High Efficiency Video Coding (HEVC))
