### ISSUE TITLE
IOSurface mem allocation remains after playing video

### ISSUE THREAD

**Issue by spacejumpunreal** [RenderHeads/UnityPlugin-AVProVideo#14]
I find that on ios we still have some mem allocated by AVPro when we are definitely not playing any video.
The first screenshot is what I found with xcode instrument after playing a 1min in game video, the next is what I found after playing a logo video(around 10 seconds), all two are mp4 format.

I don’t have much experience with iossurface but it seems to me that AVPro is holding some rendertarget internally even after the video is done? Can I have those released to save some mem?
The way we play video is to have an Object with a MediaPlayer Component on it, and destroy it when it is done.
![1](https://user-images.githubusercontent.com/19723445/52107541-ba28cd80-2631-11e9-8756-9f11be117f49.png)
![2](https://user-images.githubusercontent.com/19723445/52107544-bbf29100-2631-11e9-92c6-8cf7be2ed389.png)

**Comment by MorrisRH** [comment]
A few questions:
- What version of the plugin are you using?
- What version of Unity are you using?
- What renderer do you have selected (OpenGLES or Metal)?
- What version of iOS are you running?

**Comment by spacejumpunreal** [comment]
plugin version: 1.9.6
version of unity:5.6.3
render API:metal
iOS version: 12.1.2

**Comment by MorrisRH** [comment]
Can you upgrade to the latest version. An issue with Unity not releasing the video texture under certain conditions when using the metal renderer was fixed in version 1.9.7.

**Comment by AndrewRH** [comment]
Closing this as it seems resolved :)
