### ISSUE TITLE
Rare Black Screen

### ISSUE THREAD

**Issue by r3va13** [RenderHeads/UnityPlugin-AVProVideo#140]
Hello. 

We are facing an issue with AVPro plugin for Windows. We're using AVProVideo/Background/Full Screen solution, but some of our players for an unknown reasons see no videos, but black screen instead. Meanwhile all other game elements are correctly shown, so the problem is definately with the videoplugin. We were trying to use different videoformats and codecs, to change bitrate, to switch "Prefer Video API" in Media Player settings, but we're still recieving reports about this issue.

 - Unity version: Unity 2017.1.5
 - AVPro Video version: 1.9.17
We are unable to reply this issue ourselves, but i'll add setup of a player, who is facing this bug:
"PC, 2 monitors, Nvidia GTX 1080 Ti (only one card), Inted Core i5 4690, H97-PRO Gamer ASUSTEK board, 32GB RAM, SSD disk + classical HDD, 100GB+ free space on both, windows 10 & last nvidia drivers. I have one monitor 1920x1200 second 1920x1080, main is the first one."
 - Video specs (resolution, frame-rate, codec, file size): MOV, 1920*1080, H264, ~2500 bitrate

**Comment by RemyRM** [comment]
@r3va13 This looks like something we're also experiencing. Is it consistent on your players or does it happen to random players at random times? Also does restarting the editor/app fix it?

For me restarting the app/editor fixes it for a ranodm amount of time.

**Comment by AndrewRH** [comment]
Hi @r3va13 

Do you know which version of windows this is happening on?  Do you know whether they have the K or N editions of Windows (these don't include any media framework/codecs)?

Have you asked them to try to upgrade their graphics card drivers (both Nvidia and Intel)?

If your video is only 1080p H.264, then perhaps try changing the Video API setting from Media Foundation (the default) to DirectShow.  This is an older legacy API, but it may work.

Does that help?

Thanks,

**Comment by YuraMihailov123** [comment]
@AndrewRH ,
r3va13 is on vacation now, his duties are temporarily fulfilled by me.

All the players who informed us about the problem have powerful Nvidia videocards (for gaming), all have Windows 10. We also recommend them to update all drivers, they said they did it. About DirectShow - yes, we did it. It did not help. About K and N editions - we will try to clarify.

**Comment by AndrewRH** [comment]
Hmmm well if you tried DirectShow and that didn't help...then that's interesting.

I'm now suspecting it's an issue with the Fullscreen shader..perhaps it behaves different one some cards.  

On systems that reproduce the issue, are you able to use the DebugOverlay component to confirm whether the video frames are being decoded or not?

Thanks,

**Comment by YuraMihailov123** [comment]
@AndrewRH  ,
Unfortunately not. These problems arise from players who bought our game. Perhaps on the other side of the globe. Perhaps they speak other languages. And they just do not wish to engage in any tests. Unfortunately, we ourselves do not have computers on which this problem would be reproduced.

**Comment by AndrewRH** [comment]
Without a reproducible case it's going to be very difficult to resolve.  Could they try with 1 monitor disabled to see whether that solves it?   
Also - do they have both monitors plugged into the same GPU, or is one connected to the motherboard?

**Comment by YuraMihailov123** [comment]
@AndrewRH ,
We will try to contact one of those players who have a problem and talk to him about this.

**Comment by tp-105** [comment]
We're experiencing similar issue. Occasionally, video is black screen but audio is playing. We get events for video loaded, and video finished, etc so as far as the game is concerned, the video is playing fine.

Build:
AVProVideo 1.8.8 with Video API set to DirectShow
Unity 2017.4.22f1

Devices that we've observe black screen:
Dell Latitude 3400 Windows 10 Pro Version: 1809 OS Build:17763.737
Alienware 13 R2 Windows 10 Home Version 1809 OS Build:17763.737
Alienware 13 R3 Windows 10 Home Version:1809 OS Build:17763.503

The repro rate is about 3-4% so it's very rare but we can reproduce it after running it repeatedly overnight.

One thing we notice is that in a normal playback, these events are generated (not always in this order):
Event:MetaDataReady
ErrorCode:None
Event:ResolutionChanged
ErrorCode:None
Event:Started
ErrorCode:None
Event:FirstFrameReady
ErrorCode:None

However, when a playback is black screen, Event:FirstFrameReady is MISSING. The following ErrorCode is also missing.

We are still confirming but it does not look like this issue occurs on Windows 7.

**Comment by AndrewRH** [comment]
Any update on this?
Does the issue go away if you use the latest version of AVPro Video? (1.8.8 is quite an old version)

**Comment by r3va13** [comment]
> Any update on this?
> Does the issue go away if you use the latest version of AVPro Video? (1.8.8 is quite an old version)

Yea. Its very likely that some versions of Windows have no video codecs. We've completely solve our problem by including klite codecs pack into steam game install.

**Comment by RenderHeadsSte** [comment]
Some information provided via another support medium:

>>>
We have found that MediaFoundation on Windows 10 does not have black screen issue.

However, we still have issues on Windows 7 machines with Haali Media Splitter installed. While I don't believe the black screen issue occurs on Windows 7, we do have issue with Haali Media Splitter freezing our app when it's shutting down.

I want to ask if it's possible to force AVProVideo to use MediaFoundation on Windows 7? or alternatively, force it not to use any external 3rd party filters? We are not having much luck with the second option. Setting the preferred filter list does not seem to have any effect. It always seems to use the last installed filter. We've tried strings such as 'LAV Video Decoder', 'Microsoft MPEG-2 Video Decoder'.

**Comment by yixuan2009** [comment]
> > Any update on this?
> > Does the issue go away if you use the latest version of AVPro Video? (1.8.8 is quite an old version)
> 
> Yea. Its very likely that some versions of Windows have no video codecs. We've completely solve our problem by including klite codecs pack into steam game install.
> 
> And sorry, i forgot about this thread =)

Hi,How to install klite codecs pack?
