### ISSUE TITLE
local .m3u8 files fail to load/play

### ISSUE THREAD

**Issue by drew-512** [RenderHeads/UnityPlugin-AVProVideo#1400]
**Describe the issue**
A local m3u8 file fed to `MediaPlayer` via `MediaPath` results in an error.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.15
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.7 Ultra
 - Operating system version: OS 10.14
 - Device model: Mac Pro

**To Reproduce**
1. use any .m3u8 file (get one here [here](http://etn.fm/) > Tune-in > iTunes)
2. Option: edit extension from .m3u to .m3u8 (both result in this error)
3. Load and play this file item via MediaPlayer via `Path`
4. `[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

**Comment by MorrisRH** [comment]
Playback of a local m3u8 file is not supported by Apple, and therefore we're unable to support it. You will need to host your files on a web server, this can be running locally though (we use nginx here for testing purposes).

**Comment by drew-512** [comment]
So a GET of a m3u8 file is supported but a local read of a file isn't, correct?   For my own knowledge, this is just a matter of feeding a m3u8 (and mimetype) via http GET to AVPro, correct?   Not getting how it's related to Apple.

On a related note -- I did have a question around IRandomAccessStream support since it unfortunately is Windows-specific (which would also trivially address this issue):

https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1408

Thanks for your consideration,
Drew

**Comment by MorrisRH** [comment]
The Apple part is because AVFoundation does not support loading of local m3u8 files. For HLS playback, the m3u8 and associated files have to come from an HTTP server.
