### ISSUE TITLE
Where are cache files stored?

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1401]
Where are cached file stored on android? I have some large videos being cached from the web and would like to add more features to play with videos that have been cached to local memory.

I am using a Quest 2 on Android and Av Pro Ultra.

**Comment by Chris-RH** [comment]
Storing and playback of media from cache is currently only supported when using the ExoPlayer API path for playback.
Cached media items are downloaded to the [default external cache folder](https://developer.android.com/reference/android/content/Context#getExternalCacheDir()). They are stored in a proprietary ExoPlayer format and are not readable/usable externally from the ExoPlayer architecture

**Comment by Gurwar** [comment]
Found it in this directory This PC\Quest 2\Internal shared storage\Android\data\com.DefaultCompany.NOMADS_VR\cache\AVProMediaCache

Looks like the files are encrypted and untracable to their source. The most I can use them for is to tell users how much storage is being used for cache. 

Thanks!

**Comment by Ste-RH** [comment]
That is the correct location (for that application install).  Yes, they are not accessible as 'videos'.  This is for a number of reasons that can be read about over in the ExoPlayer documentation (I think!)
