### ISSUE TITLE
Unable to load video from buffer

### ISSUE THREAD

**Issue by sv955** [RenderHeads/UnityPlugin-AVProVideo#1404]
Hi

There is an issue while loading video from buffer

This is working
```
var path ="path of mp4 video";
GetComponent<MediaPlayer>().OpenVideoFromFile( MediaPlayer.FileLocation.AbsolutePathOrURL, path, false );
```

but
```
var path ="path of mp4 video";
var file = File.ReadAllBytes(path);
GetComponent<MediaPlayer>().OpenVideoFromBuffer(file, false);
```

This is not working. 
I'm using AV Pro (Version 1.11.3)

**Comment by Chris-RH** [comment]
What platform is this for?
You should update to the latest version of AVPro Video version 1 -> 1.11.7

**Comment by Ste-RH** [comment]
FYI @sv955. AVPro Video v1.x was deprecated almost 2 years ago and we stopped officially supporting it almost 18 months ago. Whilst we will always look to help where we can, we are not prioritising v1.x issues.

**Comment by sv955** [comment]
Thanks for your quick response.
