### ISSUE TITLE
How does AV Pro decide which stream to use?

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1405]
I am working on a project on the Quest 2 using AV Pro Ultra and it seems that the player keeps defaulting to the lowest quality stream available. Is it possible to turn off this setting or override it with our own configuration?

**Comment by Ste-RH** [comment]
I am afraid not.  The stream chosen is decided upon according to available network bandwidth.

We are looking at the possibility of adding a 'Preferred Minimum Resolution' option, as well as a way to allow single selection of a stream from an adaptive HLS stream.

Currently all you can do is set the 'Start Max Bitrate' flag:

![image](https://user-images.githubusercontent.com/46531149/208067261-7abbbd1e-2c23-4053-83a3-0afdec105894.png)

**Comment by acgourley** [comment]
I'd really like to know if there is a better way here, we've been using StartMaxBitrate and it's been fine until we added some optional UHD streams, these seem to cause some android's to stall and never notify us of first frame ready. But, turning it off, we can only use the smallest stream.
