### ISSUE TITLE
How to use IP instead of domain name to request video.

### ISSUE THREAD

**Issue by hubaoyu** [RenderHeads/UnityPlugin-AVProVideo#1409]
I use httpdns to resolve the IP of the domain name. then ,I use IP directory to play videos with  "Host" header.  while, https server can not verify cert successfully, what can i do for this?

I use OpenMedia method with customheaders such as "Host:xxx.com"

error logs:
Caused by: javax.net. ssl. SSLPeerUnverifiedException: Hostname 117.177.133.244 not verified:
certificate:sha1/nbw5Jhg18LoQP5If6EEv3380jSw=
DN: CN=* .alicdn.com, O=Alibaba (China) Technology Co. \, Ltd. , L=HangZhou, ST=ZheJiang, C=CN
subjectAltNames: [*.alicdn.com, *.cmos.greencompute.org, cmos.greencompute.org, m.intl.taobao.com, * .mobgslb.tbcach
at com.android.okhttp.internal.io. RealConnection. connectTls(RealConnection.java:205)

**Comment by MorrisRH** [comment]
You would have to switch to plain HTTP. Your server's certificate specifies a domain name so you need your request to be to that domain, an IP address is not good enough.

**Comment by hubaoyu** [comment]
but, It is a common practice to use httpdns to resolve domain names to obtain the optimal IP.

**Comment by MorrisRH** [comment]
We think the Host header is being overwritten by the underlying system, we're currently investigating.
