### ISSUE TITLE
Streaming videos are failing to load for some users

### ISSUE THREAD

**Issue by ImmotionPeterL** [RenderHeads/UnityPlugin-AVProVideo#1410]
**Describe the issue**
Some of our users are reporting that all of our videos are failing to load. I log out if it's RenderHeads.Media.AVProVideo.ErrorCode.LoadFailed or RenderHeads.Media.AVProVideo.ErrorCode.DecodeFailed. So far all users have reported that it says LoadFailed.

I am unable to reproduce the issue and am at a loss at what the issue could be to attempt a fix.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.25
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 2.6.6
 - Operating system version: iOS and Android
 - Device model: 
Realme 8 5G
Redmi Note 10 5G
Galaxy A22 5G
Moto G 5G
Nokia 3.4
Redmi Note 11 Pro
iPhone 13
Galaxy A12
Poco X3
Doogee X95Pro
Motorola moto g10 power
Sony Xperia 10 IV

 - Video specs (resolution, frame-rate, codec, file size): streaming 360, m3u8 files, I don't have the specs.

**To Reproduce**
I'm unable to reproduce.

**Videos**
The app is Vodiac VR on iOS/ Android

**Comment by Chris-RH** [comment]
Hi @ImmotionPeterL 

We can't really do a lot with that information.

1. Are you able to provide full logs for any of those devices?
2. Do you have samples of any of the videos that are failing to load? We don't have any of those exact devices, but have similar ones that we could test the video with. You can email them to unitysupport@renderheads.com

**Comment by ImmotionPeterL** [comment]
Unfortunately this is coming from our customers, who can't follow simple instructions. I do not have logs and can't get them.

They can't load any of the ~77 videos we have in the app, which all work for the vast majority of our users.

I was hoping to get some pointers of what causes the "LoadFailed" error, as they all say they're on good connections, using WiFi

**Comment by Chris-RH** [comment]
Are you able to send us any sample videos? It would be helpful to know things like resolution, codec, bitrate etc.

There are a few things that can cause loading to fail. Most likely a lack of system resources, such as memory.

**Comment by ImmotionPeterL** [comment]
I've just emailed a few links to our videos over now

**Comment by Ste-RH** [comment]
I am playing back the first link you sent here on an Xiaomi Mi10T just fine.  Video details are:

[X] Track:0, id=0, mimeType=video/avc, bitrate=10000000, res=3840x1920, supported=YES
[X] Track:1, id=1, mimeType=video/avc, bitrate=5000000, res=3840x1920, supported=YES

So 4k, 30fps (I think), 10 and 5 mbit/s.  Not crazy as videos go.

Unfortunately, without logs, I am not sure what help we can offer.

**Comment by Chris-RH** [comment]
I'm going to close this for now, but please reopen it when you can provide us with some full logs.  Thank you
