### ISSUE TITLE
Video Timeline | Handle Slide Area not moved with fill area Issue

### ISSUE THREAD

**Issue by RojanStha** [RenderHeads/UnityPlugin-AVProVideo#1411]
The problem is that, on sometimes, the timeline's "Handle Slide Area" does not move in a manner comparable to the fill area, and once the video is finished, a fast forward of 8,9 seconds begins.

Unity version: 2021.3.9f1
AVPro Video version : 2.6.6 (Ultra Edition)
Operating system version: Mac OS Ventura
Xcode Version: 14.0
IOS Version :16.0

Screenshots

![F64928A0-F85B-44B0-9969-5D644FD42C3E](https://user-images.githubusercontent.com/29281308/208588287-796d991f-e4a6-414c-91e5-543e210d195a.jpg)
![B40E054D-AB27-4B01-9946-BB7C4CFAB926](https://user-images.githubusercontent.com/29281308/208588295-d837c219-ffb7-449a-bbce-2018da6f8307.jpg)
![95D079F5-06F6-4BF1-9AAE-7AD563B89BF8](https://user-images.githubusercontent.com/29281308/208588299-5cc607ff-5969-4d94-94eb-73f236cefdc5.jpg)

**Comment by RojanStha** [comment]
@MorrisRH please reply for this issue

**Comment by Chris-RH** [comment]
I'm not entirely sure I understand. Do you mean that you are unable to seek within the full buffered time?

What devices is this occurring on?
What are the specs of the video?
Is it stored locally or streamed?
Have you tried a lower spec video?

**Comment by RojanStha** [comment]
![95D079F5-06F6-4BF1-9AAE-7AD563B89BF8](https://user-images.githubusercontent.com/29281308/208818677-2d896a1c-a230-45f7-ab97-f7d1b3afd6d3.jpg)

What devices is this occurring on?
-> Android & IOS both
What are the specs of the video?
-> 360 mp4 video
Is it stored locally or streamed?
-> The video was downloaded(playing from locally)
Have you tried a lower spec video?
-> yes, tried on lower spec

This issue was occurs, if you touch the slider and seek fast forward and backward sometime the Handle Slide Area is not moving.

**Comment by Ste-RH** [comment]
Is the 'Handle Slide Area' your custom code?

**Comment by RojanStha** [comment]
> Is the 'Handle Slide Area' your custom code?

No its default

**Comment by Chris-RH** [comment]
Are you using seekfast and not seek,  as this will jump between keyframes.  If you're playing HLS then they need an iframe playlist for smooth scrubbing.

**Comment by RojanStha** [comment]
> Are you using seekfast and not seek, as this will jump between keyframes. If you're playing HLS then they need an iframe playlist for smooth scrubbing.

No i am playing the local videos from mobile. the issue is only the Green Dot is not moving some times it pause and timeline is moving smoothly .
for now i just removed that green dots but please fix that issue

**Comment by Chris-RH** [comment]
The green line is just the buffered range, which will increase, but not necessarily at an even pace.

**Comment by Chris-RH** [comment]
Closed due to lack of response
