### ISSUE TITLE
Audio continues on iPhone when phone is muted

### ISSUE THREAD

**Issue by zb737472783** [RenderHeads/UnityPlugin-AVProVideo#1413]
**Question**

Problem description:

How can video continue to play sound when iPhone mute is turned on

Device (which devices are you having the issue with - model, OS version number):

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: v2.6.0 (plugin v2.6.0f1-ultra)
Target Platform: iPhone
Unity: v2020.3.42f1c1 WindowsEditor
OS: Desktop - 90VA0003CP (LENOVO) - Windows 11  (10.0.22621) 64bit - ChineseSimplified
CPU: 13th Gen Intel(R) Core(TM) i7-13700KF - 24 threads - 65228KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10078KB - 16384

**Comment by Chris-RH** [comment]
Hi @zb737472783,

1. Could you update to the latest version of AVPro Video and see if this is still an issue please.
2. Could you test it using just the demo medieplayer scene.
3. Which iPhone device and iOS version are you using?
4. Is this occurring if you mute your iPhone while playing a video, before playing a video, or both?
5. How are you muting your iPhone and what settings are you using?

**Comment by Chris-RH** [comment]
Hi @zb737472783,

1. Could you update to the latest version of AVPro Video and see if this is still an issue please.
2. Could you test it using just the demo medieplayer scene.
3. Which iPhone device and iOS version are you using?
4. Is this occurring if you mute your iPhone while playing a video, before playing a video, or both?
5. How are you muting your iPhone and what settings are you using?

**Comment by Chris-RH** [comment]
Closing due to lack of reply from OP
