### ISSUE TITLE
I get a black video when playing the built game.

### ISSUE THREAD

**Issue by chillasart** [RenderHeads/UnityPlugin-AVProVideo#1417]
Problem description:

I get a black video when playing the built game. However, all videos are working fine in the editor.

Device (which devices are you having the issue with - model, OS version number):

Windows 11 Pro 64bit (10.0, Build 22621)

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

6 selectable videos in scene, mp4 (H.264), 1280x720, 29.97fps

System Information:

AVPro Video: v2.6.7 (plugin v2.6.7f1-ultra)
Target Platform: Standalone
Unity: v2021.3.11f1 WindowsEditor
OS: Desktop - OMEN 30L Desktop GT13-0xxx (HP) - Windows 11  (10.0.22621) 64bit - English
CPU: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz - 20 threads - 65400KB
GPU: NVIDIA GeForce RTX 3090 - NVIDIA - Direct3D 11.0 [level 11.1] - 24340KB - 16384

**Comment by Chris-RH** [comment]
Is this build on the same computer?
Have you tried building just the media player demo scene on the same computer?
Which shader are you using?

**Comment by chillasart** [comment]
Hi,

Thanks for getting back to me.
I actually fixed the problem by moving all videos to the streaming assets
folder.

Thanks
