### ISSUE TITLE
Issue: File not found, codec not supported, video resolution too high or insufficient system resources.

### ISSUE THREAD

**Issue by RojanStha** [RenderHeads/UnityPlugin-AVProVideo#1418]
Describe the issue
The resolution 1920 * 960 with codec h265, h264 both video is playing  with AVPro ultra edition player, but i converted the original Ambix 4 channel 1st order mp4 video which has resolution with 3840 * 1920, the video is not playing.

we tried on this device: https://www.gsmarena.com/xiaomi_redmi_note_11_pro_5g-11333.php

Unity version: 2021.3.9f1
AVPro Video version : 2.6.6 (Ultra Edition)
Android Version: 12.0

![Current Media Information 12_27_2022 1_56_17 PM](https://user-images.githubusercontent.com/29281308/209634503-316d6947-77a1-4196-b2d1-7e73cc88f68b.png)

![Current Media Information 12_27_2022 1_29_01 PM](https://user-images.githubusercontent.com/29281308/209634283-8898fc1c-1a08-4174-b911-a0f4b854c955.png)

![Screenshot 2022-12-27 at 1 28 48 PM](https://user-images.githubusercontent.com/29281308/209634385-0ff3c2e1-0aa7-49da-8e4c-7fafa33c35a7.png)

**Comment by RojanStha** [comment]
@AndrewRH @RichRH @nathanlance

**Comment by Ste-RH** [comment]
Please provide the video you are having issue with.  You can email this over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) if you wish to keep it private.

**Comment by Chris-RH** [comment]
@RojanStha 
Are you able to send a video? You sent us a link when we were on holiday, so the link has expired.

**Comment by Chris-RH** [comment]
Closed due to lack of reply. Please reopen if you still require assistance.
