### ISSUE TITLE
Media player uses marked as obsolete method on opening media

### ISSUE THREAD

**Issue by aleh-patseyeu** [RenderHeads/UnityPlugin-AVProVideo#1420]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Any played video on Android device generates a warning message. N videos started simultaneously produce noticable CPU spike.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.23f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.6.7 Ultra
 - Operating system version: Android 11
 - Device model: Samsing A22 (in this particular case, but warning appears on all our available for testing devices)
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Start playing video on Android device

**Logs**
```
2022.12.29 15:17:31.591 24116 24403 Warn Unity 
2022.12.29 15:17:31.591 24116 24403 Warn Unity AndroidJNIHelper: converting Byte array is obsolete, use SByte array instead
2022.12.29 15:17:31.591 24116 24403 Warn Unity UnityEngine._AndroidJNIHelper:ConvertToJNIArray(Array)
2022.12.29 15:17:31.591 24116 24403 Warn Unity UnityEngine._AndroidJNIHelper:CreateJNIArgArray(Object[])
2022.12.29 15:17:31.591 24116 24403 Warn Unity UnityEngine.AndroidJavaObject:_Call(String, Object[])
2022.12.29 15:17:31.591 24116 24403 Warn Unity RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
2022.12.29 15:17:31.591 24116 24403 Warn Unity UIManaging.Common.MediaPlayerPool:PlayerInitializationQueue()
2022.12.29 15:17:31.591 24116 24403 Warn Unity  
2022.12.29 15:17:31.591 24116 24403 Warn Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 39)
```

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @aleh-patseyeu,

Does it do this if you build the demo mediaplayer scene?

**Comment by aleh-patseyeu** [comment]
Hi @Chris-RH,

> Does it do this if you build the demo mediaplayer scene?

Yes, I've reproduced it using `Demo_DisplayComponents` scene - got 2 warnings. 

> Are you using byte arrays in your project?

No, we moslty use deafult `Display uGUI` component and streaming.

**Comment by Ste-RH** [comment]
Yeah, I spotted this the other day as well.

We will look to fix this before it becomes obsolete.

**Comment by Chris-RH** [comment]
AVPro version 2.8.3 has been released.  Please let us know if this has not fixed your issue.
