### ISSUE TITLE
Player changes color slightly

### ISSUE THREAD

**Issue by MintX** [RenderHeads/UnityPlugin-AVProVideo#1422]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Player changes color slightly when played movie

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.6.f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 2.6.6

**To Reproduce**
1. Play white-background movie
2. Player changes color slightly. (by Screenshot, (255,255,255) -> (254,254,252)

**Screenshots**

![Screenshot_20230105](https://user-images.githubusercontent.com/13432184/210740885-2540b0d1-103f-4d4e-a923-fc02b356d1dd.jpg)

**Videos**

https://user-images.githubusercontent.com/13432184/210740840-9df2351e-c9d3-4b7a-89b8-1dc6833df364.mp4

**Comment by MintX** [comment]
It captured by AVPro Movie Capture Ultra (5.0.5)

Thank you.

**Comment by MintX** [comment]
And... It occurs on Windows, Android, iOS

**Comment by Chris-RH** [comment]
Are you using a gamma or linear colour space?
Are you using one of the demo scenes? 
Displaying as UI or on mesh? 
Which shader are you using?
What are the specs of the video you are playing?
Is it the same discrepancy on all the devices? Which devices are you using?

**Comment by MintX** [comment]
I changed color space from Linear to Gamma, but stiil exsit color discrepancy.

Thank you.

**Comment by MintX** [comment]
Yes. On Unity's video player, no color discrepancy.

But cannot play well on Android device.  (with Error opening extractor: -10004)

**Comment by Ste-RH** [comment]
Could this be to do with colour ranges of your encoded video?

How are you encoding your videos?  You can use ffmpeg to specify full colour ranges.

Off the top of my head the flags are something like:

`-vf scale=in_range=limited:out_range=full -color_range 2 -pix_fmt yuv420p -movflags +write_colr`

**Comment by MintX** [comment]
I'm capturing my app's screen in realtime via AVPro Movie Capture .

Is there any options for that?

**Comment by MintX** [comment]
Anyway, Unity's video player and web player (on this web page) shows the correct colors.

I think it's not problem from encoding, but player's fault.

Thank you.

**Comment by Ste-RH** [comment]
That is a fair comment.  As info, your video is encoded as 'yuvj420p(pc, bt709/bt709/smpte170m)'.

What API are you using on Windows to playback?  MediaFoundation I assume...Have you tried WinRT?

**Comment by MintX** [comment]
I don't use Windows standalone app. For the test only.

Trying on Windows don't help solving the problem :(

**Comment by MintX** [comment]
Is there any further information for this problem?

**Comment by Chris-RH** [comment]
Can you provide a sample of the original video that you played in the player please? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
What are you using to measure the colour?
On Android are you using Exoplayer or MediaPlayer?

**Comment by MintX** [comment]
Uploaded video file on post is original.
I took a sceenshot and measured color on image editor like PhotoShop.

Exoplayer and MediaPlayer both shows same color.

Thank you.

**Comment by Ste-RH** [comment]
I have ran a few tests here using our Demo_MediaPlayer scene.

1) Grabbing a screen shot PNG via Android Studio and checking pixels in Paint.NET.  The pixels all around the face are white (attaching screen shot)

![Screenshot_20230109_153407](https://user-images.githubusercontent.com/46531149/211346502-fdc1a9af-1a2b-4ad0-bc09-45140fae53e1.png)

2) Modifying the shader to change pixels 'close to white' to magenta.  As you can see, pixels are closer to white than the thresholds you outlined in your original post:

![image](https://user-images.githubusercontent.com/46531149/211347078-5daf2d68-65bf-45a8-985a-795e0c64182b.png)

https://user-images.githubusercontent.com/46531149/211347157-9de0d914-39f2-48c6-86a0-74fae57e8873.MOV

Is there something else at play in your scene I wonder?  The Demo_MediaPlayer scene also uses the Display uGUI component and the 'AVProVideo-Internal-UI-Default-Transparent' shader.

**Comment by Ste-RH** [comment]
Bit of additional;.  The screen shot I attached has the Demo scenes GUI up, which naturally changes the 'white' in the bottom half of the final screen render.  Here is one without the GUI showing 'white' everywhere in the background.

![Screenshot_20230109_153255](https://user-images.githubusercontent.com/46531149/211348169-1be1511a-a353-48f0-9f80-9fadb9f6e557.png)

**Comment by MintX** [comment]
Not only white background color, but also face's color.

NO.1 and NO.3 is AVPro's color (NO.3 is your screen shot)

NO2 is screenshot from Webbrowser. (and it's same color what I captured.)

![image](https://user-images.githubusercontent.com/13432184/211350485-66d650e9-ab0a-4a14-82f7-671322868c51.png)

How do you look these colors?

**Comment by Ste-RH** [comment]
Oh, ok.  I see what you are saying.  I thought the issue was the white/colour-range specifically.  You mean the video is not rendered on Android correctly when compared to the original (and windows it would seem):

![image](https://user-images.githubusercontent.com/46531149/211357510-fc02f4d3-1c34-415d-9679-09301fd3980c.png)

**Comment by Ste-RH** [comment]
This looks like a general Android difference.  Not sure what we can do to offer a solution as this could also differ by device (GPU and, naturally, screen)
