### ISSUE TITLE
Android - Audio out of sync when using Unity audio output with a looping video

### ISSUE THREAD

**Issue by joseph-o3h** [RenderHeads/UnityPlugin-AVProVideo#1424]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Same as https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1313, can reproduce on v2.6.7 ultra so reopening.

**Comment by Chris-RH** [comment]
What device are you using?
Unity version?
How is it in editor?
Can you send us a copy of the file you are using? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Chris-RH** [comment]
Seeing as this is the same issue, I'm closing this and reopening the old one
