### ISSUE TITLE
Comparison of CPU performance of Unity Videoplayer and AVProVideo.

### ISSUE THREAD

**Issue by NexonKimDucChun** [RenderHeads/UnityPlugin-AVProVideo#1425]
In our project, we are playing several videos (more than seven) in one scene. I am currently using a Unity Videoplayer.
I tried CPU profiling by replacing this with AVProVideo.
As for the profile result, Unity Videoplayer performs better than AVProVideo.

I want to know if there is any way to improve the performance of AVProVideo in this situation.

Unfortunately, due to call stack information, it is not possible to upload Unity profile data to a public place.
Instead, it is replaced with a simple screenshot.
(If you need profile data, please send me an email.)

- Unity Version : 2021.3.4f1
- AVPro Video Version : untra v2.6.7 (trial)
- Android 12
- LG v50(LM-v500N)
- There are seven different types of videos.

Unity Videoplayer
![unity_videoplayer](https://user-images.githubusercontent.com/122075982/210940901-f8bb2bfb-2a80-4369-bfc1-d1eca941fac4.png)

AVProVideo
![avpro_videoplayer](https://user-images.githubusercontent.com/122075982/210941006-8664f0f6-0f01-4d89-8151-79ca0adb4921.png)

**Comment by korleinster** [comment]
;(

**Comment by Chris-RH** [comment]
Thank you, this is very interesting.

What specs of videos were you playing?
Are they playing from local storage or streamed?
Were they looped?
What were your mediaplayer settings?
Were you using Exoplayer or MediaPlayer?
What result did you get when trying the other one?
Interesting that Animation seems very high, possibly due to the watermark in the trial version?

**Comment by NexonKimDucChun** [comment]
> Thank you, this is very interesting.
> 
> What specs of videos were you playing? Are they playing from local storage or streamed? Were they looped? What were your mediaplayer settings? What are your audio settings? Unity? System Direct? Were you using Exoplayer or MediaPlayer? What result did you get when trying the other one? Interesting that Animation seems very high, possibly due to the watermark in the trial version?

1. mp4, vertical resolution about 240, screen ratio about 1.8

2. Streaming.

3. Looping.

4. I used MediaPlayer/Apply to Material/Audio Output.

5. Use MediaPlayer.

6. What is the other one? I do not understand the intent of the question.

7. Is there a possibility that performance will increase if watermark is excluded?

**Comment by Chris-RH** [comment]
Hi,

Thank you.
Did you use Unity audio or System direct audio?
Exoplayer might get better results

We are looking at some streamlining :)

**Comment by Ste-RH** [comment]
There are a number of things here that make a direct comparison quite unfair.

Easy wins, if you are not using the functionality, are to comment out the calls to the following from the Update() function in AndroidMediaPlayer.cs :

- UpdateTracks();
- UpdateTextCue();
- UpdateSubtitles();
- UpdateTimeRanges();

...as they all make calls into the plugin layer, which is unfortunately always going to make a hit on the main thread.

**Comment by NexonKimDucChun** [comment]
> Hi,
> 
> Thank you. Did you use Unity audio or System direct audio? Exoplayer might get better results
> 
> We are looking at some streamlining :)



> 

We use Unity audio.
Because it is a multi-platform app. 
(android, ios, windows)

Can exoplayer be purchased from the Unity Asset Store?

**Comment by NexonKimDucChun** [comment]
> There are a number of things here that make a direct comparison quite unfair.
> 
> Easy wins, if you are not using the functionality, are to comment out the calls to the following from the Update() function in AndroidMediaPlayer.cs :
> 
> * UpdateTracks();
> * UpdateTextCue();
> * UpdateSubtitles();
> * UpdateTimeRanges();
> 
> ...as they all make calls into the plugin layer, which is unfortunately always going to make a hit on the main thread.
> 
> As Chris says, we have optimised these down a bit, but there will always be a hit. Looking forward we might limit this back to a single status call into the plugin once a loop. That might limit the time spent calling into the plugin layer.

As advised, the plug-in layer's call was removed, resulting in an equivalent result to the Unity video player. 
This is very good. Our project will actively review the use of AVPro.

![avpro_videoplayer_modified](https://user-images.githubusercontent.com/122075982/212797869-6b20bfb3-b72e-41b3-9fbf-bd2179d4770d.png)

**Comment by Chris-RH** [comment]
Ahh, that's great to hear, thank you for your feedback!
We are still looking at little tweaks that we can make to improve it further.

**Comment by NexonKimDucChun** [comment]
The AVPro Media Player is slowing down again.

The performance is good within one minute immediately after the initial loading, but the frame gradually decreases when the video is loaded one by one.
Initially, it maintained 60 FPS, but it fell to about 45 FPS over time.

as advised above 
	UpdateTracks();
	UpdateTextCue();
	UpdateSubtitles();
	UpdateTimeRanges();
The plug-in call has been commented.

I would like to know if there is any way to improve the FPS further in this situation.
![avpro_videoplayer_modified3](https://user-images.githubusercontent.com/122075982/213650622-dd6cd387-1658-4f4e-9fbf-db12640566f1.png)
![commented](https://user-images.githubusercontent.com/122075982/213650631-a15094bb-297f-4529-aff7-64a39de5badf.png)

**Comment by Chris-RH** [comment]
Are you using Mono or  IL2CPP build?
Have you tried using Exoplayer Video API?
In the Events section in the MediaPlayer component, try settings the "triggered events" to "nothing" to save some perf
Try ticking the "Disable Logging" option in Global section (logging is slow)
In the Global section, disable "Developer Mode"
If audio is not required, set "audio output" mode to "None"

We are also looking at some changes that we can do internally to improve performance.

**Comment by NexonKimDucChun** [comment]
> Are you using Mono or IL2CPP build? Have you tried using Exoplayer Video API? In the Events section in the MediaPlayer component, try settings the "triggered events" to "nothing" to save some perf Try ticking the "Disable Logging" option in Global section (logging is slow) In the Global section, disable "Developer Mode" If audio is not required, set "audio output" mode to "None"
> 
> We are also looking at some changes that we can do internally to improve performance.

We use IL2CPP. 
We use some events.(EventType.PlaylistFinished, EventType.FinishedPlaying)

I've looked at the functions you guide me through.
It has been confirmed that these functions can be set at the time of Unity Editor design.

However, in our project, all video players are scripted. Not statically used. 

I found a way to control the ability to guide the script, but I couldn't find it. Show me how to control it.

Thank you.

**Comment by Chris-RH** [comment]
Is there any improvement after updating to AVPro Video 2.8.0?

**Comment by Ste-RH** [comment]
Closing soon due to lack of response
