### ISSUE TITLE
Programming video to play on command

### ISSUE THREAD

**Issue by gorlitzkr** [RenderHeads/UnityPlugin-AVProVideo#1426]
**Question**

Problem description:

I need one video to pause when it ends and then to program two buttons where if you click one button, video A plays and when you click the second button, video B plays on the screen. I will pay to solve this: email me at kristen@mindweird.com

Device (which devices are you having the issue with - model, OS version number):

Unity VR project

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

12 videos, stereoscopic 2k video, .mp4, 24 fps

System Information:

AVPro Video: v2.5.3 (plugin v2.5.3f2-trial)
Target Platform: Standalone
Unity: v2021.3.5f1 WindowsEditor
OS: Desktop - TRX40 AORUS XTREME (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.19044) 64bit - English
CPU: AMD Ryzen Threadripper 3960X 24-Core Processor  - 48 threads - 130954KB
GPU: NVIDIA GeForce RTX 3090 - NVIDIA - Direct3D 11.0 [level 11.1] - 24348KB - 16384

**Comment by Chris-RH** [comment]
Hi @gorlitzkr,

It is not within the remit of our support to write code for users.  

You can look at our demo scenes (which you'll see included in your trial version) and documentation (https://www.renderheads.com/content/docs/AVProVideo/articles/intro.html) to get an idea of how to use AVPro Video.   The Mediaplayer demo is an especially useful demonstration of UI.
Here is some info on events and scripting: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-events.html
