### ISSUE TITLE
3d sound is not work

### ISSUE THREAD

**Issue by Hongsungbock** [RenderHeads/UnityPlugin-AVProVideo#1427]
Hi. I'm trying to make 3d sound for movie clip with avpro untra edition.

I want to reduce movie clip volume of 3d cude go away from audio listener on main camera.
I tested Cube-ApplyToMesh on Demo_DisplayComponents scene. Add "Audio Output" component to cube and changed
"Spatial Blend" value is 1(3d side) of audio source component on same game object of "Audio Output". But the sound volume
is not reduced when I move cube away from main camera

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16
 - AVPro Video version : ultra 2.6.7
 - Operating system version: windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**Screenshots**

![1](https://user-images.githubusercontent.com/8719896/211464264-94dc792d-0c5c-49d5-ba8d-34062c836291.png)
![4](https://user-images.githubusercontent.com/8719896/211464449-88dd3c1f-9162-456d-902a-e89023e7bd0d.png)
![2](https://user-images.githubusercontent.com/8719896/211464276-ab1e5d99-606b-4828-9ffa-224c48b48069.png)
![3](https://user-images.githubusercontent.com/8719896/211464287-1747ef5e-dd14-41e2-9ba2-beb4f1bb4f53.png)

**Comment by Ste-RH** [comment]
Attenuation of audio gain with distance does indeed work.  I am using these settings:

![image](https://user-images.githubusercontent.com/46531149/211531767-5de4cfc8-3eda-484d-b199-fa5d10b2ed66.png)
...and here is the result when I move the MediaPlayer away/towards from the Camera.  Note that here I have disabled doppler as it just sounds messy when moving the camera in the scene like this!

https://user-images.githubusercontent.com/46531149/211532655-7827afe1-c88e-49c5-8821-ace43e933296.mp4

**Comment by Hongsungbock** [comment]
Add Audio Source and Audio Output component with Meida player component is work. Thank you :)
