### ISSUE TITLE
Best way to get a thumbnail?

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProVideo#1428]
Hey! We'd like to display thumbnails of our videos in our UI before the user selects on to view. We could obviously just make each thumbnail a video, but I figure that comes with overheads? We don't want to load anything unnecessarily. 
What's the recommended way to get a smallish texture that represents a video?

**Comment by Chris-RH** [comment]
I'm not sure we can recommend anything without some video loading.
The two obvious options would be
a) load video and disable autoplay, so it pauses on first frame
b) to grab a random frame, you could try calling this:
Texture frame = mediaPlayer.ExtractFrame(10.0);
That would extract a frame at time 10s


Other than that I think you'd need to extract it manually.
