### ISSUE TITLE
360 Audio Update

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1429]
Problem description:

Is there any update on 360 audio in AV Pro? Is there any update to the Facebook 360 audio codec?

Device (which devices are you having the issue with - model, OS version number):

Quest 2

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: v2.6.6 (plugin v2.6.3f1-ultra)
Target Platform: Android
Unity: v2021.3.8f1 WindowsEditor
OS: Desktop - B550M DS3H AC (Gigabyte Technology Co., Ltd.) - Windows 11  (10.0.22621) 64bit - English
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 threads - 32691KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10067KB - 16384

**Comment by Chris-RH** [comment]
Hi, we still have this open as an enhancement.  You can follow it here to see when support is added: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1169
