### ISSUE TITLE
FB360 Matroska audio not working properly

### ISSUE THREAD

**Issue by OldMontana** [RenderHeads/UnityPlugin-AVProVideo#143]
**Bug**
We were originally using MP4 with separate TBE files for our 360 ambisonic video. The audio sounded perfect, but the required sync caused a lot of frame rate and freezing issues with the video. We then tried to use the FB360 Matroska output so we could encode the audio and video together. This eliminated our freezing issues, but the audio doesn't sound the same as it did using the TBE files. The directional audio seems to be coming from the right locations, but the "all directions" channel seems to be very quiet or even nonexistent. We feel this way because, when turning your head 180 degrees away from someone who is talking in the video, you can barely hear what they're saying. In the TBE audio, if you turned 180 degrees away from someone who was speaking, they would be noticeably quieter, but you could still hear them very clearly.

We aren't sound experts, so we feel we might be encoding our files wrong. Right now, we are dropping our MP4 and WAV files into FB360 Encoder, selecting "FB360 Matroska (Spatial Work Station 8 channel)" as the output, and then converting the output MKV into an OBB expansion file to be used for the app. We know that something has to be done with Opus, but we're not sure what that is considering that FB360 Encoder doesn't accept .opus files. **Are we doing anything wrong? Why isn't our MKV audio sounding the same as our TBE files if we're using the same source WAV files? How do we use FB360 Matroksa to make our audio work properly?**

**Setup**
- Unity version: 2018.3.0f2
 - AVPro Video version: 1.10.0
 - Operating system version: Windows 10
 - Device model: Oculus Go
 - Video specs (resolution, frame-rate, codec, file size): 4096x4096, 30fps, H265, 3GB
 - Audio specs: ambisonic B-format (1st order ambix) WAV

**Comment by AndrewRH** [comment]
Hi,

The best way to encode the video is to use the FB360 Encoder tool which comes as part of the FB360 Spatial Workstation.  Set Output Format to “FB360 Matroska (Spatial Workstaton 8 channel)” and then set your video and audio source files and encode your video.  This should create a MKV file with 10 channels of Opus audio.

It sounds like this is what you're already doing.  It could be that there is some issue converting from 1st order ambiX to the 10 channel TBE (8_2 format) that is used in Facebook's tool.  I presume the TBE files that you used before were not in the 8_2 format?

In this case I would post the question to the Facebook team here:
https://www.facebook.com/groups/audio360support/

There may be some quirks that they know about in the conversion process.

If you do hear anything back from them, it would be great to know what they say.

Thanks,

**Comment by OldMontana** [comment]
Thanks for the response, Andrew. 

Yes, unfortunately that's what we're already doing. I'm not sure what the main differences are between how TBE is encoded vs. the audio in Matroska, but I'm hoping it's something that is correctable. I'll post this question in the Facebook forum once I get accepted, and I'll let you know if anyone knows what's going wrong.

Thanks again!

**Comment by ASinVR** [comment]
This is interesting for us as well, since our clients gave the same kind of feedback about their videos. Please update :)
