### ISSUE TITLE
Shader Graph integration

### ISSUE THREAD

**Issue by JuanObiJuan** [RenderHeads/UnityPlugin-AVProVideo#1430]
Im using stereo videos in VR in Unity 2020 using the Ultra version. My question is how can I integrate AVpro video with Shader Graph and control what render to different eyes. I dont see any extra node once the plugin is intalled or extra package to install.

**Comment by Ste-RH** [comment]
I have read that getting the correct eye index can be problematic in Shader Graph.  Indeed we have had issues supporting all the rendering variants/paths (SPR/URP/HDRP, OES, Multi Pass, Multiview, Oculus SDK, etc).

I know other developers have used Shader Graph with AVPro Video, but not sure about with VR and the possible variations to the rendering pipeline.

Maybe these links will help:

https://docs.unity3d.com/Packages/com.unity.shadergraph@12.0/manual/Eye-Index-Node.html

https://forum.unity.com/threads/render-different-color-depending-on-stereo-eye-index.1037215/

**Comment by JuanObiJuan** [comment]
Thankyou for your answer. One of the reasons why I was decided to use this plugin in my project was the feature included in the documentation 
![image](https://user-images.githubusercontent.com/1729541/211609433-1a79387b-20ab-441e-b9c1-9aa25f7b2f87.png)

So maybe its time to delete that feature from the list if there is no really support for that and not to get fooled like it happens to me.

**Comment by Ste-RH** [comment]
Why would we delete it?  Shader Graph works and is supported.  It is Unity's eye index in Shader Graph that I was suggesting is hit and miss.  That is nothing to do with AVPro Video, it is a (possible) Unity issue.

**Comment by JuanObiJuan** [comment]
Thanks for your answer. 

I suggested to deleted because reading that description, any person expect to find a node in Shader Graph that is helping to extend the functionality. In my installation (in Unity 2020 LTS) there is nothing at all related with shader graph. If you mean that you can always with AVPro render to texture and then use shader graph... I would not include this as a feture and should be more clarified.

My specific needs are related to deal with stereo textures and vertex position modifications in shadergraph under URP 10.10.1, so there is no eye index for me (I think is from URP 12)

Any tip is welcome.

**Comment by JuanObiJuan** [comment]
@Ste-RH Thank you for the links. They were reallyhelpful. 

Good news is that Im able to switch per eye inside my dhader graph, and now I have this situation:
![image](https://user-images.githubusercontent.com/1729541/213663463-553b060e-6662-46fd-bca8-66b3218b39c9.png)

On the image Quad1 (left), Quad2(middle) and Quad3(right)
- Quad1: Is using my shaderGraph running using the Avpro script ApplyToMesh (I was able to offset properly per eye)
- Quad2: Is using Apply to mesh with the AVpro VR Shader
- Quad3: Is a unity video player rendering the texture using the same shader I made for the quad1

The texture sended to myShader is clearly brighter than the texture on the video and is not only a matter a brightness, blacks are not at 0. I was trying to rempad values but I had no success, the result are reducing too much the levels. For me, it feels that the AVpro shader perform a non linear opration to recover the colors levels. Im I right?

My question is... can I know wich operation are made over the colors to recreate them on the my ShaderGraph.

**Comment by Chris-RH** [comment]
Have you tried this:
![colourspace](https://user-images.githubusercontent.com/102963025/213668467-a1f4f9a6-cdf2-4733-9d64-1e8144e1012a.png)

**Comment by JuanObiJuan** [comment]
@Chris-RH That was! Thankyou!

For those who wants to use Stereo textures, here it is my ShaderGraph for AVpro

![image](https://user-images.githubusercontent.com/1729541/213670204-b9e789fa-aaef-4635-b160-2dcda70d4a13.png)

I use a custom function called EyeIndex to split beween eyes and support SinglePass/Instanced pass rendering on Unity2020 LTS

![image](https://user-images.githubusercontent.com/1729541/213670824-7b82816b-abc0-43c3-8244-80410c32ec86.png)

In my opinion, this should be included on the asset package and it is exactly what I was expecting to find already when I was reading on the features "ShaderGraph integration".

**Comment by Chris-RH** [comment]
Awesome! I'm glad that we got there in the end :)
Thanks for sharing your full ShaderGraph. No doubt someone will find it useful in the future :)
