### ISSUE TITLE
WebGL unable to load HLS stream

### ISSUE THREAD

**Issue by LordLegionKeygard** [RenderHeads/UnityPlugin-AVProVideo#1432]
Hi i am use documentation, but i receive error "ncaught ReferenceError: Hls is not defined"

Maybe i take mistake in point  5)

1)In the MediaPlayer component set Platform Specific > WebGL > External Library to hls.js
2)Build for WebGL
3)Download the latest hls.js release (we tested with 0.10.1):
https://github.com/video-dev/hls.js/releases
4)Once your build is made, copy “hls.min.js” to the TemplateData folder
5)Edit the index.html to add <script src="TemplateData/hls.min.js"></script> before the UnityLoader.js script is loaded. Ideally you would add this to a new WebGL template so that you don’t have to make these changes for each build.

![image](https://user-images.githubusercontent.com/76789721/211855411-b23894be-a938-4f2f-aa0c-535586da790c.png)
![image](https://user-images.githubusercontent.com/76789721/211855459-2ef41d54-7cb3-43d3-90c1-2875cc446a4b.png)
![image](https://user-images.githubusercontent.com/76789721/211857452-4adee973-b9f5-49ad-9079-851bb5b8b0ad.png)

**Comment by Chris-RH** [comment]
"Edit the index.html to add <script src="TemplateData/hls.min.js"></script> in a **<head>**; section of the HTML"
Yours is in the <body> section.

**Comment by LordLegionKeygard** [comment]
Thx, but now i have this error

![Безымянный](https://user-images.githubusercontent.com/76789721/212057482-3f250084-d773-47b3-8acc-16abac4b8ec2.png)

**Comment by Chris-RH** [comment]
We don't officially support WebGl.

Could this be a CORS issue? https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl
