### ISSUE TITLE
How to access AudioSource clip samples data

### ISSUE THREAD

**Issue by BestAR25** [RenderHeads/UnityPlugin-AVProVideo#1434]
**Question**
Now I want to implemente LiveStream video by using AVProVideo and Agora SDK.
Agora SDK sent audio data  from audiosource.clip.samples but I can't get access real sound data from AudioOutput script.

![image](https://user-images.githubusercontent.com/64001338/212444513-a73fa5b1-977d-4e51-a1ea-c0f3c6597eb9.png)
This is partial screenshot of my sample project.

I want to get audio samples from that "dummy" AudioClip. But that samples data in the AudioOutput.cs is initialized with 1.

![image](https://user-images.githubusercontent.com/64001338/212444454-bfe69d7f-6193-4c78-b954-dd21cb218fa0.png)

Can I get audio sample data from AVPro?

* platform is window

**Comment by Chris-RH** [comment]
![audiodata](https://user-images.githubusercontent.com/102963025/212680201-52112eb0-4f57-4809-8ba0-972cb405021b.png)

**Comment by BestAR25** [comment]
Thanks your reply.
I need that audioData. Is that audioData parameter  output , right?
If that's right output parameter, how  can I set audioData length?

Can you show me sample right such as below.
float[] audioData = SampleFunction();

**Comment by Chris-RH** [comment]
We have an API list in our documentation

https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.BaseMediaPlayer.html#RenderHeads_Media_AVProVideo_BaseMediaPlayer_GrabAudio_System_Single___System_Int32_System_Int32_

https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.AudioOutputManager.html?q=audiodata#RenderHeads_Media_AVProVideo_AudioOutputManager_RequestAudio_RenderHeads_Media_AVProVideo_AudioOutput_RenderHeads_Media_AVProVideo_MediaPlayer_System_Single___System_Int32_System_Int32_RenderHeads_Media_AVProVideo_AudioOutput_AudioOutputMode_System_Boolean_
