### ISSUE TITLE
Problem with AVPRO core in WebGL

### ISSUE THREAD

**Issue by vKlabe** [RenderHeads/UnityPlugin-AVProVideo#1436]
hello,
we would have a problem with AVpro core

we would like to buy it but we are doing tests with the trial version and to date it gives us this error:

![avpro problem](https://user-images.githubusercontent.com/122777842/212627678-b1919990-faa0-421a-b3d3-97b66aa14b72.jpeg)

we are using External Library: HLS

we are using webgl

What could be the problem?

thank you very much!

v

**Comment by Chris-RH** [comment]
We don't officially support WebGl.

It is most likely to be a CORS issue? https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl

**Comment by FedeGToto** [comment]
We uploaded the test build on itch.io due to problems with CORS, but then that error showed up. When there are CORS errors it explicitly says that, at least on our previous builds

**Comment by Chris-RH** [comment]
What browsers have you tried it in?

**Comment by FedeGToto** [comment]
We tried on Google Chrome, for now. On itch.io there was just a clean build with AVPro Trial

**Comment by Chris-RH** [comment]
So the videos that you are trying to access are on there too, or on a different server?

**Comment by FedeGToto** [comment]
Are on another server

**Comment by Chris-RH** [comment]
A 403 error indicates that it is either a CORS issue or that you are trying to get a file that does not exist.  You need to make sure that the target URL is correct and that the cases used are correct.  I can't quite make out the URL, but there seems to be some odd lettering in it.  Is all of it standard ascii?

**Comment by FedeGToto** [comment]
In editor it works just fine

**Comment by Chris-RH** [comment]
Yes, running in Editor is different.
You must treat URLs as case sensitive, so make sure they are correct.
When you upload, are you using any compression?
Which browsers have you tested on other than Chrome?

**Comment by Chris-RH** [comment]
AVPro Video doesn't officially support streaming from such platforms. This is because it tends to be against their terms & conditions, and the streaming URLs are protected by javascript and server obfuscation.

**Comment by FedeGToto** [comment]
So that may be the problem? Should we try with other streaming platforms?

**Comment by Chris-RH** [comment]
That may be the problem.
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html
