### ISSUE TITLE
Android OES on Mesh: mesh seems to be reset in build

### ISSUE THREAD

**Issue by ThibaultDpt** [RenderHeads/UnityPlugin-AVProVideo#1437]
**Describe the issue**
Trying to display a video on a quad scaled (1.6,0.9,1) using MediaPlayer and ApplyToMesh components on Android using ExoPlayer and OES material. It works in editor, but when in build the quad looks like it is reset (a Log still show the correct scale and vertices potisions, but only a perfectly square quad is displayed at position 0.0.0) 

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.42 and 2021.3.11
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  Core version 2.7.1
 - Operating system version: Andoid 12
 - Device model: Pixel 3A
 - Video specs (resolution, frame-rate, codec, file size): Using the samples "Apple Bip Bop" and "Local-Mp4-Cones"

**To Reproduce**
1. Create a new project and switch platform to Android
2. Add AvPro
3. Create a quad and scale it/move it, and add a material with the Unlit OES AvPro shader
4. Add MediaPlayer (with one of the sample as reference) and an ApplyToMesh component
5. In platform specific settings check "use OES Rendering" and Exo Player
6. Build: the quad is now at the center of your screen and unscalled

**Logs**
The only warning I get is 
Warn Unity AndroidJNIHelper.GetSignature: using Byte parameters is obsolete, use SByte parameters instead
.
.
Warn Unity RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()

**Screenshots**
In Editor
![image](https://user-images.githubusercontent.com/60197846/212925717-2fafaf59-1357-493f-8508-df23840d13d5.png)

In Build
![Screenshot_20230117-083317](https://user-images.githubusercontent.com/60197846/212926355-7b1b9253-82c3-4263-b754-f088b45c76d0.png)

**Comment by ThibaultDpt** [comment]
Update: 
Putting a material with the Android OES shader on any object, with or without mediaPlayer, causes the same behaviour: the object has its transformation "reset"

**Comment by Ste-RH** [comment]
Are you using URP? If so, I think I have seen this before. Issue #480. It was down to the core projection matrix not carrying the correct transform at shader level.

**Comment by Chris-RH** [comment]
Was that the case @ThibaultDpt ?

**Comment by ThibaultDpt** [comment]
Sorry for the late reply! I cannot precisely test if it is the case, but looking at the thread Ste-RH linked, it looks like it is the same issue!

**Comment by Ste-RH** [comment]
Circling around on this issue.  It was reported to Unity a year or so after the initial issue thread linked.  Unity won't fix it, but do offer a work around.  You can see that [here](https://issuetracker.unity3d.com/issues/opengles3-glsl-shader-always-renders-in-0-0-0-position-when-built-and-deployed).  I have tested this workaround in AVPro Video v3.x and can confirm it did address the problem.
