### ISSUE TITLE
Quest shader issue with Oculus Link ( renders in one eye )

### ISSUE THREAD

**Issue by samueljonasson** [RenderHeads/UnityPlugin-AVProVideo#1439]
There is a rendering issue with the Transparent Packed (stereo) shader when using Oculus Link.  The video only renders in one eye.  The shader works perfectly in a build.

This is the shader:
`AVProVideo/Internal/UI/Transparent Packed (stereo) shader`

The setup:
- Unity 2021.3.15 LTS
- AVPro Ultra 2.7.1
- Windows 11
- Oculus Quest 2 and Oculus Pro

**Comment by Chris-RH** [comment]
What are your component settings?
What CPU and GPU are you using?
Is it single-pass or mulit-pass rendering?
What are the specs of the video?
Which eye is rendering? 
Is the other one just blank? 
Does the other eye render at all after some time?
So it works on the device, but not when using Oculus Link?
Is it the regular cabled Oculus Link or Oculus Air Link?

**Comment by samueljonasson** [comment]
My best attempt at clarifying these points:


> **What are your component settings?**

Not sure which components settings are most relevant but here are some:

- **Display uGUI** > Display In Editor ( checked )
- **Display uGUI** > Scale Mode = Scale To Fit
- **Display uGUI** > UV Rect ( default 0,0,1,1) 
- **Media Player** > Media is read from Streaming Assets
- **Media Player** > Fallback media hints: Transparency = Transparent, Alpha packing = Top bottom, Stereo Packing = Left Right
- **Platform specific settings ( Android )** > Video API = Exo Player
- **Platform specific settings ( Android )** > Use OES Rendering ( not checked )
- **XR Plugin Management setting**s > Android plugin provider = Oculus
- **XR Plugin Management settings** > Windows plugin provider = Oculus


> **What are your Link settings?**

Not sure about where I would find any specific Link settings.  We are using the official Link cable and Link is working for everything we do so I assume settings are ok.


> **What CPU and GPU are you using?**

- GPU Nvidia Geforce RTX 3080
- CPU AMD Ryzen 5 5600X


> **Is it single-pass or mulit-pass rendering?**

On the Android yab we are using Multiview and Low Overhead Mode.  Target device Quest 2 and Quest Pro
On the Windows tab we have Single Pass Instanced.  Changing this to Multiview renders the same frame on both eyes.

> **Is it SRP, URP or HDRP?**

URP


> **6) What are the specs of the video?**

- We are using this command from AVPro docs to convert a stereoscopic ProRes video with alpha to a top/bottom alpha packed video:
`ffmpeg -i input.mov -c:v libx264 -pix_fmt yuv420p -vf "split [a], pad=iw:ih*2 [b], [a] alphaextract, [b] overlay=0:h" -y output.mp4`
- The video is 4096 x 2048 ( 36fps, half of 72 )


> **Which eye is rendering?**

Left

> **Is the other one just blank?**

Blank


> **Does the other eye render at all after some time?**

No


> **So it works on the device, but not when using Oculus Link?**

Correct.  It works on the device after building and deploying.  Therefor I think it might be using a different shader in standalone mode. 


> **Is it the regular cabled Oculus Link or Oculus Air Link?**

Cable

**Comment by Chris-RH** [comment]
Have you tried AVPro/Unlit/Transparent ?

**Comment by samueljonasson** [comment]
Very interesting.  That works perfectly.  Now I am wondering why I was using the other shader.
