### ISSUE TITLE
Integration help

### ISSUE THREAD

**Issue by inno-zunaid** [RenderHeads/UnityPlugin-AVProVideo#1442]
Problem description:

I need to play encrypted m3u8 video but need to pass encryption key from outside. Able to play m3u8 video by providing the key path in file. But my requirement is to pass the encrypted key in file then write a code at player side to decrypt and pass it to the player. 
Does this supports this type of integration .

System Information:

AVPro Video: v2.7.1 (plugin v2.7.0f1-trial)
Target Platform: Standalone
Unity: v2020.3.24f1 WindowsEditor
OS: Desktop - 11T0S00200 (LENOVO) - Windows 10  (10.0.19045) 64bit - English
CPU: 12th Gen Intel(R) Core(TM) i5-12400 - 12 threads - 16099KB
GPU: Intel(R) UHD Graphics 730 - Intel - Direct3D 11.0 [level 11.1] - 8049KB - 16384

**Comment by MorrisRH** [comment]
That is supported. You just need to call SetOverrideDecryptionKey on the media player's Control interface for example:
```csharp
byte[] key = loadKey(); // Get the key from wherever
mediaPlayer.Control.SetOverrideDecryptionKey(key);
```
