### ISSUE TITLE
360 stereo video not stereo anymore with 2.7.1

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#1443]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
With AVPro 2.6.7 and 2.7.1 stereo 360 video (top/bottom) only shows the left (red when tinting is on) image for both eyes, both in Editor (with Android set as target) and when built (to Pico Neo 3 Pro).
Using Multipass rendering (PicoMobileSDK, non XR), with a PVRCameraRig with separate cameras for the left and right eye.
There's an Update Multi Pass Stereo component on the BothEye (center) camera.
Exact same scene works fine with AVPro 2.2.2f1.

Fallback Media Hints Stereo Packing is set to Top/Bottom
Apply To Mesh Automatic Stereo Packing is disabled
Override Stereo Packing is set to Top/Bottom
The sphere mesh material is using the AVProVideo/VR/InsideSphere Unlit shader
Stereo mode of the material set to Top_Bottom, Force Eye Mode None, Layout None

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.36f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.7.1 Ultra
 - Operating system version: Windows 10 x64
 - Device model: Pico Neo 3 Pro
 - Video specs (resolution, frame-rate, codec, file size):  4K 360 Top/Bottom MP4 video, H264

**Comment by Chris-RH** [comment]
Hi @RuudvanReenen,

Are you using SRP, URP or HDRP?
Have you tried using VR-InsideSphere-Transparent?
Is AndroidOES enabled?
Have you tried going back to basics with a new project with just our 360 demo scene and building up from there?

**Comment by Chris-RH** [comment]
Is this still a problem?

**Comment by RuudvanReenen** [comment]
Yes, still an issue, I've been using 2.2.2 instead.

- Using the built-in render pipeline with forward rendering.
- Not using Android OES
- Haven't tried a new project yet
- I'll check which SDK version of Pico this is exactly, they don't have an archive online anymore.

**Comment by Chris-RH** [comment]
How is it in a new project just with AVPro Video and the demo scene?

**Comment by RuudvanReenen** [comment]
Same issue with AVPro 2.7.2

**Comment by Chris-RH** [comment]
Using your scene with the Pico SDK, I updated from  2018.4.36f1 to 2021.3.16f1 and set up XR Plug-in Management.  Selected XRCore and changed it to Multipass, and it works.
Are you able to use a newer version of Unity?

**Comment by RuudvanReenen** [comment]
Hi Chris, with 2021 and XR there are no issues indeed. 
But I'm stuck with 2018.4 for some apps due to a major rewrite requirement to switch from UNET when using more recent Unity versions. And AVPro 2.2.2 works with 2018.4, but stereo display doesn't work anymore for 2.7.1 and 2.7.2.

**Comment by Chris-RH** [comment]
Have you tried copying the shaders from 2.2.2?

**Comment by Ste-RH** [comment]
Can you not update to any major Unity version?  Maybe 2019?

The problem will be rooted in lack of available shader level matrices to determine which eye is being rendered in each pass.  These have been seemingly randomly available over time in Unity, with them relying on VR SDKs in the main (until more recent versions of Unity).  There is essentially no solution, as the variables are just not available.  Updating Unity is your only option.

As a side note, Unity do not even let us build packages with 2018 any more!  I understand legacy projects and the risks of changing Unity versions, but if this is a blocker, you have a choice to make.  No stereo videos, or update.  I would try Unity 2019.

**Comment by RuudvanReenen** [comment]
UNET was dropped after 2018 and this app heavily uses UNET for networking. Rewriting all networking to use Mirror or something similar is not feasible for this one. Weird that AVPro 2.2.2 does work though, I'll just stick with that version for this app.

**Comment by RuudvanReenen** [comment]
Yes, 2.2.2 works

**Comment by Ste-RH** [comment]
Try replacing \Assets\AVProVideo\Runtime\Shaders\AVProVideo.cginc in whatever latest version you are using (2.7.1?) with this one.  Can't promise it will work, and watch for any shader compile issues.

[AVProVideo.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/10755543/AVProVideo.zip)

**Comment by RuudvanReenen** [comment]
Awesome, that works! No shader compile issues.

**Comment by Ste-RH** [comment]
Excellent.  A few caveats.

1) You will have to replace that file if you update AVPro Video version again to a newer version.
2) I doubt OES mode will work.

**Comment by RuudvanReenen** [comment]
I've removed that reply, it seemed to work, but left eye kept switching between green and red when looking around, but not consistently. But for this app I'll just stay with 2.2.2, deadline is approaching. Majority of my work is with Unity 2021 and XR which works great, also with the latest updates.

**Comment by Ste-RH** [comment]
And you don't get that with 2.2.2?

You have the UpdateMultiPassStereo component on your camera, yeah?  You are using MultiPass (not multiview), yeah?

**Comment by Chris-RH** [comment]
Closed due to lack of reply
