### ISSUE TITLE
Failed to fetch original file descriptor

### ISSUE THREAD

**Issue by joywater** [RenderHeads/UnityPlugin-AVProVideo#1444]
when I play video on a xiaomi mobile, I have this error and the video can not play
![image](https://user-images.githubusercontent.com/25529669/217182823-02164253-fe50-4e52-812e-f42bc59e883e.png)
![image](https://user-images.githubusercontent.com/25529669/217184013-6b30c3ab-e0b8-4bae-b135-7d7e798e5edf.png)

whether I can know whether I can play the video earlier，Like:
if(supportsTranscode(path))
{
      play();
}

Thanks!

**Comment by Chris-RH** [comment]
Hi @joywater 

1. Could you test it just using our Mediaplayer demo please?
2. Have you tested our included videos?
3. What are the specs of the video you are trying to play?
4. Are you able to link to your video or email the link to us [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by joywater** [comment]
Thanks，my AVPro‘s version is AVPro Video - Ultra Edition 2.6.5
I just test it using Your demo:
1. the demo is correct
2. when I relace one video with mine,it can not play on the Redmi Note 12 5G, but can play on the Redmi Note 10 Pro 
3. I have send my mp4 file to your email,please check it!

**Comment by Chris-RH** [comment]
Can you update to the latest version of AVPro Video and then retry using our demo scene and your video please?
Are you able to provide a full logcat of the error please?

**Comment by joywater** [comment]
@Chris-RH 
I had test the video use the version  2.7.2-Trial, and the video can not play correctly also!
I mean if there is some interface I can preknow whether the video can play correctly,if can play, then I will play the video, and if can not,maybe I will skip play the video!
Thanks!

**Comment by Chris-RH** [comment]
There isn't always sufficient feedback from the API as to why it can't play a file.  
If you are streaming the video files, could you set up manifest with multiple resolutions? Or do you not control the videos that are being played?
