### ISSUE TITLE
Malfunction in Android URP

### ISSUE THREAD

**Issue by cseheon** [RenderHeads/UnityPlugin-AVProVideo#1445]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.15f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Core Edition 2.7.1
 - Operating system version: Android All.
 - Device model: Android All.
 - Video specs (resolution, frame-rate, codec, file size): None

**To Reproduce**

hello.

We have been using AVPro for a long time, and we think that we have been fully aware of and solved various problems.

Recently, our project switched from legacy shader to urp and we are fixing various problems.

We found a critical bug in AVPro in the Android build and we haven't found a solution yet.

The video screen using ApplyToMesh is outputting to random object vertices instead of the positions we set.

It already fires before playing the video.

For example, the video screen is flying in the sky with the video screen attached to the vertices of a seagull in the environment, rather than at the video screen location we set.

I would like to know if this issue has been reported and if there is a solution.

For reference, this is a phenomenon that only occurs on Android, and we are using OES.

**Comment by Chris-RH** [comment]
Is it the same as this: Issue https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/480. It was down to the core projection matrix not carrying the correct transform at shader level.

**Comment by cseheon** [comment]
@Chris-RH 
It seems to be the same problem. I've already seen the issues mentioned, but I don't know how I can find a solution.

**Comment by Chris-RH** [comment]
I don't believe there was a solution, as it seems to be a Unity problem

**Comment by cseheon** [comment]
There was a mistake in my test. This only seems to happen when using Android OES.

**Comment by Ste-RH** [comment]
This is a Unity bug.  We cannot offer a solution unfortunately.

**Comment by Ste-RH** [comment]
Circling around on this issue.  It was reported to Unity a year or so after the initial issue thread linked.  Unity won't fix it, but do offer a work around.  You can see that [here](https://issuetracker.unity3d.com/issues/opengles3-glsl-shader-always-renders-in-0-0-0-position-when-built-and-deployed).  I have tested this workaround in AVPro Video v3.x and can confirm it did address the problem.
