### ISSUE TITLE
Unable to play video from absolute path

### ISSUE THREAD

**Issue by inno-zunaid** [RenderHeads/UnityPlugin-AVProVideo#1448]
Problem description:

I have the m3u8 video file store at my pc D: drive providing that path under Absolute path to player works on editor but when I build and play getting error **"File not found"**

AVPro Video: v2.7.1 (plugin v2.7.0f1-trial)
Target Platform: WSA
Unity: v2020.3.24f1 WindowsEditor
OS: Desktop - 11T0S00200 (LENOVO) - Windows 10  (10.0.19045) 64bit - English
CPU: 12th Gen Intel(R) Core(TM) i5-12400 - 12 threads - 16099KB
GPU: Intel(R) UHD Graphics 730 - Intel - Direct3D 11.0 [level 11.1] - 8049KB - 16384

**Comment by MorrisRH** [comment]
In the editor you're just running the windows plugin so ```D:``` exists and files can be played from there.

When using WSA you're running in an Android environment and it has no knowledge of your Windows system so is unable to access your ```D:```. You will need to copy your files into the android instance or make them available via http.

**Comment by inno-zunaid** [comment]
Hi @MorrisRH I build the application for UWP platform and running it on same pc. Still it is unable to access that path.
Also have issue when tried playing the video via http still not able to play after build.  In Editor it is working with both absolute path and url.
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
tried with this url but it fails to play in UWP build working in editor.

**Comment by inno-zunaid** [comment]
playing video with url issue is resolved. Issue was of firewall from my end.
