### ISSUE TITLE
Buffer persistence on seek

### ISSUE THREAD

**Issue by ignacio-fsstudio** [RenderHeads/UnityPlugin-AVProVideo#145]
**Is your feature request related to a problem? Please describe.**
Upon seeking forward from videos streamed through HTTP on parts of the video that have not been buffered yet the buffering process skips to that section of the video, but when you seek back on places that have already been buffered those chunks have been unloaded and the buffering process needs to resume.

I've also noticed that the buffering sometimes stops and waits for the playback to catch up before resuming the buffering which on long videos means there's a substantial amount of pausing the playback.

**Describe the solution you'd like**
It would be nice if we had finer control of the buffering process and the buffering method (linearly download the file and play unbuffered parts when the buffer catches up vs buffer from the selected time onwards). It would also be nice to keep the data already downloaded in memory so that we can seek to it quickly.

**Describe alternatives you've considered**
If we had control to linearly download the file so that we can seek to the previously downloaded parts easier that'd be a first step, but also have options regarding the prefetching logic, so that we can download the whole video into the memory buffer instead of having to wait for the playback/seeking to catch up.

**Comment by AndrewRH** [comment]
Thanks for the suggestion :)

**Comment by AndrewRH** [comment]
This is a very old issue for version 1.x of the plugin.  Version 2 improves a lot of the buffering behaviour so closing this thread.
