### ISSUE TITLE
Android Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources. 

### ISSUE THREAD

**Issue by BensonMaZIHao** [RenderHeads/UnityPlugin-AVProVideo#1450]
I played the video on android superior directly crash, prompt Log。
Phone model: Mi 11
Video Type: Black & White Channel MP4
Number of videos: 5
Video resolution: 800*600
Why do I get an error when I have no high parameters。
What is the problem video? A cell phone? Is there a god who can fix it?

**Comment by BensonMaZIHao** [comment]
Avpro Version: 2.4.x

**Comment by BensonMaZIHao** [comment]
Avpro Version: 2.4.x
Unity Version :2019.4.33.x

**Comment by Ste-RH** [comment]
v2.4.x is very old now. Can you tried updating to the latest version?

As a minimum, we will require a full log at output in order to help.

**Comment by King-1997-King** [comment]
@Ste-RH  Hello, I have encountered the same issue where the app crashes while trying to play videos on Android. Below is my error log, could you please help me locate the cause of the issue? Thank you.
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/10753122/log.txt)

**Comment by King-1997-King** [comment]
Your callback resolved my issue, thank you.

**Comment by Chris-RH** [comment]
@yeximoon

We need at least the following: 
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size, local or streaming, etc): 
 - Link to video if possible
 - Logcat

**Comment by Chris-RH** [comment]
We can't help without more info, thank you.

**Comment by BensonMaZIHao** [comment]
Unity version:2019.4.33f1c1
AVPro Video version (number and edition (trial/core/ultra/enterprise)):AVPro Video - Core Edition 2.7
Operating system version:Android 12 华为鸿蒙
Device model:小米 11 
Video specs (resolution, frame-rate, codec, file size, local or streaming, etc):Black and white channel video 440*880 25.0Frame FileSize：146 KB
Logcat：Play is only seen Android Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by Ste-RH** [comment]
@BensonMaZIHao without a full log at output we cannot begin to diagnose the issue. Please provide this to either this thread, or send it over to unitysupport@renderheads.com

**Comment by BensonMaZIHao** [comment]
All right, I'll go and record it

> @BensonMaZIHao without a full logcat output we cannot begin to diagnose the issue. Please provide this to either this thread, or send it over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

All right, I'll go and record it

**Comment by BensonMaZIHao** [comment]
> [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

I have addressed to unitysupport@renderheads.com
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/10801896/log.txt)

**Comment by Ste-RH** [comment]
Could this be the characters used in your filename? These get logged as;

2(ä¸‰æŒ‡æŽ¨åŽŸç‰‡).mp4

Can you try renaming the video filename? That will at least give us something to look into if it is the problem.

**Comment by BensonMaZIHao** [comment]
> 这可能是您的文件名中使用的字符吗？这些记录为：
> 
> 2（ä ̧‰æŒ‡æŽ ̈åŽŸç‰‡）.mp4
> 
> 您可以尝试重命名视频文件名吗？如果这是问题所在，这至少会给我们一些可以研究的东西。

Ok, I'll test it again after I change the file name

**Comment by BensonMaZIHao** [comment]
> 这可能是您的文件名中使用的字符吗？这些记录为：
> 
> 2（ä ̧‰æŒ‡æŽ ̈åŽŸç‰‡）.mp4
> 
> 您可以尝试重命名视频文件名吗？如果这是问题所在，这至少会给我们一些可以研究的东西。

I retested a transparent video with the same result as my previous test. I found that the transparent video in black and white channel can only display three at the same time and at most three at the same time. Does this have anything to do with Shader (AVProVideo-Internal-UI-Default-Transparent)?

**Comment by BensonMaZIHao** [comment]
This is fine on a PC, but now a lot of people are on Android or AndroidVR devices.
Do other people have other solutions?

**Comment by BensonMaZIHao** [comment]
> Could this be the characters used in your filename? These get logged as:
> 
> 2(ä¸‰æŒ‡æŽ¨åŽŸç‰‡).mp4
> 
> Can you try renaming the video filename? That will at least give us something to look into if it is the problem.

I ran a total of five black and white channel trans parencies and only showed three with two errors.
[logTwo.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/10812453/logTwo.txt)

**Comment by Ste-RH** [comment]
Every Android device will be limited at some level with how many videos it can play back at the same time.  Factors include - resolutions, bitrates. framerates, codecs, the hardware in the device.  If you can play each video by themselves, then the playback system is working as it should.  If it is multiple videos played together you are find issues with, then that is as above - just the limitations of the device.

**Comment by Ste-RH** [comment]
The only possible solution would be to playback some of the videos as 'software decoded'.
