### ISSUE TITLE
Unable to output multiple audio tracks from Video

### ISSUE THREAD

**Issue by TomDdotExe** [RenderHeads/UnityPlugin-AVProVideo#1452]
Hey there,

I'm currently working on a VR prototype that utilises a video that has three audio tracks, two for dialogue and one for sound effects. 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/125573376/219380798-d4bc80fb-fb13-46ae-a910-9ffe78b9d73e.png">

I initially attempted to combine the audio tracks by using an Audio Output Component on the media player, but it only seems to output tracks 1/2, with track 3 not outputting at all.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/125573376/219381217-47cf3d46-ba48-454a-9be3-3b07f5c74f9c.png">

Is this a known issue with a known solution? I'm relatively new to Unity engine so I'm hoping this is just a rookie error on my part! Thanks

 - Unity version: 2021.3.18f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.7.0f1-trial
 - Operating system version: Windows 11
 - Device model: OculusQuest2/Windows
 - Video specs (resolution, frame-rate, codec, file size): 5760x5760, 29.97, H265, 579Mb

**Comment by Chris-RH** [comment]
Hi @TomDdotExe,

1. Is this occurring in Windows editor, build on android device, or both?
2. Have you tried opening the file just using our Mediaplayer demo scene?
3. Are you able to attach the file in question or email [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com?subject=Issue%231205)

**Comment by Chris-RH** [comment]
Thanks, we'll have a look at the file and have a think about it :)

**Comment by Chris-RH** [comment]
Hi @TomDdotExe,

We've had a think about this.  Its not something that we can support as its unlikely that we could get it to work across all platforms.

A couple of workarounds that we can suggest:

- Pull the audio tracks into their own files and have multiple players. 
- Pull out the background music audio track and play it as an audio clip in a separate AudioScource
- Playback the video multiple times together...one does image frames and primary audio track, other player(s) do the other audio desired
