### ISSUE TITLE
QC2Interface - Error: Failed to query parameters

### ISSUE THREAD

**Issue by GabrielRosenberg** [RenderHeads/UnityPlugin-AVProVideo#1454]
When a video is playing on an android device, I receive the error `QC2Interface  E  Failed to query parameters ` in Logcat. It is raised with a constant interval when the video is playing but not when it is paused. I don't see any errors when I test the player in Unity editor. I can't find much information on what this issue could be related to. The video player appears to work when playing a video. 

**Setup:**
 - Unity version: 
 2019.4.40
 - AVPro Video version: 
 Ultra 2.6.5
 - Operating system: 
 Android
 - Device model: 
 OnePlus 10 Pro

**Comment by Chris-RH** [comment]
Hi @GabrielRosenberg 

1. Could you update to the latest version of AVPro Video please
2. Do you get the same issue when you make a new project with just the AVPro Video Mediaplayer demo scene and build to your device?
3. Are you playing the video locally or streaming?
4. If streaming, do you get the same result from these test streams (https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#test-streams)
5. Can you provide us with a full logcat please
