### ISSUE TITLE
IsMediaCachingSupported always returning false

### ISSUE THREAD

**Issue by YleduDev** [RenderHeads/UnityPlugin-AVProVideo#1455]
Same problem with #1063, the latest version still exists

Unity version: v2020.3.24f1c1 WindowsEditor
AVPro Video version: v2.7.3 (Core Android Edition)
Operating system version: tested on both Android 8 and Android 10
Device model: tested on both PICO4 and Oculus Quest 2

**Comment by MorrisRH** [comment]
Media caching is available with the ultra edition on Android and iOS only

**Comment by YleduDev** [comment]
Core Android Edition ？

**Comment by YleduDev** [comment]
I am using the Android version, but IsMediaCachingSupported is always returning false

**Comment by Chris-RH** [comment]
Caching is not available in Core Android Edition, it is Ultra Edition only.
For more info on what is supported in each Edition, see here:
https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions

**Comment by YleduDev** [comment]
ok
