### ISSUE TITLE
Error regarding versions is thrown in shipped iOS builds

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProVideo#1459]
Hi! We're on the Pro version of 2.7.3.
When we deploy our game on iOS via Testflight the following error is thrown (we subscribe to the Debug.Log error handler and display them). Oddly, we don't see this error on builds run from XCode - we have to get them to Testflight via AppStore Connect first.
<img width="332" alt="image" src="https://user-images.githubusercontent.com/1252816/221200291-8c2abf42-962b-4cbb-b191-e43ce90437d5.png">

Error is:
`[AVPro Video] Plugin version number 3.0.0-ultra build 1 doesn't match the expected version number 2.7.3. It looks like the plugin didn't upgrade correctly. To resolve this please restart Unity and try to upgrade the package again.`

Does anyone have any ideas?

**Comment by MorrisRH** [comment]
Think this is the same as #973

**Comment by tomkail** [comment]
Yup! Ta!
