### ISSUE TITLE
On the iphone, can pause video with airpods

### ISSUE THREAD

**Issue by whitecostume** [RenderHeads/UnityPlugin-AVProVideo#146]
**Describe the bug**
On the iphone, you can pause video with airpods, but it won't continue

**Your Setup (please complete the following information):**
 - Unity version: Unity2018.4.1
 - AVPro Video version: 1.7.3
 - Operating system version:  ios12
 - Device model: iphone7

**To Reproduce**
1. Use AirPods when playing video
2. Put down the AirPods and video will pause automatically
3. Video cannot continue automatically

**Comment by AndrewRH** [comment]
First of all, I recommend you upgrade your AVPro Video version as 1.7.3 is extremely old.   

I believe this pausing behaviour is part of how iOS works - it automatically pauses media.

Try the new version of AVPro Video - does it help?

Thanks,

**Comment by whitecostume** [comment]
> First of all, I recommend you upgrade your AVPro Video version as 1.7.3 is extremely old.
> 
> I believe this pausing behaviour is part of how iOS works - it automatically pauses media.
> 
> Try the new version of AVPro Video - does it help?
> 
> Thanks,
Upgraded to 1.9.17, but the problem is still there

**Comment by whitecostume** [comment]
> First of all, I recommend you upgrade your AVPro Video version as 1.7.3 is extremely old.
> 
> I believe this pausing behaviour is part of how iOS works - it automatically pauses media.
> 
> Try the new version of AVPro Video - does it help?
> 
> Thanks,

Well..Upgraded to 1.9.17, but the problem is still there

**Comment by MorrisRH** [comment]
On iOS, audio route changes (such as unplugging headphones or putting down the AirPods) always causes media playback to pause.
We recommend that you listen for the paused event flag on the media player, and if it occurs unexpectedly then resume playback yourself or offer a mechanism for the user to resume playback.

**Comment by whitecostume** [comment]
Ok, that's settled. Thank you
