### ISSUE TITLE
[iOS] Can't open .mp4 files via https url on iPad

### ISSUE THREAD

**Issue by ApzSK** [RenderHeads/UnityPlugin-AVProVideo#1462]
**Describe the issue**
Opening mp4 video via https url throws "Loading failed. File not found, codec not supported, video resolution too high or unsufficient system resources.". Solution works fine on Windows (standalone and UWP). Loading the same video via StreamingAssets (MediaReference) works fine.

**Your Setup (please complete the following information):**
 - Unity version:  2021.3.18f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.7.3 core
 - Operating system version: Windows 11 Enterprise(latest) -> macOS 12.6.3 -> iPadOS 16.3.1
 - Device model: iPad 8
 - Video specs (resolution, frame-rate, codec, file size): 480p up to 1440p, 24/30/60 framerate, H264 - MPEG-4 AVC codec, file sizes 3-50 MB

**To Reproduce**
1. Use MediaPlayer's OpenMedia(MediaPathType.AbsolutePathOrURL, someRandomUrl, true)
2. In someRandomUrl set up https link
3. Build on Windows
4. Zip solution and copy to Mac
5. Build on Mac
6. Deploy on iPad
7. Open video scene - error occurs

**Comment by ApzSK** [comment]
Sent an email. Please have in mind that link might expire in short time, so please verify it soon.

**Comment by MorrisRH** [comment]
Replied on email but copying here for convenience.

The full error being generated is as follows (slightly edited for legibility):

```
Error Domain=AVFoundationErrorDomain
Code=-11850 "Operation Stopped"
UserInfo={
    NSUnderlyingError=0x28125d0e0 {
        Error Domain=CoreMediaErrorDomain
        Code=-12939 "content range mismatch - should be start 0 length 2 is start 0 length 0"
        UserInfo={
            NSDescription=content range mismatch - should be start 0 length 2 is start 0 length 0, 
            NSURL=...
        }
    },
    NSLocalizedFailureReason=The server is not correctly configured.,
    NSURL=...,
    NSLocalizedDescription=Operation Stopped
}
```

It looks like your server isn't configured quite right. Unfortunately there is nothing we can do from our side about this as it's iOS that is failing the request.
