### ISSUE TITLE
Multiscreen Video Player - Windows

### ISSUE THREAD

**Issue by heritageint** [RenderHeads/UnityPlugin-AVProVideo#1463]
Having performance issues trying to create a simple multiscreen (dual) video playback app.  Adding a single MediaPlayer and Display uGUI plays my test video correctly at target 30 FPS (in Editor).  If I open another Game tab, the FPS drops to 15FPS - is this expected?

The target app will have two screens, and needs to cross fade between videos on each display, so assumed 4 MediaPlayers would be required and thought this was the initial problem, but just opening a 2nd Game window affects the FPS.

Unity Version 2021.3.1f1
AVPro Video Core 2.7.3
Windows 10 Pro 64-bit
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz   3.00 GHz - 16GB RAM
nVidia GeForce GT1030

Test Video - 1690x1200 30FPS h264 26mb (though same result with any video)

**Comment by Ste-RH** [comment]
The GT1030 is not a very powerful or modern GPU. If you open task manager and look at the performance tab you will get a better idea of how much load decoding your 4 videos and rendering to two screens is having. Do send over screen grabs.

**Comment by Chris-RH** [comment]
Do you get any improvement when using winRT or Directshow?

**Comment by Ste-RH** [comment]
Sounds like it bottlenecking elsewhere then. Your CPU load looks very high.

I advise you profile what’s happening with the Unity profiler.

**Comment by heritageint** [comment]
WinRT seems to hold at target 30 FPS, DirectShow dropped to same rate as MediaFoundation.  Will add all elements removed back into the project and test running with WinRT.

**Comment by Chris-RH** [comment]
How is it looking?

**Comment by heritageint** [comment]
Rebuilt dual screen application yesterday - two video players on each screen to allow for cross fade (videos only play together when switching) - set to WinRT runs fine in Editor and maintains target 30FPS, however once built (Windows 64-bit) the video shows tearing/stuttering which was our original problem, before noticing the drop in FPS within the Editor.

Tearing is not displayed using VLC or Windows Media Player.

**Comment by Chris-RH** [comment]
Could you see what's happening with Unity profiler (with MediaFoundation and WinRT) please?

**Comment by Chris-RH** [comment]
Any more info OP?

**Comment by heritageint** [comment]
Apologies, after various tests we found the tearing issue was due to VSync being disabled in Unity, once enabled this removed the tearing issue, so no issues with the AVPro Media Player.
