### ISSUE TITLE
Hls is not defined

### ISSUE THREAD

**Issue by LordLegionKeygard** [RenderHeads/UnityPlugin-AVProVideo#1464]
Unity version: 2021.3.2f1
AVPro Video version (AVPro Video - Core Windows Edition):
Operating system version: Windows 10 Pro

I get an error hls is not defined on webgl.

I turned on hls in mediaplayer.
![image](https://user-images.githubusercontent.com/76789721/221845470-dfeca301-d3a9-445d-bc9c-f5d0406b942e.png)

Put hls.min.js in TemplateData
![image](https://user-images.githubusercontent.com/76789721/221845616-0a45bc64-8410-4051-acc8-8b6a60e1b1c2.png)

And wrote string in index html before unity.load
![image](https://user-images.githubusercontent.com/76789721/221845857-d552b8d7-fd45-4f6a-beff-5163a0c47f93.png)

What's my mistake?

**Comment by LordLegionKeygard** [comment]
But i have other problem, i have two index.html and have backend and front

**Comment by Chris-RH** [comment]
Please note: We do not officially support WebGL, but only include it as it may be useful for some people. We found too many issues with browser compatibility to continue supporting it.

Please make sure you have read our section on WebGL streaming: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl

**Comment by LordLegionKeygard** [comment]
![photo_2023-02-28_15-17-20](https://user-images.githubusercontent.com/76789721/221852775-6a516a63-f8a9-4baf-bb7f-dcab47585589.jpg)

I can fix Corsa from youtube?
