### ISSUE TITLE
Broadcasts

### ISSUE THREAD

**Issue by LordLegionKeygard** [RenderHeads/UnityPlugin-AVProVideo#1465]
Please tell me how your player downloads live broadcasts. I noticed that you upload 30 seconds of video and it rewinds by 5 seconds while continuing to work, how your plugin working with that?

**Comment by Chris-RH** [comment]
This is WebGL? On what device?
What do you mean " rewinds by 5 seconds while continuing to work"?

**Comment by LordLegionKeygard** [comment]
![image](https://user-images.githubusercontent.com/76789721/222434786-c9ff4b67-5cf1-4d78-9717-e97f2da27f8e.png)
that slider in unity

**Comment by LordLegionKeygard** [comment]
https://user-images.githubusercontent.com/76789721/222436925-3a5a106b-60ae-4c6a-ba8b-98d3adfa632d.mp4
