### ISSUE TITLE
Using AVPro Video In Oculus

### ISSUE THREAD

**Issue by HaHA3507** [RenderHeads/UnityPlugin-AVProVideo#1466]
When I Using Avprovideo, it can work on editor,but when i use it in oculus2, it was ammed and no sound for loading local video. If i turn off the oculus and then turn, it can work! This question make me very terrible.

**Comment by Chris-RH** [comment]
Are you playing it from Streaming Assets or Application.persistentDataPath?
What are the specs of the video?

**Comment by HaHA3507** [comment]
>The video in Application.persistentDataPath.And MP4

**Comment by HaHA3507** [comment]
> Are you playing it from Streaming Assets or Application.persistentDataPath? What are the specs of the video?

In oculus, he can load the video, but it can only be played for a few seconds, and it will stop, and there is no sound when playing. Only when I turn off the power button of oculus and turn it on again, can the video have sound and play smoothly

**Comment by Chris-RH** [comment]
Unity version: 
AVPro Video version (number and edition (trial/core/ultra/enterprise)):
Device model: 
Video specs (resolution, frame-rate, codec, file size):

Does the same file work when played from Streaming Assets?

**Comment by HaHA3507** [comment]
> Unity version: AVPro Video version (number and edition (trial/core/ultra/enterprise)): Device model: Video specs (resolution, frame-rate, codec, file size):
> 
> Does the same file work when played from Streaming Assets？

This is not the case in the previous use, but it is caused by not knowing what is set

**Comment by Chris-RH** [comment]
I need a bit more information please

- Unity version:
- AVPro Video version (number and edition (trial/core/ultra/enterprise)):
- Video specs (resolution, frame-rate, codec, file size):
- Does the same file work when played from Streaming Assets?
- Have you tried playing other videos from the same location?
- Does it stutter and then play eventually or does it just not play at all until you reset your Quest2?

**Comment by HaHA3507** [comment]
(1)Unity Version 2019.4.36
(2)AVPro Version 2.0.1 edition
(3)A small mp4 video,,only 2mb
(4)Never tried
(5)all video in Application.persistentDataPath can't work.
(6)Before resetting, it will only play the first few seconds of the video. At this time, if I forward the video, it can play for five seconds.In this process, the video is silent.And then I reset it, that can have sound and play smoothly .This problem occurs when the Media Player component is reloaded

**Comment by Chris-RH** [comment]
OK, first update to the latest version of AVPro Video and try again please

**Comment by HaHA3507** [comment]
However, the media player in the apk I packed a few months ago can work normally. I suspect that there is a problem with the setting of my unity

**Comment by HaHA3507** [comment]
> 好的，请先更新到最新版本的 AVPro Video 再试一次

I have upgraded to the latest version, but the problem still exists

**Comment by Chris-RH** [comment]
OK, So it did work a few months ago? What has changed?
Is it a completely new project?
Different Unity version?
Different device?

**Comment by Ste-RH** [comment]
Please send over a full logcat. We will also require the video you are seeing issue with to help diagnose the issue. You can email it over to unitysupport@renderheads.com if you wish to keep it private.

One question. Do you see this issue playing back your video in our Media Player demo scene?

**Comment by Chris-RH** [comment]
We can't really help without more info, please
