### ISSUE TITLE
Unable to playback video from multiple 360 spheres in Android/Quest 2 build

### ISSUE THREAD

**Issue by TomDdotExe** [RenderHeads/UnityPlugin-AVProVideo#1467]
Hey again,

In my project I have four projection spheres, all set up with their corresponding media players. I then have a menu that deactivates the landing projection sphere, activates the video sphere, which then auto-toggles playback. All videos are being stored locally within StreamingAssets.

In the windows build of my project, I am able to stop each video, return to the menu, and playback another video without issue. But upon compiling and testing in headset I find that attempts to open further videos result in the video not loading, causing the landing sphere to deactivate leaving the user staring out at the unity skybox. I'm able to open the landing sphere and a first video sphere, but anything past that doesn't render in-game. Is there a more advisable method for streaming multiple videos for android builds? Thanks

**Your Setup (please complete the following information):**
 - Unity version:  2021.3.18F1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.7.0F1-TRIAL
 - Operating system version:  Android
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size):  5760x5760. 29.97. h265. 580mb.

Thanks as always

**Comment by TomDdotExe** [comment]
Changing the Android Video API to Exoplayer results in the app hard freezing instead of just displaying the skybox. Seems to hard freeze the entire headset requiring a restart to be able to run the app again.

**Comment by Ste-RH** [comment]
You are trying to have four 5760x576 videos open at the same time?  No Android device on the planet will allow you to do that.  The hardware just is not specified for it - that is a very high resource demand.

Open one, close it fully before opening another.  You may even have to Destroy the player completely to be sure no SDK level resources are held on to.  Ideally you would use just one MediaPlayer and open a new video each time you want to change asset.

**Comment by TomDdotExe** [comment]
It hadn’t been my intention to have all four videos open at once - I’d been
making each player and sphere active/inactive depending on usage, but it
sounds like I need to go down the route of consolidating the non landing
page media players to do so efficiently instead.

I’ll get that done now and hopefully report back as issue solved!

Thank you
