### ISSUE TITLE
Load Button

### ISSUE THREAD

**Issue by LordLegionKeygard** [RenderHeads/UnityPlugin-AVProVideo#1468]
Please tell me what script executes the method of this button Load
![image](https://user-images.githubusercontent.com/76789721/222509375-a288c67e-92a3-48d1-810c-117e26bbd551.png)

I want find your get request on url

**Comment by LordLegionKeygard** [comment]
![image](https://user-images.githubusercontent.com/76789721/222683258-523799d3-84ff-4030-90a4-db5345da8072.png)
i found you use this script for get request on url, i want change header, but i cant find this loader in unity script

**Comment by MorrisRH** [comment]
That particular piece of UI is implemented in ```MediaPlayerEditor_Source.cs```.
We provide facilities for adding custom http headers in the platform specific section of the media player settings, see [here](https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---windows)

**Comment by LordLegionKeygard** [comment]
When you load file, your plugin use get request?
