### ISSUE TITLE
Audio Redirection sometimes not working on Windows

### ISSUE THREAD

**Issue by xanxys** [RenderHeads/UnityPlugin-AVProVideo#147]
**Describe the bug**
Sometimes, audio is not redirected to unity.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.14f1 & 2019.1.9f1 (both)
 - AVPro Video version: v1.9.17
 - Operating system version: Windows 10
 - Device model: 
     - HTC Vive headset on Windows 10 (almost 100% reproducible for certain users)
     - some non-VR Windows desktop (low probability)
 - Video specs (resolution, frame-rate, codec, file size): 
   HLS mp3 audio & HLS video, and the issue happens for both cases. It's not data-dependent.

**To Reproduce**
1. play audio (network URL)
2. sometimes audio is not redirected to Unity AudioMixer, instead it seems directly fed to Windows OS (manifests as non-working AudioMixer volume)

We also know there's a workaround of device-switching which is working 100% of the time so far.
1. Switch audio playback device to non-VR audio device in Windows
2. Launch our unity app
3. Switch audio playback device back to VR audio device
4. Start audio/video playback
(audio is properly streamed to AudioOutput component)

**Logs**
No error / warning.

**Comment by AndrewRH** [comment]
Hi,

This isn't an issue that we're aware of.  It would help us if you were able to reproduce it using a simpler setup (ie, not having a VR headset).  I'm not sure at this stage if it's caused by the VR headset switching the default audio device, or something else...  And can you make it happen with a local video file instead of a HLS stream?

Perhaps you could also email us a basic scene that shows the issue for you.

Thanks,

**Comment by xanxys** [comment]
After some investigation, we managed to reproduce it with minimum setup & with more devices.

**Sample Unity Project**
(sent to unitysupport@renderheads.com / we're ~@cluster.mu)
It repro-ed with Apple's HLS video stream (their server should be pretty stable), but **not with local files**.

**Device / Environment**
We managed to repro with a few bluetooth devices.
e.g. 
* Bose Mini 2 Sound Link
* Apple airpods
* IA-BT7 speaker https://gyazo.com/2f244318a0a01406ed8f9cee689a0bb3

However, we couldn't identify the root cause to be the bluetooth, because HTC vive headset uses wired USB audio, AFAIK.

Hope this helps with the investigation.

**Comment by I-K0haku-I** [comment]
Perhaps this can help in finding the solution somehow:

We found out that it does not work for people who have the "wrong" default audio device.
For some reason there are two for the Vive. I think one is for the GPU connection and the other is over USB?

![image](https://user-images.githubusercontent.com/49315243/69377699-1a662a00-0cad-11ea-9c44-f6940ad926e4.png)

When people, who did not hear anything, enabled the GPU one and reloaded, it started working flawlessly again.

**Comment by AndrewRH** [comment]
This could possibly some sort of ordering issue.. Where Unity switrches the default audio device when entering VR mode, but our plugin already has started on the previous audio device...
