### ISSUE TITLE
D3D Crash During Video Seek

### ISSUE THREAD

**Issue by sgh-msg** [RenderHeads/UnityPlugin-AVProVideo#1471]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
While attempting to seek on a video file, we encountered a low level crash within D3D 

**Your Setup (please complete the following information):**
 - **Unity version:** 2022.1.3f1 HDRP D3D12
 - **AVPro Video version:** AVPro Video (Enterprise) v2.7.0
 - **Operating system version:** Windows 10 19044.2604
 - **Device model:** Nvidia RTX8000 30.0.14.9649
 - **Video specs (resolution, frame-rate, codec, file size):** notchlc (nclc / 0x636C636E), yuva444p12le(pc, gbr/bt709/iec61966-2-1), 8192x8192, 7191170 kb/s, 60 fps, 60 tbr, 15360 tbn (default)

**To Reproduce**
1. Begin playing notchlc file on loop
2. Occasionally seek within the file 
3. Crash eventually occurs after repeated seeks

**Logs**
Will follow up in email with stack trace and crash dump

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
(responded via email)

**Comment by Chris-RH** [comment]
Have you had any improvement in this after updating to AVPro Video version 2.8.4?
