### ISSUE TITLE
Understanding orientation/rotation metadata

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProVideo#1472]
Hi! We've noticed that video files can have metadata that tells whatever is rendering them to rotate. For example, videos recorded on a portrait iPhone are _actually_ landscape, according to AVPro's `Player.Info.GetVideoWidth()`, but they're marked to be rotated 90 degrees and so aren't actually rendered like that by AVPro, VLC or any other video players.
The only giveaways are that the AVPro texture size of this potrait video is landscape, and that the preview GUI for DisplayUGUI renders them in landscape.

Here's a video showing that. You can see that the video's size matches that of the rect transform; but it's rotated and stretched compared to the inspector preview of the actual texture! This occurs because actually the width and height should be swapped, because it's 90 degrees rotated. But there's no way to get this information that I can see.
![image](https://user-images.githubusercontent.com/1252816/222589405-c0e3ff10-9bbc-4b67-92ff-a4f7780dac1c.png)

Can someone shed some light on exactly how AVPro handles this, and what can be done to compensate for it?

**Comment by MorrisRH** [comment]
You can use ```mediaPlayer.Info.GetTextureTransform()``` to get the required transform for the texture.
We also provide helper functions for converting this to something Unity can work with, see the ```Helper``` class methods ```GetOrientation``` and ```GetMatrixForOrientation```.
Our DisplayUGUI component handles all this internally so you can look there for examples.

**Comment by tomkail** [comment]
Wonderful, thanks!
