### ISSUE TITLE
Getting white screen when using HTTPs HLS on Quest 2

### ISSUE THREAD

**Issue by MSargiottiIndie** [RenderHeads/UnityPlugin-AVProVideo#1475]
issue
Im using Unity Plugin, trying to build on Quest 2. Im streaming using HLS through HTTP with the URL parameter on the mediaplayer.
The issue is that, in the Unity editor im getting to see the result perfectly, usign both apply to mesh and apply to material. But when i build im getting a white screen and only getting the sound, so the stream is coming thorugh but the image/video is not

Setup
 - Unity version: 2021.3.10f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AvPro Video, Trial version 2.7.3
 - Operating system version: Unity editor: Windows 10, Meta Quest 2: v49
 - Device model: Meta Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080 & 4096x2160

To Reproduce
1. Create a media player object, set the Source to "Path", "Absolut path or URL" to Http with the streaming port that is enabled (already checked the streaming url is fine)
2. Create a 3D object such as sphere or plane and attach the "Apply to mesh" or "Apply to material" AVprovideo component
3. Play on Editor and you can see and listen perfectly.
4. Build on Quest 2, you can only hear sound but white screen appearing

**Comment by Chris-RH** [comment]
Which shader are you using?
Are you using Exoplayer or Mediaplayer?
SRP, URP or HDRP?

**Comment by Ste-RH** [comment]
Android typically does not like anything served over HTTP. That said, it usually plays nothing.

Along with answers to Chris’ questions, please send over a full logcat and, if possible, the stream URL. You can email it over to unitysupport@renderheads.com if you wish to keep it private.

**Comment by Chris-RH** [comment]
Hi, we can't help you without further details please
