### ISSUE TITLE
Cached Files are not playing from local storage

### ISSUE THREAD

**Issue by ragavendranbalaCES** [RenderHeads/UnityPlugin-AVProVideo#1476]
**Describe the issue**
I'm using Unity and AVpro Video as library on my android project to play m3u8 videos. It's working as expected while passing the url of video from the Android Studio. 
We have implemented download option for the m3u8 video in Android Studio by using Exo player api and playing the same on Android Studio by using CacheFactory.  If I pass the link of the cached m3u8 video's https url inside the Unity Library, AVpro streaming it again from the internet instead of playing it from the local storage. 

Is there's any api available to play the  cached m3u8 videos from the storage?

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.7.3 trail
 - Operating system version: A12
 - Device model: Oppo A53

**Screenshots**
```C#
public string videoUrl = "";

    public MediaPlayer universalMediaPlayer;

    private void Start()
    {
        universalMediaPlayer.PlatformOptionsAndroid.videoApi = Android.VideoApi.ExoPlayer;
        universalMediaPlayer.PlatformOptionsAndroid.preferredMaximumResolution =
            MediaPlayer.OptionsAndroid.Resolution._2160p;
        universalMediaPlayer.PlatformOptionsAndroid.startWithHighestBitrate = true;
        // bool isOpening = universalMediaPlayer.OpenMedia(new MediaPath(videoUrl, MediaPathType.AbsolutePathOrURL), autoPlay:true);
        //
        // return;
        GetUnityVideoUrl();
    }

    private void GetUnityVideoUrl()
    {
#if UNITY_ANDROID
        try
        {
            AndroidJavaClass jc = new AndroidJavaClass("com.company.product.OverrideUnityActivity");
            AndroidJavaObject overrideActivity = jc.GetStatic<AndroidJavaObject>("instance");
            videoUrl = overrideActivity.Call<string>("showMainActivity");
        }
        catch (Exception e)
        {
            Debug.LogError("Exception during GetUnityVideoUrl     " + e.Message);
        }
#elif UNITY_IOS
        //todo need to call native api
#endif
        universalMediaPlayer.Stop();
        bool isOpening = universalMediaPlayer.OpenMedia(new MediaPath(videoUrl, MediaPathType.AbsolutePathOrURL), autoPlay:true);
        universalMediaPlayer.Play();
    }
```

**Comment by Ste-RH** [comment]
To access this functionality you will need to use the ‘downloading’ feature of the plug-in. You can read more about this [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-caching.html). Please note that this feature is only present in the Ultra version of the plug-in (and by extension the trial version).

**Comment by ragavendranbalaCES** [comment]
Hi @Ste-RH , thanks for quick reply, I can see the api

**In order to add media to the cache, call:
mediaPlayer.Cache.AddMediaToCache(url, headers, options);**
 Is this won't download the files again to the cache? if yes, my files are already downloaded to the cache by using the native app and Exoplayer Apis. 
 
 I'm aware of Caching feature is only available in Ultra version. I have seen a table which shows trail version having the support for it. So i'm currently testing it

**Comment by Ste-RH** [comment]
Files cached/downloaded externally to AVPro Video will not be accessible to your app that is using AVPro Video. We use a different cache folder and also, under the hood, database. This, I believe, is standard practice for all apps that use ExoPlayer.

**Comment by Ste-RH** [comment]
You will only want to download the video once. You can then check the status using AVPro Video API calls to determine if you need to download a given video, or if you can just use ‘open’. Note that the URL is the key part to this. It has to be the same across application runs/video opening/playing.

**Comment by ragavendranbalaCES** [comment]
if (mediaPlayer.Cache.IsMediaCached())
{
    // The open media is cached
}

I cannot see IsMediaCached() method ;

![image](https://user-images.githubusercontent.com/96132355/223051368-e5f7b52c-5545-47ac-a6c4-49f4fa8095d0.png)

**Comment by Ste-RH** [comment]
Yeah. That is obsolete and should have been removed from the documentation. You want to be getting the status. Can’t recall the exact API calls (sorry, I am away from my desk).
