### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager

### ISSUE THREAD

**Issue by jiuchengzjy** [RenderHeads/UnityPlugin-AVProVideo#1477]
use api ： _mediaPlayer.OpenMedia（）；
Failed to play video on Android 11；

UnityPlugin-AVProVideo-v2.6.6.unitypackage
Unity 2020.3.40f1c1
Android 11
![image](https://user-images.githubusercontent.com/26101196/223048156-d4a45ef8-9edb-4ca6-83b5-ffaf2d88bd52.png)

**Comment by Ste-RH** [comment]
We always urge using the latest releases. So that might be worth updating to.

What optimisation/stripping options do you have set? You might be being too aggressive. See notes [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#proguard-minify) .

**Comment by jiuchengzjy** [comment]
emm,  I changed medialinfo to absolute path or url. 
![image](https://user-images.githubusercontent.com/26101196/223050342-dd8bf934-97c3-4146-8bec-677729b99cc4.png)
and i changed Video API to Exo Player.
![image](https://user-images.githubusercontent.com/26101196/223050523-1a02efc9-6dd1-4cfc-9a57-7badb14b20dc.png)
So should I use the latest releases？  but AVpro-2.6.6 can play successfully when using Media Reference，adn demo can played.
![image](https://user-images.githubusercontent.com/26101196/223051414-12f8a27b-60c6-4190-a15b-8531cbcc2a51.png)

**Comment by jiuchengzjy** [comment]
![image](https://user-images.githubusercontent.com/26101196/223060040-3dcda957-234f-4856-9425-7a8be149ca72.png)
i don't use Android [minify options]

**Comment by Chris-RH** [comment]
If you use Android [minify options](https://developer.android.com/studio/build/shrink-code#keep-code), AVPro Video will be stripped out and will not work. The following options need to be added to your proguard configuration file (in Player Settings > Android > Publishing Settings > Build > Custom Proguard File) to prevent AVPro Video classes from being removed:

-keep class com.renderheads.AVPro.Video.** { ; }
-keep class com.google.android.exoplr2avp.* { ; }
-keep class com.twobigears.audio360.* { *; }
The above is included in /Assets/AVProVideo/Runtime/Plugins/Android/proguard-avprovideo.txt

When using Unity 2020.1 and above it has been seen that the build process overly optimises which causes issues in the ExoPlayer library. To overcome this issue, you will need to add a custom gradle property. In Player Settings|Publisher Settings, enable the Custom Gradle Properties Template option. The template is found at: /Assets/Plugins/Android/gradleTemplate.properties and it should be edited adding the following line to the end of the file: android.enableDexingArtifactTransform=false (This should have been done automatically, but you might want to check).

**Comment by jiuchengzjy** [comment]
emm ， but i don't use Android minify options ？  
And the proguard-avprovideo.txt exists 
-keep class com.renderheads.AVPro.Video.** { ; }
-keep class com.google.android.exoplr2avp.* { ; }
-keep class com.twobigears.audio360.* { *; }
![image](https://user-images.githubusercontent.com/26101196/223293780-3bfe23ec-70f7-4787-b867-98db8bea685f.png)

i try use MediaPlayer  can not paly.
![image](https://user-images.githubusercontent.com/26101196/223293278-65fe572b-30e1-4cde-9f44-0288842527db.png)

**Comment by Chris-RH** [comment]
How does your main gradle look?
what is your minSDK and targetSDK?

**Comment by jiuchengzjy** [comment]
![image](https://user-images.githubusercontent.com/26101196/223592740-d3bbaca6-87ea-4d44-8aec-6947dba44c3a.png)
![image](https://user-images.githubusercontent.com/26101196/223592838-67bd675d-67bb-4a62-8306-32f68c735f96.png)
is this.

**Comment by jiuchengzjy** [comment]
oh，yesterday  I updated to the latest releases , UnityPlugin-AVProVideo-v2.7.3-Trial.unitypackage

**Comment by jiuchengzjy** [comment]
And，After updating to 2.7.3, can see the video, but the video is very stuck, and both video and audio are stuck.  be like walking forward for 2 seconds and bouncing back for 1 second.
This effect is the same as that of 1.8.7，alos ducatan.  
What should I modify to play smoothly？

**Comment by Chris-RH** [comment]
any more info?
