### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'AVProVideo'. Tried the load the following dynamic libraries: Unable to load dynamic library 'AVProVideo' because of 'Failed to open the requested dynamic library

### ISSUE THREAD

**Issue by vic910** [RenderHeads/UnityPlugin-AVProVideo#1478]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.12
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.4
 - Operating system version: macOS 13.1
 - Device model: macOS 10.13.6
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. has Add AVPROVIDEO_SUPPORT_MACOSX_10_14_3_AND_OLDER to "Scripting Define Symbols"
2. Always Embed Swift Standard Libraries is Yes  still DllNotFoundException
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Please update to the latest version of AVPro Video.
2. Make sure you follow this and see if it still happening:

Significant portions of AVPro Video are now written using Swift. Unfortunately the Swift 5 standard libraries were not added to macOS until 10.14.4 (Mojave) and when running under older version of macOS you will encounter an error similar to the following:

dyld: Library not loaded: @rpath/libswiftCore.dylib

To be able to use AVPro Video in the Unity editor with older versions of macOS please install the "Swift 5 Runtime Support for Command Line Tools" package available from Apple's developer site [here](https://download.developer.apple.com/Developer_Tools/Swift_5_Runtime_Support_for_Command_Line_Tools/Swift_5_Runtime_Support_for_Command_Line_Tools.dmg).

If you just want standalone builds to be able to run on older versions of macOS, you need to do the following:

Make sure you're using Unity 2019 or later
Make sure the iOS Build Support module is installed
In the Build Settings dialog, make sure "Create Xcode Project" is checked
In the Player Settings inspector:
In the Other Settings section
Add AVPROVIDEO_SUPPORT_MACOSX_10_14_3_AND_OLDER to "Scripting Define Symbols"
Build the project
Check that "Always Embed Swift Standard Libraries" is set to "YES" in the main target's build settings.

**Comment by vic910** [comment]
update to the latest version of AVPro Video 2.7.3  and Add AVPROVIDEO_SUPPORT_MACOSX_10_14_3_AND_OLDER    still  has the programs

**Comment by Chris-RH** [comment]
Have you tried building a new project with only AVPro and the demo mediaplayer scene in it?

**Comment by vic910** [comment]
yes! i just use new  project which only has AVPro plugin!

**Comment by Chris-RH** [comment]
Our mac dev is out of office at the moment. He will be back middle of next week and will hopefully be able to look into this with one of the older macs that is in the office.

**Comment by vic910** [comment]
thank you

**Comment by vic910** [comment]
> 

do you have idea

**Comment by Chris-RH** [comment]
We'll update you when its been looked into.

**Comment by Chris-RH** [comment]
Unfortunately it seems that we no longer have a device that we can test old OS on that can support Metal.
Out of interest, what was the device model that you were trying to use?

**Comment by MorrisRH** [comment]
I have reproduced this issue and am investigating

**Comment by MorrisRH** [comment]
The plugin bundle is failing to load due to the security checks macOS uses failing to verify the bundle's code signature when the application launches. This is despite the plugin passing code signature verification on the command line.

I've tried to build apps with the plugin using older versions of Unity, Xcode and macOS with no success.

I'm out of ideas about how to solve this so at this time we're dropping support for macOS High Sierra (10.13).
