### ISSUE TITLE
Controlling bitrate

### ISSUE THREAD

**Issue by ptrhdn** [RenderHeads/UnityPlugin-AVProVideo#148]
**Is your feature request related to a problem? Please describe.**
We are currently trying out if we can replace our current native implementations of our iOS and Android video players with AVPro but are missing a key feature: Controlling bitrate and quality.

Is there a way to set the preferred peak bit rate in the AVPro Video player? Similar to what you can do in e.g. the iOS AVPlayerItem.preferredPeakBitRate.

**Describe the solution you'd like**
An option to set peak bitrate for both Android and iOS

**Comment by AndrewRH** [comment]
Hi,

Currently we don't offer this option, but it is something that will be coming in AVPro Video 2.0 which is in the works...though we don't yet have a release date for this.

Thanks,

**Comment by bepper08** [comment]
Do you know if we are talking months or years before the 2.0 will be released?

**Comment by AndrewRH** [comment]
preferredPeakBitRate is supported on iOS in AVPro Video 2.x

Closing this issue.

**Comment by AndrewRH** [comment]
I think this is almost implemented on Android....leaving this open to confirm

**Comment by Ste-RH** [comment]
Closing as this was added on Android a long time ago
