### ISSUE TITLE
Crashes on iOS when using multithreaded rendering

### ISSUE THREAD

**Issue by joseph-o3h** [RenderHeads/UnityPlugin-AVProVideo#1481]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
In rare cases the Unity render thread can crash with this call stack when using the AVPro player in an iOS app with multithreaded rendering enabled (this was obtained from crash reports of our live app):

```
Crashed: UnityGfxDeviceWorker
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000000001ec20
0  libobjc.A.dylib                0x1cac objc_msgSend + 172
1  UnityFramework                 0x145900c TexturesMetal::AddCreatedTexture(TextureID, id<MTLTexture>, bool) + 502 (TexturesMetal.mm:502)
2  UnityFramework                 0x139aeb4 GfxDeviceWorker::RunCommand(ThreadedStreamBuffer&) + 1562 (GfxDeviceWorker.cpp:1562)
3  UnityFramework                 0x142c414 GfxDeviceWorkerAutoreleasePoolProxy + 5749 (GfxDeviceMetal.mm:5749)
4  UnityFramework                 0x139d2e0 GfxDeviceWorker::RunExt(ThreadedStreamBuffer&) + 394 (GfxDeviceWorker.cpp:394)
5  UnityFramework                 0x13950ec GfxDeviceWorker::RunGfxDeviceWorker(void*) + 358 (GfxDeviceWorker.cpp:358)
6  UnityFramework                 0xf4bdd4 Thread::RunThreadWrapper(void*) + 82 (Thread.cpp:82)
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8
```

By running the app in the Xcode debugger I have found that `TexturesMetal::AddCreatedTexture` is being called with a texture from the AVPro plugin passed to `Texture2D.UpdateExternalTexture`. So the crash is likely because of a destroyed texture being passed in (or the texture is released before the rendering thread picks it up).

I am not able to provide a sample project that can reliably reproduce this because it happens very rarely.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.14
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.2-2.7.3, ultra edition
 - Operating system version: iOS 15-16

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Does it repeatedly occur on the same device or is it a range of different devices?
Do you know which devices?

**Comment by joseph-o3h** [comment]
It happens on a range of iPhone devices - XS/11/12/13/14 including Pro models.
In all instances the app was running in the foreground when it crashed and I do not know of any other background apps that could have been running.
It could happen any time after a video started playing - I don't have anything more specific right now

**Comment by Chris-RH** [comment]
OK, it would be helpful if you let me know when you get some more information from the users please, thank you :)

**Comment by Chris-RH** [comment]
Closing for now, but please reopen if you get more information

**Comment by joseph-o3h** [comment]
OK, I have been able to prevent the crash from happening by patching the scripts `AppleMediaPlayer.cs` and `AppleMediaPlayer+Native.cs` (sent by email). This could help to determine the actual cause.

**Comment by Chris-RH** [comment]
Thanks, I've passed that on to the iOS dev.

**Comment by Chris-RH** [comment]
Its good that you've found a work around, but we really need a reproducible instance to get to the bottom of the problem.

**Comment by Chris-RH** [comment]
closing for now until this can be reproduced.

**Comment by yangwz** [comment]
We have also found the same problem. How did you solve it

Unity version: 2020.3.38
AVPro Video version 2.8.0

**Comment by yangwz** [comment]
> OK, I have been able to prevent the crash from happening by patching the scripts `AppleMediaPlayer.cs` and `AppleMediaPlayer+Native.cs` (sent by email). This could help to determine the actual cause.

Hello,Bro
We have also found the same problem. How did you solve it

**Comment by MorrisRH** [comment]
Linking #1570
