### ISSUE TITLE
.MKV corrupted playback 

### ISSUE THREAD

**Issue by Benjie95** [RenderHeads/UnityPlugin-AVProVideo#1483]
Loading and playing .mkv video on Windows is rendering a solid moving line (changes color between white and grey) on top of the video. 
Is it possible that the video resolution is causing the rendering error? 

Video codec: MPEG-H Part2/HEVC (H.265) (hevc)
Video resolution: 8192x4096
Unity version: 2021.3.18f1
Tried both version of AVPro: 2.7.3 Trial Version AND 2.7.3 Core Android Edition
Processor: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz, 3792 Mhz, 8 Core(s), 16 Logical Processor(s)
Graphics: NVIDIA GeForce RTX 3080

**Comment by Chris-RH** [comment]
It sounds like this is just the watermark.  It'll show in Windows/editor even if you own the Core Android Edition, as the editor version is still counted as trial, if you see what I mean.  It should be gone if you view the video on Android (thought that is very high res for android)

**Comment by Benjie95** [comment]
I also have the moving Renderheads watermark, but this is not what I'm talking about in this case. 
The audio from the video is also extremely low pitched.

**Comment by Chris-RH** [comment]
It would be helpful to see a video of what you are describing and maybe a sample of the video itself that you are trying to play. Either here or email[unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) please.

**Comment by Benjie95** [comment]
I've just sent an email with a recording of the issue.

**Comment by Chris-RH** [comment]
Hi @Benjie95,
The line coming down looks like the watermark line to my eye (we have two watermarks that can display.  The most commonly occurring one is our logo and the other is a scrolling horizontal bar).  If you look at a scene that doesn't have a mostly black background, then you should see some text saying AVPRO TRIAL.

As for the low pitched audio. Have you used something like MediaInfo to double check that the sampling rate is 48 kHz?

**Comment by Benjie95** [comment]
You were right - it was just the watermark. Just upgraded to the Ultra edition and the issues described are now fixed. 
Thank you.

**Comment by Chris-RH** [comment]
You're very welcome. I'm glad to hear that its sorted :)
