### ISSUE TITLE
Video fails to open in Unity Editor on a Windows Server virtual machine

### ISSUE THREAD

**Issue by daltonbr** [RenderHeads/UnityPlugin-AVProVideo#1484]
**Describe the issue**

Video fails to open in Unity Editor on a Windows virtual machine.

**Your Setup:**
 - **Unity version:** `2021.3.9f1` (although tested in the current latest `2021.3.20f1`)
 - **AVPro Video version:** `2.7.1` (native plugin `v2.7.0f1-ultra`) on `Microsoft Basic Render Driver/Direct3D 11.0` - briefly tried the `2.7.3` with no success.
 - `[AVProVideo] Initialising AVPro Video v2.7.3 (native plugin v2.7.0f1-ultra) on Microsoft Basic Render Driver/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor`
 - **Operating system version:** `Windows Server 2019 Datacenter` running on EC2 in AWS
 - **Device model:** `c6i.xlarge` - AMD64 architecture - Xeon 4 core - 8GB - accessed through `Microsoft Remote Desktop`
 - **Video specs:** 
   - resolution: `960x540`
   - framerate: 25
   - codecs: `MPEG-4 AAC`, `H.264`
   - `11.3 MB`

**Context information:**

- The video plays fine on that same virtual machine when using Unity native video player
- The video plays fine on "regular" desktop machines (Windows and Mac) and mobile.
- The problem initially happened on the CI machines we use for automated tests (we have always used the Unity native video player so far) - and to verify the issue, I logged in to the machine and ran the Unity Editor graphically to get the same log error.

**To Reproduce**

It may be tricky to reproduce our environment as we have a custom Windows image, but we may get back to that if needed.

In short, playing a video inside that virtual machine would suffice.

**Logs**

```
[AVProVideo] Failed to open https://d1xdf48549vgyg.cloudfront.net/tasks/video/e6f46e47-f0da-4c06-b8f8-43f09c614f64.mp4
---
UnityEngine.Debug:LogError (object,UnityEngine.Object)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia () (at C:/jenkins/workspace/Yousician_Tests_PR-17850/Packages/com.renderheads.avpro/Runtime/Scripts/Components/MediaPlayer.cs:611)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) (at C:/jenkins/workspace/Yousician_Tests_PR-17850/Packages/com.renderheads.avpro/Runtime/Scripts/Components/MediaPlayer.cs:509)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (RenderHeads.Media.AVProVideo.MediaPathType,string,bool) (at C:/jenkins/workspace/Yousician_Tests_PR-17850/Packages/com.renderheads.avpro/Runtime/Scripts/Components/MediaPlayer.cs:488)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (RenderHeads.Media.AVProVideo.MediaPath,bool) (at C:/jenkins/workspace/Yousician_Tests_PR-17850/Packages/com.renderheads.avpro/Runtime/Scripts/Components/MediaPlayer.cs:479)
Yousician.VideoPlayer.AVPro.MediaPlayerProxy:OpenMedia (RenderHeads.Media.AVProVideo.MediaPath,bool) (at Assets/VideoPlayer/AVPro/MediaPlayerProxy.cs:94)
Yousician.VideoPlayer.AVPro.AvProVideoPlayer/<>c__DisplayClass44_0:<Load>b__0 () (at Assets/VideoPlayer/AVPro/AvProVideoPlayer.cs:109)
UniRx.Operators.DeferObservable`1<bool>:SubscribeCore (System.IObserver`1<bool>,System.IDisposable) (at C:/jenkins/workspace/Yousician_Tests_PR-17850/submodules/UniRx/Assets/Plugins/UniRx/Scripts/Operators/Defer.cs:22)
UniRx.Operators.OperatorObservableBase`1<bool>:Subscribe (System.IObserver`1<bool>) (at C:/jenkins/workspace/Yousician_Tests_PR-17850/submodules/UniRx/Assets/Plugins/UniRx/Scripts/Operators/OperatorObservableBase.cs:34)

```

**Screenshots**

![AvPro](https://user-images.githubusercontent.com/10944679/224089490-f90307bb-e8a4-41da-b938-e5d532f3f7cf.jpg)

![NativeVideoPlayer](https://user-images.githubusercontent.com/10944679/224089507-f6a79fdb-ff7e-418a-902c-58f383e22f7c.jpg)

We are running this virtual audio device to emulate an audio input device - https://vb-audio.com/Cable/

![Screenshot 2023-03-09 at 16 54 26](https://user-images.githubusercontent.com/10944679/224074953-edfcc8e4-bf74-45ab-b17b-affe789031a9.jpg)

**Comment by Ste-RH** [comment]
Can you narrow down the issue a bit, maybe try removing audio from chain to see if it’s the virtual device that is causing the issue? Are you using MediaFoundation? Have you tried WinRT and DirectShow?

**Comment by daltonbr** [comment]
Thanks for the swift response @Ste-RH!

**Disabling Hardware decoding solves the issue! 🎖️** 

We were using MediaFoundation.
For posterity, that machine doesn't seem to have a dedicated hardware GPU - it only shows a `Microsoft Basic Display Adapter`.
![Screenshot 2023-03-10 at 9 56 50](https://user-images.githubusercontent.com/10944679/224258248-e66f16c0-c569-4435-a333-d5d037e7451e.jpg)

A huge thanks to the team and you, Ste!

---

As a follow-up, is it possible to have this information in the logs? Such as 'No hardware decoding found.'

Also, is it possible to have an automatic fallback solution where we try to decode the video through software if it fails on hardware? If feasible, this is a significant feature enhancement.

**Comment by Chris-RH** [comment]
We are looking at improving logging.  I'm glad its working for you now :)
