### ISSUE TITLE
MediaPlayer freezes when "Scene Window" is open but not when "Play Window" is.

### ISSUE THREAD

**Issue by rcwongtk** [RenderHeads/UnityPlugin-AVProVideo#1485]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Currently working on implementing the MediaPlayer in a Unity Scene. When using Play Mode on editor the video will load, but not play if you have the Scene Window open. However, if you use Play Mode when the Game (or Simulator) window is open, the video will play just fine. As soon as you switch to Scene view the video freezes and will not loop.

This also occurs when using the Demo Scene (Demo_MediaPlayer), have used versions of AVProVideo in the past and this has not happened in older versions so I am thinking it might be an incompatibility between the newer version of AVProVideo and Unity.

**Your Setup (please complete the following information):**
 - Unity version: 2022.1.20f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core Edition
 - Operating system version: Windows 11
 - Device model: MSI Stealth GS77 (i9-12900H, RTX 3080 Ti Laptop GPU)
 - Video specs (resolution, frame-rate, codec, file size): Your Videos from the Demo.

**To Reproduce**
1. Open up "Demo_MediaPlayer"
2. Go to Scene View, and press Play
3. Video will not work
4. Turn off Play Mode, go to Game View
5. Press Play
6. Video Will Work.

**Logs**
Weirdly enough, no log at all.

**Screenshots**
N/A

**Videos**
N/A, Attaching a screen recording of the issue however!

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by rcwongtk** [comment]
https://user-images.githubusercontent.com/16457282/224566075-578abdb2-32e7-4430-a883-22a6f6c9cfca.mp4

**Comment by Chris-RH** [comment]
From my testing

- This occurs in Media Foundation.  When focussed on the scene view, the media appears to freeze in the scene and preview windows, while sound can still be heard, so it still playing. When you then go back to game view, the playback is jagged and buffering.  This seems to rectify itself at the end of the loop.
- With DirectShow.  When focused on scene window, the media appears to freeze in the  scene and preview windows, but it is still playing fine in game view.  Continues to play back smoothly in game view, even when switching back and forth.
- This does not occur at all using WinRT. It continues to play in scene, game and preview windows when switching between scene and game view.

**Comment by rcwongtk** [comment]
Thanks Chris! I am not too experienced with this, but how do I switch to using WinRT in this case?

**Comment by Chris-RH** [comment]
Hi @rcwongtk,

In the Mediaplayer component, go to the Windows platform specific section.  Where it says Video API, you can change it to WinRT. 

![component-mediaplayer-platform-windows](https://user-images.githubusercontent.com/102963025/224965107-5ed43614-cfef-4b14-95d9-4ad856d89c02.png)

**Comment by rcwongtk** [comment]
Confirmed to work on my end, thank you so much Chris I really appreciate the quick work and help!
