### ISSUE TITLE
.mkv not playing on Quest 2 - APK

### ISSUE THREAD

**Issue by Benjie95** [RenderHeads/UnityPlugin-AVProVideo#1486]
**Describe the issue**
My .mkv video won't play on the Quest 2 after building APK. Project settings should be fine since I can successfully play .mp4 videos. Tried with both the Mediaplayer as well as the Exoplayer - no luck with either. 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.18f1
 - AVPro Video version: 2.7.3 Ultra
 - Operating system version: Windows 10
 - Device model: Nvidia GeForce RTX3080 10GB
 - Video specs (resolution, frame-rate, codec, file size): 
 Resolution: 8192x4096
 Frame-rate: 30
 Codec: MPEG-H Part2/HEVC (H.265) (hevc)
 File size: 18,675,422 KB

**Logs**
03-13 16:04:56.954 14286 14320 I Unity   : RenderHeads.Media.AVProVideo.MediaPla
03-13 16:04:56.973 14286 14320 I Unity   : [AVProVideo] Initialising AVPro Video v2.7.3 (native plugin v2.7.1f1-trial) on Adreno (TM) 650/OpenGL ES 3.2 V@0667.0 (GIT@59a14ebd51, I5463b91de8, 1661831993) (Date:08/29/22) (MT True) on Android
03-13 16:04:56.973 14286 14320 I Unity   : UnityEngine.StackTraceUtility:ExtractStackTrace () (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
03-13 16:04:56.973 14286 14320 I Unity   : UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
03-13 16:04:56.973 14286 14320 I Unity   : UnityEngine.Logger:Log (UnityEngine.LogType,object)
03-13 16:04:56.973 14286 14320 I Unity   : UnityEngine.Debug:Log (object)
03-13 16:04:56.973 14286 14320 I Unity   : RenderHeads.Media.AVProVideo.Helper:LogInfo (string,UnityEngine.Object) (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Internal/Helper.cs:183)
03-13 16:04:56.973 14286 14320 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Initialise () (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:438)
03-13 16:04:56.973 14286 14320 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Start () (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:458)
03-13 16:04:56.973 14286 14320 I Unity   :
03-13 16:04:56.983 14286 14320 I Unity   : [AVProVideo] Opening /data/app/com.Makropol.EoNTest-pfIHWMM4JAwTLZoLjVvhCA==/Assets/Resources/EoN_DK.mkv (offset 0) with API MediaPlayer
03-13 16:04:56.983 14286 14320 I Unity   : UnityEngine.StackTraceUtility:ExtractStackTrace () (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
03-13 16:04:56.983 14286 14320 I Unity   : UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
03-13 16:04:56.983 14286 14320 I Unity   : UnityEngine.Logger:Log (UnityEngine.LogType,object,UnityEngine.Object)
03-13 16:04:56.983 14286 14320 I Unity   : UnityEngine.Debug:Log (object,UnityEngine.Object)
03-13 16:04:56.983 14286 14320 I Unity   : RenderHeads.Media.AVProVideo.Helper:LogInfo (string,UnityEngine.Object) (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Internal/Helper.cs:187)
03-13 16:04:56.983 14286 14320 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia () (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:577)
03-13 16:04:56.983 14286 14320 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:509)
03-13 16:04:56.983 14286 14320 I Unity   : RenderHeads.Medi
03-13 16:04:56.987 14286 14320 W Unity   : AndroidJNIHelper.GetSignature: using Byte parameters is obsolete, use SByte parameters instead
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine.StackTraceUtility:ExtractStackTrace () (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine.Logger:Log (UnityEngine.LogType,object)
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine.Debug:LogWarning (object)
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine._AndroidJNIHelper:GetSignature (object) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJava.cs:1503)
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine._AndroidJNIHelper:GetSignature (object) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJava.cs:1558)
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine._AndroidJNIHelper:GetSignature (object[]) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJava.cs:1574)
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine._AndroidJNIHelper:GetMethodID (intptr,string,object[],bool) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJava.cs:1383)
03-13 16:04:56.987 14286 14320 W Unity   : UnityEngine.AndroidJNIHelper:GetMethodID (intptr,
03-13 16:04:56.991 14286 14320 W Unity   : AndroidJNIHelper: converting Byte array is obsolete, use SByte array instead
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine.StackTraceUtility:ExtractStackTrace () (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine.Logger:Log (UnityEngine.LogType,object)
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine.Debug:LogWarning (object)
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine._AndroidJNIHelper:ConvertToJNIArray (System.Array) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJava.cs:1240)
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine._AndroidJNIHelper:CreateJNIArgArray (object[]) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJava.cs:1059)
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine.AndroidJNIHelper:CreateJNIArgArray (object[]) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJNI.bindings.cs:112)
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine.AndroidJavaObject:_Call (string,object[]) (at /home/bokken/build/output/unity/unity/Modules/AndroidJNI/AndroidJava.cs:428)
03-13 16:04:56.991 14286 14320 W Unity   : UnityEngine.AndroidJavaObject:Call<byte> (string,byte[])
**03-13 16:04:57.040 14286 14320 E Unity   : [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.**
03-13 16:04:57.040 14286 14320 E Unity   : UnityEngine.StackTraceUtility:ExtractStackTrace () (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
03-13 16:04:57.040 14286 14320 E Unity   : UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
03-13 16:04:57.040 14286 14320 E Unity   : UnityEngine.Logger:Log (UnityEngine.LogType,object)
03-13 16:04:57.040 14286 14320 E Unity   : UnityEngine.Debug:LogError (object)
03-13 16:04:57.040 14286 14320 E Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1399)
03-13 16:04:57.040 14286 14320 E Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at C:/Users/benja/Documents/GitHub/AVProTest/Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:827)

**Screenshots**
<img width="464" alt="SC" src="https://user-images.githubusercontent.com/36990142/224755637-13221477-1430-4b1c-817b-dab40c1716ef.png">

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, you need to be using Exoplayer,  not Android Media player

**Comment by Chris-RH** [comment]
It could well be the resolution.  Here are some guidelines:
https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/
https://headjack.io/knowledge-base/best-video-resolution-for-oculus-quest-2/
