### ISSUE TITLE
Streaming (HLS) Error.

### ISSUE THREAD

**Issue by Jay-pixelscope** [RenderHeads/UnityPlugin-AVProVideo#1488]
- Unity version: 2021.3.8f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 1.11.7
 - Operating system version: Windows10, Build to Android APK.
 - Android OS : 10.0

Sorry for posting the link following the test streaming URL.

Streaming URL does not play in Android EXOplayer.

It works fine in editor mode.

I have also set up Android ClearText and other streaming works fine.

Is it possible to check why the below URL streaming address does not work on Android?

URL : 
http://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)

**Comment by Chris-RH** [comment]
Have you tried changing it to HTTPS?

**Comment by Jay-pixelscope** [comment]
The URL is not mine, so I can't test it with https.

**Comment by Ste-RH** [comment]
Android (I think it was 10) introduced security measures that meant playing anything from http become a pain (to describe it mildly!).

I believe there is an HTTPS version of you just change the url to:

[https://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)](https://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl))
