### ISSUE TITLE
Blank on Android 9

### ISSUE THREAD

**Issue by muhammadasif527** [RenderHeads/UnityPlugin-AVProVideo#149]
**Describe the bug**
on android 9 after playing video, audio play but video is not showing. While on all other versions it is working fine.

**Your Setup (please complete the following information):**
 - Unity version:  Unity 2019.1.8f1 (64-bit)
 - AVPro Video version: 
 - Operating system version: win 10
 - Device model: on all android 9.0 
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by AndrewRH** [comment]
Could you provide more information?

AVPro Video version?
Video specs?
Which API are you using (ExoPlayer or MediaPlayer)?  And does it make a difference if you change this?

**Comment by muhammadasif527** [comment]
AVPro Video version? 1.9.12
Video specs? (720p,14.5 MB)
both APIs  (ExoPlayer or MediaPlayer) have same issue.

**Comment by AndrewRH** [comment]
Thanks, first of all I would suggest upgrading to the latest version (1.10.0)
Next I would ask you if you can replicate this issue in any of our sample demo scenes?

Thanks,

**Comment by muhammadasif527** [comment]
Same problem with version 1.10.0 i demo scene.

**Comment by AndrewRH** [comment]
Could you send over the ADB log cat so we can see what errors are logged?

**Comment by muhammadasif527** [comment]
It is hard to send you log. Test on android 9 By your self.

**Comment by AndrewRH** [comment]
We have tested on Android 9 - we don't have any problems.  We also have many other users using Android 9 without issues.  We need the log so we can work out what's happening in your setup.

**Comment by AndrewRH** [comment]
I'm afraid we'll have to close this issue soon unless we can get a ADB LOG CAT as we are unable to replicate the issue and don't have any clues as to what it could be.
