### ISSUE TITLE
Android OES geometry destruction

### ISSUE THREAD

**Issue by makuchan** [RenderHeads/UnityPlugin-AVProVideo#1493]
Unity 2021.3.21f
AVPro Video Core Android Edition ver.2.7.3
Universal RP 12.1.10
XR Interaction Toolkit 2.3.0
XR Plugin Management 4.3.3
Meta Quest2 v49

(Google Translate)
#1445 [](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1445)

I use it for urgent matters. I'm having trouble with the same content.
We handle 4K 3D VR360 videos.

It seems to be a Unity bug, but are there any Unity versions that can be saved or points to be aware of?

**Comment by Ste-RH** [comment]
I am afraid your description makes very little sense. What is the exact issue?

**Comment by makuchan** [comment]
(Google Translate)
sorry.
Right now, I'm so tight on the deadline that I don't even have time to test it, so I won't use OES this time.
I'll report back when I calm down.

**Comment by makuchan** [comment]
@ShaneRH

(Google Translate)
Mapped spheres are drawn in unintended locations.
Adding a plane in view and mapping will break the mesh.
A problem occurred in MetaQuest2.
No problem on Windows.

Unity 2021.3.2f1

[Scenes]
AVProVideo/Demos/Scenes/Demo_360Stereo

[XR Plus-in Management]
Android>Oculus

[XR Plugin Management 4.3.3>Oculus]
Render:Multitview
Low Overhead Mode (GLSE):ON
All others are OFF

MediaPlayer>Android
Use OES Rendering:ON

[Demo-360(Material)]
Shader>
AVProVideo/VR/InsideSphere Unlit (stereo+fog)
to 
AVProVideo/VR/InsideSphere Unlit (stereo+color) - Android OES ONLY

**Comment by makuchan** [comment]
@Ste-RH

(Google Translate)
If you turn on OES and use a shader that does not use OES, there is no problem with the mesh, but the colors will be negative and positive. (When playing live-action video)
Is there any way to solve the color problem?

**Comment by Chris-RH** [comment]
For the initial issue, have you tried switching to OpenGLES2?

**Comment by makuchan** [comment]
@Ste-RH

(Google Translate)
thank you.
I encountered the following problem.

・Can't use URP with OpenGLES2?
・In OpenXR, it is necessary to set the color space to be linear.
・In OpenGLES2, it is necessary to set the color space to gamma.

[error log]

Gamma Color Space is not supported when using OpenGLES.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Double click to fix OpenXR Project Validation Issues.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

BuildFailedException: OpenXR Build Failed.
UnityEditor.XR.OpenXR.OpenXRProjectValidationBuildStep.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report) (at Library/PackageCache/com.unity.xr.openxr@1.6.0/Editor/OpenXRProjectValidationRulesSetup.cs:452)

**Comment by makuchan** [comment]
@Chris-RH

(Google Translate)
Upgrading to Unity 2021.3.22 did not solve the problem, but when I checked the SRP project, there was no problem.
Will it be difficult to support Android OES with URP?

**Comment by Chris-RH** [comment]
its a Unity problem, so nothing we can do about it I'm afraid

**Comment by Andjiang707** [comment]
I also encountered this problem in a MR project using Meta Quest 3 + URP + OpenGLES3, where the image pixels are inverted and the colors are distorted. Is there any new progress on this issue?
![image20240227](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/29428186/0065d245-3baf-405d-b189-51f67e76ac5a)
![20240227-2](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/29428186/ece6b8dc-7d43-49a2-9089-7b1b44113f8d)
