### ISSUE TITLE
Seeking not working

### ISSUE THREAD

**Issue by Fedd9** [RenderHeads/UnityPlugin-AVProVideo#1494]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
We are trying to synchronise different videos with the same length but, as we open another one, the video restarts

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.34f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Trial 2.7
 - Operating system version: Ventura 13.2.1
 - Device model: MacBook Pro 14'', 2021, M1

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Fedd9** [comment]
Hi!

This is a sample project we made, https://we.tl/t-FP07RFdRJV in order to give you an example, while this is a screen of the videos are loaded (through URL) and synchronised.



Together with that, we are currently having problems also with the videos, currently hosted, but giving codec when streamed through Vimeo or YT.

Federico Di Veroli
Developer
+393499075489
***@***.***
www.federicodiveroli.com

**Comment by Chris-RH** [comment]
What is the error message when you are trying to stream from vimeo?
What type of video is it?
Have you been able to use seek when playing it through other players?

We can't really help with Youtube streaming support (https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#youtube--facebook-live--twitch-support)

**Comment by Fedd9** [comment]
Streaming from Vimeo works (I just had to change the link with the m3u8 link).

What I’m missing now is a part in which I’m able to start from a given timing.

Federico Di Veroli
Developer
+393499075489
***@***.***
www.federicodiveroli.com

**Comment by Chris-RH** [comment]
Can you open the media, seek to the preferred time, and then play?

**Comment by Fedd9** [comment]
This is what I do when I change my code

<img width="798" alt="Screenshot 2023-04-18 at 19 46 09" src="https://user-images.githubusercontent.com/15869969/232860883-9e8f6597-ab02-4234-be66-a90e518cbf6a.png">

**Comment by Fedd9** [comment]
Am I doing something wrong?

**Comment by Chris-RH** [comment]
Make sure you are creating a new media player
Open media
Wait for readytoplay event to fire
Seek to desired point
Play video

**Comment by Chris-RH** [comment]
does that help?

**Comment by Chris-RH** [comment]
Closed due to lack of reply
