### ISSUE TITLE
Volume control on MediaPlayer does not attenuate all tracks of an ambisonic file

### ISSUE THREAD

**Issue by WoutStandaert** [RenderHeads/UnityPlugin-AVProVideo#1495]
**Describe the issue**
I wanted to use the volume control of a mediaplayer as a mechanism for fading out 

**Your Setup (please complete the following information):**
 - Unity version: 2022.2.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.7 ultra
 - Operating system version: Windows 10
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 3840x3840, HEVC, overall bit rate 26.6 Mb/s, 29,97 fps with 11-channel Opus audio in an MKV container (AMBIX_9_2 mapping)

**To Reproduce**
1. Have a proper AMBIX_9_2 file to play 
2. Wiggle the volume knob in the mediaplayer in the editor
3. Now you can hear that all channels are affected, except it seems the very last one. If the volume level is on 0, I still have the headlocked R channel playing at full volume.
4. This is happening both when I manually wiggle the volume control with the mouse, and when I do it via scripting.

Maybe it's only affecting the first 10 channels (from back in the days when the TBE format only had 8 spatial channels + 2 stereo headlocked?)

**Comment by Chris-RH** [comment]
Is there any chance that you could send us a sample 9_2 track please? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
Out of interest, have you tested this on your device as well?

**Comment by WoutStandaert** [comment]
Hi Chris,

Yes, on the device it has the same effect. I'll send you a video file.
