### ISSUE TITLE
VR180 movie via media player

### ISSUE THREAD

**Issue by yasu202020** [RenderHeads/UnityPlugin-AVProVideo#1498]
**Describe the issue**

thanks for the great video system
I am currently using the trial version
I would like to ask you the following

Inside theDemo360_stereo scene
Played VR180 movie on Meta Quest with Media Player
Normally when watching VR180 videos, if you move your head up and down and left and right
You can move the viewpoint while keeping the video still.
However, when I watch a VR180 video via Media player
VR180 videos are always fixed in front of you,
Therefore, even if you move your head up, down, left, or right, the VR180 video is always fixed in front.
Is there a way to fix this condition?

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.15f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Trial
 - Operating system version: Android
 - Device model: Meta quest 2
 - Video specs (resolution, frame-rate, codec, file size): 
MP4 
stereo3d: side by side
spherical: equirectangular180
![inspector](https://user-images.githubusercontent.com/71736415/227383193-420d9d18-3315-4507-b0ca-5dfeb1b4d26e.jpg)

**Comment by Chris-RH** [comment]
Unity will rotate the camera automatically if VR is enabled,
A gyroscope will also rotate the scene.

That demo scene moves around fine with my non-VR android device.

**Comment by yasu202020** [comment]
Thank U for yor kind support!

However, I apologize for my poor English. 
I understand that the scene follows the line of sight with the gyro. 
I would like to ask you one more thing.

The screen does not rotate in Youtube VR etc.
Is there a way to show VR180 video without setting to rotate in AVPRO?

**Comment by Chris-RH** [comment]
I'm not sure about Youtube VR as we don't support streaming from Youtube (https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#youtube--facebook-live--twitch-support)
