### ISSUE TITLE
Black and crash when going back from sleep on Oculus GO

### ISSUE THREAD

**Issue by AwesomeSuri** [RenderHeads/UnityPlugin-AVProVideo#150]
On Oculus Go, when a video is playing and the device goes to sleep and back again, the screen remains black while the audio continues. Sometimes the app restarts itself automatically. But when it goes black, I get these logs: 

`08-16 19:14:33.939 29962 30002 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
08-16 19:14:33.939 29962 30002 E Unity   :  #0 0xd59c069c (libunity.so) ? 0x46b69c
08-16 19:14:33.939 29962 30002 E Unity   :  #1 0xd5f5b6fc (libunity.so) ? 0xa066fc
08-16 19:14:33.939 29962 30002 E Unity   :  #2 0xd5f99e08 (libunity.so) ? 0xa44e08
08-16 19:14:33.939 29962 30002 E Unity   :  #3 0xd5f99f30 (libunity.so) ? 0xa44f30
08-16 19:14:33.939 29962 30002 E Unity   :  #4 0xd5da8c84 (libunity.so) ? 0x853c84
08-16 19:14:33.939 29962 30002 E Unity   :  #5 0xd59b8b40 (libunity.so) ? 0x463b40
08-16 19:14:33.939 29962 30002 E Unity   :  #6 0xd59b98a0 (libunity.so) ? 0x4648a0
08-16 19:14:33.939 29962 30002 E Unity   :  #7 0xd59b1a98 (libunity.so) ? 0x45ca98
08-16 19:14:33.939 29962 30002 E Unity   :  #8 0xd5b4cc08 (libunity.so) ? 0x5f7c08
08-16 19:14:33.939 29962 30002 E Unity   :  #9 0xf06fd8d0 (libc.so) __pthread_start(void*) 0x13
08-16 19:14:33.939 29962 30002 E Unity   :  #10 0xf06cffe2 (libc.so) __start_thread 0x3
08-16 19:14:33.939 29962 30002 E Unity   :
08-16 19:14:33.939 29962 30002 E Unity   : (Filename: /Users/builduser/buildslave/unity/build/Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 340)` 

I use:

- Unity 2018.3.1f1
- AVPro 1.10.0
- ExoPlayer with OES
- MP4 vie URL from device

This error does not always happen. Sometimes within the first video played, sometimes after several videos have been watched. But always when a video is being watched with AVPro.

**Comment by AndrewRH** [comment]
Thanks for reporting this.  We'll see whether we can replicate it.

In the meantime, could you please try changing the API from ExoPlayer to MediaPlayer to see whether that helps?

Thanks,

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.
