### ISSUE TITLE
Resolve To RenderTexture doesn't work on Android

### ISSUE THREAD

**Issue by LudovicWVirtysens** [RenderHeads/UnityPlugin-AVProVideo#1500]
I have a similar probleme as #1289
Normaly this problem is solved since a long time.
I don't know if my procedure is the good way to display my video and have the posibilty to change contrast, and brightness

Setup:
Unity version: 2021.3.18f1
AVPro Video version 2.7.3
Operating system version: WIndows 11 / Android
Device model: PICO G24K

To Reproduce

Create a new empty project in unity
Import AVPro and add a media player with any 360 video
Create a render texture 2D and add it to Demo 360 material
Create new sphere and add material Demo-360
Add a Resolve To RenderTexture component and referencing the render texture
Build for android
Expected behaviour: video displays properly both in playmode and android build
Actual result: video displays in playmode, but not on the device

**Comment by Chris-RH** [comment]
OK, so there was a change somewhere between 2.6.7 and 2.7.3 that made it stop working then?

**Comment by LudovicWVirtysens** [comment]
Yes I think so

**Comment by Chris-RH** [comment]
What gradle errors are you getting?

**Comment by LudovicWVirtysens** [comment]
The problem is not with graddle, it just need to upgrade graddle if I want to use the last version.

**Comment by Chris-RH** [comment]
Could you check 2.7.0 and 2.7.1 please?

**Comment by LudovicWVirtysens** [comment]
Hi, 
I have check this morning, same problem with 2.7.0

**Comment by Ste-RH** [comment]
I have followed the steps in the original post and get a video playing.  Is this device specific?  I am using the following:

Device: Xiaomi Mi10T
Unity: 2021.3.20f1
AVPro v2.7.3 Ultra

**Comment by Ste-RH** [comment]
Also checked Unity 2021.3.18f1.  Video renders as expected.

**Comment by Chris-RH** [comment]
Are you able to send us a simple reproducible project to test please? You can email [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com). Thank you :)

**Comment by LudovicWVirtysens** [comment]
You right, It works on my Xiaomi Mi12 but not on Pico G24K

**Comment by LudovicWVirtysens** [comment]
When I use "Apply to material" instead "Resolve To RenderTexture" it works but I can't change contrast, brightness ...

**Comment by Chris-RH** [comment]
Could you update to AVPro Video 2.8.0 please.
Are you able to provide a logcat from the PicoG24K?

**Comment by Chris-RH** [comment]
1. Could you update to AVPro Video 2.8.0 please.
2. Are you able to provide a logcat from the PicoG24K?

We'll close this if there is no response soon.

**Comment by LudovicWVirtysens** [comment]
I have check the new version and it works. 
perfect.
