### ISSUE TITLE
Unity Audio is no longer playing when entering from background to foreground on iOS

### ISSUE THREAD

**Issue by adrianplapamaruintenselife** [RenderHeads/UnityPlugin-AVProVideo#1508]
- Unity version:  2021.3.18f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  v2.7.3 ultra edition
 - Operating system version: 16.3.1
 - Device model: iPhone XS
 - Video specs (resolution, frame-rate, codec, file size): 

1. Create a simple Unity project for iOS with one MediaPlayer and AudioSource
2. Interrupt the app by putting to background
3. Return the app to foreground: The audio is no longer playing

Note: When media player is stopped, the issue doesn't reproduce anymore.
The Audio Source is not related to Media Player. It's just an Audio Source with a separate audio clip.

Video:
https://drive.google.com/file/d/1WXD_hY2k1lf02efurOMFe6zIT7cszxNX/view?usp=sharing

**Comment by adrianplapamaruintenselife** [comment]
I found a workaround by pausing the MediaPlayer on app pause and play on resume.

```
private void OnApplicationPause(bool pause) {
          if (pause) {
	          m_mediaPlayer.Pause();
          } else {
	          StartCoroutine(Delay(1f, m_mediaPlayer.Play));
          }
}

private IEnumerator Delay(float delay, Action onComplete) {
          yield return new WaitForSeconds(delay);
          onComplete?.Invoke();
}
```

I wait a delay of 1 seconds, because sometimes the media player don't start when playing immediately after resume.

**Comment by Chris-RH** [comment]
So the audio source is not running via the mediaplayer?

**Comment by adrianplapamaruintenselife** [comment]
The Audio Source is not related to Media Player. It's just an Audio Source with a separate audio clip. The video doesn't contain any sound.

**Comment by Chris-RH** [comment]
Ah, then there's not really anything that we can do about that.  You should probably stick with your workaround. :)

**Comment by adrianplapamaruintenselife** [comment]
I think the Media Player it somehow modify the AVAudioSession on iOS or maybe the Unity Audio because the issue doesn't happen when the Media Player is stoped.

**Comment by Chris-RH** [comment]
Hi, 

We don't touch the audio session with media player.  If it is being modified, then it must be by AVFoundation, but that is unlikely as it should be correct for playback.
What is it that makes you think that the audio session is being changed?


If you want us to investigate, please can you send us a simple sample project to unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Fixed

**Comment by adrianplapamaruintenselife** [comment]
God news, thank you!
