### ISSUE TITLE
A Question about roadmap feature in 2.0.0 Alpha, Windows RT Plugin

### ISSUE THREAD

**Issue by cdytoby** [RenderHeads/UnityPlugin-AVProVideo#151]
I noticed that in Document's Release History, in the section 2.0.0 Alpha version, there is a thing called "New Windows RT plugin". 

I want to ask if this "Windows RT" means plugin for UWP, or plugin for Windows Desktop?

"stereo videos containing stereo metadata didn’t display correctly" This is the fix we're waiting for. If this fix will also be available for Windows Desktop, we will change our intern roadmap a little bit.

One more thing, when will you release 2.0.0?

**Comment by AndrewRH** [comment]
Hi,

The Windows RT plugin is currently for Windows Desktop, but I believe it is UWP compatible so we'll be looking at providing UWP support as well, but perhaps not initially.

Yes the stereo metadata fix :) It will be available for Windows Desktop.

We still don't have a firm date for 2.0.0 release.  Unfortunately we've been delayed by other projects....  Still planning for this year though.

**Comment by cdytoby** [comment]
Thanks for the information.

**Comment by cdytoby** [comment]
One more question: why do you call it windows RT? From my understanding, the word "RT" was windows mobile system and it's now dead and replaced by the word UWP, and RT doesn't exist anymore.

**Comment by AndrewRH** [comment]
Hehe..yeah it's confusing...

Actually it refers to WinRT: https://en.wikipedia.org/wiki/C%2B%2B/WinRT

I'm sure we'll rename it, as it just refers to internal implementation details...

**Comment by AndrewRH** [comment]
If everything is answered can we close this issue?

**Comment by cdytoby** [comment]
Ah, ok, I see. You can close the ticket.
