### ISSUE TITLE
Bug in function TextTracks.SetActiveTextTrack 

### ISSUE THREAD

**Issue by LudovicWVirtysens** [RenderHeads/UnityPlugin-AVProVideo#1512]
Bug in function mediaPlayer.TextTracks.SetActiveTextTrack();

Setup:
Unity version: 2021.3.18f1
AVPro Video version 2.7.3
Operating system version: WIndows 11 / Android
Device model: PICO G24K

**To Reproduce**

to enable or diseable subtittle I use :

if (mediaPlayer.TextTracks.GetActiveTextTrack() != null)
{
    mediaPlayer.TextTracks.SetActiveTextTrack(null);
}
else
{
    mediaPlayer.TextTracks.SetActiveTextTrack(mediaPlayer.TextTracks.GetTextTracks()[0]);
}

At the begining I can enable my subtitle ( mediaPlayer.TextTracks.GetActiveTextTrack() is null)
When I deseable it : it works the function SetActiveTextTrack diseable the subtitle but not set the Activetrack to null
when I want to enabled again, it doesn't works because mediaPlayer.TextTracks.GetActiveTextTrack() don't return null
The value is the same as before

**Comment by Chris-RH** [comment]
Are you having this issue in Windows (editor or build?) or just Android?

**Comment by LudovicWVirtysens** [comment]
I don't know, I can't test on Windows.

**Comment by LudovicWVirtysens** [comment]
this problem is for sure on Android, can you resolved this problem please ?

**Comment by LudovicWVirtysens** [comment]
Hi, some news about this bug ?

**Comment by Chris-RH** [comment]
It seems that on Android in AndroidMediaPlayer.cs  function InternalSetActiveTrack()  it is returning FALSE instead of TRUE when setting the text (and maybe others?) track to an index of -1 (which should set all subtitle tracks to inactive)

SetTextTrack() it be returning false when the track index is -1

**Comment by Ste-RH** [comment]
I was not able to reproduce this in v2.x.

For v3.x you can call:

_MediaPlayer.TextTracks.SetActiveTextTrack( null );

I also found a small v3 only issue where subtitles would stay on screen when they should not have been.  This has been fixed for v3.0.3
