### ISSUE TITLE
AVProvideo付费购买后是永久使用吗？

### ISSUE THREAD

**Issue by linzhonglong** [RenderHeads/UnityPlugin-AVProVideo#1513]
**Question**
1: AVProvideo付费购买后是永久使用吗？不需要再次购买吧
2：只能通过Unity asset store购买吗？有没有其他途径，如有请提供
3: 请提供客服电话，以便于咨询

急需购买，请尽快回复，谢谢

**Comment by Chris-RH** [comment]
1. Yes, you only need to pay once for each version/edition, then you can use it as much as you want.
2. All editions are only purchased via the Unity Store, apart from the Enterprise edition (for larger companies): https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions
3. We don't do telephone consultations, but if you need further information, please email [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
