### ISSUE TITLE
[libc.so] pthread_mutex_lock

### ISSUE THREAD

**Issue by joywater** [RenderHeads/UnityPlugin-AVProVideo#1514]
Hello,we update the avpro to 2.6.7 to resolve the ios memory leak, but it has other crash(but i can not reappear it,only
know in the google play center), so I upgrade it to 2.7.3, and the crash reduce much, but it still have
GameEngine:Unity20200328,
AVPro:2.6.7,2.7.3
 
this is 2.6.7:
        
![image](https://user-images.githubusercontent.com/25529669/232368651-ca22c4f4-1e53-46fd-a4c5-c70f5bb5bf75.png)
 and this is 2.7.3:
![image](https://user-images.githubusercontent.com/25529669/232368859-e1e99f19-9365-4eed-871b-2af2cad3405e.png)
Because,this is the all the player's crash in google,I can not gave a demo that has the crash. Thanks!

**Comment by joywater** [comment]
<html><body>


04-18 08:09:36.361 16489 16489 E CRASH   : other thread is trapped; signum = 11
--
13304-18 08:09:36.361 16489 16489 E InputEventReceiver: Exception dispatching input event.
13404-18 08:09:36.361 16489 16489 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
13504-18  08:09:36.362 16489 16489 E MessageQueue-JNI: java.lang.Error: *** ***  *** *** *** *** *** *** *** *** *** *** *** *** *** ***
13604-18  08:09:36.362 16489 16489 E MessageQueue-JNI: Version '2020.3.28f1  (83e91068c725)', Build type 'Release', Scripting Backend 'il2cpp', CPU  'arm64-v8a'
13704-18  08:09:36.362 16489 16489 E MessageQueue-JNI: Build fingerprint:  'OPPO/CPH2363T2/OP533FL1:13/TP1A.220905.001/S.e3b54d-1-21495:user/release-keys'
13804-18 08:09:36.362 16489 16489 E MessageQueue-JNI: Revision: '0'
13904-18 08:09:36.362 16489 16489 E MessageQueue-JNI: ABI: 'arm64'
14004-18 08:09:36.362 16489 16489 E MessageQueue-JNI: Timestamp: 2023-04-18 08:09:31+0700
14104-18  08:09:36.362 16489 16489 E MessageQueue-JNI: pid: 16489, tid: 30937,  name: AudioTrack  >>> com.newtypegames.dl2hmt <<<
14204-18 08:09:36.362 16489 16489 E MessageQueue-JNI: uid: 10315
14304-18 08:09:36.362 16489 16489 E MessageQueue-JNI: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x55555555555565
14404-18  08:09:36.362 16489 16489 E MessageQueue-JNI:     x0  5555555555555565   x1  0000007a3250aa80  x2  000000000000000a  x3  64696f547261636b
14504-18  08:09:36.362 16489 16489 E MessageQueue-JNI:     x4  000000000000000a   x5  64696f547261636b  x6  3928277223ff6a62  x7  7f7f7f7f7f7f7f7f
14604-18  08:09:36.362 16489 16489 E MessageQueue-JNI:     x8  b400007a9b21e800   x9  0000007b1f2b9000  x10 0000000000000003  x11 000000000000002e
14704-18  08:09:36.362 16489 16489 E MessageQueue-JNI:     x12 0000007a3250a3da   x13 000000000000006b  x14 0000000000000000  x15 0000000000000000
14804-18  08:09:36.362 16489 16489 E MessageQueue-JNI:     x16 0000007ba1b49178   x17 0000007bc2b56988  x18 0000007919a62000  x19 5555555555555565
14904-18  08:09:36.362 16489 16489 E MessageQueue-JNI:     x20 5555555555555555   x21 ffffffffffffffff  x22 0000000000000180  x23 0000007bb1e7499f
15004-18  08:09:36.362 16489 16489 E MessageQueue-JNI:     x24 b400007af6381220   x25 0000007a3250aa88  x26 0000000000000300  x27 0000007ba1b461b0
15104-18 08:09:36.362 16489 16489 E MessageQueue-JNI:     x28 0000000000000000  x29 0000007a3250a990
15204-18 08:09:36.362 16489 16489 E MessageQueue-JNI:     sp  0000007a3250a990  lr  0000007ba1b2bad4  pc  0000007bc2b56998
15304-18 08:09:36.362 16489 16489 E MessageQueue-JNI:
15404-18 08:09:36.362 16489 16489 E MessageQueue-JNI: backtrace:
15504-18  08:09:36.362 16489 16489 E MessageQueue-JNI:       #00 pc  00000000000e6998  /apex/com.android.runtime/lib64/bionic/libc.so  (pthread_mutex_lock+16) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
15604-18 08:09:36.362 16489 16489 E MessageQueue-JNI:
15704-18 08:09:36.362 16489 16489 E MessageQueue-JNI: 	at libc.pthread_mutex_lock(pthread_mutex_lock:16)


</body>
</html>
this is our google playercenter:
![image](https://user-images.githubusercontent.com/25529669/232656465-b60b4357-b9b2-49db-ac85-d669ad1e00c6.png)
this is our bugly:
![image](https://user-images.githubusercontent.com/25529669/232656655-23adf12e-85ac-46d3-a411-c4439ae97dc9.png)

we use a static picture to relace video, and the video node is not active when the game start,but the crash still exist  
![image](https://user-images.githubusercontent.com/25529669/232656994-ecbaa7d9-a15b-4ab4-a065-2d169a0c7708.png)

**Comment by Chris-RH** [comment]
I'm afraid that I can't see anything there that points to AVPro being the culprit.
