### ISSUE TITLE
Pixelation / Artefacts during video playback in Media Foundation & WinRT

### ISSUE THREAD

**Issue by danielok1993** [RenderHeads/UnityPlugin-AVProVideo#1515]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
We are using 2 screen setup, one with touch screen to control the content on the 2nd screen. When playing videos via Media Foundation or WinRT we randomly get the artefacts in forms of very large pixels. 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra
 - Operating system version: Windows 11 Home, 64Gb RAM, RTX3080, Intel i9 12th gen
 - Device model: N/A
 - Video specs (resolution, frame-rate, codec, file size): 
 - 
 The original file is  3840x2160 ProRes 422 HQ, we then use ffmpeg to encode it to an mp4 compatible with Windows

fmpeg -y -i $SOURCE -pix_fmt yuv420p -c:v libx265 -crf 17 -preset slow -movflags faststart -tag:v hvc1 $TARGET

 3840x2160, 10bit/8bit 4:2:0 60FPS, Tired H265, H264 and AV1, +- 6Mbs

**Videos**
I will send an email with the link to the email below. 

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
So does the video have artefacts when played in any other player?
Have you tried it in DirectShow?
Do you get the same thing when you have tried the other formats?
Are you able to provide a sample the actual video please?

**Comment by danielok1993** [comment]
Hi @Chris-RH,

Appreciate the fast response, please find answers to your questions:

1. No artefacts in built-in windows media player or Films & TV player, but the playback does stutter randomly.
2. DirectShow works perfect, smooth playback, however, we cannot use it as it blocks the main thread during loading which breaks some of our animations. We need to load the videos at runtime, as they are controlled by a content management application. 
3. Yes, all encoders (H264, H265, AV1) result in the same artefacts.
4. Will send over a sample video shortly.

Thanks.

**Comment by Chris-RH** [comment]
I've tested it in a new project just running the AVPro MediaPlayer demo scene.  I'm not seeing any artefacts.
Have you been doing all the testing on the same PC/screen? Have you tried a different one?
Have you tried it just running in the MediaPlayer demo scene?
Have you tried running the profiler while its running to see if anything shows up when you get the artefacts?
Are you always getting the artefacts at the same point, or is it completely random?

**Comment by danielok1993** [comment]
We can't see any artefacts in the editor, but we can see it on a deployed version. We have tried on different monitors and computers with the same effect. The artefacts are completely random and we have also tried it with a sample video tester app that we have created that does nothing but playing videos.

**Comment by danielok1993** [comment]
Ok, we have figured it out, this is caused by vsync being enabled (We were on quality ultra settings, moved to low). The issue is, when we disable vsync then the application runs at an insanely high frame rate 1700FPS, causing high CPU and GPU usage. When we use targetFramerate to limit the FPS, then rest of the app suffers from tearing issues.

**Comment by Chris-RH** [comment]
What is your monitor refresh rate, and what are you setting targetFramerate to?

**Comment by danielok1993** [comment]
Both the touch screen and the external screen are set to 60Hz, which is what they support. We have tried setting the targetFramerate to 60 and 120, with the latter having better results, but still a lot of tearing.

**Comment by Chris-RH** [comment]
Have you tried smooth video: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-smooth-video.html

**Comment by danielok1993** [comment]
Hi @Chris-RH, we gave smooth video a try and it solves the issue, we can have the vsync on and the video artefacts are gone. The issue now is, this is an experimental feature, so it might be hard to convince project managers to implement this in a production software. 

I am wondering why this issue is not present in DirectShow, but only in Media Foundation and WinRT. Is this a bug or limitation? Alternatively, it would be great if DirectShow video loading was asynchronous to stop blocking the main thread.

**Comment by Chris-RH** [comment]
I'm glad that the smooth streaming worked for you. I would suggest testing some more on different hardware to make sure it is working consistently.
