### ISSUE TITLE
Codec error on Android

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1517]
**Describe the issue**
I just played the video.
Video was not played only on certain device.
Please check..

Playable URL: https://moctobpltc-i.akamaihd.net/hls/live/571329/eight/playlist.m3u8
Non-Playable play: https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): enterprise
 - Operating system version: Android 12
 - Device model: Galaxy S20+
 - Video specs (resolution, frame-rate, codec, file size): https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Logs**
```
2023-04-21 18:59:02.829 16856-17088/com.skt.treal.jumpvrm D/AVProVideo: nativeInit : g_iCallDetailsReferenceCount = 1
2023-04-21 18:59:02.837 16856-17088/com.skt.treal.jumpvrm D/AVProVideo: UnityPluginLoad CALLED
2023-04-21 18:59:02.925 16856-17088/com.skt.treal.jumpvrm I/AVProVideo: CREATED new ExoPlayer object
2023-04-21 18:59:02.930 16856-17088/com.skt.treal.jumpvrm I/Unity: [AVProVideo] Creating player 0
2023-04-21 18:59:02.931 16856-17088/com.skt.treal.jumpvrm I/Unity: [AVProVideo] Initialising AVPro Video v2.7.3 (native plugin v2.7.1f1-core) on Adreno (TM) 650/OpenGL ES 3.2 V@0502.0 (GIT@193b2ee, I593c16c433, 1633593732) (Date:10/07/21) (MT True) on Android
2023-04-21 18:59:02.932 16856-17088/com.skt.treal.jumpvrm I/Unity: [AVProVideo] Opening https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8 (offset 0) with API ExoPlayer
2023-04-21 18:59:04.425 16856-17088/com.skt.treal.jumpvrm I/System.out: AVProVideo error MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.4D400D, 550172, null, [256, 106, -1.0], [-1, -1]), format_supported=YES
2023-04-21 18:59:04.449 16856-17088/com.skt.treal.jumpvrm E/Unity: [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
```

**Videos**
https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Comment by Chris-RH** [comment]
I think this might be an issue with something not releasing the decoder, so it isn't available when you want to play your video
Have you made sure that nothing else on the device is using the video codecs?
Are you making sure that you only have one video player instance at a time and destroying it before opening up another?
Have you tried using the "prefer software decoder" option in the mediaplayer component?

**Comment by dw8869** [comment]
@Chris-RH 
I'll try the "prefer software decoder" option.
What is the impact of this?
According to the documentation, it says not to be used in production, is this the solution? just test?

**Comment by Chris-RH** [comment]
I'm just interested to see if it works for testing purposes

**Comment by dw8869** [comment]
Tested using "prefer software decoder" option.
Playing sound, but not showing video.

Playable videos only sound and not showing video.

* Playable URL: https://moctobpltc-i.akamaihd.net/hls/live/571329/eight/playlist.m3u8
  * Log: [1번째영상.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11329197/1.txt)
* Non-Playable play: https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8
  * Log: [2번째영상.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11329200/2.txt)

**Comment by Chris-RH** [comment]
Have you checked these as well:
Have you made sure that nothing else on the device is using the video codecs?
Are you making sure that you only have one video player instance at a time and destroying it before opening up another?

**Comment by dw8869** [comment]
@Chris-RH 
> Have you made sure that nothing else on the device is using the video codecs?

How do i check?

>Are you making sure that you only have one video player instance at a time and destroying it before opening up another?

Only one URL was tested with one build.
Tested with a total of 2 builds.

**Comment by Chris-RH** [comment]
OK, So I was looking at this specific error code in your original logcat, which I believe implies there not being a codec available:
E/MediaCodecVideoRenderer: Video codec error
      com.google.android.exoplr2avp.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc

You need to make sure that all other apps on your device are closed before testing.

If you want to debug what app is holding MediaCodec instances, you may run adb shell dumpsys ([documentation](https://developer.android.com/studio/command-line/dumpsys) about the command). For example, with adb shell dumpsys media.resource_manager you can see which process holds the MediaCodec instance (you may run this after apps are in the background). This command will show the ID of the process, you can find the package name of the process by running adb shell dumpsys and searching for the specific PID

**Comment by dw8869** [comment]
I'll try debug and let you know.

**Comment by dw8869** [comment]
@Chris-RH 
I've tried debugging, but I can't find anything strange.
Any other way to help?

**Comment by Chris-RH** [comment]
hmm, ok.
Did the URL work on any devices at all?
Have you tested in android mediaplayer?

**Comment by dw8869** [comment]
URL that work on other devices.
How can i test android mediaplayer?

**Comment by Chris-RH** [comment]
1. Was it only that device that you are getting the issue with?  
2. What other devices have you tested it with?  
3. Which ones worked and which ones didn't?

Change the Video API from Exoplayer to android Mediaplayer:
https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---android

**Comment by Chris-RH** [comment]
Any more info?

**Comment by dw8869** [comment]
I will test it this week and let you know the results.

**Comment by dw8869** [comment]
@Chris-RH 
1. Yes, the second URL is not working on that device.(Galaxy S20+) 
2. It works on other devices.
3. As you said, I changed the video API to MediaPlayer, but it works normally.  Log: [s20+fulllog.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11485117/s20%2Bfulllog.txt)

**Comment by Chris-RH** [comment]
We've done a few fixes and updated the version of exoplayer that we are using, so can you see if there is any improvement with AVPro Video version 2.8.0 please.

**Comment by dw8869** [comment]
@Chris-RH 
Oh, thank you. I think it's been fixed. It will play without error log.

**Comment by Chris-RH** [comment]
Great news, thank you! :)
