### ISSUE TITLE
Packaging as an Android platform will result in an error

### ISSUE THREAD

**Issue by drzhou1** [RenderHeads/UnityPlugin-AVProVideo#1519]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.38f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): UnityPlugin-AVProVideo-v2.7.3-Trial.unitypackage
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-31.1-android.jar (guava-31.1-android.jar) and jetified-listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
This is a well documented issue. See [here](https://stackoverflow.com/questions/56639529/duplicate-class-com-google-common-util-concurrent-listenablefuture-found-in-modu).

Something else in your project is conflicting. Do you get the issue with a clean project using one of our demo scenes?
