### ISSUE TITLE
WebGL: Video not playing in safari

### ISSUE THREAD

**Issue by tecomochida** [RenderHeads/UnityPlugin-AVProVideo#1520]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
The demo scene output by WebGL does not play video on safari. Pressing the play button does not trigger a play event. However, when you move the seek bar, the specified location is displayed like a still image.
Both ios safari and macOS safari behave the same.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.22f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): trial
 - Operating system version: macOS 11.5.2
 - Device model: iPhone SE2 16.1.2 safari
 - Video specs (resolution, frame-rate, codec, file size): 1080p、30、H264、5.7MB、RenderHeads-1080p30-H264.mp4

**To Reproduce**
1. Import the trial into your project and set "Assets/AVProVideo/Demos/Scenes/Demo_MediaPlayer.unity" to the first scene.
2. Upload to AWS S3 and check.
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, we don't officially support WebGL.  
https://www.renderheads.com/content/docs/AVProVideo/articles/platform-webgl.html

AFAIK, iOS is not supported at all.  On macOS, I would suggest trying Chrome or Firefox for better compatibility.
Please read our WebGL documentation for further info

**Comment by tecomochida** [comment]
thank you.
