### ISSUE TITLE
Important latency when reading live video streams

### ISSUE THREAD

**Issue by guilmetj** [RenderHeads/UnityPlugin-AVProVideo#1521]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
We currently now have a 20 seconds latency for live streaming (vs. 4 seconds when reading the HLS stream directly in browser). We've tried to play with the buffer size using the following params :
- Use Live low latency
- Play Without Buffering
- Preroll Frame Count
- Parallel Frame Count
and trying also to set the config params (cf; https://github.com/video-dev/hls.js/blob/master/docs/API.md#fine-tuning) but didn't manage to decrase that latency.

This happens mainly if the live stream starts before the user is actually playing the video with the HLS url.
If user plays the video with the HLS and then the live stream starts, latency drop to 5-8 seconds 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.7 Ultra
 - Operating system version: Occurs whatever platform or operating system used
 - Device model: Occurs on all devices (iOS, Web, Windows)
 - Video specs (resolution, frame-rate, codec, file size): HLS live stream

**To Reproduce**
1. Broadcast a live stream
2. Open the player with the HLS url associated with the live stream
3. Notice the latency

NB. The latency is not due to the live stream because reading the HLS url directly inside a web player delivers a latency of 3-4 seconds max

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
What URL are you using for testing?
What web player are you using?

**Comment by guilmetj** [comment]
If you want to test. you can go in this scene and walk inside : https://play.rlty.dev/rlty/permanent-test-concert

You will have a big screen in the middle of the stage with the video playing

I broadcast a stream with these credentials:
RTMP url : rtmps://bce1b3fb87cb.global-contribute.live-video.net:443/app/
Stream key : sk_us-east-1_1HQ1784UPEjx_CluDSiE3JPckC8LZ2eekDQRvYoy4In

If you don't have OBS to send a stream you can simply go to this site https://stream.ivs.rocks/ and click on "Start streaming" you just put the RTMP url in the field "Ingest endpoint" and stream key in the corresponding field

As you can see in the scene the latency is at least 20 seconds

However if you download this plugin https://chrome.google.com/webstore/detail/hls-player-m3u8-streaming/eakdijdofmnclopcffkkgmndadhbjgka/related?hl=fr which allows you to read the video stream (enter the stream: https://bce1b3fb87cb.us-east-1.playback.live-video.net/api/video/v1/us-east-1.468423273566.channel.I78K9mNZaOlQ.m3u8), you will notice that the latency is 5/6 seconds

**Comment by guilmetj** [comment]
Did you have a chance to take a look ?

**Comment by Chris-RH** [comment]
Have you tried using low latency option with WinRT Video API?

Try this, it should seek to the earliest live time:

public void SeekToLiveTime(double offset = 0.0)
mediaPlayer.SeekToLivetime();

**Comment by guilmetj** [comment]
Hello

1. we've used SeekToLiveTime every frame while playing but it did not improve the situation
Also we did tests disabling or enabling options from Media Player component settings. Did not improve: live video stalled and still with around 20 seconds latency

2. we then used Video Player Manager Test and Examples.unity with our test video stream (setting url_LiveStream to https://bce1b3fb87cb.us-east-1.playback.live-video.net/api/video/v1/us-east-1.468423273566.channel.I78K9mNZaOlQ.m3u8) and results is still a video shown with high latency.

3. Using AVPro SDK Demo_DisplayComponents.unity demo and our test live video still shows 30 seconds latency

**Comment by guilmetj** [comment]
Hello, do you have any idea how we could solve that latency issue ?
thanks

**Comment by MorrisRH** [comment]
Hey @guilmetj 

The plugin does not add any real overhead to the playback of HLS streams (I would expect an additional frame of latency to get the frame decoded, into a texture and into Unity). Any overheads are from the underlying system and depend on the platform being used.

My testing using some readily available live streams:
BBC News 24:
- Windows (MediaFoundation): ~30s
- macOS: ~10s
- iOS: ~10s
- Android: ~10s

Oven Media Engine LL HLS Test:
- Windows (MediaFoundation): ~30s
- macOS: ~7s
- iOS: ~1.5s
- Android: ~1.5s

If you want latency to be as low as possible then I would recommend you use a LL HLS server.

**Comment by guilmetj** [comment]
we're actually already using a LL HLS server but we have higher latency that the ones you describe above.
The only way to get a low latency is to have the player running before the live stream actually starts broadcasting (in which case it can go down to 7-8 seconds). Otherwise, it's always 20-30 seconds

**Comment by Chris-RH** [comment]
There isn't really anything further that we could advise I'm afraid.
