### ISSUE TITLE
60 fps VR video judders on the Quest 2 with 60 Hz refresh rate

### ISSUE THREAD

**Issue by polymercreative** [RenderHeads/UnityPlugin-AVProVideo#1522]
**Describe the issue**
60 fps VR video content stutters / judders on the Quest 2 when the refresh rate is set to 60 Hz. It appears to be in sync and perfectly smooth for approximately 2 - 3 seconds and then seems to fall out of sync, stuttering or juddering for around 2 - 3 seconds. This pattern repeats indefinitely. Switching to 72 Hz, or 120 Hz has the usual framerate mismatch issues, but does not suffer from this alternating pattern of judder / smooth / judder.

I have tried dozens of things trying to track down the issue. Here are a few of them:
- Disabled multithreaded rendering
- Used multipass / multiview
- Switched to Open XR instead of Oculus plugin 
- Disabled phase sync
- Rolled back to 2020 LTS

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Video version:  2.7.3 (plugin v2.7.0f1-core)
 - Operating system version: (OS Version: SQ3A.220605.009.A1) || (Software Update: 50327160091800150) || (Version: 51.0.0.182.268.465860992) || (Runtime Version: 51.0.0.182.269.465861112)
 - Device model: Meta Quest 2 (Model Number: KW49CM)
 - Video specs (resolution, frame-rate, codec, file size): Tested with the following: 

       - (Resolution: 2048x2048, 4096x4096, 8192x4096) 
       - (Frame-rate: 60 fps)
       - (Codec: HEVC H.265)
       - (Bitrates tested at 4096x4096: 30 mbps, 50 mbps, 70 mbps, 100 mbps)
       - (File sizes tested between 300 MB - 1 GB)

**To Reproduce**
1. Create a blank Unity project using the VR template and install AVProVideo
6. Add a 60 fps VR video to the project and auto-play it in a VR sphere
7. Build and push to the Quest 2 headset
8. Set the refresh rate of the Quest 2 to 60 Hz using Side Quest or ADB commands
9. Run the build on the Quest 2 and look for any weird alternating juddering every 3 seconds or so

If unable to reproduce, please send a sample project to use with the correct settings, and share encoding settings (FFmpeg  or Adobe Media encoder) Thanks in advance!

**Logs**
The issue is purely a visual phenomenon, so there are no logs to share.

**Screenshots**
Wouldn't help demonstrate the issue.

**Videos**
Video capture is 30 fps and doesn't illustrate the problem. Might try capturing better footage using ADB commands if needed.

**Comment by polymercreative** [comment]
Thanks! Looking forward to solving this.

**Comment by Chris-RH** [comment]
Does the file have audio? If so, have you tried without?
Are you playing the video loaded from the headset?
Are you testing while linked to the PC?
Which video API are you using?

**Comment by Chris-RH** [comment]
OK, thank you.  I'd be interested in knowing what happens if you strip the audio track :)

**Comment by polymercreative** [comment]
Sorry to say I've been dealing with some major crunch on a different
project and haven't had a chance to yet. The deadline is tomorrow so I'll
be freed up to mess with it after that. Really appreciate you guys looking
into it though. I'll let you know when I'm able to test it.

**Comment by Chris-RH** [comment]
no problem :)

**Comment by polymercreative** [comment]
I tested it on a file without audio now and I'm still seeing the issue. I've also tested these videos in the TV app and did not see the same issue there. Not sure what the difference is, although I'm not sure if the TV app is using exo player or something proprietary. 

I'd love to help narrow this down, so if you aren't seeing the issue on your end maybe you could send me a test project at some point and we could rule out it's something unique to my hardware / setup.

Thanks!

**Comment by polymercreative** [comment]
A little while back I went looking for similar issues before posting here and this was the only relevant thing I found:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/633

At the time I was attempting to get 8K 60fps content to play back smoothly, and after reading these posts I decided my time would be better spent getting a decent 4K 60 fps video to work instead (had a deadline and needed a solution).

I know the Quest 2 can handle 8K 60 fps content smoothly because I've tested it in the TV app and had zero issues. It's a shame the issue seems to lie within Unity / Exoplayer, because I'm pretty sure I'm not the only one who has attempted to make this work and run into a wall. 

Headjack actually outlines their recommendations for 360 video content here:
https://headjack.io/knowledge-base/best-video-resolution-for-oculus-quest-2/

But when testing an 8K60 upload there, I first tried uploading with these FFMPEG settings (without allowing them to re-encode it)
ffmpeg -i input.mp4 -c:v libx265 -b:v 15M -pix_fmt yuv420p -c:a aac -b:a 192K output.mp4

And ran into the same issue when playing it back using one of their standard templates (not using their Unity SDK).
Afterward, I also tried letting them re-encode the file, and saw that they converted it to a low bitrate 4K 60 fps file.

Obviously, this is something that people should be aware of when trying to create content at this resolution and framerate in Unity for the Quest 2. Maybe if nothing else comes of this and the problem persists, at least there will be another search result telling people to stop wasting their time and pursue another way forward.

I'm not sure this is an issue with your plugin, but it would be helpful to know where the issue actually is, so the appropriate developers can be notified.

Love your plugin by the way -- we've gotten a lot of great use out of it over the years. Thanks again!

**Comment by Chris-RH** [comment]
We've done a few fixes and updated the version of exoplayer that we are using, so can you see if there is any improvement with AVPro Video version 2.8.0 please.

**Comment by Chris-RH** [comment]
Can you check which version of Oculus OS you are using please?

**Comment by Chris-RH** [comment]
We've done a few fixes and updated the version of exoplayer that we are using, so can you see if there is any improvement with AVPro Video version 2.8.0 please.

Can you check which version of Oculus OS you are using please?

**Comment by polymercreative** [comment]
Sorry for ghosting, been crazy lately. At the time of the initial testing I posted my Oculus OS details:
Operating system version: (OS Version: SQ3A.220605.009.A1) || (Software Update: 50327160091800150) || (Version: 51.0.0.182.268.465860992) || (Runtime Version: 51.0.0.182.269.465861112)

I will be sure to update and test this week when this project is wrapped.

**Comment by Chris-RH** [comment]
Any improvement with update to 2.8.1?

Which version of Oculus OS are you using?
