### ISSUE TITLE
Can't compile to target API level 32

### ISSUE THREAD

**Issue by blanxdev** [RenderHeads/UnityPlugin-AVProVideo#1523]
When trying to compile for Oculus Quest I get these errors when I set the target SDK to 32, which is required by oculus. Can't set it to 33.

`* What went wrong:
Execution failed for task ':launcher:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:
     
     Dependency ':exoplayer-core:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-dash:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-datasource:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-rtsp:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-common:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':extension-rtmp:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-decoder:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-extractor:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-database:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-hls:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-smoothstreaming:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'`

**Your Setup (please complete the following information):**
 - Unity version: 2022.2.16
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.7.3 Ultra Edition
 - Operating system version: Windows 11
 - Device model: Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by Chris-RH** [comment]
In your gradle, try this:

targetSDKversion 32
compileSDKversion 33

**Comment by blanxdev** [comment]
I enabled Custom Main Gradle Template now and changed the compile SDK to 33 but now I get this error

**Error**
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33

This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=33
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 33



**This is the gradle file:**

apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
**DEPS**}

android {
    compileSdkVersion 33
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.ress', '.resource', '.obb'] + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}**REPOSITORIES****SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**



And still the other error from before.

**Comment by Chris-RH** [comment]
So it looks like its suggesting two options:

1. This warning can be suppressed by adding android.suppressUnsupportedCompileSdk=33 to this project's gradle.properties
2. The build will continue, but you are strongly encouraged to update your project to use a newer Android Gradle Plugin that has been tested with compileSdk = 33

Have you tried either of there? 7.1.2 is over a year old now.

**Comment by blanxdev** [comment]
I tried that in the gradle.properties, but with no success. Does not change anything.
We use the sdk and grade that is provided with Unity, so we have no other version.

**Comment by Chris-RH** [comment]
So the build doesn't go through at all?
What is your min SDK?

have you tried increasing targetSDK to 33?

**Comment by Chris-RH** [comment]
any more info?

**Comment by Chris-RH** [comment]
closing due to lack of reply

**Comment by blanxdev** [comment]
Hi,

Sorry for the delay. Yes I can't get a build finished with targetSDK 32 and with your overrides.

We are publishing for Oculus Quest and it looks like they don't allow uploading builds with targetSDK 33.

"Android Target SDK version is 33, but should be 32 or lower (targetSdkVersion in AndroidManifest.xml)"

**Comment by Chris-RH** [comment]
Please upgrade to the latest version of AVPro Video.

**Comment by blanxdev** [comment]
I think I finally got it. The problem was that I only modified the gradle mainTemplate, but also had to edit the launcherTemplate
