### ISSUE TITLE
Livestream duration not being detected on Android with Mediaplayer Video API

### ISSUE THREAD

**Issue by PedroRossa** [RenderHeads/UnityPlugin-AVProVideo#1524]
Opening this issue based on a closed one from last year (Same bug still happens): https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1201

I can't receive the live stream duration on Android.
As soon as the live stream is loaded on Avpro, it sends a fixed value every time.
Eg.: GetDuration() = 1200;
Wait 10 seconds
GetDuration() = 1200;

(In the editor an iOS it works. I receive the Infinity value as described in the documentation).

I put a debug.log on the update, showing the current time of the broadcast.
As soon as the link was loaded, it got the current broadcast time and still received the same value.
This value only changes if I load the URL again on AV Pro.

It's only happening on Android.
Because of some other limitations, we can't use the ExoPlayer for Android, so we are using the MediaPlayer default.

I saved a logcat that I will attach here.
[tv.redbull.immersive-logcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11345941/tv.redbull.immersive-logcat.txt)

Unity version: **2021.3.10f1**
AVPro Video version (number and edition (trial/core/ultra/enterprise)): **AVPro Ultra version 2.7.3**
Operating system version: **Android**
Device model: **Android (Redmi note 9S)**
Video specs (resolution, frame rate, codec, file size): internal red bull broadcast link (That is working on iOS and Editor).

**Comment by Chris-RH** [comment]
Hi @PedroRossa,
The dev team is away at the moment, but will be back middle of next week :)

**Comment by royalrhumbus** [comment]
@Chris-RH following up on this. We are in QA for an application and solving this bug would be really helpful for our end consumers.

**Comment by Chris-RH** [comment]
Error Unity IS LIVE EVENT: False
The URL in the log is not a livestream? 
Was it live when you tested it and now cached? 
Have you tested it using the livestream from the original issue https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

Have you only been testing on the Redmi or are you getting this on other android devices?

What is it that is preventing you from using exoplayer? Maybe there is something that we could suggest that would allow you to use it?

**Comment by PedroRossa** [comment]
> The URL in the log is not a livestream? Was it live when you tested it and now cached? Have you tested it using the livestream from the original issue https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8
> 
> Have you only been testing on the Redmi or are you getting this on other android devices?
> 
> What is it that is preventing you from using exoplayer? Maybe there is something that we could suggest that would allow you to use it?

Yes, when we got this log the live stream was live and now it's cached.
We tested using the live stream link that you comment but it still with bugs in it.
Regarding the device used to test, we tested in different devices, our QA team tested in 3 or 4 different Android devices.
And related to the Exoplayer, we can't use it because our Unity app is running inside of a native Android app that calls it. This native app can't use Exoplayer for some reasons, that limit us to use the media player.

**Comment by Chris-RH** [comment]
OK, that's interesting, so it looks like it still might not be flagging as a livestream.

**Comment by PedroRossa** [comment]
Thank you @Ste-RH We are already talking with you by email.
Max and I will provide the link and send on the e-mail thread that we already have.

**Comment by Ste-RH** [comment]
Just tested your stream here on a Xiaomi Mi 10T using the latest version of AVPro Video.  I get 'Infinity' back.  We return 'Double.POSITIVE_INFINITY' from the class found in Double.java

**Comment by PedroRossa** [comment]
Did you believe that is a configuration on the Livestream broadcast? Have you some suggestions about what we can do to deal with it? Specially because it works on iOS and Unity Editor, we receive the correct value when running on iOS build.

**Comment by Ste-RH** [comment]
Yeah, we have checked mac/iOS, windows and ExoPlayer on Android and get the same result - a live stream.  It is just something about the stream setup that the MediaPlayer API does not like/recognise.  As MediaPlayer is a completely closed box I don't think there is not much we can do.

You said you could not use ExoPlayer - can you elaborate on why that is not an option for you?
