### ISSUE TITLE
How to Retrieve Video File Size?

### ISSUE THREAD

**Issue by josetteseitz** [RenderHeads/UnityPlugin-AVProVideo#1526]
Hello AVPro,

I am constructing video guidelines in our Unity application to help users in knowing the specs for uploading video. I am able to retrieve Duration of video by using mediaPlayer.Info.GetDurationMs() BUT how can I also retrieve the file size of the video? I have looked into "Info" and only see Duration, Frame Rate, etc...but is there a way to get the actual file size?

**Comment by Chris-RH** [comment]
Hi, there isn't any way to do it via mediaplayer.info.  
However if you are definitely playing a file, then you should be able to use .net FileInfo class to get the information.

**Comment by josetteseitz** [comment]
Great! Just wanted to double check. Thanks! Will continue to use FileInfo
