### ISSUE TITLE
HAP file not playing

### ISSUE THREAD

**Issue by BrunoAlberty** [RenderHeads/UnityPlugin-AVProVideo#1529]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Hi, I have an issue when I try to Load our video. This error shows up  File not found, codec not supported, video resolution too high or insufficient system resources. I tried to check Use Hap/NotchLC and Use custom MOV parser, tried to change Video API, moved the video somewhere else on disk, nothing works. Could you please guide me what could be wrong ? 

Thanks.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Trial plugin 2.7.3
 - Operating system version: W11
 - Device model: ROG G14 2021, 32gb Ram, 3060
 - Video specs (resolution, frame-rate, codec, file size):  Stereoscopic 8K, 7680x7680, HAP, 30gb size, 30fps

**To Reproduce**
1.  Click Browse... in Media Player component in inspector
2. Choose video.
3. Click Load and observe the error message

**Comment by Chris-RH** [comment]
Hi, 

It should definitely work under either MediaFoundation or DirectShow API.
You do need Use HAP/NotchLC and Use custom MOV parser checked, as you've said.
Make sure Hardware Decoding is checked
Other than those, it should work straight off the bat in the mediaplayer demo scene.

Try this smaller HAP:
https://user-images.githubusercontent.com/102963025/235873450-2a819fe4-7a4f-4ffe-8536-cfaa190e4950.mov

**Comment by BrunoAlberty** [comment]
Thank you for your response. One more question, my video 30 fps video is playing with non constant fps, around 45 fps at the beginning then drops to less than 10. How can I make video play at set frames per second? Cant find this in your documentation.

**Comment by Chris-RH** [comment]
Go into Task manager and look at the performance tab while you are playing the file and see how your hardware is coping.  It might just be struggling to decode the video quickly enough.

Are you sure the file is a constant framerate?
Are you using MediaFoundation or DirectShow? Do you get the same result using the other one?
Have you tried playing with the Parallel/Preroll Frame Count sliders?
Does you video have audio? Does it make a difference without audio?
Disable/Enable Low latency?
Disable Stereo Detection/Text Tracks/Facebook Audio 360
Disable logging
Disable Profiler

**Comment by Chris-RH** [comment]
Any more info?

**Comment by Chris-RH** [comment]
In task manager, you should be looking at disk performance.
You could try encoding it with more chunks so decoding is spread across more threads.
https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html#hap-codec

**Comment by BrunoAlberty** [comment]
Hi, thank you for your response.

Our video is 30fps, so I assume it has a constant framerate, or what else should I check ?
DirectShow is playing with more constant framerate, floating between 29-31 fps.
Media foundation is playing video at seemingly random fps, from 15 to 47 and I am sure this is not any performance bottleneck, video is located on M.2 PCI 3 gen. SSD, CPU 8 core 4.2ghz processor, RTX3060 6gb, even while playing video with 8 chunks.

Video that you sent is playing at 29 fps with occasional drop to 27 and up to 31 fps, is this considered normal and should not worry about this?

Tried the pararell/preroll frame count sliders, no change.
Yes the video has audio, will try without and let you know.
Low latency disabled enabled, logging, profiler, stereo detection, text track, fb audio no difference.

Vsync setting I am on 165hz monitor, tried switching to 60hz and changing Vsync setting in Unity, but no change. 

It seems that I will stick with DirectShow, but I am curious if anything can be done to be able to use Media Foundation too since I really don't know if there is any serious difference between them, will google it tho. Our goal is to play 8k stereoscopic transparent video and achieve precise and instant frame seeking.

**Comment by Chris-RH** [comment]
You can use something like MediaInfo to check if the framerate is constant or not (https://mediaarea.net/en/MediaInfo)
High bitrate might be causing an issue too. Especially if it varies.
Did you have any luck trying without audio?
