### ISSUE TITLE
Can't play the 6K/30fps video fluently.

### ISSUE THREAD

**Issue by tedyage** [RenderHeads/UnityPlugin-AVProVideo#153]
I used the trial version to make a demo, which played a one-minute 6K video with  30fps and 20MB bitrates and H.265 codec. I have installed the HEVC extension on my PC.
It was not so fluent during the playback and always caused some lag issues.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.8f1
 - AVPro Video version: 1.10.0
 - Operating system version: Windows 10
 - Device model: 
       PC
       Intel(R) Core(TM) I7-8700k CPU @ 3.70GHz
       8G Memory
       AMD FirePro W600
 - Video specs (resolution, frame-rate, codec, file size): 
       Resolution: 5760*1080
       Frame-rate: 30fps
       codec: H.265
       file-size:181MB

**To Reproduce**
1. Create a new 2d scene.
2. Put the fullscreenvideo prefab on that scene.
3. Put that video into the streamAssets folder.
4. fill the filename in the source path blank.
5. build this application and play it.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
There are a few things to look out for:
1) Make sure the quality setting is set to vsync
2) Make sure you have nothing that is generating garbage (via the Profiler)
3) Make sure to set the fullscreen mode to exclusive (in Player Settings)
4) Remove audio track from video file if it isn't needed
5) If it's still not smooth, try enabling the "Resampler" option on the MediaPlayer component

Does that help?

Thanks,

**Comment by tedyage** [comment]
@AndrewRH ，
Hi, thanks for your reply first.
I have tried the steps you provided one by one, but sadly nothing changed.
There and something I need to point out, that is when I ran my application, the video was not only couldn't play so smooth but also play quite slowly. It seems that the player couldn't play the video at normal speed.
So, could you please do some additional favor for me?

**Comment by tedyage** [comment]
Do you need me to send that video file to you, @AndrewRH?

**Comment by tedyage** [comment]
Hi, @AndrewRH.
I want to know if there is any progress to find out what reason it is that causing the trouble?
I can pass you the video file if it will help you make any progress.
Could you tell me where to pass it?

**Comment by AndrewRH** [comment]
Thanks - I wonder, did you check your Task Manager Performance tab?  I'm just wondering if there is a huge load on the CPU or GPU...  I'm not sure that the AMD Fire Pro card can do hardware decoding of videos of that resolution....  Perhaps you could include a screenshot of the Performance tab? 

The GPU is from 2012 so I really doubt it can decode a 6K video.  This leave it to the CPU which will really stuggle I think.

If you want to use us the project/video you can send it here:
unitysupport@renderheads.com  and include the link to this issue number(153)

**Comment by tedyage** [comment]
@AndrewRH , Thanks for your reply, I have made a screenshot which you wanted, and here it is: 
![Task_Manager_Performace](https://user-images.githubusercontent.com/32167109/64395704-bceb1580-d08d-11e9-8d32-cf6d1b32077a.png)

**Comment by tedyage** [comment]
There are something you need to know, that when I played that video file with local videoplayer such as VLC player, It is played quite smoothly. So I think it isn't the problem of that GPU, is it?

**Comment by tedyage** [comment]
And I have sent the video file to you via the email. Please check it out.
Waiting for your reply.

**Comment by AndrewRH** [comment]
I can see in Task Manager that the GPU is not being used for video decoding.  So either you need to change to a newer GPU, or you need to switch to a lower resolution video.

VLC is probably able to play it smoothly because their custom software decoder is better optimised for multi-core compared to the software decoder built into Windows.

**Comment by tedyage** [comment]
Hi，@AndrewRH.
I'm sorry to reply to you this late because there is another project cost me a lot of time.
After your last reply, I have deployed my program on another PC, which has NVIDIA Quadro P2000 Graphic card in it. 
As expected, it could play smoothly. But this made me have another doubt.
Does your package really have to rely on the performance of graphic card decoding when playing the 6K videos? If so, Could you give me some suggestions about which graphic cards with six interfaces can easily decode 6K/30fps videos as I use?
Note this, I must use a graphic-card with six interfaces, as the project requirement.
And again, thanks for your assists.

**Comment by AndrewRH** [comment]
Yes, for 6K Videos to play back smoothly, GPU decoding is mandatory.
I'm afraid I don't know specifically of any 6 output GPUs.  I know they're not very common though.  Couldn't you instead output a few higher resolution signals and then use some splitter hardware box if you need more outputs?  I think that's pretty standard in AV.
I will close this thread now as the original issue has been resolved.
