### ISSUE TITLE
Memory to Measure 

### ISSUE THREAD

**Issue by kyeongseoJ** [RenderHeads/UnityPlugin-AVProVideo#1533]
**Question**
Hi AVPro Team,
I want to know if there's any way to measure video's Memory based on different resolutions. (4k,fhd, hd)
I'm using Unity now, and I'm trying to profile to find "untracked memory."
While playing the mp4 and m3u8 with AVPro, I saw that "untracked memory" continued to increase.
I need your help finding cause. 
Thank you for your understanding :)

**Comment by Chris-RH** [comment]
Which platform are you using and is it the latest version of AVPro Video?

**Comment by kyeongseoJ** [comment]
1. Android Unity 2020.3.32f1
2. AVPro - ExoPlayer
3. Only for Mp4 and m3u8 type of Video to measure
4. not sure. i will chk it.

**Comment by Chris-RH** [comment]
I presume you are looking to see if there is a memory leak?

**Comment by dw8869** [comment]
@Chris-RH 
We would like to define and limit the video specifications to be used in the app by measuring memory usage by resolution.

**Comment by kyeongseoJ** [comment]
Hallo, @Chris-RH 
Thank you for your reply.
I found an increase in memory that cannot be tracked during video playback by resolution, and I want to know what caused it is causing.
I couldn't figure out the cause with Unity Profiler, so I asked if there was another way to measure memory.

**Comment by dw8869** [comment]
@Chris-RH 
Any more info?

**Comment by Chris-RH** [comment]
Can you see if there is any improvement after updating to 2.8.0 please :)

**Comment by dw8869** [comment]
@Chris-RH 
We don't know how to measure memory usage, so even if we update the version, we can't check if it's improved.
