### ISSUE TITLE
Android system plays video without sound

### ISSUE THREAD

**Issue by sunjunjie1104** [RenderHeads/UnityPlugin-AVProVideo#1535]
I use unity to package my program to play videos on an Android device. There are 3 videos in mp4 format. I use the video player that comes with the Android system to play these 3 videos. They are all normal and have sound, but in my case In the packaged program, avpro is used to play videos, only one is normal and has sound, and the other two only have pictures but no sound. I tried Exo player video api and media player video api, but none of them solved my problem.

unity2021.3.20
AVPro Video - Ultra Edition 2.4.1
Android 10
sunjunjie19941104@gmail.com

**Comment by Chris-RH** [comment]
Hi, 

1. 2.4.1 is over a year old, please can you update to the latest version of AVPro Video and then test again
2. Are the videos streaming or played locally?
3. What are the specs of the videos? resolution, audio and video codec etc
4. What android device have you tested on?
5. Can you supply a full logcat starting from before you start playing the video that won't play sound?
6. Are you able to show us what media is working and what isn't? Either post here or email [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by sunjunjie1104** [comment]
The problem has been solved, it is because of the audio encoding format, thank you

**Comment by sunjunjie1104** [comment]
> 你好，
> 
> 1. 2.4.1已经一年多了，请你更新到最新版本的AVPro Video，然后再测试
> 2. 视频是在本地流式传输还是播放？
> 3. 视频的规格是什么？分辨率，音频和视频编解码器等
> 4. 你在什么安卓设备上测试过？
> 5. 您能否在开始播放无法播放声音的视频之前提供完整的 logcat？
> 6. 您能否向我们展示哪些媒体有效，哪些无效？在此处发帖或发送电子邮件至[unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

The problem has been solved, it is because of the audio encoding format, thank you
