### ISSUE TITLE
UWP app crashing with AV PRO on some windows machine

### ISSUE THREAD

**Issue by vardanbalyan97** [RenderHeads/UnityPlugin-AVProVideo#1536]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

We made an UWP app with AV PRO and on some machines and crashes on Windows 10,11 virtual machine as well as some machines having AMD CPUs without any graphics card. And on the crash we not even getting event logs in windows event viewer.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.24f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.7.3
 - Operating system version: Windows 10, Windows 11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1.  Build the UWP app with Unity and Visual Studio.
2.  Install the app to the system.
3.  When we launch the app the app window opens up for 1 sec and then app crashes.

**Logs**
If applicable, add error logs to help explain your problem.

No log generated in Window's Event logs

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Have you tested just using a clean project and our mediaplayer demo scene?
What are the specs of the videos?
Are you testing on an actual Win 10/11 machine or just virtual machines?

**Comment by vardanbalyan97** [comment]
I have tested with clean project with av pro demo scene and also with project just having the Av pro plugin imported and did not used anywhere in the code. In both cases crash happens.

Tried to played the demo video that is provided with Av pro package.

The system had D3D12 on which the app crashes.

WinRT

If i play on actual machines having intel cpu's the app runs fine but on some machines having AMD cpus we occasionally get app crash issue and sometimes screen gets white and not able to play video. 

On VM i have tried 4-5 different VMs and the app crashes on all of them. I launch the app -> app opens up -> app crashes right away. Even no error logs are getting generated in  Event viewer of windows.

**Comment by Chris-RH** [comment]
Could you try D3D11 and see if that helps?
What are the specs of the videos?

**Comment by vardanbalyan97** [comment]
How do i change to D3D11 is there option available through code?

720p mp4 sample av pro video

**Comment by vardanbalyan97** [comment]
After changing to D3D11 getting the same issue, app is still crashing

**Comment by vardanbalyan97** [comment]
I have debugged the issue further below is the error call stack for the issue:

Assertion failed!
Program: ..._APP\build\bin\x64\Master\AppX\AVProVideoWinRT.dll
File: d:\work\rh\projects\products\avpro-video...\renderer.cpp
Line: 106
Expression: GetAPIDevice()
ucrtbase.dll !common_assert_to_message_box<wchar_t>()	Unknown
00007FF97DEDD9BC  int         3

The code is breaking at GetAPIDevice() method, what is this method used for.

**Comment by Chris-RH** [comment]
Perhaps try Media Foundation Video API
https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---windows-uwp
Are you loading from streaming assets?

**Comment by vardanbalyan97** [comment]
I don't think changing the video API or streaming source will work. The app crashing at the time of loading Av pro DLL file in UWP code, the code's control is not even reaching the unity code. I have debugged this issue by running the UWP app in visual studio debug mode. 

To replicate the issue I suggest you to please set a VM and build a simple unity UWP project with AV pro and run the UWP app in debug in visual studio.  I'm you will be able to replicate the scenario.

**Comment by vardanbalyan97** [comment]
Hi @Chris-RH any update on this issue. How do we resolve this?

**Comment by Chris-RH** [comment]
What VM are you using?
Do the VMs have GPU installed?

**Comment by vardanbalyan97** [comment]
I have used Virtual box windows VMs and also AWS VMs all of the VMs comes with Microsoft basic display adapters and AV pro app is crashing on all of them.

**Comment by vardanbalyan97** [comment]
Hi @Chris-RH any update. Are you able to replicate the issue?

**Comment by Chris-RH** [comment]
Can you:
* Get UnityPlayer.log 
* Get the dump file, instructions are here - http://docs.unity3d.com/Manual/WindowsDebugging.html "Force Applications to Create Dumps"

**Comment by Chris-RH** [comment]
Hmm, ok, that's strange.

The Windows dev is looking into this at the moment.

**Comment by vardanbalyan97** [comment]
Hi @Chris-RH any update on this issue?

**Comment by Chris-RH** [comment]
We should hopefully have something for the next update.

**Comment by Chris-RH** [comment]
AVPro Video version 2.8.2 has been released.  Please let us know if this is still an issue.
