### ISSUE TITLE
(Windows)Play a byte[] buffer video using MediaPlayer_OpenBuffer

### ISSUE THREAD

**Issue by XLG505** [RenderHeads/UnityPlugin-AVProVideo#1537]
AVProVideo:2.6.x

video format:Mp4

use: MediaPlay_OpenBuffer.cs
Media.StartOpenChunkedMediaFromBuffer(ReadLength,false);
Media.AddChunkToVideoBuffer(allbuffer[i], offset, alllen[i]);
Media.EndOpenChunkedVideoFromBuffer();
Media.Play();

Errors occur sporadically:
1. blank screen(no video  footage)
2. white screen(no video  footage)
3. There is no video picture but there is sound
4. There will be no screen for a while while the video is playing

The software runs for a day, and this problem is about once a day

**Comment by XLG505** [comment]
Unity2019.4.25f1c1
Mp4:3840x1200

**Comment by XLG505** [comment]
1.API
MediaPlayer_OpenBuffer.cs
namespace RenderHeads.Media.AVProVideo
{
	public partial class MediaPlayer : MonoBehaviour
......

2.Windows 10
3.playing multiple videos
4.video mp4 h264 bitrate:240 fps:60  video file size:2G~5G
5.in build

My video has a process of encryption and decryption, decryption of multiple byte[], and then call API to read the video

Media.StartOpenChunkedMediaFromBuffer((ulong)(ReadLength), false);
ulong offset = 0;
for (int i = 0; i < allbuffer.Count; i++)
{
    Media.AddChunkToVideoBuffer(allbuffer[i], offset, alllen[i]);
    offset += alllen[i];
}
Media.EndOpenChunkedVideoFromBuffer();

7.No error reported

The program runs throughout the day and may or may not appear with a black screen once
Unity doesn't give an error when a black screen appears
The next video can be played normally again

Is it my problem decrypting the video?

**Comment by Chris-RH** [comment]
Are all the videos encoded in the same way?
Is it any particular video that you have issue with or is it random?
240Mbps bitrate seems very high.  Have you tried a lower bitrate?
Those are pretty big files.  It may be struggling to decrypt quickly enough.  If you look in the Debug section of the mediaplayer component.  Check how many frames are being dropped.
![debug](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/d3b340ee-a1c9-441e-a533-643bb59a84db)

**Comment by Chris-RH** [comment]
Closed due to lack of reply
