### ISSUE TITLE
I would like to play the video with alpha as is.

### ISSUE THREAD

**Issue by Yoshisan0** [RenderHeads/UnityPlugin-AVProVideo#1538]
First of all, thank you for publishing these wonderful assets.

I have one problem and would like to ask a question.

I have prepared a webm vp8 video with alpha.

When I tried it, the alpha 0 part did not become transparent.

Is it possible to play the video without alpha packing?

please remember me。First of all, thank you for publishing these wonderful assets.

I have one problem and would like to ask a question.

I have prepared a webm vp8 video with alpha.

When I tried it, the alpha 0 part did not become transparent.

Is it possible to play the video without alpha packing?

please remember me.

Unity 2021.3.16f1
AVPro Vide by RenderHands Ltd version 2.7.3 (plugin v2.7.0f1-core)

**Comment by Yoshisan0** [comment]
Postscript.
I am working on a game for Android and iOS.

**Comment by Chris-RH** [comment]
Hi, 

I believe it won't be possible to play it without alpha packing.  Read our section on transparency for more details: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-transparency.html

Also, webm is not supported on iOS: https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html

**Comment by Yoshisan0** [comment]
Thanks for the reply.

Thank you for the video codec compatibility chart.

As for webm vp8, I did not do enough research.

Is it possible to playback a video with alpha without using alpha packing?

**Comment by Chris-RH** [comment]
Not for mobiles.  There is better support on Windows and macOS, but still not great.

**Comment by Yoshisan0** [comment]
Thank you very much.
