### ISSUE TITLE
Loading failed for video with multiple Ambisonic tracks on Quest 2.

### ISSUE THREAD

**Issue by EnolCook** [RenderHeads/UnityPlugin-AVProVideo#1539]
**Describe the issue**
I get an the following error when trying to load a video with ambisonic tracks on Quest 2:

"Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources."

I already have 2 other videos working with no issue. The new one is lighter.
I followed the steps here: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html

The new video load with no problem in the editor preview.

I use the "Relative To Streaming Assets Folder". 
Auto Open is true, Auto Play is false, play is done after "video.Control.CanPlay() && video.TextureProducer.GetTextureFrameCount() > 0"
The error seems to happen on Auto Open.

Ambisonic details:
5 tracks - B-format (3rd order ambic) + Stereo Head-lock. 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.10f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.6.5 core + trial
 - Device model: Meta Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 553mo, hevc, 3838x1920, 6513 kb/s, 29.97 fps, 29.97.  5 ambisonic audio tracks (tbe 8_2) muxed with FB360 Encoder 3.3.3.
 - Android Media player settings: "Exo Player" | Audio Output "Facebook Audio 360" | Channel Mode "TBE_8_2"

**Logs**
"Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources." on file load by AVPRO Media Player

Video file infos:

"
Input #0, matroska,webm, from 'Video3.mkv':
  Metadata:
    COMPATIBLE_BRANDS: isomiso2mp41
    MAJOR_BRAND     : isom
    MINOR_VERSION   : 512
    ENCODER         : Lavf59.27.100
  Duration: 00:08:12.76, start: -0.007000, bitrate: 9422 kb/s
  Stream #0:0, 1, 1/1000: Audio: opus, 48000 Hz, 10 channels, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:08:12.721000000
  Stream #0:1, 1, 1/1000: Audio: opus, 48000 Hz, 10 channels, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:08:12.721000000
  Stream #0:2, 1, 1/1000: Audio: opus, 48000 Hz, 10 channels, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:08:12.721000000
  Stream #0:3, 1, 1/1000: Audio: opus, 48000 Hz, 10 channels, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:08:12.721000000
  Stream #0:4, 1, 1/1000: Audio: opus, 48000 Hz, 10 channels, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:08:12.721000000
  Stream #0:5, 3, 1/1000: Video: hevc (Main), 1 reference frame, yuv420p(tv, bt709, left), 3838x1920 (3840x1920) [SAR 1:1 DAR 1919:960]         , 0/1, 29.97 fps, 29.97 tbr, 1k tbn (default)
    Metadata:
      HANDLER_NAME    : VideoHandler
      VENDOR_ID       : [0][0][0][0]
      DURATION        : 00:08:12.759000000
Successfully opened the file.
At least one output file must be specified
[AVIOContext @ 0000026465fcce00] Statistics: 32768 bytes read, 0 seeks
"

Video file infos of a working video:

"
Input #0, matroska,webm, from 'Video1.mkv':
  Metadata:
    COMPATIBLE_BRANDS: isomiso2mp41
    MAJOR_BRAND     : isom
    MINOR_VERSION   : 512
    ENCODER         : Lavf59.27.100
  Duration: 00:09:24.04, start: -0.007000, bitrate: 8303 kb/s
  Stream #0:0, 1, 1/1000: Audio: opus, 48000 Hz, 7.1, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:09:23.841000000
  Stream #0:1, 1, 1/1000: Audio: opus, 48000 Hz, 7.1, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:09:23.581000000
  Stream #0:2, 1, 1/1000: Audio: opus, 48000 Hz, 7.1, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:09:23.581000000
  Stream #0:3, 1, 1/1000: Audio: opus, 48000 Hz, 7.1, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:09:23.781000000
  Stream #0:4, 1, 1/1000: Audio: opus, 48000 Hz, 7.1, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:09:23.841000000
  Stream #0:5, 1, 1/1000: Audio: opus, 48000 Hz, 7.1, fltp, delay 312 (default)
    Metadata:
      HANDLER_NAME    : SoundHandler
      VENDOR_ID       : [0][0][0][0]
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:09:23.881000000
  Stream #0:6, 3, 1/1000: Video: hevc (Main), 1 reference frame, yuv420p(tv, bt709, left), 3840x1920 [SAR 1:1 DAR 2:1], 0/1, 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      HANDLER_NAME    : VideoHandler
      VENDOR_ID       : [0][0][0][0]
      DURATION        : 00:09:24.040000000
Successfully opened the file.
At least one output file must be specified
[AVIOContext @ 0000028d3995cfc0] Statistics: 32768 bytes read, 0 seeks
"

The only difference between the working & non working video seems to be the "7.1" vs "10 channels" but the guide tell that 10 channel is normal and I don't think this would cause a "Loading Failed" error.

The same video without any audio track seems to play just fine.

edit: The same video with only one audio track still fails to load. I just encoded it with audio360 encoder 3.3.3. Select Format to "FB360 Matroska", select format to " 3rd order", the ambisonic master and the headlock file and the working video (with no sound)

**Comment by EnolCook** [comment]
The video seems to load fine if I use "Rift Oculus Video" as the selected format in Audio360 Encoder.
I'm gonna try to make the final file with all audio tracks and come back to tell if I still have issues.
Thanks for AVPro;

**Comment by EnolCook** [comment]
It is now working fine with all audio processed with the "Rift Oculus Video" setting. 

The audio tracks now shows "1, 1/1000: Audio: opus, 48000 Hz, 7.1, fltp, delay 312 (default)" (like the old videos) instead of 10 channels.

I will see if the client is satisfied, at least it is now working. 
You can close the issue, I'll come back if needed.

Thanks and have a nice day.

**Comment by Chris-RH** [comment]
Glad you've got it sorted :)
