### ISSUE TITLE
360 Video not showing in Quest 2 but playing in Editor

### ISSUE THREAD

**Issue by funkyLucifer** [RenderHeads/UnityPlugin-AVProVideo#1540]
I have a 360 Video that i want to play on Oculus Quest 2. Video is 5760x2880, webm, VP9 codec with Vorbis audio.
Unity version is 2021.3.24f1 and I am using skybox with render texture. 

Video is playing in editor, but when build to headset, everything is black.
No log errors 

Any suggestions?

**Comment by Chris-RH** [comment]
You need to re-encode the video:

Video
Containers: MP4 (recommended), MPK (sideload only)
Codecs: h.264 or h.265
Bitrate: Recommended max 100Mbps

Audio
Facebook 360 Audio (TBE8 and TBE8.2), 1st order ambisonics, and stereo, in AAC and MP3.

More info here:
https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/
https://creator.oculus.com/media-studio/documentation/video-spec/

If you're wanting 360 audio, then it needs to be a .mkv with Opus codec

**Comment by Chris-RH** [comment]
Have you tried a new project with just AVPro Video and the 360 demo scene?

Can you provide a full logcat please
https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs

**Comment by Chris-RH** [comment]
any luck?

**Comment by funkyLucifer** [comment]
Yes, thank you for asking.

We managed to set everything up by following the instructions from https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/776#issuecomment-840471188

Though some of those things were not necessary and were causing some problems. My first mistake was a typo in the path that I didn’t notice for hours. Because I didn’t see it, I thought I had the same problem as the person from the thread I found. I followed the thread and noticed that I didn’t have the same files that he didn’t have because of the import problem. 

I reimported the package, but the files still weren’t there. I thought that I had messed up the project somehow, so I imported the package into a new project and tried everything from scratch. In that project I tried changing the custom manifest and even the custom main Gradle template, but that only made things worse. 

Each time I would attempt to change something in those files, the project wouldn’t render because of some Gradle error. I gave up on that and tried again from scratch. That was when I discovered my typo. In that project I didn’t change the rendering mode, didn’t add anything to my main camera because I used OVRCameraRig. I also didn’t add anything to the custom manifest and the script backend was already set to IL2CPP. The only thing I changed was setting the Write Permission to External (SDCard).

Anyway, everything is working fine now. We used trial version to see if we can achieve what we need, and now we are ready to buy the the asset. We are building only for Oculus, we don't need Windows or Apple. Is AVPro Video - Core Android Edition  sufficient in that case?

https://assetstore.unity.com/packages/tools/video/avpro-video-core-android-edition-184293

**Comment by Chris-RH** [comment]
Ahhhh, that is such an easy mistake to make.  I'm glad that you could sort it out.

Yes, you just need to purchase it for your intended platform :)
FYI, the editor will still have the watermark, but the watermark will not be in the android build.
