### ISSUE TITLE
No Error event is fired when trying to play a video from a URL that doesn't exist (404).

### ISSUE THREAD

**Issue by fdegryse** [RenderHeads/UnityPlugin-AVProVideo#1543]
**Problem description:**

If the HTTP server sends a 404 error in response to the specified URL, no error is thrown indicating that the video cannot be played.
The last log received is 
"[AVProVideo] Opening http://[non-existing-file].m3u8 (offset 0) with API WinRT"

Tested using
```
mediaPlayer.Events.AddListener(MediaPlayerEventHandler);
mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, videoURL, autoPlay: true)

...

private void MediaPlayerEventHandler(MediaPlayer mediaPlayer, MediaPlayerEvent.EventType eventType, ErrorCode errorCode)
{
	if(eventType == MediaPlayerEvent.EventType.Error)
	{
		// handle error
	}
}
```

**Device:**

At least in the Unity Editor on Windows 10, haven't tested in builds yet.

**Media:**

Tested with a m3u8 and mp4 video URL on the same server.

**System Information:**

AVPro Video: v2.7.3 (plugin v2.7.0f1-core)
Target Platform: Standalone
Unity: v2020.3.30f1 WindowsEditor
OS: Desktop - Precision 3650 Tower (Dell Inc.) - Windows 10  (10.0.19045) 64bit - French
CPU: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz - 16 threads - 32493KB
GPU: NVIDIA GeForce GTX 1650 SUPER - NVIDIA - Direct3D 11.0 [level 11.1] - 3943KB - 16384

**Comment by DapperDom** [comment]
I'm seeing the same issue as well - with almost identical code, running in Editor on MBP (build target is Android).  Have also not yet tested on device from a build.

The error log I'm seeing is this:  "[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources."

Originally running version 2.7.3 as above, but upgraded to latest (2.8.4?) with no change.  All under Unity 2020.3.48f1

**Comment by DapperDom** [comment]
Quick update that we confirmed the issue still persists on build to Android devices, so we do not believe it is Editor-specific.

**Comment by Ste-RH** [comment]
Just tried to reproduce this here and I get the error event fire in both Windows Editor and Android.

Are you able to provide a bare bones, simple test project?  If so, email is over to unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @fdegryse 
Are you able to provide a bare bones, simple test project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by fdegryse** [comment]
Hi,
I'm currently out of office for a couple of weeks, I'll get back to you as soon as possible.

**Comment by DapperDom** [comment]
Hi Chris,

Thanks for your response – I’m currently away on annual leave as well, so I’ll pick this up with you when I return – it will probably be around mis-Sept as I’m already getting my time monopolised by various other commitments when I get back to the office!

It should be fairly simple to get you a bare-bones version to look at…

Many thanks, all the best, look forward to chatting soon…
Dom


***@***.***
Dominic Jones
CTO
***@***.***

Mobile. +44 (0) 7734 453354<tel:+447734%20453354>
Office: +44 (0) 1273 094897<tel:+441273%20094897>
Email: ***@***.******@***.***>
www.wearechaperone.com <http://www.wearechaperone.com/>


***@***.***


From: Chris-RH ***@***.***>
Date: Thursday, 7 September 2023 at 10:09
To: RenderHeads/UnityPlugin-AVProVideo ***@***.***>
Cc: Dominic Jones ***@***.***>, Comment ***@***.***>
Subject: Re: [RenderHeads/UnityPlugin-AVProVideo] No Error event is fired when trying to play a video from a URL that doesn't exist (404). (Issue #1543)

Hi @fdegryse<https://github.com/fdegryse>
Are you able to provide a bare bones, simple test project to ***@***.******@***.***>

**Comment by DapperDom** [comment]
Hi Francois,

Thanks fore your response – I attempted to send you a note about 10 days ago saying I was on annual leave and would pick this up when back, but it looks like it didn’t send, so sorry for radio silence!

I’m back now but a bit buried in stuff – I’ll see if I can get someone to replicate the issue in a stripped-down project and share that shortly…

Many thanks, all the best, look forward to chatting soon…
Dom

***@***.***
Dominic Jones
CTO
***@***.***

Mobile. +44 (0) 7734 453354<tel:+447734%20453354>
Office: +44 (0) 1273 094897<tel:+441273%20094897>
Email: ***@***.******@***.***>
www.wearechaperone.com <http://www.wearechaperone.com/>


***@***.***


From: François Degryse ***@***.***>
Date: Thursday, 7 September 2023 at 10:34
To: RenderHeads/UnityPlugin-AVProVideo ***@***.***>
Cc: Dominic Jones ***@***.***>, Comment ***@***.***>
Subject: Re: [RenderHeads/UnityPlugin-AVProVideo] No Error event is fired when trying to play a video from a URL that doesn't exist (404). (Issue #1543)

Hi,
I'm currently out of office for a couple of weeks, I'll get back to you as soon as possible.

**Comment by DapperDom** [comment]
Hi Chris/all,

Apologies for not following up on this – the whole team has been heads-down on a major new release which doesn’t require video use…

I’ll re-open/re-post the issue when we have an example striped down project to share which replicates the issue…

Thanks as ever for you r help and apologies once again!
Dom

***@***.***
Dominic Jones
CTO
***@***.***

Mobile. +44 (0) 7734 453354<tel:+447734%20453354>
Office: +44 (0) 1273 094897<tel:+441273%20094897>
Email: ***@***.******@***.***>
www.wearechaperone.com <http://www.wearechaperone.com/>


***@***.***


From: Chris-RH ***@***.***>
Date: Wednesday, 18 October 2023 at 09:37
To: RenderHeads/UnityPlugin-AVProVideo ***@***.***>
Cc: Dominic Jones ***@***.***>, Comment ***@***.***>
Subject: Re: [RenderHeads/UnityPlugin-AVProVideo] No Error event is fired when trying to play a video from a URL that doesn't exist (404). (Issue #1543)

Closed #1543<https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1543> as completed.

**Comment by fdegryse** [comment]
> Hi @fdegryse Are you able to provide a bare bones, simple test project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

Hi @Chris-RH, terribly sorry for the delay, I just sent you an email with a small repro project using the latest package.

**Comment by Ste-RH** [comment]
On Android, I get the (your) error log fired:

 E  [MediaPlayerEvent] Error: LoadFailed
 
...is the issue just on Windows?

**Comment by Ste-RH** [comment]
Additionally.  Windows (MediaFoundation) fires your error log.  WinRT does not.

**Comment by fdegryse** [comment]
If that helps, I get these behaviours on my side :

**Windows Editor**
- Media Foundation : error in the event handler 
- Direct Show : no error in the event handler (but AVProVideo logs an error)
- WinRT : no error in the event handler (and no AVProVideo error log)

**Android Editor**
Both Media Player and Exo Player fire the error to the event handler.
