### ISSUE TITLE
Automaticaly drop player rate of HLS file playing in iOS

### ISSUE THREAD

**Issue by Kibisi** [RenderHeads/UnityPlugin-AVProVideo#1545]
**Describe the issue**
I stored HLS file in the cloud server.
When I play it in media player on iOS, sometimes initial player rate of HLS file automaticaly drop to 0.2 although I did not change player rate and the value of mediaPlayer.PlaybackRate is 1.
On Androide wiht Exo player, it can play wihtout any problem.
When I face the probem, I change the plyare rate by using mediaPlayer.PlaybackRate method. (Ofcorce, the the value of mediaPlayer.PlaybackRate and the actural rate is not match).
Do you have any solution?

**Your Setup (please complete the following information):**
- Unity version: 2022.2.12
- AVPro Video version: 2.7.3 ultra
- Operating system version: iOS 16.3
- Device model: iPhone 12 Pro, iPad 9th generation
- Video specs (resolution, frame-rate, codec, file size): resolution: any, frame-rate: any, codec: H.265 (iPhone or iPad camera caputure default setting), file size: any

**To Reproduce**
1. Upload the HLS file, and get URL of it.
2. Play the HLS file via media player on iOS app by calling the below method.
 mediaPlayer.OpenMedia(new MediaPath(HLSurl, MediaPathType.AbsolutePathOrURL), autoPlay: true);

**Log**
<When playing with problem>
2023-05-18 10:12:13.689756+0900 Dive[1069:227641] [Player] player item status is ready to play
2023-05-18 10:12:13.755357+0900 Dive[1069:227641] [Player] player rate changed to 0.200000
2023-05-18 10:12:13.755414+0900 Dive[1069:227641] [Player] player time control status changed to waiting to play at specified rate
<When playing without problem>
2023-05-18 10:18:25.871896+0900 Dive[1080:231971] [Player] player item status is ready to play
2023-05-18 10:18:25.933584+0900 Dive[1080:231971] [Player] player rate changed to 1.000000
2023-05-18 10:18:25.933676+0900 Dive[1080:231971] [Player] player time control status changed to waiting to play at specified rate

**Comment by MorrisRH** [comment]
If you've modified ```Max Playback Rate``` from its default value then that will explain the change in player rate to 0.2. The actual playback will be at the correct rate though so you should just ignore the log output (which is correct for the underlying player but not correct from your point of view).

**Comment by Kibisi** [comment]
Thank you for your message. I changed the max playback rate to 10 in the inspector. This will effect the problem?

**Comment by MorrisRH** [comment]
The behaviour is as expected for a max playback rate of 10. We achieve a higher max playback rate by scaling the time range of the media effectively squashing it in time (1 second becomes 5 seconds) requiring a slower playback rate for normal speed.

I appreciate the log message is confusing from your point of view, but the behaviour is correct and for a max playback rate of 10x, the default playback rate will be 0.2.

If you don't need to increase the max playback rate, I would set it back to the default value (which is 2) and the reported playback rate will be 1.0.

**Comment by Kibisi** [comment]
Thank you, I found my misunderstanding of the specificaiton. I could solve the problem.
