### ISSUE TITLE
Unity audio output not supported from Unity 2022.2.x

### ISSUE THREAD

**Issue by Mahesh2455** [RenderHeads/UnityPlugin-AVProVideo#1546]
The audio output in the media player settings for android platform when set to Unity doesn't work. The audio works only for system direct. I want both Windows and Android audio output in unity only. The reason for that is I am using FMETP plugin for audio encoding and it supports only unity audio output .

 - Unity version: 2022.2.14
 - AVPro Video version (Core edition): 
 - Operating system version: Windows 11
 - Device model: Z390 Aorus Pro
 - Video specs (resolution, frame-rate, codec, file size): 1080p,60fps,mp4,708 MB

To Reproduce
Change the audio output to System direct in media player settings

Screenshots
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/128449819/f69eae5a-efbb-4b34-ac11-3dd9010a2df8)
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/128449819/78212626-df7d-43dc-8e9d-787338a263ce)

**Comment by Chris-RH** [comment]
I think this might be a related to using Unity 2022

**Comment by Mahesh2455** [comment]
Which version of Unity should I use?

**Comment by Mahesh2455** [comment]
I actually wasted hours on this issue trying to change all the possible settings. Finally now I know the root cause. Thanks.

**Comment by Chris-RH** [comment]
It works in 2022.1.23, but stops working from 2022.2.0.  We'll have to look into why.

**Comment by Mahesh2455** [comment]
Please try to fix this issue in 2022.2.14 version. I can't downgrade my project for some reason

**Comment by Chris-RH** [comment]
We are looking into it.

**Comment by Mahesh2455** [comment]
Thank you so much. The issue is fixed now.
