### ISSUE TITLE
Audio not coming on the following android phones - Poco M2Pro and Vivo Y73

### ISSUE THREAD

**Issue by ravirajtesseract** [RenderHeads/UnityPlugin-AVProVideo#1547]
**Describe the issue**
The issue is that on the mentioned devices when we are trying to play the video it gets played properly but the Audio for that content is not coming this happens for a specific language, We are using the streaming method to load the content, Also when the language in that content is changes then the audio is coming, We are streaming M3U8 video format content.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.40f1
 - AVPro Video version (2.7.1 - ULTRA) 
 - Operating system version: Android
 - Device model: Poco M2Pro and Vivo Y73
 - Video specs (resolution, frame-rate, codec, file size): Full HD, NA, AAC, streaming asset

**Logs**
VIVO-Y73
[AVProY73Logs.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11542526/AVProY73Logs.txt)

**Comment by Chris-RH** [comment]
Does it work in editor and on some android devices?

**Comment by ravirajtesseract** [comment]
Yes it works on Editor and on other devices

**Comment by Chris-RH** [comment]
So there are multiple language tracks, and only a certain one isn't working?

**Comment by ravirajtesseract** [comment]
yes that's correct -we have 3 tracks - Hindi, Marathi, Bangali only the Hindi one is not working - NOTE - all 3 are of type AAC and for the HINDI mediaPlayer.Info.HasAudio() is returning us FALSE

**Comment by ravirajtesseract** [comment]
yes that's correct -we have 3 tracks - Hindi, Marathi, Bangali only the Hindi one is not working - NOTE - all 3 are of type AAC and for the HINDI mediaPlayer.Info.HasAudio() is returning us FALSE

**Comment by Chris-RH** [comment]
Are you able to send us a URL to test please? You can email unitysupport@renderheads.com if you don't want to post anything publicly.
Is any of the text related to the audio track in non standard characters?

**Comment by ravirajtesseract** [comment]
I will send you the URLs on email

**Comment by ravirajtesseract** [comment]
URLs have been mailed

**Comment by Chris-RH** [comment]
Can't really do anything more with this one without access to a useable URL.

The only other thought is that those specific devices don't support a bitrate and its trying to re-sample the audio.  So the re-sampler could be broken or not working on those devices.
Maybe have a closer look at the specific audio files and see how they differ from each other.
