### ISSUE TITLE
Some videos cannot be played and no corresponding decoder exists

### ISSUE THREAD

**Issue by SadasyKing** [RenderHeads/UnityPlugin-AVProVideo#1548]
Some videos cannot be played and no corresponding decoder exists.
If you can, add a decoder folder so you can customize the decoder contents.
Thanks

**Comment by Chris-RH** [comment]
Hi, 
Can you give a bit more information for your specific requirements, such as platform, codecs etc? :)

**Comment by Chris-RH** [comment]
Closed due to lack of information
