### ISSUE TITLE
H.265 not calling FirstFrameReady every time

### ISSUE THREAD

**Issue by doom3214** [RenderHeads/UnityPlugin-AVProVideo#155]
**Describe the bug**
When playing a h.265 videos 4k 60fps, it seems that FirstFrameReady event is ignored most of the time. Can you please check on it soon

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.7f1
 - AVPro Video version: 1.9.17
 - Operating system version: Window 10
 - Device model: Window 10
 - Video specs (resolution, frame-rate, codec, file size): H.265 4k 60fps

**To Reproduce**
1. If I played h.264 videos it's fine, this only happen for h.265

**Comment by AndrewRH** [comment]
Does this happen when using any of our demo scenes?  Or only when you do some custom method of loading the videos?  If so, how exactly are you loading videos?

In MediaPlayer.cs it uses the following check to decide whether to fire the FirstFrame event:

result = (m_Texture != null && m_Control.CanPlay() && m_Control.HasMetaData() && m_Texture.GetTextureFrameCount() > 0);

So it would be interesting to know which of those conditions aren't true.

Thanks,

**Comment by doom3214** [comment]
I didn't test with all your demo scenes but I was using the demo scene VideoController. Even when I was using this scene to load two h.265 videos, the firstframe was not called that the video player didn't even update the preview texture properly. So I already loaded the 2nd vid but yet the preview thumbnail is still using the first vid, assuming I wasn't auto playing.

I manage to recreate this in my own game project just by openvideofromfile with false auto play.

From the debug log, it's either m_texture or gettextureframecount not working at all. I can see meta data and canplay working as intended.

**Comment by doom3214** [comment]
From further debugging based of your If statement, this is the result of the three variable once the video is loaded.

GetTexture() = null
GetTextureFrameCount() = 0
GetTextureCount()  =1

Hope this able to help. Playing the same video on h.264 works perfectly.
