### ISSUE TITLE
Apply To Material offset property does not apply immediately

### ISSUE THREAD

**Issue by WASDMagician** [RenderHeads/UnityPlugin-AVProVideo#1551]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I'm using an Apply To Material component to display a texture then play video on a mesh, there is some distortion to this so I need to scale and offset it to have it look right.
The scale modification applies immediately, the offset however takes a moment to apply so it is visible to the user.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.49f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  Core - 2.8.0
 - Operating system version: Windows 10
 - Device model: Desktop PC
 - Video specs (resolution, frame-rate, codec, file size): 
 - Texture: 360x480, PNG, 116kb
 - Video: 360x480, 25fps, MP4, 923kb

**To Reproduce**
1. Set up an Apply To Material component linked to a target material on a separate object.
2. In the Offset and Scale section of the Apply To Material give a Y offset of .5 and a Y scale of 2.
3. Press play, you will see the scale value has applied and then after a few frames the offset value will visibly be applied.

**Comment by Chris-RH** [comment]
We've not been able to reproduce this.  If you are still finding an issue with this, please reopen and send us a test project to unitysupport@renderheads.com
