### ISSUE TITLE
Repeated skiping/seeking causes load failure

### ISSUE THREAD

**Issue by maxlov** [RenderHeads/UnityPlugin-AVProVideo#1553]
**Describe the issue**
After repeatedly seeking to different times in a streamed video, eventually it errors out and playback stops.
The error is `[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources`

**Your Setup (please complete the following information):**
 - Unity version: 2022.1.2f1
 - AVPro Video version: Ultra
 - Operating system version: Windows 11, Quest 2
 - Device model: Alienware m15 r7, Meta Quest 2
 - Video specs (resolution, frame-rate, codec, file size): Any streamed 360 video, 4096 X 2048@30 FPS

**To Reproduce**
1. Begin playing a video
2. Repeatedly seek to different points on the video
3. Video closes and below error is produced

`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1399)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:827)`

**Comment by Chris-RH** [comment]
1. How big is your buffer?
2. Are you seeking within or outside of the buffer?
3. How often are you seeking?
4. Are you using Exoplayer or Android mediplayer?
5. Are you able to provide a test stream URL?
6. Are you able to provide a full logcat please?

**Comment by maxlov** [comment]
Thanks for getting back to me so quickly! 
It looks like we are using the AVC codec
1. Buffer is the entire video length
2. Within the buffer
3. About 10 times within 8 seconds
4. This is happening on both windows using Media Foundation and Android using Exoplayer
5.  Here is one, though I am not sure how long it may last `https://wpsvrmedia-usea.streaming.media.azure.net/09d30926-1084-4469-9e3f-803b3cd0c4df/2023.01.16 - 360 - Todd - Jellyf.ism/manifest(format=m3u8-cmaf)`
6. I have attached a player log and an editor log below.
[Player.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11738410/Player.log)
[Editor.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11738422/Editor.log)

**Comment by Ste-RH** [comment]
Trying to reproduce here in Windows Editor (initially).  Using the stream you provided. I cannot reproduce.  Maybe you can send over a sample project to show the issue? unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
We will be closing this issue soon due to lack of response

**Comment by Chris-RH** [comment]
Closing due to lack of response
