### ISSUE TITLE
Quest 2: trying to open a MediaPlayer when one is already open cause "Loading failed.... etc" error  

### ISSUE THREAD

**Issue by ThibaultDpt** [RenderHeads/UnityPlugin-AVProVideo#1557]
**Describe the issue**
I want to pre-open my videos so there is no load time in the experience (a branching video player) when switching media players. 
However, in build on Quest 2, when I try to do Open a video via absolute path, the first one opens correctly, but the second does not open and throw the issue "Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources".
I tried getting the video from the SD cards, and from streaming assets, both not working.

It is however working with the 30Mo video on this website https://test-videos.co.uk/bigbuckbunny/mp4-h265

The error does not come up when the second mediaPlayer has the "Software decoding" flag enabled (but nothing is displayed on the second video)
 
Is there a known limit to the size of the video we can "pre-load"? 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.26
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 2.7.3
 - Operating system version: Android 12.1
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): For the test I used the same video 2 times
 Top/bottom 360 stereo video
5760*5760
59.97fps
60 Mbps
H265
00m06s
14.8Mb

**To Reproduce**
1. Create a Unity project with AVPro
2. Have 2 media player (EXO) and open the medias one after the other, loading the provided video
3. Target Android 
4. Build 

I will email a link to the mentioned video to  unitysupport@renderheads.com, citing this thread.

Thanks for the help!

**Comment by Chris-RH** [comment]
Hi, 

Apologies, I don't have a Quest2 to hand to test this on, but it can be looked at next week.   Are you able to provide a full logcat?

However, from the info that you have provided:

Have you looked at the video guidelines from meta?
https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/
https://creator.oculus.com/media-studio/documentation/video-spec/

Your video is already at the maximum recommendations, which I think is the reason that it is unable to load the second video.

The Big Buck Bunny videos that do work are a much lower resolution (1920x1080) and framerate (30FPS)

**Comment by ThibaultDpt** [comment]
Thank you for the quick answer!
I am not well versed in videos playback etc, but indeed my video is at the max recommended by meta (or at least 2 videos go over the max). That means that the limit is not based on the weight of the file, but more on the resolution, interesting!

However, I am never playing 2 videos a the same time, so is there another way to pre-load things in memory to avoid opening time?

**Comment by Chris-RH** [comment]
Caching: https://www.renderheads.com/content/docs/AVProVideo/articles/feature-caching.html
