### ISSUE TITLE
The application developed with Unity crashes when using AVPro to play two videos simultaneously.

### ISSUE THREAD

**Issue by szzber2022** [RenderHeads/UnityPlugin-AVProVideo#1558]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**

When developing an application with Unity, there is a chance that the application may crash when using AVPro to play two videos simultaneously on the same interface. This happens when using WinRT. Both videos are played using AVPro and the issue occurs randomly.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.21f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.80 ultra
 - Operating system version: window10
 - Device model: pc
 - Video specs (resolution, frame-rate, codec, file size): 
1920x1080
25fps
2155kbps
Hap(alpha)
1.5M and 1.3M
**To Reproduce**
1. Add DisplayUGUI and MediaPlayer components to two GameObjects, 
2. select different videos for each, and turn off autoOpen and autoPlay. 
3. Set one video to loop and the other one not to. 
4. Call the openMedia function in the script to play both videos simultaneously. 
5. Then build the program and run it.

**Logs**
If applicable, add error logs to help explain your problem.
[error.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11742819/error.log)

**Screenshots**
[Player1.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/11742831/Player1.log)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by szzber2022** [comment]
step1 Play first Video
public void playHqctAni()
        {
                hqctAni.SetActive(true);
                hqctAni.GetComponent<AVTool>().showVideo(this.hqctAniEnd);
        }
step2 
Play another video in the callback
        private void hqctAniEnd()
        {
                hqctAni.SetActive(false);
                this.isPlayHqctAni = false;
                this.playShowUserAni();
        }

Play video function
        public void playShowUserAni()
        {
            showUserAni.SetActive(true);
            showUserAni.GetComponent<AVTool>().showVideo();
            userInfoAni.gameObject.SetActive(true);
            userInfoAni.Play("bpPlay", 0, 0);
            Invoke("bpInComplete", 5f);
        }
showVideo function
public void showVideo(Action callBack = null)
        {
            this.curCallBack = callBack;
            isPlaying = false;
            if (!isPlaying)
            {
                avPlayer.Events.AddListener(Evts);
                avPlayer.OpenMedia(MediaPathType.RelativeToStreamingAssetsFolder, Video_Path);
            }
            else
            {
                avPlayer.Control.Rewind();
            }
        }
Here is a code snippet, can it help us solve the problem ，thank

**Comment by Chris-RH** [comment]
What hardware are you using the play the video?
What does the GPU performance look like when you are playing the first video looped?
What does the GPU performance look like when you try to play the second video while the first is playing?

You should be using Media Foundation or Direct Show for HAP files.

**Comment by szzber2022** [comment]
What are the requirements for videos to enable hardware acceleration? And which video API should be used to be compatible with lower hardware configurations? Could you please provide an explanation for this? Thank you very much.

**Comment by Chris-RH** [comment]
What hardware are you using the play the video?
What does the GPU performance look like when you are playing the first video looped?
What does the GPU performance look like when you try to play the second video while the first is playing?
Are the videos encoded with or without snappy?

There is a bit more info about encoding HAP files here: https://hap.video/using-hap.html
You might look at increasing number of chunks.  The number of chunks should never exceed the number of CPU cores on your display computer/the computer used for playback.

**Comment by Chris-RH** [comment]
Any more info?
