### ISSUE TITLE
AVPro Logo shows before video is effectively loaded

### ISSUE THREAD

**Issue by paatz04** [RenderHeads/UnityPlugin-AVProVideo#156]
AVPro Logo shows before video is effectively loaded when using DisplayUGUI, or when no video playing. Transparent default texture has no effect.

 - Unity version: 2019.1.8f
 - AVPro Video version: 1.10
 - Operating system version: macOS 10.14.5
 - Device model: Macbook Pro 2019 15"
 - Video specs (resolution, frame-rate, codec, file size):  1920x1080 30fps

1. Add Display uGUI script
2. Shows AV logo, should show nothing instead

<img width="426" alt="Screen Shot 2019-08-25 at 5 13 42 PM" src="https://user-images.githubusercontent.com/8363908/63645909-1a14cc00-c75c-11e9-9e18-f6b4a817df8c.png">

Any way to achieve this ?

**Comment by AndrewRH** [comment]
You can uncheck the option "Show in Editor"
![image](https://user-images.githubusercontent.com/5418126/63672550-75899d00-c7e2-11e9-8f73-32ac587b486e.png)

Does that help?

**Comment by paatz04** [comment]
Oops, my bad. Thanks
