### ISSUE TITLE
[macOS][iOS] Add support for playing local HLS media

### ISSUE THREAD

**Issue by kakusato** [RenderHeads/UnityPlugin-AVProVideo#1560]
**Describe the issue**
I cannot play HLS videos in local folders such as the StreamingAseets folder on macOS. windows played them. Is this a specification?
If the file was placed on a web server, it was fine.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.3f1
 - AVPro Video version 2.8 ultra: 
 - Operating system version: macOS 10.15.7
 - Device model: Mac mini Late2012
 - Video specs 
` ffmpeg -i input.mp4 -profile:v baseline -level 3.1 -s 1280x720 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls index.m3u8`

**Logs**
1. [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by Chris-RH** [comment]
Hi, 

Playback of local HLS is currently not supported on (i|mac|tv)OS.  It is something that we are looking to implement in the future.

**Comment by WhiizU** [comment]
Has this function been completed?

**Comment by Chris-RH** [comment]
Not yet.  This will be closed once we have implemented it.

**Comment by MorrisRH** [comment]
Support for playback of local HLS was added in version 3.
