### ISSUE TITLE
Audio Output Component stops getting audio signal after changing audio listener position

### ISSUE THREAD

**Issue by naattann** [RenderHeads/UnityPlugin-AVProVideo#1561]
Problem description:

I an object with audio output, audio source, apply to material and media player components.
When i move my player with audio listener component attached, some of the objects with previously described setup stops generating audio.
I suspect that audio output component is not getting any data from media player component since the green bar responsible for volume display stops changing.
Problem does not appear on all of the objects however coping working object and pasting in position of the working incorrectly does not help. Changing position of the not working object also does not change 
area where audio does not work.

Device (which devices are you having the issue with - model, OS version number):

Application works on windows 10 pro but it is streamed to meta quest 2 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

mp4 files

System Information:

AVPro Video: plugin v1.11.7 scripts v1.11.7
Target Platform: Standalone
Unity: v2021.3.15f1 WindowsEditor
OS: Desktop - System Product Name (ASUS) - Windows 10  (10.0.19044) 64bit - Polish
CPU: Intel(R) Core(TM) i9-10900F CPU @ 2.80GHz - 20 threads - 32652KB
GPU: NVIDIA GeForce RTX 3070 - NVIDIA - Direct3D 11.0 [level 11.1] - 8043KB - 16384

**Comment by Ste-RH** [comment]
I am afraid we are no longer supporting version 1.x of AVPro Video as it was withdrawn from sale in January 2021.  We offered 6 months support after that point.
