### ISSUE TITLE
Change resolution at runtime

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1563]
How do I change the resolution at runtime?
We are considering limiting the video resolution if the device runs out of memory.

**Comment by Ste-RH** [comment]
Assuming you mean when using an adaptive streaming solution?

This might be achievable on Android/Apple platforms using the preferred maximum resolution found in the platform options (see preferredMaximumResolution in MediaPlayer_PlatformOptions.cs)

**Comment by dw8869** [comment]
@Ste-RH 
Does it apply if I change that option during video playback? or should I change the options before loading the video?

**Comment by Chris-RH** [comment]
We do have a similar enhancement that we would like to look into implementing in the future: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1214

**Comment by dw8869** [comment]
@Chris-RH 
So.. any plan for #1214 ?

**Comment by Ste-RH** [comment]
> @Ste-RH Does it apply if I change that option during video playback? or should I change the options before loading the video?

Yes, I believe this should work on Android/Apple platforms during playback.  Though, after setting the maximum resolution and/or bitrate the underlying playback APIs will first continue to playback anything already downloaded and so you will not see an instant switch to a lower resolution.  This buffer amount, for example, can be be quite a number of seconds depending on the platform and video setup (manifest and segment lengths).

**Comment by Ste-RH** [comment]
> @Chris-RH So.. any plan for #1214 ?

This will not be implemented in version 2.x of AVPro Video.  It is on the roadmap for version 3.0 (we have no certain release date for this as yet).

**Comment by dw8869** [comment]
@Ste-RH 
Okay, thank you for the information.
