### ISSUE TITLE
Black screen in video player

### ISSUE THREAD

**Issue by Lojtra** [RenderHeads/UnityPlugin-AVProVideo#1564]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

I have a scene where I play video on informational AR board, video is linked to a servers, from where it plays (video is directly linked and works in browser). In Unity it worked ok, but when build to apk / app, only sound works. No video, just black screen.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.21f1
 - Operating system version: PC
 - Device model: Samsung S22+
 - Video specs (resolution, frame-rate, codec, file size): different resolutions

![Player](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/137171533/e9124827-e6b0-43f4-a845-af75a2a9d7ce)
![Quad](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/137171533/2530383e-269d-4057-9606-62bdf2f27921)

**Comment by Ste-RH** [comment]
@Lojtra The screen shots you include are using the Unity Video Player, not the AVPro Video asset.

**Comment by Lojtra** [comment]
Hello, yes that is Unity Video Player.

**Comment by Ste-RH** [comment]
We do not provide support for Unity's default Video Player.  AVPro is a completely independent video playback asset.  You can download the latest trial version [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/download/2.8.0/UnityPlugin-AVProVideo-v2.8.0-Trial.unitypackage) should you wish to check out our video playback solution.
