### ISSUE TITLE
AVPro Decklink and AVPro Video causing hang on quit from build 50% of the time

### ISSUE THREAD

**Issue by drinsley** [RenderHeads/UnityPlugin-AVProVideo#1567]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When we quit from our application, sometimes it hangs and we have to force it to quit. This happens when AVPro Decklink is active. 

In order to get it to not hang we have to force a script execution order as a OnApplicationQuit() and System.Diagnostics.Process.GetCurrentProcess().Kill().

**Your Setup (please complete the following information):**
 - Unity version: 2022.2.17
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.7.3, v2.7.0f1-ultra
 - AVPro Decklink 1.9.5
 - Operating system version: Windows 10
 - Device model: Blackmagic 8k Pro
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 2997, Hap, 200mb

**To Reproduce**
1. Run the .exe file from the build application
2. AVPro Decklink is running
3. No SDI input, just using SDI output
4. Run a clip using AVPro Video, see it on SDI output
5. Check there is output and it's working
6. Quit the application
7. It hangs and doesn't let us quit

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/8988151/26fa298c-8269-48c6-8572-a8b6995ca44c)

**Comment by RichRH** [comment]
Hi @drinsley,

Thanks for reporting this - I've tried to replicate it but so far to no avail, using the following steps:

- Open the DeckLink '05_OutputDemo' scene
- Import the (Ultra) Video package
- Copy the necessary Video 'Demo_MediaPlayer' media player hierarchy into the DeckLink scene
- Set the video playback to MF/HAP
- Redirect the 'MediaPlayerUI' component to the DeckLink output camera
- Create a build
- Run it for a while (video should play in baclground) then close it (repeat multiple times, always exits as expected)

I notice your Video version is slightly out of date (2.7.3 vs 2.8.1) so it might be worth testing that (there have been some possibly related fixes) but I am also using current, unreleased, versions of DeckLink (1.9.6) and Video (2.8.2) which offer further fixes and should both be released within a week or so.

Cheers,

**Comment by drinsley** [comment]
How do I 'Redirect the 'MediaPlayerUI' component to the DeckLink output camera'?

**Comment by RichRH** [comment]
Hi @drinsley,

I made the following changes:

<img width="458" alt="Screenshot 2023-07-11 101742" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/20209491/2fe6cbbe-c3a3-4804-89d3-f54de0d73581">

Cheers,

**Comment by drinsley** [comment]
Thanks!

Yeah it looks like it quits fine, I'll try and dig deeper in our project.

Cheers,
Doug

**Comment by Chris-RH** [comment]
Is this still occurring?

**Comment by drinsley** [comment]
Haven't found the reason yet, still looking in our project
