### ISSUE TITLE
Video don't load from StreamingAsset on Oculus Quest 2

### ISSUE THREAD

**Issue by Gandio** [RenderHeads/UnityPlugin-AVProVideo#1569]
Hi. When I run your demo 360stereo scene in oculus quest 2 I only see a black screen. I test it on PC with oculus link and everything works perfectly The scene configuration is the default.

 - Unity version: 2021.3.11f1
 - AVPro Video:  version 2.3.1 plugin v2.3.0f1-core
 - Device model: Oculus quest 2
 - Operating system version: Android api level 26
 
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/3966814/8a7e2077-f23d-4c6d-8ac3-208cc94b0804)

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/3966814/8471cc5c-3380-4601-b8f5-33b2c4868715)

Thank for you help!

**Comment by Ste-RH** [comment]
Have you tried updating to the latest version (2.8.0) as v2.3.1 is very old indeed.

Can you also provide your video, or URL to your video.  You can email it over to unitysupport@renderherads.com if you wish to keep it private.

Do you have a full, unfiltered logcat you can send over?

**Comment by Gandio** [comment]
Hi. I asked to the company that I work for the latest version meanwhile, I tried with the trial version 2.8.0, and the same result. I can hear the sound but I cant see the video, I test with videos that you include in streaming assets file and with this one https://vimeo.com/215988274 I tried with 4k version and with the 360p.

Thanks

**Comment by Gandio** [comment]
Hi. Finally resolved!!!

The solution: In player settings I disable the options Auto Graphics API and Multithread Rendering. I tested in trial 2.8.0 and core 2.3.1, both working.

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/3966814/c3c15f58-80a3-4ee7-8d89-58b1683d5145)

Thanks for the rapid response.

**Comment by Chris-RH** [comment]
Great! Thanks for letting us know :)
