### ISSUE TITLE
Video playback stops/freezes when pulling aux cable from iOS devices

### ISSUE THREAD

**Issue by paatz04** [RenderHeads/UnityPlugin-AVProVideo#157]
Video playback stops/freezes when pulling aux cable from iOS devices, and resets on alert interruptions. 

**Your Setup (please complete the following information):**
 - Unity version: Unity 2019.1.8f
 - AVPro Video version: 1.10
 - Operating system version:  macOS 10.14.5
 - Device model: Macbook Pro 2019
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080 H264 30fps mp4

**To Reproduce**
1. Play a video
2. Pull out aux cable
3. Video Freezes

**Comment by paatz04** [comment]
I'm calling 
` videoPlayer.Events.AddListener(OnVideoEvent);
     videoPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.RelativeToStreamingAssetsFolder,filePath,false);`

**Comment by MorrisRH** [comment]
When the audio route changes on iOS the system media playback engine becomes paused (same for unplugging headphones, disconnecting AirPods, etc.).
You need to listen for the Paused event message on the mediaplayer component and either resume playback or provide the user with the ability to resume playback (i.e. by overlaying a play button).

**Comment by paatz04** [comment]
I've looked for a Paused event before, but I can't seem to find one in MediaPlayerEvent.EventType.

**Comment by MorrisRH** [comment]
Sorry, clearly dreamed that one. Will look into adding it in a future version though.
For now can you poll the MediaPlayer.Control.IsPaused() method?

**Comment by paatz04** [comment]
That will resume the video - but I can't get it to properly sync with the audio (which plays separately via FMOD), as it seems like the video now plays while for example multi tasking on iOS, or even when just tapping in and out a each time a delay is created.

**Comment by MorrisRH** [comment]
I'm not sure what's best for resolving your sync issue. Perhaps seek to a specific time/frame and resync your audio accordingly?

Tying MediaPlayer.IsPaused with MonoBehaviour.OnApplicationFocus and MonoBehaviour.OnApplicationPause on your logic will allow you to better handle the multitasking issue.

Unfortunately pausing playback when the audio session route changes is a system level behaviour so there is not much to be done. However... I have added an option to the MediaPlayer for iOS that will allow you to auto-resume playback when the audio session route changes. This will be available in the next release and hopefully will help solve your issue.

**Comment by paatz04** [comment]
Thank you, that will be help for sure. Does your library expose Notifications for when the session route changes or for example AVAudioSessionInterruptionNotification? Those would be super useful...

**Comment by MorrisRH** [comment]
The auto-resume feature has made it into the latest release, hope it helps.
