### ISSUE TITLE
3D video

### ISSUE THREAD

**Issue by AlexanderDzz** [RenderHeads/UnityPlugin-AVProVideo#1573]
**Question**
I have pro version of the player, how can I work with 3D videos?

I use 3D Stereo Video (https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html) with " Top Bottom" config, in result video consists of 2 parts and looks like it's been filtered.

Perhaps there is a requirement or examples for 3D video? Or do I need to apply other settings for the player?

**Comment by Chris-RH** [comment]
Hi,

What platform are you using?
As mentioned in the documentation, stereo packing should be auto-detected.  

Is it flat stereo video?
Use the demo mediaplayer. (Play Cones-Transparent-2K60-H264.mp4 from streaming assets.  transparency on + top/bottom alpha packing)

Is it a 360 stereovideo?
We have the 360 demo scene which maps a 360 equi-rectangular stereo video onto a sphere (https://www.renderheads.com/content/docs/AVProVideo/articles/usage-demos.html#360-stereo-demo).  Perhaps try replacing that video with yours?

Could you show us a picture of how it is looking? What settings are you using?
If there is a particular video that you are having issues with, you could mail it to us at unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Any more info?

**Comment by Chris-RH** [comment]
Closed due to lack of reply
