### ISSUE TITLE
How to use Resolve To Render Texture

### ISSUE THREAD

**Issue by LudovicWVirtysens** [RenderHeads/UnityPlugin-AVProVideo#1574]
Hi, 

Since the last version (2.8.0) on Android the Resolve To Render Texture works correctly.
If I change all options (hue, contrast, brightness... ) in Unity inspector, the video brightness change.
Now I want to change it by code, I have try :

```
public void HueChange(float value)
    {
        VideoResolveOptions _options = mediaPlayer.VideoResolveOptions;
        _options.hue = value;
        mediaPlayer.VideoResolveOptions = _options;
}
```
but no changes during video playing.
What I'm doing wrong ?

**Comment by Chris-RH** [comment]
Which platform are you using?
Are you able to change it by code at all or is it just not while it is already playing?

**Comment by LudovicWVirtysens** [comment]
platform headset Pico G24K on Android. 
When I change during video is reading, no effect on display

**Comment by Chris-RH** [comment]
Hi, 

We've looked into this further and currently it is not possible to do via code.  We will add support for this.

**Comment by MorrisRH** [comment]
VideoResolveOptions are now available on the ResolveToRenderTexture component so can modified via script as follows:

```csharp
ResolveToRenderTexture resolve = gameObject.GetComponent<ResolveToRenderTexture>();
if (resolve != null)
{
    VideoResolveOptions options = resolve.VideoResolveOptions;
    options.applyHSBC = true;
    options.hue = 0.5f;
    resolve.options = options;
}
```

This will make it into the next release.

**Comment by Chris-RH** [comment]
AVPro Video version 2.8.2 has been released.  Please let us know if this is still an issue.
