### ISSUE TITLE
error when upgrading AVPro

### ISSUE THREAD

**Issue by keasukei** [RenderHeads/UnityPlugin-AVProVideo#1576]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
in 1.0, i am using IMediaControl.GetBufferingProgress, after read the Documentation, i see there is  no replacement, so  if i want to use the method GetBufferingProgress, how can i fix it ?

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.0
 - Operating system version: mac
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): mp4

**To Reproduce**
1. upgrade to 2.8.0
2. 
3. 

**Logs**
'IMediaControl' does not contain a definition for 'GetBufferingProgress' and no accessible extension method 'GetBufferingProgress'

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, 
Yes there have been a lot of changes between AVPro Video version 1 and 2.
IMediaControl.GetBufferingProgress did indeed get depreciated.
There are still a couple of buffering related options within https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.IMediaControl.html
and 
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-events.html
