### ISSUE TITLE
When I opened it the second time, it would appear like a snowflake screen.

### ISSUE THREAD

**Issue by wodenianshao** [RenderHeads/UnityPlugin-AVProVideo#1577]
Problem description:

The first time I opened the video, there was no problem and it could play normally. When I opened it the second time, it would appear like a snowflake screen.

Device (which devices are you having the issue with - model, OS version number):

Android simulator such as : LDPlayer

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1920*1080@30 , native file ,so no urls

System Information:

AVPro Video: v2.6.6 (plugin v2.6.3f1-ultra)
Target Platform: Standalone
Unity: v2021.3.16f1 WindowsEditor
OS: Desktop - Z690 UD DDR4 (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.19045) 64bit - ChineseSimplified
CPU: 12th Gen Intel(R) Core(TM) i7-12700K - 20 threads - 32539KB
GPU: NVIDIA GeForce RTX 2060 - NVIDIA - Direct3D 11.0 [level 11.1] - 5958KB - 16384

**Comment by wodenianshao** [comment]
everybody can help me, thanks

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14067700/34edd749-13a3-45ce-98dc-412f97721256

**Comment by Chris-RH** [comment]
Please update to the latest version of AVPro Video

Can you test it on an actual android device, not an emulator?

I'm not sure what you mean by "snowflake screen".  Can you provide photos?
Can you provide more information as to what media you are playing?
Have you tried a new project using just our demo scenes and videos?

**Comment by Chris-RH** [comment]
any more info?

**Comment by Chris-RH** [comment]
Closing due to lack of response

**Comment by wodenianshao** [comment]
It has been solved. Thank you for your reply
