### ISSUE TITLE
调用OpenMedia函数开始到Video准备好可以播放间的时间是不确定的。

### ISSUE THREAD

**Issue by EssaHuangXu** [RenderHeads/UnityPlugin-AVProVideo#1578]
Problem description:

我是否有方法可以在调用OpenMedia调用的时候就能够得到可用状态的Veido？

Device (which devices are you having the issue with - model, OS version number):

Window

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: v2.3.3 (plugin v2.3.2f1-core)
Target Platform: Android
Unity: v2021.3.17f1 WindowsEditor
OS: Desktop - MS-7C67 (Micro-Star International Co., Ltd.) - Windows 10  (10.0.19045) 64bit - ChineseSimplified
CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz - 8 threads - 16326KB
GPU: NVIDIA GeForce GTX 1650 - NVIDIA - Direct3D 11.0 [level 11.1] - 3949KB - 16384

**Comment by Chris-RH** [comment]
The time between when the OpenMedia function is called and when the Video is ready to play is indeterminate.
Is there a way for me to get the Veido available when calling the OpenMedia call.

1. You should update to the latest version of AVPro Video and then test again.  Version 2.3.3 is from January 2022, so 18 months old now.
2. Are you saying it takes a long time before the video starts to play?
3. Are you streaming or playing locally?
4. Is this on your android device and/or your PC? If Android, what device and OS version?
5. What are the specs of your video? Resolution, bitrate, FPS, codec etc

**Comment by EssaHuangXu** [comment]
1. My Project is used version 2.3.3 Avpro.
2. When I call OpenMedia, it return boolean to me. I think this boolean mean that the video can be played. At next frame,I play the video. I found I call GetDuration() from MediaPlayer but it return 0 ( video is 6s). 
3. Streaming,Relative To Project Folder.
4. I tested in Unity Editor, Window Platform.

I try to coding a replay system, I need to open media and count time at self update system. I get 0s from GetDuration function.
At other issue, correctly duration can get after Started or ReadyToPlay callback. Thats mean next frame the callback is not triggered.

**Comment by EssaHuangXu** [comment]
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/44046641/ced00752-ce3a-4f38-8d1c-ed962be21b06)

**Comment by EssaHuangXu** [comment]
I log my frame Index. The first video open video at 1446 frame and play at 1447. The second video open video 5057 and play at 5058. When play the second video, I got 0s duration.

**Comment by Chris-RH** [comment]
You should update to the latest version as there have been a lot of fixes.

Are you waiting for MetaDataReady event?

**Comment by EssaHuangXu** [comment]
No, I called OpenMedia Function and play video at next frame.

**Comment by EssaHuangXu** [comment]
After test:
 **indeterminate** mean I need wait few unknow second until the MetaDataReady event be triggered.
That wait duration may be one frame in my windows platform or may be take more frame in other case.

Is there any synchronized method to load video?

**Comment by Chris-RH** [comment]
Basically, there is a lot going on between OpenMedia and ReadyToPlay.   Platform variations, system load, what your app might be doing - all these things factor in and make it difficult to determine how long this will take.
Synchronous open would not work, because it would necessitate blocking the main thread.

If you are looking to speed up the process, the best thing that you can do is to play media from local storage and to make sure the mov file has been created with the faststart flag.

**Comment by EssaHuangXu** [comment]
thx for your reply.
