### ISSUE TITLE
Ripple on thin lines on video360, Oculus Quest 2

### ISSUE THREAD

**Issue by takis1631** [RenderHeads/UnityPlugin-AVProVideo#1580]
We want to display a video360 that has thin lines on a contrasting background.
If you open the video in the pre-installed viewer in the helmet  Oculus Quest 2, the lines will be displayed quite smoothly.
If you display the same video in the application using AVPro, the lines will have more noticeable steps and ripple.
We tried various project and media player settings, but none of them affected the display of lines
Is it possible to achieve the same quality as in the pre-installed viewer?

 - Unity version: 2021.3.18f1
 - AVPro Video version: 2.8.0 core
 - Operating system version: Android
 - Device model: Oculus Quest 2
 - Video specs:  mp4, 7328x1920, 24fps, h264, 746 Kb 
 Other video: mp4, 8192x4096, 25fps, 1,68 GB

To Reproduce:
1. Create Unity project, configure for Oculus Quest 2 with Oculus XR Plugin.
2. Import AvPro
3. Open Demo_360Stereo scene, add to MainCamera Tracked Pose Driver and select video example with lines in Media Player

Screenshot:
![3qvcjdGiBJQ](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/71388032/677015fb-5b59-4ba4-9b6e-42ded9ebfd80)

Video with lines
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/71388032/08a46ad5-e17c-4af6-affa-cdc25dd1ceb4

**Comment by Chris-RH** [comment]
Hi, 

That is a very odd aspect ratio and high bitrate.
It should be 2:1 aspect ratio and a recommended framerate of 30 or 60 fps and bitrate of 25-60 Mbps.

Have you got a video that meets the guidelines for 360 videos set out by Meta?
https://creator.oculus.com/media-studio/documentation/video-spec/

**Comment by Ste-RH** [comment]
It is impossible to guess at what sampling/AA the #pre-installed viewer' is using.  You can obviously add AA to your scene, and you can change the sampling in the Android platform options:

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46531149/c0d033ac-3c04-49ab-89e4-4882226162d0)

Note that this will likely not work as desired is you are using OES mode.

**Comment by Chris-RH** [comment]
Reducing field of view will also help.

**Comment by Chris-RH** [comment]
Closing due to lack of response
