### ISSUE TITLE
The WebM file couldn't be streaming played when the build was first opened.

### ISSUE THREAD

**Issue by p10588** [RenderHeads/UnityPlugin-AVProVideo#1581]
We uploaded the WebM files to AWS S3 and configured them for public access. While accessing and playing the files in the editor, everything works fine. However, after building the program, the videos fail to play correctly upon the initial launch. The log displays an error message stating "Loading failed. File not found, codec not supported, video resolution too high, or insufficient system resources." Only when we close the program and open it again for the second time do all the videos play correctly.

Unity version 2021.1.7f1
Build Platform: Standalone Windows
OS: Windows 10

**Comment by p10588** [comment]
Hi Chris 
I already send you detail you ask! If you need more information please contact me.

**Comment by Chris-RH** [comment]
I'm sorry, we haven't received your email. Please can you make sure that you used the correct address and provide all the details requested above.

**Comment by p10588** [comment]
I just sent to this Email again unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Still nothing received.  Spam has been checked.  Perhaps try sending it from a different email address?

**Comment by p10588** [comment]
Yes we played webm in standalone Windows build,
this is our video spec,
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/12834223/1c04859d-a18e-4c42-92ba-9d175875eb19)
and We use AddComponent API to add Media Player and OpenMedia to active the video 
`this.MediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, pathUrl, false); `

**Comment by p10588** [comment]
The Thread is been closed is there any solution?

**Comment by Chris-RH** [comment]
Hi @p10588,

You closed the thread, so we had presumed that the issue was solved.  We still haven't received an email from you.
