### ISSUE TITLE
DirectShow fails to load video after loading/playing a DAR video

### ISSUE THREAD

**Issue by v2k** [RenderHeads/UnityPlugin-AVProVideo#1583]
After loading and playing a DAR video (where SAR is not 1), normal videos can no longer be loaded.  MediaFoundation works without issue.

Note SAR is not 1:

```
  Duration: 00:00:13.29, start: 0.000000, bitrate: 159647 kb/s
    Stream #0:0: Video: hap (Hap1 / 0x31706148), rgb0(progressive), 960x720, 159770 kb/s, SAR 4:3 DAR 16:9, 59.94 fps, 59.94 tbr, 60k tbnefault)
```

 - Unity version: 2022.2.21f1
 - AVPro Video version: 2.8.1 trial, 2.7.3 (2.7.0f1-ultra)
 - Operating system version: Win
 - Video specs (resolution, frame-rate, codec, file size): one with DAR, one without

1. open Demo_MediaPlayer scene.
2. set MediaPlayer to DirectShow
3. in Editor, load DAR video, play it
4. load non-DAR video; notice it doesn't load - shows 0x0@0

Error:

```
[AVProVideo] Using playback path: DirectShow (0x0@0.00)
UnityEngine.Debug:Log (object)
RenderHeads.Media.AVProVideo.Helper:LogInfo (string,UnityEngine.Object) (at Assets/AVProVideo/Runtime/Scripts/Internal/Helper.cs:183)
RenderHeads.Media.AVProVideo.WindowsMediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Internal/Players/WindowsMediaPlayer.cs:827)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:822)
RenderHeads.Media.AVProVideo.MediaPlayer:EditorUpdate () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:783)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:373)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)

```
Samples videos emailed to support.

**Comment by Chris-RH** [comment]
AVPro Video version 2.8.2 has been released.  Please let us know if this is still an issue.
