### ISSUE TITLE
Cutoff with Rolloff Audio 

### ISSUE THREAD

**Issue by kathleenfox1006** [RenderHeads/UnityPlugin-AVProVideo#1584]
Hi Renderheads,

I wanted to reach out about an issue I've been having with the Audio Output. I'm building a VR Game for Quest2 on Android and I've been encountering an issue with spatial audio. There are three videos that play in the scene. They all have the same settings but only one accurately falls off as I move around the space. The other two videos have a very strong cut off with little to no specializations when I move around?. Have you seen this issue before or do you have any advice on how to move forward? Thanks in advance for any help. Here is a screenshot of the video in the hierarchy. 

 - Unity version: 2021.2.7f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): version 2.7.3 (plugin v2.7.0f1-trial)
 - Operating system version: Windows 10
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 
 Resolution: 2504 by 2048, Frame Rate 29.97, Codec H2.64, File Size 145MB

**Screenshots**

![1](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/74282499/74965519-f707-49f8-9e02-992ad4907ca7)

![2](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/74282499/4b1f1ef4-4eba-4aa2-97f0-399e9895a11d)

![3](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/74282499/c08d8b2d-a96e-4201-83e4-1b317333d8f9)

![4](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/74282499/d3276e7d-38ae-45fc-bd5f-2ce8af0ca522)

**Comment by Chris-RH** [comment]
Are you not using FB360 audio? https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html
If you are using the same component settings, are you sure that the videos are encoded in the same way?
Are you able to send us a sample of the videos? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com).

**Comment by Ste-RH** [comment]
@kathleenfox1006 If you could send a simple sample project over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) then we can look into the issue you are seeing better.

**Comment by Chris-RH** [comment]
Could you provide some more info please?

**Comment by kathleenfox1006** [comment]
Hello! Sorry I've been doing some troubleshooting and I think the issue is actually that the video seems to be freezing up. You can see it clearly in the video. Issue starts at around 1minute and 10 seconds ( first minute is to show it working as expected). When you walk away from the video it sometimes freezes but when you walk back into the area it continues as though the video never stopped. 

Video Link: https://drive.google.com/file/d/18bfp9ymrF7OC67O0nAYHIdZKM_04t6Sr/view?usp=sharing

I will email along the videos and a sample project first thing tomorrow morning. FB360 audio just kind of muted the whole thing. I am positive they are all encoded the same way.  Thanks again for the help.

**Comment by kathleenfox1006** [comment]
Hello! I am so sorry - I looked into it more the problem was unrelated to render heads, it was a scripting issue. Thank you so much for your time.

**Comment by Chris-RH** [comment]
Great, thank you for letting us know :)
