### ISSUE TITLE
trial version apply to mesh not working

### ISSUE THREAD

**Issue by kunka7** [RenderHeads/UnityPlugin-AVProVideo#1585]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.19
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): trial
 - Operating system version: window

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/626c7145-bc39-4cb2-89c2-51192e6a7363)
this is my first try, the cube is pink
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/b843b2e7-53b2-4d26-b32d-f4def05d7434)
this is my second try after follwing document
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/530459eb-7b0b-4390-9ef3-02abb4fae28f)
this is the document
what am i wrong?

if this working i will buy this plugin core version please help me

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Are you using one of the URP or HDRP render pipelines? If so you need to set ```Texture Property``` to ```_BaseMap``` in the ```Apply To Mesh``` component.

We will get the documentation updated to reflect this.

**Comment by kunka7** [comment]
@MorrisRH you mean like this? 
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14178852/c40df3d7-797b-4073-a926-f0af360a6171)
sadly its not working
