### ISSUE TITLE
Equirectangular  Video Distortion at poles

### ISSUE THREAD

**Issue by TheDevTom** [RenderHeads/UnityPlugin-AVProVideo#1586]
Equirectangular distortion / pinching at Zenith and Nidar when playing stereo-packed (Over Under) 360 Video. There are clear distortions at the top and bottom of the video when playing back, previous player ive used (which used a projection method I believe) didn't have this issue with the same video file(s). I've tried different spheres and UV maps with no avail.

**Your Setup (please complete the following information):**
 - Unity version:  2021.2.14
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core
 - Operating system version:  Windows 11
 - Device model: Desktop & VR Playback
 - Video specs (resolution, frame-rate, codec, file size): 4096 x 4096 MP4 80mbs 23.976fps

**Screenshots**
![Disrotation](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/45782622/17d3b9d5-4054-4654-916c-dc96e1222f48)

**Comment by Chris-RH** [comment]
Hi, 

As far as I know, spherical renderings will always show distortion at the poles, especially if there is fine details near the poles.  Have you tried cubemapping?

I'm interested to hear that previous players have not had this issue.  I'm wondering what they do to combat the issue,

Are you able to send us a sample of the video please? [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com).
