### ISSUE TITLE
VisionOS development question

### ISSUE THREAD

**Issue by Allen-98** [RenderHeads/UnityPlugin-AVProVideo#1587]
**Question**
Will AVPro support play HLS on the coming VisionOS platform? Or are you planning to support it?
How many audio tracks are supported at the same time？
Can it create the 3D spatial audio effects just like in the other VR platforms?

**Comment by MorrisRH** [comment]
We plan on supporting VisionOS with AVPro Video version 3 which we are hoping to release in Q4.

As we build directly on top of Apple's APIs I would expect the number of supported audio tracks to match what Apple natively support.

Support for 3D spatial audio would come from Unity and would not be something we provide support for.
