### ISSUE TITLE
A new game view is open every time that a video starts playing (Editor)

### ISSUE THREAD

**Issue by David-Luis** [RenderHeads/UnityPlugin-AVProVideo#1589]
**Describe the issue**
A new game view is open every time that a video starts playing in the editor, making the Simulator view not usable. 

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.8.1 Trial
 - Operating system version: Windows 11 Home
 - Device model: XPS 14 9520
 - Video specs (resolution, frame-rate, codec, file size): 1920 x 1080, 60fps, MP4 H.264, 20mb

**To Reproduce**
1. Open demo scene Demo_MediaPlayer
2. Use simulator view in Unity
3. Press play

**Videos**

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/709251/976bcc40-2273-41f7-bb5f-a772ffff120d

**Comment by Ste-RH** [comment]
This is just Unity's behaviour.  We believe that the 'Simulator' requires a Game window to render out from.  If you change to 'Play Focused', and hide your Game window away in the same tab group...then you just get it playing back in the 'Simulator'.

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46531149/6eca4831-f428-4017-b302-ce9e4086bb1a)

**Comment by David-Luis** [comment]
Well this is really annoying because if you play another video you lost again the focus (I'm developing a feature where you can navigate thru several videos). So this is untestable in the editor. But as you said, if this is how Unity works, probably there is nothing we can do for now.

**Comment by Ste-RH** [comment]
Complain to Unity is about all one can do :(  Sorry it is not something we can help with.
