### ISSUE TITLE
Trial - Not supported on this plaform error

### ISSUE THREAD

**Issue by StaffsJon** [RenderHeads/UnityPlugin-AVProVideo#1590]
Problem description:

Using the trial version before I buy, will be using to replace the default video player for a project targeting meta quest devices.

Opened up demo_360 stero scene, pressed load on media player, following error:

[AVProVideo] Not supported on this platform WindowsEditor HP Z2 G8 Tower Workstation Desktop PC (HP) 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz Windows 10  (10.0.19045) 64bit.  Using null media player!

Device (which devices are you having the issue with - model, OS version number):

WindowsEditor HP Z2 G8 Tower Workstation Desktop PC (HP) 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz Windows 10  (10.0.19045) 64bit. 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

Using the samples

System Information:

AVPro Video: v2.8.1 (plugin vUnknown)
Target Platform: Android
Unity: v2021.3.27f1 WindowsEditor
OS: Desktop - HP Z2 G8 Tower Workstation Desktop PC (HP) - Windows 10  (10.0.19045) 64bit - English
CPU: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz - 16 threads - 32512KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10067KB - 16384

**Comment by StaffsJon** [comment]
Also getting this error:

[AVProVideo] Failed to load DLL. AVProVideo assembly:<unknown assembly> type:<unknown type> member:(null)
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:GetPluginVersion () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor_AboutHelp.cs:52)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:IsTrialVersion () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:671)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnEnable () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:295)

**Comment by Ste-RH** [comment]
This is very strange.

Was is a new project you imported the asset to?

**Comment by StaffsJon** [comment]
An existing project, I will try importing into a fresh project and see if error persists

**Comment by StaffsJon** [comment]
Same errors on fresh project

**Comment by Ste-RH** [comment]
Just tested your project here.  Works perfectly.  Hmm.  Maybe some Windows security setting at play?

Can you send over a full editor log?

**Comment by StaffsJon** [comment]
Here you go.

I am using university domain controlled machines, I wouldn’t be surprised if that’s the issue, I do have an admin account I can try running it on.

Thanks for your help,

Jon

**Comment by StaffsJon** [comment]
I have tried another machine and it is working.

If you have any ideas how to resolve this on my office machine then please let me know, for now I will try reinstalling Unity.
