### ISSUE TITLE
Video loaded from Steaming Assets fails to play on start/ready on iOS

### ISSUE THREAD

**Issue by Wayne-nulitics** [RenderHeads/UnityPlugin-AVProVideo#1592]
When doing a new build on iOS and not using a built in splash screen the app opens, loads the Video but does not play the video.

 - Unity version: 2022.3.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 5.1.7
 - Operating system version: iOS 16
 - Device model: iPhone 12 Pro
 - Video specs (resolution, frame-rate, codec, file size): 1024x1024, H264, 2Mb

**To Reproduce**
1. Set spalsh scene to none
2. Load video from Streaming Assets folder and Render to RawImage via Render to Texture
3. Build and test
4. See error: Unbalanced calls to begin/end appearance transitions for <UnityDefaultViewController: 0x101306f60>.

**Logs**
Log Event: MetaDataReady
SplashScene:MediaPlayerEvents(MediaPlayer, EventType, ErrorCode)
UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()

Log Event: ResolutionChanged
SplashScene:MediaPlayerEvents(MediaPlayer, EventType, ErrorCode)
UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()

2023-07-14 08:17:33.888683+0200 AR Survey Tool[1072:753862] Unbalanced calls to begin/end appearance transitions for <UnityDefaultViewController: 0x101306f60>.
Log Event: Started
SplashScene:MediaPlayerEvents(MediaPlayer, EventType, ErrorCode)
UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()

Log Event: FirstFrameReady
SplashScene:MediaPlayerEvents(MediaPlayer, EventType, ErrorCode)
UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()

Log Event: ReadyToPlay
SplashScene:MediaPlayerEvents(MediaPlayer, EventType, ErrorCode)
UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()

-----------------------------------
Code used for customer splash video

[SerializeField] private MediaPlayer mediaPlayer;
    private void OnEnable()
    {
        mediaPlayer.Events.AddListener(MediaPlayerEvents);
    }
    private void OnDisable()
    {
        mediaPlayer.Events.RemoveListener(MediaPlayerEvents);
    }
    private void Start()
    {
        mediaPlayer.OpenMedia(false);
    }
    private void MediaPlayerEvents(MediaPlayer mp, MediaPlayerEvent.EventType eventType, ErrorCode code)
    {
        Debug.Log(eventType);
        switch (eventType)
        {
            case MediaPlayerEvent.EventType.ReadyToPlay:
                mediaPlayer.Control.Play();
                break;
            case MediaPlayerEvent.EventType.FinishedPlaying:
                SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex + 1);        
                break;
        }
    }

**Comment by MorrisRH** [comment]
Reproduced using Unity 2022.3.2f1, AVPro Video 2.8.2, iPhone 13 Pro, iOS 16.5.1
Not reproduced using iPhone X, iOS 14.8.1.

Will get a fix into the next release for this.

The Unity error is nothing to do with AVPro Video.

**Comment by MorrisRH** [comment]
This issue has been fixed and will make it into the next release, version 2.8.3

**Comment by Chris-RH** [comment]
AVPro version 2.8.3 has been released.  Please let us know if this has not fixed your issue.
