### ISSUE TITLE
The latest plugin cannot play 5.1 or 7.1 AAC audio track on Android, 2.3.2 has no issues

### ISSUE THREAD

**Issue by richardzhang0301** [RenderHeads/UnityPlugin-AVProVideo#1594]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.2
 - Operating system version: Windows 11
 - Device model: Pixel 7 and Samsung S20FE
 - Video specs (resolution, frame-rate, codec, file size): 1080p, 30fps, h264+aac(7.1), 280MB

**To Reproduce**
1. Based on Demo_DisplayComponents AVPro demo scene, select MediaPlayer game object.
2. Select a video content with 5.1 or 7.1 aac audio track and h264 video track. (either local or stream from URL)
3. Build for Android, and run on any Android device (up-to-date)

**Logs**
If applicable, add error logs to help explain your problem.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
https://dcezofapvlc4i.cloudfront.net/ReadyPlayerOne_1080p_512.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
AVPro version 2.8.3 has been released.  Please let us know if this has not fixed your issue.
