### ISSUE TITLE
Youtube 360 video display wrong

### ISSUE THREAD

**Issue by RoxDevvv** [RenderHeads/UnityPlugin-AVProVideo#1595]
i downloaded youtube video 360 which looks like that 
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/51464152/d535042b-af08-4ed7-bc01-c77f5ab309b0)

the video won't display correctly I tried all packing types it always display wrong

**Comment by Chris-RH** [comment]
We don't officially support streaming from Youtube
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#youtube--facebook-live--twitch-support

YouTube videos are not encoded in standard equi-rectanular layout and instead use some sort of custom cubemap packing which may be why they can't be simply mapped to a sphere.
See also: https://github.com/ytdl-org/youtube-dl/issues/15267

We already have an open enhancement ticket to support Equi Angular Cubemaps, which we believe is what they use (#135 ).  However it is not high up on our priority.

There is a shader mentioned at the bottom of that thread.  It is old, but you may be able to get it to work for you.
https://github.com/hakanai/EACSkyboxShader
