### ISSUE TITLE
Stalled video instead of looping when using cache on iOS

### ISSUE THREAD

**Issue by David-Luis** [RenderHeads/UnityPlugin-AVProVideo#1596]
**Describe the issue**
When using cache feature on iOS, sometimes the videos don't loop and they get freeze (stalled event is fired)
Note: Android is not having this issue or we can't reproduce it

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.2 - Ultra
 - Operating system version: 16.5.1
 - Device model: iPhone 11 pro
 - Video specs (resolution, frame-rate, codec, file size): 1920 x 1080, 30fps, HLS H.264, 20mb

**To Reproduce**
1. Set the MediaPlayer with loop enabled
2. Use the caching feature with the remote path
3. Wait for the media status to be "Cached" and open the media using the remote path
4. Wait for the loop to end

**Comment by MorrisRH** [comment]
Not the most reproducible of issues but I have seen it happen. If you have any tips/ideas on how to make it consistently occur that would be very useful.

**Comment by David-Luis** [comment]
Yep I can tell, but it happens to us consistently (random though)

**Comment by David-Luis** [comment]
Hello! After changing our pipeline to create the videos we can't reproduce this issue anymore, so you can close this if you want to. Cheers!
