### ISSUE TITLE
Some Videos Cause Lag and do not play Audio in Quest 2

### ISSUE THREAD

**Issue by turtle95** [RenderHeads/UnityPlugin-AVProVideo#1599]
Some of the videos we're trying to play do not play audio and cause the app to lag when playing on the Quest 2. 
They all work fine within the Unity editor however.

I believed this was due to the bit rate but the bit rate of one lagging video is only 1425kbps.

Setup:
 - Unity version: 2020.3.33f1
 - AVPro Video version 2.0, ultra edition
 - Operating system version: Android
 - Device model: Oculus Quest 2
 - Video specs (960 x 540, 29.97fps, H.264 mp4, 1.37MB, Length = 8 seconds): 

**To Reproduce**
1. Create a build for the Oculus Quest 2
2. Reference a video with similar specs and play it using the Media Player and Display uGUI

**Comment by Chris-RH** [comment]
1. Please can you make sure that you are using the latest version of AVPro Video
2. Are they within the guidelines set by Meta? https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/
3. Could you supply us with the video/url you are using please? here or unitysupport@renderheads.com

**Comment by turtle95** [comment]
Thanks for the response!

1. We'll try the newest version asap and let you know the results. 
2. Our video appears to fall within the guidelines set by Meta
3. I just sent the video over to your support team

**Comment by turtle95** [comment]
I did some error logging and it turns out our video had an incompatible color format with the Quest 2.
For those that are stuck on this, you have to use a tool such as MediaInfo to read the color format of a video file, the file properties doesn't display that and neither does VLC.

Sorry about that... should have looked deeper into the video data first.
That said, do you know if there's a way to identify incorrectly formatted videos so that we can avoid playing them?
Either way, thanks for the help! 
I'll close this issue out.
