### ISSUE TITLE
Progressive transmission problem in iOS

### ISSUE THREAD

**Issue by RaidelRoss** [RenderHeads/UnityPlugin-AVProVideo#16]
**Describe the bug**
Sometimes with the same video
-Show the first frame of the video but it is freeze
-The video is shown but it is not heard
-The video is heard but not shown
-Sometimes AVPro works correctly

**Details**
-We have the videos uploaded to our server, the videos are provided as resources (we do not use Streaming in the server)
-The video is played during the augmented reality of Vuforia
-During playback, we record a video of what is shown on the screen
-For the video recording we use (NatCorder)
-For the recording of the audio we use the native microphone of Unity
-We do not compile with (Metal) in PlayerSettings
-We are using the following function of AVPro (mediaPlayer.Control.SetPlayWithoutBuffering(true);)
-We use FFmpeg to process the video before uploading to the server
    ->For video processing with FFmpeg we use the following command line
      (-i input.mp4 -preset ultrafast -vf scale='min(320,iw)':'min(400,ih)' output.mp4)
-**In Android, so far we don't have these problems**

Note: We have activated Multithreaded Rendering

 - Vuforia:7.2.23 
 - Unity version: 2018.2.8f1
 - AVPro Video version: 1.9.10
 - Operating system version: IOS (9 and above)
 - Device model: 
 - Video sample (https://mega.nz/#!t9V3EIZK!u-DTZmqEogca7vWuNCqY44GF9k8c9vpgrYh7moJGutk)
 - Video specs (~320x400 , fps: 30, codec : H264 - MPEG-4 AVC (part 10) (avc1) , (5 ~ 10) mb): 
 - Audio specs (64 kb/s , Códec: MPEG Audio layer 1/2 (mp4a), 48000 Hz, Mono)

the logs do not show relevant information

**Comment by AndrewRH** [comment]
Thanks for the detailed report.  I have a few questions:

1) If you use our sample videos instead, does it work better?
2) I'm thinking that the encoding might be the problem.  Have you tried without "-preset ultrafast"?
3) How frequently do you have these problems?  Does it happen usually after a certain number of video loads?
4) How many videos do you have loaded at once through multiple instances of the MediaPlayer component?

Thanks,

**Comment by RaidelRoss** [comment]
hi
we update to (unity2018.3.5)
we update to (AVPro Video version: 1.9.12)
we removed the call to the method (mediaPlayer.Control.SetPlayWithoutBuffering (true);)

It seems that the problem was solved

regards
