### ISSUE TITLE
Exo Player stuck on the lowest resolution (HLS stream)

### ISSUE THREAD

**Issue by sigr3s** [RenderHeads/UnityPlugin-AVProVideo#160]
**Describe the bug**

*Behavior*: Exo Player only reproduces the lowest resolution of the HLS stream.
*Expected*: Switch to a higher resolution when possible. (Behavior of Media Player)

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.9f1
 - AVPro Video version: 1.10.0
 - Operating system version: Android 7, 8 
 - Device model: Oculus GO, Samsung S6
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1.  Add MediaPlayer to an empty scene.
2.  Add AvPro Video uGUI
3. Configure Media Player with ExoPlayer. Enable auto open and configure HLS url.
4. Build and play in android.

URL: https://d1byyq87nnr5lm.cloudfront.net/shivver/vroadcaster/gallery/pasedemicros/hls/tv_gala_9_1_flat-final.m3u8

Thank you.

**Comment by RenderHeadsSte** [comment]
A fix for this issue will be in release 1.10.1
