### ISSUE TITLE
Android build can't play video.

### ISSUE THREAD

**Issue by YangSama** [RenderHeads/UnityPlugin-AVProVideo#1600]
### Android build can't play video when add MediaPlayer Component via script.

**Describe the issue**
 In our project, we add MediaPlayer Component via script. After upgrade to 2.8.3, we can't play video on android. We encountered an error as shown below.
![avpro报错](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/17917699/1d63602d-cffb-4889-88f6-22678c180c7f)
It's point to the code in AndroidMediaPlayer as showen below.
![avpro](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/17917699/af6d963a-a3db-4bad-a64e-2f611c7e1877)

**Your Setup (please complete the following information):**
 - Unity version: Unity 2021.3.21f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.3-Core Edition
 - Operating system version: macOS Ventura 13.4.1
 - Device model: Samsung Galaxy S21, HUAWAI P40 Pro.
 - Video specs (resolution, frame-rate, codec, file size): 720*1280, 30fps, H.264

**To Reproduce**
1. Import AVPro Video - Core Edition 2.8.3
2. Switch platform to android
3. Add a test scene
4. Create a script as below

```
using RenderHeads.Media.AVProVideo;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    [SerializeField] private MediaReference _video;

    private MediaPlayer _mediaPlayer;

    void Start()
    {
        _mediaPlayer = gameObject.AddComponent<MediaPlayer>();
        _mediaPlayer.AutoOpen = false;
        _mediaPlayer.AutoStart = false;

        DisplayIMGUI displayIMGUI = gameObject.AddComponent<DisplayIMGUI>();
        displayIMGUI.Player = _mediaPlayer;

        _mediaPlayer.OpenMedia(_video);
    }
}
```
5. Add a reference to the `_video` field from inspector
6. Build and run

**Comment by Chris-RH** [comment]
Have you checked that the video plays using a new project and just the AVPro Video demo media player scene (entering the video details in the component)?

**Comment by Ste-RH** [comment]
Thanks for pointing this out. I think it’s happening only when a MediaPlayer is created in script. A miss on our part. Apologies. We will get this fixed and a new build out asap.  For now, you should just be able got add a check for ‘key’ not being null around the whole thing. Thanks for reporting it.

**Comment by Ste-RH** [comment]
AVPro Video 2.8.4 has just been released.  This should contain a fix for this issue.  Please let us know.

**Comment by YangSama** [comment]
> AVPro Video v2.8.4 has just been released. This should contain a fix for this issue. Please let us know.

We will try to upgrade to the new version, thanks for your hard work.
