### ISSUE TITLE
Symmetry Weirdness After Extending AVProVideo Unlit Transparent Shader with Alpha Fader

### ISSUE THREAD

**Issue by 4dbob** [RenderHeads/UnityPlugin-AVProVideo#1606]
Hello - I extended your 'AVProVideo/Unlit/Transparent' shader to include an 'Alpha Fader' slider visible in the Inspector plus script control via an '_Alpha' parameter, by simply adding

		_Alpha ("Alpha Fader", Range(0,1)) = 1

to the Properties section;

		uniform float _Alpha;

to the Pass{} section of the SubShader after the struct declarations; and 

		col.a *= _Alpha;
		
to the 'fixed4 frag (v2f i) : SV_Target{}' section before the fog application.

I am using your ApplyToMaterial.cs script assigned to an 'HDRP Unlit' base material that uses this extended shader.   It works nicely, and my C# coroutine is fading the video in and out over another GameObject in world space on demand.

However, as it fades out or in it blends with a symmetrical version of itself~!  This symmetry is only in the Y axis.  At an _Alpha = .5 the video is equal parts x,y and x,-y blended together.

I am hoping you have an insight you can share as to why this is happening.  And if so, what I can change to fix this behaviour.

I do see that once I hit play whatever values I have in the material's 'Base (RGB) Trans (A)' UV Tiling and Offset boxes visible in the Inspector are replaced, and the Y axis tiling now shows '-1' (a clue?);  but changing it back to 1 while running has no visible effect; neither does changing the Offset.  

If I pause Unity playback halfway through the fade and then change the Offset and Scale values broken out in the Inspector in your ApplyToMaterial.cs script, these DO affect the image mapping, but the symmetry effect mid-fade remains.

My Setup:
 - Unity 2022.3.4 LTS
 - HDRP 14.0.8
 - AVPro Video version 2.8.3 (plugin v2.8.3f1-core) 
 - Windows 10 Pro
 - NVIDIA GeForce RTx 3070 Ti

Thank you!

**Comment by Chris-RH** [comment]
Would you be able to provide a simple reproducible project and send it to unitysupport@renderheads.com please.

**Comment by 4dbob** [comment]
Hi Chris –

Thanks for the quick response.  I am preparing the example project and will send to the email address you provided.

             bOB

[Robert Mueller, Art Director/Exec VP                                                                   Lightspeed Design, Inc.  1611 116th Ave NE  Bellevue, WA USA 98004  425-637-2818                                                                                                                                        This email message is for the sole use of the intended recipient(s) and may contain confidential information.  Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.]

**Comment by Chris-RH** [comment]
Hi @4dbob 

Thank you for sending the project.  I have forwarded it to our Windows dev.  I've cropped a small screenshot of what I believe is the issue you are referring to.
![1606](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/79fb9f14-fe78-4c75-b37c-ce0ecf741239)

**Comment by 4dbob** [comment]
Thank you Chris - 

Yes, that's the problem in a nutshell.  Thank you for looking into this,

**Comment by RichRH** [comment]
Hi @4dbob,

I believe this is your issue:

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/20209491/2d3fb2ae-e6a1-4b66-9b9d-44078168e85e)

The shader has culling set to 'Off' so both sides of the cube will be rendered (and one naturally flipped) - I'd suggest either changing to a quad or changing the culling mode.

Cheers,

**Comment by 4dbob** [comment]
That makes way too much sense :-)

Thank you so much.  I'll go the quad route.  You are much appreciated~!
