### ISSUE TITLE
RTSP streaming problem in AvProVideoWindows Unity plugin

### ISSUE THREAD

**Issue by ecokim** [RenderHeads/UnityPlugin-AVProVideo#161]
**Describe the bug**

To use rtsp playing, I’ve installed LAV Filter; version 0.74.1.
https://github.com/Nevcairiel/LAVFilters/releases  

Here’s a little bit of explanation of what goes on in our program. After joining a lobby in the program, joiner’s video will be streamed via ffmeg and joiner will receive a stream via rtsp. However, the video randomly repeats itself during receiving a stream. 

Please refer to this video for the detail.
https://drive.google.com/open?id=1_5XkbOZ1IaLBGzExiG4T57W6L4l41GGg

In video, the left video is for receiving stream via rtsp. 
(I didn’t have an issue with this when testing with other program such as vlc or android application to receive a stream via rtsp) 

I’d really appreciate it if you can help me resolve this issue.

**Your Setup (please complete the following information):**
 - Unity version: 5.3.5
 - AVPro Video version: 1.10.0
 - Operating system version: Windows 7
 - Device model: windows standalone
 - Video specs (resolution, frame-rate, codec, file size): rtsp streaming

**To Reproduce**
1. Start sending stream using ffmpeg.
   We use command for ffmpeg to start sending the stream. 
   ffmpeg -f gdigrab -offset_x 0 -offset_y -0 -framerate 30 -video_size 260x462 -i desktop -an -c:v libx264 -r 20 -g 20 -profile:v baseline -level 20 -pix_fmt yuv420p -b:v 100k -s 260x462 -f rtsp -rtsp_transport tcp -muxdelay 0.1 rtsp://myserver/streamName
2. Start to receive rtsp stream MediaPlayer.OpenVideoFromFile()
3. After about 10 seconds or longer, the video starts to randomly repeats.

**Logs**
When I do a test run with event listener as followed, 
MediaPlayer player;
player.Events.AddListener(onPlayerEvent);

I get an error log like this when the problem occurs. 
[17:43:25.770] onPlayerEvent event=Stalled, err=None
[17:43:25.920] onPlayerEvent event=Unstalled, err=None
[17:43:26.880] onPlayerEvent event=Stalled, err=None
[17:43:26.914] onPlayerEvent event=Unstalled, err=None
[17:43:27.875] onPlayerEvent event=Stalled, err=None
[17:43:27.924] onPlayerEvent event=Unstalled, err=None
[17:43:28.885] onPlayerEvent event=Stalled, err=None
[17:43:28.918] onPlayerEvent event=Unstalled, err=None
[17:43:29.780] onPlayerEvent event=Stalled, err=None
[17:43:29.829] onPlayerEvent event=Unstalled, err=None

**Screenshots**

**Videos**
https://drive.google.com/open?id=1_5XkbOZ1IaLBGzExiG4T57W6L4l41GGg

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

Thanks for getting in touch and for explaining the issue.

I'm afraid RTSP isn't a protocol that we actively support.  If it works via 3rd party plugins - then great, but we can't guarantee the quality of that.

It sounds like a bug either in FFMPEG or in the LAV Filters implementation....

Our software basically just displays the decoded video, so you might want to ask in either the FFMPEG or LAV Filters GitHub Issues pages

Thanks,

**Comment by dpradell360** [comment]
It's supported now.
