### ISSUE TITLE
Can't load HAP files generated from Unity render

### ISSUE THREAD

**Issue by nolwenn-bigoin** [RenderHeads/UnityPlugin-AVProVideo#1612]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I create an hap video in runtime by launching an ffmpeg process from unity, which encodes my camera render (using this https://github.com/keijiro/FFmpegOut). 
Then I want to open this video with AVPro Video / Media Foundation / Use Hap/NotchLC, but I get this error : Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
I can open the file without error if I check Use Custom MOV Parser, but then I have a small framerate drop at file loading, which I do not want.
I don't have any issue when loading big hap files without checking Use Custom MOV Parser if those videos are created with ffmpeg from another video, and not from Unity render.
Can you tell me what is the issue with my video (link below) ?

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.4 trial
 - Operating system version: Win 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 1920 x 1080, 25fps, hap

**To Reproduce**
1. Open your demo project Demo_MediaPlayer
2. Set the Media Source path to test_countdown.mov and check Use Hap/NotchLC
3. Play the secne.

**Videos**

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/36228310/0697ed13-aba3-4bea-9fc6-3e402566450e

**Comment by Chris-RH** [comment]
Sorry, it doens't seem to be available? Could you email to unitysupport@renderheads.com please :)

**Comment by nolwenn-bigoin** [comment]
Hi,
I've just emailed you the video. Thanks.

**Comment by Chris-RH** [comment]
Have you tried changing to DirectShow API?

**Comment by nolwenn-bigoin** [comment]
Yes, it works, this is what I was previously doing with AVProVideo 1. I would like to upgrade to AVProVideo 2 and use MediaFoundation to have an async loading.

**Comment by Ste-RH** [comment]
Using custom mov parser is the correct approach if you are using MediaFoundation.

The moov atom in your test video is positioned at the end of the file.  if you add '-movflags +faststart' to your ffmpeg encoding command then this should help.  Essentially the parser has to walk all atoms in the video file until it finds the moov atom.  This can slow things down.

Do let us know.

**Comment by Chris-RH** [comment]
Any improvement?

**Comment by Chris-RH** [comment]
closed due to lack of reply

**Comment by nolwenn-bigoin** [comment]
Sorry for the late reply.
I have an issue with the "use custom MOV Parser" option. I have an HAP video, encoded with ffmpeg from another video.
If I open this video in your demo scene Demo_MediaPlayer without checking Use custom MOV parser, everything is fine, and I can seek in the video with the timeline very fast.
However, if I check the option : 
- the aspect ratio of the video is not correct anymore (which is not a big issue for me because it doesn't happen in my own scene)
- the main issue is that when I move the slider to the end of the timeline, it doesn't stop on the last frame, and not always on the same frame.
I'm sending you this video by email.

**Comment by Chris-RH** [comment]
Do you find that you get a better result using the DirectShow API?

**Comment by nolwenn-bigoin** [comment]
If I use DirectShow in your demo scene, the result is the same with the last frame not being reached when I quickly move the timeline slider. However, it works properly in my own scene (I use the SeekToFrame method). The main issue of DirectShow is the blocking loading.
