### ISSUE TITLE
360 Videos always render on top of everything when using URP

### ISSUE THREAD

**Issue by LEMPeter** [RenderHeads/UnityPlugin-AVProVideo#1613]
**Describe the issue**
On Android a 360 video, that uses the OctahedronSphere8192 mesh, with `InsideSphere Unilit (Stereo+color) - Android OES` shader, is rendering on top of everything. Everything being world space UI, and even 3d meshes (a simple cube).

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.29 (also observed on 2021.3.27, 2022.3.7)
 - URP: 12.1.12
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra Edition 2.8.4
 - Operating system version: Android 13
 - Device model: Pixel 6
 - Video specs (resolution, frame-rate, codec, file size): N/A, happens with or without a video.

**To Reproduce**
1. Create a scene with a sphere from the OctahedronSphere8192 
2. Use the InsideSphere Unilit (Stereo+color) - Android OES shader on the sphere material
3. Add some world space UI inside the sphere
4. Add a cube inside the sphere
5. Make sure the camera is inside the sphere and can see the UI + cube
6. Press play, observe everything is fine in editor
7. Build and run on an Android device
8. Observe world space items can't be seen

**Screenshots**
From Editor
![Screenshot 2023-08-12 175356](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/142110166/beaeeef7-88bc-4da3-a82e-e0661ede6d1b)
![Screenshot 2023-08-12 175403](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/142110166/177ec390-e598-4aa6-90af-8d5ced4ef767)

From Device
![Screenshot_20230812-175417](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/142110166/78894e5d-32f0-4c44-a328-153073f41f5e)
![Screenshot_20230812-175422](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/142110166/b6aae9f1-4c0e-42c4-8178-0b2eb6f516a5)

**Comment by LEMPeter** [comment]
I have the same setup on an older project, using Unity 2021.3.16 and AVPro 2.6.6, where this issue doesn't occur.

**Comment by LEMPeter** [comment]
Copying AVPro 2.6.6 from the 2021.3.16 project into the test project on 2021.3.29 didn't fix it.

**Comment by LEMPeter** [comment]
Hi,

Is there any possibility of an update on this?

It's a major issue for our app, we won't be able to release on Android with
AVPro and any development required for a replacement will take me a long
time, with our planned release a little over a month away I'd need to have
a plan in place asap.

Thanks,
Peter

**Comment by Ste-RH** [comment]
@LEMPeter Do you get the same result when you are using the none OES shader?  Are you using multipass or multiview?

**Comment by LEMPeter** [comment]
@Ste-RH If I disable OES the UI displays on top correctly. The videos look a bit brighter than they should though.

I don't know what multipass and multiview are - can you elaborate and I'll check.

**Comment by LEMPeter** [comment]
I haven't tried Standard RP, I did supply a project via email demonstrating the problem - hopefully it reproduced the issue for you. Can you use that to test Standard RP?

> I have the same UI setup on an older project, using Unity 2021.3.16, built-in render pipeline and AVPro 2.6.6, where this issue doesn't occur.

I haven't updated that project to the latest AVPro, too worried of it breaking

**Comment by LEMPeter** [comment]
@Ste-RH Thanks for the update and the work around. 

Unless we run into any problems, I'm going to keep everything as non-OES for now.
