### ISSUE TITLE
Android build fails in Unity 2022.3, workaround fails for upload to Meta 

### ISSUE THREAD

**Issue by realitygarage** [RenderHeads/UnityPlugin-AVProVideo#1616]
The workaround to change the API version 33 does not work when building for meta quest as the upload to meta fails, requiring that the target API be set to 32.

please advise... 

see original issue and workaround below
-------
   
           Change
compileSdkVersion 33

_Originally posted by @Chris-RH in https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1541#issuecomment-1547568723_

**Comment by Chris-RH** [comment]
In your gradles (main **and** launcher Templates), try this:

minSdkVersion 22
targetSDKversion 32
compileSDKversion 33

**Comment by mathisevaveo** [comment]
Hello @Chris-RH,

I wanted to let you know that I've successfully resolved the bug with your helpful comment. However, the solution I implemented goes beyond your suggestion:

- Before updating AVPRO, I removed ALL .dll files from the Assets > Plugins directory, including those from the previous version of AVPro, such as Audio360 and AVPro.
- Then, I installed the new version of AVPro.
- I made necessary script changes to accommodate the update.
- Upon encountering the build issue, I followed your advice and adjusted the SDK versions in the settings.

As a result, I'm pleased to inform you that the project is now functioning flawlessly across various Unity builds.

Thank you so much for your assistance!

**Comment by Chris-RH** [comment]
I'm glad that it works now :)

**Comment by richardmuthwill** [comment]
This helped me too, thank you so much, I've been spending hours fixing this now.

Unity 2022.3.4f1
Meta XR All-In-One SDK 63.0.0
AVPro Video - Core Android Edition 2.9.3

I also had to force Unity to update the Android SDK to 33 and then used @Chris-RH solution #

> In your gradles (main **and** launcher Templates), try this:
> 
> minSdkVersion 22 targetSDKversion 32 compileSDKversion 33
