### ISSUE TITLE
360 images get darker on Android when using Apply to Mesh  by script

### ISSUE THREAD

**Issue by BaptisteDev09** [RenderHeads/UnityPlugin-AVProVideo#1617]
**Describe the issue**
I have been using AVpro 1.11.7 version for a long time and I've decided to change to the Ultra Edition (v2.8.3).
I'm developping a 360 multimedia player for both VR and Computer. 
After the Ultra Edition integration in my project I've noticed that, on Android, my 360 images are way darker than they really are. Though it works fine on Unity and on Windows.
I've tried many things (change shader, material, save a screenshot of the actual image right before applying it to the mesh and so on) but nothing has worked so far.
The way I do this is simple :
I get the Texture2D and assign it to the ApplyToMesh.DefaultTexture and apply.
I should mention that everything works as intended with 360 videos though they are not loaded the same way but they do use the same shader and material.
Thanks in advance

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.34f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 2.8.3
 - Operating system version: Android
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 4k jpg, 797Ko

**To Reproduce**
1. Use the Apply to Mesh script and set the ApplyToMesh.defaultTexture in a script at runtime

**Comment by BaptisteDev09** [comment]
Hello,
I've tried with a new LTS version of Unity (v2021.3.29f1) and have not encounter this issue so far. Maybe changing version has fixed the issue.

**Comment by Chris-RH** [comment]
Hi @BaptisteDev09 

That's interesting to know, and frustrating too in a way!  I'm glad to hear that it seems to be fixed for you.

**Comment by BaptisteDev09** [comment]
Hello, 
I have re-opened the issue because after more testing, updating Unity version has not solved the issue like I have hoped so.
It seems as though the issue is caused by the APPLY_GAMMA variable. On the shader I am using (which is the "AVProVideo/VR/InsideSphere Unlit Transparent (stereo+color+fog+alpha)") it is set to false. But for some reasons it is applied at some point. And it's actually not only on Android.
I've noticed that because when it happens, all I have to do is enable and disable theshader's gamma toggle in the inspector for the image to be normal again.
I'm checking the shader itself as well as the .cginc right now but nothing seems out of place so far.

**Comment by Chris-RH** [comment]
Hmm, thank you, that's very interesting.
I wonder if its restricted to that shader or all of the shaders

**Comment by Ste-RH** [comment]
What colour space do you have set in our project?

What device(s) have you tested on?  In our experience, developing AVPro MovieCapture, some devices (usually the cheaper end of the market) encode darker.  So it is not beyond the realm of possibility that the decode is also not doing a correct job on some hardware.

Also, you say 360 videos are fine even using the same shader?  That cannot be!?

**Comment by BaptisteDev09** [comment]
Hello @Ste-RH ,
Here's a screenshot of the color space : 

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/77831201/e8047223-36c9-4435-9696-90be89bd0d01)

Well I've encountered the undesire effect on Android (Quest 2) and on MacOS (Macbook Pro - M1 pro). Could not reproduced it on Windows 10 yet.
The only lead I have is that it's shader related and it seems to occur when I disable and re-enable the Sphere gameobject. Though everything I've tried leads me to believe that the APPLY_GAMMA variable is the cause as I've commented everything it does in the .cginc and I could not reproduced the effect afterward.
Regarding the Image/Video, as hard to believe as it is, I could not reproduced it on any 360 videos so far.

**Comment by BaptisteDev09** [comment]
Hello @Ste-RH , @Chris-RH ,

I've finally figured out what was the issue. 

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/77831201/3bc14b75-a451-4b09-8228-a5cc6a895f02)

As you can see in the screen above , when my color space is set to Linear, whenever the ApplyToMesh.cs is enable, it will lead to this part of the code that applies gamma correction without checking the APPLY_GAMMA variable.
I don't know if it was intended but for some plateforms and my particular case it leads to strange behavior.

Thank you for your time,
Cheers to both of you.
