### ISSUE TITLE
Updating Android Exoplayer 

### ISSUE THREAD

**Issue by machenmusik** [RenderHeads/UnityPlugin-AVProVideo#1618]
How does one upgrade the version of ExoPlayer for AVPro?
The latest version (2.19.1) contains needed fixes.

If you can do a minor release with that update, obviously that solves the issue.
If that may take a while, and you can provide instructions to upgrade ExoPlayer manually in the interim, that would be much appreciated.

**Comment by Chris-RH** [comment]
We will upgrade the Exoplayer version.  Hopefully when we release the next version.  I can't give a date as we are in the midst of staff annual leave.

**Comment by Ste-RH** [comment]
We have updated AVPro Video to ExoPlayer v2.19.1

This will be available in the next release.  We hope to get this out this week or next.

**Comment by machenmusik** [comment]
Great thanks!  Happy to try some tests with it prior to initial release if helpful.

**Comment by Chris-RH** [comment]
This has been added to AVPro Video version 2.9.0
