### ISSUE TITLE
unable to play mvc video(.ssif)

### ISSUE THREAD

**Issue by tufeixp** [RenderHeads/UnityPlugin-AVProVideo#162]
Even with k-lite codec installed and lav filter working below.

**Comment by AndrewRH** [comment]
This isn't something we plan to support I'm afraid.   I'm not even sure that is a playable file type - apparently:

The SSIF file type is primarily associated with Blu-ray Disk. StereoScopic Information File(s) (SSIF) are files associated with 3D Blu-Ray viewing. The SSIF file is binary file, that determines the encryption, DRM and the type of 3D contained on the disk (separate streams for each eye, type of Delta, etc.)

I'm closing this issue.  Please reopen the issue or another issue if you have any other issues.

Thanks,

**Comment by tufeixp** [comment]
I used to play the 3D Blu-Ray ssif files with stereoscopic player(http://www.3dtv.at/Index_en.aspx), hope for AVPro can support that too in the future.
