### ISSUE TITLE
Can't play videos on PC x86

### ISSUE THREAD

**Issue by ilinchunjie** [RenderHeads/UnityPlugin-AVProVideo#1623]
**Describe the issue**
After updating the plugin to version 2.8.4, videos cannot be played on Windows x86. When the version is rolled back to 2.8.1, this issue no longer occurs. The error message displayed is: "[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high, or insufficient system resources.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.37f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.4 ultra
 - Operating system version: windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by Chris-RH** [comment]
We have recently done a fix for 32-bit Windows which should be in the next release.  Hopefully that will fix the issue.

**Comment by Chris-RH** [comment]
Can you see if the latest version of AVPro Video fixes the issue please?

**Comment by ilinchunjie** [comment]
After updating to version 2.8.5, the issue has been resolved. thanks
