### ISSUE TITLE
Duplicate class on jetified-guava-31.1-android.jar and jetified-listenablefuture-1.0.jar

### ISSUE THREAD

**Issue by HassanSohail000** [RenderHeads/UnityPlugin-AVProVideo#1624]
I am getting duplicate classes on Android Unity build. While the resolver run successfully. Error detailed are as follows.

**ERROR ON BUILD**
`[Duplicate class on jetified-guava-31.1-android.jar and jetified-listenablefuture-1.0.jar](https://stackoverflow.com/questions/76962451/duplicate-class-on-jetified-guava-31-1-android-jar-and-jetified-listenablefuture)`

If I delete the libraries, then the build will succeed, but the application is not working perfectly. If I delete AV Pro duplicate file than YouTube prerecorded is not working smoothly and if delete the other than Firebase deep linking will not work. 
A clear and concise description of what the issue is.

**Environment**
 - Unity version: 2021.3.4 
 - AVPro Video Ultra Edition 2.8.1  
 - Operating system version: Android 
 - Device model: All Android 

**To Reproduce**
1. Import AV Pro and Firebase Deeplink, FirebaseCrashlytics , FirebaseAnalytics packages.
2. Make Android build

**Error Details**
`UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <c3a2c42a45424b88b29dfadf7f497cbb>:0) UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <c3a2c42a45424b88b29dfadf7f497cbb>:0) UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <c3a2c42a45424b88b29dfadf7f497cbb>:0) UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action1[T] progress, System.String error) (at :0) UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action1[T] progress) (at <c3a2c42a45424b88b29dfadf7f497cbb>:0) Rethrow as GradleInvokationException: Gradle build failed UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action1[T] progress) (at :0) UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at :0) UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at :0) Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown. UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at :0) UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at :0) UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, AndroidPlayerBuildProgram.Data.AndroidPlayerBuildProgramOutput buildProgramOutput) (at :0) UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at :0) UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <36f62d8e760b48f7af5d32916f997ce1>:0) UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)`

**Setting Images**
[Publishing Settings](https://i.stack.imgur.com/p8BjV.jpg) 
[Resolver Android Setting](https://i.stack.imgur.com/n3dYo.jpg)

**Comment by Chris-RH** [comment]
This is a known issue
There is a solution here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1525
