### ISSUE TITLE
iPhone screen turns red while playing video that requires rotation when using MediaPlayer.ExtractFrame()

### ISSUE THREAD

**Issue by thesanketkale** [RenderHeads/UnityPlugin-AVProVideo#1626]
**Describe the issue**
I have a simple setup of playing a video on a 3D quad having a RenderTexture on an Unlit Material. Now, I am looking to recreate all the scaling modes of fitting the video inside a RenderTexture as available with Unity's VideoPlayer component. For this, I extract each frame of the video using MediaPlayer.ExtractFrame() and blit it onto a RenderTexture preserving its aspect ratio using a custom shader. 

Now, this works fine with both MP4 and MOV videos on Android devices. While on iPhone this works well for MP4 videos but turns the whole screen red as soon as I play an HEVC (.MOV) video which was shot using the same iPhone's camera.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.4f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Core 2.8.4
 - Operating system version: iOS 16.6
 - Device model: iPhone 14 Pro Max
 - Video specs (resolution, frame-rate, codec, file size): 
 Codec: HEVC (.MOV)
 Resolution: 1920 x 1080
 FPS: 59.94

**To Reproduce**
1. Create a 3D quad with RenderTexture on an Unlit Material.
2. Create a script to add a media player at runtime with HEVC video in streaming assets and set auto-play and auto-start to true
3. Start a coroutine to get MediaPlayer.ExtractFrame() and blit it onto the RenderTexture used above
4. Build and Deploy on iPhone
5. The whole screen will turn red as soon as the video starts playing

**Logs**
No error was thrown in the logs.

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/36810188/844095f2-b5be-4d68-b619-8b81c8139288)

**Videos**
https://drive.google.com/file/d/1tn9Vf5F3w9obYR_mtlo2h5xG7SUejTCz/view?usp=sharing

**Comment by MorrisRH** [comment]
ExtractFrame works perfectly for me here with the video you provided so I suspect there is something awry with your custom code. Both H.264 and HEVC mov files work fine.

A sample project would be very helpful in pinpointing what is going wrong. If you can please send one to unitysupport@renderheads.com

**Comment by thesanketkale** [comment]
I have submitted a sample Unity and Xcode project in the email with the issue. Kindly help me identify what could be going wrong. It somehow plays both MP4 and MOV videos on Android devices normally, while on iPhone it works for MP4 but not for MOV.

**Comment by MorrisRH** [comment]
A fix for this issue will make it into the next release

**Comment by thesanketkale** [comment]
Awesome, I look forward to it. I will test it once and then close this. Thanks.

**Comment by thesanketkale** [comment]
This is solved in the v2.8.5 version. Thank you!
