### ISSUE TITLE
Add scaling modes in ResolveToRenderTexture component to preserve aspect ratio while rendering on a RenderTexture

### ISSUE THREAD

**Issue by thesanketkale** [RenderHeads/UnityPlugin-AVProVideo#1627]
**Is your feature request related to a problem? Please describe.**
I wanted to play a video on RenderTexture on a 3D quad, but when I implemented it using the ResolveToRenderTexture, it stretched the video to fill in the aspect ratio of the RenderTexture. Rather, I would like to play the video preserving its aspect ratio inside the RenderTexture, something already available with Unity's VideoPlayer component.

**Describe the solution you'd like**
There could be an enum to choose from like the [VideoAspectMode](https://docs.unity3d.com/ScriptReference/Video.VideoAspectRatio.html) in the ResolveToRenderTexture component for us to choose the scaling mode before rendering to the RenderTexture.

**Describe alternatives you've considered**
I tried extracting each frame from the MediaPlayer using the MediaPlayer.ExtractFrame() and then create a custom shader to blit the frame to the RenderTexture preserving the aspect ratio of the video. I succeeded in making it work for MP4 videos, but there was some issue with extract frames of HEVC (MOV) videos that I have raised separately [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1626).

**Comment by MorrisRH** [comment]
Support for aspect scaling has been added to the ResolveToRenderTexture component and will be available in the next release.

**Comment by thesanketkale** [comment]
Awesome, I look forward to this feature. 

Just to make sure, what scaling modes have you introduced?

**Comment by MorrisRH** [comment]
I've matched Unity's modes so they're all available

**Comment by Ste-RH** [comment]
v2.8.5 has now been released @thesanketkale. Please do let us know if this addresses the issue.

**Comment by thesanketkale** [comment]
Hi @MorrisRH & @Ste-RH, the scaling modes are working great, but some videos captured from the iPhone camera in portrait mode are played rotated 90 degrees when using ResolveToRenderTexture. Is this expected?

Can the orientation of the video be managed in the player as it happens for the ApplyToMaterial component?

**Comment by MorrisRH** [comment]
Yes, this is something we just noticed ourselves - the video resolve handler is not currently handling the videos orientation data. We're looking into getting this fixed.

**Comment by thesanketkale** [comment]
> Yes, this is something we just noticed ourselves - the video resolve handler is not currently handling the videos orientation data. We're looking into getting this fixed.

Do you have any ETA for this fix?
And in the meantime, is there any quick workaround I can apply to fix it?

**Comment by thesanketkale** [comment]
Hi guys, do you have any update on ResolveToRenderTexture handling video orientation data?

Currently, I have a workaround for this by supplying a texture frame using ExtractFrame() for each video frame that correctly holds the orientation data. But, I am hoping this could be handled in the ResolveToRenderTexture API itself.

**Comment by MorrisRH** [comment]
Support for handling the orientation of a video has now been added to the ResolveToRenderTexture component and will make it into the next release.
