### ISSUE TITLE
Support to Azure Communication Services?

### ISSUE THREAD

**Issue by Haruwolf** [RenderHeads/UnityPlugin-AVProVideo#1628]
**Question**
Hello, I would know if AVPro has any type of support from ACS, the company that I work needs a solution to work like "Dynamics 365 Remote Assist", so we need video, voice and multi-stream support (Like, 3-4 persons on online room), we managed to achieve voice and room support with ACS, but we still need video streaming. Could I pick ACS Uri and work around AVPro? Another appropriate solution bar that is good too if it's not possible. We are using Hololens 2.

**Comment by MorrisRH** [comment]
Hey @Haruwolf 
I'm afraid we have no experience with ACS and so have no idea if it's possible for us to playback a video stream from the API.  Documentation on the streaming formats we support in the plugin is available [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html).
