### ISSUE TITLE
Videos will not show up in my Android Environment, but they are playing.

### ISSUE THREAD

**Issue by clintOngInnovations** [RenderHeads/UnityPlugin-AVProVideo#1629]
Problem description:

I am trying to extend the Decentraland implementation of AVPro Video to Android to support displaying the same videos that show up  on the Desktop app.  All of the videos textures become invisible on android, but I can hear the audio.  On PC, they all show up with the same settings.  I have tried several areas with videos in decentraland, and none play.

Device (which devices are you having the issue with - model, OS version number):

Meta Quest 2 and Pro. 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

https://live.avstack.net/asset/4c3e0e72-d0db-496a-a20a-d73e94d8f232

System Information:

AVPro Video: v2.8.4 (plugin v2.8.3f1-core)
Target Platform: Android
Unity: v2021.3.22f1 WindowsEditor
OS: Desktop - MPG H610 Trident 3 (MS-B941) (Micro-Star International Co., Ltd.) - Windows 11  (10.0.22621) 64bit - English
CPU: 12th Gen Intel(R) Core(TM) i9-12900 - 24 threads - 65388KB
GPU: NVIDIA GeForce RTX 3060 - NVIDIA - Direct3D 11.0 [level 11.1] - 12142KB - 16384

**Comment by Ste-RH** [comment]
What graphics API are you running with on Android? Vulkan is not currently supported by AVPro Video. Can you check you are using OpenGLES 3?

**Comment by clintOngInnovations** [comment]
I am using OpenGLES 3
***@***.***

**Comment by Ste-RH** [comment]
I have just tested your URL on a Quest 2 here in the Demo_MediaPlayer scene (that comes with the AVPro Video asset).  It plays back perfectly.  The only option I had to change was to force the file format to 'Apple HLS (.m3u8) in the MediaPlayer component.

**Comment by Chris-RH** [comment]
Have you had any luck with that @clintOngInnovations ?

**Comment by james-bad-vr** [comment]
H @Ste-RH. Beautiful work on AVPro. I'm also looking to play streaming videos (HLS) on the Quest 2/Pro and AVPro seems ideal, except our team has already ported our build to Vulkan for reasons important in our app. Do you have any idea about timing on Vulkan support? Is there any possibility that my team might help implement it for our own use, contributing the resulting integration to the product?

**Comment by clintOngInnovations** [comment]
I have found some oddities.  It appears that it is rendering, although not in the same way that it does for PCVR.  The original code that we use seems to make this kind of cubed image at the origin.  I was able to manually add a video as well and it shows up where I put it, but the colors are off (green) and I couldn’t get it to work correctly with that method.  I tried modifying our code to recreate what I am doing with the manually added video, but it doesn’t show up where it should either, even though the PCVR version shows it correctly as well, and it is using the same settings.   Let me know if you have thoughts.  I tried both singlepass and multipass for our OpenXR settings.

**Comment by clintOngInnovations** [comment]
I think I have come to a solution for our situation.  I created new RenderTextures and Materials that were applied to a ResolvetoRenderTexture component and then to my prefab  that had two RawImage and Canvas component children so I could ensure things faced the correct direction despite which side was facing out and placed that at the same location as my original mesh that refused to render on Android.
