### ISSUE TITLE
TopBottom Video Skybox Shader Error 

### ISSUE THREAD

**Issue by leeyongkyu1004** [RenderHeads/UnityPlugin-AVProVideo#1631]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version:  2022.3.5f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.8.4 ultra
 - Operating system version: window 11
 - Device model:  editor
 - Video specs (resolution, frame-rate, codec, file size): 
 -  mp4 format (all video Error)

**To Reproduce**

MediaPlayer Stereo Packing Setting TopBottom ( TopBottom Video ) and Play.
then Back Side is Flip (screenshot) i hope how to modify AVProVideo-Skybox-Sphere.shader 

Thanks you.
Best regards

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![test](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/118778769/fb8e7a4a-b063-430d-b341-c1bdb3b63828)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
That doesn't look right.

1. Can you reproduce the issue with a new project just using the AVPro Video demo scenes and no changes other than adding your video?
2. Are you able to send us a copy of the video you are using please?

**Comment by leeyongkyu1004** [comment]
Dear Chris-RH

Sorry for the late comment.
I sent you an E-mail.

Thanks you for kind :) 

have a nice day.

**Comment by Chris-RH** [comment]
Hi, 

The video supplied appears to be a Youtube 360 format video.  We don't officially support streaming from Youtube
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#youtube--facebook-live--twitch-support

YouTube videos are not encoded in standard equi-rectanular layout and instead use some sort of custom cubemap packing which may be why they can't be simply mapped to a sphere.
See:
https://github.com/ytdl-org/youtube-dl/issues/15267
https://paulbourke.net/panorama/youtubeformat/

We already have an open enhancement ticket to support Equi Angular Cubemaps, which we believe is what they use (https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/135 ). However it is not high up on our priority.

There is a shader mentioned at the bottom of that thread. It is old, but you may be able to get it to work for you.
https://github.com/hakanai/EACSkyboxShader

**Comment by leeyongkyu1004** [comment]
Hi, Chris-RH

Thanks for your help.

I'm afraid EACSkyboxShader is couldn't solve the problem.

Thank you for finding the way. 

Kind regards. 
leeyongkyu1004.
