### ISSUE TITLE
Loading progress

### ISSUE THREAD

**Issue by lionkingsiro** [RenderHeads/UnityPlugin-AVProVideo#1636]
hi, i am using the latest version trial. How can i show loading progress for the first play from url M3U8 like StalledStatus?
when i click play any stream. i got black screen to stream loaded to play.

**Comment by MorrisRH** [comment]
We don't get any progress feedback from the initial load so can't provide any specific events.

You could show a generic spinner and then when you receive the FirstFrameReady event you know you're able to begin playback. There is also the buffering progress available via ```MediaPlayer.Control.GetBufferedTimes()```
