### ISSUE TITLE
Video Frames Occasionally Render Incorrectly Fully Transparent

### ISSUE THREAD

**Issue by domcamus** [RenderHeads/UnityPlugin-AVProVideo#1637]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2022.2.0b11
 - AVPro Video version: 2.8.4 ultra
 - Operating system version: Windows 10
 - Device model: AMD Ryzen 5 3400G
 - Video specs (resolution, frame-rate, codec, file size): 960x540, 60fps, mp4, 13.1MB

**To Reproduce**
1. Use a VideoRender object in the normal way to play the video as part of a Unity project.
2. Mostly the video plays correctly and looks fine.
3. Every few seconds, a frame of the video contains only fully transparent pixels, causing flickering when the video contrasts with the graphical layer behind it (see screenshot below).

**Note**
This problem was not seen when using v2.7.3 with the same video and project.

**Logs**
N/A

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/18015340/8e556475-19d7-461a-b119-b53b561c8c6d)

**Videos**
N/A

**Comment by Ste-RH** [comment]
Is it possible to send over the video?

**Comment by domcamus** [comment]
Certainly. Will send to: unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Are you using DX11 or DX12?

**Comment by domcamus** [comment]
GPU: NVIDIA GeForce GTX 1660 Super

I think I'm using DX11, but not 100% sure. How can I check?

**Comment by Ste-RH** [comment]
It will say in the title bar of the Unity Editor.

Have you tried reproducing the issue on another PC with a different GPU?

**Comment by domcamus** [comment]
Thanks. Confirmed: it is DX11.

The bug was reported by a user, so definitely happens on another PC and very likely also a different GPU (because most of our users are on laptops and I use a desktop).

**Comment by RichRH** [comment]
Hi @domcamus,

Is this happening with a particular video API or all? (I've trying to reproduce it here and only seeing oddity with DirectShow currently - which I'm looking into)

Cheers,

**Comment by domcamus** [comment]
@RichRH - It's happening with Media Foundation. (Haven't tried anything else.)

**Comment by RichRH** [comment]
Merging this into https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1700 as the same issue.

**Comment by Chris-RH** [comment]
This should be fixed in AVPro Video version 3.0.0.  The trial version is available [here ](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases)for testing.  Please let us know if the issue is not fixed in this version.
