### ISSUE TITLE
Upload Build for Quest on AppLab whith Meta Quest Developper Hub refused cause android sdk 33

### ISSUE THREAD

**Issue by LaurentEvaveo** [RenderHeads/UnityPlugin-AVProVideo#1638]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
After build apk, trying to send on Meta Quest Console using the Meta Quest Developer Hub, it fail cause it not support android target sdk 33 (TARGET_SDK_VERSION_TOO_HIGH) ! 
It want 32, but the last avpro plugin use sdk 33.
We need the last avpro version to have no bug on mac version.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.4
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.4 Ultra
 - Operating system version: Win 11
 - Device model: for quest 2
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. create un simple android unity project using last avpro plugin, target android sdk 33.
2. Build apk, create a app (foar app lab) on https://developer.oculus.com/, try to upload your apk using Meta Quest Developer Hub
3. Upload fail say TARGET_SDK_VERSION_TOO_HIGH

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
In your gradles (main and launcher Templates), try this:

minSdkVersion 22
targetSDKversion 32
compileSDKversion 33

**Comment by LaurentEvaveo** [comment]
Perfect it works using "compileSDKversion 33" !

**Comment by robertncoomber** [comment]
This worked for me but changing compileSDKversion to 34 rather than 33 as some .aars now require 34.
