### ISSUE TITLE
Video freezes (AVPro + NatCorder + Vuforia + iOS)

### ISSUE THREAD

**Issue by WarlordGrey** [RenderHeads/UnityPlugin-AVProVideo#164]
Hello. I've started to use NatCorder plugin and got unusual bug.
So in my app I'm using Vuforia for AR on iOS. When marker is found, the video appears. It's playing by AVPro plugin. Then I'm trying to record all this stuff by Natcorder. I'm pressing something like "record" button. At this point video is getting stuck and don't want to be played anymore...

 - Unity version: 2019.1.14f1
 - AVPro Video version: 1.10.0
 - Operating system version: iOS 12.4
 - Device model: iPhone X
 - Video specs (resolution, frame-rate, codec, file size): 4096x682, 29.97 FPS, mp4, 108mb

**To Reproduce**
1. Track mark with vuforia
2. Start playing video
3. Start recording
4. You can see frozen video

**Logs**
No errors or warnings....

**Videos**
You can find video with bug in the attachment. Recording starts when "Toggle record" button isn't green.
[RPReplay_Final1567519722.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3569922/RPReplay_Final1567519722.zip)

**Comment by WarlordGrey** [comment]
At first I've asked NatCorder's developer but got next anwer:
"Hi there. I'm not sure what exactly the issue might be, but it sounds like your app might be resource constrained. You are decoding a video (AVPro), running AR (Vuforia), and encoding a video (NatCorder) at the same time. This is very resource-intensive. Are you able to successfully record with NatCorder? Also, I recommend reaching out to AVPro since it sounds like the issue is that the video stops playing, not that recording doesn't work."

**Comment by MorrisRH** [comment]
I've been doing further testing with Vuforia, AVPro Video and AVPro MovieCapture and I'm unable to reproduce the issue. At this point I have to assume the issue lies with NatCorder as it's the only part of the chain I'm unable to test against.

**Comment by WarlordGrey** [comment]
I'm sorry, but as I can see from description your plugin supports only windows and mac OS... But I need ios/android support.
https://assetstore.unity.com/packages/tools/video/avpro-movie-capture-151061

**Comment by AndrewRH** [comment]
> I'm sorry, but as I can see from description your plugin supports only windows and mac OS... But I need ios/android support.
> https://assetstore.unity.com/packages/tools/video/avpro-movie-capture-151061

Yes, the iOS version is not released yet.   We're just finishing some internal polish and it should be available any day now on the Asset Store (and the free trial version from our website).  We currently don't have Android support though.

**Comment by olokobayusuf** [comment]
Developer of NatCorder here. I've noticed that your recording resolution is very high (4096x682), so it is very likely that the hardware codecs are overwhelmed. The max recommended resolution to record at is 1920x1080.

**Comment by WarlordGrey** [comment]
> 
> 
> Developer of NatCorder here. I've noticed that your recording resolution is very high (4096x682), so it is very likely that the hardware codecs are overwhelmed. The max recommended resolution to record at is 1920x1080.

I don't record screen at 4096x682. It is video's resolution for AVPro videoplayer. I record screen at device's resolution...

**Comment by MorrisRH** [comment]
There is nothing internal to the plugin that would cause playback to pause (with the exception of the pause method). The only external event that will cause playback to pause is if the audio route changes, for instance when headphones are removed. 
Is it possible that NatCorder is triggering an audio route change somehow?

**Comment by olokobayusuf** [comment]
NatCorder doesn't touch audio routes. @WarlordGrey are you recording with a microphone? Perhaps this could be causing an audio route change.

**Comment by WarlordGrey** [comment]
Yes, I'm recording with microphone... Is there any diffrent way to record sound for iOS?

**Comment by olokobayusuf** [comment]
@MorrisRH @AndrewRH are you guys familiar with any way to use AVPro while using Unity's `Microphone` class? It seems that this is the underlying cause of the issue.

**Comment by MorrisRH** [comment]
I can confirm that Microphone usage is the cause. However the solution is quite straight forward, simply check the “Prepare iOS for Recording” option in the “Other Settings” section of the Player Settings, as shown below.

![Screenshot 2019-10-04 at 16 30 51](https://user-images.githubusercontent.com/46530460/66220271-a48a0d00-e6c4-11e9-8e99-18f9c25f5faf.png)

Thanks for the assistance @olokobayusuf !

**Comment by nvandessel** [comment]
@MorrisRH thank you so much, this just saved my bacon!
