### ISSUE TITLE
Why do you not have any 180 video demo scene?

### ISSUE THREAD

**Issue by realitygarage** [RenderHeads/UnityPlugin-AVProVideo#1641]
**Question**

**Comment by Chris-RH** [comment]
We try not to overcomplicate things by having too many demos.

You can use the 360 demo scene to play your 180 video.  Just change Video Mapping in the Mediaplayer component to Equi Rectangular 180.

**Comment by realitygarage** [comment]
this is for the quest BTW

**Comment by realitygarage** [comment]
so I've followed your instructs on page 42 of the user's manual "...Instead a material with the AVProVideo/VR/InsideSphere Unlit Transparent(stereo+color+fog+alpha) shader can be applied to the sphere..."  and now only get the video on 1/2 of the sphere, but the resolution is still not 8K - it looks way less quality as compared to playing the same video with an off the shelf video player on the quest. I've tried using both the exoplayer as well as the media player (in your android platform settings of your media player), and I've set the "HighQuality" to true on your shader.. but I am still not able to get expected quality result in a build. 

I have been able to use the Oculus  example scene "Stereo180Video" which uses the built in Unity Video player - and it looks exactly as it should - so I guess I'll ditch using AVPro for this - but it seems like I'm just missing something - Any and all advise appreciated

**Comment by Chris-RH** [comment]
What are the full specs of the video that you are using?

Have you tried OES rendering?

**Comment by realitygarage** [comment]
Here is a screen shot of the mediaInfo tree for the file.
![Screenshot 2023-09-13 103505](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/27872537/3ce3985b-79b8-42da-934d-deaead07c4df)

As far as OES rendering.. looks like in order to enable that, I would need to switch to multi-pass rendering and take a performance hit... I'd be happy to send you a link to the video if you like... I'm just looking to get as good of quality as the oculus example that comes with their SDK... Oculus\SampleFramework\Usage\Stereo180Video.unity - which works great with singlepass mode - and just need to understand how to setup AVPro as such. Also good about the oculus example scene is that it projects on a half sphere - which again is nice to have in an example - and it seems like this would be a very popular use case for you'all to support and show off, in particular with the new 180 gear like the Canon Dual Fisheye 3D VR Lens. Thanks

**Comment by realitygarage** [comment]
Here is a link to the video just in case its helpful

https://drive.google.com/file/d/1Il5h1JBQd5aj2-qAcGFajvUv1YhtQWwI/view?usp=sharing

**Comment by machenmusik** [comment]
(I suspect the visual quality difference comes from OVROverlay usage)

**Comment by realitygarage** [comment]
hmmm - you're probably right with that... I expect then that there should be a way to create a solution using avpro and the OVROverlay - but not in my wheel house nor a priority - but just say'n... seems like a use case that renderhead folks would want to support and provide as a demo scene :)

**Comment by Chris-RH** [comment]
Please bear in mind the video recommendations for the Quest 2
https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/

**Comment by Chris-RH** [comment]
Also, when you set up OES rendering, you need to add the Update Multi-Pass Stereo component and select the correct OES shaders.

**Comment by Fangh** [comment]
> We try not to overcomplicate things by having too many demos.
> 
> You can use the 360 demo scene to play your 180 video. Just change Video Mapping in the Mediaplayer component to Equi Rectangular 180.

I also have a 180 video.
I used your Demo_360Stereo Scene in AVPro 3.3.6 Core Edition and it does not render correctly.

**Comment by Fangh** [comment]
I tried with this video : https://github.com/oculus-samples/Unity-StarterSamples/blob/main/Assets/StreamingAssets/stereo-meta-sphere.mp4

but it seems weird.
Should I use a half sphere mesh ?

<img width="1363" height="1015" alt="Image" src="https://github.com/user-attachments/assets/49a48c09-0506-4e99-94e6-109d0fb4be99" />

<img width="1147" height="1093" alt="Image" src="https://github.com/user-attachments/assets/5e98385f-b385-4187-955d-2304ddf2a4d7" />

**Comment by Fangh** [comment]
Using a half sphere + using AVProVideo/Unlit/Opaque - Android OES Only + Update Multi-pass Sterero component on camera +using Single Pass Instanced / Multi View on OpenXR Project Settings + Video Maaping set to Equi Rectangular 180 in Media Player Settings + simple right/left stereo vidéo doesn't work, the left and right eyes sees a really big gap.

WHat is the correct procedure ?

**Comment by Fangh** [comment]
I succeeded. For someone stumbling on this post :
1) I used Unity FBX Exporter Package to export OctahedronSphere8192.mesh as an FBX
2) I used Blender to cut it in half
3) I set the material to `AVProVideo/VR/InsideSphere Unlit (stereo+color) - Android OES ONLY`
4) I used [this video](https://github.com/oculus-samples/Unity-StarterSamples/blob/main/Assets/StreamingAssets/stereo-meta-sphere.mp4) to test 
5) I setted Equi Rectangular 180 on the `Video Mapping` settigns in the Visual Tab in the Media Player component

ok I needed to set the material to `AVProVideo/VR/InsideSphere Unlit (stereo+color) - Android OES ONLY`
