### ISSUE TITLE
Does AVpro support play panoramic video as skybox in Pico4pro?

### ISSUE THREAD

**Issue by yq-Liang** [RenderHeads/UnityPlugin-AVProVideo#1643]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Hello,
I'm trying to play panoramic video as skybox in Pico4pro. My project ran well under the editor mode of Unity, however, there is no  picture when I build and run it on my Pico4pro. I checked the Video API of Android, there is no picture and sound under the Exo Player while another mode makes sound and no picture. I tried to change the shader of the skybox material but didn't work. Besides, I'd like to know that if I can play 8K panoramic video as skybox on Windows or Pico4pro？

 I can't figure it out so tend to you for help, thanks a lot. 
**Your Setup (please complete the following information):**
 - Unity version: 2021.3.5f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.8.3f1-core
 - Operating system version: Windows/Android
 - Device model: NVIDIA GeForce RTX 3060 Laptop GPU/Direct3D 11.0 and Pico4pro
 - Video specs (resolution, frame-rate, codec, file size): 1080p/4K/8K

**To Reproduce**
1. import pico integration sdk 230, edit project settings following the pico quick start document.
2. create AVPro-video MediaPlayer with Unity Audio, choose one video in the assets.
3. create empty, add ApplyToMaterial component, choose MediaPlayer in 2 as Media, new a material named skybox-vr as Material.
4. Window->Rendering->Lighting->Environment, choose skybox-vr as Skybox Material.
5. build and run it on Pico4pro.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Do you mean a 180/360 equirectangular video or actual panoramic video which would leave a void at the top and bottom?
2. Have you tried lower resolution/different videos?
3. What are the full specs of the video/s tested?
4. Have you tried using the demo scenes as a starting point?
5. Are you streaming or playing from locally?
6. What error messages are you getting on your logcat?

**Comment by yq-Liang** [comment]
Hello,
I've found that I missed the Unity tips when I built it. It's said that
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/96573508/b328a876-9b06-404a-945b-3751fc8c47b1)
And I remove the Vulkan from the list, just likes the picture below.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/96573508/3eecd76c-87a9-432c-b88f-07c6bc9d9cee)
And everything works well in my Pico4pro.
Thanks a lot~
