### ISSUE TITLE
update mediaplayer media path in runtime result  to memory leak

### ISSUE THREAD

**Issue by wh2000292** [RenderHeads/UnityPlugin-AVProVideo#1644]
**Describe the issue**
update mediaplayer media path in runtime result to memory leak

**Your Setup (please complete the following information):**
 - Unity version:  2022.3.7
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  core 2.8.5
 - Operating system version:  windows 10
 - Device model:  
 - Video specs (resolution, frame-rate, codec, file size):   mp4 with left right alpha packing    resolution: 2160*1920 frame-rate:25 

**To Reproduce**
1. use Demo_MediaPlayer.unity
2. use Resovle to RenderTexutre  instead  Display ugui
3. add script into MediaPlayerUI.cs  
void HandleEvent(MediaPlayer player, MediaPlayerEvent.EventType eventType, ErrorCode code)
{
    
    if (eventType == MediaPlayerEvent.EventType.FinishedPlaying)
    {
		string path1 = Application.streamingAssetsPath+"/266778.mp4";
        string path2 = Application.streamingAssetsPath + "/266779.mp4";
        _mediaPlayer.Stop();
		_mediaPlayer.CloseMedia();
        if (_mediaPlayer.MediaPath.Path==path1)
		{
			
			_mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, path2,true);
			
		}
		else
		{
            _mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, path1,true);
        }
    }
}

4. run application  and wait some times. you will see the Memory growth is significant

**Comment by wh2000292** [comment]
only untracked memory changed irregularly。 I can not get more useful information from profiler.

**Comment by Chris-RH** [comment]
Have you thought about using the playlist component? 
https://www.renderheads.com/content/docs/AVProVideo/articles/component-playlist-media-player.html

**Comment by wh2000292** [comment]
if I changed playerlist in runtime, there also have the same problem.

**Comment by Chris-RH** [comment]
1. So if you use the same videos already set up on the playlist (ie not added at runtime) are you still having this problem?
2. How big is the memory leak?
3. Does it slowly keep increasing over a time or does it rise to a certain point and then stop?
4. Have you tried garbage collection?

**Comment by Chris-RH** [comment]
Any more info?
