### ISSUE TITLE
Unable to view streaming HLS videos on Android

### ISSUE THREAD

**Issue by davemorleyuk** [RenderHeads/UnityPlugin-AVProVideo#1645]
**Issue**
I can no longer get remote HLS videos to play on Android (previously working correctly in older versions of Unity/AVPro)
Local videos ARE working.

**Setup:**
 - Unity version: 2022.3.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Core v2.8.5
 - Operating system version: Android 13 / OxygenOS 13.0
 - Device model: OnePlus Nord2 5G
 - Video specs (resolution, frame-rate, codec, file size): Demo HLS video

https://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)

**To Reproduce**
1. Install blank (URP) Unity project just with AVPro core
2. Update Demo_MediaPlayer scene to use "Sample-Https-HLS-AzureLlamaDrama4K" media reference. (SIDE NOTE: this sample reference was referencing http not https despite the name suggesting otherwise)
3. Change settings in player settings 
    -> Auto Graphics API = unticked
    -> Graphics APIs = remove Vulkan
    -> Target API level = Android 13 (API level 33)
    -> Scripting Backend = IL2CPP
    -> Target Architectures, ARMv7, ARM64 = ticked
    -> Internet Access = Require
4. Change Build settings -> Scene in build to be Demo_MediaPlayer scene
5. Build and run on device
6. Confirm no video is playing

**Logs**
[avpro-test-logcat.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/12589952/avpro-test-logcat.log)

**Videos**
(https://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl))

**Comment by BlueDonutStudios** [comment]
It's both Android and iOS. We're using Unity version: 2022.3.9f1 and deploying on Android and iOS and having the issue with the video.

**Comment by davemorleyuk** [comment]
> Hi @davemorleyuk ! I've been struggling for days with the same issue, but with Oculus Quest2, and, at least in my case, I solved it by forcing the video format to HLS (like in attached screenshot) and it worked like a charm.
> 
> ![image](https://user-images.githubusercontent.com/62797171/268004284-664fc835-a3b5-4182-85c2-a3e793a87c53.png)
> 
> I hope that works for you!
> 
> Still, I guess the issue is that the format is not being assigned correctly in Android

Thanks Jorge.. hadn't tried that

**Comment by davemorleyuk** [comment]
I think I've resolved this for the moment. My phone wasn't connecting correctly to the wifi!
