### ISSUE TITLE
Black screen appears on iOS Sometimes

### ISSUE THREAD

**Issue by companyofpotato** [RenderHeads/UnityPlugin-AVProVideo#1646]
**Describe the issue**
When play video on iOS, sometimes it shows black screen with sound.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.48f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.7.3 ultra
 - Operating system version: iOS 16.4.1
 - Device model: iPhone 13 mini
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080

**To Reproduce**
1. Use ApplyToMaterial to play video on material
2. Call OpenMedia with video URL (set autoPlay false)
3. Play Video after FirstFrameReady Event occur.

**Logs**
[iOSBlackScreen.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/12602922/iOSBlackScreen.txt)

**Videos**
[If applicable, add a copy of your video or the URL](https://mediapoccdn2-standard-ms-ams.azureedge.net/ebd5f61c-732e-4b6c-88ac-2a377a39bce5/92a72576-c80e-4994-bfc2-2dd3778f.ism/manifest(audio-only=false,format=m3u8-aapl-v3).m3u8)

**Comment by companyofpotato** [comment]
I updated to 2.8.5, but it happens again on same situation sometimes.

**Comment by Chris-RH** [comment]
Can you reproduce this in a fresh project that is only running AVPro demo scene?
Have you tested this on different devices?
Have you tested different media?

**Comment by companyofpotato** [comment]
It happens on iPhone Xs(OS 16.1) too. And I tested m3u8 only. I can't sure it happens on other type of file.

Now, I'm trying to reproduce this in fresh project.
I'll let you know if it happens again.

**Comment by Chris-RH** [comment]
Perhaps try some of these test streams too; https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#test-streams

**Comment by companyofpotato** [comment]
I tested it with unity editor and IOS in the demo scene, but it was not reproduced.
I repeated video registration and playback at 3-second intervals for an hour.

Originally, this issue occurred 2, 3 times in 1 hour of trying.

**Comment by Chris-RH** [comment]
OK, that's good to know.

**Comment by Chris-RH** [comment]
Is it still continuing to work in the demo scene and other streams?
If so, I would gradually add bits of your project and keep testing as you go to see where the conflict arises.

**Comment by Chris-RH** [comment]
How is this going?

**Comment by companyofpotato** [comment]
Currently, issue is reproduced in my project on Mac, IOS platform. But demo scene works fine on both platforms.
I suspect that the shader I used is cause of the issue. I'll let you know after I finish checking.

**Comment by Chris-RH** [comment]
Thanks, that seems a likely suspect. Please keep us updated :)

**Comment by luankun** [comment]
Our project also encountered a black screen issue when playing videos on iOS devices. One consistent observation is that once one video starts playing with a black screen, all other videos also play with a black screen. However, most of the devices can recover from this issue after a restart.

**Comment by KeeleyYu** [comment]
> Our project also encountered a black screen issue when playing videos on iOS devices. One consistent observation is that once one video starts playing with a black screen, all other videos also play with a black screen. However, most of the devices can recover from this issue after a restart.

Our project encountered as well. Black screen mainly appeared on Iphone7. We have checked the log and found no suspicious related errors. @Chris-RH

**Comment by Chris-RH** [comment]
If you can find a way to reliably reproduce the issue, please let us know.
iphone 7 is over 7 years old now.  Are you finding the issue with newer devices?

**Comment by KeeleyYu** [comment]
> If you can find a way to reliably reproduce the issue, please let us know. iphone 7 is over 7 years old now. Are you finding the issue with newer devices?

On iPhone7 plus and lower-end machines, with the same encoding (h264), videos larger than 5M will fail to play, while videos smaller than 5M will play normally, which can be reproduced stably.
In our project, we first called method 'OpenMedia', and then bound the 'Events', and then called Play after receiving the ReadyToPlay event. Is this usage correct?
@Chris-RH

**Comment by KeeleyYu** [comment]
In addition, in the ‘InternalOpenMedia’ function of ‘MediaPlayer.cs’, even if a certain video file does not exist locally, the return result is still true. This should be unreasonable, right?

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/7234842/e23074e6-4088-46ab-b0ab-f96c3b3e663a)

**Comment by Chris-RH** [comment]
Are you able to provide a sample of the video you are using?  Either here or email unitysupport@renderheads.com

**Comment by KeeleyYu** [comment]
> 1. OpenMedia, ReadyToPlay then Play is correct
> 2. It is correct, if you follow the flow of the code.  It just looks odd :)
> 
> Are you able to provide a sample of the video you are using? Either here or email [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

We are sorry that our video is still in production and cannot be released, but if you construct a video larger than 5M (our project video is about 8M, 15 seconds) and try to play it on iPhone 7, maybe you can reproduce this same issue.

In addition, we checked the log and found that the FirstFrameReady event was not sent either, which is the same problem as #1266.

**Comment by KeeleyYu** [comment]
OS version: iOS 15.8 and IOS 13.3.1
No, sorry, we haven't had time to make a new video clip.
