### ISSUE TITLE
PlaybackRate Rounding and Recommended Rates

### ISSUE THREAD

**Issue by markgrossnickle** [RenderHeads/UnityPlugin-AVProVideo#1647]
**Question**

I'm curious about the recommended playback rates in the documentation where it suggests 0.25, 0.5, etc. Are they recommended because playbackrate gets rounded to certain values? Or why are these rates recommended?

We would like to set playbackrate to precise numbers like 0.74736 and be constantly changing the rate as we are working on an exercise application where the faster the user goes, the faster the video should playback. If the user slows down it may drop to 0.44321 and then if they go real fast it could go to 1.2323 or similar.

Something seems off (and I don't know if it is the video playback) but the video tends to reach its end before the actual distance is reached. The video's completion percentage increases faster throughout playback than the distance travelled so the delta between the video completion and the distance actually completed slowly grows throughout the workout.

Soooo. Is there any rounding being done on playbackrate? In the editor when I set it, I can get it back out and it is identical so the variable itself isn't rounded.

We are currently testing on Windows and iOS.

**Comment by Chris-RH** [comment]
Hmmm, this is an interesting issue.  We think that the current framerate, the video framerate and the video playback rate are interacting such that you are not getting the desired results. There shouldn't be any rounding going on in the lower level API.

1. Can I confirm with you that this has been tested on both Windows and iOS, and that both are having this issue?
2. Are you using one video for testing or a bunch of different videos?
3. What playback rates have you tested? Have you tried 0.1 increments?
4. How is the video(s) encoded? codecs? FPS? Is the framerate variable or constant? How are the keyframes spaced? (Even better, can you provide a copy of the video you are using either here or to unitysupport@renderheads.com)
5. Can you provide a sample project please (unitysupport@renderheads.com)
6. What are you doing to determine why you think that the roundings are happenning?
7. Additional info please:

- Unity Version
- AVPro Video Version
- Windows Version
- iOS Version
- Devices used for testing

**Comment by markgrossnickle** [comment]
Hey Chris, thanks for the response. I want to take a step back for a second. I am not reporting a bug or saying there is an issue. I'm trying to figure out if we have an issue on our side or if there is known rounding with playback rates. Your documentation states rates that you recommend:

"0.25, 0.5, 1.0, 1.25, 1.5, 1.75, 2.0"

Why are those rates recommended versus something not in those increments?

**Comment by Chris-RH** [comment]
Honestly, they are pretty standard playback rates if you look at platforms such as the likes of Netflix and Youtube. You can certainly use 0.1 increments, but beyond that videos tend to look a bit janky.  There aren't too many use-cases for more precise increments.
To make variable playback rates work well/look good, you want high FPS videos, which again are not very commonly used.
Audio is another thing that makes it tricky as you need to resample to make it sound reasonable and 1/2, 1/4 etc. is nice and easy.
