### ISSUE TITLE
Crash on iOS when open/close local video

### ISSUE THREAD

**Issue by litefeel** [RenderHeads/UnityPlugin-AVProVideo#1648]
**Describe the issue**
Frequently switch between different local videos, then the app crash.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.40f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.5 ultra
 - Operating system version: ios 16.6.1
 - Device model: iphone 13
 - Video specs (resolution, frame-rate, codec, file size): 1920*1080 frame-rate:30 codec:mp4 file size:2.7M

**To Reproduce**
1. set texture format: YCbCr420
2. open local video A
3. close and open video B
4. close and open video A
5. goto step 2

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/1288575/00c90e7f-40a3-43d4-b028-e70a3c71c671)

![img_v2_0c6bde29-d7f3-4193-9c2a-2889d689778g](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/1288575/0f9f0d7b-8aa2-4c18-9be2-5aaf3565eec0)

**Comment by Chris-RH** [comment]
Is this repeatable in a new project, just running AVPro Video?
How many times are you opening/closing?
How long are you allowing a video to play before closing?

**Comment by Chris-RH** [comment]
Is this repeatable in a new project, just running AVPro Video?
How many times are you opening/closing?
How long are you allowing a video to play before closing?

**Comment by Chris-RH** [comment]
Closed due to lack of reply
