### ISSUE TITLE
Select Audio Output Device

### ISSUE THREAD

**Issue by Piflik** [RenderHeads/UnityPlugin-AVProVideo#1650]
We are currently still using Version 1.11.7.
I have an app I built for internal use, with the main functionality to display videos at specific positions on screen. Until now I used the basic Unity VideoPlayer, but now a colleague came to me with the request to select the audio output device to something different than the default Windows audio.
I have found the "ForceAudioOutputDevice" otion that works with DirectShow, but apparently this decoder is limited to 1920x1080 resolutions. When I use MediaFoundation, the App uses the default device again.
I have seen that the new version of the plugin has a third option for the Video API, WinRT, but I haven't found any information regarding audio with this one selected, except that it doesn't support Unity Audio.

Is it possible in the current version of the plugin to select the audio output device for videos larger than FullHD?

**Comment by Chris-RH** [comment]
Download and install LAV filters and add it to the "filters" in the DirectShow options on the mediaplayer as follows:

(sorry, screenshot is from version 2, but this should work for version 1)
![84421861-13d0dd00-ac14-11ea-8c1b-72f254aaa9b7](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/7cce6498-8ede-4dca-8158-c9f9d2788d01)

This should allow you to use higher-resolution videos.

**Comment by Piflik** [comment]
Do these filters need to be installed on every machine the app is running on? Or do they get bundled into the app?

**Comment by Chris-RH** [comment]
They need to be installed on the machine.  Its to get around the limitations of Windows.
