### ISSUE TITLE
Problem getting Azure Media Services with AES Clear Key to work

### ISSUE THREAD

**Issue by influjensbahr** [RenderHeads/UnityPlugin-AVProVideo#1651]
Hi! I am currently working on a project with this setup:

- Azure Media Services videos, HLS / DASH, with a ClearKey streaming policy. There is no token restriction in place for the videos. No DRM, only AES clear key, no token restriction.
- Unity 2021.3 with newest AVPro video installed

The way I understand it, I should be able to play the videos in AVPro. I currently have the Core version (newest one), but also tried with the trial for the Ultra version.

The error I am getting doesn't say much: 
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

I can play the videos using the Azure Media Player: https://ampdemo.azureedge.net/azuremediaplayer.html
But they always switch to DASH there. 

For test purposes, I also tried uploading a video with token restrictions. I can get it to work on the Azure Media Player above using the HLS Token and the URL. In AVPro on unity, the same URL and HLS token don't seem to work and produce the above error.

I have tried getting this to work over the past months, on and off again, and am starting to get desperate. I would greatly appreciate it if somebody could help! Thanks!

**Comment by Chris-RH** [comment]
1. Which platform(s) are  you testing on?
2. Which Video API(s) have tested?
3. What are the details of the videos that you have been testing? codec,resolution etc
4. Have you got a link to a test URL that you have been using? Either post here or send to unitysupport@renderheads.com

**Comment by influjensbahr** [comment]
Closing as resolved, the solutation was in #1516
