### ISSUE TITLE
Keep throwing [AudioCapture] error on iOS 17

### ISSUE THREAD

**Issue by kenson4gusto** [RenderHeads/UnityPlugin-AVProVideo#1653]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**

I'm using AVPro Video version 2.8.5 to play a video on my iOS device. However, after upgrading my iPhone 12 Pro to iOS 17, I encountered an issue where an error message kept printing while the video was playing. The error message is `[AudioCapture] failed to get output buffer size from interleaver, error: \377\377\377\316.`

Regarding the audio settings, I have set the iOS Audio Mode to Unity because I need the Unity AudioListener to hear the video sound. Currently, the audio of the video plays correctly on the iPhone device, but the Unity AudioListener is unable to capture the sound of the video and continues to throw an error while playing. It's important to note that the same build works flawlessly on iOS 16.

Additionally, I performed a test by changing the Audio Mode to System Direct, which resulted in the disappearance of the error message. However, the Unity AudioListener couldn't capture the sound of the video. Therefore, I believe this is not an acceptable solution to resolve the issue.

In conclusion, I would like to inquire if there are any specific video settings that I can adjust to meet my requirements before a new bug fix is released.

**Your Setup (please complete the following information):**
 - Unity version: Unity 2022.3.7f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  AVPro Video core edition version 2.8.5
 - Operating system version: iOS 17.0
 - Device model: iPhone 12 Pro / iPhone 11
 - Video specs (resolution, frame-rate, codec, file size):  2160x960, H.264 (side by side with Black & white alpha mask video)

**To Reproduce**
1. Set the iOS Audio mode to Unity
2. Build an app and install it on iOS 17 device
3. See the log

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
<img width="733" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/76143403/89c61181-8cc1-4726-aa69-281b735d57c0">

<img width="985" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/76143403/e4652931-9bd1-4031-9aec-0d1af5adc060">

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Can you reproduce this in a fresh project using just the AVPro Video demo scene?
2. Have you made sure to add the Audio Output component?
3. Have you tried different videos?

**Comment by kenson4gusto** [comment]
Hi Chris, thanks for the reply.

1. Yes, I have tried to create a fresh project and build the AVPro video demo scene (Demo_MediaPlayer). Even the demo video is not able to play on iOS17 (working well on iOS16).

Here's the log while playing the video on iOS17
<img width="1222" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/76143403/b03db87a-c044-4364-b0c2-d71d6a1ba68f">

2: Yes, the Audio Output component has attached
<img width="691" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/76143403/c1a4db3b-a006-4aa2-8914-3c0d12eb6612">

3: Yes, tried as well. issue still happening

**Comment by amandalam** [comment]
Thanks @kenson4gusto for reporting this. I'm also encountering this issue too.
Appreciate a fix as soon as possible as this has been breaking our app. Thanks!

**Comment by dantetwc** [comment]
Got the same issue. Please advise. @Chris-RH

**Comment by Chris-RH** [comment]
Brilliant, thank you for the information.  I'll pass it on to our iOS dev.

**Comment by soniatsl** [comment]
Hi @Chris-RH , any updates on this issue? As iOS 17 already launched for two weeks. Thanks

**Comment by Chris-RH** [comment]
Unfortunately our iOS dev is working on another project at the moment, so won't have a chance to properly dig into until mid-late October. 
That code has been solid for years across many iOS versions, so we have no idea why Apple have broken it.

**Comment by MorrisRH** [comment]
I have reproduced this issue and am currently investigating what has changed with iOS 17. I do have a work around for you though — check *Use single player item* in the iOS section of the *Platform Specific* options in the media player inspector as shown here:
<img width="531" alt="Screenshot 2023-10-09 at 11 02 58" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/3facd748-1e11-4198-8673-c82aaae59131">

This will only affect looped playback so if you're video is not looping then you will notice no difference, if it is looped then there will be a stutter at the loop point.

**Comment by kenson4gusto** [comment]
Hi @MorrisRH , thank you for your reply. I wanted to let you know that the workaround solution is currently working for me. However, I've noticed that the audio becomes slightly out of sync after the video has looped multiple times. I'm curious to understand why this configuration can fix the issue on iOS 17.

Thank you so much for your support.

**Comment by MorrisRH** [comment]
iOS 17 has changed the behaviour of the audio processing tap which unfortunately broke our implementation. This has now been fixed and normal service will resume with the next release which will hopefully be next week.

**Comment by Chris-RH** [comment]
This has been fixed in AVPro Video version 2.9.0. Please let us know if you are still having issues with it.
