### ISSUE TITLE
HoloLens2 live streaming not retrievable

### ISSUE THREAD

**Issue by iwatuki** [RenderHeads/UnityPlugin-AVProVideo#1654]
**HoloLens2 live streaming not retrievable**
If HoloLens2 is turned off and on again while acquiring live streaming from HoloLens2, live streaming cannot be acquired after that.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.4f1
 - AVPro Video version (trial): v2.8.5
 - Operating system version: Windows11 Home
 - Device model: Windows Desctop PC
 - Video specs (resolution, frame-rate, codec, file size): 1280 x 720 p 30 fps 5 Mbit

**To Reproduce**
1. Turn on HoloLens2 and enter the URL of HoloLens2 API in MediaPlayer
2. Successful connection and playback
3. Video playback stops when HoloLens 2 power is turned off during playback
4. Turn on HoloLens 2
5. MediaPlayer.OpenMedia() does not play

This will continue unless you restart the exe or UnityEditor.

Pressing the Load or Close button of MediaPlayer on UnityEditor does not acquire the latest streaming as well, and the video buffer from the last connection appears to be playing in a loop.

Holo2 API in use
/api/holographic/stream/live.mp4 (GET)

**Logs**
No error log is generated, and the buffer of the last time it was playing? is played in a loop.

**Comment by Chris-RH** [comment]
We don't have a Hololens, so can't do any testing ourselves I'm afraid.
Have you tested using both Media Foundation and WinRT?
Have you tested local video files and different types of streams?

**Comment by iwatuki** [comment]
@Chris-RH 
Currently running on Direct Show, but have also tried Media Foundation and WinRT.
Playback of local files has been tried. I have not tried any other streaming playback.
I am having problems reconnecting after disconnecting and can't find any other way to check.

**Comment by Chris-RH** [comment]
And are you getting stalled/unstalled events? 
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-events.html

**Comment by iwatuki** [comment]
yes.

[Play start log]

> [AVProVideo] Using playback path: DirectShow (1280x720@30.00)
> MediaPlayer MediaPlayer generated event: MetaDataReady
> MediaPlayer MediaPlayer generated event: ReadyToPlay
> MediaPlayer MediaPlayer generated event: Started
> MediaPlayer MediaPlayer generated event: ResolutionChanged
> MediaPlayer MediaPlayer generated event: StartedSeeking
> MediaPlayer MediaPlayer generated event: FinishedSeeking
> MediaPlayer MediaPlayer generated event: FirstFrameReady
> MediaPlayer MediaPlayer generated event: FinishedPlaying

[Turn off the holo-lens]

> No log (video stopped)

[Stop Unity Editor play]

> [AVProVideo] Shutdown
> MediaPlayer MediaPlayer generated event: Closing

[Play the game again and play the video]

> [AVProVideo] Using playback path: DirectShow (1280x720@30.00)
> MediaPlayer MediaPlayer generated event: MetaDataReady
> MediaPlayer MediaPlayer generated event: ReadyToPlay
> MediaPlayer MediaPlayer generated event: Started
> MediaPlayer MediaPlayer generated event: ResolutionChanged
> MediaPlayer MediaPlayer generated event: StartedSeeking
> MediaPlayer MediaPlayer generated event: FinishedSeeking
> MediaPlayer MediaPlayer generated event: FirstFrameReady
> MediaPlayer MediaPlayer generated event: FinishedPlaying

The difference seems to be that the FinishedPlaying event is no longer called.

**Comment by Chris-RH** [comment]
Out of interest, does the same behaviour occur when using Unity videoplayer or does it begin playing again?

**Comment by iwatuki** [comment]
UnityVideoPlayer could not play it, but AVPro could play it, so I am trying to use it.

**Comment by iwatuki** [comment]
Do you think you can solve the problem?
If not, we'll have to try something other than AVPro.

**Comment by Chris-RH** [comment]
Our Windows dev is busy with another project at the moment, so won't have the chance to look into this soon I'm afraid.
