### ISSUE TITLE
Quest 2 crashes or gets stuck when playing multiple h265 videos at different resolutions

### ISSUE THREAD

**Issue by LukeFarrer** [RenderHeads/UnityPlugin-AVProVideo#1658]
We have a Unity scene on the Quest 2. It consists of various looping videos playing at the same time depicting a river. 

Each video runs on three separate sections of geometry with texture coordinates. The part on the left runs at 4k (4096x4096). The part in the front at 2k (2048x2048), and the part on the right at 1k (1024x1024). 

Each section has its own instance of AVProVideo - MediaPlayer. So effectively, three videos are running concurrently.

The videos are h265, fps 29.97, created using ffmpeg, default bit rate, using Point rendering, Exoplayer.

ffmpeg code used to create the video:
ffmpeg -y -r 29.97 -start_number 1 -i video\\%05d.jpg -vframes 30 -s $resolutionString -vcodec libx265 -vf colormatrix=bt601:bt709 movie.mp4

We are getting the following behaviour when running the .apk:
- random crashes
- random freezing of the app
- the looping fails to work (works once as expected, then turns black)

We are on AVProVideo 2.8.5 (Core), Unity 2019.4.11f1, building on Windows 11.

When building the app with just the part on the left (the 4k video), everything works smoothly. If we build with the left and front sections (4k and 2k), sometimes it works, sometimes it crashes. If we build with all three sections (4k and 2k and 1k), it almost always crashes. If we replace the 4k video with a 2k video, all the parts work fine, but now there is not enough detail in the 4k video.

There seems to be a point where the system or AVProVideo simply cannot cope with the overhead.

Given that other people are able to get an 8k video to work with the Quest 2, this seems pretty limiting. 

Is the issue running multiple videos at once? Are there any suggestions you might have for making this setup work in a stable manner? How can we tell if we are getting too close to what the Quest 2 can handle?

Any thoughts would be much appreciated.

Luke

**Comment by Chris-RH** [comment]
Always be aware of the Maximum specs for the device that you are using: https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/

Every Android device will be limited at some level with how many videos it can play back at the same time. Factors include - resolutions, bitrates. framerates, codecs, the hardware in the device. If you can play each video by themselves, then the playback system is working as it should. If it is multiple videos played together you are find issues with, then that is as above - just the limitations of the device.

The fundamental problem is that devices cannot play multiple videos at once. Some Android devices can only provide only one decoder instance at a time to an app, some can offer multiple but with a limit. This varies per device and there is no consistent behavior (as of Android 12 there is some improvement - see next paragraph). ExoPlayer takes a conservative approach, and only occupies one codec instance at a time, e.g. when moving between items in a playlist ExoPlayer makes sure to first release a codec before acquiring the next one.

The general suggestion is to ensure you have only one player instance at a time playing video, if not having one instance in total in your app. On Android 12, the platform introduced the [performance class](https://developer.android.com/topic/performance/performance-class) by which an app can figure out if the device can provide multiple decoders concurrently, hence the app can do multiple playbacks.

The only other possible solution would be to playback some of the videos as 'software decoded'.

**Comment by LukeFarrer** [comment]
Hi Chris,

Your suggestions were spot on. I combined all my videos into one large one and everything worked 100% with a great resolution. With OES rendering it was even smoother.

I can't believe I've been using multiple videos up until now. Everything runs so much more smoothly now.

Thank you for such a clear and knowledgeable response.

Luke

**Comment by Chris-RH** [comment]
I'm so glad that you are sorted now. Have a great weekend :)

Kind regards, 
Chris
