### ISSUE TITLE
failed to load value for key "readable"

### ISSUE THREAD

**Issue by moonaoona** [RenderHeads/UnityPlugin-AVProVideo#166]
How to get around this error?

Player 324: failed to load value for key "readable", error: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “somedomain.com” which could put your confidential information at risk.

Tested the video url in browser a page says "Your connection is not private" after clicking through it allows me to proceed to play video.

**Comment by MorrisRH** [comment]
I'm guessing from the error message that you're using iOS or macOS. There's no mechanism available to the plugin by which we can override this behaviour.

However, you might be able to work around it by setting NSAllowsArbitraryLoadsForMedia to true in the NSAppTransportSecurity section of your apps info.plist, see here: [https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity)
You would then be able to access the media via http and there would be no need for a certificate.
