### ISSUE TITLE
Framerate not fixed at 25fps in Directshow API windows

### ISSUE THREAD

**Issue by Caleidocane** [RenderHeads/UnityPlugin-AVProVideo#1661]
Problem description:

Hi!
I'm developing a a windows app that use differents videos (50 videos loaded but just 1 playing.
I've noticed that the framerate of the video 25 is not correct displayed and the video plays at 30.
I need to pause to a correct frame, and it pause correct but with more frames rendered.
I double checked with the updates values of the texture tab in the editor and the frames displayed and the fps label

Device (which devices are you having the issue with - model, OS version number):

win 11 i7 12th gen rtx 3070 laptop

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

50 x 3840x2160 @ 25 

System Information:

AVPro Video: v2.8.5 (plugin v2.8.5f1-core)
Target Platform: Standalone
Unity: v2021.3.24f1 WindowsEditor
OS: Desktop - 82RB (LENOVO) - Windows 11  (10.0.22621) 64bit - Italian
CPU: 12th Gen Intel(R) Core(TM) i7-12700H - 20 threads - 16108KB
GPU: NVIDIA GeForce RTX 3070 Laptop GPU - NVIDIA - Direct3D 11.0 [level 11.1] - 8033KB - 16384

**Comment by Caleidocane** [comment]
temporary solved switching from linear to gamma, is there a way to make it work in linear?

**Comment by Caleidocane** [comment]
Ok if I use the resolve to render texture component I can create a render texture, and the colors works correctly

**Comment by Chris-RH** [comment]
Can you repeat the FPS issue in the demo scenes?
Are you able to give us a sample of your 25FPS video so we can test it in-house? unitysupport@renderheads.com

Are you using our own shaders or custom shaders?
Have you tested in D3D12?

**Comment by Chris-RH** [comment]
Any more info?

**Comment by Caleidocane** [comment]
Sorry I was in a hurry for the deadline. I can send you a sample in short.
Where can I upload the scene example?

**Comment by Chris-RH** [comment]
[unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Caleidocane** [comment]
I'm sorry for that but the only way to create the error is to share my entire project to you... I've tried to start from empty project with your demo and it works!

**Comment by Chris-RH** [comment]
Ahh, interesting.  It could be a bunch of code conflicts somewhere then.
