### ISSUE TITLE
[AVProVideo] Plugin version number 1.4.3-ultra build 19 doesn't match the expected version number 2.6.6.  It looks like the plugin didn't upgrade correctly

### ISSUE THREAD

**Issue by HFX-93** [RenderHeads/UnityPlugin-AVProVideo#1662]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.43f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.6.6 ultra
 - Operating system version: 16.6.1
 - Device model: iPhone14,5
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1.Some ios devices will initialize with this error log, but others will not.  [AVProVideo] Plugin version number 1.4.3-ultra build 19 doesn't match the expected version number 2.6.6.   It looks like the plugin didn't upgrade correctly
2. Why some iOS devices will get this version 1.4.3-ultra build 19 

**Logs**
 [AVProVideo] Plugin version number 1.4.3-ultra build 19 doesn't match the expected version number 2.6.6.   It looks like the plugin didn't upgrade correctly

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
That doesn't look right.  Did you previously have AVPro version 1 at some point?
