### ISSUE TITLE
FastSeek and Seek times are unreasonably long.

### ISSUE THREAD

**Issue by aneast08** [RenderHeads/UnityPlugin-AVProVideo#1663]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When seeking through a 360 video in vr the seek times seem to be very long when compared to other applications. The video will buffer for over a minute without any sign of playing. The video will finally load after a long wait time but it seems to be unreasonably long.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.3f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.5 Core edition
 - Operating system version: Windows 11
 - Device model: Meta Quest 3 and Meta Quest Pro
 - Video specs (resolution, frame-rate, codec, file size): 7680x3840 @ 30 fps, 12.5 GB file size in H265 codec.

**To Reproduce**
1. Play video
2. Seek to any time past where the video is playing
3. Wait for video to buffer

**Logs**
The system seems to be working fine but when seeking even just 30 seconds ahead in the video is buffers for about a minute if not longer.

**Screenshots**
![avprovideo](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/105944280/7fe27a54-85a4-4b56-b209-26cba6640a05)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Is this on your Android devices or in Windows editor too?
Is this reproducible in a fresh project using just the AVPro demo scenes?
Have you followed our guides on optimal encoding for seeking?
See the [section about encoding](https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html#fast-seeking) for further information
See the [section about seeking](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-seeking-playbackrate.html) for further information.

**Comment by Chris-RH** [comment]
Any more info?

**Comment by Chris-RH** [comment]
Closed due to lack of reply
