### ISSUE TITLE
HDRP and AV Pro Video

### ISSUE THREAD

**Issue by ntt-ebehar** [RenderHeads/UnityPlugin-AVProVideo#1665]
I'm a bit confused on the proper way to set up the lit shaders (AVProVideo/Lit/Diffuse and Transparent Diffuse) in a HDRP scene. Right now if I try to use either in my HDRP scene they render magenta.

The documentation mentions: "Materials using these lit shaders will not automatically update when upgrading to HDRP / UWP rendering pipelines."

So, I suppose my questions are:

- Is it expected of me to manually update the shaders myself, doesn't that involve rewriting the shader? This is a skill set I do not have.
- Would I lose fidelity or functionality if I use the HDRP/Lit shader over the ones supplied by AVProVideo?

Thank you for the answers.

**Comment by Chris-RH** [comment]
If you want to use the lit shader, then you would have to update it yourself.  The unlit shaders work fine.  We don't really do any work in URP/HDRP so haven't need to make specific shaders for them.  we leave that as an exercise for the programmer who wants to use URP/HDRP.  More info: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@17.0/manual/Upgrading-To-HDRP.html
I don't think that the HDRP/Lit shader would work, but you are welcome to give it a try.
