### ISSUE TITLE
Quest 2 - Live Stream from DaCast

### ISSUE THREAD

**Issue by caksabre** [RenderHeads/UnityPlugin-AVProVideo#1666]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When I use a url which is an mp4 file the AVProVideo works fine to a renderTexture.  But when I try and do a live stream using Dacast and with a url like https://iframe.dacast.com/live/7d0fba31-e2b9-f136-6741-34c2ecb8e6ce/c6b4d5dc-13aa-d0d1-503d-7b3335d0c02c it just gives me a black screen.  I have tried to set the force file format to HLS but it still didn't work.

**Your Setup (please complete the following information):**
 - Unity version: 2023.1.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Trial v2.8.5
 - Operating system version: Quest Pro (android)
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Create a live stream on DaCast
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

<img width="350" alt="Screenshot 2023-10-18 at 15 07 17" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/1992283/5ea6374a-eba3-4d36-9513-03cf7c758540">

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
The URL provided doesn't seem to be active.
Have you been able to get the file to play using any other players on the Quest 2?
Are you able  reproduce this in a fresh project using our mediaplayer demo scene?
Can you provide a full logcat?
Can you provide full specs of the video?

I'm not sure if this will work tbh. I think that you would need to use their player?
