### ISSUE TITLE
Quest2

### ISSUE THREAD

**Issue by andischw12** [RenderHeads/UnityPlugin-AVProVideo#1668]
Problem description:

I purched the android version for only 1 reason, when i downloaded and checked the trial version i got a smooth 360 3D video play, not like the jumpty-at-one-eye 
result i got with the native unity video player. after buying the andoid version and importing it, there is no water mark, but i got the jumpy at 1 eye result!! is this what i  just paid  200$ for ? 
Please help me ASAP

Device (which devices are you having the issue with - model, OS version number):

Quest2

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: v2.8.5 (plugin v2.8.5f1-trial)
Target Platform: Android
Unity: v2023.1.2f1 WindowsEditor
OS: Desktop - System Product Name (ASUS) - Windows 11  (10.0.22621) 64bit - English
CPU: 13th Gen Intel(R) Core(TM) i7-13700K - 24 threads - 65277KB
GPU: NVIDIA GeForce RTX 4090 - NVIDIA - Direct3D 11.0 [level 11.1] - 24156KB - 16384

**Comment by Chris-RH** [comment]
Hi, that doesn't sound right.  The only difference between the trial version and the android core version is that the trial version has a watermark and also supports custom http headers, 360 audio and caching, 

Did you follow the project upgrade steps: https://www.renderheads.com/content/docs/AVProVideo/articles/install.html#upgrade-steps
Can you reproduce the issue in a fresh project using just AVPro and its demo scenes as a guideline?
What are the specs of the video you are using? Are you able to provide a copy?
I'm not sure what you mean by "jumpy at 1 eye" Can you provide a video of what you are seeing?

**Comment by andischw12** [comment]
1. "Jumy at 1 eye" - while moving my head around, the left eye has rendering issues, like "fliking"/"jumpy"/not smooth, while the right eye is rendered smoothly. 
2. i didnt try a blank project yet, i tried 2 methods tho:
A. i delete the entire AVpro trial folder from the Asset folder when unity was closed, and then imported the AVpro android version from the package manager.
B.i tried replacing only the AVproVideo.jar file when importing the package to the project with the trial version.

In both methodes i got the same flickery left eye result similar to what i got using the native unity video player with their 360 tb skybox shader.

And again ! When i discared changes on my git project bringing the original trial AVproVideo.jar back 
Its totaly smooth as it should be.
About the file:

File is h265 360 TB at 120 bitrate. Preety much the maximum the quest2 can handle.

Link to the video file:
https://drive.google.com/file/d/1YX89rxPETMePBtXNcBiVsP02k9paH7RI/view?usp=drivesdk

**Comment by Ste-RH** [comment]
This sounds very strange. But would be extremely surprised if this is down to any difference between the trial and core version. Stereo eye rendering is entirely down setup/influenced at shader and component level.

Could you maybe try a fresh project and our Demo360 scene? You can enable the debug eye rendering option on the shader (AVPro CR inside sphere) to be sure you are seeing left/right eyes correctly. You should get one eye tinted red, and the other green.

Depending on whether you are using Multiview or multi pass, you might need to add the UpdateMultiPassStereo component (https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html) to your camera.

**Comment by Ste-RH** [comment]
One question. Are you using URP?

**Comment by andischw12** [comment]
Hey. In using the build in pipeline.
I fixed the problem by using EOS with Multi Pass and the its special EOS VR shader on the Sphere. Now my playback is smooth as expected.

BUT - this is somthing i did not need to do on the trial version, meaning somthing is or got different between them. Thats a fact. You should test my video on the Quest 2 using both and see for yourself, cus more of this problem would pop in my opinion.

**Comment by Chris-RH** [comment]
OES rendering is not supported in the trial version, so I'm surprised that that is the change that has improved it for you.
