### ISSUE TITLE
flicker on some Android devices

### ISSUE THREAD

**Issue by Bsonic** [RenderHeads/UnityPlugin-AVProVideo#1669]
The video playback flickers intensely on certain Android devices, while functioning normally on other Android devices and iOS devices. What could be the potential causes?

Unity Version: 2020.3.47 URP

**Comment by Chris-RH** [comment]
Are you using OES?
Are you using MSAA?
Which devices is it having issues with?
What are the specs of the video?
When you say playback flickers, do you mean that the playback is stuttering? Is it the whole screen or just part of it?
Can you reproduce this using a fresh project and only AVPro Video demo scene?

**Comment by Chris-RH** [comment]
Its probably down to your URP settings.  By default these are maxed out, so you need to make sure you customise them to suit the android platform.
There are some suggestions in these threads: 
https://www.reddit.com/r/gamedev/comments/ucuxhj/unity_2021_urp_quest_2_stuttering/
https://forum.unity.com/threads/urp-rendering-gibberish-on-old-android-devices.1453210/

**Comment by Chris-RH** [comment]
Closed due to lack of reply

**Comment by Bsonic** [comment]
Yes, this issue has been confirmed to be related to the QualitySettings. We have logically bypassed this issue. Many thanks.
