### ISSUE TITLE
GPU Address fault error on some iOS 17 devices

### ISSUE THREAD

**Issue by iisakovAG** [RenderHeads/UnityPlugin-AVProVideo#1671]
We are noticing that on some iOS 17 devices that when we go into our video scene the app will break but not crash out, and our logs are filled with errors.  

 - Unity version: 2021.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.2, but we tried 2.8.5 as well
 - Operating system version: iOS 17 and up
 - Device model: iPad Pro 12.9" (3rd gen), iPad (9th gen), iPhone 11

**To Reproduce**
1. Open app
2. Navigate to a scene with a AVProVideo media player
3. Errors

**Logs**
We get one of these errors
`2023-10-25 15:39:31.435995-0400 APP_NAME[880:97513] Execution of the command buffer was aborted due to an error during execution. Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault)
2023-10-25 15:39:31.436231-0400 APP_NAME[880:97513] MTLCommandBuffer Encoder state summary:
 Error Domain=MTLCommandBufferErrorDomain Code=3 "Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault)" UserInfo={MTLCommandBufferEncoderInfoErrorKey=(
    "<errorState: MTLCommandEncoderErrorStateCompleted, label: (null), debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateCompleted, label: [R] Render Unlit, debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateFaulted, label: [R] FinalBlit, debugSignposts: (null)>"
), NSLocalizedDescription=Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault), NSUnderlyingError=0x28147be10 {Error Domain=IOGPUCommandQueueErrorDomain Code=11 "(null)"}}`

After the initial error above we get spammed with these errors
`2023-10-25 15:39:31.785293-0400 APP_NAME[880:97513] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (00000004:kIOGPUCommandBufferCallbackErrorSubmissionsIgnored)`

(APP_NAME is just our applications name)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Can this be reproduced in a fresh project running just the AVPro demo scenes?
2. Are those the full error logs?
3. Have you tried different types (resolutions, codecs etc) of videos?

**Comment by iisakovAG** [comment]
We created a fresh project with just the AVProVideo package, and built out the Media Player scene to iOS and are still getting the same errors. I've attached the full error log. 

[avpro-fulllog.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13179070/avpro-fulllog.txt)

Also after some more looking into the issue, right now it seems as the A12 and A13 processors are the ones giving us issues.

**Comment by Chris-RH** [comment]
1. What sort of videos have you tested? codec/container/resolution/fps/bitrate etc
2. Streaming or playing locally?
3. Have you tested with A14+ processors and are they are working as expected?

**Comment by iisakovAG** [comment]
So we tested your demo video which I believe is h.264 mp4 1080p 3632kbps 30fps. Our videos are streamed at h.264 mp4 1080p 5941kbps 12fps. 

After some more testing it looks like it doesn't work on A14 too but it does on A15+. 
We've tested on 17.0.1, 17.0.3, 17.1, and the 17.2 beta

**Comment by iisakovAG** [comment]
Unfortunately even after updating to 2021.3.30f1 and building out the demo scene to an iPhone 10S Max we are still seeing the exact same errors as shown above. We tried 2021.3.31f1 as well but that also did not work. We tried building it with Xcode 14.2, 14.3, and 15.0.1

**Comment by iisakovAG** [comment]
I want to add that you can hear the video's audio, you just can't see the video itself

**Comment by MorrisRH** [comment]
This appears to be tied to something in the MediaPlayer demo scene UI. The DisplayUGUI, ApplyToMesh and ApplyToMaterial components work fine. It would be great if you could confirm this on the iPhone 10s or XR.

I'm currently trying to narrow down which aspect of the media player demo scene is triggering the issue.

**Comment by MorrisRH** [comment]
It looks like the audio spectrum visualisation is the culprit.

Disable the game object in the Demo_MediaPlayer scene as shown here:

![Screenshot 2023-11-01 at 12 41 51](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/cfb88571-b34e-4066-8c26-aa0b8a593360)

 and comment out line 739 of `MediaPlayerUI.cs` so it looks like this:
```csharp
			// UpdateAudioSpectrum();
```

**Comment by MorrisRH** [comment]
We've disabled the spectrum visualiser on iOS for the time being. This will make it into the next release.

**Comment by iisakovAG** [comment]
That fixed the issue for us! Thank you for the quick responses and help!

**Comment by Chris-RH** [comment]
Hi @aryansaurav, 

Please could you start a new issue for this with more details about your issue.
