### ISSUE TITLE
Unable to trigger MediaPlayer Play/Stop reliably from code.

### ISSUE THREAD

**Issue by secondpathstudio** [RenderHeads/UnityPlugin-AVProVideo#1673]
**Describe the issue**
Media player not loading and playing videos reliably.

Is it possible to start the Media Player without a loaded MediaReference (I get an error if I load without one)? If I do this and ignore the error I am able to load a new MediaReference while in play mode but it never plays. The only way to toggle on/off playing multiple clips is to have a pre-loaded MediaReference that loads when I start, but I have to cover the UGUI with a separate image to fake nothing being loaded...am I missing something?

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.10f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core 2.8.5
 - Operating system version: Windows 11, RTX 4090
 - Device model: Unity Editor, building for Android
 - Video specs (resolution, frame-rate, codec, file size):  h264

**Logs**
No logs this is just unity editor not getting any errors at all.

**Comment by Chris-RH** [comment]
What code are you using to open, play and stop the video?
