### ISSUE TITLE
Some sounds are always played on Android even though video is not played.

### ISSUE THREAD

**Issue by companyofpotato** [RenderHeads/UnityPlugin-AVProVideo#1679]
**Describe the issue**
When I open video on AOS, it always play sound at the beginning of video even though video is not played.
This reproduces whether I change video mute to true before/after open video.

I suspect that ApplyAudioSettings() of AudioOutput is called in Update() might be the cause of this.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.48f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.7.3 ultra
 - Operating system version: Android 10, 13
 - Device model: Galaxy S9, S10, Z Flip3
 - Video specs (resolution, frame-rate, codec, file size): 1280x720

**To Reproduce**
1. Use ApplyToMaterial to play video on material
2. Set MediaPlayer's PlatformOptionsAndroid.audioOutput as Android.AudioOutput.Unity
3. Set MediaPlayer to Player of AudioOutput
4. Call OpenMedia with video URL (set autoPlay false)

If I skip 2, 3, it isn't reproduced.

**Logs**
sounds play on 11hour 7 min 41s ~ 42s
[AOSSound41s42s.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13246942/AOSSound41s42s.txt)

**Videos**
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/30142311/6f4e63db-1e1a-4402-967a-09f5d780215b

**Comment by companyofpotato** [comment]
It also reproduces in Demo Scene of 2.9.0 ultra.

**Comment by Ste-RH** [comment]
Are you, or can you reproduce this in our Demo_MediaPlayer?  I have just tried here and cannot reproduce what you outline as the issue.

**Comment by Ste-RH** [comment]
I have tried, and failed to reproduce this here.  I wonder if there is anything you have set-up that specifically makes it happen?  Are you calling open/play from a script?  Does it happen on a first time clean/fresh app load?

**Comment by companyofpotato** [comment]
I just open video from a script but not play.

In Demo_MediaPlayer Scene, I added empty gameobject and attached test script to it.
After assigning 'MediaPlayer' object to 'Media Player' property of script, I played to see it works on editor.
Next, I built the scene on Android platform and installed apk in device.
Every time I open the app, it always play sound at the beginning of video.

This is test script I used.
[TestScript.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13274469/TestScript.zip)

**Comment by Ste-RH** [comment]
Ok, yeah.  Reproduced here now.  I think we have a fix for it.  We will roll this out into the next update.  If you require this sooner, then if you email your Unity Asset Store invoice PDF over unitysupport@renderheads.com then I can send you over a v2.9.0f2 fix set of plugins.  Just mark the subject with 'Github #1679'

**Comment by companyofpotato** [comment]
It isn't reproduced in 2.9.0 f2 in demo scene and our application. Thank you!

**Comment by Chris-RH** [comment]
Awesome, that's great news :)

**Comment by Chris-RH** [comment]
AVPro Video version 2.9.1 has been released.  Please let us know if your issue has not been fixed.

**Comment by companyofpotato** [comment]
It is not reproduced in 2.9.1 Thank you.

**Comment by Chris-RH** [comment]
Awesome,  thank you for letting us know 😀
