### ISSUE TITLE
need metadata callback implementation

### ISSUE THREAD

**Issue by tufeixp** [RenderHeads/UnityPlugin-AVProVideo#168]
with GetMediaDescription or GetVideoDescription commented out in IMediaInfo.

 I need to read all metadata from video/photo, please implement them, thanks.

**Comment by AndrewRH** [comment]
What sort of metadata do you need exactly?

**Comment by tufeixp** [comment]
eg. 360/180 media description, Exif information for Photos.

**Comment by AndrewRH** [comment]
Closing this due to vague requirements.  Also in Version 2.x now we have a much better system with multi-track API and can also query whether a video is stereo or not.  Currently though 180/360 data is not handled.
