### ISSUE TITLE
How to decrypt mp4 encrypted by drm-clearkey

### ISSUE THREAD

**Issue by SidneyZhou** [RenderHeads/UnityPlugin-AVProVideo#1680]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Get error when play encrypted mp4:

`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.5f1-ultra
 - Operating system version: windows10
 - Video specs (resolution, frame-rate, codec, file size): Cones-360Mono-4K30-H264.mp4

**To Reproduce**
1. I want to put a encrypted mp4 in my project, so i use following command:

`mp4box -crypt drm-clearkey.xml C:\UnityProj\SteamVRPCPlayer\Assets\StreamingAssets\AVProVideoSamples\Cones-360Mono-4K30-H264.mp4 -out a_encrypted_360Mono.mp4`

drm-clearkey.xml:
```
<GPACDRM type="CENC AES-CTR">
<DRMInfo type="pssh" version="1">
<BS ID128="1077efecc0b24d02ace33c1e52e2fb4b"/>
<BS bits="32" value="1"/>
<BS ID128="0123456789abcdef0123456789abcdef"/>
</DRMInfo>
<CrypTrack IV_size="8" first_IV="0x1122334455667788" isEncrypted="1" saiSavedBox="senc" trackID="1">
<key KID="0x0123456789abcdef0123456789abcdef" value="0x00112233445566778899aabbccddeeff"/>
</CrypTrack>
</GPACDRM>
```

2. I can use ffplay to watch it:

`ffplay -decryption_key 00112233445566778899aabbccddeeff .\a_encrypted_360Mono.mp4`

3. I use following code, can't play:
```
var bytes = StringToByteArray("00112233445566778899aabbccddeeff");
Debug.Log($"Base64Key: {System.Convert.ToBase64String(bytes)}"); // Base64Key: ABEiM0RVZneImaq7zN3u/w==
_controlInterface.SetOverrideDecryptionKey(bytes);
```

**Logs**
`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by SidneyZhou** [comment]
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11409038/f338639d-282f-42c4-b28c-5dc9ebb00622)

**Comment by Chris-RH** [comment]
Sorry but this feature is for HLS (m3u8) streams only, not MP4 files. You can read more about it here:
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html#hls-aes-128-encrypted-playback
