### ISSUE TITLE
m4a over http oddity

### ISSUE THREAD

**Issue by drew-512** [RenderHeads/UnityPlugin-AVProVideo#1683]
Hi AVPro friends,

Our project is coming along and I'm excited to play show and tell before long to pump up the AVPro team.

Currently trying to resolve an issue when playing m4a files.  The files play fine via local file path, and they play fine from an http response from an apache server serving those files.  However when we serve those files over a different http server that we deploy with our product, we get the AVPro error:

`Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

Maybe AVPro is looking for a special header?   These headers are from the server that AVPro plays fine:
```
lightning:~ aomeara$ curl --insecure -I https://plan-systems.org/plan-3d/running.m4a
HTTP/2 200 
last-modified: Tue, 07 Nov 2023 00:24:08 GMT
accept-ranges: bytes
content-length: 6368821
cache-control: max-age=31536000
expires: Wed, 06 Nov 2024 00:41:28 GMT
host-header: c2hhcmVkLmJsdWVob3N0LmNvbQ==
referrer-policy: no-referrer-when-downgrade
x-endurance-cache-level: 0
x-nginx-cache: WordPress
content-type: audio/mpeg
date: Tue, 07 Nov 2023 00:41:28 GMT
server: Apache
```

The headers for our asset http server that AVPro errors on:
```
lightning:~ aomeara$ curl --insecure -I http://localhost:61984/asset/miQ0qtLW7YbNXO6rvqacg5Rq3W96
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 6368821
Content-Type: audio/mpeg
Date: Tue, 07 Nov 2023 00:42:44 GMT
```

Note: AVPro plays mp3 assets from the troubled asset server just fine, so I'm scratching my head on what about serving m4a files specifically from server causes AVPro to error out.  As a sanity check, I can open the URL that AVPro errors on in any local browser and no issues playing.  

- Unity 2022.3.12
- macOS 10.14.6
- Mac Pro 2013
- AVPro 2.9.0

Thanks,
Drew

**Comment by MorrisRH** [comment]
It's likely the lack of file extension on the second url is why it's not playing for you. Another possibility is the content-type header, it should be audio/mp4 for m4a files iirc.

**Comment by drew-512** [comment]
Hi Morris!  Yes, it was the lack of .mp4 extension.

Thanks and looking forward to showing y'all this!
