### ISSUE TITLE
No sound  with bluetooth when Unity output on Android

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1684]
- Unity version: 2020.3.48f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.0 Ultra
 - Operating system version: OS 13
 - Device model: **Galaxy S22+, Galaxy buds2**

No sound  with bluetooth when Unity output on Android

I tested Demo_MediaPlayer scene.
Set the AudioOutput component and changed the AudioOutput to Unity.
When playing video on speakerphone, there is no sound when connected to the Bluetooth headset.

If you test it in the demo scene, you can reproduce it right away.

**Comment by Ste-RH** [comment]
Have you tried another device and/or other headphones?  I have just tested here using some generic bluetooth headphones paired to a Xiaomi Mi10T and it works exactly as one would expect.

Do you know the samplerate that is set when using your headphones?  Maybe this is a resampling bug (if they are not 48KHz - I have seen headphones that set the system to 22.5KHz in the past).

**Comment by dw8869** [comment]
All I have is AirPods and Galaxy Buds 2.
This devices sample rate is 44100.
Can you solve this problem?

If you experience a problem during the Bluetooth connection process, the problem occurs even after you disable Bluetooth.
Unless you run the app again, the problem cannot be resolved.

**Comment by Chris-RH** [comment]
It could be that.  Have you tested using audio with the same sample rate?

Could you send us a full, unfiltered logcat please :)

**Comment by dw8869** [comment]
I don't have another Bluetooth device.
Here is Samsung 22+/Android 13 log.
[logs.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13307927/logs.txt)

I will test it on other devices and the OS and deliver additional logs.

**Comment by dw8869** [comment]
Problems also occur with Galaxy S10 5G / Android 12.
[logs2.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13308065/logs2.txt)

**Comment by Ste-RH** [comment]
Nothing looks odd in those logs :/

I wonder, can you log out [AudioConfiguration](https://docs.unity3d.com/ScriptReference/AudioConfiguration.html).sampleRate

...when you have the headphones connected, and also when you don't...and report back the values you get?

**Comment by dw8869** [comment]
@Ste-RH 
Ok, I tried it, but the sample rate is not changing.
You can find it by looking at the log `Current AudioSettings.outputSampleRate`

[logs3.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13318911/logs3.txt)
The first log is before Bluetooth connection.
The second log is after a Bluetooth connection.
The third log is after the Bluetooth disconnect.

**Comment by Ste-RH** [comment]
Ok, good to know.

Do you get the problem if you use sample video (RenderHeads-1080p30-H264.mp4) ?

**Comment by dw8869** [comment]
@Ste-RH 
Yes, there is no problem with other applications.

The same problem is occurring with the sample video that you informed me.
And I just found out that when there's no sound, Pause-Play comes out the sound.

**Comment by Ste-RH** [comment]
I am a little lost here.  Are you saying you never get audio into your bluetooth headphones?  Or only after an issue occurs pairing them?

**Comment by dw8869** [comment]
@Ste-RH 
First, if you play a video without Bluetooth, the speakerphone will ring.
And when you connect Bluetooth, there is no sound from Bluetooth.

**Comment by Ste-RH** [comment]
And if you re-run the app after bluetooth has been enabled and the headphones connected?

**Comment by dw8869** [comment]
@Ste-RH 
If you're already connected to Bluetooth when running the app, there's no problem. comes out the sound.

**Comment by dw8869** [comment]
@Ste-RH 
Can I get the solved issue version from the next version?

**Comment by dw8869** [comment]
@Ste-RH 
any update?

**Comment by dw8869** [comment]
@Chris-RH 
Do you have any updates on this issue?

**Comment by Chris-RH** [comment]
no update as of yet

**Comment by dw8869** [comment]
@Chris-RH 
Is it in progress? I hope it will be fixed in the next version.

**Comment by dw8869** [comment]
@Chris-RH 

@Ste-RH  has been 3 weeks, but there is no answer.
Why?

This problem is adversely affecting our service, and we need to fix it.
I'd like to know the progress.

**Comment by Ste-RH** [comment]
Additional:

Something like this appears to work:

		void OnAudioConfigurationChanged(bool deviceChanged)
		{
			if (_mediaPlayer == null || _mediaPlayer.Control == null)
				return;
			_mediaPlayer.Control.AudioConfigurationChanged(deviceChanged);

			double currentTime = _mediaPlayer.Control.GetCurrentTime();
			_mediaPlayer.Control.CloseMedia();
			_mediaPlayer.OpenMedia( _mediaPlayer.MediaReference, true );
			_mediaPlayer.Control.Seek( currentTime );
		}

You might want to check/set pause as well, depending on your use-case.

**Comment by dw8869** [comment]
```c#
void OnAudioConfigurationChanged(bool deviceChanged)
{
	if (_mediaPlayer == null || _mediaPlayer.Control == null)
		return;
	_mediaPlayer.Control.AudioConfigurationChanged(deviceChanged);

	double currentTime = _mediaPlayer.Control.GetCurrentTime();
	_mediaPlayer.Control.CloseMedia();
	_mediaPlayer.OpenMedia( _mediaPlayer.MediaReference, true );
	_mediaPlayer.Control.Seek( currentTime );
}
``` 
@Ste-RH 
so.. I solved the issue with the code you told me, but there was a side effect issue.
When the player plays again, the audio is output later than the video and is out of sync.

I think the early return of the `RequestAudio` function of the `AudioOutputManager` class has an impact.
```c#
public void RequestAudio(AudioOutput outputComponent, MediaPlayer mediaPlayer, float[] audioData, int audioChannelCount, int channelMask, AudioOutput.AudioOutputMode audioOutputMode, bool supportPositionalAudio)
{
	if (mediaPlayer == null || mediaPlayer.Control == null)
	{
		if (supportPositionalAudio)
		{
			ZeroAudio(audioData, 0);
		}
		return;
	}
```

I think we can just remove the buffered audio, is there a way?
