### ISSUE TITLE
Wrong vertical size of video detected on certain Windows machines

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#1686]
When playing a transparent video on one Windows machine (in the Netherlands), the video appears correctly, correct scale and AVPro logs correctly:
[AVProVideo] Using playback path: DirectShow (1920x1920@25.00)
[AVProVideo] Opening D:/SomeFolder/1_1.mp4 (offset 0) with API DirectShow

On the other Windows machine (in Italy), the same video is squashed vertically, and AVPro logs this:
[AVProVideo] Using playback path: DirectShow (1920x480@25.00)
[AVProVideo] Opening D:/SomeFolder/1_1.mp4 (offset 0) with API DirectShow

What can cause this and how to fix it? I've noted the country in case this may have anything to do with regional settings.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.24f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.8.2
 - Operating system version: Windows 10 Pro (correct) and Windows 11 (wrong vertical size)
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): Alpha packed MP4, 1920x1920 , H264, 25fps, MPEG AAC Audio, 48kHz, 32 bps.

**To Reproduce**
I've sent the video via email

**Comment by Chris-RH** [comment]
Yeah, it could be a codec issue.  
You should get a better result using Media Foundation.
