### ISSUE TITLE
About MPEG-DASH in Unity.

### ISSUE THREAD

**Issue by YHLee23232323** [RenderHeads/UnityPlugin-AVProVideo#1688]
I am looking for a solution support for MPEG-DASH in Unity.
I have several 360 videos in hand for you to review, the only issue being they are of different quality, and were split by kvazaar, packed by GPAC and dashed into one .mpd file and several .m4s files.
Can AVProVideo reads .mpd file and pick the corresponding .m4s files for streaming, is it ok that I add in my own algorithm to choose which .m4s files it picks? 
Any advice will be appreciated!

**Comment by Chris-RH** [comment]
It should work.
We have a free, fully featured trial version available for you to test with: https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases
More info on streaming here: https://renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html
