### ISSUE TITLE
MacOS 10.15 Beta 7 issues?

### ISSUE THREAD

**Issue by paatz04** [RenderHeads/UnityPlugin-AVProVideo#169]
Sometimes videos do not play on macOS 10.15 Catalina Beta 7
Is there a known bug ? This is the last issue blocking our release.

 - Unity version: 2019.2.3
 - AVPro Video version: 1.10
 - Operating system version: macOS 10.15 Beta 7
 - Device model: Macbook Pro 15"
 - Video specs (resolution, frame-rate, codec, file size): 25-30fps mp4 h264

Trying to see if I can get some logs now.

**Comment by paatz04** [comment]
I'm getting all the normal events, including Started, and "pausing  video", "playing video again" - but nothing is visible and FinishedPlaying is never fired.

**Comment by paatz04** [comment]
Whenever it works I'm getting Event: MetaDataReady, Event: Started, Event: FirstFrameReady, Event: ResolutionChanged, Event: Finished Playing

Whenever it doesn't work I'm getting no Events at all, and no errors. (Unless I tab out and back in then it triggers Started (pausing, playing again) but doesn't actually play the video.

**Comment by AndrewRH** [comment]
Hmmm, Do you have to support a beta version of macOS for release?

**Comment by paatz04** [comment]
No but 10.15 will release soon - and we will be launching exclusively on macOS 10.15+

**Comment by AndrewRH** [comment]
We've had issue before where beta versions of macOS break video playback.  Please keep an eye on it - if the issue is still there in the RC (release candidate version) then we'll be able to take a look.

**Comment by paatz04** [comment]
I've yet to check. In the meantime I had to refactor code and not use the player.
