### ISSUE TITLE
AVPro Loading Media Reference Help

### ISSUE THREAD

**Issue by gdedi001** [RenderHeads/UnityPlugin-AVProVideo#1690]
Problem description:

Hi, 

Currently in my project I have a media player and at runtime the user can choose a video to watch by clicking an icon and loading a new media reference on the media player. When doing so, the media player will start the new video and play at 0:00. I'm looking for any new video to continue playing at the exact timestamp the previous video was at without restarting at 0:00. 

What I want to happen
1. Video A starts playing
2. At 1:15 on Video A the user chooses Video B to play
3. Video B starts at 1:15 and continues playing

This is the code I have 

```
public void ChangeSourceReference(MediaReference reference)
    {
        double when = mediaplayer.Control.GetCurrentTime();
        mediaplayer.OpenMedia(reference, autoPlay:false); // opens video and starts at 0:00 - not what I want to happen...
        mediaplayer.Control.Seek(when);
        mediaplayer.Control.Play();
    }
```

Device (which devices are you having the issue with - model, OS version number):

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1280x1088 @ 60

System Information:

AVPro Video: v2.8.0 (plugin v2.8.0f1-ultra)
Target Platform: Android
Unity: v2021.3.20f1 WindowsEditor

**Comment by Chris-RH** [comment]
Firstly, for best results, ensure your videos are encoded for fast seeking.
https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html#fast-seeking
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-seeking-playbackrate.html

What is the exact problem that you are having?

**Comment by gdedi001** [comment]
Thanks for the quick reply @Chris-RH! Fast seeking seems to work, but my videos still start at 0:00 when loaded via the media reference. Ideally I would new videos to start at the exact timestamp that previous video was at. I found this issue from another dev and it seems this is the functionality I'm also trying to accomplish. Any additional insights?

https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1470

**Comment by gdedi001** [comment]
Thanks for the quick reply @Chris-RH! Fast seeking seems to work, but my videos still start at 0:00 when loaded via the media reference. Ideally I would new videos to start at the exact timestamp that previous video was at. I found this issue from another dev and it seems this is the functionality I'm also trying to accomplish. Any additional insights?

https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1470

**Comment by Chris-RH** [comment]
Has the snippet in #1470 helped?

**Comment by gdedi001** [comment]
Hi @Chris-RH seems so thanks
