### ISSUE TITLE
Device Resource Management when Switching Videos

### ISSUE THREAD

**Issue by allused-really** [RenderHeads/UnityPlugin-AVProVideo#1691]
**Question**

I am working with AVPro Core (v2.8.5), Unity 2022.2 and deploying to Pico VR headsets (Android-based). We have a single AVPro video player instance playing high-resolution (~8K) 360-degree video. User action can stop the playback of the current video and trigger the load/playback of another video. We see a big jump in device resource usage (GPU, memory) when switching between videos, even though we stop the player / close the media for Video A before triggering the open media / play for Video B. Occasionally, this is severe enough to cause the app to be terminated on the device.

Are there any other resource management / optimisation techniques that you can suggest? Am I correct in assuming that AVPro optimises the management of the video Material (and associated Texture) internally? Currently, the Media Player is supplied with a Material based on the AVPro Skybox/Sphere shader and an Apply To Material component associates the Media Player with the Material.

**Comment by Chris-RH** [comment]
1. Which Pico device(s) are you using?
2. What are the specs of the videos? (resolution, codec, FPS, bitrate, stereo/mono etc)
3. Are you using Exoplayer or Android Mediaplayer API?
4. Are you using OES shaders?
5. Have you tried using our Playlist feature?
6. Is this reproducible in a new project using just the AVPro Video 360 demo scene and your videos?
7. Have you tried flushing the garbage collection and resources when you close a video using GC.Collect(); and Resources.UnloadUnusedAssets();?
8. Can you provide a full logcat?

**Comment by allused-really** [comment]
Thanks Chris -  answers follow below. I'd be grateful for your comments. I'll also gather the other logs, etc that you asked for and post them back here.

1. Which Pico device(s) are you using?
Pico G3 headset 

2. What are the specs of the videos? (resolution, codec, FPS, bitrate, stereo/mono etc)
7680 x 3840, H.264, 30 fps, bitrate 30-60Mbps, mono (all played from local storage, no streaming!)

3. Are you using Exoplayer or Android Mediaplayer API?
Exoplayer

4. Are you using OES shaders?
Not currently. The supplied OES shaders all seem to assume stereo packed video - how do I use/create an OES shader for mono 360-degree video? Is it OK to use the supplied "stereo" OES shader with its "Stereo Mode" property set to "None" and with the "Automatic Stereo Packing" property of the ApplyToMesh component unchecked? 

5. Have you tried using our Playlist feature?
No. The AVProVideo documentation states:
"When playing very high resolution videos (eg in VR), this component may not work on mobile systems as they usually have limited hardware video decoders and memory and this component requires two videos to be in memory at once."
Given the problems that we are having, introducing more resources didn't seem like a good approach.

6. Is this reproducible in a new project using just the AVPro Video 360 demo scene and your videos?
We haven't been able to generate an on-device crash/termination when using the AVPro Video 360 demo scene by itself.

7. Have you tried flushing the garbage collection and resources when you close a video using GC.Collect(); and Resources.UnloadUnusedAssets();?
Not yet, but we can try that and report back.

8. Can you provide a full logcat?
I don't have a logcat output to hand, but I'll obtain one and post it to this thread.

**Comment by allused-really** [comment]
Chris, I've discovered that that this issue was being triggered by a subtle bug in the version of Unity that we were using (2022.2.14). Updating Unity to 2022.3 seems to have cured the problem - at least, we have tested for many hours with no repeat of the excessive resource usage and occasional crash! I'm happy to close the issue but, before you do, I was wondering if you could respond to Question 4 in my message above? We may want to move to OES shaders in the future and it would be good to know what changes are required for mono 360-degree video rather than stereo.

**Comment by Chris-RH** [comment]
Ahh, Unity version bugs are annoying! I'm glad you've worked that out.

You should be able to use VR-InsideSphere-AndroidOES for monoscopic videos
(https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1342)
