### ISSUE TITLE
Crashes with the error java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.reset()' on a null object reference

### ISSUE THREAD

**Issue by YousukeSato** [RenderHeads/UnityPlugin-AVProVideo#1694]
**Describe the issue**
We recently purchased the AVPro Video plugin to install it in our application for the purpose of having the mp4 video playable in the app.
After releasing the updates with this plugin running, we had several reports from users that the application crushes on specific devices.
 
The crashing issue was reproduced during bug inspection on our test devices, and it was caused when the AVPro plugin required reset processing.

While we found the cause of the crush issue, we are unable to specify the reason why this issue occurs only in specific devices. We have many reports, especially from Samsung devices.
Please advise the resolution if you are aware of this issue. Thank you in advance.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.42f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): core2.8.5
 - Operating system version: Android 13
 - Device model: GalaxyTab A8 SM-X200
 - Video specs (resolution, frame-rate, codec, file size): 1920 x 1200 ,60 fps, H264

**Logs**
2023/11/21 10:20:39.426 4927 6258 Error AndroidRuntime FATAL EXCEPTION: Thread-10976
2023/11/21 10:20:39.426 4927 6258 Error AndroidRuntime Process:com.YourCompanyName.YourProductName, PID: 4927
2023/11/21 10:20:39.426 4927 6258 Error AndroidRuntime java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.reset()' on a null object reference
2023/11/21 10:20:39.426 4927 6258 Error AndroidRuntime 	at com.renderheads.AVPro.Video.Player_MediaPlayer$1.run(Player_MediaPlayer.java:1)
2023/11/21 10:20:39.426 4927 6258 Error AndroidRuntime 	at java.lang.Thread.run(Thread.java:1012)
2023/11/21 10:20:39.439 4927 6259 Error AndroidRuntime FATAL EXCEPTION: Thread-10978
2023/11/21 10:20:39.439 4927 6259 Error AndroidRuntime Process: com.YourCompanyName.YourProductName, PID: 4927
2023/11/21 10:20:39.439 4927 6259 Error AndroidRuntime java.lang.IllegalStateException
2023/11/21 10:20:39.439 4927 6259 Error AndroidRuntime 	at android.media.MediaPlayer._reset(Native Method)
2023/11/21 10:20:39.439 4927 6259 Error AndroidRuntime 	at android.media.MediaPlayer.reset(MediaPlayer.java:2444)
2023/11/21 10:20:39.439 4927 6259 Error AndroidRuntime 	at com.renderheads.AVPro.Video.Player_MediaPlayer$1.run(Player_MediaPlayer.java:1)
2023/11/21 10:20:39.439 4927 6259 Error AndroidRuntime 	at java.lang.Thread.run(Thread.java:1012)

**Screenshots**
![スクリーンショット 2023-11-21 12 49 41](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/14085076/0599b9c5-ce18-44fb-a98f-d67f295371d9)

**Comment by Chris-RH** [comment]
1. Are you streaming or playing local videos?
2. What are the full specs of the videos are you using?
3. Are you using any other audio/video players?
4. Does it occur when playing one specific video? All of your videos? Does it sometimes crash with a video and sometime not?
5. Can you repeat this using a fresh project, only running AVPro mediaplayer demo and your video?
6. Are you using flutter? Adverts?
7. Which android devices are you having an issue with and which are not having this issue?  Are they all the same android version?
8. What are you doing before the crash?
9. Are you calling open or close on anything but the main thread, or maybe from the AVPro Video events system?
10. Can you provide a full logcat as a txt file please

**Comment by YousukeSato** [comment]
1.Are you streaming or playing local videos?
We are playing a local video.
The app downloads the video from the server at the time the game starts and plays it locally.

2.What are the full specs of the videos are you using?
The following are the specs of the video.
- video1 size:1920x1080,H.264 ,1.1MB
- video2 size:1280x720,MPEG-4 AAC ,H.264 923KB
The crashing issue occurs not only when the video is playing, but also when the video was downloaded and waiting to play.

3. Are you using any other audio/video players?
Yes. Our application provides the service for playing darts at home. One of the services is an online match, which you can enjoy video chat using webRTC. That’s the first video truck, and secondly, AVPro is being used for the effect during the game.

4. Does it occur when playing one specific video? All of your videos? Does it sometimes crash with a video and sometime not?
The crashing issue may occur even when the video is not being played.
At the end of the online match, the reset of AVPro Video proceeds, and it seems this process triggers the crash.
 
5. Can you repeat this using a fresh project, only running AVPro media player demo and your video?
AV Pro Video plugin is running for local match as well, and local match does not have webRTC running. This crash issue does not occur in local matches. It may be difficult to repeat the issue by building a fresh project.

6.Are you using flutter? Adverts?
No flutter and adverts in our application.

7.Which android devices are you having an issue with and which are not having this issue? Are they all the same android version?
Our test Android devices are:
- GalaxyTab A8 SM-X200 Android 13.
- OPPO AX7 Android 8.1.0
- Pixel 4a Android 13
The issue occurs with GalaxyTab A8 SM-X200 Android 13.
According to the user report, the issue occurs with the following devices as well.
- samsung SM-G781U Android 13
- samsung SM-S908B Android 12

8.What are you doing before the crash?
Once the game ends, the screen transitions from game to result. At that moment, the app resets the data that was being used during the game. The crash occurs between these transactions.
We may show you the screen recording where the issue occurring, if necessary.

9.Are you calling open or close on anything but the main thread, or maybe from the AVPro Video events system?
We are calling only from the main thread. When you say “AVPro Video events system”, what exactly you are referring to?

10.Could you please provide us with the complete logical in txt file?
[AppclashLog.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13434903/AppclashLog.txt)

**Comment by Chris-RH** [comment]
Are you able to send us a simple reproducible test project to unitysupport@renderheads.com please?

**Comment by Chris-RH** [comment]
Please could you email us the PDF of your invoice from Unity Asset Store to unitysupport@renderheads.com and we can send you a build to test/use until our next version is released.

**Comment by Chris-RH** [comment]
AVPro Video version 2.9.1 has been released.  Please let us know if your issue has not been fixed.

**Comment by YutaMiura** [comment]
Hi, I'm working on same team with Sato.
I have been assigned to fix this problem.

This problem still occured using new version.

So, Can I question about logs that attached?

It has said relased ExoPlayerImpl In 14151 row, and also it has said called reset() in 14154 rows from thread.

I think The thread that called reset() still running after release ExoPlayer.

Can you tell me what is trigger for release ExoPlayerImpl?
and also What do  the thread that called reset() do?
Do you have any idea what method called this thread?

**Comment by Ste-RH** [comment]
The crash you reported was happening when running the MediaPlayer API, not ExoPlayer.

The thread that calls the Reset() was firing after a clean up had happened and the pointer was null.  A safety check was added around the Reset() call.  We reproduced it here, then with the fix, the crash no longer happened.

**Comment by YutaMiura** [comment]
@Ste-RH 
How do you reproduced it?
We still gets same error with new version on specific device.
Do you think If CloseMedia calls after Disposed it might gets same error?

**Comment by Ste-RH** [comment]
That is how I was seeing it happen.

Dispose will close the media as part of it's process.
