### ISSUE TITLE
Audio no longer plays when toggling an object's active state.

### ISSUE THREAD

**Issue by YonahaShota** [RenderHeads/UnityPlugin-AVProVideo#1695]
**Describe the issue**
A clear and concise description of what the issue 

I upgraded the plugin version from 2.1.8 to 2.9.0 due to the following issue.
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1653
When creating an object with the following structure and activating the MediaPlayer object with SetActive from 'deactive' to 'active,' the video plays correctly, but there is no audio playback.

・MediaPlayer               ・・・ Attached Components [ Media Player, Audio Output, Audio Source ]
・・Canvas
・・・ Display_uGUI　 ・・・ Attached Components [Display uGUI]

This issue did not occur when using 2.1.8, but now occurs after upgrading to 2.9.0.

When I installed the plug-in in an empty project and checked the settings in the Demo scene, I found that it plays normally when Audio Source's PlayOnAwake is TRUE, but this problem occurs when it is FALSE.

Were there any changes in behavior related to this PlayOnAwake between 2.1.8 and 2.9.0?

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.38f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.0/core
 - Operating system version: iOS14+ ,Android 9+ 
 - Device model: iPhone11pro,iPhone12,iPhone13pro/Pixel3a,Pixel4a(5G),Xperia_XZ1_701SO
 - Video specs (resolution, frame-rate, codec, file size): 1800x1000, 30 fps, H.264 + AAC audio, 7.7 MB
 -- You can also reproduce it with a sample video

**To Reproduce**
1. Set audio mode to Unity
2. Uncheck PlayOnAwake for AudioSource
3. Play Video
4. Disable the GameObject to which AudioSource is attached with SetActive(false)
5. Enable the GameObject to which AudioSource is attached with SetActive(true)
6. Audio will no longer play

**Comment by MorrisRH** [comment]
This is Unity's standard behaviour. You need to call Play on an AudioSource for it start playing if PlayOnAwake hasn't been enabled. Explicitly calling Play on the audio source when setting the game object active works fine.
