### ISSUE TITLE
Not getting seek events

### ISSUE THREAD

**Issue by mad284** [RenderHeads/UnityPlugin-AVProVideo#1696]
** My Issue **
Hello.  I just started using the trial and I've been able to load and play video so far.  I am trying to do some more advanced seek operations now.  I am calling SeekToFrame(), and this appears to seek correctly to the spot, but I never see the events firing for this. 

According to the documentation, I think I should get FinishedSeeking fired once the seek completes.  In the Unity Inspector, Triggered Events is set to Everything.  And in the Start() method of my behavior, I am calling _videoPlayer.Events.AddListener( HandleMediaPlayerEvent );

If I put a log call in HandleMediaPlayerEvent(), I do see other events, so I'm pretty sure I subscribed properly.

The video is paused while I call SeekToFrame(), but I also tried playing the video and still don't see the seek events.

** My Setup **
 - 2022.1.24f1
 - UnityPlugin-AVProVideo-v2.9.0-Trial 
 - Windows 10 
 - HEVC video 1920x1080 @ 30 FPS

** To Reproduce **
1. Subscribe to the event handler.
2. Call OpenMedia().
3. Wait for FirstFrameReady event.
4. Call Pause().
5. Call SeekToFrame( frame ).

**Comment by mad284** [comment]
Digging deeper, I noticed that if I call SeekToFrame( 100 ) and then immediately call GetCurrentTimeFrames(), this returns 100.  So maybe it is just expected behavior that you ONLY get the seek start/finish events when the seeking doesn't occur immediately?

**Comment by Fl0biwan** [comment]
Hello, are there any news about this issue? I'm encountering the same problem when using DirectShow. It works with Media Foundation.
