### ISSUE TITLE
Stream a tiled HEVC

### ISSUE THREAD

**Issue by YHLee23232323** [RenderHeads/UnityPlugin-AVProVideo#1697]
My Setup:
 - Unity version: 2022.3.6f1
 - AVPro Video version : v2.9.0 (trial) 
 - Operating system version: Win10 22H2
 - Device model:  CPU 13th Gen Intel(R) Core(TM) i5-13500
                             RAM	64.0 GB 
                             GPU NVIDIA GeForce RTX 4070
 - Video specs (resolution: 3840*1920, frame-rate: 30 fps, codec: HEVC ) 

My issue: 
I'm trying to stream a tiled HEVC streams (hvt1 or hvt2 in ISOBMFF).
When I loaded the MPD file from my sever ,the Media Info said  "No media loaded", but the preview window showed me the video duration and that is correct.
It hit me that could video codec mismatch?
So I repeat the same steps at VLC Media player, it said that VLC didn't support the format hvc2 and hvt1.

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/149464349/6cd6c0a5-3b4e-4efe-be44-5e46d863f4e9)

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/149464349/874ad519-0a6e-433e-9759-a89811a459e2)

I have no idea to fix it.
Any advice will be appreciated!

BTW,  when I stream a HEVC streams without tiled by kvazaar.
AVPro worked well.

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/149464349/cddfc362-171d-44a0-b4ed-dd76b3c2db6f)

 I've attached the MPD files and .m4s segments here:
https://drive.google.com/drive/folders/1Ecd43N8Hz9rPgTYW1e7O0XxWQmbtey8b?usp=sharing

**Comment by Chris-RH** [comment]
Hi, we don't support tiled HEVC and are unlikely to do so until there is platform support for it.
