### ISSUE TITLE
I can't open rtsp video.

### ISSUE THREAD

**Issue by Dev-MinSeok** [RenderHeads/UnityPlugin-AVProVideo#1699]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I Can't open rtsp video.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.27f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): core
 - Operating system version: windows 10 64
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 
1280*720
**To Reproduce**
1. 
2. 
3. 

**Logs**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/145748417/a24d790f-4fbf-40aa-b9c8-546e12ccc54d)

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/145748417/d810e8f2-ccdc-4220-964a-c880f88fcb2e)

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/145748417/b94e619a-bb32-4dcb-a020-2cd38509377c)

**Videos**
I send email to you.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
AVPro Video doesn't have strong support for real-time streaming formats as they are not the focus of this plugin and most operating systems do not have good native support for them.  More info: https://docs.microsoft.com/en-us/windows/win32/medfound/supported-protocols

On Windows if you want to use RTSP then I recommend installing LAV Filters and using the DirectShow API.

I couldn't get your URL to play in VLC, so there might be issues with the stream.

**Comment by Chris-RH** [comment]
closed due to lack of reply
