### ISSUE TITLE
Loop not smooth on Demo

### ISSUE THREAD

**Issue by LabStark** [RenderHeads/UnityPlugin-AVProVideo#170]
I'm using unity 2019 on windows 10. I'm really interested in buying this asset and I need to know a couple of things:

1 - I need to use this asset to play different video in different display (up to 4) . Is there a performance problem?

2 - I need to play videos that loop and the loop need to be very smooth. In the editor, the loop is smooth, but in the build the video stops for a moment. What can I do? 

Thank you!

**Comment by AndrewRH** [comment]
Hi,

a few questions:

1) Which version of Unity + AVPro Video are you using?
2) Which platform is this on?
3) Tell me more about the video specs (number, resolution, frame-rate, codec)

To answer your questions:

1 - Playing up to 4 videos might be fine, but it depends on the platform, the machine specs, the video specs.  If you could give more information then I can give a better idea.

2 - For best looping you should encode your video without any P or B frames.  This means you should encode as key-frames only.

Thanks,

**Comment by LabStark** [comment]
Hi,
1- for now I'm using this demo: http://downloads.renderheads.com/2019/UnityPlugin-AVProVideo-Latest-Trial.unitypackage
2- Windows 10 
3 - videos will be 1080p or 4k.  Up to 4 videos (1 each display). 
I don't know the frame rate (they will be different: 25,30,50 and 60)with different codecs :/

I'll try to encode as key-frames only for the loop. The loop is very important to me, is the main feature that I'm looking for...

**Comment by AndrewRH** [comment]
Yes key-frame only will help.  The video shoud ideally also be using a frame-rate that is a multiple of the display-rate (usually 60), so 30fps is better than 25 or 50.

Decoding 4 4K videos will require a really powerful GPU.  Even then I think this is right at the limit of most machines, plus there is extra overhead with Unity, so I think this might be a tall order.

You can use FFMPEG to re-encode your videos.  Use the options:

-tune fastdecode -x264-params "keyint=1"

for H.264, or for H.265 use:

-c:v libx265  -tune fastdecode -x265-params "keyint=1" 

Does that help?

**Comment by LabStark** [comment]
is this string ok? 
ffmpeg -i 1.mp4 -c:v libx265 -tune fastdecode -x265-params "keyint=1" 2.mp4
I tried this but avpro doesn't read the file...it says "file not found"

**Comment by LabStark** [comment]
Sorry I'm stupid...now it works.

I need to try different video, then I'll let you know if the loop is right

**Comment by LabStark** [comment]
ok the loop seems ok but I've lost a lot of quality...

**Comment by RenderHeadsSte** [comment]
@LabStark Did you figure out your loop/quality issues?

**Comment by RenderHeadsSte** [comment]
We shall be closing this bug soon should there be no response forthcoming

**Comment by LabStark** [comment]
HI!
Sorry for the late response. I still have some problem with some video.
A last question then you can close this bug report. What is the best codec
for AVPro? (I need high quality and no stuttering)

Greetings,
Mattia



Il giorno gio 19 dic 2019 alle ore 19:04 Ste Butcher <
notifications@github.com> ha scritto:

**Comment by AndrewRH** [comment]
> ok the loop seems ok but I've lost a lot of quality...

Sorry for the late reply.  You can set the quality for the encoding by adding this option to the command:

-crf 18

Where 18 is a number between 1-31.  1 is the best quality and 31 is the worst.  Usually numbers between 14-24 are best..

There is no single best codec to use when using AVPro Video - it all depends on your use case.  H.264 and H.265 are usually good bets, but then it comes down to the way you encode them and that device you're targeting.

Thanks,
