### ISSUE TITLE
DllNotFoundException   RenderHeads.Media.AVProVideo.AppleMediaPlayer in .ctor

### ISSUE THREAD

**Issue by nlaroche** [RenderHeads/UnityPlugin-AVProVideo#1701]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
We are receiving exceptions through Sentry when the AVProPlayer is loaded into Mac OS systems. "CreateMediaPlayer" is the method which is throwing. We're unable to reproduce locally, but Sentry reports the issue on what appears to be older macbook and iMac systems.

NOTE: We are loading the video at application start in order to display an onboarding video. On an unrelated issue we got information from Unity Support that sometimes Unity may not have loaded the native plugin yet before attempting to initialize it if we're trying to use it "too quick" Is it possible this may be a similar situation? For the other plugin we have implemented a retry mechanism with a 50ms retry period if a DLLNotFoundException was thrown, would something like that perhaps work here?

**Your Setup (please complete the following information):**
 - Unity version:  2022.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): : 2.8.5
 - Operating system version:  Mac OS 10.13.6
 - Device model: iMac 12,1
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Load the AVPro video and call "CreateMediaPlayer" on the target system
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
We only support minimum macOS Mojave (10.14). Could they upgrade their macOS version?
Might be the combination of a new Unity version and old mac OS not quite working well together?

**Comment by Chris-RH** [comment]
I've had a chat with our macOS dev (they are currently overseas, so our working hours currently don't overlap!), and he says the issue is definitely due to it being macOS 10.13, and its just too old for us to support I'm afraid.

**Comment by nlaroche** [comment]
Thank you for the followup, I wasn't aware of the limitation. We've added some error meseages for users with incompatible OS. Cheers!
