### ISSUE TITLE
Multi-track video doesn't work on android

### ISSUE THREAD

**Issue by FeiClay345** [RenderHeads/UnityPlugin-AVProVideo#1702]
Problem description:

Works Fine on PC,but can't detect multi-track on android device.

Device (which devices are you having the issue with - model, OS version number):

HuaWei P30

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

only one video. resolution:1920x1080, Frame rate:29.994, codec:h264

System Information:

AVPro Video: v2.9.0 (plugin v2.8.5f1-trial)
Target Platform: Android
Unity: v2019.4.37f1 WindowsEditor
OS: Desktop - All Series (ASUS) - Windows 10  (10.0.19045) 64bit - ChineseSimplified
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 8 threads - 16289KB
GPU: NVIDIA GeForce RTX 2060 - NVIDIA - Direct3D 11.0 [level 11.1] - 5968KB - 16384

**Comment by Chris-RH** [comment]
Are you able to send a sample of the video file unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
closed due to lack of reply
