### ISSUE TITLE
First Order Ambisonics Audio in 360° Video not recentering when using XRInputSubsytem.TryRecenter().

### ISSUE THREAD

**Issue by JBillson** [RenderHeads/UnityPlugin-AVProVideo#1703]
# Problem description:

I have a 360° video with First Order Ambisonics playing as expected.  If the audio source is coming from "in front" of me, and then I turn 90° to the left, I can hear the audio source coming from the "right of me" as expected.

The problem arises when I then call Unity's XRInputSubsystem.TryRecenter().  The video recenters as expected, but the audio is now offset by 90°. 
For example, the audio source is coming from right and visuals are on the right.  I recenter and then the visuals are now in front of me again, but the audio source is still coming from the right.

I also tried following the steps outlined here: 
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html

And also tried converting the video file in question according to this step:
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html#alternative-steps-for-encoding-manually

Results remain the same whether or not I convert the video file using the above step.

I am unsure if this is an issue with AVPro Video or with Unity XR Subsystem but would appreciate some feedback if this is a common issue or something that has been seen before.

# Device (which devices are you having the issue with - model, OS version number):

Skyworth S1 Pro, Android 7.1.2

# Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\G001_Edit_v16_Assembly_v13_Audio_v42_FOA+HL.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.25.100
  Duration: 00:03:03.43, start: 0.000000, bitrate: 23486 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 3840x3840 [SAR 1:1 DAR 1:1], 23133 kb/s, 30 fps, 30 tbr, 30k tbn (default)
    Metadata:
      handler_name    : ?Mainconcept Video Media Handler
      vendor_id       : [0][0][0][0]
    Side data:
      stereo3d: top and bottom
      spherical: equirectangular (0.000000/0.000000/0.000000)
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 346 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]

AUDIO STREAM CHANNELS:
channels=6
channel_layout=5.1

# System Information:

AVPro Video: v2.6.5 (plugin v2.6.3f1-trial)
Target Platform: Android
Unity: v2019.4.32f1 WindowsEditor
OS: Desktop - GP76 Leopard 11UG (Micro-Star International Co., Ltd.) - Windows 10  (10.0.22621) 64bit - English
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz - 16 threads - 16085KB
GPU: NVIDIA GeForce RTX 3070 Laptop GPU - NVIDIA - Direct3D 11.0 [level 11.1] - 8033KB - 16384

**Comment by Chris-RH** [comment]
Hmm, its not something that rings a bell.
AVPro Video version 2.6.5 is over a year old now.  Could you try reproducing it in a new minimal project using version 2.9.0, the 360 demo scene and then add the Unity XR subsystem please?
Are you able to provide us with a sample of the media that you are testing with? unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Are you changing the 'Head Transform' accordingly as well?  This is what tells the underlying FB360 audio engine which way 'Forward' is.

See: UpdateAudioHeadTransform() in MediaPlayer.cs

**Comment by Ste-RH** [comment]
No need for a minimal project.

Do we know what XrSubsystem.TryRecenter() does to the that 'Main Camera' transform?  If it does not change it, then there is the problem.  It will be doing something under the hood to adjust the transform at a different level, and AVPro/FB360-Audio-Engine will never know about it.  That head transform is the only thing, to my knowledge, that changes the audio 'forward'.

Maybe you can log out the transform to see if it is changing at all?

**Comment by JBillson** [comment]
Hmmm, yeah it seems that the XrSubsystem.TryRecenter() method does not affect the Main Camera transform at all (even though all visuals do actually recenter to the current view).  
I'll have to dig deeper into what the TryRecenter() is doing.  Thanks for the feedback!
