### ISSUE TITLE
Multiple language subtitle sideload

### ISSUE THREAD

**Issue by mohdjai** [RenderHeads/UnityPlugin-AVProVideo#1705]
Hi, is it possible to add 2 language for subtitles?

**Comment by Chris-RH** [comment]
Hi @mohdjai 

Yes, you can add multiple subtitle tracks.  There may be limitations as to how many, depending on the platform and video API (I believe Exoplayer can only see 4 tracks).  More info here: https://renderheads.com/content/docs/AVProVideo/articles/feature-subtitles.html
