### ISSUE TITLE
Facebook 360 audio is out of sync

### ISSUE THREAD

**Issue by jakobwarpin** [RenderHeads/UnityPlugin-AVProVideo#1706]
When playing an .mkv video with facebook 360 audio there is a delay in audio playback in AVPro. The delay does not appear in the native videoplayer on device.

**Your Setup (please complete the following information):**
 - Unity version:  2021.3.30f
 - AVPro Video version:  Ultra Edition - 2.9.0
 - Operating system version:  Android 10
 - Device model: Quest 2, Quest pro, Pico 4
 - Video specs:             
     "codec_name": "hevc",
     "width": 5120,
     "height": 2560,
     "r_frame_rate": "30/1"
     "size": "8634310",

**To Reproduce**
1. Create minimal VR template Unity project.
2. Add video in streaming assets.
3. Select video in the player, configure player as per instructions in the [documentation](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-360audio.html) (channel mode TBE_8_2)
4. Build project and deploy to device.
5. Observe that the audio is lagging behind the video.
6. Add video to device disk, play it in the native video player and observe that the audio is synched.

I've attached two videos in the email, one standard FB360 encoded video, and the same video with the video stream delayed 100ms that we eyeballed to match the audio.

**Comment by Chris-RH** [comment]
Thank you for the videos in the email. We will look at this when we are back in the office.

**Comment by Ste-RH** [comment]
At plugin level, when the FB360 audio sink is created, there is a 'latency' value that gets passed in.  This value comes from the FB360 audio engine itself (AudioEngine::getOutputLatencyMs()).  It is very much 'black box'.  I suppose we could add the ability for developers to decrease/increase this latency value as they desire.

**Comment by Ste-RH** [comment]
We have implemented a definable latency value.  Setting this to -100ms appears to bring your video into audio/visual sync.  This will be available in the next release.

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46531149/74b304b1-a2c0-4df0-b481-2f2cce749b2d)

**Comment by jakobwarpin** [comment]
Thank you for the quick resolution!

**Comment by Chris-RH** [comment]
AVPro Video version 2.9.1 has been released.
