### ISSUE TITLE
AVPro Video - 2.9.0 ExoPlayer build gradle error

### ISSUE THREAD

**Issue by maxlov** [RenderHeads/UnityPlugin-AVProVideo#1709]
While attempting android builds for Meta Quests (requires android version 32 maximum) the new exoplayer for AVPro 2.9.0 causes gradle errors (minimum SDK 33)

**My Setup:**
 - Unity version: Unity 2022.3.10f1
 - AVPro Video version 2.9.0 Ultra
 - Operating system version: Windows 11
 - Device model: Developing on PC building for Quest 2 and Quest 3
 - Video specs (resolution, frame-rate, codec, file size): Not relevant to issue

**To Reproduce**
1. Set maximum android SDK level to 32.
2. Attempt to build project for android with AVProVideo 2.9.0 installed
3. Gradle error occurs

**Portion of Logs Below**
`Android PostProcess task "Calling IPostGenerateGradleAndroidProject callbacks" took 78.391 ms
Total cache size 268241776
Total cache size after purge 268241776
Android PostProcess task "Cloud Diagnostics Symbol Upload" took 168.2412 ms
time="2023-12-05T11:28:45-05:00" level=info msg="Running Usymtool..." 
time="2023-12-05T11:28:45-05:00" level=info msg="Command line: C:/Program Files/Unity/Hub/Editor/2022.3.10f1/Editor/Data\Tools\usymtool.exe -symbolPath C:/Users/maxwe/wkspaces/WildXR/Library/Bee/Android/Prj/IL2CPP/Gradle\unityLibrary\symbols -log C:\Users\maxwe\AppData\Local\Unity\Editor\symbol_upload.log -il2cppOutputPath C:/Users/maxwe/wkspaces/WildXR/Library/Bee/Android/Prj/IL2CPP/Gradle/../Il2CppBackup/il2cppOutput -il2cppFileRoot C:\Users\maxwe\wkspaces\WildXR\Library/Bee/artifacts/Android/il2cppOutput/cpp" 
time="2023-12-05T11:28:45-05:00" level=info msg="Usymtool executable path: C:/Program Files/Unity/Hub/Editor/2022.3.10f1/Editor/Data\Tools\usymtool.exe" 
time="2023-12-05T11:28:45-05:00" level=info msg="Usymtool OS/Arch: windows/amd64" 
time="2023-12-05T11:28:45-05:00" level=info msg="Working directory: C:\Users\maxwe\wkspaces\WildXR" 
time="2023-12-05T11:28:45-05:00" level=info msg="Log file path: C:\Users\maxwe\AppData\Local\Unity\Editor\symbol_upload.log" 
time="2023-12-05T11:28:45-05:00" level=info msg="LZMA_PATH: C:/Program Files/Unity/Hub/Editor/2022.3.10f1/Editor/Data\Tools\lzma.exe" 
time="2023-12-05T11:28:45-05:00" level=info msg="USYM_UPLOAD_URL_SOURCE: https://perf-events.cloud.unity3d.com/url" 
time="2023-12-05T11:28:45-05:00" level=info msg="USYM_UPLOAD_AUTH_TOKEN: (present, redacted)" 
time="2023-12-05T11:28:45-05:00" level=info msg="symbolPath: C:/Users/maxwe/wkspaces/WildXR/Library/Bee/Android/Prj/IL2CPP/Gradle\unityLibrary\symbols" 
time="2023-12-05T11:28:45-05:00" level=info msg="il2cppOutputPath: C:/Users/maxwe/wkspaces/WildXR/Library/Bee/Android/Prj/IL2CPP/Gradle/../Il2CppBackup/il2cppOutput" 
time="2023-12-05T11:28:45-05:00" level=info msg="il2cppFileRoot: C:\Users\maxwe\wkspaces\WildXR\Library/Bee/artifacts/Android/il2cppOutput/cpp" 
time="2023-12-05T11:28:45-05:00" level=info msg="Scanning IL2CPP output for C# line numbers..." 
time="2023-12-05T11:28:48-05:00" level=info msg="Done scanning IL2CPP output for C# line numbers" 
time="2023-12-05T11:28:48-05:00" level=info msg="Found 3 files to check, scanning for binary images now..." 
time="2023-12-05T11:28:48-05:00" level=info msg="Found 3 binary images to process (not all files contain a binary image, and some contain multiple images)" 
time="2023-12-05T11:28:48-05:00" level=info msg="Log for folder symbol_upload_root:
C:\Users\maxwe\wkspaces\WildXR\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\symbols\arm64-v8a\libil2cpp.so
	arm64	2935169dc194caaf
C:\Users\maxwe\wkspaces\WildXR\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\symbols\arm64-v8a\libmain.so
	arm64	32d320f714a4fe6c
C:\Users\maxwe\wkspaces\WildXR\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\symbols\arm64-v8a\libunity.so
	arm64	a03451503cf39067
" 
time="2023-12-05T11:28:48-05:00" level=info msg="File with UUID 32d320f714a4fe6c already exists." 
time="2023-12-05T11:28:48-05:00" level=info msg="Signed URL is: https://storage.googleapis.com/unity-cs-common-prd-crash-symbols/c44643a5-fa76-4b73-bba7-0a03f0f35406/2935169dc194caaf.usym.lzma?Expires=1701797328&GoogleAccessId=101277371710175401107&Signature=KaAO4eR%2FRPIpc%2F3IXYSU3B4fRUXmqDuMR5Sw6K3HXwwsNfwwwXOsBMUp7wEYlP2cMm5Srdcp6RGFjgQ7AaC4Tf8eDerd5Akzyt2xtTCxl%2FqwEzJWjIRICSf0HBnnhiNBgRIiIUTr%2BXocngCXZlrKsabaBCr6fz6OQI%2Falchb9XTe0lzq%2F2oCzE6atKkkFmKNbboc2djVZNQCF0bTQR37fpbfr3dNhGEiCUVFiAcuOXB51wg%2ByEv4f97jP72iig%2FqWBpkvLG%2BIJUAei1NAbf6GMxqdyAtGPhD5J9U65r2bLBnRGrrmFwCOOXzww2wqId4BuOITFW6INTqotWUWAmydA%3D%3D" 
time="2023-12-05T11:28:48-05:00" level=info msg="File with UUID a03451503cf39067 already exists." 
Starting a Gradle Daemon, 1 incompatible and 4 stopped Daemons could not be reused, use --status for details
> Task :unityLibrary:xrmanifest.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:preReleaseBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :launcher:extractDeepLinksRelease UP-TO-DATE
> Task :launcher:extractProguardFiles UP-TO-DATE
> Task :launcher:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:mergeReleaseNativeLibs UP-TO-DATE
> Task :unityLibrary:stripReleaseDebugSymbols UP-TO-DATE
> Task :unityLibrary:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:parseReleaseLocalResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:processReleaseManifest UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :launcher:checkReleaseDuplicateClasses UP-TO-DATE
> Task :launcher:mergeReleaseShaders UP-TO-DATE
> Task :launcher:compileReleaseShaders NO-SOURCE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseRFile UP-TO-DATE
> Task :launcher:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:javaPreCompileRelease UP-TO-DATE
> Task :launcher:collectReleaseDependencies UP-TO-DATE
> Task :launcher:sdkReleaseDependencyData UP-TO-DATE
> Task :launcher:validateSigningRelease UP-TO-DATE
> Task :launcher:writeReleaseAppMetadata UP-TO-DATE
> Task :launcher:writeReleaseSigningConfigVersions UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibCompileToJarRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseNativeLibs NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:stripReleaseDebugSymbols NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:extractReleaseAnnotations UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseShaders NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:packageReleaseAssets UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:prepareReleaseArtProfile UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:mergeReleaseJavaResource UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:syncReleaseLibJars UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:writeReleaseAarMetadata UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:bundleReleaseLocalLintAar UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:extractDeepLinksRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileReleaseLibraryResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibResRelease NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibRuntimeToJarRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:createFullJarRelease UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:writeReleaseLintModelMetadata UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:copyReleaseJniLibsProjectOnly UP-TO-DATE
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:extractReleaseAnnotations UP-TO-DATE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:mergeReleaseGeneratedProguardFiles UP-TO-DATE
> Task :unityLibrary:mergeReleaseConsumerProguardFiles
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:prepareReleaseArtProfile UP-TO-DATE
> Task :unityLibrary:processReleaseJavaRes UP-TO-DATE
> Task :unityLibrary:mergeReleaseJavaResource UP-TO-DATE
> Task :unityLibrary:syncReleaseLibJars UP-TO-DATE
> Task :unityLibrary:writeReleaseAarMetadata UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :launcher:checkReleaseAarMetadata FAILED
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :unityLibrary:bundleReleaseLocalLintAar
69 actionable tasks: 5 executed, 64 up-to-date
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
UnityEditor.Android.GradleInvokationException:ParseAndShowException ()
UnityEditor.Android.PostProcessor.PostProcessRunner:RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext)
UnityEditor.Android.PostProcessAndroidPlayer:PostProcess (UnityEditor.Modules.BuildPostProcessArgs,AndroidPlayerBuildProgram.Data.AndroidPlayerBuildProgramOutput)
UnityEditor.Android.AndroidBuildPostprocessor:PostProcess (UnityEditor.Modules.BuildPostProcessArgs,UnityEditor.BuildProperties&)
UnityEditor.PostprocessBuildPlayer:Postprocess (UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,string,string,string,int,int,UnityEditor.BuildOptions,UnityEditor.RuntimeClassRegistry,UnityEditor.Build.Reporting.BuildReport)
UnityEditor.BuildPlayerWindow/DefaultBuildMethods:BuildPlayer (UnityEditor.BuildPlayerOptions)
UnityEditor.BuildPlayerWindow:CallBuildMethods (bool,UnityEditor.BuildOptions)
UnityEditor.BuildPlayerWindow:GUIBuildButtons (UnityEditor.Modules.IBuildWindowExtension,bool,bool,bool,UnityEditor.Build.BuildPlatform,UnityEditor.Modules.IBuildPostprocessor)
UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings ()
UnityEditor.BuildPlayerWindow:OnGUI ()
UnityEditor.HostView:InvokeOnGUI (UnityEngine.Rect)
UnityEditor.DockArea:DrawView (UnityEngine.Rect)
UnityEditor.DockArea:OldOnGUI ()
UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:ProcessEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool)
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ProcessEventQueue ()
UnityEngine.UIElements.EventDispatcher:OpenGate ()
UnityEngine.UIElements.EventDispatcherGate:Dispose ()
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel)
UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&)
UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr)
UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:
     
     Dependency ':exoplayer-core:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':extension-rtmp:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-dash:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-decoder:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-datasource:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-container:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-extractor:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-database:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-rtsp:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-hls:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-common:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer-smoothstreaming:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'
     
     Dependency ':exoplayer:' requires 'compileSdkVersion' to be set to 33 or higher.
     Compilation target for module ':launcher' is 'android-32'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
UnityEditor.Android.GradleInvokationException:ParseAndShowException ()
UnityEditor.Android.PostProcessor.PostProcessRunner:RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext)
UnityEditor.Android.PostProcessAndroidPlayer:PostProcess (UnityEditor.Modules.BuildPostProcessArgs,AndroidPlayerBuildProgram.Data.AndroidPlayerBuildProgramOutput)
UnityEditor.Android.AndroidBuildPostprocessor:PostProcess (UnityEditor.Modules.BuildPostProcessArgs,UnityEditor.BuildProperties&)
UnityEditor.PostprocessBuildPlayer:Postprocess (UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,string,string,string,int,int,UnityEditor.BuildOptions,UnityEditor.RuntimeClassRegistry,UnityEditor.Build.Reporting.BuildReport)
UnityEditor.BuildPlayerWindow/DefaultBuildMethods:BuildPlayer (UnityEditor.BuildPlayerOptions)
UnityEditor.BuildPlayerWindow:CallBuildMethods (bool,UnityEditor.BuildOptions)
UnityEditor.BuildPlayerWindow:GUIBuildButtons (UnityEditor.Modules.IBuildWindowExtension,bool,bool,bool,UnityEditor.Build.BuildPlatform,UnityEditor.Modules.IBuildPostprocessor)
UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings ()
UnityEditor.BuildPlayerWindow:OnGUI ()
UnityEditor.HostView:InvokeOnGUI (UnityEngine.Rect)
UnityEditor.DockArea:DrawView (UnityEngine.Rect)
UnityEditor.DockArea:OldOnGUI ()
UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool)
UnityEngine.UIElements.IMGUIContainer:ProcessEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEvent (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool)
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:ProcessEventQueue ()
UnityEngine.UIElements.EventDispatcher:OpenGate ()
UnityEngine.UIElements.EventDispatcherGate:Dispose ()
UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode)
UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel)
UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&)
UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr)
UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Uploading Crash Report
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity\Hub\Editor\2022.3.10f1\Editor\Data\PlaybackEngines\AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2022.3.10f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-7.2.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"`

**Comment by Chris-RH** [comment]
Its a Unity 2022.x issue (Unity 2021.x is fine)

In your gradles (main and launcher Templates), try this:

minSdkVersion 22
targetSDKversion 32
compileSDKversion 33

You then need to check Editor/Data/PlaybackEngines/AndroidPlayer/SDK/platforms to see if it has an android-33 folder. If it doesn't you need to copy one across from another version of Unity (I found one in 2023.1.0b17). I have no idea why 2022 doesn't have android 33 included as standard.
