### ISSUE TITLE
Win7 system plays video before card for a long time?

### ISSUE THREAD

**Issue by BYDU** [RenderHeads/UnityPlugin-AVProVideo#171]
Problem description:

The same configuration win7 card, win10 does not have this problem, stuck when calling OpenVideoFromFile (FileLocation location, string path, bool autoPlay = true)

Device (which devices are you having the issue with - model, OS version number):

win7 64  i5-7500 8G NVIDIA GeForce GT 1030

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1920*1080  17383kbps  25frame 

System Information:

AVPro Video: plugin v1.9.17 scripts v1.10.0
Target Platform: Standalone
Unity: v2018.4.3f1 WindowsEditor
OS: Desktop - B150M-D3H (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - Chinese
CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz - 4 threads - 8149KB
GPU: NVIDIA GeForce GT 1030 - NVIDIA - Direct3D 11.0 [level 11.1] - 1992KB - 16384

**Comment by AndrewRH** [comment]
I'm guessing you must have a 3rd party codec pack installed, and this is having some error while open video files..

Does that help?

**Comment by AndrewRH** [comment]
Closing issue as too old and probably related to 3rd party plugins we can't control
