### ISSUE TITLE
Audio processing doesn't work on Windows Server without physical or virtual speakers

### ISSUE THREAD

**Issue by izzy667** [RenderHeads/UnityPlugin-AVProVideo#1710]
Streaming videos with HLS always uses SystemDirect as AudioOutput instead Unity. Class AudioOutput doesn't process any audio track and AudioSource is not used too. Problem occurs probably in all platforms (tested MacOs, Windows, iOS, Android).

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.22f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.0 Trial
 - Operating system version: MacOS/Windows
 - Device model: any
 - Video specs (resolution, frame-rate, codec, file size):  any hls livestream with audio

**To Reproduce**
1. Setup Unity as AudioOutput in MediaPlayer class
2. Play any HLS stream with audio
3. Audio track is not played inside unity, AudioOutput and AudioSource doesn't work

**Comment by Chris-RH** [comment]
I can't reproduce this on my end using Windows and Android.

Are you doing this via scripting or using the components?
Can you reproduce this just using the mediaplayer demo scene?

On Android, Android Mediaplayer does not support Unity Output, only the Exoplayer API will.

You won't be able to use HLS and Unity Audio in macOS/iOS.
(see: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1086)

**Comment by izzy667** [comment]
Understood issue with Apple environment, so lets focus on Windows platform.

I'am using Windows Standalone64 build, created in MacOS's editor with Mono scripting as backend (ILL2CPP not supported for MacOS) and running on Windows Server 2019.

Ive tested both scripting and setup data directly in component, both options doesn't work.

To tests I am using your HLS stream: https://stream.mux.com/4XYzhPXzqArkFI8d1vDsScBLD69Gh1b2.m3u8 on your Demo_MediaPlayer scene. Inside that scene I am trying to access audio data via: `AudioListener.GetOutputData` but that method doesn't return anything (conclusion: MediaPlayer is not using Unity to play audio tracks from HLS).

When I am using mp4 file from StreamingAssets instead everything works fine (even in MacOS's editor - didn't check MacOS/iOS build).

**Comment by izzy667** [comment]
Closed by accident.

**Comment by izzy667** [comment]
I found an issue.
Iam running it in VPS environment, so my Windows doesn't have to any active speakers and for audio processing it is not required. Question is there any workaround to force MediaPlayer to route audio through Unity when there is no speakers?

**Comment by Chris-RH** [comment]
So the same mp4 (same audio codecs etc) runs fine with Unity Audio on the VPS through streaming assets, but not as an HLS?

**Comment by izzy667** [comment]
My bad, I was testing mp4 with active audio streaming via remote desktop, so there was active speaker in system settings, also in that configuration HLS works too.

So I installed virtual speaker driver which will be active all the time and that solves the problem with audio in unity app.

Question: is it the only option to forced audio to be played when there is no speakers in system settings? I am not sure if that is Unity's or AVPro's limitation. In my case I don't need any speakers because I am processing audio and streaming it back so don't have to playing it locally on my build.

**Comment by Chris-RH** [comment]
Ahhh, yeah it sounds like, without the virtual speaker driver, the system isn't bothering to decode the audio. In which case there is nothing to be done from our end. I.E. not a Unity or AVPro limitation.



We use MTAudioProcessingTap to extract the audio and route it through to Unity. This in turn requires using AVAudioMix and attaching it to the current player item. Sadly this is where the process breaks down as AVAudioMix does not support HLS media. The documentation for AVAudioMix states the following (available [here](https://developer.apple.com/documentation/avfoundation/avplayeritem/1388037-audiomix)):

An audio mix can only be used with file-based media and is not supported for use with media served using HTTP Live Streaming.

Until that changes, we can't do anything about it.
