### ISSUE TITLE
When calling Stop(), video does not always stop

### ISSUE THREAD

**Issue by DomHarris** [RenderHeads/UnityPlugin-AVProVideo#1712]
**Describe the issue**
Sometimes, 

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.20 and 2023.2.3f1, plus a few versions in between. It seems to be version agnostic
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.0 core edition
 - Operating system version: iOS
 - Device model: iPhone X
 - Video specs (resolution, frame-rate, codec, file size): 1280x720, 60fps, H264, 721kb

**To Reproduce**
1. New 2D URP project in 2023.2.3
2. Import AVPro Video - Core Edition (2.9.0)
3. Create UI -> Canvas
4. Create UI -> AVPro Video uGUI
5. Add Component -> Media Player
6. Settings -> Source -> Media Source -> Path, Absolute Path Or URL -> https://customer-brg6t6s82hjax7ct.cloudflarestream.com/903545d75a0ecd7e3a9c8e83ffe83744/manifest/video.m3u8
7. Settings -> Playback -> Loop -> true
8. Assign that media player to the uGUI display
9. Set the player's rect transform to stretch full screen
10. Add the following component:
```cs
public class VideoPlayPause : MonoBehaviour
{
    private MediaPlayer _player;
    
    private void Awake()
    {
        _player = GetComponent<MediaPlayer>();
    }

    public void Toggle()
    {
        Debug.Log($"Toggle - {_player.Control.IsPlaying()}");
        if (_player.Control.IsPlaying())
            _player.Stop();
        else
            _player.Play();
        Debug.Log($"Player is now {_player.Control.IsPlaying()}");
    }
}
```
11. Add a button, on press should be VideoPlayPause.Toggle
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/27929155/18fda6f0-c2b9-48ee-994c-f8c9a8a536d1)
12. Build for iOS
13. Run on-device. Tap the video to pause - it will continue playing until it loops, but the sound will stop. `_player.Control.IsPlaying()` reports `false`.

**Videos**
If applicable, add a copy of your video or the URL
https://customer-brg6t6s82hjax7ct.cloudflarestream.com/903545d75a0ecd7e3a9c8e83ffe83744/manifest/video.m3u8

**Comment by Chris-RH** [comment]
1. Which iOS version are you using?
2. Have you tested on other iOS versions?
3. Is this only occurring in URP or does it also occur in SRP?
4. Does this always happen on the same stream?
5. Are you able to give more examples of which streams do and don't work?
6. Can you reproduce this in a fresh project using just the AVPro Mediaplayer demo scene?

**Comment by DomHarris** [comment]
1. I'm currently on iOS 16.7.2 but it also happens on our other test phone which is running 17.1.2
2. yes, addressed above
3. also occurs in HDRP and BIRP
4. It always happens on this specific stream, it also happens on a few others but those videos have the clients in-shot. It works as expected for other videos, though, e.g. https://customer-brg6t6s82hjax7ct.cloudflarestream.com/95fd930b84e9e9cc4930b9dfb5d39feb/manifest/video.m3u8
5. Stream in the original issue message does not work, link above does work
6. Yes, just changing the sample Demo_MediaPlayer -> MediaPlayer object's source to path/absolute path or url with the link https://customer-brg6t6s82hjax7ct.cloudflarestream.com/903545d75a0ecd7e3a9c8e83ffe83744/manifest/video.m3u8 will reproduce the issue on all versions of Unity I have tried. The green bar at the bottom continues to progress even after pausing with this stream.

**Comment by DomHarris** [comment]
Tested it on a bunch of different devices: I can confirm that it doesn't happen in any desktop builds for Windows, macOS, or Linux. It also doesn't happen on Android. 

Easy download of the video that the issue happens with:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/27929155/a97aa75d-32e5-41c3-b1eb-30c46a957091
Video details: 1280x720, 60fps, mp4a, 721kb


Easy download of the video that it doesn't happen with:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/27929155/246e3dfa-e240-451c-a58a-1fcd71c08ceb
Video details: 606x1080, 30fps, H264, 1.6mb

My assumption would be that the codec is what's causing the issue?

**Comment by MorrisRH** [comment]
I'm not able to reproduce exactly what you describe although there is an oddity occurring where there is no output for a single loop which recovers with the next loop after a pause. I am investigating this but not hopeful for a solution as the issue seems to be internal to AVFoundation. This issue does seem to be due to your media being very short and the HLS only having a single segment with only one I-frame.

I do have a work around however, enable "Use Single Player Item" in the iOS section of the MediaPlayer settings as shown here:

![Screenshot 2023-12-13 at 12 47 48](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/a62c7685-0efd-4d5e-9a0a-bbbacd210272)

This will cause a slight stall when looping but as the media you've shared doesn't loop perfectly I don't think this will be an issue for you.

**Comment by DomHarris** [comment]
Thank you, that option seems to do the trick! It's weird that you can't reproduce it though, it's consistent for me across all my test iOS devices and across Unity/AVProVideo versions. Ah well, I can live with a slight stall while looping. Cheers!
