### ISSUE TITLE
[Question] How to switch Audio tracks

### ISSUE THREAD

**Issue by eiyamomo** [RenderHeads/UnityPlugin-AVProVideo#1714]
My online research suggests that AVPro Video supports multiple AudioTracks while playing Video. But I can't find built in functions to switch Audio track within script while playing a MP4 with 2 audioTracks (different language).

I tried to search in the documentation here https://www.renderheads.com/content/docs/AVProVideo/articles/intro.html but no luck.

I tried to search more over the internet, but people were suggesting using 

mediaPlayer.Control.SetAudioTrack(0),  where SetAudioTrack() doesn't seem to be a valid function within mediaPlayer.Control.

I tried to look deeper into the MediaPlayerEditor_Player.cs, it seems it is using the following code

AudioTracks tracks = media.AudioTracks.GetAudioTracks();
foreach (AudioTrack track in tracks)
{
  //found the audioTrack
}
audioTracks.SetActiveAudioTrack(track);

Which I tried, but it also didn't work.

NOTE #1: mediaPlayer.AudioTracks.GetAudioTracks().Count is just returning 0.
NOTE #2: The 2 Audio Track does show properly on the editor
NOTE #3: I can use mediaPlayer.control.Play(), and I can use mediaPlayer.OpenMedia() to change the videoclip in the Script.

I just couldn't figure out why it is not working. Is this a limitation of Trail Version?

Any help would be appreciated.

**EDIT: I added a Debug.log(mediaPlayer.AudioTracks.GetAudioTracks()) OnVideoEvent(), now it seems  is returning the tracks, but it doesn't always return it. It is initially returning 0, then after a console log from AVProVideo, it is starting to show the # of audio tracks.

I have attached the screenshot below.  I wanna be able to set the audiotrack after the video is loaded into the mediaplayer but before it is played. Is it possible?**

Thanks.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.13f1
 - AVPro Video version (2.9.0 Trial): 
 - Operating system version: Windows 11
 - Device model: PC
 - Video specs (1920x1080 Mp4): 

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/153699421/04a0886f-34fb-4aa0-ad01-98053ba74f04)

**Comment by MorrisRH** [comment]
Track information will not be available until the video has been opened. As this is an asynchronous operation you will need to wait for either the ReadyToPlay event (if autoplay is false) or FirstFrameReady (if autoplay is true).

The way to switch tracks is to use the AudioTracks interface on MediaPlayer as you have shown in your post.

If it still isn't working for you, could you share your video so we can investigate further? If so, please send it to unitysupport@renderheads.com mentioning this GitHub issue in your mail.

**Comment by Chris-RH** [comment]
Has this helped?
