### ISSUE TITLE
[Enhancement][iOS] Add support for MV-HEVC

### ISSUE THREAD

**Issue by doasgloria** [RenderHeads/UnityPlugin-AVProVideo#1715]
i want to play the spatial video taken by iPhone 15 pro on unity iOS platform.
can i decode it to the side-by-side stereo format by the plug-in ?

**Comment by Chris-RH** [comment]
Not yet, but its something that we can look into adding support for :)

**Comment by min9jia** [comment]
Yes Please

**Comment by 3493000** [comment]
Any update here？

**Comment by Chris-RH** [comment]
We're a small team, so will get to it when we have chance.  We will update when we have more info.

**Comment by yosun** [comment]
Checking back again! Vision Pro has launched!!!

**Comment by sergeyv-deovr** [comment]
Are you guys planning to work on that feature?

**Comment by MorrisRH** [comment]
Support for stereo MV-HEVC playback will make it into the next release, version 3.1.0

**Comment by Ste-RH** [comment]
AVPro Video v3.1.0 has just been released. Please do report back if the fixes in the version address the issue.
