### ISSUE TITLE
Video Player Freeze Issue Upon Application Pause and Resume at the Start of Video Playback on iOS

### ISSUE THREAD

**Issue by helinkayabass** [RenderHeads/UnityPlugin-AVProVideo#1718]
**Describe the issue**
The video player experiences a freeze on the initial frame under specific circumstances. This issue is observed when the following sequence of actions occurs:

Initial Playback Start: The video playback is initiated, displaying the first frame of the video.

Application Pause: The application running the video player is paused while the video is still on its first frame.

Application Resume: Upon resuming the application, the video player remains frozen on the first frame and does not proceed with normal playback.

Contrast Behavior: This issue is not observed if the video player has advanced beyond the first frame before the application is paused and resumed. In such cases, upon resumption, the video player functions correctly and continues the playback without any freezing.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.21f1
 - AVPro Video version: 2.9.1 Ultra Edition
 - Operating system version: iOS 15 to 17
 - Device model: iPhone 7 to latest
 - Video specs (resolution, frame-rate, codec, file size): Irrelevant

**To Reproduce**
1. Launch the application and start playing the video.
2. Immediately after the video starts (while it is still on the first frame), pause the application.
3. After a brief pause (a few seconds should suffice), resume the application to continue the video playback.

**Comment by helinkayabass** [comment]
Could you please provide any updates regarding this matter?

**Comment by jitendra-unity-vsf** [comment]
Facing the same issue on iOS devices.
Any workaround?

**Comment by Chris-RH** [comment]
Its still on our to do list :)

**Comment by Ste-RH** [comment]
We are unable to reproduce this in v2.x or 3.x.  We suggest testing in the latest release to see if the issue still persists.

**Comment by Ste-RH** [comment]
We will be closing this issue soon due to a lack of response.
