### ISSUE TITLE
Local Video Not Loading In Quest 2 Build, Fine In Editor

### ISSUE THREAD

**Issue by SirLoinII** [RenderHeads/UnityPlugin-AVProVideo#1719]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

-

** I am able to load and play videos from the Quest 2 download folder using the Unity Video Player, but not AVPro (using trial version).

When testing a local path in the editor (Windows 10), it works as expected. The demo scenes play well and playing a video from a reference works, too.

A debug test shows that the video is found and it's supposedly opened properly in the media player, but when it goes to play, it's just a grey screen which is the base material color. I'm using the skybox method.

The problem isn't finding the video, it's loading it to the material. 

I look forward to hearing back from any of you, thanks! **

-

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.33f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Trial, downloaded yesterday so most recent version
 - Operating system version: Windows 10
 - Device model: Quest 2 (Android)
 - Video specs (resolution, frame-rate, codec, file size): 8K, H.265, 60fps, 500MB thru 20GB

**To Reproduce**
1. Set up scene like VR skybox demo
2. Add read/write permissions to manifest.xml, enable 'External (SD Card)' in player settings
3. Build project with OpenXR to work on Quest 2 standalone

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
What works in Windows Editor is irrelevant really, as its using completely different hardware and software.

1. Are you using SRP, URP or HDRP?
2. Is the media stored in streaming assets or Application.persistentDataPath?
3. To start, If you test with a new project and just the AVPro Video demo scenes, do the videos play?
4. Can you provide a full logcat?

**Comment by SirLoinII** [comment]
1. I'm using the built-in pipeline
2. Videos are stored through an absolute path to the downloads folder. The path is: /sdcard/Download/<videoName.mp4> 
A test shows that it found and opened the video correctly. It loads with that path using the Unity video player in build

3. I'll try it with an empty project today then I'll get back to you with the results. It does play the demo videos fine when they're set up as a reference though. I have not tested the video I'm trying to play by referencing it though, so I'll do that today as well.
4. I'll send a full logcat over later today

Thanks!

**Comment by SirLoinII** [comment]
Here's the full logcat from my custom project: 
[logcat.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/13756423/logcat.log)

I'm creating a new project now to test the demo scenes with, I'll comment again shortly

**Comment by SirLoinII** [comment]
I tested with a new, empty project with only OpenXR & the AVPro Trial and the video worked successfully.

I did a few more tests with my original project and I found that it gives the error "Failed Loading". I did change a few things since the test where I sent the logcat, so that might be on my end. I'll mess with it more and I'll let you know if I have any more info to give you.

**Comment by SirLoinII** [comment]
Ok, so it says that the file is found when using System.IO.File.Exists(), but the media play throws the "Failed Loading" error. I tried with the demo cones video again, but I added it to the downloads folder then tried to play it using the same method and it worked. 

I then built the app with the original video and tried to play it via a data path and it failed to load again, so it's something with the video I'm trying to play. It's 8K 30fps, 676MB, using H.265 . The docs say that Android supports those details, or am I missing something? Is there a reason it wouldn't work?

The client I'm making this for has videos he'd like to play that are larger than 20GB at 60fps using 8K, is that going to be an issue?

**Comment by SirLoinII** [comment]
Sorry about spamming all of the messages, but I did one last test for the day where I took the same video that wasn't loading and transcoded it in Unity to use H.265. I then tried to load that and it actually worked, but only once. I quit the app then tried to run it again (the exact same app) and it gave the same "Failed Loading" error for some reason. I don't know why it worked the first time I tested it but not on the second try.

I'll close it down for today, but I look forward to hearing back from you about this. Thanks again!

**Comment by Chris-RH** [comment]
Have you got any other things going on in the scene in your original project? Any other images or videos loaded/playing?
Is there audio?
I'm wondering if its just running out of resources.

There is more info about resolutions here: https://headjack.io/knowledge-base/best-video-resolution-for-oculus-quest-2/

**Comment by SirLoinII** [comment]
Sorry I forgot to update this, but I found out my issue was a second media player that I didn't know about. I removed it and everything works perfectly now. Thanks for your help!
