### ISSUE TITLE
Video recorded using iPhone's internal screen recording feature does not play properly on a RenderTexture using ResolveToRenderTexture

### ISSUE THREAD

**Issue by thesanketkale** [RenderHeads/UnityPlugin-AVProVideo#1721]
**Describe the issue**
The videos recorded using iPhone's internal screen recording feature does not play properly on a RawImage when played using ResolveToRenderTexture component along with AvPro's MediaPlayer component.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.14f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core 2.9.1
 - Operating system version: iOS 17.2.1 & macOS Sonoma 14.2.1
 - Device model: iPhone 14 Max Pro & Mac Studio
 - Video specs (resolution, frame rate, codec, file size): 
major_brand: qt
minor_version: 0
compatible_brands: qt
creation_time: 2023-12-30T12:39:53.000000Z
com.apple.quicktime.author: ReplayKitRecording
com.apple.quicktime.creationdate: 2023-11-09T19:22:59+05:30
Duration: 00:00:35.75, start: 0.000000, bitrate: 19918 kb/s
Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709/bt709/iec61966-2-1, progressive), 886x1920, 19255 kb/s, 59.14 fps, 59.94 tbr, 600 tbn (default)
handler_name: Core Media Video
vendor_id: [0][0][0][0]
encoder: 'avc1'
Side data:
display matrix: rotation of 90.00 degrees
Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 107 kb/s (default)
handler_name: Core Media Audio

**To Reproduce**
1. Record the screen of the iPhone/iPad device and take the original video (not the one converted into a shareable format when you hit the share button from the Photos app) and place it under the streaming asset folder in a Unity project.
2. Create a render texture in Unity Editor having a 1920 x 1920 resolution and assign it to RawImage texture
3. Add MediaPlayer and ResolveToRenderTexture to an empty game object and assign corresponding values
4. Hit play

**Screenshot**
<img width="1920" alt="Screenshot 2024-01-01 at 9 30 20 PM" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/36810188/0218d557-411a-48c8-88b5-69a0997b9f16">

**Video**: https://drive.google.com/file/d/1ieNzZp-IeVu10LsPibPpIphb2fpjm4xY/view?usp=drive_link

**Project link**: Emailed to unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
I'll ask the iOS dev about this when he is back from his holiday.

**Comment by thesanketkale** [comment]
> I'll ask the iOS dev about this when he is back from his holiday.

Hi @Chris-RH, Did you get a chance to do this?

**Comment by MorrisRH** [comment]
Thanks for sending on the sample video, turned out to be an issue with how the texture transform is generated. This has been fixed and will make it into the next release.

**Comment by thesanketkale** [comment]
Hey guys, did this version with the fix hit the asset store yet?

**Comment by Chris-RH** [comment]
Not yet.  We'll update this thread when the new version is out.

**Comment by Chris-RH** [comment]
AVPro Video version 2.9.2 has been release.  Please let us know if this has not fixed your issue.
