### ISSUE TITLE
Do you have plans to support HarmonyOS for AVProVideo?

### ISSUE THREAD

**Issue by tomh520** [RenderHeads/UnityPlugin-AVProVideo#1723]
**HarmonyOS Support**
Hello, our game utilizes the AVProVideo plugin. Currently, we are planning to integrate with Huawei's HarmonyOS. Do you have plans to support HarmonyOS, and if so, when is it expected to be released?

**Comment by tomh520** [comment]
Our Unity Version is 2022 LTS

**Comment by Chris-RH** [comment]
We currently have no plans to support HarmonyOS

**Comment by tomh520** [comment]
。。。
But in China, there are a large number of Unity developers, and the AVPro plugin is also very widespread. Starting from 2024, Huawei's native HarmonyOS will be vigorously promoted. The Chinese team of Unity has officially released a new engine that fully supports the native HarmonyOS. Many Unity development teams will include adaptation for the HarmonyOS in their plans. So， We really hope that AVPro plugin can support the HarmonyOS system!

**Comment by Chris-RH** [comment]
As far as I'm aware, HarmonyOS is only available on devices in China, so it would be difficult for us to get our hands on it.
We are a very small team and at the moment we simply do not have the capacity to add support for another OS.

**Comment by tomh520** [comment]
OK
