### ISSUE TITLE
Load HLS feed requiring authorization header

### ISSUE THREAD

**Issue by Ben-DimX** [RenderHeads/UnityPlugin-AVProVideo#1724]
I am provided an hls video feed url that requires an http Auth header with bearer token be included when getting the feed

I'm looking for help setting this up if it's something that can be done :)

**Comment by DimX-Scott** [comment]
More specifically, we see the option to add a custom header, but it is not used anywhere other than Android.
Is this something we could leverage on all devices?

The vendor we are trying to integrate does not give direct media access but provides a playlist that indirectly routes us to the HLS stream.
Part of getting access to that playlist is to provide a base URL and bearer token with every request we send. It won't authorize access if we can't put a custom header on our URL requests. Direct access to the media is also not an option currently.

Any help on this would be greatly appreciated.
Our target platforms are iOS, MacOS, and Windows.

**Comment by DimX-Scott** [comment]
We think we found the solution. Thanks!
