### ISSUE TITLE
Issues with Synchronization Delay between Timeline and Recorder in Unity 3D

### ISSUE THREAD

**Issue by BananaofGOD** [RenderHeads/UnityPlugin-AVProVideo#1726]
Hello, I am a 3D animation producer mainly working with Unity 3D animations. My primary workflow involves using the Timeline for animation creation, followed by the Recorder for producing the animations. However, I am encountering an issue with the Media Player. When playing MP4 files in Media Player, I can't seem to synchronize them frame-by-frame with the videos recorded using the Recorder. How can I ensure they are synchronized?

Recorder Output Format : Apple proRes 4444 XQ (ap4x)

**Comment by Chris-RH** [comment]
Our Timeline components are not very extensive. We don't make use of the Timeline much ourselves and haven't gotten a lot of requests for further integration.

Our product AVPro Movie Capture has a Timeline Controller component that should sync the capture: https://www.renderheads.com/content/docs/AVProMovieCapture/articles/component-timeline-controller.html  
A free, fully featured, watermarked trial version is available here: https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/releases

**Comment by BananaofGOD** [comment]
Thank you for your prompt response! I have downloaded it, and I would like to know how can I link the Timeline Controller and MediaPlayer together?

**Comment by Chris-RH** [comment]
That's the closest we can get I'm afraid.  As I've said before, our timeline implementation is very basic.  
There was this mod on github that someone made a few years ago that might help, but it needs further investigation in a fresh project and probably won't work straight out the box, but you are welcome to have a look: https://github.com/ScatterCo/avpro2playables

**Comment by BananaofGOD** [comment]
Thank you very much for your answer, it was very helpful. I succeeded and managed to resolve the current issue using this solution. I am extremely grateful for your assistance.

**Comment by Chris-RH** [comment]
Awesome!  I'm so glad that it worked for you :)  Out of interest, did you have to do much fiddling around with that mod or did it work as is?

**Comment by BananaofGOD** [comment]
Yes, it was quite simple. Just followed the instructions on his GitHub page, which said to replace the four files, and it worked

**Comment by Chris-RH** [comment]
Great, that's good to know, thank you :)
