### ISSUE TITLE
Regarding format of key in hls manifest file or .m3u8 playlist file 

### ISSUE THREAD

**Issue by rounak-techxr** [RenderHeads/UnityPlugin-AVProVideo#1727]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
first I made my manifest like this

line for aes encryption
#EXT-X-KEY:METHOD=AES-128,URI="encrypt.key"

I have mentioned the key file and the .key file is in the same directory of this manifest , it got cached but when I am running it , it is showing load failed error, then I read on the content protection page on the render heads official documentation , that it supports clear key (key should be mentioned in the manifest itself), then I pass the key as the string like this

#EXT-X-KEY:METHOD=AES-128,KEY=AAABBBBBAAA  

the key is valid aes key base64 format, not mentioned the exact key

now when I am caching this , it is showing this error in android logcat , I am running this on android device in android app

error on logcat unity - 

2024-01-09 15:27:38.831 15281 17733 Error DownloadManager   com.google.android.exoplr2avp.ParserException: Couldn't match URI="(.+?)" in #EXT-X-KEY:METHOD=AES-128,KEY=AAABBBBBAAA
{contentIsMalformed=true, dataType=4}

give the correct format so that it get cached and also decrypts the video while playing with the key

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Your first attempt is correct so I suspect your encrypt.key file is somehow not valid. It should be exactly 16 bytes for AES-128 encryption and be the key itself, not encoded using any scheme such as base64.

Clear key just means that there is no protection scheme in place for retrieving the key from the server, it does not mean the key is provided in the manifest. The EXT-X-KEY tag does not support a KEY attribute and as the URI attribute is required with AES-128 the load is failing.
