### ISSUE TITLE
First frame black when loading new video

### ISSUE THREAD

**Issue by eman2XR** [RenderHeads/UnityPlugin-AVProVideo#173]
We are developing a VR 360 app targetting android. 

When switching from one video to another a black frame is shown in between. 
We are using the TextureProducer.GetTexture() api in the Update() to assign the video texture to our material. I assume what is happening is that the TextureProducer destroys the texture and creates a new one when a new clip is loading, showing a black on in between. 

We really need a seamless transition (the unity built in a player has seamless transitions to new clips but has other issues). Any ideas?

**Comment by eman-insilico** [comment]
I haven't as I didn't know it exists. It would be nice if the component was mentioned in the docs and would be even nicer to know how to use it.

**Comment by AndrewRH** [comment]
Closing this as it's old and we'll create another issue related to loading videos holding onto the previous texture
