### ISSUE TITLE
Internal ExoPlayer error when internet access is lost

### ISSUE THREAD

**Issue by GabrielRosenberg** [RenderHeads/UnityPlugin-AVProVideo#1730]
When disabling all network access (carrier and WiFi) on Android while video is playing: video eventually stops playing, no stalling event is fired and IsPlaybackStalled doesn't return true. Playback never resumes when enabling again the network accesses.
There is an internal ExoPlayer error ("ExoPlayerImplInternal: UnknownHostException (no network)").

This problem was mentioned in a previous issue (https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/872#issuecomment-885170440) and a ticket was supposed to be created for this, but I can't find it. I also got the problem as mentioned above. Have a solution been identified?

**Setup:**
 - Unity version: 2020.3.48
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.1 Ultra

**Comment by Chris-RH** [comment]
I believe you are referring to https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/874

**Comment by GabrielRosenberg** [comment]
Thanks, it probably is. I continued the conversation in that issue.
