### ISSUE TITLE
UnityPlugin-AVProVideo-v2.9.1-Trial + Unity2022.3.5f1 + WebGL +  ios 17.2.1 = HLS Bug

### ISSUE THREAD

**Issue by yty** [RenderHeads/UnityPlugin-AVProVideo#1731]
It should only report errors on iOS, (Safari  +Chrome )
Because it is correct on Windows 11+Chrome

**Describe the issue**
1. Create unity3d Project ，set Platform => `WebGL`
2. import `UnityPlugin-AVProVideo-v2.9.1-Trial.package`
3. open `Demo_DisplayComponents.untiy`
2. select  `mediaPlayer ` , setting `source` =>http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
4. select`Platform Specific\WebGL` ,set `External Library` =>` Hls Js`
5. Development Build ，Deploy on server.
6. On an `iPhone`, open the link using `Safari browser`
7. Return Error：[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources. 

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.5f1
 - AVPro Video version 2.9.1trial 
 - Operating system version:  windows11
 - Device model: iphone 12 pro
 - Video specs 
 - http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8
 - http://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)
 

**Logs**
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources. 

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/841770/3f6534af-b62f-40b5-93fc-ec93fd296e15)

**Comment by Chris-RH** [comment]
iOS
All browsers on iOS are required to use WebKit and as a result exhibit the same behaviour as Safari, which at this time is not supported.
Documentation: https://renderheads.com/content/docs/AVProVideo/articles/platform-webgl.html

**Comment by yty** [comment]
> iOS iOS 上的所有浏览器都需要使用 WebKit，因此表现出与 Safari 相同的行为，目前不支持 Safari。 Unity WebGL 不支持移动设备。文档：https://renderheads.com/content/docs/AVProVideo/articles/platform-webgl.html https://docs.unity3d.com/Manual/webgl-browsercompatibility.html

It doesn't seem so pessimistic. I haven't given up on testing yet

Because the problem seems to be related to the M3U8 specification.

Currently, it has been found that there are successful ones with a resolution of 1920x1080

**Comment by Chris-RH** [comment]
We do not officially support WebGL, but still include it as it may be useful for some people. We found too many issues with browser compatibility to continue supporting it
