### ISSUE TITLE
Meaning of "Stalled" event?

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProVideo#1734]
We're trying to get a sense of how long it takes to start streaming a piece of media. We've found that videos tend to load pretty fast, except for when the Stalled event occurs. In this case it can take several seconds (somewhere between 1 and 20 seconds, it seems fairly random) for the video to start. Can you tell us what causes this, and if there's any way we can minimise it?

**Comment by MorrisRH** [comment]
The Stalled event means playback has been suspended whilst more data is being buffered. The playback will resume when enough data has been buffered such that the player is unlikely to stall again.

**Comment by tomkail** [comment]
Gotcha. Thanks!
