### ISSUE TITLE
Unity Cloud - Missing files in classes.dex | Android

### ISSUE THREAD

**Issue by Unany** [RenderHeads/UnityPlugin-AVProVideo#1735]
**Describe the issue**
Unity cloud builds are stripping the following files from the classes.dex for Android. This is only the case with cloud builds and not the local builds. Please see attached the difference between the two (Note the missing android file in the dex is from a seperate project, so that's expected)

I have tried the following methods to try and fix this but to no avail.

- External Dependency Manager
- Explicitly disabled minify in the manifest
- Added a link.xml
- Added set dependencies to the mainTemplate.gradle
- Added a custom proguard to prevent stripping
- Forced it to build with multi-dex
- Tried updating the unity version

This is visible in empty projects containing only AVPro Core.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.22f1
 - AVPro Video version: AVPro Video - Core Edition v2.9.1
 - Operating system version: Android 14
 - Device model: Google Pixel 6A
 - Video specs (resolution, frame-rate, codec, file size):  N/A

**To Reproduce**
1. Create a new project
2. Set project settings to use IL2CPP and enable ARM64
3. Install AVPro Core
4. Setup Unity Cloud android build
5. Download APK
6. Check it in Android studio and notice the missing folders in classes.dex

**Logs**
AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager

**Screenshots**

![correctDex](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/40468566/057562f5-1553-4c30-91b6-163dd6aec785)
![missingdex](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/40468566/7a1268dd-ba6f-438f-861b-a7561a98c2ef)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hmmm, not sure as we don't use cloud build.  Seeing as it builds fine locally, I'm not sure this is an "us" thing to fix.  Have you tried opening the support issue with Unity?

**Comment by Unany** [comment]
Hi, I've posted in the Unity Build Automation forums but was wondering if you had any idea of a potential fix?

**Comment by Chris-RH** [comment]
No, we don't use cloud build.

**Comment by danhalldubit** [comment]
I'm running into the same issue with Unity 2022.3, both in my existing project and with a fresh Unity project.

I have tried all of the documented troubleshooting steps without luck. Unfortunately I'm unable to build locally to confirm whether a batch mode build would work or run into the same issue.

It's not feasible for me to replace Unity's CI with my own any time soon, so any further insight would be much appreciated @Chris-RH

**Comment by Chris-RH** [comment]
We don't use Cloud build, so we can give no advice on it.  We can only advise on issues specific to AVPro that are occurring in local builds.  For cloud build issues, your best bet is the Unity forum.
We already have notes to help people with issues that can occur during local builds (https://renderheads.com/content/docs/AVProVideo/articles/platform-android.html#build-notes).  Though these are Unity issues that happen to effect AVPro Video, they are not our bugs.
