### ISSUE TITLE
[iOS][Windows]Unable to play when loading a video of less than 1 second

### ISSUE THREAD

**Issue by Smaet** [RenderHeads/UnityPlugin-AVProVideo#1738]
**Describe the issue**
When playing a short video of less than 1 second repeatedly on iOS and Windows, the video does not appear, but plays normally on AOS.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.15f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.9.1 ultra
 - Operating system version: iOS : 15.7, 16.1 / Window 10
 - Device model: iPhone 11 Pro max,  iPhone Xs
 - Video specs (resolution, frame-rate, codec, file size):  (320*172, 30, FFmpeg-h264)

**To Reproduce**
1. Go To Demo Scene (Name : Demo_MediaPlayer)
2. Set Video URL (See video url below)
3. Play

**Logs**
If applicable, add error logs to help explain your problem.
[iOS.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/14008260/iOS.txt)
 -> Check Log ([AVProVideo] Error: Loading failed)
[Window.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/14008248/Window.txt)

**Videos**
If applicable, add a copy of your video or the URL
 - https://jumpvrapi-mscdn-api-stg.azureedge.net/blobpublic-stg/space_mbr/2023/11/02/1048549/43303_1_4868_99b0d12f-d3ba-4e63-afb9-570484e20dc5/hls/43303_1_4868.m3u8

**Comment by Chris-RH** [comment]
For short media, I'd suggest using mp4 instead.

The manifest has 0 for target duration so is definitely not valid.  Make a valid manifest and it might work

These are the errors we are getting, that need fixing:
Error: Illegal MIME type
--> Detail:  MIME type: application/x-mpegURL
--> Source:  https://jumpvrapi-mscdn-api-stg.azureedge.net/blobpublic-stg/space_mbr/2023/11/02/1048549/43303_1_4868_99b0d12f-d3ba-4e63-afb9-570484e20dc5/hls/43303_1_4868.m3u8

Error: Max extinf duration of 0.07 more than 2 * target duration 0
--> Source:  https://jumpvrapi-mscdn-api-stg.azureedge.net/blobpublic-stg/space_mbr/2023/11/02/1048549/43303_1_4868_99b0d12f-d3ba-4e63-afb9-570484e20dc5/hls/43303_1_4868.m3u8

Error: Media sequence, but no target duration
--> Source:  https://jumpvrapi-mscdn-api-stg.azureedge.net/blobpublic-stg/space_mbr/2023/11/02/1048549/43303_1_4868_99b0d12f-d3ba-4e63-afb9-570484e20dc5/hls/43303_1_4868.m3u8

**Comment by Chris-RH** [comment]
Its most likely that Android is less stringent in HLS protocol requirements.

If your HLS time is below 1 second then EXT-X-TARGETDURATION is 0. This results in an invalid condition that prevents HLS players from working.
From RFC 8216:
"The EXT-X-TARGETDURATION tag specifies the maximum Media Segment duration. The EXTINF duration of each Media Segment in the Playlistfile, when rounded to the nearest integer, MUST be less than or equal to the target duration; longer segments can trigger playback stalls or other errors."
[​https://tools.ietf.org/html/rfc8216#page-22](https://tools.ietf.org/html/rfc8216#page-22)
When EXT-X-TARGETDURATION is 0 then the condition, "MUST be less than or equal to the target duration", is never met.
In these conditions the capital word "MUST" implies that the requirement to "be less than or equal to the target duration" is a higher priority than "rounded to the nearest integer" and therefore represents a special case.

Increasing EXT-X-TARGETDURATION:0 to EXT-X-TARGETDURATION:1 should hopefully be enough to fix those errors.
