### ISSUE TITLE
Issues playing AVI with multiple video tracks

### ISSUE THREAD

**Issue by artsung410** [RenderHeads/UnityPlugin-AVProVideo#1740]
**Question**

Hello,
We are a company developing a PC app using your assets.
I am writing to inquire about an issue we encountered while testing with the demo version of AV Player for Windows.
There are AVI files that have more than one video channel.
For example, a dashboard cam video file is a single file, but within the video, there are separate channels for the front and rear views.
We set up the player using the demo version to play a 2-channel video, but the video from the second channel does not play.
Is there a specific method to address this?

**Comment by Chris-RH** [comment]
It should work, but only playing one video at a time.  It might be that MP4 format works and AVI doesn't?

Are you able to send us a sample video please? unitysupport@renderheads.com

**Comment by artsung410** [comment]
The video file was sent to you by email. 
I would really appreciate it if you could check it out.

**Comment by Chris-RH** [comment]
Video works as expected after being converted to mp4.
Further info sent via email.
