### ISSUE TITLE
Video Encoding for Android playback

### ISSUE THREAD

**Issue by Gurwar** [RenderHeads/UnityPlugin-AVProVideo#1741]
Problem description:

Our team is working on 360 VR videos and we are having trouble with getting some of the 
videos to play using AV Pro. We are experimenting with h264 and h265. Videos using h264
are working properly whereas videos encoded with h265 are giving inconsistent results.

Can you give us some pointers on how to encode the videos to get them consistently working?

![Video Specs](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/43031012/4965f395-85e7-46b5-af8a-dda5d9026c48)

Device (which devices are you having the issue with - model, OS version number):

Quest 2

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

5760x2880 at 30fps

System Information:

AVPro Video: v2.9.1 (plugin v2.8.5f1-ultra)
Target Platform: Android
Unity: v2021.3.17f1 WindowsEditor
OS: Desktop - B550M DS3H AC (Gigabyte Technology Co., Ltd.) - Windows 11  (10.0.22631) 64bit - English
CPU: AMD Ryzen 5 5600X 6-Core Processor  - 12 threads - 32691KB
GPU: NVIDIA GeForce RTX 3080 - NVIDIA - Direct3D 11.0 [level 11.1] - 10067KB - 16384

**Comment by Chris-RH** [comment]
I would lean towards the guidelines from these websites.  Remember that they are maximums, so if you have other stuff going on, then you need to reduce your video specs.  Its not just about resolution and FPS; for example, you need to pay attention to things like bitrate too.

https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/
https://headjack.io/knowledge-base/best-video-resolution-for-oculus-quest-2/
