### ISSUE TITLE
OPENGL NATIVE PLUG-IN ERROR on HTC Vive XR Elite

### ISSUE THREAD

**Issue by DaveXR** [RenderHeads/UnityPlugin-AVProVideo#1742]
**Describe the issue**
Video does not play on Vive XR Elite. Audio does play. We get a transparent (can see the default 'horizon') visual. See log dump below.

Note this same content works on other XR devices such as the Quest family and Pico devices

**My Setup:**
 - Unity version: 2021.3.2
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  Latest non-trial
 - Operating system version: Windows 10
 - Device model: Vive XR Elite
 - Video specs (resolution, frame-rate, codec, file size): Any (tried many)

**To Reproduce**
1. Get a video to run on any other platform. Note we're using 360 video but none of them worked (that we tried)
2. Try it on Vive's XR Elite headset
3. See (or not in this case) the results. 

**Logs**
01-23 11:01:35.425   779  1170 D WVCdm   : Instantiating CDM.
01-23 11:01:35.425  1121  5034 I AVProVideo: Video Loading: jar|zip|obb
01-23 11:01:35.436  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.442  1733  3649 I SER_SERDriver: [CR1_pose_cb][714802,714803] ch=1, devId=1, role=2(L1R2), status=9, result=200, using=true, pose:0.30671388,-0.3096919,-0.12719053/0.08832253,0.064152114,-0.99303716,-0.04428188 @ 1.1628929E7,pose_ts=11628928576000
01-23 11:01:35.443  1121  5506 W VideoCapabilities: Unsupported mime image/vnd.android.heic
01-23 11:01:35.445  1121  5506 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
01-23 11:01:35.445  1121  5506 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
01-23 11:01:35.452  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.457  1121  5507 D MediaCodecInfo: NoSupport [sizeAndRate.support, 4096x2048x29.999887466430664] [c2.android.avc.decoder, video/avc] [kona, VIVE XR Series, HTC, 29]
01-23 11:01:35.460  1121  5513 I OMXClient: IOmx service obtained
01-23 11:01:35.460   905  1901 I OMXMaster: makeComponentInstance(OMX.qcom.video.decoder.avc) in android.hardwar process
01-23 11:01:35.460  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.466  1121  5515 I OMXClient: IOmx service obtained
01-23 11:01:35.466   905  1901 E         : Service not available yet
01-23 11:01:35.466   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.466   550   550 I hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.capabilityconfigstore@1.0::ICapabilityConfigStore/default in either framework or device manifest.
01-23 11:01:35.466   905  1901 D PlatformConfig: getConfigStoreBool: unable to get configstore service
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32 Config name: vidc_dec_log_in value: 0
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32 Config name: vidc_dec_log_out value: 0
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32 Config name: vidc_dec_sec_prefetch_size_internal value: 209715200
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32 Config name: vidc_dec_sec_prefetch_size_output value: 13434880
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32 Config name: vidc_perf_control_enable value: 0
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32 Config name: vidc_dec_thumbnail_yuv_output value: 0
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32: Returning default
01-23 11:01:35.470   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.470   905  1901 D PlatformConfig: getInt32 Config name: vidc_dec_output_rate value: 120
01-23 11:01:35.470   905  1901 I OMX-VDEC-1080P: component_init: OMX.qcom.video.decoder.avc : fd=8
01-23 11:01:35.470   905  1901 E OMX-VDEC-1080P: Unsupported output color format for c2d (2141391876)
01-23 11:01:35.470   905  1901 E OMX-VDEC-1080P: Setting color format failed
01-23 11:01:35.470  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.473   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.473   905  1901 D PlatformConfig: getInt32: Returning default
01-23 11:01:35.473   905  1901 D PlatformConfig: getInstance: Enter
01-23 11:01:35.473   905  1901 D PlatformConfig: getInt32: Returning default
01-23 11:01:35.473   905  1901 I OMX-VDEC-1080P: omx_vdec::component_init() success : fd=8
01-23 11:01:35.473   905  1898 I OMXMaster: makeComponentInstance(OMX.qcom.video.decoder.avc) in android.hardwar process
01-23 11:01:35.475  1121  5511 D SurfaceUtils: connecting to surface 0x755712c010, reason connectToSurface
01-23 11:01:35.475  1121  5511 I MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 1147908
01-23 11:01:35.475  1121  5511 D SurfaceUtils: disconnecting from surface 0x755712c010, reason connectToSurface(reconnect)
01-23 11:01:35.475  1121  5511 D SurfaceUtils: connecting to surface 0x755712c010, reason connectToSurface(reconnect)
01-23 11:01:35.476   905  1901 E OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
01-23 11:01:35.476   905  1901 E OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
01-23 11:01:35.476   905  1901 E OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
01-23 11:01:35.476   905  1901 E OMX-VDEC-1080P: get_parameter: unknown param 7f000046
01-23 11:01:35.476   905  1901 E OMXNodeInstance: getParameter(0xebf92944:qcom.decoder.avc, ??(0x7f000046)) ERROR: UnsupportedIndex(0x8000101a)
01-23 11:01:35.476   905  1901 E OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x7f00005d
01-23 11:01:35.476   905  1901 E OMXNodeInstance: setParameter(0xebf92944:qcom.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
01-23 11:01:35.476   905  1901 E OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
01-23 11:01:35.477  1121  5513 I ExtendedACodec: setupVideoDecoder()
01-23 11:01:35.478  1121  5513 I ExtendedACodec: Decoder will be in frame by frame mode
01-23 11:01:35.478   905  1901 E OMX-VDEC-1080P: Setparameter: unknown param 2130706434
01-23 11:01:35.478   905  1901 E OMX-VDEC-1080P: set_parameter: Error: 0x8000101a, setting param 0x7f000002
01-23 11:01:35.478   905  1901 E OMXNodeInstance: setParameter(0xebf92944:qcom.decoder.avc, ??(0x7f000002)) ERROR: UnsupportedIndex(0x8000101a)
01-23 11:01:35.478  1121  5513 W ExtendedACodec: Failed to set frame packing format on component
01-23 11:01:35.479   905  1103 E OMXNodeInstance: getConfig(0xebf92944:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
01-23 11:01:35.481   905  1898 E         : Service not available yet
01-23 11:01:35.482  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.482   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.483   550   550 I hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.capabilityconfigstore@1.0::ICapabilityConfigStore/default in either framework or device manifest.
01-23 11:01:35.483   905  1898 D PlatformConfig: getConfigStoreBool: unable to get configstore service
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32 Config name: vidc_dec_log_in value: 0
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32 Config name: vidc_dec_log_out value: 0
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32 Config name: vidc_dec_sec_prefetch_size_internal value: 209715200
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32 Config name: vidc_dec_sec_prefetch_size_output value: 13434880
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32 Config name: vidc_perf_control_enable value: 0
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32 Config name: vidc_dec_thumbnail_yuv_output value: 0
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32: Returning default
01-23 11:01:35.485   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.485   905  1898 D PlatformConfig: getInt32 Config name: vidc_dec_output_rate value: 120
01-23 11:01:35.486   905  1898 I OMX-VDEC-1080P: component_init: OMX.qcom.video.decoder.avc : fd=11
01-23 11:01:35.486   905  1898 E OMX-VDEC-1080P: Unsupported output color format for c2d (2141391876)
01-23 11:01:35.486   905  1898 E OMX-VDEC-1080P: Setting color format failed
01-23 11:01:35.487   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.487   905  1898 D PlatformConfig: getInt32: Returning default
01-23 11:01:35.487   905  1898 D PlatformConfig: getInstance: Enter
01-23 11:01:35.487   905  1898 D PlatformConfig: getInt32: Returning default
01-23 11:01:35.487   905  1898 I OMX-VDEC-1080P: omx_vdec::component_init() success : fd=11
01-23 11:01:35.488  1121  5510 D SurfaceUtils: connecting to surface 0x76ed36f010, reason connectToSurface
01-23 11:01:35.488  1121  5510 I MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 1147909
01-23 11:01:35.488  1121  5510 D SurfaceUtils: disconnecting from surface 0x76ed36f010, reason connectToSurface(reconnect)
01-23 11:01:35.488  1121  5510 D SurfaceUtils: connecting to surface 0x76ed36f010, reason connectToSurface(reconnect)
01-23 11:01:35.489   905  1898 E OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
01-23 11:01:35.489   905  1898 E OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
01-23 11:01:35.489   905  1898 E OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
01-23 11:01:35.489   905  1898 E OMX-VDEC-1080P: get_parameter: unknown param 7f000046
01-23 11:01:35.489   905  1898 E OMXNodeInstance: getParameter(0xebcb7f84:qcom.decoder.avc, ??(0x7f000046)) ERROR: UnsupportedIndex(0x8000101a)
01-23 11:01:35.490   905  1898 E OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x7f00005d
01-23 11:01:35.490   905  1898 E OMXNodeInstance: setParameter(0xebcb7f84:qcom.decoder.avc, OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
01-23 11:01:35.490   905  1898 E OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
01-23 11:01:35.490  1121  5515 I ExtendedACodec: setupVideoDecoder()
01-23 11:01:35.490   905  1901 E OMX-VDEC-1080P: Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
01-23 11:01:35.490  1121  5513 D SurfaceUtils: set up nativeWindow 0x755712c010 for 2048x1024, color 0x7fa30c06, rotation 0, usage 0x20002900
01-23 11:01:35.491  1121  5515 I ExtendedACodec: Decoder will be in frame by frame mode
01-23 11:01:35.491   905 31840 E OMX-VDEC-1080P: Setparameter: unknown param 2130706434
01-23 11:01:35.491   905 31840 E OMX-VDEC-1080P: set_parameter: Error: 0x8000101a, setting param 0x7f000002
01-23 11:01:35.491   905 31840 E OMXNodeInstance: setParameter(0xebcb7f84:qcom.decoder.avc, ??(0x7f000002)) ERROR: UnsupportedIndex(0x8000101a)
01-23 11:01:35.491  1121  5515 W ExtendedACodec: Failed to set frame packing format on component
01-23 11:01:35.493   905  1898 E OMXNodeInstance: getConfig(0xebcb7f84:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
01-23 11:01:35.493  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.503  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.503   905  1898 E OMX-VDEC-1080P: Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
01-23 11:01:35.503  1121  5515 D SurfaceUtils: set up nativeWindow 0x76ed36f010 for 4096x2048, color 0x7fa30c06, rotation 0, usage 0x20002900
01-23 11:01:35.508   905  1103 E OMXNodeInstance: getConfig(0xebf92944:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
01-23 11:01:35.509  1121  5523 I OMXClient: IOmx service obtained
01-23 11:01:35.509   905  1898 I OMXMaster: makeComponentInstance(OMX.google.aac.decoder) in android.hardwar process
01-23 11:01:35.510   905  1898 E OMXNodeInstance: setConfig(0xee420800:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
01-23 11:01:35.510  1121  5523 I ACodec  : codec does not support config priority (err -2147483648)
01-23 11:01:35.511   905  1898 E OMX-VDEC-1080P: Extension: OMX.QTI.index.config.video.getdsmode not implemented
01-23 11:01:35.511   905  1901 E OMXNodeInstance: setConfig(0xee420800:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
01-23 11:01:35.511  1121  5523 I ACodec  : codec does not support config priority (err -2147483648)
01-23 11:01:35.512   905  1901 E OMXNodeInstance: setConfig(0xee420800:google.aac.decoder, ConfigOperatingRate(0x6f800003)) ERROR: Undefined(0x80001001)
01-23 11:01:35.512  1121  5523 I ACodec  : codec does not support config operating rate (err -2147483648)
01-23 11:01:35.513   905  1898 E OMXNodeInstance: getConfig(0xee420800:google.aac.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
01-23 11:01:35.513  1121  5523 W ExtendedACodec: Failed to get extension for extradata parameter
01-23 11:01:35.514  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.515  1121  5034 I AVProVideo: Changing video size 0x0 to 2048x1024
01-23 11:01:35.515  1121  5064 I RENDER_ATWC: FPS:  Left  56.00
01-23 11:01:35.520  1121  5034 I Unity   : [AVProVideo] Using playback path: ExoPlayer OES (2048x1024@25.00)
01-23 11:01:35.520  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.AndroidMediaPlayer:Update()
01-23 11:01:35.520  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.520  1121  5034 I Unity   : 
01-23 11:01:35.520   905  5525 I SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
01-23 11:01:35.520  1121  5034 I Unity   : [AVProVideo] Texture ID: 395
01-23 11:01:35.520  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.AndroidMediaPlayer:Update()
01-23 11:01:35.520  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.520  1121  5034 I Unity   : 
01-23 11:01:35.525  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.531   769   938 D audio_hw_primary: adev_get_parameters:vr_audio_mode_on
01-23 11:01:35.531   769   938 I audio_hw_primary: getting vr mode to 0
01-23 11:01:35.531   769   938 D audio_hw_primary: adev_get_parameters: exit: returns - vr_audio_mode_on=false
01-23 11:01:35.531   814  4821 I hash_map_utils: key: 'vr_audio_mode_on' value: ''
01-23 11:01:35.532   814  4821 I AudioPolicyManagerCustom: VR mode is 0, switch to primary output if request is for fast|raw
01-23 11:01:35.532   814  4821 D AudioFlinger: Client defaulted notificationFrames to 7688 for frameCount 15376
01-23 11:01:35.532   814  4821 D AF::TrackHandle: OpPlayAudio: track:113 usage:1 not muted
01-23 11:01:35.537   905  1898 E OMXNodeInstance: getConfig(0xebcb7f84:qcom.decoder.avc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
01-23 11:01:35.539   905  1898 E OMX-VDEC-1080P: Extension: OMX.QTI.index.config.video.getdsmode not implemented
01-23 11:01:35.539  1121  5034 I AVProVideo: Changing video size 0x0 to 4096x2048
01-23 11:01:35.541  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.543  1121  5034 I Unity   : Media player event MetaDataReady
01-23 11:01:35.543  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.543  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.543  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.543  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
01-23 11:01:35.543  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.543  1121  5034 I Unity   : 
01-23 11:01:35.547  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.550  1121  5034 I Unity   : [AVProVideo] Using playback path: ExoPlayer OES (4096x2048@30.00)
01-23 11:01:35.550  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.AndroidMediaPlayer:Update()
01-23 11:01:35.550  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.550  1121  5034 I Unity   : 
01-23 11:01:35.550  1121  5034 I Unity   : [AVProVideo] Texture ID: 396
01-23 11:01:35.550  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.AndroidMediaPlayer:Update()
01-23 11:01:35.550  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.550  1121  5034 I Unity   : 
01-23 11:01:35.550  1121  5034 I Unity   : Media player event ReadyToPlay
01-23 11:01:35.550  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.550  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.550  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.550  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
01-23 11:01:35.550  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.550  1121  5034 I Unity   : 
01-23 11:01:35.551  1121  5034 I Unity   : Media player event FirstFrameReady
01-23 11:01:35.551  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.551  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.551  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.551  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
01-23 11:01:35.551  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.551  1121  5034 I Unity   : 
01-23 11:01:35.552  1121  5034 I Unity   : Global timer paused at : 0 seconds
01-23 11:01:35.552  1121  5034 I Unity   : Strivr.Player.Controllers.MainHandlerController:PauseGlobalTimer()
01-23 11:01:35.552  1121  5034 I Unity   : Strivr.Player.Controllers.ClipController:StartClipFromBeginning()
01-23 11:01:35.552  1121  5034 I Unity   : Strivr.Player.Controllers.VideoPlayerController:OnFirstFrameReady()
01-23 11:01:35.552  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.552  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.552  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.552  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
01-23 11:01:35.552  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.552  1121  5034 I Unity   : 
01-23 11:01:35.554  1121  5034 I Unity   : Media player event ResolutionChanged
01-23 11:01:35.554  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.554  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.554  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.554  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
01-23 11:01:35.554  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.554  1121  5034 I Unity   : 
01-23 11:01:35.554  1121  5034 I Unity   : Media player event StartedSeeking
01-23 11:01:35.554  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.554  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.554  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.554  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
01-23 11:01:35.554  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.554  1121  5034 I Unity   : 
01-23 11:01:35.558  1121  5064 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state
01-23 11:01:35.561  1121  5034 I Unity   : Media player event FinishedSeeking
01-23 11:01:35.561  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.561  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.561  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.561  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateEvents()
01-23 11:01:35.561  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.561  1121  5034 I Unity   : 
01-23 11:01:35.561  1121  5034 I Unity   : Media player event FinishedBuffering
01-23 11:01:35.561  1121  5034 I Unity   : Strivr.Player.Presentation.VideoPlayerBehaviour:OnMediaPlayerEvent(MediaPlayer, EventType, ErrorCode)
01-23 11:01:35.561  1121  5034 I Unity   : UnityEngine.Events.UnityEvent`3:Invoke(T0, T1, T2)
01-23 11:01:35.561  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:FireEventIfPossible(EventType, Boolean)
01-23 11:01:35.561  1121  5034 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
01-23 11:01:35.561  1121  5034 I Unity   : 
01-23 11:01:35.563  1121  1121 V MediaRouter: Selecting route: ********
01-23 11:01:35.565   814  1128 W AudioFlinger: moveEffectChain_l() effect chain for session 0 not on source thread 0x7934d0be40
01-23 11:01:35.566   769 10957 D audio_hw_primary: start_output_stream: enter: stream(0xe62c6800)usecase(0: deep-buffer-playback) devices(0x2) is_haptic_usecase(0)

**Comment by DaveXR** [comment]
Note: I was building with Single Pass. Switching to Multi Pass runs the video. I've not measured the hit to performance yet.

**Comment by Chris-RH** [comment]
The HTC Vive XR Elite uses the Qualcomm Snapdragon XR2 processor, which is the same as the Quest 2 and Pico Neo 3, so you'd expect them to behave the same.

1. Can you repeat it in a new project using just the AVPro Video demo scenes?
2. Are you using SRP, URP or HDRP?
3. In Player/Other Settings, is "Default Orientation" set to "Auto-Rotate"?
4. Are you using OES video rendering mode?
5. Are you using the Update Stereo Multipass component (https://renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html)

**Comment by DaveXR** [comment]
Hi.
The issue seemed to be we were using Single Pass rendering. Changing to
multipass got around it. We have yet to measure the performance hit though.
