### ISSUE TITLE
[2.9.1] Incorrect date returned on HLS video on Mac / iOS through mediaPlayer.Control.GetProgramDateTime() API

### ISSUE THREAD

**Issue by KikiLebrun** [RenderHeads/UnityPlugin-AVProVideo#1745]
Hello we still have the same error on last versions !
Describe the issue
Cannot get value of HLS live streaming's through mediaPlayer.Control.GetProgramDateTime() API.
This method sometimes returns the correct value, and sometimes returns 2001/01/01.

Your Setup (please complete the following information):

Unity version: 2022.3.11f1
AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.1, ultra edition
Operating system version: MacOS 14.2.1 & iOS 17.2.1 (also tested on other macs and other iphones)
Device model: Macbook Pro & iPhone 13 Pro
Video specs (resolution, frame-rate, codec, file size): any resolution, HLS streaming
To Reproduce

Open attached zip folder
Unzip it, and open in Unity
Open the sample Demo_MediaPlayer scene, where we changed the video to our video stream
Press play, and look at the logs given by the script attached to the MediaPlayer gameobject.
Drag the slider at the begining, force it several times (reproduce several times until you get different results)
Logs
Debug.Log(mediaPlayer.Control.GetProgramDateTime());
// -> sometimes returns the correct value (2021-12-10-...), sometimes returns 2001-01-01

**Comment by MorrisRH** [comment]
Linking #1305

**Comment by MorrisRH** [comment]
Thanks for the demonstration video, I was unable to reproduce the issue prior to watching it.

I have fixed the issue. You will still get a date of 2001-01-01 output when seeking to the very beginning or end of the stream but it will now correct itself when playback resumes post-seek.

**Comment by Chris-RH** [comment]
AVPro Video version 2.9.2 has been release.  Please let us know if this has not fixed your issue.
