### ISSUE TITLE
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

### ISSUE THREAD

**Issue by ostasyk-ameria** [RenderHeads/UnityPlugin-AVProVideo#1749]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3
 - AVPro Video version 1.11.7
 - Operating system version: Windows 10
 - Device model: Dell Optiplex XE2
 - Video specs (resolution, frame-rate, codec, file size): 
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Video resolution: 2160x1920
Frame rate: 25
File size: 24.6 MB

**To Reproduce**
1.  File is at path /Assets/StreamingAssets/Videos/1.1_v10_IdleC_de.mp4
2.  Open file via OpenVideoFromFile (location, path, false) where:
location is MediaPlayer.FileLocation.RelativeToStreamingAssetsFolder
autoplay is off
3.  Listen for event MediaPlayerEvent.EventType.ReadyToPlay 
and start play via function Play()
4.  Listen for event MediaPlayerEvent.EventType.FinishedPlaying
and do Stop() and after CloseVideo()

5. After we destroy player and display

// remove listener
_mediaPlayer.Events.RemoveListener(OnMediaPlayerEvent);
// destroy the media player
if (_mediaDisplay._mediaPlayer != null)
{
    GameObject.Destroy(_mediaDisplay._mediaPlayer.gameObject);
     _mediaDisplay._mediaPlayer = null;
}
_mediaPlayer = null; 
// destroy the display object
GameObject.Destroy(_mediaDisplay.gameObject);
_mediaDisplay = null;

6. After we create new player and display

// create new media player
string playerName = $"MediaPlayer ({_count})";
Debug.Log("MediaPlayer: create player with name: " + playerName);
GameObject newMediaPlayerGameObject = new GameObject(playerName);
newMediaPlayerGameObject.transform.parent = _playerContainer.transform;
MediaPlayer newMediaPlayer = newMediaPlayerGameObject.AddComponent<MediaPlayer>();
newMediaPlayer.m_AutoOpen = false;
newMediaPlayer.m_AutoStart = false;
newMediaPlayer.m_Loop = false;
newMediaPlayer.PlatformOptionsWindows.useLowLatency = true;

 // create new game object
 string displayName = $"MediaDisplay ({_count})";
 Debug.Log("MediaPlayer: create display with name: " + displayName);
 GameObject newGuiGameObject = new GameObject(displayName);
 newGuiGameObject.transform.parent = _displayContainer.transform;
 newGuiGameObject.layer = _displayContainer.layer;
 newGuiGameObject.SetActive(false);

 // add components
 newGuiGameObject.AddComponent<RectTransform>();
 newGuiGameObject.AddComponent<CanvasRenderer>();

 // add DisplayUGUI component
 DisplayUGUI newGuiObject = newGuiGameObject.AddComponent<DisplayUGUI>();
 newGuiObject._mediaPlayer = newMediaPlayer;
 newGuiObject._scaleMode = ScaleMode.ScaleToFit;
 newGuiObject.rectTransform.anchorMin = _displayRectTransform.anchorMin;
 newGuiObject.rectTransform.anchorMax = _displayRectTransform.anchorMax;
 newGuiObject.rectTransform.anchoredPosition = _displayRectTransform.anchoredPosition;
 newGuiObject.rectTransform.sizeDelta = _displayRectTransform.sizeDelta;
 newGuiObject.rectTransform.pivot = _displayRectTransform.pivot;
 newGuiObject.rectTransform.localScale = _displayRectTransform.localScale;
 newGuiObject.rectTransform.localRotation = _displayRectTransform.localRotation;

 newGuiObject._noDefaultDisplay = false;
 newGuiObject.raycastTarget = false;
 newGuiObject.material = _displayMaterial;
 newGuiObject.color = new Color(1f, 1f, 1f, 0f);

 newGuiObject._mediaPlayer = newMediaPlayer;
 _mediaDisplay = newGuiObject;

 _mediaPlayer = newMediaPlayer;
 _mediaPlayer.Events.AddListener(OnMediaPlayerEvent);

 newGuiGameObject.SetActive(true);

7. After we repeat pt.1

We can't use loops because we have different videos and we have different queue of videos
(one videos repeats, another no)

**Logs**
28.01.2024 11:13:46:7699 [Log]: [AVProVideo] Opening C:/Agent/PRD/Packages/Resources/dev/App_WIN_Data/StreamingAssets/Videos/1.1_v11_IdleA_de.mp4 (offset 0) with API MediaFoundation
28.01.2024 11:13:46:7759 [Log]: Play video at path: Videos/1.1_v11_IdleA_de.mp4
28.01.2024 11:13:46:7759 [Log]: MediaPlayerEvent: event: StartedBuffering	 error: None
28.01.2024 11:13:46:8048 [Log]: [AVProVideo] Using playback path: MF-MediaEngine-Hardware (2160x1920@25.00)
28.01.2024 11:13:46:8048 [Log]: MediaPlayerEvent: event: MetaDataReady	 error: None
28.01.2024 11:13:46:8048 [Log]: MediaPlayerEvent: event: ReadyToPlay	 error: None
28.01.2024 11:13:46:8048 [Log]: MediaPlayer:  Prepared. Playing...
28.01.2024 11:13:46:8048 [Log]: MediaPlayerEvent: event: Started	 error: None
28.01.2024 11:13:46:8048 [Log]: MediaPlayerEvent: event: ResolutionChanged	 error: None
28.01.2024 11:13:46:8048 [Log]: MediaPlayerEvent: event: FinishedBuffering	 error: None
28.01.2024 11:13:46:8938 [Log]: MediaPlayerEvent: event: FirstFrameReady	 error: None
28.01.2024 11:13:47:3912 [Log]: MediaPlayerEvent: event: Closing	 error: None
28.01.2024 11:13:47:3982 [Log]: MediaPlayer: DestroyAll
28.01.2024 11:13:47:3992 [Log]: MediaPlayer: RebuildAll
28.01.2024 11:13:47:3992 [Log]: MediaPlayer: create player with name: MediaPlayer (574)
28.01.2024 11:13:47:3992 [Log]: MediaPlayer: create display with name: MediaDisplay (574)
28.01.2024 11:14:16:4938 [Log]: [AVProVideo] Opening C:/Agent/PRD/Packages/Resources/dev/App_WIN_Data/StreamingAssets/Videos/1.1_v11_IdleA_de.mp4 (offset 0) with API MediaFoundation
28.01.2024 11:14:16:4988 [Log]: Play video at path: Videos/1.1_v11_IdleA_de.mp4
28.01.2024 11:14:16:4998 [Log]: MediaPlayerEvent: event: StartedBuffering	 error: None
28.01.2024 11:14:16:5338 [Log]: [AVProVideo] Using playback path: MF-MediaEngine-Hardware (2160x1920@25.00)
28.01.2024 11:14:16:5348 [Log]: MediaPlayerEvent: event: MetaDataReady	 error: None
28.01.2024 11:14:16:5348 [Log]: MediaPlayerEvent: event: ReadyToPlay	 error: None
28.01.2024 11:14:16:5348 [Log]: MediaPlayer:  Prepared. Playing...
28.01.2024 11:14:16:5348 [Log]: MediaPlayerEvent: event: Started	 error: None
28.01.2024 11:14:16:5348 [Log]: MediaPlayerEvent: event: ResolutionChanged	 error: None
28.01.2024 11:14:16:5348 [Log]: MediaPlayerEvent: event: FinishedBuffering	 error: None
28.01.2024 11:14:16:5688 [Error]: [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
28.01.2024 11:14:16:5688 [Log]: MediaPlayerEvent: event: Error	 error: LoadFailed

**Screenshots**
After error is happened - shows only white screen.

**Videos**
I can't attach sample video file because it's more than 10МВ

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, please note that AVPro Video version 1 has been depreciated for over 3 years now and is no longer supported or updated.

I would suggest trying the video in one of the demo scenes first.  
You can also send us the video or URL to unitysupport@renderheads.com

**Comment by ostasyk-ameria** [comment]
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/44406435/cb81c3da-84a9-4159-9b52-51994590b435

Added sample of video

**Comment by ostasyk-ameria** [comment]
Video plays in this case 574 (sometimes more) times normal, but after this error happens.

**Comment by Chris-RH** [comment]
Are all of your videos the same codec/resolutions/FPS/bitrate/length as the one provided?
Do they go in a set order or can the user choose which video to play?

**Comment by ostasyk-ameria** [comment]
Hello.

1. All videos have:
- same codec h.264, but different profiles High@L5 and Main@L5
- same resolution 2160x1920
- same FPS 25
- almost same bitrate about 8Mbps
- different length
2. Videos go in different order (we can't use loops)
3. We are playing one video at a time
4. Unity app process shows: CPU about 60-70%, GPU about 40%, RAM is 400-600 MB (have about 4GB free of 16GB)

You can reproduce this bug via playing one video many times (more than 500 times as we described).

Thanks.

**Comment by Chris-RH** [comment]
I can't reproduce it here

You could try using DirectShow
Can you reproduce it in a new project, only running AVPro Video?
Have you tried Garbage collection?

**Comment by Chris-RH** [comment]
Any luck?

**Comment by ostasyk-ameria** [comment]
Hello.
Sorry for delay.

If we use DirectShow - app freezes!
We don't use it!
We use: Media Foundation API

Yes, we tried to use Garbage Collection as
```
Resources.UnloadUnusedAssets();
System.GC.Collect();
```
and it didn't help.

I created simple project for our needs to avoid other code influence - no luck!

Thanks
