### ISSUE TITLE
Stereo panning in VR of HLS video stream on Android not working

### ISSUE THREAD

**Issue by thekrix** [RenderHeads/UnityPlugin-AVProVideo#175]
Problem description:

I am currently evaluating your product  for a Unity VR prototype running on
Oculus Quest – developed on Windows 10. I am streaming HLS videos
successfully on both platforms but I am having problems with the audio
orientation (stereo panning) on Android when running on the Oculus Quest. 
Whatever I do I cannot get the video stream to be oriented in 3D space. 
It is always playing direct to left right channels.  I do not need audio spatialization. 
Simple stereo panning based on camera orientation is enough. Your manual
indicates that this is possible. 

How do I set this up? I know that Audio redirect is only supported on Windows
and this is working but I do not need that feature on Android.
Just basic stereo panning.

Thank you very much for any help you can give.

Device (which devices are you having the issue with - model, OS version number):

Oculus Quest

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

Any HLS video streams. 

System Information:

AVPro Video: plugin v1.9.17t scripts v1.10.0
Target Platform: Android
Unity: v2019.2.2f1 WindowsEditor
OS: Desktop - Default string (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz - 12 threads - 65372KB
GPU: NVIDIA GeForce RTX 2080 Ti - NVIDIA - Direct3D 11.0 [level 11.1] - 11048KB - 16384

**Comment by thekrix** [comment]
Hi Andrew!

Thanks for getting back to me. Yes, I can use the SetBalance property to adjust the audio position. I will manually calculate the balance based on audio/gameobject position and camera position/orientation. 

I was hoping there was something a bit more "automatic". Any chance you will add android support to redirect audio into Unity any time soon? 

Cheers
Chris

**Comment by RenderHeadsSte** [comment]
This is something in the roadmap, but it is not in development yet and we don't have a date as to when it will start.

**Comment by MCrawley1** [comment]
> Hi Andrew!
> 
> Thanks for getting back to me. Yes, I can use the SetBalance property to adjust the audio position. I will manually calculate the balance based on audio/gameobject position and camera position/orientation.
> 
> I was hoping there was something a bit more "automatic". Any chance you will add android support to redirect audio into Unity any time soon?
> 
> Cheers
> Chris

Just wondering if you ever achieved this, as I'm also having the same issues?

**Comment by RenderHeadsSte** [comment]
In v2.x of AVPRo Video we support audio piping into Unity @MCrawley1
