### ISSUE TITLE
Adding depth map on inside-out sphere shader for VR

### ISSUE THREAD

**Issue by AntonioStissi** [RenderHeads/UnityPlugin-AVProVideo#1750]
Hello,
I am experimenting with ai-generated depth maps on videos and I was wondering, is it possible to add the support for depth map in the inside-out sphere shader for VR?
The source frame for the depth-map could be either from the same video (e.g. mapping the left part as main texture and the right part as depth map) or even a separate video using two mediaplayer+applytomesh components, pointing to main texture and depth map parameter respectively.
I think the second solution would be preferable since it would be possible to have a different, lower, resolution for the the depth map.

Do you have anything like this planned or could you give me some advice on how to develop this myself?

Thanks!
Antonio

**Comment by Chris-RH** [comment]
Hi Antonio, 

It’s a very niche thing, so its very unlikely that we would add support for it.  However you are to modify the shader as you like.

In theory it should be quite straight forward, add the depth texture, do the lookup as for the main texture and write out the depth value.  It might look a little odd at the top and bottom where there will be a little less information.  Cube map might work better, but the edge seams may look weird.
