### ISSUE TITLE
program stuck when playing VP9 encoded videos

### ISSUE THREAD

**Issue by PyoDeaSa** [RenderHeads/UnityPlugin-AVProVideo#1752]
Problem description:

After the Windows update, 
the program will get stuck when playing VP9 encoded videos.

Device (which devices are you having the issue with - model, OS version number):

Windows10 & Windows11

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

video codec: VP9
video resolution: 7200*8100

System Information:

AVPro Video: v2.5.2 (plugin v2.5.2f2-core)
Target Platform: Standalone
Unity: v2021.3.16f1 WindowsEditor
OS: Desktop - 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16218 MB) - Windows 11  (10.0.22621) 64bit
CPU: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz - 16 threads - 16218KB
GPU: NVIDIA GeForce GTX 1650 - NVIDIA - Direct3D 11.0 [level 11.1] - 3950KB - 16384

**Comment by Chris-RH** [comment]
2.5.2 is 18 months old. Please update to the latest version and retest
