### ISSUE TITLE
Video is cut off at the top and bottom

### ISSUE THREAD

**Issue by Vah94** [RenderHeads/UnityPlugin-AVProVideo#1753]
After changing the video using the code more than twice, the video is cut off at the top and bottom

 - Unity version: 2023.2.7f1, 2021.3.19f1
 - AVPro Video version 2.9.1
 - Operating system version: Windows, Android
 - Device model: PC

**To Reproduce**
Just open and use AvPro in canvas

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/42799443/0429ebc6-53af-4d2e-bdff-a2ae2f4dcbb0)

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/42799443/b570e4e4-db7b-4dbc-8376-b734c697d7cc

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/42799443/42ba3786-f675-4df9-b77c-8462bb3855be)

**Comment by Chris-RH** [comment]
Hi, If you use the Display UGUI or Display IMGUI components then they have scaling options that you can use.  This is useful when you are using media of different resolutions.

**Comment by Vah94** [comment]
@Chris-RH It's not about the resolution of the video. 
I have the same video playing in AVPro, but sometimes the screen shows only CROPPED video with black patches on the top and bottom (like in the above example). The top and bottom parts of the video covered by the black patches are not visible, so rescaling the screen wouldn't be very useful.

**Comment by Chris-RH** [comment]
Could you please send a simple, reproducible project to unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Could you please send a simple, reproducible project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Chris-RH** [comment]
It doesn't need to be anything fancy.  Just absolute minimum fresh project with just AVPro Video.  You could start with the demo scenes and make as little adjustment as needed to show how the issue is occurring :)

**Comment by Chris-RH** [comment]
Closing due to lack of response
