### ISSUE TITLE
GetSeekableTimes() doesn't work when opening a file in Android with "File Offset"

### ISSUE THREAD

**Issue by lucas-martinic** [RenderHeads/UnityPlugin-AVProVideo#1754]
**Describe the issue**
I'm using file offset in android to protect my video, but I can't get seekable times anymore after I implemented that. I get the times without error but MinTime/MaxTime return 0.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.8f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core Android 2.9.1
 - Operating system version: 
 - Device model: Meta Quest 3
 - Video specs (resolution, frame-rate, codec, file size): 8K 360 mp4

**To Reproduce**
1. Setup a 360 video sphere
2. Add an offset of bytes to 360 mp4
3. Open the video with File Offset (which works great). Not possible to get Seekable Times to forward or rewind the movie. MaxTime returns 0.

**Comment by Chris-RH** [comment]
Resolved using Exoplayer instead of Android Mediaplayer.
