### ISSUE TITLE
When i use _mediaPlayer.Info.GetDuration() the return value is 0 or infinity on Android and i can't scrub

### ISSUE THREAD

**Issue by KevinLachance** [RenderHeads/UnityPlugin-AVProVideo#1755]
Describe the issue
In my app i can't scrub in a video the return value of _mediaPlayer.Info.GetDuration() it's 0 or infinty on Android. I use AVPro 2.2.3 but i have the same error on the latest version 2.9.1

**Your Setup (please complete the following information):**
 - Version 2021.3.24
 - AVPro Video Ultra Edition 2.2.3
 - Android 
 - Video specs (resolution, frame-rate, codec, file size): 854x480,25,mp4  

Repro:
1. Add the url on the media player and play in editor or build the app
2. The return value in editor is infinity and in a android build it's 0

Result in Editor:
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/126600481/53ace56c-f99c-4e59-a591-abe3b3666365)

Settings i use:
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/126600481/cf2ebd74-f0c6-47ed-968a-a5a734d98f88)
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/126600481/c3b14614-8bf2-41cb-b1ec-ada041eb8631)

I will send you the url at unitysupport@renderheads.com

Thx for the help.

**Comment by Chris-RH** [comment]
The video provided had been encoded in such a way that the audio and video tracks are interleaved in chunks.  I re-encoded it so that it was fully interleaved, and it plays fine now.
