### ISSUE TITLE
New Unity versions

### ISSUE THREAD

**Issue by Rietmon** [RenderHeads/UnityPlugin-AVProVideo#1756]
Hi. In the asset description you wrote supported versions are 2019.x-2021.x, what about later versions? When I trying to compile android build with 2023.2.x it throw build exception .aar files is requiring 33 version but I would to use 32 version (Oculus Store requirements). Have you plans to support new versions and when?

**Comment by Chris-RH** [comment]
Exoplayer requires Android SDK 33, which does not come with this version of Unity. In Player Settings|Other Settings, set Target API Level to Android 13.0 (API level 33) and Unity should download the correct SDK when you build. The SDK will be downloaded to Editor/Data/PlaybackEngines/AndroidPlayer/SDK/platforms/.

If you need to target a lower version of Android, then you need to add a custom gradle property. In Player Settings|Publisher Settings, enable the Custom Main Gradle Template and Custom Launcher Gradle Template options. The templates are found at: /Assets/Plugins/Android/mainTemplate.gradle and /Assets/Plugins/Android/launcherTemplate.gradle and they should be edited by adding the following lines:

minSdkVersion 22
targetSDKversion 32
compileSDKversion 33
