### ISSUE TITLE
HLS stream has no audio on MAC devices

### ISSUE THREAD

**Issue by ZisisTsatsas** [RenderHeads/UnityPlugin-AVProVideo#1762]
**Describe the issue**
Using an online encoding service called Bitmovin to encode and generate HLS manifests and streams to be used in our unity application. Previously we were using Azure Media Service.
The problem we have is that when using the attached .m3u8 stream link audio does not work on MacOS but works fine on Windows. We have tried with VLC and Quicktime on MacOS and they both worked fine with audio, but with AVPro on MacOS there is no audio

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.1- core
 - Operating system version: MacOS v14.2.1
 - Device model: Macbook Pro

**To Reproduce**
1. Use the following link with AVPro
2. Notice there is no audio

**Videos**
[m3u8 manifest file](https://genericvideotest.blob.core.windows.net/videos/99910915-caf9-4e72-a9cd-76f9dc69f53d/manifest.m3u8)

**Comment by MorrisRH** [comment]
Your video doesn't play audio for me in QuickTime or AVPro Video. A quick dig into the manifest revealed that the audio group is missing the default tag, this means that the audio track is not selected by default. Modify it as shown below and audio will work:
```
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="AUDIO",NAME="AUDIO",DEFAULT=YES,LANGUAGE="en",URI="audio_0.m3u8"
```

I'm afraid Apple rigidly stick the specification whereas other players take a more relaxed approach so there isn't much we can do about this from our end.

**Comment by ZisisTsatsas** [comment]
I've updated the file on the server to include that tag. Now we get an error saying this
```
Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
```
