### ISSUE TITLE
A flicker when use a button to ask MediaPlayer to Play Next Video

### ISSUE THREAD

**Issue by eiyamomo** [RenderHeads/UnityPlugin-AVProVideo#1766]
AVPro Video Version:
2.9.1 plugin v2.8.5f1-ultra

Unity version: 
2022.3.13f1

OS: 
Win11

Dear Support,

I am using AVPro Video for a video Novel where user click button at end of each videoclip which will play next Video Clip.

I noticed a flicker when I click the "Button" to play the Next Video Clip.

While I was searching online for setting/solution/workaround, the only thing I could found is

https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-4

Where there was two workarounds suggested by AndrewRH

**First suggestion** --- "Yes certainly. There is another sample scene called "imgui" that demonstrates how to get around this nicely. It can transition smoothly between multiple videos." 

which suggests to use "Fade to Black During Loading" option, which I couldn't found, and I could not find the sample scene called imgui either.

**Second suggestion** ---"Yes it's possible. You can have two MediaPlayer components and ping-pong between them. Use the inactive one for loading and once it has a frame you can switch to it and stop the playing MediaPlayer. So it's totally possible to do. We'll add component for this in the future so you can just drop them in :)

Is this component added now? considering this was at 2016. Or if someone can shed some lights on how this is proper supported in the latest version?

Much appreciated.

**Comment by MorrisRH** [comment]
I believe our PlaylistMediaPlayer component offers the functionality you're after. It's backed by two MediaPlayer instances and is able to smoothly transition through a playlist of videos.

**Comment by eiyamomo** [comment]
is **PlaylistMediaPlayer** component the only option for handle this? as this seems to be related to the second suggestion.

By any chance if there is anywhere I can download the "imgui" sample scene? which was suggesting using **"Fade to Black During Loading"**, is this still an option that is supported?

**Comment by Chris-RH** [comment]
The "imgui" sample scene was in a previous version of AVPro Video, that has now been depreciated.

**Comment by Chris-RH** [comment]
You could add your own fade using alpha.
