### ISSUE TITLE
Videos do not open reliably on Quest 3

### ISSUE THREAD

**Issue by BehindCodesKN** [RenderHeads/UnityPlugin-AVProVideo#1770]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I am trying to upgrade an old VR Video App for the Quest 3 with your Videplayer. It works as a PC VR Build, but I have gone through several issues now, the app finally builds and plays. However, the videos are just opening and loading very inconsistently, sometimes they are there, sometimes they are stuck on a black screen.
I thought it might be the file size first, and tried with multiple small videos - same issues.
I tried downloading the videos to the device first, instead of opening from the streaming assets, as suggested in your documentary - also the same issues.
Now I don't know what I can do to fix it on the Android Quest build. Do you have any suggestions?

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.13
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video Core - 2.9.2
 - Operating system version: Windows 11
 - Device model: Deplyoing to Meta Quest 3
 - Video specs (resolution, frame-rate, codec, file size): 9 seconds, 7200*3600 pixel, bitrate of 30389 kBit/s and 25fps

If it helps I can send over the project. :)

**Comment by Chris-RH** [comment]
1. Is it reproducible if you run a new project using just AVPro Video demo scene with your video?
2. How do these same videos play using Unity Videoplayer?
3. Are you using Exoplayer or Android Mediaplayer?
4. How many videos are you trying to play at the same time?
5. What codecs are the videos? H264 or H265?
6. What else is happening in the scene? Are the videos being paused at any point?
7. Are you using our shaders or your own?
8. Are you using OES rendering?
9. Are you able to supply samples of the videos(s) you are trying to play? You can email us at unitysupport@renderheads.com
10. Are you able to supply a full logcat please.
