### ISSUE TITLE
Playback stops when seeking after playing a video for a long time

### ISSUE THREAD

**Issue by clouds0072** [RenderHeads/UnityPlugin-AVProVideo#1771]
**Describe the issue**
After streaming an MP4 video for more than an hour, calling MediaPlayer.Control.Seek() causes the video to stop playing.

The following log is output.
[AVProVideo] Error: Decode failed. Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.11f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.2
 - Operating system version: Windows11. It doesn't happen on Windows 10.
 - Device model: DELL G15
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 15fps, H264 - MPEG-4 AVC (part 10) (avc1), 436 MB

**To Reproduce**
1. Upload a MP4 file to AWS S3
2. Play the MP4 video for an hour.
3. Call MediaPlayer.Control.Seek() 

**Logs**

[AVProVideo] Error: Decode failed. Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources.
UnityEngine.StackTraceUtility:ExtractStackTrace () (at C:/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at /Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1415)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at /Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:828)

**Comment by Chris-RH** [comment]
Hi @clouds0072,

Is this with Media Foundation/DirectShow/WinRT? Do any of the others not have this issue?
Have you had the same issues playing a video locally?
