### ISSUE TITLE
Android Custom HTTP Headers

### ISSUE THREAD

**Issue by mhoffDolby** [RenderHeads/UnityPlugin-AVProVideo#1775]
I am not currently able to get customer HTTP headers for basic authorization working on my Android app and I'm not sure if it's an issue with how i'm setting it up, or an issue with the version i'm using.

I have content on a server that is using basic authentication. I know the authentication is working because if i use chrome and enter https://user:pass@<myserver>.com it works to access the content, but it doesn't work without the user/pass. I am also able to access the server using Unity web requests and the basic authorization header.

In AVPro, i'm using the editor. Under Android i'm adding an item under "Custom HTTP Headers". In the first box i'm typing "Authorization", and in the second box i've tried both "Basic user:pass" and "Basic <Base64 of user:pass>". In all cases i'm getting a File not found error returned from AVPro. If i disable authorization on the server, AVPro works well, so it's definitely the authorization aspect.

Can you tell me if i'm setting this up wrong or if it's an issue with the AVPro version i'm using?

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.13f1
 - AVPro Video version: AVPro Video v2.9.0 (native plugin v2.9.0f1-core)
 - Operating system version: Deploying to Android 32, Developing on Windows 10
 - Device model: Meta Quest 3
 - Video specs (resolution, frame-rate, codec, file size): 4K, 24 fps, HEVC, ~125MB

**Comment by Chris-RH** [comment]
Hi @mhoffDolby, 

Custom HTTP headers are only available in the Ultra Edition of AVPro Video.  More info here: https://renderheads.com/content/docs/AVProVideo/articles/download.html#editions
You can test it using the Trial version though :)

**Comment by mhoffDolby** [comment]
Thanks Chris, that's what i was guessing but wanted to confirm
