### ISSUE TITLE
MediaPlayer.PlatformOptionsWindows.audioOutput has no effect whatsoever

### ISSUE THREAD

**Issue by MattCoalman** [RenderHeads/UnityPlugin-AVProVideo#1776]
I'm facing audio phase/balance audio problems, so i'm trying to change audio output to check if others parameters are better, but changing `audioOutput` has no effect. 
On your documentation for the [Audio Output component](https://www.renderheads.com/content/docs/AVProVideo/articles/component-audio-output.html) it is written `This component is required when the audio output mode is set to Unity` : that is not true in my case. I can put `Unity` without a `Audio Output` and i have still the sound (not a good sound, but still), and if I put a `Audio Output` linked to my Media player, the vu-meter is flat at 0 (while hearing the sound of the video). 
I can even put `None` and still having a sound.

Here is my code to create MediaPlayer :

```
            // Video player
            var mediaPlayer = virtualScreen.AddComponent<MediaPlayer>();
            mediaPlayer.AutoStart = false;
            mediaPlayer.OpenMedia(new MediaPath(file, MediaPathType.AbsolutePathOrURL), false);
            mediaPlayer.Events.AddListener(OnVideoEvent);
            mediaPlayer.AudioVolume = audioVolume != -1 ? audioVolume : AppConfig.MasterAudioVolume;
            mediaPlayer.AudioFocusEnabled = false;
            mediaPlayer.PlatformOptionsWindows.audioOutput = Windows.AudioOutput.Unity;

            var ao = virtualScreen.AddComponent<AudioOutput>();
            ao.Player = mediaPlayer;
            ao.OutputMode = AudioOutput.AudioOutputMode.MultipleChannels;
            ao.enabled = true;

            // Render Texture
            var rt = new RenderTexture(1920, 1080, 24);
            rt.name = "DynamicRT";

            // Material
            Material mat = new Material(Shader.Find("Unlit/UnlitShader")); // VirtualScreenTest gameobject with this shader must exist in the scene for this to work
            mat.mainTexture = rt;
            meshRenderer.material = mat;

            // Apply To Material
            var applyToMaterial = virtualScreen.AddComponent<ApplyToMaterial>();
            applyToMaterial.Player = mediaPlayer;
            applyToMaterial.Material = mat;
            applyToMaterial.DefaultTexture = Texture2D.blackTexture;

            if (playImmediate)
                mediaPlayer.Play();
```
 Am I doing something wrong?

Thanks.

**My Setup:**
 - Unity version: **2020.1.4f1**
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): **2.9.2 Core Edition**
 - Operating system version: **Windows 10**
PC with I7 processor
Windows 10
NVMe drive
GTX1050

Edit: Alongside the phase audio issues, the sound in the videos is ahead (approximately 100ms), creating a slight delay barely noticable. Neither of these two issues occurs when I use Unity's VideoPlayer. These problems may be related.

**Comment by Chris-RH** [comment]
I think that you are calling openMedia too early as this would use the current audio output settings, which defaults to system audio and wouldn't be able to be changed afterwards.

**Comment by MattCoalman** [comment]
Wow, this make pretty much sense, and it works!

Maybe an update of the documentation would be helpful.

Thanks a lot
