### ISSUE TITLE
DV content does not play on Android system.

### ISSUE THREAD

**Issue by witzkid** [RenderHeads/UnityPlugin-AVProVideo#1778]
Looking at the URL below, DV, H.263, Uncompressed R10K, Uncompressed V210, and Uncompressed 2VUY are supported on the Android System.
https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html

However, I was able to obtain DV content and tested it, but it does not play.
We share the information we tested below.
 - Unity version: 2022.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro UltraEdition v2.9.0f1-ultra 
 - Operating system version: Android
 - Device model: Quest Pro
 - Video specs (resolution, frame-rate, codec, file size):  24.4Mbps, 720*480(4:3) at 29.970 (29970/1000)fps, DV(NTSC)(DVCPRO)

In addition, if possible, I would like to ask if it is possible to share contents that can test DV, H.263, Uncompressed R10K, Uncompressed V210, and Uncompressed 2VUY.

Thanks

**Comment by Chris-RH** [comment]
Hi @witzkid, 

1. Have you been able to play the media on your android device using its own players?  We generally rely on the hardware to decode the videos, so it might not be supported by the device. 
2. Have you tried setting it to software decode?
3. Are you able to supply as with some media samples that you are trying to play? You can email us: unitysupport@renderheads.com

**Comment by witzkid** [comment]
Dear Chris-RH,

I've added my response to your reply.

1. Even when I try to play the content using the Oculus TV app or Files app on the Oculus-Pro device, the video does not play.
2. Even if I select Prefer Software Decoder in ExoPlayer API Options, the video does not play.
3. It seems difficult to share content due to the company's security policy.

Lastly, this is what I requested when I first inquired.
Looking at the AVPro spec, it says that the video formats below can be played on Android. Please share the URL where we can download test videos so we can check.
- DV, H.263, Uncompressed R10K, Uncompressed V210, and Uncompressed 2VUY.

Thanks.

**Comment by Chris-RH** [comment]
I'll have to look into it.  It could just be a bug in the documentation and the ticks were meant to be elsewhere.  They've been up since 2020 and this is the first time that someone has asked about any of those formats.

**Comment by witzkid** [comment]
If you have any further confirmation, please update it.
Thanks.

**Comment by Ste-RH** [comment]
It appears that as time has gone by the DV format is not supported on Android.  We will update the documentation to reflect this.
