### ISSUE TITLE
Playing large MP4 files fails on iOS

### ISSUE THREAD

**Issue by takayasan** [RenderHeads/UnityPlugin-AVProVideo#1780]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When you try to play an MP4 file on the Internet on your iPhone, the loading time increases in proportion to the data size of the target file.
Also, if the loading time exceeds approximately 120 seconds, an error of ErrorCode.LoadFailed will be output.
Therefore, MP4 files of approximately 1GB cannot be played.

The MP4 file that failed to load can be played in Safari, so it seems that there is no error in the URL or codec.
Also, on Windows and Android, MP4 files with the same URL can be played normally.

Is there a way to resolve this issue and read MP4 files larger than 1GB and play videos on iOS?

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.27f1
 - AVPro Video version: 2.9.2 - Core Edition
 - Operating system version: iOS 17.3.1
 - Device model: iPhoneSE
 - Xcode version: 15.0.1

**Logs**
Xcode is outputting the following log.
[AVProVideo] Opening https://aaaaa.bbbbb/ccccc/ddddd.mp4 (offset 0) with API 
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by Chris-RH** [comment]
Hi, 

The issue is most likely to be caused by
The video file not having the moov atom at the start (-movflags faststart)
The server not reporting the filesize correctly

Are you able to provide the URL that you are testing with please, either here or unitysupport@renderheads.com

**Comment by takayasan** [comment]
Thank you for your reply.
The URL I used for testing is not publicly available, so I sent it to "unitysupport@renderheads.com".

The problem seems to be on the MP4 side, is there anything else that needs to be addressed on the Unity or AVProVideo side?

**Comment by Chris-RH** [comment]
Hi, 

You just need to re-encode it so that the moov atom is at the start:

ffmpeg -i [input.mp4] -c:v copy -movflags faststart [output.mp4]

**Comment by takayasan** [comment]
I was able to solve the problem by putting moov atom at the beginning.
Thank you very much.
