### ISSUE TITLE
Error  404 while playing ofline video

### ISSUE THREAD

**Issue by WaqasAhmad-Unity** [RenderHeads/UnityPlugin-AVProVideo#1781]
Hi there i am getting error 404 while trying to play YouTube offline video. The live video is working fine.
![Youtube Error](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/111582253/cf906a26-55c6-46ce-883c-159417c53e44)

Av Pro Version 2.9.2
Unity Version 2021.3.4f1

Error Log
Error: HTTP/1.1 400 Bad Request
UnityEngine.Debug:Log (object)
LightShaft.Scripts.YoutubeSettings/<YoutubeGenerateUrlUsingClient>d__73:MoveNext () (at Assets/3rd Party Assets/LightShaft/Scripts/YoutubeSettings.cs:307)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

InvalidOperationException: HTTP/1.1 404 Not Found
UnityEngine.Networking.DownloadHandler.GetCheckedDownloader[T] (UnityEngine.Networking.UnityWebRequest www) (at <363ba40db79f4850800b6b87947a77c3>:0)
UnityEngine.Networking.DownloadHandlerTexture.GetContent (UnityEngine.Networking.UnityWebRequest www) (at <1e4b4314de2a4931ba4f260ec9ad734d>:0)
LightShaft.Scripts.YoutubeSettings+<DownloadThumbnail>d__87.MoveNext () (at Assets/3rd Party Assets/LightShaft/Scripts/YoutubeSettings.cs:724)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <f1212ad1dec44ce7b7147976b91869c3>:0)

**Comment by Chris-RH** [comment]
Hi, 

We don't support streaming from Youtube. Also, those are not AVPro Video error messages, so I'm not sure that we can help you with this.
