### ISSUE TITLE
IOS audit need PrivacyInfo.xcprivacy when can we update the privacy list?

### ISSUE THREAD

**Issue by LeiFengChina** [RenderHeads/UnityPlugin-AVProVideo#1783]
IOS audit need PrivacyInfo.xcprivacy when can we update the privacy list?
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

**Comment by Chris-RH** [comment]
AVPro Video version 3 will be code-signed and we'll do a privacy manifest for it.

**Comment by LeiFengChina** [comment]
Hope to update soon，apple‘ll be implemented on April 29

**Comment by dw8869** [comment]
@Chris-RH 
When I checked with the privacy report, I received the following error message.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/64513117/a5730264-080e-4de1-8775-3fb36bd1aaff)

**Comment by Chris-RH** [comment]
@dw8869 
Is that version 3.0 or 3.0.1?

**Comment by dw8869** [comment]
@dw8869 
version 3.0.1.

I added it as below, is this right?
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/64513117/4f8e8302-656b-457d-9a1e-fb3727b4e88f)
