### ISSUE TITLE
Problem with positional ambisonic sound

### ISSUE THREAD

**Issue by PParkkola** [RenderHeads/UnityPlugin-AVProVideo#1785]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I'm trying to play videos in VR with ambisonic recordings using Pico 4 VR headset. My issue is with the directionality of the audio. 
I've tried a ton of things and nothing seems to work. Also the problem seems to be in both Unity editor on windows and on android builds, though I will say that I haven't tested every editor setup in build.

**Your Setup:**
 - Unity version: 2022.3.20f1
 - AVPro Video version:  2.9.3 AVPro Video - Core Android Edition
 - Operating system version: Win 10 in editor / Minimum Android 10.0(api level 29) in build
 - Device model: Pico 4
 - Video specs (resolution, frame-rate, codec, file size): Three test videos:
 1:video: 4000x2000; 30fps; MP4 AVC1; 221mb / audio: AAC; 6 channels; Ambix1stOrder(4_2)
 2:video: 4000x2000; 30fps; MP4 AVC1; 221mb / audio: AAC; 4 channels; Ambix1stOrder(4_0)
 3:video: 4000x2000; 30fps; MKV AVC1; 221mb / audio: Opus; 6 channels; Ambix(4_2)[made from the first by using FFMPEG command on your documentation)
 
**To Reproduce** 
Two main ways I've tried, A [With FB360 audio]:
1. Make Unity scene with Main camera and AVPro MediaPlayer
2. Set following AVPro MediaPlayer settings: 
- Media Foundation on Windows and ExoPlayer on Android.
- Both using Facebook Audio 360 and Ambix(4_2)
- Set video url with matching ambisonic audio format(test videos 1&3 in my case).
3. Hit play and rotate main camera around y-axis
4. Enable Focus on with off Focus Level DB -24 and do previous step again, just to be sure that there is no directionality to the sound.
-> The audio seems the same as with System Direct and definitely doesn't have positionality.
(5.) Import Pico SDK and copy the default XR Rig to the scene and disable Main Camera.
(6.) Build and rotate your head.
-> The audio is the same, i.e no directionality when you turn your head.

B [With Pico Ambisonics Decoder]:
1. Make Unity scene with Main camera and AVPro MediaPlayer
2. Set following AVPro MediaPlayer settings: 
- Media Foundation on Windows and ExoPlayer on Android.
- Both using Unity.
- Set video url to a video with ambisonic audio format.
3. Import Pico SDK.
4. Add AudioOutput+AudioSource to the AVPro_MediaPlayer.
5. Add "PXR_Audio_Spatializer_Ambisonic Source" to the AVPro_MediaPlayer and select "Ambisonics_bus - Master"(imported with pico files) for Audio Source's audio mixer.
6. Add "PXR_Audio_Spatializer_AudioListener" to the MainCamera.
7. Select "Pico Ambisonic Decoder" from the Unity Project Settings->Audio->Ambisonic Decoder Plugin -setting.
(8.) For testing purposes you can import ambisonic .wav-file and set it as ambisonic in unity file import settings. Add that wav-file to a separate game object with an audio source, along with "PXR_Audio_Spatializer_AmbisonicSource"-component.
9.Build/play in editor and rotate main camera in y-axis.
->The result is that the .wav file works properly and has directional ambisonics through Pico ambisonics & spatializer
->The AVPro audio can't be heard at all for some reason(!), even though the Audio Output shows that it's playing. The Ambisonics_bus audio mixer also shows that it's receiving audio, so I have no idea why it cannot be heard. Theoretically it should be the same situation as with the .wav file: Pico ambisonics decoder spatializing ambisonics audio format from Unity Audio Source. But it doesn't work for some reason with the AVPro AudioOutput. If you remove the Ambisonics_bus audio mixer from the audio source you can hear audio, but it's not directional(or ambisonic).
-> Same results with android build with Pico headset.

I can show my project via screenshare on discord, or even share it probably if needed.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @PParkkola, 

360 Audio is only a feature of the Ultra edition.  More info here: https://renderheads.com/content/docs/AVProVideo/articles/download.html#editions

**Comment by PParkkola** [comment]
Right, didn't notice that... I don't suppose there is a cheaper Android Core + spatial audio price? Heh :D

Shouldn't the second approach using Pico Ambisonics still work though? There I'm just basically trying to get the (ambisonic) video sound to play through basic Unity Audio Source-component. Why I'm not getting any sound at all?

**Comment by PParkkola** [comment]
Can I get an answer to the above; is it possible to get the ambisonics working via Pico Ambisonic Decoder(or other 3rd party) and Unity Audio Source using Audio Output-component?
If no, can we write our own Audio Output-style component to use the audio from AVPro player?

**Comment by PParkkola** [comment]
To answer myself after more figuring things out: Afaik, the reason Pico Ambisonic Decoder won't work with AVPro Unity Audio is not AVPro, but rather Unity itself and how it processes video audio differently from regular audio clips. Pico itself would need to implement video audio support for it to work. 
A 3rd party ambisonics solution through Google Resonance Audio SDK might work, but we don't have time to test it so AVPro Ultra version it shall be.

**Comment by Chris-RH** [comment]
The trial version can be used to test 360 audio: https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases
