### ISSUE TITLE
H.264 NAL Decoding

### ISSUE THREAD

**Issue by witzkid** [RenderHeads/UnityPlugin-AVProVideo#1786]
Dears,

Is Play supported in AVPro when data is streaming in H.264 NAL format?

Thanks in advance.

**Comment by witzkid** [comment]
So, is it okay to understand that if a file is received in H.264 raw data format, it cannot be played back with AVPro?

**Comment by Chris-RH** [comment]
correct.

**Comment by witzkid** [comment]
Thank you for your quick response.
