### ISSUE TITLE
Files not removed from cache

### ISSUE THREAD

**Issue by AdrianRCG** [RenderHeads/UnityPlugin-AVProVideo#1787]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
We lad in our project many Videos via stream and cache them. But when we try to remove them from cache they are still present in the app settings and further more there are duplicates too (because they aren't removed properly).

Are we missing something like any setting that removing from cache is possible?
Also there often some bookmarks missing.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.8.5 Ultra
 - Operating system version: macOS
 - Device model: MacStudio

**To Reproduce**
1.  Build with Unity for IOS with Xcode 15.0.1
2. Cache Videos with mediaPlayer.Cache.AddMediaToCache(url);
3. Try remove from cache with mediaPlayer.Cache.RemoveMediaFromCache(url);
4. In the iso Setting from the app there are still all cached videos.

**Logs**
 AVProVideo version 2.8.5-ultra build 1892 on iPhone 11 Pro running iOS 17.2
AVPro Video iOS version 2.8.5-ultra build 1892 built with Apple LLVM 13.1.6 (clang-1316.0.21.2.5)
[AVProVideo] Initialising AVPro Video v2.8.5 (native plugin v2.8.5-ultra build 1892) on Apple A13 GPU/Metal (MT True) on IPhonePlayer
no cached asset, will try to resolve bookmark data...

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Can you upgrade to AVPro Video version 2.9.3 and retest please?

**Comment by AdrianRCG** [comment]
We upgraded but no difference in the behaviour. Are there any plist settings necessary to remove from cache?

Additional logs which depending on cache:
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...

**Comment by AdrianRCG** [comment]
So, any support for this?

**Comment by Chris-RH** [comment]
Its on our list of things to investigate :)

**Comment by Chris-RH** [comment]
We can't reproduce this in the latest version of AVPro Video.

**Comment by Ste-RH** [comment]
We will be closing this issue soon due to a lack of response.
