### ISSUE TITLE
Vision os build failed with message error 2 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by futurristic09** [RenderHeads/UnityPlugin-AVProVideo#1789]
Hello, I am using AVPro Video v3.0.0-RC2 (trial)

And i am trying to make build for vision os to run on simulator. 

Build failed every time on xcode with error message - 

ld: warning: -undefined dynamic_lookup is deprecated on visionOS-simulator
ld: warning: -undefined dynamic_lookup is deprecated on platform=12
duplicate symbol '_UnityPluginLoad' in:
    /Users/fbs/Documents/UnityProjects/FBSUnityProjects/visionOSTemplate-1_PulseJetLatest/Build/Libraries/ARM64/Packages/com.unity.xr.visionos/Runtime/Plugins/visionos/Simulator/arm64/libUnityVisionOS.a(Main.o)
    /Users/fbs/Library/Developer/Xcode/DerivedData/Unity-visionOS-awdkfotgaoqlykfptyffslvhkuai/Build/Products/ReleaseForRunning-xrsimulator/libAVProVideo.a(AVProVideoUnity.o)
duplicate symbol '_UnityPluginUnload' in:
    /Users/fbs/Documents/UnityProjects/FBSUnityProjects/visionOSTemplate-1_PulseJetLatest/Build/Libraries/ARM64/Packages/com.unity.xr.visionos/Runtime/Plugins/visionos/Simulator/arm64/libUnityVisionOS.a(Main.o)
    /Users/fbs/Library/Developer/Xcode/DerivedData/Unity-visionOS-awdkfotgaoqlykfptyffslvhkuai/Build/Products/ReleaseForRunning-xrsimulator/libAVProVideo.a(AVProVideoUnity.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Note- unity version i am using 2022.3.19f1

Thanks

**Comment by MorrisRH** [comment]
Fixed, UnityPluginLoad and UnityPluginUnload will no longer be exported with the next release (v3.0.0-RC3)

**Comment by MorrisRH** [comment]
AVProVideo v3.0.0-RC3 is now available

**Comment by futurristic09** [comment]
Awesome, Thanks you :)
