### ISSUE TITLE
Does the AVPro set or modify the Category property in iOS when inits ?

### ISSUE THREAD

**Issue by defchen** [RenderHeads/UnityPlugin-AVProVideo#179]
**Describe the bug**

Does the AVPro set or modify the Category property in iOS when inits ?
We had a conflict with another audio plugin.

**Your Setup (please complete the following information):**
 - Unity version: 2017.4
 - AVPro Video version: 1.10.0
 - Operating system version: iOS
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
AVProVideo does not make any changes to the audio session.
