### ISSUE TITLE
When should I call Caching?

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1791]
When should I call `mediaPlayer.Cache.AddMediaToCache` ?

Should I call you when the video is loaded?

or

Should I call before the video is loaded?

**Comment by MorrisRH** [comment]
Caching is independent of playback so ideally you want to call it first and wait for caching to complete before opening the video.

**Comment by dw8869** [comment]
Thank you for your help.
