### ISSUE TITLE
Build fail for my project

### ISSUE THREAD

**Issue by chengnay** [RenderHeads/UnityPlugin-AVProVideo#1792]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Recently, I updated my Unity project to Wave Plugin 5.6.0-r.10 and it will build fail.
After some investigation and I found out that it is due to android.enableDexingArtifactTransform=false in AVProVideo\Editor\Scripts\PostProcessBuild_Android.cs script.
I am wondering is this necessary to set it to false?
What will happen if I manually change it to true?
I did try setting it to true and it will build successfully.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video 2.0
 - Operating system version: Android
 - Device model: VIVE XR Elite
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Creating an Unity project that includes Wave Plugin 5.6.0-r.10 and AVPro Video plugin
2. It will always build fail with error message "java.lang.UnsupportedOperationException: This feature requires ASM7"

**Logs**
If applicable, add error logs to help explain your problem.
java.lang.UnsupportedOperationException: This feature requires ASM7

Execution failed for task ':launcher:dexBuilderRelease'.
> Multiple task action failures occurred:
   > java.lang.UnsupportedOperationException: This feature requires ASM7
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: C:\Users\chengnan_yang\Documents\CSharp\2023\1128_VRS\VRS\Temp\gradleOut\unityLibrary\build\intermediates\runtime_library_classes_jar\release\classes.jar
   > A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
      > Failed to process: C:\Users\chengnan_yang\Documents\CSharp\2023\1128_VRS\VRS\Temp\gradleOut\unityLibrary\build\intermediates\runtime_library_classes_jar\release\classes.jar

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, I presume you're not actually using AVPro Video version 2.0 as that is January 2021, and are in fact using a more up to date version?
More info on the dexing issue is [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#unity-20201-and-above).

**Comment by chengnay** [comment]
Hi @Chris-RH,
It is true that the project is still using AVPro Video version 2.0 as we did not update the plugin since March 2021.
We will check out the latest version, thanks!

**Comment by Chris-RH** [comment]
Yes, please update to the latest version.  There have been a lot of fixes and upgrades since then!

**Comment by chengnay** [comment]
Hi @Chris-RH,
It looks like the newer version, Ultra Edition 2.9.3 will also build fail.
I check the script and it seems it is required to set "android.enableDexingArtifactTransform=false" for using Unity 2020/2021.

**Comment by Chris-RH** [comment]
Can you reproduce this in a fresh project using only AVPro Video?
What is the full error message?

**Comment by chengnay** [comment]
Hi @Chris-RH,
As for only AVPro Video without Wave Plugin, it will build success.
After import 5.6.0-r.10.1, I will get below build error,
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/33050705/9784aac6-288a-403b-96f3-78e82ae62e08)
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/14721850/log.txt)

**Comment by Chris-RH** [comment]
So the problem is that it isn't an AVPro specific issue.  I suggest you google the error message and follow suggestions.

**Comment by chengnay** [comment]
After some investigation, when I tried to set android.enableDexingArtifactTransform=true, it will build pass.
But, I think this is not allow, am I right?

By the way, does AVPro Video recommend which gradle version to use?
Or just Unity built-in version will be enough?
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/33050705/abc69c64-0216-44e1-a0c7-936fd99effcd)

**Comment by Chris-RH** [comment]
if it works without it, then that's fine
