### ISSUE TITLE
Stalling with 4K Videos in AVPro Player on Android in 360 View

### ISSUE THREAD

**Issue by Fasilkallot** [RenderHeads/UnityPlugin-AVProVideo#1793]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

When attempting to play 4K videos using AVPro Player in a 360 view on Android devices, the video playback frequently stalls, causing interruptions in the viewing experience. This issue is affecting the smooth playback of 4K content, leading to a degraded user experience.

 - Unity version: 2023.2.3
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.3 - core
 - Operating system version: Android 10
 - Device model: moto g8 power lite
 - Video specs (resolution, frame-rate, codec, file size): 4K

**Comment by Chris-RH** [comment]
Is it streaming or playing from the device?
What are the full specs of your video? Can you provide a sample please, either here or to unitysupport@renderheads.com
Stalling implies that its having issues decoding the video fast enough.

**Comment by Fasilkallot** [comment]
The video is currently streaming from the web. However, I've noticed that the issue persists even when playing it from the device. I'll provide the video link below for your reference.

https://highendvideo.s3.ap-south-1.amazonaws.com/High.mp4

**Comment by Chris-RH** [comment]
How does the video play on the same device using (a) its own videoplayer and (b) Unity's videoplayer?

I suspect that 4k might be beyond the device's capability.

**Comment by Fasilkallot** [comment]
Thank you so much for your help. I've experimented with Unity's video player, and it's exhibiting the same problem. In light of this, considering your advice, what steps should I take next? Do you have any recommendations regarding the maximum video quality setting that would ensure playback compatibility across a wide range of devices?

**Comment by Chris-RH** [comment]
I would probably set it up as a multi bitrate HLS, this would allow you to have streams of different resolutions and the one best suited to the device's capabilities would play.

**Comment by Fasilkallot** [comment]
I have tested compressing the video, and it worked. 
After testing with compressed video, I encountered a peculiar issue where certain shadowed portions of the video appear pixelated during playback. Playing the video normally device does not exhibit this issue. Are there any settings I should adjust to ensure the video maintains its original quality? Currently, I am playing the video in 360 Sphere-ApplyToMesh, using the shader VR/InsideSphere/Unlit, with High quality and Apply gamma options enabled. The settings for MediaPlayer Texture filter are Trilinear and Anisotropy is set to 16

**Comment by Chris-RH** [comment]
When you decrease the resolution they will exhibit some pixelation.  What resolutions are you using?

**Comment by Fasilkallot** [comment]
I'm currently using a resolution of 4000 x 2000 with a total bitrate of 54372 kbps.

**Comment by Chris-RH** [comment]
That [device](https://en-gb.support.motorola.com/app/answers/detail/a_id/150110/~/moto-g8-power-lite---specifications) is showing up as having a [max display resolution of 2400x1080](https://www.mediatek.com/products/smartphones-2/mediatek-helio-p35)

**Comment by Fasilkallot** [comment]
However, even when tested on other devices, I encountered the same issue. I will attach some screenshots taken from the OnePlus 8T. 
For testing purposes, I took one frame of the video and applied it as a skybox. When the image is in PNG format, it exhibits some issues, but when in JPEG format, the quality is good in that frame. However, when I created a video using JPEG frames, the issue persisted.


![Screenshot_2024-04-03-16-35-54-67_6db678231275f23f4e2fa72c692645be](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/86238910/9c370efe-66c4-4275-8bf2-1bb95827ebdb)
![Screenshot_2024-04-03-16-36-00-91_6db678231275f23f4e2fa72c692645be](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/86238910/abe04a2d-1f8c-47cb-8f59-6941b2753f18)
![Screenshot_2024-04-03-16-36-08-66_6db678231275f23f4e2fa72c692645be](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/86238910/1c90859f-7742-44ab-973c-420347d2a4db)

**Comment by Chris-RH** [comment]
Also make sure it is encoded with [fast start ](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/feature-streaming.html#http-progressive-streaming)

**Comment by Fasilkallot** [comment]
I have encoded it with fast start, yet the issue persists

**Comment by Fasilkallot** [comment]
I suspect the issue may be related to the Google VR rendering. When playing the same video on a normal screen, there are no issues. Do you know of any specific settings I need to enable in Google Cardboard VR or any particular video format or rendering settings required for Cardboard XR Plugin?

**Comment by Chris-RH** [comment]
I've not used Google Cardboard, so can't tell you its specific requirements.  It must come with some documentation?   
You may just need to look to see if other people have had a similar issue with it.

**Comment by Fasilkallot** [comment]
Okay. Thank you for your assistance.
