### ISSUE TITLE
Force Eye Mode doesn't work in OES shaders 

### ISSUE THREAD

**Issue by Anton111111** [RenderHeads/UnityPlugin-AVProVideo#1797]
- Unity version:  2023.1.20f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.3 ultra

Shaders AVProVideo-VR-InsideSphere-AndroidOES.shader and AVProVideo-VR-InsideSphere-Transparent-AndroidOES.shader use function Android_IsStereoEyeLeft() to determine eye index but don't check Force Eye Mode parameter theresofre Force Eye Mode doesn't work.

I changed this function to back Force Eye Mode checking:
```
INLINE bool Android_IsStereoEyeLeft()
			{
				#if defined(FORCEEYE_LEFT)
					return true;
				#elif defined(FORCEEYE_RIGHT)
					return false;
				#elif defined(STEREO_MULTIVIEW_ON)
					int eyeIndex = SetupStereoEyeIndex();
					return (eyeIndex == 0);
				#else
					return IsStereoEyeLeft();
				#endif
			}
```

**Comment by Anton111111** [comment]
AVPro Video version 3.0.0-ultra build 2403201307 same issue.

**Comment by Chris-RH** [comment]
I'm not sure its a thing that ever worked in OES mode as the shaders haven't been changed recently.  We'll look into it, thanks.

**Comment by Ste-RH** [comment]
This should be fixed in the next release (v3.0.11).

**Comment by Chris-RH** [comment]
AVPro video version 3.0.11 has been released.  Please let us know if it has not fixed your issue.

**Comment by Anton111111** [comment]
> AVPro video version 3.0.11 has been released. Please let us know if it has not fixed your issue.

works for me!

**Comment by Chris-RH** [comment]
Awesome thanks! :)
