### ISSUE TITLE
Set the default texture size for 360 mpd video.

### ISSUE THREAD

**Issue by VYPERAD8** [RenderHeads/UnityPlugin-AVProVideo#1798]
I am using the AVPro trial version to test the player.  I have a MPEG-DASH video with 1920-1080 resolution.  when I load the video to the player using a 360 mesh render it starts at a very low resolution(426x240).  How can I set the default to load at a higher resolution.  I presume it's currently set lower to render smoothly for lower connection speeds.  However, 426x240 is extremely low and looks terrible. it takes 5+ seconds to render to a higher resolution.

**Comment by Chris-RH** [comment]
You've not mentioned which platform you are using.

On Android (Exoplayer) and Windows (WinRT) you can specify starting adaptive streams on the highest bitrate stream possible.  On the Apple platforms, the player adheres to Apple's standard of starting with the first stream in the manifest file.
