### ISSUE TITLE
Error while generating build using AVPro asset in the project.

### ISSUE THREAD

**Issue by iamraazz** [RenderHeads/UnityPlugin-AVProVideo#1799]
Problem description:

With the AVPro Video trail version asset in the project, we are not able to generate a build. It throws gradle errors .
When we delete the asseet and build, then we have no issues. Help us resolve this.

Device (which devices are you having the issue with - model, OS version number):

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: v3.0.0 (plugin v3.0.0f1-trial)
Target Platform: Android
Unity: v2021.3.11f1 WindowsEditor
OS: Desktop - GF65 Thin 10SDR (Micro-Star International Co., Ltd.) - Windows 10  (10.0.21996) 64bit - English
CPU: Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz - 12 threads - 16204KB
GPU: NVIDIA GeForce GTX 1660 Ti - NVIDIA - Direct3D 11.0 [level 11.1] - 5966KB - 16384

**Comment by Chris-RH** [comment]
What are your gradle errors please

**Comment by Chris-RH** [comment]
closing due to lack of reply
