### ISSUE TITLE
Video artefacts with Unlit OES shader (Android)

### ISSUE THREAD

**Issue by JackM36** [RenderHeads/UnityPlugin-AVProVideo#18]
I am playing normal videos (not 360) in VR, and I get some weird artefacts. Please see the video below.
This only happens on Android (Gear VR), but not on Oculus Go. It happens with all videos. I also play 360 videos and they are fine. This seems to happen only when using OES. If I just disable OES, and use a non-OES shader, it works just fine.

https://we.tl/t-nPoxHZKOBo

The video is displayed on a mesh (Quad). I tried other meshes (plane, cube) but the results are similar (or worse).

 - Unity version: 2018.3.0f2
 - AVPro Video version: 1.9.10
 - Operating system version: Android (Gear VR)
 - Device model: Samsung S6

**Comment by AndrewRH** [comment]
That's bizarre.   The only thing I can image it is, is z-fighting.  Are you sure you don't have two quads very close to each other there?

**Comment by AndrewRH** [comment]
If not, I would recommend trying a newer version of Unity, as 2018.3.0 is a .0 release, so it probably has a lot of bugs.  Try 2018.3.5

**Comment by JackM36** [comment]
Yes, the quad is the only mesh displaying the video.
However, around the quad I have a sphere displaying a 360 photo/background (in the video is just solid black). If I remove that one, then it works fine. But the two objects do not intersect in any way, and the camera is inside the sphere.

Also, it works fine when using nonOES, and on Oculus Go. Maybe the unlit OES shader somehow causes the artifacts?

**Comment by AndrewRH** [comment]
Are you using an OES shader / video on your background sphere?

Are you able to send us a cutdown version of your scene?

Your GearVR + Android OS etc everything is updated to the latest versions?

Thanks,

**Comment by JackM36** [comment]
> Are you using an OES shader / video on your background sphere?

No, I use a normal equirectangular shader for the background.
https://pastebin.com/bQ8mmSLF

> Are you able to send us a cutdown version of your scene?

It's not so easy to do it due to a ton of dependancies, but I will try to explain a simple setup so you can replicate it.
- I have a sphere mesh, which acts as the background. The equirectangular shader is used.
- I have a quad mesh, with an **Apply To Mesh** component on it. This is inside the sphere (not a child object). It uses your Unlit OES shader.
- I have an empty gameobject, with the **Media Player** component. Exoplayer is used, with OES enabled

> Your GearVR + Android OS etc everything is updated to the latest versions?

Yes

The setup must be correct since it works fine on both Windows and the Oculus Go. I only have the problem on Gear VR.

**Comment by JackM36** [comment]
Is there any updates on this?

**Comment by AndrewRH** [comment]
Sorry, we were never able to replicate this locally...what was the update on your side?

**Comment by AndrewRH** [comment]
We've just released a new version of AVPro Video (v.1.9.17) which should fix this issue. Please do test it and let us know if if this resolves it for you.

Thanks,

**Comment by JackM36** [comment]
Thanks, I will test it and let you know.

**Comment by AndrewRH** [comment]
Any luck?   I'll close this ticket soon if we haven't heard back and presume it's fixed.

**Comment by JackM36** [comment]
We are finishing some important features so I did not have a chance to test it yet. I will test it as soon as possible (next few days) and get back to you. Sorry for the delay.

**Comment by RenderHeadsSte** [comment]
Awesome, thanks!

**Comment by JackM36** [comment]
The issue seems to be fixed.

I will reopen the issue if encounter it again.

**Comment by RenderHeadsSte** [comment]
Awesome!  Thanks for letting us know :)
