### ISSUE TITLE
White Streak Video Glitch in Left Eye ONLY (Oculus Go)

### ISSUE THREAD

**Issue by OldMontana** [RenderHeads/UnityPlugin-AVProVideo#180]
We have recently been experiencing a white video glitch in ONLY the left eye on the Oculus Go. This is extremely distracting, and we haven't found any solution for this. Video link below. Any thoughts?

**Setup**
Unity version: 2018.3.0f2
AVPro Video version: 1.10.0
Operating system version: Windows 10
Device model: Oculus Go
Video specs: 4096x4096, 30fps, H265, 3GB

**Video**
[Link](https://www.youtube.com/watch?v=u0zhAYFB4wQ&feature=youtu.be)

**Comment by AndrewRH** [comment]
It could be an issue with the encoding.  Perhaps the bitrate is too high for the Oculus Go to decode correctly in time?

What bitrate is your video?

This link from Oculus also mentions encoding issues which may help:
https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/

Thanks,

**Comment by mark-developr** [comment]
We had the same issue, using the Fast OES Android playback resolved it for us and provided better playback

**Comment by AndrewRH** [comment]
Yeah, it sounds like it could be an overheating issue.

I will mark this as Closed for now as OES mode seems to solve it.

Thanks,
