### ISSUE TITLE
Occasional decoding failure on some machines after packaging

### ISSUE THREAD

**Issue by lzx-cloud** [RenderHeads/UnityPlugin-AVProVideo#1801]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.8f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: window11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 7680x4320、25fps、216M、 AVC

**To Reproduce**    
Occasional abnormalities
1. After Unity packages the application and runs it without any operations, there will be an exception when running the next day. Without changing any code, repackaging can run normally

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Which version of AVPro Video are you using?
Which devices is it failing on?
How long is it taking?
Can you provide any logs or error messages?

**Comment by Chris-RH** [comment]
1. Which version of AVPro Video are you using?
2. Which devices is it failing on?
3. How long is it taking?
4. Can you provide any logs or error messages?

**Comment by Chris-RH** [comment]
closing due to lack of reply
