### ISSUE TITLE
Black screen when playing video on Android 

### ISSUE THREAD

**Issue by Hllib** [RenderHeads/UnityPlugin-AVProVideo#1802]
**Description**
Videos with AVPro are not playing on Android devices with Snapdragon 680 CPU and 4GB RAM. The same videos are playing when using Unity standart videoplayer. 
At the same time, those videos work with AVPro on Samsung Galaxy A31, Redmi Note 9 Pro, Redmi Note 8 Pro

**Setup**
 - Unity version: 2021.3.26f1
 - AVPro Video version: 2.9.1 (plugin v2.8.5f1 - trial)
 - Operating system version: Android 13 TKQ1
 - Device model: Redmi Note 11
 - Video specs (resolution, frame-rate, codec, file size): 
      1. 2732*2048, 30 fps, MPEG-H Part2/HEVC(H.265)(hvc1), 199mb
      2. 2192*1644, 30 fps, MPEG-H Part2/HEVC(H.265)(hvc1), 48mb

**Additional Notes**
Problem stays when using H264 codec as well. 

**Logs**
Error Unity [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by Chris-RH** [comment]
That's odd.

Is it repeatable using a new project and just AVPro mediaplayer demo scene?
Can you provide a full logcat please?

**Comment by Hllib** [comment]
We have checked videos(with specs that were initially mentioned in the issue) in a new project - it's the same for Redmi 11, they don't play

**Comment by Hllib** [comment]
The video plays on the device iself, though it lags. It does not play at all in Unity build

**Comment by Chris-RH** [comment]
have you tried Android Mediaplayer rather than exoplayer?

**Comment by Hllib** [comment]
1. Yes, it always works in editor
2. We have not yet tried it 
3. We will check that 
4. No, we are playing only one video at a time
5. We have several spine animations in the background

**Comment by Chris-RH** [comment]
It sounds like the added overhead of Unity and background animations means that your device is unable to play the video, since it struggles to play it on its own player alone.
