### ISSUE TITLE
Exoplayer not playing mp3

### ISSUE THREAD

**Issue by scottgarner** [RenderHeads/UnityPlugin-AVProVideo#1804]
**Describe the issue**

In version 2.9.3, setting "Platform Specific" -> "Android" -> "Audio Output" to "Unity" functions as expected with an "Audio Output" component. After upgrading to 3.0, no audio seems to come through in Android builds, but it still works in editor in macOS.

**Your Setup (please complete the following information):**
 - Unity version: 2023.2.16f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): UnityPlugin-AVProVideo-v3.0.0-Trial
 - Operating system version: macOS 14.4 / Quest SQ3A.220605.009.A1
 - Device model: Meta Quest 3
 - Video specs (resolution, frame-rate, codec, file size): Audio only

**To Reproduce**
1. Configure Android settings with "Audio Output" set to Unity.
2. Attempt to play "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brain%20Dance.mp3" on device.

**Logs**

AndroidPlayer "Oculus_Quest" [AVProVideo] Initialising AVPro Video v3.0.0 (native plugin v3.0.0-trial) on Adreno (TM) 740/OpenGL ES 3.2 V@0757.0 (GIT@08435ba2e8, I4fef8e100e, 1708703667) (Date:02/23/24) (MT True) on Android
AndroidPlayer "Oculus_Quest" [AVProVideo] Opening https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brain%20Dance.mp3 (offset 0) with API ExoPlayer

**Screenshots**

<img width="686" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/786436/db9b246a-aafc-415f-92f2-15eac5849315">
<img width="710" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/786436/dd981734-9e42-4361-8a7e-c80fafae13df">
<img width="504" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/786436/b384fc8d-0cc2-40d3-a29d-e3ea8fb968f4">

**Comment by Chris-RH** [comment]
Can you repeat this using a new project with the mediaplayer demo scene?

**Comment by scottgarner** [comment]
Further testing. 

- Clean project in Unity 2022.3.22 on macOS.
- UnityPlugin-AVProVideo-v3.0.0-Trial.unitypackage.
- Demo_MediaPlayer scene.
- Tested on Google Pixel 6a running Android 14.

Results:

1. Unmodified scene.
  * Works as expected in editor.
  * Works as expected on device.
2. Changing "Audio Output" to "Unity".
  * Works as expected in editor.
  * Works as expected on device.
4. Changing "Audio Output" to "Unity" and  sample video to mp3 file.
  * Works as expected in editor.
  * No audio on device and playhead does not advance.
5. Changing "Audio Output" to "System Direct" and sample video to mp3.
  * Works as expected in editor.
  * No audio on device and playhead does not advance.
6. Changing "Video API" to "Media Player" and sample video to mp3.
  * Plays audio in editor, but does not support "Audio Output" set to "Unity".
  * Plays audio on device, but does not support "Audio Output" set to "Unity".
  
So it appears to be an issue with ExoPlayer and audio-only content. Unfortunately, I specifically need ExoPlayer for "Audio Output" support.

**Comment by scottgarner** [comment]
Some additional logging.

[logcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/14854791/logcat.txt)

**Comment by Chris-RH** [comment]
Have you tried playing the same mp3 file locally from the device instead of streaming?

**Comment by scottgarner** [comment]
Testing local mp3 in "Streaming Assets" with a "Media Reference": 

- Works in editor as expected.
- Works on device with "Video API" set to "Media Player", but not "Exo Player".

<img width="597" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/786436/8c48064f-4e3c-4153-a981-b4459891a4a4">
<img width="572" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/786436/75091343-3d9f-489b-bec9-b9e23868ded0">

**Comment by Chris-RH** [comment]
There were quite a few changes to Android in the upgrade to version 3 to accommodate Vulkan and change Exoplayer to media3.  There area few places that this issue could have crept in. 
Realistically, we are very busy at the moment with a big external project, so this probably won't get a proper look at until the end of May.  It is on the TO DO list.

**Comment by scottgarner** [comment]
Understood and thanks for checking in. I can continue working with the v2.9.3 trial for now and will plan to purchase 3.0 when this issue is resolved.

**Comment by Ste-RH** [comment]
A fix for this will be in the next release (v3.0.3)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.3 has been released.  Please let us know if it has not fixed your issue.
