### ISSUE TITLE
Build failed for iOS

### ISSUE THREAD

**Issue by TakafumiYuasaHL** [RenderHeads/UnityPlugin-AVProVideo#1805]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
AVPro Video v3 iOS build fails.

**Your Setup (please complete the following information):**
 - Unity version: Unity2021.3.36f1 (Sillicon)
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.0 (core)
 - Operating system version: macOS 13.6
 - Device model: MacBook Air (Apple M2)
- Xcode 15.2

**To Reproduce**
1. Creating an Unity project that includes AVPro Video plugin v3.0.0
2. Set "Assets/AVProVideo/Demos/Scens/Demo_MediaPlayer" scene to "Scenes In Build" in Unity
3. Output Xcode project
4. Add "-ld_classic" to "Other Linker Flags" in Xcode project
5. Build

**Logs**
Undefined symbol: __swift_FORCE_LOAD_$_swiftXPC
Linker command failed with exit code 1 (use -v to see invocation)

**Screenshots**
![スクリーンショット 2024-04-02 14 13 35](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/123433830/ae46228e-4776-46a3-98d4-2d90a66b2ae8)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
Could not reproduce this here using:
- Unity 2022.3.21f1
- Xcode 15.3
- AVPro Video 3.0.0-trial

Can you confirm that the following files from AVProVideo are included in your generated Xcode project and are members of the UnityFramework target.
![Screenshot 2024-04-02 at 10 26 59](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/46530460/9ae9fbd3-e0ac-45f7-8eb0-f020015978be)

**Comment by TakafumiYuasaHL** [comment]
Thank you so.

I confirmed.
I think AVProVideo is included in my Xcode project.

![スクリーンショット 2024-04-02 21 22 40](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/123433830/08ccdd77-9439-4d07-8006-e4248b935b23)

And each file is members of the UnityFramework target.

![スクリーンショット 2024-04-02 21 23 03b](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/123433830/25c16999-7f3a-4be2-a002-abb195bb27cc)


I tried Unity2022.3.22f1 but it didn't work.

**Comment by MorrisRH** [comment]
Are you able to upgrade Xcode to 15.3?
This does feel like an issue with Xcode as I'm completely unable to reproduce this.

**Comment by TakafumiYuasaHL** [comment]
I have to have a fixed environment due to work circumstances.
However, I got permission and tried upgrading.

Then I was able to successfully build!!

My environment where the build was successful is as follows
* macOS 14.4.1
* Xcode 15.3

Thank you so much.
