### ISSUE TITLE
Playing multiple videos results in a black screen on mobile

### ISSUE THREAD

**Issue by wayne40117** [RenderHeads/UnityPlugin-AVProVideo#1806]
**Describe the issue**
Playing multiple videos results in a black screen on mobile

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.27
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 1.11.5
 - Operating system version: Android 11
 - Device model: Nokia 8.1
 - Video specs: 
 https://drive.google.com/drive/folders/1BFos4R-Jh6HKlOra79rWx1WcDVeX8cE5?usp=sharing

**To Reproduce**
1. Use the MediaPlayer
2. Loading multiple videos may result in some not playing.

**Videos**
[If applicable, add a copy of your video or the URL](https://youtu.be/zui5SVlzwKE)

**Comment by Chris-RH** [comment]
Every Android device will be limited at some level with how many videos it can play back at the same time. Factors include - resolutions, bitrates. framerates, codecs, the hardware in the device. If you can play each video by themselves, then the playback system is working as it should. If it is multiple videos played together you are find issues with, then that is as above - just the limitations of the device.

The fundamental problem is that devices cannot play multiple videos at once. Some Android devices can only provide only one decoder instance at a time to an app, some can offer multiple but with a limit. This varies per device and there is no consistent behavior (as of Android 12 there is some improvement - see next paragraph). ExoPlayer takes a conservative approach, and only occupies one codec instance at a time, e.g. when moving between items in a playlist ExoPlayer makes sure to first release a codec before acquiring the next one.

The general suggestion is to ensure you have only one player instance at a time playing video, if not having one instance in total in your app. On Android 12, the platform introduced the [performance class](https://developer.android.com/topic/performance/performance-class) by which an app can figure out if the device can provide multiple decoders concurrently, hence the app can do multiple playbacks.

The only other possible solution would be to playback some of the videos as 'software decoded'.
