### ISSUE TITLE
IMediaCache.AddMediaToCache blocks main thread on iOS when 100% Packet Loss

### ISSUE THREAD

**Issue by jesus-mgtc** [RenderHeads/UnityPlugin-AVProVideo#1808]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When using `IMediaCache.AddMediaToCache` on iOS, having 100% Package Loss turned on under `Settings > Developer > Network Conditioner`, the game freezes completely for 10-15 seconds. This call under this conditions seems to block the main thread. **This might also affect Android, although I have no way to test it**

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.19f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.3 Ultra
 - Operating system version: MacOS 14.1.1
 - Device model: iPhone 14 Pro
 - Video specs (resolution, frame-rate, codec, file size): Irrelevant. All videos fail

**To Reproduce**
1. Turn on `100% Package Loss` under `Settings > Developer > Network Conditioner`
2. Make a call to `IMediaCache.AddMediaToCache` to cache any video from remote
3. See how the main thread gets blocked and the execution can't continue

**Logs**
No logs. Just a freeze without error

**Comment by jesus-mgtc** [comment]
Greetings! Any news on this topic? Had any chance to look at it? Thank you

**Comment by MorrisRH** [comment]
A fix for this will make it into the next release (version 3.0.5)

**Comment by MorrisRH** [comment]
1. As long as you don't make any other calls on the cache interface until after AddMediaToCache has returned I can't see any reason for this not to work.
2. This will affect any of the Apple platforms.
