### ISSUE TITLE
couldn't find "libAVProLocal.so"

### ISSUE THREAD

**Issue by LuisCRSousa** [RenderHeads/UnityPlugin-AVProVideo#181]
I'm having a problem with 64 bits I think.  App keeps throwing the following error.
I've set  /Assets/Plugins/Android/Libs/arm64-v8a to Android ARM64.

Unity   : AndroidJavaException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.karmakai.loulera-nY6A1ENpakRf604cuxqfdw==/base.apk", zip file "/data/app/com.karmakai.loulera-nY6A1ENpakRf604cuxqfdw==/split_config.arm64_v8a.apk"],nativeLibraryDirectories=[/data/app/com.karmakai.loulera-nY6A1ENpakRf604cuxqfdw==/lib/arm64, /data/app/com.karmakai.loulera-nY6A1ENpakRf604cuxqfdw==/base.apk!/lib/arm64-v8a, /data/app/com.karmakai.loulera-nY6A1ENpakRf604cuxqfdw==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libAVProLocal.so"

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.8
 - AVPro Video version: 1.10
 - Operating system version: windos 10
 - Device model: samsung s9
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by AndrewRH** [comment]
Hi,

This is easily solved.  Just go to the /Plugins/Android/libs/arm64 folder and select each file there in Unity.  Then in the Inspector set the Platform to Android and the Architecture to ARM64.  His Apply and do this for each file.  The builds should then work for 64-bit.

I hope that works?
