### ISSUE TITLE
Are MJPG videos supported?

### ISSUE THREAD

**Issue by SatishReddyBethi** [RenderHeads/UnityPlugin-AVProVideo#1810]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
We are trying to play an `.mjpg` stream on our app using AVPro.
However, we are not able to, and we get the following error message:
```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
```

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.18f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): version 2.9.3 (plugin v2.8.5f1-ultra)
 - Operating system version: Windows 11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Open the demo scene `Demo_DisplayComponents.unity`
2. Change `Media Source` from `Reference` to `Path`
3. Change `Relative to Streaming Assets Folder` to `Absolute Path Or URL`
4. Enter the following URL: `http://47.181.86.62:8082/mjpg/video.mjpg`
5. Enter Play Mode (You will see the above mentioned error and nothing will load)

**Logs**
```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1406)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:828)
```

**Comment by Chris-RH** [comment]
.mjpg as a container is not supported.  It should work in a different container, such as .mov
