### ISSUE TITLE
Toggling "Loop" on MediaPlayer doesn't cause the video to loop

### ISSUE THREAD

**Issue by cauberthonda** [RenderHeads/UnityPlugin-AVProVideo#1812]
**Describe the issue**
Toggling "Loop" on MediaPlayer doesn't cause the video to loop.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.201f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Version 3.0.0 - 22 March 2024, Core Mobile Edition
 - Operating system version: Sonoma 14.4.1
 - Device model: MacBook Pro 14-inch, Nov 2023, M3 Pro
 - Video specs (resolution, frame-rate, codec, file size): videos don't seem to matter. HD/2K, 25/30 fps all cause the problem

**To Reproduce**
1. Create a Canvas (Canvas, Graphics Raycaster and Canvas Renderer components). Make inactive
2. Parent a gameobject. Add Canvas Renderer, MediaPlayer and Display uGUI components. Assign respective MediaPlayer to uGUI component. 
3. Select a video from StreamingAssets folder. Make sure Auto Open, Auto Play and Loop are ticked.
4. Press Play button
5. Make Canvas active after play has started. Video should play once then stop.

**Comment by cauberthonda** [comment]
Are there any workaround scripts to get our current project to the finish line?

**Comment by MorrisRH** [comment]
Apologies for so taking so long to get back to you on this.
I've been unable to reproduce this in version 3.0.4 so if you upgrade to the latest I'm hoping this is resolved for you.
