### ISSUE TITLE
Audio Output Mode "Unity" Has No Effect in Unity Editor (macOS)

### ISSUE THREAD

**Issue by MisutaaAsriel** [RenderHeads/UnityPlugin-AVProVideo#1813]
### Issue
When trying to use Unity AudioSources as the primary output in testing, on macOS, Audio is instead output to System, bypassing linked AudioSources, irregardless of the fact `PlatformOptionsMacOSX.audioMode == AudioMode.Unity`.

### Environment
 - Unity version: 2022.3.6f1 (x86-64)
 - AVPro Video version: 2.8.5-trial build 1892
 - Operating System version: macOS Sonoma
 - Device Model: MacBook Air M2
 - Video Specs: ALL VIDEO (local/streaming, H264) (n/a)

&nbsp;

- VRChat SDK 3.5.2
- Architech's Video Player Shim 0.15.4

### Reproduction
1. Set audio mode to Unity (in this case, handled by Architech's VPS)
2. Set AVPro video player to output to a Unity AudioSource
3. Open media in Play Mode

Result: Audio bypasses Audio Source, Audio Mixer, and Unity audio system, outputting directly to system as if `AudioMode.System` was chosen.

**Comment by MisutaaAsriel** [comment]
### Update
As of a few minutes ago for no explicable reason, this stopped happening. I… honestly cannot explain it. I had given up trying, and moved on to other things, and now it's just… working.

**Comment by Chris-RH** [comment]
Is this reproducible using a new project and AVPro Video mediaplayer demo?

**Comment by MisutaaAsriel** [comment]
> Is this reproducible using a new project and AVPro Video mediaplayer demo?

100%. In fact, I found the behaviour even more strange, and it is something I have noticed recently in my original project too:

The audio will output to Unity **on the first playthrough after Unity has been opened, only.** On subsequent play-throughs, **the audio is output System-Direct, irregardless of the player's setting.**

**Comment by Chris-RH** [comment]
Thank you, its on our list of things to investigate :)

**Comment by MorrisRH** [comment]
I'm unable to reproduce this using version 3.0.4.
