### ISSUE TITLE
CPU usage over 80%

### ISSUE THREAD

**Issue by YuvalMasteyCreativeLabs** [RenderHeads/UnityPlugin-AVProVideo#1815]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I am experiencing an issue with excessive CPU usage on Android devices during local playback of a 4K MP4 video using AVPro Video in Unity. Despite the expectation for such tasks to primarily leverage the GPU, thereby maintaining balanced CPU usage, it has been observed that the GPU remains largely underutilized throughout the playback process. This behavior contrasts starkly with the smooth playback performance achieved when the same video file is played using an offline player app, which suggests that the offline player manages to engage the GPU effectively, mitigating the CPU load. This discrepancy raises concerns regarding the configuration or handling of video playback within the Unity environment, particularly in the context of local (non-streamed) content, where hardware acceleration should feasibly minimize CPU strain

Its Only on Android on Windows i see the GPU works fine.
**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version 3.0 
 - Operating system version: Android
 - Device model: Minix 35 Plus
 - Video specs Mp4 4k, 12kbitrate

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/143925336/a5e85652-42ce-4461-8717-5b08ff2619c9)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. I can't find information about Minix 35 Plus online.  Do you have a link to some specifications? I need to see what hardware it is running to better understand its capabilities.
2. Which version of Unity are you using?
3. What Android OS version is it running?
4. Are you using Exoplayer or Android Mediaplayer?
5. Are you using Vulkan or OpenGLES?
6. Have you tried OES rendering?
7. Are you testing in a new project, running only the AVPro Video mediaplayer demo scene?
8. Have you tested using Unity's videoplayer?
9. What are the full specs of the video? actual resolution, codec, FPS, length etc
10. Can you provide a copy of your sample video - unitysupport@renderheads.com

**Comment by YuvalMasteyCreativeLabs** [comment]
1. minix spec https://www.minix.com.hk/products/x35i-plus
2. Unity 22.3.23f1
3. android 11.
4.I use EXOplayer in mediaPlayer Game Object
5. i tryed vulkan and openGLES3.2
6.i didnt try OES rendering due to your doc about only VR contect
7.tested in the unity project also and same results abit less around 5%
8. i tested in Unity media player and i get around 60% cpu usage.
9.video spec , 4k, codec tryed in H265, H264 (H265 better results around 80% cpu and H264 around 95%) ,bitrate 10143k, FPS tryed both 30/ 60, length 1 minute.
10. sample video link https://file.io/ILwnUuBPyr4w

**Comment by Chris-RH** [comment]
Ahh, that's a 6 year old GPU.
Do you get the same results when you use [2.9.3](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/2.9.3)?
Have you tried lower resolution videos?

**Comment by Chris-RH** [comment]
Ahh, that's a 6 year old GPU.
Do you get the same results when you use [2.9.3](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/2.9.3)?
Have you tried lower resolution videos?

**Comment by Chris-RH** [comment]
Closed due to lack of reply

**Comment by YuvalMasteyCreativeLabs** [comment]
Dear AVPRO Support Group,

We are currently using the AVPro Core Edition and are interested in exploring the upgrade path to the Ultra Edition.

Would you be able to provide us with information on the upgrade cost for our existing license?
Best Regards,


***@***.***
***@***.***
[Text  Description automatically generated] [Icon  Description automatically generated] <https://www.linkedin.com/company/creative-labs-israel/> [Icon  Description automatically generated] <https://www.facebook.com/CreativeLabsIsrael> [Icon  Description automatically generated] <https://instagram.com/creative_labs_israel?igshid=YmMyMTA2M2Y=> [Text, logo  Description automatically generated with medium confidence] <http://www.creativelabs.co.il/>

**Comment by YuvalMasteyCreativeLabs** [comment]
AVPRO Support Group , Hello again,

Please see below, checking in with you guys to see I f we can an answer regarding the questions below?


Best Regards,






[Image]
[Image]
[Text  Description automatically generated] [Icon  Description automatically generated] <https://www.linkedin.com/company/creative-labs-israel/> [Icon  Description automatically generated] <https://www.facebook.com/CreativeLabsIsrael> [Icon  Description automatically generated] <https://instagram.com/creative_labs_israel?igshid=YmMyMTA2M2Y=> [Text, logo  Description automatically generated with medium confidence] <http://www.creativelabs.co.il/>


From: Yuval Mastey ***@***.***>
Date: Wednesday, 22 May 2024 at 17:35
To: RenderHeads/UnityPlugin-AVProVideo ***@***.***>
Cc: Guy Brill ***@***.***>
Subject: AVPro Upgrade Plan

Dear AVPRO Support Group,

We are currently using the AVPro Core Edition and are interested in exploring the upgrade path to the Ultra Edition.

Would you be able to provide us with information on the upgrade cost for our existing license?
Best Regards,


***@***.***
***@***.***
[Text  Description automatically generated] [Icon  Description automatically generated] <https://www.linkedin.com/company/creative-labs-israel/> [Icon  Description automatically generated] <https://www.facebook.com/CreativeLabsIsrael> [Icon  Description automatically generated] <https://instagram.com/creative_labs_israel?igshid=YmMyMTA2M2Y=> [Text, logo  Description automatically generated with medium confidence] <http://www.creativelabs.co.il/>

**Comment by Ste-RH** [comment]
@YuvalMasteyCreativeLabs all upgrade information can be found in the documentation [here](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/download.html#owners-of-avpro-video-2x).
