### ISSUE TITLE
I have successfully VR180 Side by Side Video build on Vision Pro. However, it seems that the stereoscopic effect is not working.

### ISSUE THREAD

**Issue by VENTAXR** [RenderHeads/UnityPlugin-AVProVideo#1816]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I have successfully VR180 Side by Side Video build on Vision Pro.
However, it seems that the stereoscopic effect is not working.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.20f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0 Ultra Edition
 - Operating system version: visionOS 1.1
 - Device model: AppleVision Pro
 - Video specs (resolution, frame-rate, codec, file size): 8192x4096(Side by Side) 60fps H.265  

**To Reproduce**
1. I referred to "Video was not displayed in Vision Pro when using Polyspatial"
2. I used ResolveToRenderTexture instead of Apply to Mesh. Then, I created a RenderTexture, connected it, and directly linked it to the Material.
3. but.. stereoscopic effect is not working.

**Logs**
If applicable, add error logs to help explain your problem.
none.. build perfect

**Screenshots**
![s1](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/111479402/113349b0-1f93-441c-ad7b-97884ab66048)
![2](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/111479402/2794a69c-3df2-4ff9-887a-99fdb6c3a52d)
![3](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/111479402/e29a1128-f08f-4cdd-811e-5779405927db)

**Videos**
The video connection and playback work well. I shared the file with you last time.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
You seem to have two Upadate Multi-Pass Stereo components.
We think this could be a shader issue.   Polyspatial mode only supports unity’s built-in shaders or shaders built with shader graph, so we need to look at how we can adapt ours within the constraints of what Apple allows.

**Comment by Chris-RH** [comment]
AVPro Video version 3.1 has been released
