### ISSUE TITLE
IsMediaCachingSupported returns false on android (Latest 3.0.0 Trial version)

### ISSUE THREAD

**Issue by TrusharRadadiya** [RenderHeads/UnityPlugin-AVProVideo#1822]
**Describe the issue**
I'm using the latest 3.0.0 trial version to test because our project needs a caching feature that is not supported on the Unity video player. 

I'm playing the video from the URL like this: https://storage.googleapis.com/district-pass.appspot.com/images/42dbe713-747f-47be-b847-44764e632c3a.mp4

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.20f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.0 trial
 - Operating system version: Android 12
 - Device model: POCO X3 Pro
 
At first, It was causing the build error with 'guava-31.1-android' file. But I managed to solve it by unchecking the box.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/82151539/07e659a7-845b-47ba-876e-aeb8a9d201f0)

Is this happening because I unchecked it?

**Comment by Chris-RH** [comment]
1. Are you using Vulkan or OpenGLES?
2. Can you reproduce it in a new project running only AVPro Video? (without unchecking the guava box)
3. Have you followed the caching [stipulations](https://renderheads.com/content/docs/AVProVideo/articles/feature-caching.html#android)?

**Comment by Chris-RH** [comment]
Closed due to lack of reply
