### ISSUE TITLE
iOS xcode build faild ld: Undefined symbols:   __swift_FORCE_LOAD_$_swiftXPC, referenced from:       l6268 in libAVProVideo.a[2](libAVProVideo.a-arm64-master.o)

### ISSUE THREAD

**Issue by zhiys** [RenderHeads/UnityPlugin-AVProVideo#1824]
help

**Comment by Chris-RH** [comment]
Please can you provide more information:

 - Unity version: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: 
 - Xcode version:
 - Device model: 
 - Full error log

Can you reproduce this in a fresh project using only AVPro Video?

**Comment by zhiys** [comment]
unity version：2020.3.46f1
AVPro：3.0.0
XCode vesion：15.1
Device model:mac mini

**Comment by zhiys** [comment]
my xcode project use pods

**Comment by zhiys** [comment]
and new empty unity project has question also

**Comment by Chris-RH** [comment]
Can you provide a full error log please

**Comment by zhiys** [comment]
[Build Unity-iPhone_2024-04-16T16-08-03.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/14994865/Build.Unity-iPhone_2024-04-16T16-08-03.zip)

full log please

**Comment by Chris-RH** [comment]
Could you try upgrading to xcode 15.3 please and see if that works?

**Comment by zhiys** [comment]
I upgraded to xcode15.3 and indeed compiled successfully

**Comment by felipecastrosales** [comment]
> Author

for me is not possible at this moment. any suggestions?

**Comment by felipecastrosales** [comment]
> I upgraded to xcode15.3 and indeed compiled successfully

for me it is not possible at the moment. Any suggestions?
