### ISSUE TITLE
Mobile Core edition install problem

### ISSUE THREAD

**Issue by luzidlab** [RenderHeads/UnityPlugin-AVProVideo#1825]
Unity 2022.3.12f1
AVPro Core Mobile edition 3.0.0
OSX Sonoma 14.1

I purchased AVPro Core Mobile edition. I created an empty project as described in the help files. I installed the plugin via package manager and after installation the "purchase" button is active and in "about" it displays "plugin v3.0.0 -trial build 2403201034"

I have been working on two projects that uses (or used) the trial version. Should I clean up other files outside of the project folder in order to correctly install the purchased version, even in a fresh project?

t.i.a.
Mike

**Comment by Chris-RH** [comment]
Hi @luzidlab, 

Yes, that is correct.  As it is the mobile version, it is classed as "trial" when in the editor and will display a watermark.  When you build your app to mobile, there will be no watermark.
You don't need to clean up AVPro files when upgrading.  More information on installation, upgrade from trial version, and watermarks[ here](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/install.html).

**Comment by luzidlab** [comment]
Thanks for the quick reply it works!
