### ISSUE TITLE
[Android] Got Green Screen after play HDR video on Vulkan

### ISSUE THREAD

**Issue by tinigon89** [RenderHeads/UnityPlugin-AVProVideo#1827]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.
I got a green noisy screen after play a HDR video(it play fine) then stop and play normal video H264 without HDR and vice verse

i use these code to stop mediaplayer:
mediaPlayer.Stop();
mediaPlayer.CloseMedia();

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.22f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0
 - Operating system version: Android
 - Device model: Z Fold 5
 - Video specs (resolution, frame-rate, codec, file size): 
Video
ID                          : 1
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main 10@L5@High
HDR format                  : SMPTE ST 2086, HDR10 compatible
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 2 h 5 min
Bit rate                    : 16.6 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.084
Stream size                 : 14.6 GiB (93%)
Title                       : Iron Man 2008 | IMAX
Language                    : English
Default                     : Yes
Forced                      : No
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : PQ
Matrix coefficients         : BT.2020 non-constant
Mastering display color pri : Display P3
Mastering display luminance : min: 0.0050 cd/m2, max: 4000 cd/m2

**To Reproduce**
1. Open a video with HDR
2. then stop video
3. Then open a video without HDR

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![fd1d5cac-7bf1-4948-b98e-b2caf8539716](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/3837545/f5b53995-bdfb-4969-a851-ffc3f1ad25f6)

**Videos**
If applicable, add a copy of your video or the URL
https://drive.google.com/file/d/18veeLImd7i3Z1CqKubAVbEZ3ASepGnRL/view?usp=drive_link

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @tinigon89 

We don't currently support HDR, see #1502

**Comment by tinigon89** [comment]
> Hi @tinigon89
> 
> We don't currently support HDR, see #1502

Hi, i mean it play HDR video ok(in SDR mode) but when switch to non HDR video it have problem above, i think it have problem with surface texture. Do you have anyway to reset the texture?

**Comment by Chris-RH** [comment]
1. Are you using Exoplayer or Android Mediaplayer?
2. Are you using OpenGLES or Vulkan? Could you try both please and let us know if it occurs in both or not :)
3. What are the details of the other video you are trying to play?
4. Can you provide a full logcat from the moment you load the app on the device please

**Comment by tinigon89** [comment]
> 1. Are you using Exoplayer or Android Mediaplayer?
> 2. Are you using OpenGLES or Vulkan? Could you try both please and let us know if it occurs in both or not :)
> 3. What are the details of the other video you are trying to play?
> 4. Can you provide a full logcat from the moment you load the app on the device please
1. Im using Exoplayer
2. i changed from Vulkan to OpenGLES and it ok now.

**Comment by MorrisRH** [comment]
This has been fixed and will make it into the next release (version 3.0.11)

**Comment by Ste-RH** [comment]
@tinigon89 AVPro Video v3.0.11 has now been released. Do let us know if this fixes the issue for you.
