### ISSUE TITLE
The video played by the generated mac app will be black for a long time

### ISSUE THREAD

**Issue by xuqianxg** [RenderHeads/UnityPlugin-AVProVideo#1828]
Problem description:

The video played by the generated mac app will be black for a long time,One mac m1 chip is fine but the m2 chip is

Device (which devices are you having the issue with - model, OS version number):

Mac m2 chip

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

It's just an 8-megabyte video

System Information:

AVPro Video: v2.7.3 (plugin v2.7.0f1-ultra)
Target Platform: Standalone
Unity: v2020.3.28f1 WindowsEditor
OS: Desktop - OptiPlex 7070 (Dell Inc.) - Windows 11  (10.0.22631) 64bit - ChineseSimplified
CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz - 8 threads - 32549KB
GPU: NVIDIA GeForce GTX 1650 - NVIDIA - Direct3D 11.0 [level 11.1] - 3962KB - 16384

**Comment by Chris-RH** [comment]
We've not seen this issue ourselves on the M2.
Please can you send us a sample of the video you are having issues with: unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
We've not seen this issue ourselves on the M2.
Please can you send us a sample of the video you are having issues with: [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Chris-RH** [comment]
I'm sorry, we can't help you without further information

**Comment by xuqianxg** [comment]
I updated to unity 2022.3.28 and this bug fixes what appears to be a unity bug
