### ISSUE TITLE
iOS bug 3.0.0 - video restarts inappropriately after app focus restored

### ISSUE THREAD

**Issue by daveb-tactic** [RenderHeads/UnityPlugin-AVProVideo#1829]
**Describe the issue**
On iOS when the app has finished playing a video, then the app loses focus and then gains focus, the video starts playing again from the start. AutoPlay is not enabled on the mediaplayer.

Also (possibly related) on Windows in the editor, we notice that the "Auto Play" check box is automatically checked if the Unity Pause button is pressed and then pressed again (unpaused). And this results in the same behavior (video starts playing again).

**Your Setup (please complete the following information):**
 - Unity 2023.2.12f1
 - 3.0.0 version of AVPro Video (Core Edition),  
 - OS: iOS 17.4
 - Device model: iPhone 12

**To Reproduce**
1. Modify existing demo scene "Demo_MediaPlayer" so that AutoPlay is disabled and looping playback is disabled.
2. Buid the demo app for iPhone.
3. Press the play button on iPhone and watch the video play to end
4. Minimize the app, then restore
5. Observe that the video plays without any user input

**Comment by Chris-RH** [comment]
Its unlikely to be anything to do with Autoplay.  App resuming is quite complex.  It'll be something with the app restore code applying state when it shouldn't.

**Comment by DreamYao** [comment]
I have the same problem

**Comment by MorrisRH** [comment]
A fix for this will make into the next release (version 3.0.4)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.4 has been released.  Please let us know if it has not fixed your issue.
