### ISSUE TITLE
Oculus Quest 2 Black Screen

### ISSUE THREAD

**Issue by EllaRed** [RenderHeads/UnityPlugin-AVProVideo#1830]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Videos are not playing. Followed the end resolution in a similar issue thread. Did not help. Even the demo scenes that came with the package are not playing(with OES shader). Only a Black screen with no audio. After a few more trial and error builds, I believe it's an addressing issue. Absolute obb paths simply don't work. And I don't have a server or cloud to download or stream the videos. android manifest has the MANAGE_EXTERNAL_STORAGE, legacyext and pre android 10 read write permissions.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.16f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v3.0 core mobile
 - Operating system version: windows 11
 - Device model: Lenovo Legion 5 Pro
 - Video specs (resolution, frame-rate, codec, file size): 600mb and above. Stored in obb, address using standard obb absolute path. 
 Even the provided sample video in the streaming assets folder are not working, as stated.

**To Reproduce**
1. Install v3.0 via package manager
2. Make a build on quest 2, ensure demo scene is the build settings.
3. play the build.
further notes: attempted builds with arm7 and 64, both gave the same result. Low overhead mode in oculus settings is turned off. stereo rendering mode is multipass. using OES shaders.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by EllaRed** [comment]
the sdcard/Download file path works (manually put the video there via sidequest), so it's definitely not a manifest permission issue.

**Comment by Chris-RH** [comment]
1. Is the video not playing at all, or is there audio playing but video is blank?
2. Are you using the [Update Stereo Multipass component](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/component-update-multipass-stereo.html)?
3. Have you tried both Vulkan and OpenGLES?
4. Have you tried both Exoplayer and Android Mediaplayer?
5. Have you tried starting with a fresh project and the AVPro Video demo scene to check that it works before changing other settings and trying to open your own file?
6. Does your video play from streaming assets?
7. What scripting are you using to load your video?

**Comment by EllaRed** [comment]
1. There is no Audio
2. Yes
3. No, I have not tried using Vulkan
4. No, I do not know which player is currently selected or how to change it.
5. demo files provided with the package play with their settings untouched
in my project. I have not tried creating an empty project just to test that.
6. My videos are too large to play from streaming assets ( over 600 mb) I
attempted to make a build with them in streaming assets, but it failed.

**Comment by Chris-RH** [comment]
Have you tried saving it in Application.persistentDataPath ?
Could you provide a full logcat please?

**Comment by EllaRed** [comment]
That would require users needing to download the videos, which I earlier
stated I do not wish to do as much as possible. I assume a persistent path
would also work considering SD card/Downloads did after manually placing
the files there, as I also earlier stated.

**Comment by Chris-RH** [comment]
Could you provide a full logcat please?

**Comment by EllaRed** [comment]
Sorry, I can't at this time as I'm no longer on this project, when I am
able I will, as we are still experiencing this issue.
