### ISSUE TITLE
MediaPlayer.Control.GetProgramDateTime() returns 01/01/2001 on android

### ISSUE THREAD

**Issue by flogavel** [RenderHeads/UnityPlugin-AVProVideo#1831]
**Describe the issue**
GetProgramDateTime always returns 01/01/2001 on android devices after update to V3.0.0.
I'm sending a sample project to reproduce the issue. It is just the 3D Unity project template with a MediaPlayer reading a file from an url, with auto open & play enabled, and a script showing the result of GetProgramDateTime at each frame on a Text (top left corner).

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.11
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.0 ultra
 - Operating system version: Android
 - Device model: All
 - Video specs (resolution, frame-rate, codec, file size): All

**To Reproduce**
1. Open the project sent to unitysupport@renderheads.com (mail object is "Bug Report GetProgramDateTime"
2. Switch to android
3. Build and run (you can also use the Apk from "Builds Folder"

**Logs**
-

**Screenshots**
-

**Videos**
-

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Email object "Bug Report GetProgramDateTime"

**Comment by Chris-RH** [comment]
Thanks for your email, we'll have a look at that shortly.
I just wanted to clarify..
You said "after update to 3.0.0", so do you mean that it worked in 2.9.3 and now no longer works in the same project after updating to version 3?

**Comment by flogavel** [comment]
Hello,

I'll be on holiday starting tonight, so I'm adding Kilian ***@***.***)
to this conversation in case you have any question / solutions to share.

Thanks,
Florian Gavel

**Comment by KikiLebrun** [comment]
Hi, We were wondering if there is any news on this topic ?
thanks!

**Comment by Chris-RH** [comment]
I believe GetProgramDateTime will only be valid for LIVE streams

**Comment by KikiLebrun** [comment]
Hello, thank you for your answer,
but we use the GetProgramDateTime on HLS stream, and this method is working on all other platform, including visionOS, iOS, or windows. I was wondering if we need to test something to give you some hints on the issue, if yes don't hesitate to tell us

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.2 has been released.  Please let us know if it has not fixed your issue.

**Comment by NicolasDebeurme** [comment]
Hi @Chris-RH @Ste-RH, Nicolas here member of the team that created this issue, I just tested the fix with latest version (V3.0.4) of AVPro-Video. I can indeed see that GetProgramDateTime() do return a value now that is perfectly right in a case of an ended HLS Stream, but when the stream is LIVE the value received from the method veries depending on the platform. With every platform tested (IOS/MACOS/ANDROID/WINDOWS), I can tell that only the Android Platform returns an incorrect value when we Log the timestamp at the exact same time in the stream. I have also seen that the gap increase has the stream gets longer.

**Comment by NicolasDebeurme** [comment]
Hello ! Do you have any news on this ? We would love to migrate our product to AVProVideo V3.0.0+ but we are stuck because of this bug. We really need this feature to work.

**Comment by NicolasDebeurme** [comment]
Hello @MorrisRH @Ste-RH @Chris-RH, any update on that ? Thank you !

**Comment by Chris-RH** [comment]
Hi @NicolasDebeurme, 

The dev team is on annual leave at the moment.  They should be back in the office from Tuesday of next week.

Kind regards, 
Chris

**Comment by Ste-RH** [comment]
@NicolasDebeurme do you have a test stream that shows this issue? Everything stream I have tried, that gives back a time, just returns 'current UTC time'.  I have also left it an hour and noticed no drift.

**Comment by Ste-RH** [comment]
Thanks for letting us know @KikiLebrun .  Really glad it's all sorted for you.

If you have a few moments free, it would really help us (and the asset) out if you could leave an honest review of AVPro Video (and the support offered) on the Unity Asset Store.  No worries if you don't have time.  We know how slammed developers time gets!
