### ISSUE TITLE
Scene Demo_MediaPlayer Behavior Error In Android

### ISSUE THREAD

**Issue by nero030250** [RenderHeads/UnityPlugin-AVProVideo#1832]
**Describe the issue**
I encountered abnormal behavior when playing the Demo_MediaPlayer scene in the demo on Android 9.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.12f1: 
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v3.0.0 Trial
 - Operating system version: Android9
 - Device model: samsung SM-G9730
 - Video specs (resolution, frame-rate, codec, file size): 
 
**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/7139025/5bed92dd-8997-43b5-ad15-29508fdbbcbe)

**Comment by Chris-RH** [comment]
1. Have you tried re-importing AVPro video?
2. Is that a fresh project running only the AVPro Video mediaplayer demo scene?
3. Are you using Vulkan or OpenGLES?
4. Are you using Exoplayer or Android Mediaplayer?
5. What device are you testing on?
6. Can you provide a full logcat please from just before you start the app?

**Comment by nero030250** [comment]
I import AVPro Video in new project.
Graphics APIs Vulkan and OpenGLES3.
I tried Exoplayer and Mediaplayer.
I am using the LDPlayer emulator Android 9.

**Comment by Chris-RH** [comment]
Could you test it on an actual device rather than an emulator please?
Can you provide a full logcat please from just before you start the app?

**Comment by Ste-RH** [comment]
@nero030250 We will be closing this issue soon due to lack of response.  If you have time, can you please update us.
