### ISSUE TITLE
Adjusting Audio Sync in AVPro Video

### ISSUE THREAD

**Issue by KihyunIm-Litiv** [RenderHeads/UnityPlugin-AVProVideo#1833]
**Question**
Is there a way to intentionally advance or delay the sync of audio when playing a video through AVPro Video?

**Comment by KihyunIm-Litiv** [comment]
Additional information: Playing an m3u8 HLS streaming URL

**Comment by Chris-RH** [comment]
There are a variety of reasons for sync issues.  We need a bit more information about your setup

Unity version: 
AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
Operating system version: 
Device model: 
Video specs (resolution, frame-rate, codec, file size): 
Test video URL:
Can you reproduce this in a new project running only the AVPro Video mediaplayer demo scene?
Do you have the same issue when playing that video locally?

**Comment by KihyunIm-Litiv** [comment]
> There are a variety of reasons for sync issues. We need a bit more information about your setup
> 
> Unity version: AVPro Video version (number and edition (trial/core/ultra/enterprise)): Operating system version: Device model: Video specs (resolution, frame-rate, codec, file size): Test video URL: Can you reproduce this in a new project running only the AVPro Video mediaplayer demo scene? Do you have the same issue when playing that video locally?

I'm not dealing with a video sync issue, but rather need to play the original video where the video and audio are out of sync. Is there a way to directly control the audio sync like a PC's video player program?

**Comment by Chris-RH** [comment]
Ah, no we don't do anything like that.  I'd advise re-encoding the video or looking for another source of the video that is in sync.
