### ISSUE TITLE
[macOS] 13.6.4/Unity 2022.3.11f1/AVProVideo Ultra 2.9.3 instant crash trying to load HapQ Alpha videos

### ISSUE THREAD

**Issue by clay-aw** [RenderHeads/UnityPlugin-AVProVideo#1835]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Both in run mode and within the editor, trying to load any MOV that contains HapQ Alpha encoded media causes an instant crash. This is confirmed to occur on a selection of files encoded with the AVF Batch Converter app, regardless of the size of the file, resolution, data rate etc. 

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.11f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 2.9.3
 - Operating system version: macOS 13.6.4
 - Device model: 2017 iMac Retina 5K 4.2 GHz Quad-Core Intel, Radeon Pro 580 8GB
 - Video specs (resolution, frame-rate, codec, file size): Ranging from small (92x92 px, 30fps, HapQ Alpha, 1.1MB) up to medium (1800x1800px, 100fps, HapQAlpha, 4.82GB)

**To Reproduce**
1. Start empty Unity project
2. Import AVPro Video 2.9.3
3. Create MediaPlayer component, and associated Display uGUI component
4. Try selecting a video file from the Streaming Assets folder (using the green folder button) and press the Load button.
5. Instant editor crash

**Logs**
Unity Editor log file shows failed assertion:

-[MTLTextureDescriptorInternal validateWithDevice:]:1344: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor has width of zero.
MTLTextureDescriptor has height of zero.

Entire log file included:
[Editor.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/15111349/Editor.log)

**Videos**
Copies of some smaller videos being used to test, problem reproducible in all cases:

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/161715858/bb823187-9043-46e9-a260-e76ab28fb73f
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/161715858/9f580c5d-bb4a-4c37-b938-5637ace0ae77
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/161715858/68d61b48-1a83-4ef2-9bdf-3785256ea2c1

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Can you reproduce this in a new project running only the AVPro Video mediaplyer demo scene?
Does it work if you turn off Metal Validation in Scheme -> Edit Scheme -> Run -> Diagnostics -> Metal API Validation ?

**Comment by clay-aw** [comment]
Hi Chris,

Yes - even in a completely fresh Unity project using the Demo_MediaPlayer scene, but replacing your RenderHeads-1080p30-H264.mp4 with one of my HAP Q Alpha encoded videos (in my case, I tried uiDialFill.mov) resulted in a full editor crash as soon as the Play button was pressed, as before. 

Re. Your Scheme suggestion, I’m not using Xcode so don’t have access to edit any schemes (we are building in Unity for macOS), but if I untick Metal API Validation in Player settings, the Unity Editor still crashes.

Any further guidance you can provide would be helpful.

Until now, we are forced to not use HAP Q Alpha in our product, and are reverting to HAP Alpha, which is a great shame.

Many thanks,


Adrian

**Comment by MorrisRH** [comment]
I've reproduced this in AVPro Video version 3.0.1
The issue is editor only, HapQ+A files playback fine in the builds I've tested here (both 2.9.3 and 3.0.1).
Will endeavour to find a fix for the next release (3.0.2).
