### ISSUE TITLE
Avpro mobile not create android build in unity

### ISSUE THREAD

**Issue by WebBusiness2019** [RenderHeads/UnityPlugin-AVProVideo#1842]
**Describe the issue**
i am gating this error while building android apk and  i have also configured 
compileSdkVersion 33
minSdkVersion 22
targetSdkVersion 32
and also have android 33 in editor folder but still i can not able build android apk and i am using firebase with it to play video in avpro and i try this also android.suppressUnsupportedCompileSdk=33 as mention in log when i do this i get duplicate cass error

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.20f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): trial
 - Operating system version: windows 11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**Logs**
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33

This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=33
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 33
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preBuild UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:preDebugBuild UP-TO-DATE
> Task :unityLibrary:preDebugBuild UP-TO-DATE
> Task :launcher:preDebugBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:preDebugBuild UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugAidl NO-SOURCE
> Task :unityLibrary:packageDebugRenderscript NO-SOURCE
> Task :launcher:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:compileDebugAidl NO-SOURCE
> Task :unityLibrary:writeDebugAarMetadata UP-TO-DATE
> Task :launcher:generateDebugBuildConfig UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:writeDebugAarMetadata UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:writeDebugAarMetadata UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageDebugRenderscript NO-SOURCE
> Task :unityLibrary:compileDebugAidl NO-SOURCE
> Task :launcher:compileDebugRenderscript NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:packageDebugRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugRenderscript NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:compileDebugRenderscript NO-SOURCE
> Task :launcher:compileDebugAidl NO-SOURCE
> Task :unityLibrary:compileDebugRenderscript NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugResValues UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateDebugResValues UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateDebugResources UP-TO-DATE
> Task :unityLibrary:generateDebugResValues UP-TO-DATE
> Task :unityLibrary:generateDebugResources UP-TO-DATE
> Task :launcher:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:packageDebugResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageDebugResources UP-TO-DATE
> Task :unityLibrary:packageDebugResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:extractDeepLinksDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:extractDeepLinksDebug UP-TO-DATE
> Task :unityLibrary:extractDeepLinksDebug UP-TO-DATE
> Task :unityLibrary:processDebugManifest UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:processDebugManifest UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:processDebugManifest UP-TO-DATE
> Task :unityLibrary:compileDebugLibraryResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:parseDebugLocalResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:parseDebugLocalResources UP-TO-DATE
> Task :unityLibrary:parseDebugLocalResources UP-TO-DATE
> Task :unityLibrary:generateDebugBuildConfig UP-TO-DATE
> Task :unityLibrary:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:mergeDebugShaders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateDebugRFile UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugRFile UP-TO-DATE
> Task :unityLibrary:compileDebugShaders NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:compileDebugLibraryResources UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugLibraryResources UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:generateDebugBuildConfig UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugBuildConfig UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:javaPreCompileDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugJavaWithJavac UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileDebugJavaWithJavac UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibCompileToJarDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibCompileToJarDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeDebugShaders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeDebugShaders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:compileDebugShaders NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:generateDebugAssets UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:compileDebugShaders NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:generateDebugAssets UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:packageDebugAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:packageDebugAssets UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:processDebugJavaRes NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:processDebugJavaRes NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibResDebug NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibResDebug NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeDebugJniLibFolders UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:mergeDebugJniLibFolders UP-TO-DATE
> Task :unityLibrary:xrmanifest.androidlib:mergeDebugNativeLibs NO-SOURCE
> Task :unityLibrary:FirebaseApp.androidlib:mergeDebugNativeLibs NO-SOURCE
> Task :unityLibrary:xrmanifest.androidlib:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :unityLibrary:FirebaseApp.androidlib:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :launcher:checkDebugAarMetadata UP-TO-DATE
> Task :unityLibrary:generateDebugRFile UP-TO-DATE
> Task :launcher:generateDebugResValues UP-TO-DATE
> Task :launcher:generateDebugResources UP-TO-DATE
> Task :unityLibrary:compileDebugJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileToJarDebug UP-TO-DATE
> Task :unityLibrary:generateDebugAssets UP-TO-DATE
> Task :launcher:mergeDebugResources UP-TO-DATE
> Task :launcher:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :launcher:extractDeepLinksDebug UP-TO-DATE
> Task :launcher:processDebugMainManifest UP-TO-DATE
> Task :launcher:processDebugManifest UP-TO-DATE
> Task :launcher:processDebugManifestForPackage UP-TO-DATE
> Task :unityLibrary:packageDebugAssets
> Task :unityLibrary:processDebugJavaRes UP-TO-DATE
> Task :unityLibrary:bundleLibResDebug UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :launcher:processDebugResources UP-TO-DATE
> Task :launcher:compileDebugJavaWithJavac UP-TO-DATE
> Task :launcher:mergeDebugShaders UP-TO-DATE
> Task :launcher:compileDebugShaders NO-SOURCE
> Task :launcher:generateDebugAssets UP-TO-DATE
> Task :unityLibrary:mergeDebugJniLibFolders
> Task :launcher:mergeDebugAssets
> Task :launcher:processDebugJavaRes NO-SOURCE
> Task :launcher:compressDebugAssets
> Task :launcher:mergeDebugJavaResource UP-TO-DATE
> Task :launcher:checkDebugDuplicateClasses FAILED
> Task :launcher:dexBuilderDebug UP-TO-DATE
> Task :unityLibrary:mergeDebugNativeLibs
71 actionable tasks: 6 executed, 65 up-to-date

**Screenshots**
![Setup-1](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/51046345/a2f53fc1-250c-4dcf-abff-6cb363be1c75)
![Setup-2](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/51046345/06abaf38-afa6-4864-bf98-dd4f64de6ede)
![Setup-3](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/51046345/027f3157-adce-49bb-8376-fb30bc432a29)

**Comment by WebBusiness2019** [comment]
if i remove avpro package from unity build completed successdully and run all the things in app but while importing avpro in unity its only work in editor mode and give error while creating an android build

**Comment by Chris-RH** [comment]
I'm not seeing any AVPro errors in that log.

**Comment by WebBusiness2019** [comment]
But when I remove package from the unity my app work correctly and there is
not problem with avpro it's work fine in editor mode but when you going to
create build it's showing error that requires compile SDK version 33 and I
have already done required step to solve this error in plugin folder

**Comment by Chris-RH** [comment]
Have you tried upgrading your gradle to a more recent version?

**Comment by WebBusiness2019** [comment]
No I am using inbuilt unity gargle....
I have to download upgraded gradle and have to add gradle externally in
unity?

Is there any related documentation available?

**Comment by Chris-RH** [comment]
You've still not shown me exactly what the error is that you are getting.  Please can you click on the error line "Task :launcher:checkDebugDuplicateClasses FAILED" and paste the results.

**Comment by WebBusiness2019** [comment]
* What went wrong:
Execution failed for task ':launcher:checkDebugDuplicateClasses'.
> A failure occurred while executing
com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.common.annotations.Beta found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.annotations.GwtCompatible found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.annotations.GwtIncompatible found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.annotations.VisibleForTesting found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.Absent found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.AbstractIterator found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.AbstractIterator$1 found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.AbstractIterator$State found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.Ascii found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CaseFormat found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CaseFormat$1 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CaseFormat$2 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CaseFormat$3 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CaseFormat$4 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CaseFormat$5 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CaseFormat$StringConverter
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$1 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$And found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Any found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$AnyOf found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Ascii found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$BitSetMatcher found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$BreakingWhitespace
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Digit found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$FastMatcher found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$ForPredicate found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$InRange found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Invisible found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Is found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$IsEither found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$IsNot found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$JavaDigit found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$JavaIsoControl
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$JavaLetter found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$JavaLetterOrDigit
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$JavaLowerCase found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$JavaUpperCase found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$NamedFastMatcher
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Negated found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$NegatedFastMatcher
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$None found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Or found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$RangesMatcher found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$SingleWidth found
in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.CharMatcher$Whitespace found in
modules jetified-guava-31.1-android (com.google.guava:guava:31.1-android)
and jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.Charsets found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CommonMatcher found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.CommonPattern found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.Converter found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.Converter$1 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.Converter$1$1 found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.Converter$ConverterComposition
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class
com.google.common.base.Converter$FunctionBasedConverter found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.Converter$IdentityConverter
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.Converter$ReverseConverter
found in modules jetified-guava-31.1-android
(com.google.guava:guava:31.1-android) and jetified-guava-31.1-android
(guava-31.1-android.jar)
     Duplicate class com.google.common.base.Defaults found in modules
jetified-guava-31.1-android (com.google.guava:guava:31.1-android) and
jetified-guava-31.1-android (guava-31.1-android.jar)
     Duplicate class com.google.common.base.E<message truncated>

**Comment by Chris-RH** [comment]
Unfortunately that is guava library error that occurs when you have more than one asset requiring guava libraries.  Its not specific to AVPro (In fact the library is required by Exoplayer, not our asset).

Obviously in this case you would need to use jetified-guava-31.1-android in your gradle to correct it.

https://github.com/firebase/firebase-android-sdk/issues/1320
https://github.com/firebase/firebase-android-sdk/issues/1575
https://stackoverflow.com/questions/56639529/duplicate-class-com-google-common-util-concurrent-listenablefuture-found-in-modu
https://gist.github.com/caseykulm/8f229ef3d89dec02780ea880129bc75d

**Comment by WebBusiness2019** [comment]
Thank you for your response....

But when I remove avpro package then why my project able to create build?
If your package is not using that package can you clear me that....

Is there any other ways to solve this error... With our upgrade or changing
default unity gradle

**Comment by Chris-RH** [comment]
Its because both Exoplayer (in AVPro) and Firebase use guava libraries, so if you remove one of them then there will not be any conflicts and will build properly.

There are solutions listed in those links that I have posted.

**Comment by WebBusiness2019** [comment]
Thank you for your reply sir, I'll check them out.

**Comment by Chris-RH** [comment]
https://github.com/firebase/firebase-android-sdk/issues/1320
https://github.com/firebase/firebase-android-sdk/issues/1575
https://stackoverflow.com/questions/56639529/duplicate-class-com-google-common-util-concurrent-listenablefuture-found-in-modu
https://gist.github.com/caseykulm/8f229ef3d89dec02780ea880129bc75d

but in your case you will need to change it to  jetified-guava-31.1-android

**Comment by LILQK** [comment]
I dont know if this will help but I found a solution for my case:
justo removed the the guava file from the avpro files.
and added this line on the dependencies in the mainTemplate.gradle:
        implementation 'com.google.guava:guava:33.2.0-jre'
I hope this helps

**Comment by Chris-RH** [comment]
It does seem that different methods work for different setups.
