### ISSUE TITLE
AVProVideo v3 Android build in media player video path always returns width and height as 0

### ISSUE THREAD

**Issue by phileday** [RenderHeads/UnityPlugin-AVProVideo#1843]
An issue with the new version 3 is that when switching to the mediaplayer video path when using myMovie.Info.GetVideoWidth() to retrieve the media width or height it always returns 0.

Switching back to the latest AVPro Version 2 and it returns the width and height as normal.

OS - Android (Quest 3)
Unity - 2022.3.27f1
AVPro version - 3
Video spec - N/A issue happens on all videos

**Comment by phileday** [comment]
OpenGL
Media player
Quest 3
Unity 2022-3.19f1 (was previously testing on the latest 2022 but had to revert because of an OpenXR issue)

Sorry I didn't make this clear in my original post. When I said "Media player" I meant the render path.

I'm looking into this myself but I recently hit another issue which causes the app to crash when switching to "Media player" render path so I haven't been able to check if this is still and issue.

I'll look at recreating the issue on a stripped down project and see if I can send you a Unity Project if that would be useful.

**Comment by Ste-RH** [comment]
hehe, no problem.  Yeah, we always refer to it as 'MediaPlayer API Path' for the very reason that the name conflicts with our internal component name!

I have this issue in hand now.  A fix for it will be in the next release (v3.0.3).

**Comment by phileday** [comment]
Thanks, I'll see if I can provide more information on the issue with the crash I'm experiencing when in 'MediaPlayer API Path'.

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.3 has been released.  Please let us know if it has not fixed your issue.
