### ISSUE TITLE
AVPro 3 on Android (Quest 3) falsely returns  true when using myMovie.Control.IsFinished()

### ISSUE THREAD

**Issue by phileday** [RenderHeads/UnityPlugin-AVProVideo#1844]
An issue with the new version 3 is that when trying to see if the media has finished using the myMovie.Control.IsFinished() I am getting a false true statement. This doesn't happen 100 percent of the time but again when switching back to AVPro v2 the issue resolves itself.

Switching back to the latest AVPro Version 2 and it returns the width and height as normal.

OS - Android (Quest 3)
Unity - 2022.3.27f1
AVPro version - 3
Video spec - N/A issue happens on all videos

**Comment by Ste-RH** [comment]
This should be fixed in v3.0.2 (penciled in for release by the end of the week)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.2 has been released.  Please let us know if it has not fixed your issue.

**Comment by phileday** [comment]
I can confirm that it is working correctly on EXO player, thanks for the hard work, however I cannot test this on Media player as switching to Media player causes the app to crash immediately. I've added an issue relating to this.
