### ISSUE TITLE
Question about core edition

### ISSUE THREAD

**Issue by Quan5599** [RenderHeads/UnityPlugin-AVProVideo#1847]
Dear RenderHeads,
I have a project that utilizes HLS streaming for CCTV, and I noticed that your package includes all the features I need. I am planning to purchase your package, but I am still confused about the various editions you offer. I'm not sure which one is right for me, so I would like to know more about the Core edition, Core Desktop Edition, and Ultra Edition. My project platform is Windows and VR. It would be great if you could explain in more detail so I can choose the edition that is best suited for my needs.

Thank you!

**Comment by Chris-RH** [comment]
Please make sure you have used our free, watermarked[ trial version ](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases)to test against your specific use case before purchase.

You need to purchase the version that your end product will be used on.  VR is a bit vague, as that could be Windows, Android or VisionPro?  We have a[ table ](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/download.html#editions)that shows target devices and features of each edition.  Core Desktop is Windows and macOS.  Core Mobile is Android, iOS, and tvOS, Core is for Windows, macOS, Android, iOS, and tvOS.  Ultra is as above, but includes support for visionOS and a lot of additional features.
