### ISSUE TITLE
NSRangeException when opening multiple videos

### ISSUE THREAD

**Issue by adrianplapamaruintenselife** [RenderHeads/UnityPlugin-AVProVideo#1848]
When opening multiple videos using
`mediaPlayer.OpenMedia(new MediaPath(url, MediaPathType.AbsolutePathOrURL), isFirstVideo);`
I have this exceptipm
```
AVPPluginGetCachedMediaStatusForURL
NSRangeException - *** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty array
Fatal Exception: NSRangeException
0  CoreFoundation                 0xec678 (Missing UUID 5a6c1f41bf7032f6a1d65b894dd21362)
1  libobjc.A.dylib                0x2bc80 objc_exception_throw
2  CoreFoundation                 0xf7ae4 (Missing UUID 5a6c1f41bf7032f6a1d65b894dd21362)
3  libswiftCore.dylib             0x134a0 (Missing UUID 496d989cd1d93db8ba7c8f2d16215c1d)
4  UnityFramework                 0x3caab7c AVPPluginGetCachedMediaStatusForURL
5  UnityFramework                 0x3c9383c AVPPluginGetCachedMediaStatusForURL
6  UnityFramework                 0x3c913b1 AVPPluginGetCachedMediaStatusForURL
7  UnityFramework                 0x3cab7dd AVPPluginGetCachedMediaStatusForURL
8  UnityFramework                 0x3cade51 AVPPluginGetCachedMediaStatusForURL
9  UnityFramework                 0x3cc0d01 AVPPluginGetCachedMediaStatusForURL
10 UnityFramework                 0x3cadfc5 AVPPluginGetCachedMediaStatusForURL
11 libswift_Concurrency.dylib     0x49a41 (Missing UUID 51d41f8acf113af689efc1acce7c833b)
```

 - Unity version: 2022.3.19f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  3.0.0 ultra
 - Operating system version: iOS 17.4.1
 - Device model: iPhone14
 - Video specs (resolution, frame-rate, codec, file size): 640x1386 mp4 7mb

**To Reproduce**
1. Open multiple videos (looping is enabled)
2. Playing only one switching between them after 2-4 seconds

**Comment by Chris-RH** [comment]
Are you using Firebase?
How many videos are you playing?
How many videos are playing at any one time?
Are you always going to be playing them in the same order or is it random?
Do you have the same issue when you play longer videos?
How are you switching between videos?

**Comment by adrianplapamaruintenselife** [comment]
Are you using Firebase?
Yes

How many videos are you playing?
About 10

How many videos are playing at any one time?
Only one

Are you always going to be playing them in the same order or is it random?
I have a circular scroll view

Do you have the same issue when you play longer videos?
I don't know.

How are you switching between videos?
I have a circular scroll view. At a time I have 3 open videos and only one playing.

**Comment by Chris-RH** [comment]
Can you see if you can replicate this in a new project using only AVPro Video (no Firebase etc)?

**Comment by adrianplapamaruintenselife** [comment]
I wasn't able to reproduce this issue in a new project (no Firebase).

**Comment by adrianplapamaruintenselife** [comment]
I removed firebase just to test it again and the crash occurs after a longer time than with firebase.

**Comment by Chris-RH** [comment]
Could you retest in a new project, rather than one that has had Firebase in it, please?

**Comment by adrianplapamaruintenselife** [comment]
I made a new project without Firebase and reproduce the issue. The issue occurs without Firebase.

**Comment by adrianplapamaruintenselife** [comment]
Does the last update from asset store fix this issue? I observed there is an update from 10 May. Thanks!

**Comment by Chris-RH** [comment]
Hi, no we would post here to let you know if it was fixed

1. Could you try playing longer videos and see if the issue still occurs?
2. Could you try using the [playlist component](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/component-playlist-media-player.html) to switch between videos?
3. If you are playing the videos in the same order, could you try putting them together in one file?
