### ISSUE TITLE
Can AVProVideo play h264 packets from network?

### ISSUE THREAD

**Issue by lygyue** [RenderHeads/UnityPlugin-AVProVideo#185]
Hi, i try to render a huge scene in my computer, and then capture the screenshot, encode into H264 and send to my Ipad.

Can AVProVideo play these h264 packets from network? I Had test some media player on window10,  which can play on potplayer and some other players. 

But when i save these packets to a file without a container(mp4, avi...), it can't be play in AVProVideo. can somebody help? thanks.

**Comment by AndrewRH** [comment]
As nice as this feature would be to have, it's a ton of work to implement and so not on our roadmap
