### ISSUE TITLE
How can play ffmpeg video packet??

### ISSUE THREAD

**Issue by Dev-MinSeok** [RenderHeads/UnityPlugin-AVProVideo#1851]
Hi. this is ko.

I need to make a video player.
The packet I received is a packet of ffmpeg, but I don't know how to play it using avpro.
I really need your help.

The Unity version used is 22.3.16f1, and the OS uses Windows.

I wish there was an example.

**Comment by Chris-RH** [comment]
we can only play videos from files or streaming URLs.

**Comment by Dev-MinSeok** [comment]
I see. Then, I want to know how to play the RTSP video.
I would like to receive a sample if there was one.
I use Version 2.9.3 - 11 March 2024.
