### ISSUE TITLE
Windows, AVPro 3.0.1 - Loop doesn't work in Media Foundation or DirectShow.

### ISSUE THREAD

**Issue by phileday** [RenderHeads/UnityPlugin-AVProVideo#1852]
Loop doesn't work in Media Foundation or DirectShow. It just holds at the end.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.28f1
 - AVPro 3.0.1
 - Windows 11
 - Video specs - The video, Sample-Local-MP4-RenderHeads.mp4 from your demo

**To Reproduce**
1. Create a new project
2. import AVPro 3.0.1
3. open the demo scene Demo_MediaPlayer
4. hit play on the build and play in the window. The video stops at the end.
5. Change to WinRT.
6. hit play on the build and play in the window. The video loops as expected.

**Videos**
[Loop issue video](https://www.dropbox.com/scl/fi/mnvrt8bueiimn78mc02xl/AVPro-Loop-Not-working.mp4?rlkey=m52jrsbdvggnzefhvi5mrsac4&st=3jillq67&dl=0)

**Comment by Chris-RH** [comment]
We are aware of this issue, thank you :)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.2 has been released.  Please let us know if it has not fixed your issue.
