### ISSUE TITLE
GIF support and question regarding LEADTOOLS

### ISSUE THREAD

**Issue by nickhudson4** [RenderHeads/UnityPlugin-AVProVideo#1853]
Get this warning when trying to load a GIF file.
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/44004215/528961cc-c282-4adf-8163-021fb66c36bf)

2 Questions:
- Will there ever be GIF support?
- Just out of curiosity, does AVPro use a Leadtools backend?

**Comment by Chris-RH** [comment]
Hi Nick, 

We are very unlikely to support GIF
We don't use Leadtools
 :)
