### ISSUE TITLE
WebGL Error

### ISSUE THREAD

**Issue by XiaoMinghui** [RenderHeads/UnityPlugin-AVProVideo#1857]
Describe the issue
Unity2023 webgl play video error. Unity 2021 webgl play video good.

 - Unity version: Unity2023.2.19f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v3.0.1-Trial
 - Operating system version: Win11
 - Device model: RTX4070Ti  i7-14700KF
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. import package
2. change url
3. build webgl
4. error

**Logs**
[localhost-1715668077204.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/15303834/localhost-1715668077204.log)

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/36829808/40a0c851-967a-428d-b8f3-6113a0571653)

**Comment by Chris-RH** [comment]
AVPro Video version 3 does not support WebGL, see [here](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/requirements.html#platforms-not-supported).

**Comment by XiaoMinghui** [comment]
https://github.com/facebook/facebook-sdk-for-unity/issues/671
