### ISSUE TITLE
Issue building for iOS

### ISSUE THREAD

**Issue by ethanPDK** [RenderHeads/UnityPlugin-AVProVideo#1861]
I'm attempting to integrate AVPro Video with Google Cardboard for iOS development. Initially, I managed to successfully build and run an empty project with Cardboard. However, upon adding the AVPro asset to the project, I encountered issues during the Xcode build process. The specific error message I'm seeing is "Unity framework failed, undefined symbols." I'm uncertain if there's a configuration step I might have missed.

**SETUP:*
 - Unity version: 2022.3.20f1 
 - AVPro Video 3.0 Ultra version: 
 - Operating system version: Mac OS Sanoma 14.5 
 - Device model: Mac Mini 2023 M2

**To Reproduce**
1. Empty unity project in 2022.3.20f1
2.  Import and setup cardboard
3. Export and build succesfully in xcode
4. (back to unity) import AVpro ultra version
5. Build xcode project
6. Run xcode project and the error shows up

**Logs**
The only error message I'm seeing is "Unity framework failed, undefined symbols."

**Comment by Chris-RH** [comment]
1. Could you try upgrading to xcode 15.3 please and see if that works?
2. Can you reproduce this in a new Unity project using only AVPro Video?
3. If not, can you include the full error log please

**Comment by ethanPDK** [comment]
Thanks for the fast response.
I updated my mac and xcode and that did fix the problem.

Thank you for the help!
