### ISSUE TITLE
v3.0 Crashes on UWP ARM64 (HoloLens 2) on app start

### ISSUE THREAD

**Issue by WikkidEdd** [RenderHeads/UnityPlugin-AVProVideo#1863]
**Describe the issue**
When using the latest version of AVPro Video on the HoloLens 2 it crashes on startup. Rolling back to v2.9.3 the issue does not occur.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.37 (built with Visual Studio 2022)
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  3.0.1 Core
 - Operating system version: Windows Holographic 22621.1258
 - Device model: HoloLens 2
 - Video specs (resolution, frame-rate, codec, file size): N/A

**To Reproduce**
1. Create a new project
2. Install AVPro Video Core 3.0.1 from the asset store
3. Add the Demo_MediaPlayer scene to the build settings
4. Build for Windows Media Platform
5. Build Visual Studio Project and deploy to device

Observe that the app tile spawns, briefly shows a spinner and then does nothing. If you instead of just running the app you also attach the debugger, you will see the following lines in the log

```
Assertion failed!

Program: ...es\Template3DVS.Release_ARM64.eddsm\AVProVideo.dll
File: d:\work\rh\projects\products\avpro-video...\renderer.cpp
Line: 328

Expression: _renderer
```
Then the debugger pauses with `A breakpoint instruction (__debugbreak() statement or a similar call) was executed in AVPro Video.exe.`

It is possible to press continue in the debugger twice and then the app will run and attempt to play the video at which point the audio plays, but no visuals. This also happens when running a UWP build on a laptop ( #1864 )

**Comment by Chris-RH** [comment]
We no longer [support UWP](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/requirements.html#platforms-not-supported).  There have been quite a few changes to version 3, which is probably why it is no longer working properly.

**Comment by WikkidEdd** [comment]
ok, That is a shame to hear.
