### ISSUE TITLE
v3.0 Media player only plays audio UWP

### ISSUE THREAD

**Issue by WikkidEdd** [RenderHeads/UnityPlugin-AVProVideo#1864]
**Describe the issue**
When using the latest version of AVPro Video in a UWP x64 app only the audio plays. Rolling back to v2.9.3 the issue does not occur.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.37 (built with Visual Studio 2022)
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  3.0.1 Core
 - Operating system version: Windows 11
 - Device model: Laptop, Intel i9, 32gb RAM
 - Video specs (resolution, frame-rate, codec, file size): Sample-Local-MP4-RenderHeads from the asset store package

**To Reproduce**
1. Create a new project
2. Install AVPro Video Core 3.0.1 from the asset store
3. Add the Demo_MediaPlayer scene to the build settings
4. Build for Windows Media Platform
5. Build Visual Studio Project and run on Windows Laptop

Observe that the app starts and runs, but only the audio is played, the visuals do not start and only a loading spinner is shown

**Comment by Chris-RH** [comment]
We no longer [support UWP](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/requirements.html#platforms-not-supported).  There have been quite a few changes to version 3, which is probably why it is no longer working properly.
