### ISSUE TITLE
Ad Support/MediaTailor/Disable Seek

### ISSUE THREAD

**Issue by rogerhinze** [RenderHeads/UnityPlugin-AVProVideo#1865]
Is there a way to flag ad breaks so the viewer can't past the advertisements?

**Comment by Chris-RH** [comment]
Its not something that we support.  You would need to program that yourself.

**Comment by rogerhinze** [comment]
I'm not a programmer myself, but if we could detect the ad breaks is there a way in the AVPro API to turn seeking on and off?

Thank you.

**Comment by Chris-RH** [comment]
We have no in built settings for that, but just disable the UI during ad breaks, then they can't seek.
