### ISSUE TITLE
Cant load 4k videos with AV pro plugin (Paid version)

### ISSUE THREAD

**Issue by mara-a-dev** [RenderHeads/UnityPlugin-AVProVideo#1866]
Problem description:

I have been trying to load (.mp4) videos as they are 4k, but I couldnt, even after updating to the latest May 2024 version.

Device (which devices are you having the issue with - model, OS version number):

Windows 10 Pro

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1 video , 4k , .mp4

System Information:

AVPro Video: v2.9.3 (plugin v2.8.5f1-core)
Target Platform: Standalone
Unity: v2022.3.20f1 WindowsEditor
OS: Desktop - MS-7B61 (Micro-Star International Co., Ltd.) - Windows 10  (10.0.19045) 64bit - English
CPU: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz - 6 threads - 65482KB
GPU: NVIDIA GeForce RTX 3060 - NVIDIA - Direct3D 11.0 [level 11.1] - 12129KB - 16384

**Comment by Chris-RH** [comment]
Hi, 
Can you provide a sample of the video you are trying to play please. unitysupport@renderheads.com

**Comment by mara-a-dev** [comment]
Hi, thank you for responding 
this is the link 
https://www.dropbox.com/scl/fi/5pwr6dsk7n8e4556w3uom/Timelapse_Attract_Loop_4k_050724a.mp4?rlkey=80qixb1q2ypliq62wvdcdpijs&st=elmde7nr&dl=0

**Comment by Chris-RH** [comment]
I downloaded the video and it plays fine.  We don't support [streaming from Dropbox](https://renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#dropbox--google-drive--one-drive-support).
