### ISSUE TITLE
When I try to play a video on Android, the video appears to flash, and it crashes when I try to seek.

### ISSUE THREAD

**Issue by meka6021** [RenderHeads/UnityPlugin-AVProVideo#1868]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: v2019.4.10f1
 - AVPro Video version:v3.0.1 (plugin v3.0.0f1-core)
 - Operating system version: Android10
 - Device model: Redmi 9T(https://www.mi.com/jp/product/redmi-9t/)
 - Video specs (1920*1080, 56.53, codec:mp4, file size:70.69MB): 

Sorry for my poor English.
When I play a video on an Android device, the video screen appears to flash.
When I load a video on an Android device and then try to seek, it crashes.

**Logs**

**Screenshots**

**Videos**

**Comment by meka6021** [comment]
Sorry for the trouble. I found a solution.

**Comment by Chris-RH** [comment]
For reference, can I ask what the solution to your issue was please?

**Comment by meka6021** [comment]
![2024-05-22 164142](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/170389686/7e0a5547-46db-4c51-b1cd-8b2563cc3050)
I changed the "Texture Format" setting of the attached image from "BGRA" to "Y Cb Cr 420_OES".
