### ISSUE TITLE
Video with spatial audio is started only once

### ISSUE THREAD

**Issue by rrenderr** [RenderHeads/UnityPlugin-AVProVideo#1870]
**Describe the issue**
Video with spatial audio is started only once. After the second start of the same video, it doesn't play anymore. Also, I get MediaPlayerEvent.EventType.MetaDataReady event only once, at first start. I started other videos with spatial audio and I don't get MetaDataReady event. If I open a video without spatial audio, everything works fine.

**My Setup:**
 - Unity version:  2022.2.15f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  3.0.1 ultra
 - Operating system version: Android 
 - Device model: Meta Quest 1, 2, 3
 - Video specs (resolution, frame-rate, codec, file size): has spatial audio

**To Reproduce**
1. Start a video with spatial sound - currentPlayer.OpenMedia()
2. Close media player - currentPlayer.CloseMedia()
3. Start the same video again - currentPlayer.OpenMedia()
4. The video doesn't play anymore.

**Logs**
These are logs of events from MediaPlayer
![Screen1](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/18209996/765da0c6-537f-4d08-8cae-1af598d29632)

**Screenshots**
MediaPlayer setup
![Screen2](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/18209996/7f097380-afac-4910-bba8-908e5a023dee)

**Comment by Chris-RH** [comment]
Are you able to provide a sample of the media played? either here or unitysupport@renderheads.com
Can you provide a full logcat of the error occurring please, from when the app is opened.
Have you tried enabling looping?

**Comment by rrenderr** [comment]
Yes, ofcourse.

[logs.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/15391930/logs.txt)
[FB360_CB.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/15391950/FB360_CB.zip)

> Have you tried enabling looping?
It doesn't help.

> Have you tried playing the same video, but with the audio track removed?
It works without spatial audio.

Also, I've tried to destroy the player when closing UnityEngine.Object.Destroy(_myPlayer) and create new one when open another. It works, but there is another problem. After a few closures, my app just freezes.

By the way, I have this problem https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1838

Before we used version of AVP 2.7.3, all these problems weren't presented there.

**Comment by Ste-RH** [comment]
I think this might have been fixed in v3.0.2. I have tried to reproduce this here with the latest version and cannot.

Would it be possible to update, re-test, and feedback @rrenderr ?

**Comment by Chris-RH** [comment]
Any luck @rrenderr ?

**Comment by Ste-RH** [comment]
That was a bug that was fixed in v3.0.2 and I do not get an issue using SeekFast here.

Can we get a logcat for the crash please?

**Comment by rrenderr** [comment]
@Ste-RH 
Here is the log
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/18209996/1c331855-d631-4f3e-83c0-2ec30c73440c)
[FullLog.log](https://github.com/user-attachments/files/15898097/FullLog.log)

**Comment by Ste-RH** [comment]
We need a full logcat please in txt file format.  Screen grabs don't allow us to look deeper

**Comment by Ste-RH** [comment]
That is not a full log.  We need everything from app start (AVPro creation) right through to crash please.

**Comment by Ste-RH** [comment]
This is the same as #1903 .  Please report back in that issue on the SeekFast issue.  We will be closing this issue now as the original problem has been addressed.
