### ISSUE TITLE
Significant drop in FPS with Playback on Vulkan

### ISSUE THREAD

**Issue by cieraej** [RenderHeads/UnityPlugin-AVProVideo#1871]
### Issue
There is a significant loss in frame rate (around 15 frames) when playing a video on the Quest 2 using Vulkan. This issue was not present when using OpenGLES with the same setup.

### Setup (please complete the following information):
**Unity version:** 2022.3.4 (upgrading to 2022.3.11)
**AVPro Video version** (number and edition (trial/core/ultra/enterprise)): 3.0.0, Ultra
**Operating system version**: Android
**Device model:** Quest 2
**Video specs** (resolution, frame-rate, codec, file size): 2500x1248 ll360 H264.mp4

### Other Notes
The issue occurs only with Vulkan.
No significant frame rate issues were experienced with OpenGLES using the same version of Unity and AVPro.

### Before/After Video Playback OVR Metrics Tool (Vulkan) (Drops 15 Frames)
<img width="777" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/6461347/3e88276e-d2ea-48fd-9921-f350cdca5b7e">
<img width="812" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/6461347/21e0d4a9-b072-494e-9b55-463953292cb8">

### Before/After Video Playback OVR Metrics Tool (OPENGLES + OES) (Drops 3 frames)
<img width="711" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/6461347/4094c348-c508-4a86-8290-585f95f2f758">
<img width="791" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/6461347/4b70c889-a2c2-438a-947e-e6a71bb31435">

**Comment by Chris-RH** [comment]
Is this repeatable in a new project running Unity video player?
Is this repeatable in a new project running only AVPro video mediaplayer demo (no other assets, such as XR)?

**Comment by cieraej** [comment]
I can make a test project that is fairly empty, however, i would need an xr package to ensure I can have it run on our target device (Oculus Quest)

**Comment by cieraej** [comment]
So I ran a build and it looked good when I made a test project. The issue seems to be that we have a custom shader that assumes OES for playback. Is there any initiative to get OES playback on Android/Vulkan? That looks like it would solve our FPS drop.

**Comment by Ste-RH** [comment]
OES on Vulkan is a desire to support, but currently it is not being worked on and there is no time-frame for it's potential delivery to AVPro Video

**Comment by Ste-RH** [comment]
Do you see the same issue using one of the supplied sample videos? (BigBuckBunny or the RenderHeads videos)

**Comment by Ste-RH** [comment]
I think this has been addressed in v3.0.2.  Can you update and verify please @cieraej ?

**Comment by Chris-RH** [comment]
Any luck @cieraej ?

**Comment by cieraej** [comment]
I have had really mixed results with stability after the new update! Notably, I had one build that was pretty stable, but I have been unable to replicate that stability since then. The primary issue appears to be related to seeking and toggling between streams and local files. So I have a few questions to investigate this:

- Do you have any recommendations for optimal AVPro settings when using Vulkan?
- Which player (ExoPlayer or MediaPlayer) would you recommend?

For additional context our local files are 2500x1248 resolution and formats tend to be ll360 H264.mp4, and our stream formats are m3u8 and mpds.

Thanks again :)
