### ISSUE TITLE
[Spatial Video] How to play spatial video on Quest3 device using Unity?

### ISSUE THREAD

**Issue by witzkid** [RenderHeads/UnityPlugin-AVProVideo#1872]
I want to play the spatial video taken by iPhone 15 pro with unity App based on Android platform.
When I play spatial video using AVPro, it plays in 2D. How can I play spatial video in 3D?
The test was conducted using spatial video downloaded from the URL below.

https://www.zdnet.com/article/download-my-spatial-videos-from-tech-events-and-view-them-on-quest-3-or-vision-pro/#google_vignette

**Comment by Chris-RH** [comment]
Hi, 

We don't support MV HEVC.
We support left right and top bottom stereo videos
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1715

**Comment by witzkid** [comment]
So what are your plans to support MV-HEVC in the future?
Looking at #1715 provided as a related link, it seems that there is no update yet on the MV-HEVC support plan.

**Comment by Chris-RH** [comment]
Its something that we may add support for in the future.  It depends on if there is much user interest, and if we have the time.  We are a very small team.

**Comment by sergeyv-deovr** [comment]
Any updates here?
