### ISSUE TITLE
Enabling "UseMotionBlur" corrupts exported video when capture mode is Offline Render

### ISSUE THREAD

**Issue by ertan-retinize** [RenderHeads/UnityPlugin-AVProVideo#1873]
Enabling "Use Motion Blur" on CaptureFromCamera component with "Offline Render" mode corrupts the output video file. It exports just fine if I either set motion blur bool to false or set render mode to realtime.. in my case using realtime render is not acceptable so I'd like to proceed with offline render and enable motion blur if possible.

 - Unity version:  2021.3.13
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  4.7.11
 - Operating system version: Windows 10.0.22631 Build 22631
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): any resolution, 60FPS, H264

**To Reproduce**
1. Set the render mode to "offline render"
2. Enable motion blur
3. Capture something for a few seconds via "CaptureFromCamera"
4. Once capture is stopped it'll throw an error into log 

**Logs**

can't find moov or mdat chunks
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing:Process (System.IO.Stream,System.IO.Stream) (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:243)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing:ProcessFile (string,string,RenderHeads.Media.AVProMovieCapture.MP4FileProcessing/Options) (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:218)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing:ProcessFile (string,bool,RenderHeads.Media.AVProMovieCapture.MP4FileProcessing/Options) (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:185)
RenderHeads.Media.AVProMovieCapture.MP4FileProcessing/<>c__DisplayClass32_0:<ProcessFileAsync>b__0 () (at Assets/Plugins/RenderHeads/AVProMovieCapture/Runtime/Scripts/Internal/Mp4FileProcessing.cs:162)
System.Threading.ThreadHelper:ThreadStart ()

**Comment by Chris-RH** [comment]
Hi, you've put this in the wrong place, it should be [here](https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues)
