### ISSUE TITLE
Videos not loading in Windows 11 pro

### ISSUE THREAD

**Issue by Rajeshnalla1996** [RenderHeads/UnityPlugin-AVProVideo#1874]
i made a app for windows, when app opened ,it loads videos from application data path and plays.
in windows 10 it is working fine but in windows 11 it is not showing anything. just blank.

iam using AVPro Video v3 - Core Desktop Edition 3.0.1.

**Comment by Chris-RH** [comment]
Hi, please can you provide more information.

1. Unity version
2. Video specs (resolution, codec, FPS, bitrate etc)
3. Video sample (either here or unitysupport@renderheads.com)
4. Error message when you try to play the video
5. Is this reproducible in a new project, with only AVPro Video, using the mediaplayer demo scene

**Comment by Chris-RH** [comment]
Closed due to lack of reply.
