### ISSUE TITLE
Apple visionOS DeviceSDK Build fails

### ISSUE THREAD

**Issue by PanoCAST** [RenderHeads/UnityPlugin-AVProVideo#1879]
Apple visionOS Device SDK Build fails (see attached screenshot)
Downloaded the unity package and integrated into a spatial demo scene.
Works in editor, does not compile using the DeviceSDK

Setup
 - Unity version: 2022.3.29f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version:  MacOS Sonoma 14.5
 - XCode 15.3
 - Device model: Apple M3 Pro
 - Video specs  HD
 - visionOS 1.2.3
 - Polyspatial visionOS 1.2.3

<img width="1920" alt="Screenshot 2024-06-02 at 9 56 19 AM 2" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/171477567/41a12bbb-5d6e-45a6-be7f-aea51bd10939">

**Comment by Chris-RH** [comment]
We don't yet support Polyspatial as it doesn't support our custom shaders, so we need to rebuild them.

As for your error message; in Unity, you need to go to:
Assets/AVProVideo/Runtime/Plugins/visionOS
select AVProVideo and make sure VisionOS is checked under “Select platforms for Plugin” in the inspector and then click "Apply".
![Screenshot 2024-06-03 at 09 51 41](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/87914758-c36c-426a-a899-75b939aec304)

![Screenshot 2024-06-03 at 09 51 54](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/7a536e9f-0e74-429d-b215-a97808ff20fe)

**Comment by PanoCAST** [comment]
Thank you very much, it indeed solved the problem and following what I found in https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1800 it DOES work on the device
in "bounded" mode.
<img width="1512" alt="Screenshot 2024-06-03 at 4 03 15 PM" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/171477567/5638ce62-929e-45ba-9e98-e19cc77a181b">
