### ISSUE TITLE
Remove Listener

### ISSUE THREAD

**Issue by iiidefektiii** [RenderHeads/UnityPlugin-AVProVideo#188]
Maybe I don't understand this completely and looking for clarity, but if I add an event listener to a video for an on on finished event and I decide to switch video's does that event listener reset when the new video is loaded or is there a way I need to remove the event listener on the previous video?

**Comment by AndrewRH** [comment]
The event listener is for the MediaPlayer component, not for an individual video.  So when you use the same MediaPlayer to play multiple videos, then when one video closes you'll still be subscribed to the event of that MediaPlayer.  I hope that helps to explain it.  I will close this issue now :)

**Comment by iiidefektiii** [comment]
AndrewRH That makes sense but if I'm playing multiple videos through 1 media player and I want 1 video to do an oncomplete event and a different video not to have an oncomplete event how is it possible to remove the oncomplete event? I feel like there should be some sort of removelistener to do so. I'm creating a sort of media server specific to playing different videos that all either have an oncomplete or don't. I'm already using a few media players and using even more becomes messy when all I want to do is remove the listener.

**Comment by AndrewRH** [comment]
Just like you call AddListener, you can call RemoveListener() or even RemoveAllListeners();

I hope that helps?

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.
