### ISSUE TITLE
[iOS] Crash when starting playback on devices running iOS 14

### ISSUE THREAD

**Issue by buoutuanzi** [RenderHeads/UnityPlugin-AVProVideo#1880]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
play video on ios crash， debug on xcode know that trigger EXC_BAD_ACCESS

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.28f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.1
 - Operating system version: ios 14.0.1
 - Device model: iphone 11 pro max
 - Video specs (resolution, frame-rate, codec, file size):  1080p

**To Reproduce**
just add a mediaPlayer and a displayUGUI to play a video

**Logs**
can see the avproVideo started event

**Screenshots**
![1717415161339](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/96377696/9a5a637b-5a5e-4fc2-a64a-992de1224812)

**Comment by Chris-RH** [comment]
EXC_BAD_ACCESS is caused because you are trying to access an object that has already been released from memory.

Which version of xcode are you using?
Is it reproducible in a new project, only running the AVPro Video mediaplayer demo scene?

**Comment by buoutuanzi** [comment]
15.3

**Comment by buoutuanzi** [comment]
> EXC_BAD_ACCESS is caused because you are trying to access an object that has already been released from memory.
> 
> Which version of xcode are you using? Is it reproducible in a new project, only running the AVPro Video mediaplayer demo scene?

15.3

**Comment by buoutuanzi** [comment]
> EXC_BAD_ACCESS is caused because you are trying to access an object that has already been released from memory.
> 
> Which version of xcode are you using? Is it reproducible in a new project, only running the AVPro Video mediaplayer demo scene?

yes, it's a new 2dURP project only import AVPro

**Comment by Chris-RH** [comment]
Have you got any further error messages (if so, please copy and paste rather than screenshot)?
Have you been able to test on any other iOS devices?

**Comment by buoutuanzi** [comment]
> Have you got any further error messages (if so, please copy and paste rather than screenshot)? Have you been able to test on any other iOS devices?

no, it just crash, so there is no more log

**Comment by buoutuanzi** [comment]
> Have you got any further error messages (if so, please copy and paste rather than screenshot)? Have you been able to test on any other iOS devices?

the started event is trigger, and crash

**Comment by buoutuanzi** [comment]
> Have you got any further error messages (if so, please copy and paste rather than screenshot)? Have you been able to test on any other iOS devices?

I tested this issue on an iPhone 14 Pro running iOS 16.2.1, and the video plays normally.

**Comment by Chris-RH** [comment]
When using your iphone 11 pro max.  Do you get the same result when building a new project in 3d built-in renderer?

**Comment by MorrisRH** [comment]
Fixed. This will make it into version 3.0.2

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.2 has been released.  Please let us know if it has not fixed your issue.

**Comment by efeurun** [comment]
We've recently upgraded from Version 2 to 3.0.2 and started encountering this error.

Our crashes on iOS skyrocketed because of this... Looking forward for the fix.
