### ISSUE TITLE
[Android] Playing Video From Offset Doesn't Work

### ISSUE THREAD

**Issue by HZekriDEV** [RenderHeads/UnityPlugin-AVProVideo#1881]
**Description**
When trying to use the "mediaPlayer.PlatformOptionsAndroid.fileOffset" functionality, the player simply plays from the beginning of the video rather than from the offset. This happens despite replicating the instructions given in this page:

https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-core.html

**Setup**
 - Unity version: 2021.3.33f1
 - AVPro Video version 2.0 trial version: 
 - Operating system version: Android 10.0
 - Device model: Oculus Quest 2 & 3
 - Video specs (resolution, frame-rate, codec, file size): 360 Stereo (H.265 at 5760 X 5760)

**Comment by Chris-RH** [comment]
Hi, 

Have you put your video within a dummy video and its playing the dummy video instead?
Or are you expecting file offset to start your video at a later point?

**Comment by HZekriDEV** [comment]
Thanks for your response! 

I'm using a dummy video that is appended at the beginning of the real video. When I play the video, the dummy video is the only thing that plays.

**Comment by Chris-RH** [comment]
Are you setting the offset by scripting or in the mediaplayer component?

**Comment by HZekriDEV** [comment]
I tried both ways.

**Comment by HZekriDEV** [comment]
Here is the code that I am using to play the video. It could be that I made a mistake in reading the instructions.

using UnityEngine;
using RenderHeads.Media.AVProVideo;
using System.IO;

public class Play360Video : MonoBehaviour
{
    public MediaPlayer mediaPlayer;
    public string videoFileName = "Video.mp4";
    private string videoPath;

    void Start()
    {
        if(Application.platform == RuntimePlatform.Android)
            videoPath = System.IO.Path.Combine(Application.persistentDataPath, videoFileName);
        else
            videoPath = System.IO.Path.Combine(Application.dataPath, videoFileName);

        //Setup
        MediaHints hints = mediaPlayer.FallbackMediaHints;
        hints.stereoPacking = StereoPacking.TopBottom;
        mediaPlayer.FallbackMediaHints = hints;
        
        //Offset
        mediaPlayer.PlatformOptionsAndroid.fileOffset = 319044;

        // Load the video
        mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, videoPath, autoPlay: true);
        
    }

**Comment by Ste-RH** [comment]
This should be fixed in v3.0.2 (penciled in for release by the end of the week)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.2 has been released.  Please let us know if it has not fixed your issue.

**Comment by Ste-RH** [comment]
A new fix for this will be in the next release (v3.0.3).

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.3 has been released.  Please let us know if it has not fixed your issue.
