### ISSUE TITLE
[Android] Can not open video on Oppo

### ISSUE THREAD

**Issue by HaSyHieu** [RenderHeads/UnityPlugin-AVProVideo#1882]
**Describe the issue**
Can not play video (Using avpro video in android)

**Your Setup (please complete the following information):**
 - Unity version: 2022.1.20f1
 - AVPro Video version : Trial 3.0.1 (newest)
 - Operating system version: Android 10 
 - Device model: OPPO A15
 - Video specs (resolution, frame-rate, codec, file size):
 + Resolution : 576 * 1024
 + Frame rate : 24 frame / second
 + Codec ID : isom (isom/iso2/avc1/mp41)
 + file size : 1.97MB
 + bit rate : 311 kbps
 + Channels : 2 (stereo)
 + Audio Sample Rate : 48.000 khz

**To Reproduce**
1. Import AVPro Trail Version (Version 3.0.1)
2. Using Media Source : Path (Relative to Persistent Data Folder), Using Default Settings (When drag to scene)
3. Put the video to the persistent data folder
4. Play on editor (Fine)
5. Build on devices (Oppo A15)
6. Put the video to persistent data path on the device (com.oke.hieuhs)
7. Open The App
8. Video not show on the screen

**Logs**
Playback error : androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
AVProVideo error Unexpected runtime error 
Logs File From Android Studio : 
[log.txt](https://github.com/user-attachments/files/15541730/log.txt)

**Comment by Chris-RH** [comment]
Did you remember to set the permissions to access this folder which is in Player Settings > Android > Write Permission > External (SDCard) ?
Can this be reproduced using a new project and running the AVPro Video mediaplayer demo scene?

**Comment by HaSyHieu** [comment]
I use the demo scene of avpro, i already have permission and that apk runs well on some devices, except that device. Yes it can be reproduced

**Comment by HaSyHieu** [comment]
I can attach that project to you through mail. Can you check it ?

**Comment by Chris-RH** [comment]
Have you tested using both Vulkan and OpenGLES?

**Comment by HaSyHieu** [comment]
I use only opengles 3.0, not vulkan. It's our settings

**Comment by HaSyHieu** [comment]
Using vulkan will make some of our .mp4 video, in some device, can not be played (Using Unity Video Player)

**Comment by Chris-RH** [comment]
So you are saying that the videos will not run on the device using Unity Videoplayer?
Does the video run using the device's native videoplayer?

**Comment by HaSyHieu** [comment]
the video it self can run on the native video player. We remove vulkan to reduce crash, anr and that problem (video can not play on devices)

**Comment by HaSyHieu** [comment]
[update] : I have tried version 3.0.1, using both vulkan and opengles3. It dont work on that mode;

**Comment by Chris-RH** [comment]
So this worked on the same device using AVPro Video version 2.9.3?

**Comment by HaSyHieu** [comment]
I can provide you my project through mail.

**Comment by HaSyHieu** [comment]
Yes, i tried different ways to do it, but it seem not working. I also try with unity default settings, no multithreaded rendering, have multi thread rendering, open gles 3 + vulkan, only open gles 3. We need a version that can play from local path, not streaming.

**Comment by Chris-RH** [comment]
A project would be helpful thanks. unitysupport@renderheads.com
What devices have you tested it on? Is this the only one it doesn't work on?

**Comment by HaSyHieu** [comment]
I test on Oppo A15, Realme 3, Huawei Y9s

**Comment by Chris-RH** [comment]
Can you provide a full, unedited logcat please

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.3 has been released.  Please let us know if it has not fixed your issue.
