### ISSUE TITLE
[Windows] HAP File in MOV container locked after playback

### ISSUE THREAD

**Issue by dgacke** [RenderHeads/UnityPlugin-AVProVideo#1883]
HAP video files in .mov container remain locked on disk after playback, in both the Unity IDE and with a release build.
Additionally, the files remain locked after stopping playback in the Unity editor. To unlock, you must close the editor.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.22f1
 - AVPro Video version 2.9.3 Ultra
 - Operating system version: Windows 10 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Press play button in Unity IDE
2. Play HAP codec .mov file.
3. Press Stop in IDE. 
4. Try to delete the file from disk. It will fail. Windows reports the file as locked by the Unity IDE
5. Works the same with a release mode application. After file has played, it will remain locked until the application is closed.

**Comment by Chris-RH** [comment]
I'm going to close this now as it seems to be fixed in version 3 and we aren't doing any updates to version 2.  I would suggest either upgrading to version 3, or using the DirectShow API to play you HAP files in version 2.
