### ISSUE TITLE
[macOS] AVPro 3.0.1 does not load Language information for TextTracks

### ISSUE THREAD

**Issue by krahen94** [RenderHeads/UnityPlugin-AVProVideo#1884]
**Describe the issue**
After loading the text tracks, observe that the embedded text tracks in a video have null 'Language' entries.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.1
 - Operating system version: MacOS Sonoma
 - Device model: M1 Max
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Load a video with embedded text tracks
2. Query the text tracks
3. Observe that the native objects do not fill the Language fill anymore opposed to 2.x

**Comment by MorrisRH** [comment]
What kind of video are you trying to play? (HLS, local mp4, remote mp4)
Can you provide a sample video and what you would expect to see for the language track names?

**Comment by MorrisRH** [comment]
This should be fixed in the next release (version 3.0.2)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.2 has been released.  Please let us know if it has not fixed your issue.
