### ISSUE TITLE
Can Plugin Support   HarmonyOS?

### ISSUE THREAD

**Issue by XuDaFei** [RenderHeads/UnityPlugin-AVProVideo#1886]
I bought AVProVideo and AVMoive Caputre UnityPlugin，It work well on Android and IOS .
But we recently need to support a new operating system，HarmonyOS（This is a special operating system that runs on Huawei phones in China）
Is it possible to provide plug-in support for HarmonyOS?
Here is Unity Support for HarmonyOS 
https://unity.cn/tuanjie/releases
Here is official documents
https://developer.huawei.com/consumer/en/doc/harmonyos-guides-V2/start-overview-0000001478061421-V2

**Comment by XuDaFei** [comment]
Ok, Thanks Reply

**Comment by yanglei** [comment]
> Hi,
> 
> We don't plan on supporting HarmonyOS. As far as I'm aware, its only supported by Unity China, which we don't have access to, and not on any devices that we can use for testing in Europe.

One more comments here: 
HarmonyOS has been announced publicly on Huawei HDC 2024 event in June. 
So far, there are some SDK has been adapted to run on HarmonyOS, refer to: https://fmod.com/docs/2.02/api/platforms-openharmony.html.  
If you want to adapt the OS and need any supports (e.g. OS, device), our team can help on.
