### ISSUE TITLE
What's mean High quality in shaders?

### ISSUE THREAD

**Issue by Anton111111** [RenderHeads/UnityPlugin-AVProVideo#1888]
What's mean High quality in shaders? What does this parameter affect and when should it be turned on and when off?

**Comment by MorrisRH** [comment]
I assume you're referring to the HIGH_QUALITY define in the AVProVideo-VR-InsideSphere... set of shaders.
When enabled a more precise calculation is performed to work out the texture coordinate for the fragment being rendered. This improves the quality of the output at the cost of being a much more expensive calculation than using the standard interpolators for generating the texture coordinate.

**Comment by Anton111111** [comment]
Thanks
