### ISSUE TITLE
macOS Playback broken with Trial version

### ISSUE THREAD

**Issue by BergerBytes** [RenderHeads/UnityPlugin-AVProVideo#189]
**Describe the bug**
Currently evaluating AVPro using the trial version, and the playback on macOS, both in editor and a build, seems to be broken. The video will skip around wildly and the watermark continuously stacks. There is a video attached showcasing this behavior. I made an iOS build and the video playback there seems to work as intended.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.10, 2019.2.7, 2019.2.8, 2019.3.0b6
 - AVPro Video version: The trial version
 - Operating system version: macOS 10.14.6
 - Device model: MacBook Pro (15-inch, 2018)
 - Video specs (resolution, frame-rate, codec, file size): Happens on all videos, including the sample videos provided in the trial package.

**To Reproduce**
1. Create a new Unity Project.
2. Import the trial package.
3. Open any demo scene and play the video.

**Videos**
https://youtu.be/Tb-nETDMybM

**Comment by AndrewRH** [comment]
Hi,

This is a known issue with the trial version and certain macOS machines.  It only happens on certain machines (mostly MBP's with dual GPUs) and only with the trial version and when using the Metal graphics API.

You can get around it by: 
1) Switching to the full version
2) Switching the graphics API from Metal to OpenGL (in Player Settings)

I hope this helps :)

**Comment by BergerBytes** [comment]
Thank you @AndrewRH ! I figured it could just be a trial package issue, wanted to make sure before purchasing.
