### ISSUE TITLE
AV pro - Preferred maximum bitrate

### ISSUE THREAD

**Issue by AmalBabuM** [RenderHeads/UnityPlugin-AVProVideo#1891]
// Set the maximum adaptive resolution to 1080p - ExoPlayer only
mediaPlayer.PlatformOptionsAndroid.videoApi = Android.VideoApi.ExoPlayer;
mediaPlayer.PlatformOptionsAndroid.preferredMaximumResolution = OptionsAndroid.Resolution._1080p;

when i change the resolution while on run time in my android device its not getting triggered in the below event

void HandleEvent(MediaPlayer mp, MediaPlayerEvent.EventType eventType, ErrorCode code)
{
if (eventType == MediaPlayerEvent.EventType.ResolutionChanged)
{
IsVideoReady.text = "Resolution Changed";
Debug.LogError("Resolution Changed");
}
}

**Comment by Chris-RH** [comment]
// Set the peak adaptive bitrate to 4Mbps - ExoPlayer only
mediaPlayer.PlatformOptionsAndroid.videoApi = Android.VideoApi.ExoPlayer;
mediaPlayer.PlatformOptionsAndroid.preferredPeakBitRate = 4.0f;
mediaPlayer.PlatformOptionsAndroid.preferredPeakBitRateUnits = OptionsAndroid.BitRateUnits.Mbps;
