### ISSUE TITLE
A Avpro Ultra user, I have a few questions on the product 

### ISSUE THREAD

**Issue by SplunkyDev** [RenderHeads/UnityPlugin-AVProVideo#1894]
Hello,
I am using the version 2.9.3 of AVpro. I believe it is the ultra edition bought by the company using this email id: software@optimumcompanies.eu

I have few questions

1: Is the upgrade to version 3 free for version 2 customers if so how do we upgrade since the update plugin only upgraded us to 2.9.3

2: Is there a feature to trim or only play part of the loaded video in AVpro ? What I mean is if I have a 5 second video I would like to just player the video from time 2s to 4s rather than the whole 5 seconds video. Is this possible without using the seek API rather something like trimming the video

3: I have implemented video stepping(seek next frame) using the API SeekToFrameRelative() but I notice there seems to be a delay from the StartedSeeking event type being called and FinishedSeeking event being called. How can I improve that, not sure what is causing the delay.

**Comment by SplunkyDev** [comment]
Hello team,

It would be great if anyone could help me out here. 
Thank you in advance, and I appreciate the time taken to help.

**Comment by Chris-RH** [comment]
Hi @SplunkyDev, 
Apologies for the delay in response.

There is a [discounted upgrade path](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/download.html#upgrade-pricing) between AVPro Video versions 2 and 3.  It is automatically applied in the Unity Asset Store. 
There isn't a trimming feature.  Is there a reason that you don't trim the videos to the required length beforehand?
What sort of media are you using and on what platform?
Have you encoded for fast seeking?
How long is the delay?

**Comment by SplunkyDev** [comment]
> Hi @SplunkyDev, Apologies for the delay in response.
> 
> There is a [discounted upgrade path](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/download.html#upgrade-pricing) between AVPro Video versions 2 and 3. It is automatically applied in the Unity Asset Store. There isn't a trimming feature. Is there a reason that you don't trim the videos to the required length beforehand? What sort of media are you using and on what platform? Have you encoded for fast seeking? How long is the delay?



"There isn't a trimming feature. Is there a reason that you don't trim the videos to the required length beforehand?"
My apologies, I cannot disclose the specifics but on high level our backend record certain action  the video contains certain noise in the beginning and the end. We require the middle part which is the actual cream of the video ;-P. We were just curious if we could trim it if the BE could let us know how much of noise are they sending pre and post the primary video. 
Thanks for clarifying that though. 

"What sort of media are you using and on what platform?"
Mp4 on android devices 

"Have you encoded for fast seeking?"
H264-MPEG-4 AVC. I am not fully aware of how or if that done. May need to check with the backend team. Any resources/references  that you could share would help a lot. 

"How long is the delay?"
0.75s to 1s, and these are just 1 to 5 frames  SeekToFrameRelative() operations

**Comment by Chris-RH** [comment]
More info on fast seeking [here](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/feature-seeking-playbackrate.html#optimal-encoding).
