### ISSUE TITLE
[Bug] Demo scenes don't work in Unity6 and D3D12 - use D3D11 instead

### ISSUE THREAD

**Issue by agalloch21** [RenderHeads/UnityPlugin-AVProVideo#1896]
**Describe the issue**
When running demo scenes in Unity6, there are no textures being shown but there are sounds. 
The log says:
1) d3d12 error: Creating a default shader resource view with non compatible format (dxgi-fmt=87 for a resource that uses dxgi-fmt=91)
2) d3d12: Attempting to bind a NULL or empty texture.  Perhaps the texture contains no image data or has an invalid size.

Demo scenes work fine in Unity2023.2.20

**Your Setup (please complete the following information):**
 - Unity version: Unity6000.0.5f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.1
 - Operating system version: windows11
 - Video specs (resolution, frame-rate, codec, file size): Sample video

**To Reproduce**
Just import package and run the demo scene in Unity6

**Workarounds**
Reordering "Graphics APIs for Windows" in Player Settings to make sure D3D11 is above of D3D12 can temporarily solve the issue. Is there a way that I can specify which API to use in AVPro settings?

**Comment by Chris-RH** [comment]
Unity 6 is still in preview.  It could be a small temporary bug on their part, or an overhaul of the way they handle things.  We'll keep an eye on it, thanks.
Just stick to changing it in Player Settings :)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.8 has been released.  Please can you let us know if it has not fixed your issue.

**Comment by agalloch21** [comment]
Yes, version 3.0.8 works now under the same environment described at the top. 
Thank you for your support!

**Comment by Ste-RH** [comment]
Thanks for letting us know so quickly @agalloch21.  We are very happy the fix worked for you.  If you have a few free minutes, might we respectfully ask if you could leave a review of AVPro Video on the Unity asset store.  Every honest review helps us advance the product with more features and allow us to offer better support.
