### ISSUE TITLE
I buy Core Moblie Version and import from package but still import a trial version

### ISSUE THREAD

**Issue by AcornDenStudio** [RenderHeads/UnityPlugin-AVProVideo#1897]
Problem description:

As title, I buy Core Moblie Version 
and import from package but still import a trial version.
How should I do?
I am check the platform I run is Android. My Unity version is 2022.3.16f1.
And updated to the latest version yet. (v3.0.3)

And I buy this plugin for the VR360 on Meta Quest 2, 
I want to know how to use OES Path to make it work easier.
If you have any imformation of this I will really appreciate it.
Thanks!
Good Luck!

Device (which devices are you having the issue with - model, OS version number):

Android, need to run on Meta Quest 2

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

VR360, 3840 X 3840

System Information:

AVPro Video: v3.0.3 (plugin v3.0.0f1-trial)
Target Platform: Android
Unity: v2022.3.16f1 WindowsEditor
OS: Desktop - GP65 Leopard 9SD (Micro-Star International Co., Ltd.) - Windows 10  (10.0.19045) 64bit - ChineseTraditional
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz - 12 threads - 16228KB
GPU: NVIDIA GeForce GTX 1660 Ti - NVIDIA - Direct3D 11.0 [level 11.1] - 5979KB - 16384

**Comment by Ste-RH** [comment]
What evidence are you seeing that makes you think that it is still the trial version?

Core Mobile will give you watermark free when running on Android and Apple devices only. Not in the editor.

**Comment by AcornDenStudio** [comment]
> What evidence are you seeing that makes you think that it is still the trial version?
> 
> Core Mobile will give you watermark free when running on Android and Apple devices only. Not in the editor.

Thank you for your prompt response!

I have created a new test project and imported AVProVideo in the Package Manager. 
<img width="960" alt="222" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/172505661/62cd45ca-3a6b-4343-b566-a11c146b70c8">

However, in the Inspector, it still shows that this is the Trial Version. 
<img width="967" alt="111" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/172505661/72f63a30-15b5-401a-b987-8004f3e8c460">

I would like to use the OES Path as guided in the documentation, but I don't see this option. 
According to the documentation, it should be available under the Android settings.
<img width="236" alt="333" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/172505661/d60f74eb-7911-4d04-b55d-cd556e966953">

**Comment by Ste-RH** [comment]
Yes. You are seeing this because the editor is still under a trial (watermarked) license because you only purchased the mobile version. The desktop version encompasses the editors on windows and macOS as there is no way to differentiate editor from stand alone.

Your builds to Android device(s) should be watermark free and you will be able to use OED.

**Comment by AcornDenStudio** [comment]
Okay, I understand the situation. 
However, I need to edit my project in the Unity Editor. 
I saw the option and description about the OES Path in the documentation you provided, and I need to use it. 
If I can't see this option in the Unity Editor, how should I proceed to use it?
<img width="837" alt="555" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/172505661/3ee0dc4c-f80f-4299-b41f-edc7d0925362">

Thank you for your assistance.

p.s. Material is set to the shader needed already.
<img width="519" alt="666" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/172505661/c27c33f7-73b6-4e88-a0ef-e59e76b19005">

**Comment by AcornDenStudio** [comment]
Excuse me?
Any further idea?

**Comment by Chris-RH** [comment]
Hi @AcornDenStudio 

Apologies, the documentation is still in the process of being updated.
In the Mediaplayer component, In the Android settings:
Change Texture Format from BGRA to Y Cb Cr 420_OES
![Untitled](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/102963025/eaa8905b-1233-479f-92c4-f1d1ca5ebd3b)
