### ISSUE TITLE
App doesn't launch when build includes AVPro

### ISSUE THREAD

**Issue by HZekriDEV** [RenderHeads/UnityPlugin-AVProVideo#1898]
**Issue**
In my project, I've been having an issue where launching it after building leads to an immediate crash. After investigating, this only happens after importing the AVPro package. This only happens after building to the quest., everything in the editor works fine. 

**Setup**
 - Unity version: 2021.3.33f1
 - AVPro Video version: AVProVideo-v3.0.3-Trial
 - Operating system version: Most recent version of Android for Quest
 - Device model: Oculus Quest 2 & 3

**Logs**
[logcat.log](https://github.com/user-attachments/files/15854972/logcat.log)

**Comment by MorrisRH** [comment]
We've been unable to reproduce this here on our Quest 2, if you could provide the following that may help us to track down the issue:
- Are you using any other plugins within your project?
- What are the player settings for your project?

**Comment by HZekriDEV** [comment]
I've been trying to reproduce the issue in a separate unity project, and It seems to occur after enabling "Low Overhead Mode (GLES)" in the Oculus settings within XR Plug-in Management. For now, I can disable it in my project, and the build works.

![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/62521050/1df4c476-ab74-4fca-b20b-98ee4dbc0794)

**Comment by MorrisRH** [comment]
Reproduced here by enabling `Low Overhead Mode (GLES)`

**Comment by MorrisRH** [comment]
This issue has been fixed and will make it into the next release (version 3.0.4).
