### ISSUE TITLE
[iOS] Application crashes immediately after launching

### ISSUE THREAD

**Issue by yaozb-gif** [RenderHeads/UnityPlugin-AVProVideo#1899]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Hello,

We are encountering an issue where our application crashes immediately after launching when using the AV PRO plugin. We hope you can help us resolve this issue.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.6f1c1 
 - Xcode version: 15.4
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v3 - Ultra Edition 3.0.1 
 - Operating system version: IOS15.3.1
 - Device model: ipad9
 - Video specs (resolution, frame-rate, codec, file size): *.mp4

**To Reproduce**
1. After publishing with Xcode, the app crashes immediately upon running
2. 
3. 

**Logs**
.framework/UnityFramework, 0x0109): Symbol not found: _$s7Network10NWEndpointO4PortVMn
  Referenced from: /private/var/containers/Bundle/Application/D8A9106F-D6D8-43D4-B5FC-62389A3EEF74/VeryFun.app/Frameworks/UnityFramework.framework/UnityFramework
  Expected in: /System/Library/Frameworks/Network.framework/Network

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
The latest version of AVPro Video is v3.0.3.  Please update to this and report back if you still see/don't-see the issue.

**Comment by MorrisRH** [comment]
The missing symbol you reference is not related to AVPtoVideo. From the looks of it the Unity framework itself is not compiled against the latest SDK. I would recommend that you update your Unity version to the latest LTS version (Unity 2021.3.39f1).

**Comment by Chris-RH** [comment]
Closed due to lack of reply
