### ISSUE TITLE
simple json not working on android

### ISSUE THREAD

**Issue by syedali1621** [RenderHeads/UnityPlugin-AVProVideo#190]
i am fetching text from url using simple json unity it is working fine in unity and iphone but not showing json text in android anyone faced similar issue please let me know if you have any solution.?

**Comment by AndrewRH** [comment]
Umm - how is this related to AVPro Video? :)

**Comment by syedali1621** [comment]
yes i know it is not related but i am using avpro and fetching json from url in same project and this repo people are active that is why i asked here if you have any solution do let me know kindly..

**Comment by MorrisRH** [comment]
Closing as not related to AVPro Video.
