### ISSUE TITLE
[Android] Exo Player Crashes on Quest

### ISSUE THREAD

**Issue by cieraej** [RenderHeads/UnityPlugin-AVProVideo#1900]
Hi,

I am having Exoplayer crash when playing media on Vulkan, specifically when playing a stream. I've included the logs and a screenshot of my AV Pro Gameobject. When it is in Media Player rather than Exo, we do not experience crashing, but lesser performance

**My Setup (please complete the following information):**

- Unity version: 2022.3.4
- AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.3
- Operating system version: Android + Vulkan
- Device model: Quest 2
- Video specs (resolution, frame-rate, codec, file size): 2500x1248 ll360 H264.mp4

<img width="349" alt="image" src="https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/6461347/89de44ba-8971-43df-bb96-360376380230">

[odh_logs_2024-06-18 14.09.07.575.txt](https://github.com/user-attachments/files/15887851/odh_logs_2024-06-18.14.09.07.575.txt)

**Comment by Ste-RH** [comment]
Can you make this happen using one of our Demo scenes?

Under what behavior/circumstances does this happen?  Log suggests some rapid fire seek after a seek has been called and not completed yet?

**Comment by MorrisRH** [comment]
A fix for this will be in the next release (version 3.0.4)

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.4 has been released. Please let us know if it has not fixed your issue.

**Comment by cieraej** [comment]
Great! I will update this and get back to you before I close this! Thank you :)

**Comment by Chris-RH** [comment]
I'm closing this for now.  please reopen it if you are still having issues
