### ISSUE TITLE
[Question] Main thread blocked by synchronous property query on not-yet-loaded property

### ISSUE THREAD

**Issue by tomkail** [RenderHeads/UnityPlugin-AVProVideo#1901]
When loading video on iOS I see the following error message in XCode
`Main thread blocked by synchronous property query on not-yet-loaded property (assetProperty_CompatibleWithAirPlayVideo) for HTTP(S) asset. This could have been a problem if this asset were being read from a slow network.`
I don't know what this means, or even if it's a problem, but I'd like to understand it!
Ta!

**Comment by MorrisRH** [comment]
Well it's not ideal ;)

Basically one of the properties on the asset I'm querying hasn't been loaded yet and I'm holding up the main thread until it has.

What version of AVPro Video are you seeing this in and what version of iOS are you running? Let me know and I'll see about getting it fixed.

**Comment by MorrisRH** [comment]
Well I've added a potential fix for this. AFAICT this will only affect versions of iOS older than 15 as we use the new async APIs for 15 and later.

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.4 has been released.  Please let us know if it has not fixed your issue.

**Comment by tomkail** [comment]
Thank you! I am on iOS 15 already but I'll let you know if it crops up again.

**Comment by tomkail** [comment]
Oh! I don't seem to have access to V3? We bought V2 full price not even 18 months ago! Are we expected to buy V3 again?

**Comment by Chris-RH** [comment]
Hi Tom, 
I'm afraid that fixes only apply to AVPro Video version 3 as version 2 was depreciated.  There is a [discounted upgrade path](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/download.html#upgrade-pricing) for owners of AVPro Video version 2.  You can also test the[ trial version here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases).

**Comment by tomkail** [comment]
Ooof. I understand, and we like your software a lot, but it doesn't endear us to your company very much.

**Comment by Chris-RH** [comment]
I'm sorry to hear that.  We do try to make it clear in our[ documentation](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/download.html#future-updates).
