### ISSUE TITLE
Android : OpenMedia(MediaPathType.AbsolutePathOrURL, path, true)   need twice, first return false,second return true and begin play.

### ISSUE THREAD

**Issue by Aunter1992** [RenderHeads/UnityPlugin-AVProVideo#1904]
need twice, first return false,second return true and begin play.

**Comment by Aunter1992** [comment]
exoplayer

**Comment by Aunter1992** [comment]
3.0.3

**Comment by Aunter1992** [comment]
false
 [AVProVideo] Opening /storage/emulated/0/Android/data/com.DefaultCompany.AVProTest/files/TestA.mp4 (offset 0) with API ExoPlayer
                                                                                                    RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
                                                                                                    LoadMedia:LoadAFile()
                                                                                                    UnityEngine.Events.UnityEvent:Invoke()
                                                                                                    UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:Process()
2024-06-19 18:25:19.705 15220-15275 Unity                   com.DefaultCompany.AVProTest         E  [AVProVideo] Failed to open /storage/emulated/0/Android/data/com.DefaultCompany.AVProTest/files/TestA.mp4
                                                                                                    RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
                                                                                                    LoadMedia:LoadAFile()
                                                                                                    UnityEngine.Events.UnityEvent:Invoke()
                                                                                                    UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:Process()
2024-06-19 18:25:19.706 15220-15275 Unity                   com.DefaultCompany.AVProTest         I  umplayer loadafile = False
                                                                                                    LoadMedia:LoadAFile()
                                                                                                    UnityEngine.Events.UnityEvent:Invoke()
                                                                                                    UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
                                                                                                    UnityEngine.EventSystems.StandaloneInputModule:Process()

**Comment by Aunter1992** [comment]
first
![1718793041336](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/13fbb569-a9b9-4ea9-9e1c-1b3a304b3747)

**Comment by Aunter1992** [comment]
second
![Uploading 1718793100408.jpg…]()

**Comment by Aunter1992** [comment]
second
![1718793100408](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/21072395/5e52b1c5-a9a8-4a7b-837d-199a6e45524d)

**Comment by Chris-RH** [comment]
Hi @Aunter1992 , 

Please can you provide some more details.

1. Unity version: 
2. AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
3. Operating system version: 
4. Device model: 
5. Video specs (resolution, frame-rate, codec, file size): 
6. Reproducible in a new project using only AVPro Video?
7. Vulkan or OpenGLES?
8. Does it work in Android Mediaplayer API instead of Exoplayer?
9. Full logcat in txt form.

**Comment by Aunter1992** [comment]
I found the issue: it was caused by calling ForceDispose  before OpenMedia
[logAvpro.txt](https://github.com/user-attachments/files/15900277/logAvpro.txt)
