### ISSUE TITLE
Playback very unsmooth after finishedbuffering or finishedseeking in all devices#V3.0.3 

### ISSUE THREAD

**Issue by DreamYao** [RenderHeads/UnityPlugin-AVProVideo#1907]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
playback very unsmooth after finishedbuffering or finishedseeking in all devices#V3.0.3 

**Your Setup (please complete the following information):**
 - Unity version: 2023.3.21f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): V3.0.3 
 - Operating system version:  iphone11 and android 10 and so on 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size):  1440 × 1080 ,MPEG-4 AAC、H.264 274 MB 

**To Reproduce**
1. just play mp4 buy url
2. seek or buffer , there are finishedbuffering or  finishedseeking event triggered, then play the video after about 3 seconds

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Can you provide the URL that you are using for testing please?
2. What exactly do you mean by "unsmooth"?
3. What devices are you using for testing? 
4. Does it run "not smooth" on all of them or only some of them?

**Comment by Chris-RH** [comment]
We've not received a URL in our email yet.

**Comment by Chris-RH** [comment]
We've not received a URL in our email yet.

**Comment by Chris-RH** [comment]
We've not received a URL in our email yet.

**Comment by Ste-RH** [comment]
Closing due to lack of response
