### ISSUE TITLE
No finishedPlaying event when i seek to the end in android #3.0.3

### ISSUE THREAD

**Issue by DreamYao** [RenderHeads/UnityPlugin-AVProVideo#1909]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
 When I seek to the end,  finishedbuffering event is triggered, but no finishedPlaying event  android #3.0.3 

**Your Setup (please complete the following information):**
 - Unity version:  2023.3.21f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version: android 10
 - Device model: any one android 10 device
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1.  play the video from url
2.  before finished bufferring, seek to the end, it will trigger the event finishedBuffering, then show the end frame of the video,but no finishedPlaying event
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
any one video

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Is looping enabled or disabled?

**Comment by DreamYao** [comment]
disabled

**Comment by Chris-RH** [comment]
1. Are you able to reproduce it in a new project, running only the AVPro Video demo scenes?
2. Is it only streaming or is it local files too?
3. Have you tested it on different Android OS versions and does it occur on them?

**Comment by Chris-RH** [comment]
We've not been able to reproduce this.

Are you able to reproduce it in a new project, running only the AVPro Video demo scenes?
Is it only streaming or is it local files too?
Have you tested it on different Android OS versions and does it occur on them?
Can you provide a full logcat in txt form?

**Comment by Chris-RH** [comment]
We've not been able to reproduce this.

Are you able to reproduce it in a new project, running only the AVPro Video demo scenes?
Is it only streaming or is it local files too?
Have you tested it on different Android OS versions and does it occur on them?
Can you provide a full logcat in txt form?

**Comment by DreamYao** [comment]
Sorry, i have upgrade to 3.0.4. And i avoid the bug.
case MediaPlayerEvent.EventType.FinishedBuffering:
                if ((int)mediaPlayer.Info.GetDuration() == (int)mediaPlayer.Control.GetCurrentTime())
                {
                    // 直接seek到最后一秒，按照完成处理
                    HandleFinishedPlaying();
                    break;
                }
               .....
case MediaPlayerEvent.EventType.FinishedSeeking:
                if ((int)mediaPlayer.Info.GetDuration() == (int)mediaPlayer.Control.GetCurrentTime())
                {
                    // 直接seek到最后一秒，按照完成处理
                    HandleFinishedPlaying();
                    break;
                }
              .....
