### ISSUE TITLE
Video Looping on Windows Platform (WinRT) event if Loop is disabled.

### ISSUE THREAD

**Issue by NicolasDebeurme** [RenderHeads/UnityPlugin-AVProVideo#1913]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
I juste started an ended HLS Stream in the UnityEditor with WinRT and at the end of the stream the video Loop even if the Loop toggle is disabled and no event are fired, if you enable/disable it at runtime it fixes the issue and the FinishedPlaying event is fired.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.11f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): V3.0.4 Ultra
 - Operating system version: Windows11
 - Device model: /
 - Video specs (resolution, frame-rate, codec, file size): /

**To Reproduce**
1. In the Editor, start a video and go to the end with Loop disable on mediaPlayer WinRT platform.
2. Observe that its looping without any events fired.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Confirmed, issue occurs for WinRT, but not MF or DS.
If you disable loop during playthrough, you get FinishedPlaying and Paused events.

**Comment by RichRH** [comment]
Thanks for reporting this - issue found, fixed and will be in the next release.

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.5 has been released.  Please let us know if it has not fixed your issue.
