### ISSUE TITLE
The video freezes when playing 4K 60fps video for a while

### ISSUE THREAD

**Issue by Aunter1992** [RenderHeads/UnityPlugin-AVProVideo#1915]
Problem description:

1、When using the ExoPlayer API on the Android platform to play local 4K60 video, the video freezes after playing for several minutes, but the audio continues to play normally.
2、In the Unity scene, only the AVPro Video plugin is used.
3、Avprovideo version,  ultra  3.0.3

Device (which devices are you having the issue with - model, OS version number):

Model: Galaxy s20 5G ; OSVersion:Android 13

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

codec:h264
resolution:3840x2160
url:https://www.alipan.com/s/SmXc5c9QiBo
frame-rate:60

System Information:

AVPro Video: v3.0.3 (plugin v3.0.0f1-ultra)
Target Platform: Android
Unity: v2021.3.16f1c1 WindowsEditor
OS: Desktop - 82JK (LENOVO) - Windows 11  (10.0.22631) 64bit - ChineseSimplified
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz - 16 threads - 32535KB
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU - NVIDIA - Direct3D 11.0 [level 11.1] - 3977KB - 16384

**Comment by MorrisRH** [comment]
Which rendering API are you using? (Vulkan or OpenGLES)
If you're using OpenGLES, have you set the texture mode to YCbCr 420 OES?

**Comment by Aunter1992** [comment]
OpenGLES，  used brgb。

**Comment by Aunter1992** [comment]
I tried OES, but the same situation still occurs."

**Comment by Chris-RH** [comment]
1. Is it reproducible in a new project running only AVPro Video?
2. Can you send us the file you are testing with please to unitysupport@renderheads.com
3. Can you provide a full logcat in txt format

**Comment by Aunter1992** [comment]
> 1. Is it reproducible in a new project running only AVPro Video?
> 2. Can you send us the file you are testing with please to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
> 3. Can you provide a full logcat in txt format

1. yes,It is reproducible in a new project running only AVPro Video
2.you can download 4k 60 from here:   https://4kmedia.org/tag/60-fps/  
3. 
[logAvpro.zip](https://github.com/user-attachments/files/15981495/logAvpro.zip)

**Comment by rrenderr** [comment]
@Chris-RH 
I have the same issue on Meta Quest 3. The video plays for 2–10 seconds and freezes.
I use YCbCr 420 OES. With BGRA mode video plays well! And it reproduces on some videos. I've not found parameters that affect reproduce of the issue.

AVPro Video: v3.0.5 (plugin v3.0.5-ultra)
Target Platform: Android
Unity: v2022.3.15f1 WindowsEditor

Reproduced here https://deovr.com/kdzi6c
I can attach a video with the issue if you need one.

**Comment by rrenderr** [comment]
More details. 
Added full log
[FullLog.log](https://github.com/user-attachments/files/16107461/FullLog.log)
After a video freezes, audio continues to play.

When do you plan to release the version 3.0.6?

**Comment by MorrisRH** [comment]
@rrenderr planning to get 3.0.6 released later today

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.6 has been released.  Please let us know if it has not fixed your issue.

**Comment by rrenderr** [comment]
@Chris-RH This one works fine. Thank you!
But I had other rare issues, maybe connected with it. I opened new ticket
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1935
