### ISSUE TITLE
MediaPlayer Audio volume resetting on load and not updating in the Editor

### ISSUE THREAD

**Issue by heritageint** [RenderHeads/UnityPlugin-AVProVideo#1916]
**Describe the issue**
The MediaPlayer volume level seems to be resetting to 1 each time a new file is loaded although it's value (MP_Player.AudioVolume) reports the correct value (e.g. if we set to 0.2) the actual audible volume is 1 - the volume slider in the Editor shows 0.2 but if you move it slightly to adjust it then correctly sets the audible volume level.

**Your Setup (please complete the following information):**
 - Unity version:   2022.3.13f1:
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  AVPro Core 3.0.4)
 - Operating system version: Win11 Pro
 - Device model: Intel(R) Core(TM) i7-13700K 32GB RAM RTX3060
 - Video specs (resolution, frame-rate, codec, file size): Any file

**To Reproduce**
1. Set the Volume level of a MediaPlayer to 0.1
2. Load a new file
3. Audible volume appears to reset to 1 - volume in the Editor and AudioVolume property show 0.1
4. Change the volume level (e.g. to 0.2) and then the audible volume is correct

**Comment by RichRH** [comment]
Thanks for reporting this @heritageint - issue found, fixed and will be in the next release.

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.5 has been released.  Please let us know if it has not fixed your issue.
