### ISSUE TITLE
Does AVPro Media Player support transparent video on Xiaomi Redmi Note 9?

### ISSUE THREAD

**Issue by LibGame** [RenderHeads/UnityPlugin-AVProVideo#1917]
**Question**
Hello,

I am using AVPro Media Player to play videos on my Xiaomi Redmi Note 9 device. I need to play transparent videos (with an alpha channel). I would like to know if this feature is supported on the mentioned device.

Device Information:

Model: Xiaomi Redmi Note 9
Operating System: Android 10 (or the correct version if different)
AVPro Media Player Version Information:

Version: 3.0.1
Thank you in advance for your response!

**Comment by Chris-RH** [comment]
Its highly unlikely that the device supports codecs with alpha channels.  You would be better off using alpha packing.  More information on transparency in our [documentation](https://renderheads.com/content/docs/AVProVideo-v3/articles/feature-transparency.html).  For your specific device, why not test it using our[ trial version](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases).

**Comment by LibGame** [comment]
Hello, I use alpha packing but it doesn't work

**Comment by Chris-RH** [comment]
Can you provide us with a sampled of the video you are using please? Either here or to unitysupport@renderheads.com
