### ISSUE TITLE
AVPro Video's Support of Playing encrypted mp4 or Play Video From Memory

### ISSUE THREAD

**Issue by eiyamomo** [RenderHeads/UnityPlugin-AVProVideo#1918]
Before I asked this question, I have tried to search online or going through existing issues. Yet I can't find any solution for this.

I am creating a FMV-like game using Unity which includes a lot of videoclips (which currently in mp4).

I would like to encrypt the video files so the player would play the game (rather than find and play those videoclips locally)

It seems that AvPro Video's media player only support playing Video from File Path. I was hoping I could just load the encrypted video, decrypt it, then feed it to AvPro Video's mediaplayer. But I couldn't find out how.

the cycle of "load encrypted video -> decrypt -> write into local -> delete after finished playing" doesn't seem to be feasible as it might introduce uncertainties in terms of delays/performance hit/etc.

a lot of question I have found even traced back to 2020-2021, which really concerns me.

As today of June 2024, just wondering if there is any way (or alternative way) that is currently supported by AvPro Video to achieve being able to play encrypted videoclips?

Any help would be appreciated.

Thanks in advance.

**Comment by Chris-RH** [comment]
Which platform are you looking at using?

**Comment by eiyamomo** [comment]
Windows

**Comment by eiyamomo** [comment]
Updates:
I was finally able to get OpenMediaFromBuffer working 

By load the encrypted mp4, decrypt it into a byte[]

then set the videoAPI to be directshow

mediaPlayer.PlatformOptionsWindows.videoApi = Windows.VideoApi.DirectShow;

However the videoclip's aspect ratio / resolution got changed.

It was originally 1440p, but it got changed to 720x480.

**Comment by Chris-RH** [comment]
Are you able to send us a sample of the media you are playing please? Either here or to unitysupport@renderheads.com

**Comment by eiyamomo** [comment]
When I tried - You can just try it in the editor.

Set the videoapi to directshow, then use the browse(of the mediaplayer
gameobject)

If you play any mp4 greater than 1080p, under the media info(mediaplayer
gameobject), you will see it says 720×480.

While anything under or including 1080p it will be fine.

**Comment by Chris-RH** [comment]
Which version of AVPro Video are you using?
I can't reproduce this in the mediaplayer demo scene.

**Comment by eiyamomo** [comment]
Version 2.9.3

By adding a mediaplayer component to the gameobject, and set the videoapi
to directshow(then browse the videoclip)

**Comment by Chris-RH** [comment]
Do you see the same issue in MediaFoundation and WinRT?

**Comment by eiyamomo** [comment]
> You need to try WinRT please

Hi Chris,

I have tried WinRT, no it doesn't have this issue.

But it is not related to the issue I am reporting.

In order to use the OpenMediaFromBuffer, The VideoAPI has to be set to DirectShow.

But when VideoAPI is set to be DirectShow in the MediaPlayer, It will decrease the Resolution of the Video (if it is greater than 1080p)

It will be downsized to 720x480@29.97

NOTE: I am not sure why you keep mentioning about WinRT. Have you check my last Comment?

**Comment by Ste-RH** [comment]
@eiyamomo You are correct, OpenMediaFromBuffer is only an option when using the DirectShow API.  DirectShow relies on external filters (installed to the PC).  We have seen the best results using the LAV filters.  What codec is the video?  1080p could just be a limitation of the codec (in combination with the filters being used).

**Comment by Chris-RH** [comment]
@eiyamomo   What codec is the video?

**Comment by eiyamomo** [comment]
Hi Chris-RH

The codec of my video is H264-MPEG-4 AVC

I don't think it is the Codec. As it is not just the video file of my game.
I also tried other video files which are 4k resolution.

They can all play at its corresponding Resolutions (1440p or 4k)

But when the file is being encrypted and trying to play by using
*OpenMediaFromBuffer (which
requires directShow API)*

*It will force the resolution to become *720x480.

**Comment by RichRH** [comment]
Hi @eiyamomo,

I've had a look into this and a few notes:

- 'OpenMediaFromBuffer()' does only work with DirectShow
- By default the Microsoft H.264 decoder used by DirectShow only supprts up to 1920x1088 videos
- From version 2 of AVPro we included some dynamic format change code for DirectShow that permits higher resolutions
- The consquenece of the dynamic format change is initally the video is recgonised at a lower resolution (720x480) then later resized to the correct resolution

I've just tried loading our sample 'Cones-360Mono-4K30-H264.mp4' video via our 'Demo_MediaPlayer' scene (albeit in Video 3.0) using DirectShow and get the following log output:

```
[AVProVideo] Using playback path: DirectShow (720x480@30.00)

Registering a native texture with width=720 while the actual texture has width=3840

[AVProVideo] Texture size changed: 3840 X 1920
```
The net result is the video plays at the correct resolution but only after the resize event has corrected it - does this mirror what you're seeing? (As this is expected behaviour to get around the quirk of the MS H.264 decoder limitation)

Cheers,

**Comment by eiyamomo** [comment]
Hi Richard,


Regarding the three line in console.

I am only seeing the first one.

Just to be clear.  Is this only supported in AvPro video 2？

Since i am using last version. (avpro video 2  was released 2-3 months
after i made the purchase, can't justify another purchase Right after i
just purchased it.


*AVProVideo] Using playback path: DirectShow ***@***.***)

Registering a native texture with width=720 while the actual texture
has width=3840

[AVProVideo] Texture size changed: 3840 X 192*0

**Comment by RichRH** [comment]
Hi @eiyamomo,

"Just to be clear.  Is this only supported in AvPro video 2?" <- It should in any version from 2 onwards. I've just tried 2.9.3 Trial and get the following:

![image](https://github.com/user-attachments/assets/4e6cd94d-6a3e-4aaa-8868-0ffb5410c343)

The logging is slightly different but the end result is the same dynamically resized video rendered in 4K.

Cheers,
