### ISSUE TITLE
No finishedPlaying event on ios sometimes

### ISSUE THREAD

**Issue by DreamYao** [RenderHeads/UnityPlugin-AVProVideo#1919]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
The video has started play, there are no finishedPlaying event on ios sometimes

**Your Setup (please complete the following information):**
 - Unity version: 2022.3121f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 
 - Operating system version:  ipados 16.6
 - Device model: ipad mini (5) 64G 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. play the video
2. the video will stop at the last frame 

**Logs**

**Screenshots**

**Videos**
[If applicable, add a copy of your video or the URL](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11754273/db11167f-4bf9-4534-98b3-abd0780a5ed3)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
1. Which version of AVPro Video are you using?
2. Can you reproduce this issue using a new project and only running AVPro Video mediaplayer demo?
3. How often are you not getting the FinishedPlaying event?
4. What are your mediaplayer settings?
