### ISSUE TITLE
EntryPointNotFoundException

### ISSUE THREAD

**Issue by leonidax** [RenderHeads/UnityPlugin-AVProVideo#192]
After updating to the newest version of AVPro, I'm getting the following exception:

> EntryPointNotFoundException: SetHeadOrientation
> RenderHeads.Media.AVProVideo.WindowsMediaPlayer.SetAudioHeadRotation (UnityEngine.Quaternion q) (at Assets/AVProVideo/Scripts/Internal/WindowsMediaPlayer.cs:682)
> RenderHeads.Media.AVProVideo.MediaPlayer.UpdateAudioHeadTransform () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1770)
> RenderHeads.Media.AVProVideo.MediaPlayer.Update () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1099)

The error seems to be related to the DLLs.

**Setup**
 - Unity version:  2019.1.6f1
 - AVPro Video version: 1.10.1
 - Operating system version: Windows 10
 - Device model: PC
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 59.94, H264 mp4, 229 MB

**Comment by leonidax** [comment]
Ok I found the problem, the DLL was not being unloaded while importing the new ones and thus it was not finding the function since it was still working with the old dlls, I switched the platform from x86_64 to x86 and reimported the DLLs from the unitypackage.

**Comment by AndrewRH** [comment]
Yeah, if yup try to update after the plugin has run (by playing the scene for example) then the DLL files will become locked.  The correct process to update is to close Unity, open Unity then immediately import the new package to upgrade.

Since you solved the problem yourself I will close the issue now :)  Thanks,
