### ISSUE TITLE
Error event triggered on android 12 sometimes 

### ISSUE THREAD

**Issue by DreamYao** [RenderHeads/UnityPlugin-AVProVideo#1920]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Error event triggered on android 12 sometimes 

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.21f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.4
 - Operating system version: android 12
 - Device model:  Huawei matepad SE harmony os 3.0.0 android 12  apilevel 31 and HuaWei nova 11 harmony Os 4.0.0 android 12 api level 31
 - Video specs (resolution, frame-rate, codec, file size):  

**To Reproduce**
1. the origin file run  ffmpeg -i  EP01.mp4 -c:v libx264 -pix_fmt yuv420p -y EP01-01.mp4
2. play the video 

**Logs**
[2024/7/1 17:19:43] [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()

**Screenshots**

**Videos**
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/11754273/191bee89-962b-4fe6-8e54-b0b80dc7cd8f

**Comment by Chris-RH** [comment]
We don't support Harmony OS

**Comment by Chris-RH** [comment]
1. What android device are you using?
2. OpenGLES or Vulkan?
3. Exoplayer or Android mediaplayer?
4. Is it reproducible in a new project running only the AVPro Video mediaplayer demo scene?
5. Can you provide a full, unfiltered logcat in txt format?

**Comment by DreamYao** [comment]
[Uploading HUAWEI-AGS5-W00-Android-12_2024-07-01_160342.txt…]()

**Comment by DreamYao** [comment]
I will send the logcat by email

**Comment by DreamYao** [comment]
I have send the logcat by email

**Comment by Chris-RH** [comment]
Which non-Harmony OS device does it not work on?

**Comment by Chris-RH** [comment]
As I've said, we don't support HarmonyOS.  Is this issue only occurring on devices with HarmonyOS?
