### ISSUE TITLE
Add 10bit support to the Resolve To Render Texture component

### ISSUE THREAD

**Issue by acgourley** [RenderHeads/UnityPlugin-AVProVideo#1921]
When decoding 10bit HEVC videos on OSX Editor, PlatformMediaPlayer.cs queries _playerTexture.planes[i].textureFormat and sets textureFormat based on what it finds there. That switch statement finds a BGR10A2 texture but does not know how to handle it, so it falls back to using the 8-bit texture format. 

![Screenshot by Dropbox Capture](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/7680/3a266a80-113c-45b5-91ee-adb234ed8f1a)

I modified the code myself to have a new switch statement and it seems to work

```
case Native.AVPPlayerTextureFormat.BGR10A2:
  textureFormat = TextureFormat.RGBAFloat;
  break;
```

I'm not sure if RGBAFloat, or Half, or perhaps one of the 16bits per color textures would be optimal, but any would be better than 8 bit. 

**Setup**
 - Unity version: 2023
 - AVPro Video version: 3.0.5 Ultra
 - Operating system version: OSX 14.2 
 - Device model: M2 Studio
 - Video specs (resolution, frame-rate, codec, file size): UHD 10b HEVC off a GoPro. 

**Videos**
Here's a clip you can use https://www.dropbox.com/scl/fi/jjfai0x4a534suuwo7eix/H12_10b_Log_WBAuto.MP4?rlkey=3f8sn9lwi1nwwh4ycbmqmsnbg&st=oysst8af&dl=0

**Comment by MorrisRH** [comment]
I'm not sure what you mean. The platform media player doesn't perform any blits when updating the texture. Unity's texture simply wraps the native texture handle. No processing or conversion is performed.
Are you using the ResolveToRenderTexture component? (which would perform a blit)

**Comment by acgourley** [comment]
Yes I am using resolve to render texture. Is there any other way to get
access to the 10 bit data before that blit?

**Comment by MorrisRH** [comment]
ResolveToRenderTexture internally creates an ARGB32 render target. We'll look at getting that fixed so that it will create a render target capable of keeping the increased colour precision (probably RenderTextureFormat.ARGB2101010).

**Comment by MorrisRH** [comment]
Support for resolving to higher bit-depth render targets will make it into the next release (version 3.0.9)

**Comment by Ste-RH** [comment]
AVPro Video v3.0.9 has just been released.  Do let us know if the issue has been fixed for you.
