### ISSUE TITLE
Video is playing with only sound but no image

### ISSUE THREAD

**Issue by cheesam-fms** [RenderHeads/UnityPlugin-AVProVideo#1923]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
To achieve: 2 media players crossfading, switch the players' video using tween and close media when done switching. 
Full Issue Descriptions: While playing videos using media players, the media player can be played and trigger events but occasionally it will play without image/picture.
Examples: MP = Media Player;
"MP A" switching to "MP B" while "MP A" is playing, fade out the display A, and fade in display b. After fading display A will close media on "MP A". The issue will sometimes occurs when switching back to "MP A" from "MP B" which the "MP A" is playing the video without the image(black screen).

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.12f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Version 2.9.3 - AV Pro Video Ultra Edition
 - Operating system version: Windows 10 Pro
 - Device model: System Model - MS-7A70 ; Processor - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 4200 Mhz, 4 Core(s), 8 Logical Processor(s)
 - Video specs (resolution, frame-rate, codec, file size):  Resolution - Any (1920x1080, 1280x720, 2048x1536, etc) ; Frame-rate - 24/25 fps ; Codec - H.264 | 0x34363248 ('H264') ; File-size - Any (3++mb - 800++mb)

**To Reproduce**
1. It occurs occasionally, but to reproduce, spamming the close media and open media between the "MP A" and "MP B" will sometimes occurs this error. I am spamming it once per 1.2sec.

**Logs**
If applicable, add error logs to help explain your problem.
There is no error logs for this issue because the video is still consider playing.

**Screenshots**
![image](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/174414857/42894805-ae27-4c56-960f-8ad682faaf74)
This is the code snippet I am using to achieve the crossfade. Even though removing the close media on "Line:851", the error will still occurs. I am spamming this code snippet it once per 1.2sec. The fade duration is 0.5f using DOTween library.

**Videos**
If applicable, add a copy of your video or the URL
https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/174414857/a0598cbc-7876-4593-be6a-6f1ebd6fcb45
In this video, the media player is actually playing but there is no image on the inspector shown. It will also trigger the events as you can see after the video is finished playing. This issue can happen in both the "MP A" and "MP B" that I am using for crossfade.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Apologies, this issue seems to have slipped through the net.  Are you still requiring some input on it @cheesam-fms ?

**Comment by Chris-RH** [comment]
Is there a reason that you didn't use the playlist component?
Have you tried both Media Foundation and DirectShow?

**Comment by Chris-RH** [comment]
Is there a reason that you didn't use the playlist component?
Have you tried both Media Foundation and DirectShow?

**Comment by Chris-RH** [comment]
We will be closing this issue soon due to a lack of response.
