### ISSUE TITLE
Type or Namespace does not exist

### ISSUE THREAD

**Issue by Gianni-K** [RenderHeads/UnityPlugin-AVProVideo#1926]
(there are 16 total errors, some happen more than once, numbers are the order of the errors from top to bottom)For Pun(1,5-9), Realtime(2), Voice(3), ExitGames(4), MonoBehaviourPunCallbacks(10,14), RoomOptions(11), DisconnectCause(12), MonoBehaviorPun(13), PunRPCAttribute(15), PunRPC(16)

**My Setup:**
 - Unity version: 2022.3.35f1
 - AVPro Video version: I don't have AVPro(I think)
 - Operating system version: Windows 11
 - Device model: ASUS Tuf Gaming F15

Assets\PhotonVR\Scripts\PhotonVRManager.cs(11,14): error CS0234: The type or namespace name 'Pun' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\PhotonVRManager.cs(12,14): error CS0234: The type or namespace name 'Realtime' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\PhotonVRManager.cs(13,14): error CS0234: The type or namespace name 'Voice' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\PhotonVRManager.cs(15,7): error CS0246: The type or namespace name 'ExitGames' could not be found (are you missing a using directive or an assembly reference?)

Assets\PhotonVR\Scripts\PhotonVRManagerGUI.cs(13,14): error CS0234: The type or namespace name 'Pun' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\Player\PhotonVRPlayer.cs(5,14): error CS0234: The type or namespace name 'Pun' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\Player\PlayerSpawner.cs(3,14): error CS0234: The type or namespace name 'Pun' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\Testing\PhotonVRColourChangerGUI.cs(5,14): error CS0234: The type or namespace name 'Pun' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\Testing\PhotonVRCosmeticsChangerGUI.cs(7,14): error CS0234: The type or namespace name 'Pun' does not exist in the namespace 'Photon' (are you missing an assembly reference?)

Assets\PhotonVR\Scripts\Player\PlayerSpawner.cs(7,34): error CS0246: The type or namespace name 'MonoBehaviourPunCallbacks' could not be found (are you missing a using directive or an assembly reference?)

Assets\PhotonVR\Scripts\Player\PhotonVRPlayer.cs(13,35): error CS0246: The type or namespace name 'MonoBehaviourPun' could not be found (are you missing a using directive or an assembly reference?)

Assets\PhotonVR\Scripts\PhotonVRManager.cs(19,36): error CS0246: The type or namespace name 'MonoBehaviourPunCallbacks' could not be found (are you missing a using directive or an assembly reference?)

Assets\PhotonVR\Scripts\Player\PhotonVRPlayer.cs(72,10): error CS0246: The type or namespace name 'PunRPCAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\PhotonVR\Scripts\Player\PhotonVRPlayer.cs(72,10): error CS0246: The type or namespace name 'PunRPC' could not be found (are you missing a using directive or an assembly reference?)

Assets\PhotonVR\Scripts\PhotonVRManager.cs(50,17): error CS0246: The type or namespace name 'RoomOptions' could not be found (are you missing a using directive or an assembly reference?)

Assets\PhotonVR\Scripts\PhotonVRManager.cs(349,45): error CS0246: The type or namespace name 'DisconnectCause' could not be found (are you missing a using directive or an assembly reference?)

https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/122071705/49bf3a90-1ef0-4b3b-9dff-f56ecdeccc67

**Comment by Chris-RH** [comment]
Hi, This is the github for AVPro Video issues.  I suggest that you contact Photon about this issue.
