### ISSUE TITLE
[Bug] v3 Android play video crash.

### ISSUE THREAD

**Issue by zzimagination** [RenderHeads/UnityPlugin-AVProVideo#1927]
**Describe the issue**
Play the video while the game is running, and then the game crashes. An error was found in the java code.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.21f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.3 core
 - Device: iQOO Neo7 (V2231A) 
 - CPU: MediaTek Dimensity 9000
 - GPU: Mali-G710
 - Video specs (resolution, frame-rate, codec, file size):  1920x864  24fps  h264  12963kbps 6722KB

**Logs**
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Collection.isEmpty()' on a null object reference<br> at com.renderheads.AVPro.Video.Player_Base.UpdateCommandQueue(Unknown Source:14)<br> at com.renderheads.AVPro.Video.Player_Base.Update(Unknown Source:100)<br> at com.renderheads.AVPro.Video.Manager$1.run(Unknown Source:8)<br> at android.os.Handler.handleCallback(Handler.java:942)<br> at android.os.Handler.dispatchMessage(Handler.java:99)<br> at android.os.Looper.loopOnce(Looper.java:223)<br> at android.os.Looper.loop(Looper.java:324)<br> at android.app.ActivityThread.main(ActivityThread.java:8382)<br> at java.lang.reflect.Method.invoke(Native Method)<br> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)<br> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)<br>

**Comment by Chris-RH** [comment]
Can you reproduce this in a new project running only AVPro Video mediaplayer demo scene?
Can you supply a full, unfiltered logcat in txt form of the above
Is the video streamed or played locally?
Can you supply a sample of the video/stream URL.  Either here or to unitysupport@renderheads.com
Have you tested it on any other devices?

**Comment by Ste-RH** [comment]
We fixed a bug that looks very similar to this a release or two ago.  Please update to check @zzimagination .

**Comment by zzimagination** [comment]
> 1. Can you make sure you are using the latest version of AVPro Vide (3.0.5) and retest please.
> 2. Can you reproduce this in a new project running only AVPro Video mediaplayer demo scene?
> 3. Can you supply a full, unfiltered logcat in txt form of the above
> 4. Is the video streamed or played locally?
> 5. Can you supply a sample of the video/stream URL.  Either here or to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
> 6. Have you tested it on any other devices?

1. We are in close beta, I will try to upgrade later.
2. 3. Sorry. This is error occurred on the player's device, No further information is available
4. Local，streamingAssets and persistentData
5. Sorry, the original video cannot be provided at the moment, but this video should be a very normal mp4.
6. Some phones had similar problems, but no further information was available.

We will run more tests and provide new information as it becomes available

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.6 has been released.  Please let us know if it has not fixed your issue.
