### ISSUE TITLE
Can I have the video display in gamma color space while Unity project is in linear color space

### ISSUE THREAD

**Issue by SkylerGubbels** [RenderHeads/UnityPlugin-AVProVideo#1929]
**Question**
I've current got a Unity project where the gameplay is in linear color space. This works well for the in-game lighting but unfortunately it means that when I try to play pre-rendered cutscenes exported in Rec.709 they are also displayed in a linear color space and look very washed out.

If I switch the project to gamma color space then the cutscenes display correctly but unfortunately this ruins the lighting in a lot of other areas meaning this unfortunately isn't an option.

I was wondering if anyone knew of a way that I could have the videos not look washed out while still keeping my project in a linear color space. I'm open to any solution, whether this involves something in AVPro, exporting the videos in a different color space that plays better with Unity's linear color space or some other alternative. I'm not the most experienced with this kind of stuff so there may be an obvious solution that I'm missing.

**Comment by Chris-RH** [comment]
What platform are you wanting to use this on?
Could we get a sample of one of your videos please, either here or to unitysupport@renderheads.com :)

**Comment by SkylerGubbels** [comment]
This would be on Windows, Mac OSX and Linux.

I just sent a sample video to the email and also included some comparison shots. Thanks!

**Comment by Chris-RH** [comment]
Closing due to lack of reply
