### ISSUE TITLE
Changing volume does not affect sound on Android platform

### ISSUE THREAD

**Issue by Quovadistom** [RenderHeads/UnityPlugin-AVProVideo#1930]
**Describe the issue**
When trying to change the volume of videos with sound on an Android device, the actual volume does not change. I've added logs all the way to the implementations of BaseMediaPlayer and it seems that the actual value is passed on correctly. However, nothing is happening in any of the implementations of BaseMediaPlayer (NullMediaPlayer, WebGLMediaPlayer, WindowsMediaPlayer, WindowsRtMediaPlayer). I've also tested with an adapted version of the mediaplayer/ui from an AVPro demo scene (Demo_MediaPlayer), which shows the same issue. No errors.
Windows and iOS work as expected.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.18f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.5 Core
 - Operating system version: Android 12.1 (Quest), Android 13 (phone)
 - Device model: Quest 2, Galaxy A51
 - Video specs (resolution, frame-rate, codec, file size): Various, also happening with the demo video RenderHeads-1080p30-H264.mp4

**To Reproduce**
Android phone:
1. Build and run Demo_MediaPlayer scene
2. Try changing volume -> no audio change

Quest 2
1. Grab the MediaPlayer & MediaPlayerUI from the Demo_MediaPlayer scene
2. Create a Quest-ready scene
4. Paste the copied items in this scene
5. Make sure UI is interactable (and world space)
6. Build to Quest 2
7. Open the application in Quest 2
8. Move volume slider -> no audio change

**Comment by Ste-RH** [comment]
Thanks for reporting this.  We have identified the issue and there will be a fix in for it in the next release (v3.0.6).

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.6 has been released.  Please let us know if it has not fixed your issue.

**Comment by Quovadistom** [comment]
I can confirm the fix works. Thanks for picking this up and providing a fix so quickly!
