### ISSUE TITLE
Why UnityEditor window is focused when start playing video with meta XR Simulator.

### ISSUE THREAD

**Issue by Anton111111** [RenderHeads/UnityPlugin-AVProVideo#1932]
It is not urgent question. I just wonder why Unity Editor window is focused when start playing video with meta XR Simulator. It is not comfortable in development process.

A little bit more details. I develop app for Quest VR Headset. And in development process i use Meta XR Simulator. And when AVPro start video XR simulator lost focus and focus jump to UnityEditor. 

May be you know how to avoid it?

**Comment by Chris-RH** [comment]
Its not something that we use ourselves, so wouldn't be sure if there are settings required to change this.
