### ISSUE TITLE
Does AvProVideo Will Support HarmonyOS?

### ISSUE THREAD

**Issue by polaris7765** [RenderHeads/UnityPlugin-AVProVideo#1937]
**Is your feature request related to a problem? Please describe.**
Our App want support Harmony Os at 2 months, but we are using Avpro Video plugins can not support Harmony Os. this is a big problem for us at this time.

**Describe the solution you'd like**
So we are strongly hope that this plugin can adapt to the HarmonyOS.

**Describe alternatives you've considered**
Otherwise, we have to consider using alternative solutions.

**Additional context**

**Comment by Chris-RH** [comment]
We currently have no plans to support HarmonyOS.  The SDK only seems to come with the Chinese version of Unity.  We are a very small team and don't have time to start supporting another OS.
