### ISSUE TITLE
AVPro Video doesnt work on Google Chromecast with Google TV

### ISSUE THREAD

**Issue by Gabox0242** [RenderHeads/UnityPlugin-AVProVideo#1939]
When trying to play an m3u8 content it doesn't work, it shows the following message in the log.

 - Unity version: Unity 6000.0.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.6 Trial 
 - Operating system version: Android 13
 - Device model: Google Chromecast with Google TV. HD

![1](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/17486059/b78c7bef-69a3-4396-8046-0251e7e6d8a3)
![2](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/17486059/b1333404-44f9-4c87-853b-3f1abd5ffa42)

The first image is on Google Chromecast, and the second image is on my phone (S24 Ultra) in the same scene.

This happens with any m3u8 content, I have tried several and it always gives the same error on Chromecast.

I am using Vulkan, but with OpenGL ES is the same result.

**Comment by Chris-RH** [comment]
Hi,
We don't support Chromecast.
