### ISSUE TITLE
[iOS] Facing crashes on iOS 12 and iPadOS 12

### ISSUE THREAD

**Issue by AnSmulie** [RenderHeads/UnityPlugin-AVProVideo#1946]
We are currently having a lot of AVPro related issues in iOS 12 and iPadOS 12. Our team have not been able to reproduce these issues in testing environment and have no ideas what is causing these crashes. We really need the help from RenderHeads team to look into this.

 - Unity version:  2021.3.12f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.8.4 Core Edition
 - Operating system version: 
 - Device model:
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Open the app on a device with iOS 12
2. 

**Logs**
Firebase Crashlytics Log: [LINK](https://console.firebase.google.com/u/0/project/simplest-piano/crashlytics/app/ios:com.smulie.simpia/issues/4de063c0b9d4daf1b0c0e077119b92d6?time=last-seven-days&sessionEventKey=6e62552f515b40189f219666417cf08f_1970011065769481192)

**Screenshots**
![image](https://github.com/user-attachments/assets/09bece04-3134-4c80-9181-6594f5188e8e)
![image (1)](https://github.com/user-attachments/assets/61b8da86-1e6e-4e03-bdf3-d2556393f86d)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @AnSmulie, 

AVPro Video version 2 has been depreciated and will no longer be receiving updates.  I suggest you update to the last version, which is AVPro Video version 2.9.3 before retesting.

**Comment by AnSmulie** [comment]
Hi @Chris-RH thank you for your quick response. I also checked on the asset store and it seems that we would need to upgrade to AVPro Video 3 for active support since 2 has been deprecated for some months now. I want to ask if there are any discounted update plan for users that already bought 2, or do we have to buy 3 wholesale again if we want to upgrade?

**Comment by Chris-RH** [comment]
There is a [discounted upgrade path](https://renderheads.com/content/docs/AVProVideo-v3/articles/download.html#owners-of-avpro-video-2x) between AVPro Video 2 and 3, which will automatically be applied in the Unity Asset Store.
