### ISSUE TITLE
[iOS] Crashes on iOS AVPPluginGetRenderEventFunction

### ISSUE THREAD

**Issue by IgorKubyshkin** [RenderHeads/UnityPlugin-AVProVideo#1947]
Hello. We've noticed some crashes after release our app in the AppStore. This happens when AVPPluginGetRenderEventFunction is called. Could you help us to resolve this? I attached crash logs and screenshot from xcode

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.6
 - Operating system version: iPhone OS 16, 17
 - Device model: iPhone, iPad

**Logs**
https://drive.google.com/file/d/174xYTQ6QxJLaQ23VUBTazZqMqSuFMOvN/view

**Screenshots**
https://drive.google.com/file/d/1B-bJMG1jrIBGY8fRucvkNpTVJN35oY0S/view?usp=sharing

**Comment by MorrisRH** [comment]
AVPPluginGetRenderEventFunction is only called when the plugin is initialised the first time a MediaPlayer component is created. The odd thing from your crash logs is that this is being called from Unity's render thread when I would expect it to be called from the main thread.

Unfortunately there is not enough information in the log files to work out what's going wrong and without a reproducible case a fix will not be possible. If you could provide as much information as possible around how you're using the player in your app that would be helpful.

**Comment by MorrisRH** [comment]
@IgorKubyshkin if you're able to share your reproducible case that would be great, please send a link to unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
@IgorKubyshkin thanks for the project. I've been able to reproduce the crash and identified the underlying issue. A fix will make it into the next release.

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.8 has been released.  Please can you let us know if it has not fixed your issue.
