### ISSUE TITLE
HEVC Video is not working on Android

### ISSUE THREAD

**Issue by Fasilkallot** [RenderHeads/UnityPlugin-AVProVideo#1949]
When attempting to play an HEVC video, the video fails to load and generates the following error in the Android logcat:

2024-07-18 18:19:11.458 24421 27336 Error Unity [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

Unity version: 2023.2.3f
AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.3 Core Edition
Operating system version: Windows 11
Device model: Oneplus 8T
Video specs (resolution, frame-rate, codec, file size): 4k 24 fps, H.265, 396 MB

To Reproduce

1 -> Encoded 4k video to HEVC using Hand Brake 
2 -> Upload video to server and attach video link to Playlist Media Player 
3 -> Build and run the android apk and try to play the video 

Logs
2024-07-18 18:19:11.458 24421 27336 Error Unity [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
2024-07-18 18:19:11.458 24421 27336 Error Unity UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
2024-07-18 18:19:11.458 24421 27336 Error Unity RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
2024-07-18 18:19:11.458 24421 27336 Error Unity RenderHeads.Media.AVProVideo.MediaPlayer:Update()
2024-07-18 18:19:11.458 24421 27336 Error Unity

**Comment by Ste-RH** [comment]
We are no longer supporting AVPro Video v2.x.  That said, I do not think this is an issue with AVPro itself.

In Windows you need to install the H265/HEVC codec from the Windows Store.  If you search for 'HEVC' on the store you will find the codec to purchase/download.  It should be approximately $0.99 (or your locales equivalent) and is published by 'Microsoft'.

**Comment by Fasilkallot** [comment]
Thank you for the information regarding AVPro Video v2.x and the H265/HEVC codec. I understand the need for this codec on Windows. However, could you please clarify if I also need to purchase the codec for testing on Android?

**Comment by Ste-RH** [comment]
Apologies, I miss-read your issue initially and thought it was a Windows problem.  I have updated my response since.  Please refresh and re-read.

**Comment by Fasilkallot** [comment]
Thanks for the suggestions! My device supports 4k HEVC, and I've already enabled the software decoder preference in the ExoPlayer API options. I also tried lowering the video quality to 1440p and 1080p, which resolved the "file not found" log issue, but unfortunately, the video still isn't playing. When I switch to the MediaPlayer API instead of ExoPlayer on Android, the video does play, but I encounter frequent lagging during playback. Do you have any other ideas on how to solve this issue?

**Comment by Chris-RH** [comment]
Hi @Fasilkallot, 

Are you able to send us a sample of the video you are using for testing please.  Either here or to unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Have you tried v3.0.7 trial?  Just to see if the big overhaul we made in v3 has had a positive impact.

**Comment by Chris-RH** [comment]
Any luck @Fasilkallot ?

**Comment by Fasilkallot** [comment]
Hi Cris,

Thank you for your support.

I think the issue is with the video. When I tested it with other HEVC codec videos downloaded from the internet, it worked fine. So, I'm currently working on the video.
