### ISSUE TITLE
AV pro video Dlls not compatible with Android App Bundles 64-bit Gradle builds.

### ISSUE THREAD

**Issue by quindo** [RenderHeads/UnityPlugin-AVProVideo#195]
**Describe the bug**
The new google play policies require apps to be submitted as App Bundles using the Gradle build pipeline.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.9f1
 - AVPro Video version: 1.10.1
 - Operating system version: Android
 - Device model:  Generic
 - Video specs (resolution, frame-rate, codec, file size): NA

**To Reproduce**
1. Build an Android App Bundle with AV Pro Video for the play store.
2. Submit to the play store.
3. Attempt to move forward to the internal testing track.
4. Google will throw an error saying 32 bit libraries are being used.

Alternatively:
1. Build an apk using gradle and AV Pro Video.
2.  Analyze the APK with android studio
3. Check to see if lib/x86 contains all the same .so files as the lib/arm64-v8a.  If they do not that means google will throw the 32 bit error and will not accept the upload.

**Comment by RenderHeadsSte** [comment]
Hi. Is this just not the same issue as:

https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/181#issuecomment-533053680

**Comment by Haseeb905** [comment]
Hi, So I followed the exact method mentioned in following message

"This is easily solved. Just go to the /Plugins/Android/libs/arm64 folder and select each file there in Unity. Then in the Inspector set the Platform to Android and the Architecture to ARM64. His Apply and do this for each file. The builds should then work for 64-bit."

But this didnt worked for me. Any help here would be appreciated.
I am using Unity2019.2.2f

**Comment by quindo** [comment]
It was.

In addition to the steps in #181 I also needed to manually go in and disable x86 support in the project.  I don't know if it was AVpro or something else, but attempting to include x86 support was causing google to reject the package.
