### ISSUE TITLE
3.0.7 not playing video in 360 demo scene for VisionOS project

### ISSUE THREAD

**Issue by funiqueHarry** [RenderHeads/UnityPlugin-AVProVideo#1950]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
After setting up a VisionOS project with AVPro Video 3.0.7 and modifying the 360 demo scene, the video is not playing as expected.

The output shows the test Sphere correctly, but the video is not playing.
YpCbCr has been attempted (also checked in the shader settings) but did not resolve the issue.
This issue persists whether using YpCbCr or not.

**Your Setup (please complete the following information):**
- Unity version: 2022.3.38f1
- AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.7 (edition not specified)
- Operating system version: VisionOS (version not specified)
- Device model: 1.2
- Video specs (resolution, frame-rate, codec, file size): Not specified

**To Reproduce**

1. Create a new project using Unity 2022.3.38f1
2. Set up the project for VisionOS following the standard procedures
3. Import AVPro Video 3.0.7 into the project
4. Open the 360 demo scene from AVPro Video
5. Replace the camera with XR Origin and add an AR Session
6. Add a test Sphere to the scene for visual reference
7. set YpCbCr
8. Build 

**Logs**
`
[XR] Display Start
The referenced script (Unknown) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!
A scripted object (probably RenderHeads.Media.AVProVideo.MediaReference?) has a different serialization layout when loading. (Read 64 bytes but expected 87604 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
The referenced script (RenderHeads.Media.AVProVideo.ApplyToMesh) on this Behaviour is missing!
The referenced script (RenderHeads.Media.AVProVideo.MediaPlayer) on this Behaviour is missing!
The referenced script (RenderHeads.Media.AVProVideo.ResolveToRenderTexture) on this Behaviour is missing!
The referenced script (RenderHeads.Media.AVProVideo.Demos.LookAround360) on this Behaviour is missing!
The referenced script (RenderHeads.Media.AVProVideo.UpdateMultiPassStereo) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Sphere-ApplyToMesh') is missing!
A scripted object (probably RenderHeads.Media.AVProVideo.ApplyToMesh?) has a different serialization layout when loading. (Read 32 bytes but expected 112 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
The referenced script on this Behaviour (Game Object 'MediaPlayer') is missing!
A scripted object (probably RenderHeads.Media.AVProVideo.MediaPlayer?) has a different serialization layout when loading. (Read 32 bytes but expected 824 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
The referenced script on this Behaviour (Game Object 'MediaPlayer') is missing!
A scripted object (probably RenderHeads.Media.AVProVideo.ResolveToRenderTexture?) has a different serialization layout when loading. (Read 32 bytes but expected 108 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
The referenced script on this Behaviour (Game Object 'Main Camera') is missing!
A scripted object (probably RenderHeads.Media.AVProVideo.Demos.LookAround360?) has a different serialization layout when loading. (Read 32 bytes but expected 44 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
The referenced script on this Behaviour (Game Object 'Main Camera') is missing!
A scripted object (probably RenderHeads.Media.AVProVideo.UpdateMultiPassStereo?) has a different serialization layout when loading. (Read 32 bytes but expected 44 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
-> applicationWillEnterForeground()
-> applicationDidBecomeActive()
`
**Screenshots**
<img width="1506" alt="截圖 2024-07-19 下午3 55 31" src="https://github.com/user-attachments/assets/b33556fc-9873-487a-9529-b9d164a5f5a8">
<img width="721" alt="截圖 2024-07-19 下午3 54 43" src="https://github.com/user-attachments/assets/1abf53a0-f4d6-4827-8c07-943bab0c0151">

**Videos**
AVProVideoSamples/Cones-360Stereo-2K30-H264.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by funiqueHarry** [comment]
1. We are using Xcode 15.4 simulator for testing.
2. The project is using the .NET framework.
3. The app mode is set to VR.
4. We have ensured that there are no warnings or errors displayed in the XR Project Validation.
5. Both Unity and Xcode builds complete without displaying any errors.

**Comment by Chris-RH** [comment]
This is a known issue
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1794

**Comment by funiqueHarry** [comment]
I apologize for overlooking this message.
(it might be helpful to mention this in the "Known Issues" section of the docs).
Do you currently have any progress on this issue?
We really need to know. Thank you.
