### ISSUE TITLE
[iOS]  - Video not playing in simulator builds

### ISSUE THREAD

**Issue by deepakag123** [RenderHeads/UnityPlugin-AVProVideo#1951]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Testing AVPro in my project using IOS simulator.  Core mobile edition

I only included the demo scene for testing.  Unticked all other scenes.

On the simulator i get a blank screen. 

On Xcode i am seeing a EXC_BAD_ACCESS  message.

Tried reimporting and still shows same error.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  AVPro Video v3 - Core Mobile Edition . Version 3.0.7 - July 16, 2024
 - Operating system version:  Ventura 13.6.7
 - Device model: MAC
 - Video specs (resolution, frame-rate, codec, file size): 

**Screenshots**
attached.
Error
<img width="1435" alt="Screenshot 2024-07-20 at 22 30 09" src="https://github.com/user-attachments/assets/91d0e260-88a3-4678-8ca7-817e73a15f6f">

<img width="1082" alt="Screenshot 2024-07-21 at 12 26 49" src="https://github.com/user-attachments/assets/b7f9f695-0d42-4da3-8ea2-d75f52101c35">
<img width="1096" alt="Screenshot 2024-07-21 at 12 26 21" src="https://github.com/user-attachments/assets/abb020cc-355f-401e-9a82-2f1aa934e57f">
<img width="1092" alt="Screenshot 2024-07-21 at 12 25 08" src="https://github.com/user-attachments/assets/d890488d-0dd3-4c84-b65d-f794e1b6f1a4">
<img width="1092" alt="Screenshot 2024-07-21 at 12 25 23" src="https://github.com/user-attachments/assets/43156c3f-669f-4d2c-b040-c6bd77991ac2">
<img width="1061" alt="Screenshot 2024-07-21 at 12 25 39" src="https://github.com/user-attachments/assets/12674e30-e9a5-400b-b8ea-5d1713315ba4">
<img width="1096" alt="Screenshot 2024-07-21 at 12 25 48" src="https://github.com/user-attachments/assets/d7dc51ba-e67d-47ad-97ca-bf3ee91b1b62">
<img width="1088" alt="Screenshot 2024-07-21 at 12 25 59" src="https://github.com/user-attachments/assets/74458ef0-7a19-4d7c-a453-2cdde28cdc16">
<img width="1058" alt="Screenshot 2024-07-21 at 12 26 07" src="https://github.com/user-attachments/assets/78d3b0cf-bb6c-4c70-bd02-438a54762355">

**Comment by Chris-RH** [comment]
So its a new project, running only a demo scene? Which one?
Does it play in mac editor?
Have you tested it on an actual iOS device?
Which version of xcode are you using?

**Comment by deepakag123** [comment]
Answers below

So its a new project, running only a demo scene? Which one?
This is an existing project that I have where  I have added AVPro . However, for testing , I have just excluded all the other scenes and only playing the Demo_MediaPlayer scene. See screenshot. 

Does it play in mac editor?
Yes, its playing on a mac editor.

Have you tested it on an actual iOS device?
No, only tested on simulator. 

Which version of xcode are you using?
Version 15.2

Note that when I use a standalone new project, its working on the simulator. Its not working when I use it in my existing project. 
![Uploading Screenshot 2024-07-22 at 17.15.18.png…]()

**Comment by deepakag123** [comment]
<img width="1438" alt="Screenshot 2024-07-22 at 17 15 18" src="https://github.com/user-attachments/assets/b0742e47-dec7-4cb6-b684-c43ffd327358">

**Comment by Chris-RH** [comment]
Its difficult to know what's happening if it doesn't work in your project, but works when built on its own.
Are you able to make a simplified project that reproduces the issue (ie not your whole project, but whatever you have to do to the one that works to cause the same issue)?  You can send it to unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
@deepakag123 thanks for the sample project. I was able to reproduce the crash and think I have a solution which will make it into the next release. Please let us know if it solves the problem for you.

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.8 has been released.  Please can you let us know if it has not fixed your issue.

**Comment by deepakag123** [comment]
Thank you for the quick response. It works fine now.

**Comment by deepakag123** [comment]
thanks.
