### ISSUE TITLE
[Windows 7] Windows 7 cannot jump to the last frame when using the SeekToFrame method. It will be randomly positioned between 3-10 seconds at the end of the video. Currently, AVPro Video Core Edition 3.0.8 is used.

### ISSUE THREAD

**Issue by Ver-j** [RenderHeads/UnityPlugin-AVProVideo#1952]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
After publishing the software to Windows 7 system, when using the SeekTo Frame method, it cannot jump to the last frame. It will be randomly positioned between 3-10 seconds at the end of the video. Currently, AVPro Video Core Edition 3.0.8 is used.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.6f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core Edition 3.0.8
 - Operating system version: Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size):    H.264
![image](https://github.com/user-attachments/assets/4e7b43c8-52a2-4c86-80cf-25704d8e1cb5)

**To Reproduce**

                var videoDuration = _mediaPlayer.Info.GetDurationFrames();
		_mediaPlayer.Control.SeekToFrame(videoDuration);
		await UniTask.Delay(TimeSpan.FromSeconds(0.2f));
		_mediaPlayer.Control.SeekToFrame(videoDuration);

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, 

We only support Windows 10 and 11.

**Comment by Ver-j** [comment]
How can I get a package that supports Windows 7

**Comment by Chris-RH** [comment]
I'm afraid that we don't have any assets available for purchase that support Windows 7.

**Comment by Chris-RH** [comment]
Do you get the same issue in Windows 10 or 11?

**Comment by Chris-RH** [comment]
I'm going to close this now, as we don't support Windows 7.  If you are having this issue in Windows 10 or 11, please reopen.
