### ISSUE TITLE
[Android] Playback fails on NVIDIA Shield Pro

### ISSUE THREAD

**Issue by MarsKK** [RenderHeads/UnityPlugin-AVProVideo#1953]
**Describe the issue**
A clear and concise description of what the issue is.
androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.40f1c1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.8
 - Operating system version: Android 9
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 
https://oscdn.holatek.cn/window/video/forest.mp4

**Logs**
![111](https://github.com/user-attachments/assets/8a7dc98f-ce97-4e8e-b5ae-ceb6dc2ce5a6)
![222](https://github.com/user-attachments/assets/fedb8902-48be-47d7-aa48-4e0927e2cee9)

**Videos**
[[If applicable, add a copy of your video or the URL]()](https://oscdn.holatek.cn/window/video/forest.mp4)

**Comment by Chris-RH** [comment]
Are you able to reproduce this in a new project running only the AVPro
Video demo scenes?
Thats very difficult to read. Can you post the full unfiltered logcat in
txt format please.
Have you tested it on other devices?

**Comment by pete-edwards** [comment]
I also seem to get this error after updating. I also ran it on the demo scene and it still happens

Unity Version: 2022.3.39f1
AVPro Version: 3.08
Demo scene: Demo_MediaPlayer
Android Version: 11
Device: NVidia Shield Pro
[av_issue_logs.txt](https://github.com/user-attachments/files/16440572/av_issue_logs.txt)

**Comment by Chris-RH** [comment]
Hi @pete-edwards 

1. Can you confirm which model of Nvidia shield this is please (2015, 2017 or 2019)
2. Is it reproducible when switching from Vulkan to OpenGLES?
3. Is it reproducible when switching from Exoplayer to Android mediaplayer?
4. Can you reproduce this on any other devices?

**Comment by pete-edwards** [comment]
> Hi @pete-edwards
> 
> 1. Can you confirm which model of Nvidia shield this is please (2015, 2017 or 2019)
> 2. Is it reproducible when switching from Vulkan to OpenGLES?
> 3. Is it reproducible when switching from Exoplayer to Android mediaplayer?
> 4. Can you reproduce this on any other devices?

Thanks for the suggestions @Chris-RH. On the demo project, turning off Vulcan and using OpenGLES instead had the same crash. Switching to android media player from exo player no longer had the crash in the logs, but still was not rendering anything. However, building with both changes (ie Android media player AND OpenGLES) it now seems to run the demo video on the device.

I've attached logs of the first 2 cases where it was not working.
We are using the 2019 version of the Shield. I've not tried on other Android devices yet (we only target the Nvidia Shield so really it needs to work on that). 

Also this has just started happening when trying to update to version 3. We've been running on v2 succesfully for a couple of years now (2.93 I believe is the current version we have live)
Thanks.

[av_issue_android_media_player_logs.txt](https://github.com/user-attachments/files/16455446/av_issue_android_media_player_logs.txt)
[av_issue_opengles_logs.txt](https://github.com/user-attachments/files/16455447/av_issue_opengles_logs.txt)

**Comment by Chris-RH** [comment]
OK, thank you very much, that's interesting.
There were quite a few changes made in the upgrade to version 3.  One of which was migrating from Exoplayer  2.19.1 to Media3 1.1.0.
Out of interest, are you able to test Exoplayer (media3)'s [demo app](https://developer.android.com/media/media3/exoplayer/demo-application)?
I think that we might look into purchasing one of these devices for testing, however the dev team is on holiday, so it won't happen until the end of August at the earliest.

**Comment by pete-edwards** [comment]
Ah right ok. I'll try that demo when I get the chance. I think for now we'll hold off upgrading then until this is fixed as I'd rather stick with exoplayer. Thanks.

**Comment by Chris-RH** [comment]
Quick update. We are looking to purchase an Nvidia Shield Pro (2019) so that we can get a better idea of what is going on.

**Comment by MorrisRH** [comment]
The Tegra hardware is proving to be a bit problematic. I've fixed the issue that generates the unexpected runtime error. However the following issues are now present:
1. Vulkan rendering does not work - we're investigating but currently have no clues as to why it's not working
2. OpenGL ES3 with the texture format set to YCbCr420 OES flickers badly - again we're investigating but have no idea why the Tegra is behaving differently to other hardware

For now you will be able to playback using the OpenGL ES3 renderer with the media player's texture format set to BGRA.

This will make it into the next release and we'll keep this issue open whilst we figure out what's going on with the other problems.

**Comment by MorrisRH** [comment]
OpenGL ES3 OES texture issues have been fixed and will make it into the next release

**Comment by MorrisRH** [comment]
I've opened a new issue for Vulkan not working: #1990

**Comment by pete-edwards** [comment]
> OpenGL ES3 OES texture issues have been fixed and will make it into the next release

That's great thankyou. We'll keep an eye out for the next release

**Comment by Ste-RH** [comment]
That for letting us know @pete-edwards .  If you have 5 minutes free, it would really help us out if you could leave an honest review of the asset (and support) on the Unity Asset Store.  Thanks!
