### ISSUE TITLE
Trial watermark appears despite having purchased product (AVpro Video v3 - Core Mobile Edition)

### ISSUE THREAD

**Issue by Spamming-Spammer** [RenderHeads/UnityPlugin-AVProVideo#1954]
Problem description:

I have purchased AVpro VIideo v3 -Core Mobile Edition but when i play video it shows the avpro watermark on the video and when i add a new mediaplayer component it tells me to purchase the product, desipte alraedy having purchased it on the Unity Asset store and downloading it form the Unity Asset Store.

Device (which devices are you having the issue with - model, OS version number):

unity editor, have not tested builds

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

-non relevant to issue-

System Information:

AVPro Video: v3.0.8 (plugin v3.0.8f1-trial)
Target Platform: Android
Unity: v6000.0.12f1 WindowsEditor
OS: Desktop - 82BG (LENOVO) - Windows 11  (10.0.22631) 64bit - English
CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 8 threads - 16118KB
GPU: Intel(R) Iris(R) Xe Graphics - Intel - Direct3D 11.0 [level 11.1] - 8059KB - 16384

**Comment by Spamming-Spammer** [comment]
Not sure i consider it to be a github issue but the help and support seciton on the mediaplayer component told me to paste it here

**Comment by Chris-RH** [comment]
The Core and Ultra editions of AVPro Video have no watermarks for any platforms. If you use one of the platform bundle Core editions (eg AVPro Video v3 - Core Desktop Edition) then you will not see the watermark on the platform you purchased for, but you will see the watermark on the other platforms. For example if you purchased AVPro Video v3 - Core Mobile Edition then you will still see the watermark in the Unity editor as this is running on Windows/macOS, but the videos played back when you deploy to your Android/iOS/tvOS device will be watermark-free.
