### ISSUE TITLE
Media plays after application focus

### ISSUE THREAD

**Issue by NachiketJadhav** [RenderHeads/UnityPlugin-AVProVideo#1955]
Problem description:

When I open the iOS app after closing my alarm, all the media players start playing. (even if they are disabled). Using Mobile Core SDK version 3.0.8 

Device (which devices are you having the issue with - model, OS version number):

iPhone 11 version  17.5.1

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

15-20 videos with a 1920x1080 resolution.

System Information:

AVPro Video: v3.0.8 (plugin v3.0.8f1-trial)
Target Platform: Standalone
Unity: v2023.2.15f1 WindowsEditor
OS: Desktop - ROG Strix G512LI_G512LI (ASUSTeK COMPUTER INC.) - Windows 11  (10.0.22621) 64bit - English
CPU: Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz - 16 threads - 16169KB
GPU: NVIDIA GeForce GTX 1650 Ti - NVIDIA - Direct3D 11.0 [level 11.1] - 3962KB - 16384

**Comment by Chris-RH** [comment]
1. Is this reproducible in a new project, running only the AVPro Video demo scenes?
2. What iOS device/OS version are you using?

**Comment by MorrisRH** [comment]
Bug in the audio interruption handler causing playback to resume when it should remain paused. A fix will make it into the next release.

**Comment by Chris-RH** [comment]
AVPro Video version 3.1.3 has been released. Please let us know if it has not fixed your issue.
