### ISSUE TITLE
After playing the video, there are threads still running in the background with Android.

### ISSUE THREAD

**Issue by Yami1207** [RenderHeads/UnityPlugin-AVProVideo#196]
**Describe the bug**
After playing the video, there are threads still running in the background with Android.Through adb, this thread has a higher CPU ratio than the main thread.The function Dispose is called when the video object is destroyed, but the thread is still running. In short, the game cannot be closed while it is running.

**Your Setup (please complete the following information):**
 - Unity version: Unity2017.4.23f1
 - AVPro Video version: 1.10.0
 - Operating system version: Android 6.0.1
 - Device model: OPPO R9s
 - Video specs (resolution, frame-rate, codec, file size): NA

**To Reproduce**
1. Build an apk using AV Pro Video.
2. Run the game and play the video.
3. Using “adb shell top -m 5”

![图片](https://user-images.githubusercontent.com/56525140/66733197-5d083b80-ee91-11e9-95a5-bee931f086f7.png)

**Comment by nsmith1024** [comment]
Hello, i have this problem too, sometimes i exit the app but when i go back in the videos dont play unless i kill the app totally first.

**Comment by RenderHeadsSte** [comment]
What device/OS version do you see this on @nsmith1024 ?

**Comment by RenderHeadsSte** [comment]
We shall be closing this issue soon due to inactivity.
