### ISSUE TITLE
NotchLC Alpha Precision

### ISSUE THREAD

**Issue by Kalumo** [RenderHeads/UnityPlugin-AVProVideo#1961]
Problem description:

Loading up a video with NotchLC Codec and alpha channel displays unexpected results.
The video itself is simply a moving color shape with an alpha gradient.

Playing with the Media Player it appears that there are only 4 steps of alpha. Something like alpha = 1.0, 0.66, 0.33, 0.0.

The same video shows up fine with other video players.

Device (which devices are you having the issue with - model, OS version number):

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1 video, 1890 x 1620 px,  NotchLC, 60 fps

System Information:

AVPro Video: v2.3.1 (plugin v2.3.0f1-ultra)
Target Platform: Standalone
Unity: v2022.3.9f1 WindowsEditor
OS: Desktop - HP Z4 G4 Workstation (HP) - Windows 10  (10.0.19045) 64bit - German
CPU: Intel(R) Xeon(R) W-2225 CPU @ 4.10GHz - 8 threads - 130799KB
GPU: NVIDIA RTX A6000 - NVIDIA - Direct3D 11.0 [level 11.1] - 48571KB - 16384

**Comment by Chris-RH** [comment]
Hi, 

AVPro Video version 2 has been depreciated and will no longer be receiving any updates.  Please ensure that you are using the latest version (2.9.3) and retest.

**Comment by Kalumo** [comment]
After upgrading to 2.9 the issue still persists.

**Comment by Chris-RH** [comment]
Are you able to send us a sample of your test video please? unitysupport@renderheads.com

**Comment by Kalumo** [comment]
I sent a sample with the issue number in the subject.

**Comment by Chris-RH** [comment]
Hi, 

We've received the email, thank you.  
Our dev team is on annual leave for the duration of the month, so will have a chance to look at it when they get back.
Please note: AVPro Video version 2 has been depreciated and is no longer receiving any updates.  If there are any fixes, they will only be available in AVPro Video version 3.

**Comment by Kalumo** [comment]
Thank you for the message. Looking forward to hearing back.
If the issue is indeed a bug that has been fixed in version 3, please let us know.

**Comment by Ste-RH** [comment]
AVPro Video v3.0.10 has now been released.  Do let us know if this fixes the issue for you.

**Comment by Kalumo** [comment]
Thank you for your support. The issue is indeed fixed in 3.0.10.
