### ISSUE TITLE
Sound is not play 

### ISSUE THREAD

**Issue by arai-yuki** [RenderHeads/UnityPlugin-AVProVideo#1962]
Before I asked this question, I have tried to search online or going through existing issues. Yet I can't find any solution for this.

I am using the trial version of AVPro to verify if it can meet the requirements of our product. While the video plays, the audio does not. Is this due to limitations of the trial version, or is it because of file format or etc issues?

The used files are MP4 with H.264 video codec and AAC audio codec, as well as M3U8 files with the same codecs for HLS streaming.

In the Unity settings, I tried setting the Audio Output to both Unity and System Direct, but neither produced audio. When the Audio Output was set to Unity, I also added the Audio Output component, and placed both an Audio Source and an Audio Listener.

**Comment by Chris-RH** [comment]
What platform is this on?
What device is used for testing?
Have you tried putting it in a new project running the mediaplayer demo scene?
Are you able to provide a sample of the video you are having issues with?

**Comment by arai-yuki** [comment]
Sorry, I fogot the information about the runtime environment.
The Unity version is 2023.2.16f1 and the OS is Windows 10 and Windows11.
We are not assuming any other runtime environment.

To begin with, I had introduced it to an empty project and tested it, but only the audio did not play.
I was checking the volume in the State window while the video was playing, and it seemed to be going up and down around -16 dB, and when nothing was playing, it was at -80dB, so it seems like the sound might be working.

I'm soryy, but I am not allowed to release what I am currently testing to the outside world due to rights issues, so I will try another video at a later date.
If that doesn't work, I will upload the video used for the test.

**Comment by arai-yuki** [comment]
Sorry, I tried it on another computer and was able to play the sound.
It seems my computer was broken.
Thank you very much for your reply.

**Comment by Chris-RH** [comment]
I'm glad its working.  Thanks for letting us know :)
