### ISSUE TITLE
Play video stuck

### ISSUE THREAD

**Issue by MissDong** [RenderHeads/UnityPlugin-AVProVideo#1963]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
When I try to play a specific video, clicking the play button multiple times often causes it to get stuck. I click play every time after the video finishes.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.29f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): [UnityPlugin-AVProVideo-v3.0.8-Trial.unitypackage]
 - Operating system version: window10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 
          Duration:00:00:00.808000000
          ENCODER:Lavf60.16.100
    Stream 0
         Codec: Google/On2's VP9 Video (VP90)
        Type: Video
         Video resolution: 2560x1440
         Buffer dimensions: 2560x1440
         Frame rate: 30.000300
        Orientation: Top left
        Color primaries: ITU-R BT.709
        Color transfer function: ITU-R BT.709
    Stream 1
        Type: Audio
        Codec: Opus Audio (Opus)
        Sample rate: 48000 Hz
        Bits per sample: 16
**To Reproduce**
1. run unity
2. click play to play the video
3. when play complete, click play 
4. do 2-3 for few more times
5. stuck

**Logs**
  No logs
 
**Screenshots**
![image](https://github.com/user-attachments/assets/46e69195-2a65-4875-bdb1-fd6a5fdfea44)

https://github.com/user-attachments/assets/afc0d198-e193-473d-8953-41d029c9e79a

**Videos**
https://github.com/user-attachments/assets/afc0d198-e193-473d-8953-41d029c9e79a

Please forgive me for forgetting to attach the original video. Because the file is small, I did not send it via email.

https://github.com/user-attachments/assets/0d692df5-53d2-4c76-8fb8-2721037cdfa5

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
I'm not able to view your test video.  Can you send it to unitysupport@renderheads.com please

**Comment by MissDong** [comment]
> 我无法观看您的测试视频。您能将其发送至[unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)吗？

Hello, I have sent the video to your email.

**Comment by MissDong** [comment]
Hello, I have sent the video to your email.

**Comment by Chris-RH** [comment]
Hi, 

I think that the reason you are having issues is because you are using the Media Foundation API.  You can't use that with VP9 and have audio codecs.  More info [here.](https://renderheads.com/content/docs/AVProVideo-v3/articles/supportedmedia.html#video-codecs).  Try using the DirectShow API.
