### ISSUE TITLE
iOS - on older devices, FMOD audio stutters when resource load is high and video is opened

### ISSUE THREAD

**Issue by reuben-originatorkids** [RenderHeads/UnityPlugin-AVProVideo#1969]
**Describe the issue**
Our team has been using AVPro 2.9.* for a large amount of video content in our app. Recently, we have noticed that in certain situations, on somewhat older iOS devices (iPad 8 and lower), when playing multiple sounds (music, ambient, sfx, etc.) in FMOD and opening a video with AVPro at the same time, the audio will cut out or stutter. The weird thing is that this doesn't seem to happen on similarly low-resourced Android devices. Perhaps this is a quirk of the platform but we were wondering if others have seen similar interactions before. Thank you in advance for your help looking into this! Please let me know how I can assist with the process.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.14f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.9.3 core
 - Operating system version: iPadOS 16.7.1
 - Device model: iPad 6th Gen
 - Video specs (resolution, frame-rate, codec, file size): 1280x720, 30fps, H.264, 3.1MB (for example)

**To Reproduce**
Occurs when multiple FMOD sounds are playing and then a video is opened with AVPro.

**Videos**
https://github.com/user-attachments/assets/9dd5eeeb-27ac-4b9f-9517-91febee3580c

**Comment by Chris-RH** [comment]
Are you using Unity audio or System Direct?
How many audio sources are being played at the same time?
Are you able to provide any error logging?

It sounds like there aren't enough system resources to process all the audio.

**Comment by reuben-originatorkids** [comment]
Thanks for your response! Yes, I will retest with a trial version of AVPro Video 3. We're using System Direct audio. There are approximately 5 audio sources playing at the time of stuttering. We're not receiving any errors but I will continue profiling and share any relevant findings.

**Comment by MorrisRH** [comment]
If the video's audio needs to be resampled to match the sample rate set by Unity then that will put a strain on audio resources. Make sure your video's audio track's sample rate matches Unity's.
If you haven't configured it in the player settings then Unity's default of 24kHz will be being used so I would advise changing that to 44.1kHz or 48kHz.

**Comment by reuben-originatorkids** [comment]
Thank you, we will try this!
