### ISSUE TITLE
There is a memory leak on the Android platform

### ISSUE THREAD

**Issue by Yami1207** [RenderHeads/UnityPlugin-AVProVideo#197]
**Describe the bug**
Keep creating and destroying Android MediaPlayer objects, and memory is rising. By checking the code through jar, the MediaPlayer object is not actually destroyed, but is saved in the _renderFree. Need to call the function "RendererDestroyPlayers" to destroy MediaPlayer objects.

**Your Setup (please complete the following information):**
 - Unity version: Unity2017.4.23f1
 - AVPro Video version: 1.10.0
 - Operating system version: Android
 - Device model: Generic
 - Video specs (resolution, frame-rate, codec, file size): NA

**To Reproduce**
1. Build an apk using AV Pro Video.
2. Run the game and play the video.

**Comment by RenderHeadsSte** [comment]
Hmm, this is a strange one.  The path through to the function you refer to is via the Dispose function in AndroidMediaPlayer:

AndroidMediaPlayer.IssuePluginEvent( Native.AVPPluginEvent.PlayerDestroy, m_iPlayerIndex );

Dispose() is called from the MediaPlayer class inside OnDestroy():

m_Dispose.Dispose();

**Comment by Yami1207** [comment]
In the “Dispose” function, just call the "DestroyPlayer" function.
![1](https://user-images.githubusercontent.com/56525140/68171996-e7cfe800-ffb0-11e9-80f7-41657b8c81f7.png)

By checking the code through jar, the MediaPlayer object is not actually destroyed.
![2](https://user-images.githubusercontent.com/56525140/68172068-21a0ee80-ffb1-11e9-8bbc-b3e7c1ff3f50.png)

Need to call the function "RendererDestroyPlayers" to destroy MediaPlayer objects.
![3](https://user-images.githubusercontent.com/56525140/68172115-49905200-ffb1-11e9-82ae-a1589dc5dd55.png)

But AndroidMediaPlayer did not call "RendererDestroyPlayers”.
And I'm sorry to crack jar.

**Comment by RenderHeadsSte** [comment]
I have deleted your post due to the sensitive nature of what you included.  Please take this polite notice that we do not offer support when such actions are undertaken.

As I stated above, it is the issue plugin event that calls which in turn, indirectly, calls RendererDestroyPlayers().

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response.
