### ISSUE TITLE
Can't play on HarmonyOS

### ISSUE THREAD

**Issue by Slpekamer** [RenderHeads/UnityPlugin-AVProVideo#1970]
- Unity version: 2022.3.21f1
- AVProVideov3-UltraEdition[3.0.1]
- Operating system version: Harmony 4.2.0
- Device model: Huawei p30 Huawei p40
- Video specs: demo video RenderHeads-1080p30-H264

I used two Huawei phones, Huawei p30 and Huaweip 40, running HarmonyOS. AvproVideo does not work on this, any video can not be played, you can see the time after running time bar, but the black screen can not play, I wonder if the plugin is not supported for HarmonyOS. It works fine on other Android phones, including Samsung and XiaoMi.

**Comment by Chris-RH** [comment]
Hi, We don't support HarmonyOS
