### ISSUE TITLE
Android- hls video playing but there's only black screen and dash files are not playing/loading at all.

### ISSUE THREAD

**Issue by MJcheonma** [RenderHeads/UnityPlugin-AVProVideo#1971]
So I am experiencing two issues currently when i use android mediaplayer as the video api,

1. When I play a hls file, only a black screen is visible i.e., my video is playing as I can hear the audio and interestingly, this is only happening in older devices. In newer devices, videos are playing perfectly fine and are visible.
2. My dash file is not playing. It is giving an error "[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources."

Note:- The url is working when i play it in browser or using exoplayer video api but using it gives another issue that is the mediaplayer is not loading no matter what file format i use (dash/hls) in older devices or devices with mediatek processor i assume as It is working completely fine in samsung devices which has snapdragon processors. This is what i assume thats why i shifted from exoplayer to android media player.

**My Setup**
 - Unity version: 2022.3.40f
 - AVPro Video v3.0.8 trial version 
 - Operating system version: Android 13 (both)
 - Device model: Samsung s20fe 5g and Samsung M32 prime
 - Video specs: streaming- dash and hls; res- 50mb, 200mb, 700mb

**My Project Settings**
 - Android sdk 33 (compile sdk 33)
 - Android ndk 23.1.7
 - Android jdk 11
 - Color space: Linear
 - Graphics API: OpenGLES 3
 - Min API lvl: 26
 - Target API lvl: 33
 - Scripting backend: IL2CPP

**To Reproduce**
1. You may try using this url in the demo scene "https://viewcon360.s3.eu-north-1.amazonaws.com/TestVideo200MB.mpd" with the settings above.

**Logs**
I am attaching two logcat files for android mediaplayer, one is from the older device and the other one is from the newer device and one logcat file for exoplayer.

[android media player mlogcat_dev build_older device.txt](https://github.com/user-attachments/files/16641961/android.media.player.mlogcat_dev.build_older.device.txt)
[android media player mlogcat_dev build_newer device.txt](https://github.com/user-attachments/files/16641962/android.media.player.mlogcat_dev.build_newer.device.txt)
[exoplayer_release build_older device.txt](https://github.com/user-attachments/files/16642108/exoplayer_release.build_older.device.txt)

**AVpro mediaplayer settings**
![Screenshot 2024-08-17 030140](https://github.com/user-attachments/assets/f68eeb3a-de39-4467-8210-335ad3dbd7c2)

I am sending the project file url as well to the email address.

**Comment by Chris-RH** [comment]
Dash format is only supported in Exoplayer

1. What devices have you tested? Which work and which don't work?
2. What is the URL for your HLS stream?
3. Which resolution/codecs/FPS/bitrate are your streams using?
4. Can you reproduce this in a new project running only the AVPro Vide mediaplayer demo scene and your streams please and then please can you provide full, unfiltered logcat from the moment you app opens until after you have started playing the stream.

**Comment by MJcheonma** [comment]
> Dash format is only supported in Exoplayer
> 
> 1. What devices have you tested? Which work and which don't work?
> 2. What is the URL for your HLS stream?
> 3. Which resolution/codecs/FPS/bitrate are your streams using?
> 4. Can you reproduce this in a new project running only the AVPro Vide mediaplayer demo scene and your streams please and then please can you provide full, unfiltered logcat from the moment you app opens until after you have started playing the stream.

1. I have tested on multiple android devices which are android 13. In newer devices the hls videos are working but dash wont, in older devices hls videos are playing as i can hear the audio but its a black screen and dash videos dont play at all.

2. https://viewcon360.s3.eu-north-1.amazonaws.com/output/Startraum.m3u8 - hls video link, Opening https://viewcon360.s3.eu-north-1.amazonaws.com/TestVideo200MB.mpd - dash video link

3. 
![dash video info](https://github.com/user-attachments/assets/b6366219-ca13-4d74-a150-53df83bab805)
![hls video info](https://github.com/user-attachments/assets/d3c36592-57b0-4693-ad99-226b68ce6ced)

4. In this sample scene, i have set a start courotine that plays the hls video and after about 20seconds, the dash video should start
[demoscene android mediaplayer mlogcat_older device.txt](https://github.com/user-attachments/files/16645501/demoscene.android.mediaplayer.mlogcat_older.device.txt)
[demoscene android mediaplayer mlogcat_newer device.txt](https://github.com/user-attachments/files/16645505/demoscene.android.mediaplayer.mlogcat_newer.device.txt)


I have emailed you the new project file link as well.

**Comment by MJcheonma** [comment]
Thanks for replying! Alright then I want to set aside the exoplayer for now and check the issue with the android media player. I'll be generating a new issue for the exoplayer i think.

1. I have tested on multiple android devices which are android 13. In newer devices the hls videos are working, in older devices hls videos are playing as I can hear the audio but it's a black screen.
My current testing models are Samsung s20fe 5g and Samsung M32 prime.

3. https://viewcon360.s3.eu-north-1.amazonaws.com/output/Startraum.m3u8 - hls video link

4.  https://github.com/user-attachments/assets/d3c36592-57b0-4693-ad99-226b68ce6ced

5. https://github.com/user-attachments/files/16645572/demoscene.android.mediaplayer.mlogcat_older.device.txt
https://github.com/user-attachments/files/16645573/demoscene.android.mediaplayer.mlogcat_newer.device.txt


Here's the demo scene project link- https://drive.google.com/drive/folders/1fqSI5XPIlDC3PadVsN9XoiKp8jhxtv0S?usp=sharing

Screenshots of the older device and newer device.
https://github.com/user-attachments/assets/6463f733-59ac-4cc1-a793-36d56d5fbb88
https://github.com/user-attachments/assets/f7d55d6d-84ed-4979-aaf9-16e7c5c53415

Thanks & Regards,
Mudit Jain
(- Multiversal Alchemist)<http://beacons.ai/mjcheonma>

________________________________

**Comment by Chris-RH** [comment]
The [Samsung Galaxy M32](https://www.gsmarena.com/samsung_galaxy_m32-10887.php) has a [Mediatek MT6769V/CU Helio G80](https://www.mediatek.com/products/smartphones-2/mediatek-helio-g80)  chipset, which has a maximum display resolution of 2520x1080.  Your HLS only has a single stream of 4320x2160.  Encode your HLS so that it has streams of lower resolutions so that they fit within the phone's capability.

**Comment by Chris-RH** [comment]
Have you had any luck with that?

**Comment by MJcheonma** [comment]
Yes that resolved my issue. I had totally ignored that part of adaptive streaming. Thanks!!
