### ISSUE TITLE
Video not rendering when using Polyspatial

### ISSUE THREAD

**Issue by manojahujaTess** [RenderHeads/UnityPlugin-AVProVideo#1974]
**Describe the issue**

I am getting white display when I have selected Y Cb Cr 420_OES Texture format and Pink (Missing) texture when I have selected BGRA Texture format. I can hear the audio though. The video is playing in the Unity editor. Also, the same settings work on Quest3. I have added the workaround from #1800 issue which sets the render texture dirty.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.31f1
 - AVPro Video version: Latest Trial version
 - Operating system version: macOS Sonoma 14.4 M3
 - Polyspatial version: 1.3.1
 - Apple VisionOS XR Plugin version: 1.3.1
 - Device model: Vision Pro

@Chris-RH  Please let me know if you need any screenshots and/or project files. Thanks in advance.

**Comment by Chris-RH** [comment]
Are you able to provide a **minimal** project that reproduces the issue please.  Send to unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Are you able to provide a minimal project that reproduces the issue please. Send to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by Chris-RH** [comment]
closed due to lack of reply
