### ISSUE TITLE
Could you please provide the PDB file so that the stack can be restored in case of a crash?

### ISSUE THREAD

**Issue by buoutuanzi** [RenderHeads/UnityPlugin-AVProVideo#1975]
Could you please provide the PDB file so that the stack can be restored in case of a crash? We have brought the core edition

**Comment by Chris-RH** [comment]
The method it crashed under should show in the stack and any system level APIs should also show so I can’t see how it would be that useful.

**Comment by buoutuanzi** [comment]
> The method it crashed under should show in the stack and any system level APIs should also show so I can’t see how it would be that useful.

When I see the keyword "exoplayer" in the crash stack trace, for example, I know to try modifying the video API instead of testing all the configuration options one by one.

**Comment by Chris-RH** [comment]
That level of debugging is usually something done by ourselves.  Saying that, we are looking at improving our error handling. 
If you are having an issue then we usually suggest testing in a new project running only AVPro Video to see if the issue is still occurring.
