### ISSUE TITLE
AVpro 3.0.8 can not support below android 8.0

### ISSUE THREAD

**Issue by wishes2018** [RenderHeads/UnityPlugin-AVProVideo#1978]
**Describe the issue**
AVpro 3.0.8 can not support below android 8.0, ANativeWindow_toSurface Available since API level 26.

**Logs**
AndroidJavaException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ANativeWindow_toSurface" referenced by "/data/app/com.miner.and.pd-1/lib/arm64/libAVProVideo2Native.so"...

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "ANativeWindow_toSurface" referenced by "/data/app/com.miner.and.pd-1/lib/arm64/libAVProVideo2Native.so"...
java.lang.Runtime.loadLibrary(Runtime.java:372)
java.lang.System.loadLibrary(System.java:1076)
com.renderheads.AVPro.Video.Manager.<clinit>(SourceFile)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source)
com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:158)
com.unity3d.player.UnityPlayer$F.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.NewObject (System.IntPtr clazz, System.IntPtr methodID, System.Span`1[T] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._AndroidJavaObject (System.IntPtr constructorID, System.Object[] args) (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.PlatformMediaPlayer+Native.AVPPluginBootstrap () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.PlatformMediaPlayer..cctor () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer (RenderHeads.Media.AVProVideo.MediaPlayer+OptionsAndroid options) (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at <00000000000000000000000000000000>:0)
Rethrow as TypeInitializationException: The type initializer for 'RenderHeads.Media.AVProVideo.PlatformMediaPlayer' threw an exception.
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer (RenderHeads.Media.AVProVideo.MediaPlayer+OptionsAndroid options) (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at <00000000000000000000000000000000>:0)

**Comment by WeiLingQiang** [comment]
> I'm afraid that Android 8.0 (Oreo, API 26) is the lowest Android version we support with version 3 of AVPro Video.

If the v3 version does not support Android 6, can a version that supports 16kb alignment be released in the v2 version?
