### ISSUE TITLE
Is AVPro has ability to change brightness and contrast settings?

### ISSUE THREAD

**Issue by Anton111111** [RenderHeads/UnityPlugin-AVProVideo#1984]
I use ApplyToMesh. I wonder is AVPro has ability to change color settings like brightness and contrast?

**Comment by Chris-RH** [comment]
The closest that we have is our[ resolve to render texture component](https://renderheads.com/content/docs/AVProVideo-v3/articles/component-resolve-to-rendertexture.html).

**Comment by Anton111111** [comment]
> The closest that we have is our[ resolve to render texture component](https://renderheads.com/content/docs/AVProVideo-v3/articles/component-resolve-to-rendertexture.html).

Thanks! Is it has example how to use it for stereo video ?

**Comment by Anton111111** [comment]
> The closest that we have is our[ resolve to render texture component](https://renderheads.com/content/docs/AVProVideo-v3/articles/component-resolve-to-rendertexture.html).

Please, skip my previous question. I've found how to use it. Will test it for performance. Can you say is size of render texture affect performance? I think how to use it because i will play video with different resolutions and need understand is enough to create one texture with biggest size o video or not.

**Comment by Anton111111** [comment]
Looks like i've found better solution ;) i just added call ApplyHSBEffect to shader that i use (InsideSphere Unlit Transparent (stereo+color+alpha) - Android OES ONLY). And it works. Will use it. 
just information for those who will look for the same opportunity.
