### ISSUE TITLE
Shader Settings for Playing AlphaClip Videos on VisionOS with AVPro Video

### ISSUE THREAD

**Issue by pkaichi** [RenderHeads/UnityPlugin-AVProVideo#1986]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: Unity2022.3.44f1
 - AVPro Video version (AVPro Video v3.0.8  trial): 
 - Operating system version:  VisionOS 1.3
 - Device model: AppleVisionPro
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
I am using the Trial version of AVPro Video v3.0.8 - 24 July 2024.

I would like to play a video with alpha clipping on VisionOS.
I have prepared an mp4 with AlphaPacking set to Left Right.
In the Unity Editor’s Inspector preview, I was able to see the alpha-clipped video.
However, when I apply the video to a mesh using ApplyToMesh in the scene, the video does not play.
In this situation, which shader should I use to play the video correctly?**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Are you using polyspatial?
Have you tried using the resolvetorendertexture component and directing a rendertexture to the material instead of applytomesh?

**Comment by Chris-RH** [comment]
closed due to lack of reply
