### ISSUE TITLE
Active MediaPlayer is paused when another MediaPlayer begins playing

### ISSUE THREAD

**Issue by tejasXR** [RenderHeads/UnityPlugin-AVProVideo#1987]
**Describe the issue**
When two MediaPlayers are active in a scene and both are set to AutoPlay and AutoOpen, only one of them will start playing. Furthermore, when MediaPlayer 'A' is playing and a second/alternate MediaPlayer  'B' starts playback, MediaPlayer A will pause playback.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.40f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core Edition 3.09
 - Operating system version: SQ3A.220605.009.A1
 - Device model: MetaQuest 3
 - Video specs (resolution, frame-rate, codec, file size): 1080p, 60fps, using AVPro 'Cones' and 'RenderHeaders' sample files

**To Reproduce**
1. Open the `Demo_MediaPlayer` scene
2. Create another media player canvas with a separate media reference. I'm using the `Sample-Local-MP4-RenderHeads` media reference for one player and the `Sample-Local-MP4-Cones` media reference for the other media player.
3. Set both media players to `AutoPlay` and `AutoOpen`
4. Deploy the scene on a Quest 3 device
5. Only one media player will start, while the other will only show its first frame

**Logs**
No error, info, or warning logs appear.

**Images**
![image](https://github.com/user-attachments/assets/ea472662-62e0-45cc-b7bb-51615ec32c60)

**Videos**
https://github.com/user-attachments/assets/cf3f113b-0d5a-49de-866c-e7bb9fa02187

**Temporary Workaround**
I found that using the native Media Player video API instead of the default Exo Player temporarily solves this issue

**Comment by Ste-RH** [comment]
The MediaPlayer Demo UI was never designed to be duplicated, though I don't see a reason it could not be.  Have you re-targeted all the components that have a reference to a MediaPlayer inside the UI structure?

I am struggling to reproduce it here.  If you can package up your project and send it over to unitysupport@renderheads.com with the subject '#1987' then I can take a look for you.

**Comment by tejasXR** [comment]
Hey there, I'm sorry I haven't been able to package up an isolated project with this issue. Let me get to it early next week when I'm back at my desk.

**Comment by Ste-RH** [comment]
Bump on this @tejasXR .  Have you managed to get some free time to put together an isolated example project?

**Comment by Chris-RH** [comment]
any luck @tejasXR ?
