### ISSUE TITLE
Unity6 new a empty android project, just import avprovideo， not done Build

### ISSUE THREAD

**Issue by HotYearKit** [RenderHeads/UnityPlugin-AVProVideo#1988]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: Unity 6000.0.18f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.9
 - Operating system version: win11 23H2
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. new android project
2. in avprovideo 
3. build

**Logs**
* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-31.1-android (guava-31.1-android.jar) and jetified-listenablefuture-1.0 (com.google.guava:listenablefuture:1.0)
     
     Go to the documentation to learn how to Fix dependency resolution errors.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 22s

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by Chris-RH** [comment]
Hi, 

It sounds like something else in your project is using a different guava library to the one that Exoplayer uses.   Are you using Firebase perhaps?  
Its not an AVPro specific issue. 

Here are some solutions that you can try:
https://github.com/firebase/firebase-android-sdk/issues/1320
https://github.com/firebase/firebase-android-sdk/issues/1575
https://stackoverflow.com/questions/56639529/duplicate-class-com-google-common-util-concurrent-listenablefuture-found-in-modu
https://gist.github.com/caseykulm/8f229ef3d89dec02780ea880129bc75d

but in your case you will need to change it to jetified-guava-31.1-android

**Comment by Ste-RH** [comment]
Also see here: https://www.renderheads.com/content/docs/AVProVideo-v3/articles/platform-android.html#unity-20230-and-above

**Comment by HotYearKit** [comment]
The project is a new empty project ,just avprovideo.

**Comment by HotYearKit** [comment]
> Also see here: https://www.renderheads.com/content/docs/AVProVideo-v3/articles/platform-android.html#unity-20230-and-above
This is right
