### ISSUE TITLE
Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources with DASH video play

### ISSUE THREAD

**Issue by dorcatty** [RenderHeads/UnityPlugin-AVProVideo#1989]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Dear AVPro Support,

I am going to play build an Meta Quest VR app with 360 video streaming from HTTP server. 
I followed with documentation on [Encoding Notes | AVPro Video - Documentation](https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html), to encode my 360 videos with HEVC, then segmented with Shaka Packager,
the output was few mp4 with different resolutions and a mpd file,

the mpd can be easily load by any Dash Players, but when i tried with Path input with MediaPlayer of AVPro, i got error about:

[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.25f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.9 trial
 - Operating system version: MacOS 14.16.1
 - Device model: Meta Quest Pro
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
Using Path to direct the MediaPlayer to .mpd file, once played in Unity Editor, then having this issue.
https://d1hv4xiuf35r8p.cloudfront.net/testpackager/sample-manifest-full.mpd

**Screenshots**
<img width="465" alt="Screenshot 2024-09-05 at 23 02 52" src="https://github.com/user-attachments/assets/4f7542f4-cf8d-4968-ada2-3d277ea8220d">
<img width="284" alt="Screenshot 2024-09-05 at 23 02 20" src="https://github.com/user-attachments/assets/d7ff3c08-0bbd-4db8-8737-e41084ba3a82">

thanks a lot for help.

**Comment by Chris-RH** [comment]
Did you original HEVC file play on the Quest Pro, before you turned it into a dash stream?
Are you able to provide a full, unfiltered logcat please in txt format.

**Comment by dorcatty** [comment]
now, my issue is in Unity Editor, mp4 with HEVC can be played within Editor, but not yet test on Meta Quest. 
if i give .mp4 with URL, then it works with Unity Editor. 
only mpd having some issue within Editor, so there's no logcat debug info yet. 

did you mean, i can see streaming in the Quest, not the editor ?

**Comment by Chris-RH** [comment]
Dash isn't supported on macOS.  Documentation [here.](https://renderheads.com/content/docs/AVProVideo-v3/articles/feature-streaming.html)

**Comment by dorcatty** [comment]
OK, good to know, at meantime i found that link as well. 
 i will do another test:
run directly in Quest to see if mpd DASH was Ok or not. 
load HLS streaming within Quest and MacOS...

Thanks for the help at the moment. i will back to you soon in 48h.

**Comment by Ste-RH** [comment]
Anything to report @dorcatty ?

**Comment by dorcatty** [comment]
it works on Meta Quest, but not on MacOS. interesting.  as you said, DASH play back isn't supported on MacOS. only on Android (Quest).
