### ISSUE TITLE
Need VP8 Codec on iOS

### ISSUE THREAD

**Issue by redccoma** [RenderHeads/UnityPlugin-AVProVideo#199]
** Is the feature request related to the issue? explain it to me please. **
We need an implementation of webm on iOS.

** Description of Alternative Considered **
To use webm (vp8) on iOS,  Unity VideoPlayer and RenderTexture provided by Unity, but performance is poor.

**Comment by TravisC1** [comment]
I'm also interested in webm support on iOS devices. Is this something that might ever be supported by AVPro? Or is it an Apple/iOS issue to solve?

**Comment by AndrewRH** [comment]
Can I ask why the interest in webm/vp8/vp9?

**Comment by TravisC1** [comment]
@AndrewRH I'm mostly interested in it for the alpha channel support. Though I've just discovered that Safari on iOS doesn't support them either and I need a solution that works across Unity iOS/Android and the web so maybe this isn't actually going to be something we can use even if put in place. Transparent video is such a pain.

**Comment by AndrewRH** [comment]
I see!  Yes, transparency is something that isn't widely supported in codecs.  The best option for comparability is to use alpha packing.  This should be supported on all platforms.

**Comment by MorrisRH** [comment]
Unless Apple provide hardware support for decoding in the future we will not be providing support for the VP8 codec.
