### ISSUE TITLE
How to use Resolve To RenderTexture component correctly?

### ISSUE THREAD

**Issue by Anton111111** [RenderHeads/UnityPlugin-AVProVideo#1991]
I'm trying switch my project from Apply To Mesh to Resolve To RenderTexture component. 
What i've done:
1) Disable current  Apply To Mesh and added Resolve To RenderTexture.
2) Set aspect ratio fit inside in Resolve To RenderTexture.
3) I use in my sphere material with AVProVideo/VR/InsideSphere Unlit Transparent (stereo+color+alpha) - Android OES ONLY shader. I keep it without changes
4) In script that manage my video player i add code that set texture from _resolveToRenderTexture to sphere material:
`Material.SetTexture("_MainTex", _resolveToRenderTexture.TargetTexture);`

In result in quest2 headset it starts play video but the video is upside down and it seems to ignore the stereo packing settings because it shows the whole frame instead of half.  

If i change shader to AVProVideo/VR/InsideSphere Unlit Transparent (stereo+color+fog+alpha) (without OES) it play video but video doesn't look like stereo.

Also with Apply To Mesh i used the following code snippets to change stereo packing and video mapping:
`_mediaPlayer.VideoLayoutMapping = videoMapping;`
```
MediaHints hints = _mediaPlayer.FallbackMediaHints;
        hints.stereoPacking = stereoPacking;
        _mediaPlayer.FallbackMediaHints = hints;
```

But when i moved to Resolve To RenderTexture component these snippets stops working.

What's i do wrong and how to use Resolve To RenderTexture component in right way?

**Comment by MorrisRH** [comment]
The ResolveToRenderTexture component will decouple the MediaPlayer from the inside sphere shader so you'll need to make sure the material on your sphere is configured correctly for stereo rendering as this information will not be provided by the component.

Not sure what you're trying to achieve by using resolve to RT so if you can provide any extra information we may be able to help further.

**Comment by Anton111111** [comment]
@MorrisRH , I use Apply to Mesh and it works good. But i want add ability to change brightness/contrast and etc. 
Can you write some example how to correct configure material for stereo rendering ?

**Comment by Anton111111** [comment]
Looks like i've found better solution ;) i just added call ApplyHSBEffect to shader that i use (InsideSphere Unlit Transparent (stereo+color+alpha) - Android OES ONLY). And it works. Will use it.
