### ISSUE TITLE
Unity 6, The second build on Android doesn't work.

### ISSUE THREAD

**Issue by NK-Studio** [RenderHeads/UnityPlugin-AVProVideo#1993]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
The build fails from the second Build And Run onwards due to the code that adds `android.useFullClasspathForDexingTransform=true` in AVPro's PostProcessBuild_Android.

**Your Setup (please complete the following information):**
 - Unity version: Unity 6000.0.17
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.10 ultra
 - Operating system version: Android
 - Device model: Samsung S23
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Create a new project in Unity and switch to the Android platform.
2. Add the AVPro plugin and set it up to play any video.
3. Nothing happens in the first build and it builds successfully. However, from the second build onwards, a build error occurs.

**Logs**
```
ArgumentException: An item with the same key has already been added. Key: android.useFullClasspathForDexingTransform
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <c040dc59dcbc4ddb95ffc99a02c8bae9>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <c040dc59dcbc4ddb95ffc99a02c8bae9>:0)
System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <8605c4e4a5e4419e8e3ba1e785381860>:0)
System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) (at <8605c4e4a5e4419e8e3ba1e785381860>:0)
Vuforia.EditorClasses.GradlePropertiesParser.FromString (System.String content) (at <b158c357818c4550aba0522d3ecf6a73>:0)
Vuforia.EditorClasses.GradlePropertiesParser.FromFile (System.String path) (at <b158c357818c4550aba0522d3ecf6a73>:0)
Vuforia.EditorClasses.PostProcessAndroidBuild.ParseGradleProperties (System.String projectPath) (at <b158c357818c4550aba0522d3ecf6a73>:0)
Vuforia.EditorClasses.PostProcessAndroidBuild.OnPostGenerateGradleAndroidProject (System.String path) (at <b158c357818c4550aba0522d3ecf6a73>:0)
UnityEditor.Android.PostProcessor.Tasks.ProcessGenerateProjectCallbacks.OnGeneratePlatformProjectPostprocess (System.String path, System.Boolean strict) (at <1dc12b2a92b34abebd4d0337636ff85f>:0)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler() (at /Users/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:520)
```

**Screenshots**
<img width="802" alt="image" src="https://github.com/user-attachments/assets/dcd0292b-2bdc-4e4c-8ced-97f3530a9c77">
<img width="1565" alt="image" src="https://github.com/user-attachments/assets/23801921-765d-48aa-a669-2b7697fc0259">

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
Hmm. That’s very odd. That code checks if that line exists and does not add it…then adds it at the end. Can’t think of how it would end up in there twice.

There will be a gradle.build file in the staging folder (you can debug that script and get the exact path). Can you hunt that out and send it over? (After you have made the first build)

**Comment by NK-Studio** [comment]
The problem where `android.useFullClasspathForDexingTransform` was applied twice was resolved after modifying the code as follows.
I'm wondering if there was any omission in writing the code like this by mistake.
<img width="1524" alt="image" src="https://github.com/user-attachments/assets/12617cf2-60d3-4305-b2bd-87c81d4f1f70">

**Comment by Ste-RH** [comment]
@NK-Studio I think this is the change you want to make to that file.

![image](https://github.com/user-attachments/assets/267fa203-11c6-44c1-b411-2c1b09654ba2)

Do let us know if this change fixes things for you and we will action the change into the next/future releases.

**Comment by Ste-RH** [comment]
@NK-Studio Yes, that looks about right.  We will action a change to that effect for the next release.  Thanks for pointing out the issue!

**Comment by Chris-RH** [comment]
AVPro Video version 3.0.11 has been released.  Please let us know if it has not fixed your issue.

**Comment by Ste-RH** [comment]
That for closing the issue @NK-Studio .  If you have 5 minutes free, it would really help us out if you could leave an honest review of the asset (and support) on the Unity Asset Store.  Thanks!
