### ISSUE TITLE
[Android] No playback when using Android emulator

### ISSUE THREAD

**Issue by alltry1014** [RenderHeads/UnityPlugin-AVProVideo#1994]
Dear AVProVideo Support,
The plugin behaves very bad on the simulator.There are some logs for you.

Logs:
[lightning_simulator_error_log.txt](https://github.com/user-attachments/files/16915133/lightning_simulator_error_log.txt)
[mumu_simulator_crash_log.txt](https://github.com/user-attachments/files/16915134/mumu_simulator_crash_log.txt)

Screenshots:
![20240907-141326](https://github.com/user-attachments/assets/4d671bb4-733f-4207-9072-3ba7b9cd471d)
![img_v3_02ee_14c6e0ee-f770-4c6c-afa4-f80f38031b2g](https://github.com/user-attachments/assets/6357b53d-3bbb-420a-9f3a-274a4507a498)

These two simulators with download link:
![3fa0f9f2-0e8c-4b15-9119-747102c1d6fe](https://github.com/user-attachments/assets/867fbebd-78e8-453e-9936-5e27e679fcce)
lightning_simulator: https://www.ldmnq.com/
mumu_simulator: https://mumu.163.com/

My Setup:
 - Unity version: 2022.3.20f1
 - AVPro Video version: v3.08 Core Edition 
 - Operating system version: Andriod 12
 - Device model: Andriod Simulator
 - Video specs (resolution, frame-rate, codec, file size): 
   - resolution: 1440 * 2476
   - frame-rate: 60fps
   - codec: H.264
   - file size: 13.8 MB
   - average bitrate: 3309kbps

Please reply as soon as possible, thanks.

**Comment by Chris-RH** [comment]
Unity doesn't support android simulators.  In the [Unity manual under system requirements](https://docs.unity3d.com/2021.3/Documentation/Manual/system-requirements.html), it states "Hardware must be running Android OS natively. With the exception of Android for Chrome OS, Android within a container or emulator isn’t supported."

**Comment by alltry1014** [comment]
I try my best to use the AVProVideo Plugin well. So Confused,  I have used CRIWARE Plugin before.That can play well in andriod emulator.Is there any other solution?Thanks.

**Comment by alltry1014** [comment]
In China, there are still some players who use  andriod emulator.Can you support the plugin play on andriod emulator?Thanks.

**Comment by MorrisRH** [comment]
I'm currently investigating issues with the Google Android simulator so hopefully fixing that will resolve the issues you're seeing with these other emulators.

**Comment by alltry1014** [comment]
When will it be resolved? We recently had an online test.Thanks.

**Comment by alltry1014** [comment]
By the way, the old vesrion v2.9.3 play well on the android emulators.

**Comment by MorrisRH** [comment]
The issues with running under the Google Android emulator have been resolved and will make it into the next release. Hopefully this will fix the issues seen in other Android emulators.

The OES texture fast path does not appear to work under the emulator so is disabled for the Google Android emulator, however this does require detection of an emulated OpenGLES renderer which may not be possible with other emulators.

**Comment by alltry1014** [comment]
Dear MorrisRH, thank you very much!

**Comment by Ste-RH** [comment]
@alltry1014 AVPro Video v3.0.11 has now been released. Do let us know if this fixes the issue for you.

**Comment by alltry1014** [comment]
The plugin only play well on lightning simulator.There are some logs for you.
[lightning_simulator_log2.txt](https://github.com/user-attachments/files/16987773/lightning_simulator_log2.txt)
[mumu_simulator_crash_log2.txt](https://github.com/user-attachments/files/16987775/mumu_simulator_crash_log2.txt)

**Comment by alltry1014** [comment]
How about this issue? Thanks.

**Comment by MorrisRH** [comment]
Hey @alltry1014 
As we have no way to determine if the plugin is running on actual hardware or on emulated hardware we have to prioritise supporting the actual hardware. You say the plugin works fine on the lightning emulator which would suggest the issue lies with the mumu emulator.

**Comment by alltry1014** [comment]
Dear AVProVideo Support,  the old vesrion v2.9.3 can play well on the mumu emulator. I think the issue may not be with the mumu emulator.
