### ISSUE TITLE
Video files cannot be played on Android 12

### ISSUE THREAD

**Issue by chengnay** [RenderHeads/UnityPlugin-AVProVideo#1995]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Recently system upgrades from Android 10 to Android 12, some of the video files cannot be played.
Mostly are 5.1 channel AAC format.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.30f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 2.7.3
 - Operating system version: Android 12
 - Device model: Meta Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 24FPS, AVC, 312MB

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.
09-10 14:05:35.384  5421  5450 I Unity   : [AVProVideo] Opening /storage/emulated/0/Download/5.1ch_aac/wonder_woman_2017_tlr3-DWEU_aac.mp4 (offset 0) with API ExoPlayer
09-10 14:05:36.349  5421  5450 E Unity   : [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
https://www.dropbox.com/scl/fi/vxqgdnhlofleweykidvh6/Kong_Skull_Island_TLR-1_1080p_A_51-thedigitaltheater_aac.mp4?rlkey=zmjo54mgmqudgbetktoj4besb&st=ydqbsr2m&dl=0
https://www.dropbox.com/scl/fi/i268733jzqwhuzthcmaq6/wonder_woman_2017_tlr3-DWEU_aac.mp4?rlkey=hgk6aslbbwjdtk2523jg8w7cg&st=id5pjd12&dl=0
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi @chengnay 

AVPro Video version 2 has been depreciated and will no longer be receiving updates.  I suggest that you upgrade to the last version, 2.9.3, and retest using a new project and the AVPro Video mediapayer demo scene.

AVPro Video version 3 is available to you via a [discounted upgrade path](https://renderheads.com/content/docs/AVProVideo-v3/articles/download.html#upgrade-pricing).  You can test the free, fully featured, [watermarked trial version](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases) to see if you get better results on your device.  If not, then we can look at putting in a fix.

Was it just an upgrade in Android version on your Quest 2 or have you also upgraded Meta's own software?  Which version are you using at the moment?

**Comment by chengnay** [comment]
Hi @Chris-RH,
I will try upgrade to 2.9.3.
If the issue still existed, I will check out version 3 too.
Current version is 68.0.0.567.364.630582898.
I just tested with Quest 2's built-in file viewer which also cannot play the video file.

**Comment by Chris-RH** [comment]
For clarification, did these particular videos work beforehand?
It looks like the audio format is not supported.

**Comment by chengnay** [comment]
Hi @Chris-RH,
Yes, it was working on Android 10.

**Comment by Chris-RH** [comment]
What was the previous version that you upgraded from?

**Comment by chengnay** [comment]
I couldn't remember, but I tested on VIVE XR Elite which was running with Android 10.
The video files can play without any issue.
