### ISSUE TITLE
Display uGUI renderer glitches out on loading videos   

### ISSUE THREAD

**Issue by VarunLila** [RenderHeads/UnityPlugin-AVProVideo#1996]
Loading a specific video causes Media Player to render out a glitched screen

 - Unity version: 2022.3.18f1
 - AVPro Video version 3.0.9/Trial: 
 - Operating system version: Works on Windows/In-Editor, this bug happens on Android.
 - Device model: IQOO Neo 6
 - Video specs (resolution, frame rate, codec, file size):  1920 X 1080, 23.97 FPS, 20 MBs file size, codec: .h265 

**To Reproduce**
I'm trying to load a video onto a secondary media player as another plays in the primary media player.
1. As soon as the secondary video gives me the FirstFrameReady event, I switch out the referenced media player onto a Display uGUI component.
2. Switching to this secondary video player causes the Media Player or Display uGUI to glitch out

**Screenshots**
![image](https://github.com/user-attachments/assets/de45eb92-efa2-4b28-8921-04f52b946ac7)

**Comment by VarunLila** [comment]
> @VarunLila Can you try updating to v3.0.10? We fixed an issue where FirstFrameReady might have fired a early in certain circumstances in the latest release.

I will try and let you know

**Comment by MorrisRH** [comment]
I think this issue is related to #1827 which has now been fixed.
Unable to reproduce in version 3.0.11 which will be release shortly.

**Comment by Ste-RH** [comment]
@VarunLila AVPro Video v3.0.11 has now been released. Do let us know if this fixes the issue for you.

**Comment by VarunLila** [comment]
Thanks for the updates folks. I will try out v3.0.11 when I can.
