### ISSUE TITLE
Expose API Method to change min buffer size

### ISSUE THREAD

**Issue by jpienbroapollojourney** [RenderHeads/UnityPlugin-AVProVideo#20]
We want to stream high speed videos (120 fps & 240 fps) from a server, but as we noticed while debugging: the plugin will always buffer 5 seconds regardless of the frame rate. For a 120 fps and 240 fps 5s is a lot of data to process, which causes slow buffering times. We only allow a max playbackrate of 0.5X for 120 fps videos and 0.25X for 240 fps video.

A parameter to change the min buffer size (to start/continue playing) in code would be useful. We have 3 video types we are using in our app:
30 fps: min buffer can stay at 5s (max playbackrate is 1X)
120 fps: min buffer should be half, so 2.5s (max playbackrate is 0.5X)
240 fps: min buffer should be quarter, so 1.25s (max playbackrate is 0.25X)

Unity version:  2018.2.20
AVPro version: 1.9.12

**Comment by AndrewRH** [comment]
We have improved settings in version 2.x of the plugin to control buffering size, but this is the maximum size, not the minimum.  On Apple platforms there is no way currently to set the minimum size.

**Comment by AndrewRH** [comment]
Closing this issue as it is related to version 1 which is now deprecated.
