### ISSUE TITLE
Dropped support for platforms between 2.x and 3.x

### ISSUE THREAD

**Issue by fdegryse** [RenderHeads/UnityPlugin-AVProVideo#2000]
Hello,

I noticed the documentation for AVProVideo 3.x lists higher OS version requirements for some platform.
Some of these new requirements would prevent us from upgrading (notably Windows 7 & 8.1 support), which we need to support Vulkan on Android platforms.

If I'm not mistaken, those platform support drop were not listed in the release notes for the 3.x version,
could you confirm that the new version of the plugin will not work on Windows 7 & 8.1 and Android 7 ?

Some of these new requirements seems quite a bit higher than what the Unity player still supports on Unity 2022.3 although the documentation states that the package supports starts at Unity 2018.

**Comment by Chris-RH** [comment]
Hi, 

Our supported platforms are clearly listed in [our documentation](https://renderheads.com/content/docs/AVProVideo-v3/articles/requirements.html).  We no longer support Windows 7, 8, and 8.1, or Android below 8.0.

Unfortunately we cannot keep supported old OS that are no longer even supported by their manufacturer.  There are often compatibility issues with newer API that is required by newer OS.  The vast majority of our users aren't using the old OS, as the hardware that it is on doesn't allow them to run apps that modern users are looking for. We have a lot more pressure from users to support up to date software versions.  We are a small team and can only manage so much.
