### ISSUE TITLE
Xcode build failed with firebase

### ISSUE THREAD

**Issue by CYCPeter** [RenderHeads/UnityPlugin-AVProVideo#2001]
**Describe the issue**
When trying to build my AvPro Video project that utilizes Firebase Database, the Xcode export process fails with the following error: Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.27
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 1.11.5
 - Operating system version: Mac os
 - Device model: iPhone X

**To Reproduce**
1. only import FirebaseDatabase_11.9.0 and avpro video
firebase link
https://developers.google.com/unity/archive#firebase
2. export xcode and open xcworkspace to build

**Logs**
error log
https://drive.google.com/drive/folders/1WiDhvNB07sKarnGlH3CvYVg_J6tqAENq?usp=sharing

**Comment by MorrisRH** [comment]
Could you provide the build error as a text file, there's not enough information in the png to identify what's going wrong.

We no longer support version 1.x of the plug-in however version 1.11.7 was the last official release of the plugin so it may be worth upgrading.

For more recent Unity versions and iOS you will need version 1.11.9 which we provide on request, please send your invoice pdf from Unity for the plugin to unitysupport@renderheads.com mentioning this issue so we can provide you with it.

**Comment by CYCPeter** [comment]
log text file
https://drive.google.com/file/d/1KKDaJyNwdmawRXtbP9A1MvHEsllZFWdd/view?usp=sharing
xcode file
https://drive.google.com/file/d/1HRu57MmwKX8NIEtvBwRy0Dvt8SUZVJ2w/view?usp=sharing

The original purchase was handled by another person. I'll need to inquire about the invoice.

**Comment by MorrisRH** [comment]
Please don't provide project files here - send them to unitysupport@renderheads.com. Please remove them from you google drive.

**Comment by MorrisRH** [comment]
Your project does not include the native iOS AVPro Video plugin files. I've no idea why Unity hasn't added them, I would check Unity's build log to make sure there are no errors reported there. Also worth checking that the plugin is correctly enabled in the inspector.

I don't think Firebase is the cause of this but I'm not familiar with its build process so it might well be the issue here.

**Comment by CYCPeter** [comment]
Thank you for your help. The problem has been resolved after upgrading to version 1.11.9.
