### ISSUE TITLE
Crash reported  -  AvPro v3.0.11, Android XR running using Graphics API : Vulkan (First)  OpenGLES3 (Second)

### ISSUE THREAD

**Issue by yinyuanqings** [RenderHeads/UnityPlugin-AVProVideo#2002]
I got this error crash when deploying Avpro v3.0.11 to an XR devices (RhinoX Mixed-Reality headset)

Error log snippet likes below  , seems when AvPro depends on an vulkan allocation API which encounters an critcal error

VULKAN DEBUG: ERROR:  [vulkan, 0]: VK_ANDROID_external_memory_android_hardware_buffer not enabled. Exported vkGetAndroidHardwareBufferPropertiesANDROID not executed.
 E CRASH   :       #00 pc 00000000000dee58  /vendor/lib64/hw/vulkan.kona.so (qglinternal::vkAllocateMemory(VkDevice_T*, VkMemoryAllocateInfo const*, VkAllocationCallbacks const*, VkDeviceMemory_T**)+1056) (BuildId: e2bd4c9aa7022895d1fdade361b99285)

*****  Full unfilter logcat logs is attached:   *****

[logcat_vulkan.txt](https://github.com/user-attachments/files/17004524/logcat_vulkan.txt)

My test environment : 

Ximmerse RhinoX Mixed Reality headset ;

Unity 2021.3.21f1 , Windows 10,, unity XR SDK is enabled, no URP(Builtin render pipeline)
Graphics API : Vulkan (Top) + OpenGLES3.0 (Second)
Android target is 9.0

Some notes :
When disable vulkan , only OpenGLES3, the plugins work perfect in XR or Non-XR (normal mobile app) mode .
When disable XR (normal mobile app), then plugins do works well too , no matter graphics API choose vulkan , openGLES or vulken-then-openGLES3 .

I guess this error relates to some vulkan API issue then unity XR sdk is turning on .  And I read the threads before, you are falling back to depends openGLES3 API when vulkan is not supported at the some old Android device. Is that some sofeware switch I can use, to mannually toggle this feature ON ? I currently needs the vulkan ON for some reason, and I needs to play the video as well . So can I do  some work, to make unity render scene using vulkan , and AvPro render video , using openGLES3, so as a hybrid mode , is that possibile ?

**Comment by MorrisRH** [comment]
I don't know what we can do about this. The XR plugin has hooked the Vulkan initialisation so our code which would enable the necessary extensions (or fail initialisation if they're not available) is not being called.

I would open an issue with Unity or whoever provides the XR plugin.

You could try disabling `Initialise XR on Startup` (in the "XR Plug-in Management inspector") and see if you can handle starting the plugin later (after AVPro Video has initialised). I am not sure what would be required for this.

**Comment by MorrisRH** [comment]
Having tested I can confirm this is an issue with Unity. Only one plugin can hook the Vulkan initialisation and unfortunately the XR plugin was loaded last so was able to hook the init.

If you can affect the plugin load order and make AVPro Video the last plugin to be loaded then our Vulkan initialisation hook will be called instead of the XR plugin's.

Unfortunately because our Vulkan initialisation code is not being called we have no way to fallback onto OpenGLES 3.

**Comment by yinyuanqings** [comment]
> Having tested I can confirm this is an issue with Unity. Only one plugin can hook the Vulkan initialisation and unfortunately the XR plugin was loaded last so was able to hook the init.
> 
> If you can affect the plugin load order and make AVPro Video the last plugin to be loaded then our Vulkan initialisation hook will be called instead of the XR plugin's.
> 
> Unfortunately because our Vulkan initialisation code is not being called we have no way to fallback onto OpenGLES 3.

Hi Morris, 
Well so if I understand you correctly, what actually cause the crash , is that plugin (whatever Unity XR plugin or the headset's SDK plugin) hooks vulkan initialization (which should be the jobs of AvPro) and that hook code internally cause the error..
