### ISSUE TITLE
sample video plays in apk but my own 360 is just black

### ISSUE THREAD

**Issue by frowestbrennan** [RenderHeads/UnityPlugin-AVProVideo#2003]
Problem description:

Hello!  I am trying out this plugin and can get the Media Player to play my h265 6k stereo video
great in Unity.  Your sample video also lays fine.  After I build an apk and side to a 
quest 3 the video is black without audio.  However your sample footage will build. 
I have a Media Reference for my video file as well.

Device (which devices are you having the issue with - model, OS version number):

quest 3

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

eventually lots of videos but starting with just 1. 5760 x 5760. 29.97. h265. No streaming videos- I have the video files in the project itself.

System Information:

AVPro Video: v3.0.11 (plugin v3.0.10f1-trial)
Target Platform: Android
Unity: v2022.3.11f1 WindowsEditor
OS: Desktop - MS-7C91 (Micro-Star International Co., Ltd.) - Windows 11  (10.0.22631) 64bit - English
CPU: AMD Ryzen 9 5900X 12-Core Processor  - 24 threads - 65461KB
GPU: NVIDIA GeForce RTX 3090 - NVIDIA - Direct3D 11.0 [level 11.1] - 24326KB - 16384

**Comment by Chris-RH** [comment]
1. Can you reproduce this in a new project with only AVPro Video, running the 360 demo scene with your video?
2. Can you provide a full, unfiltered logcat in txt format?
3. Have you encoded the video with [faststart](https://renderheads.com/content/docs/AVProVideo-v3/articles/feature-streaming.html#http-progressive-streaming)?
4. Have you tried reducing the resolution to something like 4096x4096?
5. Are you able to provide a sample of the video you are using for testing? Either here or to unitysupport@renderheads.com

**Comment by frowestbrennan** [comment]
Appreciate the response!  I will get started on those things to test but
here is the video I am trying this on:

https://drive.google.com/file/d/1bOEW-AtScm5swSBqv3akxrtrZ3E-pg64/view?usp=sharing

*Forrest Brennan*
Co-Founder
360 Cinematographer & VFX
H <http://goog_1943268698>ungryMantis.com <http://HungryMantis.com>
[image: hungrymantis.com] <http://hungrymantis.com>

**Comment by Ste-RH** [comment]
@frowestbrennan For reference, I have tested your video on a Quest 2 in our 360 Demo scene and it plays just as it should (when using both OpenGLES and Vulkan).  I do not have a Quest 3 to hand at the moment, but I would think if the 2 plays the video, the 3 should be the same result.

When you get chance, send us over a log so we can take a better look.

**Comment by frowestbrennan** [comment]
The .txt files were too big so zipped them here.

*Forrest Brennan*
Co-Founder
360 Cinematographer & VFX
H <http://goog_1943268698>ungryMantis.com <http://HungryMantis.com>
[image: hungrymantis.com] <http://hungrymantis.com>

**Comment by Chris-RH** [comment]
Hi @frowestbrennan 

Unfortunately files can't be sent via email replies to github.  Could you email it to unitysupport@renderheads.com please.

**Comment by frowestbrennan** [comment]
Ok just emailed directly.

*Forrest Brennan*
Co-Founder
360 Cinematographer & VFX
H <http://goog_1943268698>ungryMantis.com <http://HungryMantis.com>
[image: hungrymantis.com] <http://hungrymantis.com>

**Comment by Ste-RH** [comment]
@frowestbrennan The log you sent is does not look like a complete log from start of app run to end.

From what we can see in the log, there is a hint of it being related to an issue we fixed in v3.0.11.  Can you try updating to the latest release and see if your issue still persists?

**Comment by Ste-RH** [comment]
Anything to report back @frowestbrennan ?

**Comment by frowestbrennan** [comment]
Hey there!

We ended up going with the native video player and for the most part it
seems to be working.  I initially had 3.0.9 installed and I think I did
upgrade to 3.0.11 before sending you the log.  It's possible I upgraded
incorrectly though.

*Forrest Brennan*
Co-Founder
360 Cinematographer & VFX
H <http://goog_1943268698>ungryMantis.com <http://HungryMantis.com>
[image: hungrymantis.com] <http://hungrymantis.com>
