### ISSUE TITLE
Issue with Black Line Overlay on 360 Video after Upgrading to AVPro Video 3

### ISSUE THREAD

**Issue by Fasilkallot** [RenderHeads/UnityPlugin-AVProVideo#2006]
I am experiencing a black line overlay on my 360 VR video when played on Android using Google VR after updating to AVPro Video version 3.0.11. This issue was not present when using AVPro version 2, and interestingly, it did not occur when I tested the trial version of version 3.

Unity version: 2023.2.3f
AVPro Video version (core): 3.0.11 
Operating system version: Android 14
Device model: Oneplus 8T
Video specs (resolution, frame-rate, codec, file size): 4k, 25 fps, h.264, 110 Mb

To Reproduce

1. Delete AVPro Video version 2 from the project.
2. Import AVPro Video version 3.0.11 into Unity.
3. Load the 360 VR video in Unity.
4. Play the video on an Android device using Google VR.
5. Observe the black line overlay on the video.

Screenshots
![Screenshot_2024-09-18-11-40-40-78_6db678231275f23f4e2fa72c692645be (1)](https://github.com/user-attachments/assets/b86e54d4-6f5b-4a5c-82f6-abdbf536db83)
![Screenshot_2024-09-18-14-45-34-35_6db678231275f23f4e2fa72c692645be](https://github.com/user-attachments/assets/b4472c10-0aa7-47f9-a7f9-4d425451200a)
![Screenshot_2024-09-18-14-45-44-73_6db678231275f23f4e2fa72c692645be](https://github.com/user-attachments/assets/f4794ba0-5b33-4104-84b1-3d87f02c9ca8)
![Screenshot_2024-09-18-11-40-40-78_6db678231275f23f4e2fa72c692645be](https://github.com/user-attachments/assets/eeb98767-1de9-47f3-97fa-2d41ffa80664)

**Comment by Chris-RH** [comment]
You've said that it occurred after update.  
1. Which previous version did it not appear in?
2. Which trial version was it?
3. Is it reproducible in any other android devices?
4. Is it reproducible in editor, and if so, what OS version is it?
5. Can you reproduce this in a new project running only AVPro Video and the 360 demo scene?
6. Can you reproduce this in a new project running only AVPro Video and the 360 demo scene, with your video?
7. Sample of your video and link to URL if streaming
8. Can you provide a full, unfiltered logcat in txt format

**Comment by Fasilkallot** [comment]
Did you follow the project upgrade steps?
Yes

Which previous version did it not appear in?
2.9.3

Which trial version was it?
3.0.11

Did you use GoogleVR in the previous tests that it was in?
Yes

Is it reproducible in any other Android devices?
Yes

Is it reproducible in editor, and if so, what OS version is it?
No

Can you reproduce this in a new project running only AVPro Video and the 360 demo scene?
No

Can you reproduce this in a new project running only AVPro Video and the 360 demo scene, with your video?
No

Sample of your video and link to URL if streaming.
Can't provide the video.

Can you provide a full, unfiltered logcat in txt format?
2024-09-18 16:32:00.617 10494 10564 Info Unity playerID: 0000E9B6
2024-09-18 16:32:00.617 10494 10564 Info Unity flags: 00000000
2024-09-18 16:32:00.617 10494 10564 Info Unity flags: 0000E9B6
2024-09-18 16:32:00.617 10494 10564 Info Unity [AVProVideo] Opening https://ibeesu.s3.ap-south-1.amazonaws.com/JungleSafariNew/Intro_Scene/Master.m3u8 (offset 0) with API ExoPlayer
2024-09-18 16:32:00.633 10494 10564 Info Unity Starting XR...
2024-09-18 16:32:00.633 10494 10564 Info Unity [XR] [CardboardXrInputProvider]: Lifecycle started
2024-09-18 16:32:00.634 10494 10785 Info Unity [XR] [CardboardXrDisplayProvider]: Initializes Cardboard API.
2024-09-18 16:32:00.646 10494 10564 Info Unity [XR] [CardboardXrInputProvider]: No events to handle
there is no errors showing

Additional Information:
When I build the APK in development mode, the issue does not occur.

**Comment by Fasilkallot** [comment]
Did you follow the project upgrade steps?
Yes

Which previous version did it not appear in?
2.9.3

Which trial version was it?
3.0.11

Did you use GoogleVR in the previous tests that it was in?
Yes

Is it reproducible in any other Android devices?
Yes

Is it reproducible in editor, and if so, what OS version is it?
No

Can you reproduce this in a new project running only AVPro Video and the 360 demo scene?
No

Can you reproduce this in a new project running only AVPro Video and the 360 demo scene, with your video?
No

Sample of your video and link to URL if streaming.
Can't provide the video.

Can you provide a full, unfiltered logcat in txt format?
2024-09-18 16:32:00.617 10494 10564 Info Unity playerID: 0000E9B6
2024-09-18 16:32:00.617 10494 10564 Info Unity flags: 00000000
2024-09-18 16:32:00.617 10494 10564 Info Unity flags: 0000E9B6
2024-09-18 16:32:00.617 10494 10564 Info Unity [AVProVideo] Opening https://videoExample.m3u8 (offset 0) with API ExoPlayer
2024-09-18 16:32:00.633 10494 10564 Info Unity Starting XR...
2024-09-18 16:32:00.633 10494 10564 Info Unity [XR] [CardboardXrInputProvider]: Lifecycle started
2024-09-18 16:32:00.634 10494 10785 Info Unity [XR] [CardboardXrDisplayProvider]: Initializes Cardboard API.
2024-09-18 16:32:00.646 10494 10564 Info Unity [XR] [CardboardXrInputProvider]: No events to handle
there is no errors showing

Additional Information:
When I build the APK in development mode, the issue does not occur.

**Comment by Ste-RH** [comment]
Are you using GoogleVR Unity SDK? (https://github.com/googlevr/gvr-unity-sdk)

**Comment by Fasilkallot** [comment]
Google Cardboard XR plugin for unity 
https://github.com/googlevr/cardboard-xr-plugin

**Comment by Ste-RH** [comment]
Using your video URL, the cardboard XR plugin, AVPro Video 360 Demo Scene, on a Xiaomi Mi 10T...I get playback exactly as I would expect.  No corruption as you are seeing.

Are you able to share a project that reproduces the issue? (unitysupport@renderheads.com  - subject: #2006)

**Comment by Fasilkallot** [comment]
Hi @Ste-RH ,

Unfortunately, I can’t share the project files due to company policies. Have you tried upgrading from AVPro V2 to V3? My project was working fine in Version 2. In the project I'm using the playlist media player to play 360 videos via URL, and the video is streaming as HLS.

Interestingly, it works fine in the development build, or if I remove all canvases from the project, or when I enable Auto Graphics API (though the video seems to lag in this case).

I can provide some project settings that might help, and let me know if you need any more specific details.

Thank you!

![Screenshot 2024-09-19 100025](https://github.com/user-attachments/assets/475f08cb-3e81-478d-95f8-f314eb3ce66e)

**Comment by Fasilkallot** [comment]
After much frustration and searching, I discovered that checking “Disable Depth & Stencil” in the Player Settings resolved the black line overlay issue. A big thank you to @Ste-RH  and @Chris-RH  for your assistance!

It appears that having multiple world canvases might contribute to the problem, although I’m not entirely sure why. I also noticed a slight difference in video quality—could this be linked to disabling Depth & Stencil?

Thanks again for the support!

**Comment by Fasilkallot** [comment]
After much frustration and searching, I discovered that **checking “Disable Depth & Stencil” in the Player Settings** resolved the black line overlay issue. A big thank you to @Ste-RH and @Chris-RH for your assistance!

It appears that having multiple world canvases might contribute to the problem, although I’m not entirely sure why. I also noticed a slight difference in video quality—could this be linked to disabling Depth & Stencil?

Additionally, I wonder why the issue isn't present in AVPro Version 2.

Thanks again for the support!

**Comment by Ste-RH** [comment]
Thanks for the update @Fasilkallot 

We re-wrote the entire OpenGLES pipeline between v2 and v3, so I am not surprised that one does not show the issue and the other does.

Unfortunately, without a reproducible case in our hands we cannot guess at what difference has caused this.  It will likely be some nuance in your project that clashes with some state/setting in the AVPro Video OpenGLES renderer.

I am going to close this issue now, but if you are able to provide a simple project that shows the issue we will naturally investigate further.  If you experience anything further pertaining to the issue, please do reach out again.
