### ISSUE TITLE
Playback speed doesn't work for Spatial audio

### ISSUE THREAD

**Issue by rrenderr** [RenderHeads/UnityPlugin-AVProVideo#2007]
**Describe the issue**
Playback speed doesn't work for Spatial audio - _currentPlayer.PlaybackRate. On Android it doesn't affect video speed.

**My Setup**
- Unity version: 2022.2.15f1
- AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.11 ultra
- Operating system version: Android
- Device model: Meta Quest
- Video specs (resolution, frame-rate, codec, file size): has spatial audio

**To Reproduce**
- Start a video with spatial sound
- Change playback speed

**Logs**
Attached full log
[AndroidFullLog.txt](https://github.com/user-attachments/files/17042588/AndroidFullLog.txt)

**Comment by Chris-RH** [comment]
Unfortunately this is something that the FB360 library doesn't support.  As it is depreciated, its not going to ever be, I'm afraid.

**Comment by rrenderr** [comment]
Thank you for answer.
It is useful to know it
