### ISSUE TITLE
Can Support On Windows With OpenglES3?

### ISSUE THREAD

**Issue by alltry1014** [RenderHeads/UnityPlugin-AVProVideo#2010]
![image](https://github.com/user-attachments/assets/12aca347-56c2-4cc9-bdfa-bb0d4c598de6)

![image](https://github.com/user-attachments/assets/e5d41f9f-616a-44f6-a271-8eb9f16d753f)

Dear AVPro Video Support, how can the plugin play well on windows with openglES3? Thanks.

**Comment by Chris-RH** [comment]
Hi @alltry1014 

[Windows supports D3D11 and D3D12](https://renderheads.com/content/docs/AVProVideo-v3/articles/requirements.html).
