### ISSUE TITLE
[Android] No playback when using media player on Android emulator

### ISSUE THREAD

**Issue by alltry1014** [RenderHeads/UnityPlugin-AVProVideo#2012]
Dear AVProVideo Support,
The plugin that use media player can not play on the simulator.There are some logs for you.

Logs:
[lightning_simulator_dont_play_log3.txt](https://github.com/user-attachments/files/17132090/lightning_simulator_dont_play_log3.txt)

My Setup:
Unity version: 2022.3.20f1
AVPro Video version: v3.0.11 Core Edition
Operating system version: Andriod 9
Device model: Andriod Simulator
Video specs (resolution, frame-rate, codec, file size):
resolution: 1440 * 2476
frame-rate: 60fps
codec: H.264
file size: 13.8 MB
average bitrate: 3309kbps

This is very important for us. We have an online test recently. Please reply as soon as possible, thanks.

**Comment by Chris-RH** [comment]
Hi @alltry1014,

You said previously that it was working on lightning simulator? What has changed since then?

We prioritise playback on actual hardware rather than emulators.

**Comment by alltry1014** [comment]
I just changed the exo player to media player.  this works well when using exoplayer on lightning simulator.By the way, the version v.2.9.3 works well on both mumu simulator and lightning simulator.

**Comment by Ste-RH** [comment]
I _think_ this is fixed in the next release (v3.1.0) which we are aiming to release in the coming days.

![image](https://github.com/user-attachments/assets/ad95b62d-6357-4c6b-ba50-e11f649c8d69)

**Comment by alltry1014** [comment]
Dear AVProVideo Support,thank you very much!

**Comment by alltry1014** [comment]
Dear AVProVideo Support,When will the next version be available? We have a test recently.

**Comment by Ste-RH** [comment]
@alltry1014 Apologies for the delay.  We have been working very hard to get it out asap, but have hit many small blockers which have meant a release would have been bug heavy, and that benefits no one.  As my previous estimation was wildly incorrect - even though we were confident we could get it released in that timeframe - I am hesitant to put another timeframe on release.  It will be as soon as possible.

**Comment by alltry1014** [comment]
OK, thanks.

**Comment by Ste-RH** [comment]
AVPro Video v3.1.0 has just been released. Please do report back if the fixes in the version address the issue.

**Comment by alltry1014** [comment]
I change build settings like this:
![image](https://github.com/user-attachments/assets/5c0cf048-6a2d-4935-a556-874ff5a86089)

![image](https://github.com/user-attachments/assets/9b7057be-d15c-401f-9844-8bef7928da42)
so，that can build apk well.
But still get errors and not playback both in mumu or lightning emulator.
There are some logs for you.
[lightning_simulator_dont_play_log4.txt](https://github.com/user-attachments/files/17443272/lightning_simulator_dont_play_log4.txt)
[mumu_simulator_dont_play_log2.txt](https://github.com/user-attachments/files/17443273/mumu_simulator_dont_play_log2.txt)

There are some screenshots on the simulator for you:
![image](https://github.com/user-attachments/assets/6fce7502-9181-40b4-a6f6-00ebb9823396)

**Comment by alltry1014** [comment]
Dear AVProVideo Support,the issue is still not solved.

**Comment by Ste-RH** [comment]
Hmm.  Something looks to have become broken between when I tested and release of v3.1.0.  I have just tested our latest development code branch and it appears to all work on MuMu.  Will test again against our next release and report back.

**Comment by Ste-RH** [comment]
Nothing has changed in v3.1.1 for this.  MuMu still does not playback videos in AVPro Video.  Though it appears to work with debug builds of the AVPro Video plugin.

**Comment by alltry1014** [comment]
OK，When will the next version be available? Thanks!

**Comment by Ste-RH** [comment]
We have no planned date for v3.1.2 yet, and no fix implemented for this problem as things stand.

**Comment by alltry1014** [comment]
Too hard for me. The online test comes soon.Thanks.

**Comment by Ste-RH** [comment]
> Too hard for me. The online test comes soon.Thanks.

I am sorry, I do not understand this.  Do you mean:  'This is too long for me, we have a demonstration/delivery soon' ?

As we do not officially support third part emulators, and AVPro Video works on the emulator you can use in Android Studio, I am afraid we will not be prioritising a fix for 3rd party emulators such as MuMu.

**Comment by alltry1014** [comment]
Our online paid test for players is coming soon.Now we temporarily use version 2.9.3. Thanks.

**Comment by Ste-RH** [comment]
Just want to circle back on this.  Are you making sure you are building your APK targetting x86_64 ?

![image](https://github.com/user-attachments/assets/9c5ed21c-7556-48d9-8998-cab3a4b9f7b9)

If I target ARM64 (the default for IL2CPP + real device), I get a crash shortly after the audio starts on video playback.  If I target like the above, I get fully correct playback.

![image](https://github.com/user-attachments/assets/fc6da500-59e8-412d-b3c5-9dcdf24ed47e)

**Comment by Chris-RH** [comment]
Have you tried that @alltry1014 ?

**Comment by alltry1014** [comment]
Sorry for the long wait! I'm sorry for tell you that is not work for me.
![image](https://github.com/user-attachments/assets/b635b2dc-d06b-44c8-8e74-cb62792d2d9b)
![image](https://github.com/user-attachments/assets/3b287f06-c522-4c04-a782-dad76be8de84)

The logs for you!
[dont_play_log.txt](https://github.com/user-attachments/files/18006589/dont_play_log.txt)

**Comment by Ste-RH** [comment]
I see you are using the MediaPlayer API.  Please try the ExoPlayer API.

**Comment by alltry1014** [comment]
Very Good! I still keep this setting and change api to Exo Player.  It works! Thanks, Dear AVProVideo Support!
![image](https://github.com/user-attachments/assets/b3f6a202-c5de-434d-8cbf-e0cb24f8fd01)

**Comment by Ste-RH** [comment]
Yes, we recommend ExoPlayer.

The Huawei Mate 60 Pro is a HarmonyOS device, no?

**Comment by alltry1014** [comment]
Yes, but still using Android instead of OpenHarmony.

![image](https://github.com/user-attachments/assets/b649ec36-657e-460b-9579-96a3b8e97faf)
![img_v3_02h8_4ce2ed1e-a690-4e94-8ef9-b366f174517g](https://github.com/user-attachments/assets/4e8e8a88-24a9-4d8c-85a3-07c63391d1a8)

**Comment by alltry1014** [comment]
Sorry, I tried it again and found that it doesn't work on HarmonyOS, whether using media player or exo player.
There are some logs for you!
[dnot_play_on_harmonyOS.txt](https://github.com/user-attachments/files/18009134/dnot_play_on_harmonyOS.txt)
[dnot_play_on_harmonyOS2.txt](https://github.com/user-attachments/files/18009135/dnot_play_on_harmonyOS2.txt)

**Comment by Chris-RH** [comment]
We don't support HarmonyOS yet.

**Comment by alltry1014** [comment]
OK, but the v2.9.3 can work well on both HarmonyOS and Android emulator.

**Comment by Ste-RH** [comment]
I believe the support for Android on HarmonyOS has a limited life.  We are looking to support HarmonyOS at native level, but cannot put a timeframe on this at this stage.  We will close this issue now as we have taken it as far as we can.

**Comment by alltry1014** [comment]
Thank you very much!

**Comment by alltry1014** [comment]
Dear AVProVideo Support, When the video starts playing, there will be a blue screen for a moment，how to solve it？

**Comment by Ste-RH** [comment]
This issue is now closed.  If you have a new/different problem, please open a new issue for each individual problem/question.  Be sure to include **all** the information asked for.

**Comment by alltry1014** [comment]
OK

**Comment by alltry1014** [comment]
I fixed that bug.It's not a plugin issue.
