### ISSUE TITLE
AVPro 360 Video Not Working on Realme C25 Device

### ISSUE THREAD

**Issue by Fasilkallot** [RenderHeads/UnityPlugin-AVProVideo#2015]
AVPro 360 video is not functioning on the Realme C25 device. The demo 360 scene fails to load or display properly, resulting in a blank screen.

Unity version: 2023.2.3f1
AVPro Video version: 3.0.11 (Core)
Operating system version: Android 13
Device model: Realme C25
Video specs:
Resolution: 1080X1920
Frame-rate: 25 FPS
Codec: H.264
File size: 100 MB

To Reproduce

1. Build apk with demo 360 scene 
2. Install and Launch the app 

Screenshots
Not applicable as the screen remains blank.

Videos
Not applicable as the demo fails to load.

Logcat
[logcat.txt](https://github.com/user-attachments/files/17160079/logcat.txt)

**Comment by Chris-RH** [comment]
Your logcat seemed to include cardboard and a streamed URL

1. Is this reproducible in a new project running only the AVPro Video mediaplayer demo scene and nothing else?
2. Is this reproducible in a new project running only the AVPro Video 360 demo scene and nothing else?
3. Have you tested both OpenGLES and Vulkan?
4. Have you tested bother Exoplayer and Android Mediaplayer?

**Comment by Fasilkallot** [comment]
I have tried with vulkan and OpenGLES also in Exo player and media player but the issue persist.


When I try to build a new project with only the AVPro package, this issue occurs:

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':launcher
'.
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules jetified-guava-31.1-android (guava-31.1-android.jar) and jetified-listenablefuture-1.0 (com.google.guava:listenablefuture:1.0).

**Comment by Chris-RH** [comment]
https://renderheads.com/content/docs/AVProVideo-v3/articles/platform-android.html#unity-20230-and-above

**Comment by Fasilkallot** [comment]
Yes, the issue is reproducible in a new project running only the AVPro Video 360 demo scene and nothing else. However, there is no issue in the AVPro Video Media Player demo scene.

**Comment by MorrisRH** [comment]
Your HLS is malformed. Here is a corrected Master.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3

#EXT-X-START:TIME-OFFSET=0.0
#EXT-X-STREAM-INF:BANDWIDTH=6500000,RESOLUTION=4096x2160
4k/output.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=3000000,RESOLUTION=1920x1080
1080/output.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=2000000,RESOLUTION=1280x720
720/output.m3u8
```

It should play correctly when you've fixed this.
