### ISSUE TITLE
Frame Missing issues on Android and Editor

### ISSUE THREAD

**Issue by noman5412** [RenderHeads/UnityPlugin-AVProVideo#2016]
I want to popup a button on rendering a specific frame number but on checking the frame number in Update() via _mediaPlayer.Control.GetCurrentTimeFrames(); it sometimes skip or miss the that frame number and button can't get popped up.

Is there any frame change event like other events which can be used for this purpose?

I have attached details of my settings

**Describe the issue**
A clear and concise description of what the issue is.

**My Setup:**
 - 2021.3.5f1: 
 - AVPro Video version (3.0.7 (trial)): 
 - Android 14: 
 - Device model: Redmi Note 12
 - Video specs (1920x1080, 50fps, mp4, 200mb approx, streaming from aws cloudfront): 

**Screenshots**
![8](https://github.com/user-attachments/assets/118fda43-d1bd-474e-bee2-9d9040cba939)
![7](https://github.com/user-attachments/assets/a40b8e1d-2725-4758-8f66-17459e7e3379)
![6](https://github.com/user-attachments/assets/93181d52-be18-4b18-9f58-c0af9c46d2e2)
![5](https://github.com/user-attachments/assets/8ebb2199-dbb6-446d-8e9f-46e2e9186817)
![4](https://github.com/user-attachments/assets/a7d69471-0b6e-4bc1-8fe5-d8d41766dff0)
![3](https://github.com/user-attachments/assets/d36969cc-d583-4703-81b7-0568b37bff6b)
![2](https://github.com/user-attachments/assets/708bb923-47a5-475e-b78d-89d96239def0)
![1](https://github.com/user-attachments/assets/bc058745-8792-4ff0-a1e3-79c440c658fe)

**Comment by Chris-RH** [comment]
Hi, can you update to the latest version of AVPro Video and retest please, as we fixed a similar issue recently.

**Comment by noman5412** [comment]
Hello, I have tried using latest AVPro version 3.0.11 but issue is there.
Most of the time, only one frame is usually skipped but occasionally more than one frame can get skipped too.

Looking forward to hear from you

**Comment by Ste-RH** [comment]
What frame rate is your application achieving? If it’s lower than the frame rate of the video, taking into account any frame drops as well, then you will not get every frame of the video presented.

**Comment by Chris-RH** [comment]
The decoder under the hood will be decoding against a clock (regular time).  But Unity, the render thread, will only be pulling the frames from the decoder according to it's update.  So if you slow down the app, you will miss frames.  You have to hold the framerate of the video if you want to see every frame.

You could try to slow down the playback rate.  This would mean that there was more chance of seeing every frame.  You would have to balance the framerate of the app and how much to slow down playback rate.
