### ISSUE TITLE
[iOS] Unable to resume playback after removing headphones

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/UnityPlugin-AVProVideo#2017]
Removing headphones from the Lightning port causes the video to freeze. The video stops playing and will not resume, even if the user attempts to unpause it using the play/pause button.

**Comment by MorrisRH** [comment]
Reproduced using:
- Unity 2022.3.44f1
- AVPro Video 3.0.11
- iPad Pro (10.5") running iPadOS 17.6.1

**Comment by MorrisRH** [comment]
Fixed

**Comment by Ste-RH** [comment]
AVPro Video v3.1.0 has just been released. Please do report back if the fixes in the version address the issue.
