### ISSUE TITLE
VP9 in Windows 10 Enterprise LTSC

### ISSUE THREAD

**Issue by GreenSnake22** [RenderHeads/UnityPlugin-AVProVideo#2018]
I have recently started experimenting with AVPro for use in a project where I will be displaying multiple videos across 3 screens. However due to the version of windows I am using it appears I am unable to use VP9 videos, both webm and mp4. Is there any way to get them working as the videos must be in this format?

Thanks In advance

Setup
-Unity 2022.3.10f1
-AVProVideo v3.0.11 - Trial version
-Windows 10 enterprise LTSC 64-bit(10.0, Build 17763)
-Video Specs (1040x650 and 700x374, 30fps, VP9, file size ~ 5mb to 10mb)

Logs-
"[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources."

**Comment by Chris-RH** [comment]
Have you tried using Direct Show and [LAV filters](https://github.com/nevcairiel/lavfilters/releases)?
Alternately, there may be codecs in the Microsoft Store?

**Comment by GreenSnake22** [comment]
Getting a codec from the microsoft store fixed it, thanks
