### ISSUE TITLE
Small issue at 'poles' when playing 180 stereo video

### ISSUE THREAD

**Issue by charlesingea** [RenderHeads/UnityPlugin-AVProVideo#2019]
**Describe the issue**
There is a tiny issue at the 'north and south poles' of an 180 video - a few pixels that stick out of the semisphere. It is not a big problem in itself but it messes up the feathering when using UnlitTransparent(stereo+color+fog+alpha) - it causes the feathering to be inconsistent at the north and south poles compared to the edges of the sphere.

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.46f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v3 - Ultra Edition
 - Video specs (resolution, frame-rate, codec, file size): 8K side-by-side stereo, H265, 29.97 fps

**Screenshots**
Without feathering:
![image](https://github.com/user-attachments/assets/61803ce4-3556-4013-bde6-b9341a6e079b)

With feathering:
![image](https://github.com/user-attachments/assets/1a245a0d-37c9-4d54-9fe5-6e6c86fd0bb4)

**Comment by Ste-RH** [comment]
Enable 'High Quality' in the shader

![image](https://github.com/user-attachments/assets/9fd78fdf-a661-4950-b6bc-1f3d4157184b)

**Comment by charlesingea** [comment]
Thank you! This has fixed the issue when no feathering is applied.
But when I apply feathering, I still get this strange kind of artefact where the feathering at the poles is in this weird pattern:
![image](https://github.com/user-attachments/assets/6c15a18c-60ec-4c0f-acc2-1569c97e3668)
Do you know of any fix?

**Comment by Chris-RH** [comment]
There often tends to be distortion at the poles.   What you could do is use something like Blender to create a high-resolution UV Sphere (looking at around 128k verts) and that should improve it.

**Comment by charlesingea** [comment]
I see - thanks for the help!

**Comment by Ste-RH** [comment]
@charlesingea You could also look to change the feathering better solve your use-case.  You want to be looking at this line of code:

![image](https://github.com/user-attachments/assets/aa0729c0-9e08-449d-9ad4-56ec0f270eb5)

Maybe swapping it out for this line instead better works for your use-case?

float d = (uv.x - featherDirection.x) * (uv.y - featherDirection.y) * (featherDirection.z - uv.x) * (featherDirection.w - uv.y);

...and you end up with this kind of effefct:

![image](https://github.com/user-attachments/assets/d721c27e-3cfd-4222-b45c-f8961ad27171)

**Comment by Ste-RH** [comment]
With and without this feathing (screen grab of one of the poles):

![image](https://github.com/user-attachments/assets/c8a158a9-5391-458e-9cf9-3f09ec29c3f3)

![image](https://github.com/user-attachments/assets/2d725761-f47a-45ce-a574-78912bc9165a)

**Comment by Ste-RH** [comment]
We have fixed the 'notch' issue.

We have also changed the feathering code to the change documented above.

**Comment by Chris-RH** [comment]
AVPro Video version 3.1 has been released

**Comment by Fangh** [comment]
> With and without this feathing (screen grab of one of the poles):
> 
> ![image](https://github.com/user-attachments/assets/c8a158a9-5391-458e-9cf9-3f09ec29c3f3)
> 
> ![image](https://github.com/user-attachments/assets/2d725761-f47a-45ce-a574-78912bc9165a)

Where did you get the 180° version of the video ?

**Comment by Fangh** [comment]
> **Describe the issue** There is a tiny issue at the 'north and south poles' of an 180 video - a few pixels that stick out of the semisphere. It is not a big problem in itself but it messes up the feathering when using UnlitTransparent(stereo+color+fog+alpha) - it causes the feathering to be inconsistent at the north and south poles compared to the edges of the sphere.
> 
> **Your Setup (please complete the following information):**
> 
>     * Unity version: 2022.3.46f1
> 
>     * AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v3 - Ultra Edition
> 
>     * Video specs (resolution, frame-rate, codec, file size): 8K side-by-side stereo, H265, 29.97 fps
> 
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. Without feathering: ![image](https://github.com/user-attachments/assets/61803ce4-3556-4013-bde6-b9341a6e079b)
> 
> With feathering: ![image](https://github.com/user-attachments/assets/1a245a0d-37c9-4d54-9fe5-6e6c86fd0bb4)

Where did you get the semisphere mesh ?
