### ISSUE TITLE
Android phone getting hot while playing a video

### ISSUE THREAD

**Issue by amitdor84** [RenderHeads/UnityPlugin-AVProVideo#202]
**Describe the bug**
When I open a video from a URL using the AVProVideo plugin on the Android device (the App is running on 64bit), the phone is getting very how. I use only one mediaplayer.
I think that when the MediaPlayer gameobject is enabled its started to get warm and when watching the video its make the phone warmer.

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.29 
 - AVPro Video version: 1.10.1
 - Operating system version: Android 9
 - Device model: Samsung A8
 - Video specs (resolution, frame-rate, codec, file size): 
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Video resolution: 480x270
Frame rate: 25
File size: 5579 kb

**To Reproduce**
1. Open the URL below from the AVProVideo plugin media player.

**Videos**
https://gocubebucket.s3.amazonaws.com/GoCubeAcademy/DaisyTip1.mp4

**Comment by RenderHeadsSte** [comment]
Sorry, I am failing to see what the issue here is?  Unity is a high powered rendering engine.  On top of that you are either asking the CPU/GPU to decode video frames.  Small devices, such as phones, get warm whilst running unity apps and decoding video frames.
