### ISSUE TITLE
How to build for Android with large video files (Gradle error)?

### ISSUE THREAD

**Issue by charlesingea** [RenderHeads/UnityPlugin-AVProVideo#2020]
**Describe the issue**
I am trying to build a video player for Meta Quest 3 (Android). I have a video file in StreamingAssets that is 2.19 GB. Whenever I try to build to my headset, I get the following Gradle error:

> A failure occurred while executing com.android.build.gradle.internal.tasks.CompressAssetsWorkAction
   > Required array size too large

How can I build for large video files?

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.46f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v3 - Ultra Edition
 - Device model: Meta Quest 3
 - Video specs (resolution, frame-rate, codec, file size): 8K side-by-side stereo, H265, 2.19 GB, 29.97 fps.

**Comment by Ste-RH** [comment]
This is not an AVPro Video issue.

2.19GB is waaaaay to big to go in the Streaming Assets folder.  I advise one of the following:

- Put the file locally on the device and point AVPro Video to it
- Stream the file off a server (you will want to ensure it has been encoded with faststart if you continue using an MP4, though HLS would be a better choice)
- Cache/Download the video from a server using AVPro Video (Ultra only) caching/downloading features

**Comment by charlesingea** [comment]
Thank you!
