### ISSUE TITLE
After seeking video events were triggered with a delay

### ISSUE THREAD

**Issue by rrenderr** [RenderHeads/UnityPlugin-AVProVideo#2021]
**Describe the issue**

We have a special mask for the video, and we constantly synchronize it. However, after seeking, the video plays a few frames first, and after a while, we receive the events FinishedBuffering and FinishedSeeking.

 It looks like this:
1. We seek the video.
2. We can see the video already playing.
3. Approximately 0.1-0.3 seconds later, the mask is applied in the correct place.

**Your Setup (please complete the following information):**
- Unity version: 2022.2.15f1
- AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.11 ultra
- Operating system version: Android
- Device model: Meta Quest
- Video specs (resolution, frame-rate, codec, file size): any

**Comment by Ste-RH** [comment]
At most, there will be a single frames delay between the seek being reported as 'finished' (from the media3/ExoPlayer API) and the c# SeekFinished event.

We cannot report back any sooner that the seek has finished other than when the API tells us it has.

Maybe in your use-case you want to be watching for a change in texture count after you call for a seek? (GetTextureFrameCount())

**Comment by rrenderr** [comment]
It is an interesting idea. I logged FrameCount and Player time between events StartedSeeking and FinishedSeeking. It looks like in the middle we change frame to other with the same time.
I guess you have to change frame to another only after FinishedSeeking call.
[log.txt](https://github.com/user-attachments/files/17244806/log.txt)

**Comment by Ste-RH** [comment]
We do not have control to that level.  It all happens under the hood inside the API.  Hence suggesting the swap when you see a change in frame count.  Does this not work as you would expect/desire?
