### ISSUE TITLE
Hap alpha video not playing

### ISSUE THREAD

**Issue by paulorenanmelo** [RenderHeads/UnityPlugin-AVProVideo#2023]
Hap alpha videos are not playing on AVPro 3.0, same files that play fine on the AVPro 2.5.
It gives the generic error "[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources."

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.25f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.11 Ultra
 - Operating system version: Windows 10
 - Device model: Workstation with Nvidia rtx 3080 and Intel Xeon W-2275
 - Video specs (resolution, frame-rate, codec, file size): .mov hap alpha video

**To Reproduce**
1. Make a unity scene, add an AVPro media player to the scene
2. Put hap alpha video under streaming assets folder and link it on the hierarchy
3. Tick "Use Hap/NotchLC" under "Platform Specific", in Windows
4. Click play in the inspector and/or Play game to see the error logged below

**Logs**
[AVProVideo] Initialising AVPro Video v3.0.11 (native plugin v3.0.10f1-ultra) on NVIDIA GeForce RTX 3080/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor
UnityEngine.Debug:Log (object)
RenderHeads.Media.AVProVideo.Helper:LogInfo (string,UnityEngine.Object) (at Assets/AVProVideo/Runtime/Scripts/Internal/Helper.cs:181)
RenderHeads.Media.AVProVideo.MediaPlayer:Initialise () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:438)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:506)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (RenderHeads.Media.AVProVideo.MediaReference,bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:496)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI_Player (RenderHeads.Media.AVProVideo.MediaPlayer,RenderHeads.Media.AVProVideo.ITextureProducer) (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor_Player.cs:569)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:396)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

[AVProVideo] Opening D:/wkspaces/05622 Zayed National Museum/05622-prototype/Assets/StreamingAssets\Videos/Scanner.mov (offset 0) with API MediaFoundation
UnityEngine.Debug:Log (object,UnityEngine.Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo (string,UnityEngine.Object) (at Assets/AVProVideo/Runtime/Scripts/Internal/Helper.cs:185)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:577)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:509)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia (RenderHeads.Media.AVProVideo.MediaReference,bool) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:496)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI_Player (RenderHeads.Media.AVProVideo.MediaPlayer,RenderHeads.Media.AVProVideo.ITextureProducer) (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor_Player.cs:569)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:396)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1426)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:837)
RenderHeads.Media.AVProVideo.MediaPlayer:EditorUpdate () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:792)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI () (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:379)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by Ste-RH** [comment]
Do you have 'Use HAP/NotchLC' checked in the 'Platform Specific | Windows' options in the 'Media Player' component?

![image](https://github.com/user-attachments/assets/068f96a2-b60d-488d-98f6-84eaccbb9a01)

**Comment by Ste-RH** [comment]
You will also need the 'Use Custom MOV Parser' ticked

![image](https://github.com/user-attachments/assets/d6add5fd-74ce-4221-afdf-39f686e1e97c)

**Comment by paulorenanmelo** [comment]
Oh so that's required now - I had it unticked and it worked on 2.5. Just ticked that on 3.0.11 and it works again. Thanks!

**Comment by Ste-RH** [comment]
No problem, we are here to help.

v2.5 is very old now.  We are not surprised this is now a requirement.

Glad it is sorted for you.
