### ISSUE TITLE
Stereo video on active sequential projector setup

### ISSUE THREAD

**Issue by charlesingea** [RenderHeads/UnityPlugin-AVProVideo#2024]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Hello, I am struggling to understand how to render stereo video in Windows on my active sequential stereoscopic projector system. In the past I have used the MiddleVR package in Unity to render out Direct3D11 on my stereo display. But I am struggling to find any information on how to build a stereo video player with AVPro that can render out to such a display (rather than a VR headset).

**Your Setup (please complete the following information):**
 - Unity version: 2023.3.20f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video v3 - Ultra Edition
 - Supported stereo formats: Active, sequential stereo, Direct3D

**Comment by RichRH** [comment]
Hi @charlesingea,

Thanks for your message. What projector hardware are you using?

Have you tried our 'Demo_360Stereo' scene (most likely as a build)? And if so, what are you seeing?

Cheers,

**Comment by charlesingea** [comment]
Hi @RichRH, thanks for getting back to me.

I've tried building the stereo demo scene - it shows a monoscopic image and flickers every few seconds. It doesn't seem to pick up stereo information.

I am in a CAVE-like environment that uses 2 Barco F70-4K6C projectors that blend a stereo image on a curved screen. This screen shows up as a single 3D display in my display settings. I usually use the MiddleVR Unity package that outputs a Direct3D11 compositor window to the curved screen. It works well but is better suited for geometry, as it creates a stereo camera in the Unity scene that renders out to the 3D display.

I am trying to build a stereo video player. One option I have is to keep using MiddleVR with AVPro Video -- but that means creating meshes that are locked to the frustums of the MiddleVR cameras, and finding a way to display only left eye information to the MiddleVR left camera and only right eye information to the MiddleVR right camera.

I've done it in the past using Unity's built-in video player but that came with complications and performance issues. I was hoping AVPro Video would allow me to directly output stereo video to my display (e.g. on a screen space canvas), so that I wouldn't have to deal with the faff of creating geometry, displaying video on it and rendering it via a camera.

Appreciate any lead you might have on how to approach this!

**Comment by RichRH** [comment]
Hi @charlesingea,

Thanks for the comprehensive reply - it sounds like quite a setup you've got going there!

We're trying to get our head around the constituent parts but fundamentally, excluding AVPro Video, is Unity itself seeing/able to treat your display as stereo out of the box? Or is that why you're having to use MiddleVR to fill the gap(s)?

AVPro Video stereo support is (currently) built around Unity's stereo support so if that part isn't supported then we would expect issues - in which case it does sound like we're veering into enhancement/custom work territory.

Cheers,

**Comment by charlesingea** [comment]
Ah yes, we use MiddleVR to fill the gaps - Unity itself doesn't do well at supporting stereo displays if they aren't on a HMD.

I see, do let me know if you have any idea but in the meantime I think I will just try to get this to work via MiddleVR.

Thanks for the help!

**Comment by RichRH** [comment]
Ok, thanks for confirming that, and makes sense if Unity's stereo support itself isn't great for your display setup.

Sounds like leveraging MiddleVR is your best approach right now - I think we'd effectively be replicating some of its functionality within AVPro which is definitely heading into bespoke territory. Do drop us an email if this something you might want to pursue further.

Cheers,

**Comment by charlesingea** [comment]
Thanks Rich, I'll try to get it to work myself for now but will definitely drop an email if I think there is a better way to go about it.

On this topic, I am trying to use `SetupStereoEyeModeMaterial` to apply the left eye and right eye render to different materials - but they seem to both be showing the same eye. Am I missing something?

**Comment by RichRH** [comment]
`SetupStereoEyeModeMaterial` just sets keywords ('FORCEEYE_LEFT'/'FORCEEYE_RIGHT') on the shaders so they'd need to be supported - I've just checked our 'Demo_360Stereo' scene and in the editor can happily force the Inspector values and see it change accordingly:

![image](https://github.com/user-attachments/assets/a9900564-386c-4d50-801b-1a1572b0adfc)

Cheers,
