### ISSUE TITLE
Performance Issues when compared to built in player

### ISSUE THREAD

**Issue by GreenSnake22** [RenderHeads/UnityPlugin-AVProVideo#2027]
Hi,

I have recently been experimenting with the trial version of AVPro to make a menu program that cycles the buttons default image with a video. To achieve this I have attached a DisplayuGUI component to each button. A script cycles which video is set to play by changing the media players filepath, The same script them sets the video to play, waits for it to finish, then cycles to the next button/video. There are 2 screens, each displaying a different set of buttons and as such my unity scene contains 2 media players, one for each screen.

My problem is that the menu is now running at ~45 fps compared to ~90fps with the built in unity player. Is there anything I can do to improve performance? Have I made any obvious mistakes while setting up my scene?

Thanks in Advance

Setup
-Unity 2022.3.10f1
-AVProVideo v3.0.11 - Trial version
-AMD Ryzen Embedded V1605B
-AMD Radeon Vega 8 Graphics
-Windows 10 enterprise LTSC 64-bit(10.0, Build 17763)
-Video Specs (1040x650 and 700x374, 30fps, VP9, file size ~ 5mb to 10mb)

**Comment by Chris-RH** [comment]
Is this the exact same scene and videos, but Unity videoplayer is 90fps and AVPro is 45fps?
Are you using D3D11 or 12?
Are you using Media Foundation or DirectShow?

**Comment by GreenSnake22** [comment]
Yea its the exact same scene and the same videos, It was using D3D11, and both media players were set to media foundation

**Comment by RichRH** [comment]
Hi @GreenSnake22,

If using Media Foundation have you tried disabling "Renderer Sync"? (We're aware of some potential bottlenecks here)

Failing that, are you able to send your test project to us? (via [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com))

Cheers,

**Comment by GreenSnake22** [comment]
Disabling render sync brought it up to ~85fps, Cheers
