### ISSUE TITLE
HDRP video way too dark, unclear how to avoid Gamma over-correction

### ISSUE THREAD

**Issue by wybo** [RenderHeads/UnityPlugin-AVProVideo#2028]
I'm using the HDRP render pipeline on Unity 6. In the screenshot the picture in the left bottom is what it looks like in windows media player, and what it should look like.

The large middle picture in the middle is what comes out. Looks over-corrected to Gamma color space. I have gamma disabled in the shader, and have searched the AVPro source code for gamma settings / adjustments as well. But couldn't find anything that affects DisplayUGUI / can be tweaked there.

And the picture on the right bottom is probably what it looks like in linear color space, uncorrected.

How can I make it look like in windows media player (left bottom picture) ?

![Screenshot](https://github.com/user-attachments/assets/d6ffad7e-cb65-42b4-826b-b6d3e3b103de)

Might be a question as much as an issue...

AVPro 3.0.4. in this project
OS: Windows 10, desktop.
Mp4 h264 video

**Comment by Chris-RH** [comment]
Could you update to the latest version (3.0.11) and retest please? :)

**Comment by wybo** [comment]
Upgraded to 3.0.11, also unity to 6000.0.22f1 still the same.

![Screenshot2](https://github.com/user-attachments/assets/f6af52b5-f695-41c2-bb54-c4f51f311c70)


Am using the Playlist Video Player. Don't know if that makes any difference, or requires tweaking the shaders or such.

**Comment by wybo** [comment]
Ran it with the standard Video Player. No difference either. Problem persists

**Comment by wybo** [comment]
Did some experiments:

I tore out things deliminated by AVPRO_CHEAP_GAMMA_CONVERSION in AVProVideo.cginc. That's not it as it doesn't change anything.

Then I tore out all calls to GammaToLinear. That does change things, and makes it look almost like the picture in the bottom right, BUT still a little darker. Though not as dark as it should be, in Media Player.
- Seems that that 'little darker' + the gamma correction is what creates the problem. But where does it come from?

![Screenshot (145)](https://github.com/user-attachments/assets/c67b2c23-acad-49eb-81c3-1adcdafd3254)
