### ISSUE TITLE
After stop, seek position is not initialized to 0.

### ISSUE THREAD

**Issue by HyundongHwang** [RenderHeads/UnityPlugin-AVProVideo#2029]
**Describe the issue**
Hello.
Thank you for your quick and kind reply.
After stop, seek position is not initialized to 0.
When using in client app, seek(0) is additionally called after stop, but is it usually necessary to call it separately like this?
Because of this, when using in client app, stop and pause seem to work the same, so I wonder if it is intended or if it can be considered a bug.

**Your Setup**
unity : 2022.3.37f1
AvProVideo : 3.0.11
os : ALL (ios, android, macos, editor)
video : mp4(h264+aac), 30fps

**Screenshots**
I recorded the screen in my unity ide.
It is easy to reproduce in unity ide, but it can also be reproduced with the example project of issue #2026.
I sent you the example project #2026 by email.

[](https://github.com/user-attachments/assets/74b2c2be-0089-4496-a41b-f7247c47a52a)

**Comment by Chris-RH** [comment]
Hi, 

Yes, stop() and pause() basically have the same function.  Stop() basically does a bit of resetting/cleaning up things under the hood in some platforms.  If you want it to seek back to 0 then you need to code that into your button :)

**Comment by HyundongHwang** [comment]
Thank you for your kind explanation.
