### ISSUE TITLE
An error appears when you try to view video from a surveillance camera

### ISSUE THREAD

**Issue by maramak** [RenderHeads/UnityPlugin-AVProVideo#203]
An error appears when you try to view video from a surveillance camera:

> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

Access to the camera can be obtained from the link http://91.211.6.212/mjpg/video.mjpg or http://91.211.6.70/mjpg/video.mjpg

Video without problems opens in the Internet browser and in AVPro Live Camera, problems are noticed only in AVPro Video.

Windows 10 Pro
Unity 2018.3.14.f1
AVPro Video - last trial version from official site

**Comment by MorrisRH** [comment]
It looks like something is off with your server setup, I'm seeing the following error returned when opening the first URL:
```byte range and no content length - error code is 200```

**Comment by AndrewRH** [comment]
Closing this old issue due to inactivity.
