### ISSUE TITLE
Youtube Streaming in Unity (issue)

### ISSUE THREAD

**Issue by ZargaryanHayk** [RenderHeads/UnityPlugin-AVProVideo#2030]
Hi,We have developed a program where users can select content from YouTube at home, and then watch it in the 2nd place.
At home, the patient selects a video, and our system stores the video link in a database, attaching a unique 4-digit number or QR code. In the 2nd placer, another system is connected to Smart Glasses that scans the QR code and streams the content from YouTube (we use the AvPro free version) using the same link directly to the glasses.
After six successful months of operation, the streaming has stopped working for the past two weeks. Did something change? Has anyone had a similar experience? Any help from the community would be greatly appreciated.

**Comment by Chris-RH** [comment]
Hi, 

We don't [support streaming from Youtube](https://renderheads.com/content/docs/AVProVideo-v3/articles/feature-streaming.html#youtube--facebook-live--twitch-support) as its against their T&C's.  We've not changed anything on that side, so its probably something that they have done.

If you have an AVPro Video issue to report, please fill in the full issue report form.
