### ISSUE TITLE
Upload Symbols Failed - The archive did not include a dSYM

### ISSUE THREAD

**Issue by tomashined** [RenderHeads/UnityPlugin-AVProVideo#2031]
Hello,

When submitting a project to TestFlight from Xcode, the following warning appears. It started appearing when I began working in Xcode 16. Could this be an issue with your plugin, or is it something on my side?

<img width="422" alt="Screenshot 2024-10-11 131558" src="https://github.com/user-attachments/assets/8794aff0-bd62-411c-b72c-352bb46b07c2">

AVPro Video - Core Edition 2.9.3

**Comment by Chris-RH** [comment]
Hi, 

You should be able to ignore this warning.  The app should still be able to go through.  Its just regarding debug symbols, which we haven't included in AVPro Video 2 or even AVPro Video 3 yet.  As AVPro Video version 2 has been depreciated, these will not ever be included.

**Comment by mossman07** [comment]
This error is not skippable, you can not upload to release an app without the dSYM file on iOS with the las version of XCode 16.3. AVPro needs a solution as soon as possible.

**Comment by sgm55** [comment]
Hi any updates on this? 
The error is not skippable and the upload to the app store fails. Our entire app's production is now stuck.
Is there anything we can do on our end? Or can you please provide a solution to this asap?
I am using AVPro Video 3.2.6 Core Mobile + XCode 16.3
