### ISSUE TITLE
Video doesn't play smoothly after playing for sometime and app becomes unresponsive

### ISSUE THREAD

**Issue by noman5412** [RenderHeads/UnityPlugin-AVProVideo#2032]
I have been testing this plugin for the last three months and I have been facing an issue while playing video on android phone, fps drops too much and sometimes to 1fps and app is completely halt. Android logcat doesn't show any of the error and i have been facing this issue on multiple devices. I am sharing every details with you so you can guide me if i am doing something wrong.

The video is placed on S3 and using cloudfront for this.
Moreover, I have downloaded the video on persistent datapath using DownloadHandler and playing from there but the issue is still there. [NEED HELP] 

**This issue is frequent on various devices except Samsung devices, atleast i didn't find**

Moreover, I have attached a file having android logs during this issue along with my project settings screenshots.

 - Unity version: 2021.3.5f1
 - AVPro Video version (3.0.11 (trial): 
 - Operating system version: Android
 - Device model: Redmi Note 12 and various other phones
 - Video specs (resolution, 30 fps, 200 mb, video length 19:34): 

[AndroidLogs.txt](https://github.com/user-attachments/files/17347027/AndroidLogs.txt)
![8](https://github.com/user-attachments/assets/8786ff70-fbf9-4acd-8594-b51242095409)
![7](https://github.com/user-attachments/assets/77eeb418-f0a9-4d33-9e17-abb9b9a7b316)
![6](https://github.com/user-attachments/assets/e818a977-f73c-4e1f-a453-9577c5498b97)
![5](https://github.com/user-attachments/assets/2051d55f-3228-4396-9681-ae148a5c253a)
![4](https://github.com/user-attachments/assets/a1cf860f-8b3b-4c54-91b5-9080946be48b)
![3](https://github.com/user-attachments/assets/d821cb39-52f7-4e0c-9fdc-9fcd8088bfd4)
![2](https://github.com/user-attachments/assets/71944537-2f59-422a-b3b4-34ae3fe0b415)
![1](https://github.com/user-attachments/assets/ba29b4a5-e097-4836-8fd2-8d40ea373426)

**Comment by Ste-RH** [comment]
Can you define ‘sometime’ ?

**Comment by noman5412** [comment]
> Can you define ‘sometime’ ?

Sometimes means almost everytime when the video is played for a longer time and seeking to different parts of videos frequently.
I am also emailing you the video link so you can check it yourself.

**Comment by Ste-RH** [comment]
We have tested your video here on a range of older Android hardware (oldest being a Remi Note 10S) and not seeing anything like you are reporting.

Some things of note:

- The log you sent says you are running AVPro Video v3.0.7, not the 3.0.11 you reported
- We notice you are running with the mono backend, please change this to IL2CPP

Please update to 3.0.11, IL2CPP, re-test and send over a new logcat if you are still seeing the issue.

**Comment by noman5412** [comment]
Thanks for your detailed response.
I have tested using IL2CPP and the problem seems resolved.
I am still curious why it was not working with mono.

**Comment by Ste-RH** [comment]
Mono does work, just a lot slower.  On some devices this can be cripplingly slow, depending on what your application is doing aside from video decoding - which is what you are seeing.

The mono runtime is a lot slower than IL2CPP (essentially this is compiled c++ code as opposed to 'compile at runtime').

See [here](https://www.reddit.com/r/Unity3D/comments/zag4ka/mono_or_il2cpp/) for good explanations of the difference and why Mono is slower than IL2CPP.

Also see [here](https://github.com/tbg10101/dotnet-burst-comparison) for the comparisons between them (note how Mono is vastly slower, taking many more cycles, than IL2CPP).
