### ISSUE TITLE
Interactive Video Implementation

### ISSUE THREAD

**Issue by noman5412** [RenderHeads/UnityPlugin-AVProVideo#2036]
I have been using trial version of AVPro in order to check the feasibility of an interactive video based app just like some interactive seasons and movies in netflix where user is given options to play a specific part of the video unlike linearly watching the entire video.
I have tried multiple solutions in AVPro but none of them work perfectly. 
Can you suggest a perfect way to implement this?

**Comment by Ste-RH** [comment]
I am afraid our support is not here to implement your use-case, or offer ideas on how you might go about it.

If you have a specific issue with the asset, please do provide all the information requested when you open a bug issue.
