### ISSUE TITLE
OVROverlay support on meta quest

### ISSUE THREAD

**Issue by realitygarage** [RenderHeads/UnityPlugin-AVProVideo#2039]
**Question**
Does you updated version support OVROverlay on the meta quest yet?

**Comment by realitygarage** [comment]
and are examples included? Would ideally like to see examples for 180, 360, and passthrough - using Meta's ovroverlay

**Comment by Chris-RH** [comment]
Hi @realitygarage, 

We haven't added support for it.  However some devs have managed to get it to work.  See [this thread](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/63) for more details.

**Comment by realitygarage** [comment]
Thanks  - Any plans to add support and examples? I had purchased the 1st and 2nd versions of avpro, but abonded the 2nd version w/o gthe vulken support, and no ability to get best quality video on the quest via the ovroverlay. A bit reluctant to drop another few hundred bucks on version 3, w/o knowing I can get the needed quality in the VR headset for 180, and 360, mono, and stereo videos. Also now keenly interested in the passthrough - but again would be great to get some samples/example scene with everything set up as such :)

**Comment by Chris-RH** [comment]
Keep an eye on the aforementioned thread, as it'll be updated if/when we do support it.  I suppose we'll decide at the time whether or not it requires a specific demo scene.  However its not a very commonly requested enhancement, and there is a workaround in the thread that seems successful, so its unlikely that we will specifically be adding support for it soon.
