### ISSUE TITLE
Play vertical format videos easily?

### ISSUE THREAD

**Issue by tleylan** [RenderHeads/UnityPlugin-AVProVideo#2043]
Hi. I have a video player and it plays YouTube videos. Some videos are in vertical format however and these will stretch wider to fit the screen. Is there a setting that can prevent this resizing and simply play with a darkened frame. I would like to reduce it down to a setting or perhaps a method or two if possible. I don't want to reformat the visible game object screen.

Thanks.

**Comment by Chris-RH** [comment]
[Display IMGUI](https://renderheads.com/content/docs/AVProVideo-v3/articles/component-display-imgui.html) and [Display UGUI ](https://renderheads.com/content/docs/AVProVideo-v3/articles/component-display-ugui.html)components have different scale modes.

**Comment by tleylan** [comment]
**Ah, thanks so much.** The Display UGUI would have worked (this is a VR app) but I'm using the VRChat version and I don't seem to have access to that component. The good news (for me) is I created 2 "screens" representing the 2 aspect ratios and I can easily swap the output between them. For now that works.
