### ISSUE TITLE
Video Timeline 

### ISSUE THREAD

**Issue by SamiNasirEuphoria** [RenderHeads/UnityPlugin-AVProVideo#2044]
**Question**how to get video open from previous timeline, instead of video playing from 00:00 in the same scene.

**Comment by Ste-RH** [comment]
Use:

_mediaPlayer.Control.Seek( timeMS );

**Comment by SamiNasirEuphoria** [comment]
private void InitializeVideoPlayer()
    {
        // Get the MediaPlayer instance
        videoPlayer = SceneManager.Instance.myMediaPlayer;
        // Assign the video player to the mesh media
        meshMedia.Player = videoPlayer;
        //Play video accordingly from proper path 
        videoPlayer.OpenMedia(new MediaPath(videoName + ".mp4", MediaPathType.RelativeToStreamingAssetsFolder), autoPlay: true);
        if (timeline >0)
        {
            SceneManager.Instance.myMediaPlayer.Control.Seek(timeline);
            Debug.Log("Resuming video from: " + timeline + " seconds.");
        }
      
        //this line of code is used to load videos from local storage of meta
        //videoPlayer.OpenMedia(new MediaPath("/sdcard/Movies/" + videoName + ".mp4", MediaPathType.AbsolutePathOrURL), autoPlay: true);
    }
    
    
    
   But actually it is not working

**Comment by Ste-RH** [comment]
You need to do one or both of the following:

1) Enable external access (Player Settings):

![image](https://github.com/user-attachments/assets/7fbae8e7-0b08-4ecf-af7a-985289c983ad)

2) You path might not be correct.  Try this:

		using var envClass = new UnityEngine.AndroidJavaClass("android.os.Environment");
		using var moviesDir = envClass.CallStatic<UnityEngine.AndroidJavaObject>("getExternalStoragePublicDirectory", "Movies");
		string moviesPath = moviesDir.Call<string>("getAbsolutePath");
		videoPlayer.OpenMedia(new MediaPath(moviesPath  + "/MyVideo.mp4", MediaPathType.RelativeToStreamingAssetsFolder), autoPlay: true);

**Comment by SamiNasirEuphoria** [comment]
i have already enabled this bool in unity>Settings>Player Setting.

i am running application in editor? could it be the cause?
Actually MediaPlayer.OpenMedia(param) this method pick up video from start placed in drive.

and i have only media player object and at runtime, video will get loaded on user's choice.

is there anything i'm missing?
