### ISSUE TITLE
The video will pause while buffering

### ISSUE THREAD

**Issue by shenxiaobai1001** [RenderHeads/UnityPlugin-AVProVideo#2045]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
sorry， I'm a new developer。
I load the video from the url and then start playing the video after receiving the FinishedBuffering event, with no other Settings
Now I find that every time the video plays for a period of time, it will start buffering and pause the video playback, and then continue after the buffering ends, which greatly affects the experience.
May I ask if there is any way to make it buffer the whole video completely, or make it buffer while playing? If there is any other way, please inform me

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![image](https://github.com/user-attachments/assets/688031e1-c025-4615-848b-d642ee70f635)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Chris-RH** [comment]
Hi, 

Is this an adaptive HLS or DASH stream, or is it an mp4 stream?

**Comment by shenxiaobai1001** [comment]
.mp4

**Comment by shenxiaobai1001** [comment]
I have a question, avvideopro version for 3.0.1, mediaPlayer. PlatformOptionsAndroid. VideoApi = = ExoPlayer
But after I pack the android platform=》 mediaPlayer. Cache. IsMediaCachingSupported () == false,

**Comment by Ste-RH** [comment]
> I have a question, avvideopro version for 3.0.1, mediaPlayer. PlatformOptionsAndroid. VideoApi = = ExoPlayer But after I pack the android platform=》 mediaPlayer. Cache. IsMediaCachingSupported () == false,

What edition of AVPro Video do you own a license for?  Caching is an Ultra only feature.

In addition, I believe this was a bug early on in v3.x history, please update to the latest version and check again as I am 95% certain we addressed this after v3.0.1

**Comment by Ste-RH** [comment]
> .mp4

I think you have answered your own question here.  MP4 files are not meant for streaming from a server.  You might get away with lower resolution/bitrate videos, and will certainly want to make sure they are encoded with the faststart flag (else the whole file would need to be downloaded prior to playback starting).

If you must use MP4 video files, then using the caching feature is your best option (as you have already found).  That way you can start a download and playback from cache as it is downloaded.  This will not guarantee no 'buffering' phases, as this is at the mercy of your server and local download capability.  Downloading the whole MP4 to device via caching features would guarantee zero buffering moments though.

**Comment by Ste-RH** [comment]
We will be closing this issue soon due to lack of response.
