### ISSUE TITLE
FirstFrameReady is called only sometimes after OpenMedia on Android

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#2049]
**Describe the issue**
To avoid black frames we have a MediaPlayer running OpenMedia() and wait until the event FirstFrameReady is called.
Then we make the switch. 
We now encountered the issue that FirstFrameReady Event is only sometimes not called, thus we wait forever.
Waiting for ReadyToPlay is not an option, because this can cause blackframes.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.24f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 3.0.11 Ultra
 - Operating system version: Android 14
 - Device model: Samsung S22 Ultra
 - Video specs (resolution, frame-rate, codec, file size): MP4 - H264, 1920x1080, 30fps, 11Mb

**To Reproduce**
1. Disable Auto Open and Auto Play, then use OpenMedia to open a file (AbsolutePathOrURL) from persistentDataPath.
2. Expected: FirstFrameReady event to be invoked, but this does not always happen, only ReadyToPlay is invoked then
3. After ReadyToPlay, waiting for a few seconds but still no FirstFrameReady is invoked, I force the video to Play the FirstFrameReady is invoked right immediately when playing starts.

**Comment by Chris-RH** [comment]
Could you upgrade to AVPro Video version 3.1 and retest please, because we had quite big changes for Android. :)

**Comment by RuudvanReenen** [comment]
Awesome, thanks!

**Comment by Ste-RH** [comment]
AVPro Video v3.1.1 has just been released.  Please do let us know if this fixes your issue.
