### ISSUE TITLE
DirectShow Preferred Filters

### ISSUE THREAD

**Issue by tp-105** [RenderHeads/UnityPlugin-AVProVideo#205]
I have LAVFilter installed and when I run a video, the LAVFilter tray icon shows up.

I want to bypass LAVFilter and use Windows's default decoder, but no matter what I set to the preferred filters list, LAVFilter icon still show up which indicates to me that it's not using Windows default decoder.

Using this straight up crash the app:
Microsoft DTV-DVD Video Decoder

Using these and LAVFilter icon still show up:
Mpeg4s Decoder DMO
Microsoft MPEG-2 Video Decoder
Windows Media Source Filter

There's very little documentation to this feature so I'm not sure if these are the correct string to use.

 - Unity version: 2017.4.22f1
 - AVPro Video version: 1.8.8
 - Operating system version: Windows 10 
 - Device model: Alienware
 - Video specs: Codec: 
MPEG-4 Video (mp4v)
Video resolution: 1280x720
Frame rate: 60

**Comment by AndrewRH** [comment]
So LAV usually uses 3 types of filters:

1) file splitter
2) video decoder
3) audio decoder

So even if you force a different video codec, it will still be using LAV for the file splitter / audio decoder.    You should be able to disable the system tray via the configuration apps...and I think also this might be an option during installation if I remember correctly.

It sounds strange that using "Microsoft DTV-DVD Video Decoder" would crash the app.  We haven't seen that before.

It's possible that there's a bug in that old version of the AVPro Video plugin as 1.8.8 is quite old.  You could try to upgrade to the latest version of the plugin.
