### ISSUE TITLE
Playback stops after some time Unity 6

### ISSUE THREAD

**Issue by javdavalos** [RenderHeads/UnityPlugin-AVProVideo#2050]
I'm streaming a video file on a Vision OS project built in Unity 6.after 1 or 2 minutes of playing , it stops silently. No warnings errors or nothing, just stops.
Happens on device and in the unity editor.

using hte trial version, unless the trial stops on purpose?

**Comment by Chris-RH** [comment]
Please fill in all the information in the issues form. Include platform and
OS version of editor computer.
Can this be reproduced in a new project only running the demo scenes?
Have you tried different videos and streams?
