### ISSUE TITLE
Image quality and framerate on Meta Quest significantly lower in AVPro versus Meta TV app

### ISSUE THREAD

**Issue by charlesingea** [RenderHeads/UnityPlugin-AVProVideo#2053]
**Describe the issue**
I am trying to wrap my head around how to get the best video quality and framerate on Meta Quest using AVPro. I've built a very simple video player Unity project using OES and the supplied shader for 180 video. I am using an H265 8192x4096 side-by-side stereo video at 30fps. When I run the same video in my Unity app and compare it to the built-in Meta TV app, the resolution I get is lower and the framerate is not as smooth. Is it possible to get as good a quality as the Meta TV app or is this as good as it gets?

**Your Setup (please complete the following information):**
 - Unity version: 2022.3.46f1
 - AVPro Video version: AVPro Video v3 - Ultra Edition
 - Device model: Meta Quest 3
 - Video specs (resolution, frame-rate, codec, file size): 8192x4096, 30fps, H265, 1.81GB

**Comment by Chris-RH** [comment]
Unity is a powerful 3d engine, so will naturally have more overheads than a lightweight purpose-built app.
As it is, you're pretty much at the top of [recommended maximum](https://headjack.io/knowledge-base/best-video-resolution-for-oculus-quest-2/) [video specs](https://creator.oculus.com/getting-started/media-production-specifications-for-delivery-to-meta-quest-2-headsets/).

**Comment by MorrisRH** [comment]
Make sure you're using the OpenGLES 3 renderer and have set the MediaPlayer's texture format to 'YCbCr 420_OES' (as shown below) in order for the player to be as performant as possible.

<img width="797" alt="Screenshot 2024-11-01 at 14 04 48" src="https://github.com/user-attachments/assets/60ceeaf8-7156-4afb-8274-0197ddc626f9">
