### ISSUE TITLE
Want to load three videos simultaneously display one of them at a time depending upon user!

### ISSUE THREAD

**Issue by noman5412** [RenderHeads/UnityPlugin-AVProVideo#2054]
I want to load three different videos simultaneously and display one of them at a time depending upon what user selects!
Should i use 3 different MediaPlayer along with one displayUGUI and switching between them or is there any option through which i can do switching **seamlessly** between different videos using only one MediaPlayer?
Moreover, loading more than one video is okay? in terms of performance etc.

**Comment by Chris-RH** [comment]
It depends on a lot of factors such as platform, device, and video specs.
Generally, for improved transitions, we'd recommend using multiple mediaplayer components - see our [playlist demo scene](https://renderheads.com/content/docs/AVProVideo-v3/articles/usage-demos.html#playlist-demo).
The ability to load multiple videos depends on the video specs and the device that you are using.  For example  Older devices may struggle.  Higher resolution videos will use up more resources. etc
