### ISSUE TITLE
UDP h264 video stream

### ISSUE THREAD

**Issue by edevdoge** [RenderHeads/UnityPlugin-AVProVideo#2056]
Hi! Is it possible to receive a UDP h264 video stream on the Android platform (Oculus Quest 3) using AVProVideo?
Stream is sent to specified IP and port in local network. I've tried to receive it using absolute path udp://@:5000 but nothing works. I just get "File not found, codec not supported, video resolution too high or insufficient system resources".
Thanks!

**Comment by Ste-RH** [comment]
I think it might be possible to playback over UDP, but it depends on what's underneath.

See [here](https://developer.android.com/media/media3/exoplayer/supported-formats#supported_network_types) and [here](https://www.reddit.com/r/androiddev/comments/15hos20/displaying_a_udp_video_stream_on_android_with/).

**Comment by edevdoge** [comment]
So, I've tried sending stream with ffmpeg and gstreamer commands:
1. ffmpeg -re -i D:/test.mp4 -c:v libx264 -preset ultrafast -tune zerolatency -f mpegts -omit_video_pes_length 1 udp://<IP>:<port>
2. ffmpeg -re -i D:/test.mp4 -c:v libx264 -preset ultrafast -tune zerolatency -f h264 omit_video_pes_length 1 udp://<IP>:<port>
3. gst-launch-1.0 filesrc location=D:/test.mp4 ! decodebin ! x264enc tune=zerolatency ! mpegtsmux ! udpsink host=<IP> port=<port>      
With the first stream-send command it could be received in android build. The second and the third commands were unsuccessful. But the first command uses MPEG-TS for output and I need h264

**Comment by Ste-RH** [comment]
All the examples of serving over upd via ffmped all use mpegts but that is the just the container format.  Your frames are still going to be h264 as you are forcing that with -c:v.  -f h264 is invalid as it is not a container format. -f mp4 would be valid, but I suspect you would need a fragmented mp4 format as opposed to just mp4...and I cannot find reference to ffmpeg supporting that.

Conclusion, your first command will be serving up h264 video frames, just in the format of mpegts.
