### ISSUE TITLE
[Android] First Frame Ready invoked when closing the player

### ISSUE THREAD

**Issue by bentalebahmed** [RenderHeads/UnityPlugin-AVProVideo#2065]
### Unity version

2021.3.18f1

### Unity editor platform

Windows

### AVPro Video edition

Core

### AVPro Video version

Core Mobile Edition version 3.011

### Device hardware

PICO 4 enterprise

### Which Android OS version are you using?

10

### Unity Graphics API

OpenGLES 3

### Video API

media3/ExoPlayer

### Texture format

Y Cb Cr 420_OES

### Audio output

Unity

### Which output component(s) are you using?

Apply to Mesh

### The issue

When I start the player, I get the First Frame Ready event, but when I close the player, I also get the First Frame Ready event on my Unity VR app using Pico 4

**Comment by Chris-RH** [comment]
Can you provide a full, unfiltered logcat in txt format please, showing all the events.

**Comment by bentalebahmed** [comment]
Here is the logcat, I player a video in flat screen after that I did another as a 360 video
[logcat.txt](https://github.com/user-attachments/files/17679493/logcat.txt)

**Comment by Chris-RH** [comment]
Could you provide an unfiltered logcat please

**Comment by Ste-RH** [comment]
We have put a fix in for this.  It will be available in the next release (v3.1.3).

**Comment by Ste-RH** [comment]
Re-openeing - we will close when release is out and fix confirmed with yourself @bentalebahmed  :)

**Comment by Chris-RH** [comment]
AVPro Video version 3.1.3 has been released. Please let us know if it has not fixed your issue.

**Comment by bentalebahmed** [comment]
i just have tested it, bug fixed.
