### ISSUE TITLE
[Question] Immediate Start for 20+ Players

### ISSUE THREAD

**Issue by AlexeyPechnikov** [RenderHeads/UnityPlugin-AVProVideo#2069]
### AVPro Video Version

recent trial

### Which platform is your question for?

Android, iOS

### Your question

Even with just 3 players using low-resolution (240p) HLS video, each player starts with noticeable delays between them. When setting a small start buffer (e.g., 500ms) to enable quick startup for multiple HLS players, the app crashes. Is there a way to initialize multiple players to start immediately upon app launch without significant delay?

**Comment by Chris-RH** [comment]
You've not given any information as to what hardware you are using, nor the specs of the videos, so I'm just going to answer broadly regarding playing multiple videos.

The fundamental problem is that a lot of devices cannot play multiple videos at once. Some Android devices can only provide only one decoder instance at a time to an app, some can offer multiple but with a limit. This varies per device and there is no consistent behaviour (as of Android 12 there is some improvement - see next paragraph). ExoPlayer takes a conservative approach, and only occupies one codec instance at a time, e.g. when moving between items in a playlist ExoPlayer makes sure to first release a codec before acquiring the next one.

The general suggestion is to ensure you have only one player instance at a time playing video, if not having one instance in total in your app. On Android 12, the platform introduced the [performance class](https://developer.android.com/topic/performance/performance-class) by which an app can figure out if the device can provide multiple decoders concurrently, hence the app can do multiple playbacks.

You want to make sure that you have the videos opened (and therefore buffering) first, and then trigger them to play.

To get a better idea of what is happening, some more information about your use case would be helpful as well as a full, unfiltered logcat.

**Comment by AlexeyPechnikov** [comment]
Hi @Chris-RH,

As mentioned earlier, I’m interested in handling video streams on iOS and Android devices, specifically for low-res 240p HLS. Since the AVPro demo includes examples with multiple (2-3) players, I’m exploring the feasibility of scaling this up to support 20+ players. The test setup can be a rotating icosahedron with 20 video streams mapped to its faces. Upon opening the app, the rotating icosahedron is immediately visible, with each of its faces displaying different live video streams, each playing independently on every visible face. Do you have any recommendations on implementing this on Android 12+ and iOS devices? Is this possible with AVPro, or should we consider using a different video player?

Additionally, I’ve encountered an issue with preventing shadows from video players on mesh surfaces. Standard approaches (such as using transparent materials and assigning a layer ignored by the light source) haven’t resolved this. Would it be best to raise this question in a separate ticket?

**Comment by Chris-RH** [comment]
OK, so its pretty much down to the limitations of the hardware that will cause the issue.  So you are likely to face the same issues, whichever player you are using.

- As mentioned previously, the decoding ability of an Android device does vary considerably, so older or low end devices will struggle with this more.
- There is also the issue of HLS traffic.  The more videos that you are trying to play concurrently, the more bandwidth required.
- I think in the past we have seen up to 9 concurrent videos, but that is stretching it.

1. Playing videos locally will eliminate the bandwidth issue, or you could use a mix of both local and streamed.
2. Using software decode for some videos and hardware decode on others will also help, BUT it may cause framerate issues.
3. You could make videos open and start when they are facing the users, and closing when they are not.  By closing the players it should allow you to release the codec and allow it to be used by another player.

And yes, a separate full bug report for the other issue please :)

**Comment by AlexeyPechnikov** [comment]
Hi @Chris-RH 

Could you provide some estimates? For example, the number of streams feasible for mid-range devices from 2022 onward or high-range devices from 2020 and later.

I’m assuming a bandwidth of around 400 kbps for 240p HLS video, while 1080p might require up to 8 Mbps. This suggests that 20 parallel 240p streams would be roughly equivalent to a single 1080p stream, which is why I’m curious about support for around 20 streams and players.

Would adjusting the frame rate make a noticeable difference? I’m considering the possibility of using lower frame rates for non-central faces of the icosahedron.

Also, how do standard video conferencing apps handle multiple low-resolution streams? I haven’t used these on Android, but I imagine they perform similarly across platforms. How do apps like Discord or Telegram manage to display multiple streams simultaneously?

**Comment by Chris-RH** [comment]
The last time I used video conferencing on my android device, it limited the amount of video participants that I could see.  It was far fewer than when I've used my PC for the same thing (Discord, WhatsApp, Zoom, Teams).

Assuming you have some devices in hand, I think this is something that you need to play around with yourself.  Compare the results that you might get from Unity's video player.

**Comment by Ste-RH** [comment]
Whilst we cannot pretend to know what such applications do to provide solutions...one option they might implement is to combine all feeds into a single served video to the user.  But, as Chris says, on mobile I am not aware of mass video feeds simultaneously.

20+ is simply unachievable as single videos. regardless of how modern the hardware is.  The only possible thing to try is using software decoding.  This will come (at some point) with massive CPU overheads which will destroy app frame-rate, battery, and heat up the device over a prolonged period of time.

As this is a ultimately a limitation of hardware, and not the AVPro Video asset, we can offer no further assistance I am afraid.
