### ISSUE TITLE
[Android] When the media player starts playing, any other sound disappears

### ISSUE THREAD

**Issue by IgorKubyshkin** [RenderHeads/UnityPlugin-AVProVideo#2076]
### Unity version

2022.3.32f1

### Unity editor platform

Windows

### AVPro Video edition

Core

### AVPro Video version

3.1.2

### Device hardware

realme 8i

### Which Android OS version are you using?

13

### Unity Graphics API

OpenGLES 3, Vulkan

### Video API

MediaPlayer

### Texture format

BGRA

### Audio output

Unity

### The issue

When the media player starts playing a video, any other sound (except directly video sound) disappears and does not even return after the video is closed. If you minimize/expand the application (pause/unpause), the sound will be restored. There was no such problem in the previous version (3.0.8) of the plugin I used. When playing the video again after the application has returned from background mode, the sound no longer disappears, i.e. it starts working as expected.

**Comment by Chris-RH** [comment]
We've done a quick test and can't reproduce this.

1. What do you mean by "any other sound"? Do you mean other sounds coming from your app, or do you mean other sounds that are also playing on your phone? Or something else?
2. Have you tested it on any other devices, and if so, does the error still occur?
3. Which audio output are you using? System Direct/Unity/FB360, and does it occur in the others?
4. Does this also occur when Video API is set to 'Exoplayer'?
5. Can it be reproduced in a new project running only AVPro Video demo scenes?
6. Can you provide a step by step of how to reproduce this please?

**Comment by Ste-RH** [comment]
<last post deleted>

Please do not post up projects.  Instead, email them to unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
What scene should we run to reproduce the issue?

**Comment by Ste-RH** [comment]
The test project you sent uses v3.1.0, not 3.1.2 as you initially stated.

**Comment by Ste-RH** [comment]
In 'OnPostGenerateGradleAndroidProject( string path )'

...why is the call to 'GradleMainTemplate( path );' commented out?  That is why ExoPlayer does not work.

I have reproduced it in your project/scene.  I will look into why, but as could not reproduce this in our Demo_MediaPlayer scene...I am wondering if it is something specific to your scene/project.

**Comment by Ste-RH** [comment]
Yup, just found the same looking at the differences.  Disable it and it works fine.

We have made no changes in the MediaPlayer API path regarding this, so I am reluctant to call this an AVPro Video issue.  I am going to try v3.0.8 myself to verify.

![image](https://github.com/user-attachments/assets/8534089c-0b91-4e5d-a5eb-95217a0a7219)

**Comment by Ste-RH** [comment]
Verified that audio still works with that flag enabled in 3.0.8 + 3.0.9 + 3.0.10 + 3.0.11.  It fails in 3.1.0 - which is when we updated to media3 v1.4.1 - and 3.1.1 + 3.1.2.

There is not much I can think of by way of reason as media3 is not even being initialised...and in your project you have completely removed the dependencies with the script change.

**Comment by Ste-RH** [comment]
Why do you want 3.0.11?

**Comment by Ste-RH** [comment]
If you email your Unity PDF invoice over to unitysupport@renderheads.com we can send send over 3.0.11

**Comment by Ste-RH** [comment]
It looks like this issue has come about due to us adding in code to gain focus from the audio manager.  We need to do this to catch when the OS takes focus for such things as incoming calls, alarms, etc.  When this happens, we action a pause on all videos.  Then, when focus is regained, we play those videos that were paused when focus was relinquished earlier.

Currently, we have no solution to satisfy both cases.

**Comment by Ste-RH** [comment]
In terms of your use-case @IgorKubyshkin .  Applications that contain AVPro v3.1.0 onwards will obtain audio focus.  This in essence is automatically performing the same job as 'mute other audio sources', and so you can safely remove this option and continue to use the latest version of AVPro Video.
