### ISSUE TITLE
[Question] Why Isn't My HLS Stream Playing Newly Downloaded .ts Files After Dynamic Update?

### ISSUE THREAD

**Issue by ViSDK** [RenderHeads/UnityPlugin-AVProVideo#2078]
### Your question

Hello, I have a question about HLS. Let's say I generate a complete .m3u8 file in advance, which contains 4 .ts file paths: D:/1.ts, D:/2.ts, D:/3.ts, and D:/4.ts. However, only 1.ts and 2.ts are available on the D drive. Now, while playing 1.ts, I manage to download 3.ts and 4.ts and place them on the D drive. However, I notice that the video does not play 3.ts and 4.ts. How can I resolve this?

**Comment by MorrisRH** [comment]
You should look to use an EVENT playlist type (one with no EXT-X-ENDLIST tag and optionally EXT-X-PLAYLIST-TYPE:EVENT set) if you're not going to have all segments available when playback starts. You could then update the playlist as each new segment becomes available.

With a VOD playlist (#EXT-X-PLAYLIST-TYPE:VOD) it is expected that all segments are available. I expect your segment length is short enough that the player tried to start buffering 3.ts and 4.ts before that became available and as it couldn't find them removed them from the playlist.

**Comment by ViSDK** [comment]
> You should look to use an EVENT playlist type (one with no EXT-X-ENDLIST tag and optionally EXT-X-PLAYLIST-TYPE:EVENT set) if you're not going to have all segments available when playback starts. You could then update the playlist as each new segment becomes available.
> 
> With a VOD playlist (EXT-X-PLAYLIST-TYPE:VOD) it is expected that all segments are available. I expect your segment length is short enough that the player tried to start buffering 3.ts and 4.ts before they became available and as it couldn't find them removed them from the playlist.

----------------------------------------------------------------------------------------------------------------------------------------------
Thank you for your response. You mentioned 'You could then update the playlist as each new segment becomes available.' So how can I update the playlist within the AVProVideo plugin? The playlist is a .m3u8 file, and this file gets locked when OpenMedia is called, so I can't modify its contents.

**Comment by MorrisRH** [comment]
Not sure what can be done about this. The low-level windows API is locking the file so we have no way to prevent this behaviour.
