### ISSUE TITLE
[Android] gradle issue when building

### ISSUE THREAD

**Issue by Cobrakinggames** [RenderHeads/UnityPlugin-AVProVideo#2081]
### Unity version

2023.2.20

### Unity editor platform

Windows

### AVPro Video edition

Core

### AVPro Video version

3.1.3

### Device hardware

Unity

### Which Android OS version are you using?

8

### Unity Graphics API

OpenGLES 3

### Video API

media3/ExoPlayer

### Texture format

BGRA

### Audio output

System Direct

### Any other Media Player component configuration required to reproduce the issue.

no

### The issue

after updating  AVPRO

FAILURE: Build failed with an exception.
 
* Where:
Build file 'D:\ACEPLUS\NEW AVPRO\ACEPLUS_AVPRO NEW\ACEPLUS_AVPRO NEW\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\build.gradle' line: 10
 
* What went wrong:
A problem occurred evaluating project ':unityLibrary'.
> Could not find method implementation() for arguments [androidx.media3:media3-common:1.4.1] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.

**Comment by PradeepSymb** [comment]
I am also facing same issue while upgrading AVpro from 2.9.1 to 3.1.3

stderr[

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pradeepkumar/Downloads/CleverTapWithWebView/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/build.gradle' line: 10

* What went wrong:
A problem occurred evaluating project ':unityLibrary'.
> Could not find method implementation() for arguments [androidx.media3:media3-common:1.4.1] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
]
stdout[

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings
]
exit code: 1

**Comment by Cobrakinggames** [comment]
buildscript {
repositories {
google()
mavenCentral()
}
dependencies {
classpath 'com.android.tools.build:gradle:8.1.0' // Updated Android Gradle
Plugin version
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'
}
}

apply plugin: 'com.android.library'
apply plugin: 'com.google.firebase.crashlytics'

repositories {
google()
mavenCentral()
}

task wrapper(type: Wrapper) {
gradleVersion = '8.3' // Latest Gradle version
distributionUrl = '
https://services.gradle.org/distributions/gradle-8.3-all.zip'
}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation
'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
implementation 'androidx.core:core:1.1.0'
implementation 'androidx.appcompat:appcompat:1.3.1'
implementation 'com.google.android.gms:play-services-auth-api-phone:18.0.1'
implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
implementation 'com.google.android.gms:play-services-base:18.4.0'
implementation 'com.google.firebase:firebase-analytics:22.0.0'
implementation 'com.google.firebase:firebase-app-unity:12.0.0'
implementation 'com.google.firebase:firebase-common:21.0.0'
implementation 'com.google.firebase:firebase-crashlytics-ndk:19.0.0'
implementation 'com.google.firebase:firebase-crashlytics-unity:12.0.0'
implementation 'com.google.firebase:firebase-iid:21.1.0'
implementation 'com.google.firebase:firebase-messaging:24.0.0'
implementation 'com.google.firebase:firebase-messaging-unity:12.0.0'
implementation 'com.google.flatbuffers:flatbuffers-java:1.12.0'
implementation 'com.unity3d.mediation:mediation-sdk:[1.0,2.0['
implementation 'com.unity3d.mediation:unityads-adapter:[1.0,2.0['
//implementation 'com.unity3d.mediation:mediation-sdk:1.+'
//implementation 'com.unity3d.mediation:unityads-adapter:1.+'
implementation 'androidx.browser:browser:1.2.0'
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21'
}

android {
compileSdkVersion 35 // Replace with actual API version
buildToolsVersion '35.0.0' // Replace with the correct build tools version

defaultConfig {
    minSdkVersion 26 // Replace with minimum SDK version
    targetSdkVersion 35 // Replace with target SDK version
}

ndkPath "**NDKPATH**" // Update this to the correct NDK path
namespace "com.unity3d.player"

compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}

lint {
    abortOnError false
}

packagingOptions {
    resources {
        excludes += [
            'META-INF/DEPENDENCIES',
            'META-INF/LICENSE',
            'META-INF/LICENSE.txt',
            'META-INF/license.txt',
            'META-INF/NOTICE',
            'META-INF/NOTICE.txt',
            'META-INF/notice.txt',
            'META-INF/ASL2.0',
            '/lib/armeabi/**',
            '/lib/mips/**',
            '/lib/mips64/**',
            '/lib/x86/**',
            '/lib/x86_64/**'
        ]
    }
}


aaptOptions {
noCompress += ['.unity3d', '.ress', '.resource', '.obb', '.bundle',
'.unityexp'] + unityStreamingAssets.tokenize(', ')
ignoreAssetsPattern =
"!*.svn:!*.git:!*.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!~"

}

}

*IL_CPP_BUILD_SETUP*
*SOURCE_BUILD_SETUP*
*EXTERNAL_SOURCES*
// Android Resolver Exclusions End

// IL_CPP_BUILD_SETUP
// SOURCE_BUILD_SETUP
// EXTERNAL_SOURCES

here it is

**Comment by PradeepSymb** [comment]
buildscript {
	repositories {
		google()
		mavenCentral()
	}
	dependencies {
		classpath 'com.android.tools.build:gradle:8.1.0' // Updated Android Gradle Plugin version
		classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'
	}
	implementation 'androidx.media3:media3-common:1.4.1'
	implementation 'androidx.media3:media3-container:1.4.1'
	implementation 'androidx.media3:media3-database:1.4.1'
	implementation 'androidx.media3:media3-datasource:1.4.1'
	implementation 'androidx.media3:media3-datasource-cronet:1.4.1'
	implementation 'androidx.media3:media3-datasource-okhttp:1.4.1'
	implementation 'androidx.media3:media3-datasource-rtmp:1.4.1'
	implementation 'androidx.media3:media3-decoder:1.4.1'
	implementation 'androidx.media3:media3-extractor:1.4.1'
	implementation 'androidx.media3:media3-exoplayer:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-dash:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-hls:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-rtsp:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-smoothstreaming:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-workmanager:1.4.1'
}

dependencies.constraints { implementation( "com.google.guava:guava" ) { attributes { attribute( Attribute.of( "org.gradle.jvm.environment", String ), "standard-jvm" ) } } }

apply plugin: 'com.android.library'
apply plugin: 'com.google.firebase.crashlytics'
repositories {
	google()
	mavenCentral()
}
task wrapper(type: Wrapper) {
	gradleVersion = '8.3' // Latest Gradle version
	distributionUrl = 'https://services.gradle.org/distributions/gradle-8.3-all.zip'
}
dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
	implementation 'androidx.core:core:1.1.0'
	implementation 'androidx.appcompat:appcompat:1.3.1'
	implementation 'com.google.android.gms:play-services-auth-api-phone:18.0.1'
	implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
	implementation 'com.google.android.gms:play-services-base:18.4.0'
	implementation 'com.google.firebase:firebase-analytics:22.0.0'
	implementation 'com.google.firebase:firebase-app-unity:12.0.0'
	implementation 'com.google.firebase:firebase-common:21.0.0'
	implementation 'com.google.firebase:firebase-crashlytics-ndk:19.0.0'
	implementation 'com.google.firebase:firebase-crashlytics-unity:12.0.0'
	implementation 'com.google.firebase:firebase-iid:21.1.0'
	implementation 'com.google.firebase:firebase-messaging:24.0.0'
	implementation 'com.google.firebase:firebase-messaging-unity:12.0.0'
	implementation 'com.google.flatbuffers:flatbuffers-java:1.12.0'
	implementation 'com.unity3d.mediation:mediation-sdk:[1.0,2.0['
	implementation 'com.unity3d.mediation:unityads-adapter:[1.0,2.0['
	//implementation 'com.unity3d.mediation:mediation-sdk:1.+'
	//implementation 'com.unity3d.mediation:unityads-adapter:1.+'
	implementation 'androidx.browser:browser:1.2.0'
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21'
}
android {
	compileSdkVersion 35 // Replace with actual API version
	buildToolsVersion '35.0.0' // Replace with the correct build tools version
	defaultConfig {
		minSdkVersion 26 // Replace with minimum SDK version
		targetSdkVersion 35 // Replace with target SDK version
	}
	ndkPath "/Applications/Unity/Hub/Editor/2023.2.20f1/PlaybackEngines/AndroidPlayer/NDK" // Update this to the correct NDK path
	namespace "com.unity3d.player"
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_11
		targetCompatibility JavaVersion.VERSION_11
	}
	lint {
		abortOnError false
	}
	packagingOptions {
		resources {
			excludes += [
			'META-INF/DEPENDENCIES',
			'META-INF/LICENSE',
			'META-INF/LICENSE.txt',
			'META-INF/license.txt',
			'META-INF/NOTICE',
			'META-INF/NOTICE.txt',
			'META-INF/notice.txt',
			'META-INF/ASL2.0',
			'/lib/armeabi/**',
			'/lib/mips/**',
			'/lib/mips64/**',
			'/lib/x86/**',
			'/lib/x86_64/**'
			]
		}
	}
	aaptOptions {
		noCompress += ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp'] + unityStreamingAssets.tokenize(', ')
		ignoreAssetsPattern = "!*.svn:!*.git:!*.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!~"
	}
}
// Android Resolver Exclusions End
// IL_CPP_BUILD_SETUP
// SOURCE_BUILD_SETUP
// EXTERNAL_SOURCES


Tthis is my build.gradle file which is being generated by mainTemplate.gradle and giving this error

@Chris-RH

**Comment by Chris-RH** [comment]
@Cobrakinggames 

Which version did you upgrade from?

**Comment by Cobrakinggames** [comment]
unity 2023.3.20
avpro  2.9.1 to  3.1.3

**Comment by Ste-RH** [comment]
@Cobrakinggames @PradeepSymb Are you from the same company?  Or is this potentially two different issues?

Have you followed the update routine from 2.x to 3.x?

![image](https://github.com/user-attachments/assets/2b9cc41e-dac4-4cce-b02b-e77b7a110549)

**Comment by Cobrakinggames** [comment]
yes we are from same company after i do 2.x to 3.x i got platform errors
that platforms are not supported

**Comment by Ste-RH** [comment]
Ok, cool.  Thanks for confirming.

You need to set Unity to compile against API 34 or higher.

If you change it in the 'Player Settings', you will then be prompted to 'Update'.  Select this, then build again.

![image](https://github.com/user-attachments/assets/f1d51e20-b287-4196-98a4-a41dc5451a86)

**Comment by Cobrakinggames** [comment]
Thanks For Replay But after doing same steps i got same errors

[image: image.png]

**Comment by Cobrakinggames** [comment]
Thanks For replied
[image: image.png]

**Comment by Cobrakinggames** [comment]
Still hot same error in unity

**Comment by Ste-RH** [comment]
Can you paste in the complete error that is logged?

**Comment by Ste-RH** [comment]
Can you reproduce the issue in a new project?

Are you using any 3rd party libs/sdks? (Flutter, etc)

**Comment by Cobrakinggames** [comment]
Here is the Error And We Are not using any 3rd party libs we are using
clevertap , firebase

error CS0246: The type or namespace name 'PlatformMediaPlayer' could not be
found

**Comment by Ste-RH** [comment]
That looks like you have not imported or updated (v2.x to v3.x process mentioned earlier with a screen shot) correctly. 'PlatformMediaPlayer' is a new script in v3.x that did not exist in v2.x

**Comment by Cobrakinggames** [comment]
can you give me correct steps tp updated v2x to 3x

**Comment by Chris-RH** [comment]
Upgrade steps are in the [documentation](https://www.renderheads.com/content/docs/AVProVideo-v3/articles/upgrading-from-avpro-video-2x.html).

**Comment by Cobrakinggames** [comment]
after follow documentations step  I got same error

FAILURE: Build failed with an exception.

* Where:
Build file
'D:\ACEPLUS\AVPRO\AVPRO\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary\build.gradle'
line: 10

* What went wrong:
A problem occurred evaluating project ':unityLibrary'.
> Could not find method implementation() for arguments
[androidx.media3:media3-common:1.4.1] on object of type
org.gradle.api.internal.initialization.DefaultScriptHandler.

**Comment by Ste-RH** [comment]
Have you tried the process in a new project?

**Comment by Cobrakinggames** [comment]
Yes, I did.

**Comment by Cobrakinggames** [comment]
it's working fine because in that i not use any other things like main
template not selected

**Comment by Ste-RH** [comment]
I am sorry to say, but your posts are a mess and we did not see you are using custom template files.  Can you please attach all files (as files, not text) here and a screen shot of your 'Publisher Settings' please?

**Comment by Cobrakinggames** [comment]
here is the screenshot of publisher settings
[image: Capture.PNG]

**Comment by Cobrakinggames** [comment]
Now check

**Comment by Cobrakinggames** [comment]
![Capture](https://github.com/user-attachments/assets/492c9b6a-183d-4549-8de7-476c63e62671)

**Comment by Ste-RH** [comment]
Cool, that came through.  Can you now attach in those 5 template files please?

**Comment by Cobrakinggames** [comment]
[Android.zip](https://github.com/user-attachments/files/17920939/Android.zip)

here is all the file

**Comment by Ste-RH** [comment]
Ok, cool.  I think I see the problem here.

We inject the media3 libs during the build process.  Without much to go on as to where they should be injected, we put them in the first 'dependencies' block.  That, in your custom template, is not going to be correct.

We will need to look into a better set of rules to determine which block to inset it into.

For now, you can change your local PostProcessBuild_Android.cs script.  Look for function 'private void GradleMainTemplate( string path )' ...

You are looking for the line (there is only one occurance in the file):

if( line.Contains( "dependencies {" ) )

...and change this to:

if( line.StartsWith( "dependencies {" ) )

Let us know if this helps.  If it does not, can you post up the build.gradle file (created during the build) with the above change implemented.

**Comment by Cobrakinggames** [comment]
after do your changes i got Duplicate class error 

> Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)

**Comment by Ste-RH** [comment]
> after do your changes i got Duplicate class error
> 
> > Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)
> > Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)

That does not look AVPro Video or media3 related.  But please post the build.gradle file requested in my last post (as it did not resolve your issue)

**Comment by Ste-RH** [comment]
Or, I think you can force the version with something like:

android {
    ...

    configurations.all {
         resolutionStrategy.force 'androidx.work:work-runtime:2.7.0'
    }
}

...or maybe you need to force 2.8.1

**Comment by Cobrakinggames** [comment]
Ok I will Check And Get back To You

**Comment by Ste-RH** [comment]
Any joy @Cobrakinggames ?

**Comment by bthan7** [comment]
Hi, i was facing with same problem that @Cobrakinggames described in the above. 

I simply add this line of code to my mainTemplate.gradle 

`implementation 'androidx.work:work-runtime-ktx:2.8.1'`   

it solved my problem. 

I hope it helps...

**Comment by Cobrakinggames** [comment]
@bthan7  thank For the comment  it's help me and issues solved now 
also Thank @Ste-RH  for support

**Comment by Cobrakinggames** [comment]
@Ste-RH after i updated this https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/2081#issuecomment-2500966769

i got some weird issues  Like Some Images are automatically change in devices  please see the attached screenshot  

please look both the image 1 is editor image and 1 is mobile 
![Media](https://github.com/user-attachments/assets/606b2a5c-dbb5-44e8-bd49-3128b97e7b7c)
![undefined](https://github.com/user-attachments/assets/7bf2eb1e-c515-4e9d-822c-a1c6ea7b6eb3)

![Capture](https://github.com/user-attachments/assets/86637ed2-299b-44e1-9969-1e3c3c5ec9d7)
