### ISSUE TITLE
[Windows] Can support Vulkan on Windows or Unity Editor

### ISSUE THREAD

**Issue by NieYanzhe** [RenderHeads/UnityPlugin-AVProVideo#2083]
### Unity version

2022.3.50f1

### Unity editor platform

Windows

### AVPro Video edition

Ultra

### AVPro Video version

3.1.2

### Device hardware

any windows device

### Which Windows version are you using?

11

### Graphics API

D3D 11

### Video API

Media Foundation

### Audio output

None_

### The issue

We will simulate the graphics performance of other platforms on Windows under Vulkan, so sometimes we will add the "-force-vulkan" arguments when starting the Unity Editor to force Vulkan rendering. However, Windows currently does not support Vulkan, which can cause exception.

```
Exception: Specified cast is not valid.
RenderHeads.Media.AVProVideo.MediaPlayer:SetLoadOptions() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:652)
RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:612)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(Boolean) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:514)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(MediaPathType, String, Boolean) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:493)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(MediaPath, Boolean) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:484)
```

**Comment by Chris-RH** [comment]
We have no plans to support Vulkan on the Windows platform at this time.
