### ISSUE TITLE
The Apple spatial video cannot be played normally.

### ISSUE THREAD

**Issue by jingxin-yingsi-shaosiming-daye** [RenderHeads/UnityPlugin-AVProVideo#2087]
### AVPro Video Version

3.1.3 trial

### Which platform is your question for?

Windows

### Your question

![image](https://github.com/user-attachments/assets/df125809-3034-42b6-802a-bc095ddc5ff7)
Spatial videos recorded with Apple do not play correctly in the left and right eye view. When left and right eye mode is selected, the video is cropped in half.

**Comment by Chris-RH** [comment]
Hi, this isn't a question related to our product.  Please fill out a full issue form, including all of the issue details required.
