### ISSUE TITLE
[Question] HLS stream with h265 on Android & iOS?

### ISSUE THREAD

**Issue by daveb-tactic** [RenderHeads/UnityPlugin-AVProVideo#2095]
### AVPro Video Version

3.0.11

### Which platform is your question for?

Android, iOS

### Your question

I have created two HLS streams for the same video. The first one uses h264, and the second used h265. The second one won't play on Android or iOS (or in the windows editor or Mac editor either) in a test app build with Unity 6.0.14f1, but will play in the Windows VLC player. Here are the URLs:
- https://cfa-cms.tactic-api.com/hls/master.m3u8
- https://cfa-cms.tactic-api.com/hls2/master.m3u8

Is HLS with h265 encoding supported in AVPro Video? If so, can you recommend how I could encode an mp4 into this format?

**Comment by MorrisRH** [comment]
You have to use fmp4 segments with HEVC, mpeg2 ts segments are not supported.
