### ISSUE TITLE
[Question] Our adaptive streaming video looks pixelated in the player (but not when rendered in a full screen browser)

### ISSUE THREAD

**Issue by cprimozich** [RenderHeads/UnityPlugin-AVProVideo#2098]
### AVPro Video Version

V3.0.5

### Which platform is your question for?

iOS

### Your question

We have an m3u8 file specifying several resolutions of our video. At lower resolutions, the video looks quite pixelated in the player.

Wondering if you have any suggestions or solutions to improve the anti-aliasing when the video renders in the player.

I don't think this is specific to ios.

Browser:
![IMG-3158](https://github.com/user-attachments/assets/04c115d4-da2d-48e3-87fa-929747dc7f7b)

Video player:
![IMG-3159](https://github.com/user-attachments/assets/8532a40f-2e3d-462a-b39a-a2905087933c)

**Comment by Ste-RH** [comment]
This looks like a filtering issue.  Maybe you have it set to 'Point' in the MediaPlayer component?  If so, try another option.

![image](https://github.com/user-attachments/assets/c7dc1af4-8aa5-4b8d-b939-443d37062bf0)

Failing that, send over your video and we will take a look.  If you want to keep it private, email it to us at unitysupport@renderheads.com with the subject '#2098'

**Comment by Ste-RH** [comment]
> V3.0.5

Please update to the latest version as we made some changes/fixes to the iOS render path in v3.1.0.  It would be good to rule out if we have already addressed this issue or not at very least.

**Comment by Chris-RH** [comment]
Have you retested with the latest version please?

**Comment by cprimozich** [comment]
Also, the new plugin is requiring an android SDK upgrade. This is a big deal for us.

Is there any chance we can get a build that doesn’t require that? Here is the error we are seeing:

Exception: UnityEditor.Build.BuildFailedException: AVPro Video requires the 'Minimum API Level' must be set to Android 8.0 'Oreo' (API Level 26) or higher in 'Player Settings' at RenderHeads.Media.AVProVideo.Editor.PreProcessBuild_Android.OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport report)


From: Christian Primozich ***@***.***>
Date: Tuesday, December 17, 2024 at 12:35 PM
To: RenderHeads/UnityPlugin-AVProVideo ***@***.***>
Subject: Re: [External] Re: [RenderHeads/UnityPlugin-AVProVideo] [Question] Our adaptive streaming video looks pixelated in the player (but not when rendered in a full screen browser) (Issue #2098)
Hello. I just finished testing. The new version looks good.

One thing I found interesting is that the first play through on a relatively fast network connection (Wifi in Network Link Conditioner – 18 Mbps) looks really bad. The text is highly pixelated. If I play it again it looks fine. Do you know why that is?

From: Chris-RH ***@***.***>
Date: Monday, December 16, 2024 at 4:15 AM
To: RenderHeads/UnityPlugin-AVProVideo ***@***.***>
Cc: Christian Primozich ***@***.***>, Author ***@***.***>
Subject: [External] Re: [RenderHeads/UnityPlugin-AVProVideo] [Question] Our adaptive streaming video looks pixelated in the player (but not when rendered in a full screen browser) (Issue #2098)

Have you retested with the latest version please?

**Comment by Chris-RH** [comment]
Android 8.0 is as low as we can go due to the APIs we have to use.  This is a result of adding support for Vulkan.
