### ISSUE TITLE
multiple displays for a panorama

### ISSUE THREAD

**Issue by jensteinkamp** [RenderHeads/UnityPlugin-AVProVideo#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jensteinkamp** [comment]
HI Renderheads (I also sent you an email)
A friend of mine programmed Unity and AVProVideo windows to play a 5000x1200 HAP video on a poly quad out to 3 video projectors in sync. It does not quite play smooth enough. (It is close.)

I am using an Intel NUC8i7HVK with Radeon RX Vega M GH, I also tried a Nexcom B535
Unity 2018.3.1f1  AVProVideo Windows 1.9.12  Windows 10 embedded

She used MediaPlayer and the Apply to Mesh Script and shifts the quad for 3 different cameras and 3 different Target Displays. Basically 1 large video shifts horizontally to create a panorama across 3 projectors.

I would like to try using DisplayIMGUI to do the same thing. I am not able to get the video to play on 3 separate displays. I am hoping to improve the performance by taking out the quad.

Do you have any suggestions?

I added a link to the files, play from your desktop and change the user name in:
multiscreen-pref.json
and in the path to the configuration file in the Display Script public field linked to the MediaPlayer.

http://jsteinkamp.com/Nexcom_Player_builder.zip

**Comment by AndrewRH** [comment]
Hi, we've answered this via email, so I'm going to close the ticket here.
