### ISSUE TITLE
HTTP Header Support for Android ExoPlayer

### ISSUE THREAD

**Issue by travismmorgan** [RenderHeads/UnityPlugin-AVProVideo#210]
**Is your feature request related to a problem? Please describe.**
Our videos require the use of signed cookies to play. I add them to the android http headers but it only works for Android MediaPlayer, not ExoPlayer.

**Describe the solution you'd like**
Send custom headers when using ExoPlayer

**Describe alternatives you've considered**
Using MediaPlayer works but has it's own issues.

**Comment by RenderHeadsSte** [comment]
Bug replicated and fixed.  Header support working again when using ExoPlayer API path.

Will be present in AVPro version 1.10.2 and onward.

**Comment by travismmorgan** [comment]
@RenderHeadsSte When will this fix be released?
