### ISSUE TITLE
[VisionOS] .srt subtitles not displayed

### ISSUE THREAD

**Issue by liuyedaozhang** [RenderHeads/UnityPlugin-AVProVideo#2103]
### Unity version

2022.3.45

### Unity editor platform

Windows

### AVPro Video edition

Trial

### AVPro Video version

3.1.0

### Device hardware

Vision Pro

### Which visionOS version are you using?

1.1.0

### Application mode

Windowed

### Texture format

BGRA

### Audio output

System Direct

### Any other Media Player component configuration required to reproduce the issue.

After editing the externally imported. srt file, the subtitles can be displayed normally in the Unity editor, but after packaging the exe file, the subtitles cannot be displayed

### The issue

After editing the externally imported. srt file, the subtitles can be displayed normally in the Unity editor, but after packaging the exe file, the subtitles cannot be displayed

**Comment by Chris-RH** [comment]
Any more info?

**Comment by Chris-RH** [comment]
Closing due to lack of reply
