### ISSUE TITLE
[Question] Does Video Spatial (MV-HEVC) works in Meta Quest 3

### ISSUE THREAD

**Issue by Hydr0gen19** [RenderHeads/UnityPlugin-AVProVideo#2104]
### AVPro Video Version

3.1.3-trial

### Which platform is your question for?

Android

### Your question

Does Video Spatial (MV-HEVC) works in Meta Quest 3? If yes what is the suggested configuration of the Media Player

Thank you in advance

**Comment by Chris-RH** [comment]
AFAIK the [Quest 3](https://docs.qualcomm.com/bundle/publicresource/87-73689-1_REV_A_Snapdragon_XR2_Gen_2_Platform_Product_Brief.pdf) does [not support MV-HEVC](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/2041).  We cannot add support until it is natively supported by the hardware.

**Comment by Hydr0gen19** [comment]
On Quest 3 you can see the Video Spatial without any problem, if you want i can make a video for you with one of the video that i made with my iPhone 15 Pro Max

**Comment by Chris-RH** [comment]
We don't support streaming from Youtube.  As far as I know, the Quest 3 converts files to[ left-right or top-bottom stereoscopic](https://www.meta.com/en-gb/blog/quest/v62-software-update-spatial-video-playback-gamepad-support-browswer/).

**Comment by Hydr0gen19** [comment]
The video was for you, to see the support on Meta

**Comment by Chris-RH** [comment]
As I've said, we'll add support for MV-HEVC when it is more natively supported on devices.  Currently, we only support it on VisionOS.

**Comment by Hydr0gen19** [comment]
Ok perfect, thank you
