### ISSUE TITLE
[Android] "media3-exoplayer-workmanager" duplicate class issue

### ISSUE THREAD

**Issue by IgorKubyshkin** [RenderHeads/UnityPlugin-AVProVideo#2106]
### Unity version

2022.3.32f1

### Unity editor platform

Windows

### AVPro Video edition

Core

### AVPro Video version

3.1.2

### Device hardware

realme 8i

### Which Android OS version are you using?

13

### Unity Graphics API

Vulkan

### Video API

MediaPlayer

### Texture format

BGRA

### Audio output

Unity

### The issue

If the project contains Unity Ads network and AV Pro plugin Unity throws Duplicate class exception during the build. AV Pro uses media3-exoplayer-workmanager which uses androidx.work:work-runtime:2.8.1, but Unity Ads uses androidx.work:work-runtime-ktx:2.7.0. Can you help me resolve this duplicate class issue?

1. Add the AV Pro plugin to the project.
2. Add the Ads Mediation package
3. Add the latest Unity Ads network (4.3.51.0).
4. Try build the project 

### Logcat output

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.work.OneTimeWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)
     Duplicate class androidx.work.PeriodicWorkRequestKt found in modules work-runtime-2.8.1-runtime (androidx.work:work-runtime:2.8.1) and work-runtime-ktx-2.7.0-runtime (androidx.work:work-runtime-ktx:2.7.0)
```

**Comment by Ste-RH** [comment]
See issue #2081 (the last set of comments)
