### ISSUE TITLE
[Android] Too much whiteness or gamma is too high

### ISSUE THREAD

**Issue by bentalebahmed** [RenderHeads/UnityPlugin-AVProVideo#2107]
### Unity version

2021.3.18f1

### Unity editor platform

Windows

### AVPro Video edition

Core

### AVPro Video version

Core Mobile Edition version 3.1.3

### Device hardware

PICO 4 enterprise

### Which Android OS version are you using?

10

### Unity Graphics API

OpenGLES 3

### Video API

media3/ExoPlayer

### Texture format

Y Cb Cr 420_OES

### Audio output

System Direct

### Which output component(s) are you using?

Apply to Material, Apply to Mesh

### The issue

After updating Core Mobile Edition from 3.0.11 to 3.1.3 my video is too white, i m using Unlit/opaque - Android OES and VR/InsideSphere Unlit - Android OES with Pico 4 Enterprise headset

Before v3.1.3

![before V3 1 3](https://github.com/user-attachments/assets/8f73a4a4-4259-4072-8431-ce33026f1cdd)

After v3.1.3

![after V3 1 3](https://github.com/user-attachments/assets/51197c1f-fa6d-403c-8ed6-483d542de302)

**Comment by Ste-RH** [comment]
I _think_ we have already fixed this in the codebase and it is just awaiting release (which we are working very hard to try and get out this week, certainly next).

**Comment by Ste-RH** [comment]
Yes, reproduced in v3.1.3.  Not seeing this in our latest codebase.  So it will be fixed in the next release.

**Comment by Ste-RH** [comment]
We are working extremely hard to try and get it out this week

**Comment by Chris-RH** [comment]
AVPro Video version 3.2.0 has been released.  Please let us know if it has not fixed your issue.

**Comment by bentalebahmed** [comment]
It fixed the problem
