### ISSUE TITLE
H.265 with Android MediaPlayer

### ISSUE THREAD

**Issue by travismmorgan** [RenderHeads/UnityPlugin-AVProVideo#211]
**Describe the bug**
Playing H.265 video with Android MediaPlayer does not render video, only audio. It works fine when using ExoPlayer but ExoPlayer doesn't support headers.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.8
 - AVPro Video version: 1.10.1
 - Operating system version: Android 8.1.0
 - Device model: Pico Goblin 2
 - Video specs (resolution, frame-rate, codec, file size): 3840x3840, 30fps, H.265 HLS, 1.4GB

**To Reproduce**
1. Change media player to use Android MediaPlayer
2. Try and stream HLS H.265 video

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
H.265 in general does work with the MediaPlayer API, but I suspect the issue might be 'not at 4k'.

Headers do work with the ExoPlayer path.  Could you provide a sample video/header combination that is not working? (email it to unitysupport@renderheads.com if you wish to keep it private)

**Comment by travismmorgan** [comment]
@RenderHeadsSte thanks for replying. I emailed you the url and header I am using. Same combination works fine with MediaPlayer but not ExoPlayer. The cookie is good for 1 day but if you want to test it and need longer than that, let me know and ill sign a longer one.

**Comment by RenderHeadsSte** [comment]
The cookie does not work for either video...

**Comment by travismmorgan** [comment]
When testing H.265 with MediaPlayer, you will notice the audio plays but not the video. I need either MediaPlayer to play H.265 or ExoPlayer to work with the cookie header. Otherwise, I can't use this library :/.

**Comment by RenderHeadsSte** [comment]
Bug replicated and fixed.

Will be present in AVPro version 1.10.2 and onward.

**Comment by RenderHeadsSte** [comment]
I think this is device specific.  The H265 sample provided works on the Samsung S7 (EU version) using MediaPlayer.  The ExoPlayer header issue has been fixed (in version 1.10.2 onward).
