### ISSUE TITLE
[Android] ExoPlayer 1.4.1, asked minSDK 34

### ISSUE THREAD

**Issue by N7Nico** [RenderHeads/UnityPlugin-AVProVideo#2110]
### Unity version

2022.3.54f1

### Unity editor platform

macOS

### AVPro Video edition

Ultra

### AVPro Video version

3.1.3

### Device hardware

Meta Quest 3

### Which Android OS version are you using?

12

### Unity Graphics API

Vulkan

### Video API

media3/ExoPlayer

### Texture format

BGRA

### Audio output

System Direct

### Which output component(s) are you using?

Apply to Mesh

### The issue

Hello,
When I build win min and targetSDK 32 as required by Meta Quest Store, I get the error :
`
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 20 issues were found when checking AAR metadata:
     
       1.  Dependency 'androidx.media3:media3-exoplayer-dash:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       2.  Dependency 'androidx.media3:media3-exoplayer-hls:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       3.  Dependency 'androidx.media3:media3-exoplayer-rtsp:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       4.  Dependency 'androidx.media3:media3-exoplayer-smoothstreaming:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       5.  Dependency 'androidx.media3:media3-exoplayer-workmanager:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       6.  Dependency 'androidx.media3:media3-exoplayer:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       7.  Dependency 'androidx.media3:media3-extractor:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       8.  Dependency 'androidx.media3:media3-container:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
       9.  Dependency 'androidx.media3:media3-datasource-cronet:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      10.  Dependency 'androidx.media3:media3-datasource-okhttp:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      11.  Dependency 'androidx.media3:media3-datasource-rtmp:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      12.  Dependency 'androidx.media3:media3-datasource:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      13.  Dependency 'androidx.media3:media3-database:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      14.  Dependency 'androidx.media3:media3-decoder:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      15.  Dependency 'androidx.media3:media3-common:1.4.1' requires libraries and applications that
           depend on it to compile against version 34 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 7.4.2 is 33.
     
           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 34, then update this project to use
           compileSdkVerion of at least 34.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      16.  Dependency 'androidx.work:work-runtime:2.8.1' requires libraries and applications that
           depend on it to compile against version 33 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 33, for example 33.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      17.  Dependency 'androidx.room:room-runtime:2.5.0' requires libraries and applications that
           depend on it to compile against version 33 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
     
           Recommended action: Update this project to use a newer compileSdkVersion
           of at least 33, for example 33.
     
           Note that updating a library or application's compileSdkVersion (which
           allows newer APIs to be used) can be done separately from updating
           targetSdkVersion (which opts the app in to new runtime behavior) and
           minSdkVersion (which determines which devices the app can be installed
           on).
     
      18.  Dependency 'androidx.sqlite:sqlite-framework:2.3.0' requires libraries and applications that
           depend on it to compile against version 33 or later of the
           Android APIs.
     
           :launcher is currently compiled against android-32.
  <message truncated>`

Why is it asking for SDK 34 minimum ?

**Comment by Chris-RH** [comment]
Exoplayer requires Android SDK 34, which does not come with this version of Unity. In Player Settings|Other Settings, set Target API Level to Android 14.0 (API level 34), Build and you will be prompted that the 'Android APK is missing'.  Select 'Update Android SDK'.  This will open up a command window and the required APK should be downloaded. The SDK will be downloaded to Editor/Data/PlaybackEngines/AndroidPlayer/SDK/platforms/.

If you need to target a lower version of Android, then you need to add a custom gradle property. In Player Settings|Publisher Settings, enable the Custom Main Gradle Template and Custom Launcher Gradle Template options. The templates are found at: /Assets/Plugins/Android/mainTemplate.gradle and /Assets/Plugins/Android/launcherTemplate.gradle and they should be edited by adding the following lines:

minSdk 26
targetSdk 32
compileSdk 34

**Comment by Ste-RH** [comment]
As Chris says...but your output also contains all the answers.  media3 and the components it uses require 34+ to compile against.

**Comment by N7Nico** [comment]
> If you need to target a lower version of Android, then you need to add a custom gradle property. In Player Settings|Publisher Settings, enable the Custom Main Gradle Template and Custom Launcher Gradle Template options. The templates are found at: /Assets/Plugins/Android/mainTemplate.gradle and /Assets/Plugins/Android/launcherTemplate.gradle and they should be edited by adding the following lines:

> minSdk 26
targetSdk 32
compileSdk 34

That did the job: the compilation finished without errors. Unity can compile with SDK > 32, but the Meta Quest Store refuses APKs with target > 32...

I was just surprised it asked for such a recent SDK as the plugins specs for v3 ask for:

> This plugin requires minimum SDK Android 8.0.0 (Oreo, API level 26)
> This plugin requires target SDK Android 12.0.0 (Snow Cone, API level 31)

**Comment by Chris-RH** [comment]
Compile SDK of 34 is a requirement of Exoplayer, and is different to target SDK. [Here](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd#.fo6h6k65r) is an article that gives a bit more information in the differences.

You can absolutely reduce the number that you enter for Target SDK to suit your requirements.  The only ones that are required to stay the same are min SDK and Compile SDK :)
