### ISSUE TITLE
[Question] Bundling LAV Filters on PC builds

### ISSUE THREAD

**Issue by pablodawson** [RenderHeads/UnityPlugin-AVProVideo#2116]
### AVPro Video Version

3.1.3

### Which platform is your question for?

Windows

### Your question

Hey,
So I developed an app with AVPro that uses DirectShow+LAV Filters to decode media.
I thought I'd ask what the usual way is to bundle LAV Filters as you probably encountered this a few times.
Or if you just prompt the user to install it themselves. Any info helps.

Thanks!

**Comment by Chris-RH** [comment]
Hi, the user should be prompted to download and install it themselves.

**Comment by pablodawson** [comment]
Thanks
