### ISSUE TITLE
Default Texture with Android OES

### ISSUE THREAD

**Issue by travismmorgan** [RenderHeads/UnityPlugin-AVProVideo#212]
**Describe the bug**
Setting the 'Apply to Mesh' Default Texture does not work when Android Fast OES Path is enabled.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.8
 - AVPro Video version: 1.10.1
 - Operating system version: Android 8.1.0
 - Device model: Pico Goblin 2

**To Reproduce**
1. Enable Fast OES Path
2. Set Default Texture in 'Apply to Mesh'
3. Build to device

**Comment by RenderHeadsSte** [comment]
I have reproduced this issue.  As a work around, you can disable 'Auto Open', which keeps the default texture until the video is later opened/started.

**Comment by RenderHeadsSte** [comment]
A fix for this will be in v2.1.0 and onward
