### ISSUE TITLE
Force Eye Mode with Android OES

### ISSUE THREAD

**Issue by travismmorgan** [RenderHeads/UnityPlugin-AVProVideo#213]
**Describe the bug**
Setting the 'Update Stereo Material' Force Eye Mode does not work when Android Fast OES Path is enabled.

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.8
 - AVPro Video version: 1.10.1
 - Operating system version: Android 8.1.0
 - Device model: Pico Goblin 2

**To Reproduce**
1. Enable Fast OES Path
2. Set 'Force Eye Mode' to Left
3. See stereo video still renders both eyes/3D

**Comment by RenderHeadsSte** [comment]
@travismmorgan 

'Force Eye Mode' does not currently exist in the OES shader (AVProVideo-VR-InsideSphere-AndroidOES.shader)...

So have you brought over the relevant parts from the shader that does include it? (AVProVideo-VR-InsideSphere-StereoUV.shader)

**Comment by travismmorgan** [comment]
Confirmed modifying the OES shader to include the Force Eye components from the regular shader fixes this issue.

**Comment by RenderHeadsSte** [comment]
Awesome

**Comment by bhermer** [comment]
Hi, we are having htis same problem. What was the fix? we are on the last up to date version 1. Really dont want to may a huge upgrade to version 2

**Comment by RenderHeadsSte** [comment]
I will post up a modified shader @bhermer.  Just need to test it...

**Comment by RenderHeadsSte** [comment]
@bhermer Here is a modified script that supports the 'Force Eye Mode' when OES is enabled on Android

[AVProVideo-VR-InsideSphere-AndroidOES.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5882384/AVProVideo-VR-InsideSphere-AndroidOES.zip)

**Comment by bhermer** [comment]
Your a legend. Thank you
