### ISSUE TITLE
Spelling mistakes in AVProVideo 1.9.18

### ISSUE THREAD

**Issue by Coeur** [RenderHeads/UnityPlugin-AVProVideo#214]
Please find below some spelling issues in AVProVideo 1.9.18

### All files

Headers should all read "**All rights reserved.**" instead of "_All rights reserverd._"

### AVProVideo/Demos/Scripts/SimpleController.cs

simpel -> simple

### AVProVideo/Scripts/Components/MediaPlayer.cs

NOte -> Note
WE've -> We've
offical -> official
interal -> internal

### AVProVideo/Scripts/Internal/AudioOutputManager.cs

mulitple -> multiple

### AVProVideo/Scripts/Internal/BaseMediaPlayer.cs

effecient -> efficient

### AVProVideo/Scripts/Internal/HLSStream.cs

navitation -> navigation
BANDWITH_NAME -> BANDWIDTH_NAME

### AVProVideo/Scripts/Internal/Interfaces.cs

suported -> supported
whhen -> when
AVfoundation -> AVFoundation

### AVProVideo/Scripts/Internal/Stream.cs

retreiving -> retrieving

### AVProVideo/Scripts/Internal/WindowsMediaPlayer.cs

specificying -> specifying

---

**Comment by AndrewRH** [comment]
Thanks for these great suggestions - we really appreciate it :)  

These changes have been made and will appear in the next release.

Cheers,
