### ISSUE TITLE
Playing a streaming by URL(.m3u8) -Video delay 

### ISSUE THREAD

**Issue by DuDuBingXuan** [RenderHeads/UnityPlugin-AVProVideo#215]
**Describe the bug**
Hello,

When I Playing a streaming by URL(.m3u8) in AVPro Video,and this video always delay when I loaded from the beginning.
Even if I reload this video,this video is still delay.
This video by url in web didn't delay.But by AVPro in Unity /Android/IOS platform will delay when playing.
Is there any ways to make avpro's video sync with my online streaming?
Keep avpro's video update without delay from the beginning.

Thanks.

**Your Setup (please complete the following information):**
 - Unity version: v5.6.5p3 WindowsEditor
 - AVPro Video version: plugin v1.10.1 scripts v1.10.1
 - Operating system version:  Windows 10  (10.0.0) 64bit
 - Target Platform: Android/IOS

**Comment by RenderHeadsSte** [comment]
Do you have an example stream URL?

Are you playing back with ExoPlayer or MediaPlayer API path?

**Comment by RenderHeadsSte** [comment]
We shall be closing this issue shortly due to lack of response.

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response.
