### ISSUE TITLE
For some videos, video and audio not synchronize on Android and Windows.

### ISSUE THREAD

**Issue by cdytoby** [RenderHeads/UnityPlugin-AVProVideo#216]
**Describe the bug**

I have a test project, which will be sent to your email later.

There are 2 bugs here:

- Video is a little bit not synchronize on both android and windows, audio is delayed
- On Windows, when the app lost focus, means switch to other window and switch back, the audio will be more delayed.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.11 LTS
 - AVPro Video version: 1.10.0
 - Operating system version: Win10 1903
 - Device model: 
Android: Sony Xperia XZ2, This lag happens also in our other project, which runs on Oculus Go and Oculus Quest.
Desktop: Surface Pro 6 i7, 16GB RAM, and another desktop pc with i5 7300HQ, GTX 1060 3G and 8GB RAM.
 - Video specs (resolution, frame-rate, codec, file size): 3840*1920, 29.97FPS, avc

**To Reproduce**
1. Open the test project. 
1.1. I sent an earlier version of this test project before, so you may want to delete the app data folder first, on both android and pc.
2. Run the project on Windows or Editor, wait for the file to download, after the file is downloaded, video will be automatically played. 
3. You'll notice the handclap audio is slightly delayed.
4. On windows or editor, when you switch window, and switch back, the audio will be more delayed. 
5. Switch to Android mode, and build and run on Android device. You'll notice audio is also delayed on android.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
Video url will be in the source code in the project.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
In Editor: Running downloads the video and plays it back with no audio sync issues.

On Android: I have ran your test project on a Samsung S7 here.  The video does not download for me.  So I manually downloaded the video and put in on the device.  Running again the video plays, but with no audio sync issues.

Have you tried updating to v 1.10.1?

**Comment by cdytoby** [comment]
No, I didn't see any related updates in 1.10.1 so I haven't tested it yet, will do.

And about Windows, it plays back without sync issue but once you lost focus, (minimize Unity, switch to another window, call up desktop etc), and get back, it will have sync issue.

**Comment by RenderHeadsSte** [comment]
I notice your video is 29.97 fps.  Is there a specific reason for that? Have you tried re-encoding it to 30 to see if that makes a difference on either platform?

**Comment by cdytoby** [comment]
No, I can try, but our App/Service will serve all kinds of videos and we don't serve "Redo framerate" when transcoding them, because it generally makes a video frame issue.

there are multiple video standards, for fps there are 23.976, 24, 25, 29.97, 30, we never know what kind of videos our clients upload, and we intend to support them all since they're part of the standards.

**Comment by AndrewRH** [comment]
Yes on Windows it can get confused when the application doesn't have focus.  It can take time for it to catch up.  I believe this is most true when the video has complex encoding and not many keyframes.  If your video has frequent keyframes then this shouldn't be an issue.

To solve this I would recommend trying to detect when the app loses focus and pausing/resuming the video at this point.  I believe you may be able to do this via OnApplicationFocus:
https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationFocus.html

I'm not sure why there is a delay on Android...we will have to investigate...

Thanks,

**Comment by RenderHeadsSte** [comment]
I looked at reproducing the lag issue when you sent your project over to us...on an Oculus GO.  I could not reproduce your issue.  We now have a Quest in hand, so will test on that this morning and report back.

**Comment by RenderHeadsSte** [comment]
@cdytoby What kind of audio lag are you seeing?  On the Quest here I am seeing very marginal, if any.  Certainly no more than is usual for Oculus systems.

**Comment by cdytoby** [comment]
https://www.dropbox.com/s/pag9m63tv91hbkh/AVProVideoLagTest-20200227.apk?dl=0

OK, then I'll just post the apk here. It's produced by same project I sent you last time, without modification. It's a normal android device apk, not oculus.

If you compare the video playback on android device with the playback on PC, you'll notice the audio is delayed. On PC the audio plays almost the same time as visual hand claps, but on Android, the audio plays some time after the hand claps.
