### ISSUE TITLE
Warped texture when using Android OES

### ISSUE THREAD

**Issue by travismmorgan** [RenderHeads/UnityPlugin-AVProVideo#217]
**Describe the bug**
When enabling OES path and using Sphere360-OES material, the bottom of the 360 video appears warped. See logo in pictures.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.0
 - AVPro Video version: 1.10.1
 - Operating system version: Android 8.1.0
 - Device model: Pico Goblin 2
 - Video specs (resolution, frame-rate, codec, file size): HLS H.264 1080p

**To Reproduce**
1. Enable 'Use Fast OES Path' for Android
2. Set 'Mesh Renderer'->'Material' to 'Sphere360-OES'
3. Play 360 video: 'https://d19setc678u3xp.cloudfront.net/469046f6fe7f11e9aa421afa9dd3ff3b/playlist.m3u8'

**Screenshots**
![IMG_2640](https://user-images.githubusercontent.com/10135288/68439863-07683b80-017e-11ea-8f51-5d7660677be7.jpg)
![IMG_8227](https://user-images.githubusercontent.com/10135288/68439864-07683b80-017e-11ea-880b-fd29663eb006.jpg)

**Videos**
https://d19setc678u3xp.cloudfront.net/469046f6fe7f11e9aa421afa9dd3ff3b/playlist.m3u8

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
To me, this looks like the pinch point you get at the poles when using spherical projection.  It does not look like a bug with AVPro per se.  You could convert your source videos and try the cube map shader?

**Comment by travismmorgan** [comment]
It is a bug with the OES shader. you can see the first picture looks correct using the regular Sphere360 shader. That logo is designed to correct with spherical projection.
