### ISSUE TITLE
Crash on Unity

### ISSUE THREAD

**Issue by CyangYu** [RenderHeads/UnityPlugin-AVProVideo#218]
When I run the demo, the unity editor crash. I don't know what's the problem is.

**Comment by MorrisRH** [comment]
Could we get a little more information please:
1. Platform (Windows, macOS) and version of the OS
2. Unity version
3. AVPro Video Version
4. The demo you're trying to run
5. The unity editor log file

**Comment by RenderHeadsSte** [comment]
We shall be closing this issue down soon if no further information is delivered.
