### ISSUE TITLE
Quality issues when playing VR content on Pico G2 (stuttering)

### ISSUE THREAD

**Issue by ThomasVROwl** [RenderHeads/UnityPlugin-AVProVideo#219]
Playing content on a Pico G2 using the AV Pro player results in quality loss, and stuttering. This issue does not occur in the Native Player, or when using the VideoPlayer by Unity.

 - Unity version: 2018.3.2f1
 - AVPro Video version: 1.10.1
 - Operating system version: 
 - Device model: Pico G2 & Pico G2 4K
 - Video specs 1 (resolution, frame-rate, codec, file size): 4096x2048, 60fps, h.265, 343 Mb
 - Video specs 2 (resolution, frame-rate, codec, file size): 3980x3980, 30fps, h.264, 2.14 Gb

I have tried using Exoplayer, as well as MediaPlayer, EOS / standard. I tried using the Resampler. But nothing improved the quality, or helped with the stuttering issue.

**Comment by RenderHeadsSte** [comment]
Closing as we are dealing with this issue via email.
