### ISSUE TITLE
Not playing 4K 360 streaming videos on Android

### ISSUE THREAD

**Issue by eugenelyzya** [RenderHeads/UnityPlugin-AVProVideo#22]
**Description**
I have about 7-8 spheres with 360 4K videos in my project. It's fine works on PC but on Android sometimes these videos are not loading therefore not playing but sometimes it works fine. 

I created a test project to catch this bug. I placed 6 spheres with these videos on a scene. It works fine on PC but on Android two videos are not playing.I brought the logs on the PC and on the Android. I think a problem is insufficient system resources. 

I'm going to play ten 8K videos at the same time on AV Pro Video Media Player in two months but it doesn't work with 4K videos... 

**My Setup**
 - Unity version: 2018.3.0f2
 - AVPro Video version: 1.9.6
 - Operating system version: Windows 10 x64
 - Test device: Samsung Galaxy G6
 - Video resolutiuon: 4K 

**To Reproduce**
1. Download archive with test project
2. Open Project -> Play -> All works fine 
3. Find .apk file in MediaPlayerIssues -> Builds or make you own build and install on Android 
4. See two videos will not be played

**Comment by AndrewRH** [comment]
Hi,

Thanks for getting in touch.

Hardware has a limited amount of GPU decoding resources.  On a Windows PC with a top GPU it can only decode a maximum of 1 8K video at a time on hardware, or 4 4K videos - and this is right at the limit of its capabilities.

On Android the options are even less, with usually a single 4K video being playback at once.

This is why the video loading is failing.  

So you will need to perhaps not load all of your videos at once.  If they don't need to all play at once, consider loading them on demand using a single MediaPlayer instance, or merging them into a single video that you can seek into to play the different parts.

**Comment by AndrewRH** [comment]
I will close this thread if this answer is satisfactory

**Comment by eugenelyzya** [comment]
OK, thank you a lot :)

чт, 21 февр. 2019 г. в 20:23, Andrew <notifications@github.com>:

**Comment by albertoxamin** [comment]
> So you will need to perhaps not load all of your videos at once. If they don't need to all play at once, consider loading them on demand using a single MediaPlayer instance, or merging them into a single video that you can seek into to play the different parts.

I have the same problem with the OculusGO, I'm already using a single MediaView, but I've not yet tried merging them since it is quite time consuming for my project, are there any other alternatives?
I also have noticed that every-time I play a video the used memory increases but when a new video is loaded and the previous unloaded the used memory doesn't decrease, I suspect there is a memory leak.

**Comment by ehsanwwe** [comment]
@albertoxamin 
your problem was solve ? if yes say us how
