### ISSUE TITLE
MediaPlayerEvent events not occurring when expected

### ISSUE THREAD

**Issue by wombatzus** [RenderHeads/UnityPlugin-AVProVideo#221]
**Describe the bug**
After upgrading to 1.10.1 from the Asset Store, MediaPlayerEvent events triggered during video playback have the following unexpected properties:
 - in Editor and on iOS devices, FinishedPlaying never triggers when playing a non-looping video (haven't checked Android). I see the following sequence of events:
   - MetaDataReady
   - ReadyToPlay
   - FirstFrameReady
   - ResolutionChanged
   - Started
   - ResolutionChanged (2x)
   - Closing
 - on WebGL, ReadyToPlay doesn't trigger until after FinishedPlaying. I see the following sequence of events when playing a non-looping video:
   - StartedBuffering
   - MetaDataReady
   - ResolutionChanged
   - Started
   - FirstFrameReady
   - FinishedBuffering
   - FinishedPlaying
   - ReadyToPlay
   - Closing

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.5f1
 - AVPro Video version: 1.10.1
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Play any video in editor or on device or WebGL
2. Observe MediaPlayerEvent being triggered
3.

**Comment by wombatzus** [comment]
After further investigation about the FinishedPlaying event never triggering seems that when this happens here the video stops playing about 120 ms before the very end and is stuck here with `IsFinished()` continually returning false until I close the media.

**Comment by ErikSchulzeFizbin** [comment]
Experiencing the same problem: We recently updated our App to Unity 2018.4.8f1 and AVPro 1.10.1 and everything seems to be going smooth except for one thing: On iOS (and only there, on Android everything works fine) the MediaPlayerEvent.EventType.FinishedPlaying is not fired. All other events seem to be working just fine. I get this behaviour both on the device and inside the Editor, but only when using the Editor on a Mac, it doesn't happen when on Windows with build target set to iOS.

**Comment by AndrewRH** [comment]
Hey @wombatzus  and @ErikSchulzeFizbin 
I know this is a bit old, but could you confirm whether you were talking about streaming video (eg ?HLS) or just a normal local MP4?

Also, we have a theory the video encoded might have a different track length of the video/audio tracks and that's causing this problem.  Perhaps you could attached the video to this thread if it's not too large, or email it our support?

Thanks,

**Comment by Man-0-waR** [comment]
I have the latest AVPro and it does not trigger FinishedPlaying event on Android.

**Comment by MorrisRH** [comment]
An issue with the finished playing event when streaming HLS on macOS and iOS was fixed in the last release 1.10.2.

**Comment by RenderHeadsSte** [comment]
> I have the latest AVPro and it does not trigger FinishedPlaying event on Android.

Can you provide some more information please?

- What version of AVPro Video are you using?
- What device(s) are you seeing this issue on?
- What video(s) are you seeing this with? (would it be possible to provide a link to a stream, or video files - sent to unitysupport@renderheads.com)

**Comment by Man-0-waR** [comment]
> > I have the latest AVPro and it does not trigger FinishedPlaying event on Android.
> Can you provide some more information please?
This was fixed in the latest version 1.10.2

**Comment by RenderHeadsSte** [comment]
@Man-0-waR Are you reporting the issue fixed for you?

**Comment by Man-0-waR** [comment]
Yes, after updating plugin I can get that event.

**Comment by RenderHeadsSte** [comment]
FYI. We have found and fixed another circumstance whereby HLS streams in Unity Editor on macOS would not fire the FINISHED event.  A fix for this will be in the next released version of AVPro Video.

**Comment by RenderHeadsSte** [comment]
> Yes, after updating plugin I can get that event.

Awesome :)

**Comment by Amidee89** [comment]
Still happening on 1.11.3 android, on a Pico headset it won't trigger IsFinished when finished playing a non looping video.
VIdeo is H265 4096x4096 and rendering to material.

**Comment by AndrewRH** [comment]
> Still happening on 1.11.3 android, on a Pico headset it won't trigger IsFinished when finished playing a non looping video.
> VIdeo is H265 4096x4096 and rendering to material.

Does it happen when you use any of our samples videos instead?

Thanks,

**Comment by AndrewRH** [comment]
@Amidee89 ?

**Comment by Amidee89** [comment]
Hi, sorry I've not been able to test this today.
To be sure – which sample videos do you refer to? 
I've tried many h265 videos we make and the result is always the same – event path is never called, even on a short 2sec test video.

**Comment by Amidee89** [comment]
> @Amidee89 ?

Tried with sample videos from your trial, still nothing (at this point I really hope I didn't do anything wrong, but I kinda used your own code here so I think I'm in the clear) 
I've uploaded project & compiled here:
https://we.tl/t-Vt9DgYg1GM

videomanagerscript is the one doing the heavy lifting.

**Comment by AndrewRH** [comment]
Sorry please do not upload project files here.  You can email them to unitysupport@renderheads.com

Also - could you try running our sample scenes to see whether the events are generated on your device?  It may be something specific to the Pico (which we do not have).

Thanks,

**Comment by Amidee89** [comment]
I'm kinda between projects and I'm not exactly super free to make your
scene debug this problem.
I can say that I just tried the same event on the Quest and it worked as
intended, so it's probably platform specific.

**Comment by AndrewRH** [comment]
Thanks, yeah of course 👍 

it must be Pico related I think....We'll need to try get our hands on one.  I guess a workaround would be to manually monitor time and check if it's close to the duration and then consider the video over.

**Comment by Amidee89** [comment]
that's what I did (:
