### ISSUE TITLE
How do load video from assetbundle？

### ISSUE THREAD

**Issue by lz66299** [RenderHeads/UnityPlugin-AVProVideo#222]
I call the api OpenVideoFromBufferInternal(byte[] buffer), but is not work in Android. the error is “[AVProVideo] Loading from buffer is currently only supported in Windows when using the DirectShow API”

**Comment by RenderHeadsSte** [comment]
This functionality is currently not supported on Android.  I suspect it will not be possible, but we will flag this as an enhancement and look into it at a future date

**Comment by justin-pierce** [comment]
Might be a long shot but try building the asset bundle with compression turned off. IIRC I had a similar issue in another context and it was issue with android assetbundle compression.

**Comment by Jayatubi** [comment]
Well, I found a walkaround:

1. Setup an HttpListener on some port in your application
2. Handle the incoming request as a resource path
3. Load the asset bundle at the path and return the data to the reponse
4. Use a loopback URI such as http://127.0.0.1:port/foo.assetbundle in AVPro media player

I tested on Android and Windows and works.

**Comment by jnroesch** [comment]
Hey @Jayatubi could you explain your approach a bit more? I think I am looking for a similar solution. thanks

**Comment by Jayatubi** [comment]
Using the C# builtin [HttpListener](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener?view=netframework-4.8) class to setup a local http server in your app. After the server starts you could provide a url such as `http://127.0.0.1:8888/the_name_of_the_assetbundle` to the AVPro media player. Then you could serve your assetbundle data by the path which could be got from the incoming HttpListenerRequest. Write the data via the HttpListenerResponse the AVPro would play the video.

This is a doable approach but a bit hard to become perfect. The main issue I encounter is I don't know how the make AVPro play the video streamly. It always start to play only after all the data had been transfered completely.

**Comment by iLyxa3D** [comment]
> Using the C# builtin [HttpListener](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener?view=netframework-4.8) class to setup a local http server in your app. After the server starts you could provide a url such as `http://127.0.0.1:8888/the_name_of_the_assetbundle` to the AVPro media player. Then you could serve your assetbundle data by the path which could be got from the incoming HttpListenerRequest. Write the data via the HttpListenerResponse the AVPro would play the video.
> 
> This is a doable approach but a bit hard to become perfect. The main issue I encounter is I don't know how the make AVPro play the video streamly. It always start to play only after all the data had been transfered completely.

Thanks! 
Sadly, it's not supported in WebGL.

**Comment by evan-spiegel** [comment]
> This functionality is currently not supported on Android. I suspect it will not be possible, but we will flag this as an enhancement and look into it at a future date

Hi there, is this functionality still not supported on Android? Playing videos from an asset bundle using AVPro I mean. Thanks!

**Comment by AndrewRH** [comment]
Playing natively from an AssetBundle is not possible.  See some of the workarounds above.   The only other ways currently woudl be to embed the video in the AssetBudnle as a TextAsset and then save the byte[] to disk and play from there.

Closing this issue as we have no other ways to suggest playback from AssetBundles.
