### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by sergipanadero** [RenderHeads/UnityPlugin-AVProVideo#223]
*I have a unity windows standalone project that uses avpro to play a h.265 HEVC video with a resolution of 6500x1080 pixels.
I use uGUI and the video is loop=true.
I use windows 10 for run the app.
The application start using 700mb of memory.

The problem is that when i run the aplication on some computers there is a memory Leak that every 10-15 seconds makes increase the application memory and the application memory grow to reach the limit of windows memory and finish to crash Windows in 1-2 hours.
But on other computers this do not happend and the app can run "for eternity" :) without any problem.

I have probed with different h.265 videos with same result.
Can anyone help with this issue? Any idea of what can i try to solve this?

**Your Setup (please complete the following information):**
 - Unity version:  Unity 5.6.2 and Unity 2018.4.0
 - AVPro Video version:  all versions, test on 1.10.1
 - Operating system version:  Windows 10
 - Device model: all devices
 - Video specs (resolution, frame-rate, codec, file size): h.265 HEVC video with a resolution of 6500x1080 pixels.

**Comment by RenderHeadsSte** [comment]
This sounds like a very strange issue.  If you are running the exact same build with the exact same data set on different PC's and some leak memory and some don't, then it sounds very unlikely that it is the software per se.  Possibly something in the implementation that certain versions of Windows do not like?  Have you looked for a commonality with the set of PC's that elicit this issue?

**Comment by RenderHeadsSte** [comment]
We will be closing this issue soon due to a lack of response

**Comment by AndrewRH** [comment]
We have not heard any more about this, and I suspect the issue could have been a driver implementation.   I am going to close this ticket.
