### ISSUE TITLE
Playback issues in Trial on multiple Unity versions

### ISSUE THREAD

**Issue by str11ngfello** [RenderHeads/UnityPlugin-AVProVideo#227]
**Describe the bug**
Downloaded latest Unity trial from RenderHeads website.

**Your Setup (please complete the following information):**
 - 2019.1.14f and have also tried 2019.2.x on Mac

**To Reproduce**
Just open any of the trial demos and press play. The movie plays for one second then repeats and stutters for the remainder of the video. This happens in all demos.

I've shared a .mov screen recording. I've also sent a this video to unitysupport@renderheads.com
http://ge.tt/5nGwnnz2

**Comment by MorrisRH** [comment]
Unfortunately the watermarking in the trial version causes this when using the Metal renderer with certain hardware configurations. If you switch the renderer to OpenGL Core it will behave correctly.

This issue does not affect the full version of the plugin.

It would be really handy to know your hardware specifications (model, processor, gpu, ram, etc.).

**Comment by RenderHeadsSte** [comment]
We shall be closing this bug soon should no response be forthcoming
