### ISSUE TITLE
Unable to convert classes into dex format

### ISSUE THREAD

**Issue by paulgullett** [RenderHeads/UnityPlugin-AVProVideo#228]
Build error in Unity when using ARM64 and IL2CPP

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.11f1
 - AVPro Video version: Trial Version from website UnityPlugin-AVProVideo-Latest-Trial.unitypackage
 - Operating system version: Android
 - Device model: Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size): N/A

**To Reproduce**
1. Requires a project set up for Oculus Quest with Photon (photon adds libopus_egpv)
2. Import AVPro package
3. Build with IL2CPP with target architecture arm64 (Internal or Gradle)

The plugins do need setting to the right platforms as they are not correct on import. But once set on build you get the following error

Unable to convert classes into dex format.

**Logs**
CommandInvokationFailure: Unable to convert classes into dex format.
C:\Program Files\Unity\Hub\Editor\2018.4.11f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -Xmx4096M -Dcom.android.sdkmanager.toolsdir="D:/Users/paulgullett/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Hub\Editor\2018.4.11f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/AmbisonicRenderer;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/AmbisonicRenderer$SwigNext;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/AssetDescriptor;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/AttenuationMode;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/AttenuationMode$SwigNext;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/AttenuationProps;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/Audio360;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/Audio360JNI;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/twobigears/audio360/AudioDeviceType;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
	at com.android.dx.command.dexer.Main.main(Main.java:244)
	at com.android.dx.command.Main.main(Main.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at SDKMain.main(SDKMain.java:136)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
	... 9 more
]

**Comment by paulgullett** [comment]
Ok workaround is this

In Unity use Gradle, export project. in ProjectName/libs delete audio360.jar everything is already in classes.jar. The build will now work.

However, this is a pain so needs to be fixed so that Build System Internal works

**Comment by RenderHeadsSte** [comment]
Hi,

Is this Photon the networkingengine? (https://www.photonengine.com/en-us/Photon)

If so, I suspect they are including libopus for something like voice comms.

As I am sure you know. the Android build environment really does not like including multiple of the same libraries, and I suspect this is why you are seeing the error at dex conversion stage - every time I have seen it in the past it has been multiple of the same lib.

I am not sure what solution we could offer at this stage as libopus is built into facebook360.  Maybe you could try removing the facebook 360 lib and build?  (assuming you are not using facebook 360).

**Comment by RenderHeadsSte** [comment]
Cross-over posts! Cool  :)

Did you try deleting audio360.jar from the Plugins/Android folder prior to building?  So at least you don't have to go through the mess of exporting the project.

**Comment by RenderHeadsSte** [comment]
Oh a side note, looking further down the track, we have the ability to build in the facebook360 lib now, rather than include it.  This might offer a path to having it's libopus dependency externally - which is the bad-thing/criticism here, and one that can be levelled at Photon as well.

**Comment by paulgullett** [comment]
Hello

Appreciate the fast response. Yes I did try deleting it and that didn’t work. I may revisit now I know what I am looking for.

Regards
Paul

**Comment by paulgullett** [comment]
Yes Photon, and plugins at some point start tripping over each other, so no worries. Just need to find a path to allow a simpler build

**Comment by paulgullett** [comment]
It sure can, but I guess everyone uses what they have

On a side not, any guidance on using the skybox in VR. I have a render texture setup and am using ApplyToMaterial, but the texture slot in ApplyToMaterial won’t take the render texture, just trying to debug.

Getting the error 

Material doesn’t have a texture property _MainTex

In Unity the skybox material has a _Tex not a _MainTex

Regards
Paul

**Comment by RenderHeadsSte** [comment]
Have you tried setting 'Texture Property Name' in the ApplyToMaterial script/object to '_Tex' ?

**Comment by RenderHeadsSte** [comment]
I see you have posted another issue regarding the above.  Will reply there.

Closing this issue now, do please re-open it if you gather more info for a more elegant fix or see more issue.
