### ISSUE TITLE
Material doesn't have a texture property '_MainTex'

### ISSUE THREAD

**Issue by paulgullett** [RenderHeads/UnityPlugin-AVProVideo#229]
**Describe the bug**
Using RenderHeads.Media.AVProVideo.ApplyToMaterial to set the skybox

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.11f1
 - AVPro Video version: Trial version from web site
 - Operating system version: Android
 - Device model: Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size): N/A

**To Reproduce**
1. Use ApplyToMaterial to set skybox

**Logs**

E/Unity: Material doesn't have a texture property '_MainTex'

However, this has caught me before SkyBox has a _Tex

skyboxMaterial.SetTexture("_Tex", texture);
Will have a play and see whether I am missing something

**Comment by RenderHeadsSte** [comment]
Have you tried setting the 'Texture Property Name' field in the ApplyToMaterial script?

Without that set it will do this:  _material.mainTexture = texture;

With it set it will do this:  _material.SetTexture(_texturePropertyName, texture);

**Comment by paulgullett** [comment]
Couldn’t get this working and with the overhead of the two step with Gradle parked it and moved on, no matter what I tried it kept grumbling about not finding _mainTex.

I think it was more to do with initialisation issues. I had to get a reference to the MediaPlayer and ApplyToMaterials to allow me to do what I wanted to do and then set url, material etc from there.

**Comment by RenderHeadsSte** [comment]
Some more info on this...

The Unity skyboxes have 6 textures:  _FrontTex, _BackTex, _LeftText, _RightTex, _UpTex, _DownTex

We are working on a skybox shader that takes a facebook 3x2 face frame formatted video that might help you in what you need.

**Comment by paulgullett** [comment]
You are a star, that would be perfect

**Comment by RenderHeadsSte** [comment]
For future viewers of this issue...

@MorrisRH has written a skybox shader that will be included in future versions of AVPro Video.
