### ISSUE TITLE
AVProWindowsMedia for H264 encoded videos

### ISSUE THREAD

**Issue by spaul13** [RenderHeads/UnityPlugin-AVProVideo#23]
I am using the AVPro MediaPlayer to play my own H.264 encoded 360 video stream in Unity on Windows Platform. But while playing that video files it's showing me the following errors.

Errors :
**_[AVProWindowsMedia] Movie failed to load - do you have the required codecs installed?
[AVProWindowsMedia] For MP4 files you need an MP4 splitter such as Haali Media Splitter or GDCL.
[AVProWindowsMedia] For HIGH profile H.264 videos you need to install an external H.264 decoder._**

Can u please tell me what are additional things I have to install and add to make the H.264 encoded videos work with AVPro?

**Comment by AndrewRH** [comment]
AVPro Windows Media is a very old plugin and we no longer support it.  We replaced it with the AVPro Video plugin a number of years ago.  We recommend switching to this.   Otherwise, in your case you can try installing LAV Filters (3rd party codec).
