### ISSUE TITLE
DirectShow: more options to control the filters graph

### ISSUE THREAD

**Issue by chainikdn** [RenderHeads/UnityPlugin-AVProVideo#230]
Basically, it'd be great to be able to add a post-processing filter (i.e. ffdshow raw video filter) to the filter chain.

Why?
High frame rate is very important in VR, so many users use a video frame interpolation software ("SVP"). The problem is it uses ffdshow to inject into a video player, so with any VR video player available now (and they all are based on AVPro) the only way is to force "ffdshow video decoder" as a system-default one. It's outdated, software-only and doesn't even support H.265. 
The best way to use SVP is LAV video decoder + ffdshow raw filter combo, but there're no ways to configure such filter chain in AVPro and, in turn, in the video players (e.g. DeoVR, Whirligig).

The other possible solution was to do something on the LAV side, but they said it's up to the video player to configure the filter chain (which is absolutely true) - https://github.com/Nevcairiel/LAVFilters/issues/321

**Comment by AndrewRH** [comment]
Closing this as there is little other interest for this feature.
