### ISSUE TITLE
restart android application video doens't play

### ISSUE THREAD

**Issue by a-sousa** [RenderHeads/UnityPlugin-AVProVideo#231]
Problem description:

On android Application if i close application and reopen video doesn't play any more
I need to restart device to play again

Device (which devices are you having the issue with - model, OS version number):

android 6.0.1 and some others

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1 video 1920x1080 mp4

System Information:

AVPro Video: plugin v1.10.1t scripts v1.10.1
Target Platform: Android
Unity: v2019.1.2f1 WindowsEditor

**Comment by RenderHeadsSte** [comment]
Can you send a sample project to unitysupport@renderheads.com showing this issue please?

**Comment by frogpjn** [comment]
We are having the same problem.....
I'd appreciate it if you could fix it.

**Comment by RenderHeadsSte** [comment]
@frogpjn Can you send a sample project to unitysupport@renderheads.com showing this issue please?

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response.
