### ISSUE TITLE
Adding Chromecast for your AVpro plugins

### ISSUE THREAD

**Issue by gvax-tv** [RenderHeads/UnityPlugin-AVProVideo#232]
Hello,

Hope you are well.

Do you think it would be possible to add chrome cast into your plugin directly? 
I’m using your plugin in my Apps for Android, Android TV, IOS and Apple Tv, and this would be the greatest feature to have, so either it has to be developed in Unity from scratch, or maybe you are already working on it’s implementation within your plugin.

Please let me know if that feature will be available, if not how I could help (even pay) to have it implemented 

It would be a great addition to your features!

Many thanks for getting back to me.
Kind regards

**Comment by RenderHeadsSte** [comment]
We have no plans to implement this feature currently.

**Comment by AndrewRH** [comment]
Closing as not much interest in this feature and a lot of work to implement and not really the aim of this plugin
