### ISSUE TITLE
Resources Folder question

### ISSUE THREAD

**Issue by ColorTwist** [RenderHeads/UnityPlugin-AVProVideo#234]
Since the `Resources `folder is included in the asset it has some icons and shaders which will be included in the build.
Which shaders do AVPRO use for Android (Exp player) and iOS ( ypcbcr420 enabled) for streaming video with a URL?
Is it safe to remove the folder or rename it?

**Comment by ColorTwist** [comment]
anyone?

**Comment by RenderHeadsSte** [comment]
As we cannot pretend to know what components/materials you have used in your project, we cannot really comment on what would be _safe_ to remove.  I am afraid it will be a matter or trial and error should you want to trim down the asset resource set.

You cannot rename the folder without causing error and undefined behaviour.

Icons should be safe to be removed.  Worse case Unity will throw in a dummy replacement.
