### ISSUE TITLE
Can't open video on Android System.

### ISSUE THREAD

**Issue by raindropfall** [RenderHeads/UnityPlugin-AVProVideo#236]
**Describe the bug**
<br>The last two days I investigate the availability of AVPro Video as a way of playing online video on Android platform, however, it can't normally play one video on the Android phones.
<br>I tried to fix the problem by reading the issues here, but I failed again and again after taking some fixes.
<br>In my tests, I have tried ExoPlayer&MediaPlayer, mono and IL2CPP, and I also check the Inspector window of files on libs/arm64-v8a... Unfortunately, I can't still play videos online nor locally. I wonder is there any configs that I ignored in the trail? Please Help!

**Your Setup (please complete the following information):**
 - Unity version: Unity2019.3.0f3
 - AVPro Video version: AVPro Video 1.9.16
 - Operating system version: Andorid10, Android 7.1.1
 - Device model: Huawei Mate 30 Pro 5G, Oppo R11, respectively
 - Video specs (resolution, frame-rate, codec, file size): format: mp4

**To Reproduce**
1.  Import AVPro Video 1.9.16. In AVPro Video directory, only left Resources/Shaders and Scripts. In Plugins, only leave Android. Set all the files in Android/libs/arm64-v8a, select only Android, and selecte CPU ARM64.
2.  In Preferences, use all default settings besides "Android NDK". Download android-ndk-r19 and browse it.
3.  In Project Setting/Player/Other Settings, set **Mininum API levels** to API level 19,  **Target API Level** to Automatic, **Scipting Backend** to IL2CPP, **API compatibility Level** to .NET standard 2.0, **Target Archetecture** select both, **Install Location** select Prefer External, **Internet Access** select Require and **Write Permission** select External. All the other use default settings.
4. In Build Settings, I selected "Don't overried", "32-bit", "Default device" and "LZ4".

**Logs**
There is no logs, even the scripts are designed to show logs on Text component.

**Screenshots**
The screen shows only blank.

**Videos**
1. https://media.w3.org/2010/05/sintel/trailer.mp4
2. http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Have you tried using the latest version of AVPro Video? (1.10.1)

**Comment by raindropfall** [comment]
Not yet, I'll try it.

**Comment by raindropfall** [comment]
I have just tried it, and here is the result.
The problems are most solved, but the case that when I play network video via scripting, there's still blank on screen. But when I directly input a url in MediaPlayer and PlayOnAwake, there's nothing wrong.
Why?

**Comment by RenderHeadsSte** [comment]
Have you set the 'Source Path' (FlieLocation) to FileLocation.AbsolutePathOrURL ?

It is 'location' in the standard open function...

OpenVideoFromFile(FileLocation location, string path, bool autoPlay = true)

**Comment by AndrewRH** [comment]
It sounds like this issue has been resolved and we have not heard anything else back.  I will close this issue now.  If you're still having problems please create a new ticket.  Thanks,
