### ISSUE TITLE
Microphone plugin (wrapper by AudioUnit) and AVPro use togethers will appear a little noisy randomly

### ISSUE THREAD

**Issue by 3wz** [RenderHeads/UnityPlugin-AVProVideo#237]
**Describe the bug**
In my project, I need to turn on the microphone all the time, and then play the video at the same time. The video playback method is to play many video clips continuously. The earliest we used the built-in microphone component of Unity, but we found that some equipment will have another problem, when using with the AVPro plug-in, there will be a problem that the microphone component cannot collect audio data. Later, the project sought another microphone plug-in. At first, we found the NatMic plug-in in the Unity store. This plug-in interface is simple and friendly to use. But when using this plug-in, a new problem appeared, which is the problem mentioned in my title. When using this plug-in with the AVPro plug-in, there will be a random small popping problem. It is not fixed in the process of continuous video playback. The appearance of is a random appearance. It confuses me. I switched back to the Unity microphone component. This problem no longer occurs. Basically, I can determine that it is a problem with the AVPro plug-in. Then I tested to stop playing the video and then turned on the microphone with the NatMic plug-in. There was no noise problem. Since the NatMic plugin does not open OC-level source code, I can't try to modify anything. Later, I researched how to implement an iOS low-latency microphone plug-in. I checked a lot of information and spent a lot of time writing one. Then I tested it. The problem is still the same as using the NatMic plug-in. It's OK to double check. I can only come here for help. I haven't yet developed a test demo, but I recorded a video to demonstrate this problem. This problem appears at the end of the video.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.7
 - AVPro Video version: 1.10.1
 - Operating system version: iOS
 - Device model: All
 - Video specs (resolution, frame-rate, codec, file size): 480*360，24fps，h.264，1.64MB

**Videos**
https://youtu.be/XqwDkdjSx9w

**Comment by MorrisRH** [comment]
Not sure what is happening here; we don't do any processing of the audio in the plugin, playback is entirely handled by Apple's APIs.

I'm wondering if something is triggering a change to the audio configuration...
Do you have "Prepare iOS for Recording" enabled in the iOS Player settings?

**Comment by 3wz** [comment]
yes，I enabled the "Prepare iOS for Recording",  I google that will improved the micphone api started speed. so I enabled it.

**Comment by 3wz** [comment]
about the audio  config, I only set once when I begin play the video. and in my project, the videos are played one by one. I noticed that when I play video, AVPro seems to change audio config. when all the videos played  complete, I will stop the microphone.

**Comment by MorrisRH** [comment]
"Prepare iOS for Recording" should put the audio session in the correct state and not need touching after that. We don't modify the audio session at all in the plugin so any changes to the session will be coming from Apple's lower level stuff.

**Comment by 3wz** [comment]
It's really strange, but I will try to do more tests to guess the problem.

**Comment by AndrewRH** [comment]
@3wz did you manage to resolve this or discover any more clues?  Thanks,
