### ISSUE TITLE
some time can not recive "FirstFrameReady" message;

### ISSUE THREAD

**Issue by TopPlay** [RenderHeads/UnityPlugin-AVProVideo#238]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 20192.11
 - AVPro Video version: 
 - Operating system version: windows 10
 - Device model: surface book 1
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
i play a media list with pre load and play,for not show black screen ,so i need this message to switch new video image,but some time can not recivie this message;

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Are you targeting Windows 10?

Would it be possible to send the video/link to unitysupport@renderheads.com ?

**Comment by TopPlay** [comment]
I Debug on windows10 and run on android system,but I found same media allways not notify firstframeready event;
And I want play h264 frame stream by avpro palyer ,can you supports this request?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Ste Butcher <notifications@github.com>
发送时间: Wednesday, January 15, 2020 12:46:05 AM
收件人: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
抄送: TopPlay <iTopPlay@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] some time can not recive "FirstFrameReady" message; (#238)


Are you targeting Windows 10?

Would it be possible to send the video/link to unitysupport@renderheads.com<mailto:unitysupport@renderheads.com> ?

―

**Comment by RenderHeadsSte** [comment]
@TopPlay Do you still require support for this issue?  Would it be possible to email over the video, or paste a link to a stream?

**Comment by TopPlay** [comment]
my phone is huswei p30,some media always can  not decode,so i write a custom decoder by android mediacodec, media can be play, your player can not select right decoder on some device!

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
