### ISSUE TITLE
Some events doesn't work on iOS.

### ISSUE THREAD

**Issue by Crash-512** [RenderHeads/UnityPlugin-AVProVideo#239]
Big part of API doesn't work on iOS (but works fine on Android).

**Events:**
Stalled
Unstalled
StartedSeeking
FinishedSeeking
StartedBuffering
FinishedBuffering

**Methods:**
IMediaInfo.IsPlaybackStalled()
IMediaControl.IsBuffering()

 - Unity version: 2018.4.13f
 - AVPro Video version: 1.10.1 
 - Operating system version: iOS 13.3, 12.1.4
 - Device model: iPhone XS, XS Max, iPad mini.
 - Video specs: MP4 (AAC, H.264, 960x540, 5.7 Mb)

**Comment by MorrisRH** [comment]
Stalled and Unstalled are not implemented but their behaviour would be identical to the buffering events.

Seeking and buffering events should be firing correctly though.

**Comment by tyler-o3h** [comment]
I've noticed the StartedSeeking and FinishedSeeking events won't get called if you seek to a position that has already been loaded. I would assume it's the same behaviour with the buffering events.

**Comment by MorrisRH** [comment]
Unfortunately seeking and buffering events can mask each other so you'll see one or the other but never both which is obviously wrong. We're working towards a fix.

**Comment by MorrisRH** [comment]
Reworked the underlying system so that seeking and buffering can no longer mask each other.
Also worked in stalled handling independent of buffering.

**Comment by MorrisRH** [comment]
This has been released with version 1.10.3.
