### ISSUE TITLE
Not working on Android with Unity 2019.3.0f3

### ISSUE THREAD

**Issue by JanOwiesniak** [RenderHeads/UnityPlugin-AVProVideo#240]
**Bug**

Video Player is not working on Android with Unity 2019.3.0f3

**Setup**

 - Unity version: 2019.3.0f3
 - AVPro Video version: 1.10.1
 - Operating system version: macOS Mojave 10.14.6 (18G103)

**Reproduce from scratch**

1. Install Unity 2019.3.0f3
2. Install AVPro Video 1.10.1
3. Load demo scene 04_Demo_uGui
4. Set Android plugin import settings for all files

![Screenshot 2020-01-02 at 17 29 49](https://user-images.githubusercontent.com/213214/71678640-f0148b80-2d85-11ea-81cf-723743e1c2d1.png)
![Screenshot 2020-01-02 at 17 29 57](https://user-images.githubusercontent.com/213214/71678641-f0148b80-2d85-11ea-9c22-c776f6584df0.png)
![Screenshot 2020-01-02 at 17 30 07](https://user-images.githubusercontent.com/213214/71678642-f0148b80-2d85-11ea-8421-af7804ce182a.png)

5. Export project to Android
6. Open project with Android Studio
7. Run project on test device 

**Reproduce with sample project** 

1. Checkout https://github.com/JanOwiesniak/UnityPlugin-AVProVideo-Android
2. Load Video scene
3. Export project to Android
4. Open project with Android Studio
5. Run project on test device

**Logs**

```
2020-01-02 17:17:58.383 9634-9683/? E/Unity: Unable to find libAudio360
2020-01-02 17:17:58.391 9634-9683/? E/Unity: Unable to find libopus
2020-01-02 17:17:58.396 9634-9683/? E/Unity: Unable to find libAudio360-JNI
2020-01-02 17:17:58.401 9634-9683/? E/Unity: Unable to find libopusJNI
2020-01-02 17:17:58.404 9634-9683/? E/Unity: Unable to find libAVProLocal
2020-01-02 17:18:01.203 9634-9683/<myapp> E/Unity: [AVProVideo] Vulkan graphics API is not supported 
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2020-01-02 17:18:01.244 9634-9683/<myapp> E/Unity: [AVProVideo] Not supported on this platform Android samsung SM-A505FN ARM64 FP ASIMD AES Android OS 9 / API-28 (PPR1.180610.011/A505FNXXU1ASD6).  Using null media player! 
    (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

**Comment by RenderHeadsSte** [comment]
Looks like there are two issues here with you setup...

1) As the log suggests, APro Video Vulkan graphics API is not supported.  Please remove it from the graphics API list and use OpenGL.

2) It looks like you are using ARM64.  You will need to do the following...

Check the arm64 plugin files are flagged for (platform) Android and (CPU) ARM64. There are 5 of them (listed below) and they live under the folder: Plugins/Android/libs/arm64-v8a/

libAudio360.so
libAudio360-JNI.so
libAVProLocal.so
libopus.so
libopusJNI.so

**Comment by AndrewRH** [comment]
Hi @JanOwiesniak ,

Does the above solve your problem?  Is it does then we can close this ticket.

And then please could you also remove the GitHub repo containing our plugin, especially if it is the non-trial version.

Thanks,

**Comment by JanOwiesniak** [comment]
@AndrewRH yes it does. This issue was that i was using Vulkan instead of OpenGL.
@RenderHeadsSte thanks for your answer and sorry for not responding to this issue sooner.
