### ISSUE TITLE
AVPro for WebGL on iOS

### ISSUE THREAD

**Issue by pemmerich** [RenderHeads/UnityPlugin-AVProVideo#241]
**Describe the bug**
Hi,
 
My team has been struggling with AVPro using WebGL from Unity.
 
The video player seems to work well on everything but iOS.
After reverting to the IMGUI component we were able to get video to work in WebGL for iOS, but only on iPads. The same video still won’t play on iPhones.
 
I was hoping maybe you have some insight or best practices you can suggest for our team. We have been working on this for a week and so far iPhones are still a problem.

**Your Setup (please complete the following information):**
 - Unity version: Latest
 - AVPro Video version: Latest
 - Operating system version: Windows 10
 - Device model: iPhone 8 - iPhone X
 - Video specs (resolution, frame-rate, codec, file size): 720p, 30fps, h.264, 4MB

**Comment by MorrisRH** [comment]
Apple's WebGL support is woefully lacking in Safari so I'm impressed you got it to work on iPad.

To the best of my knowledge Unity's WebGL player requires WebGL2.0 and iOS Safari only supports WebGL1.0. You can enable WebGL2.0 support in the Settings app, however even with WebGL2.0 support enabled I've not been able to get a build to work.

I'm afraid that as this is an issue with Safari on iOS (and to a lesser extent macOS) there is little we can do to help.
