### ISSUE TITLE
Unity 2019.2.6f1 brings up error VRDevice' is obsolete

### ISSUE THREAD

**Issue by leesfs** [RenderHeads/UnityPlugin-AVProVideo#243]
**Describe the bug**

When I import the latest release from the Asset Store into Unity 2019.2.6f1, i get the following errors.

error CS0619: 'VRDevice' is obsolete: 'VRDevice has been moved and renamed. Use UnityEngine.XR.XRDevice instead (UnityUpgradable) -> UnityEngine.XR.XRDevice'

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.6f1
 - AVPro Video version: 1.10.1
 - Operating system version: windows 10

 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

![4BC7529C-A4F4-43FB-B522-498D2F1153CA](https://user-images.githubusercontent.com/59626918/71934918-673e8b00-319d-11ea-91c6-4e5c8c95cd4a.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
I have downloaded a fresh version of 2019.2.6f1 and imported the latest trial package of AVPro Video and do not get the error you are reporting.  Are you importing over a previous (older) version of AVPro Video?

**Comment by AndrewRH** [comment]
Yeah it looks like Unity just didn't do it's automatic conversion.  When you import the plugin it should ask if you want to automatically upgrade the scripts - Select YES.
I'm going to close this as importing the plugin again and letting Unity upgrade the scripts should work.

Thanks,
