### ISSUE TITLE
Video crash in VR - Oculus Virtual Audio Device

### ISSUE THREAD

**Issue by ArnaudC2Care** [RenderHeads/UnityPlugin-AVProVideo#244]
Since the last update of Oculus (software on windows), when I launch a video there is the following errors:

> XR: Error setting active audio output driver.  Falling back to default.

and
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

The last Oculus Update creates a new audio device on Windows (Oculus Virtual Audio Device) used by default by the headset, I have this error with this configuration and the video doesn't start.
When I switch to select the old audio device (Rift S), the video starts without errors.

**Setup**
 - Unity version: 2018.4.2f1
 - AVPro Video version: 1.10.1
 - Operating system version: Windows 10 Pro version 1909

**To Reproduce**
In Unity Editor, launch a video (with the plugin) with an Oculus headset connected with the last update of Oculus (be sure to have the Oculus Virtual Audio Device selected), the last update of the plugins AVPro Video and Oculus Integration.

**Comment by Sense** [comment]
I also encounter exactly the same error since the last Oculus update.

**Comment by JasonC2Care** [comment]
The problem is still present and we have no interesting solution
