### ISSUE TITLE
Error when building for Android device

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#246]
**Describe the bug**
Got the following error when i build demo for Android
CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Unity.3.14\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "C:\Program Files\Unity.3.14\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "bundleRelease"

stderr[
D8: Program type already present: com.google.android.exoplayer2.source.dash.DashMediaSource$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.

**Comment by RenderHeadsSte** [comment]
DEX errors are always when a duplicate library is linked.  From this limited information I would fathom a guess that something else in your project is including ExoPlayer.

**Comment by nsmith1024** [comment]
Yes i do have another Unity Video ExoPlayer in there that was giving me problems (Universal Media Player from unity asset store) it keeps running out of memory on Android after playing just a few short 1 minute videos. 

So im trying to switch to yours to see if its better, im just using your demo  version now, if it works i will buy the full version!!! fingers crossed!!!

Will keep you posted
Thanks

**Comment by RenderHeadsSte** [comment]
Ah, cool.  Yeah, that will be the problem.  Lose that (maybe back-up first :) ) and you shouldn't have any problems building.
