### ISSUE TITLE
Cubemap not supporting stereo

### ISSUE THREAD

**Issue by realitygarage** [RenderHeads/UnityPlugin-AVProVideo#249]
**Describe the bug**
Trying to get a L/R stereo to work with cubmap. There is no demo / prefab setup, but I added the stereo component to the Cube object, and no luck. The video I am using plays great in the GoPro VR player, set ti cubemap and l/r stereo.

**Your Setup (please complete the following information):**
 - Unity version: 19.3
 - AVPro Video version: latest 1.10.1
 - Operating system version: running in the editor 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. create l/r stereo cuebmap video
2. create scene from cubemap demo scene, add stereo component to cube
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

https://rg-drop-bucket.s3.us-west-2.amazonaws.com/Outgoing/take2-2-cm32.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by realitygarage** [comment]
any feedback on this?

**Comment by AndrewRH** [comment]
Hi,

Thanks for reporting this issue.  Yes you're right, the stereo option is lacking in the Cubemap Cube component.

I've attached a fixed version here - just replace the script with this one.  

Let me know if that solves the issues for you.  We will include this in the next plugin release then.

Thanks,
[CubemapCube.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4220695/CubemapCube.zip)

**Comment by realitygarage** [comment]
Thanks much! Will test and revert back next week :)
On a related topic... Are you all familiar with visbit? Any chance you guys are cooking any similar technology for foveated rendering to get higher resolution out of the VR headsets? 

Thanks

**Comment by AndrewRH** [comment]
Yes please let me know if it resolves the issue so that we can close this ticket :)

visbit..no we haven't heard about that.... It's not on our roadmap I'm afraid.

**Comment by RenderHeadsSte** [comment]
We shall be closing this bug shortly due to lack of response.

**Comment by amoebatron** [comment]
Wow. This has been driving me crazy. Finally found the solution. Thanks.

**Comment by realitygarage** [comment]
will test this out today :)

**Comment by realitygarage** [comment]
sorry - have to buy another day - but promise to test tomorrow - THANKS FOR YOU GREAT SUPPORT !

**Comment by AndrewRH** [comment]
The shader I attached here should work.  You just need to also add the UpdateStereoMaterial to your scene (if it's not here already) and set it to the correct camera and mesh....

**Comment by AndrewRH** [comment]
I'm closing this issue now as I believe we have given a solution and haven't heard otherwise.  Thanks,

**Comment by realitygarage** [comment]
Thanks for the solution - sorry for lagging. I am sure it will work fine... I will pu and use as soon as possible - been a bit crazy lately

**Comment by amoebatron** [comment]
To be honest I still never got it to work, even with the added UpdateStereoMaterial. What we're probably going to do is hire someone to create a prefab that we can reverse engineer. The issue for us might be the new Youtube VR format. Still not sure why it doesn't work.

**Comment by AndrewRH** [comment]
I've including this fix and a also a new demo scene that uses cubemap and sphere map on the unity Skybox.  hopefully these may also help you.
If you're still having issues please open a new ticket as closed tickets are not checked.  Thanks!
