### ISSUE TITLE
Save streamed video (fragments) to local storage

### ISSUE THREAD

**Issue by RemyRM** [RenderHeads/UnityPlugin-AVProVideo#25]
**Is your feature request related to a problem? Please describe.**
As far as I am aware there is no current method exposed that allows for saving streamed video(fragments) to local storage so it can be replayed from local storage at a later time, without having to be streamed again.

**Describe the solution you'd like**
Have a method exposed (or overloaded) that allows for saving streamed data to a local path.
I would imagine something like:
```
//The original OpenVideoFromFile method overloaded with a destination
public bool OpenVideoFromFile(FileLocation location, string path, bool autoPlay = true, string destination = "")
```

That is called like this

```
MediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, "http://192.168.0.1:8080/foobar.m3u8, true, Application.PersistentDataPath + "/Downloads/");
```
Preferred this would be done on a seperate thread so it doesn't block the stream. However I can imagine this may be a problem for some devices, so this should probably be optional.

Writing to file can be done using the standard `FileStream` class.

**Describe alternatives you've considered**
Currently I am redirecting all video requests through a HttpListener so I can catch and create a copy of the streamed data to be used for local storage, before sending the stream back to AVPro/mediaplayer using the HttpListener.Response.

**Comment by RemyRM** [comment]
any chance version 2.x will see a functionality like this?

**Comment by AndrewRH** [comment]
Closing this issue, as this feature has partially been implemented in AVPro Video 2.x as the media caching feature on mobile (iOS and Android).
