### ISSUE TITLE
is there any parameter or setting that determines the alpha value of texture produecd by MediaPlayer component? What we need to do to get the alpha 1?

### ISSUE THREAD

**Issue by garric** [RenderHeads/UnityPlugin-AVProVideo#250]
The MediaPlayer component produces a texture with alpha 0(black) in our project.
![image](https://user-images.githubusercontent.com/1220348/72581775-72bb5000-391b-11ea-8afa-aace31b549af.png)
But with the same video file, When I tested it in a demo project, the texture is outputed with alpha 1(white)。
![image](https://user-images.githubusercontent.com/1220348/72581791-823a9900-391b-11ea-8155-0694bc27b0a5.png)

**So, is there any parameter or setting that determines the alpha value of texture produecd by MediaPlayer component? What we need to do to get the alpha 1?**

System Information:

AVPro Video: plugin v1.10.1 scripts v1.10.1
Target Platform: Standalone
Unity: v2018.4.13f1 WindowsEditor
OS: Desktop - Precision Tower 3620 (Dell Inc.) - Windows 7  (6.1.0) 64bit - Chinese
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz - 8 threads - 16275KB
GPU: GeForce GTX 1050 Ti/PCIe/SSE2 - NVIDIA Corporation - OpenGL 4.5.0 NVIDIA 440.97 - 3998KB - 32768

**Comment by AndrewRH** [comment]
The only thing I can think of is this option:
![image](https://user-images.githubusercontent.com/5418126/75018542-089c4a80-5487-11ea-848f-127032181ac8.png)

But I'm not sure why the same video would decode differently on the same system....Did anything else change?   If it's on a different system then it could decode differently when using DirectShow, because there could be a different H.264 decoder installed that handles alpha differently.

If you could provide more information then I can try to offer more help/suggestions

**Comment by garric** [comment]
Hi, sorry to replay after a long time.
There's no difference whether I check the "Alpha Channel Hint" or not.
What's else information should I  send to you?

**Comment by garric** [comment]
I set the Windows platform options like yours
![image](https://user-images.githubusercontent.com/1220348/77150646-48c70b00-6acf-11ea-9372-791348f723aa.png)
And I Find that the preview shows decoding using DirectShow。Is this matter?
![image](https://user-images.githubusercontent.com/1220348/77150733-7f9d2100-6acf-11ea-99b9-6c8eefa2fee8.png)

**Comment by garric** [comment]
I also find that, when working in linear space, the texture genearted by MediaPlayer give two  results:
1.using DirectShow(like normal srgb)
![image](https://user-images.githubusercontent.com/1220348/77417741-c4db8e80-6e00-11ea-9328-5e6e9d6aeaba.png)
2.using Media Foundation(like another gamma correction of normal srgb, more bright)
![image](https://user-images.githubusercontent.com/1220348/77417773-d4f36e00-6e00-11ea-8513-20fc3a150878.png)
the difference is driven by video codec(Directshow/MediaFoundation)? or by MediaPlayer?
What' about mobile platform?

**Comment by AndrewRH** [comment]
> I also find that, when working in linear space, the texture genearted by MediaPlayer give two results:
> 1.using DirectShow(like normal srgb)
> ![image](https://user-images.githubusercontent.com/1220348/77417741-c4db8e80-6e00-11ea-9328-5e6e9d6aeaba.png)
> 2.using Media Foundation(like another gamma correction of normal srgb, more bright)
> ![image](https://user-images.githubusercontent.com/1220348/77417773-d4f36e00-6e00-11ea-8513-20fc3a150878.png)
> the difference is driven by video codec(Directshow/MediaFoundation)? or by MediaPlayer?
> What' about mobile platform?

Please try the latest version 1.10.2 as this brightness difference should now be fixed.  Thanks,

**Comment by garric** [comment]
> I set the Windows platform options like yours
> ![image](https://user-images.githubusercontent.com/1220348/77150646-48c70b00-6acf-11ea-9372-791348f723aa.png)
> And I Find that the preview shows decoding using DirectShow。Is this matter?
> ![image](https://user-images.githubusercontent.com/1220348/77150733-7f9d2100-6acf-11ea-99b9-6c8eefa2fee8.png)

How about this one?

**Comment by AndrewRH** [comment]
> > I set the Windows platform options like yours
> > ![image](https://user-images.githubusercontent.com/1220348/77150646-48c70b00-6acf-11ea-9372-791348f723aa.png)
> > And I Find that the preview shows decoding using DirectShow。Is this matter?
> > ![image](https://user-images.githubusercontent.com/1220348/77150733-7f9d2100-6acf-11ea-99b9-6c8eefa2fee8.png)
> 
> How about this one?

Which operating system are you using?   Media Foundation is only available in Windows 8.1 and above, and even then some versions of Windows (K/N editions) don't include it by default and require an extra download from Microsoft (Media Pack).

If you're using Windows 7 then it will always fall back to DirectShow

**Comment by AndrewRH** [comment]
As for your alpha issue - I wonder if it's due to the Graphics API used?  
Perhaps your project is using OpenGL, but the other project is using DirectX9/11?

**Comment by garric** [comment]
> As for your alpha issue - I wonder if it's due to the Graphics API used?
> Perhaps your project is using OpenGL, but the other project is using DirectX9/11?

System Information:

AVPro Video: plugin v1.10.1 scripts v1.10.1
Target Platform: Standalone
Unity: v2018.4.13f1 WindowsEditor
OS: Desktop - Precision Tower 3620 (Dell Inc.) - Windows 7 (6.1.0) 64bit - Chinese
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz - 8 threads - 16275KB
GPU: GeForce GTX 1050 Ti/PCIe/SSE2 - NVIDIA Corporation - OpenGL 4.5.0 NVIDIA 440.97 - 3998KB - 32768

We used to force opengl on Windows, but other computer using win10 shows alpha right. And we have switched to dx11 recently, but the alpha still output zero on computer using win7

**Comment by garric** [comment]
> As for your alpha issue - I wonder if it's due to the Graphics API used?
> Perhaps your project is using OpenGL, but the other project is using DirectX9/11?

You're right! When I swithced to Dx11, it's ok now. :)
So why OpenGL will make the output of alpha zero?
