### ISSUE TITLE
Is 8K movie impossible to play  at Oculus go or pico g2 by avpro?

### ISSUE THREAD

**Issue by igom11** [RenderHeads/UnityPlugin-AVProVideo#251]
Problem description:

Is 8K movie impossible to play by avpro at Oculus go or pico g2?

Device (which devices are you having the issue with - model, OS version number):

PICO G2 4K 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

8k  https://www.youtube.com/watch?v=b6vQQit2ZU8

System Information:

AVPro Video: plugin v1.10.1 scripts v1.10.1
Target Platform: Android
Unity: v2019.2.6f1 WindowsEditor
OS: Desktop - PB50_70EF,ED,EC (Notebook) - Windows 10  (10.0.0) 64bit - Japanese
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 12 threads - 16293KB
GPU: NVIDIA GeForce RTX 2070 - NVIDIA - Direct3D 11.0 [level 11.1] - 8031KB - 16384

**Comment by gtk2k** [comment]
The highest image quality that can be played on Oculus Go is 6K (5760x2880)
https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/

日本語
Oculus Go(Quest)で再生可能な動画の解像度は6K(5760x2880)です。
このページに解説があります。
https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/
PICOはわかりません。
