### ISSUE TITLE
Extract frame causes device hang and no resulting texture

### ISSUE THREAD

**Issue by tyler-o3h** [RenderHeads/UnityPlugin-AVProVideo#254]
When calling ExtractFrame or ExtractFrameAsync on a video file that has rotation, the device will hang/freeze for a few seconds then throw an error, and never return a texture

 - Unity version: 2019.2.5f1
 - AVPro Video version: 1.10
 - Operating system version: OSX 10.14.6
 - Device model: iPhone 11 Pro, ios 13.3
 - Video specs: Seems to be any video taken with the device camera

**To Reproduce**
1. Capture video with device camera (or have existing one saved)
2. Load video in avpro player
3. Call ExtractFrame or ExtractFrameAsync

**Logs**
`Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)`

**Comment by tyler-o3h** [comment]
I've narrowed the issue down to the GL.Clear call in Interfaces.GetReadableTexture, if I comment that line out then it works as expected. I notice that line is not in the similar block of code above it, so it seems likely it isn't necessary but I'm not sure what the clear call was for.

**Comment by AndrewRH** [comment]
@MorrisRH were you able to replicate this issue?  
I wonder if it was an old driver/OS issue or something...

**Comment by MorrisRH** [comment]
Cannot reproduce this using the ExtractFrame demo.
@tyler-o3h might be worth you sending on the video in question.

**Comment by MorrisRH** [comment]
This issue will be closed soon as we haven't heard more details and can't replicate the issue.

**Comment by roger-o3h** [comment]
This is still occurring for me on an iPhone 11, iOS 15.6.1, using AVPro 2.6.2, inside Helper.cs `GetReadableTexture(Texture, bool, Orientation, Texture2D)` right at the `GL.Clear()` line, and can still be fixed with no apparent downside by removing that clear.

The GPU pipeline (and app) stalls, and I get the error:
```
2022-10-31 16:06:37.113666-0700 OoohSDK[11459:588348] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)
2022-10-31 16:06:37.114567-0700 OoohSDK[11459:588348] MTLCommandBuffer Encoder state summary:
 Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)" UserInfo={NSLocalizedDescription=Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout), MTLCommandBufferEncoderInfoErrorKey=(
    "<errorState: MTLCommandEncoderErrorStateFaulted, label: (null), debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateAffected, label: [R] GUITexture.Draw, debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateAffected, label: (null), debugSignposts: (null)>"
)}
2022-10-31 16:06:37.114975-0700 OoohSDK[11459:588348] MTLCommandBuffer Encoder state summary:
 Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)" UserInfo={NSLocalizedDescription=Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout), MTLCommandBufferEncoderInfoErrorKey=(
    "<errorState: MTLCommandEncoderErrorStateFaulted, label: (null), debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateAffected, label: [R] GUITexture.Draw, debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateAffected, label: (null), debugSignposts: (null)>"
)}
2022-10-31 16:06:37.115411-0700 OoohSDK[11459:588348] MTLCommandBuffer Encoder state summary:
 Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout)" UserInfo={NSLocalizedDescription=Caused GPU Timeout Error (00000002:kIOGPUCommandBufferCallbackErrorTimeout), MTLCommandBufferEncoderInfoErrorKey=(
    "<errorState: MTLCommandEncoderErrorStateFaulted, label: (null), debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateAffected, label: [R] GUITexture.Draw, debugSignposts: (null)>",
    "<errorState: MTLCommandEncoderErrorStateAffected, label: (null), debugSignposts: (null)>"
```

I will work to build a test case for this.
