### ISSUE TITLE
FinishedPlaying event on replay

### ISSUE THREAD

**Issue by lupustom** [RenderHeads/UnityPlugin-AVProVideo#255]
In the Unity Editor (2018.4.15, platform is iOS), using the latest version of AVProVideo, if the video is not closed and loaded again, the FinishedPlaying event is only called once after the first finishing of the video, not when replaying the video. Is there another way to tell if a video has finished playing after replaying it without having to close and reload it (and without having to ask the player in the update loop ...)?

**Comment by AndrewRH** [comment]
@MorrisRH  were you able to replicate this?

**Comment by MorrisRH** [comment]
Unfortunately not. Was this a HLS video being played? If so then a fix for a similar issue will be available with the next plugin release (1.10.2) due very soon.
If not then any extra information you can provide would be helpful.

**Comment by lupustom** [comment]
@MorrisRH it's a web hosted m3u8 stream.

**Comment by MorrisRH** [comment]
It should be fixed with version 1.10.2. If you're able to try it and let us know if it's fixed, that would be great.

**Comment by AndrewRH** [comment]
@lupustom  are you able to test in the latest version to confirm that it's working for you now?  

Thanks,

**Comment by lupustom** [comment]
Hi, I was only now able to test it, apologies. But, unfortunately, I only receive the OnFinishedPlaying event the first time, that's it.
