### ISSUE TITLE
Can’t Play mp4 file with Command line arguments -force-gle

### ISSUE THREAD

**Issue by shirahama-manabu-app** [RenderHeads/UnityPlugin-AVProVideo#256]
Can’t Play mp4 file with Command line arguments -force-gles

Windows10 + Unity + Use Command line arguments:None --> Can Play
Windows10 + Unity + Use Command line arguments:-force-gles --> Can’t Play

Please tell us, problem reason and solution.

**Comment by shirahama-manabu-app** [comment]
System Information:
AVPro Video: plugin v1.10.1 scripts v1.10.1
Target Platform: Android
Unity: v2019.2.11f1 WindowsEditor
OS: Desktop - Precision 3630 Tower (Dell Inc.) - Windows 10  (10.0.0) 64bit - Japanese
CPU: Intel(R) Xeon(R) E-2174G CPU @ 3.80GHz - 8 threads - 32597KB
GPU: Quadro RTX 4000/PCIe/SSE2 - NVIDIA Corporation - OpenGL ES 3.2 NVIDIA 431.40 - 8018KB - 32768

**Comment by AndrewRH** [comment]
Hi,

We do not support GLES on Windows desktop.  You could use OpenGL though if you wanted by using the command-line:   "-force-glcore"

Does that help?

**Comment by AndrewRH** [comment]
Closing this issue as I believe it is now resolved.
