### ISSUE TITLE
PICO G2 openGL-error "GL_OUT_OF_MEMORY" with blackscreen but ongoing sound

### ISSUE THREAD

**Issue by andzq** [RenderHeads/UnityPlugin-AVProVideo#258]
We have an app for the Pico G2 with an interactive video player that plays 4096x4096 stereoscopic 360° videos. The AVPro player worked out of the box but every now and then we encounter a blackscreen accompanied by a adb logcat message reading "OPENGL NATIVE PLUG-IN ERROR: GL_OUT_OF_MEMORY: Not enough memory left to execute command". Interestingly the sound still plays but the screens remain black even though at least a crosshair with an always-on-top-shader should be visible, This error can be replicated by us in a specific scenario. 

1. A video of said resolution is being played (H265)
2. While the video is being played we reload the current scene
3. Upon scene reload we start a different video of equal resolution
4. The video that is being played after the scene reload plays audio but screens are black

The frequency of this occurence is totally random but always tends to kinda softlock the app. Controllerbuttons are still handled and reloading the scene can be done, however, the screens always remain in a backlit black. 
Ineffective countermeasures so far were to call "mp.ClearVideo( )" before restarting the scene and before loading any video followed by half a second yield duration. We also made sure it´s no sort of fader that is causing the black screens. This problem started occuring once we switched from EasyMovieTexture to AVPro Video. 

Videos: H265 4096x4096
Method: ApplyToMaterial
Unity: 2019.2.2f1
AVPro Video: 1.10.1

Any suggestions what the cause of this problem is and how we could potentially solve it?

**Comment by nsmith1024** [comment]
I see that too after playing around 20 short videos, each video around 30 seconds long, it crashes with out of memory on Android 7.0. 

When used on Android 8.xxx it crashes with out of memory after just playing just 3 or 4 videos on a tablet.

Android 9 it doesnt play at all

**Comment by nsmith1024** [comment]
ApplyToMaterial is flakey, sometimes i have to turn it on and off SetActive(true/false) before you see the video.

**Comment by andzq** [comment]
Tried turning the applyToMaterial toggle with no effect. I either see the video right away or get the **out of memory**-error.

**Comment by nsmith1024** [comment]
what i do is after the video starts playing i toggle (the ApplyToMaterial game object ) off for around 1 or 2 seconds, then back on and then you can see the video

**Comment by adi5785905** [comment]
Any chance this: [https://forum.unity.com/threads/app-crashes-with-black-screen-and-music-in-the-back.821031/](url) is related (it's my post in the unity forum about it)? Because were stuck on this for a week and nothing helps.

**Comment by andzq** [comment]
> Any chance this: [https://forum.unity.com/threads/app-crashes-with-black-screen-and-music-in-the-back.821031/](url) is related (it's my post in the unity forum about it)? Because were stuck on this for a week and nothing helps.

the link does not lead anywhere

**Comment by adi5785905** [comment]
it says: Awaiting moderation before being displayed publicly.

here it is:
Unity editor: 2019.2.4f1 and 2019.3.0f6
Oculus plugin: 1.44 and 1.40
mono android build api compatibility level .net 4.x
crash and both oculus quest and go.
while the crash itself happens, there is a black screen but the audio and tracking works. Happens most often after a scene loading (but not only). Logcat shows the following:
OPENGL NATIVE PLUG-IN ERROR: GL_OUT_OF_MEMORY: Not enough memory left to execute command
but according to VrApi, Unity profiler and Unity memory profiler there is more then 300 mb of ram (it happens when there is 600 mb of ram as well).
Exporting the project to Android studio gave me the following errors:
W Adreno-GSL: <sharedmem_gpuobj_alloc:2706>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory

E Adreno-GSL: <gsl_memory_alloc_pure:2270>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.

and then a crash (the package name is censored as com.********.**************)
E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

    Version '2019.3.0f6 (27ab2135bccf)', Build type 'Development', Scripting Backend 'mono', CPU 'armeabi-v7a'

E/CRASH: Build fingerprint: 'oculus/vr_monterey/monterey:7.1.1/NGI77B/434260.5710.0:user/release-keys'

    Revision: '0'

    ABI: 'arm'

    Timestamp: 2020-02-02 17:17:11+0200

    pid: 10550, tid: 10752, name: Thread-3  >>> com.********.************** <<<

    uid: 10091

    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1a

    Cause: null pointer dereference

        r0  00000002  r1  00000003  r2  00000000  r3  00000001

        r4  c5d7c8e4  r5  c58836c0  r6  00000000  r7  00000000

        r8  c5d7ca70  r9  c5d7c600  r10 c5885a0c  r11 c588596c

        ip  c5b7e250  sp  c4d7eb78  lr  d9be7405  pc  d9bbdc5c

    backtrace:

          #00 pc 00196c5c  /system/vendor/lib/egl/libGLESv2_adreno.so

          #01 pc 001c0401  /system/vendor/lib/egl/libGLESv2_adreno.so

          #02 pc 0010185f  /system/vendor/lib/egl/libGLESv2_adreno.so

          #03 pc 00151349  /system/vendor/lib/egl/libGLESv2_adreno.so

          #04 pc 00171f49  /system/vendor/lib/egl/libGLESv2_adreno.so

          #05 pc 00974f88  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxFramebufferGLES::InvalidateAttachments(bool const*, bool, bool, GfxFramebufferGLES::InvalidateAttachmentsPurpose)+228) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #06 pc 009763fc  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxFramebufferGLES::PrepareImpl(bool)+412) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #07 pc 009765c8  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxFramebufferGLES::Clear(GfxClearFlags, ColorRGBAf const&, float, int, bool)+292) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #08 pc 009537c8  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxDeviceGLES::Clear(GfxClearFlags, ColorRGBAf const&, float, unsigned int)+56) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #09 pc 00365c2d  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxDeviceWorker::RunCommand(ThreadedStreamBuffer&)+716) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #10 pc 0036c557  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxDeviceWorker::RunExt(ThreadedStreamBuffer&)+50) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #11 pc 0036c505  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxDeviceWorker::Run()+96) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #12 pc 0036580f  /data/app/com.********.**************-1/lib/arm/libunity.so (GfxDeviceWorker::RunGfxDeviceWorker(void*)+2) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #13 pc 007e769f  /data/app/com.********.**************-1/lib/arm/libunity.so (Thread::RunThreadWrapper(void*)+342) (BuildId: 05c939025a1e3503a6fad35329599f82459e83b2)

          #14 pc 00047d83  /system/lib/libc.so (__pthread_start(void*)+22) (BuildId: ea718846ad36e51a614ac645ba57f9bc)

          #15 pc 0001a035  /system/lib/libc.so (__start_thread+6) (BuildId: ea718846ad36e51a614ac645ba57f9bc)

Looking in the device kernel logs i see many:
[  200.812164] kgsl kgsl-3d0: |kgsl_get_unmapped_area| _get_svm_area: pid 2941 mmap_base ec63f000 addr 0 pgoff 275 len 29687808 failed error -12


The worst part is that it's getting worse every time I run the app, after crash and closing the app the adb shell dumpsys meminfo total ram line have (status critical), and the next time I run my app it will crash faster. I assume it's a memory fragmentation but I cant find what its tring to allocate that is a problem.
I considered it maybe connected to out use in AVPRO plugin but the movie can be already loaded when it crash and lowering the movies size did nothing.
I don't know what else to try! Help!

its really is urgent

**Comment by adi5785905** [comment]
When I tried to change from exo player to media player I got:
02-02 15:21:40.085  4030  4047 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_OUT_OF_MEMORY: Not enough memory left to execute command
02-02 15:21:40.085  4030  4047 E Unity   : UnityEngine.GL:GLIssuePluginEvent(IntPtr, Int32)
02-02 15:21:40.085  4030  4047 E Unity   : UnityEngine.GL:IssuePluginEvent(IntPtr, Int32) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Graphics/Graphics.bindings.cs:481)
02-02 15:21:40.085  4030  4047 E Unity   : RenderHeads.Media.AVProVideo.AndroidMediaPlayer:IssuePluginEvent(AVPPluginEvent, Int32) (at C:\VRPhysio\Repositories\GoPortal\GOPortal\Assets\AVProVideo\Scripts\Internal\AndroidMediaPlayer.cs:150)
02-02 15:21:40.085  4030  4047 E Unity   : RenderHeads.Media.AVProVideo.AndroidMediaPlayer:Render() (at C:\VRPhysio\Repositories\GoPortal\GOPortal\Assets\AVProVideo\Scripts\Internal\AndroidMediaPlayer.cs:948)
02-02 15:21:40.085  4030  4047 E Unity   : RenderHeads.Media.AVProVideo.<FinalRenderCapture>d__188:MoveNext() (at C:\VRPhysio\Repositories\GoPortal\GOPortal\Assets\AVProVideo\Scripts\Components\MediaPlayer.cs:1257)
02-02 15:21:40.085  4030  4047 E Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
02-02 15:21:40.085  4030  4047 E Unity   :
02-02 15:21:40.085  4030  4047 E Unity   : [./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp line 358]

**Comment by RenderHeadsSte** [comment]
> We have an app for the Pico G2 with an interactive video player that plays 4096x4096 stereoscopic 360° videos. The AVPro player worked out of the box but every now and then we encounter a blackscreen accompanied by a adb logcat message reading "OPENGL NATIVE PLUG-IN ERROR: GL_OUT_OF_MEMORY: Not enough memory left to execute command". Interestingly the sound still plays but the screens remain black even though at least a crosshair with an always-on-top-shader should be visible, This error can be replicated by us in a specific scenario.
> 
> 1. A video of said resolution is being played (H265)
> 2. While the video is being played we reload the current scene
> 3. Upon scene reload we start a different video of equal resolution
> 4. The video that is being played after the scene reload plays audio but screens are black
> 
> The frequency of this occurence is totally random but always tends to kinda softlock the app. Controllerbuttons are still handled and reloading the scene can be done, however, the screens always remain in a backlit black.
> Ineffective countermeasures so far were to call "mp.ClearVideo( )" before restarting the scene and before loading any video followed by half a second yield duration. We also made sure it´s no sort of fader that is causing the black screens. This problem started occuring once we switched from EasyMovieTexture to AVPro Video.
> 
> Videos: H265 4096x4096
> Method: ApplyToMaterial
> Unity: 2019.2.2f1
> AVPro Video: 1.10.1
> 
> Any suggestions what the cause of this problem is and how we could potentially solve it?

Would it be possible to send the video over to unitysupport@renderheads.com so we can take a look?  We no not have a Pico device, but can try it on an Oculus GO and Quest.

**Comment by RenderHeadsSte** [comment]
We shall be closing this bug shortly due to lack of response.

**Comment by AndrewSpalato-FGMNT** [comment]
I am getting this issue on a Pico G2 using AVProVideo and ApplyToMaterial

**Comment by RenderHeadsSte** [comment]
Please open another issue @AndrewSpalato-FGMNT including all the requested details (also what VR settings you are using).
