### ISSUE TITLE
AVPro HTTP Progressive Streaming not accurate buffering range

### ISSUE THREAD

**Issue by zbzdys** [RenderHeads/UnityPlugin-AVProVideo#26]
**Describe the bug**

Problem: Buffer range not accurate

I opened 02_Demo_imGui and switched to http://bananalab.huawei.com/mss.mp4. AVPro will try to buffer. If you seek to the buffered time point, sometimes it cant play at all. Web player like youtube is more accurate, i mean if you seek to the buffered range, it can play immediately. But with avpro, if you get some buffered range like 10secs, you cant play freely in the range.

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.15f1
 - AVPro Video version: 1.9.4
 - Operating system version: Windows 10 x64
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Open your demo scene 02_Demo_imGui
2. Play stream: http://bananalab.huawei.com/mss.mp4
3. When you find some buffered time available, try to seek between the time range and you can run into the problem above

**Logs**
If applicable, add error logs to help explain your problem.
No err.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
http://bananalab.huawei.com/mss.mp4
or you can test with some long and high bitrate mp4 videos by http progressive streaming

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by liguangyi1991** [comment]
你好我也遇到了同样的问题,请问你解决了吗

**Comment by zbzdys** [comment]
没继续跟进，很久不用了
