### ISSUE TITLE
SSL seems to ignore the OS settings

### ISSUE THREAD

**Issue by VincentMarnier** [RenderHeads/UnityPlugin-AVProVideo#262]
**Bug:**
When having a self-signed SSL certificate with the CA added to the OS trusted CAs, AVPro fails to stream video contents.
On the same device, web browser successfully read the video without error and Unity successfuly perform GET requests on the video file too. The issue is definitely from AVPro.

**Setup:**
Unity version: 2019.3.0f6
AVPro Video version: 1.9.8
Operating system version: Windows 10 1903 (v18362.628), iOS 13.3.1, Android 7.0

**To Reproduce:**

1. Install OpenSSL
2. Edit and run the script in attachment to generate a "ca.crt" file and a "server.crt" and "server.key" file
3. Add "ca.crt" to the device's trusted root CAs
4. Config a web server to use "server.crt" and "server.key" (I used nginx to do so) and run it
5. Setup a DNS server to redirect "selfsigned.avpro.com" to your web server (the bug is not reproduced if you edit your windows hosts file)
6. Put a video file on your webserver (I used this video taken from w3c: https://www.w3schools.com/html/mov_bbb.mp4)
7. Create a Unity project that tries to read the video file with AVPro (in my case it tries to read "https://selfsigned.avpro.com/mov_bbb.mp4")
8. AVPro fails to read the file

**The script to generate the self signed certificate:**
```
@echo off

:: IMPORTANT: After this script ran, add a rule to accept ca.crt as a Certificat Authority
:: WARNING: Remember to delete %CA_KEY% and %CA_CRT% if you change a single variable from this script

set SERVER_ADRESS=selfsigned.avpro.com
set CERTIFICATES_DIRECTORY=C:\Program Files (x86)\Nginx\nginx\conf\certificats
set OPENSSL_CMD=openssl

:: Files
set CA_CRT=ca.crt
set CA_KEY=ca.key
set SERVER_KEY=%CERTIFICATES_DIRECTORY%\server.key
set SERVER_CSR=server.csr
set SERVER_CONFIG=server.cnf
set SERVER_CONFIG2=server2.cnf
set SERVER_CRT=%CERTIFICATES_DIRECTORY%\server.crt
set OPENSSL_CONFIG=C:\Program Files\OpenSSL\bin\cnf\openssl.cnf

:: OpenSSL configuration
set COUNTRY=FR
set STATE=Auvergne-Rhone-Alpes
set LOCALITY=Lyon
set ORGANIZATION=None
set ORGANIZATION_UNIT=None

:: Generate the Certificate Authority (CA) if it does not exist
if not exist "%CA_CRT%" (
    "%OPENSSL_CMD%" genrsa -des3 -out "%CA_KEY%" 4096
    "%OPENSSL_CMD%" req -x509 -new -nodes -key "%CA_KEY%" -sha256 -days 1024 -out "%CA_CRT%" ^
        -subj "/C=%COUNTRY%/ST=%STATE%/L=%LOCALITY%/O=%ORGANIZATION%/OU=%ORGANIZATION_UNIT%/CN=[Self Signed] %SERVER_ADRESS%"
)

:: Generate the server's private key
"%OPENSSL_CMD%" genrsa -out "%SERVER_KEY%" 2048

:: Generate the config file
@echo. > "%SERVER_CONFIG%"
xcopy /y "%OPENSSL_CONFIG%" "%SERVER_CONFIG%"
@echo. >> "%SERVER_CONFIG%"
@echo [ san ] >> "%SERVER_CONFIG%"
@echo subjectAltName=DNS:%SERVER_ADRESS% >> "%SERVER_CONFIG%"

:: Generate the Certificate Signature Request (CSR)
"%OPENSSL_CMD%" req -new -sha256 -reqexts san -config %SERVER_CONFIG% -key "%SERVER_KEY%" -out "%SERVER_CSR%" ^
    -subj "/C=%COUNTRY%/ST=%STATE%/L=%LOCALITY%/O=%ORGANIZATION%/OU=%ORGANIZATION_UNIT%/CN=%SERVER_ADRESS%"

"%OPENSSL_CMD%" req -text -noout -in "%SERVER_CSR%"

:: Accept the CSR and generate the self signed Certificate
@echo subjectAltName=DNS:%SERVER_ADRESS% > "%SERVER_CONFIG2%"
"%OPENSSL_CMD%" x509 -req -extfile "%SERVER_CONFIG2%" -in "%SERVER_CSR%" -CA %CA_CRT% -CAkey %CA_KEY% -CAcreateserial -out "%SERVER_CRT%" -days 500 -sha256

:: Delete temporary files
del "%SERVER_CSR%"
del "%SERVER_CONFIG%"
del "%SERVER_CONFIG2%"

pause
```

**Comment by MorrisRH** [comment]
Thanks for the detailed guide to setting up a self-signed certificate, very handy.

Unfortunately I was not able to reproduce your issue on Win10, macOS or iOS (android currently untested).

I'm using Unity2018.4 with a slightly more recent AVPro Video (1.10.1) but I don't think there is anything in there that would make a difference, however we always recommend using the latest version where possible.

OS versions: Win10 1809, iOS 13.3, macOS 10.15.3

**Comment by VincentMarnier** [comment]
Hello Morris,
Thanks a lot for your very kind and clever answer.
I updated my AVPro and tried with Unity2018.4 and Unity 2019.1.
I was setting up a full git repository so you could reproduce the exact same scenario and I found an issue with my DNS server, so I configured a brand new.
Here are my results so far both Unity version and the re-configured DNS server:
- It works as expected on Windows
- It does not works on Android (it works with a Web Browser, but UnityWebRequests also fails, so it seems to be a Unity bug)

I was not able to test on iOS yet because I don't have the hardware to do so. I will be back home on Friday and will provide you with more data then.
Eventualy everything works just fine and my issue was with my weird DNS configuration and AVPro (for some reason I cannot figure).
If you happen to test with Android, let me know if you reproduce the selfsigned issue.
Thanks a lot for your time and your patience.
Be sure I will close the bug if it happens to work on iOS.

**Comment by VincentMarnier** [comment]
Hello Morris,
So, I was able to perform the iOS test and it seems to work.
So far here are my results:

|  | **Web browser** | **Unity** | **AVPro** |
|--|--|--|--|
| **Windows** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| **Android** | :heavy_check_mark: | :no_entry: | :no_entry: |
| **iOS** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

So AVPro seems alright. 
I will keep digging for Android in case I missed something.
And if I did not I will pursue with Unity's support.
Thanks a lot for your time and for our help.
I am closing that bug.
Best regards,
Vincent Marnier.

**Comment by VincentMarnier** [comment]
In case anyone once encounter the same (or a similar) issue, I opened a Unity ticket and created a [forum post](https://forum.unity.com/threads/on-android-unity-seems-to-ignore-the-certificates-trusted-by-the-system.833071/)
