### ISSUE TITLE
MediaPlayer Control.isPlaying() return true after video end on Windows

### ISSUE THREAD

**Issue by blueyeti** [RenderHeads/UnityPlugin-AVProVideo#263]
When calling MediaPlayer Control.IsPlaying() in the Update function, the behaviour is different on MacOS and on Windows (test with HAP alpha video and directshow):
- on MacOS when the video ends, Control.IsPlaying() goes to false
- on Windows when the video ends, Control.IsPlaying() returns true
AVPro Version 1.10.1, Unity 19.3.0f6

**Comment by AndrewRH** [comment]
Hmm Yes....this sounds like a sort of bug...

We can of course use something like Control.IsFinished() to check whether the video has reached the end, and then ignore the IsPlaying() status.

I believe on Windows when the video is completed it still considers that the 'playhead' is in play mode, so calling seek would seek and continue playback, but on macOS it's in a paused state.

We aim to address this in the future, but hopefully you can use a workaround for now.

**Comment by RichRH** [comment]
An old issue but DS/MF should now match the behaviour of WinRT and other platforms.
