### ISSUE TITLE
Videos cache

### ISSUE THREAD

**Issue by ShuiYueTianLang** [RenderHeads/UnityPlugin-AVProVideo#264]
**Is your feature request related to a problem? Please describe.**
If I played some videos,and I exited my app.When I open the app later,are there videos cached? I did not read relative description in PDF。

**Describe the solution you'd like**
I wish to some anwser.If supports Cahce Videos,please tell me where I should do.If not supports,
I wish to support this issue probably。

Thank you！

**Comment by AndrewRH** [comment]
This has been implemented on Android and iOS on AVPro Video 2.x

Closing this issue.
