### ISSUE TITLE
Issue with AVPro Media Player url videos in oculus quest

### ISSUE THREAD

**Issue by javiersantaella** [RenderHeads/UnityPlugin-AVProVideo#266]
Problem description:

We are using AVPro for unity (sphere360 asset with media player component) and exporting to android (oculus quest). We are having a trouble with a video from url. If we use ‘browse’ for a local video it is played in both unity GUI and oculus glasses, but if we use a video from url (mp4 or hls m3u8) the video is played in unity GUI but we have black screen in oculus glasses. It may be internet permission of the apk? We have checked it and we have wifi internet connection in oculus glasses.

Device (which devices are you having the issue with - model, OS version number):

Oculus quest android

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

http://downloads.renderheads.com/2016/BigBuckBunny_360p30_Streaming.mp4

System Information:

AVPro Video: plugin v1.10.1t scripts v1.10.1
Target Platform: Android
Unity: v2019.2.20f1 WindowsEditor
OS: Desktop - HP ProBook 640 G3 (HP) - Windows 10  (10.0.0) 64bit - Spanish
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz - 4 threads - 8071KB
GPU: Intel(R) HD Graphics 620 - Intel - Direct3D 11.0 [level 11.1] - 4035KB - 16384

**Comment by javiersantaella** [comment]
up

**Comment by RenderHeadsSte** [comment]
When I try to access that link in a browser I receive the following error.  It looks like your server is not configured correctly.

<<<
Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
