### ISSUE TITLE
impossible to get the video bitrate!

### ISSUE THREAD

**Issue by tarmata** [RenderHeads/UnityPlugin-AVProVideo#267]
**Describe the bug**

Hello! I'm AVpro user. It is impossible to get the bitrate of the video through url or video, so please contact us.

According to the given document, mediaplayer.Info.GetCurrentVideoTrackBitrate ()); The bitrate should be returned, but only 0 is still returned.

Please reply.
**Your Setup (please complete the following information):**
 - Unity version: 2019.2.4f1
 - AVPro Video version: latest
 - Operating system version: 
 - Device model: android, desktop
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.
just 0;
**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
I assume this in on Android?  Currently, we do not pass anything back for 'current bitrate'.  IT might be possible to pass something back from the API when using the ExoPlayer API path.  I will investigate this and add it to the next release if I find it returns anything usable.

**Comment by AndrewRH** [comment]
Closing this as it should now be possible in the latest version 1.10.2.  Thanks,

**Comment by DragontaleStudio** [comment]
We are getting mediaplayer.Info.GetCurrentVideoTrackBitrate () = -1 on android builds with latest release. Is there any other way to retrieve the playing bitrate?

**Comment by RenderHeadsSte** [comment]
@DragontaleStudio Are you able to share your video/stream-URL with us? (you can send it to unitysupport@renderheads.com if you wish to keep it private)
