### ISSUE TITLE
Calling IsPaused() immediately after Pause() causes program to hang

### ISSUE THREAD

**Issue by DragonLadyBlue** [RenderHeads/UnityPlugin-AVProVideo#268]
I just upgraded to V 1.10.1 and found it would hang 90% of the time when running on Oculus Go (Android).  I have traced it down to the following lines in my code, where the while loop would never exit.
            if (doPause)
            {
                CurrentlyRunningPlayer.Pause();
                // This is causing the VR to hang for some reason
                //while (!CurrentlyRunningPlayer.Control.IsPaused())
                //{
                //    // wait for it to actually pause
                //}
            }
            else
            {
                CurrentlyRunningPlayer.Play();
                //while (!CurrentlyRunningPlayer.Control.IsPlaying())
                //{
                //    // wait for it to actually restart
                //}
            }
Commenting out the while loop lines it worked fine 100% of the time.  This code has worked fine for over a year with the previous version of AVPro

 - Unity version: 2018.3.8f1
 - AVPro Video version: 1.10.1
 - Operating system version: 13
 - Device model: Oculus Go

**Comment by RenderHeadsSte** [comment]
You have a while loop blocking the main thread?  If so, I would suggest if very bad practice indeed to block the main thread with while loops.

The AVPro player object requires its update loop to be called in order for the plugin guts to perform its operation.  Blocking the main threads execution will stop this, and that will be why you are seeing nothing 'under the hood' change.
