### ISSUE TITLE
Is the open source cardboard sdk supported?

### ISSUE THREAD

**Issue by jnroesch** [RenderHeads/UnityPlugin-AVProVideo#269]
Hey guys, 

with Unity dropping the internal cardboard support in Unity 2019 and with the open source project not having a current sdk for unity, I am a bit lost with the current state of things. Are you planning on supporting the new open source cardboard sdk in unity? Does this change even have an effect on you or is this the player completely separated from the VR APIs?

Would love to hear some reassuring words that cardboard is not going to be a nightmare in the future.

**Comment by MorrisRH** [comment]
We're very unlikely to support the cardboard sdk directly in the plugin. Our recommendation would be to continue with a Unity version that does support cardboard.
Sorry, not very reassuring.
