### ISSUE TITLE
Minor bug in HLSStream class

### ISSUE THREAD

**Issue by Chris-Simon** [RenderHeads/UnityPlugin-AVProVideo#27]
**Description**
Hello,

we are currently using the AVPro Video plugin for a Unity project. In this project we are using .m3u8 playlists to stream video content. While fetching all streams from the playlist, I noticed that there is a minor bug when reading the width and especially the height from the playlist.

In our case we have multiple video streams with different resolutions, for example 3840 x 2160. When reading this information from the playlist, the resulting Stream object contains the width and height properties, whereat the width property is correct (3840) but the height property is not. For this example it has the value 216 instead of 2160. Since this is the case for each video stream we have in the playlist, we currently use a workaround by multiplying the value by 10 to get the correct value for the height.

The problem occurs in the HLSStream.cs file in line 138 (latest version from the Asset Store). In this line the length of the actual resolution string is calculated. For example when having the resolution of 3840x2160 in the playlist, this line should calculate a length of 9 because there are 9 characters. In the current version the result of this calculation is only 8 and furthermore the last character is cut when applying these information to the width and the height. The result is, that we get the correct value for the width but an incorrect one for the height. It is reproducible with other resolutions we have in the playlist, for example 1920x1080, 1280x720, etc. 

**Setup**
- Unity version: 2018.3.5f1
- AVPro Video version: 1.9.12
- Operating System: mac OS 10.14.3 (probably happens on all supported devices)
- Video Specs: happens on multiple resolutions (see above), irrespective of frame rate, codec, etc.

**How to reproduce**
- Try to open any .m3u8 playlist file by calling `HLSStream hlsStream = new HLSStream("uri");`
- Iterate through GetAllStreams(), for example: `foreach (Stream stream in hlsStream.GetAllStreams()) { }`
- In this loop check the width and height of each stream object

In our case the playlist file looks like this:

> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-STREAM-INF:BANDWIDTH=5720000,RESOLUTION=3840x2160
> chunklist_w910779299_b5720000_slDE.m3u8
> #EXT-X-STREAM-INF:BANDWIDTH=3320000,RESOLUTION=1920x1080
> chunklist_w910779299_b3320000_slDE.m3u8

**Comment by AndrewRH** [comment]
Thanks for reporting this.  I've attached the fixed file here.  Closing this ticket now :)

[HLSStream.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/2926510/HLSStream.zip)
