### ISSUE TITLE
notchlc support request

### ISSUE THREAD

**Issue by cgfrosty** [RenderHeads/UnityPlugin-AVProVideo#270]
Hi,
We are using avpro for a long time and very happy about this.
It will be very good to add support of new and best codec notchlc https://notchlc.notch.one/ 
They have sdk and all people will be happy to see in avpro. See discussion https://www.facebook.com/groups/notchusergroup/permalink/1040835726292541/

**Comment by AndrewRH** [comment]
Great suggestion...  we'd love to support this but time is always the issue.  We can't promise anything but when we get a moment we'll take a look to see how feasible this would be.

**Comment by cgfrosty** [comment]
Thank you, Andrew! If you will need early testers we will be happy to help you.
If you will have a lack of time, we are ready to discuss our involvement in this development. We have a few c++ and many c# developers. Our artists will be happy to see this codec in AVPRO, because AVPRO is our main playing system right now. :)

**Comment by AndrewRH** [comment]
Update on this...we are currently evaluating NotchLC SDK

**Comment by haaziqldn** [comment]
Hey @AndrewRH - is the notchLC integration still on the roadmap? Would be great to see it come through as we're doing a lot of disguise/Unity integration and using a superb quality codec across both would be awesome!!

**Comment by AndrewRH** [comment]
@haaziqldn  yes it's still on the roadmap.   We have a bunch of things to get done first though before we can focus on NotchLC.  Our initial tests though look positive!

Thanks,

**Comment by AndrewRH** [comment]
NotchLC support is now in AVPro Video 2.0 RC1 which is available now.
