### ISSUE TITLE
Audio Loop doesn't work when using Unity Audio

### ISSUE THREAD

**Issue by MarioVoithofer** [RenderHeads/UnityPlugin-AVProVideo#271]
I use AVPro Video (1.10.1) for Unity (2018.4.5f1 LTS).
I am developing an application for the Hololens (2).
Here a bug occurs when I try to use Audio Spatialisation. I use the component AudioOutput (+ AudioSource) as described in the documentation.
If I want to loop an audio file which is specified relative to the StreamingAssets folder, the sound will be played only once. In the preview of the MediaPlayer components, however, it is shown that the file is played multiple times. 
More precisely, this bug occurs as soon as I activate UseUnityAudio (also already in the editor).
If the file should not be looped, everything works as desired (Windows (Editor) and Windows UWP (HoloLens 2 build)).
Is a bug-fix / workaround known here?

Thanks for your help!

**Comment by AndrewRH** [comment]
I believe this has now been fixed - if not in version 1.x then certainly in the upcoming 2.x

Thanks,
