### ISSUE TITLE
Can I play a video from an AssetBundle?

### ISSUE THREAD

**Issue by Jayatubi** [RenderHeads/UnityPlugin-AVProVideo#272]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to store a video file in the a binary format, such as rename foo.mp4 to foo.bytes, and build it into a Unity AssetBundle. Then after I build my application package it could load the video from that AssetBundle. This is supposed to work on all platforms.

**Describe alternatives you've considered**
If it is not possible to make AVPro to load a video directly from an AssetBundle then could I play a video from a memory stream? If so I could extract the data from the AssetBundle and load it into a stream for AVPro.

**Additional context**
No.

**Comment by AndrewRH** [comment]
Playing from an assetbundle is not supported.

You could however read your file out of the assetbundle and then save it to disk for playback.  But if the file is very large this could have tricky memory issues.   We don't support playing video from a memory stream.

Another approach could be to use a file offset to hide your file.  We currently only support this on Android at the moment, but if that helps you can can read our PDF documentation where talk about how to use this feature.

I hope that answers your question. 

Thanks,

**Comment by mrcarriere** [comment]
Is there any intention of ever bringing support to this feature? We were looking for an improvement on the current Unity Video Player, and this would have been a perfect solution for our project (a FMV project with 20GB+ of video) if it had asset bundle/addressable support.

**Comment by evan-spiegel** [comment]
Hi there, is playing videos from an asset bundle still not supported on Android?

**Comment by fingerx** [comment]
@AndrewRH  want to know is support?

**Comment by AndrewRH** [comment]
this is still not supported and is still a 'feature request'  we currently have no roadmap for this request

**Comment by guiglass** [comment]
Hi is this implemented yet?

**Comment by Chris-RH** [comment]
As it stands, we have no plans to implement this.  We are a very small team so have to carefully decide which features to focus on developing.

**Comment by oleg-mindojo** [comment]
Just wanted to say that I'm sad about the fact that we can't feed bytes from the unpacked file right into the player.
Don't get me wrong, I really love the product and appreciate your work.
