### ISSUE TITLE
no EventType.FinishedPlaying after HLS stream is finished playing

### ISSUE THREAD

**Issue by kennethc-olivex** [RenderHeads/UnityPlugin-AVProVideo#273]
I am trying to play https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
I can receive events like FirstFrameReady, StartedSeeking, but cannot receive FinishedPlaying after the stream ended.

 - Unity version: 2019.3.0.f6
 - AVPro Video version: script v1.10.1 plugin v1.10.1
 - Operating system version: iOS 12.4.1
 - Device model: iPhone X
 - Video specs (resolution, frame-rate, codec, file size): 

**Logs**
Initialising AVPro Video (script v1.10.1 plugin v1.10.1) on Apple A11 GPU/Metal (MT True) on IPhonePlayer iOS 12.4.1

OnMediaPlayerEvent : Closing None
OnMediaPlayerEvent : MetaDataReady None
OnMediaPlayerEvent : ResolutionChanged None
OnMediaPlayerEvent : FirstFrameReady None
OnMediaPlayerEvent : StartedSeeking None
OnMediaPlayerEvent : Started None
OnMediaPlayerEvent : FinishedSeeking None
OnMediaPlayerEvent : ResolutionChanged None

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
This has been fixed and will be available in the next release.
