### ISSUE TITLE
Decode error when seeking through a WebGL video stored in IndexedDB

### ISSUE THREAD

**Issue by spectral-labs-christian** [RenderHeads/UnityPlugin-AVProVideo#275]
**Describe the bug**
When playing a video from a blob url, video player will get errorcode 3 (decode error) when calling the Seek() or SeekFast() functions.

**Your Setup (please complete the following information):**
 - Unity version: Unity 2018.3.7f1
 - AVPro Video version: 1.10.1t
 - Operating system version: Windows 10
 - Device model: PC
 - Video specs (resolution, frame-rate, codec, file size): 1280 x 720, 30 fps, MP4, 14.9 MB

**To Reproduce**
1. In WebGL, open a video file with OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, url, true). The url should be a blob url.
2. Try to seek through the video.

**Screenshots**
![image](https://user-images.githubusercontent.com/61336572/75082996-3c995f00-54cb-11ea-8012-032627f7bd66.png)

**Comment by spectral-labs-christian** [comment]
Tried to get around this with workarounds:

- Created a button to seek forward ahead 5 seconds (Seek function). Will seek the first time but the second seek will error out.

- Created a button to seek forward ahead 1 second (Seek function). Will seek multiple times (20+) but will eventually error out. 

- Created a button to seek forward (Changed playback rate to 100x for 1 second). This works but cannot be used to seek backward. WebGL does not support negative playback rate.

**Comment by AndrewRH** [comment]
Hmm strange...so if you play it from another location (non-indexdb)?

Have you tried in different browsers?

We are just using the standard web video API, so if it's complaining while calling those methods I'm not sure what we can do about it...

**Comment by spectral-labs-christian** [comment]
Tested on different browsers (Chrome, Firefox, Old Microsoft Edge, New Microsoft Edge)

When playing from a normal url, had no issues with seeking on all browsers. 
Seeking when playing from IndexDB worked in Firefox and an old version of Microsoft Edge. 

So it seems that this is only an issue in chromium-based browsers.
