### ISSUE TITLE
Cannot connect to straming URL in Oculus Quest (import Oculus Integration plugin).

### ISSUE THREAD

**Issue by ricktsukida** [RenderHeads/UnityPlugin-AVProVideo#278]
**Describe the bug**
I want to play streaming video in Oculus Quest. but cannot play the streaming video in Quest.
I use Oculus Integration plugin(https://assetstore.unity.com/packages/tools/integration/oculus-integration-82022). it can be playing the video removed Integration Plugin.
but, I want to use Oculus Integration Plugin, please tell me how to fix it. 

**Your Setup (please complete the following information):**
 - Unity version: 
Unity 2019.2.20
 - AVPro Video version: 
1.10.1
 - Operating system version: 
Windows10
 - Device model: 
Oculus Quest(latest version)
 - Video specs (resolution, frame-rate, codec, file size): 
FullHD, h.264, hls streaming.

-Use other plugins
Oculus Integration(latest version)

**Screenshots**
![Snapshot 2020-02-24 20 59 20](https://user-images.githubusercontent.com/9640007/75152268-fdc60c00-574b-11ea-99bb-cae458c1e97f.png)

**Comment by gtk2k** [comment]
AndroidManifest.xmlにパーミッションを設定する必要があると思います。
```
<application android:usesCleartextTraffic="true"
        ...
</application>
```

**Comment by gtk2k** [comment]
I think you need to set permissions in AndroidManifest.xml.
```
<application android: usesCleartextTraffic = "true"
         ...
</ application>
```

**Comment by ricktsukida** [comment]
I wrote it, but cannot connect streaming path. 
By the way, I create simple UnityWebRequest sample. this program can connect internet.
and, I checked app permission, maybe it is no problem.

![MINGW64__d_linux_vagrant_centos7 2020-02-26 12 54](https://user-images.githubusercontent.com/9640007/75310368-27d81500-5897-11ea-9b6b-c44252a48a15.png)

**Comment by RenderHeadsSte** [comment]
It is to do with android API versions that are used as part of newer versions of Unity.  Here is the important part of the logcat logging that shows the problem:

     Caused by: java.io.IOException: Cleartext HTTP traffic to qthttp.apple.com.edgesuite.net not permitted

Information on potential fixes can be found at these links:

https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
https://forum.unity.com/threads/android-9-cleartext-http-traffic-to-my_ip-not-permitted.594298/  

Or...just use a stream served off a secure https server, for example: https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8
