### ISSUE TITLE
Inquiry about strange load error

### ISSUE THREAD

**Issue by DongJuLim** [RenderHeads/UnityPlugin-AVProVideo#279]
**Describe the bug**

When I developed with AVpro, the video came out correctly, but suddenly I got a load error, which didn't work since that same error.
Some of our companies are experienced

The error point is after the texture change (up to the first fameRender)

By the way, even if it runs on the same project and works on another PC, it's strange that the project doesn't work only on my PC.

Do you know why this happens?

**Your Setup (please complete the following information):**
 - Unity version: 2018.1.9f2
 - AVPro Video version:  likely 1.8.8 
 - Operating system version: Windows 10
 - Device model: windows and oculus quest (working in oculus) 
 - Video specs (resolution, frame-rate, codec, file size): 
resulutrion : 2304 * 2304
frame-rate 60.24/(59.94)  - frame/per second
codec : H264

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

* Loding Failed Error : [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
I believe the following issue was linked, and solved you issue.

https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/209
