### ISSUE TITLE
YouTube Live Playback

### ISSUE THREAD

**Issue by gtk2k** [RenderHeads/UnityPlugin-AVProVideo#280]
I can play Youtube Live HLS.
but I can't play Youtube Live MPEG-DASH.

Unity 2019.3.1f1
Win10 2004(19041)
VP9 video extensions installed.

**Comment by RenderHeadsSte** [comment]
We do not officially support streaming from YouTube due to licensing.

How are you getting a DASH URL from the service?

**Comment by RenderHeadsSte** [comment]
We will be closing this issue soon due to inactivity.
