### ISSUE TITLE
Peristent (typo)

### ISSUE THREAD

**Issue by AldeRoberge** [RenderHeads/UnityPlugin-AVProVideo#281]
Problem description:

There's a Typo in 'Peristent storage'

Device (which devices are you having the issue with - model, OS version number):

No devices

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

No video

System Information:

AVPro Video: plugin v1.10.1t scripts v1.10.1
Target Platform: Android
Unity: v2019.2.11f1 WindowsEditor
OS: Desktop - Z97X-UD3H (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz - 8 threads - 16220KB
GPU: NVIDIA GeForce GTX 1060 3GB - NVIDIA - Direct3D 11.0 [level 11.1] - 2988KB - 16384

**Comment by AndrewRH** [comment]
thanks for reporting this, we've fixed it and it will be resolved in the next version
