### ISSUE TITLE
Video loops only twice

### ISSUE THREAD

**Issue by JanOwiesniak** [RenderHeads/UnityPlugin-AVProVideo#282]
**Describe the bug**

Set playback loop flag and expected the video to loop infinite but it stops after the second run.

**Setup**

 - Unity version: 2019.3.f1f
 - AVPro Video (script v1.10.1 plugin v1.10.1) on AMD Radeon Pro 460/Metal (MT True) on OSXEditor Mac OS X 10.14.6

**Reproduce**

1. Add MediaPlayer to Scene
2. Set Source Path to "Absolute Path Or URL"
3. Add Video URL: https://player.vimeo.com/external/390689317.m3u8?s=24d6ec4be11e9e581b9118992df2cef098ed8a3c&oauth2_token_id=1286106498

@AndrewRH is there another way to loop the video e.g. by removing the loop flag an reacting to media player events?

**Comment by MorrisRH** [comment]
Looping is working fine in editor here using the video URL you provided. Are you able to provide any more information?

My setup:
Unity 2019.3.3f1
AVPro Video (script v1.10.1 plugin v1.10.1) on AMD Radeon RX 580/Metal (MT True) on OSXEditor Mac OS X 10.15.3

**Comment by AndrewRH** [comment]
This issue will be closed soon as we haven't heard more details and can't replicate the issue.
