### ISSUE TITLE
Video playback stops after certain number of videos. 

### ISSUE THREAD

**Issue by PrateekG21** [RenderHeads/UnityPlugin-AVProVideo#283]
The videos are being played sequentially, one after another, on the different AVPro objects. Behavior displayed: 

MediaPlayer API --> Plays 5 videos, then stops playing Video. Audio plays as expected.
ExoPlayer API --> Plays 6 videos, then stops playing both Audio and Video.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.14f1 
 - AVPro Video version:  
 - Operating system version: N/A
 - Device model: Vive Focus Plus
 - Video specs (resolution, frame-rate, codec, file size):  1920 x 1080, 60 fps, size variable 

**To Reproduce**
1. Create multiple AVPro objects.
2. Play videos sequentially. The second video starts after the first is over.
3. The issue appears once 5 or 6 videos have played.

**Comment by MorrisRH** [comment]
Standalone VR headsets have quite limited resources. It sounds like your system is running out of resources due to having so many players active. You would be better served by having just two players and swapping between them as you move through your playlist.

**Comment by PrateekG21** [comment]
That makes sense. A standalone headset does have limited resources, however keeping that in mind, I make sure that only one player object is active at a time. Essentially, only the player that is currently playing the video remains active. Would that still cause issues? Is there a way to manually unload a video from memory once it's done playing?

**Comment by RenderHeadsSte** [comment]
Closing a video (on Android) should free off all the main resources.  So yea, it should be fine.

Do let us know if you hit an issue though.
