### ISSUE TITLE
Skybox panorama video flipped vertically

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#284]
Problem description:

When using the MediaPlayer with Apply To Material on a Skybox material (Skybox/Panoramic) the video is flipped vertically (upside down).
The Skybox material has Mapping: Latitude Longitude Layout and Image Type: 360 Degrees, 3D Layout: None
MediaPlayer Video Mapping is set to 'Equi Rectangular 360.

I've tried setting the y-scale of ApplyToMaterial to -1 but that doesn't change anything. Tested with several videos. The preview in the Media Player Inspector looks good, not upside down, but the Skybox is upside down. 

Device (which devices are you having the issue with - model, OS version number):
Unity 2018.2.4f1, AVPro 1.10.1t, tested with build for Windows x86_x64 and build for Android

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):
Video: MP4, 4096x2048 H264 30fps
From metadata: Orientation: Top left, Yaw: 0, Pitch: 0, Roll: 0 

System Information:

AVPro Video: plugin v1.10.1t scripts v1.10.1
Target Platform: Android
Unity: v2018.2.4f1 WindowsEditor
OS: Desktop - X299 AORUS Gaming 3 Pro (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - Dutch
CPU: Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz - 28 threads - 65234KB
GPU: NVIDIA GeForce GTX 1080 - NVIDIA - Direct3D 11.0 [level 11.1] - 8079KB - 16384

It's the same issue as described here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/42 but since that issue was closed I've created a new one here.

**Comment by RuudvanReenen** [comment]
Looking at the Skybox/Panoramic shader I noticed a [NoScaleOffset] on the _MainTex, so that would explain why setting a scale in the ApplyToMaterial doesn't do anything. So the texture will have to be flipped by the MediaPlayer itself or custom Skybox/Panorama shaders would have to be created for monoscopic and stereoscopic (top/bottom and left/right) skyboxes. Can a fix for this be implemented soon or is there a workaround?

**Comment by AndrewRH** [comment]
Hi,

Yes I suspect the best way to go would be to clone that shader and make a customised version of it.  Doing the flip to the texture would be extra overhead that you would want to avoid in a VR app.  Perhaps in the future we can include a version of this shader for people to use.   For now perhaps you could make the modifications yourself and test it?

**Comment by AndrewRH** [comment]
Alternatively , we do include a demo scene that shows mapping video to a sphere - perhaps that'd be useful?   That shader could also probably be modified to work at infinite far-plane distance like the skybox shader does...

**Comment by RuudvanReenen** [comment]
Thanks for your quick reply! Currently I'm already using the workaround using a sphere instead which works great, very helpful demo scenes. I have no experience with editing shaders, so I have no idea how to make that work. Would love it if you could include shaders so these panoramic videos can be made to work with skyboxes as well.

**Comment by AndrewRH** [comment]
Oh great that you resolved it yourself :)  well it's a good point you raise...i'll keep this ticket open until we have a solution like this... thanks,

**Comment by AndrewRH** [comment]
I'm closing this as in the next version (1.10.2) we are introducing some new skybox shaders and demo scene for this feature.  Thanks,
