### ISSUE TITLE
Oculus Go PersistentDataFolder

### ISSUE THREAD

**Issue by MrJackLackMac** [RenderHeads/UnityPlugin-AVProVideo#285]
Hi,
I try to deploy the 360 Sphere Demo Scene on my Oculus Go.
But no video is played after I started the app. 
I tried every variation of source path option in the MediaPlayer and I could play it every time in unity without errors. (Auto Open and AutoPlay are true)
But after every deploy no video is played inside the Oculus go, only black screen of the Sphere. 
Via Debugoption inside the app I know the

-Application.persistentDataPath   
 (/Storage/emulated/0/Android/data/com.CompanyName.ProductName/files)  
-m_VideoLocation   (RelativetoPersistentDataFolder)
-m_VideoPath (SkyRetreatA220.mp4)

and
I manually dragged the video (SkyRetreatA220.mp4) in the location  (/Storage/emulated/0/Android/data/com.CompanyName.ProductName/files)  and just for fun in every subfolder of the app inside the go, too. 
Still no progress, only blackness.
I used the same Build options from my other go app to make sure they are right. Pretty Default. 

Oculus Gallery can play the vid with no problems
The file is 1 Video, 4096x2048, H.264 mp4

AVPro Video: plugin v1.10.1t scripts v1.10.1  (trial)
Target Platform: Android
Unity: v2019.2.8f1 WindowsEditor
OS: Desktop - Blade (Razer) - Windows 10  (10.0.0) 64bit - German
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 12 threads - 16284KB
GPU: NVIDIA GeForce GTX 1070 with Max-Q Design - NVIDIA - Direct3D 11.0 [level 11.1] - 8081KB - 16384

**Comment by AndrewRH** [comment]
Hmm, did you try enabling the option in Player Settings to allow Write Access to External?   I think that may be required...

Does that help?

**Comment by RenderHeadsSte** [comment]
Anything to report @MrJackLackMac ?

**Comment by LeZginT** [comment]
> 
> 
> Anything to report @MrJackLackMac ?

Unfortunately no positiv update. Changing the rights to "External" in the PLayer Settings was not the solution for me.

**Comment by RenderHeadsSte** [comment]
This is almost always a problem with the path to the storage location.  Try setting the 'Install location' to 'Force Internal'.  Run the app, close it, copy files to: /Storage/emulated/0/Android/data/com.CompanyName.ProductName/files , and run again.

**Comment by RenderHeadsSte** [comment]
Anything to report @MrJackLackMac @LeZginT  ?

**Comment by RenderHeadsSte** [comment]
We will be closing this issue shortly due to inactivity.

**Comment by LeZginT** [comment]
Sorry for the very late response on my site.
Unfortunately no positiv feedback to report after trying the presented solutions.

**Comment by RenderHeadsSte** [comment]
Maybe this thread will help @LeZginT :

https://forums.oculusvr.com/developer/discussion/66354/oculus-go-internal-storage-path

**Comment by RenderHeadsSte** [comment]
Did that help @LeZginT ?

**Comment by gino8080** [comment]
I have same problem with oculus go and a video from the streaming assets

the default demo scene does not work on oculus go
In unity editor or oculus quest works good

tried install location Prefer External AND write permission External
but still no video playing

**Comment by RenderHeadsSte** [comment]
I only have a Quest to hand (at home), but will endeavour to get a Go (from our offices) to see if I can reproduce the issue.  Please bear with us!

**Comment by AndrewRH** [comment]
> I have same problem with oculus go and a video from the streaming assets
> 
> the default demo scene does not work on oculus go
> In unity editor or oculus quest works good
> 
> tried install location Prefer External AND write permission External
> but still no video playing

Could you possibly post the adb log cat?  that shoudl have an error message which will help us determine the reason for it not working.

**Comment by RenderHeadsSte** [comment]
I have tested a few demo scenes on a GO now.  I placed the video in the location:

/storage/emulated/0/Android/data/com.renderheads.avpro2_test1/files/SampleSphere.mp4

...and playback has been as expected.

Can you ensure you are on the latest version of AVPro Video (1.11.0)?  As Andrew says, can you send over the logcat to unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
We shall be closing this issue soon due to inactivity.
