### ISSUE TITLE
Videos don't load/play when attempting to play multiple videos on a Radeon R5 graphics card

### ISSUE THREAD

**Issue by StephenTriviumDev** [RenderHeads/UnityPlugin-AVProVideo#287]
**Describe the bug**
We're trying to play 9 videos at the same time on a 4K screen. However once we load 2 or 3 videos, we start getting this error:

> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

The program (and the videos) work on other computers - specifically my dev computer which has a Nvidia GTX 1050, and a laptop we tried it on with an Intel UHD 620 integrated chip. The strange thing is the program doesn't load the videos if we use the Intel UHD 630 that is in the computer that has the Radeon R5 430, but if we take out the Radeon R5, the UHD 630 does work (it's a bit choppy but overall works, and all the videos do actually load and play). It also runs well on a Radeon RX 550.

I'm relatively sure the issue is the R5, but it seems weird that it would have so many issues, even when it's just 1 regular video the video seems choppy. I have a "default/placeholder" video that we've used in numerous programs and I know it plays smoothly, but on the R5 computers it seems choppy.

Turning off "Hardware Decoding" under "Media Foundation Options" can help, especially with only 1 video playing, but with the 9 videos the CPU starts backing up causing lag in the video playback and within the program. We've also tried using DirectShow instead but that didn't help either.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.12
 - AVPro Video version: 1.10.1
 - Operating system version: Windows 10 Pro
 - Device model: Radeon R5 430
 - Video specs (resolution, frame-rate, codec, file size): The videos range in resolution/frame-rate, and size, but all are using H264 codec. Generally the resolutions are 1920x1080 with 5,000-10,000 kbps data rates and range in file size from 15mb to 70mb.

**Comment by AndrewRH** [comment]
Hi,

GPU's only have limited resources for hardware video decoding.  Radeon R5 430 is a pretty old and weak card compared to Geforce 1050, so it will not be able to decode as many videos simultaneously.  Some GPU drivers will fall back to a software decoding implementation automatically, while others will not.
I would recommend you try to not loads so many videos at once if you want to support a broad range of hardware devices.  Either load them on the fly as needed, or combine several videos together into an ubervideo, which you can scrub through to get to the appropriate video.

I hope that helps?

**Comment by AndrewRH** [comment]
Closing this issue as I believe the reason for the issue has been explained and we have not heard back.  Thanks,
