### ISSUE TITLE
Stalled streaming never resume playing unless re-open the stream manually

### ISSUE THREAD

**Issue by tufeixp** [RenderHeads/UnityPlugin-AVProVideo#290]
This happens after everytime the broadcaster switch views, single to twin view, and back force, on Douyin live-broadcasting channels. No Unstalled event popping, either on DirectShow and Mediafoundation mode.

**Comment by MorrisRH** [comment]
Are you able to share the URL you're having difficulties with?

**Comment by tufeixp** [comment]
http://pull-flv-f6.douyincdn.com/stage/stream-106307439898656869.flv
http://pull-hls-f5.douyincdn.com/stage/stream-106307439898656869/index.m3u8

**Comment by RenderHeadsSte** [comment]
@tufeixp The link to the m3u8 manifest appears to be broken

**Comment by tufeixp** [comment]
Those live streams are only valid for several hours. I sent these two videos after I saw you online two minutes ago, you have to take the chance. 
Another way is to install the Tick Tok on you phone, and parse the stream url using this tool:
https://github.com/wbt5/real-url

**Comment by RenderHeadsSte** [comment]
We need streams to be available for a lot longer than several hours in order to reproduce (ideally weeks).  Can you provide that?

**Comment by tufeixp** [comment]
No I can't. Those video chat rooms are out of my control. I suggest you can make the second way out.

**Comment by AndrewRH** [comment]
Hi @tufeixp coudl you try the latest version of AVPro Video to see if it resolves this issue?

Thanks,
