### ISSUE TITLE
HLS + AES-128 video playback on iOS

### ISSUE THREAD

**Issue by aikelb** [RenderHeads/UnityPlugin-AVProVideo#293]
I'm trying to do is to playback a m3u8 file stored in StreamingAssets encrypted using Bento4 with no luck. I get the "failed to load value for key ''readable"" error in every try.
It worked using an online hls streaming though (http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8).

I couldn't find any examples online about making it work offline, so I'm not sure if I'm doing anything wrong, or if it's possible at all. Is there any reference I could check out? Or any ideas to make it work?

Thanks in advance

**Comment by MorrisRH** [comment]
I'm afraid playback of HLS streams using file:// style URLs is not supported.
