### ISSUE TITLE
AVProVideo for Windows (and UWP), can't even load the file on the Demo Scene

### ISSUE THREAD

**Issue by predictcare** [RenderHeads/UnityPlugin-AVProVideo#294]
Hi, i have a problem since 4/5 days. Before that all worked Great.

My Stable project using AVProVideo for Windows (and UWP) suddenly stopped working. Nothing was changed on my side, i think (you know it's always someone else's fault... ;-) ).

To be sure, reinstalled windows (using parallels, but it always worked), created a New Unity 2019.2.15 project and tried the demo/scene number 3:
03_Demo_VideoControls

No other plugins, only Window build. Super simple.

if you need i can zip the whole simple package and attach here:

I have everytime the same single error :

—

[AVProVideo] Initialising AVPro Video (script v1.10.1 plugin v1.10.1) on Parallels Display Adapter (WDDM)/Direct3D 11.0 [level 10.1] (MT True) on WindowsEditor Windows 10 (10.0.0) 64bit
UnityEngine.Debug:Log(Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at Assets/AVProVideo/Scripts/Internal/Interfaces.cs:611)
RenderHeads.Media.AVProVideo.MediaPlayer:Initialise() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:481)
RenderHeads.Media.AVProVideo.MediaPlayer:Start() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:513)

[AVProVideo] Opening C:/Users/victor/Desktop/HoloComponents/Assets/StreamingAssets\AVProVideoSamples/BigBuckBunny_720p30.mp4 (offset 0) with API MediaFoundation
UnityEngine.Debug:Log(Object, Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at Assets/AVProVideo/Scripts/Internal/Interfaces.cs:615)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:893)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile(FileLocation, String, Boolean) (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:544)
RenderHeads.Media.AVProVideo.Demos.VCR:OnOpenVideoFile() (at Assets/AVProVideo/Demos/Scripts/VCR.cs:101)
RenderHeads.Media.AVProVideo.Demos.VCR:Start() (at Assets/AVProVideo/Demos/Scripts/VCR.cs:277)

[AVProVideo] Failed to open C:/Users/victor/Desktop/HoloComponents/Assets/StreamingAssets\AVProVideoSamples/BigBuckBunny_720p30.mp4
UnityEngine.Debug:LogError(Object, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:908)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile(FileLocation, String, Boolean) (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:544)
RenderHeads.Media.AVProVideo.Demos.VCR:OnOpenVideoFile() (at Assets/AVProVideo/Demos/Scripts/VCR.cs:101)
RenderHeads.Media.AVProVideo.Demos.VCR:Start() (at Assets/AVProVideo/Demos/Scripts/VCR.cs:277)
—

I’m not a super expert, but could it be a problem on your side ? Can you see the “BACKSLASH” before “BickBuckBunny” String ??? Could it be the problem ?

Opening C:/Users/victor/Desktop/HoloComponents/Assets/StreamingAssets\AVProVideoSamples/BigBuckBunny_720p30.mp4 (offset 0) with API MediaFoundation

But i cant’ figure out this thing, i didn’t upgrade my AVPROVIDEO...

Thanks in advance.

**Comment by predictcare** [comment]
Ended up zipping the whole project : 
[https://www.dropbox.com/s/ktotsvcx596z7wq/HoloComponents.zip?dl=0](url)

Thanks, again

**Comment by RenderHeadsSte** [comment]
Please do not post project to this issue board.  I have deleted the post with the link.

**Comment by predictcare** [comment]
Eventually seemed only a problem of my configuration. Still don't know what happened, but the behaviour doesn't happen in another PC and in another Windows Via Parallels. 
So, my fault this time seems :-)

Let's close it.
