### ISSUE TITLE
ios Video Memory Management

### ISSUE THREAD

**Issue by ansyal2006** [RenderHeads/UnityPlugin-AVProVideo#298]
Hello I wanted to know if your plugin will be able to play 4-5 4k quality 360 videos at a time in my iphone8 which has a RAM of 2GB. Right now my iPhone app crashes whenever I try to play even two 4k 360-videos simultaneously in my scene.

**Comment by AndrewRH** [comment]
I feel like this is an issue that we can close...  Playing 4-5 4K videos at once is really beyond the capabilities of such devices....
I'm sure iPhone (you don't mention which model you're running on) can only decode a single 4K video.  These devices only have limited capabilities as their hardware decoders are typically designed to only decode up to a single 4K video.  I hope that answers your question @ansyal2006 ?

@MorrisRH i suspect I know the answer, but is there any way to prevent a hard crash?

**Comment by MorrisRH** [comment]
It's not a crash. The OS will be evicting it due to memory constraints.
