### ISSUE TITLE
(iOS) the video start 2 sec after audio 

### ISSUE THREAD

**Issue by RaidelRoss** [RenderHeads/UnityPlugin-AVProVideo#3]
Hello
I am using the AVPro test version (1.9.8)
I am using AVPro to play a video processed by FFmpeg 
the video is obtained from the device gallery and then processed by FFmpeg
The code used for video processing is:
-i imputFile -preset ultrafast -vf scale='min(540,iw)':'min(348,ih)' outputFile.mp4
any idea why the first 2 seconds do not show in iOS?
it happened on an iPhone 6

Note: in android this does not happen

can you help us

**Comment by MorrisRH** [comment]
Hello
I performed a quick test using the ffmpeg settings you mentioned and could not reproduce the issue.
A few questions:
- Are you playing the video locally or over http?
- What version of Unity are you using?
- What version of iOS is running on the iPhone?
A copy of the video you're trying to play would also be very useful.

**Comment by RaidelRoss** [comment]
Apparently, AVPro is not the problem, it seems to be a problem when converting the video using FFmpeg in iOS, we are trying to find the problem
Thank you!
