### ISSUE TITLE
AVPro video error

### ISSUE THREAD

**Issue by ChrisRue12** [RenderHeads/UnityPlugin-AVProVideo#30]
Dear renderheads,

Unfortunately, we have a strange problem in one of our apps using AVPro for video playback.

We have an idleMode in our app, where 5 different videos are constantly and randomly shown, but sometimes (3-4 hours after starting the app), we have a strange error and no video is played anymore. 
Attached you can find the snippet from our log where the error occurs. Unfortunately we didn’t log the error code so far, which we implemented now. But since there is only "loading fail" and "decode fail", maybe you already have an idea what might be the problem? As soon as there is a user input (see at the end of the log), normally one of the main videos should be played – but we get an error instantly. The only solution is to restart the app. Until the error occured, the videos were played without any problems for 65 times (see „video count“). Sometimes the app runs the whole day without any problems (around 600 plays). 
[LogErrors.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/2966228/LogErrors.txt)

Our Setup:
 - Unity version: 2018.3.5f1
 - AVPro Video version: 1.9.12
 - Operating system version: Windows 10
 - Video specs (resolution, frame-rate, codec, file size):  2160x2160px, h264 - MPEG-4AVC (part10) (avc1), 25fps, ~20-70mb

Do you have any idea, what we can do/test?

Best regards,
Chris

**Comment by AndrewRH** [comment]
Hmm, are you creating+destroying MediaPlayer instances many times?  For simplicity I'd recommend always trying to reuse existing MediaPlayers, and have as few as possible.  Video playback is quite a complex operation as it uses many system resources (OS code, GPU drivers, video codecs, audio drivers etc), so if any of those have an implementation issue, or resources leak, it will trickle down to your application.  This is why it is best to open/close videos as few time as possible.  So you should also make sure that you have the latest GPU drivers installed - that may help too.  We do soak testing here and can open+close many thousands of videos, but again it is system dependent.  If you're still having issues perhaps you could replicate the issue using one of our sample apps, and then send us steps to reproduce, or email us your scene+project files (email to the address at www.renderheads.com/contact/)

Does that help?

Thanks,

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.
