### ISSUE TITLE
Can't play videos in Unity Editor on Mac. Video run for 1 second and then stalls.

### ISSUE THREAD

**Issue by Drugges** [RenderHeads/UnityPlugin-AVProVideo#300]
When I try to play videos in Unity editor it runs for about 1 second. Then it stalls and jumps between frames for the rest of the video. The audio continues correctly but the video just flashes between a few frames. I get this error on every video I try. Even with the demo scenes. It might be at the same time the watermarks appear.

When I deploy to my Oculus GO it works.

 - Unity version: 
2019.2.13, 2019.3.5 and 2019.3.6

 - AVPro Video version: 
Not really sure how to see it. I downloaded the trial today.

 - Operating system version: 
Mac OS Catalina, 10.15.3

**Comment by MorrisRH** [comment]
The trial version has this issue when using the editor with Metal rendering.
A fix is being worked on but in the interim you can uncheck "Metal Editor Support*" in the project settings inspector to work around this issue.

**Comment by Drugges** [comment]
Thanks for the answer. As long as it works in the non-trial I'm happy.

**Comment by AndrewRH** [comment]
Yes the non-trial version doesn't have this issue.  Thanks,
