### ISSUE TITLE
Feature Request: Subtitles toggle switch and array list

### ISSUE THREAD

**Issue by DeafPhilosopher1** [RenderHeads/UnityPlugin-AVProVideo#301]
Could you please add a toggle switch for subtitles to be switched on and off.
Also, with the array list of videos, it would be ideal to have an array list of subtitles.

Create one more demo with the toggle switch for subtitles to be turned on/off along with VCR script having both the video file size and subtitle file size.

![image](https://user-images.githubusercontent.com/33989780/77185318-22ca5680-6b21-11ea-8fef-71416ec952c4.png)

I haven't brought the asset yet but I can see its potential.  I am willing to buy if it has the toggle and array list.  Then I am all set to buy it.

**Comment by AndrewRH** [comment]
Version 2.x of AVPro Video now has a toggle subtitles option in the MediaPlayer demo and supports embedded subittles.

Closing this issue
