### ISSUE TITLE
macOS crash when using incorrect JSON format for HTTP header fields

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#304]
A user reported here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/56#issuecomment-602977777

that a crash happens when parsing this incorrect JSON:
{"cookie":{"CloudFront-Policy":"xxx","CloudFront-Key-Pair-Id":"yyy","CloudFront-Signature":"zzz"}}

would be good to prevent crashing behaviour even if JSON is not right

**Comment by MorrisRH** [comment]
Well it was a bodge to get header support in quickly so I'm not surprised there's an issue, just surprised it took so long to be noticed!

Will review and see about improving this but the crash is fundamentally a problem with using JSON for this.

**Comment by MorrisRH** [comment]
Replaced the current text box json entry with a more appropriate key-value text field pairing.
