### ISSUE TITLE
Duplicate class when using with other plugins

### ISSUE THREAD

**Issue by alanrenouf** [RenderHeads/UnityPlugin-AVProVideo#306]
I am hitting issues when using this plugin and trying to compile for an android based device (Oculus Quest and Pico G2 4K).  

It seems that when you use this plugin in a project with the Vuplex Browser (https://developer.vuplex.com/webview/overview) plugin and then try and build for android there are some duplicate classes and the build fails as you can see below, i get a lot (600+) of these kind of errors:

Duplicate class com.google.android.exoplayer2.C$ColorRange found in modules classes.jar (:geckoview-nightly-71.0.20191003093956:) and exoplayer2.jar (exoplayer2.jar)

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

It looks like there are now two packages in my repo which use the exoplayer library, I have tried removing one of the duplicates but when I do it stops the player from working.

 - Unity version: 2019.1.8f1
 - AVPro Video version: 
 - Operating system version: Android
 - Device model: All
 - Video specs (resolution, frame-rate, codec, file size):  N/A

**To Reproduce**
1. Import Vuplex Plugin
2. Import AVPro Video Plugin
3. Compile for android fails with duplicate class errors

**Comment by RenderHeadsSte** [comment]
You have stumbled upon an issue we have seen a few other developers recently, where multiple Unity plugins are using the ExoPlayer library.  I am sorry to report there is not a 100% perfect fix.

What you can do, is remove the 'exoplayer2' JAR files from the /Assets/Plugins/Android/ folder and tell AVPro to use the 'MediaPlayer' API path.  The limitation here is not having the choice to use ExoPlayer for video playback in AVPro.

**Comment by RuudvanReenen** [comment]
I'm trying to use Vuplex together with AVPro as well and am running into the same issue.
When removing the exoplayer2 JAR files and setting the Preferred Video API to 'Media Player' the following exception occurs when running the app in Android: 

`AndroidJavaException: java.lang.VerifyError: Verifier rejected class com.RenderHeads.AVProVideo.AVProMobileVideo: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean) failed to verify: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean): [0x2F] cannot access instance field boolean com.RenderHeads.AVProVideo.AVProVideoPlayer.m_bShowPosterFrame from object of type Unresolved Reference: com.RenderHeads.AVProVideo.AVProVideoExoPlayer (declaration of 'com.RenderHeads.AVProVideo.AVProMobileVideo' appears in /data/app/com.companyname.applicationname-2/base.apk)`

Stacktrace: 
`java.lang.VerifyError: Verifier rejected class com.RenderHeads.AVProVideo.AVProMobileVideo: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean) failed to verify: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean):  cannot access instance field boolean com.RenderHeads.AVProVideo.AVProVideoPlayer.m_bShowPosterFrame from object of type Unresolved Reference: com.RenderHeads.AVProVideo.AVProVideoExoPlayer (declaration of 'com.RenderHeads.AVProVideo.AVProMobileVideo' appears in /data/app/com.companyname.applicationname-2/base.apk)
java.lang.Class.classForName(Native Method)
java.lang.Class.forName(Class.java:400)
java.lang.Class.forName(Class.java:326)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source)
com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
android.os.MessageQueue.next(MessageQueue.java:392)
android.os.Looper.loop(Looper.java:136)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.AndroidMediaPlayer.InitialisePlatform () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.CreatePlatformMediaPlayer () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at <00000000000000000000000000000000>:0)`

After this error the following error occurs on each Update(): 
`NullReferenceException: Object reference not set to an instance of an object.
Stack_Trace: SkyboxVideoManager.Update () (at <00000000000000000000000000000000>:0)
`
Any ideas on how to fix this?

**Comment by jolly17ify** [comment]
> You have stumbled upon an issue we have seen a few other developers recently, where multiple Unity plugins are using the ExoPlayer library. I am sorry to report there is not a 100% perfect fix.
> 
> What you can do, is remove the 'exoplayer2' JAR files from the /Assets/Plugins/Android/ folder and tell AVPro to use the 'MediaPlayer' API path. The limitation here is not having the choice to use ExoPlayer for video playback in AVPro.

How do I tell AVPro to use the 'MediaPlayer' API path?
