### ISSUE TITLE
RequiresVerticalFlip() bug for picture loading [il2cpp windows directDraw] 

### ISSUE THREAD

**Issue by tufeixp** [RenderHeads/UnityPlugin-AVProVideo#307]
RequiresVerticalFlip() always return true with picture decoded, but in fact it does not flipped as video decoding does.
In order to fix this, I have to disable the flip code at ApplyMapping() when loading pictures.

**Comment by AndrewRH** [comment]
hmm...so is this only when making an IL2CPP build?  Or does it happen in the editor too?

Also, which picture formats are you seeing this with?

**Comment by tufeixp** [comment]
It happens only in il2cpp build, not in mono build or in the editor for any picture format, eg. png,jpg,etc.

**Comment by AndrewRH** [comment]
Interesting, thanks.

Which version of Unity are you using?
Are you building to 32-bit or 64-bit executable?

**Comment by tufeixp** [comment]
2019.3.2f1
64bit executable

**Comment by AndrewRH** [comment]
I was able to replicate the issue.

We will fix this in the next update.  For now you can fix it yourself by opening WindowsMediaPlayer.cs (in Scripts/Internal folder)

and changing line 11-13:

```
#if UNITY_WP_8_1 || UNITY_WSA || UNITY_WSA_8_1 || UNITY_WSA_10
	#define AVPROVIDEO_MARSHAL_RETURN_BOOL
#endif

```
to

```
#if UNITY_WP_8_1 || UNITY_WSA || UNITY_WSA_8_1 || UNITY_WSA_10 || ENABLE_IL2CPP
	#define AVPROVIDEO_MARSHAL_RETURN_BOOL
#endif
```

Please let me know if this solves your issue.

Thanks,

**Comment by tufeixp** [comment]
This does fix the flip issue, thanks!
