### ISSUE TITLE
can't play a rtmp video on windows

### ISSUE THREAD

**Issue by carlye** [RenderHeads/UnityPlugin-AVProVideo#308]
Problem description:

we want use avpro video to  play a rtmp video ,  we change the demo that in trail version, we only change the source path type to  "absolute path or URL" ,
 and url to "rtmp://127.0.0.1:1935/live/movie".  
it does not work normal and report a error ,"[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.".
but it's seem ok in vlc , 
Please help us solve it. thanks a lot !

Device (which devices are you having the issue with - model, OS version number):

windows 10 pc,

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

video url 链接：https://pan.baidu.com/s/1SNxAgWoHtlCEF3m9iEQT3w 
提取码code：3yq7 
rtmp server : livego,  https://github.com/gwuhaolin/livego
ffmpeg.exe -re -stream_loop -1 -i e:\a74a6c6d7cde234bea35531e533529db.mp4 -c copy -f flv rtmp://localhost:1935/live/movie

System Information:

AVPro Video: plugin v1.9.17t scripts v1.10.2
Target Platform: Metro
Unity: v2019.3.5f1 WindowsEditor
OS: Desktop - ASUSPRO P5440FA_P5440FA (ASUSTeK COMPUTER INC.) - Windows 10  (10.0.0) 64bit - Chinese
CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz - 8 threads - 16235KB
GPU: Intel(R) UHD Graphics 620 - Intel - Direct3D 11.0 [level 11.1] - 8117KB - 16384

**Comment by RenderHeadsSte** [comment]
I am afraid we do not currently officially support RTSP/RTMP on any platform.
