### ISSUE TITLE
Mobile autorotation responsive

### ISSUE THREAD

**Issue by Aitzhan1** [RenderHeads/UnityPlugin-AVProVideo#312]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.8
 - AVPro Video version: 1.10.0
 - Operating system version: MacOS
 - Device model: Iphone 11
I want to make a smooth orientation change from portait to landscape (and backwards) in my application (like Youtube and Vimeo works)
Video should not be stretched and flattened during the transition.
Does your plugin support this? 
aitmuhan0@gmail.com

**Comment by MorrisRH** [comment]
Orientation changes are handled entirely by unity, the plugin has no involvement in this at all. We just provide a texture as produced by the video in whatever aspect the video is in.
