### ISSUE TITLE
App with AVPRO player crashed after playing few videos in phone.

### ISSUE THREAD

**Issue by syedali1621** [RenderHeads/UnityPlugin-AVProVideo#313]
**Describe the bug**
I am playing many HLS videos from URL with vuforia image target recognition when app recognizes the image then avpro play video on image target. I purchased both avpro android and iPhone versions when I run the app in phone it plays few videos perfectly but then after playing several videos app crushed. I think avpro player not releasing the memory after playing video kindly please check this problem.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3
 - AVPro Video version: latest
 - Operating system version: mac latest
 - Device model: Samsung S10+5g
 - Video specs (mp4, 5mb): 

**To Reproduce**
1. Download vuforia core sample from unity assets store.
2. run the image target scene.
3. check the video play sample replace unity player with avpro player by changing material.

**Comment by RenderHeadsSte** [comment]
Can we assume this is happening on Android? (as you have put Samsung S10 as the device model).  Have you tried this on iOS, or another Android device?  Could you provide a log?

**Comment by syedali1621** [comment]
As I remember when we deal with many videos from the URL in the app after playing some videos it crushed and it is also happening in Iphone 7 plus i think i tested on that device too.
Please test on both the devices just try to run 100 videos in one device i think when player play video it do not remove the video from memory after playing.
For my project i need to play more than 10000 videos from the URL that is a reason i checked many videos.
Please test with minimum 100 videos then you will see a crashed..

Thank you

**Comment by syedali1621** [comment]
[logcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4526363/logcat.txt)
Here is a log from my friend phone he is facing the same crashed problem.

**Comment by RenderHeadsSte** [comment]
Part of our QA prior to releasing version updates is to open, play, close a video many thousand times.  We also perform this test both reusing, and creating a fresh MediaPlayer object each time.  We are not seeing the behaviour you describe.

Can you give some more information on your pipeline?  Or maybe email over a project demonstrating the issue you are seeing to unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Bump @syedali1621

**Comment by syedali1621** [comment]
As I am calling many videos in the same app from URL. One video play then stop then 2nd video play then stop and so on almost 100 videos. I updated some code and will give more load to app again then i will update you in the meantime I request you please try to run 100 different videos from different URLs then check if app crushed or not in my case it crushed but i am trying to again check with different devices then i will update you soon.
as i think avpro is not releasing memory after playing video.

Thanks..

**Comment by RenderHeadsSte** [comment]
@syedali1621 Would it be possible to send over your project (or a sample project that demonstrates the issue) to [unitysupport@renderheads.com](url) ?
