### ISSUE TITLE
Unity WebGL browser issues

### ISSUE THREAD

**Issue by jensteinkamp** [RenderHeads/UnityPlugin-AVProVideo#314]
I was wondering if you have any advise on how to play video on various platforms and browsers with WebGL?
Do you think Chrome will ever work?

AVPro Video (Windows) 1.10.2 Unity asset
Unity 2019.3.7f1
Microsoft Surface Laptop Windows 10 Pro

Mac browsers Safari works by changing settings, Firefox does not work, Chrome does not work
PC browsers Edge works, Firefox sometimes works, Chrome 81.0.4044.92 does not work

WebGL publish  http://jsteinkamp.com/build_test/

source files were emailed

**Comment by MorrisRH** [comment]
Sadly we're at the mercy of the browser vendors here.

Firefox and Chrome should work although they do require settings site specific settings:
Firefox - enable allow audio and video autoplay
Chrome - enable allow insecure content

Safari still doesn't support WebGL2.0 out of the box so you need to make WebGL1.0 builds from Unity as well as enable autoplay for audio and video (even with this enabled I struggle to get a video to play in safari).

**Comment by RenderHeadsSte** [comment]
We shall be closing this issue soon due to inactivity.

**Comment by AndrewRH** [comment]
Have not heard anything back - assuming resolved - closing issue
