### ISSUE TITLE
Unity version for macOS fails to play video, but works on Android and PC

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#315]
**Describe the bug**

Compile a Unity app for MAC standalone, when run on MAC it gives error that the codec is wrong or something like that, and doesnt play the video How do i fix?
I have set the platform to MAC in the inspector, but same result.

**Your Setup (please complete the following information):**
 - Unity version:  2018.3
 - AVPro Video version: Dont know how to get the version
 - Operating system version:  Compiled on Windows, run on Mac
 - Device model:  MAC OSX
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Run Unity Editor on Windows
2. Set build target to MAC and compile stand alone MAC version
3. Copy app to mac and run it
4. App runs, but when it tries to play video, it gives the following error:

[AVProVideo ] Error: Loading failed: File not found, codec not supported, video resolution too high or insufficient system resources.

I have the AVPro setting to MAC in the inspector, but it still dont work

This same app was built for Android and PC and it works, only on the MAC it gives this error.

**Logs**
If applicable, add error logs to help explain your problem.

[AVProVideo ] Error: Loading failed: File not found, codec not supported, video resolution too high or insufficient system resources.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
The error message suggests that the video you are trying to play isn't a supported format on macOS.  Are you able to provide any information about it? File format, codec, etc.

**Comment by nsmith1024** [comment]
Its just a regular MP4 video file, the same file plays when i build for android and stand alone PC, so why wouldn't it play on MAC?

**Comment by MorrisRH** [comment]
Can you check that in the build Mac application the plugin exists? It should be : Product.app/Contents/Plugins/AVProVideo.bundle.

In the mp4, it it using the h264 codec for the video and aac codec for the audio? If you can share the video that might be helpful in diagnosing the issue (send a link to unitysupport@renderheads.com if you would like to keep it private).

**Comment by nsmith1024** [comment]
Yes AVProVideo.bundle exists in the mac build.

I dont know if its using aac coded or not, Do you have some kind of tool i can use to check?

i cant share the video unfortunately.

**Comment by MorrisRH** [comment]
I tend to use ffprobe which comes with ffmpeg, available here: https://www.ffmpeg.org
Something with a GUI (I've not used this though): https://mediaarea.net/en/MediaInfo

**Comment by RenderHeadsSte** [comment]
@nsmith1024 Do you have anything to report on this issue?

**Comment by nsmith1024** [comment]
Here is the ffprobe output, the command was this

 **ffprobe 1_0e7f4910be9362c79e9c9ddf28c18714.mp4**

ffprobe version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1_0e7f4910be9362c79e9c9ddf28c18714.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
    comment         : vid:v09044000000bpn84l1sihva88cnmaf0
  Duration: 00:00:31.67, start: 0.000000, bitrate: 2960 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x1280 [SAR 1:1 DAR 9:16], 2890 kb/s, 43.14 fps, 45 tbr, 11520 tbn, 90 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

**Comment by nsmith1024** [comment]
Here is the ffprobe output, the command was this

**ffprobe 1_0e7f4910be9362c79e9c9ddf28c18714.mp4**

ffprobe version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2007-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil 55. 78.100 / 55. 78.100
libavcodec 57.107.100 / 57.107.100
libavformat 57. 83.100 / 57. 83.100
libavdevice 57. 10.100 / 57. 10.100
libavfilter 6.107.100 / 6.107.100
libavresample 3. 7. 0 / 3. 7. 0
libswscale 4. 8.100 / 4. 8.100
libswresample 2. 9.100 / 2. 9.100
libpostproc 54. 7.100 / 54. 7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1_0e7f4910be9362c79e9c9ddf28c18714.mp4':
Metadata:
major_brand : isom
minor_version : 512
compatible_brands: isomiso2avc1mp41
encoder : Lavf57.83.100
comment : vid:v09044000000bpn84l1sihva88cnmaf0
Duration: 00:00:31.67, start: 0.000000, bitrate: 2960 kb/s
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 720x1280 [SAR 1:1 DAR 9:16], 2890 kb/s, 43.14 fps, 45 tbr, 11520 tbn, 90 tbc (default)
Metadata:
handler_name : VideoHandler
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 64 kb/s (default)
Metadata:
handler_name : SoundHandler

**Comment by nsmith1024** [comment]
Hello, Do you know when this will be fixed? I need it now!!

**Comment by AndrewRH** [comment]
Hi @nsmith1024 

Thanks for providing those details.  Someone on our team will get back to you.

In the meantime please you can let us know which version of AVPro Video you're using.  The version number can be found when you play the app in Unity, it will be printed to the console window:
![image](https://user-images.githubusercontent.com/5418126/81024355-16991f00-8e6b-11ea-9563-7b93cca60f77.png)

Or you can go to the MediaPlayer component Help/About section and it is printed there:
![image](https://user-images.githubusercontent.com/5418126/81024329-0a14c680-8e6b-11ea-9971-435a8007faf3.png)

The latest released version is 1.10.3, and we always recommend using the latest version when possible.

Thanks,

**Comment by nsmith1024** [comment]
Im using Unity 2018.3.14 and AVPro version 1.10.1t (scripts V1.10.1)

    On Monday, May 4, 2020, 7:57:07 PM EDT, Andrew <notifications@github.com> wrote:  
 
 


Hi @nsmith1024

Thanks for providing those details. Someone on our team will get back to you.

In the meantime please you can let us know which version of AVPro Video you're using. The version number can be found when you play the app in Unity, it will be printed to the console window:


Or you can go to the MediaPlayer component Help/About section and it is printed there:


The latest released version is 1.10.3, and we always recommend using the latest version when possible.

Thanks,

**Comment by nsmith1024** [comment]
Im using Unity 2018.3.14 and AVPro version 1.10.1t (scripts V1.10.1)

**Comment by MorrisRH** [comment]
The output from ffprobe for the video looks to be fine. It would be ideal if you could provide a link to the video so that we might be able to diagnose what is going on more quickly. If you want to keep it private, send it to unitysupport@renderheads.com (mention this GitHub issue if you do).

Here's a few more questions that might help us to understand what the problem is:
1. How are you accessing the video? Is it bundled locally in StreamingAssets or being accessed over the internet?
2. Have you tried using one of the sample videos included in the trial package?
3. What specification is Mac you're using?
4. What version of macOS is the Mac running?

**Comment by nsmith1024** [comment]
1. The video player is given a URL for the video that is located on a server. Its the same code and everything else for Android and PC and MAC, but when compiled for MAC it doenst play
2. No havnt tried sample videos on Mac
3. Its an old Mac Mini
4. Have to boot it up and get the OS version

**Comment by timokorkalainen** [comment]
Just noticed this after posting my own issue: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/365 Perhaps these are related?

**Comment by AndrewRH** [comment]
Hi @nsmith1024 

Were you able to send us your video file, or is the issue resolved?

Also, were you eventually able to try our sample videos on that Mac, and also get the OS version?

Thanks,

**Comment by nsmith1024** [comment]
Its not stale sheesh
