### ISSUE TITLE
playback rate

### ISSUE THREAD

**Issue by aaronng78** [RenderHeads/UnityPlugin-AVProVideo#316]
Problem description:

I'm working on a  project but when i set playback rate to -1, it won't play   

Device (which devices are you having the issue with - model, OS version number):

oculus go

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: plugin v1.10.2 scripts v1.10.2
Target Platform: Android
Unity: v2019.3.3f1 OSXEditor
OS: Desktop - MacBookPro15,1 - Mac OS X 10.15.4 - English
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 12 threads - 16384KB
GPU: AMD Radeon Pro 555X - Apple - Metal - 4096KB - 16384

**Comment by AndrewRH** [comment]
Hi,

Negative playback is generally not supported.  It does work on some platforms but it's really an edge case.

Please see the AVPro Video PDF documentation, there is a section about playback rate.  This has details on why this is and possible workarounds.

Let me know if you still have any further questions?

Thanks,
