### ISSUE TITLE
NVidia Experience and AVPro - crash after update.

### ISSUE THREAD

**Issue by yarvr** [RenderHeads/UnityPlugin-AVProVideo#317]
**Describe the bug**
I just got an update of **NVidia Experience** and it crashed all **AVPro** playback on my computer. I removed this components and it started to work perfectly.
Do you have any ideas on this and how is this related to the latest updates?

_I'm investigating this problem, but maby if some user complains that **AVPro** has stopped playing video **better than 1080p**, try removing **NVidia Experiance** from the **Control Panel -> Delete** and answer if this helped or not.
Tnx!_

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.11
 - AVPro Video version:  1.10.0
 - Operating system version: Windows 10
 - Device model: oculus rift

**Comment by AndrewRH** [comment]
Hi,
Thanks for reporting this issue.  We have had reports of this component causing issues in the past, but not recently.  

I have a few questions to help us resolve the issue:

1) Do you mean the "Geforce Experience" that is an optional extra that comes with NVidia driver?
2) Do you know which version of Geforce Experience you had installed that was causing the problem?
3) Also, could you tell us the specs for the video that caused the crash - or did it also happen when using out sample media and demo scenes?
4) What model of GPU are using?
5) Is this in the Unity editor that it's crashing, or when you've made a build?
6) Could you try upgrading to the latest version (1.10.3) of the AVPro Video plugin to see whether that resolves the issue.
7) Could you explain what sort of crash happens.  When the video tries to play back does the application quit?

Thanks,

**Comment by AndrewRH** [comment]
Have not heard anything back - assuming resolved - closing issue
