### ISSUE TITLE
can not run in OpenGL ES 3.1AEP

### ISSUE THREAD

**Issue by caihuazei2012** [RenderHeads/UnityPlugin-AVProVideo#319]
**Describe the bug**
AVPro can running in DX, but I use OpenGL ES 3.1AEP.There is no texture in preview,and WindowsMediaPlayer.GetTexture() is null. And 
 Native.GetTexturePointer(_instance)==System.IntPtr.Zero. what can I DO!

please reply to me quickly!!!!!!!!!!!!!!

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.2
 - AVPro Video version: 1.10.0
 - Operating system version: windows10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): yours mp4

**To Reproduce**
1. 
2. 
3. 

**Logs**
no error log

**Screenshots**
 
![Uploading 企业微信截图_15871987383453.png…]()
There is no texture in preview,and WindowsMediaPlayer.GetTexture() is null. And 
 Native.GetTexturePointer(_instance)==System.IntPtr.Zero

**Videos**
If applicable, add a copy of your video or the URL

**Comment by AndrewRH** [comment]
Hi,

I'm confused...you're running on Windows...

Windows doesn't support OpenGL ES 3.1AEP - that's only for Android.

Thanks,

**Comment by caihuazei2012** [comment]
> Hi,
> 
> I'm confused...you're running on Windows...
> 
> Windows doesn't support OpenGL ES 3.1AEP - that's only for Android.
> 
> Thanks,

haha,I am so sorry

**Comment by AndrewRH** [comment]
Oh no problem...are you still having any issue, or can we close this ticket?

**Comment by caihuazei2012** [comment]
I have closed，now I have a question: which event I should addListener,when media.stop()




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andrew"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月19日(星期天) 凌晨0:37
收件人:&nbsp;"RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com&gt;;
抄送:&nbsp;"娱乐圈王主播"<963687571@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] can not run in OpenGL ES 3.1AEP (#319)





 
Oh no problem...are you still having any issue, or can we close this ticket?

**Comment by caihuazei2012** [comment]
The video memory need&nbsp; I to release？&nbsp;The video is auto release memory?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrew"<notifications@github.com&gt;; 
发送时间: 2020年4月19日(星期天) 凌晨0:37
收件人: "RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com&gt;; 
抄送: "娱乐圈王主播"<963687571@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] can not run in OpenGL ES 3.1AEP (#319)





 
Oh no problem...are you still having any issue, or can we close this ticket?
