### ISSUE TITLE
Looping video lag and Playlist component with videoapi "Mediaplayer" on Android - Pico Goblin

### ISSUE THREAD

**Issue by couragesemawu** [RenderHeads/UnityPlugin-AVProVideo#32]
**Describe the bug**
We are currently using this plugin for a tight deadline project and have run into some issues regarding video performance over a certain amount of time specifically when looping the video. Over a few loops, there is a lag at the end of the video before it loops again and this happens after a few runs. We noticed changing the Android videoapi from Exoplayer to Mediaplayer helps but we can't get this to work with your Playlist component. Any help?

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.0.f2
 - AVPro Video version: 1.9.12
 - Operating system version: Android 6.0.1
 - Device model: Pico Goblin
 - Video specs (resolution, frame-rate, codec, file size): 2048X2048 stereo, 30, H264, 40mb

**To Reproduce**
1. Load looping video in Headset, After few runs of looping video it starts to lag.

**Comment by AndrewRH** [comment]
Hmmm, by "lag" do you mean it starts to play slowly?

Could the device be overheating and so throttling the hardware?

**Comment by RenderHeadsSte** [comment]
We shall be closing this issue shortly due to a lack of response.  Please do update us on the status if there is anything to report.
