### ISSUE TITLE
Mac App Store review rejection due to non-public API usage

### ISSUE THREAD

**Issue by peoplepilot** [RenderHeads/UnityPlugin-AVProVideo#322]
**Describe the bug**
Our app update was rejected due to use or reference to non-public APIs, as described in the rejection message below. Is there any chance this is due to AVProVideo?

Rejection message:

Your app uses or references the following non-public APIs:

_XCreateColormap, _XUngrabPointer, _XConfigureWindow, _XGrabPointer, _XSetWindowColormap, _XDefineCursor, _XGetWindowProperty, _XFillRectangle, _XQueryColors, _XCreateGC, _XRefreshKeyboardMapping, _XFreeColors, _XSelectInput, _XRaiseWindow, _XDestroyWindow, _XMapWindow, _XWarpPointer, _XResizeWindow, _XDrawLines, _XGetVisualInfo, _XInternAtom, _XFillPolygon, _XAllocColor, _XChangeProperty, _XCreateBitmapFromData, _XUnmapWindow, _XFreeColormap, _XGetGeometry, _XChangeWindowAttributes

The use of non-public APIs is not permitted on the App Store, because it can lead to a poor user experience should these APIs change.

We are constantly reevaluating and identifying non-public APIs that you may have been using for an extended period of time. You should always use public APIs and frameworks and ensure they are up-to-date to prevent this issue in the future.

Next Steps

If you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.21f1
 - AVPro Video version: 1.8.7 (I have just updated to 1.10.3 but have yet to resubmit due to the warning message about continuing to use non-public apis)
 - Operating system version: 10.14.6
 - Device model: 2017 Macbook Pro
 - Video specs (resolution, frame-rate, codec, file size): n/a

**To Reproduce**
1. build our app and submit to the Mac App Store
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
AVPro Video doesn't make use of any of those APIs. They look like they're X-Windows related, are you using anything that links with XQuartz?

Closing this as it's not AVPro related and to the best of my knowledge we only use public APIs.
