### ISSUE TITLE
How calculate the livestream latency? 

### ISSUE THREAD

**Issue by StarWardo** [RenderHeads/UnityPlugin-AVProVideo#323]
We would like to calculate the delay between when the frames were captured by our insta360 pro camera and when they are displayed on our Hololens 2 end device using live steam HLS protocol. 

To do this we want to check the creation date/time of the video and compare it to the current time of the device and when the next frame is created. The difference would be the delay. 

But right now there doesn't seem to be a way to check the creation date/time of the video. 

Are there any other alternatives the calculate the livestream delay? 

Thanks

**Comment by AndrewRH** [comment]
Does the HLS stream provide the EXT-X-PROGRAM-DATE-TIME field?
If so, then you should be able to call mediaPlayer.Control.GetCurrentDateTimeSecondsSince1970()

This can be converted into a DateTime using Helper.ConvertSecondsSince1970ToDateTime()

Currently we only support this tag on macOS, iOS, tvOS and Android (using ExoPlayer API)

I hope that helps?

Thanks,

**Comment by AndrewRH** [comment]
Have not heard anything back - assuming resolved - closing issue
