### ISSUE TITLE
Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

### ISSUE THREAD

**Issue by camminglkp** [RenderHeads/UnityPlugin-AVProVideo#324]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.13.f1
 - AVPro Video version: v1.10.0 plugin v1.9.17
 - Operating system version: windows 10
 - Device model: HUAWEI MagicBook inter i5-8250U 1.80GHz
RAM:8.00GB x64
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
**Screenshots**

**Videos**
http://vod.tfwangs.com/061965c7a03d4f039f8db171bb195ce9/21c05d24167543f3bb871d6357513011-48a859f4c219001fb8c69be782eabdec-sd.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Is it not loading in Windows 10, or another platform that you're building to?

I can't see any obvious issues with the video.  Do our sample videos play for you?

Thanks,
