### ISSUE TITLE
Hololens 2 video codec support

### ISSUE THREAD

**Issue by predictcare** [RenderHeads/UnityPlugin-AVProVideo#326]
**Describe the bug**
Initially seemd i can build our app for holo 1 and it works but it doesn't for holo 2. 
Edit, updated with new version and now it works ok, so my fault. But still we had some problems with Codecs.

**Your Setup (please complete the following information):**
 - Unity version: 
2019.2.15
 - AVPro Video version: 
April 2020
 - Operating system version: 
Windows 10 - 
 - Device model: 
Hololens 2
 - Video specs (resolution, frame-rate, codec, file size): 

(attached)
<img width="502" alt="Screenshot 2020-04-24 at 12 02 51" src="https://user-images.githubusercontent.com/44294239/80200870-929d9680-8623-11ea-8806-e057f128072f.png">

**To Reproduce**
1. 
Just Play Video

The error is :

Avplayer error, loading failed, file not found codec not supported, video resolution too high or insufficient system resources

Thanks

**Comment by AndrewRH** [comment]
Hi,

Do our sample videos work for you?

Many platforms do not support MP3 in the audio track for MP4 files...  I recommend encoding the audio track as AAC for best compatibility.

Does that help?

**Comment by AndrewRH** [comment]
Since we have not heard back, we assume you resolved the issue.  I will close this ticket soon if we haven't heard back soon.  Thanks,

**Comment by AndrewRH** [comment]
Have not heard anything - assuming resolved - closing issue
