### ISSUE TITLE
How to clear up  the texture of video from memory?

### ISSUE THREAD

**Issue by Justin-sky** [RenderHeads/UnityPlugin-AVProVideo#328]
Describe the bug
When I play a video from the game scene of Login and finished, then destory the login scene, and switch to other scene, but I  capture the gpu frame with xcode, and find the CoreVideo Texture still in the memory? (I have call the CloseVideo() method before swith scene) Is there have other method to clear up the video texture from memory?

Your Setup (please complete the following information):

Unity version:
2018.4.7
AVPro Video version:
1.9.17
Operating system version:
Windows 10 -
Device model:
Hololens iphone x
Video specs (resolution, frame-rate, codec, file size):
mp4
![t1](https://user-images.githubusercontent.com/58215826/80306419-c0d2d000-87f5-11ea-8b11-a6600b84face.png)

**Comment by AndrewRH** [comment]
Please try upgrading to the latest version of AVPro Video (1.10.3) as some improvements in iOS memory usage were recently implemented.

Let us know if that solves the issue for you.

Thanks,

**Comment by Justin-sky** [comment]
Today, I upgraded the version of 1.10.3 and the issue was solved, thanks very much!
