### ISSUE TITLE
Switching to YouTube and playing 4k issues

### ISSUE THREAD

**Issue by dayjur** [RenderHeads/UnityPlugin-AVProVideo#329]
I am getting QA from Amazon saying if I switch from App to YouTube and try to play 4k video it serves a black screen, I gather this is happening on certain fire tv 4k devices, wondering whether onapplicationfocus do something to release resources.

**Comment by AndrewRH** [comment]
I'm not aware of anything that is done OnApplicationFocus.

Please provide more details, such as:

1) Unity version
2) AVPro Video version
3) Android version
4) Whether you're using the ExoPlayer or MediaPlayer video API

I know amazon have a special port of ExoPlayer for their devices...and we don't use that port.  Perhaps if you're using ExoPlayer you could try to switch to the MediaPlayer video API to see whether that helps?

Thanks,

**Comment by dayjur** [comment]
Unity 2017.2.17, avpro 10.1, amazon fire tv os lastest, exo player

got this from them 
**The issue is happening on Grundig OLED 4K (2019), Grundig Vision 7 4K (2019), Fire TV Edition - JVC 4K (2019), Fire TV Edition - Toshiba 4K (2018/2019) and Fire TV Edition - Insignia 4K (2018).
The root cause of the issue is that the app was not releasing resources on Activity.onStop()**

Its not happening on their very popular 4k stick which is great, but on OS built into 4k tv's
Note also i did recently switch to EXO after i encountered video issues using MediaPlayer

[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4536368/log.txt)

**Comment by dayjur** [comment]
Update
Issue appears to be happening only on 4k TV's with OS built in, not on standalone devices
as well as devices mentioned above, I have repro issue on my Sony Bravia Android 4k tv also.

Using av pro mediaplayer and Display UGUI  components start app play video, press home button start youtube, try to play 4k video, black screen video will not play, go back into App with avpro, press back button exit app, go back into youtube 4k video now plays,
Note setting mediplayer or exoplayer does the same thing
any ideas

**Comment by dayjur** [comment]
Update if closevideo() thus releasing resources before home screen and switching to youtube 4k video plays fine, so appears lack of resources, but isnt the android OS supposed to kill Apps when resoucres are low ? its killing it one one of my Fire TV's but not others

**Comment by RenderHeadsSte** [comment]
I was about to suggest closing all videos on switching away from the app that is using AVPro Video!

Not all incarnations of Android are built the same.  Some hardware vendors adjust things to suit their needs.  On top of that, I would bet that releasing the decoders/other resources is not on that list...so if the app/activity using AVPro Video was not being killed for other reasons (memory, etc) then I can well believe the decoder or whatever other resources ExoPlayer uses that there is only one/limited-amount-of was locked...no video playback.

Glad you got it sorted though :)  Happy for me to close this issue now?

**Comment by dayjur** [comment]
Yes you can close this
