### ISSUE TITLE
UWP ARM64 build

### ISSUE THREAD

**Issue by mgrman** [RenderHeads/UnityPlugin-AVProVideo#33]
**Describe the solution you'd like**
There are already builds for UWP x86, x64 and ARM platforms. With Unity 2019 there is an option of UWP ARM64. DLL for this platform is missing. Is it possible to build the plugin for UWP ARM64 as well?

**Comment by provencher** [comment]
With HoloLens 2 coming, it would be nice for this to be supported. Is there any ETA on the feature?

**Comment by michalek-marcin** [comment]
Is there any ETA on the feature? I need it to build app for Hololens 2.

**Comment by RenderHeadsSte** [comment]
This is certainly something we might be able to look at including in our releases.

If we can, and you are interested in testing a version, drop me an email at unitysupport@renderheads.com with a copy of your asset store purchase receipt...and we can go from there.

**Comment by michalek-marcin** [comment]
Hi @RenderHeadsSte I've sent invoice to address you give me and just got answer:

"We are no longer handling bug reports or feature requests at this email address.
Only product questions will be replied to here.
..."

Do you have access to that mailbox?

**Comment by michalek-marcin** [comment]
@RenderHeadsSte Can you check your mailbox? I still haven't received testing version from you.

**Comment by michalek-marcin** [comment]
@RenderHeadsSte @AndrewRH I need version with UWP ARM64 support.

**Comment by mgrman** [comment]
@RenderHeadsSte We would also be very interested in UWP ARM64 version, for use on HoloLens2. My colleague sent you an email as well with the receipt, see email from nicolas.koutnik@re-flekt.com

**Comment by michalek-marcin** [comment]
@RenderHeadsSte @AndrewRH  Hi, I'm waiting nearly 3 weeks for answer. Do you still provide support for customers?

**Comment by RenderHeadsSte** [comment]
> @RenderHeadsSte @AndrewRH Hi, I'm waiting nearly 3 weeks for answer. Do you still provide support for customers?

We only stated that it was:  'something we might be able to look at including in our releases'.  There were no firm guarantees or timelines.

This is en enhancement, not support for an issue with AVPro Vieo.  Please bear this in mind when posting up such comments that, unfortunately, just end up wasting development and support time.

**Comment by RenderHeadsSte** [comment]
I have a compiled watermarked UWP ARM64 dll that I will be sending along to those that emailed with interest.

**Comment by provencher** [comment]
@RenderHeadsSte if I provide an invoice, is it possible to get a non watermarked dll? I’m not in a hurry so if you plan on releasing this dll down the line, I’m happy to wait.

**Comment by RenderHeadsSte** [comment]
> @RenderHeadsSte if I provide an invoice, is it possible to get a non watermarked dll? I’m not in a hurry so if you plan on releasing this dll down the line, I’m happy to wait.

At this stage we are restricting it to a watermarked test release.  Once we ascertain the build is fit for purpose, we will be releasing it with future updates.  If the next build is beyond an important date for those testing it, we will look at sending over a none-watermarked build upon proof of purchase.

Have you sent en email over to unitysupport@ ?  (apologies if I have missed it)

**Comment by AndrewRH** [comment]
I'm closing this ticket as this feature should now be in the next release (1.10.2) which will be released shortly.  Thanks,
