### ISSUE TITLE
Problem with SRT file via URL

### ISSUE THREAD

**Issue by rabdenlip** [RenderHeads/UnityPlugin-AVProVideo#330]
We have a problem with a SRT subtitle file URL. When using the following URL (https://san-t1.w3.rbb-online.de/av/sendung/_20200426_26_moffels_radfahren.subtitle.srt) with „Absolute path or URL“ as a subtitle in a media player of the current AVPro asset store version we get an error.
When we copy the text from the URL into a file and use it from the steaming assets folder, everything works fine.

Our setup
 - Unity version: 2019.3.9
 - AVPro Video version: 1.10.3
 - Operating system version: macOS 10.14.6, Android 8.1

**To Reproduce**
1. Open SVPro Subtitle demo scene
2. Change subtitle path to our URL

**Logs**
[AVProVideo] Failed to load subtitles https://<our-url>/file.srt
UnityEngine.Debug:LogError(Object, Object)
RenderHeads.Media.AVProVideo.<LoadSubtitlesCoroutine>d__166:MoveNext() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:744)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

I sent you the SRT URL via mail.

**Comment by RenderHeadsSte** [comment]
The URL to your SRT file appears to require authentication.  Would it be possible to remove this barrier to ascertain that is the problem here, rather than the SRT being fed off the server in question?

**Comment by rabdenlip** [comment]
I think that's the reason. We can not test it because we have to wait for our backend team. I am pretty sure this issue can be closed.
