### ISSUE TITLE
WebGL unable to load HLS stream

### ISSUE THREAD

**Issue by Twyker** [RenderHeads/UnityPlugin-AVProVideo#331]
Hi!

**Describe the bug**
I seem to be having the exact problem as stated here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/327

But the solution doesn't work for me.
I did activate CORS for the test server.
I did put in the hls.min.js as well as the map into the Template folder and call it before the Unity script in the index.html.
I did allow everything on every browser, meaning insecure content, video and audio.
I'm opening the video with MediaPlayer.OpenVideoFromFile(MediaPlayer.m_VideoLocation, MediaPlayer.m_VideoPath, false); and waiting for the MediaPlayerEvent.EventType.ReadyToPlay to trigger the MediaPlayer.Control.Play();

Tried different Chromium browsers as well as Firefox. Same error on all of them.

**Your Setup:**
 - Unity version: 2019.3.0f6
 - AVPro Video version: latest trial
 - Operating system version: Windows 10 Pro
 - Device model: desktop
 - Video specs: m3u8 live stream that is confirmed working via VLC

**Logs**
Error: video not supported (errorcode=4) color:red;
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by AndrewRH** [comment]
Hi,

Thanks for reporting the issue.  In the other post he seems to have been able to get it working just fine.  I wonder why it's not working for you.

Some of the events don't trigger in WebGL, so have you tried not waiting for an event and just doing AutoPlay?

Did you set the use of HLS.JS in the Platform Specific > WebGL options on the MediaPlayer component?

Did you try different HLS sources?

Thanks,

**Comment by Twyker** [comment]
I tried to call the Play manually via a UI Button, I going to try it with AutoPlay real quick.
I read about the FirstFrame issue as well, so I thought I'd couple it to a different event that seems to be working in Browser, but oh well. :)

I did set the HLS.JS in the WebGL Options of the MediaPlayer component.
The test URLs in the PDF are producing the same errors sadly.

**Comment by AndrewRH** [comment]
Edge has native HLS support, so that should definitely work (even without using the HLS.JS)...Let me know how it goes with your test.  If you don't have any luck I will try to build using your Unity version to see if that reveals anything.

**Comment by Twyker** [comment]
Well, the new Edge is Chromium based so not much of a change there. The older one doesn't even load the project cause of the graphics API it uses.

Did try to get native HLS support via plugins, but to no avail.

I did however buy AVPro already. Gonna see if that helps. ;)

**Comment by Twyker** [comment]
Ok. This issue has been resolved. I'm just stupid, is all.
I had the MediaPlayer component on a GO that was part of an addressable asset. After adding the HLS.js setting, I forgot to rebuild the addressables.

Thanks @AndrewRH ! :)

**Comment by AndrewRH** [comment]
Glad you managed to resolve it :) Best of luck!

**Comment by adrw2** [comment]
Hi @Twyker 
Im having the same issue, after following the steps from #327 livestream videos dont load.

i didnt undertand well what you meant in your last sentence: "I forgot to rebuild the addressables." 

could you show how you finally achieved it?  i would appreciate it!

**Comment by Twyker** [comment]
@adrw2 
Hi!
Are you actually using Addressables in your project? If you don't then this would not apply in your case. :)
I had the main RenderHeads component on an "addressable object" but I did not rebuild/update it in the database,
so the RenderHeads component was not actually on it/the HLS setting was not set.

So if you're having the same setup as me, just make sure the HLS setting is set in the options on the MediaPlayer component and add the hls.min.js file to the WebGL files of your project (TemplateData). :)
