### ISSUE TITLE
live mpegts streams just freeze on the first picture

### ISSUE THREAD

**Issue by serversdz** [RenderHeads/UnityPlugin-AVProVideo#332]
**Describe the bug**
when I try to play a live mpegts stream it just freezes on the first picture
**Your Setup (please complete the following information):**
 - Unity version: 2019.3.11.f1
 - AVPro Video version: the latest
 - Operating system version: editor
 - Device model: desktop
 - Video specs (resolution, frame-rate, codec, file size): mpegts live

**Comment by AndrewRH** [comment]
Hi, the platform/OS is really important information to help us work out what the issue could be  - which OS is the editor running in?

Also could you give more information about the stream?  Is it HLS?  Do you have a sample URL?

Thanks,

**Comment by serversdz** [comment]
yeah
it s mpeg because it's faster than hls
using windows
http://serversdz.com:25461/sofiane/f9iRUmVtqD/689

**Comment by AndrewRH** [comment]
I have replicated the issue.  I'm not sure why this is happening.  It could be that Media Foundation doesn't support MPEG-TS

I have also tried on our yet-unreleased AVPro Video 2.0 which uses the newer WinRT video API, and it's working in that.

Thanks for providing the example, I will dig a bit further to see about the Media Foundation API support, and will get back to you.

Thanks,

**Comment by AndrewRH** [comment]
@serversdz  could you confirm whether you're using the DirectShow or Media Foundation API ?  It should log this in the console window, but you can also check your settings on the MediaPlayer Component > Windows > Video API

Thanks,

**Comment by AndrewRH** [comment]
Hi @serversdz 
We found the issue (it was a bug in our software).  We'll have a fix out shortly in the next version (1.11.0)
Thanks,

**Comment by serversdz** [comment]
thanks a lot 
Looking forward to the new updates

**Comment by serversdz** [comment]
preferred video API Media Foundation

**Comment by AndrewRH** [comment]
I will close this now.  The new version with the fix will be out next week.
Thanks,
