### ISSUE TITLE
From QA Amazon

### ISSUE THREAD

**Issue by dayjur** [RenderHeads/UnityPlugin-AVProVideo#333]
**Describe the bug**
I am getting this form QA at Amazon while it does not affect end user, apparently its affecting their debug capabilites
**The App is trying to access a “system protected paths” for cpuinfo_max_freq, which is generating a Log Spam on our devices logging at 25 logs a second.**
Does this ring a bell for AVPro or is this a Unity platform issue I posted on Unity forums too but no answer yet
**Your Setup (please complete the following information):**
 - 2017.2.17f1
 - AVPro Video version: 10.1
 - Fire OS

**Comment by AndrewRH** [comment]
For reference, here is the post to the forum which contains more details:
https://forum.unity.com/threads/qa-issue.876328/

**Comment by AndrewRH** [comment]
Hi,

Are you able to replicate this logging issue on your side?  If so, perhaps you can remove AVPro Video to see whether you still get the logging?   You could also try switching the Media API from ExoPlayer to MediaPlayer to see whether that makes any difference.

I'm not sure if it's coming from our plugin, or just from Unity app in general, and we don't have any Fire OS hardware here to test on...

Thanks,

**Comment by dayjur** [comment]
I cannot repro my end have asked QA team for more details

**Comment by dayjur** [comment]
After upgrading Unity to 2019_3_1 they are not getting it anymore u can close out
