### ISSUE TITLE
2 videos doesn't play at the same time on Android

### ISSUE THREAD

**Issue by levin-Imagin8ors** [RenderHeads/UnityPlugin-AVProVideo#336]
Problem description:

when i try to play two videos, first video gets stuck or frozes only the second video plays

Device (which devices are you having the issue with - model, OS version number):

android tv, Mali-G31, Android 9

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

2 videos, bunny video from streaming assets

System Information:

AVPro Video: plugin v1.9.17t scripts v1.10.3
Target Platform: Android
Unity: v2019.3.5f1 WindowsEditor
OS: Android OS 9 / API-28 (1.15.5/20200120)
CPU: ARM64 FP ASIMD AES
Cores: 4
Ram Memory: 2008mb
GPU: Mali-G31/OpenGL ES 3.2 v1.r16p0-01rel0.bcc0cdabec638d4bf85475d4a5ae47a7

**Comment by RenderHeadsSte** [comment]
Can you provide more information about the videos?  Or the URLs to them?

When API path are you using? (ExoPlayer or MediaPlayer)

Can you send over the logcat output?

**Comment by levin-Imagin8ors** [comment]
Scenes: 05_Demo_Multiple and 10_Demo_Transparency.
Videos: AvPro\Assets\StreamingAssets\AVProVideoSamples\AlphaLeftRight and AvPro\Assets\StreamingAssets\AVProVideoSamples\BigBuckBunny_360p30
![AvPro - 10_Demo_Transparency - Android - Unity 2019 3 5f1 _DX11_ 30-04-2020 01_54_27 PM](https://user-images.githubusercontent.com/19970911/80689378-de9c7f80-8aea-11ea-9fd1-662acd0f67ca.png)
![AvPro - 10_Demo_Transparency - Android - Unity 2019 3 5f1 _DX11_ 30-04-2020 01_56_19 PM](https://user-images.githubusercontent.com/19970911/80689383-dfcdac80-8aea-11ea-8b23-391c83b017d8.png)
![Screenshot 30-04-2020 01_55_23 PM](https://user-images.githubusercontent.com/19970911/80689385-e0664300-8aea-11ea-982f-db5a11ab0c64.png)

**Comment by RenderHeadsSte** [comment]
I see you are using the Media Player API path...Have you tried using the ExoPlayer API path?  If that does not help, you could always try enabling the 'Prefer Software Decode' option on all but one of the media player components.

**Comment by levin-Imagin8ors** [comment]
Tried with exoplayer as well same result. Will try with 'Prefer Software Decode'

**Comment by levin-Imagin8ors** [comment]
Tried with 'Prefer Software Decode' on exoplayer, getting performance issues. Video lags. 
Video 1. https://coobo.s3.ap-south-1.amazonaws.com/5878D2F0-5E1C-11EA-B08D-A7DCC64D9143/8F1C36D3-0E65-49E7-AD33-0883B08BB2BC.webm_alpha.mp4
Video 2. https://coobo.s3.ap-south-1.amazonaws.com/5878D2F0-5E1C-11EA-B08D-A7DCC64D9143/E089D02B-82C3-45C8-BC92-ADDD00745415.webm_alpha.mp4

**Comment by RenderHeadsSte** [comment]
But they both play?

**Comment by levin-Imagin8ors** [comment]
> But they both play?

Yes. But, both video lags. Which version of the exoplayer are we using in the plugins?

**Comment by RenderHeadsSte** [comment]
Oki, so both playing now tells us there is only a single hardware decoder in that device.  Software decoding is going to put a strain on a lower powered device.

You are trying to playback two decent sized videos on a device that appears to have limited capability.  I am afraid it looks like there is little we can do as the problem does not appear to be one with AVPro Video.

FYI: We currently use ExoPlayer v2.8.4

**Comment by levin-Imagin8ors** [comment]
Will try with 'Use Fast OES Path'

**Comment by RenderHeadsSte** [comment]
Anything to report @levin-Imagin8ors ?

**Comment by RenderHeadsSte** [comment]
We will be closing this issue shortly due to lack of activity
