### ISSUE TITLE
AVPRO VIDEO integration with Vimeo SDK

### ISSUE THREAD

**Issue by savek1986** [RenderHeads/UnityPlugin-AVProVideo#337]
Hi,
I need to integrate AVPro Video in Vimeo SDK for adaptive resolution,  but I can't.
Can you help me, please?
![avpro+Vimeo_ error adaptive resolution](https://user-images.githubusercontent.com/6131397/80702101-d0e1fc80-8ae0-11ea-8068-027d94a0db82.jpg)

**Comment by AndrewRH** [comment]
One thing I can tell from the screenshot is that you're running using OpenGL ES emulation... I recommend trying without graphics emulation when running in the editor.

Does that help?

**Comment by savek1986** [comment]
I've tryied, but it's not change. If I use a specific resolution I can hear audio of video but I can't see video, but without errors.
If I use adaptive mode I can't hear audio and I can't see video, but I have this error:
"[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:2093)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1403)"


________________________________
Da: Andrew <notifications@github.com>
Inviato: giovedì 30 aprile 2020 15:39
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


One thing I can tell from the screenshot is that you're running using OpenGL ES emulation... I recommend trying without graphics emulation when running in the editor.

Does that help?

**Comment by AndrewRH** [comment]
Hm that's strange.. well another thing I noticed from the logs is that you're using an old plugin version.  It looks like the script updated, but the native DLL plugin didn't.  This can easily happen if you upgrade after the plugin has run, because then it becomes locked and Unity can't overwrite it.  Try closing Unity, opening Unity and then install the plugin again.  This will at least make sure you're on the latest version...

**Comment by savek1986** [comment]
I've tryied but nothing is Changed

**Comment by AndrewRH** [comment]
Perhaps you could send us over your project so we can replicate the issue and offer a fix?  You can email us files at the Product Technical Support email here: www.renderheads.com/contact/

**Comment by savek1986** [comment]
Hi, I would share my repository with you, can you give me an email of yours to do this? Thank you very much.

**Comment by AndrewRH** [comment]
unitysupport@renderheads.com

**Comment by savek1986** [comment]
ok, thanks
I shared it with you. The scene of the question is "360Player_Vimeo_Touch+Gyro.unity".

**Comment by AndrewRH** [comment]
Hi @savek1986  thanks I have your project.

Do you know if you're using the latest Vimeo SDK?
I couldn't tell which version you have in your project, but it doesn't seem to be the latest one.

They fixed a similar bug to your in the lastest version (0.9.5), so perhaps you could try it?

Thanks,

**Comment by savek1986** [comment]
Hi,
yes, it is.
maybe you could create a new scene in the project to test Vimeo with Avpro.
________________________________
Da: Andrew <notifications@github.com>
Inviato: mercoledì 13 maggio 2020 18:44
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


Hi @savek1986<https://github.com/savek1986> thanks I have your project.

Do you know if you're using the latest Vimeo SDK?
I couldn't tell which version you have in your project, but it doesn't seem to be the latest one.

They fixed a similar bug to your in the lastest version (0.9.5), so perhaps you could try it?

Thanks,

**Comment by AndrewRH** [comment]
I really don't think it's the latest version...because I tried upgrading it and it upgraded and has the fixes that they made for this very issue you're using.

Also I'm not able to test right now as I don't have a Vimeo Pro or Business account...  but I'm pretty sure my suggestion should work.

Thanks,

**Comment by savek1986** [comment]
So, if now I pull repository with your changes, the project will go?
However for testing you are just using my Vimeo business token.
________________________________
Da: Andrew <notifications@github.com>
Inviato: mercoledì 13 maggio 2020 19:04
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


I really don't think it's the latest version...because I tried upgrading it and it upgraded and has the fixes that they made for this very issue you're using.

Also I'm not able to test right now as I don't have a Vimeo Pro or Business account... but I'm pretty sure my suggestion should work.

Thanks,

**Comment by AndrewRH** [comment]
No I have not committed anything to your project.
The tokens are not saved in the project.  I believe they are saved in EditorPrefs so they are local to your machine.

**Comment by savek1986** [comment]
Of it'sure that It Is ok, please commit It. And of you want I don't Have problema ti share with you my token.

Inviato da Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by savek1986** [comment]
If it'sure that It Is ok, please commit It. And if you want, I don't Have problem to share my Vimeo token with you.
Thanks
Inviato da Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by savek1986** [comment]
I have tried to uodate Vimeo SDK but I have an error, you can see in the picture.
Thanks
________________________________
Da: save ve <savek1986@hotmail.it>
Inviato: giovedì 14 maggio 2020 11:58
A: RenderHeads/UnityPlugin-AVProVideo <reply@reply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


If it'sure that It Is ok, please commit It. And if you want, I don't Have problem to share my Vimeo token with you.
Thanks
Inviato da Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by AndrewRH** [comment]
I'm afraid I can't see the picture.  I think it's because you're using email.  Please visit the github issue here and post it directly.   
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/337

**Comment by savek1986** [comment]
![Vimeo updating error](https://user-images.githubusercontent.com/6131397/81950838-be99af80-9604-11ea-8323-71dacb107a5f.PNG)

**Comment by AndrewRH** [comment]
I don't know why you're having the problem.

The fact that it can't find the RenderHeads namespace means that either our plugin has gone missing from your project, or it's being compiled into a different assembly, which the assembly that the Vimeo code is being compiled into doesn't know about. 

All I did to update your project was go to the Vimeo Unity SDK on GitHub and download the latest unitypackage (v0.9.5)
https://github.com/vimeo/vimeo-unity-sdk/releases/download/0.9.5/vimeo-0.9.5.unitypackage

Then I double clicked on the unitypackage while Unity had your project open, and accepted the dialog that asked if I wanted to import it.

I didn't get any error.

Thanks,

**Comment by savek1986** [comment]
Hi,
I have updated Vimeo SDK. Now,  I can hear audio but I can't see video.
________________________________
Da: Andrew <notifications@github.com>
Inviato: giovedì 14 maggio 2020 18:22
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


I don't know why you're having the problem.

The fact that it can't find the RenderHeads namespace means that either our plugin has gone missing from your project, or it's being compiled into a different assembly, which the assembly that the Vimeo code is being compiled into doesn't know about.

All I did to update your project was go to the Vimeo Unity SDK on GitHub and download the latest unitypackage (v0.9.5)
https://github.com/vimeo/vimeo-unity-sdk/releases/download/0.9.5/vimeo-0.9.5.unitypackage

Then I double clicked on the unitypackage while Unity had your project open, and accepted the dialog that asked if I wanted to import it.

I didn't get any error.

Thanks,

**Comment by AndrewRH** [comment]
Ahhh, progress I guess.  Glad that you no longer get the error about failing to load.

Some questions:
1) Is this in the editor that you're not seeing video, or only on build target device?
2) Could you give a bit more details, perhaps a screenshot of what the component is showing, what the previous shows and the console window log?

If you still want to send me your Vimeo KEY and the ID of the video you're trying to stream, then I can try it on this side.  You can send those to our support email unitysupport@renderheads.com

Thanks,

**Comment by savek1986** [comment]
Hi,
My Vimeo token is "97e67a5b3a8c2a41866587e58b1fa857".

I've noticed that to make Adaptive Mode work, I need:

  *   to add Media Player Component on a Sphere object, like in an AVPRO demo scene;
  *   to set "Preferred Video API" attribute to "EXO Player", and get "Use Fast EOS Path" ticked (in Media Player component inspector) ;
  *   to set the Sphere  shader to "AVProVideo-VR-InsideSphere-AndroidOES".

This is the only way to see video, but only on android device, so I need to build app to verify it (in editor mode in Unity doesn't work because it's not supported, but it's not a problem).
So, now I can see video, but video does not fit the sphere (how you can see in screenshots).

In addition, before adding AVPro to my project, I was using Vimeo functions to make video controlling (play, pause, seeking, etc...).
Now, I can't use Vimeo functions because they don't work with AVPro.
So, I use play() and pause() functions in MediaPlayer.cs of AVPro, but in that script there isn't nothing for seeking.

Can you help me please?
Thanks

________________________________
Da: Andrew <notifications@github.com>
Inviato: lunedì 18 maggio 2020 16:24
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


Ahhh, progress I guess. Glad that you no longer get the error about failing to load.

Some questions:

  1.  Is this in the editor that you're not seeing video, or only on build target device?
  2.  Could you give a bit more details, perhaps a screenshot of what the component is showing, what the previous shows and the console window log?

If you still want to send me your Vimeo KEY and the ID of the video you're trying to stream, then I can try it on this side. You can send those to our support email unitysupport@renderheads.com<mailto:unitysupport@renderheads.com>

Thanks,

**Comment by savek1986** [comment]
![Screenshot_2020-05-19-16-46-16-70_abfc8f081802d21a24536c2add664853](https://user-images.githubusercontent.com/6131397/82575145-5d378a80-9b88-11ea-8185-c79ae9e24c27.png)
![Screenshot_2020-05-19-16-45-39-15_abfc8f081802d21a24536c2add664853](https://user-images.githubusercontent.com/6131397/82575147-5f014e00-9b88-11ea-9d81-1d5dbcee0ad1.png)

**Comment by AndrewRH** [comment]
Hmm I'm not sure why your video is appearing stretched like that - could you send us a link/copy of your video, or a snippet of it so we can test and let you know?

For seeking you can use:

if (mediaPlayer.Control != null)
{
mediaPlayer.Control.Seek(timeMilliseconds);
}

Thanks,

**Comment by savek1986** [comment]
Hi,
link of video is https://vimeo.com/239100620 and his id for vimeo component is 239100620.

Thank you very much
________________________________
Da: Andrew <notifications@github.com>
Inviato: venerdì 22 maggio 2020 14:08
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


Hmm I'm not sure why your video is appearing stretched like that - could you send us a link/copy of your video, or a snippet of it so we can test and let you know?

For seeking you can use:

if (mediaPlayer.Control != null)
{
mediaPlayer.Control.Seek(timeMilliseconds);
}

Thanks,

**Comment by AndrewRH** [comment]
Hmm,
In the editor the video should still display, even if you are using the OES shader, because it will fall back to the non-OES shader on non-GLES platforms.   Perhaps try to restart Unity and see if it is able to display in editor then.  I'm not seeing any of the strange stretching you get.  Here it running for me:
![image](https://user-images.githubusercontent.com/5418126/82684257-30e44280-9c4a-11ea-8c17-d27fdbf1a459.png)

**Comment by savek1986** [comment]
Ok, now it works.
Thank you very much.

I have some questions for you:

  *   what is the maximum resolution in adaptive mode?
  *   how can I create a drop down menu to select the resolution that I prefer?
  *   In which script can I find the seek function, that you told me, to attach to my slider?

Thank you so much!
________________________________
Da: Andrew <notifications@github.com>
Inviato: venerdì 22 maggio 2020 17:36
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


Hmm,
In the editor the video should still display, even if you are using the OES shader, because it will fall back to the non-OES shader on non-GLES platforms. Perhaps try to restart Unity and see if it is able to display in editor then. I'm not seeing any of the strange stretching you get. Here it running for me:
[image]<https://user-images.githubusercontent.com/5418126/82684257-30e44280-9c4a-11ea-8c17-d27fdbf1a459.png>

**Comment by AndrewRH** [comment]
Glad it's working!

Maximum resolution - it should support up to 8192x8192 - but that requires having hardware capable to decode that, and also use of H.265 codec.  Also I have no idea about whether Vimeo supports that.  But our player can do up to 8K itself, or 16K when using a codec like Hap (but that's very special case).

We don't currently have any support for locking to a specific resolution.  The closest we have is using a specific HLS manifest, but Vimeo uses MPEG-DASH so that wouldn't help.  We will be adding support for resolution selecting in the next major release of our plugin, some time later this year.

The seek function - you can find it in Interfaces.cs

Since your issue is resolved now, can I close this issue thread?

Thanks,

**Comment by savek1986** [comment]
OK,
Thank you very much for all.
________________________________
Da: Andrew <notifications@github.com>
Inviato: venerdì 22 maggio 2020 19:55
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (#337)


Glad it's working!

Maximum resolution - it should support up to 8192x8192 - but that requires having hardware capable to decode that, and also use of H.265 codec. Also I have no idea about whether Vimeo supports that. But our player can do up to 8K itself, or 16K when using a codec like Hap (but that's very special case).

We don't currently have any support for locking to a specific resolution. The closest we have is using a specific HLS manifest, but Vimeo uses MPEG-DASH so that wouldn't help. We will be adding support for resolution selecting in the next major release of our plugin, some time later this year.

The seek function - you can find it in Interfaces.cs

Since your issue is resolved now, can I close this issue thread?

Thanks,

**Comment by savek1986** [comment]
Hi,
I'm adding adaptive functionality to iOS version of my app.
I just have updated Vimeo SDK and AVPRO, but when I select "adaptive", there isn't possibility to choose between Vimeo Player and AVPro Player.
Can you help me, please?
Thanks
![IOS](https://user-images.githubusercontent.com/6131397/83146560-ca9e6a80-a0f6-11ea-9b64-19a50b85d549.PNG)
