### ISSUE TITLE
HLS Multi-angle

### ISSUE THREAD

**Issue by biomcanic** [RenderHeads/UnityPlugin-AVProVideo#338]
Hello,

I'd like to know if AVProVideo supports HLS multi-angle and has the feature of changing the angle by custom scripting in Unity.

Thank you very much in advance.

**Comment by RenderHeadsSte** [comment]
I am afraid this is a feature of HLS that is not supported on any platform.

**Comment by biomcanic** [comment]
Thank you very much for the information.

Regards!
