### ISSUE TITLE
Gibberish Korean subtitle

### ISSUE THREAD

**Issue by SonGit** [RenderHeads/UnityPlugin-AVProVideo#34]
**Describe the bug**
- Go to demo subtitle scene (11_Demo_Subtitles.unity)
- Load a korean SRT subtitle file
- Subtitle text sometimes show correct korean words, the rest are gibberish texts.

**Setup:**
 - Unity version: 2018.3.5f1
 - AVPro Video version: 1.9.12
 - Operating system version: Android

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8287748/55050688-9d82a200-5084-11e9-9630-6c8f1a918b34.PNG)

**Subtitle file**
[KOR.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3011489/KOR.zip)

Any help is greatly appreciated. Opening the file via Microsoft Word is fine, texts are correctly shown . I have tried using various Korean font, setting font import setting in Unity to Dynamic/Unicode - no dice.

**Comment by AndrewRH** [comment]
I've had a look into this.  Doesn't seem to be Android specific - I get the same thing in the Unity editor.  The SRT file itself seems a bit funky..  Many editors can't understand what encoding it is, but some can.  I tried a bunch of things but couldn't get it to make sense.  I suspect that the encoding is either a type that Unity's .Net (Mono) library doesn't support fully, or that the file is missing the correct encoding markers and it's only luck/cleverness that other editors are able to read it.

**Comment by AndrewRH** [comment]
I'm closing this as it doesn't seem to a bug on our side - more an issue with the data.  If you still want to pursue this please reopen the ticket.  Thanks,
