### ISSUE TITLE
AndroidJavaException when using AVPro and Vuplex

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#340]
I'm trying to use Vuplex together with AVPro (same as issue #306 ) but am running into an error when removing the exoplayer2 JAR files and setting the Preferred Video API to 'Media Player'. 
Building the app goes fine, but the following runtime error occurs in the app in Android (Oculus Go): 

```
AndroidJavaException: java.lang.VerifyError: Verifier rejected class com.RenderHeads.AVProVideo.AVProMobileVideo: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean) failed to verify: 
com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean): [0x2F] cannot access instance field boolean com.RenderHeads.AVProVideo.AVProVideoPlayer.m_bShowPosterFrame from object of type Unresolved Reference: 
com.RenderHeads.AVProVideo.AVProVideoExoPlayer (declaration of 'com.RenderHeads.AVProVideo.AVProMobileVideo' appears in /data/app/com.companyname.applicationname-2/base.apk)
```

Any ideas on how to fix this?

Unity version: 2018.4.22f1
AVPro Video version: 1.10.1 (scripts v1.10.3)
Operating system version: Android
Device model: Oculus Go
Video specs (resolution, frame-rate, codec, file size): N/A
Note: Vuplex uses geckoview-nightly-71.0.20191003093956.aar which conflicts with the exoplayer2 JAR files.

**To Reproduce**
1. Start a new project in Unity
2. Import Vuplex and AVPro packages
3. Remove exoplayer2*.jar files from Assets/Plugins/Android
4. Build and run an Android app with scene '07_Demo_mapping3D'

**Logs**
```
Stacktrace:
java.lang.Class.classForName(Native Method)
java.lang.Class.forName(Class.java:400)
java.lang.Class.forName(Class.java:326)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source)
com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
android.os.MessageQueue.next(MessageQueue.java:392)
android.os.Looper.loop(Looper.java:136)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._CallStatic[ReturnType] (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.AndroidMediaPlayer.InitialisePlatform () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.CreatePlatformMediaPlayer () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at <00000000000000000000000000000000>:0)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at <00000000000000000000000000000000>:0)

```

**Comment by RenderHeadsSte** [comment]
The variable m_bShowPosterFrame is only accessed in common code when you are creating a player of ExoPlayer type.  Can you post up your logcat filtered to 'AVPro' please?

**Comment by RuudvanReenen** [comment]
Filtering on AVPro doesn't show any results, I'm using: adb logcat AVPro:V *:S
AVPro logging is not disabled. The AndroidJavaException is only showing when filtering to 'Unity'.

**Comment by RuudvanReenen** [comment]
Note that in AndroidMediaPlayer.cs for SetOptions a comment mentions: 
 // Show poster frame is only needed when using the MediaPlayer API
and it only allows showPosterFrame to be true if the MediaPlayer is used, but seems to be accessed in both cases.

**Comment by AndrewRH** [comment]
@RuudvanReenen do you know which Android SDK version you're compiling with, and Android Studio version if you're using that?
Is it possible to send us your project for debugging?  (to the product enquiries support email at www.renderheads.com/contact)

Thanks,

**Comment by RuudvanReenen** [comment]
@AndrewRH I'm not using Android Studio, building for minimum API Level 21 and target level 27.
I've sent a test project with WeTransfer to the product enquiries support email.

**Comment by RuudvanReenen** [comment]
@AndrewRH Happy to let you know that Nate Hill from Vuplex has been able to fix the clash between the exoplayer of Vuplex WebView and AVPro Video by removing the exoplayer classes from the AAR file included with WebView. Now the two plugins can coexist perfectly, Thanks for your efforts looking into this!

**Comment by AndrewRH** [comment]
That's great!  Glad you found a solution!
@RenderHeadsSte feel free to close this ticket if you don't need to do anything else.
