### ISSUE TITLE
Video become red

### ISSUE THREAD

**Issue by caihuazei2012** [RenderHeads/UnityPlugin-AVProVideo#341]
**Describe the bug**
PC is normale ,but Iphone turn red

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.2
 - AVPro Video version: 1.10.0
 - Operating system version: windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your vi
![20200505_IMG_0227](https://user-images.githubusercontent.com/63900825/81030316-014be100-8ebb-11ea-8aae-c3ad69fe6173.png)
deo or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by caihuazei2012** [comment]
I use NGUI 
![1588664835(1)](https://user-images.githubusercontent.com/63900825/81044926-c613d700-8ee7-11ea-8d92-309b8fd58297.png)

**Comment by AndrewRH** [comment]
Hi,

NGUI isn't aware of the format we use to store iOS/macOS textures by default.  You can fix this by simple unchecking the option "Use YpCbCr" in the MediaPlayer component, in the "Platform Specific" section.

Does this help?

**Comment by caihuazei2012** [comment]
resolve    thanks！

**Comment by umresh** [comment]
Hi, I'm using the Extract frame demo scene from the AVPro video player on IOS(iPhone 6 and iPhone X) with unity 2019.4.13. All the extracted textures are red in color.
Screenshot : [https://pasteboard.co/JyNh2kF.jpg](url)
