### ISSUE TITLE
Play any 360 8K video

### ISSUE THREAD

**Issue by sunilsingha** [RenderHeads/UnityPlugin-AVProVideo#344]
**Is your feature request related to a problem? Please describe.**
Some 360 videos when played looks **weird**.

**Describe the solution you'd like**
we have a requirement to play any 360 video in VR preferably 8K videos. 
Basically the videos will be projected in sphere and video content will be visible from inside.
To start with we are using videos from kandaovr, there are some videos which are working and there are other videos which are not working.

https://onedrive.live.com/?authkey=%21AA4AG8DEzBHdjP8&id=3B28AF740261022E%2119103&cid=3B28AF740261022E

this video has top and bottom duplicated, which when played doesn't look like a 360 video.
Could you guide me here...
![Image](https://dirigiblea9820668f.hana.ondemand.com/services/js/docs_explorer/read/document/preview?path=/Test%20folder/360%20not%20working%20video.png)

**Comment by AndrewRH** [comment]
This is a stereo video, where the top half is the left  eye, and the bottom half is the right eye.  
If you want this to display correctly you should set the StereoPacking mode to TopBottom in the MediaPlayer > Visual section

I hope that solves your issue?

**Comment by sunilsingha** [comment]
> This is a stereo video, where the top half is the left eye, and the bottom half is the right eye.
> If you want this to display correctly you should set the StereoPacking mode to TopBottom in the MediaPlayer > Visual section
> 
> I hope that solves your issue?

Thanks will check it and also will it work for 360 Image?
