### ISSUE TITLE
Help please!         Why does the looped video still freeze after the first playback

### ISSUE THREAD

**Issue by caihuazei2012** [RenderHeads/UnityPlugin-AVProVideo#345]
**Describe the bug**
I use URL to play video,and check the loop setting.
The looped video plays stuttering for the first time, but stutters for the second time, as if it was still re-downloaded for the second time.
It is always stuck.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.2
 - AVPro Video version: 1.10.0
 - Operating system version: iphone 11
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
http://ydlinglong.the3.changyou.com/0/login.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by caihuazei2012** [comment]
My ios
![微信图片编辑_20200506202448](https://user-images.githubusercontent.com/63900825/81176520-d4d9b700-8fd7-11ea-8130-e81a990c5e36.jpg)
 setting

**Comment by MorrisRH** [comment]
I just tried the URL you provided in our Background demo scene and there was no noticeable stutter. That being said, looping isn't seamless on iOS and I expect adverse network conditions will make things worse. For best results you should bundle the movie with the application.

**Comment by caihuazei2012** [comment]
> I just tried the URL you provided in our Background demo scene and there was no noticeable stutter. That being said, looping isn't seamless on iOS and I expect adverse network conditions will make things worse. For best results you should bundle the movie with the application.

After the first playback, is it already downloaded, why is it still stuck for the second time?

**Comment by caihuazei2012** [comment]
> > I just tried the URL you provided in our Background demo scene and there was no noticeable stutter. That being said, looping isn't seamless on iOS and I expect adverse network conditions will make things worse. For best results you should bundle the movie with the application.
> 
> After the first playback, is it already downloaded, why is it still stuck for the second time?

Stuck for the third and fourth time.........

**Comment by caihuazei2012** [comment]
> 我只是尝试了您在背景演示场景中提供的URL，并且没有明显的卡顿现象。话虽这么说，iOS上的循环并不是无缝的，我预计不利的网络状况会使情况变得更糟。为了获得最佳效果，您应该将影片与应用程序捆绑在一起。

My need is to download ， not be bundled

**Comment by MorrisRH** [comment]
We don't download the movie, only as much as is required for smooth playback is buffered by iOS. When the movie loops iOS begins buffering from the start.

**Comment by caihuazei2012** [comment]
> When the movie loops iOS begins buffering from the start.

Meaning that the looped video is always buffered？？

**Comment by MorrisRH** [comment]
No, only as much as is needed to maintain smooth playback. This is dependent on many factors (memory constraints, network bandwidth, etc.) and not something we can control.

However, if you switch to using HLS instead of the mp4 then your experience will be much better. A quick test here using your video over HLS yielded looping playback that didn't need to reload the video.

I used mediafilesegmenter from Apple's HLS tools (available [here](https://download.developer.apple.com/QuickTime/http_live_streaming_tools/HTTPLiveStreamingTools417.2.dmg)) to create the HLS files.
