### ISSUE TITLE
Unity Editor crash on attempting to call OpenVideoFromFile on existing MediaPlayer

### ISSUE THREAD

**Issue by sebjf** [RenderHeads/UnityPlugin-AVProVideo#346]
**Describe the bug**
I am trying to control a MediaPlayer from a Unity Playable (Unity Timeline behaviour). The Timeline starts, stops and seeks the MediaPlayer on various events, and can also change the file being played.
In Play Mode and on Android the videos change without issue, but on selecting a new Timeline (which invokes a video change) in the Editor the Editor crashes to desktop.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.10f1
 - AVPro Video version: 1.10.3
 - Operating system version:  Windows 10.0.18363 Build 18363
 - Device model: -
 - Video specs (resolution, frame-rate, codec, file size): 5760x2880, 29.9, H264, 267 Mb

**Screenshots**
The first screenshot below shows the stack trace for a *working* invocation, along with the code that changes the video and the line of my code at which the crash occurs.
The second screenshot shows the stack trace of a failed call (it is taken with the debugger stopped at the same line as in the previous screenshot - trying to step over that line will cause the crash).
As can be seen the calls come from the main thread.
![image](https://user-images.githubusercontent.com/5058369/81207999-59233e80-8fc6-11ea-9d23-76ae4e22983f.png)
![image](https://user-images.githubusercontent.com/5058369/81208200-9687cc00-8fc6-11ea-8aa1-6f3547b3b8ed.png)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

Thanks for reporting the issue.  I've tried to replicate it (using 5K videos, creating Playable behaviour and asset etc), but it's working fine in my test and I can't get it to crash or leak memory...

One thing that's worth noting is that the MediaPlayer component isn't designed to load/play videos while the application isn't in Play mode, so I would recommend wrapping all of your method calls with:
if (Application.isPlaying)
{
}

This should prevent behaviour we have not tested for.

Another potential issue is that your video is 5K H.264.  As far as I know there are no hardware decoders available in Windows for this configuration, so it will be decoded on the CPU.  5K H.265 is more common, with 4K being the typical limit for H.264 on Windows (hardware decoding of > 4K H.265 on Windows requires an NVidia 10xx GPU or higher.  Can you play the video with AVPro Video generally fine outside of the timeline?

Although I wasn't able to replicate your crash bug, I wonder if it's related to other components in your scene that you're using to display the video.  I mean things like DisplayIMGUI, DisplayUGUI, ApplyToMesh, ApplyToMaterial etc.  Are you using any of these?

Does that helps at all?  If not, perhaps you could comment further and give answers to the above questions.  Until we've able to replicate the crash it's really difficult to know what the cause could be.

Thanks,

**Comment by sebjf** [comment]
Hi Andrew,

The video plays OK on my 1080, both inside the Editor in Play Mode and in external media players. 

Also, on re-reading I realise I wasn't very clear in what I wrote: I only try this interaction in Play Mode. That is, I hit Play, then open the Timeline Editor GUI, which prompts a video change (and crash). However, I can interact in Play Mode using the in-world GUI via the Game window, and everything works OK. So it is only when the calls come via the Timeline. From the stack trace this appears to go through some IMGUI functionality.

I don't see how the calling function could make such a difference (I thought it may be coming from a separate thread but I checked that), unless a caller is relying on some object not changing.

I will implement a message queue to be polled in Update, to see if that functions as a workaround.

**Comment by sebjf** [comment]
Hi, I have modified my code so that a single Update method executes all necessary starts, stops and seeks and it works. I am happy enough with this solution. (Please close if you consider this sorted, but if you want my Playables code that cause the issue I can look into sending it as well.)

**Comment by AndrewRH** [comment]
Glad you solved it :) Yes please, we're always interested in fixing issues, especially crashes.  If you could email it to unitysupport@renderheads.com and mention that it's for AndrewRH that would be great :)

I will close this issue soon once I have tested your code.

Cheers,
