### ISSUE TITLE
Help！Why NGUI Color distortion

### ISSUE THREAD

**Issue by caihuazei2012** [RenderHeads/UnityPlugin-AVProVideo#348]
**Describe the bug**
Linnear Space, which is also used, uses unity's videoplayer, and the video color is the same. After importing the plugin, it becomes white in NGUI
Supplement: I use NGUI.
**Your Setup (please complete the following information):**
 - Unity version: 2018.4.2
 - AVPro Video version: 1.10.0
 - Operating system version: android 8.0
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
On the left is the effect of using videoplayer or AV Display UGUI, on the right is the effect of the Apply To Texture Widget NGUI
![企业微信截图_15888186204116](https://user-images.githubusercontent.com/63900825/81273890-20489f80-9082-11ea-9368-94f71cab436f.png)

This is android setting
![企业微信截图_15888402954170](https://user-images.githubusercontent.com/63900825/81272673-5e44c400-9080-11ea-8ef5-0f1621fa9f92.png)

![企业微信截图_15888413742407](https://user-images.githubusercontent.com/63900825/81274436-d9a77500-9082-11ea-82fb-fd4cc9e4f4d8.png)

left is NGUI ,right is UGUI

![480609fa2a963f3be11183939f0f17d](https://user-images.githubusercontent.com/63900825/81275830-c9909500-9084-11ea-9149-4fd8e3070639.jpg)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by DragontaleStudio** [comment]
Hello all,

We are having the same issue (color distortion), using UGUI on android builds.

Image ios vs android

![Screenshot_20200511-133557](https://user-images.githubusercontent.com/10207892/81553653-272b2700-938e-11ea-92e2-6f8161451166.png)

**Comment by AndrewRH** [comment]
Hi DragontaleStudio, it's actually a different but similar issue.  Please provide us with which version of Unity and AVPro Video you're using.  We did fix UGUI recently for Linear mode, so it's best if you're on the latest version of the plugin (1.10.3 now, and 1.11.0 later today).

Thanks,

**Comment by DragontaleStudio** [comment]
Hello @AndrewRH. Thanks for your prompt answer. We are using unity 2019.3.9f1 and avpro version 1.10.3 (full ios, not trial)

**Comment by AndrewRH** [comment]
Thanks @DragontaleStudio we're investigating....

**Comment by AndrewRH** [comment]
Both of these issues are caused by the Unity colorspace setting being set to Linear.  If you set to Gamma then the problem will resolve.   This isn't the ideal solution though, because it's meant to work in both, so we're looking into it.

**Comment by DragontaleStudio** [comment]
Thanks @AndrewRH. We changed colorspace to gamma for the time being. Please let us know once the issue is resolved.

**Comment by AndrewRH** [comment]
@RenderHeadsSte I think we may just have an #ifdef wrong or something - perhaps you could take a look?   DisplayUGUI should support displaying content when Unity is in Linear colourspace correctly....If it detects the platform can't do it natively, then it uses the shader to do the conversion...

**Comment by RenderHeadsSte** [comment]
@DragontaleStudio Can I ask if you are using the 'Fast OES' option?

**Comment by DragontaleStudio** [comment]
@AndrewRH  we will check it and let you know.
@RenderHeadsSte I suppose it is the "Use Fast OES path" on android settings. No we don't have it enabled.

**Comment by AndrewRH** [comment]
Oh if you're using your own material, then that's the cause...
We have our own shaders to handle things like gamma/linear etc when displaying using UGUI, but if you override the material/shader on the component, then our shader will not be used.   Is there no way you could achieve the same mask effect but using another UGUI component placed at a higher layer?

**Comment by DragontaleStudio** [comment]
Hey @AndrewRH. I suppose iOS doesn't have same issue cause it is doing it natively? Is that correct? We will try to use AVpro shader and mask component at a higher level as suggested and let you know.

**Comment by caihuazei2012** [comment]
I use pow(color,2.2) resolve this
