### ISSUE TITLE
HLS Streaming Resolution Starts at lowest on Android, IOS AVPRO

### ISSUE THREAD

**Issue by saulpena** [RenderHeads/UnityPlugin-AVProVideo#35]
**Describe the bug**
We are currently working on an application that uses Unity and AVPRO. Specifically we have HLS Streams that we are viewing using AVPRO. We have our HLS master file set up to handle different resolutions and bandwidth, and AVPRO is able to switch between them. The problem we are running into is that AVPRO always starts with the lowest resolution possible regardless of the connection of the user and it takes about 10 seconds into the video before it starts increasing. When we load a new video the process starts all over again, and it starts at the lowest resolution for a while before updating.  As a result, our client's app always shows an unclear video until it slowly steps up to an appropriate resolution.  As you can imagine the client is unwilling to accept that, which is delaying our ability to launch.

We tried changing the order of the #EXT-X-STREAM-INF lines in the metadata as we are unsure in what order they are processed.  We also tried specifying different values for #EXT-X-VERSION.

We have been looking inside the code, on forums, and the documentation, but we have not found a solution. Is there a way to indicate AVPRO which resolution to start with and if there is not, could we have it remember what was the last resolution used so it doesn't have to start from scratch every time.

**Your Setup (please complete the following information):**
 - Unity version: 2018.2.0f1
 - AVPro Video version: 1.9.12
 - Operating system version: Multiple Android OS
 - Device model: Multiple Android devices
 - Video specs (resolution, frame-rate, codec, file size): HLS Stream

We have seen this response in a forum: https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-59#post-3938638

It says that the problem does not occur in Android, but we are currently facing the same issues on Android devices.

**Comment by petermauger** [comment]
We're having difficulty even playing an HLS encoded video on our Android devices... Any chance you could share your encoding parameters so we can try them out? We're using ffmpeg on an MP4

**Comment by RemyRM** [comment]
Hi, OP of the question/answer you linked here.

> We tried changing the order of the #EXT-X-STREAM-INF lines in the metadata as we are unsure in what order they are processed.

 According to the HLS specification by apple it should honour the order that is specified in the main .m3u8 file. That is the first in the list of #EXT-X-STREAM-INF streams is taken as the "default". Not every (expecially older) mediaplayers honour this though. 

What is the "Preferred video API" you're using on AVPro under the Android tab? On Exo player this rule gets honoured for me across all Android devices i've tested.  Mediaplayer however seems to not always do it as well though, and may default to a lower stream instead.

> about 10 seconds into the video before it starts increasing

How long are your segments, and how often are your keyframes? shorter segments and more keyframes will help it bump up faster,

Hope my two cents on this helps you.

**Comment by holah-reiken** [comment]
Thank you RemyRM. We are using Exo player, and it still seems to always start with the lowest resolution regardless of the order in the file, but we will test again. We will also look at breaking into smaller segments.
IMPORTANT: Is this support group also monitored by Renderheads.  We've not seen a reply from them to this thread or to our similar email, and this resolution issue is really becoming a problem for us with one of our important clients.

**Comment by RemyRM** [comment]
Yes this is monitored by Renderheads (atleast by Andrew). However there hasn't been any activity from him all week here or on the forum, maybe he is on vacation or something, I don't know.

**Comment by AndrewRH** [comment]
I understand the issue you're having and why it is not desirable.

This behaviour of starting with the lowest resolution and working up to a higher resolution has always been how our plugin works.  We rely on the methods used by the operating system level decoders so we don't have any control over this.

I have heard from some sources that on Apple platforms you can try to change the order of the entries in the HLS manifest, and that it will start with the first entry in the file.  I'm not sure if this is true or not.

Another option would be to parse the HLS manifest (using our StreamParser component) and play the specific quality stream that you think the user requires, or give them the option to do this.

We are working on a new version of the plugin which does give you control over the stream/bandwidth selection, but this won't be released for a few months still.

**Comment by Schoenhofer-Humain** [comment]
Any news on the tream/bandwidth selection feature? Couldn't find anything in the docs.

**Comment by AndrewRH** [comment]
Yes this is a new feature we're currently working to add to the next beta version 2.0

Thanks,

**Comment by AndrewRH** [comment]
There is now an option to start using the highest resolution on Windows and Android in AVPro Video 2.0 which will be released soon.  We will have similar support on Apple platforms soon after that.

**Comment by nirniron** [comment]
hello Renderhead
is there any update regarding this issue?
does AVPro2 already has control over the default streaming quality

**Comment by AndrewRH** [comment]
On Android we have the option 'startWithHighestBitrate' which will start using the highest bitrate.
On Apple platforms the default stream selection is based on Apple's spec which is [documented](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices).

It's best to use the Apple tools for validating your HLS manifest.

Closing this issue.

**Comment by nirniron** [comment]
Hello, is there a solution that also works with WebGL? or should it be the
same?
