### ISSUE TITLE
Crashed on iPhone 6s iOS 9

### ISSUE THREAD

**Issue by tifish** [RenderHeads/UnityPlugin-AVProVideo#350]
**Describe the bug**
Crashed on iPhone 6s iOS 9 when playing video.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.0f2
 - AVPro Video version: 1.10.3
 - Operating system version: iOS 9
 - Device model: iPhone 6s
 - Video specs (resolution, frame-rate, codec, file size): 720P, H.264

**To Reproduce**
1. Play any video.
2. Crashed...

**Logs**
<Error>: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AVPlayer setAutomaticallyWaitsToMinimizeStalling:]: unrecognized selector sent to instance 0x122b60440'

**Comment by MorrisRH** [comment]
Thanks for this. A fix will be available with the next release.
