### ISSUE TITLE
Media player slows down the whole project if playing 4K video

### ISSUE THREAD

**Issue by zcseri** [RenderHeads/UnityPlugin-AVProVideo#351]
Playing 4K videos (4096x2048) in WebGL causes the application to drop FPS over time and becomes unplayable in Google Chrome. The memory leak only occurs if we play 4K video, for Full HD (1920x1080) it works like a charm, it seems like, it just gives up at that high resolution.  In the Unity Editor and Firefox  it works fine, I think it is something with the WebGL build. 

In Firefox everything works smoothly. The video is placed within Streaming Asset folder and directly referenced.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.20f1
 - AVPro Video version: 1.10.3
 - Operating system version: Windows 10 64bit
 - Device model: Chrome Version: 81.0.4044.138 (64-bit)
 - Video specs (resolution, frame-rate, codec, file size):  4096x2048, 30 fps, H.264, MP4, 8 sec length, 30 MB

**To Reproduce**
1. Open example scenes (08_Demo_360SphereVideo) from AVPro Video. 
2. Place a 4K video in the StreamingAsset folder
3. Add the 4K video to the MediaPlayer component
4. Build and run Unity project for WebGL
5. Observe that the project slows down overtime

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

I'm afraid there isn't much we can do about WebGL performance.  We're already doing the minimal amount of processing on the video (basically a single blit).  WebGL is very high level, so there is not much chance to optimise the playback.

You should just check that hardware decoding is being used (check via the Task Manager > Performance > GPU tab in Windows).  Depending on your GPU hardware, the higher resolution videos may not may not use GPU decoding.   Also switching to H.265 can help in some cases.

It could also just be a bug in Chrome, as we're not doing anything different per-browser.  Perhaps you could test on some older versions of Chrome?

You could also try making WebGL 1.0 and 2.0 builds to see whether that makes any difference.

Thanks,
