### ISSUE TITLE
Unable to play URL streams on Android

### ISSUE THREAD

**Issue by cheesemichael** [RenderHeads/UnityPlugin-AVProVideo#352]
Nothing is loading from online URLs on Android.  It runs in the Unity Editor though.  Even the sample url in the demo.  It wont load on android. Get black screen. 

Did i miss something.?

**Comment by AmitBagadaV** [comment]
i am facing same issue getting error like Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources
avpro version : 1.11.0 
unity version 2019.3.1
android device : android 10 
url : http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4

**Comment by cheesemichael** [comment]
tried new trial version.  still the same.  Streaming video loads in editor but not in Android

**Comment by AndrewRH** [comment]
Hi @cheesemichael ,
Could you give more information such as:
1) Unity version
2) AVPro Video version
3) Android version
4) The ADB cat log showing error messages from the OS during loading time

Did you enable the internet permission option in your Android app (in Unity Player Settings)?

Thanks,

**Comment by AmitBagadaV** [comment]
1.unity version : 2019.3.13f1
2.Avpro version : 1.11.0
3. Android Version : 10.3.2 
4. ADB cat logs as follow:
05-13 19:07:51.622 31553 31583 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 7477mb
05-13 19:07:51.622 31553 31583 I Unity   : SystemInfo ARM big.LITTLE configuration: 1 big (mask: 0x80), 7 little (mask: 0x7f)
05-13 19:07:51.623 31553 31583 I Unity   : ApplicationInfo com.av.pro version 1.0 build e9c4e75a-f9d2-48bc-912e-f6eb56633cd2
05-13 19:07:51.623 31553 31583 I Unity   : Built from '2019.3/release' branch, Version '2019.3.13f1 (d4ddf0d95db9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
05-13 19:07:51.663 31553 31583 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
05-13 19:07:51.663 31553 31583 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
05-13 19:07:51.663 31553 31583 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather
05-13 19:07:53.802 31553 31583 I Unity   : [AVProVideo] Creating player 0
05-13 19:07:53.802 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.AndroidMediaPlayer:.ctor(Boolean, Boolean, VideoApi, Boolean, Audio360ChannelMode, Boolean)
05-13 19:07:53.802 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:CreatePlatformMediaPlayer()
05-13 19:07:53.802 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
05-13 19:07:53.802 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Start()
05-13 19:07:53.802 31553 31583 I Unity   :  
05-13 19:07:53.802 31553 31583 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
05-13 19:07:53.802 31553 31583 I Unity   : 
05-13 19:07:53.805 31553 31583 I Unity   : [AVProVideo] Initialising AVPro Video (script v1.11.0 plugin v1.10.2t) on Adreno (TM) 640/OpenGL ES 3.2 V@408.0 (GIT@bc92c36, I9e73322269, 1567026228) (Date:08/28/19) (MT True) on Android Android OS 10 / API-29 (QKQ1.190716.003/2003271900)
05-13 19:07:53.805 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
05-13 19:07:53.805 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Start()
05-13 19:07:53.805 31553 31583 I Unity   :  
05-13 19:07:53.805 31553 31583 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
05-13 19:07:53.805 31553 31583 I Unity   : 
05-13 19:07:53.806 31553 31583 I Unity   : [AVProVideo] Opening http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4 (offset 0) with API ExoPlayer
05-13 19:07:53.806 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile()
05-13 19:07:53.806 31553 31583 I Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Start()
05-13 19:07:53.806 31553 31583 I Unity   :  
05-13 19:07:53.806 31553 31583 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
05-13 19:07:53.806 31553 31583 I Unity   : 
05-13 19:07:56.878 31553 31583 E Unity   : [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
05-13 19:07:56.878 31553 31583 E Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
05-13 19:07:56.878 31553 31583 E Unity   : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
05-13 19:07:56.878 31553 31583 E Unity   :  
05-13 19:07:56.878 31553 31583 E Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
05-13 19:07:56.878 31553 31583 E Unity   : 
Thanks

**Comment by AndrewRH** [comment]
Hi, we will need the complete log so we can see what's happening on the system - not just the Unity events.

And can you confirm that you have enabled the internet permission option in your Android app (in Unity Player Settings)?

Thanks,

**Comment by AmitBagadaV** [comment]
yes we have set internet permission require in player settings.

**Comment by AndrewRH** [comment]
@AmitBagadaV  thanks, and if you try changing the Video API from ExoPlayer to MediaPlayer, does that make any difference?   (in MediaPlayer component, under Platform Specific > Android)

And do send the full log if you can :)

**Comment by AmitBagadaV** [comment]
Hello,
Thanks for your reply
here is the link for complete log file : https://www.dropbox.com/s/bk13ym3idozv778/logs.txt?dl=0
And yes i have tried with Mediaplayer but it is not working.

**Comment by AndrewRH** [comment]
Hi,

Thanks for sending the log over - very useful.  I see the error message.
I believe the problem is due to Android security.  Have a look at this article about this:
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

One of those suggestions (either using HTTPS or adding that permission into the manifest) should solve your problem.

Does that help?

**Comment by AndrewRH** [comment]
@cheesemichael  I haven't heard any details from you, but perhaps you have the same issue as @AmitBagadaV  and that solution will work for you too?

Please let me know.

Thanks,

**Comment by cheesemichael** [comment]
hi,

its the same issue.. and i fixed it  thanks so much…  either using https

Best Regards,

Michael Chan

**Comment by shounak00** [comment]
how did you use https?

**Comment by charanjeet1997** [comment]
> Hello,
> Thanks for your reply
> here is the link for complete log file : https://www.dropbox.com/s/bk13ym3idozv778/logs.txt?dl=0
> And yes i have tried with Mediaplayer but it is not working.

https://www.dropbox.com/s/bk13ym3idozv778/logs.txt?dl=1
set dl from 0 to 1
