### ISSUE TITLE
EXOPlayer seems to buffer the whole video into memory when download a video

### ISSUE THREAD

**Issue by zhwongbo** [RenderHeads/UnityPlugin-AVProVideo#353]
**Describe the bug**
When playing the same video the memory is much bigger using EXOPlayer than using MediaPlayer

videoPath:/storage/emulated/0/Android/data/com.baiao.avpro/files/AVProVideoSamples/BigBuckBunny_720p30.mp4

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.26f1
 - AVPro Video version:  plugin v1.10.1 scripts v1.10.2
 - Operating system version: Android8.0
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Add Demo Scene 03_Demo_VideoControl to In build Scene
2. Build apk and run
3. Check memory in AndroidStudio Proflier

**Screenshots**
using Exoplayer
![image](https://user-images.githubusercontent.com/8254709/81817039-aff8bd00-955e-11ea-8f38-4f7377d1d461.png)

using MediaPlayer
![image](https://user-images.githubusercontent.com/8254709/81815509-a4a49200-955c-11ea-963a-d07277599838.png)

**Videos**
BigBuckBunny_720p30.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

Thank for you providing so many details.

Video playback is a resource intensive operation.  ExoPlayer is probably just allocation extra buffers to help we decoding.   MediaPlayer implementations might actually differ on different devices too as they are part of the OS.  MediaPlayer may also be allocation memory elsewhere (like on the GPU) instead, so perhaps the whole picture is not clear from the profiler?

I see in the screenshot you're on CreateFloatBuffer....I don't think that allocated much memory - it should only be allocation maximum 16 floats for a matrix....

25MB allocations for a 720p video playback doesn't seem unreasonable to me.

Is this causing a problem for you?  

You're not seeing a memory leak I assume?

**Comment by zhwongbo** [comment]
> Hi,
> 
> Thank for you providing so many details.
> 
> Video playback is a resource intensive operation. ExoPlayer is probably just allocation extra buffers to help we decoding. MediaPlayer implementations might actually differ on different devices too as they are part of the OS. MediaPlayer may also be allocation memory elsewhere (like on the GPU) instead, so perhaps the whole picture is not clear from the profiler?
> 
> I see in the screenshot you're on CreateFloatBuffer....I don't think that allocated much memory - it should only be allocation maximum 16 floats for a matrix....
> 
> 25MB allocations for a 720p video playback doesn't seem unreasonable to me.
> 
> Is this causing a problem for you?
> 
> You're not seeing a memory leak I assume?

Hi,
Thank for your reply.
It's definitely not a memory leak.
But Compare the two screenshots,the only difference is Java,Is that mean ExoPlayer requires 20 MB more ram than MediaPlayer?
The video which I playback is only 6M.but 25M is allocated to playback,Is this really normal?
I always thought video was streaming, Am I wrong??

**Comment by AndrewRH** [comment]
The video decoder has to allocation buffers for the decoding process.   So for example a 720p video RGBA buffer is 1280*720*4 = 3.6MB   Ususally it has to allocate at least 2 of these for double buffering, but some implementations might allocate more.  Then there the buffers for the reference frames used for decoding.  So you see all of these add up.  It's not the actual video file that's loaded into memory, but buffers set up to decode it.

ExoPlayer is probably just allocating more buffers for some reason.  It's an interesting find.  

I hope that helps explain?

**Comment by zhwongbo** [comment]
Hi,
I have understood what you mean, And realize that this is not a issue,I will close this issue.
Thank for your reply again!
