### ISSUE TITLE
OES Shader not properly mapped to mesh on Oculus Go/quest

### ISSUE THREAD

**Issue by sammyvrmadman** [RenderHeads/UnityPlugin-AVProVideo#354]
**Describe the bug**
OES Shader not properly mapped to mesh when changing from resolution in adaptive stream

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.11f1
 - AVPro Video version: 1.8.7
 - Operating system version: Android 
 - Device model: Oculus quest
 - Video specs (resolution, frame-rate, codec, file size): 
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=5430449,AVERAGE-BANDWIDTH=4956000,RESOLUTION=2048x1024,FRAME-RATE=30.000,CODECS="avc1.640828,mp4a.40.2"
../6306105a/playlist.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=18691036,AVERAGE-BANDWIDTH=17353000,RESOLUTION=3840x1920,FRAME-RATE=30.000,CODECS="avc1.640834,mp4a.40.2"
../902a8bc9/playlist.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=11663348,AVERAGE-BANDWIDTH=10767000,RESOLUTION=2732x1366,FRAME-RATE=30.000,CODECS="avc1.640833,mp4a.40.2"
../04d09b99/playlist.m3u8

**To Reproduce**
1. use exoplayer and fast OES path
2. use OES shader
3. stream a video using vimeo 
4. Run avpro on oculus

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
Here is an example video of the behavior https://youtu.be/F0ecrx9XRwc

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hmm that's strange...
I notice you're using a very old version of the plugin.  Could you try with the latest version?

And if you just disable OES, do you then not have that issue?

Thanks,

**Comment by sammyvrmadman** [comment]
Hi after digging a bit further i noticed that its actually this bug here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/80
as it is going through the different resolutions sometime the seam pops up and sometimes it disappears creating a smal glitchy movement in VR
I noticed it's status is still open, so I am guessing there is no fix for it yet ?

**Comment by AndrewRH** [comment]
Right good find!
Yes...so it appears to be related to video resolutions that aren't a multiple of 16... So you could just change it to be multiple of 16 as a workaround.

**Comment by sammyvrmadman** [comment]
Yes but I am streaming from vimeo so their HLS server determines what resolutions the videos get. So then I guess a workaround is excluding the resolutions that aren't a multiple of 16. but that will result in a big gap between hd and 4k resolutions which might not be so nice visually. Is there anything else I could try ?

**Comment by AndrewRH** [comment]
@RenderHeadsSte  There's a good description of this bug here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/80

I think we may need to ad some adjustment to the UV coordinates in all OES shaders.  I'm not sure if we can just do this with some calculation based on multiple of 16 rounding, or whether it's not always a multiple of 16 issue and we need to use the transform matrix data..

**Comment by RenderHeadsSte** [comment]
We have tracked the issue and are working on a fix.

**Comment by RenderHeadsSte** [comment]
A fix for this will be presented in v 1.11.1 and onward.  Please do re-open the issue if the fix does not solve the issue for you

**Comment by sammyvrmadman** [comment]
Hi,

So the bug with the seam is fixed after downloading the latest version however it still gives a little glitch when switching between these resolutions here is an example of what it looks like 
https://youtu.be/0X4XSL_Ekvc
