### ISSUE TITLE
Can't specify HLS.JS path in WebGL

### ISSUE THREAD

**Issue by Twyker** [RenderHeads/UnityPlugin-AVProVideo#356]
Hi!

I'm trying to deploy for WebGL and I'd like to add a custom path to where my hls.min.js file is located on my server. The console tells me it's always looking at TemplateData/hls.min.js.
Is it possible to easily change this?

Thanks.

**Comment by AndrewRH** [comment]
Yes it should be easy to change.  It's up to you where hls.min.js is loaded from...In the index.html the following line loads the javascript:
<script src="TemplateData/hls.min.js"></script> 

So you should be able to change that location there.

Does that solve your issue?

**Comment by Twyker** [comment]
@AndrewRH Oof, sorry, seems like it was a **cache** problem. I already did exactly what you proposed before. :)
