### ISSUE TITLE
AVPro Video Android OES Release Build not working

### ISSUE THREAD

**Issue by mikerz** [RenderHeads/UnityPlugin-AVProVideo#359]
**Describe the bug**
I have an issue with Android OES release builds. When opening a video, the video successfully opens, reports new frames, and plays audio but there is no texture; it just comes in black.

The same shader works in Android OES development builds, non-OES Android release and development builds. Note: The GLSL shader has variants which switch between external and non-external texture, which is why the same shader can be used with OES or non-OES.

I've tried building Mono, Il2CPP, turning off stripping and trying different compression. Additionally, I am trying to preload the shaders (without preload also doesnt work).

Any guidance would be helpful here. Given that release builds work with non-OES, and development builds work with OES I don't think it's a problem with the custom GLSL shader. Additionally, I've tried building without the define so that it only has the external sampler, and it still fails.

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.11f1
 - AVPro Video version: 
 - Operating system version: Up to date Quest OS 
 - Device model: Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size): 
2880x2880 fisheyes, 4kx2k equirect, h264, h265, small and large files

**To Reproduce**
1. Uncheck "development"
2. Build to quest
3. Play Video
4. Watch the black screen

**Logs**
If applicable, add error logs to help explain your problem.
2020/05/15 22:39:01.048 5628 5642 Info Unity Built from '2019.3/staging' branch, Version '2019.3.11f1 (ceef2d848e70)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'

2020/05/15 22:46:20.905 5932 5946 Info Unity [AVProVideo] Initialising AVPro Video (script v1.10.3 plugin v1.10.2) on Adreno (TM) 540/OpenGL ES 3.2 V@461.0 (GIT@6950ec0, I01788bbc52, 1584759914) (Date:03/20/20) (MT True) on Android Android OS 7.1.1 / API-25 (NGI77B/6023800249000000) 

2020/05/15 22:47:23.767 5932 5946 Info Unity [AVProVideo] Opening /storage/emulated/0/Movies/TimeCodeTest_sideload_h265_crf17_hvc1_fisheye.mp4 (offset 0) with API ExoPlayer 

2020/05/15 22:47:24.208 5932 5946 Info Unity [AVProVideo] Using playback path: ExoPlayer OES (2880x2880@-1.00) 

2020/05/15 22:47:24.216 5932 5946 Info Unity [AVProVideo] Texture ID: 81 
2020/05/15 22:47:24.219 5932 5946 Info Unity AVPro Video:TimeCodeTest_sideload_h265_crf17_hvc1_fisheye.mp4 width:2880 height:2880 
2020/05/15 22:47:24.219 5932 5946 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by RenderHeadsSte** [comment]
This sounds very strange.  Unfortunately I don't have a Quest to hand (possibility I might be able to fetch it this week).

Could you try building one of the demo scenes with OES enabled, shader changed to the appropriate OES Android shader, and check that on the Quest...to rule out device as the issue trigger...?

**Comment by mikerz** [comment]
Sure, I just built and ran 08_Demo_360SphereVideo with the OES inside sphere shader and OES fast path enabled; video opens and thinks it plays (I hear the audio correctly) but the image is completely black.

**Comment by RenderHeadsSte** [comment]
You changed the shader as well?  To...  InsideSphere (stereo) - ANDROID OES ONLY

**Comment by mikerz** [comment]
Yes, correct; I used the InsideSphere ANDROID OES ONLY shader.

**Comment by RenderHeadsSte** [comment]
Hmm, interesting.  Do you have another device to run the same build on?  Can you send the APK over to [unitysupport@renderheads.com](url) ?

**Comment by mikerz** [comment]
Ok, done. I initially deleted because I was still testing with my video and not the sample video, but I also tried with the sample video and it's not working. double checked shader and OES bool on the player

**Comment by RenderHeadsSte** [comment]
Following up on this issue.  I believe it has been tracked back to the 'Low Overhead Mode' flag being set in the Oculus setyuip

**Comment by mikerz** [comment]
Great, so is this a confirmed-will-fix or a confirmed-will-not-fix?

**Comment by RenderHeadsSte** [comment]
For version v of AVPro Video, it is down the priority list.  It is on the version 2 radar now though, so hopefully at some point we will get chance to look into it.  That said, there appears to be an extremely limited amount of information to start the hunt with.
