### ISSUE TITLE
My app crashed on Android

### ISSUE THREAD

**Issue by gerhardtEyes** [RenderHeads/UnityPlugin-AVProVideo#362]
**Describe the bug**
My app crashed when I switched Video. It doesn't happen every time, but it happens frequently. My app flow is quite long and the crash doesn't happen at the same time, so I can only provide some logs exported from adb logcat. And I used three Medio players and added event listeners for them, listening for the FirstFrameReady and FinishedPlaying events. 
This problem troubles me a lot.
 I hope I can get your help. 
Really appreciate it.

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.35f1
 - AVPro Video version: 1.9.14
 - Operating system version: Android 9.0
 - Device model: Android Phone
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
--------- beginning of crash
05-19 18:15:11.789 26332 26332 E AndroidRuntime: FATAL EXCEPTION: main
05-19 18:15:11.789 26332 26332 E AndroidRuntime: Process: com.game.aiClass, PID: 26332
05-19 18:15:11.789 26332 26332 E AndroidRuntime: java.util.NoSuchElementException
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:264)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:682)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:622)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:567)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:109)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:112)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
05-19 18:15:11.789 26332 26332 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,
Thanks for your report.
The first thing I notice is that you're using an old version of the plugin.  I believe we improved a number of related issues in recent versions.  Please could you try upgrading to the latest version of AVPro Video.  Hopefully it will solve your issue.

Thanks,

**Comment by AndrewRH** [comment]
Hi @gerhardtEyes  did you try my suggestion?
Thanks,

**Comment by gerhardtEyes** [comment]
Yes, I tried your suggestion and solved the problem. Thank you very much.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andrew"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月26日(星期二) 凌晨1:45
收件人:&nbsp;"RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com&gt;;
抄送:&nbsp;"谭子豪"<252447586@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] My app crashed on Android (#362)





 
Hi @gerhardtEyes  did you try my suggestion?
 Thanks,
