### ISSUE TITLE
Streaming m3u8 http or https

### ISSUE THREAD

**Issue by Moriska32** [RenderHeads/UnityPlugin-AVProVideo#363]
Hello! I use AVProVideo and see some problem with streaming. If i take link like https:// android can play this video, but http:// can't. How can i play video with AVPro video, but use links http://?

**Comment by AndrewRH** [comment]
So starting with Android 9 (API level 28) cleartext support (unencrypted connections) is disabled by default, which can cause some HTTP streams to fail.  You should be able to resolve this by switching the URL to HTTPS or by adding android:usesCleartextTraffic="true" into your AndroidManifest.xml file

Does that solve your issue?

**Comment by Moriska32** [comment]
Yes, it's works. But i have same problem with webGL.

**Comment by AndrewRH** [comment]
Could you give more detail?
Have you investigated CORS?  perhaps it's related to CORS permissions set up..

**Comment by AndrewRH** [comment]
@Moriska32  which browsers have you tried?  Did you use the HLS.JS library (see PDF documentation).

Or perhaps the issue has been resolved?

Thanks,

**Comment by Moriska32** [comment]
I solved this problem by hls.min.js. Thanks

**Comment by AndrewRH** [comment]
Glad it's solved :) I'll close this issue now
