### ISSUE TITLE
Gradle transitive dependency error of Exoplayer from AVPro

### ISSUE THREAD

**Issue by santoshsatti** [RenderHeads/UnityPlugin-AVProVideo#364]
**Describe the bug**
When we import Unity project which is using Google ARCore for Unity lilbrary and AVPro Video player into Android project which is also using Exoplayer where we getting Gradle transitive dependency error

**Your Setup (please complete the following information):**
 - Unity version: 2019.2
 - AVPro Video version: 1.11.0
 - Operating system version: Android API 24
 - Device model: AR Core Supported devices
 - Video specs (resolution, frame-rate, codec, file size): Build is failing

Related issue in Exoplayer: https://github.com/google/ExoPlayer/issues/4902
**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.
error: no suitable method found for newSimpleInstance(FragmentActivity)
method ExoPlayerFactory.newSimpleInstance(Context,TrackSelector,LoadControl) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(Context,TrackSelector,LoadControl,DrmSessionManager<FrameworkMediaCrypto>) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(Context,TrackSelector,LoadControl,DrmSessionManager<FrameworkMediaCrypto>,int) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(Context,TrackSelector,LoadControl,DrmSessionManager<FrameworkMediaCrypto>,int,long) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(Context,TrackSelector) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(RenderersFactory,TrackSelector) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(RenderersFactory,TrackSelector,DrmSessionManager<FrameworkMediaCrypto>) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(RenderersFactory,TrackSelector,LoadControl) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(RenderersFactory,TrackSelector,LoadControl,DrmSessionManager<FrameworkMediaCrypto>) is not applicable
(actual and formal argument lists differ in length)
method ExoPlayerFactory.newSimpleInstance(RenderersFactory,TrackSelector,LoadControl,DrmSessionManager<FrameworkMediaCrypto>,Factory) is not applicable
(actual and formal argument lists differ in length)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
As you have correctly identified, this is because both AVPro Video and ARCore use ExoPlayer internally.  The problem is they are using different versions to each other.  The only current solution is to remove the ExoPlayer library files from the '/Assets/Plugins/Android/' folder and switch to using the MediaPlayer API path within AVPro Video.

Please do re-open this issue should you hit a problem.
