### ISSUE TITLE
iOS: Video format not detected without file extension

### ISSUE THREAD

**Issue by timokorkalainen** [RenderHeads/UnityPlugin-AVProVideo#365]
**Describe the bug**
We are loading video files from a cache system that does not store actual filenames, but instead hashes without the file extension. On Android this works fine, but on iOS AVPro (actually AVFoundation underneath?) does not recognise it the properly and thus does not display it. Modifying the filename to include the extension (.mp4 in this case) makes the file open perfectly.

I believe this also happens on OSX, but I did test that a lot less.

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.13f1
 - AVPro Video version: 1.11.0
 - Operating system version: iOS 13.5
 - Device model: iPad Pro (10.5-inch)
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 24, h264, 12MB

**To Reproduce**
1. Name file to not have a file extension
2. Try to load it
3. Result: Error about not being able to open

**Logs**
```

[AVProVideo] Opening /var/mobile/Containers/Data/Application/[ID]/Documents/downloadManager_cache/b18f088f0a10 (offset 0) with API 
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile()
---
System.Threading.ContextCallback:Invoke(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
System.Action:Invoke()
<ReturnVoid>d__0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Player 431: failed to load asset file:///var/mobile/Containers/Data/Application/[ID]/Documents/downloadManager_cache/b18f088f0a10
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
RenderHeads.Media.AVProVideo.MediaPlayer:Update()
```

**Videos**
An actual file I've tested with: https://coverr.co/videos/cat-chilling-on-the-street-ZyIpymHlRm

**Comment by AndrewRH** [comment]
Hi @timokorkalainen  I believe that is the native behaviour of the Apple API's....Without the correct extensions they will just not play the files.  I will bring in @MorrisRH  to confirm.

Thanks,

**Comment by MorrisRH** [comment]
Yes, local files require a recognised extension (qt, mov, mp4, m4v, etc.) in order to play.

**Comment by timokorkalainen** [comment]
Ok, thank you both for the quick responses! :)

**Comment by summitn** [comment]
我的老天奶啊，iOS本地视频播放需要加后缀！我说怎么文件确定存在，视频格式正确怎么还不能播放视频 - -|

**Comment by MorrisRH** [comment]
> 我的老天奶啊，iOS本地视频播放需要加后缀！我说怎么文件确定存在，视频格式正确怎么还不能播放视频 - -| 希望官方能在文档里面提一嘴 -> https://www.renderheads.com/content/docs/AVProVideo/articles/faq.html#1-why-doesnt-my-video-play

Oh my god, iOS local video playback requires a suffix! I said how can I make sure the file exists and the video format is correct, but why can't I play the video? - -|
I hope the official can mention it in the document -> https://www.renderheads.com/content/docs/AVProVideo/articles/faq.html#1-why-doesnt-my-video-play

**Comment by MorrisRH** [comment]
We'll look into getting this added to the documentation.
