### ISSUE TITLE
 Sync 2 or more videos

### ISSUE THREAD

**Issue by Kaimen001** [RenderHeads/UnityPlugin-AVProVideo#366]
Hello very good complement.
Is it possible to sync 2 or more videos (W10 and OS X,) so they play at the same time? I have the videos in separate files and they cannot be put into one. When I play at all, many times they are synchronized but other times they are not. It is a little random.
Thank you

**Comment by AndrewRH** [comment]
Hi,
Synced playback is not a feature of this plugin.  However we do provide some starting points that may help.  There is an example component called PlaybackSync that allows you to set up a MediaPlayer as the master and have multiple slave MediaPlayer's which will try to sync to the master.

I hope that helps and solves your issue?

**Comment by Kaimen001** [comment]
Thanks Andrew, it works great.

**Comment by AndrewRH** [comment]
Awesome, I'll close this issue then :)
