### ISSUE TITLE
Linking fails in unity cloud build xcode 11.3.1

### ISSUE THREAD

**Issue by tylkomat** [RenderHeads/UnityPlugin-AVProVideo#367]
**Describe the bug**
Compilation fails at linking stage.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.10f1
 - AVPro Video version: 1.11.0
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
Compiling with unity cloud build newest xcode version (11.3.1)

**Logs**
```
Compiling AVProVideoUnityRegisterRenderingPluginV5.c
Compiling AVCapture.mm
❌;  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1103.0.32.59.0_0' Reader: '1100.0.33.17_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.17)' for architecture arm64
❌;  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
AVPro Video 1.11.0 was built with Xcode 11.4 which is why you're seeing the linker error.
Normally Unity are pretty quick to update to the latest Xcode version for cloud build but this time they seem to be struggling somewhat.

AVPro Video 1.10.2 was built using Xcode 11.3 so if you're able to revert to that version then that may be the quickest route for you.

**Comment by tylkomat** [comment]
I am aware of that.
The reason I upgraded was because events where not working on iOS. Our app depends on those events.

**Comment by tylkomat** [comment]
Would it be possible to receive the latest update compiled with 11.3? Let me now how I should confirm that I hold a full license.

**Comment by MorrisRH** [comment]
AVPro Video 1.11.1 will be released quite soon and will have the iOS plugins built against Xcode 11.3.1.

**Comment by AndrewRH** [comment]
@tylkomat 1.11.1 has been released - please let us know if it solves your issue.

Thanks,

**Comment by tylkomat** [comment]
Yes everything works as expected now. Thank you.
