### ISSUE TITLE
Direct Show Mode  AudioOutput.cs and AudioChannelMixer.cs dont work

### ISSUE THREAD

**Issue by fingerx** [RenderHeads/UnityPlugin-AVProVideo#368]
using Direct Show Mode  AudioOutput.cs and AudioChannelMixer.cs dont work

play mp4 and hap codec video

 - Unity version: 2018.4.22f1
 - AVPro Video version: v1.11.0
 - Operating system version:  win10 1909
 - Device model: desktop

**Comment by AndrewRH** [comment]
That's correct.  We only currently support Unity audio output when using the Media Foundation API.  I don't see this changing any time soon, but we do plan to add Hap codec support to Media Foundation in version 2.0 of the plugin

**Comment by fingerx** [comment]
thanks. want to know 2.0 about time.If you need pre-testers please contact me, I've emailed you.

**Comment by AndrewRH** [comment]
A beta download link will be going on our website soon

**Comment by fingerx** [comment]
@AndrewRH  any news for 2.0 beta .thanks

**Comment by AndrewRH** [comment]
Hi @fingerx 2.0-beta1 will be released today (check website or this github releases page), but it will not include Hap Media Foundation support yet.  We expect that to come in beta2.

Thanks,

**Comment by fingerx** [comment]
thanks

**Comment by fingerx** [comment]
@AndrewRH  watting for beta2

**Comment by mikedreambooth** [comment]
@AndrewRH We have a need for audio output to unity while using HAP so looking forward to this release also. Any update on the beta? 

Thanks

**Comment by fingerx** [comment]
@AndrewRH  any news?thanks

**Comment by AndrewRH** [comment]
> @AndrewRH any news?thanks

Beta2 will be out before the end of this week

Thanks,

**Comment by fingerx** [comment]
@AndrewRH  using beta2 play hap(using media foundation and set audio output to unity ),AudioOutput.cs running is ok.thanks.
i want to know released to assetstore about time, i want to buy new version.thanks

**Comment by AndrewRH** [comment]
> @AndrewRH using beta2 play hap(using media foundation and set audio output to unity ),AudioOutput.cs running is ok.thanks.
> i want to know released to assetstore about time, i want to buy new version.thanks

I'm afraid we don't even know ourselves.  I suspect there will be 2 more Beta's before it is ready for release.

**Comment by AndrewRH** [comment]
This issue has been resolved so I'm closing this thread.  If you have more questions please post a new issue or email our product team (https://www.renderheads.com/contact).  Thanks
