### ISSUE TITLE
Bought AVPro Android but still has watermark

### ISSUE THREAD

**Issue by cheesemichael** [RenderHeads/UnityPlugin-AVProVideo#369]
Hi,

did i miss something ?  i paid for the package but it still shows watermark in the video ?

order number for AVPro Android is   18966904924882

**Comment by AndrewRH** [comment]
Hi,

So if you bought the Android package, then the watermark should only be removed in Android.  On the other platforms (including in editor which will be Windows or macOS platforms) the watermark will still be displayed.

If you're seeing the watermark in Android, then perhaps try to upgrade the package again.

Does this solve your issue?

Thanks,

**Comment by cheesemichael** [comment]
Ahh understood thks
