### ISSUE TITLE
Video Stutter in Game mode

### ISSUE THREAD

**Issue by jakezaslav** [RenderHeads/UnityPlugin-AVProVideo#370]
**Describe the bug**
AVPro video stutters in game mode of Unity. I tried it in my game with H264 and H265 and there was no difference. I also tried it using the multiple video demo scene and also encountered major stutter (video attached). However, this stutter does not occur when using unity's native video player.

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.7f1
 - AVPro Video version: Mac 1.11.0
 - Operating system version: MacOS Catalina 10.15.4
 - Device model: MacBook Pro (Retina, 13-inch, Early 2015)
 - Video specs (resolution, frame-rate, codec, file size): Occurs on H264, H265 and Demo video file. H264 and H265 are 24-30 fps and under 20 mb. 

**To Reproduce**
1. Occurred anytime I played the game in game mode in Unity using AVPro video player. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
[JZ AVPro Video Glitch.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4689753/JZ.AVPro.Video.Glitch.zip)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
hi @jakezaslav 

Could you check the plugin version in the console window please - because there are 2 versions (plugin and script version numbers).  I just want to make sure your plugin is the latest version too.

Also could you try switching from Metal to GLES to see whether that makes any difference?

And lastly, which Mac hardeware are you running on exactly?

Thanks,

**Comment by jakezaslav** [comment]
"AVPro Video (script v1.11.0 plugin v1.11.0) on Intel(R) Iris(TM) Graphics 6100/Metal (MT True) on OSXEditor Mac OS X 10.15.4"

**Comment by jakezaslav** [comment]
How do i switch from Metal to GLES in Unity?

**Comment by AndrewRH** [comment]
Thanks,
@jakezaslav  go to Edit > Project Settings > Other > Automatic Graphics API MacOSX  and move OpenGLCore to the top of the list

Is that a macbook pro? or what model and year machine is it?  Do you know if it has another GPU inside (eg Radeon)

**Comment by jakezaslav** [comment]
Ok so I switched to OpenGLCore and 50% of the time when I try to play the game my computer automatically restarts. When it does work it is ok but still not as good as the normal unity video player.

**Comment by jakezaslav** [comment]
It is a MacBook pro early 2015

**Comment by jakezaslav** [comment]
The only graphics card im running is Intel Iris Graphics 6100 1536 MB

**Comment by jakezaslav** [comment]
The processor is 2.9 GHz Dual-Core Intel Core i5

**Comment by AndrewRH** [comment]
Okay thanks for the detailed feedback, we're looking into it now and will get back to you.

**Comment by AndrewRH** [comment]
Hi @jakezaslav I've just had a look through the Unity release notes and it seems like they have fixed a number of issues for macOS in the latest version (2019.3.14), that sounds identical at least to the OpenGLCore crash issue.
![image](https://user-images.githubusercontent.com/5418126/83049183-aed98c80-a042-11ea-9d47-95fd02210124.png)

Perhaps you could try to upgrade to this latest version and test again, both with Metal and OpenGLCore?

Thanks for your co-operation :)

**Comment by AndrewRH** [comment]
Hi @jakezaslav 

The new version is out (1.11.2), could you confirm whether that solves your issue?

Thanks,

**Comment by jakezaslav** [comment]
Going to try it out tomorrow. Will keep you updated!

**Comment by jakezaslav** [comment]
So I downloaded it all and did a quick test. I updated to AvPro Video 1.11.2 and tried it out on both Unity 2019.3.7f1 and Unity 2019.3.15f1. 
1. While using Metal the major skipping issues I encountered were gone! There are still some very minor ones but I will have to compare it to the native unity video player. 
2. When I try to use OpenGL my computer still forcefully restarts. It only works on Metal. So that issue has not been resolved. 
I will run a test tomorrow probably comparing the update to unity's video player to make sure that the quality and cpu usage are either better or the same.

**Comment by AndrewRH** [comment]
Thanks for testing.  And also probably just worth double checking the console window to make sure it does say 1.11.2 as the version number for both scripts and plugins.
Let us know how it goes.
Thanks,

**Comment by AndrewRH** [comment]
Hi @jakezaslav  as well as the above request - would it be possible for you to do a short video capture showing the "While using Metal the major skipping issues I encountered were gone! There are still some very minor ones"?

Thanks,

**Comment by jakezaslav** [comment]
So the skipping is CPU related I realized. I compared the two and it seems like AVPro uses slightly less CPU than Unity Video Player

**Comment by jakezaslav** [comment]
Here are the Profiler files

**Comment by jakezaslav** [comment]
ok it won't let me load data files

**Comment by jakezaslav** [comment]
Quick question: If I am working on this project with a windows user but I only have the MacOS version can they still use and edit?

**Comment by AndrewRH** [comment]
> Here are the Profiler files

I don't see anything?

**Comment by AndrewRH** [comment]
> Quick question: If I am working on this project with a windows user but I only have the MacOS version can they still use and edit?

Yes it should indeed.   It'll just watermark it.

**Comment by AndrewRH** [comment]
We will close this issue unless we hear further details soon.

@MorrisRH that okay?

Thanks,
