### ISSUE TITLE
AVPRO VIDEO integration with Vimeo SDK (iOS)

### ISSUE THREAD

**Issue by savek1986** [RenderHeads/UnityPlugin-AVProVideo#372]
Hi,
Reference issue: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/337

I'm adding adaptive functionality to iOS version of my app.
I just have updated Vimeo SDK and AVPRO, but when I select "adaptive", there isn't possibility to choose between Vimeo Player and AVPro Player.
Can you help me, please?
Thanks
![IOS](https://user-images.githubusercontent.com/6131397/83146677-f3266480-a0f6-11ea-99ca-ef7212076a4d.PNG)

**Comment by AndrewRH** [comment]
Try going to Player Settings / Other Settings / Scripting Define Symbols and adding VIMEO_AVPRO_VIDEO_SUPPORT

Does that solve your issue?

Thanks,

**Comment by savek1986** [comment]
Yes, thank you.
________________________________
Da: Andrew <notifications@github.com>
Inviato: giovedì 28 maggio 2020 19:31
A: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: savek1986 <savek1986@hotmail.it>; Author <author@noreply.github.com>
Oggetto: Re: [RenderHeads/UnityPlugin-AVProVideo] AVPRO VIDEO integration with Vimeo SDK (iOS) (#372)


Try going to Player Settings / Other Settings / Scripting Define Symbols and adding VIMEO_AVPRO_VIDEO_SUPPORT

Does that solve your issue?

Thanks,
