### ISSUE TITLE
How to interact with PlaylistMediaPlayer

### ISSUE THREAD

**Issue by Alessandruus** [RenderHeads/UnityPlugin-AVProVideo#374]
Hi!
I'm using the PlaylistMediaPlayer with several 360° videos and I need to implement a button to switch from one video to the next/previous one. I didn't find any way to make it work, is it any documentation available about the PlaylistMediaPlayer?
Thank you!

**Comment by AndrewRH** [comment]
There isn't an documentation for PlaylistMediaPlayer besides the component Methods and Properties themselves.   I think you posted another issue about this so I think you managed to solve this yourself?

You can use these methods to switch between items:

mp.NextItem();
mp.PrevItem();

I hope solves your issue?

Thanks,

**Comment by Alessandruus** [comment]
It's solved thanks to your reponse. Thank you!
