### ISSUE TITLE
Integrate my own watermark in the paid version

### ISSUE THREAD

**Issue by Alessandruus** [RenderHeads/UnityPlugin-AVProVideo#375]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to integrate my own dynamic watermark (I have the paid version of the plugin). How is it possible?

Thank you in advance!

**Comment by AndrewRH** [comment]
Hi @Alessandruus 
Are you talking about for the AVPro video plugin, or AVPro Movie Capture?

Could you explain more about the feature request?

Thanks,

**Comment by Alessandruus** [comment]
Hello,

I’m talking about the AVpro video plugin, I would like to be able to implement my own watermark system. The idea is streaming through avpro and in the app add a (moving) watermark to be sure our streaming content is not so easily stealable.

De : Andrew<mailto:notifications@github.com>
Envoyé le :lundi 1 juin 2020 15:32
À : RenderHeads/UnityPlugin-AVProVideo<mailto:UnityPlugin-AVProVideo@noreply.github.com>
Cc : Alessandruus<mailto:alessandrocierro@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [RenderHeads/UnityPlugin-AVProVideo] Integrate my own watermark in the paid version (#375)


Hi @Alessandruus<https://github.com/Alessandruus>
Are you talking about for the AVPro video plugin, or AVPro Movie Capture?

Could you explain more about the feature request?

Thanks,

**Comment by fingerx** [comment]
This is definitely a very useful feature. An easy way to do this currently is to export the watermark directly to the screen position via the method provided by UNITY itself, which can be done quite simply.

**Comment by Alessandruus** [comment]
Thank you for your response, could indicate me what's the method provided by unity? I didn't find anything.

**Comment by fingerx** [comment]
write your watermark in unity gui or ugui

**Comment by AndrewRH** [comment]
I'm going to close this issue as this isn't something we will be adding.  If you need a watermark in your application you can create it via Unity scripting.

Thanks,
