### ISSUE TITLE
Can't seek properly (even when increasing key frames)

### ISSUE THREAD

**Issue by NaorHadar** [RenderHeads/UnityPlugin-AVProVideo#376]
**Describe the bug**

**Essentially, what I am trying to do is mimic the playback functionality, but advance the frame only if certain conditions are met (everything is loaded for the next frame for example)**

There seem to be a problem when you want to control the playback by using the seeking.
Essentially what I am trying to do is load a video, stop the playback (and I have set the playback speed to 0 also), and for every X `Update` (Unity call), I advance the frame count and seek to it.
The problem it seems, that AVPro Video is "fighting" with the seeking and keep going back to the first frame (it seems to be the first frame anyway).

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.22f1
 - AVPro Video version: script v1.10.3,  plugin v1.10.2
 - Operating system version: Windows 10
 - Device model: Desktop
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 25fps, x264, about 20MB

**To Reproduce**
1. Set playback speed to 0, load a video (tried multiple codecs so I am pretty sure any mp4 would reproduce the problem) through script using `OpenVideoFromFile`.
2. Using the `Control` from the `MediaPlayer`, `Stop` the video.
3. In this step, create an integer variable, start at 0 (if you start at a latter frame, like 200 or more, the problem seem to be a lot more noticeable), and for every `Update`/`FixedUpdate` create an if statement that will advance the current frame by one *and seek* (once). 

Notice!:
In my case, I try to simulate a game, so just when everything is loaded for the next frame (the animation is set, every file is loaded, and every part of the scene is there), only then, I advance my frame, so you could replicate my state with something like this:
```
if(Random.value < 0.95f)
{
    currentFrame++;
    // Do seeking here or somewhere else (**once** for the new frame!)
}
```

**Logs**
There are no logs that indicate something is wrong, just the plugin say the it uses MediaFoundation as the API.

**Videos**
https://streamable.com/dysvkr

**Comment by AndrewRH** [comment]
Hi,

That sounds very strange.  Could you paste the code you're using for seeking?

Have you tried using our sample videos?

Thanks,

**Comment by NaorHadar** [comment]
Hey, yeah, 
when loading a new video I just do:
```
if (mediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, _currentFilePath))
{
	// We pause the player because this is the only way we can seek
	mediaPlayer.Control.Stop();
	...
```
for every update I just do:
`mediaPlayer.Control.Seek(frame / 25.0f * 1000.0f);`
(my frame rate is 25, and the `Seek` function needs milliseconds so I multiply by 1000.0f)
but as I said, I only seek from time to time, I am not sure if its related to the problem, but if you want to replicate my case, this is the way.

That's basically it. I tried multiple things before based on your demos and this one worked.

About the samples, it seems to be better than my videos, but I can't seem to tell what is the difference in the format that I need to take for my videos. here is the media info for the sample and my file:
https://i.imgur.com/BxtCZmw.png
The left file is the sample one, the right is mine.
Notes: 
• Ignore the frame rate, I know its different (and resolution)
• The info on the right was changed multiple times because we tested multiple cases, none worked.
• The things that to me seems like could be it is the GOP (which I tried and failed), the bit rate seems way higher in my video, maybe its related.

**Comment by NaorHadar** [comment]
Just an update, I tried replicating the sample encoding, and I am still getting the same results, I did this conversion on my video:
`ffmpeg -y -i H10_GR_B.mp4 -g 2 -keyint_min 1 -refs 5 -coder 0 -profile:v main -level:v 3.1 test.mp4`
but I get the same result.
Also, I tried converting the video to a constant bit rate and still the problem remain.

**Comment by AndrewRH** [comment]
To seek accurately using frames you should use our helper methods.  For example:

```
int frame;
MediaPlayer mediaPlayer;

void Update()
{
float mediaPlayer.Info.GetVideoFrameRate();
float time = Helper.ConvertFrameToTimeSeconds(frame, frameRate);
mediaPlayer.Control.Seek(time * 1000f);
frame++;
}
```

As for FFMPEG we use the following command to make an I-frame only video for rapid seeking:

```
ffmpeg -hide_banner -y -i input -pix_fmt yuv420p -c:v libx264 -crf 18 -tune fastdecode -x264-params "keyint=1" output.mp4
```

Does this help?

**Comment by NaorHadar** [comment]
Hey Andrew, I tried both your options, both doesn't seem to work. 
The first one is essentially exactly what I did, but more correct for more frame rate options.

The FFmpeg command worked great for the first 2 tests, and somehow now its not working at all (didn't changed a thing, same video even).

The results are the same as the posted video (https://streamable.com/dysvkr)

**Comment by NaorHadar** [comment]
Update: I tried downloading Big Buck Bunny (the original mp4 1920x1080 @30fps) and tried seeking using it, the same result happened, after that, I tried using your FFmpeg command line on it, it got better, but not enough to avoid the frame jumping you see in the video I linked.

**Comment by AndrewRH** [comment]
Hmm that's strange.  A few more questions

1) Have you tried running this on another machine?
2) Could you make sure your GPU drivers are up to date?
3) If you pause the video in the editor via the MediaPlayer component Preview section and scrub through it - do you get those visual artifacts still?
4) You really shouldn't be changing PlaybackRate if you just want to scrub through the video, and actually this could be causing side effects.  Perhaps you could try without this?

Thanks,

**Comment by NaorHadar** [comment]
1. Yeah I have tested on two machines, one has 2060GTX and one 1070GTX.
2. The drivers are indeed up to date.
3. Gonna try this and update soon.
4. Trying it now (I am assuming you mean setting the playback rate to 1, which is the default).

Thanks for the fast reply! gonna update soon.

**Comment by NaorHadar** [comment]
Ok so:
3. It works great!
4. Didn't change anything.

**Comment by AndrewRH** [comment]
Hmm, are you sure you don't have something in your scene that is also trying to seek or play the video?   I can't think of any reason why the scrubbing would work via the editor UI but not via script - it all works the same way..

**Comment by NaorHadar** [comment]
No there is nothing that try to seek or play the video except that line, are you sure its nothing related to the fact that I seek only for `some` update calls?

**Comment by NaorHadar** [comment]
Tried modifying the code a bit:
```		
if(_currentFrame != frame)
{
	mediaPlayer.Control.Pause();
	_currentFrame = frame;
	float frameRate = mediaPlayer.Info.GetVideoFrameRate();
	float time = Helper.ConvertFrameToTimeSeconds(frame, frameRate);
	mediaPlayer.Control.Seek(time * 1000.0f);
}
```
`frame` is a parameter I get that says exactly what frame we should be on, this could be the same across multiple `Update` calls.
`_currentFrame` is used to not `Seek` every `Update` call, just when the frame has changed. 
this doesn't effect anything.

I am now trying to create an empty project and try again with a really simple script and update with it if you guys want to try and reproduce the same project with the same script.

**Comment by AndrewRH** [comment]
Okay that sound like a good plan.

By the way, two suggestions for you to try:

1) Remove the call for Pause so it's not happening per-frame
2) Instead of mp.Control.Pause() just use mp.Pause();

Thanks,

**Comment by NaorHadar** [comment]
Ok! I found it!
The thing is, I used `ExtractTexture` right after the `Seek`, and for some reason (which is not documented, again, you really need to work on your documentation in my opinion) the `ExtractTexture` also do a seek, 

I don't know if it is a bug or not, but you didn't mention anything about it, so I guess it is.

**Comment by AndrewRH** [comment]
This is the first time you've mentioned that you're using ExtractTexture (I presume you mean ExtractFrame).  We include a demo scene that shows how to use ExtractFrame method to grab a sequence of frames from the video.

Is there anything else we can help with, or is your issue resolved?

Thanks,

**Comment by NaorHadar** [comment]
Its the first time I've mentioned it (Yeah I meant `ExtractFrame`, sorry), but its really not obvious that this is the cause of the problem, so I didn't mention it.

 What exactly does `ExtractFrame` do?

**Comment by AndrewRH** [comment]
Okay, I'm super confused.   You say you're using it, but now you're asking what it does?

It is used to extract a frame from the video into a texture.  You specify the time you want to extract, it will seek there, wait for the frame to render and then return the texture.  The included demo scene 06_Demo_FrameExtract.unity with demo script FrameExtract.cs should give a good overview of that feature.

The original issue raised about seeking has been solved.  Are you happy for me to close this ticket?

We're now starting to talk about other things and it's best if you open up a new ticket for different issues.

Thanks,
