### ISSUE TITLE
Bug With PlaylistMediaPlayer.cs when switching videos

### ISSUE THREAD

**Issue by joanmitjansamuse** [RenderHeads/UnityPlugin-AVProVideo#377]
Problem description:

I have added onButtonClick callbacks for PrevItem() and NextItem() directly in the unity 
inspector (I created new void functions as unity doesn't allow to add callback functions returning bools),
 - I also added a button with the callback 'JumpToItem(1)' just for testing. 
Most of the time it works but, in some cases, instead of showing the transition, the video screen
goes dark for some milliseconds and then, when it comes back ,the video that plays is not 
the good one (it has a different index from the previous or next video, for example).
This happens specially when going to a video with a smaller index than the current one. 

Thank you very much for the help!

Device (which devices are you having the issue with - model, OS version number):

Unity Editor (Windows 10) and in builded android version

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

I added four videos in the PlaylistMediaPlayer items list, all of them hls videos. 

System Information:

AVPro Video: plugin v1.11.1t scripts v1.11.2
Target Platform: Android
Unity: v2019.3.7f1 WindowsEditor
OS: Desktop - MS-7918 (MSI) - Windows 10  (10.0.0) 64bit - French
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz - 8 threads - 8140KB
GPU: NVIDIA GeForce GTX 970 - NVIDIA - Direct3D 11.0 [level 11.1] - 4043KB - 16384

**Comment by AndrewRH** [comment]
Thanks for the bug report - we're investigating and will get back to you.

**Comment by AndrewRH** [comment]
Hi,

I have a potential fix for you to try.  PlaylistMediaPlayer line 567,

change from 

'						if (NextPlayer != null)
						{
							NextPlayer.CloseVideo();
						}'

to

'						if (NextPlayer != null)
						{
							NextPlayer.m_VideoPath = string.Empty;
							NextPlayer.CloseVideo();
						}'

Does that help?

**Comment by joanmitjansamuse** [comment]
It is working! Thank you very much for your help (and fast reply!!)

**Comment by AndrewRH** [comment]
Thanks for reporting it!  We will include this fix in the next update.
