### ISSUE TITLE
Playing video is not smooth in Android with obb

### ISSUE THREAD

**Issue by haiyaojing** [RenderHeads/UnityPlugin-AVProVideo#378]
Problem description:

The whole package is running normally, the video load in the packet is obviously slower than the whole package, and the occasional stuck phenomenon, if the same video is put into Application.persistentDataPath playback, works well, The plugin comes with video BigBuckBunny_720p30.mp4 still has a problem

Device (which devices are you having the issue with - model, OS version number):

Simulators, such as mumu simulators

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

BigBuckBunny_720p30.mp4 in orignail package

System Information:

AVPro Video: plugin v1.11.0 scripts v1.11.0
Target Platform: Standalone
Unity: v2018.4.21f1 WindowsEditor
OS: Desktop - OptiPlex 7050 (Dell Inc.) - Windows 10  (10.0.0) 64bit - Chinese
CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz - 8 threads - 16247KB
GPU: NVIDIA GeForce GTX 1060 3GB - NVIDIA - Direct3D 11.0 [level 11.1] - 2988KB - 16384

**Comment by haiyaojing** [comment]
Any help welcome. . .thanks

**Comment by AndrewRH** [comment]
Thanks for reporting the problem.

1) I'm still not quite sure what the issue is.  Do you have a video showing the problem that you could share?

2) Does it only happen on these 'mumu simulators', or have you seen it on devices as well?

Thanks,

**Comment by RenderHeadsSte** [comment]
'mumu simulators' is essentially an emulator is it not?  If that is the case, I am not surprised some elements of emulating a device are slower.

**Comment by haiyaojing** [comment]
> Thanks for reporting the problem.
> 
> 1. I'm still not quite sure what the issue is.  Do you have a video showing the problem that you could share?
> 2. Does it only happen on these 'mumu simulators', or have you seen it on devices as well?
> 
> Thanks,

I'll wait to see other simulators, Android devices.

**Comment by haiyaojing** [comment]
We're going to unzip the video out of the obb, and that's fine.

**Comment by lvchy** [comment]
i have this problem too,any help welcome ,tks

**Comment by lvchy** [comment]
i use the newest asset from asset store .. and  not only the mumu can not play with android obb, but also some phones can not play with android obb .  these devices android version is 6.0

**Comment by haiyaojing** [comment]
> i use the newest asset from asset store .. and not only the mumu can not play with android obb, but also some phones can not play with android obb . these devices android version is 6.0

extract to persistentdatapath,
