### ISSUE TITLE
Video Caching

### ISSUE THREAD

**Issue by pandajoris** [RenderHeads/UnityPlugin-AVProVideo#379]
Hey guys,

I was wondering if there is support to cache the stream progress of a video.
We have the case that a video might be played many times over and over. We would like to be able to cache the data that was already download, and load that back in if the same video url gets requested again.

**Comment by DrPandaDev** [comment]
Any comment on this please? 

Thanks!

**Comment by timleader** [comment]
I'm also interested in this enhancement, is this something that is being worked on at? For us its kind of the make or break as to if we can use your plugin.

It also seems like there are solutions out there. eg. 
https://github.com/neekeetab/CachingPlayerItem
https://stackoverflow.com/questions/28700391/using-cache-in-exoplayer


It would be a good way to keep ahead of the built-in Unity VideoPlayer as it doesn't supporting caching.

**Comment by RenderHeadsSte** [comment]
Closing this issue as caching has been added for Android and iOS in v2.1.0 which has been released today.
