### ISSUE TITLE
The First frame of video should be shown before playing.

### ISSUE THREAD

**Issue by SniperED007** [RenderHeads/UnityPlugin-AVProVideo#38]
Bug on Android (can't test on iOS yet)
1) Open the 04_Demo_uGUI test scene
2) Set the Media Players "Auto Play" option to unticked
3) Make sure your Player Settings has "Multithreaded Rendering" is enabled

Run on Android
Expected Results:
- The First frame of the video should be shown.

Actual Results:
- Just a Black texture.

4) Switch Player Settings has "Multithreaded Rendering" to disabled

New Results:
- The First frame of the video should is shown.

 - Unity version: Unity 2018.3.9f1 (64-bit)
 - AVPro Video version:  AVPro: Version 1.9.12 - 18 January 2019
 - Operating system version: Android
 - Device model: Samsung S8+
 - Video specs (resolution, frame-rate, codec, file size): Any

**Comment by AndrewRH** [comment]
Yes, the native Android players don't show the first frame until the video is played.  One way around this is to enable the "show poster frame" option in MediaPlayer component > Platform Specific > Android section.

I hope that helps?

**Comment by SniperED007** [comment]
I have tried both and both have the same issue.

Yet as I mentioned above:
Switch Player Settings has "Multithreaded Rendering" to disabled
New Results:
The First frame of the video should is shown. (Even with "Show Poster Frame" disabled.

**Comment by AndrewRH** [comment]
You could also try switching the video API to MediaPlayer (from ExoPlayer).

We will have to investigate this further.

Thanks,

**Comment by SniperED007** [comment]
I tried the MediaPlayer and whilst the first frame showed the videos failed to actually play.

**Comment by AndrewRH** [comment]
Also customer email [#FIRev] reported the same issue.  They provided a demo scene.

**Comment by RenderHeadsSte** [comment]
We have just released version 1.9.17 which contains a number of fixes to the ExoPlayer API path.

I have tested the reported issue on a Galaxy S7 (EU/UK version) with the latest version and got the following results:

- ExoPlayer, MT rendering enabled, poster frame disabled = first frame IS shown.
- ExoPlayer, MT rendering enabled, poster frame enabled = first frame IS shown.
- MediaPlayer, MT rendering enabled, poster frame disabled = first frame IS NOT shown.
- MediaPlayer, MT rendering enabled, poster frame enabled = first frame IS shown.

Maybe you could get the latest version and report back as to whether the problem you are seeing has been addressed for you?

**Comment by AndrewRH** [comment]
We'll close this issue in a couple of days, as we've proposed a solution (new plugin version) but haven't heard anything back.  If you're still having this issue with the new version please do let us know.

Thanks,

**Comment by SniperED007** [comment]
I switched to another Unity Asset Store plugin and had zero issues on both iOS and Android with theirs.

**Comment by AndrewRH** [comment]
Thanks for reporting the issue - we'll continue improving our plugins.
