### ISSUE TITLE
DisplayUGUI wrong appearance with custom UVRect (WebGL, stereo video)

### ISSUE THREAD

**Issue by Oneiros90** [RenderHeads/UnityPlugin-AVProVideo#380]
**Bug description**
I am reproducing a stereoscopic video in an AVPro `MediaPlayer`, displayed through a `DisplayUGUI` component in a Canvas in a WebGL application. I want to visualize only the left eye view of the video (which is in the TopBottom stereo packing format), so what I do is:
```
mediaPlayer.m_StereoPacking = StereoPacking.TopBottom;
display.uvRect = new Rect(0.0f, 0.0f, 1.0f, 0.5f);
```
It works just fine in the editor.
In the WebGL build it is just wrong: it is cut in half, it is stretched and it is the wrong eye. After some testing, the only way to make it right seems to be:
```
mediaPlayer.m_StereoPacking = StereoPacking.TopBottom;
#if UNITY_WEBGL && !UNITY_EDITOR
display.uvRect = new Rect(0.0f, -1.0f, 1.0f, 1.0f);
#else
display.uvRect = new Rect(0.0f, 0.0f, 1.0f, 0.5f);
#endif
```
Those values have been found by trial and error, I have no idea why the `y` value should be negative and the height should be `1` in WebGL

**My Setup**
 - Unity version: 2019.3.5f1
 - AVPro Video version: 1.11.2 (trial)
 - Operating system version: Windows 10 Pro
 - Browser: Both Firefox and Chrome (last version)
 - Device model: Desktop PC
 - Video specs (resolution, frame-rate, codec, file size): 2300x2300, 30fps, mp42, 60Mb

**To Reproduce**
1. Create a WebGL application in Unity
2. Create a Canvas with a `DisplayUGUI` component in it
3. Load a stereo video and change the stereo packing settings + uvrect settings as described before
4. Try in in the browser

**Comment by AndrewRH** [comment]
Hi @Oneiros90 

Couldn't you just set the eye mode of the Camera?
https://docs.unity3d.com/ScriptReference/Camera-stereoTargetEye.html

Thanks,

**Comment by Oneiros90** [comment]
Hi @AndrewRH, thank you for the response

No, I'm actually working on a GUI only web tool that has a media player inside one of the pages (think of it like an embedded youtube video player), I don't think that I should mess with the main camera eye mode

**Comment by AndrewRH** [comment]
Hi,

You should be able to to force the eye already.  Your scene should have the UpdateStereoMaterial component in it, which has the option to assign the DisplayUGUI component, and force which eye to display.  This should save you from manually trying to adjust uvRects etc which could differ per-platform.

I hope that helps?

**Comment by AndrewRH** [comment]
Oh but it actually will require a slight shader tweak.  I've attached the shader here for you to replace.

Does this help solve your issue?

Thanks,
[AVProVideo-UI-Default-Stereo.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4746051/AVProVideo-UI-Default-Stereo.zip)
