### ISSUE TITLE
Switch between resolutions when using Master Playlists / an HLS Stream

### ISSUE THREAD

**Issue by julienkay** [RenderHeads/UnityPlugin-AVProVideo#381]
I guess the first part of this feature request applies to the documentation. I found it a bit difficult at first to understand how AVPro handles master playlists of an HLS stream. If I pass an HLS playlist in the .m3u8 format, the stream is played back fine by the plugin. I just would like to understand how the playlist is interpreted by the plugin.

An HLS master playlist can define several 'variant streams' (usually different resolutions) according to the specification: https://tools.ietf.org/html/rfc8216
From inspecting the resolution of the video that the MediaPlayer script provides, it seems like it respects the attributes in the EXT-X-MEDIA tag of the master playlist (see AUTOSELECT and DEFAULT attributes in the spec). I.e. if the tag of a specific variant stream contains 'AUTOSELECT=YES', then that will be the variant that AVPro ends up playing back.

However, it seems like at the beginning, the player loads one of the lower resolutions first, before switching to the higher resolution (is this a bug or intended behaviour?). 
Since I haven't found a section in the documentation about this, my proposal would be to add a paragraph that explains this behaviour and gives more insight to developers that are familiar with the HLS spec.

The second part of this feature request would be to add the possibility for developers to change/override the variant stream that is used. Changing the resolution is a thing that you usually even want to expose to users, let alone developers. I am aware I could work around this, by just passing the .m3u8 playlist of the actual stream to the plugin. (Something that also could be added to the documentation). However, that would require parsing the master playlist to extract the individual playlists. Not the hardest task, but I still think it would be convenient to add a feature to your plugin that lets a developer select/override the variant stream that the MediaPlayer currently displays when using an HLS stream as a source. I assume you already parse the playlist in some form, if I'm correct in my assumption that your plugin uses the information in the EXT-X-MEDIA tag. I think it would be a big help for developers to add that feature. Otherwise developers would have to implement a complete HLS playlist parser themselves.

Just for reference, a (simplified) example of an HLS playlist I'm testing this with looks like that:

```
#EXTM3U

#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p60",NAME="720p60",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=3461582,RESOLUTION=1280x720,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="720p60",FRAME-RATE=60.000
<link to .m3u8>

#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p30",NAME="720p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=2411582,RESOLUTION=1280x720,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="720p30",FRAME-RATE=30.000
<link to .m3u8>

#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p30",NAME="480p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=1466582,RESOLUTION=852x480,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="480p30",FRAME-RATE=30.000
<link to .m3u8>

#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="360p30",NAME="360p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=630000,RESOLUTION=640x360,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="360p30",FRAME-RATE=30.000
<link to .m3u8>

#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="160p30",NAME="160p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=230000,RESOLUTION=284x160,CODECS="avc1.4D401F,mp4a.40.2",VIDEO="160p30",FRAME-RATE=30.000
<link to .m3u8>

```
P.S.: I agree this is probably not the highest priority feature request. Just something I thought would be neat.

**Comment by Eittipat** [comment]
I am waiting for this feature!

**Comment by AndrewRH** [comment]
Yes this is a new feature we're currently working on for the next beta of version 2.0

Thanks,

**Comment by AndrewRH** [comment]
We can't support this natively easily...
On iOS it's possible to set the preferredMaximumResolution to give it a hint for which to play.  On Apple platforms there is no way to lock it to a specific variant.   

You could parse the manifest file yourself, extract the different bitrate URLs are play those directly...but currently this isn't something we are implementing natively.

Closing.
