### ISSUE TITLE
Side by side video comes out as Mono video

### ISSUE THREAD

**Issue by ToddJo** [RenderHeads/UnityPlugin-AVProVideo#387]
**Describe the bug**

Side by side video comes out as Mono video
In the vlc player, it is displayed as Side by Side video normally.

**Your Setup (please complete the following information):**
 - Unity version:  2019.2.12f1
 - AVPro Video version: 1.10.3
 - Operating system version: Windows 10
 - Device model: Desktop
 - Video specs (resolution, frame-rate, codec, file size):  2160 x 1080,  7462kbps, H264

**To Reproduce**
1.  Play url
2.   http://flv14.afreecatv.com/afflv14/_definst_/smil:save/afreeca/station/2019/1028/14/1572241979372077.smil/chunklist_w1426606121_b8000000_t64b3JpZ2luYWw=.m3u8
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

![2222](https://user-images.githubusercontent.com/31684034/84749001-5fa8cb00-aff4-11ea-9de7-1dad77541d4e.PNG)

![vlc](https://user-images.githubusercontent.com/31684034/84748971-53bd0900-aff4-11ea-9bd4-627245ee8234.PNG)

**Videos**

http://flv14.afreecatv.com/afflv14/_definst_/smil:save/afreeca/station/2019/1028/14/1572241979372077.smil/chunklist_w1426606121_b8000000_t64b3JpZ2luYWw=.m3u8

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi @ToddJo 
Yes this is a limitation of our Windows implementation.  Videos that contain stereo metadata only render the left eye.  If you remove the stereo metadata from the video then it will display correctly.
This is something we are working on fixing in 2.0.0 of this plugin, which is currently in beta.

Thanks,
