### ISSUE TITLE
How to render 8k videos on sphere with out any lag in Unity 3d

### ISSUE THREAD

**Issue by Ramsss123** [RenderHeads/UnityPlugin-AVProVideo#389]
**Is your feature request related to a problem? Please describe.**
8k videos are lagging(getting stuck) when we render on a sphere.

**Describe the solution you'd like**
We are trying to display 360 videos on sphere and the projection will be from inside. There are few videos possibly of  4k, 6k are playing bit fine. But when we try to render the 8k videos, video is getting lagged(video is jerky, not playing smooth). As of now we are using few videos from kandaovr. Below is the video which has the problem in rendering smoothly.
reference Video link :   https://drive.google.com/file/d/13Ys3JaF_aQ2bRbcp-HdUDjs3M7C-oGJ5/view?usp=sharing

We need to play this type of videos on sphere smoothly.

Target platform : Both standalone and UWP.

Could you please guide me here..

**Comment by AndrewRH** [comment]
Hi,

Could you tell me more about the hardware you're using to play back the video?

Thanks,

**Comment by Ramsss123** [comment]
![hardware](https://user-images.githubusercontent.com/67152271/85279083-7d1ddf00-b4a3-11ea-8872-d462dfbed4f1.png)

Please find the above screen shot for the hardware reference.

**Comment by RenderHeadsSte** [comment]
> Please find the above screen shot for the hardware reference.

Can you include the GFX card specification please?

**Comment by Ramsss123** [comment]
Here is the screen shot for graphics specifications.
![graphics](https://user-images.githubusercontent.com/67152271/85361840-9b82e980-b53a-11ea-8c2e-cedc072fad3b.png)

**Comment by AndrewRH** [comment]
Hi @Ramsss123 

Thanks for those details.  I suspect 8K might just be too much.  That card is based on the Pascal Archiecture, which is the first series of the cards to offer 8K decoding.  While the card can technically do it, it's right at the limit of what the hardware can do, meaning that if you have other overheads you're likely to end up dropping frames.   Unity itself adds overheads, then whatever your app is doing, and then the video decoding that we do also has extra overheads.

In addition I think you should try transcoding the video into H.265 (HEVC).  The sample video you linked to is H.264 which I believe most NVidia hardware doesn't offer 8K decoding for, but they do for HEVC.

I converted your video to HEVC and then played it back using the Media Foundation Video API option, and making sure the Hardware Decoding option was enabled (in Player Specific > Windows section of MediaPlayer component), and I was able to achieve 30fps playback on Geforce 1060

![image](https://user-images.githubusercontent.com/5418126/85587534-c43dd880-b639-11ea-904c-cf23a3c0723f.png)

Does that helps?

Thanks,

**Comment by AndrewRH** [comment]
Closing as the decoding is as fast as the hardware allows, and this issue is very old
