### ISSUE TITLE
Memory leaks in iOS

### ISSUE THREAD

**Issue by crazylulu9999** [RenderHeads/UnityPlugin-AVProVideo#39]
**Describe the bug**
Video playing consumes over 100 MB for very little video (51 KB).
And that memory never released.

But using internal Unity VideoPlayer, memory released after closing video.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.11f1, 2018.2.21f1
 - AVPro Video version: 1.9.12
 - Operating system version: 12.2
 - Device model: iPad Mini 2
 - Video specs (resolution, frame-rate, codec, file size): Any

**To Reproduce**
1. Play video.
2. CloseVideo and Dispose MediaPlayer.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
When you close the video and dispose, are you using remove the ApplyToMesh/ApplyToMaterial etc components?

**Comment by AndrewRH** [comment]
Closing this ticket due to lack of information, and also we weren't able to replicate
