### ISSUE TITLE
Direct Show Mode Play Hap and MP4 5.1 sound 

### ISSUE THREAD

**Issue by fingerx** [RenderHeads/UnityPlugin-AVProVideo#390]
Trying to play hap-encoded and MP4-formatted standard video using direct show mode, only three channel sound can be heard. I'm not sure if it's a bug or if I set it up wrong.

I am using win10 1909,Asus 7.1 sound card, win10 system has been set to 5.1 mode. The sound card is directly linked to the 6 monitor speakers.

I also have a question if I use ffmpeg to convert video to 5.1 channel, can you give me an example? Thank you very much.

**Comment by AndrewRH** [comment]
I'm afraid I don't have any ffmpeg scripts to share for that.  Perhaps you can give us more details about the ffmpeg script you're using and we can try it too or offer suggestions
