### ISSUE TITLE
Periodic lag in high resolution hap video playback

### ISSUE THREAD

**Issue by jnissin** [RenderHeads/UnityPlugin-AVProVideo#391]
I am attempting to play a 3840 x 3840 resolution hap encoded video file in Unity, which is playing fine most of the time but the game freezes periodically apparently due to Garbage Collect (GC) from MediaPlayer.Update. The interval between consecutive GC calls becomes shorter, from 15-30 seconds to 6 seconds, when the video content is more dynamic (changes more rapidly).

When viewed in the profiler on macOS the GC calls track down to: `MediaPlayer.Update() -> OSXMediaPlayer.Update() -> OSXMediaPlayer.AVPPlayerUpdate()`, which can take up to 930 ms to execute. On Windows we are encountering the same problem on our more powerful machine, but I haven't had the chance to run deep profile on that machine yet.

We are using a single MediaPlayer and a Display uGUI component to show the video. On Windows we are using Direct Show as the Preferred Video API.

If this is a problem we can solve by moving to hap-q or other video formats that might have a better performance I am interested to hear those suggestions as well.

**Setup**
 - Unity version: 2019.3.7f1 
 - AVPro Video version: 1.11.2
 - Operating system version:
   - macOS Mojave 10.14.6 
   - Windows 10 Pro 
- Device model: 
  - macOS: 15" MacBook Pro 15-inch 2018, 2,2 GHz Intel Core i7, 16 GB 2400 MHz DDR4, Radeon Pro 555X 4 GB, 512 GB SSD
  - Windows: Windows 10 Pro, Intel Core i9, 32GB DDR4, Quadro RTX 6000, 1 TB NVMe SSD

**Video specs**

The video was transcoded using ffmpeg with the following command:

```
ffmpeg -i Laila_Base_FullSet_01.mp4 -vcodec hap -format hap -chunks 4 ~/Desktop/Laila_Base_FullSet_01.mov
```

ffprobe output:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Assets/StreamingAssets/BaseLayerVideos/hap/Laila_Base_15min_06_Color.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf58.29.100
  Duration: 00:16:27.22, start: 0.000000, bitrate: 386788 kb/s
    Stream #0:0(eng): Video: hap (Hap1 / 0x31706148), rgb0(progressive), 3840x3840, 386659 kb/s, SAR 1:1 DAR 1:1, 30 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : Lavc58.54.100 hap
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : #Mainconcept MP4 Sound Media Handler
```

**Screenshots**

![Screenshot 2020-06-22 at 22 13 03](https://user-images.githubusercontent.com/13102334/85326437-f8988400-b4d5-11ea-9545-1a0f3c967507.png)

**Comment by MorrisRH** [comment]
I'm afraid I was unable to reproduce this. I had a 3840x3840 HAP video playing back in our demo scenes with no issues.

AVPPlayerUpdate's time is mostly spent handling the texture upload to GPU RAM which is driver level stuff and not something we really have control over. The fact that is shows up so strongly in your trace and that you mention GC issues (on the native side AVProVideo has nothing to do with the GC, that's Unity side only) suggests you're seeing some serious memory contention issues.

It would be great if you could try your video in one of our demo scenes and if you're still seeing the issue, try and get a trace using the "Time Profiler" tool in Instruments.
