### ISSUE TITLE
Streaming, stalling doesn't resume Windows

### ISSUE THREAD

**Issue by LukasRoper** [RenderHeads/UnityPlugin-AVProVideo#394]
**Describe the bug**
When running either through editor or Windows I can frequently notice oddities when trying to load a stream. Playback will begin but then get stuck at a certain point. At that point, buffering will occur but seems to keep looping as if stuck between which stream to display. Curious if this is an issue AVPro side or to do with how the stream is setup?

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.4
 - AVPro Video version: 1.11.3
 - Operating system version: Windows 10 x64
 - Device model: PC Desktop (have noticed happening to two machines)
 - Video specs (resolution, frame-rate, codec, file size): HLS stream (m3u8 file). Streams up to 4k. Happy to share a sample stream but not publicly. Have video of the buffering issue I can share (again not publicly as contains footage for a client). 

**To Reproduce**
1. Get a stream and just run it in Windows.

**Videos**
Happy to share privately though can perhaps see if I can recreate with something less client sensitive. I've emailed the video though to the support address.

**Comment by LukasRoper** [comment]
Just to add, I did notice it will eventually sort itself out but it stalls for like 2-3 minutes before resuming. It will then playback in a fairly stable manner. Is the stalling behaviour adjustable in any way as such a massive stall is odd. Still not sure why the buffer progress keeps resetting as shown in the video I sent either.

**Comment by AndrewRH** [comment]
2-3 minutes of stalling is very unusual, and not something we have ever seen.  Thanks for sending over the video by the way.

Are you able to replicate this behaviour with:
1) our demo scenes in Unity
2) any other HLS media?

Thanks,

**Comment by LukasRoper** [comment]
I have tried in the sample scene and noticed the same. On Android/iOS our existing streams seem fine (but whether the 4K version is used is probably a question as device download speed is more likely to be limited).

I've not tried with another stream. I can do but not sure if it helps diagnose the issue. I've provided one of our streams via email which may be worth trying.

Will have an investigation though of our stream files as maybe the high quality stream is just too big.

**Comment by LukasRoper** [comment]
Though if we play the transcode .mp4 file itself, it barely buffers at all so I'm not sure bandwidth is the problem here.

**Comment by aracid** [comment]
Hi there

Has this issue been resolved because I'm seeing similar results.
Media starts fine and then shortly the media stalls once it reaches the end of the buffer.

![image](https://user-images.githubusercontent.com/4083949/115175399-bdc49580-a07f-11eb-81d7-95cbebbbc11d.png)
![image](https://user-images.githubusercontent.com/4083949/115175410-c3ba7680-a07f-11eb-96b2-f41d02cc36e9.png)

[AVProVideo] Initialising AVPro Video v2.0.11 (native plugin v2.0.10f1-trial) on NVIDIA TITAN X (Pascal)/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor
Unity 2020.1.8f1

Thanks in advance
Brian
