### ISSUE TITLE
m3u8 Stream will play on Windows but not on Android

### ISSUE THREAD

**Issue by THPictures** [RenderHeads/UnityPlugin-AVProVideo#398]
Hi,
I'm doing a Project with Videomapping in Unity. I have one gameobject with the media player component and an "apply to material" component. The URL I'm using is a custom one from an URL-shortener, which leads to an HTTPS URL addressing an index.m3u8.
When I Build the App for Windows, everything just works fine and I get the live video. If I build it for Android, there is no Video at all. I've tried the "Mapping3D" demo scene on Android and it works well. Is there any setup I missed? I've tried both settings: "MediaPlayer" and "ExoPlayer". Do I have to use the ExoPlayer API and program something there to get it working?

Thanks in advance.

**Comment by AndrewRH** [comment]
Did you try accessing the full media URL on Android instead of the shortened version?

Thanks,

**Comment by THPictures** [comment]
I just tried it and it works. Any suggestions why the shortened URL will
work just fine on windows but not on Android?
Would be very cool or, for my case, even necessary to be able to change the
link even when the app is already delivered.

Andrew <notifications@github.com> schrieb am So., 28. Juni 2020, 21:18:

**Comment by RenderHeadsSte** [comment]
Have you tried the option to force the media type to HLS/m3u8? Android relies on an extension on the path/url to know what it is loading...I am guessing your shortened url doesn’t have the m3u8 filename extension.

**Comment by THPictures** [comment]
I honestly never touched that setting again, since it worked on windows,
but I did now and unfortunately it has no impact. I also tried to customize
the shortened URL to end with index.m3u8 but then the shortener would say
this is an invalid URL.

Ste Butcher <notifications@github.com> schrieb am Mo., 29. Juni 2020, 09:54:

**Comment by THPictures** [comment]
UPDATE: I think, I have solved the problem. An URL ending on index-m3u8
seems to be fine for Android and is also compatible with the url shortener.

Thanks for your nice and fast support. It was very important to me to get
these issues fixed before buying the asset for 400 Euros.

Thorbjörn Ruppel <th.ruppel@googlemail.com> schrieb am Mo., 29. Juni 2020,
10:20:

**Comment by RenderHeadsSte** [comment]
That's great news.  Glad we could be of help to nudge in the right direction for a fix :)
