### ISSUE TITLE
Bitrate and Quality control when using the H264 codec  

### ISSUE THREAD

**Issue by Alexandre69** [RenderHeads/UnityPlugin-AVProVideo#4]
Dear RenderHeads Support,

we are working with AVPro Movie Capture for quite some time now but for a new project we need to get a .mp4 movie not .avi anymore.
Previously we were using the x264 codec (https://sourceforge.net/projects/x264vfw/) so we could control the quality and the size of the movie pretty easily but the plugin does not allow use to switch to mp4.

Using the Microsoft H264 and mp4, there is no control on the quality and the bitrate, which does not work for us as the move is way too big with default settings.

1 - is there a possibility to change the bitrate and the quality with Media Foundation h264 in the very close future?
2 - is there an alternative to get mp4 with x264vfw ?

Thank you for your help and time !

**Comment by AndrewRH** [comment]
Hi Alexandre,

This Github Issues is actually for AVPro Video.  We don't have one yet for AVPro Movie Capture but I'll answer here anyway for now.  We plan to create Issues pages for all of the plugins, but for now it's probably best to use the forums or email us.

I'll answer your questions below:

> 1 - is there a possibility to change the bitrate and the quality with Media Foundation h264 in the very close future?

You are correct that this is not available currently.   This is on our roadmap, but we're really busy right now so I'm not sure when we will get around to it.  Definitely in the next couple of months.

> 2 - is there an alternative to get mp4 with x264vfw ?

Yes, I think in the documentation we have written about this. It is possible to install a plugin called GDCL-MP4Mux.  Then you should be able to set the extension to MP4.  You should be able to download the installer from here:
https://github.com/roman380/gdcl.co.uk-mpeg4/tree/master/_Bin

I hope that helps.  Let me know if you have any other questions.

Thanks,
