### ISSUE TITLE
How to decrease the video switching and decode & display lag

### ISSUE THREAD

**Issue by spaul13** [RenderHeads/UnityPlugin-AVProVideo#40]
I am using AVProVideo for my project to display 360 videos on Unity Editor on windows platform. After every Mouse click, I am switching the videos and I have observed the time taken from changing the video file path to the first frame of the video becoming ready to play is almost 40 ms.
I want to get it by less than 16 ms. Is there any way or configuration to increase the number of threads or using direct GPU acceleration to decrease the video switching and playing time?

FYI, I have a 4096*2048 360 video which contains only one I frame. I will be happy to answer you if u have any further questions. Any help on this regard will be highly helpful.

**Comment by AndrewRH** [comment]
Do you mean that your video contains only I-frames, or that it only contains a single I-frame?  

If you are using Windows 8.1 or above then it should be using multi-threading, GPU acceleration and asynchronous loading already.  Generally to get videos to load quickly, you need to have the video encoded in as simple way as possible.  This means disabling advanced encoding features, or not having any B or P frames in the video.  Having a lower bit-rate video may also help.  All of these encoding features can be done using a tool like FFMPEG which has a "fastdecode" tuning profile.  No having audio in the video file can also help.  Having the mp4 encoded for "fast start" can also help.

Here is an example FFMPEG script that could be used:

ffmpeg -hide_banner -y -i %1 -pix_fmt yuv420p -c:v libx264 -crf 12 -preset slow -tune fastdecode -x264-params "keyint=1" -an -movflags faststart %1-h264.mp4

Another thing you can do is use a second MediaPlayer to load the video before the first video has completed and then switch to it when the first frame texture becomes available.

I hope this helps.  If you have further questions just let us know.

**Comment by spaul13** [comment]
@AndrewRH, really thanks for the detailed reply. It's really helpful. About the encoded video advice, I tried different parameters and configurations as you specified (different CRF) but the decoding time nominally changes (marginally). 

Although you mentioned its already using GPU acceleration while on the performance tab under GPU inside video decode part I have n't seen any percentage of GPU usage. Am I missing some configuration parameters (maybe some Autographics API I have to use)? I tried on two devices one with Intel UHD and another has powerful NVIDIA GPU both cases I didn't see any GPU usage inside the performance tab. Please tell me if I am missing something. (Although I am using Windows 10)

FYI, My video contains just one I frame. Just to reduce the decoding time (No dependency) I use just one I frame as you mentioned)

I am thinking for adding a few more I frame inside a video. On this regard, can you please tell me how I can specifically display one particular frame on the sphere texture? We can consider two scenarios
1) First is a video with 4 I frames encoded with fps 60, after showing the first frame how to exactly show the third frame from the video onto the screen.
2)If the video contains (IPPP) one I and 3Ps all P frames directly referenced to the I frame then, similarly after showing the first frame how to exactly show the third frame from the video onto the screen.

If you can clear these doubts, it will be highly helpful. Again thanks a lot for the reply.
