### ISSUE TITLE
Jar conflict with Vuplex

### ISSUE THREAD

**Issue by jolly17ify** [RenderHeads/UnityPlugin-AVProVideo#401]
Hi

I was facing the issue mentioned here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/306 and I followed the suggestion mentioned but after that, I get the following error:

AndroidJavaException: java.lang.VerifyError: Verifier rejected class com.RenderHeads.AVProVideo.AVProMobileVideo: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean) failed to verify: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean): [0x2F] cannot access instance field boolean com.RenderHeads.AVProVideo.AVProVideoPlayer.m_bShowPosterFrame from object of type Unresolved Reference: com.RenderHeads.AVProVideo.AVProVideoExoPlayer (declaration of 'com.RenderHeads.AVProVideo.AVProMobileVideo' appears in /data/app/"xxxbundle-idxxx"/base.apk

 - Unity version: 2019.2.3f1
 - AVPro Video version: 1.11.0
 - Operating system version: Windows 10
 - Device model: Oculus Go

**To Reproduce**
1. Remove exoplayer2-hls.jar and so that there are no build errors(Suggested in https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/306).
2. Change Preferred video api to Media Player instead of Exo Player in every media player component used in the project.
3. Get error at app start.

**Logs**
AndroidJavaException: java.lang.VerifyError: Verifier rejected class com.RenderHeads.AVProVideo.AVProMobileVideo: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean) failed to verify: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean): [0x2F] cannot access instance field boolean com.RenderHeads.AVProVideo.AVProVideoPlayer.m_bShowPosterFrame from object of type Unresolved Reference: com.RenderHeads.AVProVideo.AVProVideoExoPlayer (declaration of 'com.RenderHeads.AVProVideo.AVProMobileVideo' appears in /data/app/"xxxbundle-idxxx"/base.apk

**Comment by RenderHeadsSte** [comment]
Could you send over the logcat output please?

**Comment by jolly17ify** [comment]
AndroidJavaException: java.lang.VerifyError: Verifier rejected class com.RenderHeads.AVProVideo.AVProMobileVideo: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean) failed to verify: com.RenderHeads.AVProVideo.AVProVideoPlayer com.RenderHeads.AVProVideo.AVProMobileVideo.CreatePlayer(int, boolean, boolean, int, boolean): [0x2F] cannot access instance field boolean com.RenderHeads.AVProVideo.AVProVideoPlayer.m_bShowPosterFrame from object of type Unresolved Reference: com.RenderHeads.AVProVideo.AVProVideoExoPlayer (declaration of 'com.RenderHeads.AVProVideo.AVProMobileVideo' appears in /data/app/"xxxbundle-idxxx"/base.apk

**Comment by RenderHeadsSte** [comment]
Could you send over the **full** log output please :)  A snippet is rarely useful.

Are you removing all exoplayer library files?  It is a bit unclear if you are just removing the single file 'exoplayer2-hls.jar'.

**Comment by RenderHeadsSte** [comment]
@jolly17ify We hope to have a possible fix coming for this issue later today in version 1.11.4
