### ISSUE TITLE
WebGL + Dash - cannot stop or close video properly

### ISSUE THREAD

**Issue by MikeSzym** [RenderHeads/UnityPlugin-AVProVideo#404]
EDIT: Since we found a way to use HLS correctly the issue below has little (if any) importance to us. Leaving it here as a bug report but we are not looking for a solution to it anymore

When attempting to close a streamed dash video - or when unloading the scene with video player - I get hit with the following errors and the video continues to play in background. Upon reopening the video - it will play multiple times over each other:

[1326][SourceBufferSink] getAllBufferRanges exception: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
Error: video not supported (errorcode=4) color:red;
[1327][StreamController] Video Element Error: MEDIA_ERR_SRC_NOT_SUPPORTED (MEDIA_ELEMENT_ERROR: Empty src attribute)
[1327][StreamController] [object MediaError]
[1327][SourceBufferSink] Failed to remove source buffer from media source.
https://gyazo.com/6978c5a0d2a02601818999e4e6e2b956

I attempt to close the video in various ways, but they all bug out in the same way way:
- before unloading the scene
- OnDestroy in my video controller (after scene is unloaded)
- and the plugin itself closes it in its own OnDestroy

I'm using:
Unity 2019.4.1 LTS
Latest AVPro version (updated yesterday)
Dash 2.8.0 library, but also tested with 3.1.1
Browser - Chrome, Firefox, doesn't make any difference
Replicated on several devices

What I tried:
- No issues whatsoever in the Editor. No warnings, nothing. Flawless
- No issues whatsoever on Android. No warnings, nothing. Flawless
- Dash 2.9.3; 3.1.1 -> both crash (library not defined or sth along those lines)

Video URL... Cannot provide, sorry. NDA, work for hire, video tokenized per IP and only works for an hour... 

EDIT: Did manage to get HLS working which "resolves" the issue for us

Cheers,
Mike

**Comment by AndrewRH** [comment]
Thanks for reporting this.  We will still be investigating in case this is something we can improve.

Cheers,
