### ISSUE TITLE
Color space issue with VP9 video file

### ISSUE THREAD

**Issue by julienkay** [RenderHeads/UnityPlugin-AVProVideo#405]
When playing back a video, I'm having what looks like color space issues.

This is the original video:
https://storage.googleapis.com/immersive-lf-video-siggraph2020/welder/video/mdi_rgb_000.mp4

This is what I'm getting with the AVPro MediaPlayer:
![AVProVideoPlayer](https://user-images.githubusercontent.com/26555424/86500688-26fa4700-bd93-11ea-9e91-a3d788bd3bc6.png)

This is what I'm seeing when using Unity's native VideoPlayer:
![UnityVideoPlayer](https://user-images.githubusercontent.com/26555424/86500700-37122680-bd93-11ea-87ff-40a8934db2d8.png)

And finally another version from Windows Movies & TV app:
![win_movies tv](https://user-images.githubusercontent.com/26555424/86500783-d7684b00-bd93-11ea-9f4b-78dd73665b2a.png)

When playing back the original video in Chrome, it seems to match the screenshot from the windows app. Judging from that, I assume that is the most correct one. Any suggestions on what settings I need to change to get that result in AVPro?

**Setup:**
 - Unity 2019.3.14f1: 
 - AVPro Video v2.0.0-beta1
 - Windows 10
 - VP9, 1920x1080, 30FPS, 158MB

**Some more info from ffmepg about the video:**
Metadata:
major_brand     : isom
minor_version   : 512
compatible_brands: isomiso2mp41
encoder         : Lavf58.44.100
Duration: 00:00:30.03, start: 0.000000, bitrate: 44347 kb/s
Stream #0:0(und): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, progressive), 1920x1080, 44347 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 11988 tbc (default)

**Comment by AndrewRH** [comment]
Hi,

Cool, that's a very interesting siggraph paper!

I think this is a bug in beta-1.  Beta-2 is coming out next week but until then there are a few workaround for this colour issue that you could try:

1) Check Colorspace from Linear to Gamma (in Player Settings > Other) 
OR
2) Change the video API in Platform Specific > Windows section on the MediaPlayer component from WinRT to Windows Media.

I hope that helps?

Thanks,

**Comment by julienkay** [comment]
Switching to Gamma fixed the issue for now, thanks a lot. 👍 

Do you have any more info on why that happens, and what the fix is in the newer versions, or something for me to read up on. Trying to understand the issue (and maybe also possibly knowing how i can work around the issue with the Unity video player in linear space).

**Comment by AndrewRH** [comment]
bump i need to check this again
