### ISSUE TITLE
Access denied opening galler file on android

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#406]
**Describe the bug**
Cant open mp4 file from android gallery path UnauthorizedAccessException any idea why?
My phone upgraded to android 10 over night, and now this happened, stupid android.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3
 - AVPro Video version: dont know
 - Operating system version: android 10
 - Device model: samsung
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. open a video file located at /storage/emulated/0/DCIM/Camera/20200704_230148.mp4
2. UnauthorizedAccessException

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
This seems to be the same issue talked about here:
https://forum.unity.com/threads/android-10-and-scoped-storage-missed-features-in-unity-2019.749333/

Perhaps the manifest "requestLegacyExternalStorage" value solves it for you?

**Comment by nsmith1024** [comment]
Yes, that solved it

**Comment by AndrewRH** [comment]
Awesome!  Thanks,
