### ISSUE TITLE
Video Lags after adding URP for post processing.

### ISSUE THREAD

**Issue by umresh** [RenderHeads/UnityPlugin-AVProVideo#407]
We are trying to add an outline to the 3d objects in the scene along with a video(URL) and using post-processing(URP) for the outline. Video plays smoothly in the editor but I build and play in android video lags where audio is played first and then video(texture) is rendered, audio and video are not synced. When I remove postprocessing it plays as expected. Tried switching from mediaplayer to exoplayer.

 - Unity version:  2019.3.5.f1
 - AVPro Video version: 1.11.3

**Comment by AndrewRH** [comment]
Hi,

Have you tried profiling your app?  It doesn't sound like a problem with AVPro Video, but just an issue with the device struggling to keep up.

If you profile you may see that there is a high load on the GPU.  The only option we have to use less GPU for the video playback is to enable OES mode.  We have a section in the documentation about how to enable this mode.  It doesn't work in the trial version by the way (in case you're using that).

It may also be that some shaders are being compiled / loaded which leads to the delta between video and audio frames.  You could try delaying the start of your video playback a bit?

Thanks,

**Comment by RenderHeadsSte** [comment]
@umresh anything to report on this?

**Comment by RenderHeadsSte** [comment]
We will be closing this issue soon due to lack of response.
