### ISSUE TITLE
Stuttering in Firefox

### ISSUE THREAD

**Issue by MikeSzym** [RenderHeads/UnityPlugin-AVProVideo#408]
Video Playback across wide range of formats is stuttering on Firefox. Here's an example - issue stars from 00:04, it's like it's going back and forth between frames
https://gyazo.com/215102eae6296cd9fadd5378c4831480
This is an HLS test stream from Apple, it's not even a high quality stream. It's also straight from your documentation:
http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

(This might be the same as issue #360 which is stale now)

Similar issue has been reported on Unity Forums using their built-in video player since... 2015? It's actually why we bought your plugin in the first place - but this issue does not want to go away

We really tried everything:
- We have seen it from Unity 2019.2.something, across all versions of 2019.3, now at 2019.4.2 - no difference
- 360p, 480p, 720p, 1080p, HLS, Dash - all experience the same issue
- All "typical encodings" have that issue - on Firefox only. Chrome, Edge - no issues
- Firefox - multiple versions tested, this problem has been kicking our asses for months
- Windowed or fullscreen make no difference whatsoever

VP8 encoding was the *only* format that we have seen working 100%. Maybe VP9 as well, but didnt test it

Plugin settings - nothing out of the ordinary. Videos from the same URL play just fine in editor, Chrome Windows, Chrome Mac,, Edge, Android... There is nothing wrong with them

**Comment by InceptSolutions** [comment]
Same issue here, I think that this is a compatibility issue between Unity WebGL <> Firefox Engine.

**Comment by PacifistWarrior** [comment]
Wanted to report, this issue has been marked as closed, but as of today, I am still seeing this issue. 

Latest version of Firefox. Unity 2019.48f1. Latest version of AVPro video.

Trying various video codecs now to see if I can find a solve.

**Comment by Twyker** [comment]
@PacifistWarrior Did you ever find a fix for this?
