### ISSUE TITLE
problem url mdp

### ISSUE THREAD

**Issue by ilsanto17** [RenderHeads/UnityPlugin-AVProVideo#409]
Problem description:

When I try to run url mdp the video freezes after a few seconds. is it any bug?

System Information:

AVPro Video: plugin v1.9.17t scripts v1.11.0
Target Platform: Android
Unity: v2019.4.1f1 WindowsEditor
OS: Desktop - H110 Gaming Infinite(MS-B915) (Micro-Star International Co., Ltd.) - Windows 10  (10.0.0) 64bit - Italian
CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz - 8 threads - 8142KB
GPU: NVIDIA GeForce GTX 1060 6GB - NVIDIA - Direct3D 11.0 [level 11.1] - 6052KB - 16384

**Comment by AndrewRH** [comment]
Is it on Windows or Android that you're seeing this freeze?

If Android, please could you give details about the device.

And could you please explain what happens exactly - does it just freeze and never recovers?  Does audio stop too?

Could you share the MDP you're using.  Have you tried other MDP streams?

Thanks,

**Comment by RenderHeadsSte** [comment]
@ilsanto17 bump on Andrews questions/requests

**Comment by ilsanto17** [comment]
With others it goes. So the problem is my problem.
But I noticed that a hls in webGl doesn't work for me. I followed the guide the hls.min.js file is imported but I don't see anything.

**Comment by AndrewRH** [comment]
I'm afraid that doesn't give us much to go on.
