### ISSUE TITLE
load new URL in runtime

### ISSUE THREAD

**Issue by adrw2** [RenderHeads/UnityPlugin-AVProVideo#410]
Hi,

in Runtime, if i want to change the URL to a new one it appears a new "load" button in the media player.
How can i access to that button from script? or load it automaticaly to run the new link, cause auto-open/auto-play functions do not work.

thanks!

**Comment by AndrewRH** [comment]
Have a look at the included demo script "ChangeVideoExample.cs" - it shows how to do this.

basically:

`_mediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.RelativeToStreamingAssetsFolder, filePath, true);`

Does that help?

Thanks,

**Comment by RenderHeadsSte** [comment]
@adrw2 anything to report on this?
