### ISSUE TITLE
Screen becomes crash

### ISSUE THREAD

**Issue by caihuazei2012** [RenderHeads/UnityPlugin-AVProVideo#412]
**Describe the bug**

When the MediaPlayerEvent.EventType.FirstFrameReady event fire,I SetActive NGUITextrue True;

But Crash on Android phone screen In the first few frames;Look at the picture below。

Looking forward to your answer
**Your Setup (please complete the following information):**
 - Unity version: 2018.4.2
 - AVPro Video version: 1.10.2
 - Operating system version: Android8.0
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![793c7b26-bd43-4fc8-a553-7a678759ed0e](https://user-images.githubusercontent.com/63900825/87035580-1f67f180-c21c-11ea-99f4-65a2f19a94e1.png)
![企业微信截图_15942663786758](https://user-images.githubusercontent.com/63900825/87035591-2262e200-c21c-11ea-9a95-97a02be40e62.png)
![企业微信截图_15942957251695](https://user-images.githubusercontent.com/63900825/87037077-458e9100-c21e-11ea-8523-b4f66e849f4d.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Do you mean a crash (like app quits), or just that the video appears to be corrupt?  Does the corruption dissapear and the video display correctly after the first few frames?

Perhaps you could try to upgrade AVPro Video to the latest version?

Have you tried with our sample media files?

Thanks,

**Comment by caihuazei2012** [comment]
> Do you mean a crash (like app quits), or just that the video appears to be corrupt? Does the corruption dissapear and the video display correctly after the first few frames?
> 
> Perhaps you could try to upgrade AVPro Video to the latest version?
> 
> Have you tried with our sample media files?
> 
> Thanks,

just the first few frames appears to be corrupt,after first few frames display ok

**Comment by caihuazei2012** [comment]
> Do you mean a crash (like app quits), or just that the video appears to be corrupt? Does the corruption dissapear and the video display correctly after the first few frames?
> 
> Perhaps you could try to upgrade AVPro Video to the latest version?
> 
> Have you tried with our sample media files?
> 
> Thanks,

I use 1.10.2 version

**Comment by caihuazei2012** [comment]
sory,It is my own problems
