### ISSUE TITLE
AVPro + Vimeo SDK doesn't work on my iPad 4

### ISSUE THREAD

**Issue by savek1986** [RenderHeads/UnityPlugin-AVProVideo#413]
Hi,

in past we resolve this issue:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/337

Now, I have built app for iOS and I tried to install it on my iPad 4.
App works but when I open the scene with AVPRO and Vimeo SDK, that doesn't work; I can't see video. The screen remains grey.

Can you help me, please. 
Thanks

**Comment by AndrewRH** [comment]
Hi,

I'm afraid that doesn't give us much to go on.

Some information which would help:

1) Which version of Unity?
2) Which version of AVPro Video?
3) Which version of Vimeo SDK?
4) Is it a HTTPS or HTTP URL?
5) Did you check the error logs?   
6) Did you try with other media?

Thanks,

**Comment by savek1986** [comment]
Unity version is 2018.2.14f1
AVPro version 1.11.3
Vimeo SDK version 0.9.5
HTTPS url
No
No

**Comment by savek1986** [comment]
if you need, I can share with you the repository

**Comment by savek1986** [comment]
However, I invite you.
Thanks

**Comment by savek1986** [comment]
I have added AVPro Debug Overlay component and I have noted that it doesn't show the name of video, so I trust that AVPro player can't find file path.

**Comment by AndrewRH** [comment]
Please check the error logs via XCode console to see what errors are reported, and also trying other media to see if the problem is with the media itself.  It's worth also trying non-adaptive media of different resolutions to see whether those work to try to pin-point what is failing.

Thanks,

**Comment by savek1986** [comment]
I don't have Mac for building because I have only PC, so I'm using Unity Cloud to build for iOS.
So I can give you only unity Cloud Build Log: 
[compact log.pdf](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4902598/compact.log.pdf)

**Comment by AndrewRH** [comment]
> I have added AVPro Debug Overlay component and I have noted that it doesn't show the name of video, so I trust that AVPro player can't find file path.

This would indicate that the path is not being set by Vimeo SDK on the AVPro Video MediaPlayer component.   Because the display code for the path in DebugOverlay component is simply:

GUILayout.Label(System.IO.Path.GetFileName(_mediaPlayer.m_VideoPath));

This is looking like a problem with the Vimeo SDK rather than a problem with AVPro Video.

It's worth also trying non-adaptive media of different resolutions to see whether those work to try to pin-point what is failing.

Thanks,

**Comment by savek1986** [comment]
I have tried non-adaptive mode but it's same.

**Comment by savek1986** [comment]
Hi, 
I solved the path issue, but video doesn't work on iPad.

**Comment by AndrewRH** [comment]
> Hi,
> I solved the path issue, but video doesn't work on iPad.

oh how did you solve it?  perhaps it can help other people.

IPad4 is pretty old - I don't think it supports videos over 1080p resolution...I'm not sure if that could be the reason why it's not working.  AVPro Video certainly supports iPad 4.

**Comment by savek1986** [comment]
no I enject my url in Vimeo script directly instead of putting it in my script. 
I don't think resolution is the problem because I try to build after setting Vimeo player in 360pi too, instead of adaptive mode.
