### ISSUE TITLE
AutoStart and Loop is enabled but my video ends upon completion and does not restart

### ISSUE THREAD

**Issue by RyBK** [RenderHeads/UnityPlugin-AVProVideo#414]
I have an object that I have applied the avpro mediaplayer to that is triggered to play upon entering the specified collider space and stops the mediaplayer upon exit of the specified collider space.  

Before I integrated the AVPro media player, I was able to have the video restart every time I triggered the player no matter when I exited the trigger space to stop the video.   However, when I integrated the AVPro media player, upon first entry the video plays perfectly and upon exit it stops (as intended), but when I re-enter the video just shows a frozen (paused) frame from when I had previously exited and does not play no matter how long I wait.  

Is there a way to get this media player to restart upon autoplay?

Apologies if there is a simple and obvious solution (i'm new at all of this).

**Comment by AndrewRH** [comment]
Hi which platform is this on?

**Comment by RyBK** [comment]
WebGL

**Comment by AndrewRH** [comment]
Can you not tell it to rewind and play?

**Comment by RyBK** [comment]
Let me see how that can be done (i'm a newb) and I'll get back to you if I solve or run into issues.  Thanks!

**Comment by AndrewRH** [comment]
@RyBK did you have any luck resolving this looping issue?

**Comment by RyBK** [comment]
@AndrewRH I have a friend looking into it for me, so shouldn't be a problem anymore. Thanks for the help!

**Comment by AndrewRH** [comment]
Okay great, best of luck!
