### ISSUE TITLE
rtsp and rtmp steams on webgl with unity3d

### ISSUE THREAD

**Issue by absinthejt** [RenderHeads/UnityPlugin-AVProVideo#415]
We are recently trying to develop webgl application with unity3d, we are using AVpro as a 3D interface player, but only HLS video streams are supported, I would like to ask you if AVpro has any plans to access rtsp and rtmp video streams for unity3d on webgl?
thanks:)

**Comment by MorrisRH** [comment]
Closing as we no longer support WebGL
