### ISSUE TITLE
Seeking in a video with ambisonic (TBE) embedded audio results in desync betweeen audio and video

### ISSUE THREAD

**Issue by Rulfer** [RenderHeads/UnityPlugin-AVProVideo#417]
**Describe the bug**
Seeking in a video with Matroska embedded audio (Facebook 360 ambisonic) causes a wide array of potential issues. The audio can desync, the video can freeze while the audio plays, or the entire project freezes. This has been tested with internal videos, as well as the included Demo Scene 13 and the video "FantasyStereoFB360". You can try to launch Demo Scene 13 and jump around in the video, and you can see that the video quite often freezes while the audio plays, or the audio simply doesn't seek to the right point in the video. 

I'm using the paid for AVPro Video plugin. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.15f1
 - AVPro Video version: 1.11.3
 - Operating system version: Windows 10 Pro - 1903

**Project settings**
Unity
Audio: Spatializer Plugin is OculusSpatializer
Audio: Ambisonic Decoder Plugin is OculusSpatializer

AVPro Windows Platform
Preferred Video API: Media Foundation
Hardware Decoding: True
Use Low Latency: True
Audio Mode: Facebook Audio 360
Channel Mode: TBE_8_2 (Our videos are encoded for this)
Audio Device Name: Default

AVPro Android Platform 
Preeferred Video API: Exo Player
File Offset: 0
Use Fast OES Path: True
Audio Mode: Facebook Audio 360
Channel Mode: TBE_8_2

**Why I need this**
I'm currently working on a project where the user can jump between different videos in a scene. Imagine you are viewing a concert in VR, and there are multiple cameras you can jump between to get different perspectives of the concert. Every camera have their own audio recording to simulate what its like to view the concert from that position. 
When the user changes position to another camera we need to change both the video and the audio.
The concert shouldn't restart when the user changes position, but continue without interruption. 

**What I've tried**
 Seeking programmatically with Seek and SeekFast. This is what causes the bug mentioned.

Seeking via the Inspector. Here I clicked on the timeline available on the Media Player class. Same bug as with Seek and SeekFast. 

Having two different Media Players rendering two different videos at the same time. I wanted to test the behaviour when having multiple instances of the Media Player class, each rendering on their own sphere. The find was interesting. 
Lets call the Media Players for "Media Player A" and "Media Player B". If Media Player A loaded its video before Media Player B, then the audio of Media Player A can no longer be controlled. 
If I try to change the volume of Media Player A, or simply mute it, then it affects Media Player B instead of Media Player A for whatever reason. You can test this too in example scene 13 by duplication the media player there. It helps by having two different videos, but you can manually load one of the videos to ensure that they don't play at the exact same time just to make the testing easier.   
I also tried pausing the media players before changing the volume, even with a wait function in a coroutine. This didn't help. 

**To Reproduce**
1. Open AVPro demo scene "13_Demo_360StereoSpatialAudio"
2. Play the video "FantasyStereoFB360.mkv"
3. Via the Media Player component in the Inspector, simply click on the timeline or programmatically seek to anywhere in the video. This will result in the audio and video no longer being synchronized, the video freezing while the audio plays, or the editor crashing if you spam-click the timeline.

**Comment by AndrewRH** [comment]
Thanks for reporting this.  We're looking into it now.

By the way,
Audio: Spatializer Plugin is OculusSpatializer
Audio: Ambisonic Decoder Plugin is OculusSpatializer
I don't think these are needed or make a difference to AVPro Video using FB Audio 360 as we're playing audio directly to the system after it has been converted from 360 audio into stereo.

The issue of seeking causing desync - did you see that on Android as well, or just Windows?

Thanks,

**Comment by AndrewRH** [comment]
@Rulfer The issue of seeking causing desync - did you see that on Android as well, or just Windows?

**Comment by Rulfer** [comment]
Sorry for the late reply. 
I can confirm that this is not a bug on Android. I tested it on an android phone and Oculus Quest now, and can't see the desync on those devices. I can only replicate this bug in the editor and Windows builds.

**Comment by AndrewRH** [comment]
Thanks @Rulfer  I have replicated the issue on Windows, and we have a fix for it.  Can I send you an update DLL to test?

**Comment by Rulfer** [comment]
That would be great! I sent an email to unitysupport@renderheads.com with the subject "Issue 417 - Rulfer". Please send the DLL to that email address.

**Comment by AndrewRH** [comment]
losing this as it has been fixed in 1.11.4
