### ISSUE TITLE
Unity crash while playing 360 video H265

### ISSUE THREAD

**Issue by Jas-y** [RenderHeads/UnityPlugin-AVProVideo#418]
**Problem description:**  
- In a simple Unity project (version 2019.3.0b10) run on Windows MSI Laptop, using the Oculus Rift S and SteamVR, I use your 360SphereVideo prefab with default parameter settings and "Windows" selected in the "Platform Specific" tab of the AVPro-Video-Media-Player game object UI. My videos were recorded with the Garmin VIRB 360 and converted to mp4-H265-hevc(hev1). I have the HEVC extension app from Microsoft installed under my user/account and videos are playing fine on the default Windows MediaPlayer.  
- In Unity, up until last week, no problems were occurring, i.e. I could play my videos, rewind, stop, load, etc. within a C# script and also on the game object AVPro UI itself  (I have been working with your unity plugin for approx. 2 months now).  
- The PROBLEM: End of last week (or beginning of the current one - present date: 16-07-2020), the video freezes after a few seconds of playing. While on freeze, the time on the timeline from the AVProPlayer preview section still runs, and I can still operate in Unity (e.g. click on game objects), but once I stop the game, Unity crashes and I need to force stop the program from the task manager. The time after which it freezes varies from 1 second to 30 seconds. Other videos, such as the samples you provide in AVProVideoSamples folder, work okay. But as soon as I load one of my videos, the program crashes after a few seconds, sometimes even during the loading process.  
- I tried:  
1.  Starting a new Unity project with only a steamVR camera object and the 360SphereVideo prefab from a fresh import of AVPro from the asset store.  
2.  Uninstall-Reinstall HEVC extension app.  
3.  Re-encode video with ffmpeg command (resulting in mp4-H265-hevc(hvc1)) :  
`ffmpeg -i <infile> -c:v libx265 -crf 20 -tag:v hvc1 -c:a copy <outfile>`
4.  Repeated point (1) in a previous Unity version (2019.1.4f1).  
But the issue persists.  

**Setup:**
 - Unity version: 2019.3.0b10  
 - AVPro Video version: 1.11.1  
 - Operating system version: Windows10, 64bits,  i7-7700HQ, CPU 2.80GHz, RAM 16 Go  
 - Device model: MSI GT62VR 7RE Dominator Pro,  
 - Device Graphics: GeForce GTX 1070  
 - Video specs (resolution, frame-rate, codec, file size): duration: 2min14sec, size:  341 Mo
` Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, progressive), 5760x2880, 20653 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 29.97 tbc (default)`

**Logs**
No errors in the log

Please let me know if you need more info.
Thank you in advance!
Jason

**Comment by AndrewRH** [comment]
Hi @Jas-y,

Are you still having this problem?   It seems strange that it suddenly started happening.  I wonder whether a Windows/Driver update could be the cause?

1) Have you tried your project on another system?
2) Have you tried just making a new blank project and importing AVPro Video and trying to play your videos using some of the demo scenes?
3) Try upgrading Windows and GPU drivers?

Thanks,
