### ISSUE TITLE
Unity WebGL build does not trigger MediaPlayer EventType Change Subtitle hence subtitles from .SRT file not working in webGL.

### ISSUE THREAD

**Issue by basuarya** [RenderHeads/UnityPlugin-AVProVideo#419]
**Describe the bug**
Unity WebGL build does not trigger MediaPlayer EventType Change Subtitle hence subtitles from .SRT file not working in webGL.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.11f1 LTS
 - AVPro Video version: 1.11.3
 - Operating system version: Macintosh Catalina 10.15.6
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
I wonder if perhaps the SRT subtitles are just failing to load in WebGL at all.  

Are you loading them from a URL or from a local file?

Thanks,

**Comment by AndrewRH** [comment]
@basuarya 
I've just tested building the demo scene "11_Demo_Subtitles" for WebGL and running it locally in the browser (via Unity 2019.3.13).  The subtitles are loading correctly and triggering the event.

Perhaps you could see if this demo scene works for you?  This will help us narrow down the cause of the problem you're having.

**Comment by basuarya** [comment]
Hello Andrew,

So I am using Unity 2018.4.11f1. Do you think that could be the reason?

Also, when you tested the “11_Demo_Subtitles” scene, did you see the "MediaPlayer EventType Change Subtitle” event being triggered on the web console?


Sincerely,

Aryabrata Basu, Ph.D.
Visual Information Specialist II
Digital Visualization Laboratory

Emory Center for Digital Scholarship
Emory University

email: abasu5[AT]emory[dot]edu
web: spatiotemporalbasu.com/<http://spatiotemporalbasu.com/>

“Natura naturans…"












On Jul 21, 2020, at 10:30 AM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:



@basuarya<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbasuarya&data=02%7C01%7Caryabrata.basu%40emory.edu%7C401e3a06c10a4ff3c86e08d82d829314%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309386137630168&sdata=Rw5G4lzcw70k1Z0U83OJiSCyRsLt6xK%2F3CfmufKsCks%3D&reserved=0>
I've just tested building the demo scene "11_Demo_Subtitles" for WebGL and running it locally in the browser (via Unity 2019.3.13). The subtitles are loading correctly and triggering the event.

Perhaps you could see if this demo scene works for you? This will help us narrow down the cause of the problem you're having.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRenderHeads%2FUnityPlugin-AVProVideo%2Fissues%2F419%23issuecomment-661896280&data=02%7C01%7Caryabrata.basu%40emory.edu%7C401e3a06c10a4ff3c86e08d82d829314%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309386137640160&sdata=AFSvooUZ3l9Pig5HuZ5R1JMDJMTV0t%2FzmvZFX2vIx0Y%3D&reserved=0>, or unsubscribe<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABM57DHQ7OAIIIM5YEX4Z2DR4WQ7FANCNFSM4O6PZBVQ&data=02%7C01%7Caryabrata.basu%40emory.edu%7C401e3a06c10a4ff3c86e08d82d829314%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309386137640160&sdata=6Qoe8nEClpsnfBqZpM3mtcoPdDvHrYWjPkw6WQaPmjk%3D&reserved=0>.


________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by basuarya** [comment]
Hello Andrew,

To your question, I am loading the SRT file locally.


Sincerely,

Aryabrata Basu, Ph.D.
Visual Information Specialist II
Digital Visualization Laboratory

Emory Center for Digital Scholarship
Emory University

email: abasu5[AT]emory[dot]edu
web: spatiotemporalbasu.com/<http://spatiotemporalbasu.com/>

“Natura naturans…"












On Jul 21, 2020, at 10:16 AM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:



I wonder if perhaps the SRT subtitles are just failing to load in WebGL at all.

Are you loading them from a URL or from a local file?

Thanks,

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRenderHeads%2FUnityPlugin-AVProVideo%2Fissues%2F419%23issuecomment-661887972&data=02%7C01%7Caryabrata.basu%40emory.edu%7Cbed9b92b7bf742f6353008d82d809b9c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309377674443349&sdata=sLknXIKNRpSyegXC824ZkWaTs8IUKMbO1aMH2pWO4kc%3D&reserved=0>, or unsubscribe<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABM57DDCDFXHXCAQ2RMCD5TR4WPKLANCNFSM4O6PZBVQ&data=02%7C01%7Caryabrata.basu%40emory.edu%7Cbed9b92b7bf742f6353008d82d809b9c%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309377674453342&sdata=A3bUybTKQOVIDosa5Kx24Zqfeq%2BNwDTXo0yllUxP3FA%3D&reserved=0>.


________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by basuarya** [comment]
Hello Andrew,

So I tried building the scene all over again using Unity 2019.4.0f1 and the subtitles are still not playing.
I tried the demo scene and it works. I am perplexed as to why?

Kindly suggest.


Sincerely,

Aryabrata Basu, Ph.D.
Visual Information Specialist II
Digital Visualization Laboratory

Emory Center for Digital Scholarship
Emory University

email: abasu5[AT]emory[dot]edu
web: spatiotemporalbasu.com/<http://spatiotemporalbasu.com/>

“Natura naturans…"












On Jul 21, 2020, at 10:30 AM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:



@basuarya<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbasuarya&data=02%7C01%7Caryabrata.basu%40emory.edu%7C401e3a06c10a4ff3c86e08d82d829314%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309386137630168&sdata=Rw5G4lzcw70k1Z0U83OJiSCyRsLt6xK%2F3CfmufKsCks%3D&reserved=0>
I've just tested building the demo scene "11_Demo_Subtitles" for WebGL and running it locally in the browser (via Unity 2019.3.13). The subtitles are loading correctly and triggering the event.

Perhaps you could see if this demo scene works for you? This will help us narrow down the cause of the problem you're having.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRenderHeads%2FUnityPlugin-AVProVideo%2Fissues%2F419%23issuecomment-661896280&data=02%7C01%7Caryabrata.basu%40emory.edu%7C401e3a06c10a4ff3c86e08d82d829314%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309386137640160&sdata=AFSvooUZ3l9Pig5HuZ5R1JMDJMTV0t%2FzmvZFX2vIx0Y%3D&reserved=0>, or unsubscribe<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABM57DHQ7OAIIIM5YEX4Z2DR4WQ7FANCNFSM4O6PZBVQ&data=02%7C01%7Caryabrata.basu%40emory.edu%7C401e3a06c10a4ff3c86e08d82d829314%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637309386137640160&sdata=6Qoe8nEClpsnfBqZpM3mtcoPdDvHrYWjPkw6WQaPmjk%3D&reserved=0>.


________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).
