### ISSUE TITLE
Playlist Media Player does not work with fewer than 3 videos

### ISSUE THREAD

**Issue by chuakc92** [RenderHeads/UnityPlugin-AVProVideo#421]
I'm using the 14_Demo_PlaylistTransitions.scene to learn how to implement playlists. I removed one of the default items (2 total) in the playlist and it plays the first video fine, but after that, it enters into an infinite loop and no longer plays any videos.

![a](https://user-images.githubusercontent.com/17212124/87879436-67bba800-c9b0-11ea-9f8d-70b3f1526813.png)

I found that I have to add more than 3 videos in order for the playlist to successfully work. Even if I do that, it ignores the first video on the first run and skips straight to the 2nd. After the playlist finishes, it will play the first video.

**Comment by AndrewRH** [comment]
Thanks for reporting this issue.  Is this happening with the latest version of AVPro Video?

**Comment by chuakc92** [comment]
Andrew, it appears I'm using 1.10.3. I'll have to ask my colleague for the later version and I'll test it out again.

**Comment by AndrewRH** [comment]
Hi @chuakc92 do you have any more details?  I've tested here on Windows and it's working just fine in the Editor.

Useful information would be:
1) AVPro Video version
2) Unity version
3) Platform and OS version

Thanks,

**Comment by chuakc92** [comment]
Hey Andrew, I'm on 1.11.3 now and the issue seems to have been fixed. The issues were happening on 1.10.3. 

Apologies, here were the information you requested:
AVPro Video version : 1.10.3
Unity version: 2019.1.14f1
Platform and OS version: PC, Windows, Linux Standalone platform, Windows 10

**Comment by AndrewRH** [comment]
Okay thanks, I think it was a bug in an older version.  Glad it's working for you now.  I will close this issue but if you spot anything else you can post another issue.

Thanks!
