### ISSUE TITLE
Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

### ISSUE THREAD

**Issue by JanOwiesniak** [RenderHeads/UnityPlugin-AVProVideo#425]
**Describe the bug**

Started a video from web (link below) and application crashed with `Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`. This is only happening on Android. macOS and iOS is working as expected.

**Your Setup (please complete the following information):**

 - Unity version: 2019.4.3f1
 - AVPro Video version: 1.11.3
 - Operating system version: macOS Catalina 10.15.5 (19F96)
 - Device model: Nokia 6.1 or Samsung Galaxy A50 or HUAWAI Mate 20 lite with Android 10 or Samsung J5 with Android 9
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**

Start video on one of the devices i mentioned above

**Logs**

```
I/Unity: [AVProVideo] Initialising AVPro Video (script v1.11.3 plugin v1.11.3) on Adreno (TM) 508/OpenGL ES 3.2 V@415.0 (GIT@f2ab992, I401605978b, 1569657027) (Date:09/28/19) (MT True) on Android Android OS 10 / API-29 (QKQ1.190828.002/00WW_4_10D)

I/Unity: [AVProVideo] Opening https://baff-app-production.oss-eu-central-1.aliyuncs.com/app-intro.mp4 (offset 0) with API ExoPlayer

E/ExoPlayerImplInternal: Source error.

I/System.out: AVProVideo error null

E/Unity: [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
     #0 0x7094301458 (libunity.so) ? 0x0
     #1 0x70941bc6cc (libunity.so) ? 0x0
     #2 0x7093ecfe74 (libunity.so) ? 0x0
     #3 0x7093ecfda4 (libunity.so) ? 0x0
     #4 0x702ee7a908 (libil2cpp.so) ? 0x0
     #5 0x702ee7a3f0 (libil2cpp.so) ? 0x0
     #6 0x702e83a954 (libil2cpp.so) ? 0x0
     #7 0x702e919240 (libil2cpp.so) ? 0x0
     #8 0x7093e399b4 (libunity.so) ? 0x0
     #9 0x7093e45f14 (libunity.so) ? 0x0
     #10 0x7093e4ec04 (libunity.so) ? 0x0
     #11 0x7093d29dfc (libunity.so) ? 0x0
     #12 0x7093db9a3c (libunity.so) ? 0x0
     #13 0x7093db9a70 (libunity.so) ? 0x0
     #14 0x7093db9ca8 (libunity.so) ? 0x0
     #15 0x7093eafcec (libunity.so) ? 0x0
     #16 0x7093ec3060 (libunity.so) ? 0x0
     #17 0x70faf2d350 (libart.so) art_quick_generic_jni_trampoline 0x90
     #18 0x70faf24334 (libart.so) art_quick_invoke_stub 0x224
     #19 0x70faf32fec (libart.so) art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*) 
```

**Videos**

https://baff-app-production.oss-eu-central-1.aliyuncs.com/app-intro.mp4

**Comment by JanOwiesniak** [comment]
Tested it again with a local video and it always works.
Tested it with another video url and it always works.

This leads to the assumption that it has to do something with this particular video url.
Moved video to another place and it always works now.

**Conclusion**

It is not related to your product. Therefore this issue can be rejected.

**Comment by RenderHeadsSte** [comment]
Thanks for investigating and letting us know

**Comment by qq2528589211** [comment]
But this issue happened on PC，even through I change many URL
