### ISSUE TITLE
HLS .TS not playing

### ISSUE THREAD

**Issue by MDNST** [RenderHeads/UnityPlugin-AVProVideo#43]
**Describe the bug**
Showing only white Screen.

**Your Setup (please complete the following information):**
 - 18.3.6: 
 - AVPro Video version: 
 - Win10 64Bit: 
 - PC Win10 64Bit: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/42674839/55798728-4dc4c180-5aed-11e9-98be-fb58b0b22a85.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
No shortage of details here :)
Please could you supply more information.

**Comment by AndrewRH** [comment]
I'm closing this ticket - not enough details and no reply
