### ISSUE TITLE
MediaPlayer.Control.Seek does not fire an event if seek finishes immediately.

### ISSUE THREAD

**Issue by cameronfeng** [RenderHeads/UnityPlugin-AVProVideo#435]
**Describe the bug**

When in the Editor play mode, calling MediaPlayer.Control.Seek on the SampleSphere.mp4 video some times will not fire any events when seek completes immediately when called.

As a workaround, MediaPlayer.Info.IsPlaybackStalled needs to be checked after calling 'Seek' to consistently determine if seek already finished and to control for if an event will fire.

This seems to happen randomly, and symptoms are consistent with issues related to script execution order.

*PS - While trying to reproduce the bug for this report, I realize that event firing happens within the MonoBehaviour Update loop. This indeed seems to be a script execution order issue. Whether or not this is intended, this is not intuitive for the developer.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.4f1
 - AVPro Video version: 1.11.3
 - Target platform: Oculus Quest (Android)
 - Operating system version: Windows 10 (bug occurs in the Unity Editor during play mode)
 - Video specs (resolution, frame-rate, codec, file size): Using SampleSphere.mp4 that comes with the AVProVideo package.

**To Reproduce**
Call MediaPlayer.Control.Seek on SampleeSphere.mp4 while listening for events. No event will be called. Seems to happen randomly.

**Videos**
SampleSphere.mp4 video that comes with the AVProVideo package (version 1.11.3).

**Comment by cameronfeng** [comment]
Another user commented on a related issue in January: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/239#issuecomment-577880547

**Comment by AndrewRH** [comment]
Thanks for reporting this!  

Have you only encountered this issue on Windows?

Thanks,

**Comment by AndrewRH** [comment]
I have replicated the issue with the attached script:

[TestSeeking.cs.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5056733/TestSeeking.cs.txt)

I think what happens is sometimes the seeking finishes so quickly, that by the time the event triggering code runs, Control.IsSeeking() return false - so it doesn't issue the seeking event.

We will have to think about how we solve this...I guess we always want to issue the StartedSeeking event regardless
