### ISSUE TITLE
Error when loading video from CloudFront

### ISSUE THREAD

**Issue by vpzomtrrfrt** [RenderHeads/UnityPlugin-AVProVideo#438]
(Windows 10.0.18362, Unity 2018.4.24f1, AVPro Video 1.11.4)

Loading this video hosted on S3 works fine: https://vrigami.s3.amazonaws.com/CnkN0KNxpafGM2NzGBr5hDBP4Iv1ScN3.mp4

But trying to use this CloudFront distribution pointed at S3 doesn't: https://d3pk9p2ot72weq.cloudfront.net/CnkN0KNxpafGM2NzGBr5hDBP4Iv1ScN3.mp4

This vague error is logged:
```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:2111)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1412)
```

The two links download the same file, so I don't know what would be different that's tripping up the video player

**Comment by AndrewRH** [comment]
The CloudFront URL with just http instead of https seems to work.  There must be some issue with TLS/SSL....

**Comment by jrjones** [comment]
I've seen this behavior. You need to modify your CloudFront endpoint to not require any request headers OR pass the necessary request headers (which requires AVPro Video version 2.0)

**Comment by vpzomtrrfrt** [comment]
What request headers would be required? Is it not passing Host?

**Comment by jrjones** [comment]
It depends on how you have things configured on the CloudFront side. If you're using the AWS default policies, it will be expecting an origin and access-control-request

![image](https://user-images.githubusercontent.com/1821443/90073578-b231fb00-dcb6-11ea-8705-9cf3bd0d7533.png)

Depending on your needs, you'll either need to send the necessary headers (which requires AVProVideo 2.0) or set up your own custom Cache Policy that doesn't require any headers be present (but don't do that if you're trying to restrict loading the videos to just your app!)

![image](https://user-images.githubusercontent.com/1821443/90073819-240a4480-dcb7-11ea-9aa5-d6c717d1130a.png)

More info can be found here:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/add-origin-custom-headers.html

Note that I have no affiliation with Amazon or Renderheads, just trying to be helpful. 👍

**Comment by vpzomtrrfrt** [comment]
I wouldn't expect the cache policy whitelist to require headers, but our policy doesn't have any anyway

**Comment by vpzomtrrfrt** [comment]
I wouldn't expect cache/origin policies affect required headers, but I don't really need headers passed anyway.

It still doesn't work even after changing the policies

**Comment by MarkusNigrin** [comment]
@jrjones @AndrewRH We'll experiment with this more and report back, that said, big thanks for being super helpful!!
