### ISSUE TITLE
Support for WebRTC so that we can play a stream received over WebSocket

### ISSUE THREAD

**Issue by holah-reiken** [RenderHeads/UnityPlugin-AVProVideo#44]
We don't currently find support documented for playing video streams over WebSocket (WebRTC).  We are currently streaming video over Wowza which offers ultra-low latency using websockets, or a HLS fallback which has a prohibitively greater delay for our purpose.  Can you tell us if Websocket support exists in the current version of AVPro or is in the roadmap?  Any assistance in finding this feature, or otherwise optimizing HLS playback is appreciated. Thanks.

**Comment by MorrisRH** [comment]
At this time we do not support playback via WebRTC. Should the platform (iOS, Android, etc.) provide support for WebRTC in the future then we will endeavour to make sure that it as available.

**Comment by imosapatryk** [comment]
Still not supported?
