### ISSUE TITLE
4k streaming video playback

### ISSUE THREAD

**Issue by HectorCharter** [RenderHeads/UnityPlugin-AVProVideo#445]
**Describe the bug**
I am using Wowza to stream video in 4k at 30 and 60 fps. When I use the mdash version of the stream, I receive the following error:

> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
> UnityEngine.Debug:LogError(Object)
> RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Assets/Libs/AVProVideo/Scripts/Components/MediaPlayer.cs:2111)
> RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/Libs/AVProVideo/Scripts/Components/MediaPlayer.cs:1412)

If I replace the video with a 2k file, it works fine. Also, if I link to the video via file path, playback works fine. Streaming also works using VLC.

Is it possible to have a more descriptive error, than 1 of 4 problems?

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.15f1
 - AVPro Video version: 11.4
 - Operating system version: Win 10 Pro
 - Device model: what device?
 - Video specs (resolution, frame-rate, codec, file size): 4k, 30 and 60 fps, h.264, n/a

**To Reproduce**
1. New scene, create a new media player
2. Switch source path to absolute path or url
3. Paste the 4k stream from wowza live i.e: http://10.0.0.176:1935/live/myStream/manifest.mpd
4. Add a plane, add Apply to mesh component
5. Press play

**Logs**
see above

**Screenshots**

**Videos**
Video can be found here: http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_30fps_normal.mp4

**Comment by HectorCharter** [comment]
I created this ticket yesterday. Is there someone I can contact or pay for elevated service?

**Comment by AndrewRH** [comment]
Are you able to send us links to the streams so that we can investigate?  

Have you tried using HLS instead of MPEG Dash?

If you have links please send them to our product support email here: https://www.renderheads.com/contact/

**Comment by HectorCharter** [comment]
@AndrewRH HLS worked.

The stream is a local Wowza streaming server, and the link is part of the original post.

**Comment by RenderHeadsSte** [comment]
@HectorCharter The link you originally provided appears to be a link to a local IP address, which naturally we cannot access to test here.  Can you provide a link to a publicly available stream?
