### ISSUE TITLE
 IOS platform video stuck

### ISSUE THREAD

**Issue by mengflyQ** [RenderHeads/UnityPlugin-AVProVideo#447]
**Describe the bug**
Hello there!
I found a problem when using AVProVideo: When playing a video on the IOS platform, if there is a call at this time and the call is closed or the Bluetooth headset is connected, the video will be stuck and cannot be played.
We tried to set the Media Player and checked Pause Media On App Pause and Play Media On App Unpause, but it still didn’t take effect; after checking the code, we found that in MediaPlayer.cs
In the OnApplicationPause function, m_Control.Pause() will only be called under non-Iphone platforms; after the restrictions on this platform are removed, the above problems will not occur in the ios package that is printed. I would like to ask: Why is it restricted to call this function under the IOS platform?
Will there be other problems if I remove this restriction? Or is there any other way to solve the problems encountered above

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.19f1
 - AVPro Video version: 1.11.0
 - Operating system version: IOS
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. The video can continue to play

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us 2569386351@qq.com

**Comment by MorrisRH** [comment]
Hello!
There is an option under the platform specific settings for iOS: "Resume playback on audio session route change". You need to enable this in order for the video to automatically resume playing when headphones are connected or disconnected.

**Comment by mengflyQ** [comment]
Thank you! I also encountered another problem: MediaPlayer is embedded in a scene, but suddenly when returning from another scene, the video cannot be played, and the black screen is displayed. This problem does not work on Android, but only encountered on ios.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProVideo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月20日(星期四) 晚上7:39
收件人:&nbsp;"RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com&gt;;
抄送:&nbsp;"2569386351"<2569386351@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo]  IOS platform video stuck (#447)





 
Hello!
 There is an option under the platform specific settings for iOS: "Resume playback on audio session route change". You need to enable this in order for the video to automatically resume playing when headphones are connected or disconnected.
