### ISSUE TITLE
IsPlaying() always return FALSE, and Pause() does nothing

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#453]
**Describe the bug**

calling isPlaying() always returns false, even if called when the video is playing. If I call Pause() when the video is playing nothing happens the video keeps playing.

**Your Setup (please complete the following information):**
 - Unity version: 2020.1
 - AVPro Video version: 1.11.4t
 - Operating system version: IOS 13.xxxx
 - Device model:  iPhone
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. call IsPlaying() while video is playing always returns FALSE
2. calling Pause() while video playing does not pause video
3. 

This only happens on stupid IOS, same code on Android works.

**Comment by MorrisRH** [comment]
Please provide the output from Xcode when running your project on an iOS device.
