### ISSUE TITLE
Custom Shaders no longer work in IOS

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#454]
**Describe the bug**

I have a bunch of custom shaders that worked with "Apply material" where while the video is playing the user can change shaders to see different video enhancements. This worked using 1.11.4f, before but it no longer works on IOS using a version downloaded Aug 5th.

Actually there are two problems. One version of your package always returns FALSE when i call isPlaying() even if the video is actually playing, in that version my custom shaders work. 

In the other version of your package IsPlaying() returns the correct value, but my custom shaders no longer works.

**Your Setup (please complete the following information):**
 - Unity version: 2020.1
 - AVPro Video version: version downloaded Aug 5th
 - Operating system version: IOS 13.xxx
 - Device model: iPhone
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Use a custom shader results in black screen, 
2. 
3. 

I looked at your ApplyToMaterial.cs  code and there are many differences in there between the two versions mentioned below.

Here is the run down....
V1.11.4t (Scripts v1.10.1).     custom shaders work (with red tint), but IsPlaying returns WRONG value
V1.11.4t (Scripts V1.11.4).    custom shaders DONT work (black screen), IsPlaying returns CORRECT value

Other bug with V1.11.4t (Scripts V1.11.4)  is if you pause a video, when you resume the video becomes inverted.

I fix all these problem by using package V1.11.4t (scripts V.1.11.4) and replacing ApplyToMaterial.cs from that package with the ApplyToMaterial.cs from V1.11.4t (Scripts v1.10.1) then commenting out the following since it wouldnt compile

public override void OnInspectorGUI()
...        
	//foreach (Object obj in this.targets)
		//{
		//	((ApplyToMaterial)obj).ForceUpdate();
		//}

**Comment by AndrewRH** [comment]
Hi,

If you could send us a reproducible case then we will be able to look into this further.   You can send us a link to your project or ideally a minimal reproducible case via our product support email here: https://www.renderheads.com/contact/

Thanks,

**Comment by nsmith1024** [comment]
Hello, unfortunately i cannot send you my project, its around 10G, however there is something wrong for sure. like i said one version always returns that the video isnt playing even when it is (but my custom shaders work), and the other version reports it correctly but my customer shaders stopped working. 

So i used the later unity package (the one that correctly reports that the video is playing), and merged that with the ApplyToMaterial.cs from the earlier package where my custom shaders worked. Doing that fixed both problems. 

That means there is something wrong underneath since everything works in the Android version and my code hasnt changed, only the ApplyToMaterial.cs

**Comment by nsmith1024** [comment]
What other information do you need? I gave you detailed version  on everything and also code

**Comment by AndrewRH** [comment]
We can't replicate the problems you're having, so we suspect there is something wrong in your project somehow.  

We asked for the console output from XCode, and a simple reproducible project showing the problem.

Right now we can't reproduce what you're experiencing so it's next to impossible for us to diagnose the issue.

Thanks,

**Comment by nsmith1024** [comment]
I mixed two of your versions to make it work
