### ISSUE TITLE
360 3D left-right video appears all green

### ISSUE THREAD

**Issue by gpratas** [RenderHeads/UnityPlugin-AVProVideo#456]
I'm trying several options and configurations to make a 360 3D LR video to play in Oculus Go, but every configuration the video plays in the editor, but in the Headset everything apears green.

Device (which devices are you having the issue with - model, OS version number):

Oculus Go

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

https://xrman.s3-eu-west-1.amazonaws.com/First-Ever+3D+VR+Filmed+in+Space+One+Strange+Rock.mp4

System Information:

AVPro Video: plugin v1.11.4t scripts v1.11.4
Target Platform: Android
Unity: v2020.1.1f1 WindowsEditor
OS: Desktop - 20M3 (LENOVO) - Windows 10  (10.0.0) 64bit - Portuguese
CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz - 8 threads - 8062KB
GPU: Intel(R) UHD Graphics 620 - Intel - Direct3D 11.0 [level 11.1] - 4031KB - 16384

**Comment by AndrewRH** [comment]
Hi @gpratas   I few questions please:

1) if you try our demo scene "08_Demo_360SphereVideo" do you still get the green?

2) By green - do you mean you just see solid green colour, or everything is tinted green?

3) Are you using any special custom shaders?

4) Oculus Go has has pretty specific requirements for encoding when playing very high resolution videos.  There's the spec:
https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/
Perhaps try some of those encoding methods?

5) Is there any error message in the Android adb logs?

Thanks,

**Comment by RenderHeadsSte** [comment]
Running your video here in one of the sample demo scenes gives the following log output:

D/MediaCodecInfo: NoSupport [sizeAndRate.support, 4096x4096x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [pacific, Pacific, Oculus, 25]

The problem here is exactly as Andrew outlines in point 4. The GO does not support your video (4096 x 4096 @30fps H264).  It does support this resolution/framerate encoded with the H265 codec.

**Comment by gpratas** [comment]
Alright, thanks for the support.

Nevertheless it is playing in Oculus Gallery player.

Rgds,
Gonçalo Pratas



Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
