### ISSUE TITLE
Windows support for OpenGLES3 in Unity Editor

### ISSUE THREAD

**Issue by huatime** [RenderHeads/UnityPlugin-AVProVideo#459]
AVProVideo cann't work if we use OpenGLES3 API for windows in Unity Editor as shown below:
![bug01](https://user-images.githubusercontent.com/60645770/91785177-56182200-ec37-11ea-90c5-7e5a4fca0475.png)
I want to know why, can you support it, thank you.

**Comment by AndrewRH** [comment]
Yes, we do not support OpenGL in the Windows editor, but it is supported on Android devices.  Is there a reason why you need to run in OpenGL mode in the editor?

You can fix it by going to Player Settings for Standalone platform and change the Auto graphics API to have DirectX11 at the top.

Thanks,

**Comment by huatime** [comment]
3Q.
And There is also the possibility that I did not express clearly and you did not understand what I mean.
I mean that after we buid asset bundle and play game in unity editor, if we don't switch to OpenES API, then the materials loaded from asset bundle  in runtime will become purple, maybe unity's bug?
But we don't do that very often. So I just want to ask if you could support OpenGLES API. 3Q again.
