### ISSUE TITLE
Crash on Android with unhandled SocketException

### ISSUE THREAD

**Issue by peoplepilot** [RenderHeads/UnityPlugin-AVProVideo#460]
**Describe the bug**
App crashes while attempting to play video with unstable network connection.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.21f1
 - AVPro Video version: 1.11.3
 - Operating system version: Android 10
 - Device model: Samsung SM-T860
 - Video specs (resolution, frame-rate, codec, file size): 
See https://makersempireprd.blob.core.windows.net/assets/video_room/pencil_topper.mp4

**To Reproduce**
1. Play video in Makers Empire 3D on Android with unstable network connection
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.
[Unstable_network_Video_Crash.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5153985/Unstable_network_Video_Crash.log)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
https://makersempireprd.blob.core.windows.net/assets/video_room/pencil_topper.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by SteUK** [comment]
Are you seeing this crash on an actual Android device, or is it an virtual device or emulator?  Your log suggests the later.

**Comment by RenderHeadsSte** [comment]
Are you seeing this crash on an actual Android device, or is it an virtual device or emulator? Your log suggests the later.

**Comment by peoplepilot** [comment]
Thanks for the quick reply. We've had it reported by a customer using a real android device, but have so far been unable to reproduce ourselves on our devices. The closest we have so far is this log from an emulator. It's possible it's a different issue on the real device, but this seems a likely culprit. We have verified the report via server logs but don't have logcat output from the device.

**Comment by AndrewRH** [comment]
Unless I'm mistaken the exception seems to be on retrieving a JPG image:

UnityWebRequest: errorCallback with error=java.net.SocketException: Connection reset url=https://makersempireprd.blob.core.windows.net/assets/img/mesh/thumbnail/95c05cde-ee7c-4a89-a17e-5ee01d9c7fad.jpg

So I'm not sure this is related to the AVPro Video plugin?

**Comment by peoplepilot** [comment]
Ah, yes... sorry about that!
