### ISSUE TITLE
Can I use this plugin to build WebGL?

### ISSUE THREAD

**Issue by Wudi-Unity** [RenderHeads/UnityPlugin-AVProVideo#461]
Can I use m3u8 format URL to build WebGL at Unity3D?
Because When I play in the unity simulator is OK
But build to WebGL is Error....

**Comment by AndrewRH** [comment]
Yes we support WebGL.
What is the error?
Please use the bug report template to help give us the information we need to help you.

**Comment by Wudi-Unity** [comment]
When I open my web (build from Unity WebGL)
It show:

An error occurred running the Unity content on this page.
see your brower JavaScript console for more info.
The error was:UncaughtError: His is not defined

**Comment by AndrewRH** [comment]
Did you integrate the hls.js library as in the documentation?

**Comment by Wudi-Unity** [comment]
No, I don't use hls.js. (Only select)
If I build WebGL. Is this necessary?

Because I select none, that is no error

**Comment by AndrewRH** [comment]
Which browser are you using, and on which platform?

Most browsers don't have native HLS support (or it is disabled by default), so it's best to use the hls.js library - we have instructions in the documentation on how to do this.

Does that helps?

**Comment by Wudi-Unity** [comment]
Thanks for your help.
I use Windows10 and Chrome.
And I find this documentation information:
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
To add support for hls.js:
1. In the MediaPlayer component set Platform Specific > WebGL > External Library to
hls.js
AVPro Video © 2016-2020 RenderHeads Ltd
2. Build for WebGL
3. Download the latest hls.js release (we tested with 0.10.1):
https://github.com/video-dev/hls.js/releases
4. Once your build is made, copy “hls.min.js” to the TemplateData folder
5. Edit the index.html to add <script src="TemplateData/hls.min.js"></script> before the
UnityLoader.js script is loaded. Ideally you would add this to a new WebGL template
so that you don’t have to make these changes for each build.
============================================
so...
If I want to use m38u format, maybe I must add this hls.js

but if I want to use RTSP, can I directly use the RTSP URL?

**Comment by Wudi-Unity** [comment]
ps. my m3u8 format movie can be played smoothly.
Thanks for your help ^^

**Comment by AndrewRH** [comment]
I'm glad to hear that ^_^
RTSP is not a format we support I'm afraid...I think we may support it on Android (using the MediaPlayer API and not the default ExoPlayer API), but in general it is not supported.

I will close this issue since it is resolved.

Thanks,
