### ISSUE TITLE
Removing watermark without updating/breaking functionality of previous AVPro version

### ISSUE THREAD

**Issue by FransHuntink** [RenderHeads/UnityPlugin-AVProVideo#463]
**Describe the bug**
I'm updating an existing VR video player app that uses a ~2018 version of AVPro Media (Android) for video playback. The problem I'm facing is that I'm seeing the trial watermark on all my videos, even on the Android platform. In an attempt to remove the watermark, I tried to overwrite the existing AVPro package with a fresh version. This removes the watermark, but is not a great solution for solving the watermark issue. After updating the package, videos appear in different rotations on a VR sphere, and various AVPro Media shaders for video playback now show a black screen.

My questio**n: Is there a way to remove the watermark/verify the plugin WITHOUT updating to the latest package version (thus preserving the current functionality exactly the way it is).** Normally I would upgrade the project to work with the latest package version of a plugin, but note that the video player I am working on is used on many different devices and platforms, therefore reworking it to work with a new version of AVPro Media (updating shaders, video placement) would be very costly.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.5f1
 - AVPro Video version: ?, AVPro Android was purchased ~Q4 2018
 - Operating system version:  Android, built on MacOS 
 - Device model: Pico G2 4K
 - Video specs (resolution, frame-rate, codec, file size): Problems is format independent 

**To Reproduce**
1. Have an existing project that uses AVPro media Android
2. Attempt to update the plugin .DLL files/all files to remove watermark
3. Watch project malfunction

**Comment by AndrewRH** [comment]
Hi,

We can probably supply you with an old version of the plugin - please email out product support team http://renderheads.com/contact/ and give details of which product you own already (PDF purchase invoice would be best, or invoice number) and which version of AVPro Video you need (it should print this in the console window, or you can look at the Help/About section on the MediaPlayer component).

Thanks,

**Comment by FransHuntink** [comment]
Thank you Andrew. Contacted the support team by e-mail. Looking forward to your reply.

**Comment by FransHuntink** [comment]
Hi Andrew, 

After my e-mail I received a .jar file (AVProVideo.jar) from your team that I used to replace the one in assets/plugins/android directory.  However, when I do so, functionality of my video player breaks (all my video players return a black screen after rebuilding with the replaced .jar file). Can you fill me in on how AVPRo verifies that I actually purchased the asset? Surely there must be a way to do so without changing the actual functionality of the plugin? Hoping to hear from you soon!


Thanks again, 

Frans

**Comment by AndrewRH** [comment]
Hi Frans,

If you're still using all of the old plugin files (scripts, shaders etc) from your 2018 project, and you just replace the JAR file then I can't understand why it would change behaviour since it was working before and I believe we've just gone from a watermarked JAR to a non-watermarked JAR of the same version.

Thanks,

**Comment by FransHuntink** [comment]
The change I'm seeing when I swap .JAR files is that the _shader AVProVideo/VR/InsideSphere Unlit (stereo+fog)_  no longer works on my android based Pico G2 device. This shader worked perfectly well with the watermarked jar file.

The weird thing is that when I swap this shader for the 'Android OES Only' shader, I'm able to see a watermark free video. This however, as I've stated before, would require me adjust all video playback functionality because it changes the way videos are displayed and rotated (definitely not an option).

Any chance I can verify what version the .JAR file claims to verify? Might be a version mismatch? Any help is greatly appreciated. Cheers.

**Comment by AndrewRH** [comment]
If you look at the ADB log cat while the app is running on the Android device, it will print the version number (can be difficult to spot but if you search for "avpro" you should see it).

Do you have the OES mode enabled in the MediaPlayer > Platform Specific > Android section?

If you have OES mode selected then you must have an OES shader - otherwise you shouuld be able to use a normal non-OES shader (such as AVProVideo/VR/InsideSphere Unlit (stereo+fog))

Thanks,

**Comment by FransHuntink** [comment]
Thanks for getting back to me Andrew, turned out the OES setting was actually turned on. Resolved the issue, cheers.
