### ISSUE TITLE
Playing a video no longer works if app goes to background and comes back

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#468]
**Describe the bug**

On IOS, if while playing a video, you stop it then move to another app, when you come back and try playing videos again it always stalls and never plays again until you kill and restart the app.

Any way to prevent forcing the app user to do that?

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.2
 - AVPro Video version: unknown
 - Operating system version: IOS
 - Device model: iPhone 13.6
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Start a video playing
2. stop the video
3. switch to another app without fully closing this app
4. return to original app
5. try playing videos
6. videos can never be played anymore unless i terminate the app and start it again

player reports a stall event when try to play video

**Comment by AndrewRH** [comment]
Hi nsmith - thanks for those details.  I have a few followup questions:

1) Are you able to replicate this issue just using one of our sample scenes in a fresh Unity project?
2) We need to know the AVPro Video version that you're having issues with - please check this it will print it in the Console Window.  The latest version is 1.11.4
3) If you have a working case with (1) then could you try toggling the option "in Player Settings > Player > Run in Background" to see whether that changes this behaviour?

Thanks,

**Comment by nsmith1024** [comment]
It was fixed, another app was holding the audio channel for some reason. but its fixed now
