### ISSUE TITLE
Video has no sound

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#469]
**Describe the bug**

I recorded a video using iPhone. The video is in MOV format. I convert MOV into MP4 using ffmpeg like this

ffmpeg -i  file1.mov -vcodec h264 -acodec mp2 file2.mp4

When i do that and play the converted MP4 video with your player it plays but there is no audio

here is the video 

http://apps.basereality.tv/test.mp4

If i use chrome browser to play i hear audio and see video fine. But if i use firefox browser or your player on IOS  there is no audio but i can see the video.

If i use your player on Android i see video but the audio is totally scrambled and trashed.

Do you know how how to convert MOV to MP4 with ffmpeg so both audio and video plays properly when using your player for both ANDROID and IOS?

Thanks

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.2
 - AVPro Video version: unknown
 - Operating system version: iPhone (as usual)
 - Device model: 13.6
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1.  encode MOV video to mp4
2.  play video
3. video plays but there is no audio

**Comment by AndrewRH** [comment]
Hi,

The problem is that you're using the MP2 codec for audio which isn't widely supported.  You should use AAC instead as this is the most common:

Try 

ffmpeg -i file1.mov -vcodec h264 -acodec aac file2.mp4

Thanks,
