### ISSUE TITLE
Any video is not showing in one specific project after standalone build.

### ISSUE THREAD

**Issue by ikay70** [RenderHeads/UnityPlugin-AVProVideo#475]
**Describe the bug**
Any Video is not showing, but its sound plays and event callbacks works.
I've tried using both DirectShow and Media Foundations. Fed file with OpenVideoFile and buffer bytes array.  Using NGUI Texture and ApplyToMaterial script. It happens to any video including BigBuckBunny_360p30.mp4. I've tried switching platforms.
AVPro Debug overlay showing correct source, dimensions, frame rate and time elapsed. 

I've tried importing AVPro to a new project and it works as expected - both video and audio are playing.

To mention, standalone build also had some problems with finding AVPro dll library. I had to copy it from Plugins folder to build root folder.

**Your Setup (please complete the following information):**
 - Unity version: 2018.1.f11
 - AVPro Video version:  1.11.2
 - Operating system version:  Win 10
 - Device model: --
 - Video specs (resolution, frame-rate, codec, file size): BigBuckBunny_360p30.mp4

**To Reproduce**
Couldn't reproduce on a fresh project

**Logs**
Logs are okay

I know it's all foggy, but maybe you've got any ideas what i can try.

**Comment by AndrewRH** [comment]
Do any of the demo scenes run on your system?

Please check that /Plugins/x86_64 contains these files:
AVProVideo.dll
Audio360.dll

and that that're assigned to the correct platform and CPU architecture in the Inspector window.

Does that helps?
Thanks,
