### ISSUE TITLE
iphone 11   ios14 Play 60m MP4 video, only sound, no picture

### ISSUE THREAD

**Issue by lwtbn1** [RenderHeads/UnityPlugin-AVProVideo#476]
**Describe the bug**
iphone 11   ios14 Play 60m MP4 video, only sound, no picture

**Your Setup (please complete the following information):**
 - Unity version: 2017.
 - AVPro Video version: 1.1.4
 - Operating system version: ios14
 - Device model: iphone11
 - Video specs (resolution:720x484, frame-rate:30, codec:mp4, file size:65M): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

Do our sample videos player?

Is your video using H.264 or HEVC codec?  If it's HEVC then you need to make sure the fourcc tag is 'hvc1' as Apple doesn't recognise the other tags types for HEVC that other platforms support.   If you're ussing FFMPEG to encode your videos to HEVC then add "-tag:v hvc1" for this.

Thanks,

**Comment by ismaelash** [comment]
Describe the bug:
The video play, but, not show image, only sound.

Your Setup (please complete the following information):

Unity version: 2019.4.x
AVPro Video version: 1.11.5
Operating system version: iOS 13.5
Device model: iphone SE 1 gen
Video specs: https://drive.google.com/file/d/1HSg1D4l21ZPnqdv2Xt2s9YqCBxFJIOJi/view?usp=sharing

I convert this video for HLS and show via streaming on iOS.
On log of iOS, not show any error

**Comment by MorrisRH** [comment]
Tested the provided URL with Unity 2018.4.27f1 and Unity 2019.4.12f1, using the 01_Demo_BackgroundShader scene on the following devices with no issue:
iPhone5s - iOS 12.4.8
iPad Pro - iOS 14.0

**Comment by mdtphylony** [comment]
on iPad 14.0 & 14.1 there are some videos can show pictures, some not and the audios are played. but on iPhone 14.01 everything is okay. very strange.

**Comment by lwtbn1** [comment]
My problem solved, video compression format problem
