### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by dyhmichail** [RenderHeads/UnityPlugin-AVProVideo#477]
When I try to build APK with you demo scene on Android I've got error:
"Unity android build failed Workers$ActionFacade"

**Comment by AndrewRH** [comment]
@dyhmichail thanks for posting your issue but i'm afraid we will need more information so that we can help you.

Useful information includes:
1) AVPro Video version
2) Unity version
3) Your build settings (gradle version, IL2CPP etc / Mono version etc)
4) The full build log

Thanks,

**Comment by RenderHeadsSte** [comment]
We will be closing this issue shortly due to a lack of response.  Can you update us on it please @dyhmichail
