### ISSUE TITLE
Transparency with Hap codec & Media Foundation

### ISSUE THREAD

**Issue by mikedreambooth** [RenderHeads/UnityPlugin-AVProVideo#478]
Hey @AndrewRH Any idea when you plan to add transparency support for the Hap codec using media foundation?  Thanks

**Comment by AndrewRH** [comment]
We're hoping to have support for this in the next beta release - which should be out in a week or two.

Thanks,

**Comment by mikedreambooth** [comment]
@AndrewRH that's great! We need sound to be routed through unity plus transparency so waiting on this. Do you have a rough idea of the release date for V2? 

Thanks, Mike

**Comment by mikedreambooth** [comment]
Hey @AndrewRH any update on this? Thanks

**Comment by AndrewRH** [comment]
I am closing this issue - this feature is now included in AVPro Video.  Thanks,
