### ISSUE TITLE
video always plays automatically in Android player

### ISSUE THREAD

**Issue by andriworld** [RenderHeads/UnityPlugin-AVProVideo#48]
In the Android player, the video always starts automatically, disregarding the value of the autoPlay parameter in MediaPlayer.OpenVideoFromFile

 - Unity version: 2018.3.12f1
 - AVPro Video version: 1.9.12 (from the Asset Store) using exoplayer
 - Operating system version: Android 9
 - Device model: Pixel 3
 - Video specs: 1080w x 1920h, 30fps, h.264 4.3 MB

Steps: (Android player)
1. call mediaPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, path, false)
EXPECTED: the video should not start playing
ACTUAL: the video starts playing automatically
Troubleshooting:
mediaPlayer.Control.IsPlaying()  returns true
mediaPlayer.m_AutoStart  is false

**Comment by RenderHeadsSte** [comment]
Thanks for reporting this issue. A fix for this will be in version 1.9.15 onward.
