### ISSUE TITLE
Loading videos from indexedDB in WebGL

### ISSUE THREAD

**Issue by DebugD0tLog** [RenderHeads/UnityPlugin-AVProVideo#482]
So I'm developing an application that first downloads various medias from a server, stocks them in local (IndexedDB) and load them afterward when it's needed. 
I can get files such as .jpeg or .png but when it comes to video I always get this error : 

- [AVPro] Unknown URL protocol
- [AVPro] Failed to open + path which looks like so "idbfs/xxxxxx/Medias/6/xxxx.mp4"

Is there anything to know/change to use AVPro with WebGL comparing to other plateform ?

Set up :
 - Unity version: 2019.3.4f1
 - AVPro Video version: 1.11.5
 - Operating system version: Windows 10
 - Device model: Chrome Version 86.0.4240.75 (64 bits)

**Comment by AndrewRH** [comment]
Take a look at this forum post:
https://forum.unity.com/threads/videoplayer-webgl-from-streamingassets-to-indexeddb.527527/

Basically it can play but you need to pass in a "blob:"  URL

Does that help?

**Comment by DebugD0tLog** [comment]
After more research I found out that this error is not due to AVPro plug in but a bad gestion of indexedDB on my part, I therefore close this issue.
