### ISSUE TITLE
Videos become black on OpenGLES2 

### ISSUE THREAD

**Issue by AnhPham** [RenderHeads/UnityPlugin-AVProVideo#484]
**Describe the bug**
Videos become black on OpenGLES2 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.11
 - AVPro Video version: 1.11.5
 - Operating system version: Android only (iOS & MacOS are ok)
 - Device model: Vsmart Joy 1+
 - Video specs (resolution, frame-rate, codec, file size): your sample videos.

**To Reproduce**
1. Create new unity project
2. Import AVPro 1.11.5
3. Add one of your demo scene to build settings.
4. Turn off Auto Graphics API, set OpenGLES2 is the only one.
5. Build and run on an Android device.

**Comment by RenderHeadsSte** [comment]
Can you send over a logcat dump please?

**Comment by AnhPham** [comment]
<img width="853" alt="Screen Shot 2020-10-08 at 9 37 13" src="https://user-images.githubusercontent.com/1193578/95409359-9f9d1080-094b-11eb-99a1-43fef2174dc2.png">

Hi,
After using logcat, I found that libAVProLocal is missing for arm64. I just checked Android - arm64 on Import Settings. Then it works now. (default is unchecked)

**Comment by RenderHeadsSte** [comment]
That is great news.  Thanks for updating us.  I will close this issue now.
