### ISSUE TITLE
video/audio stutters on some android simulators

### ISSUE THREAD

**Issue by yanjiech** [RenderHeads/UnityPlugin-AVProVideo#487]
When playing video on some android simulator, video/audio stutters randomly.
Adb logcat show a warning message "W/AudioFlinger( 1442): temp test MixerThread::prepareTracks_l mRetryCount=41 line=3634" when it stutters.
Any ideas?

**Comment by RenderHeadsSte** [comment]
The simulator is completely reliant on the hardware you are running it on.  What are the specifications of that PC?

**Comment by yanjiech** [comment]
gpu gtx 1050, win 10,  cpu intel i7 8700.
btw, avpro version is 1.9.14

**Comment by RenderHeadsSte** [comment]
That is a very old version of AVPro Video.  I would advise updating to the latest version and report back.
