### ISSUE TITLE
Live stream does not continue after it was stalled due to connection loss

### ISSUE THREAD

**Issue by ualogic** [RenderHeads/UnityPlugin-AVProVideo#488]
**Describe the bug**
I am testing with live hls stream from vimeo. Using vimeo sdk. Trying to simulate network problems with disconnecting from the internet and then connecting back. I am getting "Stalled" event, but it never unstalls after the connection is restored. Calling Play() also does nothing in that state. Is this a bug? Or if it is by design, what is the standard procedure to continue video when a connection was restored?

**Your Setup (please complete the following information):**
 - Unity version:  2019.4.8f1
 - AVPro Video version: 1.11.5
 - Operating system version: Windows 10, Android 9, iOS 13.7
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): Vimeo HLS adaptive resolution stream

**To Reproduce**
1. Intall vimeo sdk
2. Force it to feed HLS stream to AVPro
3. Sever the internet connection completely
4. Wait for "Stalled" event to be fired
5. Connect back to the internet

Untalled is not called, calling Play() does nothing, calling Rewind() unstalls the player (and rewinds obviously).

**Comment by RenderHeadsSte** [comment]
Are you seeing this issue on all the platforms you list?

On Android I believe there was an issue when CanPlay() would always return false after a network connection loss.  This is fixed in version 1.11.6 and onward (yet to be released).  Calling Play() directly without checking on CanPlay() should have worked though...

**Comment by ualogic** [comment]
I don't remember what I did for iOS, but definitely Windows and Android. It works fine with pre-recorded video (as in stalls and unstalles without any problems), but with live stream it never plays again. Also CanPlay() is always true, even without network connection for both live and recorded video.

**Comment by RenderHeadsSte** [comment]
Can you provide a stream URL that doesn't work for you?

**Comment by ualogic** [comment]
We are testing with own live stream on Vimeo, so I need to start it first. I can run it tomorrow more or less11-18 uk time. If that would be good, I'll post a link tomorrow.

**Comment by RenderHeadsSte** [comment]
Android: I have tested your stream (using ExoPlayer API path) and it performs exactly as it should (calling play after a network drop continues the playback).  The playback point is not a natural continuation of the video.  One thing I did notice, is that in v1 it took quite some time to restart playback (buffering).  In v2 playback resumed a lot quicker.  I am putting this down to advances in ExoPlayer that mean stream restarting is a lot quicker.

Windows: Tested in Editor and the stream automatically continues playback after the connection comes back up, there seems no need to call 'Play()' again. The stream carried on from where it stalled.

iOS: Exactly he same behaviour as with Windows (above).

**Comment by ualogic** [comment]
This is strange. I don't have an access to 1.11.6 yet, are you testing with 1.11.5? If yes, then the problem is somewhere on my side, I'll try to update Unity to the latest version and do the tests again.

**Comment by RenderHeadsSte** [comment]
Yes, I am testing with the latest/last released version of AVPro Video.  I am using Unity 2018.4.15f1.

**Comment by AndrewRH** [comment]
@ualogic 
I think I recreated it on Windows.  I would recommend that you create a fix for this situation at the app level.  If playback is stalled for longer than a certain amount of time, simply reload the stream.

**Comment by ualogic** [comment]
Ok, done tests with Unity 2019.4.12, still not playing in windows editor and android. Mac and ios play as expected. Unity 2018.4.23 in windows editor does not play as well. Same behaviour with my scene, or example scenes (used videocontrols scene) that come with AVPro. Not sure what is different in my case.
@AndrewRH Starting player before there is a connection clears the video texture, so I have done your suggested workaround with unity webrequest coroutine that checks for the connection until it is restored and only then reloads the stream, would that be your recommeded way, or do you expose anything better to test the connection that I can use?
