### ISSUE TITLE
Screen-capture-recorder

### ISSUE THREAD

**Issue by czuczorf** [RenderHeads/UnityPlugin-AVProVideo#489]
**Describe the bug**
I've tried to record the screen using FFMPEG and screen-capture-recorder, but I am not able to playback it with AvProVideo, with other video players, it works fine.

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.5f1
 - AVPro Video version: 1.11.5
 - Operating system version: Win 10
 - Video specs (resolution, frame-rate, codec, file size): 1936x1060

**To Reproduce**
1. ffmpeg.exe -y -f dshow -i audio="virtual-audio-capturer":video="screen-capture-recorder" -vcodec h264_nvenc -acodec aac -ac 2 -ar 44100 -ab 128k -pix_fmt yuv420p -crf 17 -preset slow bla.mp4

[bla.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5355189/bla.zip)

**Comment by AndrewRH** [comment]
Hi,

It plays back fine for me.  I can't see anything strange with the video - it should play...

Hmm, do our included sample videos play?

Thanks,

**Comment by czuczorf** [comment]
Hi Andrew, Thanks for your fast reply!
I've put it into the included demo and works fine, sorry I've only tried to change the Video API durring runtime, now I realized if I change from directshow to  media foundation before play, everything is ok!
