### ISSUE TITLE
OSXMediaPlayer functions not being called on Mac

### ISSUE THREAD

**Issue by sneunz** [RenderHeads/UnityPlugin-AVProVideo#49]
I'm working on a phone app that uses AVPro to stream Vimeo videos. I have it working in Android/Windows, but when I transfer the project to a Mac, none of the interface controls (pause, seek, etc) are being called. For example, I'm using the "OnPauseButton()" method in VCR to pause a video, and the call to "PlayingPlayer.Control.Pause" is reached, but the Pause method in OSXMediaPlayer is not being called, even though PlayingPlayer.Control.getType() returns "OSXMediaPlayer".

Do you have any idea what could be causing this?

 - Unity version: 2018.3.9f1
 - AVPro Video version: Not sure, trial downloaded 11/28/2018
 - Operating system version: MacOS Mojave 10.14.3
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): n/a

**Comment by sneunz** [comment]
Correction: PlayingPlayer.Control.Pause is being called, but it calls the 'extern' method AVPPlayerPause() which on Android seems to cause the video to pause, but doesn't do so on iOS or Mac. Any advice? I can't access AVPPlayerPause() to see what's going on in there.

**Comment by AndrewRH** [comment]
*Bump* @sneunz  ?

**Comment by sneunz** [comment]
I actually figured it out, sorry for the delay.

Turns out I needed to add "VIMEO_AVPRO_VIDEO_SUPPORT" to the Scripting Define Symbols on Mac -- Unity had apparently defaulted to using the regular Vimeo Player, so it still played the video, but none of the AVPro player-specific functions could be called.
