### ISSUE TITLE
Frames of previous video showing before next video starts

### ISSUE THREAD

**Issue by ImmotionIoannis** [RenderHeads/UnityPlugin-AVProVideo#490]
Hello,

We have an issue where the last frame displayed from a video will be displayed before the next video to be played starts.  It is important to note that videos are streamed and not stored in the project. 
Video 1 gets played, user stops the video half way through - our video player setup now gets disabled. When the user chooses Video 2 to play, before this video starts, the frame where Video 1 was stopped is displayed first. 
We made sure that the video is stopped, closed and load an empty file after it to make sure. Changing the render textures on the mesh used to display didn't seem to work, neither from ApplyToMesh and ApplyToMaterial. Is this something to do with a frame buffer? Is there a way to clear it? If not is there something else we could try? 

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.15, the issue happens on Android devices
 - AVPro Video version: v1.11.5
 - Operating system version: Android 7.0+ (Issue appeared on Android 11 and 8)
 - Device model: Android devices (Pixel 2, Samsung S7)
 - Video specs (resolution, frame-rate, codec, file size): (these info are not available at the moment, will update the post once I have them but I dont think they are relevant to the issue)

Video showing behaviour:
https://www.dropbox.com/s/1rri9r087uewaqk/PXL_20201009_130545711.mp4?dl=0

**Comment by ImmotionIoannis** [comment]
Video specs (resolution, frame-rate, codec, file size):  
- Codec: H264 - MPEG-4 AVC (part 10) (avc 1)
- Video Resolution = 1920 x 1080
- Buffer Dimensions  = 1920 x 1088
- Frame rate = 30
- Video size =  ranges from 28MB-150MB (not accurate because they are streamed)

**Comment by RenderHeadsSte** [comment]
What API are you using? (MediaPlayer or ExoPlayer)

If it is ExoPlayer, do you have the Fast OES option enabled?

**Comment by ImmotionIoannis** [comment]
We are using MediaPlayer

**Comment by RenderHeadsSte** [comment]
Does this happen if you switch to using ExoPlayer?

**Comment by ImmotionIoannis** [comment]
That seemed to fix it thank you very much for the help!
