### ISSUE TITLE
We are heavily relied on 'Use Low Latency' on Windows, please come it back.

### ISSUE THREAD

**Issue by TyounanMOTI** [RenderHeads/UnityPlugin-AVProVideo#491]
**Is your feature request related to a problem? Please describe.**
We are using 'Use Low Latency' option on VRChat for Windows to watch/listen RTSP stream with ultra low latency (~0.5 seconds), please come it back.

**Describe the solution you'd like**
Re-enable 'Use Low Latency' option for Windows Media Foundation.

**Describe alternatives you've considered**
Reduce latency of RTSP playback on Windows, or implement some other low latency streaming (ex. Low-Latency HLS).

**Additional context**
We are using AVProVideo to stream live audio/video into VRChat. VRChat is a metaverse application for Windows and Oculus Quest (Android) released on Steam. VRChat users will join user created world which is made with Unity.
I have an AWS EC2 instance with Wowza Streaming Engine and I opened it publicly for free as a service TopazChat since January, so every VRChat user can stream their live music performance to other VRChat users. The stream is ultra low latency (about 0.5 seconds) thanks to RTSP downstream with 'Use Low Latency' option of AVProVideo Windows. Streamers are mostly Japanese, they are performing everyday and peak simultaneous listeners are 250 people.
But now 'Use Low Latency' option is removed, then the latency increased to 8 seconds at least. So we cannot perform live music with our avatar movement in-sync, also communications between voice chat and stream can be impossible. That's the problem.
Currently we targets Windows only. It seems that VRChat implemented AVProVideo for Android, so we are preparing for it.

**Comment by AndrewRH** [comment]
Ahh thanks for your request - yes we can add it back again, we didn't think anyone used the option.

We will get it back into the next version.

Thanks,

**Comment by TyounanMOTI** [comment]
Thank you for your fast response! We are glad to hear that.
