### ISSUE TITLE
GetCurrentTimeMs() is not accurate enough, and GetTextureTimeStamp() returns wrong values on Android

### ISSUE THREAD

**Issue by HaimBendanan** [RenderHeads/UnityPlugin-AVProVideo#493]
**Describe the bug**
Basically the same as [this issue](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/245), but creating a new one since it was closed.
Issue: 
`GetCurrentTimeMs()` seems to not be accurate enough, and `videoPlayer.TextureProducer.GetTextureTimeStamp()` returns wrong values on Android.
I am doing frame by frame tracking and overlay effects on top of the video, so they need to be in perfect sync with the current time of the video.
The syncing on windows works perfectly when using GetTextureTimeStamp(), and I would like to use it on Android too - but it is off by a random value which constantly change.

Here are some examples of the difference between the two values while playing the video on Windows, note that it is not a constant difference:
_mediaPlayer.Control.GetCurrentTimeMs():**2445**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **2444**
_mediaPlayer.Control.GetCurrentTimeMs():**2547**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **2546**
_mediaPlayer.Control.GetCurrentTimeMs():**615.2079**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **599**
_mediaPlayer.Control.GetCurrentTimeMs():**640.8537**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **633**
_mediaPlayer.Control.GetCurrentTimeMs():**641.9162**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **633**
_mediaPlayer.Control.GetCurrentTimeMs():**860.7283**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **833**
_mediaPlayer.Control.GetCurrentTimeMs():**884.6241**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **866**
_mediaPlayer.Control.GetCurrentTimeMs():**1918.727**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **1866**
_mediaPlayer.Control.GetCurrentTimeMs():**2487.851**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **2433**
_mediaPlayer.Control.GetCurrentTimeMs():**3547.287**, (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000): **3533**

So I would either need to make `GetCurrentTimeMs()` more precise, or find a way to get right values for `GetTextureTimeStamp()` on Android.
Do you have a suggestion on how to overcome this? Really stuck here :(

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.5f1
 - AVPro Video version: 1.11.5
 - Operating system version: Windows 10, Android
 - Device model: Laptop, galaxy note s10
 - Video specs (resolution, frame-rate, codec, file size): 500x890, 30fps. 

**To Reproduce**
1. Log the values of _mediaPlayer.Control.GetCurrentTimeMs() and (_mediaPlayer.TextureProducer.GetTextureTimeStamp() / 10000) during playing

**Comment by HaimBendanan** [comment]
@MorrisRH thanks for tagging :) but note that it's not an issue only on android - `GetCurrentTimeMs()` is not accurate on Windows too.
`GetTextureTimeStamp()` is accurate on Windows, but doesn't work on Android

**Comment by HaimBendanan** [comment]
Found another [similar issue](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/41). Is there any way to fix this?

**Comment by HaimBendanan** [comment]
I have no experience in this so I might be wrong, but it seems that [this thread](https://github.com/google/ExoPlayer/issues/5860) has info about how to manipulate `GetTextureTimeStamp()` in order to get the exact frame information. Is that right?

**Comment by AndrewRH** [comment]
Hi @HaimBendanan,

So on Windows, using GetCurrentTimeMs() there certainly can be an offset that makes it not completely frame accurate.  This offset seems to be a bug in the Microsoft decoder and depends on how the video is encoded.  The offset means that when you rewind the video time is not zero, but some small value.  

This seems to related to B-frames in the video.  When I removed B-frames then this offset went away.  If you're using FFMPEG and H.264 codec then you can encode without B-frames via:

-x264-params "bframes=0"

An alternative, in case you can't control the media would be to seek to time = 0, and then read back the time from GetCurrentTimeMs().  You can then use this offset value in your calculations when you want to do accurate seeking.

I would also recommend using the static methods in the Helper class to convert from time to frames and back again if you wish to work with frames.  Working with frames is always best when the video is encoded as keyframes only.

Thanks,

**Comment by HaimBendanan** [comment]
Hey @AndrewRH, my scenario is that I need to get accurate current timing of the video, either with current frame index (like unity's video player) or current precise timestamp (millisecond is enough). I need a solution for mobile (iOS, Android), I am using Windows only in the editor.

I dont control the media, it is set by the user.

Regarding the solution you proposed -I will test it on Android and update.

**Comment by RenderHeadsSte** [comment]
We are happy to replace the timestamp return on Android to the presentation time.  It would look like this:

onVideoFrameAboutToBeRendered: presentationTimeMS = 66.666 | GetCurrentTimeS(in MS)0.0 | m_TextureTimeStamp = 87112160201640
onVideoFrameAboutToBeRendered: presentationTimeMS = 100.00001 | GetCurrentTimeS(in MS)37.0 | m_TextureTimeStamp = 87112248205386
onVideoFrameAboutToBeRendered: presentationTimeMS = 133.33301 | GetCurrentTimeS(in MS)67.0 | m_TextureTimeStamp = 87112343534966
onVideoFrameAboutToBeRendered: presentationTimeMS = 166.666 | GetCurrentTimeS(in MS)106.0 | m_TextureTimeStamp = 87112376868298
onVideoFrameAboutToBeRendered: presentationTimeMS = 200.00002 | GetCurrentTimeS(in MS)137.0 | m_TextureTimeStamp = 87112410201630
onVideoFrameAboutToBeRendered: presentationTimeMS = 233.33301 | GetCurrentTimeS(in MS)177.0 | m_TextureTimeStamp = 87112448505433
onVideoFrameAboutToBeRendered: presentationTimeMS = 266.66602 | GetCurrentTimeS(in MS)196.0 | m_TextureTimeStamp = 87112481838765
onVideoFrameAboutToBeRendered: presentationTimeMS = 300.0 | GetCurrentTimeS(in MS)227.0 | m_TextureTimeStamp = 87112498505431
onVideoFrameAboutToBeRendered: presentationTimeMS = 333.333 | GetCurrentTimeS(in MS)257.0 | m_TextureTimeStamp = 87112531838763

**Comment by HaimBendanan** [comment]
Let's try it and see :) 
How can I test it?

**Comment by RenderHeadsSte** [comment]
Unfortunately there is a sticking point here.  VideoFrameMetadataListener was only introduced in ExoPlayer 2.9.0.  v1 of AVPro Video is stuck at v 2.8.4 (whihc is the release prior to VideoFrameMetadataListener being added).

The upshot is that there is no way we can make this change to v1.  I will make it for v2 and it will be included in beta5 that we are planning on releasing by the end of this week.  I know this doesn't help you much as all beta releases of v2 are watermarked trial versions. 

The only other thing I can think to try is store the surface timestamp (which is what is returned currently) on the first frame returned, and subtract that off subsequent timestamps.

**Comment by HaimBendanan** [comment]
Storing the initial timestamp won't work, it seems it is randomly changing while playing :( 
What about overriding `processOutputBuffer()` as mentioned [here](https://stackoverflow.com/questions/33626850/android-exoplayer-get-current-frame-number-from-video#comment61351768_33626850)? 
If `VideoFrameMetadataListener`  is the only option, I will try beta5. If that works, is there no way to remove the watermark on the beta?

**Comment by RenderHeadsSte** [comment]
Ahh, sorry, missed that link first time round.  Will implement in v1 and see what comes out.

All beta releases of v2 will be watermarked.

**Comment by RenderHeadsSte** [comment]
@HaimBendanan: I have created a beta of the next version of the Android plugin of v1.  I will message you over the unitysupport email channel to arrange delivery for you to test.

**Comment by RenderHeadsSte** [comment]
By way of an update. We have re-implemented GetTextureTimeStamp() in both v1.11.6 and v2 (beta5).  We now return the last textures presentation time - ExoPlayer and Mediaplayer API >= 23. MediaPlayer API < 23 will return a 'best guess'.
