### ISSUE TITLE
MKV video freezes on first frame

### ISSUE THREAD

**Issue by mvmvm** [RenderHeads/UnityPlugin-AVProVideo#494]
Hi there
I'm develop a simple player for 360 video in Unity 2019.4.3, using last version of AVPro plugin/exoplayer on Oculus Quest
And sometimes my files are freezing on first frame, sometimes not
Videos in H256 codec 5760x2880 35mbps 30 minutes long with main profile and audio in wav 9ch ambisonics + 2 stereo, then i muxing it in MKV container with Facebook 360 encoder
Downscaling video to 5120x2560 and 4096x2048 and changing codec to H264 not helps

Logcat gives me some issues
Somebody knows what could be wrong?
![Screenshot (34)](https://user-images.githubusercontent.com/72887338/96055104-e4fd9880-0e8b-11eb-957a-9d33f5633dba.png)

**Comment by AndrewRH** [comment]
Hmm that's strange.  I have a few followup questions:

1) How often does it freeze on the first frame in your app?

2) Have you tried playing your video in our demo scenes?  Does it also freeze in those?

3) Could you post the full log here?

4) Are you using the OES rendering method?  (it's advised as it will use less memory, which for huge videos like yours is important)

5) If you remove the audio track does that solve it? (i'm trying to figure out if it's the video or audio track that's causing this issue)

6) Have you tried updating the firmware on the Quest?

7) Finally if we're not getting anywhere after the above, we would need you to send us your project so we can replicate it and investigate further (see the product support email address at https://www.renderheads.com/contact)

Thanks,
