### ISSUE TITLE
FinishedPlaying () //custom event trigger

### ISSUE THREAD

**Issue by DanielTocik** [RenderHeads/UnityPlugin-AVProVideo#495]
Hi there, **RenderHeads**. 

May I ask you for your help, please? It might help others as well! I wonder if it is possible to set up a custom event trigger like this:  

![Event trigger](https://user-images.githubusercontent.com/72899062/96068099-70caf100-0e9b-11eb-8a1f-742045c12c65.jpg)

...so when my main video reaches the end or ''FinishedPlaying'', another function gets automatically called. I feel like it should be a fairly short and easy C# script. Probably something close to your example script from AVpro's documentation: 

![5641F4DC-B08B-4F9D-BD85-E67D8AAD3EEC](https://user-images.githubusercontent.com/72899062/96068765-0e72f000-0e9d-11eb-8b1c-bab8af3a20be.jpeg)

**Any suggestions will be highly appreciated! :)** 

Thanks 
Dan

**Comment by AndrewRH** [comment]
Yes, it's almost exactly like that 👍 
For an example perhaps look at the included script SimpleController.cs - you'll see how it sets up the event listener and handler.

Thanks,

**Comment by RenderHeadsSte** [comment]
@DanielTocik Are you happy with this answer?  Can we close this issue?
