### ISSUE TITLE
Memory leaks when running on Windows 10.

### ISSUE THREAD

**Issue by R-Kamimura** [RenderHeads/UnityPlugin-AVProVideo#496]
Hello,

When using AVProVideo to continuously play back a movie file, the memory usage will gradually increase.
I am using BigBuckBunny_720p30.mp4 which is included in the AVProVideo package and the settings are MediaFoundation and HardwareDecoding.
It looks fine on UnityProfiler, but if you look at it on Windows ResourceMonitor, you can see that the memory usage has increased.

Execution Environment :.
OS: Windows 10
CPU: Intel Core i3 3.50GHz
GPU: NVIDIA Quadro P620

Are there any causes of memory leaks in AVProVideo?

**Your Setup (please complete the following information):**
 - Unity version: 5.6.6f2
 - AVPro Video version: Version 1.11.5 
 - Operating system version: Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): AVProVideoSamples/BigBuckBunny_720p30.mp4

**Screenshots**
*Before*
![AVProVideoTest_Before](https://user-images.githubusercontent.com/72904150/96096154-7f042600-0f0a-11eb-8620-2811fd786ca2.png)
*After*
![AVProVideoTest_After](https://user-images.githubusercontent.com/72904150/96096213-8f1c0580-0f0a-11eb-8ccb-75803dbf887e.png)

**Comment by AndrewRH** [comment]
Thanks,

1) Try updating your GPU Drivers - there could be bug in them

2) What exactly is your app doing?  It it just playing that video on loop, or are you reloading the video etc?

3) How much does the RAM increase over time, or per play?  Does it continue to increase forever?

4) Is your build 32-bit or 64-bit?  Try the other one and see if it still happens.

We have not seen a leak, but once we have the information above we should be able to help further.

Thanks,

**Comment by R-Kamimura** [comment]
Thank you for your reply.

> 1. Try updating your GPU Drivers - there could be bug in them

The GPU driver is up to date.

> 2. What exactly is your app doing? It it just playing that video on loop, or are you reloading the video etc?

I am reloading the same video file. One second after playing it, it destroys the video by calling "GameObject.Destroy()". And it repeats the process.

> 3. How much does the RAM increase over time, or per play? Does it continue to increase forever?

It doesn't increase by a fixed amount per play, but it does increase overnight, as shown in the attached image.

> 4. Is your build 32-bit or 64-bit? Try the other one and see if it still happens.

Both occur.

Thanks,

**Comment by AndrewRH** [comment]
So I've left it running, constantly loading the sample video, and I did see an increase in memory usage over time, but it settled down after a while and then it would decrease and then build up again.  It never went over a certain amount, which leads me to think that this is just the system allocating various buffers internally.  I can't see the behaviour of a typical leak where it increases forever until eventually you run out of memory.
