### ISSUE TITLE
OES shader video gives a little glitch

### ISSUE THREAD

**Issue by sammyvrmadman** [RenderHeads/UnityPlugin-AVProVideo#497]
**Describe the bug**
On android using the OES shader the video gives a little glitch when switching between resolutions

**Your Setup (please complete the following information):**
 - Unity version:  2019.4.1.f1
 - AVPro Video version: v 1.11.1
 - Operating system version: android 9
 - Device model: huawei psmart +
 - Video specs (resolution, frame-rate, codec, file size): 
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=3715062,AVERAGE-BANDWIDTH=3160000,RESOLUTION=2048x1024,FRAME-RATE=30.000,CODECS="avc1.640028,mp4a.40.2",AUDIO="audio-high"
../3ace431d/playlist.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=10711473,AVERAGE-BANDWIDTH=9802000,RESOLUTION=3840x1920,FRAME-RATE=30.000,CODECS="avc1.640034,mp4a.40.2",AUDIO="audio-high"
../64cd4a4c/playlist.m3u8
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,BANDWIDTH=6982353,AVERAGE-BANDWIDTH=5877000,RESOLUTION=2732x1366,FRAME-RATE=30.000,CODECS="avc1.640033,mp4a.40.2",AUDIO="audio-high"
../abf31c1a/playlist.m3u8

**To Reproduce**
1. use a .m3u8 or .mpd link with atleast 1 resolution that that aren't a multiple of 16 and also one that is.
2. Play the video on mapped to a sphere, with oes shader on android

**Videos**
So the bug with the seam is fixed after your update see https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/354 however it still gives a little glitch when switching between these resolutions here is an example of what it looks like
https://youtu.be/0X4XSL_Ekvc

**Comment by RenderHeadsSte** [comment]
Is it possible to provide a stream URL?

**Comment by sammyvrmadman** [comment]
Hi yes but I am using the vimeoplayer though so the url will lose it's validity in like a day 

https://30vod-adaptive.akamaized.net/exp=1602837911~acl=%2F9ce353ea-82c7-4541-b072-76bfaf9677ad%2F%2A~hmac=95ef12e6eea8b5c9392fc91e40ba9a16080b07d40535e935d249de446b186cb4/9ce353ea-82c7-4541-b072-76bfaf9677ad/sep/video/902a8bc9,04d09b99,6306105a/master.m3u8

I have the vimeo url here aswell:
https://vimeo.com/344791999

**Comment by RenderHeadsSte** [comment]
The link appears to have expired...?

**Comment by sammyvrmadman** [comment]
Ah yes I see I changed the permissions now

**Comment by RenderHeadsSte** [comment]
I am getting the same:

Access Denied
You don't have permission to access "http://30vod-adaptive.akamaized.net/exp=1602837911%7eacl=%2F9ce353ea-82c7-4541-b072-76bfaf9677ad%2F%2A%7ehmac=95ef12e6eea8b5c9392fc91e40ba9a16080b07d40535e935d249de446b186cb4/9ce353ea-82c7-4541-b072-76bfaf9677ad/sep/video/902a8bc9,04d09b99,6306105a/master.m3u8" on this server.
Reference #18.99f44317.1602850278.8726164

**Comment by sammyvrmadman** [comment]
ah oke yes it expires because it's generated by vimeo with a different token each time here is another one https://30vod-adaptive.akamaized.net/exp=1602857077~acl=%2F9ce353ea-82c7-4541-b072-76bfaf9677ad%2F%2A~hmac=c22351a127023f86fac9d9a7223651d54b7f00606739d000d2edd12c0f643fa7/9ce353ea-82c7-4541-b072-76bfaf9677ad/sep/video/902a8bc9,04d09b99,6306105a/master.m3u8

**Comment by RenderHeadsSte** [comment]
@sammyvrmadman  We think the glitch is happening when changing from one stream resolution to another where there is a change in whether the texture matrix adjustment is required to account for padding.

Hunch is the glitch is happening for one frame where the padding is being applied into the shader when it shouldn't be.

In order to verify any fix we are going to need a dedicated HLS stream.  Are you able to send over your HLS stream so we can serve is locally to us for continued testing/resolution?  If so, please send it over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com).  If not then we will have to recreate a similar stream here in the hop we can recrate the issue (this will push the timescale up).

**Comment by sammyvrmadman** [comment]
Hi unfortunately because we use the vimeo sdk I do not have a dedicated HLS stream, however you could create a the same stream by using the vimeo sdk and parsing the hls manifest and cutting out the 4 lowest resolutions. that's exactly what we do.

**Comment by RenderHeadsSte** [comment]
Could you at least send us the three source videos (the three resolutions) so we can recreate it.  I am afraid that if we have to put together everything here from scratch, it is going to lower the priority for addressing the issue.

**Comment by sammyvrmadman** [comment]
Hmm well vimeo does the encoding but I can encode the video manually myself in those 3 resolutions would that be workable for you ?

**Comment by RenderHeadsSte** [comment]
Anything you can provide that will save us time (we are extremely busy putting version 2.0 together) will help! Thanks

**Comment by sammyvrmadman** [comment]
> Anything you can provide that will save us time (we are extremely busy putting version 2.0 together) will help! Thanks

I've send you an email to: unitysupport@renderheads.com with the issue number and title in the subjectline with the 3 video's in the right resolution.

**Comment by AndrewRH** [comment]
@RenderHeadsSte  - can this be closed or shall we give it an enhancement/bug/high label to keep it alive if it's still being looked at?

**Comment by RenderHeadsSte** [comment]
I have a kind of fix implemented in v2.x.  Unfortunately we will not be able to back port this to v1.x.

I say 'kind of fix' because I am now getting the exact same results in OES as I get in none-OES, and the glitch is certainly not the same as you were seeing and reported in the youtube video you posted..  In the HLS I put together, I see a slight offset/squash difference in X/width when the middle video is switched to.  I am applying the texture transform matrix that comes back from the decoder, so there is little more we can do than that.

**Comment by sammyvrmadman** [comment]
> I have a kind of fix implemented in v2.x. Unfortunately we will not be able to back port this to v1.x.
> 
> I say 'kind of fix' because I am now getting the exact same results in OES as I get in none-OES, and the glitch is certainly not the same as you were seeing and reported in the youtube video you posted.. In the HLS I put together, I see a slight offset/squash difference in X/width when the middle video is switched to. I am applying the texture transform matrix that comes back from the decoder, so there is little more we can do than that.

Thanks for looking at it I will update to v2 soon, I never saw anything in none-OES so that should work!

**Comment by RenderHeadsSte** [comment]
A fix has been offered for this issue in v2.1.0 which has been released today.  Please do report back if you get chance @sammyvrmadman

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
