### ISSUE TITLE
After upgrade Gradle tool, Unable to play video

### ISSUE THREAD

**Issue by lwtbn1** [RenderHeads/UnityPlugin-AVProVideo#498]
**Describe the bug**
After upgrade Gradle to 4.6  and
dependencies {
		classpath 'com.android.tools.build:gradle:3.2.1'
	}。
Unable to play video，no such file or directory。
But when i use Gradle 2.10 and 
dependencies {
		classpath 'com.android.tools.build:gradle:2.1.0'
	}。
it's ok
any one can help?

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.37f1
 - AVPro Video version: 1.11.4
 - Operating system version: android
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Can you provide a full logcat output?  Even better would be to send the AndroidStudio project over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
