### ISSUE TITLE
[HIGH PRIORITY] Fails to initialize on ARM64 with IL2CPP

### ISSUE THREAD

**Issue by SniperED007** [RenderHeads/UnityPlugin-AVProVideo#50]
On Android... throws the following error when running on ARM64 with IL2CPP which is a requirement from Google Play store starting from 1 August 2019 all releases must be compliant with the Play 64-bit requirement.

05-01 11:33:12.901 14728 14801 E Unity   : AndroidJavaException: java.lang.NoClassDefFoundError: com.RenderHeads.AVProVideo.AVProMobileVideo
05-01 11:33:12.901 14728 14801 E Unity   : java.lang.NoClassDefFoundError: com.RenderHeads.AVProVideo.AVProMobileVideo
05-01 11:33:12.901 14728 14801 E Unity   :      at java.lang.Class.classForName(Native Method)
05-01 11:33:12.901 14728 14801 E Unity   :      at java.lang.Class.forName(Class.java:453)
05-01 11:33:12.901 14728 14801 E Unity   :      at java.lang.Class.forName(Class.java:378)
05-01 11:33:12.901 14728 14801 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
05-01 11:33:12.901 14728 14801 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
05-01 11:33:12.901 14728 14801 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
05-01 11:33:12.901 14728 14801 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:395)
05-01 11:33:12.901 14728 14801 E Unity   :      at android.os.Looper.loop(Looper.java:181)
05-01 11:33:12.901 14728 14801 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
05-01 11:33:12.901 14728 14801 E Unity   : Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.LighthouseGamesStudio.ChallengeStars-m8qVikusn872Di8r-NwmyA==/base.apk"],nativeLibraryDirectories=[/data/app/com.LighthouseGamesStudio.ChallengeStars-m8qVikusn872Di8r-NwmyA==/lib/arm64, /data/app

**Comment by wombatzus** [comment]
What I noticed was, when I installed the package, there were arm64 versions of the libraries, but I had to select them in Unity and check the box to enable them, and change their architecture to arm64. This worked for me.

**Comment by SniperED007** [comment]
> What I noticed was, when I installed the package, there were arm64 versions of the libraries, but I had to select them in Unity and check the box to enable them, and change their architecture to arm64. This worked for me.

Thanks, I'll give that a try.

**Comment by SniperED007** [comment]
Yup, that worked.
