### ISSUE TITLE
Video don't load from StreamingAsset on Oculus Quest

### ISSUE THREAD

**Issue by Xela124** [RenderHeads/UnityPlugin-AVProVideo#500]
**Describe the bug**
I'm working for a customer on a 360 sphere video app on Oculus Quest. The app is basically one script that just plays the mediaplayer when the headset is mounted. However, I set the mediaPlayer to play a video from StreamingAsset but when I launch the app, i got a black background and the video never start/show. 

![AvPro_Request_01](https://user-images.githubusercontent.com/51998689/96630321-1e635780-1315-11eb-9311-0e0b5238753d.PNG)
![AvPro_Request_02](https://user-images.githubusercontent.com/51998689/96630322-1f948480-1315-11eb-830f-516b1f5e928c.PNG)

I tried with your SampleSphere.mp4 and everything works well as expected! 
The video we get from the customer is pretty heavy ! 6.1Go at 4K 60fps Mp4.

I also tried with a small video (1Go - a part of the "Big" video) and it never loaded... Only your sample works
I also tried the "OpenVideoFromFile" that's return true but never start the video and the sphere stays black in the Oculus App

Is it really possible to load such a big file on an Oculus quest ? I test it on PC and everything works perfectly. Seems that the Quest has trouble (maybe memory ?) to load a 6.1Go file ? 

Am I Missing something ? I'm pretty new with the pluging and the Oculus Quest Developement so I'm a bit confused.
I'm having the warning that says it's not recommended but i did not see what can i used instead

Thank for you help !

**Your Setup (please complete the following information):**
 - Unity version: Unity 2019.3.3f1
 - AVPro Video version: 1.11.5
 - Operating system version: Android I Guess
 - Device model: Oculus quest
 - Video specs (resolution, frame-rate, codec, file size): 4K | 60FPS | MP4 | 6.1Go. 360 Video with Top-Down Packing

**Comment by RenderHeadsSte** [comment]
Maybe check your video fits within the recommended guidelines?

[https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/?locale=en_GB](https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/?locale=en_GB)

**Comment by Xela124** [comment]
Yes I totally mean 6.1Go file size. The size is maybe big but in the past on Oculus Go we manager to play a .mkv file with a size of 2.5Go. I maybe need to stop with mp4 and start working with .mkv ?

I check the mp4 file and got a "moov" at the start (see picture below)
![AvPro_Request_03](https://user-images.githubusercontent.com/51998689/96683633-b5162f80-137a-11eb-8552-c430e9d0eade.PNG)

**Comment by RenderHeadsSte** [comment]
Have you tried streaming the mp4 off a server?  This might rule out the filesize being an issue.  That said, I am not aware that the Quest has any limits on filesize...I am 99%sure it isn't fat32 under the hood!

**Comment by Xela124** [comment]
We can't streaming it. The client we work for don't want..

We think that the problem comes from the video. I tried to play the video via the video player integrated to the Quest and the result is that the video is not playing. Got a blackscreen and the timeline stay at 00:00.

I also tried to put the video file to the persistant data of the application. And now i got a green screen instead of the video on the mediaplayer. I also tried to set the preferred Video Api to "Media Player" and nothing is changing. It seems that the media can't load the video

I remind that the application works without problem with your video "SampleSphere".

**Comment by RenderHeadsSte** [comment]
I only meant stream it as a test, not a solution.

I think you are correct...it is very telling that the default Oculus video player will not play it.  If that won't AVPro Video is very unlikely to.

**Comment by Xela124** [comment]
We tried to compress the video and i'm still having the green screen.. 
Here is a link to download the video : https://we.tl/t-HaAbhBM8zf. Maybe we miss understood something ?

**Comment by Xela124** [comment]
Litlle up : 
I tested it on a Oculus Quest2 (It's the same apk). I don't have any problems for loading the video. Everything works as expected ! So it maybe come from oculus Quest hardware ?

**Comment by RenderHeadsSte** [comment]
I have just downloaded your video.  It is because it is beyond the limits of the Quest - as per the link I sent yesterday.

When you had said it was '4k' I had assumed you meant 4096x2048 (or 3840 x 2160) which the Quest 1 can do at 60fps in both H264 and H264.

Your video is 4096 x 4096, which the Quest 1 can do but only at 30Hz and only with H265. Your video is 60fps and H264...which the quest cannot do.

I am closing this as a none-bug.
