### ISSUE TITLE
Last Video Frame as Default Texture

### ISSUE THREAD

**Issue by A4VR** [RenderHeads/UnityPlugin-AVProVideo#505]
Hey there, 
I don't know if this feature exists, but i can't find it anywhere. 
It it possible to save the last rendered frame as default texture when switching Video content?
We have a Networked Videoplayer solution for Vr and currently when we switch Video Content we have a short black screen. Our Video content consist of simular scenes, so a freeze frame on Video switch won't be that noticeable. 
Creating a deefault texture for every Video would be very time consuming in our case because we cas switch out videos post build.

**Comment by A4VR** [comment]
We are using the default AVPro Video Plugin (Android) for Unity 2019.4.8f1 updated to the newest Version. 
We just used the 360vr Demo prefab. Mediaplayer setting are almost default aswell. Just changed Video Path to absolut path.
We genarate Buttons for each Video File in a Folder. We then just switch videos just by "Mediaplayer.OpenVideoFromFile".
We build the Experience for Android Tablet and AndroidVR (Oculus Go). The Blackscreen (for a few frames) appears on both Systems. I trieda small Hack, transparent default Texture and Video Thumbnail as Background Image. It kinda worked but the Colors were a bit off. It would be an elegant solution to copy the last Frame before switching Videos and setting it as Default Texture. Instead of an black screen we would than have the last frame as still image while the new Video is Loading. I tried Graphics.CopyTexture() but could't get it to work.

**Comment by RenderHeadsSte** [comment]
Have you thought about using two MediaPlayer components?  You can leave one playing, or paused whilst you spin up the newly chosen video (which is on the other MediaPlayer component)...then when that is ready to play, or the first frame is ready might be better suited to our use-case, you swap over to render the new player.

Alternatively, a better fit for your use-case might be to use the PlaylistMediaPlayer - see the 14_Demo_PlaylistTransitions demo.
