### ISSUE TITLE
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

### ISSUE THREAD

**Issue by aracid** [RenderHeads/UnityPlugin-AVProVideo#507]
Hey there

I seem to get this error a lot when changing videos that have different encoding properties and formats.

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

Everything works fine with videos that have matching specifications.

I see that in the PlaylistMediaPlayer scene it has 2 Media Players are instantiated however I've heard that this may be a problem when play 4/5/6k footage on the oculus quest.

What is the correct way to switch videos that have different properties or is the recommended route recreating a media player?

Unity 2020.1.8f1 
AVPro 1.11.5

Thanks in advance

**Comment by aracid** [comment]
Hi there
Any chance that advise provided about this issue?

Thanks in advance

**Comment by AndrewRH** [comment]
Do you have the options ```autoCloseVideo``` and ```pausePreviousOnTransition``` enabled in ```PlaylistMediaPlayer```?  These will help to free up resources when loading the second video.

The problem with 5K/6K video on that platform is that you're at the limits of what the device can decode, so if you then load another video while the first is still loaded, then it will have to allocate new buffers, textures etc.  at least if the video is the same resolution then it has a chance of perhaps sharing some of the existing buffers.

If the above doesn't help then you may want to instead just use a single ```MediaPlayer``` which will ensure the first video is closed before the second video is displayed.  This will cause a few frames where there is no texture available to display.  If this is an issue then you could potentially create a ```RenderTexture``` and ```Graphics.Blit()``` the current ```MediaPlayer.TextureProducer.GetTexture()``` into it and display that while the next video loads.  It may be easiest to modify ```PlaylistMediaPlayer``` to do this.  

In version 2.0 of the plugin we hope to improve the behaviour for this use case.

Thanks,

**Comment by aracid** [comment]
Hi Andrew

Thanks for the response,

I was hoping to actually do this via one MediaPlayer, the error occurs when I load a video with certain specifications(Resolution/Sound Mode), then stop that video, and then load a different video with different a resolution and sound mode that it reports that error.

This doesn't occur with same video specifications.

Thanks again in advance
Brian

**Comment by huzhongxia** [comment]
Is there a solution?

**Comment by mykrana** [comment]
Hi,

i get the same error when I'm trying to play a 360 video from an rtsp url.  
Does AVProVideo support 360 live streaming?

Unity 2019.4.14f1
AVPro 1.11.7

**Comment by RenderHeadsSte** [comment]
> Hi,
> 
> i get the same error when I'm trying to play a 360 video from an rtsp url.
> Does AVProVideo support 360 live streaming?
> 
> Unity 2019.4.14f1
> AVPro 1.11.7

There is limited support for RTSP...which is as outlined in the v1.x PDF manual.  360 support is not limited to the streaming delivery and will work regardless of how the video frames are delivered.

**Comment by RenderHeadsSte** [comment]
> Is there a solution?

If you are the limits of the device being used, and the options that Andrew has outlined do not help your use-case, then there is no solution on the given device other than to lower resolution of your videos.

**Comment by PaulKsi** [comment]
Same here, samsung galaxy tab s5e
