### ISSUE TITLE
Trying to use https headers to access AWS Cloudfront stream

### ISSUE THREAD

**Issue by dalkia** [RenderHeads/UnityPlugin-AVProVideo#508]
**Describe the bug**

Hello! Im trying to access a mpd stream from a AWS CloudFront url using a PreSigned Cookie, to ensure that only authenticated users gets the video.

I am adding the Cookie through the HTTP header, but I always get the FileNotFound exception. I know the values of the cookie are fine, as I can get the stream if I go through Postman, using the exact same header. 

Could it be there is some malforming in the request?

Any recommendations? Thanks for your help!

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.3
 - AVPro Video version: 1.11.5
 - Operating system version:  Android 9
 - Video specs (resolution, frame-rate, codec, file size): Expo Player, mpd stream

**To Reproduce**
1.  Use uGUI scene from the examples
2.  Change address and insert AWS credentials
3. Build and play.

**Logs**
If applicable, add error logs to help explain your problem.

![image](https://user-images.githubusercontent.com/1999557/97361566-7a326100-187e-11eb-9a74-a4ab70908aad.png)

**Videos**
If applicable, add a copy of your video or the URL

URL: https://d3b8l6web9hs03.cloudfront.net/fish/Prachtflosser.mpd

HttpHeader being used:
```
Key: Cookie 
Value: CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kM2I4bDZ3ZWI5aHMwMy5jbG91ZGZyb250Lm5ldC9maXNoL1ByYWNodGZsb3NzZXIqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjA0Njk2ODQzfX19XX0_; CloudFront-Key-Pair-Id=APKAJI242OSPYR5SKKMQ; CloudFront-Signature=aPsP7XSTdI6mz0KQ~dTQ2bpCBdvrnCR22cKIXIVp9v9ulMMC1zbxNzKLP316JOTW~dKRRgCPaQHE-yqOeyCg1Xfl3eQ8WzC17x9HZu8OeqKVNyL2w1yIGskniAluorLX-B2NbqxFuP0eveXOhdjnVLJo8PLNqseMFFBlGxpNTlygkT9nXAteXnn5Vw~-y4i9AETH-s1SkczVpQOn2Sb-4KFCWE5uoOgTyj427bptf8sCXCHo058Bnf0EbqaKUjHwkX5rwCxdvOXseckJ67G4Q-JLDXkRquLlbJ6ahOC5A-NKCdmON8es6yTyT7p6-rfhzgeM8o3FG2AyDjFyRwfCFg__
```

**Comment by dalkia** [comment]
So, I ve tried using it in the  2.0.0 beta 5 using the same video and settings, and it works in Android.

Any recommendation on how should I procede? Is there something I could try passing from one project to the other one?

**Comment by AndrewRH** [comment]
Thanks @dalkia - could you paste us the full adb logcat of the AVPro Video 1.11.5 build please?  There's probably an exception happening somewhere, and that will help us identify the issue.

Thanks,

**Comment by dalkia** [comment]
Sure thing.

I was just printing the Unity log. Now that I expanded it to all, I think found a 

bug:

-s Unity Log:
![Only_Unity_Log](https://user-images.githubusercontent.com/1999557/98024123-9ede8980-1de6-11eb-931b-0c334c7a2da2.png)

Full Log:
![Full_Log](https://user-images.githubusercontent.com/1999557/98024155-abfb7880-1de6-11eb-9751-5d280f87d3d4.png)

**Comment by dalkia** [comment]
Hello! Any news?

Im having a deadline coming real soon. Given that it work in AVProVideo 2.0.0 beta 5, would you recommend chaing my current version to that one? If answer is yes, how can I get the version without the watermark?

**Comment by RenderHeadsSte** [comment]
I have been looking into it.  There is a possible fix (outlined [here](https://stackoverflow.com/questions/51459344/getting-a-403-response-code-error-from-exoplayer)). But it is far from risk free and so we will not be looking to implement it within AVPro version 1.

That said, there might be some joy found by looking at the information in [this](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/438) issue. 

I wonder also, if you could try serving it via HTTP (rather than HTTPS)...as a test...?

**Comment by dalkia** [comment]
Hello!

I thougt about using http, but unfortunately, due to Play Store policies, I am obliged to use https. I can try It, but even if it works, I cant use it. 

Im setting up the required headers, as suggested by the issue mentioned. I pass the cloudfront credentials to get the authorized link, and also checked that my configuration is correct on cloudfront.

Maybe I should change the exoplayer in my versión of AVPro to use the one in versión 2.0.0?

**Comment by RenderHeadsSte** [comment]
It is very unlikely that changing the ExoPlayer library files will work due to interface changes between versions.

**Comment by dalkia** [comment]
Mmmmmh.

Do you have anything else in mind that I could try?

Thanks!

**Comment by dalkia** [comment]
Hello!

So, any other suggestion to try? Is there some way I can try and integrate exoplayer2 to the current version of AvProVideo?

Thanks!

**Comment by RenderHeadsSte** [comment]
I would like to take another look at this today as we have had a report of cloudfront problems on Android that, apparently, worked in version 1.10.2.   Is it possible to make the stream available again @dalkia ?

**Comment by dalkia** [comment]
Hello @RenderHeadsSte !

Sure. This token should be validad for the following 7 days. The url is the same: https://d3b8l6web9hs03.cloudfront.net/fish/Prachtflosser.m3u8

`Key: Cookie 
Value: CloudFront-Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kM2I4bDZ3ZWI5aHMwMy5jbG91ZGZyb250Lm5ldC9maXNoL1ByYWNodGZsb3NzZXIqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjA2NDYwMTYxfX19XX0_; CloudFront-Key-Pair-Id=APKAJI242OSPYR5SKKMQ; CloudFront-Signature=QPjS~U8yb2-cR~XtQYNOnpaxRsdeKv1zCVgV70wyk4aW8uIYMH8GQJtE1hkxc3IwGRsIY~ozse14yGuKZyLx4uBTILjHdJ3eb5-kC8jb72vSxb~NC1OdB8MmlwQgmyywAtEixw4GA1M2S6-yExfolsgkjWnqf1fFX2BtjB1ApsQRpb4CvEtpoVbTuHp0sv64oylSHGvsJYBg6K1pJRz-0IrEGxSqQ2i4Qz4VrSAshmy7mJXNKY3ER9sGa5zI5Xa9K4b8hEn3TZpXLgxo3luPhst4UEytcKfwRiFkvl2TmI7aFztPXWKpIkMwxPjjANIanagMpEU~z74lW5BkqmmBlA__`

Thanks for your help!

**Comment by AndrewRH** [comment]
@RenderHeadsSte  not sure if you're looked at this yet, but the stream will expire soon

**Comment by dalkia** [comment]
Hey @RenderHeadsSte ! Did you get a chance to look at the stream?

So, I ve searched around regarding the 403, cookie handling and setting headers. There are different solutions, I would really like to try setting up the Cookie Manager as described here (https://github.com/google/ExoPlayer/issues/3728). 

I really cant do much as I cant modify or debug the code inside the AVProVideo jar.  Is there anything I can do to help you with this issue?

Also, if thats not possible, is there a release date regardin V2 of AvProVideo? I got it working there, so if there is an estimation of release, I can plan accordingly.

This is a requirement for my development, so if I can t do anything about it, I have to start looking for a workaround. 

Thanks for your help!

**Comment by RenderHeadsSte** [comment]
@dalkia playing with the cookie manager was something I tried...but the changes became quite involved (bringing in new libs and overriding okhttp3 etc).  Basically it became a whole rabbits hole where the changes would have put far more at risk than they solve.

'Working in v 1.10.2' is s false.  So that is not worth pursuing.

The only option here is v2.  We expect release 'within the coming weeks, and certainly before the year is out'.  I hope this helps you plan.

**Comment by dalkia** [comment]
@RenderHeadsSte Thanks for the heads up! It helps with my plan. Lets keep in touch =).

Thank you!
