### ISSUE TITLE
want to know avpro support dual gpu decode video

### ISSUE THREAD

**Issue by fingerx** [RenderHeads/UnityPlugin-AVProVideo#509]
want to know avpro support dual gpu decode video,thanks

**Comment by AndrewRH** [comment]
I don't believe that decoding a video can be split across GPUs.  The only thing I can think of is being able to select which GPU does the decoding - but no this isn't supported - we just decode the video using the same GPU that Unity is using for rendering.

**Comment by fingerx** [comment]
@AndrewRH  thanks infos.If I use dual GPUs, can I use any gpu hdmi interface to output video signals normally?

**Comment by AndrewRH** [comment]
Yes you should be able to, however the GPU doing the decoding will have to copy the video frames over to the 2nd GPU, so there is extra overhead.  Overall a single GPU solution usually gives the best results.

**Comment by fingerx** [comment]
@AndrewRH  thanks
