### ISSUE TITLE
Buffering issues in when trying to stream from Vimeo in 4k

### ISSUE THREAD

**Issue by falldeaf** [RenderHeads/UnityPlugin-AVProVideo#51]
**Describe the bug**
My app is pulling 4K video from Vimeo and it constantly buffers every 4-5 seconds. The in-editor preview works fine on desktop. And if I use a 2K video feed that seems to work well too. Both the buffer and stalled events are being called, the buffer event gets called just before stalled. (What's the difference between these two events?) On the same network, I'm able to watch 4k video on the Oculus Go on someone else's app (Amaze). Is there a way to increase the size of the buffer that gets downloaded and cached before playing, maybe? I also tried to stream the video with the demo/example AVPro scene only to ensure there wasn't something else in my app hogging either bandwidth or GPU.

**Your Setup (please complete the following information):**
 - Unity version: 2018.3.13f1
 - AVPro Video version: 1.9.12
 - Operating system version: 
 - Device model: Oculus Go
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Load demo 360 scene (08_Demo_360SphereVideo.unity)
2. Set avpro player to any 4k 360 vimeo url 
3. Build and run on Oculus Go

**Comment by AndrewRH** [comment]
I've heard via email that this was resolved by reencoding the video.. Closing this ticket.
