### ISSUE TITLE
Quest2 online video （HTTP、HLS） black screen

### ISSUE THREAD

**Issue by leewensong** [RenderHeads/UnityPlugin-AVProVideo#510]
**Describe the bug**
Quest2 online video （HTTP、HLS） black screen
Quest is OK with same APK

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version: 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

Quest 2 is running Android 10 which has higher security requirements.  I believe the issue may be that your URL is HTTP instead of HTTPS.  

Does that help?

**Comment by leewensong** [comment]
Yeah, my URL is HTTP, but I'm using HLS Live Steaming, which is HTTP based
by server, I cant't change the URL.
How to get  higher security  in Android 10?

Andrew <notifications@github.com> 于2020年11月1日周日 上午1:53写道：

**Comment by AndrewRH** [comment]
Have a look at this issue here, as it explains various ways to solve this issue without having HTTPS available on the server: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/352

I believe this should solve your issue.

I'm just assuming this is the issue - we would need to see the full log (via adb logcat) to know for sure.

Thanks,

**Comment by shounak00** [comment]
Baler plugin baniso tmi shauya choda. 

the solutions doesnt work what u mentioned there.

**Comment by shounak00** [comment]
shauwa choda madarchod

**Comment by shounak00** [comment]
Reply des na khanki magir pola

**Comment by AndrewRH** [comment]
Do send us the full Android log from ADB LOGCAT to see what the error messages are.  

Thanks,

**Comment by RenderHeadsSte** [comment]
@leewensong We suspect you are seeing the following issue...

On Android 9 and above HTTP streaming is not supported by default. You have to use HTTPS url, or you have to enable 'cleartext' in the AndroidManifest.xml.

See: [https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6](https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6)

**Comment by leewensong** [comment]
Thanks guys! I fixed this by  enable 'cleartext' in the AndroidManifest.xml.
