### ISSUE TITLE
Can't play the sample video in 'AVPro Demo 360 Spatial Audio demo'

### ISSUE THREAD

**Issue by AldeRoberge** [RenderHeads/UnityPlugin-AVProVideo#511]
**Describe the bug**

Can't play the sample video in 'AVPro Demo 360 Spatial Audio demo'

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.12f1 (LTS)
 - AVPro Video version: Latest
 - Operating system version: Windows 10
 - Video specs (resolution, frame-rate, codec, file size): FantasyStereoFB360.mkv

**To Reproduce**
1. Install the package
2. Try to run the AVPro Demo 360 Spatial Audio demo

**Logs**
If applicable, add error logs to help explain your problem.

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

StreamingAssets\AVProVideoSamples

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hmm that's strange... we haven't had anyone else report a problem and it's working fine for me.

I'm not sure what to suggest.  Could you try it on another system?
