### ISSUE TITLE
DirectX 12 Compatibility

### ISSUE THREAD

**Issue by djorna** [RenderHeads/UnityPlugin-AVProVideo#513]
My team is looking into switching to DX12 so that we can use DirectML for machine learning. Our software currently relies on AVProVideo, and it is our main obstacle to switching.

Is there any plan to support DX12 in the future?

**Comment by AndrewRH** [comment]
Hi,

Yes we have DX12 support coming in the next major version - 2.0 which is currently in beta and available for trial here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/2.0.0beta5

Should be released fairly soon.

Thanks,

**Comment by djorna** [comment]
Hi Andrew,

Awesome, I'll test it out. Thanks.
