### ISSUE TITLE
Getting Errors when running AVPro v2.0beta5 on Android with Exoplayer

### ISSUE THREAD

**Issue by shazamk** [RenderHeads/UnityPlugin-AVProVideo#514]
**Describe the bug**
1. Android build crashes when using Media Player with settings:

- Video API: Exo Player
- Audio Output: System Direct

Additional details:
Runs _StartedBufferring_ Media Player event, followed by _java.lang.AbstractMethodError_, then runs _Closing Media Player Event._

------------------------------------------------------------------------------------------------------------------------------------
2. Media Player stuck on loading screen when running an Android build with Media Player having settings:

- Video API: Exo Player
- Audio Output: Unity

Additional details:
Gives a _Error Unity java.lang.NegativeArraySizeException: -480000_ before running any Media Player Events.

------------------------------------------------------------------------------------------------------------------------------------

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.8f1
 - AVPro Video version: -v2.0beta5-Trial 
 - Device model: HUAWEI KII-L05 & Pixel 2(Emulator)

**To Reproduce**
1. Install AVPro v2.0beta5-Trial package in new Unity 2020.1.8f1 project
2. Project Settings:
              - remove Vulkan
              -Internet Access: required
              -Write Permission: External(SD card)
3. Open provided Demo_MediaPlayer scene and make sure Android video API is set to Exoplayer 
4. Build and run Demo_MediaPlayer scene with Exoplayer Audio Output set to System Direct or Unity

**Logs**
[Error when Exoplayer audio is set to System Direct.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5502424/Error.when.Exoplayer.audio.is.set.to.System.Direct.txt)
[Error when Exoplyer audio is set to Unity.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5502425/Error.when.Exoplyer.audio.is.set.to.Unity.txt)

**Comment by AndrewRH** [comment]
@shazamk thanks for your thorough report!

The second issue  (Unity audio) we know about and are working on a fix.
We will report back about the first issue soon.

Thanks,

**Comment by RenderHeadsSte** [comment]
Thanks for reporting these @shazamk.  Super helpful.

Issue (1) I think is outlined [here](https://github.com/MasayukiSuda/GPUVideo-android/issues/25). Specifically "it <grade> tries to optimize external dependencies as well and it strips default method implementations from exoplayer"

Issue (2) we have already committed a fix for.

We will implement the mused fix for (1) and hope you get time to test this in the next build.

**Comment by shazamk** [comment]
Thanks for the help! :)
