### ISSUE TITLE
Why not start every time you play a network video from 0 milliseconds

### ISSUE THREAD

**Issue by kuer131** [RenderHeads/UnityPlugin-AVProVideo#520]
Each time the video is played, the initial position is in the fifth frame,
For example, for a 25-frame video, the initial playback position is 160ms

**Your Setup (please complete the following information):**
 - Unity version: 2018.1
 - Operating system version: Windows 10
 - Device model: HTC VIVE PRO

**Comment by AndrewRH** [comment]
I think that it must be related to how the video is encoded.  Does that happen with our sample videos too?
If you remove the audio track from your video file does it still happen?

Thanks,
