### ISSUE TITLE
4k Streaming now doesn't render

### ISSUE THREAD

**Issue by FringeCase** [RenderHeads/UnityPlugin-AVProVideo#521]
Problem description:

Using Unity 2020.1.9f1 & 2019.3.0f6 Just upgraded to 1.11.7; when we pull our URL ( hosted via AWS Mediastore through AWS Cloudfront ) I can see that the inspector preview is getting the time and updating appropriately. However, nothing is getting rendered in either the inspector's preview or in the scene. I can pull my specific URL in VLC and it 
works, so I am wondering if something broke with the latest release for 4k H.265 streaming? 

Device (which devices are you having the issue with - model, OS version number):

Windows

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

1 video, 4k (3840x2160), H.265, 30FPS

System Information:

AVPro Video: plugin v1.11.7 scripts v1.11.7
Target Platform: Standalone
Unity: v2019.3.0f6 WindowsEditor
OS: Desktop - System Product Name (System manufacturer) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz - 8 threads - 32692KB
GPU: NVIDIA GeForce GTX 1070 - NVIDIA - Direct3D 11.0 [level 11.1] - 8088KB - 16384

**Comment by FringeCase** [comment]
As I continue to drill in some more, I feel like it's not even correctly pulling the stream at all. While the preview inspector _sometimes_ has the time being rendered, the actual video does not ( sorry if that was unclear earlier ). Logs say the system is opening the m3u8 URL however it spits out the following 

```
[AVProVideo] Using playback path: MF-MediaEngine-Hardware (0x0@0.00)
UnityEngine.Debug:Log(Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at Assets/AVProVideo/Scripts/Internal/Interfaces.cs:614)
RenderHeads.Media.AVProVideo.WindowsMediaPlayer:Update() (at Assets/AVProVideo/Scripts/Internal/WindowsMediaPlayer.cs:796)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1407)
```

I also tried using your demo scene `02_Demo_imGui` ( and the others ) and like some of the other streams you can test I am seeing the event say `Started` then `Stalled`

Is there something that needs to be set for the builds to pull the stream? If it is pulling the stream correctly, are there specific `gotcha's` that need to be implemented for 4k video files? 

I've also gone back and tried a different version ( 1.11.3 ) and noticed it is now not rendering there. Though the only bits that have changed would be the Unity version themselves. 

The video streams are generated with a pre-defined set of channel attributes ( HEVC 265, UHD 3840x2160 ), and have been previously working and they do work with other applications like VLC.

Any help would be much appreciated.

**Comment by AndrewRH** [comment]
@FringeCase  hmm that does sounds strange.. Any chance you could share a test stream that's having this issue?

**Comment by FringeCase** [comment]
Sure, as to not throw URLs here willy-nilly; can I send it directly to the unitysupport@renderheads.com ?

**Comment by FringeCase** [comment]
@AndrewRH I am sending an email with the URL to unitysupport@renderheads.com, it's an email titled "Issue with Rendering 4K m3u8 Livestream - Version 1.11.7" from myself and coworker Mark M. 

We'll keep the stream up for a while, note we've disabled audio temporarily so it's just the video.

Thank you!

**Comment by AndrewRH** [comment]
Thanks @FringeCase we'll take a look

**Comment by AndrewRH** [comment]
I've tested your stream and reproduced the issue.

The stream seems very strange.  I've never seen a stream with this behaviour before.  It doesn't seem to have any sort of duration specified and isn't detected as a live stream, and indeed the frames don't come through.  I suspect there is something incorrect with the stream.  It almost seems like that presentation timestamps (PTS) aren't quite right..

**Comment by FringeCase** [comment]
AWS also creates a m3u8 that's just cam_0.m3u8 on the same path (just chop
off the _11 from the previous link), not sure if that will be more helpful

**Comment by AndrewRH** [comment]
Thanks, same results though.  How exactly are the streams generated and encoded?
Could you try removing the audio from that stream entirely?

**Comment by FringeCase** [comment]
@AndrewRH 
I've attached ( omitted some sensitive items ) I apologize for the length of it, but it's definitely to give you insight. I did try removing the audio stream entirely and I still get not rendering; (using the same link you have)

```
 "encoderSettings": {
    "audioDescriptions": [
      {
        "audioSelectorName": "English-Audio",
        "audioTypeControl": "FOLLOW_INPUT",
        "languageCodeControl": "FOLLOW_INPUT",
        "name": "audio_11jx3"
      }
    ],
    "captionDescriptions": [],
    "outputGroups": [
      {
        "outputGroupSettings": {
          "hlsGroupSettings": {
            "adMarkers": [],
            "captionLanguageSetting": "OMIT",
            "captionLanguageMappings": [],
            "hlsCdnSettings": {
              "hlsBasicPutSettings": {
                "numRetries": 5,
                "connectionRetryInterval": 30,
                "restartDelay": 5,
                "filecacheDuration": 300
              }
            },
            "inputLossAction": "EMIT_OUTPUT",
            "manifestCompression": "NONE",
            "ivInManifest": "INCLUDE",
            "ivSource": "FOLLOWS_SEGMENT_NUMBER",
            "clientCache": "ENABLED",
            "tsFileMode": "SEGMENTED_FILES",
            "manifestDurationFormat": "FLOATING_POINT",
            "segmentationMode": "USE_SEGMENT_DURATION",
            "redundantManifest": "DISABLED",
            "outputSelection": "MANIFESTS_AND_SEGMENTS",
            "streamInfResolution": "INCLUDE",
            "iFrameOnlyPlaylists": "DISABLED",
            "indexNSegments": 10,
            "programDateTime": "INCLUDE",
            "programDateTimePeriod": 600,
            "keepSegments": 21,
            "segmentLength": 6,
            "timedMetadataId3Frame": "PRIV",
            "timedMetadataId3Period": 10,
            "codecSpecification": "RFC_4281",
            "directoryStructure": "SINGLE_DIRECTORY",
            "segmentsPerSubdirectory": 10000,
            "mode": "LIVE"
          }
        },
        "name": "TN2224",
        "outputs": [
          {
            "outputSettings": {
              "hlsOutputSettings": {
                "nameModifier": "_11",
                "hlsSettings": {
                  "standardHlsSettings": {
                    "m3u8Settings": {
                      "audioFramesPerPes": 4,
                      "audioPids": "492-498",
                      "pcrControl": "PCR_EVERY_PES_PACKET",
                      "pmtPid": "480",
                      "programNum": 1,
                      "scte35Pid": "500",
                      "scte35Behavior": "NO_PASSTHROUGH",
                      "timedMetadataPid": "502",
                      "timedMetadataBehavior": "NO_PASSTHROUGH",
                      "videoPid": "481"
                    },
                    "audioRenditionSets": "program_audio"
                  }
                }
              }
            },
            "outputName": "lvqr3b",
            "videoDescriptionName": "video_f1n9i",
            "audioDescriptionNames": [
              "audio_11jx3"
            ],
            "captionDescriptionNames": []
          }
        ]
      }
    ],
    "timecodeConfig": {
      "source": "SYSTEMCLOCK"
    },
    "videoDescriptions": [
      {
        "codecSettings": {
          "h265Settings": {
            "parNumerator": 1,
            "parDenominator": 1,
            "afdSignaling": "NONE",
            "rateControlMode": "CBR",
            "framerateNumerator": 60,
            "framerateDenominator": 1,
            "gopSize": 90,
            "gopSizeUnits": "FRAMES",
            "gopClosedCadence": 1,
            "sceneChangeDetect": "ENABLED",
            "profile": "MAIN",
            "tier": "MAIN",
            "scanType": "PROGRESSIVE",
            "level": "H265_LEVEL_AUTO",
            "adaptiveQuantization": "HIGH",
            "flickerAq": "ENABLED",
            "colorMetadata": "INSERT",
            "alternativeTransferFunction": "OMIT",
            "lookAheadRateControl": "HIGH",
            "timecodeInsertion": "DISABLED"
          }
        },
        "height": 2160,
        "name": "video_f1n9i",
        "respondToAfd": "NONE",
        "sharpness": 50,
        "scalingBehavior": "DEFAULT",
        "width": 3840
      }
    ]
  },
```

**Comment by FringeCase** [comment]
@AndrewRH looks like there were several issues that are `new` on the AWS side of the house. I needed to swap from a standard HLS type to `fmp4 hls` which is a new sub category in AWS from my perspective. I also needed to adjust a couple of other items. I now have rendering working. I am going to re-enable audio but I am sure that is going to work just fine now.

Thank you for taking a look into this with us, we here sincerely appreciate it

**Comment by FringeCase** [comment]
Just out of curiosity, if you know of some ways to make `Standard HLS` work with your system ( above configuration ) please let me know. I am still trying to figure out why FMP4 HLS from AWS does not provide audio ( video works just fine ), even if I try to output Audio only HLS stream to layer manually in Unity. Seems to be rather recent and I would love to continue using your product before I need to look at alternatives. 

-Anthony

**Comment by AndrewRH** [comment]
Glad to hear it's working now.
I'm not sure why you're not getting audio - not even in VLC?

Yes .fmp4 apparently has better support for HEVC.  i wonder if H.264 might work better with the default (.ts)

Also if you're going to use HEVC you should change the tag as AWS seems to be using a less supported tag of 'hevc' instead of 'hvc1'.  I believe you can change this in the JSON via H265PackagingType: HVC1, in HlsSettings.

Unfortunately I'm not familiar with the AWS encoding system...but HEVC live streaming should certainly work with our plugin.
For example Apple has some fMP4 sample streams here:

https://developer.apple.com/streaming/examples/
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/master.m3u8

Thanks,

**Comment by FringeCase** [comment]
Hey, @AndrewRH, I've been digging into this quite a bit more this past week, and I am still having absolutely no luck getting MediaStore *.m3u8's to render with AVPro Video. I've tried and tuned every single dial and knob I can think of that would cause such an issue. I still am running into problems where other APIs like NexPlayer or application (VLC) do not. Is there any way we could set up a time and talk over a Google Meet or something? I can walk through the settings and items I see both in your 1.11.7 and 2.0* beta releases? I can show you what I've had previously and the changes made to accommodate. We really want to use this product, but somehow from when we got things working a few months ago to now, we have nothing and coming up with our own deadlines. I also would love to see that you guys can say you work with AWS MediaStore setups too! 

Thanks, 
   -Anthony

**Comment by AndrewRH** [comment]
@FringeCase  sounds good - could you email unitysupport@renderheads.com and we can set up a meet.

**Comment by AndrewRH** [comment]
It seems the fix currently is to switch the codec to H.264

We will investigate why it doesn't play using H.265 (HEVC) codec.  The hunch currently is that it's using something that is incompatible with the Microsoft decoder.  For reference Microsoft supports different HLS tags depending on the version of Windows:
https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/hls-tag-support

AWS also has a list of HLS features that require more advanced HLS players which should be kept in mind:
https://docs.aws.amazon.com/mediaconvert/latest/ug/hls-player-version-support.html

We will update once we have replicated the issue, but any other details about your AWS setup would be welcomed.

Thanks,
