### ISSUE TITLE
Chroma Key ability for videos played as an m3u8 stream

### ISSUE THREAD

**Issue by JimDeBarker** [RenderHeads/UnityPlugin-AVProVideo#522]
Are there any plans to include a simple chroma keyer into the player or integrate Chroma Key Kit compatibility to the media player as you have done for the live video camera asset. It would be a really helpful feature to be able to key an incoming live stream for display in a virtual venue. Many thanks.

**Comment by Twyker** [comment]
+1 I would also really need this.

How would you go about solving this currently otherwise?
