### ISSUE TITLE
Set custom http headers for Exoplayer

### ISSUE THREAD

**Issue by kenneth-ox** [RenderHeads/UnityPlugin-AVProVideo#523]
**Describe the bug**
We are trying to use pre-signed cookies for AWS CloudFront. We have to set custom headers to AVPro exoplayer through
PlatformOptionsAndroid.httpHeaders.Add(new MediaPlayer.PlatformOptions.HTTPHeader("Cookie", "CloudFront-Policy=XX;CloudFront-Key-Pair-Id="XXX";CloudFront-Signature="YYYY"))
But it did not work and failed to load the HLS playlist.
The logs showed something like
"failed to load asset"
"[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources."
From this thread, https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/210, 1.10.2 seems to work.
Is there a way that we can get this package?

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.0f6
 - AVPro Video version: 1.11.7
 - Operating system version: OSX 10.15.5
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
I am sure we could sort you out with an older package, but I would much rather investigate why you are seeing this issue and fix it.  Would it be possible to send over an example URL/header so we can reproduce it here?  If you would rather not make this public then you can email it over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by kenneth-ox** [comment]
Hi Ste Butcher,

I am sorry we cannot give out the actual urls we use for development. But
we can give out the sample hls asset folder.
https://drive.google.com/file/d/1mpGntPSQUFhBrVeAKTs0YJ8hORzOQ6ZQ/view?usp=sharing
In order to exactly reproduce the problem, you need access to AWS and put
the hls folder on an S3 bucket, generate cloudfront pre-signed cookies to
secure them following the tutorial below.
https://www.youtube.com/watch?v=iw-OtY5_A0w
May I also ask about the issue of HLS being played only at the lowest
resolution for unity exoplayer? The ticket below said it will be fixed in
2.0. May I ask when it will be released on Unity?
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/35

Thanks,
Kenneth

**Comment by kenneth-ox** [comment]
Hello,Thank you for your enquiry regarding our Unity products.  Our product team will reply shortly.In the meantime you may also find the answer to your question at one of these resources:
AVPro VideoDownloadUser ManualIssue Tracker

AVPro Live CameraDownloadUser ManualIssue Tracker

AVPro Movie CaptureDownloadUser ManualIssue Tracker

AVPro DeckLinkDownloadUser ManualIssue Tracker Thank you! The RenderHeads Team

**Comment by kenneth-ox** [comment]
Hi Kenneth,
We are aiming to release version 2 to the Unity store before Christmas.
In version 2 we have added an option to hint to the player to start at the highest bitrate for streams.
Best,Ste
On Wed, 25 Nov 2020 at 10:21, <unitysupport@renderheads.com> wrote:
Hello,Thank you for your enquiry regarding our Unity products.  Our product team will reply shortly.In the meantime you may also find the answer to your question at one of these resources:
AVPro VideoDownloadUser ManualIssue Tracker

AVPro Live CameraDownloadUser ManualIssue Tracker

AVPro Movie CaptureDownloadUser ManualIssue Tracker

AVPro DeckLinkDownloadUser ManualIssue Tracker Thank you! The RenderHeads Team

**Comment by RenderHeadsSte** [comment]
It appears something changed in AWS that has caused this to stop working in v1 of AVPro Video.  This has been fixed for v2 due to changes to the core of ExoPlayer.  Unfortunately we will not be offering a fix for v1.
