### ISSUE TITLE
FMOD support

### ISSUE THREAD

**Issue by joonjoonjoon** [RenderHeads/UnityPlugin-AVProVideo#526]
Would be awesome if there's a way to get support for FMOD for Unity.

**Comment by kypopete** [comment]
+1

**Comment by AndrewRH** [comment]
Could you go into more detail about this feature request? :-)

**Comment by joonjoonjoon** [comment]
Fmod is a popular and high-end audio engine plugin for Unity.
It entirely replaces Unity's audio system and is incompatible with it.

At the time of writing I thought that your plugin was able to capture Unity Audio (in offline render mode), but I had misunderstood.
There is a way to record video + audio offline detailed here: https://twitter.com/SFBTom/status/1187697799699275777
This method is incompatible with FMOD, meaning we can't use it.

I think I understand now that this should be a feature request for Unity rather than Renderheads, but if there's anything that can be done it would of course be a great solution for capturing 60fps 4K footage which some store fronts are starting to request :)

https://twitter.com/SFBTom/status/1187697799699275777
https://qa.fmod.com/t/recording-audio-with-unity-recorder/15173
https://www.fmod.com/unity

**Comment by AndrewRH** [comment]
Hmm, I thought that Unity uses FMOD internally.

Yes the latest version of AVPro Movie Capture does have support for capturing Unity audio in offline mode (via the new CaptureAudioFromAudoRenderer component) - give it a try and let us know how it works for you.

Lastly this github is actually for the AVPro Video plugin, you can find the AVPro Movie Capture github here:
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture/issues

Thanks,

**Comment by joonjoonjoon** [comment]
I posted it there too, sorry for the mix up.
Fwiw Unity's under the hood audio uses FMOD but it is branched off and not compatible with modern day FMOD Studio which sound designers like to use :)
