### ISSUE TITLE
Just bought full version, but Unity still says "Trial version"

### ISSUE THREAD

**Issue by joonjoonjoon** [RenderHeads/UnityPlugin-AVProVideo#527]
I just deleted the trial version files, grabbed the last version from the asset store, and put it in my project but the purple header still appears.

Unity 2019.4.9f1
AVPro 4.4.5
Installed directly from the embedded asset store in Unity, and I am logged in to both Unity Hub and Unity itself.

**Comment by AndrewRH** [comment]
Hi,

I think perhaps the plugin files were locked and so they weren't updated.  Try closing Unity completely, then open it, then immediately install the asset store version.

Hope that works.  Otherwise please let us know your platform.

Thanks,

**Comment by RenderHeadsSte** [comment]
Do you have an update on this issue @joonjoonjoon ?

**Comment by joonjoonjoon** [comment]
I ended up not being able to use the plugin (due to the missing fmod feature) - and also had some issues with my account that could've caused this. I'll close the issue and re-open or rreport if it occurs again. Thanks
