### ISSUE TITLE
Incorrect video color

### ISSUE THREAD

**Issue by Barbelot** [RenderHeads/UnityPlugin-AVProVideo#528]
Hello,
I am using AVPro to play an mp4 (H264) video file but I get washed out colors in Unity.
In the screenshot below you can see the difference between the video texture in Unity and the video read in vlc which has the correct colors.
 
![image](https://user-images.githubusercontent.com/2972871/99792494-77e2c000-2b27-11eb-9389-3d63e4c83d40.png)

Any idea what could be causing this color issue ?

**Comment by AndrewRH** [comment]
How are you displaying the video in Unity?  Are you using one of our display components - eg ApplyToMesh / ApplyToMaterial / DisplayUGUI etc?

If you're running Unity in Linear colorspace mode (probably are) then our textures sometimes (depending on the platform) need to have gamma adjusted.  Our display components and shaders should take care of this, but if you are just using the texture directly, or using your own shader then the gamma adjustment wont' be applied.

Does that help?

Thanks,

**Comment by Barbelot** [comment]
Hi, thanks for the quick answer, that was the exact problem !

I had a custom ApplyToRawImage to apply the texture to a UI image but as you said the gamma was not accounted for. Using your displayUGUI component instead works perfectly.

Thanks again for the help.
