### ISSUE TITLE
On Android video is restarted when calling Rewind() after video finished playing

### ISSUE THREAD

**Issue by azixMcAze** [RenderHeads/UnityPlugin-AVProVideo#529]
**Describe the bug**
Hi, I am playing a local video on android. When the video is finished (`FinishedPlaying` is received), stop the video and I rewind it so that my seek bar is reset and the next time I play the video, it plays from the start :

```csharp
    void OnVideoEvent(MediaPlayer mp, MediaPlayerEvent.EventType et, ErrorCode errorCode)
    {
        if(et == MediaPlayerEvent.EventType.FinishedPlaying)
        {
            m_mediaPlayer.Stop();
            m_mediaPlayer.Rewind(true);
        }
    }
```

When Rewind is called on android after the video has finished, the video rewinds and plays again instead of staying stopped.
This behaviour does not exists in the editor where the video rewinds and stays stopped

If I call `Stop()` when the video is playing and then `Rewind()`, the video stays stopped. One difference is that `IsFinished()` is `false` ins this case instead of `true`.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.15
 - AVPro Video version: 1.11.7
 - Operating system version: Android 9 & Android 10
 - Device model: Samsung A50 & Nokia 6.1
 - Video specs (resolution, frame-rate, codec, file size): mp4 h264 1920x1080

**Comment by RenderHeadsSte** [comment]
We have put a fix in for this issue into v2 of AVPro Video.  Unfortunately this fix is not back-portable to v1.  Is it not viable for you to call Stop before the Rewind to achieve the desired result?

**Comment by azixMcAze** [comment]
Hi, thanks for the answer!

I used another workaround, that is rewinding the video before starting playback. At the moment this bug id not blocking me.
