### ISSUE TITLE
Beta watermark - paid customer

### ISSUE THREAD

**Issue by RaximusMaximus** [RenderHeads/UnityPlugin-AVProVideo#531]
We a paid copy of AVpro for windows. I have tested the beta version and have found the WinRT API works much better at streaming our media.

The problem is the beta version displays the watermark, as we have paid for a license is their a way to use the beta with our valid license?

**Comment by RenderHeadsSte** [comment]
The beta versions being released are of AVPro Video version 2.  Version 1 and version 2 of AVPro Video will be separate assets.  The license for version 1 will not be transferable to version 2.  That said, we will be offering upgrade options for current version 1 license holders to purchase version 2.
