### ISSUE TITLE
Unity webserver on macOS unable to play videos on local WebGL builds in Safari

### ISSUE THREAD

**Issue by jensteinkamp** [RenderHeads/UnityPlugin-AVProVideo#532]
AVPro Mac does not local publish with video, it does local publish on PC. 

This could be related to permissions being changed on the video files. Unity 2020 with AVpro is sketchy.

Please see this site for my research notes:
http://users.design.ucla.edu/~cariesta/MayaCourseNotes/html/unity_video_texture_maps.html

h.264 mp4 320x240 8480kbps with audio48000 stereo

MacPro7,1 Catalina, updated browsers

AVPro 1.11.6 1.11.7

**Comment by AndrewRH** [comment]
Interesting - thanks for your extensive notes!

Perhaps you could help us out and see what the error message is in the Mac browsers (enter development mode to see the console) when it failed to load the video?

I found some similar issues mentioned here which could be related:
https://stackoverflow.com/questions/32996396/safari-9-0-can-not-play-mp4-video-on-the-storage-server

Thanks,

**Comment by jensteinkamp** [comment]
Hi Andrew
There were no error messages with Full Log selected, there was this message:
Build completed with a result of 'Succeeded' in 169 seconds (169286 ms)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun() (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:136)

Here is an image of how the permissions changed after publish


Thanks
Jennifer

**Comment by AndrewRH** [comment]
Hi,
I'm afraid no image came though - I think if you reply via email then attachments are lost - you have to attach via Github.

I was looking for the web browsers logs.  If you press F12 in the browser, or use the options menu you can open the developer Console window.  This will show any error messages during the loading of the Unity player.

Thanks,

**Comment by jensteinkamp** [comment]
Here is the image
![compare](https://user-images.githubusercontent.com/34894047/100792705-e64d3b00-33cf-11eb-818a-e39dfa0fa1ca.png)

**Comment by jensteinkamp** [comment]
Here is a screen grab of the error
![Uploading error.png…]()

**Comment by jensteinkamp** [comment]
Here is the error
![error](https://user-images.githubusercontent.com/34894047/100794240-1f86aa80-33d2-11eb-9aff-fa34c9d360fe.png)

**Comment by jensteinkamp** [comment]
Here is the set publish
http://classes.dma.ucla.edu/Fall20/156-1/projects/temp/video_tests/mac/avpro_2019_no_steam_mac_player/

**Comment by AndrewRH** [comment]
At first I thought the reason for the failure was because your localhost is using HTTP instead of HTTPS...But then the URL you posted is using HTTP so it can't be that...
@MorrisRH  any idea why it won't play using localhost but is find once put on a remote web server?

**Comment by jensteinkamp** [comment]
Could it be permissions? I had a lot of trouble because of permissions, it took me quite a while to figure that out. It is only a Mac issue.

**Comment by MorrisRH** [comment]
Just tried a WebGL export to my local http server and found no issues. The scene played back correctly in Firefox.
Does sound like something is awry with your local server setup.

**Comment by jensteinkamp** [comment]
HI I am on a Mac, my Mac defaults to playing back the local publish in Safari. I imagine this is a default situation for many Mac users. My PC works perfectly. The problem is the initial local playback when you select Build and Run. Publishing to a server works great for Mac and PC, much better than the Unity videoPlayer. I know my students become very confused when they don't see video playing back with the local publish.
Here is an image of my research results.
![WebGL_video_compare](https://user-images.githubusercontent.com/34894047/100895545-8a87be00-3472-11eb-8569-04645fe20122.png)

**Comment by MorrisRH** [comment]
Ahhhh, I see. Sorry, hadn't realised you were using "Build And Run".

Unfortunately Unity's internal http server isn't handling byte-range requests correctly so Safari refuses to play the content. This is an issue with Unity and as such there is nothing we can do about.

**Comment by jensteinkamp** [comment]
Are you sure it is not a permission issue? The permissions do get changed when the publish content is generated.

If permissions is not the issue, is there a clear description of the problem so I can let Unity know this is a factor? I may need to wait for them to fix their VideoPlayer on the Mac.

**Comment by MorrisRH** [comment]
Yes, as Firefox is able to work. I also checked the http headers and responses via the developer console which confirmed it.

The Apple documentation about it is [here](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6). Whilst it specifically mentions iOS it applies to Safari in general.

**Comment by jensteinkamp** [comment]
Thanks, I will attempt to pass this along to Unity even though they have not fixed their own VideoPlayer working with Mac. 
Can you tell me how to make the Build and Run default to Firefox or Chrome?

**Comment by MorrisRH** [comment]
Unity just opens the default browser so you would need to change it in the Settings app's General pane.

**Comment by jensteinkamp** [comment]
Hi Both Firefox and Chrome do not preview the audio FYI. (I can play the same work in those browsers that was published on a remote server.) 
I believe it is best not to change the settings in Firefox and Chrome to accept the audio, it makes more sense to keep it default for debugging.
