### ISSUE TITLE
setButtonEnabled

### ISSUE THREAD

**Issue by nicolaeciobota** [RenderHeads/UnityPlugin-AVProVideo#533]
Hi

I just purchased the plug in and it works great. I was trying to make a player controller but when attempting to do a Play/Pause swap I got an error saying feature not implemented? Is the setButtonEnabled. I set all game object correctly but it rejects the VCR scrip after adding the game objects and uncomenting the setButonenabled...
Is there a work around? Is not very user friendly to have two separate buttons for Play and Pause.

Many thansk
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RenderHeadsSte** [comment]
The VCR script has only been provided as a guide how to implement a set of features.  I would urge you to implement your own script that fits your use-case better.

If you can be more specific with your what you are trying to achieve then I hope we can provide a fuller answer.

**Comment by RenderHeadsSte** [comment]
Closing bug sue to inactivity
