### ISSUE TITLE
No sound with AudioOutput Component through Unity AudioSource with "Spatialize" enabled.

### ISSUE THREAD

**Issue by takayoshishimizu** [RenderHeads/UnityPlugin-AVProVideo#535]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version:  Unity2019.4.13LTS
 - AVPro Video version: 1.11.4.
 - Operating system version:  Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Always occured while AVProVideo Playing
2. 
3. 

**Screenshots**
![AudioOutput](https://user-images.githubusercontent.com/63390082/101231784-d9db2200-36f0-11eb-9876-f0692657bdd5.png)

**Comment by AndrewRH** [comment]
Hi,

First I would recommend upgrading to the latest version of AVPro Video.

Next, do you mean the Unity spatializer?

Lastly, in your platform (Android/Window) do you have the Audio Output mode set to "Unity"?  (in the MediaPlayer > Platform Specific > Windows menu)

Thanks,
