### ISSUE TITLE
In iOS, Audio plays again after the media player has been closed

### ISSUE THREAD

**Issue by sanathkukkillaya** [RenderHeads/UnityPlugin-AVProVideo#537]
**Describe the bug**
There is one issue in iOS, where in my game I call mediaplayer.CloseVideo() and go to the next stage, and the audio starts playing again.(it is just a panel hiding and enabling another panel). This issue occurs only on the iOS build and not on the android or editor. Since this is occurring only on iOS, we believe we are missing some setting for iOS. If you are aware of any setting that I must be missing, do let me know. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.5f1 LTS
 - AVPro Video version: 1.11.7
 - Operating system version: iOS (found the issue in both iOS 12 and 14. Didn't test in other versions)
 - Device model: iPhone 6 Plus, iPhone X
 - Video specs (resolution, frame-rate, codec, file size): .m3u8 files streamed from the server

**To Reproduce**
1. We have a scene where we call the AVPro media player through the Display GUI component. Once the FinishedPlaying event is called, we call the mediaplayer.CloseVideo() event and hide the video player panel and open another panel which shows a static quiz based on the video.
2. In iOS, when this happens, the audio starts playing again from the beginning but the video cannot be seen. 
3. This issue occurs only in iOS. In Android and in the Windows editor, we are not facing this issue.

**Logs**
From the logs, I can see that the Event: MetaDataReady and Event: FirstFrameReady is being called again. This makes me think the entire video is being played again somehow.

**Videos**
I have shared an attached video to unitysupport@renderheads.com.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi thanks for reporting this.  To make sure it isn't something in your application causing this - are you able to reproduce it using our sample scenes?

**Comment by sanathkukkillaya** [comment]
Hi, We tried with the sample scenes, but could't replicate it correctly. 
I was going through the forums and the issues, and I saw this note for v2.0.0 beta4: Fixed bug where audio sent to Unity AudioSource could get stuck and repeat if plugin stopped sending audio data due to stalling. 
Could this anyway be similar to my issue? I am using System Direct mode, though. Should I try with Unity AudioSource mode?

**Comment by AndrewRH** [comment]
Good work checking the release notes :) But no I think that was a completely unrelated issue.

Could you try calling CloseVideo() from Update() instead of from within the event callback?  There's a chance that it's related to this.

Thanks,

**Comment by sanathkukkillaya** [comment]
Hi, I tried multiple things like calling CloseVideo() from Update() and then even tried setting the audio mode to Unity, but these didn't work. As a workaround, what did work was setting a flag for videoPlayed on FinishedPlaying event and then calling Mediaplayer.Control.Mute(true) when videoPlayed== true inside Update() method.

I feel this is a hacky way to achieve this. While it does work, and serves my purpose for now, I would appreciate it if we could find a better solution to this.

In terms of testing, I did attach logs inside the FInishedPlaying callback method, and it was called correctly. So my mediaplayer.CloseVideo() was also called correctly once when the video ended. Ironically, now when I checked thoroughly with color code logs, I found that no new event was also called (So I was wrong in my initial report that FirstFrameReady was being called again). Yet inspite of all this, the audio still played again in the iOS app. I wasn't sure where to place the logs to see where the audio was coming from.

**Comment by MorrisRH** [comment]
Are you calling MediaPlayer.Control.Rewind or one of the Seek methods at any point when handling the FinishedPlaying event?

**Comment by sanathkukkillaya** [comment]
No, I am not.

This is my close video method which I was previously calling on
FinishedPlaying

  public void CloseVideoPlayer()
{
Debug.Log($"<color=yellow>Close video player</color>");
_VideoSeekSlider.value = 0;
// _BufferedSliderRect.anchorMin = Vector2.zero;
// _BufferedSliderRect.anchorMax = new Vector2(0, 1);
_ErrorText.text = string.Empty;
_MediaPlayer.CloseVideo();
_MediaPlayer.gameObject.SetActive(false);
//Screen.sleepTimeout = SleepTimeout.SystemSetting;
isVideoClosed = true;
Debug.Log($"<color=yellow>Close video player complete</color>");
}

Now I keep the bool values and call it via the update method, where I also
manually mute the audio.
This is my update code snippet

   if (isVideoPlayed && !isVideoClosed)
{
Debug.Log($"<color=yellow>Closing video player from update</color>");
CloseVideoPlayer();
_MediaPlayer.Control.MuteAudio(true);
Debug.Log($"<color=yellow>Muted audio after closing</color>");
}

if(isVideoPlayed && !isAudioMuted)
            {
_MediaPlayer.Control.MuteAudio(true);
isAudioMuted = true;
Debug.Log($"<color=yellow>Muted audio</color>");
}

**Comment by MorrisRH** [comment]
Looking at your code, I think a seek may be being called indirectly by the reset of the slider. As a test could you remove the line:
```_VideoSeekSlider.value = 0;```

Because seeking is an asynchronous operation, my hunch is that it's keeping the underlying video playback alive event though you closed it. If removing the line works, could you then try resetting the slider after you've closed the video?
