### ISSUE TITLE
Control.IsPlaying() is reporting incorrectly, iOS

### ISSUE THREAD

**Issue by LukasRoper** [RenderHeads/UnityPlugin-AVProVideo#538]
**Describe the bug**
It seems when using a Stream, the Control.IsPlaying() value reports a false value when the stream quality changes. I can tell as I check whether to set the play/pause icon graphic to a play sprite or pause sprite and essentially the play icon will show whilst the video/stream is already playing. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.5
 - AVPro Video version: 1.11.7
 - Operating system version: iOS
 - Device model: IPhone X
 - Video specs (resolution, frame-rate, codec, file size): Stream (m3u8). 4K but with a low/medium/high transcodes.

**To Reproduce**
1.  Use a stream.
2.  Wait for a stream change (not completely sure if it is the stream change specifically but I notice the error report at pretty consistent times which suggests it's swapping at around about this point).
3. Check Control.IsPlaying()

**Videos**
Can record if needed but using materials that shouldn't be shared publicly.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
So are you saying that IsPlaying() == false for only a 1 frame when the resolution switches while streaming an HLS stream?  Or that after a stream resolution change IsPlaying() continually returns false?

And is it the case that the playback is in fact continuing even though IsPlaying() is returning false?

Also - are you able to reproduce this issue in any of our sample scenes?

Thanks,

**Comment by MorrisRH** [comment]
Sounds like the player has become stalled for a very brief moment. We're looking into changing the behaviour slightly so that IsPlaying isn't cleared when a stall occurs. For now I suggest you check that Info.IsPlayerStalled() isn't set when toggling your icon graphics.

**Comment by LukasRoper** [comment]
@AndrewRH the former so isPlaying is consistently false there after even though the stream has resumed (and hasn't actually stalled at all).

I can try with a sample but I haven't noticed this behaviour with predownloaded content. If I use my code with a downloaded video, it's fine.

Thanks,

**Comment by colinmacleod** [comment]
@MorrisRH We have this issue too - only appears sometimes. The video is playing but IsPlaying() is returning false

**Comment by LukasRoper** [comment]
Hi,

I wanted to report this is now actually becoming a more annoying problem as you actually can't technically pause the video using mediaPlayer.Pause() without commenting out the IsPlaying check there. Just a word of warning to anyone else running into this.
