### ISSUE TITLE
Only One Eye Rendering on Hololens 2

### ISSUE THREAD

**Issue by utzy** [RenderHeads/UnityPlugin-AVProVideo#539]
**Describe the bug**
When using AVPro to show videos on the Hololens 2, only the left eye is rendering the video. The right eye stays black.
Used to work on HL1.

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.12f1
 - AVPro Video version: 1.11.7
 - Operating system version: Windows 1909
 - Device model: Hololens 2
 - Video specs (resolution, frame-rate, codec, file size): MPEG4 Video (H264) 854x480 25fps 713kbps [V: Alias Data Handler [eng] (h264 main L3.1, yuv420p, 854x480, 713 kb/s)]

**To Reproduce**
1. Setup MRTK in UnityScene
2. Add AVPro
3. Add MediaPlayer with AutoOpen/AutoPlay
4. Add Quad with ApplyToMesh and AVProUnlitOpaqueShader.
5. Build for Hololens 2 UWP D3D Project. Use Master Config when building in Visual Studio.

**Comment by AndrewRH** [comment]
Hi,

I suspect your video may contain stereo metadata.  Unfortunately our plugin has an issue on Windows platforms using Media Foundation where videos with stereo metadata only decode one eye.  This doesn't happen on other platforms.  The solution right now is to remove (or not embed in the first place) the stereo metadata from the video file.

If your video doesn't contain the stereo metadata then something is probably not set up correctly.  Make sure you have the UpdateStereoMaterial comonent in your scene and set up, and that you have set the stereo packing format on the MediaPlayer component.

We have the upcoming AVPro Video 2.0 which thankfully has solved this issue.

Does this help?

**Comment by utzy** [comment]
Hi, thanks for the quick reply :)
Maybe I should explain what we are trying to do.
We do not want to play stereoscopic video.

We simply want to play a video as part of the AR world. Basically like you have a TV floating in front of you, when you wear the Hololens.

This is where the bug shows up and you can only see the TV in one eye.
I was thinking this might be an issue due to stereo instancing on the shader or sth, but could not find an appropriate option.
Do you still think this is an error in our setup?

**Comment by AndrewRH** [comment]
Hmm, and if you change the stereo instancing mode - does that help?
If the whole TV mesh isn't appearing then it doesn't sound related to AVPro Video...

**Comment by utzy** [comment]
btw, we were not able to fix this bug.
Instead we used the following workaround:

Use a Canvas and an AVPro Display_uGUI component with Default UI Material, instead of a Mesh and an ApplyToMesh component with Unlit Material.
