### ISSUE TITLE
Mute video audio when Unity "Mute Audio" is active

### ISSUE THREAD

**Issue by RemyRM** [RenderHeads/UnityPlugin-AVProVideo#54]
**Is your feature request related to a problem? Please describe.**
When playing in the editor the video's audio will play, even though "Mute Audio" is enabled in Unity game view. To actually mute the audio now you have to either turn down the volume on the media player, or mute Unity from Windows,. 

**Describe the solution you'd like**
Avpro mutes with the rest of Unity when "Mute Audio" is enabled.

**Describe alternatives you've considered**
As described above it can be fixed by either setting the audio volume on the component to zero, meaning i'd have to remember to set it back whenever I build, or mute it from windows. however muting from Windows needs to be done after every startup

**Additional context**
I'm not really sure wether this is by design, oversight, not possible perhaps or a bug. So for now i'll keep it as a feature request. It can be observed in any of the demo scenes.

**Comment by AndrewRH** [comment]
Thanks for the suggestion, we're looking into adding support for this.

**Comment by AndrewRH** [comment]
Closing this as it has been implemented in the upcoming (today hopefully) version 1.10.2
