### ISSUE TITLE
Can't play HEVC video Loading from buffer 

### ISSUE THREAD

**Issue by sam8890** [RenderHeads/UnityPlugin-AVProVideo#540]
**Describe the bug**
Can't play HEVC(h265) video By LoadFromBuffer.cs

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.15
 - AVPro Video version: [AVProVideo] Initialising AVPro Video (script v1.11.0 plugin v1.11.0) on NVIDIA GeForce GTX 1060 3GB/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor Windows 10  (10.0.0) 64bit
 - Operating system version: Win10 20H2
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

General
Unique ID                   : 117126908064385321744327094718674198655 (0x581DD26B8AE4685059188ED4A4BB607F)
Complete name               : F:\视频和图片\视频\jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
Format                      : Matroska
Format version              : Version 4
File size                   : 1.40 GiB
Duration                    : 30 s 97 ms
Overall bit rate            : 400 Mb/s
Writing application         : Lavf56.3.100
Writing library             : Lavf56.3.100

Video
ID                          : 1
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main 10@L6.1@High
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 30 s 97 ms
Bit rate                    : 392 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 29.970 (29970/1000) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 1.577
Stream size                 : 1.37 GiB (98%)
Title                       : hevc@GPAC0.5.2-DEV-rev565-g71748d7-ab-suite
Writing library             : x265 1.8+190-75d1c62d8f0c:[Windows][MSVC 1700][64 bit] 10bit
Encoding settings           : wpp / ctu=64 / min-cu-size=8 / max-tu-size=32 / tu-intra-depth=1 / tu-inter-depth=1 / me=1 / subme=2 / merange=57 / no-rect / no-amp / max-merge=2 / temporal-mvp / no-early-skip / rdpenalty=0 / no-tskip / no-tskip-fast / strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / no-fast-intra / open-gop / no-temporal-layers / interlace=0 / keyint=250 / min-keyint=25 / scenecut=40 / rc-lookahead=20 / lookahead-slices=8 / bframes=4 / bframe-bias=0 / b-adapt=2 / ref=3 / limit-refs=3 / no-limit-modes / weightp / no-weightb / aq-mode=1 / qg-size=32 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=3 / psy-rd=0.30 / rdoq-level=0 / psy-rdoq=0.00 / signhide / deblock / sao / no-sao-non-deblock / b-pyramid / cutree / no-intra-refresh / rc=2 / pass / bitrate=414000 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ipratio=1.40 / pbratio=1.30
Default                     : Yes
Forced                      : No
Encoded date                : UTC 2016-02-05 16:11:30

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.
[AVProVideo] Initialising AVPro Video (script v1.11.0 plugin v1.11.0) on NVIDIA GeForce GTX 1060 3GB/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor Windows 10  (10.0.0) 64bit
[AVProVideo] Opening buffer of length 1504953150
[AVProVideo] Using playback path: DirectShow (3840x2160@29.97)
**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
https://jell.yfish.us/media/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by sam8890** [comment]
I have tried multiple h265 videos, some have sound but no picture, some can’t be played, stop at the end

**Comment by AndrewRH** [comment]
Thanks for reporting the issue - we will investigate.
Are you using a 3rd party decoder such as LAV Filters?
Does the file play if you just play it directly using the MediaPlayer component (both with DirectShow and Media Foundation API)?

**Comment by sam8890** [comment]
yes，i using LAV Filters
can play if i just play it directly using the MediaPlayer component (both with DirectShow and Media Foundation API)
