### ISSUE TITLE
AVPro Video 2.0 Launch and 1.x Retirement

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#542]
Hi All,

**AVPro Video 1.x will be retired soon!**

It's been almost 5 years since we initially launched AVPro Video 1.0 and now with the upcoming release of the new version 2.0 it's time to retire it. We will still keep the old version around for a bit longer and of course we'll still be supporting existing customers, but we can't continue supporting the old product forever.

**AVPro Video 2.0 has been released!**

We've very excited about the release of the new version, which we've been working hard on for more than a year.  It's been completely modernised and has so many new features and improvements .  The new version 2.0 is currently on the Asset Store and is be available now.

AVPro Video trial version can be downloaded here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases

We've also replaced the old PDF documentation with a [new web portal](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html) which will has allowed us to massively improve the documentation.

There are discounted upgrade paths for users of the old AVPro Video 1.x product, see here:
https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#owners-of-avpro-video-1x

If you do spot any issues in the new version please report them to us.  If you have any questions or feedback do let us know.

Thanks,

**Comment by fingerx** [comment]
@AndrewRH How much does it cost to upgrade from 1.x to 2.x? Thank you

**Comment by AndrewRH** [comment]
> @AndrewRH How much does it cost to upgrade from 1.x to 2.x? Thank you

All the prices and upgrade discounts are listed here:
https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#owners-of-avpro-video-1x

Thanks,

**Comment by umresh** [comment]
Does AVPro 2.x supports vp9 webm videos?

**Comment by AndrewRH** [comment]
> Does AVPro 2.x supports vp9 webm videos?

Yes on some platforms.  You can see the list of supported media here:
https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html

WebM and VP9 are supported on Android and Windows 10 (1607 and above).

Thanks,

**Comment by Atsutoshi** [comment]
AVPro Video 1.11.7 throws the following error.

[AVProVideo] Not supported on this platform WindowsEditor To Be Filled By O.E.M. (To Be Filled By O.E.M.) AMD Ryzen 9 3950X 16-Core Processor  Windows 10  (10.0.19042) 64bit.  Using null media player!

Is it supported in 2.0?

**Comment by AndrewRH** [comment]
> AVPro Video 1.11.7 throws the following error.
> 
> [AVProVideo] Not supported on this platform WindowsEditor To Be Filled By O.E.M. (To Be Filled By O.E.M.) AMD Ryzen 9 3950X 16-Core Processor Windows 10 (10.0.19042) 64bit. Using null media player!
> 
> Is it supported in 2.0?

Hi, I have made an issue for this so we can discuss off this thread:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/690

Thanks,

**Comment by AndrewRH** [comment]
Closing this announcement as AVPro Video 2.x has been out for almost a year now
