### ISSUE TITLE
Unexpected Crunch texture format Exception - Android iL2CPP Build

### ISSUE THREAD

**Issue by thesanketkale** [RenderHeads/UnityPlugin-AVProVideo#543]
**Describe the bug**
I am seeing an 'Unexpected Crunch texture format' exception in the Unity console every time I build an Android app with the AVPro video player from Unity 2020.1.8.

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.8f1, Graphics API: OpenGLES3, Color space: Linear
 - AVPro Video version: 1.11.7
 - Operating system version: Windows 10
 - Device model: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz   3.20 GHz
 - Video specs (resolution, frame-rate, codec, file size): Full HD - 1920 x 1080, 15 MB

**To Reproduce**
1. Import AVPro 1.11.7 to Unity project with Graphics API: OpenGLES3, Color space: Linear
2. Set Build Target to Android
3. Build (or Build and Run)

**Logs**
Editor Logs after build:
Launched and connected shader compiler UnityShaderCompiler.exe after 0.07 seconds
Compiled shader 'Standard' in 25.28s
    gles3 (total internal programs: 2262, unique: 1004)
Compressed shader 'Standard' on gles3 from 9.11MB to 0.38MB
Compiled shader 'AVProVideo/UI/Stereo' in 2.28s
    gles3 (total internal programs: 432, unique: 144)
Compiled shader 'AVProVideo/Lit/Diffuse (texture+color+fog+stereo support)' in 9.11s
    gles3 (total internal programs: 3840, unique: 1088)
Compressed shader 'AVProVideo/Lit/Diffuse (texture+color+fog+stereo support)' on gles3 from 4.46MB to 0.07MB
Compiled shader 'AVProVideo/VR/InsideSphere Unlit (stereo+fog)' in 1.68s
    gles3 (total internal programs: 2304, unique: 768)
Compressed shader 'AVProVideo/VR/InsideSphere Unlit (stereo+fog)' on gles3 from 1.91MB to 0.04MB
Compiled shader 'AVProVideo/Skybox/3x2 Cube' in 2.78s
    gles3 (total internal programs: 3456, unique: 672)
Compressed shader 'AVProVideo/Skybox/3x2 Cube' on gles3 from 2.36MB to 0.03MB
Compiled shader 'AVProVideo/VR/InsideSphere Unlit Transparent(stereo+color+fog+alpha)' in 1.96s
    gles3 (total internal programs: 2304, unique: 768)
Compressed shader 'AVProVideo/VR/InsideSphere Unlit Transparent(stereo+color+fog+alpha)' on gles3 from 2.59MB to 0.10MB
Compressed shader 'AVProVideo/VR/InsideSphere Unlit (stereo) - Android OES ONLY' on gles3 from 4.25MB to 0.03MB
Compiled shader 'AVProVideo/VR/InsideSphere Unlit Transparent(stereo+color+alpha) - Android OES ONLY' in 2.77s
    gles3 (total internal programs: 1152, unique: 576)
Compressed shader 'AVProVideo/VR/InsideSphere Unlit Transparent(stereo+color+alpha) - Android OES ONLY' on gles3 from 13.65MB to 0.08MB
Unexpected Crunch texture format
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions, String[], Boolean)
UnityEditor.DefaultBuildMethods:BuildPlayer(BuildPlayerOptions)
UnityEditor.BuildPlayerWindow:CallBuildMethods(Boolean, BuildOptions)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun(Boolean)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
UnityEditor.EditorApplication:ExecuteMenuItem(String)
UnityEditor.ShortcutManagement.MenuItemEntryDiscoveryInfo:<.ctor>b__7_0(ShortcutArguments)
UnityEditor.ShortcutManagement.Trigger:HandleKeyEvent(Event, IContextManager)
UnityEditor.ShortcutManagement.ShortcutController:HandleKeyEvent(Event)
UnityEditor.ShortcutManagement.ShortcutIntegration:EventHandler()
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()

[C:\buildslave\unity\build\Runtime/Graphics/CubemapTexture.cpp line 151] 
(Filename: C:\buildslave\unity\build\Runtime/Graphics/CubemapTexture.cpp Line: 151)

**Comment by AndrewRH** [comment]
Hmm we've never heard of this error before.  I don't think we use any crunch features... are you sure the error is related to AVPro Video?  Have you tried another version of Unity?  Have you tried with a blank project to make sure it's not something specific to your project?

Thanks,

**Comment by thesanketkale** [comment]
I am using crunch texture compression on some of my textures in the project. Maybe it is not related to AVPro if you say so. Also, I tried and was not able to reproduce it in a blank project with just AVPro in it.

I'll check it in my project, what went wrong. Thanks for the tip.
