### ISSUE TITLE
Multiple video loading issues on android 10(Q) 

### ISSUE THREAD

**Issue by LightGather** [RenderHeads/UnityPlugin-AVProVideo#544]
**Describe the bug**
Multiple videos are not played on Android 10 (Galaxy s9+)

**Your Setup (please complete the following information):**
 - Unity version: 2019.4
 - AVPro Video version: 1.11.7 
 - Operating system version: Android 10(Q)
 - Device model: Samsung Galaxy S9+
 - Video specs (resolution, frame-rate, codec, file size): video0_path(4K 30 fps, h264), video1_path(fHD 30 fps, h264)

**To Reproduce**
1. Load a video using OpenVideoFromFile(FileLocation.AbsolutePathOrURL, video0_path, false) at MediaPlayer0 instance; 
2. Load another video using OpenVideoFromFile(FileLocation.AbsolutePathOrURL, video1_path, false) at MediaPlayer1 instance; 
3. The first video is stopped After the second video is loaded. 
(Same code, No problem on Android 9. I just changed the target SDK because of a policy of google since Nov.
Also, video loading and seeking speed are slower on Android 10, than on Android 9.
I know that access policies of android is changed after Android 10. Should I do something to fix this problem?)

**Comment by damonkim80** [comment]
I have the same problem. please review this issue.

**Comment by RenderHeadsSte** [comment]
Can you provide the requested information please?

- Videos/stream url (can be emailed to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)
- Full logcat output

**Comment by LightGather** [comment]
Hi, I found a temporal solution. 
Add <application android:requestLegacyExternalStorage = "true" > to a AndroidManifest file.
This is the code that gives temporary permission to the storage path in Android 10. (https://forum.unity.com/threads/android-10-and-scoped-storage-missed-features-in-unity-2019.749333/)
The strange thing is that without the code that grants this permission, the video shouldn't load at all. Because of this reason, The Unity video player cannot load external files on Android 10. But in AVPro Video, it loads, but it works as if there is something wrong.
Regarding video format, I found these issues for various video formats (I tested more than 30 different videos). I guess that it's not a problem of specific video resolution or codec.

**Comment by RenderHeadsSte** [comment]
This is interesting,  I would have thought setting 'Write Permissions' in Unity 'Player Settings' would do the trick.

Maybe checking/requesting permissions might help? Info [here](https://docs.unity3d.com/2019.3/Documentation/Manual/android-RequestingPermissions.html)

**Comment by RenderHeadsSte** [comment]
@damonkim80 Can you confirm the fix suggested by @LightGather addresses your use-case as well?

**Comment by damonkim80** [comment]
@RenderHeadsSte Yes. I've fixed it. :) but It doesn't seem to be perfect solution. please keep checking it on new version.
