### ISSUE TITLE
Very low resolution videos not playing on Quest 2

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#549]
**Describe the bug**
I'm using animated video 'patches' on top of a static 360 photo background in VR.
Very small videos (64x64 pixels, or 80x624) don't play on the Quest 2 (Android 10), while they work fine on a Pico G2 4K (Android 8.1), both with AVPro 1.11.7. Larger videos in the same scene play well on both devices. Also everything plays fine in the Editor on Windows.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.22f1 on Windows 10 x64
 - AVPro Video version: 1.11.7
 - Operating system version: Android
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Using Exo Player, no Fast OES Path, Apply To Mesh assigned to a Plane
2. 
3. 

**Logs**
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5706463/log.txt)

**Screenshots**

**Videos**
https://www.vrtourviewer.com/images/Time.mp4 (64x64, 24fps, H264)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Can you send over a logcat output please?

**Comment by RuudvanReenen** [comment]
Sure, added in the first post

**Comment by RenderHeadsSte** [comment]
@RuudvanReenen Have you tried using the MediaPlayer API path?

**Comment by RenderHeadsSte** [comment]
This appears to work using the ExoPlayer API path in AVPro v2 despite the decoder reporting (as it does in v1) that the resolution/framerate is unsupported.

Advice is to upgrade to AVPro Video v2 (using the trial version before to confirm v2 plays these small resolution files as desired)

**Comment by RuudvanReenen** [comment]
Thanks for looking into it! But I've purchased AVPro about 10 months ago for more than € 400, and upgrading to 2.0 now from the full edition to ultra edition (so spatial audio is supported) with a price of € 800 to fix this issue is not possible for an indie/solo dev like me I'm afraid...

**Comment by RenderHeadsSte** [comment]
I understand, sorry there is back-portable fix we can offer.  v1.x is stuck on an older version of ExoPlayer with no path to updating.

The only other option is to increase your video resolution.  It appears the lowest that will playback (of your Time video re-encoded) is 112x112.

I am going to close this issue now as we cannot be of any more help at this time.
