### ISSUE TITLE
Add support for Mixcloud live stream service

### ISSUE THREAD

**Issue by towneh** [RenderHeads/UnityPlugin-AVProVideo#551]
**Is your feature request related to a problem? Please describe.**
I am currently unable to play Mixcloud live video streams with the player e.g. https://www.mixcloud.com/live/capitol54dc/
However the player does work with the audio on demand URLs (non livestream) which plays back the audio and leaves a white screen for the video.

**Describe the solution you'd like**
I would like to see mixcloud live video streams working with avpro video

**Describe alternatives you've considered**
n/a - this request is actually to help provide an alternative away from other services, which are supported by avpro, but are locking down the content which can be broadcast .e.g music.
Mixcloud provides a legal path for the broadcasting and playing of music.

**Additional context**
n/a

**Comment by MorrisRH** [comment]
Mixcloud just uses HLS streams under the hood so it is already supported. Extracting the URL from the embedded video player is beyond the scope of the plugin though.

Perhaps it's worth speaking to Mixcloud to see if they can provide a means for getting the URL to the live stream?

**Comment by towneh** [comment]
> 
> 
> Mixcloud just uses HLS streams under the hood so it is already supported. Extracting the URL from the embedded video player is beyond the scope of the plugin though.
> 
> Perhaps it's worth speaking to Mixcloud to see if they can provide a means for getting the URL to the live stream?

Thank you. I will follow up with youtube-dl as it appears to be more of an issue with resolving an m3u8 file from the URL and instead is crashing the binary.
