### ISSUE TITLE
 Google Cardboard XR Plugin for Unity

### ISSUE THREAD

**Issue by hyenachi** [RenderHeads/UnityPlugin-AVProVideo#553]
Google Cardboard XR Plugin for Unity
I find error with Google Cardboard XR Plugin for Unity.
I can play video but I can't see video Left/Right properly.
I can only see Left/Left or Right/Right in cardboard + android phone(gallexy s10, s8).
I set  target eyes Both at a MainCamera in unity.

**Your Setup (please complete the following information):**
 - Unity version:  2019.3.15f1
 - AVPro Video version: 1.11.7 Android
 - Operating system version:  
 - Device model: Samsung S8, S10
 - Video specs (resolution, frame-rate, codec, file size):  

I wll send a video to your mail address.

**Comment by CYCPeter** [comment]
Hi, We have a similar situation
- Unity version: Unity 2019.4.14
- AVPro Video version: 1.11.5 
- Device model: Sony Xperia J9110
- cardboard version: 1.4.1
Project Settings→XR Plug-in Management→enable Cardboard XR Plugin
stereo render doesn't work (two eye same)

and we also find same project use other setting(don't use XR Plug-in) :
Player→XR Settings→enable Virtual Reality Supported and add Cardboard under Virtual Reality SDKs
stereo render work, but this version  can't  scan the QR code of a Cardboard viewer 
(need to install google VR app, use XR Plug-in setting don't need to install google VR)

**Comment by RenderHeadsSte** [comment]
In v1 of AVPro Video on Android, you must ensure there is no stereo packing metadata in your video.

Appendix A - FAQ, section

**Comment by RenderHeadsSte** [comment]
In v1 of AVPro Video on Android, you must ensure there is no stereo packing metadata in your video.

Appendix A - FAQ, Question (8), outlines exactly how to re-encode to remove all stereo metadata from your video.  Once this is done, you should also check you have the correct stereo packing set in your MediaPlayer component.  Note here that I have set the debug tinting, this will tint the left eye green and the right eye red...so you can ensure you are seeing stereo.

@CYCPeter I would also recommend updating to the latest release of version 1.

![image](https://user-images.githubusercontent.com/46531149/104035597-3cc94880-51ca-11eb-88dc-2acacf6e8167.png)

**Comment by CYCPeter** [comment]
my setting
<img width="257" alt="截圖 2021-01-21 下午3 23 28" src="https://user-images.githubusercontent.com/13131656/105317583-52dcfd00-5bfd-11eb-872d-a64aa6ffcaa0.png">
<img width="560" alt="截圖 2021-01-21 下午3 22 59" src="https://user-images.githubusercontent.com/13131656/105317590-553f5700-5bfd-11eb-8934-e04a30b60020.png">
<img width="265" alt="截圖 2021-01-21 下午3 23 12" src="https://user-images.githubusercontent.com/13131656/105317597-57091a80-5bfd-11eb-9358-8fb7ce214993.png">
my result: https://drive.google.com/file/d/1g8WrOsYeM0ddGIwaD0G8njoHmM_nbwNW/view?usp=sharing

**Comment by RenderHeadsSte** [comment]
@CYCPeter Can you send me a project showing this issue to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) so I can find the issue and offer you a solution?

**Comment by RenderHeadsSte** [comment]
@CYCPeter Thanks for sending over your project.  I have tweaked a few settings and edited one shader to make stereo work with 'Google Cardbaord XR Plugin'.  Here is what you need to do:

1) Disable 'Mock HMD' in 'Project Settings->XR Plug-in Management'
![image](https://user-images.githubusercontent.com/46531149/105510154-39ec4e80-5cc6-11eb-920f-1cacba12688a.png)

2) Edit '\Assets\AVProVideo\Resources\Shaders\AVProVideo.cginc', locate the function:

INLINE bool IsStereoEyeLeft(FLOAT3 worldNosePosition, FLOAT3 worldCameraRight)

Change this to:
![image](https://user-images.githubusercontent.com/46531149/105510014-0f9a9100-5cc6-11eb-8cc1-e37263b560a8.png)
(I have highlighted the changed section)

3) Ensure the 'Tracked Pose Driver' component (found on the MainCamera) has the following settings:
![image](https://user-images.githubusercontent.com/46531149/105510360-7455eb80-5cc6-11eb-9669-62552ad6d941.png)

4) Remove the component 'Update Stereo Material':
![image](https://user-images.githubusercontent.com/46531149/105510526-a6674d80-5cc6-11eb-8546-a79d1a2213a5.png)


That should be all you need to do.

Do let me know how you get on @CYCPeter, and @hyenachi this should also wok for you.

We will look at making this support automatic in AVPro Video version 2, though the support from the Cardboard XR Plugin looks to be a little thin on first research.

**Comment by ar2vrPeter** [comment]
it's ok, thanks for your help

**Comment by RenderHeadsSte** [comment]
@ar2vrPeter: Are you associated with @CYCPeter or @hyenachi at all?  Would be great to get some feedback on whether the solution presented here has solved the issue.

**Comment by CYCPeter** [comment]
@hyenachi is not associated with me.

**Comment by RenderHeadsSte** [comment]
We will be closing this issue son due to lack of response

**Comment by synthercat** [comment]
I can't build the project: I think there is something wrong here:
![image](https://user-images.githubusercontent.com/15571710/169223681-bb2f6cb6-688c-49b4-b8f2-dbd9e4a7808a.png)
The error I get is this:
> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:checkReleaseManifest UP-TO-DATE
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:prepareLintJar UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :launcher:preReleaseBuild
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:checkReleaseManifest UP-TO-DATE
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:generateReleaseSources UP-TO-DATE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:generateReleaseSources UP-TO-DATE
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:bundleLibRuntimeRelease UP-TO-DATE
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :launcher:processReleaseManifest
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :launcher:processReleaseResources
> Task :launcher:compileReleaseJavaWithJavac UP-TO-DATE
> Task :launcher:compileReleaseSources UP-TO-DATE
> Task :launcher:lintVitalRelease
> Task :launcher:mergeReleaseShaders UP-TO-DATE
> Task :launcher:compileReleaseShaders UP-TO-DATE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:validateSigningRelease UP-TO-DATE
> Task :launcher:signingConfigWriterRelease UP-TO-DATE
> Task :launcher:checkReleaseDuplicateClasses UP-TO-DATE
> Task :launcher:transformClassesWithDexBuilderForRelease UP-TO-DATE

> Task :launcher:transformDexArchiveWithExternalLibsDexMergerForRelease FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
41 actionable tasks: 12 executed, 29 up-to-date

UnityEditor.EditorApplication:Internal_CallGlobalEventHandler ()

Can anyone help? What's your custom manifest/gradle files?
Unity 2019.4.30f
OpenSource Carboard 1.8.0
AVPro 2.5.0
