### ISSUE TITLE
Passing audio through AudioMixer

### ISSUE THREAD

**Issue by vmp1r3** [RenderHeads/UnityPlugin-AVProVideo#554]
I'm using AudioOutput component but it is not passing trough AudioSource

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.30f1
 - AVPro Video version: AVPro Video v1.11.7 
 - Operating system version: Windows 10 20H2
 - Device model: Lenovo Legion Y-540
 - Video specs (resolution, frame-rate, codec, file size): FantasyStereoFB360.mkv from Defaults

**To Reproduce**
1. On 13_Demo_360StereoSpatialAudio add AudioOutput and AudioSource component to AVPro Video
2. Set Video Player to AudioOutput
3. Create AudioMixer and apply it to AudioSource
4. Play. You can see that AudioOutput's value is flashing from 01 seconds to 02 and turns back to 01

What I actually want to do is to change pitch when I speed up and slow down video to reduce low sound on slow playback speed and high on fast playback speed

**Comment by AndrewRH** [comment]
13_Demo_360StereoSpatialAudio is set up by default to play audio through the Facebook Audio 360 path, so it will not send audio to Unity.   you would need to go to MediaPlayer > Platform Specific > Windows and change the AudioOutput mode to Unity.  You then need to set the AudioOutput component up and you should then get audio playing and chaining through to the AudioMixer component.

If you do use that demo scene as a starting point, then please change the media as the sample MKV it uses is designed for usage with Facebook Audio 360 only.

Does that help?

**Comment by vmp1r3** [comment]
Not really, I want to apply audio effects to my audio by keeping facebook's audio path, will I loose spatial audio if I pass it trough Unity?

Thank you

**Comment by AndrewRH** [comment]
Yes I'm afraid the two audio options are mutually exclusive.  We don't have support for parsing the spatial audio back into Unity.
