### ISSUE TITLE
Relative To Streaming Assets Folder not working on [Android] platform if the device does not have SDCard.

### ISSUE THREAD

**Issue by reysantana** [RenderHeads/UnityPlugin-AVProVideo#555]
Issue:
[METHOD 1]
- Platform: Android
- Build Settings -> Other Settings -> Install Location: Prefer External/Prefer Internal/Automatic
- Build Settings -> Other Settings -> Write Permission: External(SDCard)

Result: Video plays on NOX Emulator, works on the devices that have SDCard inserted.
Not working on the devices that do not have SDCard inserted.

[METHOD 2]
- Platform: Android
- Build Settings -> Other Settings -> Install Location: Prefer External/Prefer Internal/Automatic
- Build Settings -> Other Settings -> Write Permission: Internal

Result: Video is not playing on any devices including the emulator.

-----
Unity version: Unity 2018.4.30f1
AVPro Video Version: the latest version.

**Comment by RenderHeadsSte** [comment]
I have tried to reproduce this issue on a physical Android device that does not have an external SDcard.  I cannot reproduce.  Are you able to provide specific device information and a logcat dump?

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
