### ISSUE TITLE
Vimeo Live not working 

### ISSUE THREAD

**Issue by WulfGames** [RenderHeads/UnityPlugin-AVProVideo#557]
**Describe the bug**

When trying to reproduce a live video from vimeo having a premium account and using
their SDK https://github.com/vimeo/vimeo-unity-sdk we get the following error:
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)

Not sure if there's an additional step in order to get it working, seems like the codec is not supported.

Thanks!

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.9
 - AVPro Video version: 1.11.7
 - Operating system version: Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 1280x720, 30fps, mpd, live

**To Reproduce**
1. Create live streaming on vimeo
2. Using vimeo SDK
3. Select live video and hit play

**Comment by sathishkntrjhexa** [comment]
Me too having the same issue, I want to stream the videos directly on the screen(WebGL, Android and iOS) )from my vimeo pro account, so i came to use this AV Pro.
Am trying to get it worked using the trial version, but there is no proper guidance or documentation for streaming the live from vimeo. If you can help me out for completing this, i will buy it for the future usage without water mark.

Hope i will get the answers from you guys soon.
Thank you.

**Comment by WulfGames** [comment]
The problem is not on AvPro but actually on the vimeo access for live streaming. Their API is only available for Enterprise level users.

Hope that helps.
