### ISSUE TITLE
How to improve/eradicate video stalling in a streamed video playback on Android and iOS devices?

### ISSUE THREAD

**Issue by thesanketkale** [RenderHeads/UnityPlugin-AVProVideo#559]
Hi,

I hope the title covers the question quite clearly. But just to elaborate, while streaming a video on the AVPro video player in Android and iOS devices, for a brief moment after playing the initial few seconds, the video enters a stalled state. I can see that It's not buffering as the IsBuffering flag is false almost throughout the video (except in the beginning). Now, after 2-5 seconds (depending on the device) it continues the video normally. The same video plays smoothly in the browsers but somehow stalls a minimum of twice in a 30-second video.

Given that the internet speed is adequate (4G) on the device and a 30-second video with 1080x1920 resolution served through AWS S3 storage with Cloudfront edge-caching enabled, what can I do to have a seamless and smooth video experience in the app without any stalling from the AVPro player and server side(if I am missing anything there too)?

P.S. - I just want the video streaming experience to be as seamless as possible and I need best practices for this from you guys.

**Comment by AndrewRH** [comment]
Hmm I'm not sure why it would pause like that - though connections like 4G I guess the download rate could change and so it might be trying to adapt to that.

I would first check that your videos (mp4 files I assume) are encoded with 'fast start' enabled.  For best results you might also want to check your bitrate settings to make sure that there aren't any massive spikes in bitrate.  With variable rate encoding you can get sudden huge spikes in bitrate, so you have to be a bit careful about this.  Without knowing about the specs of your videos (frame rate, duration, file size, encoding settings etc) it's tricky to tell.

Thanks,

**Comment by thesanketkale** [comment]
Great, thanks for the pointers. I have already enabled faststart while encoding using ffmpeg. Here is my sample video. 
https://www.dropbox.com/s/2lbi3zeo5naq32q/encoded.mp4?dl=0

Originally this video was recorded from a smartphone. Then I encoded it using below command:

ffmpeg -i srcVideoPath -vcodec h264 -acodec aac -strict -2 -preset superfast -crf 20 -movflags +faststart -b:v 4000k -b:a 128k -r 30 outputVideoPath -y

Does the command make sense? What else can I do to improve streaming?
Thanks.

**Comment by AndrewRH** [comment]
Thanks, we will take a look.

A few questions:
1) Could you share the S3 URL for it with us?
2) Which version of Unity and AVPro Video are you using?
3) If you try lowering the bitrate, and/or removing the audio track - does that help?

Thanks,
