### ISSUE TITLE
HTTP Cookies

### ISSUE THREAD

**Issue by Dyhr** [RenderHeads/UnityPlugin-AVProVideo#56]
**Is your feature request related to a problem? Please describe.**
When trying to access files from a web service that uses cookies for sessions, AVProVideo fails to authenticate.

**Describe the solution you'd like**
An option to specify an HTTP Cookie, or even any header if possible

**Describe alternatives you've considered**
Not using AVProVideo

**Comment by AndrewRH** [comment]
Which platform is this on?

**Comment by Dyhr** [comment]
Ideally any platform, but specifically Windows

**Comment by AndrewRH** [comment]
On Android, iOS and macOS we allow custom http fields to be specified.  
So perhaps the cookie could be read and put into this field?

Here is how you can set the field in code:

`mediaPlayer.PlatformOptionsAndroid.httpHeaderJson = @"{ "mykey":"myvalue" }"';`

I know it's not exactly what you're looking for, so we'll keep this ticket open and see what's possible.  Perhaps you could give more information about how we could replicate this?

**Comment by Dyhr** [comment]
Yeah, that's what I'm looking for, but on Windows and UWP too

**Comment by lukemonaghan** [comment]
Has there been any updates to this feature request? I am also looking at building using this plugin and one necessity is using HTTP headers on windows.

**Comment by AndrewRH** [comment]
Not yet.. i believe this is coming in version 2.0 of the plugin

**Comment by AnhPham** [comment]
@AndrewRH Hi, we are using the last version of AVPro Video(full version), we need to add cookie for streaming video from amazon cloud, these data required:
- CloudFront-Policy
- CloudFront-Key-Pair-Id
- CloudFront-Signature

On platform specific, I tried to set http header (json) (on macOS, iOS, Android), for example,
{"cookie":{"CloudFront-Policy":"xxx","CloudFront-Key-Pair-Id":"yyy","CloudFront-Signature":"zzz"}}

But Unity Editor crashes when I click Play button. Please help!

**Comment by AndrewRH** [comment]
> @AndrewRH Hi, we are using the last version of AVPro Video(full version), we need to add cookie for streaming video from amazon cloud, these data required:
> 
> * CloudFront-Policy
> * CloudFront-Key-Pair-Id
> * CloudFront-Signature
> 
> On platform specific, I tried to set http header (json) (on macOS, iOS, Android), for example,
> {"cookie":{"CloudFront-Policy":"xxx","CloudFront-Key-Pair-Id":"yyy","CloudFront-Signature":"zzz"}}
> 
> But Unity Editor crashes when I click Play button. Please help!

Which platform is this on?

**Comment by AnhPham** [comment]
> > @AndrewRH Hi, we are using the last version of AVPro Video(full version), we need to add cookie for streaming video from amazon cloud, these data required:
> > 
> > * CloudFront-Policy
> > * CloudFront-Key-Pair-Id
> > * CloudFront-Signature
> > 
> > On platform specific, I tried to set http header (json) (on macOS, iOS, Android), for example,
> > {"cookie":{"CloudFront-Policy":"xxx","CloudFront-Key-Pair-Id":"yyy","CloudFront-Signature":"zzz"}}
> > But Unity Editor crashes when I click Play button. Please help!
> 
> Which platform is this on?

I tested on Unity Editor (current platform is iOS)

**Comment by AndrewRH** [comment]
> > > @AndrewRH Hi, we are using the last version of AVPro Video(full version), we need to add cookie for streaming video from amazon cloud, these data required:
> > > 
> > > * CloudFront-Policy
> > > * CloudFront-Key-Pair-Id
> > > * CloudFront-Signature
> > > 
> > > On platform specific, I tried to set http header (json) (on macOS, iOS, Android), for example,
> > > {"cookie":{"CloudFront-Policy":"xxx","CloudFront-Key-Pair-Id":"yyy","CloudFront-Signature":"zzz"}}
> > > But Unity Editor crashes when I click Play button. Please help!
> > 
> > 
> > Which platform is this on?
> 
> I tested on Unity Editor (current platform is iOS)

Yes, but I mean which platform is your Unity Editor running on - Windows or macOS?

**Comment by AndrewRH** [comment]
It definitely shouldn't crash - that's a bug - we will investigate this.  I think though your JSON layout may be incorrect.  Try this:

{
"Set-Cookie":"CloudFront-Policy=xxx",
"Set-Cookie":"CloudFront-Key-Pair-Id=xxx",
"Set-Cookie":"CloudFront-Signature=xxx"
}

**Comment by AnhPham** [comment]
> It definitely shouldn't crash - that's a bug - we will investigate this. I think though your JSON layout may be incorrect. Try this:
> 
> {
> "Cookie":"CloudFront-Policy=xxx; CloudFront-Key-Pair-Id=xxx; CloudFront-Signature=xxx"
> }
> 
> Thanks,

It works like a charm. Thank you very much for your support!

**Comment by AnhPham** [comment]
@AndrewRH 
Hi,
{
"Cookie":"CloudFront-Policy=xxx; CloudFront-Key-Pair-Id=xxx; CloudFront-Signature=xxx"
}
It works for macOS, iOS, but not for Android. Please help!

**Comment by AndrewRH** [comment]
> @AndrewRH
> Hi,
> {
> "Cookie":"CloudFront-Policy=xxx; CloudFront-Key-Pair-Id=xxx; CloudFront-Signature=xxx"
> }
> It works for macOS, iOS, but not for Android. Please help!

@AnhPham which Media API do you have set? (under Platform Specific > Android) settings, and what sort of URL media is it (straight mp4 file, or m3u8 etc)?

hmmm @RenderHeadsSte could you check these HTTP fields are coming through in 1.10.2?   ta!

**Comment by AnhPham** [comment]
@AndrewRH 
1. Exo Player (default)
2. m3u8
3. Android 8.1.0
4. AVPro Video 1.10.1

**Comment by AndrewRH** [comment]
@AnhPham could you please update to the latest version of AVPro Video (1.10.2) as I believe we fixed that issue in the last update.   Let me know if that solves your issue.

Thanks,

**Comment by AnhPham** [comment]
@AndrewRH I will try then let you know soon!

**Comment by AnhPham** [comment]
@AndrewRH I confirm that 1.10.2 works for Android too. Thank you!

**Comment by AndrewRH** [comment]
This is now supported in Windows in 2.0.0-beta1

**Comment by dalkia** [comment]
Hi! Im setting up the http header using the add function httpheaders using the format

LoadingPlayer.PlatformOptionsAndroid.httpHeaders.Add(
					new MediaPlayer.PlatformOptions.HTTPHeader("Cookie",
						"CloudFront-Policy=XXXXX; " +
						"CloudFront-Key-Pair-Id=XXXXX; " + 
						"CloudFront-Signature=XXXXX; "));

Im getting the " Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources." error.

Im currently using

- Exo Player (default)
- m3u8
- Unity Editor 2019.4.3 (Target Android)
- AVPro Video 1.11.5

Any suggestions? Thanks in advance!
