### ISSUE TITLE
Avprovideosamples / Fantasy stereo fb360.mkv cannot be played using demo program

### ISSUE THREAD

**Issue by Z149032105** [RenderHeads/UnityPlugin-AVProVideo#561]
**Describe the bug**
Avprovideosamples / Fantasy stereo fb360.mkv cannot be played using demo program

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.11f1
 - AVPro Video version: UnityPlugin-AVProVideo-v1.11.7-Trial
 - Operating system version: windows10
 - Device model: pc
 - Video specs (resolution, frame-rate, codec, file size): 
Samples/FantasyStereoFB360.mkv
**To Reproduce**
1. [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
2. I can use potplayer to play the video
Avprovideosamples / Fantasy stereo fb360.mkv cannot be played using demo program

**Comment by AndrewRH** [comment]
Is this on Windows?

Are you playing the video in the 360SpatialAudio demo scene?   If so - it should work as that MediaPlayer is configured correctly to play that media.

If you're just trying to play it in general, then you need to set the MediaPlayer correcty, as that media contains special audio format that can only be played using Facebook Audio 360.  You need to go to Platform Specific > Windows options, and set the Audio Output mode to Facebook Audio 360.  This should stop it crashing.  Then if you want to hear the audio you need to add an AudioOutput component and set that up to use the MediaPlayer.   Or you can just look at the 360SpatialAudio demo scene as a reference.

I hope this helps?

**Comment by Z149032105** [comment]
yes,on windows
audio format already set to Facebook Audio 360(I actually opened the demo project without making any changes)
still can not play the video.
I have try to bulid to exe.can not play.
I don't know where the problem is.

PS.
1. Avpro cannot play the video
2. Windows media play cannot play the video
Then I installed a combined community codec pack
[windows media play] can play the video
Avpro is still unable to play the video

**Comment by AndrewRH** [comment]
Are you using Windows 10?

**Comment by Z149032105** [comment]
Win10, of course

I don't know if your component comes with a decoder

Or components that depend on windows

If I use your plug-in. If my customer encounters this problem

How should I solve it.

1. If you are dependent on windows components

Unable to play the video. There should be some updated Microsoft patches to solve the problem

But I don't know which patch to download

2. If your component comes with decoder

Then we should check why it fails

**Comment by RenderHeadsSte** [comment]
My hunch here is that you require the Microsoft HEVC codec (which can be obtained [here](https://www.microsoft.com/en-gb/p/hevc-video-extensions/9nmzlz57r3t7?activetab=pivot:overviewtab) - it used to be free, but MS now charge a small fee for it :/ ).  Are you able to purchase this to test?

**Comment by RenderHeadsSte** [comment]
@Z149032105 are you still requiring support for this issue?
