### ISSUE TITLE
Seeking API changes in 2.0

### ISSUE THREAD

**Issue by skooby** [RenderHeads/UnityPlugin-AVProVideo#564]
Problem description:

Using the new version 2.0rc2 and my player broke when I upgraded to the new version.

I have a videos of 3d models that are rendered in 360 and scrubbing the video back and forth to give the illusion of 3d.
My player was based on the 1.x version that used 2 media players to help smooth seeking. 
Which was swapping between the players based on seeking. Which was working rather nicely.
Is this functionality no longer available? 
Do you have an example that I could see for reference? 
Or is there something built into the new version that provides this functionality?

Device (which devices are you having the issue with - model, OS version number):

In Editor

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

System Information:

AVPro Video: v2.0.0-rc2 (plugin v2.0.0f2-ultra)
Target Platform: Standalone
Unity: v2019.4.13f1 WindowsEditor
OS: Desktop - HP Spectre x360 Convertible 13-ae0xx (HP) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz - 8 threads - 16223KB
GPU: NVIDIA GeForce GTX 1060 3GB - NVIDIA - Direct3D 11.0 [level 11.1] - 2988KB - 16384

**Comment by AndrewRH** [comment]
Hi,

I'm afraid that the new version 2 is not compatible with the old version as it contains too many changes.  You should remove version 1.x completely before adding version 2 to your project.  The API has also changed so you will have to adjust any scripts you have that used the old plugin.

Seeking functionality is still there.  What exactly do you need an example of?

The biggest change is that time has changed from float-milliseconds to double-seconds.

The methods you used before for seeking and getting duration etc should still all be the same.

Let me know if that helps or if you need more information.

Thanks,

**Comment by skooby** [comment]
Forget what I said about multiple MediaPlayers I see that is for helping with loading media samples more seemlessly.

The new version is extremely choppy when seeking. I want to be able scrub the video for my pseudo 360 viewer. This sluggishness is apparent using the off the shelf demo and grabbing the timeline control and moving it back and forth.

**Comment by AndrewRH** [comment]
Hmm it shouldn't be choppy - the new version has many improvements, so it must be an issue if it wasn't choppy previously using AVPro Video 1.x?

Are you developing on macOS?

Changing to all keyframes should definitely give the best scrubbing performance.

**Comment by gvax-tv** [comment]
Hello,
I just upgraded the full v1 plugin to the new v2 core plugin. Just wanted to make sure, if all our projects were working fine with the full v1 plugin, then all should work fine with v2 core, or did you remove some v1 functionalities and put it into the new "ultra" version? If that is the case, could you list what was available in full v1 and is now only available in ultra v2?
If nothing has been removed, then it's great...just wanted to make sure before starting to work on changing APIs and scripts. Thanks a lot
Kind regards
Patrick

**Comment by skooby** [comment]
Your question is valid, however gvax-tv you may want to create a new post, to make sure that your question gets answered. 

In response to Andrew. I created a new video file with keyframes on each frame and that is much better, it appears to be at least as fast as 1.x in the editor.

I really like the new player changes. I modified the given example to be able to scrub. And I also added a full screen toggle option. And flags for turning on/off the extra cool ui elements.

**Comment by RenderHeadsSte** [comment]
@gvax-tv There are some more advanced features that were included in v1 that are no longer in the core version.  You can find a table of features per flavour [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions).

**Comment by RenderHeadsSte** [comment]
@skooby

- Are you using the exact same OS and source video in your v2 project as your v1 project?
- Are you using the same Video API in v2 that you were using in v1?
- Does it happen in the editor as well as a Windows standalone build?

i.e. can you say for certain that the choppy behaviour is down to changes between the two version?

**Comment by RenderHeadsSte** [comment]
@skooby do you still require support for this issue?
