### ISSUE TITLE
Save Streamed Video

### ISSUE THREAD

**Issue by skooby** [RenderHeads/UnityPlugin-AVProVideo#565]
Looking to save the Streamed video to the persistent folder.

The documentation is a bit sparse for details :)

**Comment by AndrewRH** [comment]
Do you mean download a file and store it in the persistent folder?

We don't have an example of this, but you should have a look at: https://docs.unity3d.com/Manual/UnityWebRequest.html

It might not be the best choice today, it's hard to keep up as Unity keep changing their networking API.

**Comment by skooby** [comment]
This appears to not be really allowed from the OS standpoint to copy from Streamed folder to Persistent folder. I guess that makes sense.

**Comment by RenderHeadsSte** [comment]
Are you happy for us to close this issue now @skooby ?

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
