### ISSUE TITLE
AVPro Video player delay

### ISSUE THREAD

**Issue by mykrana** [RenderHeads/UnityPlugin-AVProVideo#566]
Hi,

I use the AVPro Video player to play a 360 live streaming video on Unity. 
I noticed that when I start the video player it takes about 8s to load the video and the live streaming video I watch has 8s delay. 
That is the video player starts, it takes 8s to show the live streaming video  and when it shows the video, it is 8s back in time (as long as the delay is).
The same delay appears when I run it in Oculus Quest.
How could I decrease the delay of the video player? Are there any settings?   

**Your Setup (please complete the following information):**
 - Unity version: 2019.14f1
 - AVPro Video version: 1.11.7
 - Operating system version: Windows, Android
 - Device model: Dell G5, Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size): 640X480@30

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Are you able to provide a link to the stream?

**Comment by mykrana** [comment]
Unfortunately, I cannot provide a link of the stream due to privacy issues.
Do you have any idea why this is happening? Or what could I do to my server
to reduce this latency?
I use an rtsp protocol. Is there any case that the protocol causes the
delay?

Myrto

Στις Παρ, 15 Ιαν 2021 στις 12:50 μ.μ., ο/η Ste Butcher <
notifications@github.com> έγραψε:

**Comment by RenderHeadsSte** [comment]
I would say 100% the delay you are seeing is the due to it being an RTSP stream.  RTSP streams always seem to have a lot of inherent lag compared to HLS etc.  If you google 'rtsp delay start' you might find some tricks on server setup to minimise the delay.
