### ISSUE TITLE
AVPro mp4 video width different size vs ffmpeg info

### ISSUE THREAD

**Issue by IL55** [RenderHeads/UnityPlugin-AVProVideo#567]
**Describe the bug**
We want to play video with pixel precise quality:
I.e. we silced it with ffmpeg, fro example that size 1920x1080
 Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 3227:3236 DAR 12908:7281], 15999 kb/s, SAR 3191

but AVPro shows next info:
[AVProVideo] Using playback path: MF-MediaEngine-Hardware (1915x1080@30.00)

**Your Setup (please complete the following information):**
[AVProVideo] Initialising AVPro Video (script v1.11.5 plugin v1.11.4) on NVIDIA GeForce GT 545/Direct3D 11.0 [level 11.0] (MT True) on WindowsEditor Windows 10  (10.0.0) 64bit
 - Video specs (resolution, frame-rate, codec, file size): 
ffmpeg -i 5dcb9eb6-ee2a-4da8-bbb1-301b1a7b5a12_1-sliced-3.mp4
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gpl --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-opencl --enable-videotoolbox
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '5dcb9eb6-ee2a-4da8-bbb1-301b1a7b5a12_1-sliced-3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:00:24.00, start: 0.000000, bitrate: 15987 kb/s
    Stream #0:0(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 3227:3236 DAR 12908:7281], 15999 kb/s, SAR 31911:32000 DAR 10637:6000, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : ?Mainconcept Video Media Handler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s (default)
    Metadata:
      handler_name    : #Mainconcept MP4 Sound Media Handler
At least one output file must be specified

**Comment by RenderHeadsSte** [comment]
It looks like the issue is in your encoding.  The video stream has a SAR (Sample Aspect Ratio) of 3227:3236 which is 0.99721878862793572311495673671199.  So...

1920 x 0.99721878862793572311495673671199 = 1914.660074165636588380716934487

...rounded, that 1915.  This is what you are seeing reported (1915 x 1080)

**Comment by RenderHeadsSte** [comment]
@IL55 Do you require further support with this issue?

**Comment by IL55** [comment]
Thanks for support, I confirm that it was problem with SAR/DAR parameters, we changed it and I see right width here in AVPro player. Could you close the issue ?
