### ISSUE TITLE
Memory issues on Android and IOS device

### ISSUE THREAD

**Issue by KejieZhan** [RenderHeads/UnityPlugin-AVProVideo#568]
**Describe the bug**
Hi,I'm trying to Play and Stop one video repeatedly on Andriod and IOS device, but they both exist memory issues to bother me.
On Android , the memory is rising from 57mb at the beginning to 89mb later, and the memory looks like is not very stable after every stop and destroy. **what can i do to make the memory stable or at least make the memory reduce to as same as the begining after destroy**(maybe Avpro has cached some buffers and I'm wondering if there is api to release them).

On IOS, the memory is rising from 111mb at the beginning to 129mb later,and the memory seems like increased 1mb every time I stop and destroy the video. It looks like memory leaking but the memory stop increasing when it comes to 129mb. **I'm wondering if avpro has memory leak problem on IOS, and what can I do to make the memory not increase everytime . And also ,what can i do to release memory to make it return to 111mb in this case.**

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.36c1
 - AVPro Video version: 1.11.7
 - Operating system version: Android(6.0.1)
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 
 - 1920*1080
 - framerate:30
 - filesize:503mb

**To Reproduce**
 create and destroy MediaPlayer

**Screenshots**
Android:
![memoryIssue](https://user-images.githubusercontent.com/41566559/104290737-a82a5780-54f5-11eb-9331-5ddaf3a6f071.jpg)

IOS:
![1](https://user-images.githubusercontent.com/41566559/104300113-06a90300-5501-11eb-9b4f-6759287e708b.jpg)
![2](https://user-images.githubusercontent.com/41566559/104300136-0d377a80-5501-11eb-93fa-616991f0d9b3.jpg)
![3](https://user-images.githubusercontent.com/41566559/104300146-0f99d480-5501-11eb-918c-613d2a8779fa.jpg)
![4](https://user-images.githubusercontent.com/41566559/104300149-11639800-5501-11eb-87c7-d3aa04b03e81.jpg)

**Comment by KejieZhan** [comment]
this is my testcode.
![testcode](https://user-images.githubusercontent.com/41566559/104291447-8087bf00-54f6-11eb-9f8f-67180e50d681.jpg)

**Comment by RenderHeadsSte** [comment]
Not really sure I am seeing an issue here?  It looks like memory is more or less stable.  There certainly isn't an consistent incremental increase on either platform from what I can see, or our testing here.  Have you left it for, say, a thousand open/play/close cycles? (which is one of the way we test here)

**Comment by KejieZhan** [comment]
> Not really sure I am seeing an issue here? It looks like memory is more or less stable. There certainly isn't an consistent incremental increase on either platform from what I can see, or our testing here. Have you left it for, say, a thousand open/play/close cycles? (which is one of the way we test here)

So,once i played a video . about 20mb - 30mb memory will never release ,even i close it and destroy the video component. 
is there any way to make these memory release?

**Comment by MorrisRH** [comment]
It looks like Unity's managed heap is behind the bulk of the increased memory usage so you're unlikely to be able to get it back. More information on the heap is available [here](https://docs.unity3d.com/Manual/BestPracticeUnderstandingPerformanceInUnity4-1.html). Specifically the section **Key Problems with the Heap** seems to apply, pasted in part below:

**Key problems with the heap**
The core issues with managed heap expansion are twofold:
- Unity does not often release the memory pages allocated to the managed heap when it expands; it optimistically retains the expanded heap, even if a large portion of it is empty. This is to prevent the need to re-expand the heap should further large allocations occur.
- On most platforms, Unity eventually releases the pages used by empty portions of the managed heap back to the operating system. The interval at which this occurs is not guaranteed and should not be relied upon.

**Comment by KejieZhan** [comment]
thank you for your reply! It helps a lot!

**Comment by MorrisRH** [comment]
You might find keeping the MediaPlayer object around gives you better memory performance instead of repeatedly creating and destroying it.

**Comment by KejieZhan** [comment]
> You might find keeping the MediaPlayer object around gives you better memory performance instead of repeatedly creating and destroying it.

ok.I will try. Thanks again！

**Comment by RenderHeadsSte** [comment]
Are you happy for us to close this issue @KejieZhan ?

**Comment by KejieZhan** [comment]
> Are you happy for us to close this issue @KejieZhan ?

Yes~

**Comment by jiuchengzjy** [comment]
Hello, what if I didn't destroy the object but still didn't release the memory ？
      private void OnDisable()
    {
        _mediaPlayer.CloseVideo();
        _mediaPlayer.Stop();
        _mediaPlayer.Events.RemoveAllListeners();
    }

**Comment by jiuchengzjy** [comment]
@RenderHeadsSte
