### ISSUE TITLE
HLS stream with .fmp4 not playing on Android

### ISSUE THREAD

**Issue by ishaans** [RenderHeads/UnityPlugin-AVProVideo#57]
**Describe the bug**
An HLS stream with fmp4 chunks doesn't play on Android 8 or 9. This is the stream from the examples in the avpro documentation.
It works on the same Unity code run on iOS devices

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.8f1
 - AVPro Video version: 1.9.6
 - Operating system version: Android 9/ Android 8
 - Device model: Pixel 1, Pixel 2, S7, S9
 - Video specs (resolution, frame-rate, codec, file size): RESOLUTION=1920x1080,FRAME-RATE=60.000, CODECS="avc1.64002a,ec-3"

**To Reproduce**
1. Try playing an fmp4 stream on an Android 8 or 9 device

**Logs**
05-17 07:41:07.551 14496 14539 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
05-17 07:41:07.551 14496 14539 W VideoCapabilities: Unrecognized profile 2130706434 for video/avc
05-17 07:41:07.552 14496 14539 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
05-17 07:41:07.552 14496 14539 W VideoCapabilities: Unrecognized profile 2130706434 for video/avc
05-17 07:41:07.556 14496 14539 W VideoCapabilities: Unrecognized profile 4 for video/hevc
05-17 07:41:07.562 14496 14539 W VideoCapabilities: Unrecognized profile 2130706433 for video/avc
05-17 07:41:07.562 14496 14539 W VideoCapabilities: Unrecognized profile 2130706434 for video/avc
05-17 07:41:07.566 14496 14539 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
05-17 07:41:08.371 14496 14539 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
05-17 07:41:08.371 14496 14539 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
05-17 07:41:10.748 14496 14539 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
05-17 07:41:10.748 14496 14539 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
05-17 07:41:10.749 14496 14539 I Unity   : [AVProVideo] Opening https://tungsten.aaplimg.com/VOD/bipbop_adv_fmp4_example/v9/prog_index.m3u8 (offset 0)
05-17 07:41:10.749 14496 14539 I Unity   :  
05-17 07:41:10.749 14496 14539 I Unity   : (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
05-17 07:41:10.749 14496 14539 I Unity   : 
05-17 07:41:10.754 14496 14539 V MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
05-17 07:41:10.754 14496 14539 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
05-17 07:41:10.754 14496 14539 W MediaPlayer: Couldn't open https://tungsten.aaplimg.com/VOD/bipbop_adv_fmp4_example/v9/prog_index.m3u8: java.io.FileNotFoundException: No content provider: https://tungsten.aaplimg.com/VOD/bipbop_adv_fmp4_example/v9/prog_index.m3u8
05-17 07:41:10.762 14496 14539 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@64368a3): Cookies: null
05-17 07:41:10.769   943   943 D NuPlayerDriver: NuPlayerDriver(0xea831880) created, clientPid(14496)
05-17 07:41:10.776   943   943 D SurfaceUtils: connecting to surface 0xea878808, reason setVideoSurfaceTexture
05-17 07:41:10.778   943 14702 D NuPlayer: onSetVideoSurface(0xead65000, no video decoder)
05-17 07:41:10.784   943 14703 I LiveSession: onConnect https://<suppressed>
05-17 07:41:10.785 14496 14583 V MediaHTTPService: makeHTTPConnection: CookieHandler (java.net.CookieManager@d1bd71e) exists.
05-17 07:41:10.785 14496 14583 V MediaHTTPService: makeHTTPConnection(android.media.MediaHTTPService@64368a3): cookieHandler: java.net.CookieManager@d1bd71e Cookies: null

**Videos**
Video URL : https://tungsten.aaplimg.com/VOD/bipbop_adv_fmp4_example/master.m3u8

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Thanks, we will investigate.

Does it make a difference if you switch the Video API from ExoPlayer to MediaPlayer ( in MediaPlayer component, in section Platform Specific > Android)?

**Comment by ishaans** [comment]
Hi Andrew, 

It looks like I had this configured the other way round. Our video API was set to MediaPlayer instead of ExoPlayer. I changed it to use ExoPlayer and the video works on a Pixel 2 on Android 9. I'll test with other devices to see if there's any issue. 

Thanks!
