### ISSUE TITLE
MediaPlayer in prefab root with path source causes endless prefabs modification loop

### ISSUE THREAD

**Issue by ruben-ivre** [RenderHeads/UnityPlugin-AVProVideo#570]
**Describe the bug**
When the MediaPlayer component is in the root of a prefab and the source is set to path, previewing the prefab in the inspector (without entering prefab editing mode) causes a weird endless modification loop, causing editor slowness and a prompt to save or discard changes when entering prefab mode.
The loop disappears when entering prefab editing mode.

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.21f
 - AVPro Video version: 2.0.1
 - Operating system version: Windows 10 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Open demo scene Demo_MediaPlayer.
2. Drag MediaPlayer GameObject to somewhere in the project to create a prefab out of it.
3. Change the media source to path.
4. Observe the mouse icon changing to busy and a general slowness in the system.

**Comment by AndrewRH** [comment]
Thanks for reporting this.  Yes it looks like the prefab is constantly trying to save itself each frame.  I've attached the fixed script here for you to copy over the old script in /AVProVideo/Editor/Scripts:

[EditorHelper.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5810317/EditorHelper.zip)

We will include this fix in 2.0.2 when it is released.

Thanks,

**Comment by ruben-ivre** [comment]
I can confirm that the fix works, thanks.
