### ISSUE TITLE
Trying to play back MP4 video doesn't work on Mac

### ISSUE THREAD

**Issue by pmb1701** [RenderHeads/UnityPlugin-AVProVideo#574]
**Describe the bug**
We have a multiplatform application that needs to play back MP4 files from URLs. On Windows and Android it works normally, but on Mac we get this error:

`[AVProVideo] Cannot load resource, AVPro Video Ultra Edition is required for HLS AES support.`

These are just regular MP4 files, so this message doesn't seem to make much sense.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1
 - AVPro Video version: 2.0.1
 - Operating system version: macOS Big Sur 11.1
 - Device model: iMac

**Comment by MorrisRH** [comment]
Are you able to provide a link to a video that isn't working for you? (You can email us at unitysupport@renderheads.com if you don't want to share it publicly).

**Comment by MorrisRH** [comment]
Support handled privately.
