### ISSUE TITLE
FinishedPlaying event does not fire on iOS

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/UnityPlugin-AVProVideo#575]
When playback of a non-looped asset finishes, the FinishedPlaying event does not fire on iOS.
AVPro Video version 2.0.1

**Comment by MorrisRH** [comment]
The FirstFrameReady event is also not being triggered.

**Comment by AndrewRH** [comment]
Closing this as 2.0.2 has been released with this fix
