### ISSUE TITLE
Set my user agent

### ISSUE THREAD

**Issue by serversdz** [RenderHeads/UnityPlugin-AVProVideo#577]
i'd like to know if there is a way to set a useragent for my player to limit the access to a specific video
thanks in advance

**Comment by RenderHeadsSte** [comment]
What platform are you hoping to do this on?  What is your use-case?

**Comment by serversdz** [comment]
Windows and android
I have some videos on my server I want to limit access to a specific app if somebody uses the video link directly he shouldn't be able to play it unless he is using the app

**Comment by RenderHeadsSte** [comment]
Ahh, right...so 'User-Agent' HTTP header?

HTTP headers is a feature of the [AVPro Video v2 Ultra asset](https://assetstore.unity.com/packages/slug/184294?aid=1101lcNgx).  You can also trial your use-case in the trial package available [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/2.0.1)

**Comment by norbykov** [comment]
Hey, @RenderHeadsSte, so you're saying that there's the API and the UI for it in AVProVideo, but it doesn't work? A heads-up in the code or the UI would be nice but disabling it would be a proper way of letting the developers know, no? 
![image](https://user-images.githubusercontent.com/3226572/105173499-674bc780-5b21-11eb-8f8a-ad35d109b70b.png)

**Comment by MorrisRH** [comment]
That looks like version 1 of AVPro Video, limited http header support is available for Android using the ExoPlayer API.

**Comment by RenderHeadsSte** [comment]
Ahh, right, v1.x.

Yeah...you can send headers over as you can see.  I am not sure if setting it here would override the default UserAgent we sent in ExoPlayer...which is...

m_UserAgent = "AVProMobileVideo/" + version + " (Linux;Android " + Build.VERSION.RELEASE + ") " + "ExoPlayerLib/" + ExoPlayerLibraryInfo.VERSION;

Are you able to test that easily @norbykov ?

**Comment by norbykov** [comment]
Yeah, tested it, working fine. Thanks for the very quick response and apologies for snapping without testing :)

**Comment by norbykov** [comment]
Just for reference, it's working for me like this:

`string m_UserAgent = "TheUserAgent";`
`string cookieValue = "TheCookie";`
`player.PlatformOptionsAndroid.httpHeaders.Add(new MediaPlayer.PlatformOptions.HTTPHeader("Cookie",cookieValue));`
`player.PlatformOptionsAndroid.httpHeaders.Add(new MediaPlayer.PlatformOptions.HTTPHeader("User-Agent", m_UserAgent));`

**Comment by RenderHeadsSte** [comment]
That is great news.  Glad it does what you need @norbykov.  Are you the same organisation as @serversdz ?  i.e. can we close this issue now?

**Comment by norbykov** [comment]
Nope, just hijacked the issue since I was facing the same challenge, but my problem was actually an invalid cookie. Sorry about that. I hope it does help @serversdz  though.

**Comment by RenderHeadsSte** [comment]
We will be closing this issue soon.  Please let us know if the information here has solved your issue @serversdz.
