### ISSUE TITLE
avpro depricated after 7 months of purchase

### ISSUE THREAD

**Issue by serversdz** [RenderHeads/UnityPlugin-AVProVideo#578]
hello, i've just realized that avpro got deprecated after 7 months of the purchase....can I get a free upgrade?
thanks in advance

**Comment by RenderHeadsSte** [comment]
We have set a grace period of 60 days for those who recently purchased AVPro v1.x, where the equivalent v2 product will be free.

For anyone outside that grace period, we are offering reduced cost upgrade paths for all v1.x products to all v2 flavours.

Version 1.x will naturally continue to work for everyone who holds a valid license, and we will continue to offer official support the product for a period of time.
