### ISSUE TITLE
File not found, codec not supported, video resolution too high or insufficient system resources.

### ISSUE THREAD

**Issue by PedroViestel** [RenderHeads/UnityPlugin-AVProVideo#579]
I'm testing AVPRO trial to see if fits my needs, and while trying to play an m3u8, I'm getting the error: File not found, codec not supported, video resolution too high, or insufficient system resources.
VLC plays with no problem

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.18f
 - AVPro Video version: 2.01
 - Operating system version: Windows 10 64 bits
 - Device model: Asus TUF. Ryzen 7 gtx 1660TII
 - Video specs (resolution, frame-rate, codec, file size): stream m3u8

**To Reproduce**
1. Using the demo that comes with the trial just add the URL to the video player
2. Will send the URL in the unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
What Video API are you using?

Can you provide the stream URL so we can try to preproduce the issue here? (you can email it over to [mailto:unitysupport@renderheads.com](url) if you do not want to make it public.

**Comment by PedroViestel** [comment]
You can test with this url(https://tinyurl.com/y39s7fqc). I'm using the video player in the demo app
________________________________
De: Ste Butcher <notifications@github.com>
Enviado: segunda-feira, 18 de janeiro de 2021 16:57
Para: RenderHeads/UnityPlugin-AVProVideo <UnityPlugin-AVProVideo@noreply.github.com>
Cc: PedroViestel <pedroviestel@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [RenderHeads/UnityPlugin-AVProVideo] File not found, codec not supported, video resolution too high or insufficient system resources. (#579)


What Video API are you using?

Can you provide the stream URL so we can try to preproduce the issue here? (you can email it over to mailto:unitysupport@renderheads.com<url> if you do not want to make it public.

**Comment by RenderHeadsSte** [comment]
Ahh, kk, yeah.  It is because you are using a URL that redirects.  AVPro Video does not support that.  You will have to resolve the redirect feeding it into AVPro Video.  [This](https://github.com/vimeo/vimeo-unity-sdk/issues/56#issuecomment-460996498) might help you achieve that.
