### ISSUE TITLE
HAP and NLC Mov files not playing

### ISSUE THREAD

**Issue by prisonerjohn** [RenderHeads/UnityPlugin-AVProVideo#581]
**Describe the bug**
Installed the trial version in an empty project.
Tried running examples, only BigBuckBunny MP4 video plays. 
Everything else gives me the `Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`
Also tried loading my own HAP and NLC videos but getting errors.
This setup runs fine with AVPro Video 1.x.
The HEVC and HAP videos play fine in VLC.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1
 - AVPro Video version: 2.0.1-Trial
 - Operating system version: Windows 10 Pro 2004
 - Device model: Razer Blade 15" 2018
 - Video specs (resolution, frame-rate, codec, file size): Varies, but it appears that HEVC, HAP, and NotchLC are not working. MP4 is.

**To Reproduce**
1. Create a new Unity project with standard pipeline.
2. Import AVPro Video.
3. Try example `Demo_360Stereo`

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

I think these problems may be a combination of:

1) Windows 10 no longer ships with the HEVC codec built-in, and requires it to be downloaded from the Store.  It used to be free, but now they're charging 99 cents for it.  Our plugin doesn't include any built in codec support (except for Hap and NotchLC) and relied on the codecs that ship with the operating systems.  I believe this is why none of the HEVC videos play.  All of our sample videos are HEVC except for the Big Buck video which is H.264.  I think soon we will transcode all the sample videos to H.264 for better compatibility.

2) Hap and Notch videos should work, but we do currently have a bug for these videos when used inside a MOV file container (AVI is fine), where videos with a very high bitrate > 4Gbps do not load.  We have a fix for this coming out in the next version.  This is the only known issue with these formats, so without testing your files it's difficult to say if it could be something else.  If you think there is another problem then perhaps you could share one of these video files with us for testing.

Does this help answer your issue?

Thanks,

**Comment by prisonerjohn** [comment]
Thank you @AndrewRH for the prompt response.
1. Yes, that did the trick. I installed the codec and it's working now.
2. Both are pretty high bitrate so this is probably the issue. I'm not sure how to put that in a HAP container, Adobe ME keeps reverting back to `mov`. Do you have a suggestion?

**Comment by prisonerjohn** [comment]
Also, can you give me an idea of when the next version with the fixes will be released?
Thank you

**Comment by RenderHeadsSte** [comment]
> Also, can you give me an idea of when the next version with the fixes will be released?
> Thank you

We are aiming to release v2.0.2 either tomorrow or early next week.

**Comment by RenderHeadsSte** [comment]
> 2. Both are pretty high bitrate so this is probably the issue. I'm not sure how to put that in an `avi` container, Adobe ME keeps reverting back to `mov`. Do you have a suggestion?

ffmpeg is your friend I would think here.  You could try changing just the container with something like:

ffmpeg -i movie.mov -acodec copy -vcodec copy movie.avi

Not knowing the specifics of the encoding of your video(s) makes it a little hard to comment further.  Though with ffmpeg you can also re-encode as well as change the container type, if required.

**Comment by AndrewRH** [comment]
> Also, can you give me an idea of when the next version with the fixes will be released?
> Thank you

2.0.2 was released today, but unfortunately the MOV fix is not quite ready yet.  It will likely be out in the next 2-3 weeks.

Thanks,

**Comment by prisonerjohn** [comment]
Ok, getting closer. I switched to an AVI container using the ffmpeg commands above and now both the HAPQ and NotchLC videos play. 

However, the NotchLC video looks like it inverted the R and B channels. Is that something I need to set in the player, in the encoding, or is it a bug?

![image](https://user-images.githubusercontent.com/119702/105752970-f556f200-5f15-11eb-8306-477d2d9a274d.png)

**Comment by AndrewRH** [comment]
@prisonerjohn  how are you generating that NotchLC video?  
The swapped R/B channels is strange...I'm investigating that.
Also expect the Hap and NotchLC MOV support to appear around 2.1 of the plugin - we're working on it.

**Comment by prisonerjohn** [comment]
I used the Adobe Media Encoder plugin on Windows to generate an mov, then
ffmpeg to make the avi but I just used `copy` for the video codec.

I don't have another notchlc player so I can't really tell if the issue is
in the file or AVPro...

~
Elie

**Comment by AndrewRH** [comment]
@prisonerjohn  ok thanks for the information.  Well we're about to make an update in the next major version for NotchLC support so we will be looking into this and hopefully have it resolved in that version.

**Comment by AndrewRH** [comment]
@prisonerjohn the flipped red-blue channel bug has been fixed in version 2.0.5 which was just released.

Thanks,

**Comment by prisonerjohn** [comment]
Great thanks, I will take a look.

--
Elie Zananiri
@prisonerjohn

**Comment by AndrewRH** [comment]
This issue should now be solved in 2.0.9 - please let us know if you have any issues.

You need to enable the new option "Use Custom MOV Parser" in Windows Specific > Windows section.

Thanks,
