### ISSUE TITLE
AndroidMediaPlayer with ComputeShader not working

### ISSUE THREAD

**Issue by Andjiang707** [RenderHeads/UnityPlugin-AVProVideo#582]
Problem description:

Hello, my ongoing project must use ComputeShader to reorganize the movie. 
My ComputeShader can be executed smoothly on WindowsMediaPlayer, 
but it does not work on Android.

Device (which devices are you having the issue with - model, OS version number):

 Android  (Check require Quest2 OpenGLES3.1 3.2)

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

7680*4320，10000kbps，50fps，MP4

System Information:

AVPro Video: plugin v1.9.17 scripts v1.10.0
Target Platform: Android
Unity: v2019.4.9f1 WindowsEditor
OS: Desktop - To Be Filled By O.E.M. (To Be Filled By O.E.M.) - Windows 10  (10.0.0) 64bit - ChineseTraditional
CPU: AMD Ryzen 9 3900XT 12-Core Processor  - 24 threads - 65464KB
GPU: NVIDIA GeForce RTX 2080 SUPER - NVIDIA - Direct3D 11.0 [level 11.1] - 8010KB - 16384

WindowsMediaPlayer :
![image](https://user-images.githubusercontent.com/29428186/105328609-2fb94a00-5c0b-11eb-8021-e72a09468ce4.png)

AndroidMediaPlayer :
![image](https://user-images.githubusercontent.com/29428186/105328768-5bd4cb00-5c0b-11eb-95d4-0ab9deb3f7ae.png)

ComputeShader :
![image](https://user-images.githubusercontent.com/29428186/105328946-8d4d9680-5c0b-11eb-802b-366e9f6430bb.png)

**Comment by AndrewRH** [comment]
Hi,

I'm not sure why the compute shader isn't working (is there any error message clues in the Android adb log cat logs?), but for simplicity and better performance you're probably better off creating a mesh and using the texture coordinates to do the sort of remapping you're trying to do in this shader.  I'll run a ton faster and won't require any extra memory.

Thanks,

**Comment by Andjiang707** [comment]
Thanks for the reply, but I tried for a whole day today and I have not solved this problem. (Reproduced the UV map on Maya)
I need to remap a top-bottom VR video (refer to the attached image file). 
It seems that there is no way to solve this problem?

![videodevout1_flive](https://user-images.githubusercontent.com/29428186/105830934-15171480-6001-11eb-8a9a-6cccac923a48.png)

thanks. ^^

**Comment by AndrewRH** [comment]
There is a shader included called "AVProVideo-VR-InsideSphere-StereoUV" it will use the custom UV sets in your mesh for mapping to your geometry.  It works with 2 uv sets - one for each eye.

What is this layout that you have here - is it something standard that we should perhaps include native support for in the future?

I hope that helps.
