### ISSUE TITLE
MacOS - [AVProVideo] Failed to load key 'playable', error: You do not have permission to access the requested resource.

### ISSUE THREAD

**Issue by dean-ivre** [RenderHeads/UnityPlugin-AVProVideo#583]
**When I play a video via url I get the error -  **[AVProVideo] Failed to load key 'playable', error: You do not have permission to access the requested resource.** **

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.2f1
 - AVPro Video version: 2.0
 - Operating system version: macOS Catalina
 - Device model: MacBook Pro
 - Video specs (resolution, frame-rate, codec, file size): 

AV PRO LINK:
videoplayback?expire=1611245686&ei=FlQJYIiZM835sAK814CwBQ&ip=52.49.189.9&id=o-ACb_9eUgn5BC7pnIZkjopkSGxg0mLCCaH9pT-FHllJmh&itag=22&source=youtube&requiressl=yes&mh=V4&mm=31%2C26&mn=sn-1gieen7e%2Csn-q0c7rn76&ms=au%2Conr&mv=u&mvi=5&pl=24&vprv=1&mime=video%2Fmp4&ns=sGvWfQsOOchTCyO6omdhU_AF&ratebypass=yes&dur=160.519&lmt=1610524347322953&mt=1611223687&fvip=5&beids=23886207&c=WEB&txp=5532434&n=6lM3yX83FgKTkp&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgXO1i_SL2caYUtf-DxJLbd3rOafXTn070BTQav9xnZ7kCIQD0y1z6GMUZRQfvVwuCHsxWyWJgFfOIRxRVyPY8Na_t7g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRAIgAjejWBF0Jln4IOUU5mkN1V5leDnBrA5FfWaZZ3W3-b8CID0zR1GJweBc-y9AYnJKmGmqGT7KTU9kIve2PjpSNYNm

**To Reproduce**
1. 
2. 
3. 

**Logs**
[AVProVideo] Failed to load key 'playable', error: You do not have permission to access the requested resource.

**Videos**
https://www.youtube.com/watch?v=4b1GOsoLb7Q

**Comment by MorrisRH** [comment]
Playing back URLs from YouTube is a breach of their Terms of Service (available [here](https://www.youtube.com/static?template=terms)), however I can confirm that it does work and whatever mechanism you used to get the URL is the root cause of this issue.

**Comment by dean-ivre** [comment]
No Problem I will stop doing that
