### ISSUE TITLE
HEVC MKV not playing on Surface Pro 2017

### ISSUE THREAD

**Issue by serversdz** [RenderHeads/UnityPlugin-AVProVideo#585]
hello
i m getting this error when i try to play some video files....they work perfectly on vlc though

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:2113)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1412)

**Comment by RenderHeadsSte** [comment]
Can you please provide more information (as outlined when you create an issue).

**Comment by serversdz** [comment]
Thanks...the issue got solved after purchasing the HEVC codec

**Comment by serversdz** [comment]
still, it works on one machine but not on a second low-end laptop "surface pro-2017"

**Comment by RenderHeadsSte** [comment]
> still, it works on one machine but not on a second low-end laptop "surface pro-2017"

Again, we will require more information in order to offer support.

**Comment by serversdz** [comment]
unity version: 2020.2.2.1
avpro version: 1.x
device: surface pro 2017



this error occurs with some videos and not all of them....mostly MKV

[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high, or insufficient system resources.
UnityEngine.Debug:LogError (object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:2113)
RenderHeads.Media.AVProVideo.MediaPlayer:Update () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1412)

**Comment by serversdz** [comment]
i 've made a video that recreates the bug
https://youtu.be/ysVKC5rc78I

**Comment by RenderHeadsSte** [comment]
Is there a common theme to the encoding of the videos that do not work?  If you are unsure, are you able to send some over so I can check them?  If you do not want to make them public, you can send them to [unitysupport@renderheads.com](unitysupport@renderheads.com)

**Comment by serversdz** [comment]
errors occur mainly with mkv files
some of the videos freeze and others don't play at all ...like the following one
Version 1.11.7 - November 14, 2020
https://serversdz.com/S01E00%20-%20Chariots,%20Gods%20and%20Beyond.mkv

**Comment by RenderHeadsSte** [comment]
This is the output from ffprobe on that video.  You will see it is 10bit.  My hunch is that is the issue with playback on the Surface Pro 2017 device.  I wonder f you could check other videos that do not play to see if that is a theme?

![image](https://user-images.githubusercontent.com/46531149/105987356-16465100-6096-11eb-9c68-dffe8413d0a0.png)

**Comment by serversdz** [comment]
the episode that won't play are mainly from the same series
this is another episode
https://serversdz.com/S01E02%20-%20The%20Visitors.mkv

as for the videos that break up so often, here is one of them:
https://serversdz.com/The.Twilight.Zone.S02E06.Eye.Of.The.Beholder.mkv

**Comment by RenderHeadsSte** [comment]
A few questions:

1) Do other HEVC (none 10bit) videos play back on the Surface Pro 2017 device? (Maybe try some of the sample videos found [here](https://jell.yfish.us/))

2) Does 'S01E02 - The Visitors.mkv' play back in the default Windows media/video player on the Surface device? (NOT VLC or any third party player)

3) Is the Microsoft HEVC codec installed on the Surface device, and is it installed for the user you are logged in as?

Not sure what is going on with 'The.Twilight.Zone.S02E06.Eye.Of.The.Beholder.mkv'...could you send over a video demonstrating what you mean by 'break up so often' ?  Is that just on the Surface device, or on other PCs as well?

**Comment by AndrewRH** [comment]
@serversdz 
You can check to see whether the HEVC codec is installed via:
![image](https://user-images.githubusercontent.com/5418126/106779312-c7249100-663e-11eb-8bdb-39ae390dc816.png)

**Comment by serversdz** [comment]
yeah, but I am getting two hevc video extensions. Is that normal?
https://serversdz.com/errors/error6.PNG
the main pc does not have any problem neither with the hevc files, or the other mkv everything is smooth
as for the surface pro ..what I meant is that the videos freeze so often, sometimes they slow down or stop playing.
I'm talking about mkv videos.

**Comment by RenderHeadsSte** [comment]
@serversdz Can you post screen grabs of the versions of both HEVC extensions you have installed please?

Also, what version of Windows are you running? (run 'winver')

**Comment by RenderHeadsSte** [comment]
Possibly the same as issue as #622

**Comment by AndrewRH** [comment]
@serversdz  did you have any luck finally?

Otherwise I have a few more questions which will help us solve this issue:

1) Could you click on those extensions and go to "Advanced options" and see which versions are installed?    The latest version is 1.0.40203, so if the machine is not on that perhaps you could try upgrading it?
2) Could you try upgrading GPU drivers on that device?
3) Could you do all tests with the "Cones-360Stereo-2K30-HEVC.mp4" sample video because that way we can also test on that media.

We have someone else reporting what seems to be the same issue....they're also having HEVC issues on some machine - there seems to be some sort of machine/os/driver combination that has this conflict and so we're trying to work out what it is.  We haven't been able to replicate this issue on any of our machines yet.

Thanks,
