### ISSUE TITLE
"The type or namespace name 'VR' does not exist" error on package importing

### ISSUE THREAD

**Issue by serversdz** [RenderHeads/UnityPlugin-AVProVideo#587]
**Describe the bug**
when i install the asset i get these errors
Assets\AVProVideo\Demos\Scripts\SphereDemo.cs(102,6): error CS0234: The type or namespace name 'VR' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets\AVProVideo\Demos\Scripts\SphereDemo.cs(102,43): error CS0234: The type or namespace name 'VR' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
**Your Setup (please complete the following information):**
 - Unity version:  2020.2.2f1
 - AVPro Video version: 1.x
 - Operating system version: windows 10
 - Device model: Microsoft surface pro

**Comment by AndrewRH** [comment]
Yes, the VR namespace is from previous versions of Unity.  They changed it from VR or XR at some point.

It seems like Unity has not run it's automatic upgrade script process.  When you imported the package it may have asked you if you wanted to upgrade the scripts - make sure to select 'yes'.  Perhaps try import the package again?

If that doesn't work, you can change the VR to XR in that script.

Does this help?

Thanks,

**Comment by RenderHeadsSte** [comment]
@serversdz Do you require further assistance with this issue?

**Comment by ul3d** [comment]
> Yes, the VR namespace is from previous versions of Unity. They changed it from VR or XR at some point.
> 
> It seems like Unity has not run it's automatic upgrade script process. When you imported the package it may have asked you if you wanted to upgrade the scripts - make sure to select 'yes'. Perhaps try import the package again?
> 
> If that doesn't work, you can change the VR to XR in that script.
> 
> Does this help?
> 
> Thanks,
