### ISSUE TITLE
AVPro video error on Android, not rendering video

### ISSUE THREAD

**Issue by jerrykingGH** [RenderHeads/UnityPlugin-AVProVideo#588]
I used AVPro  in Android.When the program is running, it doesn't show the Video .Only the sound can be heard.
And ,it works fine with Unity Editor.
Please can you provide me with some instructions on how to deal with this issue.Thank you.

Unity version: 2019.4.8f1
AVPro Video version: 2.0.1
Operating system version: Android 9.0.0
Device model: Redmi Note 7 pro

**Comment by jerrykingGH** [comment]
The MediaPathType is :MediaPathType.RelativeToStreamingAssetsFolder

**Comment by withstand007** [comment]
Hi, Even I was getting this issue when today I was trying the trial plugin. Please try selecting the Auto Graphics API from PlayerSettings. That fixed this issue for me in Android device.

**Comment by RenderHeadsSte** [comment]
@jerrykingGH I would need a dump of your logcat output to help investigate why you are seeing this issue.  What @withstand007 says is always a good thing to check.   AVPro Video only supports OpenlGLES2 and OpenGLES3 on Android, not Vulkan.

**Comment by jerrykingGH** [comment]
> Hi, Even I was getting this issue when today I was trying the trial plugin. Please try selecting the Auto Graphics API from PlayerSettings. That fixed this issue for me in Android device.

It works!Thank you for your help, I really appreciate it.Thank you！

**Comment by jerrykingGH** [comment]
> @jerrykingGH I would need a dump of your logcat output to help investigate why you are seeing this issue. What @withstand007 says is always a good thing to check. AVPro Video only supports OpenlGLES2 and OpenGLES3 on Android, not Vulkan.

Thank you as well！

**Comment by fareedTahir131** [comment]
> Hi, Even I was getting this issue when today I was trying the trial plugin. Please try selecting the Auto Graphics API from PlayerSettings. That fixed this issue for me in Android device.

I have the same issue but with the audio, After selecting Auto Graphics API from PlayerSettings, It also works for me.
thanks a lot.
