### ISSUE TITLE
Media does not playback in Windows 7

### ISSUE THREAD

**Issue by RenderHeadsSte** [RenderHeads/UnityPlugin-AVProVideo#589]
[From keeping #qhald4K5dT]

The trial version isn’t working on Windows 7 (it’s playing fine on other platforms).

The log shows the following message:

Fallback handler could not load library G:/v040/ v040_Data/Mono/libAVProVideo
[AVProVideo] Failed to load DLL. AVProVideo

[AVProVideo] Not supported on this platform WindowsPlayer MS-7693 (MSI) AMD FX(tm)-8120 Eight-Core Processor  Windows 7  (6.1.0) 64bit.  Using null media player!

**Comment by RenderHeadsSte** [comment]
Potential fix will be to remove the following DLL dependency from the Windows plugin:

![image](https://user-images.githubusercontent.com/46531149/105715009-f9364480-5f14-11eb-89d4-3ab2a28cb57f.png)

We will look to do this for the v2.0.3 release

**Comment by AndrewRH** [comment]
@RenderHeadsSte  this issue should be resolved now, I am closing it.
