### ISSUE TITLE
LL HLS not working

### ISSUE THREAD

**Issue by Twyker** [RenderHeads/UnityPlugin-AVProVideo#590]
Hi!

HLS seems to be working fine in Windows and WebGL via the external library.
As the latency in WebGL is rather high though, we wanted to try use LL HLS, but it seems it's probably not supported?

I'm getting the standard loading error when going for LL HLS:
_[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources._

Is there any support for LL HLS planned if it is indeed not currently supported? Or any other formats we could use in WebGL aside from DASH and HLS? Or any other tips how to lower the latency?

Thanks.

**Comment by RenderHeadsSte** [comment]
What version of AVPro Video are you using?

**Comment by Twyker** [comment]
According to WebGLMediaPlayer that should be "1.9.17" ?

Also:
I just realized that has been replaced by a new windows core version in the asset store, do we get an automatic update to this package or how do I go about get the older package now? Does the new core version also support WebGL? Didn't see that in the description.

**Comment by RenderHeadsSte** [comment]
We have indeed deprecated AVPro Video v1 recently and v2 is now available to developers.  You should be able to update to the latest version of v1 (which is v1.11.7) through the unity store still.

There is a 60 day grace period for anyone who purchased AVPro Video v1 within 60 days proceeding the release of v2.  Anyone v1 license holder who purchased outside that window is currently being offered a discount on purchasing version 2 (see [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#owners-of-avpro-video-1x)).

For details on WebGL support in version 2, see [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-webgl.html).

**Comment by RenderHeadsSte** [comment]
I am not aware of any other developers using LL-HLS.  On WebGL I would suspect there would need to be support from HLS.js - which appears WIP ([https://github.com/video-dev/hls.js/projects/7](https://github.com/video-dev/hls.js/projects/7) ?

**Comment by Twyker** [comment]
Ah, thanks for clearing that up!
Do you know how long that discount will last? 
To be honest I don't really see any current need to update otherwise, as the older version seems to be working fine and we are only using it for WebGL. So my guess would be it wouldn't help with the latency and I should probably just wait for LL HLS support on the HLS.js side?

**Comment by RenderHeadsSte** [comment]
Sorry, bad choice of words on my part.  We do not intend to revoke the discount upgrade path for v1 license holders, but the discounts may be reduced in time as we add more features to v2.

Sounds to me like there is no reason for you to upgrade at this time.  v1 will, naturally,  continue to work for you as it is now.  It must be said that we will eventually withdraw support for v1 of the asset.  Also you will not benefit from the common feature additions/improvements we have brought, and continue to add, to v2.
