### ISSUE TITLE
AVPro Video: Adding AVPRO_PACKAGE_TIMELINE to player defines results in errors

### ISSUE THREAD

**Issue by mjmvisser** [RenderHeads/UnityPlugin-AVProVideo#591]
**Describe the bug**
Timeline integration in https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/2.0.2 has compile errors.

I added this define "AVPRO_PACKAGE_TIMELINE" as described by the docs: https://www.renderheads.com/content/docs/AVProVideo/articles/component-timeline-playables.html
Also note that this page is a duplicate of the previous page (VFX graph), which seems to also be a bug.

The Timeline-specific code generates this compile error:

```
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlAsset.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlBehaviour.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlMixerBehaviour.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(8,19): error CS0234: The type or namespace name 'Timeline' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(19,41): error CS0246: The type or namespace name 'TrackAsset' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(17,3): error CS0246: The type or namespace name 'TrackClipTypeAttribute' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(17,3): error CS0246: The type or namespace name 'TrackClipType' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(18,3): error CS0246: The type or namespace name 'TrackBindingTypeAttribute' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(18,3): error CS0246: The type or namespace name 'TrackBindingType' could not be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlTrack.cs(21,28): error CS0115: 'MediaPlayerControlTrack.CreateTrackMixer(PlayableGraph, GameObject, int)': no suitable method found to override
```

Same result in both 2020.2 and 2019.4. If I manually add Timeline and Timeline.Editor to
_AVProVideo.Extensions.TImeline.asmdef, those errors disappear and are replaced with these:
```Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlBehaviour.cs(29,71): error CS1061: 'MediaPlayer' does not contain a definition for 'VideoPath' and no accessible extension method 'VideoPath' accepting a first argument of type 'MediaPlayer' could be found (are you missing a using directive or an assembly reference?)
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlBehaviour.cs(31,37): error CS0103: The name 'MediaLocation' does not exist in the current context
Assets/AVProVideo/Extensions/Timeline/MediaPlayerControlBehaviour.cs(31,19): error CS1061: 'MediaPlayer' does not contain a definition for 'OpenVideoFromFile' and no accessible extension method 'OpenVideoFromFile' accepting a first argument of type 'MediaPlayer' could be found (are you missing a using directive or an assembly reference?)
```

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.17f1 and 2020.2.1f1
 - AVPro Video version: 2.0.2 trial
 - Operating system version: Mac OS Catalina 10.15.7
 - Device model: MacBook Pro 2019
 - Video specs (resolution, frame-rate, codec, file size): n/a

**To Reproduce**
1. Install AVPro Video
2. Add AVPRO_PACKAGE_TIMELINE to player defines
3. Add Unity.Timeline and Unity.Timeline.Editor to Assembly Definition References in _AVProVideo.Extensions.TImeline.asmdef

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Thanks for reporting this.  It looks like this extension got left behind during the last days of the 2.0.0 launch and so missed some of the API updates.  We will fix those and release them in the next update.  For now I have attached the fixed file here for you to try.

[MediaPlayerControlBehaviour.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5870092/MediaPlayerControlBehaviour.zip)

As for the documentation - yes we will also get that fixed, thanks for bringing it to our attention.

**Comment by AndrewRH** [comment]
@mjmvisser 

I've updated the scripts again to fix a few more issues.  This will be in version 2.0.3

Thanks,

[Timeline.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/5876932/Timeline.zip)

**Comment by AndrewRH** [comment]
@mjmvisser 2.0.3 has been released and the issue should be resolved in that package.  I will close this issue now.
