### ISSUE TITLE
ExtractFrame is returning null, events fired are in a wrong order (Android 10/11)

### ISSUE THREAD

**Issue by cyliax** [RenderHeads/UnityPlugin-AVProVideo#592]
**Describe the bug**
I try to figure out the why ExtractFrame (tried Async as well) is returning null. I tried different ways to get the texture from a specific time and everything works well in a Windows 10 Unity Editor. But when I log the events fired on an Android device, it looks different and it is not working. I have no idea why there is no MetaDataReady and seeking started before video started. What would be the optimal order of events to wait for to get a thumbnail from a specific time? I'm confused.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.13f1
 - AVPro Video version: 2.0.2
 - Operating system version: Windows, Android 10, 11
 - Device model: Huawei P20 Pro, Google Pixel 3a
 - Video specs (resolution, frame-rate, codec, file size): 1024x576, 25, H264 - MPEG-4 AVC (part 10) (avc1), 1090kb

**To Reproduce**
1. Open media from an AbsolutePathOrURL with autoplay (or without)
2. Wait for Started event to seek to position
3. Wait for FinishedSeeking to extract frame (sync or async)
4. Texure returned is null

**Logs**
Log on a Windows PC Unity Editor:
```
StartedBuffering
MetaDataReady
ResolutionChanged
FinishedBuffering
Started
FirstFrameReady
StartedSeeking
FinishedSeeking
frameTexture2D  (UnityEngine.Texture2D)
```

Log on a Android device (Google Pixel 3a, same script):
```
StartedSeeking
StartedBuffering
Started
FinishedSeeking
frameTexture2D null
```

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
I am looking to reproduce this but am interested in how you are getting the FinishedSeeking event fired on Android.  I was made aware this morning that there is a bug around this event firing, and indeed I am not seeing it fire here in my testing.  I am using the ExoPlayer API path.  Can you confirm you are also using ExoPlayer?  Would it be possible to send me your logcat output and your test c# script? (so I am looking at the same event sequence as you are).  You can email it over to [unitysupport@renderheads.com](unitysupport@renderheads.com) if you wish to keep it private.

**Comment by RenderHeadsSte** [comment]
The FinishedSeeking issue has been added: #594

It was also found there was an issue with supporting these events when using the MediaPlayer API path: #595

**Comment by AndrewRH** [comment]
@cyliax  do let us know if 2.0.3 (released now) solves this issue. Thanks,
