### ISSUE TITLE
Audio Output to Unity doesn't work on Windows in 2.0.2 / 2.0.3 / 2.0.4 

### ISSUE THREAD

**Issue by pmb1701** [RenderHeads/UnityPlugin-AVProVideo#593]
**Describe the bug**
Audio no longer gets routed to a Unity Audio Source when adding an Audio Output component and setting the Media Player's Audio Output option to "Unity" in AVPro Video 2.0.2.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1
 - AVPro Video version: 2.0.2
 - Operating system version: Windows 10 (have not tested on other platforms)

**To Reproduce**
1. Import AVPro Video to empty Unity project
2. Open Demo_DisplayComponents scene, add Audio Output component to MediaPlayer gameobject, set the Media Player Field in the output component, set the Audio Output option in Media Player to Unity. Set Media Reference to the BigBuck video and enter Play mode in Unity.
3. Note that the volume levels shown by the Audio Output component remain at zero and that you can disable that and the Audio Source component and still hear the sound. Also, setting Spatial Blend on the Audio Source to full 3D and moving the audio source around relative to the Audio Listener has no effect on the sound.

**Comment by AndrewRH** [comment]
@pmb1701 are you using the trial, core or ultra edition?

It is not a core feature, so it will only be available in trial and ultra editions.

Thanks,

**Comment by AndrewRH** [comment]
Hi @pmb1701 Oops, that's a mistake - it seems that feature was removed by mistake in 2.0.2 (it was there in 2.0.0 and 2.0.1).  We will add it back in for the next update (soon).

It should work fine on other platforms, it was only on Windows that it was accidentally removed.

Thanks,

**Comment by pmb1701** [comment]
Yes, we are using Core edition, and indeed it was still working in Core Edition 2.0.1, it only broke when we updated to 2.0.2. Looking forward to the update as this is an essential feature for us!

**Comment by pmb1701** [comment]
Hi @AndrewRH 
Are you able to give an estimate on when 2.0.3 will be released?

**Comment by AndrewRH** [comment]
I think it will be released on Monday

**Comment by AndrewRH** [comment]
@pmb1701 do let us know if 2.0.3 (released now) solves this issue.  Thanks,

**Comment by pmb1701** [comment]
Sadly, it did not. Audio is still not getting routed to the Audio Output component. I verified this by reproducing using your own sample scene in the same way as in my original post.

In addition, every video on Quest now fires an Error MediaPlayerEvent in our application, which did not happen using 2.0.2.

**Comment by RenderHeadsSte** [comment]
The Quest issue you mention.  If this on a Quest 1 headset?  Where are you loading videos from?

**Comment by pmb1701** [comment]
Yes, Quest 1. Our videos come from our S3 bucket (you previously fixed an issue on Mac related to handling of our URI's). I'll do further testing and open a new issue on this once I have more information gathered.

**Comment by AndrewRH** [comment]
> Sadly, it did not. Audio is still not getting routed to the Audio Output component. I verified this by reproducing using your own sample scene in the same way as in my original post.

Hmm that's strange.  Could you give more details - like which platform is this on?  I'm testing here on Windows and it's certainly working with 2.0.3.  The MediaPlayerUI demo scene should be set up to play audio through Unity by default - and in the MediaPlayer UI you should see a little spectrum meter showing the audio waveform.

**Comment by pmb1701** [comment]
On Windows. The spectrum meter stays a flat line in the MediaPlayer demo. I'll see if importing into an empty project instead of overwriting the previous version makes a difference, just to be sure.

**Comment by pmb1701** [comment]
I imported the 2.0.3 Core Edition unitypackage into an empty project. Same result - audio is not routed through Audio Output component and the spectrum meter remains a flat line.

**Comment by pmb1701** [comment]
I have now tested also with v2.0.4 Core Edition. Works on Android, as it did before,, but still no audio routing to Audio Output component on Windows. Tested using the MediaPlayer demo and spectrum meter stays flat. Also, we don't get 3D positional audio in our application on Windows, but do on Quest.

This is now our last remaining obstacle with AVPro Video for our next release - any chance this could get looked at asap?

**Comment by RenderHeadsSte** [comment]
@pmb1701 What graphics API are you using?  (MediaFoundation | WinRT | DirectShow )

**Comment by pmb1701** [comment]
We're using Media Foundation, just like the MediaPlayer demo.

**Comment by RenderHeadsSte** [comment]
Not that then!

Are you able to try is on another PC?  Is there anything in the console/log that might suggest an issue? (send over if you can)

**Comment by pmb1701** [comment]
Here's the entire log from running a build of the MediaPlayer demo:

> Mono path[0] = 'E:/AVProTest/_Build/AVProTest_Data/Managed'
> Mono config path = 'E:/AVProTest/_Build/MonoBleedingEdge/etc'
> Initialize engine version: 2020.2.1f1 (270dd8c3da1c)
> [Subsystems] Discovering subsystems at path E:/AVProTest/_Build/AVProTest_Data/UnitySubsystems
> GfxDevice: creating device client; threaded=1
> Direct3D:
>     Version:  Direct3D 11.0 [level 11.1]
>     Renderer: NVIDIA GeForce GTX 1080 (ID=0x1b80)
>     Vendor:   
>     VRAM:     8079 MB
>     Driver:   27.21.14.5671
> Begin MonoManager ReloadAssembly
> - Completed reload, in  1.203 seconds
> D3D11 device created for Microsoft Media Foundation video decoding.
> <RI> Initializing input.
> 
> <RI> Input initialized.
> 
> <RI> Initialized touch support.
> 
> UnloadTime: 0.756700 ms
> [AVProVideo] Initialising AVPro Video v2.0.4 (native plugin v2.0.3f1-core) on NVIDIA GeForce GTX 1080/Direct3D 11.0 [level 11.1] (MT True) on WindowsPlayer
> 
> [AVProVideo] Opening E:/AVProTest/_Build/AVProTest_Data/StreamingAssets\AVProVideoSamples/RenderHeads-1080p30-H264.mp4 (offset 0) with API MediaFoundation
> 
> Setting up 4 worker threads for Enlighten.
>   Thread -> id: 75e4 -> priority: 1 
>   Thread -> id: 6dc4 -> priority: 1 
>   Thread -> id: 6fd4 -> priority: 1 
>   Thread -> id: a160 -> priority: 1 
> [AVProVideo] Using playback path: MF-MediaEngine-Hardware (1920x1080@30.00)
> 
> [AVProVideo] Shutdown
> 
> 

I'll run it on a different PC and report back.

**Comment by pmb1701** [comment]
I get the same result on a different PC.

**Comment by RenderHeadsSte** [comment]
Do you get audio output if you set to output to 'System Direct' ?

**Comment by pmb1701** [comment]
I do, there's no audible or visible difference in audio output between that or any of the other options. I also tried with and without "Hardware Decoding", "Use Low Latency", and "Use Resampler". None of the options make a difference.

**Comment by RenderHeadsSte** [comment]
Just to clarify...do you get audio output from speaker/headphones when you set 'Unity' as the 'Audio Output' option?

**Comment by pmb1701** [comment]
Yes, exactly the same audio as when set to "System Direct".

**Comment by pmb1701** [comment]
mediaPlayer.Control.GetAudioChannelCount() in RequestAudio seems to return zero, so it just returns.

**Comment by RenderHeadsSte** [comment]
Interesting...something for us to go on there.

What happens if you force the return value from GetAudioChannelCount() to 2?

**Comment by pmb1701** [comment]
Doesn't make a difference, I'll look further

**Comment by pmb1701** [comment]
Correction, GetAudioChannelCount() actually returns -1

**Comment by pmb1701** [comment]
It's just not getting any PCM data. GrabAudio returns 0 as the number of audio samples.

**Comment by AndrewRH** [comment]
@pmb1701  hmmm that's strange...

Could you try looking at your audio device settings and see what they are set to for sample rate and channel count?  Eg:
![image](https://user-images.githubusercontent.com/5418126/106777737-271a3800-663d-11eb-8b67-4a1b6147e89e.png)

And also have a look at the Enhancements tab and see how that is set:
![image](https://user-images.githubusercontent.com/5418126/106777793-36998100-663d-11eb-80a8-37aa1184e500.png)

Finally check Unity's audio settings to see whether anything odd has been set there:
![image](https://user-images.githubusercontent.com/5418126/106777874-4b761480-663d-11eb-9b19-7ef662f41a5a.png)

Thanks,

**Comment by pmb1701** [comment]
24 bit, 48000 Hz, no enhancements, Unity's audio settings are the same defaults as in your screenshot. The only differences are that under DSP buffer Size, mine says "the requested buffer size (default) has been overridden to 1024 by the operating system", and your screenshot is missing the dropdown for "Ambisonic Decoder Plugin", which to my knowledge has been there since Unity 2017.1...

**Comment by AndrewRH** [comment]
I'm running out of ideas here... Perhaps you could send us your build of the MediaPlayer demo scene so we can run it here and see how it behaves?  (email to unitysupport@renderheads.com)

Thanks,

**Comment by RenderHeadsSte** [comment]
Maybe also...you could start a fresh project and import v2.0.1 then test again...so we can make absolutely sure it is a change in version between v2.0.1 and v2.0.2 and not something odd that happened externally to the asset?

**Comment by pmb1701** [comment]
Ok, I made a build using 2.0.4, then imported the 2.0.1 package again and made a build of that. 2.0.1 shows the spectrum meter while 2.0.4 does not. I'll send both builds by email.

**Comment by RenderHeadsSte** [comment]
Cool, thanks.

I believe we have found and fixed the issue.  It will be landing with v2.0.5 today.

**Comment by pmb1701** [comment]
I can confirm this is now fixed in v2.0.5. Thank you!

**Comment by ngz82** [comment]
@RenderHeadsSte I'm having the same issue with iOS and Mac OSX , audio output set to Unity but it is not respecting the audio source and audio output components. It behaves the same as System Direct, it's as though it's simply not working.
Everything is working as expected on Android and Windows (positional audio).
The content is streamed audio  (HLS on demand audio only content and HLS live stream audio only) - all working fine in editor and Android , just not on Mac editor (both Mac and iOS platform targed) or iPhone builds.
Happy to make a new ticket just wondering if this is a known issue.

**Comment by ngz82** [comment]
I have lodged ticket here with more info/findings - thanks. https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1086
