### ISSUE TITLE
StartedSeeking and FinishedSeeking events do not fire when using the MediaPlayer API path on Android

### ISSUE THREAD

**Issue by RenderHeadsSte** [RenderHeads/UnityPlugin-AVProVideo#595]
As title

**Comment by RenderHeadsSte** [comment]
'Is Seeking' flag now set correctly at native plugin level.

This fix will be in v2.0.3

**Comment by cyliax** [comment]
Great, can't wait to get this fixed version. Cheers for your fast support.
