### ISSUE TITLE
Upgrade to AVProVideo 2.0 throws invalid binary when uploaded to TestFlight

### ISSUE THREAD

**Issue by dalkia** [RenderHeads/UnityPlugin-AVProVideo#597]
**Describe the bug**
Hello!

I upgraded a project from AVPro 1 to AVPro 2.0, built it to iOS succesfully and uploaded to Testflight. Once the ipa finishes processing, I get an invlidad binary error. 
![image](https://user-images.githubusercontent.com/1999557/105912110-bc984500-6009-11eb-8ceb-ef9144c19543.png)

Nothing has changed in the project but the upgrade to AVPro 2, and I didnt have this error when using AVPro 1. Maybe Im missing some import regarding the Unity assets? Or maybe I should change something in the path for the XCode build?

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.14
 - AVPro Video version: 2.0.1
 - Operating system version: Developed in Windows, Built in Unity Cloud, Deployed to App Store
 - Device model: iOS

**To Reproduce**
1.  Build Project
2. Upload to TestFlight

Thanks for the help!

**Comment by AndrewRH** [comment]
@dalkia  could you try upgrading to AVPro Video 2.0.2 and see if that helps?  I think we may have fixed that issue in that release.

Thanks,

**Comment by MorrisRH** [comment]
You need to make sure AVProVideo.framework is set to "Embed & Sign" in the Unity-iPhone target of your project.
Version 2.0.2 improved our PostProcessBuild_iOS script to handle the case where the plugin installation has been relocated.

**Comment by dalkia** [comment]
Hello! 

So, some update on this problem. 

I ve updated to AVPro 2.0.2; and send to build. 

Im trying to build using Unity Cloud, so the Embed & Sign option is no good for me; since I dont have access to the XCode console. Checking the log at the Unity Cloud side, I see the following error:

 [Unity] ERROR: Failed to find 'AVProVideo.framework' for 'iOS' in the Unity project. Something is horribly wrong, please reinstall AVPro Video.

Checking out the PostProcessBuild_iOS script, I ve found out the path may be incorrect; mainly because Im not completely sure where the files are dropped in UnityCloud. Im going to play around with it, and see if I can get somewhere. Maybe you can help me here?

If I fail here, I will proceed to use a Mac and build using XCode. But given out current CI pipeline, it would be the best to find a solution using Unity Cloud.

Thanks for your help!

**Comment by MorrisRH** [comment]
The motivation for improving the PostProcessBuild_iOS script was due to cloud build failing for another user so I can confirm that AVPro Video does work with Unity Cloud Build.

From the error I can tell that either AVProVideo.framework does not exists as part of your project or the location of the framework has been changed such that the script cannot find it. The script does rely on the layout of the AVProVideo plugin folder hierarchy not being changed (although you can relocate it), so if for instance you copied the AVProVideo.framework to another location the script would fail to find it and therefore fail to apply the "Embed & Sign" setting.

**Comment by dalkia** [comment]
Okay, little bit of progress, but still not there.

As suggested, I reorder the Hierarchy, since I had the AVProVideo inside another folder for project organization. Nonetheless, Im still havent troubles.

So, this is my current hierarchy for Plugins:
![image](https://user-images.githubusercontent.com/1999557/106032008-b0b28e80-60ae-11eb-824f-57e84ba96ff0.png)

And this is my hierarchy for AVProVideo:
![image](https://user-images.githubusercontent.com/1999557/106032104-d0e24d80-60ae-11eb-85eb-1caf0e4250a4.png)

![image](https://user-images.githubusercontent.com/1999557/106032846-bfe60c00-60af-11eb-911c-6a33a04defa1.png)

![image](https://user-images.githubusercontent.com/1999557/106032864-c8d6dd80-60af-11eb-8f50-b1d75eec120d.png)



I doubled check, and left in untouch regarding the importing from the asset store.

I generated some debug functions to see where the PostProcessBuild_iOS is looking for the PluginName. And I get the following assetPath:

_Assets/Plugins/iOS/AVProVideo.framework
Assets/Plugins/tvOS/AVProVideo.framework_

But none pass the validation of assetPath.Contains("AVProVideo/Runtime/Plugins/" + platform .

So, maybe some incorrect naming? Maybe Im missing something

**Comment by MorrisRH** [comment]
Those paths are wrong. I'm thinking Unity's import process has put the new frameworks in to the old locations.
The frameworks should by default live under Assets/AVProVideo/Runtime/Plugins/iOS and Assets/AVProVideo/Runtime/Plugins/tvOS for iOS and tvOS respectively.

**Comment by dalkia** [comment]
That was it @MorrisRH . Thanks a lot for your help!

**Comment by dotesfera** [comment]
Seems like this issue of framework paths is still not fixed on Asset Store. Just bought the iOS Core bundle, and had this error when building. Had to change the Assets/Plugins/iOS folder to Assets/AVProVideo/Runtime/Plugins/iOS, to work. 
Avpro Video Core iOS Version 2.0.8.

**Comment by MorrisRH** [comment]
Unfortunately this is an issue with how Unity upgrades packages. Version 1.x had the plugins in a different location to 2.x and it seems Unity is putting the new plugins in the old path. We're looking for a better solution, hopefully for the next release. Ideally users should remove AVPro Video 1.x entirely before upgrading to version 2.x.
