### ISSUE TITLE
Don't skip frames on low FPS feature

### ISSUE THREAD

**Issue by cihadturhan** [RenderHeads/UnityPlugin-AVProVideo#598]
**Is your feature request related to a problem? Please describe.**
Hi,
As far as I see, if a game has low FPS, AVPlayer just skips frames to catchup current time

I have a project in which it's important frames are not skipped even it's on low FPS.
I couldn't see or isn't there a feature in current version?

**Describe the solution you'd like**
I need a feature that I can disable skipping video frames on FPS drop.

**Describe alternatives you've considered**
There is a "Skip on Drop" feature in unity built-in videoplayer 
![image](https://user-images.githubusercontent.com/3739536/106046070-d792b400-60f2-11eb-90ca-2a5a635df568.png)

**Additional context**
Thanks

**Comment by AndrewRH** [comment]
Hi @cihadturhan thanks for the suggestion.  Is it on any specific platform that you're hoping for this feature?

**Comment by cihadturhan** [comment]
@AndrewRH thanks for a quick response. 
Right now, I need it on MacOS editor and iOS.
If this is difficult to implement, I have another solution to my problem. 

I can manually play video by seeking to next video frame after WaitForNextFrame e.g.
```csharp
var frameTime = 1/30f; // Assuming 30fps video

while(time < totalTime){
   yield return new WaitForEndOfFrame();
   time += frameTime;
   mediaPlayer.Controller.Seek(time)
}
```
However, it's not guaranteed seek will be completed until the next frame. If it's a 4k video with compression, seek time can take up to 4-5 frames.

The actual problem is, 
If I'm at frame `N`, I expect decompressing and showing frame `N+1` to be fast because it already has a previous frame `N`
but I think what it does is, find `I` frame and proceeds to `I+1`, `I+2`, `I+3`... until it finds `N` and `N+1`

**Comment by MorrisRH** [comment]
Have you tried adjusting the playback rate to suit the current frame rate?

**Comment by cihadturhan** [comment]
Thanks for your time, I guess it won't fix for now
