### ISSUE TITLE
Black screen first second of video playing 

### ISSUE THREAD

**Issue by ostepanenko69** [RenderHeads/UnityPlugin-AVProVideo#599]
Hello guys I use AVPro Video 1.11.7, quite often I occur the issue where video starts to play but screen is dark for the first second or less, it happens with different videos and in random manner. This bug appears on the AMD Radeon™ R7 200 graphic card, when I try to run the same app but on more powerful card this issue doesn't exist.  It would be great if you can help with it...

Thanks in advance

**Comment by RenderHeadsSte** [comment]
Can you provide the following information:

- Platform
- Operating system version
- Unity version
- Video information (resolution, framerate, video codec, audio codec) - ideally a screengrab of the output from ffprobe

**Comment by ostepanenko69** [comment]
I run the app on Windows 8 PC , Unity 2018.4.2f1
Video info: codec H264 - MPEG-4 AVC (part 10)(avc1), resolution 928x558, 25fps
file size is about 4mb
