### ISSUE TITLE
About supported capture device by "AVPro Live Camera"

### ISSUE THREAD

**Issue by dzspb** [RenderHeads/UnityPlugin-AVProVideo#60]
Hi! I bought your "AVPro Live Camera" in Unity Assetstore, and I'm not sure whether it can support the blackmagic "Intensity" series capture device？
  Thank you!

**Comment by AndrewRH** [comment]
Please post this to the correct GitHub Issues.  This one is for AVPro Video plugin.
The AVPro Live Camera one is here:
https://github.com/RenderHeads/UnityPlugin-AVProLiveCamera

Yes it does support the Intensity card cards - it say so in the PDF documentation.

Thanks,

**Comment by dzspb** [comment]
Thanks a lot
