### ISSUE TITLE
Legacy settings are not preserved when upgrading to version 2.0

### ISSUE THREAD

**Issue by ruben-ivre** [RenderHeads/UnityPlugin-AVProVideo#600]
**Describe the bug**
Legacy settings in the MediaPlayer are not preserved when upgrading to version 2.0, for example, if you had a prefab with a MediaPlayer and a path to a video set, it's lost in the upgrade because the variable where it was stored has been replaced with another one with different name or type.

I understand and appreciate the code improvements, but maintaining retro compatibility is important for us, as we have lots of prefabs and scenes, and having to manually find and change those settings is both painful and error prone.

I provide below some code samples to keep some of variables that has been replaced, as we've used that to fulfil our needs, but I'm sure there are plenty others that should be taken care of.
The code doesn't modify the public interface of the classes, just uses the ISerializationCallbackReceiver interface to do some postprocessing after deserializing to preserve those legacy variable.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.18f1
 - AVPro Video version: 2.0.2
 - Operating system version: Windows 10 

**MediaPlayer.cs**
Just add ISerializationCallbackReceiver to MediaPlayer class and add this code somewhere in the class.

```
#region Legacy parameters retro compatibility
[SerializeField]
[HideInInspector]
private string m_VideoPath;
[SerializeField]
[HideInInspector]
private FileLocation m_VideoLocation = FileLocation.RelativeToStreamingAssetsFolder;

private enum FileLocation
{
    AbsolutePathOrURL,
    RelativeToProjectFolder,
    RelativeToStreamingAssetsFolder,
    RelativeToDataFolder,
    RelativeToPersistentDataFolder,
}

void ISerializationCallbackReceiver.OnAfterDeserialize()
{
    if (!string.IsNullOrEmpty(m_VideoPath))
    {
        MediaPathType mediaPathType = MediaPathType.AbsolutePathOrURL;
        switch (m_VideoLocation)
        {
            default:
            case FileLocation.AbsolutePathOrURL:
                mediaPathType = MediaPathType.AbsolutePathOrURL;
                break;
            case FileLocation.RelativeToProjectFolder:
                mediaPathType = MediaPathType.RelativeToProjectFolder;
                break;
            case FileLocation.RelativeToStreamingAssetsFolder:
                mediaPathType = MediaPathType.RelativeToStreamingAssetsFolder;
                break;
            case FileLocation.RelativeToDataFolder:
                mediaPathType = MediaPathType.RelativeToDataFolder;
                break;
            case FileLocation.RelativeToPersistentDataFolder:
                mediaPathType = MediaPathType.RelativeToPersistentDataFolder;
                break;
        }
        _mediaPath = new MediaPath(m_VideoPath, mediaPathType);
        _mediaSource = MediaSource.Path;
        m_VideoPath = null;
    }
}

void ISerializationCallbackReceiver.OnBeforeSerialize() { }
#endregion
```

**MediaPlayer_PlatformOptions.cs**
Add ISerializationCallbackReceiver to OptionsWindows class and add this code somewhere in the class.
```
#region Legacy parameters retro compatibility
[SerializeField]
[HideInInspector]
private bool useUnityAudio = false;
[SerializeField]
[HideInInspector]
private bool enableAudio360 = false;

void ISerializationCallbackReceiver.OnBeforeSerialize()	{ }

void ISerializationCallbackReceiver.OnAfterDeserialize()
{
    if (useUnityAudio && audioOutput == Windows.AudioOutput.System)
    {
        audioOutput = Windows.AudioOutput.Unity;
        useUnityAudio = false;
    }
    if (enableAudio360 && audioOutput == Windows.AudioOutput.System)
    {
        audioOutput = Windows.AudioOutput.FacebookAudio360;
        enableAudio360 = false;
    }
}
#endregion
```

**Comment by AndrewRH** [comment]
Thanks for reporting this issue and your code for fixing it.

We generally don't do large breaking API changes, but since it was a big new version 2.0 we decided now was the time to do it.

Quite a lot of API changed, so we asked users to not upgrade from previous versions as there would be too many issues to fix.

We will take a look at your code examples and see whether we can incorporate these into the product to make it easier for those who do decide to upgrade their existing projects.

Thanks,
