### ISSUE TITLE
Metal: Fragment shader missing texture binding at index 0

### ISSUE THREAD

**Issue by JanOwiesniak** [RenderHeads/UnityPlugin-AVProVideo#603]
**Bug**

I using `Apply To Material` Component to render video output on `_MainTex` of a `Material`.

![Screenshot 2021-02-01 at 17 47 16](https://user-images.githubusercontent.com/213214/106489995-a7159600-64b5-11eb-952d-5f8802a79fb4.png)

To use the `Material` on a `RawImage` afterwards.

![Screenshot 2021-02-01 at 17 47 55](https://user-images.githubusercontent.com/213214/106490085-bc8ac000-64b5-11eb-8c40-793f2911a75e.png)

This results in following error (not all the time but most of the time):

`Metal: Fragment shader missing texture binding at index 0`

**Setup**
 - Unity version: 2019.4.18f1
 - AVPro Video version: v2.0.1 Ultra Edition
 - Operating system version: macOS Catalina Verison 10.15.6
 - Device model: MacBook Pro (15-inch, 2016)

**Comment by AndrewRH** [comment]
Instead of using RawImage, can you instead try using DisplayUGUI component?

Does that solve the issue?

Thanks,

**Comment by JanOwiesniak** [comment]
Thanks for the hint but i think this does not solve my issue. I'm using additional components like `Mask` and `AspectRatioFitter` on that `RawImage` to "shape" it and keep ratio in different circumstances.

Neverless i will give it another try. Maybe i can work around it somehow with `DisplayUGUI`

Any idea what might the issue with this?

`Metal: Fragment shader missing texture binding at index 0`

**Comment by MorrisRH** [comment]
I've not been able to reproduce this using:
- Unity 2019.4.18f1
- AVPro Video 2.0.2 Trial & Ultra editions
- macOS 10.15.7

Are you able to share a sample project that reproduces this issue? If so please send it to unitysupport@renderheads.com
