### ISSUE TITLE
Videos are playing randomly. Avpro Version 1.11.7

### ISSUE THREAD

**Issue by NinjaBuoy** [RenderHeads/UnityPlugin-AVProVideo#604]
public class ButtonScript : MonoBehaviour, IPointerClickHandler
{
    public string path;
    private MediaPlayer mediaPlayer;
    private MediaPlayer.FileLocation m_videoLocation = MediaPlayer.FileLocation.RelativeToStreamingAssetsFolder;

    [HideInInspector]
    public RectTransform bottomPanel;

    //save state in json
    private string statePath = Application.streamingAssetsPath +"/state.json";
    private string jsonString;

    void Awake() 
    {
        //Avoid declaring mediaplayer again n again
        mediaPlayer = GameObject.Find("EventSystem").GetComponent<GlobalVariables>().mediaPlayer;
    }

    void OnEnable() 
    {
        //Close previous videos
        if (mediaPlayer && (mediaPlayer.Control != null) && mediaPlayer.Control.IsPlaying())
        {
            mediaPlayer.Stop();
        }

        if (mediaPlayer && mediaPlayer.VideoOpened)
        {
            mediaPlayer.CloseVideo();
            //mediaPlayer.Dispose();
            mediaPlayer.m_VideoPath = string.Empty;
        }
    }

   public IEnumerator videoListener(string videoName)
    {
        //Wait for a frame
        yield return new WaitForEndOfFrame();
        //yield return new WaitUntil(() => mediaPlayer.Control.IsFinished() == true);
        //Play another video
        mediaPlayer.OpenVideoFromFile(m_videoLocation, "videos/" +videoName, true);
        mediaPlayer.Play();
    }

    // Start is called before the first frame update
    void Start()
    {
       
    }

    public void OnPointerClick(PointerEventData eventData)
    {
        //TODO: add LeanTouch
        if (eventData.button == PointerEventData.InputButton.Left)
        {
            StopAllCoroutines();

            StartCoroutine(videoListener(this.path));

     
        }
    }

}

This is my button script attached to every button. Every button has a path as well relative to the streaming assets folder. However mediaplayer behaves randomly and plays any random videos attached to the other buttons. Please let me know how to fix this issue.
![Capture](https://user-images.githubusercontent.com/73826140/106603370-1a6ee480-6556-11eb-93f8-f8abe4b05b86.PNG) 

AVPro Version: 1.11.7

**Comment by kahnivore** [comment]
Pretty sure the problem is something to do with this implementation and not with the software. I'd check the following things:

1. Are you sure the media player is not null? you could try just referencing it instead of finding it on awake 
2. Are you sure your path strings are correct? both that the button scripts have the correct video name and that they are indeed in a folder in streaming assets called (lowercase) "videos"
3. I'd also uncheck 'auto open' and 'auto play' on the media player component to avoid getting null path errors before you've clicked a button 

Hope that helps!

**Comment by NinjaBuoy** [comment]
Thanks for your help.
I found out the issue was with the button. Sometimes it gets selected when the mouse is properly on it. So anyways it was not the issue with AVPro anyway.
