### ISSUE TITLE
Playback of single file videos (MP4) not playing back off http/https servers (e.g. from an S3 bucket on Quest)

### ISSUE THREAD

**Issue by pmb1701** [RenderHeads/UnityPlugin-AVProVideo#606]
**Describe the bug**
Videos from our S3 bucket fire an Error event on Quest 1. It looks like an issue with URL handling (possibly caused by the colon after "team" in the URL?). The same URL's worked on all platforms on 2.0.2, and still work at least on Windows in 2.0.3.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1
 - AVPro Video version: 2.0.3 Core Edition
 - Operating system version: Android
 - Device model: Quest 1

**Logs**

> 2021-02-02T13:55:53.665Z:error4302/3505 ExoPlayerImplInternal
> Playback error<br>  com.google.android.exoplr2avp.ExoPlaybackException: Source error<br>      at com.google.android.exoplr2avp.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)<br>      at android.os.Handler.dispatchMessage(Handler.java:98)<br>      at android.os.Looper.loop(Looper.java:154)<br>      at android.os.HandlerThread.run(HandlerThread.java:61)<br>  Caused by: com.google.android.exoplr2avp.upstream.HttpDataSource$HttpDataSourceException: Unable to connect<br>      at com.google.android.exoplr2avp.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:309)<br>      at com.google.android.exoplr2avp.upstream.DefaultDataSource.open(DefaultDataSource.java:199)<br>      at com.google.android.exoplr2avp.upstream.StatsDataSource.open(StatsDataSource.java:84)<br>      at com.google.android.exoplr2avp.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)<br>      at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:415)<br>      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)<br>      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)<br>      at java.lang.Thread.run(Thread.java:761)<br>  Caused by: java.net.MalformedURLException: no protocol: /team:0nfwkhf599ae4n8s/8fac26ef-36e9-4d06-b16b-cba07f9b0930/Celebration.mp4<br>      at java.net.URL.<init>(URL.java:589)<br>      at java.net.URL.<init>(URL.java:486)<br>      at java.net.URL.<init>(URL.java:435)<br>      at com.google.android.exoplr2avp.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:468)<br>      at com.google.android.exoplr2avp.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:307)<br>      ... 7 more<br>
> 2021-02-02T13:55:53.677Z:info3521/3505 System.out
> AVProVideo error Source error

**Videos**
https://glue-public-static-resources.s3.eu-west-1.amazonaws.com/team%3A0nfwkhf599ae4n8s/8fac26ef-36e9-4d06-b16b-cba07f9b0930/Celebration.mp4

**Comment by RenderHeadsSte** [comment]
This is fixed in v2.0.4 which we will rush out asap.

**Comment by RenderHeadsSte** [comment]
@pmb1701 Please do let us know if the fix in v2.0.4 addresses the issue for you

**Comment by pmb1701** [comment]
@RenderHeadsSte  Confirming fixed in v2.0.4
