### ISSUE TITLE
Can't build DemoScene on iOS: Missing library

### ISSUE THREAD

**Issue by paulosalvatore** [RenderHeads/UnityPlugin-AVProVideo#608]
**Describe the bug**
I've created a new project and import AVPro Core 2.x, but when I try to build Xcode project and run it on iOS, it gives an error.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.30f1
 - AVPro Video version: AVPro 2.0.4 Ultra
 - Operating system version: macOS Catalina 10.15.7
 - Device model: iPhone XR
 - Video specs (resolution, frame-rate, codec, file size): 2200x1300, 30fps, mp4, 40MB

**To Reproduce**
1. Create a Unity project and import package
2. Add Demo_MediaPlayer scene to build settings
3. Build on Xcode and then play on iOS

**Logs**
```
yld: Library not loaded: @rpath/AVProVideo.framework/AVProVideo
  Referenced from: /private/var/containers/Bundle/Application/735CFF89-8CE0-4488-89A3-C92E0D570B82/AVProTest.app/AVProTest
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

**Screenshots**

AvProVideo framework can be found on frameworks list, but it says "Image not found" for some reason.

![Screenshot 2021-02-03 às 00 21 02](https://user-images.githubusercontent.com/7906171/106693694-c0057080-65b5-11eb-90c4-03de983f54e1.png)

**Comment by MorrisRH** [comment]
AVProVideo.framework needs to be set to "Embed & Sign" in the Xcode project settings.

The PostProcessBuild_iOS script should do this automatically however if the plugin is "out of place" in your Unity project it will fail. It would be useful to know if you either:
* moved the plugin folder from its default location and if so, to where; or
* did you upgrade from version 1.x without first removing the version 1.x plugin?

**Comment by paulosalvatore** [comment]
Hey Morris, thanks for your response.

I did move AVPro to `Assets/Packages/` folder.

Now, I've created an empty project, imported AVPro and built on iOS. Everything works fine.

Can I do something to have AVPro inside `Assets/Packages` folder? Or is it not recommended?

**Comment by MorrisRH** [comment]
```Assets/Packages``` should be fine. You should be able to move the AVProVideo folder anywhere under Assets without any issue.

**Comment by paulosalvatore** [comment]
That's strange, because is exactly what I did.

I'll try to do it again later, but I think this issue can be closed.

Thank you.
