### ISSUE TITLE
How setup hls for webgl in 2020

### ISSUE THREAD

**Issue by futuraspace** [RenderHeads/UnityPlugin-AVProVideo#610]
Hi, I was following these steps to load hls videos in webgl, and working fine: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/327#issuecomment-619021113

Nevertheless, in 2020 unity change the way to do builds to webgl, the index.html is different now. How could i reference the hls.min.js?

**Comment by RenderHeadsSte** [comment]
What version of AVPro Video are you using?

**Comment by futuraspace** [comment]
Version 1.11.7

**Comment by kahnivore** [comment]
Hi @futuraspace

Yes, Unity have updated the way the index.html is set up - but it's still possible to include the hls.min.js in the head and this will work. 

It's possible that the problem you're having comes from [this](https://issuetracker.unity3d.com/issues/webgl-build-gets-stuck-on-the-loading-screen-when-compression-is-enabled). I've found if you remove compression on build (PlayerSettings -> PublishingSettings -> CompressionFormat -> None) it works. 

This is however not an AVPro problem, but do let us know if this fixes it!
