### ISSUE TITLE
I would like to play Hap-Q video fluently with AVPro2.0

### ISSUE THREAD

**Issue by keitasumiya** [RenderHeads/UnityPlugin-AVProVideo#611]
**Describe the bug**
I tried to play my Hap-Q video using AVPro 2.0.4, but it doesn't work. 
First of all, I tested Media foundation setting, but AVPro can not load the video. 
Therefore, I changed to Direct Show and it can load, but playing fps is not enough (about 40 fps). 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.19
 - AVPro Video version: 2.0.4
 - Operating system version: Windows 10 pro
 - Device model: Thinkpad P1 Gen1
 - Video specs (resolution, frame-rate, codec, file size): 
   - resolution: 7680x4320
   - frame-rate: 60fps
   - codec: Hap-Q
   - file-size: 79.3GB (per 1 minute)
   - file length: 1 minute
   - audio: This video don't have audio. 

**To Reproduce**
1. Import AVPro (2.0.4, Ultra Edition)
2. Open `Assets/AVProVideo/Demos/Scenes/Demo_MediaPlayer`
3. Click `MediaPlayer` game object. 
4. Change `Media Source` to `Path`
5. Browse and select a specific video file
6. (Change `Video API` from `Media Foundation` to `Direct Show`)
7. Play Unity

**Logs**
When I tested it using Media Foundation, the following error occurred:
```
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1164)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:599)
``` 

The above error didn't occur using Direct Show. 

**Screenshots**

**Videos**

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by keitasumiya** [comment]
I tested it with AVPro 2.0.5 too. 
However the problem still occurred and same as v2.0.4.

**Comment by kahnivore** [comment]
Hi @keitasumiya 

There is currently a bug with playing large Hap-Q files with Media Foundation. We're looking into fixing this issue, and should have it resolved in a few weeks time. In the meantime, you could consider transcoding to AVI (using ffmpeg to simply change the container) which should work fine. 

In terms of framerate and performance, while Media Foundation is a bit faster than Direct Show, there might also be hardware limitations with playback of such large files. It'd be advisable to check the performance in the task manager to see if your system is running at full speed. 

Hope that helps!

**Comment by keitasumiya** [comment]
Thank you for your reply. 
I see... I understand the situation for large Hap-Q files. Until the release of the updated version, I'll try the transcoding to AVI as you said. 
Moreover, according to my task manager, it seems my pc doesn't work fully because the CPU is not 100%. 

I really really looking forward to your new release!!
Best regards, 
Keita

**Comment by AndrewRH** [comment]
> Thank you for your reply.
> I see... I understand the situation for large Hap-Q files. Until the release of the updated version, I'll try the transcoding to AVI as you said.
> Moreover, according to my task manager, it seems my pc doesn't work fully because the CPU is not 100%.
> 
> I really really looking forward to your new release!!
> Best regards,
> Keita

Hi @keitasumiya  yes we have made some internal performance improvements to our Hap implementation over the last few days - so some good things will be coming soon.

Thanks,

**Comment by keitasumiya** [comment]
I had guessed the the version 2.0.6 is not suitable for this problem, but I tested it just in case and it doesn't work. 
I really looking forward to the future 2.1.0!!

Thanks a lot, 
Keita

**Comment by keitasumiya** [comment]
I tested the the version 2.0.7 but it doesn't work.
(I guess probably you know this version is unsuitable. )

Thanks a lot,
Keita

**Comment by AndrewRH** [comment]
Thanks @keitasumiya 

Yes 2.0.7 has some performance improvements for Hap+NotchLC but still doesn't allow for very high bitrate videos to play.  We have this working internally and will be releasing it soon in 2.1.0

Thanks for your patience.

**Comment by AndrewRH** [comment]
@keitasumiya  please try the new version 2.0.9 - you should see a big difference with Hap codec support.

Thanks,

**Comment by keitasumiya** [comment]
@AndrewRH 
Thank you for telling new version!! I'll check it from now!!

**Comment by AndrewRH** [comment]
@keitasumiya  thanks for testing, sorry that it didn't work immediately.

Did you enable the new option **"Use Custom MOV Parser"** in Platform Specific > Windows ?

If you're still unable to play one of your videos, could you please email us a copy of it so we can debug and test? (unitysupport@renderheads.com)

Thanks,

**Comment by keitasumiya** [comment]
@AndrewRH 
Thank you very much for your reply!!

I tested your suggestion of "Use Custom MOV Parser" and I could play my Hap-Q video with Media Foundation setting. 
However it was not fluent and the playing fps is about 12. Therefore I also turned on "Use Law Latency" then the playing fps was 25 and it is better than before. 

I am sorry for I can not send my actual video because of my work but I can send similar file size video (Hap-Q, 60 fps, 73.2GB/1min).

**Comment by AndrewRH** [comment]
@keitasumiya  we have just released 2.0.10 which has a lot of improvements for Hap - hopefully it will have better performance for you.

**Comment by keitasumiya** [comment]
@AndrewRH 
Thank you for release of 2.0.10!!
Now I tested my video but it looks almost same as 2.0.9... So, the playing fps is about 12-17 and fluctuating for the video (79.3GB/1min).

**Comment by keitasumiya** [comment]
Sorry, my above test was for AVPro 2.0.11 and it's not for 2.0.10.

**Comment by AndrewRH** [comment]
Closing this as 2.1.0 has been released with this fix - if you're still having issues please do start a new thread.  Thanks,
