### ISSUE TITLE
Hardware decoding doesn't work in Windows 8.1

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#612]
**Describe the bug**
Videos dont play in the demo, just spins busy all the time. Maybe because im using Universal Rendering pipeline?

**Your Setup (please complete the following information):**
 - Unity version:  2020.1.2
 - AVPro Video version: ltest downloaded just now from your website
 - Operating system version: windows 8.1
 - Device model: Windows 8.1 Unity editor
 - Video specs (resolution, frame-rate, codec, file size): demo video scene from your package

**To Reproduce**
1. create brand new project with Universal Rendering Pipeline
2. Import AVPRO
3. press play while running one of the demo scenes

**Comment by kahnivore** [comment]
Hi @nsmith1024 

URP shouldn't be a problem. 

We switched to using HEVC videos for the demo from our 2.x releases, which is not supported prior to Windows 10. 

Could you try substituting the demo videos with media that has a codec supported by Windows 8.1?

**Comment by nsmith1024** [comment]
Everything i used came from the demo i downloaded from you site, even the video and scene everything. Are you saying it wont work on Windows 8.1?

**Comment by RenderHeadsSte** [comment]
Windows 8.1 is supported, but the demo videos we included in the first few versions of the asset package are HEVC/h265, which Windows 8.1 cannot playback.  If you change the demo to playback a different h264 video, you should see video playback.

Alternatively, if you download the latest [trial version](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/download/2.0.5/UnityPlugin-AVProVideo-v2.0.5-Trial.unitypackage) (2.0.5), the demo scenes now are setup to playback a h264 video.

I hope this helps.  Do let us know.

**Comment by nsmith1024** [comment]
I downloaded the version of AVProVideo at that link in the previous post above, and imported it into a new Unity project, and loaded up scene Demo_MediaPlayer. and hit play. A spinning icon appeared and that was all, no video played.

Please let me know how to get it to to work, im on windows 8.1 using Unity 21020.1.2

**Comment by RenderHeadsSte** [comment]
Did you make sure all the files were ticked when you imported the new package? (so the old ones are overwritten)  Can you send a screen shot of the console output when you run please? Also one of the MediaPlayer GameObject settings.

**Comment by nsmith1024** [comment]
I deleted the AVPro Video folder before i imported it a second time, but same result. Yes everything was imported player just spins without playing anything, i did'nt change any setting

![Capture](https://user-images.githubusercontent.com/22501617/107093794-dbe65d80-67d3-11eb-9db8-caafedecc555.PNG)

![c2](https://user-images.githubusercontent.com/22501617/107093986-426b7b80-67d4-11eb-8d2f-7fd92e8d65c6.PNG)

**Comment by RenderHeadsSte** [comment]
What edition of Windows  8 are you running?  (Is it K, M or KN, etc)

I believe a few of them did not come with codecs included.

**Comment by nsmith1024** [comment]
Here is the version, tried downloading that media feature pack, it said its not applicable to my computer.

I already have another version of AVPro that i been using,  now i want to start a new project, but for some reason the demo dont work with your latest demo

![cap2](https://user-images.githubusercontent.com/22501617/107247636-7971a500-69ff-11eb-8c26-52c04edcf8c2.PNG)

**Comment by RenderHeadsSte** [comment]
> Here is the version, tried downloading that media feature pack, it said its not applicable to my computer.

Did you forget to include it?

> I already have another version of AVPro that i been using, now i want to start a new project, but for some reason the demo dont work with your latest demo

Were you using v1.x previously?

**Comment by nsmith1024** [comment]
I could not include it because it said it wasn't compatible with my computer.

I was previously using V1.11.4t (scripts V1.10.1) which currently works in another Unity project on the same computer.

I now started a new Unity project, so I decide to try your new version from the demo. When I try it don't not play any of the demo videos. It just shows a spinning busy where the video would be playing.

**Comment by AndrewRH** [comment]
@nsmith1024 we're looking into this and will get back to you soon.

**Comment by AndrewRH** [comment]
We have replicated the problem.  It seems to be related to having "hardware decoding" enabled as it works with this option disabled.  We are investigating.

**Comment by AndrewRH** [comment]
@nsmith1024  we have fixed this issue - Windows 8.1 will be supported in the next release.

Thanks,

**Comment by AndrewRH** [comment]
I'm closing this issue as I'm confident that our upcoming fix resolves the issue.
