### ISSUE TITLE
MediaPlayer doesn't work on iOS after scene is restarted

### ISSUE THREAD

**Issue by paulosalvatore** [RenderHeads/UnityPlugin-AVProVideo#613]
**Describe the bug**

MediaPlayer doesn't work on iOS after scene is restarted.

Video play for the first time, but when touch happens and scene is restarted, log shows that AVPro tried to open video, but there are no errors nor video.

Already tried to use both `Display uGUI` and `Apply to Material` components, but it didn't make any difference.

**Your Setup (please complete the following information):**

 - Unity version: 2018.4.30f1
 - AVPro Video version: AVPro 2.0.5 Ultra
 - Operating system version: macOS Catalina 10.15.7
 - Device model: iPhone XR
 - Video specs (resolution, frame-rate, codec, file size): 2200x1300, 30fps, mp4, 40MB

**To Reproduce**

1. Create an empty scene
2. Add MediaPlayer with AutoOpen/AutoPlay and `Display uGUI`
3. Reference a video from `StreamingAssets` (not sure if that's related)
4. Create a script that restarts the scene on `MouseButtonDown(0)`
5. Build on iOS.

**Comment by MorrisRH** [comment]
I've reproduced the issue, will try and get a fix ready for the next release.

**Comment by JanOwiesniak** [comment]
Fixed with [v2.0.6](https://www.renderheads.com/content/docs/AVProVideo/versions/2.0.6.html) (ran into the same issue)

**Comment by paulosalvatore** [comment]
Fixed with v2.0.6.

Thank you, @MorrisRH

Closing issue.
