### ISSUE TITLE
FB360 encoded .mkv files not playing on Windows 10 or Quest 2

### ISSUE THREAD

**Issue by FredrikHa** [RenderHeads/UnityPlugin-AVProVideo#614]
As title says.
Started a clean Unity project and imported a video file encoded from FB360 Encoder to the "Streaming Assets" folder. When trying to  load the files Unity gives me the error:
`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`
The .mp4 video file I use as the input to FB360 Encoder plays fine in the Editor and in the Quest 2. But not the .mkv file from FB360 Encoder.

Using the new v2.0 AVPro Video version, the .mkv file worked on AVPro Video v1.x.

I have also tried this: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/596#issuecomment-771606090

**Setup:**
 - Unity version: 2020.2.2f1
 - AVPro Video version: 2.0.4
 - Operating system version: Windows 10 
 - FB360 Encoder: v3.3.3
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): See ffprobe output underneath.
 
![image](https://user-images.githubusercontent.com/986695/107011574-1e8a4480-6798-11eb-98d7-91a65ed25eae.png)

![image](https://user-images.githubusercontent.com/986695/107011917-9e181380-6798-11eb-870b-cd3c10580125.png)

![image](https://user-images.githubusercontent.com/986695/107011942-a5d7b800-6798-11eb-9f58-78234e0489ba.png)

**Comment by RenderHeadsSte** [comment]
What version of AVPro Video 2.0.4 are you using?  (Trial, Core, Ultra)

**Comment by FredrikHa** [comment]
Using Core Android Edition and Core Windows Edition

**Comment by RenderHeadsSte** [comment]
I am afraid that spatial audio is not a feature of the Core edition (see [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions))

**Comment by FredrikHa** [comment]
I saw that after I purchased the Android and Windows Edition. Since AVPro v1.x had it included, I tought this one also did...

Does spatial audio work in trail edition?

**Comment by RenderHeadsSte** [comment]
It indeed does.  The trial version is based on the Ultra edition so developers can trial all features.

**Comment by FredrikHa** [comment]
Same issue.
Started a new clean Unity project (2020.2.2f1), added the "UnityPlugin-AVProVideo-v2.0.5-Trial" package. 

Only thing I've done is replacing the path.
![image](https://user-images.githubusercontent.com/986695/107027988-31f3da80-67ad-11eb-8c87-175a6e80b70d.png)

Same error as before:
`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

**Comment by RenderHeadsSte** [comment]
Is this on Windows, Android, or both?

**Comment by FredrikHa** [comment]
This is on Windows, building on Quest 2 as we speak.

**Comment by RenderHeadsSte** [comment]
Cool, thanks...that is what I was going to ask if you could do :)

**Comment by FredrikHa** [comment]
Same on issue on my Quest :/

**Comment by RenderHeadsSte** [comment]
Have you tried the original v1 FB360 mkv video?

Can you send your video over to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)? I have a Quest 2 to hand, so can test it here.

**Comment by FredrikHa** [comment]
Same error on the "FantasyStereoFB360.mkv" file from v1.

I've sent the video over now :)
Thanks!

**Comment by RenderHeadsSte** [comment]
Awesome, thanks.

We will look into it and get back to you.

**Comment by RenderHeadsSte** [comment]
Can you post or email over a logcat dump please @FredrikHa?

**Comment by RenderHeadsSte** [comment]
Scrap that.  I think I know what the issue is.  On Android it is simply an access permission issue.  You can find the steps to fix this [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/596#issuecomment-771606090).

Small note on the path.  It doesn't have to be file:///sdcard/etcetcetc/myVideo.mkv, it can be /sdcard/etcetcetc/myVideo.mkv (on the Quest 2).

**Comment by RenderHeadsSte** [comment]
RE Windows, we are still looking into this one.  I think this might be a genuine bug.  Stand by!

**Comment by FredrikHa** [comment]
> Scrap that. I think I know what the issue is. On Android it is simply an access permission issue. You can find the steps to fix this [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/596#issuecomment-771606090).
> 
> Small note on the path. It doesn't have to be file:///sdcard/etcetcetc/myVideo.mkv, it can be /sdcard/etcetcetc/myVideo.mkv (on the Quest 2).

As I mentioned in the description at first, I have already tried that one :/ 
Noe problem with path referencing with the .mp4 files.

**Comment by RenderHeadsSte** [comment]
Ah yes, sorry...missed that.

Will need the logcat output then :)

**Comment by FredrikHa** [comment]
Ahh, stragne. Then the .mvk is not corrupt then :) 
Sendt the logcat via email now.

**Comment by RenderHeadsSte** [comment]
As an update on this issue:

Whilst we are awaiting confirmation still, the Android issue was reproduced and fixed by setting the correct 'Audio Output' (to 'Facebook Audio 360') and the Quest 2 appears to need a reboot should (possibly) hardware decoders get locked.  We have seen this on other Android devices and can only put it down to 'the stresses of continual development' that require devices to be rebooted periodically.

Windows is a genuine bug that we will be fixed in the v2.0.6 release.

**Comment by FredrikHa** [comment]
I can confirm that it runs perfectly on my Quest 2 now 👌🏼
Looking forward to the Windows bug fix in the future.

**Comment by RenderHeadsSte** [comment]
Do let us know

**Comment by RenderHeadsSte** [comment]
This should be fixed on Windows now in v2.0.6.  Please do let us know @FredrikHa if you get chance to update and test.

**Comment by FredrikHa** [comment]
Works great! Thanks :) 

Tested using Unity 2020.2.2f1, Windows 10.
