### ISSUE TITLE
Access to persistent data path

### ISSUE THREAD

**Issue by bradipo3001** [RenderHeads/UnityPlugin-AVProVideo#616]
Hi,
I'm trying to play via video player a file in the device memory (oculus go).

I'm trying the usual url format that i use with the built in unity video player but it looks like is not working.
I'm using for the test the video inside the unity package.

What's the right way to link in a video in the device memory?

I've already give to the app the permission to internal memory.

**Comment by RenderHeadsSte** [comment]
Can you please provide all the information asked for when you open an issue.  It is a little hard to help without it.

**Comment by bradipo3001** [comment]
I've imported the unity package and opened the demo_360stereo scene.
I installed it on an oculus go and everything works fine.

Now i want to play a video in the internal memory of the oculus go.
I've created a folder "360videos" and put in the "Cones-360Stereo-2K30-HEVC.mp4".

in the mediaplayer object under settings->source i change "media source" to "path".
Than "relative to persistent data folder" and make it point to "360videos/Cones-360Stereo-2K30-HEVC.mp4".

When the app start on the oculus go everything is black.

I'm using unity 2019.1.8f1

**Comment by RenderHeadsSte** [comment]
Unity says that the persistent data path on Android points at:

/storage/emulated/0/Android/data/<packagename>/files

Firstly you will need another slash on your path '/360videos/Cones-360Stereo-2K30-HEVC.mp4'

Other things you might need to set are outlined in #596. The last two points in [this](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/596#issuecomment-771606090) post.

Hope that gets things working from you.  If not, please post a logcat dump from the device so we can assist further.

**Comment by bradipo3001** [comment]
Thanks, it worked using the suggestion on the other post.
The pat should start with "file:///sdcard/" if i want to an absolute path.

Now i have problems to make work the ambisonic audio.
Probably i've to open another thred.
