### ISSUE TITLE
Android build file size increase

### ISSUE THREAD

**Issue by withstand007** [RenderHeads/UnityPlugin-AVProVideo#618]
Hi,
Recently we bought the core edition and integrated this plugin. But the issue is that we are seeing an increase of 20-30 MB in our android build size. 

How can we reduce the build size as this much increase in size is not feasible for us.

Thank you

**Comment by kahnivore** [comment]
Hey @withstand007 

I think the first point of call would be to remove the sample videos from the StreamingAssets folder which is just short of 50mb. 

You can also remove the followings libs which would free up an additional 9.6mb: 

\Assets\AVProVideo\Runtime\Plugins\Android\libs\arm64-v8a\libAudio360.so
\Assets\AVProVideo\Runtime\Plugins\Android\libs\arm64-v8a\libAudio360-JNI.so
\Assets\AVProVideo\Runtime\Plugins\Android\libs\armeabi-v7a\libAudio360.so
\Assets\AVProVideo\Runtime\Plugins\Android\libs\armeabi-v7a\libAudio360-JNI.so
\Assets\AVProVideo\Runtime\Plugins\Android\libs\x86\libAudio360.so
\Assets\AVProVideo\Runtime\Plugins\Android\libs\x86\libAudio360-JNI.so

Let us know if that solves your problem!

**Comment by withstand007** [comment]
Hi @kahnivore 
Thank you for the fix. This helped us reduce the apk size back to our previous build :)

Thank you
