### ISSUE TITLE
Single Pass Instanced rendering mode issue

### ISSUE THREAD

**Issue by M2MarcusKan** [RenderHeads/UnityPlugin-AVProVideo#619]
Problem description:

When using Single Pass Instanced rendering mode right eye show nothing, I am using HDRP s
o can't change to Multi-Pass, any fix on it?

Device (which devices are you having the issue with - model, OS version number):

windows 10 2004

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

3840*2160, frame-rate 25

System Information:

AVPro Video: v2.0.6 (plugin v2.0.6f1-ultra)
Target Platform: Android
Unity: v2020.1.0f1 WindowsEditor
OS: Desktop - Alienware Aurora R8 (Alienware) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz - 8 threads - 16185KB
GPU: NVIDIA GeForce RTX 2070 - NVIDIA - Direct3D 11.0 [level 11.1] - 8031KB - 16384

**Comment by RenderHeadsSte** [comment]
What Android VR device are you targetting?

**Comment by M2MarcusKan** [comment]
Upgrading the project to 2020.2.3f can fix this issue
