### ISSUE TITLE
Flickering video osx avpro 1.x

### ISSUE THREAD

**Issue by Chunkdafunk** [RenderHeads/UnityPlugin-AVProVideo#620]
Hey guys I moved my pc build over to mac and noticed video is messed up. Setup is just a canvas player setup all straight forward. 

I thought it was due to transfer but created a clean project and even the avpro demos are doing the same.  Media player is set to osx, videos are mp4 via aws.   I've scanned the git and haven't noticed anyone with similar

Mac is old mbp running big sur

**Comment by kahnivore** [comment]
Hey @Chunkdafunk 

Not sure what's causing this. Could you please supply the following info:
 
1. What year/model MacBook Pro?
2. Which Unity version? 
3. Are you using the Metal or OpenGl API? 
4. When you say the same thing is happening with the demo videos, do you mean if you reference a video in your scene, or using one of the demo scenes? 
5. Any more description you could give of flickering behaviour 

Thanks!

**Comment by Chunkdafunk** [comment]
1.  Late 2013 mbp big sur 11.2
2.  2020.2.3f1
3.  I have auto graphics button ticked
4.  I'll sort a vid link

**Comment by kahnivore** [comment]
Could you try unchecking auto graphics and setting OpenGL Core as the rendering API?
