### ISSUE TITLE
Multiple Media Players in the same scene cause flickering

### ISSUE THREAD

**Issue by Oneiros90** [RenderHeads/UnityPlugin-AVProVideo#624]
**Describe the bug**
I have a scene where I have to reproduce two videos simultaneously. So I have two `MediaPlayer` components, configured with two different paths and two `Apply To Mesh` components. Everything works fine in Windows but we're facing serious problems on macOS and WebGL: both videos have a fast flickering glitch, like they are fighting to eachother. The bug is visible also in the `MediaPlayer` inspector.

**Your Setup (please complete the following information):**
 - Unity version: Unity 2020.2.2f1
 - AVPro Video version: 2.0.6
 - Operating system version: macOS 11.0 Big Sur
 - Video specs (resolution, frame-rate, codec, file size): I tried all demo videos (those in `AVProVideo\Demos\SampleMedia`)

**To Reproduce**
1. Create two `MediaPlayer` components
2. Assign one video each (same video or different videos, it doesn't matter)
3. Play the scene and look at the inspector

**Comment by kahnivore** [comment]
Hey @Oneiros90 

Which browser are you using to test the WebGL?

**Comment by Oneiros90** [comment]
Hi @kahnivore 

I'm using Firefox 85. However I would suggest to consider my report mostly about macOS, the problem is most visible there

**Comment by kahnivore** [comment]
Could you let us know what hardware you're using?

**Comment by Oneiros90** [comment]
MacBook Pro (15-inch, 2016) with Radeon Pro 460 4 GB

**Comment by MorrisRH** [comment]
Have reproduced this on a 2015 MacBook Pro (Radeon R9 M370X).
Seems to happen when the video's framerate is greater than the Unity player's framerate.
Will look into getting this fixed ASAP.

**Comment by MorrisRH** [comment]
A fix will be in the next release (2.0.7).
