### ISSUE TITLE
PreferredMaximumResolution for Android ExoPlayer

### ISSUE THREAD

**Issue by JanOwiesniak** [RenderHeads/UnityPlugin-AVProVideo#626]
Is there something similar to [PreferredMaximumResolution](https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.MediaPlayer.OptionsApple.PreferredMaximumResolution.html) for Android ExoPlayer as well? I would like to pin max video resolution to 720p but found no way of doing that on Android so far.

**Comment by RenderHeadsSte** [comment]
Yeah, we can look at adding sideways support for that on Android.

Great suggestion, thanks :)

**Comment by RenderHeadsSte** [comment]
This will be completed for v2.1.0.  It should behave in a similar fashion to iOS, in that only tracks equal to or above the specified resolution will be included for consideration in the adaptive group when playing back an adaptive streaming format.  If there are no tracks that fall into this bracket, then the closest track to the desired resolution will be included.

**Comment by KuribaraH** [comment]
This is good news for us. 
It would be nice to have PreferredPeakBitRate for Android.

**Comment by acgourley** [comment]
I'm using 2.0.11 right now, and when I tick this option on for Android, I still have a tablet here which is selecting the lowest bitrate stream from the bottom of the HLS playlist. 

In code, when I query `mediaPlayer.PlatformOptionsAndroid.startWithHighestBitrate` it comes back as False. I'm quite positive I have it checked in the editor. I also have tried setting `mediaPlayer.PlatformOptionsAndroid.startWithHighestBitrate` to true myself but that doesn't seem to matter.

**Comment by RenderHeadsSte** [comment]
I will add PreferredPeakBitRate to the list.  It will hopefully be released in 2.1.1 :)

Closing this issue as we have added PreferredMaximumResolution to Android in the newly released v2.1.0 today.
