### ISSUE TITLE
Videos working in Unity but don't work on the WebGL Build published on the internet

### ISSUE THREAD

**Issue by Shiwabiwa** [RenderHeads/UnityPlugin-AVProVideo#628]
Hello,
I have a problem. I'm using the AV Pro video, the videos are working on unity but when published to the Web the videos aren't working.
I'm using the shader - AVProVideo/Unlit/Opaque. Trying to look into other shaders.
Need your help please, would be grateful for any help
Thank you!

OS: Windows 10
Unity : 2019.4.18
WebGL 2.0
AV Pro - AVPro Video v2.0.6 - 8 February 2021

![videounity](https://user-images.githubusercontent.com/34218452/107969642-b1a55480-6fb8-11eb-80eb-85d75f2811a2.png)
<img width="1440" alt="Screen Shot 2021-02-15 at 6 02 42 PM" src="https://user-images.githubusercontent.com/34218452/107969737-d4d00400-6fb8-11eb-8196-9e231ae08e6d.png">

**Comment by kahnivore** [comment]
HI @Shiwabiwa 

I see you closed this issue, did you come right?

**Comment by Shiwabiwa** [comment]
I did, I put the videos and the build on amazon services in the same bucket. Then it worked properly 
Thanks
