### ISSUE TITLE
Video not streaming on Samsung A6

### ISSUE THREAD

**Issue by dalkia** [RenderHeads/UnityPlugin-AVProVideo#629]
**Describe the bug**

AVPro is not being able to load a video on a Samusng A6 phone using Android 10 using an mpd stream. The ReadyToPlay event is never called so the video doesnt start. 

The same stream is working correctly on another phones, we seem to have problem just on this one. Another interesting thing is that the video player worked when using AVPro 1.X. I know it may be a particular phone, but had you had problems on Android phones with streamings not starting?

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.14 
 - AVPro Video version: 2.0.2
 - Operating system version: Built on Windows
 - Device model: Android 10 - SamsungA6 phone
 - Video specs (resolution, frame-rate, codec, file size): mpd stream

Thank you!

**Comment by RenderHeadsSte** [comment]
Have you tried the latest version of AVPro Video? (2.0.6 at time of writing)

**Comment by kahnivore** [comment]
Hey @dalkia - would it be possible to get the mpd stream url you're having issues with so we can test it on our side? 

You can send it to our support email, unitysupport@renderheads.com.

**Comment by RenderHeadsSte** [comment]
This issue was handled privately.  It appears it was a conflict with importing v2.x into a project that did not have v1.x fully removed.
