### ISSUE TITLE
Android build fails with Firebase Firestore

### ISSUE THREAD

**Issue by bonsenz** [RenderHeads/UnityPlugin-AVProVideo#630]
**Describe the bug**
I worked with the AVPro Media Trial-Version 1.x.x and bought the Core Android Edition 2.0.6. I removed all the files of the trial version and added the new version via the Package Manager. In Unitys-Editor it works fine, but when building an APK (minimum API Level 21) we facing following errors.

As you can see in the LOG it says "_Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0_" but gradle version in PlaybackEngines>AndroidPlayer>Tools>gradle is 5.1.1, if I use gradle 6.0 it says "_Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0"_.

_> Task :launcher:checkReleaseDuplicateClasses FAILED_

And it looks like that it has problems with com.google.guava.guava-28.1-android.jar and guava-27.1-android.jar.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.18f1
 - AVPro Video version: 2.0.6
 - Operating system version: macOS Catalina 10.15.7
 - Device model: MacbookAir 2015
 - Video specs (resolution, frame-rate, codec, file size): -

**To Reproduce**
1. create empty 3D-Unity project
2. import AVPro Media Core Android 2.6.0
3. build Android APK minimum API Level 21 - SUCCESS
4. import Firebase Filestorage from https://firebase.google.com/download/unity. Assets>Import Package>Custom Package. Choose dotnet3>FirebaseFirestorage.unitypackage.
5. build Android APK minimum API Level 21 - FAILS

**Logs**

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:checkReleaseManifest UP-TO-DATE
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :launcher:preReleaseBuild
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:checkReleaseManifest UP-TO-DATE
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :launcher:generateReleaseSources UP-TO-DATE
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :unityLibrary:generateReleaseRFile
> Task :unityLibrary:prepareLintJar UP-TO-DATE
> Task :unityLibrary:generateReleaseSources UP-TO-DATE
> Task :unityLibrary:javaPreCompileRelease
> Task :launcher:mergeReleaseResources
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :launcher:processReleaseManifest

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders UP-TO-DATE
> Task :unityLibrary:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
> Task :unityLibrary:transformNativeLibsWithIntermediateJniLibsForRelease UP-TO-DATE
> Task :launcher:processReleaseResources
> Task :launcher:javaPreCompileRelease UP-TO-DATE
> Task :launcher:compileReleaseJavaWithJavac
> Task :launcher:compileReleaseSources
> Task :launcher:lintVitalRelease
> Task :launcher:mergeReleaseShaders UP-TO-DATE
> Task :launcher:compileReleaseShaders UP-TO-DATE
> Task :launcher:generateReleaseAssets UP-TO-DATE
> Task :launcher:mergeReleaseAssets
> Task :launcher:validateSigningRelease UP-TO-DATE
> Task :launcher:signingConfigWriterRelease UP-TO-DATE
> Task :launcher:checkReleaseDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
38 actionable tasks: 14 executed, 24 up-to-date

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

----------------------------------------------------------------------------

If I try to build the exported project in Android Studio:

Execution failed for task ':launcher:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.common.annotations.Beta found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.annotations.GwtCompatible found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.annotations.GwtIncompatible found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.annotations.VisibleForTesting found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.base.Absent found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.base.AbstractIterator found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.base.AbstractIterator$1 found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.base.AbstractIterator$State found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.base.Ascii found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.base.CaseFormat found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
  Duplicate class com.google.common.base.CaseFormat$1 found in modules com.google.guava.guava-28.1-android.jar (com.google.guava.guava-28.1-android.jar) and guava-27.1-android.jar (guava-27.1-android.jar)
...
and many more

**Comment by bonsenz** [comment]
**SOLUTION**

You have put the _guava-21.1-android_ binary in Assets>AVProVideo>Runtime>Plugins>Android, this obviously collides with the guava dependency from firebase. I deleted the binary file and now it works ! 

Maybe you should add google.guava as a dependency to avoid conflicts.

Anyways, nice plugin !

**Comment by RenderHeadsSte** [comment]
As you state, we do include guava-27.1-android in the asset package and it is a dependency required for the ExoPlayer API.

The problem is clashes with other plugins...as you have seen here.  The fix can be a bit of a lottery based on which version is used by the other asset, and which one is loaded first.  In this case it looks like Firebase bundles a newer version.  I have not seen a problem with newer versions of guava in ExoPlayer, so your fix is the correct one I this case.

More can be read about the problem here: [https://blog.gradle.org/guava](https://blog.gradle.org/guava)

Thanks for your kinds words.  We are always here to help out :)
