### ISSUE TITLE
Demo 360StereoSpatialAudio error

### ISSUE THREAD

**Issue by dun82** [RenderHeads/UnityPlugin-AVProVideo#634]
Problem description:

While running the demo in Unity Editor, an error pops up.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
Unity 2020.1.17f1
AVPro version 1.11.7

Device (which devices are you having the issue with - model, OS version number):

Windows 10 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

Using demo sample mkv (FantasyStereoFB360.mkv)

System Information:

AVPro Video: plugin v1.11.7 scripts v1.11.7
Target Platform: Standalone
Unity: v2020.1.17f1 WindowsEditor
OS: Desktop - MacBookPro12,1 (Apple Inc.) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz - 4 threads - 16286KB
GPU: Intel(R) Iris(TM) Graphics 6100 - Intel - Direct3D 11.0 [level 11.1] - 8143KB - 16384

**Comment by kahnivore** [comment]
Hey @dun82 

Saw you closed this issue. Not sure if you solved it or not so just in case - problem might be that Windows dropped native HEVC support a while back. So you'd need to install the extension from the Microsoft Store [here](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7?activetab=pivot:overviewtab).
