### ISSUE TITLE
[AVProVideo] Failed to load DLL. AVProVideo

### ISSUE THREAD

**Issue by jordanmuraskin** [RenderHeads/UnityPlugin-AVProVideo#635]
On Windows 10 build, Getting a Fallback handler error. 

> Fallback handler could not load library [...]/Mono/AVProVideo.dll
> Fallback handler could not load library [...]/Mono/AVProVideo
> Fallback handler could not load library [...]/Mono/libAVProVideo
> [AVProVideo] Failed to load DLL. AVProVideo 

Video plays on all other systems (Unity Editor, iOS,Android, macOS)

Unity Version: 2019.2.21f1
AVPro Version: 1.11.7
Operating System: Windows 10 Home

Have used on windows before and been fine. Not sure why this time I am having an issue. 
Could this have to do with unity removing the "Mono" folder?

Any help would be appreciated. 

Thanks

**Comment by AndrewRH** [comment]
I'm not sure why Unity would be removing the Mono folder? 

But no, the Plugin is builds gets built to the yourapp_Data/Plugins folder - so it should be in there.

If the plugin isn't in your build for some reason - then that's the problem.  If it is there, then there must be some dependency that the system doesn't have which then prevents the DLL from being loaded.

Thanks,

**Comment by jordanmuraskin** [comment]
Thanks for the quick response. 

Yes, the AVProVideo.dll is located in the Plugins folder after build. However, there isn't a libAVProVideo.dll in the plugins folder. I can't even find that file in the unity project for x86_64 builds. Is there supposed to be a libAVProVideo.dll in the plugins folder? If so, where should it be in the project?

**Comment by AndrewRH** [comment]
There is no such file as libAVProVideo.dll - I suspect Unity may just be searching for possible Mono libraries with the same name (for some unknown reason).  In the Plugins folder there should be AVProVideo.dll and Audio360.dll.

Also make sure that your plugin files are the correct architecture..  Perhaps somehow the plugins have lost their plugin architecture settings and it is copying in the 32-bit (Plugins/x86 folder) plugin files when it's a 64-bit build, or vice-verse.

Thanks,

**Comment by jordanmuraskin** [comment]
Thank you for the help. 

I figured out the issue. The AVProVideo and Audio360 dlls were in the Plugins folder when they needed to be in the Plugins/x86_64 folder. I am not sure why the build didn't put them in the correct folder. But after manually moving everything worked correctly.
