### ISSUE TITLE
Can't Play CMAF Mpeg Dash low laytency LiveStreaming

### ISSUE THREAD

**Issue by sjy9137** [RenderHeads/UnityPlugin-AVProVideo#639]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.12f1
 - AVPro Video version: Demo Ultra AVPRO  version 2.0.5
 - Operating system version: Window10
 - Device model: PC
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, 30fps, CMAF-MpegDash, 1000bps

**To Reproduce**
1. Can't Play CMAF Mpeg Dash low laytency LiveStreaming
2.  Just use Ultra AVPRO Demo
3. 

**Logs**
If applicable, add error logs to help explain your problem.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1164)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:599)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by sjy9137** [comment]
I just use Demo Packags.

**Comment by kahnivore** [comment]
Hi @sjy9137 - would it be possible to send the URL of your stream to unitysupport@renderheads.com? Then we can test it for you on our side. Thanks!

**Comment by Andjiang707** [comment]
Hello, I have the same problem, I cannot play m3u8 in CMAF format.
