### ISSUE TITLE
How to implement a custom HTTP header field on Android?

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#64]
Currently AVPro Video doesn't include any code examples showing how to use the custom HTTP fields on Android/ExoPlayer.

You would use it like this:

mediaPlayer.PlatformOptionsAndroid.httpHeaderJson = @"{ "mykey":"myvalue" }"';

For example, this could be used to pass a custom key to your web server for authentication.

Thanks,

**Comment by travismmorgan** [comment]
This does not work with ExoPlayer
