### ISSUE TITLE
iOS: App crashes when disconnecting headphones after scene change

### ISSUE THREAD

**Issue by WI-Lee** [RenderHeads/UnityPlugin-AVProVideo#640]
**Describe the bug**
iOS app crashes when disconnecting headphones after scene change.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.20f1
 - AVPro Video version: 2.0.7
 - Operating system version: iPadOS 14.4
 - Device model: iPad (8th generation)
 - Video specs (resolution, frame-rate, codec, file size): using RenderHeads-1080p30-H264.mp4

**To Reproduce**
1. Open `Demo_MediaPlayer` scene
2. Add a button to reload the current scene (e.g. `SceneManager.LoadScene("Demo_MediaPlayer")`)
3. Build and run on iOS
4. Disconnecting headphones works correctly
5. Press reload scene button
6. Disconnecting headphones now crashes the app

**Comment by MorrisRH** [comment]
A fix for this will be in the next release.
