### ISSUE TITLE
iOS TestFlight: Crash on exit with v2.0.7

### ISSUE THREAD

**Issue by JanOwiesniak** [RenderHeads/UnityPlugin-AVProVideo#643]
**Whats the issue?**

We started our project with v1.10.1 and upgraded until v1.11.7 without any issues in the past.
Our project is on v2.0.7 right now. We followed the upgrade guide but we are experiencing crashes on most of our iOS test devices (6s, 7, 8, 11) when user hard closes the app. This is happening all the time on the previous mentioned devices but only sometimes on a iPhone 12 Pro.

![PHOTO-2021-02-24-12-09-34](https://user-images.githubusercontent.com/213214/109160186-c54d7980-7775-11eb-92f3-9519b38fdb39.jpg)

The crashlogs pointed us to your library.

![Screenshot 2021-02-25 at 10 17 16](https://user-images.githubusercontent.com/213214/109159562-0a24e080-7775-11eb-8f8e-9c6fbaa2d049.png)

This is only happening when when the iOS App is distributed via TestFlight. It is not happening when i connect those devices to XCode and deploy the app.

I deactivated Unity code stripping and XCode optimizations as well to ensure it's not related to minifying (as someone mentioned in the Unity Forums) but this did not fixed it.

![Screenshot 2021-02-24 at 11 55 46](https://user-images.githubusercontent.com/213214/109160318-eb731980-7775-11eb-82c0-00844e71d75f.png)

We also tried to remove this line from `UnityCleanupTrampoline` as mentioned [here](https://github.com/firebase/quickstart-unity/issues/610#issuecomment-618897361) (without success) because further stack traces pointed into this direction (which indicates a memory leak when closing Unity)

```
 [_UnityAppController window].rootViewController = nil;
```

We downgraded back to v1.11.7, distributed via TestFlight and tested again.

The error is gone.

This whole thing seems to be related to 2.x + TestFlight.

I hope this information helps you to fix this issue.

**Comment by MorrisRH** [comment]
I've reproduced this, will get a fix in hopefully for the next release (2.0.8).

**Comment by JanOwiesniak** [comment]
Good to hear that i'm not the only one where this is happening.

Can you provide me with a hotfix? We need to release a major update of our software by the end of the week and this issue is certainly a blocker for us. Downgrading to v1.11.7 should only be last option here.

Can you tell me if this is happening for App Store versions as well or is this message a TestFlight feature only?
Never seen it before.

**Comment by MorrisRH** [comment]
Fixed, it will make it into the next release which is due later-today/tomorrow.
The crash will be in all versions, however I'm pretty sure that message is TestFlight only.

**Comment by MorrisRH** [comment]
2.0.8 is now available

**Comment by JanOwiesniak** [comment]
Hey @MorrisRH, thanks for the fast fix. v2.0.8 fixes this issue for me.
