### ISSUE TITLE
Application Crashing When Playing Video on  HTC Vive Focus Plus

### ISSUE THREAD

**Issue by shazamk** [RenderHeads/UnityPlugin-AVProVideo#644]
**Describe the bug**
Application crashes on start of playing a video with AVPro Media Player on the HTC Vive Focus Plus. Strangely, the crash SEEMS to only occur when you are in a scene with a lot of empty space(skybox) in view. 

**Additional Information
App does NOT crash on the Vive when playing a video where the display screen is placed in the middle of a 3d environment that blocks out majority of the skybox/background (For example, placing the display screen and camera in the middle of a coliseum -like 3d environment). A crash occurs as soon as you hide the 3d environment. From the log the first noticeable issue seems to be- Warn Adreno-GSL  failed: errno 71 Protocol error

**Your Setup (please complete the following information):**
 - Unity version:              2020.1.8f1
 - AVPro Video version:  Android Core 1.11.5 AND Trial version 2.0.5
 - Device model:             HTC Vive Focus Plus (FA03JAZ00063)
 - Video specs:                BigBuckBunny-360p30-H264.mp4 From demo

**To Reproduce**  *!(EDITED 2021-02-27)
1. Install Avpro Trial version 2.0.5, 2.0.9
2. Load Demo_Mediaplayer scene that comes with AVPro
3. Set MediaPlayerUI canvas render mode to screen space camera 
4. Add Vive Wave XR package to Unity

5. Build and play on the HTC Vive Focus Plus

**Logs**
[AvproTest-logcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6219911/AvproTest-logcat.txt)

**Comment by RenderHeadsSte** [comment]
There is nothing of very much to on on in the log you have posted.  We could expect to see a number of 'AVPro' log lines.  Can you send over a complete logcat dump?

**Comment by RenderHeadsSte** [comment]
Another thing to try @shazamk.  Have you applied the >= 2020.1.x fix outlined [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#unity-20201-and-above)?

Symptom of this is usually an outright crash of the app instantly, but worth applying if you have not already.

**Comment by shazamk** [comment]
Thank you I'll take a look. I will provide an updated log as soon as I get a chance.

**Comment by RenderHeadsSte** [comment]
There is still no reference to AVPro in your log @shazamk.  Are you filtering it?  We need it to be set to 'Verbose' so we have all the information.

**Comment by shazamk** [comment]
Sorry for the lack of response, I got tied up in other stuff.  In the **Additional Information** of my post, I mentioned the app would close when I hide the environment. Clearing the GI cache as mentioned by the user in issue #499 fixed this issue.  I haven't yet tested to see if this resolved the crashing issue in the mediaplayer demo. I will get back to you by the weekend. Thanks for the help.

**Comment by RenderHeadsSte** [comment]
Awesome, thanks @shazamk.  Looking forward to getting an update from you :)

**Comment by shazamk** [comment]
I'm still experiencing the app crashing when building the Demo_Mediaplayer scene for the Vive. I've also tested it with Unity 2019.4.12.f1  and Avpro 2.0.9 and experience the same issue. Something I didn't mention before which is important is that we're using Vive Wave XR 1.0.1 package for Unity. I've updated the logs and made sure there were no filters on (they are some RenderHeads logs present now). Thanks!

**Comment by RenderHeadsSte** [comment]
Still crashing when applying the fix from #499 ?

**Comment by RenderHeadsSte** [comment]
Looking at your log now.

This is a bit odd...?

Error Unity Unable to find OculusXRPlugin
Error Unity DllNotFoundException: Unable to load DLL 'OculusXRPlugin': The specified module could not be found.
Error Unity   at Unity.XR.Oculus.OculusLoader.LoadOVRPlugin (System.String ovrpPath) [0x00000] in <00000000000000000000000000000000>:0 
Error Unity   at Unity.XR.Oculus.OculusLoader.RuntimeLoadOVRPlugin () [0x00000] in <00000000000000000000000000000000>:0

**Comment by RenderHeadsSte** [comment]
...and a ton of:

Error libEGL eglMakeCurrent:818 error 3002 (EGL_BAD_ACCESS)
Error Unity [EGL] Unable to acquire context: EGL_BAD_ACCESS: EGL cannot access a requested resource (for example a context is bound in another thread). 
Error Unity (Filename: ./Runtime/GfxDevice/egl/WindowContextEGL.cpp Line: 274)

**Comment by shazamk** [comment]
Yeah. Clearing the GI cache doesn't stop crashing.  I'll look more into those errors and try my best to get back to you tomorrow. Thanks

**Comment by shazamk** [comment]
Sorry again for the delay. We are using a Unity package for green screen keying and we noticed that when we get the texture directly from AVPro MediaPlayer and pass it to the keying component (from green screen package) to key and display it **avoids** the crash. One notable thing that is happening in that keying component is that the texture we get from AVPro is being copied using RenderTexture.DiscardContents() and Graphics.Blit(). I didn't get a chance to look further into yet.
