### ISSUE TITLE
MediaPlayer.ExtractFrame return Gray texture when Use Fast OES path is enabled for Android.

### ISSUE THREAD

**Issue by Adeptus-Mekanicus** [RenderHeads/UnityPlugin-AVProVideo#646]
**Describe the bug**
After selecting Use Fast OES Path MediaPlayer.ExtractFrame returns gray texture.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.20
 - AVPro Video version: 1.10.2
 - Operating system version: Android
 - Device model: Pico G2 4K
 - Video specs (resolution, frame-rate, codec, file size): 4096x2048, 29.97, h265, 120Mb

**To Reproduce**
1. Enable Use Fast OES Path
2. MediaPlayer.ExtractFrame
3. See the results

**Comment by kahnivore** [comment]
Hey @Adeptus-Mekanicus 

1) is there a particularly reason you're using version 1.10.2? We'd recommend updating to the latest version of 1.x (1.11.7) for better performance generally. 

2) The extract frame code doesn't support OES currently (although will in the future) - have you tried without OES? Extracting a frame is a quick operation and so using OES is not particularly beneficial here anyway.

**Comment by Adeptus-Mekanicus** [comment]
@kahnivore  without OES it is working as expected. So I will switch back on non-OES for now.
