### ISSUE TITLE
PlaylistMediaPlayer bug preventing adding item in inspector

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProVideo#647]
**Describe the bug**
When trying to 'insert item' Playlist Media Player component a null ref is thrown and an item cannot be added. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.18
 - AVPro Video version: 2.0.7
 - Operating system version: Windows 10
 
**To Reproduce**
1. Import AVPro
2. Create a PlaylistMediaPlayer Component
3.  Insert Item (if the inspector collapses on itself remove component and recreate)

**Logs**
If applicable, add error logs to help explain your problem.
![playlistmediaplayer](https://user-images.githubusercontent.com/44468274/109327124-a8da3b80-7860-11eb-965a-be285747bca5.PNG)

**Comment by AndrewRH** [comment]
This has been fixed and will be included in the next release.
