### ISSUE TITLE
FirstFrameReady is not called until video is played on WebGL (Chrome and Edge)

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProVideo#649]
**Describe the bug**
 Info from keeping:

I have a problem with the event FirstFrameReady: under specific circumstances it is not called until the video is played, showing a black screen instead of a preview of the first frame from the video source.

This problem occurs only in browsers like Chrome and Edge, and only from a build hosted to an online server, while using a localhosted build works correctly.
In the Firefox browser this problem doesn't exist, neither using the localhost nor using the online server.

Looking on internet, I saw in an older documentation of the plugin (version 1.9.12, Link) this specific note (section: 6.4.3 Event):
FirstFrameReady - Called when the first frame has been rendered. (NB: This event
currently doesn’t get fired for certain browsers in the WebGL build. This includes all
non-mozilla non-webkit browsers)
and I was wondering if this problem was fixed in the newer version of AVPro Video. Looking in the current documentation I couldn't find anything about this problem.

I've also found that this event isn't called due to this check into the MediaPlayer_Events partial class into CanFireEvent() method at R.213:

![image (15)](https://user-images.githubusercontent.com/44468274/109328933-ae388580-7862-11eb-84b7-f9bfb7db7462.png)

Debugging these checks, the only one that returns False is the last one: "_textureInterface.GetTextureFrameCount() > 0"; GetTextureFrameCount() method returns a value of 0

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1
 - AVPro Video version: Core 2.0.7 with ApplyToMesh

**Comment by AndrewRH** [comment]
Yes I have reproduced this issue.  Firefox doesn't seem to have this problem, but Edge and Chrome do.  When streaming an MP4 file, no initial frame will be rendered until play is pressed.  This is different when playing back local media.
Investigating...

**Comment by AndrewRH** [comment]
We have fixed this issue and the fix will be included in the next release.

The fix involves some updates file (attached), and also potentially setting "Run in Background" in the Player Settings.

[webGlFix.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6064683/webGlFix.zip)

Do let us know how this fix works for you.

Thanks,

**Comment by AndrewRH** [comment]
@kahnivore please point the user to these updated notes 👍

**Comment by Elvuis** [comment]
Hi, I'm the user who asked for support regarding this problem.

Just want to let you know that replacing the attached files works.

Thanks for your help
