### ISSUE TITLE
Add migration guide for 1.x to 2.x users to docs 

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProVideo#650]
This could be useful for users who are used to AVPro 1.x who are starting new projects using 2.x. Also as a quick change in API reference, and those who upgrade within the same project (although this is not recommended).

**Comment by AndrewRH** [comment]
This has been done and will be included in the next release

**Comment by AndrewRH** [comment]
Actually I've made this live now:
https://www.renderheads.com/content/docs/AVProVideo/articles/upgrading-from-avpro-video-1x.html
