### ISSUE TITLE
The 2.0.8 AVPro Core Edition package still contains the 2.0.7 Mac bundle

### ISSUE THREAD

**Issue by TheloTheGreat** [RenderHeads/UnityPlugin-AVProVideo#651]
The Unity package for AVPro Core edition for Mac, marked as 2.0.8, still contains the 2.0.7 version of the bundle. It's shown as 2.0.7 in the MacOS "Get Info" screen, it's the same size as the 2.0.7 bundle, and it doesn't fix the 2.0.8 issues.

The trial package for 2.0.8 seems correctly updated, it's just the Core edition package from the Asset Store that's incorrect.

Probably just a missed update on your side.

**Comment by AndrewRH** [comment]
Investigating..

**Comment by MorrisRH** [comment]
As far as we can tell the package on the store is 2.0.8.
I suggest that you install it into a fresh Unity project and check as it sounds like something went awry with the update process.

**Comment by TheloTheGreat** [comment]
Looks like you're right, Unity had a failed package update to 2.0.8, and displayed having 2.0.8 even though what it kept downloaded in its download cache was 2.0.7.

Reimporting it into a fresh project did not work, that just reinstalled the 2.0.7 bundle. I had to manually delete the Unity asset store cache at "~/Library/Unity/Asset Store-5.x" to clear the bad state, then redownload and reimport from there, then that worked out.

Thanks for taking the time to check this out.
