### ISSUE TITLE
Crashed in the real device Android. 

### ISSUE THREAD

**Issue by stevekim0417** [RenderHeads/UnityPlugin-AVProVideo#656]
**Describe the bug**
When I installed the example scene include in the AVPro Assets, it is crashed on the real device Android. 

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.6.f1
 - AVPro Video version: 2.0.8
 - Operating system version: Mac OS(Unity), Android 8 
 - Device model: Galaxy A90 5G
 - Video specs (resolution, frame-rate, codec, file size): the videos in the AVPro Assets 

**To Reproduce**
1. I installed the example scene in the real device.
2. it crashed when it launched. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Have you followed the fix outlined [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#unity-20201-and-above) for 2020.1 and above?

If not, give that a try.  If you are then still seeing an issue, please do send over a full logcat output so we can diagnose.

**Comment by AndrewRH** [comment]
@stevekim0417 does the fix above solve your issue?

Thanks,
