### ISSUE TITLE
Mac: Video colors are incorrect, "washed out"

### ISSUE THREAD

**Issue by TheloTheGreat** [RenderHeads/UnityPlugin-AVProVideo#658]
When I play a video in AVPro on Mac (but not on Windows), its colors look incorrect, "washed out". They look different from playing the same video file in Unity VideoPlayer, or in Quicktime or VLC, where the colors appear correctly.

Example from the Demo_MediaPlayer scene (in AVPro 2.0.8) playing a short example video, with AVPro on the left (incorrect) and Quicktime on the right (correct):
https://thelo.ca/AVPro-Quicktime-Mac-colors.png

That short video file is:
https://thelo.ca/spiderman_featured_anim.mp4

(One thing I noticed is that when playing that video file in the demo scene, AppleMediaPlayer.PlayerSupportsLinearColorSpace returns false. Is that correct? The underlying OS certainly has no problem playing that video file correctly outside of AVPro.)

**Comment by kahnivore** [comment]
Which version of Unity are you using?

**Comment by TheloTheGreat** [comment]
Unity 2020.2.1

**Comment by MorrisRH** [comment]
There was an issue with the BT.709 colour space conversion, a fix will be in the next release.

**Comment by TheloTheGreat** [comment]
Fix confirmed in 2.0.9, thanks.
