### ISSUE TITLE
Can AVProVideo play mp3 files?

### ISSUE THREAD

**Issue by reysantana** [RenderHeads/UnityPlugin-AVProVideo#660]
I would like to know if AVProVideo can play mp3 files

**Comment by kahnivore** [comment]
Hi @reysantana 

Yes it can. 

You're welcome to test it using our free trial versions which can be found [here](http://renderheads.com/downloads/).

**Comment by AndrewRH** [comment]
@reysantana  see the full list of supported media here:
https://www.renderheads.com/content/docs/AVProVideo/articles/supportedmedia.html

**Comment by AndrewRH** [comment]
This is answered so I am closing the thread.
