### ISSUE TITLE
Unlit stereo shader doesn't support only renders a single eye when Stereo Rendering mode is set to Single Pass Instanced

### ISSUE THREAD

**Issue by psy-ankka** [RenderHeads/UnityPlugin-AVProVideo#661]
**Describe the bug**
Non-VR videos are renderer only to one eye if OpenVR XR plugin is used and it's Stereo Rendering Mode is set to Single Pass Instanced.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1, 2020.2.3f1 and 2020.2.6f1
 - AVPro Video version: AVPro Video v2.0.5 (native plugin v2.0.5f1-core)
 - Operating system version: Windows 10, 1909
 - Device model: SteamVR (Oculus Link)
 - Video specs (resolution, frame-rate, codec, file size): Any video

**To Reproduce**
1. Create project using any of the Unity version above.
2. Add Unity XR Management, OpenVR XR plungin and SteamVR
3. Enable OpenVR XR plugin and set Stereo Rendering Mode to _Single Pass Instanced_
4. Create video surface which uses `AVProVideo-Unlit` shader.
5. Run scene and play video. The video will render in only in the left eye.

Expected result: Video renders normally in Single Pass Instanced for OpenVR.

This is most likely due to missing support in non-VR shader for the [Single Pass Instancing support](https://docs.unity3d.com/Manual/SinglePassInstancing.html). Curiously the AVProVideo-VR-* shaders seem to support this, but the same support is needed for non-VR video surfaces as well.

**Comment by kahnivore** [comment]
Hi @psy-ankka 

Thanks for pointing this out. 

We've added this as an enhancement and will add the instancing code to the Unlit shader in a future update. 

In the meantime you could just use the VR shader if this is a suitable workaround?

**Comment by AndrewRH** [comment]
@psy-ankka 
Here is the updated shader.  Do let us know if this works for you.

[AVProVideo-Unlit.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6091322/AVProVideo-Unlit.zip)

Thanks,

**Comment by jukka-at-fake** [comment]
> @psy-ankka
> Here is the updated shader. Do let us know if this works for you.
> 
> [AVProVideo-Unlit.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6091322/AVProVideo-Unlit.zip)
> 
> Thanks,

Thanks for the quick reply! The fix works :)
