### ISSUE TITLE
Is there a function to play video files in the resource folder?

### ISSUE THREAD

**Issue by darydol** [RenderHeads/UnityPlugin-AVProVideo#663]
Is there a function to play video files in the resource folder?

**Comment by darydol** [comment]
Is there a function to play video files in the resource folder?

**Comment by kahnivore** [comment]
Hi @darydol 

This would work in the editor but not in a build. The way Unity packages the folder makes the files inaccessible.

**Comment by darydol** [comment]
Thank you.
