### ISSUE TITLE
[AVProVideo] Initialising AVPro Video (script v1.11.7 plugin v1.7.3) on NVIDIA GeForce RTX 2060/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor Windows 10  (10.0.0) 64bit

### ISSUE THREAD

**Issue by GrayZYH** [RenderHeads/UnityPlugin-AVProVideo#666]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 
 - AVPro Video version: 
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by GrayZYH** [comment]
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by GrayZYH** [comment]
[AVProVideo] Initialising AVPro Video (script v1.11.7 plugin v1.7.3) on NVIDIA GeForce RTX 2060/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor Windows 10  (10.0.0) 64bit

**Comment by GrayZYH** [comment]
How to solve this problem? [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by RenderHeadsSte** [comment]
Please provide all the details in the issue template, including details of the video you are trying to playback.  Alternatively, send over the video to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com).

**Comment by GrayZYH** [comment]
Well, it's OK to play one or 26 videos at the same time using the MediaPlayer plugin, but I reported this error when I played the 27th video at the same time.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProVideo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 晚上8:05
收件人:&nbsp;"RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com&gt;;
抄送:&nbsp;"侧影"<2206629756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] [AVProVideo] Initialising AVPro Video (script v1.11.7 plugin v1.7.3) on NVIDIA GeForce RTX 2060/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor Windows 10  (10.0.0) 64bit (#666)





 
Please provide all the details in the issue template, including details of the video you are trying to playback.  Alternatively, send over the video to unitysupport@renderheads.com.
