### ISSUE TITLE
Pico G2 4K stereoscopic glitch

### ISSUE THREAD

**Issue by hrlarsen** [RenderHeads/UnityPlugin-AVProVideo#667]
**Describe the bug**
When rendering stereoscopic videos on the Pico G2 4K headset, the left and right eye image gets switched when turning

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.17f1 
 - AVPro Video version:  2.08
 - Operating system version: Android, 
 - Device model: Pico G2 4K
 - Video specs (resolution, frame-rate, codec, file size): mkv or mp4

**To Reproduce**
1. Include Pico SDK
2. Open the Demo_360Stereo, Build and run

When moving the head around (from the demo video) it is very hard to see the glitch, but is most notable when looking downwards in the demo video. Try with another "realistic" video to see the glitch more easy, video attached for reference.

**Videos**
Recorded through the lens
https://user-images.githubusercontent.com/6569130/110339182-26076c80-8028-11eb-981b-ef410bc612ce.MOV

**Comment by RenderHeadsSte** [comment]
This is a little hard to diagnose without more information.  Can send over the following:

- full logcat dump
- screen grab of your XR settings

**Comment by hrlarsen** [comment]
Thanks for mentioning XR settings, because with the PicoVR Unity SDK it works a bit like the old Google Cardboard SDK. That got me thinking, that there might be a Unity XR SDK for Pio. 

There is, and I just tried switching to the Pico XR Platform SDK and that solves the issue, so it is only related to using PicoVR Unity SDK. The issue is solved for me for now by switching SDK.

**Comment by kahnivore** [comment]
Thanks for letting us know!

**Comment by mbzworld** [comment]
I am having the exact same issue here. I just want to add that in my case, this bug only occurs while using the Android OES rendering. 
I also noticed the following:
- When Pico SDK Head Position Tracking is ON (Pico G2 4K is only 3DOF) the bug appears to be like the following: While looking straight forward within about 45 degrees the picture appears normal and stereoscopic. Beyond that it becomes monoscopic. However, if you look behind you 180 degrees, there is another 45 degree range where stereoscopic is normal
- When Head Position Tracking is OFF, the front range where stereoscopic is normal increases to about 150 degrees. However, beyond that eyes get reversed! So, foreground becomes background and vice versa, Very annoying. 

May I ask how much OES is better than regular playback, in terms of a percentage on the Pico G2 4K (Snapdragon 835)?
I just want to see if it is worth it to upgrade my project to Unity 2020 XR which might take few weeks of work. In my case, the Pico G2 4K seems to be able to handle my video file just fine without OES. However, I am not sure about battery consumption/heat etc.

Unity version: 2019.4.25f1
AVPro Video version: 2.1
Operating system version: Android
Device model: Pico G2 4K
Video specs (4096x4096 30fps, mp4 HEVC (H.265), 15mb)

**Comment by mbzworld** [comment]
Not sure if I should have posted this in a separate issue but I thought it fits here since it is the exact same issue.

**Comment by RenderHeadsSte** [comment]
Are you using the PicoVR SDK, or the newer Pico XR Platform SDK?  The former seemed to be the problematic link in the chain for the OP.

Am very interested to hear more about your issues...as OES should not really affect things in the way you are seeing.  It is essentially just a way for a shader to access an external texture directly for rendering.

If you feel you want to explore the issue and if there is a solution, please do open a new github issue @mbzworld .

We have no benchmarking figures for specific devices.  OES mode essentially avoids an internal blit and so you see performance increases...and therefore less battery consumption...and thus less heat generated.  My call on it would be...if you are using video playback for large parts of your software experience, then if you can make OES work by upgrading Unity (not sure why this is going to make a difference?) then do it.  If on the other hand, you are just playing the occasional  video here and there, you will likely not see much or any real world gains.

**Comment by mbzworld** [comment]
I am using the PicoVR SDK. My app is basically a video playback software, playing mainly high resolution VR videos (4096x4096) so OES might be beneficial to my use case. 

I do agree this issue is weird. I am considering upgrading to XR but I am still not familiar with the work flow. Plus some of my assets are not compatible with Unity 2020.

Any advise on how to fix this? Do you have a Pico G2 4K on hand? The issue can be easily replicated in few minutes.

**Comment by RenderHeadsSte** [comment]
We don’t have a Pico G2 4K in hand unfortunately.

I would suggest creating a bee test project, import AVPro Video, setup Pico XR, load our 360 demo scene, set it up for OES. Test on the Pico.

It appears the Pico VR SDK is a bit iffy.

**Comment by mbzworld** [comment]
I just did what you suggested and it seems that the issue doesn't happen in Pico XR. I guess that's the way to go.

On a side note, I am an old customer of AVPro 1.x and recently purchased the 2.x. Totally worth the investment, a great asset just became spectacular. Keep it up!

**Comment by mbzworld** [comment]
I just conducted a performance comparison between OES and a regular shader. OES consumed about 20% less battery. I think this is impressive.
