### ISSUE TITLE
Pico G2 4K MKV Facebook 360 playback slow

### ISSUE THREAD

**Issue by hrlarsen** [RenderHeads/UnityPlugin-AVProVideo#668]
**Describe the bug**
When playing MKV files from the Pico G2 4K headset, the video playback is lacking. The app itself runs at 60 fps, but the playback seems to be around 5 fps.

I have tried both with and without OES rendering, but no difference.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.17f1
 - AVPro Video version: 2.0.8
 - Operating system version: Android 8.1
 - Device model: Pico G2 4K
 - Video specs (resolution, frame-rate, codec, file size): 5600x5600, 29.97 fps, 1.44 gb, bitrate: 40 Mbps, MKV w. Facebook 360 audio

**To Reproduce**
1. Create a scene, and add pvr_UnitySDK prefab
2. Setup playback of MKV video from sdcard with Facebook 360 audio
3. Build and run

**Videos**

https://user-images.githubusercontent.com/6569130/110340734-dc1f8600-8029-11eb-91fc-0efb41d989b7.mp4

**Comment by RenderHeadsSte** [comment]
I am not sure the Pico G2 4k can decode that resolution quickly enough.  See [here](https://headjack.io/knowledge-base/best-video-resolution-for-pico-headsets/).

Have you tried a lower resolution?

**Comment by hrlarsen** [comment]
Thanks for pointing me in that direction. Lowering the resolution of the video to 4K (4096x4096) solved the issue.
