### ISSUE TITLE
Support HAPR

### ISSUE THREAD

**Issue by fingerx** [RenderHeads/UnityPlugin-AVProVideo#671]
please see[https://jokyohapencoder.com/jokyo-hap-meencoder-hap-encoder-plugin-for-adobe-media-encoder-and-premiere-pro/]

thanks

**Comment by MorrisRH** [comment]
HapR support is already available in AVPro Video v2.x on the following platforms:
- macOS
- Windows, requires Direct3D 11 and either the DIrectShow or MediaFoundation APIs.

**Comment by fingerx** [comment]
thanks
