### ISSUE TITLE
Probable memory leak in when closing video files. 

### ISSUE THREAD

**Issue by vedranskarica** [RenderHeads/UnityPlugin-AVProVideo#672]
**Describe the bug**
Probable memory leak in when closing video files. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.21
 - AVPro Video version:  AVPro Core 2.0.9
 - Operating system version: Windows 10, Android 10.0, Oculus Quest
 - Device model: Desktop PC, Oculus Quest 1 and 2, several Android phones
 - Video specs (resolution, frame-rate, codec, file size): varied, from your sample Cones-360Mono-4K60-HEVC.mp4 to 7680x3840 30fps 100Mb/s HEVC 200MB video

Developing a VR application that needs to play multiple videos on the same scene we ran into a
problem with Oculus Quest where no more than two videos at the time could be loaded or
opened simultaneously. Solution to this problem should have been to create a custom playlist
that would play one video while loading the next.
Attempt 1
On the first try there were two Media Player Components on two separate empty objects
referenced through the script. The script also had references to two seperate Media Reference
objects. Each Media Reference object points to its own mp4, 15 second long, 8K video.
The event listener was added through the script for both Media Player objects. On start Media
Reference was assigned to the first Media Player using OpenMedia method and the Play
method was called. Once the video was done playing, the Media Player was closed using the
CloseMedia method and the other Media Reference was assigned to the other Media Player
which was then opened, played and closed after the video was done. This was alternated three
times before application started to show behaviour alike to memory leak.
Attempt 2
This time references given through event handling weren’t used, instead the OpenMedia and
CloseMedia methods were called on local Media Player references. On the fourth round the
application starts to consume more memory after each OpenMedia call, or rather doesn’t
release all of the memory after the CloseMedia method call.
Attempt 3
Not using the events. The alternation was done on only one Media Player using coroutines and
waiting until the video is done, closing it and opening the next video. The same memory
problem was noticed again.
Attempt 4
Last try was done using only one video and one Media Player. No events.The Open Media
method was called, waited until the video was done, then Close Media method was called and
after that opened again and so on. When that didn’t work, all of the attempts were done again
using paths instead of Media References and recreated in a regular 3D scene. Memory still
leaked.
Calling the ForceDispose method before opening media made memory usage grow
continuously from the first try of playing the video.

Problem is present when running in editor as well as on several devices (Quest, Quest 2, and regular Android smartphones we tested for consistency)

**Comment by kahnivore** [comment]
Hi @vedranskarica 

We haven't seen any memory leak issues so we'd need to reproduce this to figure out what's going on here. Is there any chance you could please send us a reproducible case? You could send to unitysupport@renderheads.com.

We'd also need to know how you are measuring this memory leak so that we can do so in the same way. Can you also tell us how much memory is leaking and how often? 

Have you tried flushing the garbage collection and resources when you close a video using GC.Collect(); and Resources.UnloadUnusedAssets();?

Is there a chance you could also try recreating this on a blank project using our sample videos to see if you get the same behaviour? 

Thanks!

**Comment by kahnivore** [comment]
Hi @vedranskarica any word on this? We've just released version 2.0.10, and it would be a good idea to update and see if this solves your issue. 

Thanks.

**Comment by kahnivore** [comment]
Closing because has gone stale awaiting user response. @vedranskarica let us know if you've solved this or can reopen if it's still an issue. 

Thanks.
