### ISSUE TITLE
Gamma correction in linear space not the same as Gamma color space

### ISSUE THREAD

**Issue by prisonerjohn** [RenderHeads/UnityPlugin-AVProVideo#673]
**Describe the bug**

I'm not sure if this is a bug or not, but I'm using AVPro Video in a project in linear color space, and the result after the gamma correction applied is darker than if the project was just in gamma color space.

Here are some screenshots, gamma on top, linear on the bottom. The video is mapped to the bridge shape and has the same (baked) lighting applied to it. You can really see the difference in the bright spots on the right column.

<img width="493" alt="frame-gamma" src="https://user-images.githubusercontent.com/119702/110635930-a8537600-8179-11eb-8f60-735138b9e814.png">
<img width="490" alt="frame-linear-corr-acc" src="https://user-images.githubusercontent.com/119702/110635933-a8ec0c80-8179-11eb-9d09-200ff79c228c.png">

Is my understanding of how the correction is supposed to work accurate? Should those two frames be identical?
If so, any ideas what could be happening? Is there a setting somewhere else I should be using?
I tried setting the color space to Rec 709 (and others) and while that does change the color, there is still a discrepancy between the gamma and linear/gamma-corrected versions.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.5f1
 - AVPro Video version: 1.11.7
 - Operating system version: Windows 10 but project is targeting Android. I'm seeing similar issues both in editor and on the device. Those screenshots were taken on the device.
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 4096x4096, H264, 23.97fps.,ITU-R BT.709 color

**Comment by kahnivore** [comment]
Hey @prisonerjohn,

Could we possibly get the video you're using (or a snippet of the video) so we can test this? You can send it to unitysupport@renderheads.com.

Thanks!

**Comment by AndrewRH** [comment]
@prisonerjohn 
Thanks for submitting this.  Yes we have reproduced the issue and narrows it down to the shader where it's using a cheaper approximation of the Gamma to Linear colourspace conversion.  We will have a think abou how to better expose the selection of shader quality for the next update.

For now though a workaround is to edit AVProVideo.cginc and remove the GammaToLinear function and replace it with this:

	INLINE HALF3 GammaToLinear(HALF3 col)
	{
	// Accurate version
		if (col.r <= 0.04045)
			col.r = col.r / 12.92;
		else
			col.r = pow((col.r + 0.055) / 1.055, 2.4);

		if (col.g <= 0.04045)
			col.g = col.g / 12.92;
		else
			col.g = pow((col.g + 0.055) / 1.055, 2.4);

		if (col.b <= 0.04045)
			col.b = col.b / 12.92;
		else
			col.b = pow((col.b + 0.055) / 1.055, 2.4);
		return col;
	}

Does this fix the issue for you?

Thanks,

**Comment by prisonerjohn** [comment]
Hi just a note that I didn't forget about this, I'm blocked by #698 at the moment, but can check once that is resolved!

**Comment by AndrewRH** [comment]
Great, okay thanks

**Comment by AndrewRH** [comment]
This should be fixed so I'm closing it
