### ISSUE TITLE
Vertical video support?

### ISSUE THREAD

**Issue by michalek-marcin** [RenderHeads/UnityPlugin-AVProVideo#675]
**Describe the bug**
I found that post on Unity forum: https://forum.unity.com/threads/released-avpro-video-complete-video-playback-solution.385611/page-51#post-3554268

I tried to play vertical video (1080x1920 resolution) using DisplayUGUI and Unity gives me error: `[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.4
 - AVPro Video version: 1.11.7
 - Operating system version: Windows 10
 - Device model: Windows PC / iOS device
 - Video specs (resolution, frame-rate, codec, file size): 1080x1920, framerate: 24, bitrate 128 kb/s, codec: MPEG (h264)

**Logs**
`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`

**Videos**
https://drive.google.com/file/d/1yy4EUjpVqc9U2VizImlIcAP-D9yagDiY/view?usp=sharing

**Comment by kahnivore** [comment]
Hi @michalek-marcin 

It looks like the audio from this video is in mp3 format - the standard audio format for H.264 is AAC and some players won't allow mp3. We tried stripping the audio and the video played - so your best bet is re-encoding with AAC audio. 

Let us know if you come right?

**Comment by RenderHeadsSte** [comment]
Anything to report on this one @michalek-marcin ?
