### ISSUE TITLE
Could you tell me how to set video AssetBundle file generated from MP4 to the Unity AVProVideoPlayer in Unity?

### ISSUE THREAD

**Issue by takayoshishimizu** [RenderHeads/UnityPlugin-AVProVideo#676]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version:  n/a
 - AVPro Video version: n/a
 - Operating system version: Windows10
 - Device model: PC
 - Video specs (resolution, frame-rate, codec, file size): n/a

**To Reproduce**
n/a

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @takayoshishimizu 

Unfortunately we don't support opening videos from within asset bundles.

There is currently no way we can do this.

**Comment by takayoshishimizu** [comment]
Thanks for your quick reply! How about setting an instance data loaded as
mp4 format to your AV pro video?

2021年3月13日(土) 0:21 kahnivore ***@***.***>:

**Comment by takayoshishimizu** [comment]
I'd like to know the AVProVideo API to set Video Clip data directly for playback MP4. I know how to load Vide Clip Data from AssetBundle file.

**Comment by kahnivore** [comment]
Video Clips are Unity's own format, we don't support playing those unfortunately.
