### ISSUE TITLE
[#E08or] Get Safari to play videos - currently blocks them if they contain audio

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#68]
When building for WebGL on Safari, the videos (mp4 and m3u8) don't play if the video contains audio.  This seems to be a feature of Safari but we need to find a solution to this.

The same happen with the standard Unity VideoPlayer, but with it you get the console message
"Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

It seems that Safari can only play the video if it is triggered by user interaction.  I guess this has to be via normal HTML and not something in JS?

**Comment by AndrewRH** [comment]
We've made some improvements to this.

1) We now log an error if playback fails
2) We now try to play the video anyway, but with audio muted

We will put this change into the next version, but for now you can edit AVProVideo.jslib line 370:

`AVPPlayerPlay: function (playerIndex) {`

replace this function with:

`       AVPPlayerPlay: function (playerIndex) {
        if (!_hasVideos(playerIndex)) {
            return false;
        }

		// https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/
		// https://developers.google.com/web/updates/2017/06/play-request-was-interrupted
        var playPromise = _videos[playerIndex].video.play();
		if (playPromise !== undefined) 
		{
			playPromise.then(function() {
			  // Automatic playback started!
			  // Show playing UI.
			 })
			 .catch(function(error) {
			  // Auto-play was prevented
			  // Show paused UI.
			  if (!AVPPlayerIsMuted(playerIndex))
			  {
			  	console.error("[AVProVideo] Video failed to start playback - check your browser permission settings as videos that contain audio can be blocked by default.  Muting video and attempting playback again.");
			  	AVPPlayerSetMuted(playerIndex, true);
			  	AVPPlayerPlay(playerIndex);
			  }
			});
		}
		return true;
    },`

I'm still not sure though how you would create a user interaction in Unity WebGL that would be equivelent to something like an HTML button press which would then allow videos with audio to play back..

Currently you either have to have videos with no audio, or you have to got the Safari settings and allow audio for the site.

**Comment by AndrewRH** [comment]
The above fix is included in v1.9.16

**Comment by DanieleSuppo73** [comment]
I don't know if it's directly related to the browser, but we experienced a strange issue on Chrome too.
During video playback, or after video was stopped, we get the error (on Chrome)
"Failed to execute 'setValueAtTime' on 'AudioParam': The provided float value is non-finite".

And obviuosly the web app crash.

**Comment by DanieleSuppo73** [comment]
P.s. the audio parameter of MediaPlayer was muted...

**Comment by daerxi** [comment]
I am also having this issue, did you figure it out?

**Comment by AndrewRH** [comment]
All browsers now don't play videos that contain audio.  We work around this currently by trying to detect this and then starting playback with the video muted.

There is a more general problem where video playback requires user interaction (ie a button click) to play with audio.  This can be hacked using an invisible HTML button over the video area.  See #770 for suggestion.

This would be tricky to add to AVPro Video WebGL plugin in general.....  

Closing this issue now as #770 seems to cover this.
