### ISSUE TITLE
AVPro Video (2.0.9) does not work on iOS 11 or lower devices

### ISSUE THREAD

**Issue by NakaharaYuichi** [RenderHeads/UnityPlugin-AVProVideo#680]
**Describe the bug**

I introduced AVProVideo to my project. It worked fine on Android devices and iPhones with iOS 14 or higher, but on devices with iOS 11 or lower, it crashes immediately after launching the app. When I introduced the trial version of 1.x series (https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/1.11.7) as a trial, this problem did not occur. Please tell me how to solve this. Is it possible to obtain the official version of 1.x series?

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.22
 - AVPro Video version: 2.0.9
 - Operating system version: iOS11
 - Device model: iPhone10.2
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Import AVPro Video into my Unity project (no files moved after import).
2. build.
3. Launch the app.

**Logs**
> Termination Description: DYLD, Library not loaded: @rpath/AVProVideo.gramework/AVProVideo

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @NakaharaYuichi 

Please see iOS platform notes [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html) - iOS 11.0 and later are supported. See also the section under troubleshooting - let us know if setting the AVProVideo.framework to Embed & Sign solves your issue? 

We do also offer 1.x to 2.x license holders. If you would like a copy please send your 2.x Unity invoice to unitysupport@renderheads.com.

**Comment by NakaharaYuichi** [comment]
Hi @kahnivore 

I emailed unitysupport@renderheads.com. for the official version of 1.x. (from takada).
Please answer here.

Best regards,

**Comment by NakaharaYuichi** [comment]
I made sure the AVProVideo.framework is set to Embed & Sign in the Frameworks, Libraries. but the problem is not resolved.
The version of xcode is 12.4

![AVProVideo](https://user-images.githubusercontent.com/8326615/111433250-6611d200-8741-11eb-9751-0e04fc6102c8.png)

**Comment by InseiRobin** [comment]
Hi @NakaharaYuichi 

I had the same issue. It was solved by selecting "Always Embed Swift Standard Libraries" in the Build Settings.
![Screenshot_20210318_130028](https://user-images.githubusercontent.com/2786044/111623690-fd7f2f80-87ea-11eb-868d-9b902a07deaf.png)
https://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib

Regards,

**Comment by NakaharaYuichi** [comment]
Hi @InseiRobin 

Thank you for the information !
I'll try !

Regards,

**Comment by kahnivore** [comment]
Package sent via keeping.
