### ISSUE TITLE
[Mac] MediaPlayer.Control.IsPlaying incorrectly returns true immediately after MediaPlayer.OpenMedia with autoPlay:false

### ISSUE THREAD

**Issue by TheloTheGreat** [RenderHeads/UnityPlugin-AVProVideo#685]
On Mac AVPro 2.0.9, but not on Windows, right after calling MediaPlayer.OpenMedia(..., autoPlay:false) on a mediaPlayer that was playing a previous video, MediaPlayer.Control.IsPlaying() incorrectly returns true. It should return false, because it's no longer playing at that point.

To repro, in Demo_MediaPlayer, edit MediaPlayerUI.Update by adding the following:

```
if (Input.GetKeyDown(KeyCode.Q)) {
    _mediaPlayer.OpenMedia(MediaPathType.RelativeToProjectFolder, "Assets/StreamingAssets/AVProVideoSamples/BigBuckBunny-360p30-H264.mp4", autoPlay: false);
    Debug.Log("IsPlaying: " + _mediaPlayer.Control.IsPlaying());
}
```

Then launch the demo, and while the default video is playing, press Q.

Expected result: "IsPlaying: False"
Actual result: "IsPlaying: True"

**Comment by MorrisRH** [comment]
Same issue as #687

**Comment by TheloTheGreat** [comment]
2.0.10 does not fix this issue, despite it fixing issue #687 .

**Comment by MorrisRH** [comment]
This will be fixed in the next release.

**Comment by AndrewRH** [comment]
@MorrisRH  can we close this one?

**Comment by TheloTheGreat** [comment]
2.1.0 does fix this issue, thanks.
