### ISSUE TITLE
Videos plays in editor, black screen on Quest 2

### ISSUE THREAD

**Issue by willemOH** [RenderHeads/UnityPlugin-AVProVideo#686]
Issue is as title describes

 - Unity version: 2019.4.11f
 - AVPro Video version:  1x-1.11.7
 - Operating system version: Windows 10
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size):  4096 x 2048, 29.97 fps, MP4, 12.2MB

**To Reproduce**
1. load video to video sphere
2. see it playing in editor and viewing in VR streaming from editor
3.  black screen when started from a build

**Logs**
only error:
Assets\Oculus\VR\Scripts\OVRDisplay.cs(168,3): warning CS0618: 'InputTracking.Recenter()' is obsolete: 'This API is obsolete, and should no longer be used. Please use XRInputSubsystem.TryRecenter() instead.'

However I believe this is to be expected for Quest 2

I've seen this problem in forums. I have switched the preferred Video API to Mediaplayer from Exosphere

Sending project file via email

**Comment by RenderHeadsSte** [comment]
My hunch is that this is a problem accessing the video file (as you have it loading from the 'Relative to the Data Folder'.  I just tried to recreate the issue with the project you sent over, but loading the video out of the 'Streaming Assets' folder...and the video played back just fine.

Can you try loading the video out of the Streaming Assets folder to rule out an access/permission issue?

**Comment by willemOH** [comment]
Yes that was it! Thanks for helping a noob out!
