### ISSUE TITLE
why most of 360 videos in Youtube is not suitable for  scene 08_Demo_360SphereVideo?

### ISSUE THREAD

**Issue by nongzhang** [RenderHeads/UnityPlugin-AVProVideo#688]

**Comment by AndrewRH** [comment]
Could you give an example of why you think it's not suitable?  Is there a screenshot you could share of how the video looks in 2D?

I suspect some YouTube videos are not encoded in equi-rectanular layout and instead use some sort of custom cubemap packing which may be why they can't be simply mapped to a sphere.

See here:
https://github.com/ytdl-org/youtube-dl/issues/15267

Does that make sense?

Thanks,

**Comment by nongzhang** [comment]
> Could you give an example of why you think it's not suitable? Is there a screenshot you could share of how the video looks in 2D?
> 
> I suspect some YouTube videos are not encoded in equi-rectanular layout and instead use some sort of custom cubemap packing which may be why they can't be simply mapped to a sphere.
> 
> See here:
> [ytdl-org/youtube-dl#15267](https://github.com/ytdl-org/youtube-dl/issues/15267)
> 
> Does that make sense?
> 
> Thanks,

Thanks, this is the AV Pro Video demo. 
[https://drive.google.com/file/d/147Of-MwrRQbSB3AJQCPRa9q3odjC-rt6/view?usp=sharing](url)
the video "SampleSphere.mp4" in StreamingAssets works well in Scene "08_Demo_360SphereVideo".
But I download many 360 video in YouTube cant work well. like this
[https://www.youtube.com/watch?v=WncZxApnB3w](url)
![image](https://user-images.githubusercontent.com/24870308/112716985-b698e480-8f24-11eb-9b32-2de4b42ab495.png)
[https://www.youtube.com/watch?v=20eGmjRlsmI&t=99s](url)
![image](https://user-images.githubusercontent.com/24870308/112717082-4179df00-8f25-11eb-829c-1766d42cb6c4.png)
[https://www.youtube.com/watch?v=bE3-j6MOTis](url)
![image](https://user-images.githubusercontent.com/24870308/112717114-70905080-8f25-11eb-8a39-c087ffd52a99.png)

**Comment by kahnivore** [comment]
Hi @nongzhang 

We don't currently support this type of cubemapping. It might be something we support in the future. If you needed it to work sooner you'd need to write your own shader to map it correctly. We don't support Youtube streaming in general as it is against their terms of use. 

Thanks.

**Comment by Chris-RH** [comment]
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/135
