### ISSUE TITLE
Insecure random number generator/weak hash

### ISSUE THREAD

**Issue by ColinYaoH1** [RenderHeads/UnityPlugin-AVProVideo#689]
There are some libraries in AVPro (1.11.7) that have been flagged as security vulnerabilities by our partners. I want to inquire if there is already plans to change/remedy these in future versions and if not, will it be possible? Alternatively, is this addressed in AVPro v2?

**1) MD5 is a weak hash known to have hash collisions.**

CVSS Score - 7.5
CWE-327 - https://cwe.mitre.org/data/definitions/327.html
OWASP - M5: Insufficient Cryptography

libs:
- com/RenderHeads/AVProVideo/AVProMobileWMImage.java

**2) Insecure Random Number Generator.**

CVSS Score - 7.4
CWE-330 - https://cwe.mitre.org/data/definitions/330.html
OWASP - M5: Insufficient Cryptography

libs:
- com/RenderHeads/AVProVideo/AVProVideoPlayer.java
- com/RenderHeads/AVProVideo/AVProMobileVideo.java
- com/RenderHeads/AVProVideo/AVProVideoMediaPlayer.java
- com/RenderHeads/AVProVideo/AVProVideoExoPlayer.java

**Comment by RenderHeadsSte** [comment]
All MD5 and random usage is linked to elements used in the trial version only and are for verification and placement purposes only.  At their core, they have not changed in v2.x.
