### ISSUE TITLE
Platform not supported, falling back to null media player

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#690]
@Atsutoshi wrote:

AVPro Video 1.11.7 throws the following error.

[AVProVideo] Not supported on this platform WindowsEditor To Be Filled By O.E.M. (To Be Filled By O.E.M.) AMD Ryzen 9 3950X 16-Core Processor Windows 10 (10.0.19042) 64bit. Using null media player!

Is it supported in 2.0?

**Comment by AndrewRH** [comment]
Windows 10 should be supported just fine in 1.x and 2.x.   

Which platform do you have selected in Build settings?  

What GPU do you have?

You could also run "winver" to report exactly which version of Windows you're using.

Also try selecting "DirectSHow" as the Video API in Platform Specific > Windows section of the MediaPlayer component to see if that helps.  It sounds like the Windows video player is detecting that it can't initialize for some reason.

Thanks,

**Comment by ImmotionPeterL** [comment]
Hi, just bought and imported AVPro Ultimate.. whenever I try to play a video in the editor, I get the following error

`[AVProVideo] Not supported on this platform WindowsEditor System Product Name (ASUS) Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz Windows 10  (10.0.19041) 64bit.  Using null media player!`

My g/card is a 2080 Super.

Before that error, I get another
`[AVProVideo] graphicsDeviceType not supported: Metal`

I'm unsure why Metal is being shown here, I'm on Windows, and don't even have the iOS module for Unity installed. My project was loaded for Windows builds, and now I've swapped to Android - no difference.

Changing the Video API makes no difference.

**Comment by ImmotionPeterL** [comment]
Figured it out - it says Metal because I am using the Device Simulator. I've had issues with v3 of Device Simulator with Vuforia too.. downgrading to v2.2.4 allows AVPro to work and the device type is Direct3D11.

**Comment by AndrewRH** [comment]
See #845 for solution
