### ISSUE TITLE
Playback issues at speeds greater than 2x 

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProVideo#692]
As you know, we are currently suffering from a very embarrassing issue with Apple's platforms (Mac OS and iPad) in which any play rate over 2x causes a rough playback.

I've been doing tests over the past hours using the latest 2.x version available (2.0.9) and this is the information I can give you:

With any mp4 video (using different keyframes separation configurations between 1 second a 6 seconds), we can accelerate the playback rate until exactly 2.0 with a correct visualization and fps rate. As soon as we set 2.01x, fps drops to around 3 and the video plays very rough. It's very weird, as we only need to go from 2.0 to 2.01 to encounter this problem
With an mp4 video with keyframes every frame, the problem disappears but as you may suppose, it's not something that can be done in real life.

Just to clarify, the problem is only related and encountered in Apple's platforms, as the same videos go over 2x in Windows and Android platforms without any issues.

Do you know if there is any kind of limitation using Apple's platforms and playback rate over 2x?

We haven't decided yet which maximum rate we want to set in the code, we were just doing tests when we encountered this problem.

We think something between 3x and 4x would be perfect, but it depends on the testing results.

[Edit (adding earlier messages)]

Thank you for your help, I didn't consider the keyframes as a key for my issues. I've been testing your suggestions and those are my results:

Issue 1: Sharp mp4 & HLS videos above 2x
I've encoded the mp4 video for increasing the number of keyframes. This time I've tested on an iMac (10.15.7) as it behaves the same as the iPad.
Test 1: Every frame is a keyframe [removed video link]
This video can be played at any speed without issues. It works as expected.

Test 2: Keyframe every second [removed video link]
It plays smoothly up to 2x, above that it is jerky. This issue only happens on Mac and iPad, it works on Android and Windows. The same behaviour as the original video.

Issue 2: HLS videos freeze when seeking above 2x
I'm encoding the HLS videos increasing the keyframe rate to check the improvements, I will keep you updated with my progress.
By now I've tried to set the frame rate to 0 when it gets stuck but it doesn't work, I need to Stop() to recover it actually.

I made a new version of the HLS video to meet your guidelines. It has 4 seconds segments and keyframes every second. I'm not been able to reproduce the issue 2 with this new video. It doesn't freeze anymore.
Issue 1 persists even with this video. Do you have any further information about this?

**Comment by MorrisRH** [comment]
By default when the player rate is set > 2.0 the player drops to showing key-frames only. In order to support playback rates > 2.0 we've added an option to the platform specific settings to allow you to specify the maximum playback rate you want to be able to support, shown below.

<img width="344" alt="Screenshot 2021-03-23 at 17 45 36" src="https://user-images.githubusercontent.com/46530460/112193549-e59b1780-8bff-11eb-91df-94cc74a4aed0.png">

**Comment by AndrewRH** [comment]
2.0.10 has just been release - so closing this issue.
