### ISSUE TITLE
[Mac] Unable to notarize application due to error in HapInAVFoundation.framework

### ISSUE THREAD

**Issue by psy-ankka** [RenderHeads/UnityPlugin-AVProVideo#693]
**Describe the bug**
`AVProVideo.bundle/Contents/Frameworks/HapInAVFoundation.framework` is preventing notarization due to codesign error.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1f1
 - AVPro Video version: AVPro Video v2.0.5 (native plugin v2.0.5f1-core)
 - Operating system version: macOS Big Sur 11.2.2
 - Device model: MacBook Pro
 - Video specs (resolution, frame-rate, codec, file size): N/A

**To Reproduce**
1. Build application `Application.app`
2. Codesign the binary and all the embedded libraries.
3. Verify signature `codesign -v Application.app/Contents/PlugIns/AVProVideo.bundle`

Current result:
Error during codesigning:
> Application.app/Contents/PlugIns/AVProVideo.bundle/Contents/MacOS/AVProVideo: invalid signature (code or signature have been modified)

Error verifying the application:
> Application.app/Contents/PlugIns/AVProVideo.bundle: embedded framework contains modified or invalid version
> In subcomponent: Application.app/Contents/PlugIns/AVProVideo.bundle/Contents/Frameworks/HapInAVFoundation.framework

This effectively prevents notarizing the application, which is a requirement for applications to be succesfully distributed outside of the AppStore.

Addendum: The codesign error can be detected even immediately after building the application in Unity by running `codesign -v Application.app/Contents/PlugIns/AVProVideo.bundle` or even in the project assets

**Comment by MorrisRH** [comment]
Please update to the latest version (2.0.9 at the time of writing).
We changed how Hap is supported on macOS so that HapInAVFoundation.framework is no longer included in the plugin because of this very problem.
