### ISSUE TITLE
Seek makes video hang for a few frames before actually rendering on play?

### ISSUE THREAD

**Issue by dhjat** [RenderHeads/UnityPlugin-AVProVideo#694]
Hi, I use keyframes-only videos for precise seeking although I find this behavior with encoded videos too.
Playing after pausing starts right away, but after seeking (forward or backward), the actual rendering  hangs for a while (maybe 10-ish frames?)
And the start event is not synchronized with the actual rendering so I can't synchronize.
Is the video buffering again after seek? If so can I force the buffering right after the seek to reduce the hang time?
Or is there a rendering event that I can catch to synchronize? Or did I miss a bit from the documentation?

I'm on Mac OS, using for now the trial version of AVPro.

Thanks!

**Comment by kahnivore** [comment]
Hi @dhjat 

Which trial version are you using, and which version of Unity?

Seeking is precise on Mac, is there another reason for going with a keyframe-only video?

The default behaviour for playing videos over the net is to buffer as much as required to minimise stalling (assuming this is over the net), and a keyframe-only video would be a bad choice for this. 

Would it be possible to send us a reproducible case to unitysupport@renderheads.com? 

Thanks

**Comment by dhjat** [comment]
Hi @kahnivore  So sorry for the late follow up

> Which trial version are you using, and which version of Unity?
I just tried with a fresh project on 2019.4.19f1 with the last trial version 2.0.11

> Seeking is precise on Mac, is there another reason for going with a keyframe-only video?
I had to have precise seek in a previous projects and adopted all key frames then since it was the only way to go. Kept going for this one. I'm really local, no problem for size

I can sed a case to support but behavior is seen in fresh project with sample material on my end (with the Demo_MediaPlayer scene). I guess it means it's not related to keyframes-only videos.
Attached is a video showing one play after manual seek through the slider showing the hang
Then a play right after (without seek before) that starts rendering fast (something like 1 frame after play press):
https://user-images.githubusercontent.com/30034377/113389936-6e197500-93c3-11eb-957b-14bce891d31c.mp4

Thanks

**Comment by RenderHeadsSte** [comment]
This issue appears to have become stale.  Are you still requiring support for this issue still @dhjat?

**Comment by MorrisRH** [comment]
From the video you sent it looks like play and pause events are being triggered when you scrub, this is not the standard behaviour and could explain why you're seeing such big pauses.
@dhjat Can you upgrade to the latest version (2.1.0) and see if the issue is still happening?

**Comment by dhjat** [comment]
I created a new project with only the 2.1.0 version, behavior is the same in the demo scene Demo_MediaPlayer

- click play button after launching -> video starts right away
- click in the slider to change time
- click play  -> video hangs for almost half a second (slider waits for the video and starts moving when video starts)
- click pause
- click play -> video starts right away

Does the same if seek through the seek 5 sec forward or backward buttons

**Comment by MorrisRH** [comment]
I'm unable to reproduce the issue here, seeks are taking around 70ms to complete. Can you provide more information about your setup?
For instance, my set-up is as follows:
* Mac mini (M1, 2020), macOS Bug Sur 11.3
* Unity 2020.3.6f1
* AVPro Video 2.1.0

**Comment by dhjat** [comment]
The seek is very fast and satisfactory on my end too.
It's when I start playing the video after a seek, that the play hangs (much longer than if I didn't seek before it). This is my issue. Sorry if it wasn't clear so far.

My setup :
- MacBook Pro (16-inch, 2019), macOS Catalina 10.15.7
- Unity 2020.3.6f1
- VPro Video 2.1.0
