### ISSUE TITLE
Can't use OES player after installing (then reverting) AVPro Video 2.0 trial

### ISSUE THREAD

**Issue by prisonerjohn** [RenderHeads/UnityPlugin-AVProVideo#698]
I have a licensed version of AVPro Video 1.0 and it will not work with the fast OES path on Android anymore. The project I'm working on was working fine up until I installed the trial version of AVPro Video 2.0 for a test drive, then reverted my changes to go back to version 1.0.

I'm not 100% sure that's the cause of the problem, but the last time it was working OK was right before I tried the trial. I can currently only hear the audio and see no image. If I switch to the non-OES version, the image appears. I'm wondering if maybe there's a flag that got set when I installed the trial that needs to be turned back on?

I have tried:
* deleting the `Library` folder and rebuilding a clean project, which didn't work
* deleting all AVPro Video files and re-importing the package, which also didn't work
* compiling the same project on another computer, which did work

I'm using git for version control, and it's not reporting any changes on the machine with the issue.

Any ideas?

Thank you

**Comment by kahnivore** [comment]
Hi @prisonerjohn 

Did you close Unity before removing the trial?

**Comment by prisonerjohn** [comment]
I don't remember exactly what I did when I switched from 2.0 back to 1.0. I might have just changed branches on my project (I have a main branch and an AVPro 2.0) branch when I switched back, and possibly didn't have Unity closed when I did that.

However I've definitely closed Unity and completely deleted the folder and DLLs a couple of times since then while troubleshooting. I'm like 99% sure the libs in the Android folder are the right ones.

**Comment by AndrewRH** [comment]
Hmm that's strange.  Could you try creating a new project and using 1.11.7?

**Comment by RenderHeadsSte** [comment]
For OES to work correctly, you need to ensure OES is ticked in the MediaPlayer Android options:

![image](https://user-images.githubusercontent.com/46531149/112512306-296e5800-8d8b-11eb-83af-ffe45a0e50c2.png)

...and also make sure you are using the correct OES shader.

**Comment by RenderHeadsSte** [comment]
"compiling the same project on another computer, which did work"

"I'm using git for version control, and it's not reporting any changes on the machine with the issue."

This is extremely interesting.  Maybe the shaders have been cached from the usage of v2?

**Comment by prisonerjohn** [comment]
I apologize, I was barking up the wrong tree. 
Turns out the issue was enabling `Low Overhead Mode` in the XR / Oculus settings for Android. Has nothing to do with AVPro 2.0, sorry about that.
I'm not sure how that toggle would affect OES textures and I don't quite understand why it still worked fine on two of our dev machines but I guess something was cached on those PCs and kept the thing going.
Thank you for your time!
