### ISSUE TITLE
Android OOM after switching videos many times

### ISSUE THREAD

**Issue by scott-limbix** [RenderHeads/UnityPlugin-AVProVideo#7]
**Describe the bug**
OOM after switching videos many times

**Your Setup (please complete the following information):**
 - Unity version: 2017.4.17f1
 - AVPro Video version: 1.9.8
 - Operating system version:  Android 6.0.1
 - Device model: Pico Goblin 1
 - Video specs (resolution, frame-rate, codec, file size): 
    -  Duration: 00:01:49.01, start: 0.000000, bitrate: 2154 kb/s
    - Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 2160x2160 [SAR 1:1 DAR 1:1], 2016 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 29.97 tbc (default)
    - Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)

**To Reproduce**
Note, we are using two instances of AVPro, which alternate playback of videos.  With each video playback, memory utilization increases until an OOM crash.  See the log message below indicating a file is opened but not closed at:
`com.RenderHeads.AVProVideo.AVProVideoMediaPlayer.OpenVideoFromFileInternal(AVProVideoMediaPlayer.java:259)`

**Logs**
```
01-25 14:05:10.713 12771-12781/com.picovr.vrlauncher I/art: Background partial concurrent mark sweep GC freed 12031(744KB) AllocSpace objects, 18(292KB) LOS objects, 39% free, 2MB/4MB, paused 660us total 265.592ms
01-25 14:05:10.787 12771-12779/com.picovr.vrlauncher E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.io.FileInputStream.<init>(FileInputStream.java:78)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at com.RenderHeads.AVProVideo.AVProVideoMediaPlayer.OpenVideoFromFileInternal(AVProVideoMediaPlayer.java:259)
        at com.RenderHeads.AVProVideo.AVProVideoPlayer.OpenVideoFromFile(AVProVideoPlayer.java:645)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
        at android.os.MessageQueue.next(MessageQueue.java:392)
        at android.os.Looper.loop(Looper.java:135)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
```
**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

**Comment by AndrewRH** [comment]
Thanks for the detailed bug report.  It looks like a genuine bug in our code where we're not calling Close()

http://tutorials.jenkov.com/java-io/fileinputstream.html#closing-a-fileinputstream

We'll do some testing and let you know when we have a fixed version.

**Comment by AndrewRH** [comment]
We've fixed the issue in code now, and will release it with version 1.9.14 soon.  Thanks,

**Comment by AndrewRH** [comment]
Did you get a chance to try the beta version we sent you?

**Comment by scott-limbix** [comment]
Yes, thank you for sending it over for testing.

The update appears to resolve the issue with files not being closed.

**Comment by christo-auer** [comment]
I'd be willing to try out a beta! We have the same issue and plan to release our software very soon. Or is there already a data for the release of the new version?

Thanks!

**Comment by AndrewRH** [comment]
The new version will be out "soon", we're just working on a number of other changes for the release.  In the meantime you can contact us to get access to a beta.
