### ISSUE TITLE
[#fsauE] Can't play more than 4 audio channels under Android MediaPlayer

### ISSUE THREAD

**Issue by RenderHeadsMrT** [RenderHeads/UnityPlugin-AVProVideo#70]
**Describe the bug**
MediaPlayer only sees 4 of the 6 audio channels. ExoPlayer sees all 6 but can't handle the video resolution/frame-rate.

**Your Setup (please complete the following information):**
 - Unity version: 'Latest' ARM64
 - AVPro Video version: 1.9.12
 - Operating system version: 
 - Device model: Oculus Go?
 - Video specs (resolution, frame-rate, codec, file size): (4096x4096 30fps) HEVC H.265 (60 Mbps)

**Comment by AndrewRH** [comment]
Here's the users video file, with 8 audio tracks

[output_8audiochannel_Test.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3247638/output_8audiochannel_Test.zip)

**Comment by AndrewRH** [comment]
@RenderHeadsSte  any insight?

**Comment by RenderHeadsSte** [comment]
Using the provided 8 audio channel video I have tested both MediaPlayer and ExoPlayer API paths on the an Nvidia Shield tablet, Samsung S70 (UK/EU version), Oculus GO.  On all devices, ExoPlayer sees and playback all 8 audio channels.  MediaPlayer performs the same on all devices except the Oculus GO.  The GO only sees 4 channels.

Debugging has revealed that, on the GO, the Android MediaPlayer API returns back that there are only 5 channels in the video (1 video and 4 audio).  On the other devices tested on, we are getting 9 channels returned (1 video and 8 audio).

It would appear this is a bug in the Android implementation on the GO.  This is something we unfortunately cannot fix.

The suggested solution is to use the ExoPlayer API path to playback videos on the GO that have more than 4 audio tracks.  If you are seeing issue playing back in ExoPlayer, please do open another bug and send us the video you are seeing issues with.
