### ISSUE TITLE
iOS armv7 build issue 

### ISSUE THREAD

**Issue by withstand007** [RenderHeads/UnityPlugin-AVProVideo#700]
Hi, 
We have bought the Core pack AVPro. Our Android build worked fine no issues but the IOS build is not building and ending with loads of errors. We are able to build it on device but when we try to archive it then it starts giving us errors. We even tried building just an empty project with plugin and nothing else and still failed to archive.

Can you please tell me how I can resolve this issue. 
I have attached the screenshot of error logs and link to the error logs is this :- https://paste.ofcode.org/cuKG83mCun98bfjyF5SexM

When we integrated plugin with our project then we are getting this single error log :- 
***/Build/Unity-iPhone.xcodeproj The linked framework 'AVProVideo.framework' is missing one or more architectures required by this target: armv7.

Thank you
![Screenshot 2021-03-25 at 5 09 50 PM](https://user-images.githubusercontent.com/77960357/112467363-faf17c80-8d8c-11eb-8681-b4b2c4fd7f3a.png)

**Comment by MorrisRH** [comment]
We only support devices using the 64bit arm64 architecture, armv7 is not supported.
