### ISSUE TITLE
Unable to view / playback HAP videos macOS 10.15.7

### ISSUE THREAD

**Issue by CDCMacDaddy** [RenderHeads/UnityPlugin-AVProVideo#701]
**Describe the bug**
I've created some HAP videos that After Effects and Premiere see fine. When I bring them into Unity and attempt to play them the preview in the Media Player shows an empty frame. The duration is accurate. The dimensions are accurate. The image is not there.

**Your Setup (please complete the following information):**
 - Unity version: 
 - 2019.4.8
 - AVPro Video version: 
 - Ultra 2.0.9
 - Operating system version: 
 - macOS 10.15.7
 - Device model: 
 - Mac Pro 2019
 - Video specs (resolution, frame-rate, codec, file size): 
 - 3440x1440 30fps HAP file size is 62 MB

**To Reproduce**
1. Take ProRes file. Render out from After Effects as HAP or HAP Q
2. Place in StreamingAssets
3. Point to file in MediaPlayer
4. Attempt to play asset. 

**Logs**
If applicable, add error logs to help explain your problem.

[AVProVideo] Opening /Volumes/Glyph 2TB/Interactive Graphic - Master 2/Assets/StreamingAssets/Cue_1_Top_Code_Loop-HAP A.mov (offset 0) with API 
UnityEngine.Debug:Log(Object, Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at Assets/AVProVideo/Runtime/Scripts/Internal/Helper.cs:184)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:429)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(MediaPathType, String, Boolean) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:341)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(MediaPath, Boolean) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:346)
RenderHeads.Media.AVProVideo.Editor.RecentMenu:Callback_Select(Object) (at Assets/AVProVideo/Editor/Scripts/RecentMenu.cs:82)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/GenericMenu.cs:119)

**Screenshots**
<img width="650" alt="image" src="https://user-images.githubusercontent.com/81551326/112795999-3060c900-901e-11eb-8f16-e9915d584c5b.png">

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by CDCMacDaddy** [comment]
I should add that After Effects can read in the HAP file created without a problem and displays it correctly.

**Comment by MorrisRH** [comment]
Yup, definitely broken. Will get a fix in for the next release.

**Comment by MorrisRH** [comment]
Fixed.

**Comment by AndrewRH** [comment]
@CDCMacDaddy 

2.0.10 has just been release - please let us know whether this fixes the issue for you.

Thanks,

**Comment by CDCMacDaddy** [comment]
Perfect. Thank you - I will try it shortly!

**Comment by CDCMacDaddy** [comment]
By the way - this fixed it!
