### ISSUE TITLE
Custom HLS Livestream with H.265 Encoding and 5.1 Sound Freezes During Playback 

### ISSUE THREAD

**Issue by shazamk** [RenderHeads/UnityPlugin-AVProVideo#703]
**Describe the bug**
 MediaPlayer freezes when attempting to play a custom HLS stream with H.265 encoding and 5.1 Surround Sound(aac) in an Android build(ExoPlayer). 

**Additional Info**
-The first frame of the video loads (visible on screen) but never continues playing.
-Continuously toggles between "StartedBuffering" and "Finishedbuffering" MediaPlayer events.
-The custom stream plays back in editor.
-I'm able to play a custom 4k HLS stream with H.265 video and **STEREO AUDIO** in Android without any issues.

This might just be a hardware limitation issue but we wanted to get your insight anyways.
 
**Your Setup (please complete the following information):**
 - Unity version: 2020.1.8f1
 - AVPro Video version: 2.0.9 Ultra
 - Device model: HTC Vive Focus Plus (FA03JAZ00063), HUAWEI KII-L05
 - HLS Stream Specs: 4k Resolution, H.265 codec, 5.1 audio (aac), 2 video variations, 3 segments 1 second each

**To Reproduce**
1. Add MediaPlayer instance to a scene.
2. Set MediaPlayer to playback an HLS stream with H.265 encoding and 5.1 Audio.
3. Set video API to ExoPlayer 
4. Build and Run for Android.

**Videos**
Due to privacy issues I'm unable to provide the stream immediately. I will get back to you about this as soon as I can.

**Logs**
[AvproHLSLogcat.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6223693/AvproHLSLogcat.txt)

**Comment by RenderHeadsSte** [comment]
This should work using ExoPlayer.  Are you piping audio to Unity, or 'System Direct' ?  If you are using Unity, then you would have to set Unity to be 5.1...that said, I am not sure that the Android OS will honour what Unity has set.  'System Direct might be your best bet'.

**Comment by shazamk** [comment]
I found this 5.1 surround sound stream online that I'm able to playback in ExoPlayer without that freezing issue (https://www.maxradio.ca/UHD/LG73Surround/LG73.m3u8). I think the freezing issue could be caused by how our HLS livestream is configured. Are you aware of any special considerations that should be made when playing back an HLS stream with ExoPlayer? We hope to test the stream again today with different settings. Thanks.

**Comment by RenderHeadsSte** [comment]
I have tested the stream URL here...

Using 'Unity Audio' (where the audio samples are piped though the unity audio subsystem' I get what appears to be a channel miss-match.  This is not unsurprising.  I believe that somewhere along the chain Unity/Android does not honour what Audio 'Default Speaker Mode' you set in your unity project. For example, if you set 'Surround 5.1', you still get only 2 channels configuration reported in the script callback method 'void OnAudioFilterRead(float[] audioData, int channelCount)' (found in AudioOutput.cs).

![image](https://user-images.githubusercontent.com/46531149/113707129-5f8ad080-96d7-11eb-9014-7bd20067597d.png)
![image](https://user-images.githubusercontent.com/46531149/113707211-792c1800-96d7-11eb-8b6b-662f940d37df.png)

Using 'System Direct' I get clean/correct audio playback.

The setting is set here:

![image](https://user-images.githubusercontent.com/46531149/113706484-a4623780-96d6-11eb-9b37-bc5fbbc39a60.png)

**Comment by shazamk** [comment]
Thanks for that update. We managed to get our stream running yesterday. I'm not the person responsible for setting up the stream so I don't completely understand the solution. They mentioned they removed a "transfer-encoding:chunked" tag that was on the stream and reconfigured the init on the CDN and that resolved the issue. For some reason we **ONLY** experienced that freezing issue when the stream was set to 5.1 surround sound and was playing back on Android. We have never had issues playing back custom H.265 streams with 5.1 audio on Windows OR  custom H.265 streams with stereo audio on Android.

 I did notice that channel mismatch issue before when using Unity as the audio output. Unfortunately we need to use Unity audio to take advantage of specialization.  We've been working on our own scripts to try to achieve that. 

Thanks for the help. The main issue is resolved.

**Comment by RenderHeadsSte** [comment]
Thanks for letting us know @shazamk.  Glad you have some form of resolution.

On the Unity/5.1 issue.  There is no reason why you should not be able to take the output samples (which should be 6 channel interleaved) and do what you desire with them.  Playing them back through the Unity audio subsystem would require mapping to stereo I would think.

Do let us know how you get on if you venture down that path as the Android audio/Unity pipe is quite young and we are always keen to improve.
