### ISSUE TITLE
OverrideDecryptionKey in inspector for HLS AES-128 Encryption not working 

### ISSUE THREAD

**Issue by yudi-xiao-letscoze** [RenderHeads/UnityPlugin-AVProVideo#705]
I've run some basic testing using the trial version.

1. I encrypted the 'RenderHeads-1080p30-H264.mp4' video in demo using following command. 
`ffmpeg -i ./RenderHeads-1080p30-H264.mp4 -c copy -bsf:v h264_mp4toannexb -hls_time 4 -hls_key_info_file key_info ./playlist/playlist.m3u8` . The following link contain my 'key_info' file and encryption key (which is generated by running command `openssl rand -hex 16`).
[Videos.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6228565/Videos.zip)
2. Then I manual remove the URI value in generated m3u8 file and host all the contents at my local servers.
3. I use [this website](https://www.base64encode.org/) to get the base64 string of my key.
4. Enter host path and the base64 string into the inspector field and click load, its given me a error log : 
`[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1207)
RenderHeads.Media.AVProVideo.MediaPlayer:Update() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:637)
RenderHeads.Media.AVProVideo.MediaPlayer:EditorUpdate() (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:593)
RenderHeads.Media.AVProVideo.Editor.MediaPlayerEditor:OnInspectorGUI() (at Assets/AVProVideo/Editor/Scripts/Components/MediaPlayerEditor.cs:319)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

**Comment by yudi-xiao-letscoze** [comment]
I then tried to host the key file on my local server and restore the URI value to the key file path in the m3u8 file. Everything is working fine.

**Comment by yudi-xiao-letscoze** [comment]
Found how to fix this 
`// Player.KeyAuth.overrideDecryptionKey = Convert.FromBase64String(base64Key); // This has no effect
Player.GetCurrentPlatformOptions().keyAuth.overrideDecryptionKey = Convert.FromBase64String(base64Key); //This will work `

**Comment by kahnivore** [comment]
Thanks for the update. Closing this as it has been solved.
