### ISSUE TITLE
2.0.10 regression - GLSL compilation failed

### ISSUE THREAD

**Issue by IARI** [RenderHeads/UnityPlugin-AVProVideo#707]
**Describe the bug**
Note: This Problem only occurs with the Unity Editor running in OpenGLES.
Since AVPro does not actually support OpenGLES within the Editor (See #645) this issue will probably not be a high priority. It does not affect our mobile builds.
However, this does **not happen on Unity 2019.4.x** - so I figured, it could be worth an issue anyways.

On Unity 2020.3, Android VR shaders fail to compile.
Affected shaders:
* AVProVideo-VR-InsideSphere-AndroidOES.shader
* AVProVideo-VR-InsideSphere-Transparent-AndroidOES.shader

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.1f1 (OpenGLES)
 - AVPro Video version: 2.0.10
 - Operating system version: Windows
 - Device model: -
 - Video specs (resolution, frame-rate, codec, file size): -

**To Reproduce**
1. Open Unity Project in Unity 2020.3.x
2. Make sure that in Project Settings "Graphics APIs for Windows" is set to OpenGLES
2. import AVpro

**Logs**
A few more of these kinds of Exceptions are shown in the Unity console.
```
GLSL compilation failed:
0(91) : error C1503: undefined variable "_CroppingScalars"
GLSL compilation failed:
0(86) : error C1503: undefined variable "_CroppingScalars"
....

```

**Comment by AndrewRH** [comment]
@IARI 

Sorry about this, there was a regression in 2.0.10 that introduced this bug - please see the just released 2.0.11 for the fix.

Thanks,
