### ISSUE TITLE
Video orientation is broken after a quick video load after another

### ISSUE THREAD

**Issue by cihadturhan** [RenderHeads/UnityPlugin-AVProVideo#709]
**Describe the bug**
If you quickly load one video after another, sometimes orientation is broken. 
Looks like there is a race condition when it cancels/stops previous video.

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.3
 - AVPro Video version: 2.0.11
 - Operating system version: Catalina
 - Device model: MacOS Editor & iOS 
 - Video specs (resolution, frame-rate, codec, file size): Video captures recorded with HD & 4K on iPhone XR

**To Reproduce**
- Create a mediaplayer component
- Create a DisplayUGUI component
  - Load a portrait video (`Video P`), 
  - Wait a bit and load another video (`Video A`)
  - Quickly load `Video P` again
  - Observe sometimes orientation is broken (See Video below)

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
https://user-images.githubusercontent.com/3739536/113399375-cdb65700-93a8-11eb-9d9a-eaadedaeb4a8.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

As my project is time-sensitive, I'll try to find and fix DisplayUGUI component but if the problem is in the native library, please help me to fix it.

Thanks,
Cihad

**Comment by cihadturhan** [comment]
Fixed issue by modifying some code on DisplayUGUI component. 
Problem is, it assumes orientation is portrait when one video is closed and the other is being opened.

Posting here so devs can find better solution:
```diff
+		protected override void OnEnable()
+		{
+			if (_mediaPlayer && _mediaPlayer.Info.HasVideo())
+			{
+				base.OnEnable();
+			}
+
+			Debug.Log("OnEnable " + ((_mediaPlayer != null ? _mediaPlayer.MediaPath.Path : null) + " ") +
+			          gameObject.name);
+		}
```


```diff
		private void OnMediaPlayerEvent(MediaPlayer mp, MediaPlayerEvent.EventType et, ErrorCode errorCode)
		{
			switch (et)
			{
				case MediaPlayerEvent.EventType.MetaDataReady:
					break;
				case MediaPlayerEvent.EventType.FirstFrameReady:
					if (_userMaterial && null != GetRequiredShader())
					{
						Debug.LogWarning("[AVProVideo] Custom material is being used but the video requires our internal shader for correct rendering.  Consider removing custom shader or modifying it for AVPro Video support.", this);
					}
					LateUpdate();
+					SetVerticesDirty();
+					SetMaterialDirty();
					break;
				case MediaPlayerEvent.EventType.PropertiesChanged:
				case MediaPlayerEvent.EventType.ResolutionChanged:
-				case MediaPlayerEvent.EventType.Closing:
+				//case MediaPlayerEvent.EventType.Closing:
					LateUpdate();
					break;
			}
			// TODO: remove this, we're just doing this so we can make sure texture is correct when running in EDIT mode
			LateUpdate();
		}

```

**Comment by MorrisRH** [comment]
A fix will be in the next release
