### ISSUE TITLE
samizzo - iPad lock/unlock causes not properly playing/pausing videos

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#71]
I'm using AVPro Video 1.9.14 for a project on iOS, on the latest iPad Pro. The app is divided into a bunch of sections which are turned on and off as you go between them. I play an intro video at the start of most of the sections. When the section is complete, the root GameObject is disabled and the next section is enabled.

I've noticed that once the videos have finished playing and I'm in the next section, if I lock the device then unlock it some of the previous section videos will start playing (sometimes they start near the end of the video). I can't see anything rendering but I can hear the audio from it. I have logs enabled, but I don't get any messages from MediaPlayer.OnApplicationFocus or MediaPlayer.OnApplicationPause. I don't see anything else useful in the device logs either (which I've attached). I'm not using OnApplicationFocus/OnApplicationPause anywhere else.

[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3241714/log.txt)

**Comment by samizzo** [comment]
Hi, I've emailed through a link to a project that reproduces this bug!

**Comment by MorrisRH** [comment]
> Hi, I've emailed through a link to a project that reproduces this bug!

Thanks for the project, unfortunately I was not able to get it to work (TextMesh Pro issues).
However I was a able to reproduce something similar and implement a fix which will be available in the next release.

**Comment by samizzo** [comment]
Thank you! Strange about the TMP issues, but great that you were able to reproduce it!

**Comment by AndrewRH** [comment]
Hi Samizzo, we've released v1.9.17 which should fix this issue.  Let us know if it's resolved or not.

Thanks,

**Comment by AndrewRH** [comment]
We'll close this issue in a couple of days, as we've proposed a solution (new plugin version) but haven't heard anything back.  If you're still having this issue with the new version please do let us know.

Thanks,

**Comment by samizzo** [comment]
I'm sorry I didn't reply sooner. The new version seems to have fixed the issue! Thank you.
