### ISSUE TITLE
MetaDataReady event never gets called

### ISSUE THREAD

**Issue by cihadturhan** [RenderHeads/UnityPlugin-AVProVideo#710]
**Describe the bug**
 ```csharp
void OnMediaPlayerEvent(MediaPlayer mp, MediaPlayerEvent.EventType et, ErrorCode errorCode)
		{
			switch (et)
			{
				case MediaPlayerEvent.EventType.MetaDataReady:
                                         // Never gets called
					break;
			}
		}
```

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.3
 - AVPro Video version: 2.0.11
 - Operating system version: Catalina
 - Device model: MacOS Editor & iOS 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. On MacOS editor try the code above.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
So, I waited a few seconds after video load. Looks like MetadataReady is never sent from native code.
![image](https://user-images.githubusercontent.com/3739536/113455429-40f4b300-9413-11eb-841f-756d766eca00.png)

**Comment by MorrisRH** [comment]
A fix will be in the next release.

**Comment by cihadturhan** [comment]
@MorrisRH thanks!
