### ISSUE TITLE
OpenGl Native Plug-in error

### ISSUE THREAD

**Issue by willemOH** [RenderHeads/UnityPlugin-AVProVideo#712]
**Describe the bug**
When loading a build of a basic AVPro setup in an otherwise blank project to a Quest 2, the build does not start and instead there are just three loading dots from which it is impossible to escape without restarting the Quest. Adb Logcat reports this error: `OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range`

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.13f1
 - AVPro Video version: 1.11.7
 - Operating system version: Android 10
 - Device model: Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 4k 360 30fps

**To Reproduce**
1. Drag videosphere prefab in blank scene and set player settings to necessary specs (remove vulkan, etc)
2. Set video API from Exoplayer to Mediaplayer
3. Add video from streaming assets folder
4. build to quest 2

**Logs**
04-06 11:49:23.653  1035  2371 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.INFO] flg=0x10010000 pkg=com.DefaultCompany.VideoPlayer_Standalone cmp=com.DefaultCompany.VideoPlayer_Standalone/com.unity3d.player.UnityPlayerActivity (has extras)} from uid 10020
04-06 11:49:23.767  1035  1070 I ActivityManager: Start proc 7870:com.DefaultCompany.VideoPlayer_Standalone/u0a111 for activity {com.DefaultCompany.VideoPlayer_Standalone/com.unity3d.player.UnityPlayerActivity}
04-06 11:49:23.958  1035  1068 I ActivityTaskManager: Displayed com.DefaultCompany.VideoPlayer_Standalone/com.unity3d.player.UnityPlayerActivity: +263ms
04-06 11:49:24.584  7870  7893 I Unity   : SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 3, Memory = 5842mb
04-06 11:49:24.584  7870  7893 I Unity   : SystemInfo ARM big.LITTLE configuration: 3 big (mask: 0x70), 0 little (mask: 0x0)
04-06 11:49:24.584  7870  7893 I Unity   : XR UsableCoreMask: 0x70
04-06 11:49:24.587  7870  7893 I Unity   : ApplicationInfo com.DefaultCompany.VideoPlayer_Standalone version 0.1 build 331f3a00-8a28-418b-b4aa-a25ccd690e57
04-06 11:49:24.587  7870  7893 I Unity   : Built from '2019.2/release' branch, Version '2019.2.13f1 (e20f6c7e5017)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a', Stripping 'Disabled'
04-06 11:49:24.687  7870  7893 I chatty  : uid=10111(com.DefaultCompany.VideoPlayer_Standalone) UnityMain identical 14 lines
04-06 11:49:24.699  7870  7893 E Unity   : Unable to find libAudioPluginOculusSpatializer
04-06 11:49:24.724  7870  7893 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
04-06 11:49:24.724  7870  7893 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
04-06 11:49:24.724  7870  7893 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_motion_estimation GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather
04-06 11:49:27.309  7870  7893 I OVRPlugin: UnityPluginLoad called
04-06 11:49:27.339  7870  7893 I Unity   : Unity v2019.2.13f1, Oculus Utilities v1.52.0, OVRPlugin v1.52.1, SDK v0.0.0.
04-06 11:49:27.339  7870  7893 I Unity   :
04-06 11:49:27.339  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.339  7870  7893 I Unity   :
04-06 11:49:27.377  7870  7893 I Unity   : SystemHeadset None
04-06 11:49:27.377  7870  7893 I Unity   :
04-06 11:49:27.377  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.377  7870  7893 I Unity   :
04-06 11:49:27.385  7870  7893 I Unity   : OVRPlugin.Media not initialized
04-06 11:49:27.385  7870  7893 I Unity   :
04-06 11:49:27.385  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.385  7870  7893 I Unity   :
04-06 11:49:27.441  7870  7893 I Unity   : [OVRManager] OnApplicationPause(false)
04-06 11:49:27.441  7870  7893 I Unity   :
04-06 11:49:27.441  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.441  7870  7893 I Unity   :
04-06 11:49:27.443  7870  7893 I Unity   : [OVRManager] OnApplicationFocus(true)
04-06 11:49:27.443  7870  7893 I Unity   :
04-06 11:49:27.443  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.443  7870  7893 I Unity   :
04-06 11:49:27.552  7870  7893 I Unity   : [AVProVideo] Creating player 0
04-06 11:49:27.552  7870  7893 I Unity   :
04-06 11:49:27.552  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.552  7870  7893 I Unity   :
04-06 11:49:27.554  7870  7893 E Unity   : OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range
04-06 11:49:27.554  7870  7893 E Unity   :
04-06 11:49:27.554  7870  7893 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 348)
04-06 11:49:27.554  7870  7893 E Unity   :
04-06 11:49:27.574  7870  7893 I Unity   : [AVProVideo] Initialising AVPro Video (script v1.11.7 plugin v1.11.6) on Adreno (TM) 650/OpenGL ES 3.2 V@0529.0 (GIT@a8017ed, I1caff7147d, 1611555193) (Date:01/24/21) (MT False) on Android Android OS 10 / API-29 (QQ3A.200805.001/15280600139600000)
04-06 11:49:27.574  7870  7893 I Unity   :
04-06 11:49:27.574  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.574  7870  7893 I Unity   :
04-06 11:49:27.592  7870  7893 I Unity   : [AVProVideo] Opening jar:file:///data/app/com.DefaultCompany.VideoPlayer_Standalone-QVSVRPyv0QeEkXIjBJmIHw==/base.apk!/assets/test loop 5 mono -1.mp4 (offset 0) with API MediaPlayer
04-06 11:49:27.592  7870  7893 I Unity   :
04-06 11:49:27.592  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.592  7870  7893 I Unity   :
04-06 11:49:27.708  7870  7893 I Unity   : The current MSAA level is 0, but the recommended MSAA level is 2. Switching to the recommended level.
04-06 11:49:27.708  7870  7893 I Unity   :
04-06 11:49:27.708  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.708  7870  7893 I Unity   :
04-06 11:49:27.712  7870  7893 I Unity   : [OVRManager] InputFocusLost event
04-06 11:49:27.712  7870  7893 I Unity   :
04-06 11:49:27.712  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.712  7870  7893 I Unity   :
04-06 11:49:27.836  7870  7893 I Unity   : [AVProVideo] Using playback path: MediaPlayer NonOES (4096x2048@30.00)
04-06 11:49:27.836  7870  7893 I Unity   :
04-06 11:49:27.836  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.836  7870  7893 I Unity   :
04-06 11:49:27.844  7870  7893 I Unity   : [AVProVideo] Texture ID: 27
04-06 11:49:27.844  7870  7893 I Unity   :
04-06 11:49:27.844  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:27.844  7870  7893 I Unity   :
04-06 11:49:49.440  7870  7893 I Unity   : [OVRManager] OnApplicationPause(true)
04-06 11:49:49.440  7870  7893 I Unity   :
04-06 11:49:49.440  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:49.440  7870  7893 I Unity   :
04-06 11:49:49.442  7870  7893 I Unity   : [AVProVideo] OnApplicationPause: pausing video
04-06 11:49:49.442  7870  7893 I Unity   :
04-06 11:49:49.442  7870  7893 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
04-06 11:49:49.442  7870  7893 I Unity   :

**Comment by RenderHeadsSte** [comment]
I have tested your steps here, but with the following differences:

- I used Unity 2019.4.20fa
- I used '360SphereVideo' prefab
- I used the sample BigBuckBunny 720p video, and also tried our AVPro v2 4k 60fps HEVC video

The MediaPlayer API played back the video just fine on the Quest 2.

Question: Were you enabling VR/XR settings at all?

**Comment by willemOH** [comment]
Thank you. A tired error. All good

**Comment by RenderHeadsSte** [comment]
All good?  Can we close this issue now?  Be great to hear what it turned out to be.

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response.
