### ISSUE TITLE
app crashed when I exit it while playing encrypted video

### ISSUE THREAD

**Issue by xxfs** [RenderHeads/UnityPlugin-AVProVideo#715]
# Describe the bug
carsh code : _player.OpenVideoFromBuffer(videoBytes, false);

# Setup:
 - Unity version: 2018.4.11f1
 - AVPro Video version: 1.10.0
 - Operating system version: windows7
 - Device model: win7 X64
 - Video specs (resolution, frame-rate, codec, file size): 1920X1080, 30fps,  h264, 15MB

**To Reproduce**
1. encrypt the video with C# System.Security.Cryptography.AesCryptoServiceProvider
2. then read the decrypt video stream and play the video with OpenVideoFromBuffer(videoBytes, false) api
3. while video playing, quit the app on windows7 x64 platform

# Logs
none logs

# Screenshots
none screen

# Videos**
https://ilab.s3.cn-north-1.amazonaws.com.cn/videos/f2680875b32ebef613278ecd3ef54deb.mp4

# Email
mcxxfs@outlook.com

**Comment by kahnivore** [comment]
HI @xxfs 

What exactly do you mean by the app crashed on exit? Is this a Windows build, or in the Unity editor? And how are you exiting the app? What exactly happens when you exit? 

Is there a reason you haven't updated to the latest version of AVPro Video 1.x? (It's 1.11.7).

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
