### ISSUE TITLE
startWithHighestBitrate seemingly not respected on Android

### ISSUE THREAD

**Issue by acgourley** [RenderHeads/UnityPlugin-AVProVideo#716]
When I toggled on the "Start Max Bitrate" in the Android platform settings, at runtime this is always returning false: `mediaPlayer.PlatformOptionsAndroid.StartWithHighestBandwidth()`

And both devices I have tested on (an older tablet and a Pixel 3 on android 11) start on lower res streams. The Pixel 3 eventually ladders up to 1080p.

 - Unity version: 2020.3
 - AVPro Video version: 2.0.11
 - Operating system version: Android 11
 - Device model: Pixel 3

It seems to reproduce on:
https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by AndrewRH** [comment]
Hi @acgourley this is a mistake in the code, and we will fix it in the next release.

For now though you can add this line: 

`			public override bool StartWithHighestBandwidth() { return startWithHighestBitrate; }
`

In file ```MediaPlayer_PlatformOptions.cs``` at line 274:

![image](https://user-images.githubusercontent.com/5418126/114700979-23c8ba00-9d1a-11eb-9fcb-d1427d802d4b.png)

Does that solve your issue?

Thanks,

**Comment by RenderHeadsSte** [comment]
A fix for this issue has been offered in v2.1.0 which was released today.  Please do report back is you get chance to test this @acgourley

**Comment by AndrewRH** [comment]
Closing this as 2.1.0 has been released with this fix
