### ISSUE TITLE
It would be nice if the HLS stream parser would ladder into streams the platform doesn't think it can play

### ISSUE THREAD

**Issue by acgourley** [RenderHeads/UnityPlugin-AVProVideo#717]
**Is your feature request related to a problem? Please describe.**
My problem is after upgrading to AVPro2 it seems as though HLS master playlists which were working fine for our users before now won't play with adaptive bitrate on mid-range androids. Instead, the client enters at the smallest stream and never ladders up. 

**Describe the solution you'd like**
If an HLS master playlist is full of streams a client doesn't think it can play, I'd like it to consider them as options for variable speed streaming anyway. 

**Describe alternatives you've considered**
A toggle for this behavior would also be fine. 

**Additional context**
It seems as though the problem is the client not believing it can play streams in higher profile levels. I see this output in log cat: `VideoCapabilities: Unsupported profile 4 for video/mp4v-es` and `MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640028, video/avc] [OMX.MTK.VIDEO.DECODER.AVC, video/avc]`

**Comment by acgourley** [comment]
As some additional confirmation, I edited the m3u8 to incorrectly advertise the profile level and it will ladder correctly on the older android.

**Comment by kahnivore** [comment]
Hi @acgourley 

It'd be good to get a bit more information on this, could you please provide the following:

1. Which version of Unity are you using?
2. Which platform are you developing on?
2. Which Android device are you targeting? 
3. Do you have URL we could test with? 
4. Could you potentially test with the following stream and see if the results are the same? [https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8](https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8)

Thanks.

**Comment by acgourley** [comment]
As a Main 3.1 stream that will work fine. The issue here is our streams are advertising themselves at High 4.0, which on our older AVPro (and thus, older Exoplayer) worked. That said I realize this is an exoplayer issue (or lower) and not really an AVPro one so I'll close it for now. If I find a solution I'll post it here.
