### ISSUE TITLE
 360 video as skybox using AVPro

### ISSUE THREAD

**Issue by megha-sen** [RenderHeads/UnityPlugin-AVProVideo#718]
I want to apply the 360 video as skybox for immersive experience in a VR headset. The video is in Dash format so I am using AVPro to read the video in unity but I am not able to use it as a skybox. As with Unity video player, using skybox/panoramic shader we can easily do it. But how to do the same with AVPro.

**Comment by kahnivore** [comment]
Hi @megha-sen 

I believe I responded over email. But just in case, have you had a look at our [skybox shaders](https://www.renderheads.com/content/docs/AVProVideo/articles/usage-shaders.html#skybox-shaders)? 

You should be able to see an example of this in our Demo_DisplayComponents scene. 

Does this help?

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response.
