### ISSUE TITLE
Video fails to load when using 360 Audio on a device that doesn't support the media sample rate

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#719]
Repro steps:

1) Change your default audio device so that it is set to 44100hz (eg original Vive audio device  only supports this sample rate)
2) Try to play back media using 360 audio that has a 48000hz sample rate

The video will not load.

**Comment by RenderHeadsSte** [comment]
Closing as developer who reported reports this is fixed.
