### ISSUE TITLE
[#Jfi48] Multi-channel audio for VR

### ISSUE THREAD

**Issue by RenderHeadsMrT** [RenderHeads/UnityPlugin-AVProVideo#72]
**Describe the bug**
I see from the documentation that you support using the Unity audio path, which can allow multiple channels of audio from the video to be sent through Unity, then individual channels spatialized independently.

However, the documentation states that the hardware speaker setup must contain the same number of channels as the video contains – this does not make sense in a VR situation, where you may have 5.1 or 7.1 virtual speakers setup, but after binaural spatialization, the hardware is actually stereo HMD audio.

Is it possible to play back multiple channels of audio, but still have the hardware speakers set to stereo?

**Comment by owlboy** [comment]
Sending each channel of a 5.1 audio track to individual Audio Sources in the Unity Scene is the goal. 

This currently works with stereo audio tracks. Specifically, the Left and Right channels of the track can be placed in separate locations in the scene with separate audio settings for each Audio Source.

I apologize if this clarification is redundant. I just want to make sure it's clear.

**Comment by AndrewRH** [comment]
Thanks for the clarification

**Comment by AndrewRH** [comment]
For reference, another user has a similar request:


**Problem description:**

Does this plugin support direct audio output to a specific 5.1 channel?
Unity is set to 5.1, PC is set to 5.1 output. (playing a 5.1 video works correctly)
I like to mute left and right and only play the center channel using the output Audio script.
I can only get this feature to work when the it’s in Unity audio mode and stereo is checked.
But this only plays the sound in either left or right when using the channel filter the other channels do not work. 

Using Direct mode I can hear left right and center but I can’t disable the other channels using the audio script and deselecting channels.

I followed the instructions in the manual but I can’t get output to individual channels.
I also tried with a video that only had a mono channel and it did not work and the other channels were not playing only left and right.


**Device (which devices are you having the issue with - model, OS version number):**
PC


**Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):**
MP4 video with 5.1 audio encoded.

**System Information:**

AVPro Video: plugin v1.9.12 scripts v1.9.12
Target Platform: Standalone
Unity: v2018.3.0f2 WindowsEditor
OS: Desktop - To Be Filled By O.E.M. (To Be Filled By O.E.M.) - Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz - 12 threads - 16309KB
GPU: NVIDIA GeForce GTX 1060 3GB - NVIDIA - Direct3D 11.0 [level 11.1] - 2988KB - 16384

**Comment by cdytoby** [comment]
+1, on our side we have the similar requirement. Our client won't understand "spatial sound format", we're also investigating new formats besides TBE. But assign individual channel to different audio source is a big improvement if it can be done on PC, even better with android.

**Comment by owlboy** [comment]
Still very interested in sending each audio channel of a 5.1 audio track to separate individual Unity Audio Sources!

**Comment by fingerx** [comment]
+1

**Comment by AndrewRH** [comment]
We've written a new component which may be useful.  It allows control over per-channel volume.

[AudioChannelMixer.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/4235575/AudioChannelMixer.zip)

If you set the AudioOutputMode to Single then one of the channels will be duplicated to all other channels, which be use useful for a multi-speaker setup, where using the AudioChannelMixer component can be used to move that audio between the physical speakers.

![image](https://user-images.githubusercontent.com/5418126/75027110-ee1d9d80-5495-11ea-9fd4-188752c10a41.png)

This component might not help in all cases, eg being able to direct audio channels to specific Transforms, but this could act as a reference to make a new component to achieve this.

I'm closing this issue now - please open another issue on the specific topic if you're still having problems/feature requests.

**Comment by andriworld** [comment]
For anyone still trying to play each audio channel of a 5.1 audio track in a separate Unity AudioSource, here's how I configured each speaker object:
![image](https://user-images.githubusercontent.com/6136757/208475924-4df2515c-02ea-4fd7-a6d7-a6fd54533c4e.png)

Tested on  Windows and Android, Unity 2021.3.9f1, AVPro v2.6.7.  
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 92 kb/s (default)

**Comment by Chris-RH** [comment]
Very interesting, thank you
