### ISSUE TITLE
Videos not playing in Quest 1 Build (after playing fine in project) Plz help! 

### ISSUE THREAD

**Issue by sultanreflects** [RenderHeads/UnityPlugin-AVProVideo#720]
**Describe the bug**
New to Unity so forgive my greenness**
I purchased the Windows Core version of AVpro to use with a game with many videos playing through Timeline and building to Quest 1. I followed all the download and import instructions and got the videos working fine on my build but they had the logo. I was told it was because I had the Windows version not the Android. 

I then uninstalled the Windows version, bought the Android version, and set up all my clips from scratch. However, now none of the clips (same videos that worked in the build before) won't work in my build to Quest. They play fine in the Unity player--whether in the Timeline or outside of it (auto play on or off). But every time I build to Quest, nothing happens with the videos. 

I've rebooted multiple times, logged in and out of Unity, and even reverted back to an older version of the project (before I ever downloaded AVpro) and deleted all the Cache files and started from scratch. Still not working. 

****2 things to note.**** 
A) I feel like in the Windows version we stored the video files in the "Streaming Assets" (Basically mimmicking the way the sample videos were set up. This time around however, we don't get the Media Reference set up ability in that folder so we put them in the Videos folder. 

B) When I go back and review the packages in my project, it still says I can import the package, though all the items under the Media Player UI folder are unclickable. 

![Import AVPro settings](https://user-images.githubusercontent.com/39164315/114605651-ec95d280-9c5f-11eb-9284-3d6cac36d761.PNG)

Any ideas?

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.6f1
 - AVPro Video version:  2.0.11
 - Operating system version: AVPro Android Core Edition
 - Device model: Acer Predator running Windows 10
 - Video specs (resolution, frame-rate, codec, file size):  Have tried 2 different kinds
 - 540x1024 transparent with LR alpha packing, mpeg4, 5.38MB, 60fps, (used the LR alpha packing code from the manual)
 - 1920x1080, opaque, 60fps,mp4, 21MB

**To Reproduce**
1. I'm simply trying to get a video to play on the quest build. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.
EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hmmm have you tried on another Android device?

Have you checked in Player Settings to make sure the Vulkan graphics API is not set as default?

Have you tried to look at the [Android log](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs) to see if there is a useful error messages?

Thanks,

**Comment by sultanreflects** [comment]
Hey, 
After doing some experiments I found a workaround - at least for now. Ultimately, I just started saving all the files in the Demo materials folder that's in the Streaming Assets folder. I did a test build of one of the demo scenes and it worked. Then I copied the Cube with the 2d apply to mesh video and pasted it into my scene, did a build, and that worked. So I knew the player was at least working. 
Then I put another video in that same folder and after that they worked. So I'm just going to do that for now. But if there's a reason why they wouldn't work out of the videos folder I'd still like to know. 

Cheers,

**Comment by RenderHeadsSte** [comment]
There is no reason videos in the StreamingAssets folder will not work on Android.  Your MediaPlayer component should look something like this:

![image](https://user-images.githubusercontent.com/46531149/115617024-cc61b580-a2e8-11eb-9451-7aa927a8e91e.png)

If you are loading out of an 'Absolute Path' on the device, then you will have to ensure you have the correct path to the 'sdcard' on the device (it is something like /storage/emulated/0/ usually, but is different on different Android devices).  You will also need to ensure you have the correct permissions to access files outside the applications root installed folder (Issue #596 might help guide you here).

Please do post a log if you are still having issue.

**Comment by RenderHeadsSte** [comment]
Are you still requiring support on this issue @sultanreflects, or can we close it?

**Comment by sultanreflects** [comment]
Hi, 
No I resolved the issue. I just added everything to the AVP sample folder so that seems to be the only thing that'll work for me. 
Thanks 
SS
