### ISSUE TITLE
unity export webgl  cannot play video on ios devices

### ISSUE THREAD

**Issue by hasionerin** [RenderHeads/UnityPlugin-AVProVideo#721]
unity export webgl  cannot play video on ios devices

Unity2019.1.4

**Comment by kahnivore** [comment]
Hi @hasionerin 

Mobile devices are not supported by WebGL. Please see supported platforms in the Unity docs [here ](https://docs.unity3d.com/Manual/webgl-gettingstarted.html).

Thanks.
