### ISSUE TITLE
I bought avprovideo1. x, why can't I upgrade to 2. x

### ISSUE THREAD

**Issue by LBCross** [RenderHeads/UnityPlugin-AVProVideo#722]
![image](https://user-images.githubusercontent.com/19235947/114693783-86d34480-9d4c-11eb-87ab-4142820da7d0.png)

**Comment by kahnivore** [comment]
Hi @LBCross 

AVPro Video 2.x is a separate product to 1.x. We offer discounts to all 1.x users, please see discounted upgrade paths [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#owners-of-avpro-video-1x).

Please let us know if you have further questions.

**Comment by LBCross** [comment]
> Hi @LBCross
> 
> AVPro Video 2.x is a separate product to 1.x. We offer discounts to all 1.x users, please see discounted upgrade paths [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#owners-of-avpro-video-1x).
> 
> Please let us know if you have further questions.

ok. thanks
