### ISSUE TITLE
WebGL build: Video not working because of typo in jslib

### ISSUE THREAD

**Issue by yp3898** [RenderHeads/UnityPlugin-AVProVideo#723]
**Describe the bug**
The WebGL build is not working because of the error _gl is not defined_

**Your Setup:**
 - Unity version: 2019.4.22f1
 - AVPro Video version: v2.0.11-Trial
 - Operating system version: Windows 10
 - Browser: Brave

**To Reproduce**
1. Create scene and player with getting started tutorial
2. Build and run with WebGL and hls.js
3. Resulting in the following error 
![Browser](https://user-images.githubusercontent.com/39097159/114723105-ad887f80-9d3a-11eb-803f-1910a264687f.PNG)

**Fix**
1. Changing jslib
![Error](https://user-images.githubusercontent.com/39097159/114723229-cd1fa800-9d3a-11eb-8510-1479a2b3a006.PNG)
to
![fix](https://user-images.githubusercontent.com/39097159/114723852-4919f000-9d3b-11eb-945e-906565999e82.PNG)

**Comment by kahnivore** [comment]
Hi @yp3898 

Thanks for reporting this. It will be fixed in the next update.

**Comment by AndrewRH** [comment]
Fixed in 2.1.0 which will be released soon
