### ISSUE TITLE
EXC_BAD_ACCESS when playing a video on iOS

### ISSUE THREAD

**Issue by cihadturhan** [RenderHeads/UnityPlugin-AVProVideo#724]
**Describe the bug**
Closing a media and opening another leads to crash. Unfortunately I can only see symbols

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.3
 - AVPro Video version: 2.0.11
 - Operating system version: 14
 - Device model: iOS 
 - Video specs (resolution, frame-rate, codec, file size): Video captures recorded with 30 FPS HD & 4K on iPhone XR (HEVC)

**To Reproduce**
1. Open a video
2. Close it
3. Open another in a short time

**Logs**

```
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2021-04-15 03:16:59.432606+0300 x[13503:1519237] [Player] asset duration is   2.62 seconds
2021-04-15 03:16:59.432652+0300 x[13503:1519237] [Player] creating 2 player items
2021-04-15 03:16:59.434302+0300 x[13503:1519237] [Player] asset is compatible with AirPlay
2021-04-15 03:16:59.441199+0300 x[13503:1519237] [Player] player time control status changed to paused
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

2021-04-15 03:16:59.574407+0300 x[13503:1519237] [Player] player rate changed to  0.000
2021-04-15 03:16:59.574460+0300 x[13503:1519237] [Player] player time control status changed to paused
2021-04-15 03:16:59.575380+0300 x[13503:1519237] [Player] player time control status changed to paused
[AVProVideo] Opening /var/mobile/Media/DCIM/118APPLE/IMG_8971.MOV (offset 0) with API 
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object, Object)
UnityEngine.Debug:Log(Object, Object)
RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia()
RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(MediaPathType, String, Boolean)
...
```

**Screenshots**
Unfortunately, I can only share crash break breakpoint screenshots.
Do you plan to share source code?

![image](https://user-images.githubusercontent.com/3739536/114796739-53b7a200-9d9a-11eb-8a04-4ed2ba45bf88.png)
![image](https://user-images.githubusercontent.com/3739536/114796760-5d410a00-9d9a-11eb-83d0-89ba4b71f3ba.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Thanks @cihadturhan 

I believe that this may by the same issue as this one:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/704

If so, then this has been fixed and will be available in the next release (soon)

Thanks,

**Comment by AndrewRH** [comment]
Actually it might not be exactly the same bug - since you're getting a hard crash.

questions:
1) Do you get this crash in the Editor or only on the iOS device?
2) Are you able to reproduce this using our demo scenes and sample media?

Thanks,

**Comment by cihadturhan** [comment]
@AndrewRH 
1. It happens on iOS device.
2. I haven't tried with sample media but I'll take a look. This crash is hard to reproduce because it looks like random but I'll try.

**Comment by MorrisRH** [comment]
I've been unable to reproduce this using our Demo_Playlist scene and two 4K@60 videos using the following:
- Unity 2020.3.4f1
- iPad Pro (10 inch), iOS 14.4
- AVPro Video 2.1.0

It may be that this got fixed as part of the improvements for version 2.1.0.

If you're able to make a scene with a reproducible case please send it to unitysupport@renderheads.com so that we can investigate further.

**Comment by cihadturhan** [comment]
@MorrisRH thanks for your time and effort.
I think it's ok to close issue now. I'll try updated version and try to reproduce if I see similar issue.

**Comment by georgemarkosian** [comment]
After updating to 3.0.6 the problem still exists for us. We hoped it was an old issue from 2.9.* versions. We use Unity 2022.3.40, iOS, Android, and Unity. We're a live app with ~13K DAU. We use Crashlytics and we have many reports and logs regarding this. We're happy to share any information to help with the fix.

<img width="1280" alt="Screenshot 2024-08-15 at 13 02 35" src="https://github.com/user-attachments/assets/102a5753-7a96-4f01-add9-8db5422c3f89">

**Comment by Chris-RH** [comment]
Hi @georgemarkosian 

Can you open a new issue for this and fill out the form with as much detail as possible.
Can it be reproduced in a new project only running our demo scenes?
What devices is the error occurring on?
Can you provide crash logs

**Comment by georgemarkosian** [comment]
Hello Chris, thank you for the quiz response. I'll open a new issue and fill everything. Our team hadn't succeeded in reproducing this issue, all our iOS test devices work with no issues even when we follow our users' steps. We can't tell you whether a new project works fine or not as we can't place it in the same environment. The only place where we see it is our live app. All data we have comes from Firebase Crashlytics. I'll try exporting it or, alternatively, we can add you as a viewer to our Firebase project and let you explore the crash reports. Or we can do it together on a Meet/Zoom call, whatever works for you.

**Comment by georgemarkosian** [comment]
As for the devices, I see the full spectrum of iPhones and iPads, from 7 Plus to 15 Pro Max, and also iOS versions (17.5.1, 16.6.1, 15.8.2, 18.0.0).

Additionally, we use multithreaded rendering in our Unity app as it has plenty of 3D content.
