### ISSUE TITLE
long time avpro crash

### ISSUE THREAD

**Issue by fingerx** [RenderHeads/UnityPlugin-AVProVideo#730]
A long-running avpro internal error, the program exits directly

 - Unity version: Unity2018.3.34f1
 - AVPro Video version: version 2.0.11 (plugin v2.0.10f1 - ultra)
 - Operating system version: win20H2, 19042.928
 - Device model: win x64,rtx5000,64gb ram,i9-10920x cpu
 - Video specs (resolution, frame-rate, codec, file size): 
 - 
![image](https://user-images.githubusercontent.com/5524551/115097866-38e25a80-9f5f-11eb-83d8-810fb4e26419.png)

avpro setting:
![image](https://user-images.githubusercontent.com/5524551/115097892-60392780-9f5f-11eb-84b5-65164850a915.png)

**Logs**
note: start avpro is ok and playing is loop ok but long time avpro internal error, the program exits directly

2021/04/16/10:20:54:951 [ERROR] Unity: [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
UnityEngine.Debug:LogError(Object)
RenderHeads.Media.AVProVideo.MediaPlayer:Update()

test three pc ,same error,need your help.

**Comment by fingerx** [comment]
@AndrewRH three days,need avpro team help,thanks

**Comment by AndrewRH** [comment]
Hi,

A few questions:
1) Are you able to reproduce this error using the MediaPlayer demo scene?
2) Are you able to reproduce this error using one of our sample videos?
3) How long do you have to leave it looping for the crash to occur?
4) If you set the Audio Output mode to None/System Direct does the problem go away?
5) Is there any error message / log generated when the crash occurs and causes Unity/your app to quit?

Thanks,

**Comment by fingerx** [comment]
thanks infos, I will give you detailed information later.

**Comment by fingerx** [comment]
@AndrewRH  want to know system direct sound test in 5.1/7.1 sound system[usb sound card or build in ],Has this feature been tested? thanks

**Comment by fingerx** [comment]
1.using mediaPlayer demo and setting unity sound 5.1， this usb system 5.1 sound dont work, using system direct ,usb 5.1 sound card ok and 2 hours is running ok.
2.It seems that there is a problem with my program, and I need to investigate further.
3.my exe running >8h，is crash and show "Unity: [AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources."
4.Still testing...
5.New mode still testing...

@AndrewRH  thanks for all!

**Comment by fingerx** [comment]
Driver problem, update the latest sound card driver
