### ISSUE TITLE
Recieving errors when upgrading AVPro

### ISSUE THREAD

**Issue by nirniron** [RenderHeads/UnityPlugin-AVProVideo#732]
**Describe the bug**
I've received a project using AVPro 
[AVProVideo] Initialising AVPro Video (script v1.9.2 plugin v1.9.1)
which was giving me the error `Unsupported D3D format 0x58 unity` and stopping the flow whenever playing a video.
checking this conversation
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/85

I've thought the reason could be AVPro not up to date.
before purchasing, I downloaded the trial watermarked version for technical testing and replaced the old version.
after the upgrade I immediately received the following errors

1.Assets\AVProVideo\Runtime\Scripts\AssetTypes\MediaReference.cs(15,10): error CS0246: The type or namespace name 'MediaPath' could not be found (are you missing a using directive or an assembly reference?)

2.Assets\AVProVideo\Runtime\Scripts\AssetTypes\MediaReference.cs(20,10): error CS0246: The type or namespace name 'MediaHints' could not be found (are you missing a using directive or an assembly reference?)

3.Assets\AVProVideo\Runtime\Scripts\AssetTypes\MediaReference.cs(87,51): error CS0246: The type or namespace name 'Platform' could not be found (are you missing a using directive or an assembly reference?)

4.Assets\AVProVideo\Runtime\Scripts\AssetTypes\MediaReference.cs(14,20): error CS0246: The type or namespace name 'MediaPath' could not be found (are you missing a using directive or an assembly reference?)

5.Assets\AVProVideo\Runtime\Scripts\AssetTypes\MediaReference.cs(19,20): error CS0246: The type or namespace name 'MediaHints' could not be found (are you missing a using directive or an assembly reference?)

in previous attempt (deleting the old AVPro rather than updating) I've also had an issue with 
mediaplayer.FileLocation inaccessibility due to protection level and many more errors.
I need an explanation of what is the correct way to upgrade AVPro from 1.9.2 to 2.0.11

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.6
 - AVPro Video version: 1.9.2
 - Operating system version: win 10 64 bit 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): mp4 

**To Reproduce**
1. install AVPro 1.9.2 in a unity project
2. upgrade to 2.0.11 trial

**Comment by AndrewRH** [comment]
Hi,

So I believe this issue was resolved in a later version:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/85

The 2.0.11 version is a new product with large API changes.  You can see some documentation about upgrading here:
https://www.renderheads.com/content/docs/AVProVideo/articles/upgrading-from-avpro-video-1x.html

The latest version of the previous 1.x series is still available, and you can try the trial here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/tag/1.11.7

Upgrading to the 1.11.7 from your 1.9.2 should work seamlessly and resolve your original error.

Thanks,

**Comment by RenderHeadsSte** [comment]
Can you provide some feedback @nirniron? (so we might look to close this issue)

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
