### ISSUE TITLE
AudioOutput not repsonding with certain videos on MacOS

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProVideo#734]
From Keeping:

**Describe the bug**
The user sent a video showing how the AudioOutput works as expected with one of the sample videos, but then added their own video to test and it did not register audio coming in. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.15f1
 - AVPro Video version: 2.0.0
 - Operating system version: MacOS
 - Device model: not sure 
 - Video specs (resolution, frame-rate, codec, file size): 720x1440, 60fps, h264, 1.74mb 

**To Reproduce**
1. Install AVPro (also tested on 2.0.11)
2. Set user's video to media player in Demo_MediaPlayer
3. Play and note that AudioOutput bar does not show output on UI bar or in inspector, although audio is playing audibly

**Comment by MorrisRH** [comment]
Audio tracks with no language set in the metadata are being skipped.

A workaround for now is to fix up the video using the following ffmpeg command:
```ffmpeg -i in.mp4 -c copy -metadata:s:a:0 language=eng out.mp4```

**Comment by MorrisRH** [comment]
This will be fixed in the next release
