### ISSUE TITLE
AVPro Android: m3u8 and ts file playback from StreamingAssets Folder on Quest not working

### ISSUE THREAD

**Issue by davidfufu** [RenderHeads/UnityPlugin-AVProVideo#735]
AVPro Player v2.0.10f1-ultra 
build target is the Oculus Quest.
Unity 2019.4.16

 We are trying to stream playback m3u8 files from the root of the StreamingAssets folder and although it works in the editor, it doesn't work in build. However, playback from the StreamingAssets folder works for mp4 files so I know it's not an issue with the Quest not being able to access the StreamingAssets folder.

In the unity editor, during play mode, everything works as expected, but in build, AVpro gives the error message :

`
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
`

Logcat gives a more detailed error:

`com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.`

Here is my Streaming Assets Folder structure:

StreamingAssets
    >fossola.m3u8
    >riomaggiore_shot_02_v009_audio3840_20mb_00001.ts
    >riomaggiore_shot_02_v009_audio3840_20mb_00002.ts
    >riomaggiore_shot_02_v009_audio3840_20mb_00003.ts
    >etc...

There are 10 ts files in total and are in the root StreamingAssets folder along with the m3u8 file. Here is the fossola.m3u8 file contents:
```

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00001.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00002.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00003.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00004.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00005.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00006.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00007.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00008.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00009.ts
#EXTINF:3,
riomaggiore_shot_02_v009_audio3840_20mb_00010.ts
#EXTINF:1,
riomaggiore_shot_02_v009_audio3840_20mb_00011.ts
#EXT-X-ENDLIST
```

I have also sent an invitation for collaboration on a private repo with the build.

**Comment by AndrewRH** [comment]
As far as I know StreamingAssets is compressed into the JAR file, so it is not a normal part of the file system.  If you want to playback something like HLS you should copy the files into a real file system, into your [peristentDataPath](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html)

**Comment by davidfufu** [comment]
I've specified .m3u8 files and .ts files in the  aaptOptions noCompress property in the  mainTemplate.gradle file so it's not compressing. I can also confirm I've played back a mp4 file from the StreamingAssets folder. Right, I think I'm just going to copy them from StreamingAssets to persistentDataPath and play them that way.

**Comment by RenderHeadsSte** [comment]
Andrew is correct on this one.  The JAR file is a compressed file.  I am not aware of any mechanism in the ExoPlayer API that will allow playback of an HLS stream out of a compressed file, regardless of whether the files in the JAR are actually compressed or not.  The problem is they are obfuscated by the compressed JAR file.

Your options are going to be:

- Place your HLS stream manifest and segment files on your devices file system.
- Manually extract the HLS files from the Unity asset system (the JAR), saving them to the local devices file system for playback.
- Use the new caching system in v2.1.0 to cache the HLS stream from a remote server and then playback the HLS stream out of cache every subsequent time playback is required.

**Comment by davidfufu** [comment]
Thanks, I think the manifest couldn't find the segment files within the StreamingAssets folder. I copied them over to persistentData path and playback is working.
