### ISSUE TITLE
Full screen button

### ISSUE THREAD

**Issue by nintendaii** [RenderHeads/UnityPlugin-AVProVideo#737]
Hi. I was wondering if it is possible to make full screen feature in AVP Video Player. I want to implement the maximizing video functionality into my app. I thought this feature is native for AVP but I can't find it. Any suggestions?

**Comment by RenderHeadsSte** [comment]
This is 100% possible, but such functionality is left to the developer to implement according to their use-case.

You could control the size of your video display dynamically by adjusting the size of the Transform/RectTransform of your display component (e.g. Display uGUI).
