### ISSUE TITLE
AVProVideo support rtsp or flv?

### ISSUE THREAD

**Issue by sd63534790** [RenderHeads/UnityPlugin-AVProVideo#738]
Hls is Too much delay, Ask it can support flv or rtsp? Reference flv.js?

**Comment by RenderHeadsSte** [comment]
RTSP has limited support on some platforms (see [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html)).

Regarding FLV.  There should be limited support on Android when using the ExoPlayer API path (see [here](https://exoplayer.dev/supported-formats.html) for supported formats and limitations).  But in testing I could not get playback to work.
