### ISSUE TITLE
Android Phone Show blank screen. AVProVideo-v2.1.0-Trial

### ISSUE THREAD

**Issue by waisoon90** [RenderHeads/UnityPlugin-AVProVideo#739]
hi , i try demo media player scene in AVProVideo-v2.1.0-Trial package with unity3D 2020.3.4f1 , 2019.4.24 both show empty black screen but the audio did works ..Device Huawei Nova 4e .. android version 9

**Comment by RenderHeadsSte** [comment]
Can you post a full logcat output file please?

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
