### ISSUE TITLE
Unable to sync HLS video playback across multiple players

### ISSUE THREAD

**Issue by mikemilla** [RenderHeads/UnityPlugin-AVProVideo#742]
I am making a game that uses a dedicated server to grab a video url m3u8, send that url to the clients, and the clients start playing the video. The goal is to have the playback synchronized as closely as possible.

This works well, but getting them to sync up is very difficult. The video playback is not guaranteed to have the same exact duration of the video. Or more simply put: forcing the client video players to skip to a specific time will not work.

I've tried a few other approaches, with no luck as well.

----

Here is my latest idea.

I want to use these functions, but do now know how to use them properly because there is missing documentation (or at least I haven't found it):
`StartOpenChunkedMediaFromBuffer`
`AddChunkToVideoBuffer`

What I would like to try:
1. Get the current playing url in the playlist
2. Pass that url to all the clients
3. On the clients add that url to the player playlist
4. Let the player do it's thing

I am using Unity and exporting for Windows PC.

If someone has docs or knows a better way to handle this please let me know! 
Apologies for this not _really_ being a bug

**Comment by AndrewRH** [comment]
Hi,

I'm not sure what code you're written already to try to get play them in sync.  Some code will definitely be needed as syncing won't happen by itself, and there is always latency and differences between each instance that need to be dealt with.

For example, when loading the videos, you should wait for all instances to buffer a certain amount before calling Play on all of them.   Then once they are playing, there will still be some tiny time difference which will build up over time, that must be dealt with otherwise the players will drift out of sync.  One way to do this is to call Pause() then Play() again within the same frame (this is known as micro-pausing) and this will gradually slow down the player that is ahead of the others.  If things get way out of sync, then the players have to pause, seek to a time, wait for buffering and then play again.  

We haven't have any nature support for this, but below I've attached some old sample code which may give you some ideas, but probably won't compile.

Does that answer your question?

Thanks,

```
using UnityEngine;
using RenderHeads.Media.AVProVideo;

//-----------------------------------------------------------------------------
// Copyright 2015-2020 RenderHeads Ltd.  All rights reserved.
//-----------------------------------------------------------------------------

namespace RenderHeads.Media.AVProVideo.Demos
{
	/// <summary>
	/// Small demonstration of how you might synchronise multiple video playback
	/// Ideally the videos should be encoded with as many key-frames (I-frames) as possible
	/// </summary>
	public class PlaybackSync : MonoBehaviour
	{
		private enum State
		{
			Loading,
			Playing,
			Finished,
		}

		public MediaPlayer _masterPlayer;
		public MediaPlayer[] _slavePlayers;
		public float _toleranceMs = 30f;
		public bool _matchVideo = true;
		public bool _muteSlaves = true;
		private State _state = State.Loading;

		void Start()
		{
			// Setup the slaves
			for (int i = 0; i < _slavePlayers.Length; i++)
			{
				_slavePlayers[i].m_Muted = true;
				if (_matchVideo)
				{
					_slavePlayers[i].OpenVideoFromFile(_masterPlayer.m_VideoLocation, _masterPlayer.m_VideoPath, false);
				}
			}
		}

		void LateUpdate()
		{
			if (_state == State.Loading)
			{
				// Finished loading?
				if (IsAllVideosLoaded())
				{
					// Play the videos
					_masterPlayer.Play();
					for (int i = 0; i < _slavePlayers.Length; i++)
					{
						_slavePlayers[i].Play();
					}
					_state = State.Playing;
				}
			}

			if (_state == State.Finished)
			{
				Debug.Log("Do Something");
			}
			else if (_state == State.Playing)
			{
				if (_masterPlayer.Control.IsPlaying())
				{
					// Keep the slaves synced
					float masterTime = _masterPlayer.Control.GetCurrentTimeMs();
					for (int i = 0; i < _slavePlayers.Length; i++)
					{
						MediaPlayer slave = _slavePlayers[i];
						float slaveTime = slave.Control.GetCurrentTimeMs();
						float deltaTime = Mathf.Abs(masterTime - slaveTime);
						if (deltaTime > _toleranceMs)
						{
							slave.Control.SeekFast(masterTime + (_toleranceMs * 0.5f)); // Add a bit to allow for the delay in playback start
							if (slave.Control.IsPaused())
							{
								slave.Play();
							}
						}

						// TODO: add per-frame micropauses to get videos in sync.  This can be done with a Pause() in Update() and a Play() in LateUpdate()
						// to slowly shift slave videos that are ahead back in sync.
					}
				}
				else
				{
					// Pause slaves
					for (int i = 0; i < _slavePlayers.Length; i++)
					{
						MediaPlayer slave = _slavePlayers[i];
						slave.Pause();
					}
				}

				// Finished?
				if (IsPlaybackFinished(_masterPlayer))
				{
					_state = State.Finished;
				}
			}
		}

		private bool IsAllVideosLoaded()
		{
			bool result = false;
			if (IsVideoLoaded(_masterPlayer))
			{
				result = true;
				for (int i = 0; i < _slavePlayers.Length; i++)
				{
					if (!IsVideoLoaded(_slavePlayers[i]))
					{
						result = false;
						break;
					}
				}
			}
			return result;
		}

		private static bool IsVideoLoaded(MediaPlayer player)
		{
			return (player != null && player.Control != null && player.Control.HasMetaData() && player.Control.CanPlay() && player.TextureProducer.GetTextureFrameCount() > 0);
		}

		private static bool IsPlaybackFinished(MediaPlayer player)
		{
			bool result = false;
			if (player != null && player.Control != null)
			{
				if (player.Control.IsFinished())
				{
					result = true;
				}
			}
			return result;
		}
	}
}
```

**Comment by mikemilla** [comment]
@AndrewRH thanks for the advice. I looked into this snippet in the examples before. It works for HLS streams that return the same video "chucks" all the time.

The source of the stream I am working with is different per client. Or in other words, the stream may not return the same video chucks back as the other clients.

I am working on trying this to solve it now: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/792

Simple idea is to just pass the raw bytes from the master player to the slave players.

It would be incredible if the media player had a `mediaplayer.streamRawBytes((byte[]) => {  })` and also a `mediaplayer.playRawBytes(byte[])`
