### ISSUE TITLE
Does the mobile terminal play video support buffering? (translated online)

### ISSUE THREAD

**Issue by yoyohan1** [RenderHeads/UnityPlugin-AVProVideo#743]
请问下，使用AVProVideo在移动端上播放视频，可以支持边缓冲边播放吗？

**Comment by fingerx** [comment]
please using english

**Comment by yoyohan1** [comment]
Can I use avprovideo to play video on the mobile terminal while buffering?

**Comment by RenderHeadsSte** [comment]
I am not sure I understand what you are asking.  Could you provide more detailed information about what your use-case is an what platform(s) you are targeting?

**Comment by yoyohan1** [comment]
videoPlayer.Control.GetBufferingProgress()   This value not change In AndroidPhone. but this value alway is 1 In UnityEditor。The bufferProgress can not follow and greater than GetCurrentTimeMs() ?

**Comment by RenderHeadsSte** [comment]
What exactly is your use-case?

You can get the buffering times using:

TimeRanges times = _mediaPlayer.Control.GetBufferedTimes();

...which we us in our MediaPlayerUI,cs script to render the buffered ahead portion of the video on the scrub bar in the Demo_MediaPlayer example scene.

**Comment by yoyohan1** [comment]
get it

**Comment by yoyohan1** [comment]
Where is the buffer cache In the disk？
