### ISSUE TITLE
Content Protection video embedding not working?

### ISSUE THREAD

**Issue by Cucurbit1988** [RenderHeads/UnityPlugin-AVProVideo#746]
Referred to in the https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-core.html of the ContentProtection;Mp4 + % 1% ~n1-hidden. Mp4 is always unable to insert the video into an empty video. Is there a problem with the command?

**Comment by AndrewRH** [comment]
There's nothing wrong with the command - I just tested it.

It required that you have a file named DummyVideo.mp4 and that you create that command as a .bat file.  You then drag your video into the .bat file and it will product the hidden video.

Thanks,

**Comment by RenderHeadsSte** [comment]
Does this help @Cucurbit1988?

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
