### ISSUE TITLE
The local m3u8 file cannot be played

### ISSUE THREAD

**Issue by lhmgithub** [RenderHeads/UnityPlugin-AVProVideo#747]
1、Windows platform  Version 2.0.10
2、The m3u8 file contains the available URI and need httpHeader，I added a custom header。
`   mediaPlayer.GetCurrentPlatformOptions().httpHeaders.Add("MtsHlsUriToken", "2345678");   
        mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, path);`
3、Then the video duration has been obtained but it cannot be played back
4、I tried another way, too `     mediaPlayer.GetCurrentPlatformOptions().keyAuth.overrideDecryptionKey = Convert.FromBase64String("qwertyuiop123456");`  But it still won't play

**Comment by RenderHeadsSte** [comment]
What API are you using? (DirectShow/MediaFoundation/WinRT)

Can you provide a URL and header to test (valid for a long as possible to give us a chance to test here)?  You can email this to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) if you wish to keep it private.

**Comment by lhmgithub** [comment]
MediaFoundation
unity2018.4.15f1
window10 Education edition
 in the Unity Editor

**Comment by kahnivore** [comment]
Hey @lhmgithub 

You'll need to switch from Media Foundation to WinRT. It's the only Windows API that supports HTTP headers. 

Let us know if this solves your problem.

Thanks!
