### ISSUE TITLE
When plugging in and out the headset, the video under IOS platform gets stuck

### ISSUE THREAD

**Issue by mengflyQ** [RenderHeads/UnityPlugin-AVProVideo#749]
**Describe the bug**
I have a problem: when I play video on my iPhone, the video gets stuck when I unplug the headset。I've checked “Resume playback on audio session route change”

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.12f1
 - AVPro Video version: 1.11.0
 - Operating system version: IOS
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. The video can continue to play

**Screenshots**
![image](https://user-images.githubusercontent.com/59573433/116380194-501a2580-a846-11eb-8731-1793a382ae0e.png)
![image](https://user-images.githubusercontent.com/59573433/116380646-b8690700-a846-11eb-9f38-5213debabe7a.png)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us 2569386351@qq.com

**Comment by MorrisRH** [comment]
I can't reproduce this, playback is resuming just fine when unplugging headphones.
My set-up:
- Unity 2019.4.22f1
- AVPro Video 1.11.7
- iPad Pro, iOS 14.4.2

**Comment by kahnivore** [comment]
Hi @mengflyQ 

Please let us know if you're still experiencing this issue. If so, could you send a reproducible project case to unitysupport@renderheads.com? 

Thanks.

**Comment by MorrisRH** [comment]
Should also mention that pausing playback on headphone removal is the expected behaviour on iOS.

**Comment by mengflyQ** [comment]
Solved. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Morris ***@***.***&gt;; 
发送时间: 2021年5月4日(星期二) 晚上7:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] When plugging in and out the headset, the video under IOS platform gets stuck (#749)





 
Should also mention that pausing playback on headphone removal is the expected behaviour on iOS.
