### ISSUE TITLE
Crash on close when playing an mp4 with multiple audio tracks and switching between them

### ISSUE THREAD

**Issue by MorrisRH** [RenderHeads/UnityPlugin-AVProVideo#751]
When playing an mp4 with multiple audio tracks whilst using the AudioOutput component and having switched between audio tracks, the player will crash when Close is called.

**Comment by MorrisRH** [comment]
The crash is being caused by a buffer over-release. This has been fixed and will be available in the next release.

**Comment by Jammyo** [comment]
This is tagged iOS and macOS, but I think this is the same issue I'm getting on Windows caused by a recent windows update. Is that possible?

**Comment by MorrisRH** [comment]
This issue is specific to the implementation of the native component for macOS and iOS and will have nothing to do with the Windows plugin. However, issue #752 might be related to the problem you're seeing.
