### ISSUE TITLE
Possible memory leak on 1.11.7 with PlaylistMediaPlayer

### ISSUE THREAD

**Issue by kahnivore** [RenderHeads/UnityPlugin-AVProVideo#754]
From forums: 

Hi, In Unity2019.4.17, I used AVpro1.11.7 to release a Windows10 - x86_64 application, and it contain 4 or 5 Horizontal arrangement Videos,then they are all playlist media player, videos are streaming asset. Now it would only be application crashing after your application has been running for a while, not on the first play. when all videos is playing, textures of memory has been increasing in profiler. Was it a memory leak bug？What Can I do? Thank you. Or what are the coding requirements for MP4 video files?

The App crash is random after the application has been running for a while.
Latest test results:
I Use the playlistmedia player (beta).When the number of video items exceeds 2, and each time the video is switched and played to the next video,so textures of the memory will increase in profiler. Yesterday, the result increased from 100M to 7G.
When the number of video items is one or two, textures of the memory will not increase in profiler.

 - Unity version: 2019.4.7
 - AVPro Video version: 1.11.7
 - Operating system version: Windows 10

![pic1](https://user-images.githubusercontent.com/44468274/116400262-26530580-a82a-11eb-8527-8641ab8a65f6.png)
![pic2](https://user-images.githubusercontent.com/44468274/116400270-27843280-a82a-11eb-888a-35ffaa648ec5.png)

**Comment by z79422957** [comment]
Hi, How can I solve this problem Please?

**Comment by kahnivore** [comment]
Hey @z79422957 

Roughly how long does the app run for before it crashes?

Would you be able to send us a sample reproducible project to unitysupport@renderheads.com?

**Comment by z79422957** [comment]
In version 1.11.7 package, Demos -  scenes ‘14_Demo_PlaylistTransitions’,It will have the problems I said. New version 2.1.0 is no the problem.

**Comment by AndrewRH** [comment]
Hi @z79422957 

Thanks for reporting this issue.  We found the problem and have attached the fixed script here.

[PlaylistMediaPlayer.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6442016/PlaylistMediaPlayer.zip)

Does that solve the issue for you?

**Comment by AndrewRH** [comment]
This has been fixed in 2.1.2.. I will close this issue now.
