### ISSUE TITLE
Crash when closing media

### ISSUE THREAD

**Issue by Jammyo** [RenderHeads/UnityPlugin-AVProVideo#757]
**Describe the bug**
At the beginning of March we received a bug report from a client that our software crashed. After a lot of investigation across multiple different machines we believe that something changed with the 2004 Windows update which has caused AVPro to very occasionally crash when trying to close some video files. When this crash occurs it is unrecoverable and the application hangs until it is forced to close. We originally experienced this crash in version 1 of AVPro, but have upgraded to version 2 in the hopes that it had already been found and fixed, but this bug is still present.

**Your Setup (please complete the following information):**
 - Unity version: 2021.1, but originally found in 2018.3.12
 - AVPro Video version: 2.0.11, but originally found in 1.11.4
 - Operating system version: Windows 20H2
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 
![image](https://user-images.githubusercontent.com/39237761/116590889-2b8d7e80-a916-11eb-9110-f92be5c04557.png)

**To Reproduce**
1. I created an empty project just with the latest AVPro.
2. I added a script to spawn multiple instances of AVPro (20 on my machine), and then to respawn them when they finish.
3. I added the media player with the default settings, added my media file using a media reference.
4. Usually around the 2nd/3rd iteration, Unity crashes.

**Logs**
I have struggled to get any logs because Unity closes before I get a chance, and any attached debugger does not stop/handle the crash.

**Videos**
I have emailed the video which most reliably causes this issue to unitysupport@renderheads.com.

**Comment by RenderHeadsSte** [comment]
Thanks for sending over the video.  So there is no doubt, can you send over the script or test project you are using please?

**Comment by Jammyo** [comment]
Just sent the test project by email. Thank you!

**Comment by kahnivore** [comment]
Hi @Jammyo 

We've tested this and have managed to reproduce the crash. We will investigate to see if this is something happening our side that we can fix - but it seems like quite a particular edge case.

In the meantime, it looks like there are some things you could adjust your side that would circumvent this issue entirely. For starters, your video is h.264 with a width greater than 4096, which is the max resolution for h.264 on Windows. Encoding with HEVC or HAP would be a lot better as h.264 doesn't support such wide video. Secondly, your video has an audio track encoded and removing this would help, seeing as though there's no audio playback. Thirdly, I'm not sure what your final project looks like, but having 20 Media Player instances is not necessary to play the same video. It would be better to use a single media player with multiple instances of display components. For the video in question you could also consider simply using a single texture and scrolling the UVs.

**Comment by Jammyo** [comment]
Hi thanks for the reply. I've been testing on an old machine I found in the cupboard, and I can't get it to crash on that which is a 1909 version of Windows. I can't be certain, but I'm increasingly thinking that a Windows update caused this issue.

Our final project is a piece of stadium software which plays multiple pieces of media in different locations configured by the stadium operator, so unfortunately we don't have much control over what media they add. As far as I understand, we need multiple media player instances, since we can't guarantee that they will start and finish at the same time (timings are configured by the user), if this is incorrect please point me in the right direction and I can make some optimisations. 

Good spot on the h.264 width being exceeded. I will add a warning to the software to encourage the user to re-encode in HEVC.
