### ISSUE TITLE
WebGL error in 2.0.10

### ISSUE THREAD

**Issue by sathishkntrj** [RenderHeads/UnityPlugin-AVProVideo#758]
**Describe the bug**
A clear and concise description of what the bug is. While i have taken the build as per the documentation given in AvPro and tested with .m3u8 extension file for webgl build in chrome and edge, am receiving the below error "ReferenceError: gl is not defined at _AVPPlayerFetchVideo

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.10f1
 - AVPro Video version: latest only
![AnyDesk_shKCQRh7fv](https://user-images.githubusercontent.com/83462532/116716314-3a972e00-a9f5-11eb-947f-de5c7d696c08.png)

 - Operating system version: windows 10
 - Device model: dell
 - Video specs (resolution, frame-rate, codec, file size):  its is a file with .m3u8 extension

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.
-> exception thrown: ReferenceError: gl is not defined,ReferenceError: gl is not defined
    at _AVPPlayerFetchVideoTexture (blob:https://dev-app-1.hexafair.com/64e43428-d488-4145-b97d-5cc77f1d5808:8:698917)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Please update to 2.1.0 - this issue has been fixed.

Thanks,

**Comment by sathishkntrj** [comment]
This has been working fine after i updated the version to AVProVideo-v2.1.0, thanks you so much

**Comment by sathishkntrj** [comment]
Hi Andrew,

Thanks for the solution you provided.
Can you please suggest the idea for passing the Absolute path or url
through script as we have a requirement of playing various live streaming
dynamically in cross platforms?
As we have planned to purchase the asset from unity asset store, once it
works.

Thanks and regards
Sathish kumar N
Hexafair, chennai
