### ISSUE TITLE
unable to pass Absolute path or url through script dynamically

### ISSUE THREAD

**Issue by sathishkntrj** [RenderHeads/UnityPlugin-AVProVideo#762]
**Describe the bug**
A clear and concise description of what the bug is. Need guidance in passing dynamic urls to AvPro mediaPlayer

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.10f1
 - AVPro Video version: 2.1.0
 - Operating system version: windows 10
 - Device model: dell
 - Video specs (resolution, frame-rate, codec, file size): passing url with .m3u8 extension

**To Reproduce**
1. Can you please suggest the idea for passing the Absolute path or url through script as we have a requirement of playing various live streaming dynamically in cross platforms?
As we have planned to purchase the asset from unity asset store, once it works.
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @sathishkntrj 

You could do something like this:             

`mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, "yourURL", true);`

Does this help?

**Comment by sathishkntrj** [comment]
woowww !
It works perfectly great.
