### ISSUE TITLE
HLS manifest still called after video player is closed when using hls.js

### ISSUE THREAD

**Issue by futuraspace** [RenderHeads/UnityPlugin-AVProVideo#763]
**Describe the bug**

we are using hls to stream different videos in multiple screens

we use "CloseMedia()" to stop buffering when you are not watching the stream.

Nevertheless it still calling to chunks.m3u8 , so the conection is not really closed

**Your Setup (please complete the following information):**
 - Unity version: 2020.1
 - AVPro Video version: 2.1.0
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size):  720p25fps streaming

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Can you provide what platform, device(s), OS version, and if possible your HLS stream link.

**Comment by futuraspace** [comment]
Hi ste sure

yes im in a middle of a event, its through this link
https://www.futura.space/offfbarcelona/  (you can register with fake email
and check one screen on the left in the virtual world) (you can enter in
server 7 8 9.. for example)

if you press F12 network filter by flumotion  you can see how even when you
leave the screen is calling to chunks.m3u8

what we see is that sometimes works but other no

hls link (is so confidential for the clients)
https://events4-live4.flumotion.com/playlist.m3u8

**Comment by futuraspace** [comment]
webgl, any browser.  I can not provide the link, but it comes from flumotion. If you debug the network from the browser, and filter by flumotion , there shows up calls to chunks.m3u8 even after closing the media player.

**Comment by patmval** [comment]
Any news on this matter?

**Comment by futuraspace** [comment]
hls.js library upgrated to version 1 and there are some changes in the configuration. Could be related to this? I attach the doc https://github.com/video-dev/hls.js/blob/v1.0.0/MIGRATING.md

**Comment by AndrewRH** [comment]
Is the issue that you're having while you're using hls.js with our plugin?    
If so, which version of hls.js are you using?  We don't use hls.js internally, it's an optional feature that you can add via External Library as documented here: 
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#webgl

If you're not using hls.js then it must just be the browser that continues to call that file.... Perhaps we can add something into our script to stop that, we'll have to look into it.

If you could let us know the answers to these questions it would help us.

Thanks,

**Comment by futuraspace** [comment]
Yes. I use the hls.min.js from the newest version. (I also tried v0.14)   If the m3u8 belongs to a normal video asset, it stops calling correctly. But when loading streaming videos keeps calling to chunks after closing media, and the queue increase every time you load another or the same streaming again.

**Comment by AndrewRH** [comment]
Oh I see.  Well I read this:
https://github.com/video-dev/hls.js/blob/master/docs/API.md#final-step-destroying-switching-between-streams

Perhaps we need to call the hls.destroy() as part of the media closing process...

**Comment by futuraspace** [comment]
there is a guy who added hls.destroy.  Do you plan to update the asset? https://www.gitmemory.com/issue/RenderHeads/UnityPlugin-AVProVideo/141/719405704

**Comment by AndrewRH** [comment]
@futuraspace 
thanks for this information - we will make sure this gets added to the next version

**Comment by AndrewRH** [comment]
@futuraspace 

here is the fixed JSLIB file (inside the ZIP).  Please replace the existing one in /Assets/AVProVideo/Runtime/Plugins/WebGL
[AVProVideo.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6617182/AVProVideo.zip)

Please do let me know if this fixes the issue for you.

Thanks,

**Comment by kahnivore** [comment]
Hi @futuraspace,

Did this fix work for you?
