### ISSUE TITLE
 [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

### ISSUE THREAD

**Issue by apar945** [RenderHeads/UnityPlugin-AVProVideo#764]
**Describe the bug**
Only noticed on the Samsung T505 tablet with One UI version 2.5. The same app works fine on windows, one version older Samsung Android tablet SM-T510 with One UI version 2.1. It is definitely not a size or memory issue. The Media player just fails to load another video after one has loaded, played and closed.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.25f1
 - AVPro Video version: 1.11.5
 - Operating system version: Android 10,One UI version 2.5
 - Device model: Samsung T505
 - Video specs (resolution, frame-rate, codec, file size): 1920*1200, 25 fps, MP4, 4 MB

**To Reproduce**
1. Use the MediaPlayer
2. Loading the first video and playing works.
3. Using the same media player open another video in the same scene and it fails.

**Logs**
2021-05-05 10:57:37.546 12376-12522/com.abc.xyz I/Unity: [AVProVideo] Opening jar:file:///data/app/com.abc.xyz-Atq-pNTq3QHEkh1lcXRnKg==/base.apk!/assets/Videos/vid1.mp4 (offset 0) with API ExoPlayer
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object, Object)
    UnityEngine.Debug:Log(Object, Object)
    RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at 
     
    (Filename: C Line: 0)
2021-05-05 10:57:37.751 12376-12522/com.abc.xyz I/System.out: AVProVideo changing video size 0x0 to 1920x1080
2021-05-05 10:57:37.777 12376-12522/com.abc.xyz I/Unity: [AVProVideo] Using playback path: ExoPlayer NonOES (1920x1080@-1.00)
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) 
     
    (Filename: C Line: 0)
2021-05-05 10:57:37.779 12376-12522/com.abc.xyz I/Unity: [AVProVideo] Texture ID: 154
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at 
     
    (Filename: C Line: 0)
2021-05-05 10:57:49.417 12376-12522/com.abc.xyz I/Unity: [AVProVideo] Creating player 2
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    RenderHeads.Media.AVProVideo.Helper:LogInfo(String, Object) (at

2021-05-05 10:57:49.420 12376-12522/com.abc.xyz I/Unity: [AVProVideo] Opening jar:file:///data/app/com.abc.xyz-Atq-pNTq3QHEkh1lcXRnKg==/base.apk!/assets/Videos/vid2.mp4 (offset 0) with API ExoPlayer
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object, Object)
    UnityEngine.Debug:Log(Object, Object)   

2021-05-05 10:57:49.494 12376-12522/com.abc.xyz I/System.out: AVProVideo error null
2021-05-05 10:57:49.502 12376-12522/com.abc.xyz I/Unity: [MediaPlayer] - [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
    UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
    UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
    UnityEngine.Logger:Log(LogType, Object)
    UnityEngine.Debug:Log(Object)
    RenderHeads.Media.AVProVideo.MediaPlayer:Log(String, Boolean)

**Comment by kahnivore** [comment]
Hi @apar945 

Is it always the same video that's failing to load? If so, could you provide details on which video codec and audio codec you are using? 

How are you closing the previous video and opening the next video? Where are your videos stored? 

Could you potentially provide a reproducible sample project? If so, please send to unitysupport@renderheads.com with  "#764" included in the subject line.

Thanks.

**Comment by apar945** [comment]
Hello
No it is not the same video. It is the second video. The previous video is unloaded use Stop and CloseVideo calls.
Also as far as I know it only happens on the Samsung tablet mentioned. A better error code would help us find the issue.
I have tried the unity video player and it works fine so if this can't be resolved then we will have to fall back to that.

**Comment by kahnivore** [comment]
Hi @apar945 

We'd still more info to be able to help. I'm trying to establish whether the second video is always the same video that fails i.e. if it's something specific with that video. Is there any chance you could send the video in question to us? 

Regarding the error, unfortunately the API's don't give us a lot of useful feedback so it's not really possible to be more specific with the error.

**Comment by apar945** [comment]
Hello @kahnivore 

I am 100% sure it is not the video. Only the first video we load works. The subsequent one doesn't.

These are the 2 key pieces of information that I provided
Operating system version: Android 10,One UI version 2.5
Device model: Samsung T505

It is only reproducible on this device. Unfortunately we are committed to using this device and have sourced multiple of them. 
You could run your tests on an Andorid device running the above One UI version to confirm.

**Comment by AndrewRH** [comment]
@apar945 thanks for this information.  What we really need is the full Android log so we can see what low-level messages are logged when the video fails to load.

We've put some [notes ](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#collecting-logs)together on how to get hold of these logs:

Thanks,

**Comment by apar945** [comment]
@AndrewRH 

Where can I email these logs?
I will share the error message here but I would like to email the logs rather than share it on a forum.

Regards

**Comment by apar945** [comment]
@AndrewRH 

I have attached the concise version of the logs for a single video that opens in the app on one prefab but fails on another in the same scene. 
Looking forward to your findings.

[003_Not_Working_With_AVPro.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6437548/003_Not_Working_With_AVPro.txt)
[003_Working_With_AVPro.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6437549/003_Working_With_AVPro.txt)

**Comment by AndrewRH** [comment]
The only thing this could be is an out of resources issue, probably the hardware decoder resources are limited to 1.   Something is still holding on to resources.  If we don't have a bug with resource leak, then I guess it might be the GC that's still holding on to them.  Maybe fixed by forcing a GC Collection between video loads.... 

Perhaps @apar945 you could test this theory, as we don't have access to that tablet device.

Before loading the second video, please try:
calling CloseMedia(); and then System.GC.Collect(); and then waiting a few frames before loading the video - does that help?

Otherwise we could perhaps also try calling System.gc() in Java... this should be possible via C# scripting but we'll have to work out the code for that....

**Comment by apar945** [comment]
@AndrewRH 

I have checked the profiler and don't see a spike in memory usage. When I switched to the default media player, the loading process seems to complete and player progress bar moves forward but no video is rendered. So it does better than the exo player but is not functional.

I am still waiting for an email address where I can send detailed logs if the above weren't sufficient.
Also I have not had any comment on the AVPro version I mentioned. (AVPro Video version: 1.11.5)

**Comment by RenderHeadsSte** [comment]
> Could you potentially provide a reproducible sample project? If so, please send to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) with "#764" included in the subject line.

Terry provided an email address to send extra support items over to us at, we also state it in the issue template.

We would always suggest updating to the latest version of AVPro Video (1.11.7 is the latest release of v1.x).  I would also suggest testing your use-case and on the troublesome device with the trial version of v2.x - found [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases/download/2.1.2/UnityPlugin-AVProVideo-v2.1.2-Trial.unitypackage))

**Comment by apar945** [comment]
Hello All,

We have switched to the default unity player which works without issues in our app. It is unfortunate that we couldn't get this resolved. 

Hopefully someone finds this thread helpful in future.

Regards
