### ISSUE TITLE
How to support 8k video in mobile (android and ios)?

### ISSUE THREAD

**Issue by 952067477** [RenderHeads/UnityPlugin-AVProVideo#77]
We test AVProVideo on android with local video file, it can play H264_7680x3840 with 30fps 170000kbps.It is great!
But we test AVProVideo on android with http stream video file, it can only play H264_4096*2048 with 30fps 170000kbps.
I want to ask about it, can AVProVideo support 8k steaming video on server? Or how to set video file to make it support 8k streaming video?

**Comment by AndrewRH** [comment]
I don't think there are any Android devices that can decode 8K.  The Oculus Go can decode 5K and that is the maximum of any Android device that I know of.  Which device are you using?

Perhaps you could also share the URL for us to test?

Also, which version of AVPro Video and Unity are you using?

**Comment by 952067477** [comment]
Hi!We use AVPro Video_1.8.7 and Unity 2017.4.21f1 (64-bit)_LTS， i copy the 8k video with 100000bitrate to persistentPath in android mobile, and open sample of AVPro, it can decode 8k video in local. But when use http streaming, it can only support 4K.
I have no url for this, just publish to a apk, and use a local server for streaming.


Kind Regards,
unicoea




------------------ 原始邮件 ------------------
发件人: "Andrew"<notifications@github.com>; 
发送时间: 2019年6月6日(星期四) 晚上6:04
收件人: "RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com>; 
抄送: "unico"<952067477@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] How to support 8k video inmobile (android and ios)? (#77)




I don't think there are any Android devices that can decode 8K.  The Oculus Go can decode 5K and that is the maximum of any Android device that I know of.  Which device are you using?
 
Perhaps you could also share the URL for us to test?
 
Also, which version of AVPro Video and Unity are you using?

**Comment by AndrewRH** [comment]
1) Which Android device are you using?
2) Did you try switching the Video API (in MediaPlayer > Platform Specific > Android)?

**Comment by 952067477** [comment]
we use device: xiaomi9 snapdragon 855
I use prefered media player for android video api. (in MediaPlayer > Platform Specific > Android)

**Comment by 952067477** [comment]
Hi! i test AVPro Video (1.9.17) with Unity 2018.4.0f1 (64-bit), the exoPlayer mode can only support 4k in http, not support 8k, but in local it can support 8k with mediaplayer mode.
If it can support 8k with http in future, it will be wonderful!
Thank you!

**Comment by AndrewRH** [comment]
Out of interest, have you tried H.265 (HEVC)?  It might be better supported for 8K

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.
