### ISSUE TITLE
Fallback stereo packing mode not correctly handled with DirectShow

### ISSUE THREAD

**Issue by RazTeer** [RenderHeads/UnityPlugin-AVProVideo#772]
Hi,

when opening your demo scene - example video with the 360 sphere it is horizontally incorrect (see attached pic).

Also it appears that the "layout mapping property" changes itself automatically to other values preventing me to see the 360 spere.
![upload_2021-5-11_14-58-4](https://user-images.githubusercontent.com/84038747/117862245-bbc2b080-b292-11eb-81e3-d49643d73532.png)

I also read through this post and did exify etc. NOTHING helps:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/305

Please help as soon as possible.

Thanks Simon

**Comment by AndrewRH** [comment]
Thanks, this is a bug and we've fixed it now - the fix will be in the next release.

This issue is specific to using the DirectShow API, so if you can switch to Media Foundation API for now then it will work correctly.

Thanks,

**Comment by RazTeer** [comment]
Thanks!

sadly I had following issue when using Media Foundation previously
![image](https://user-images.githubusercontent.com/84038747/117932584-cfa4fb80-b300-11eb-87ca-29385d48a1c7.png)

I didn't get a reply on the unity forum regarding this. Thus, had no choice, but to use Direct Show.


Any chance I can get the next release sooner?

Thank you.

**Comment by AndrewRH** [comment]
That's probably just because our video is encoded using HEVC and your PC may now have the Microsoft HEVC codec installed on it.  

We will try to get the next release out this week.

**Comment by AndrewRH** [comment]
Closing this issue as 2.1.3 has now been released.  The videos have also now been reencoded as H.264 which should make Media Foundation work for you.  Thanks once again for reporting the issue.

**Comment by RazTeer** [comment]
> Closing this issue as 2.1.3 has now been released. The videos have also now been reencoded as H.264 which should make Media Foundation work for you. Thanks once again for reporting the issue.

Thank you for your quick reaction and help!
