### ISSUE TITLE
Is it possible to play Wowza's WebRTC based ultra-low-latency video?

### ISSUE THREAD

**Issue by kengonakajima** [RenderHeads/UnityPlugin-AVProVideo#774]
**Question**

Title says almost all, but you can see Wowza's explanation about WebRTC streaming:

https://www.wowza.com/docs/how-to-use-webrtc-with-wowza-streaming-engine#about-webrtc-in-wowza-streaming-engine

I tested it in my browser and it looks about only 2.5 seconds delayed.

**Comment by monoAI-sya** [comment]
Hi

How about this question.
I am also discussion with my team about WebRTCl
Anyone can answer this question?

**Comment by kahnivore** [comment]
Hi there,

We don't support WebRTC currently and haven't planned for this on our roadmap. Do you possibly have any streams we could test with? We haven't looked into integrating it but it's likely possible if a user wanted to integrate this themselves.
