### ISSUE TITLE
Demo 360 does not work on Pico G2 4K

### ISSUE THREAD

**Issue by JonathanTroyer** [RenderHeads/UnityPlugin-AVProVideo#777]
**Describe the bug**
The included demo 360 video does not work on a Pico G2 4K. Furthermore, other scenes we've tried with 360 videos have had issues when attempting to start a second media player using Display uGUI. These issues are not present when using a Pico Neo 2 Eye.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.7
 - AVPro Video version: 2.1.2
 - Operating system version: Android 8.1.0 (PUI 4.0.1)
 - Device model: Pico G2 4K
 - Video specs (resolution, frame-rate, codec, file size): 
   - 360: 4096x2048, 60fps, H.265, 109.1 MB
   - uGUI: 3840x2160, 23.98fps, H.265, 5.3 MB

**To Reproduce**
1. Load Demo_360Stereo onto a Pico G2 4K

**Logs**
When running the scene, `Assertion failed: OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range` is rapidly logged to the console.

**Comment by RenderHeadsSte** [comment]
According to [this](https://headjack.io/knowledge-base/best-video-resolution-for-pico-headsets/) resource, one of those videos framerate exceeds the maximum of the Pico G2 4K.

It is not clear to me, have you tried something within the bounds of the device that the source article suggests?

Can you send over a logcat output?

**Comment by JonathanTroyer** [comment]
The Pico G2 4K _does_ support the video formats supplied and is able to play each video individually (specifically, the G2 uses a [Snapdragon 835](https://www.qualcomm.com/products/snapdragon-835-mobile-platform)).

I've uploaded the [logcat output](https://gist.github.com/JonathanTroyer/72e9535b6783c053be680c3e13a02232). Note the large amount of `OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range` errors. Additionally, I just emailed a minimal project that recreates the issue.

**Comment by RenderHeadsSte** [comment]
You are indeed right, the processor should be fine for your video res/framerate. However, your log is reporting a lot of ‘not supported’ by the decoder...which is not always an accurate indication in my experience. There seem to be a lot of different videos referenced. Is the log from running our demo360 scene?

I am afraid I do not have a pick g2 4k to hand, so your demo project is likely to be of little use as I believe this issue is device specific.

Are you running single or multi-pass?

**Comment by JonathanTroyer** [comment]
After reaching out to Pico, it seems there are some limitations on the 835 while playing multiple videos. From Pico:
> as confirmed with our engineer, Qualcomm 835 has particular limit for dual instance playback in UHD that both videos are limited to codec spec 3840\*2160\*30 or 4096\*2048\*30

After some testing, we also found that 4096x2048@60 with 1920x1080@30 works as well.

It seems the demo 360 scene issue is due to the single/multi-pass issue described.

**Comment by RenderHeadsSte** [comment]
That is great info to know, thanks for connecting with them and sharing.

Glad to hear you have a solution :)
