### ISSUE TITLE
 There's no way to play

### ISSUE THREAD

**Issue by MoFeiPeng** [RenderHeads/UnityPlugin-AVProVideo#778]
windows xp  There's no way to play

**Comment by kahnivore** [comment]
HI @MoFeiPeng 

Could you please describe the issue you're having in detail. Please include Unity version, AVPro Video version, details about your media: audio/video codecs, framerate, resolution and a description of the behaviour and how to reproduce it.

**Comment by kahnivore** [comment]
We don't support Windows XP in AVPro Video 2.x. It was previously supported in 1.x.
