### ISSUE TITLE
OES shader on Oculus Quest 2 causes vertically flipped video

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#780]
**Describe the issue**
When using OES (building for Android / Oculus Quest 2) to display a 360 monoscopic video on the inside of a sphere, the video is flipped vertically. 
Shader: AVProVideo/VR/InsideSphere Unlit Transparent(stereo+color+alpha) - Android OES ONLY
Material settings: Tiling 1, 1 / Offset 0, 0
Even when setting Tiling to 1, -1 the video is still flipped vertically. 
This doesn't happen when OES is not used and using the regular shader: AVProVideo/VR/InsideSphere Unlit (stereo+fog)

**Your Setup (please complete the following information):**
 - Unity version: 2018/4/22f1
 - AVPro Video version: 2.1.2
 - Operating system version: Android
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by RuudvanReenen** [comment]
As it seems the tiling is not used/ignored by the shader, I'll try giving the sphere a negative Y scale instead as a workaround, when OES is used.

**Comment by AndrewRH** [comment]
Thanks for reporting this - are you using ApplyToMaterial or ApplyToMesh?

We will see if we can replicate this issue.   I can't see anything missing in the shader - the texture transform seems to be applied...

Thanks,

**Comment by AndrewRH** [comment]
One more question, if your video is transparent, is it using top-bottom or left-right packing?  And any stereo?

Thanks,

**Comment by RuudvanReenen** [comment]
I'm using ApplyToMesh, to an octahedron sphere (from an AVPro Video 1 demo I think).
The video has no transparency, and is monoscopic. I haven't tested with transparency or stereoscopic video.

**Comment by KyoheiYonemoto** [comment]
I have the same problem.
In my case, my video is transparent, uses left-right packing, and also has stereo top-bottom.


- Unity version: 2019.4.22f1
- AVPro Video version: 2.1.0
- Operating system version: Android
- Device model: Oculus Quest 2

**Comment by kahnivore** [comment]
HI @RuudvanReenen  and @KyoheiYonemoto 

Sorry for the delay and thanks for reporting this. We found a small bug in the transparent OES shader. 

The fix will be included in our next release, but here's a corrected version of the shader in the meantime. 

Please let us know if this solves the problem for you. 

[AVProVideo-VR-InsideSphere-Transparent-AndroidOES.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6701215/AVProVideo-VR-InsideSphere-Transparent-AndroidOES.zip)

**Comment by imsumittyagi** [comment]
Hi, I am facing the same issue and the provided shader by @kahnivore  is for transparent videos only and solution for non transparent videos

**Comment by AndrewRH** [comment]
2.1.6 has been released with this fix - please let us know if you have any further issues

**Comment by imsumittyagi** [comment]
It is working fine But the issue is that HSBV values are not working on it any solution to that ? @AndrewRH

**Comment by AndrewRH** [comment]
@imsumittyagi HSBV values?  I'm not sure what you're talking about - please start a new thread with details of your issue as it doesn't seem to be related to this issue which I'm closing now.

Thanks,
