### ISSUE TITLE
SkipOnDrop option

### ISSUE THREAD

**Issue by Dubarov** [RenderHeads/UnityPlugin-AVProVideo#782]
Is there a way to stop frames from skipping. Like option in builtin Unity VideoPlayer: SkipOnDrop = false?
My application is running on 30 FPS with Time.CaptureFramerate = 30, video is also at 30 FPS. And I want to render every frame even if some frames are rendered more than 1/30 sec. I need this because there are rare spikes in deltatime and other content moves out of sync with video because of CaptureFramerate.

I tried settingTimeScaleSupport, but it is not working. Application starts working at less than 15 FPS, and video switch frames at about 2 FPS, Video Decode in task manager shows 100%. It seems that the video constantly rewinds. Without this option video rendering is smooth at 30 FPS.

PS
Platform: Windows 10
Codec H.265, 8k

**Comment by cihadturhan** [comment]
#598

**Comment by kahnivore** [comment]
Hi @Dubarov 

Could you please advice which versions of Unity and AVPro Video you are using?

**Comment by kahnivore** [comment]
Closing this as no further information has been provided.
