### ISSUE TITLE
iOS error opening remote mp4 file

### ISSUE THREAD

**Issue by Adz10kvtech** [RenderHeads/UnityPlugin-AVProVideo#783]
Im getting an error when trying to play an mp4 on iOS, see logs below.

Videos play in the editor under iOS platform fine with no issues,  same code runs on windows fine, error occurs only on the iOS device (my iPhone SE 2020).

Any help would be greatly appreciated.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.25
 - AVPro Video version: 2.1.3
 - Operating system version: iOS 14
 - Device model: iPhone SE 2020
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Run mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, path, false);

**Logs**
[AVProVideo] Initialising AVPro Video v2.1.3 (native plugin v2.1.1-core build 582) on Apple A13 GPU/Metal (MT True) on IPhonePlayer
Initialising for graphics device type Metal
2021-05-14 23:49:07.839615+0100 CregoTools-Presence[30726:3747987] [Process] 0x10352c818 - [pageProxyID=13, webPageID=14, PID=30736] WebPageProxy::didFailProvisionalLoadForFrame: frameID = 10, domain = NSURLErrorDomain, code = -999
[AVProVideo] Opening http://static.i-hydra.uk/6d591922-0d6d-4f2a-aac0-f4dff99ef903/h264/772992a7-e038-4c96-8cf0-216b72d236fe.mp4 (offset 0) with API 
2021-05-14 23:49:50.184688+0100 CregoTools-Presence[30726:3747987] -[AVProVideo.Player openURL:]: unrecognized selector sent to instance 0x118ad4750
2021-05-14 23:49:50.263493+0100 CregoTools-Presence[30726:3747987] Uncaught exception: NSInvalidArgumentException: -[AVProVideo.Player openURL:]: unrecognized selector sent to instance 0x118ad4750
(
	0   CoreFoundation                      0x0000000191f54880 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1202304
	1   libobjc.A.dylib                     0x00000001a6f6dc50 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000191e5b95c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 182620
	3   CoreFoundation                      0x0000000191f57438 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1213496
	4   CoreFoundation                      0x0000000191f59740 _CF_forwarding_prep_0 + 96
	5   UnityFramework                      0x0000000104d35c4c AVPPlayerOpenURL + 688
	6   UnityFramework                      0x0000000104edb784 Native_AVPPlayerOpenURL_m910165AFD8A5375239B3987518DA47F4B9E3734D + 64
	7   UnityFramework                      0x0000000104edb5c8 AppleMediaPlayer_OpenMedia_m3B35BF3F002FDEB4A509282A73697CD9BD19604B + 248
	8   UnityFramework                      0x0000000104ee5b38 MediaPlayer_OpenMedia_m0F71AC8636AECA07389A90371BEBA37C8E06776B + 888
	9   UnityFramework                      0x0000000104f01df8 U3CBufferThenPlayAvU3Ed__39_MoveNext_m26920BF706DA17581EA043C41AFD9126C640DD5D + 912
	10  UnityFramework                      0x00000001062c424c SetupCoroutine_InvokeMoveNext_m9106BA4E8AE0E794B17F184F1021A53F1D071F31 + 196
	11  UnityFramework                      0x000000010391089c _Z89RuntimeInvoker_FalseVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017_RuntimeObject_IntPtr_tPFvvEPK10MethodInfoPvPS4_ + 28
	12  UnityFramework                      0x0000000104c10e44 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
	13  UnityFramework                      0x00000001043a5b6c _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 116
	14  UnityFramework                      0x00000001043b47a4 _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 136
	15  UnityFramework                      0x00000001043c02b8 _ZN9Coroutine14InvokeMoveNextEP21ScriptingExceptionPtr + 164
	16  UnityFramework                      0x00000001043bfe64 _ZN9Coroutine3RunEPb + 52
	17  UnityFramework                      0x00000001043c2524 _ZN13MonoBehaviour24TryCreateAndRunCoroutineE18ScriptingObjectPtr18ScriptingMethodPtrPP9Coroutine + 348
	18  UnityFramework                      0x00000001043c2a0c _ZN13MonoBehaviour22StartCoroutineManaged2E18ScriptingObjectPtr + 80
	19  UnityFramework                      0x000000010444709c _Z43MonoBehaviour_CUSTOM_StartCoroutineManaged2P37ScriptingBackendNativeObjectPtrOpaqueS0_ + 180
	20  UnityFramework                      0x0000000104f02584 U3CPlayVideoU3Ed__37_MoveNext_m0315D145943D8AF2E0BAB4B34C93ED3F6C7E6C66 + 580
	21  UnityFramework                      0x00000001062c424c SetupCoroutine_InvokeMoveNext_m9106BA4E8AE0E794B17F184F1021A53F1D071F31 + 196
	22  UnityFramework                      0x000000010391089c _Z89RuntimeInvoker_FalseVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017_RuntimeObject_IntPtr_tPFvvEPK10MethodInfoPvPS4_ + 28
	23  UnityFramework                      0x0000000104c10e44 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
	24  UnityFramework                      0x00000001043a5b6c _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 116
	25  UnityFramework                      0x00000001043b47a4 _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 136
	26  UnityFramework                      0x00000001043c02b8 _ZN9Coroutine14InvokeMoveNextEP21ScriptingExceptionPtr + 164
	27  UnityFramework                      0x00000001043bfe64 _ZN9Coroutine3RunEPb + 52
	28  UnityFramework                      0x0000000103f5d50c _ZN18DelayedCallManager6UpdateEi + 764
	29  UnityFramework                      0x0000000104149cf4 _ZZ23InitPlayerLoopCallbacksvEN49UpdateScriptRunDelayedDynamicFrameRateRegistrator7ForwardEv + 80
	30  UnityFramework                      0x000000010413fe28 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 92
	31  UnityFramework                      0x000000010413fe84 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 184
	32  UnityFramework                      0x0000000104140140 _Z10PlayerLoopv + 384
	33  UnityFramework                      0x00000001047a6c74 _ZL19UnityPlayerLoopImplb + 240
	34  UnityFramework                      0x0000000103819490 UnityRepaint + 140
	35  UnityFramework                      0x000000010381936c -[UnityAppController(Rendering) repaintDisplayLink] + 88
	36  QuartzCore                          0x00000001952266fc 8510F139-0824-3686-A9AA-3E198539A021 + 83708
	37  QuartzCore                          0x00000001952ffa80 8510F139-0824-3686-A9AA-3E198539A021 + 973440
	38  CoreFoundation                      0x0000000191eabdd0 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 511440
	39  CoreFoundation                      0x0000000191ed0fe8 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 663528
	40  CoreFoundation                      0x0000000191ed0378 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 660344
	41  CoreFoundation                      0x0000000191eca08c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 635020
	42  CoreFoundation                      0x0000000191ec921c CFRunLoopRunSpecific + 600
	43  GraphicsServices                    0x00000001a9a93784 GSEventRunModal + 164
	44  UIKitCore                           0x0000000194909ee8 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 12357352
	45  UIKitCore                           0x000000019490f75c UIApplicationMain + 168
	46  UnityFramework                      0x0000000103817e2c -[UnityFramework runUIApplicationMainWithArgc:argv:] + 108
	47  CregoTools-Presence                 0x00000001001bbe1c main + 68
	48  libdyld.dylib                       0x0000000191b896b0 21B19919-1334-38BC-B233-896E929945E0 + 5808

**Comment by AndrewRH** [comment]
Hi,

See the streaming notes for iOS here:
https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html#streaming

I believe the issue is related to your URL being HTTP instead of HTTPS

Does this solve your issue?

Thanks,

**Comment by Adz10kvtech** [comment]
Just tried with https with same video url unfortunately no luck, still same error

2021-05-15 10:10:52.743601+0100 CregoTools-Presence[31948:3888052] Uncaught exception: NSInvalidArgumentException: -[AVProVideo.Player openURL:]: unrecognized selector sent to instance 0x13898e430

**Comment by MorrisRH** [comment]
The URLs you've pasted as part of the log output are working fine in the Demo_MediaPlayer scene, my setup is:
Unity 2018.4.35f1
AVPro Video 2.1.3 Core & Trial
iPad Pro - iOS 14.4.2

Are you able to play back those URLs using the Demo_MediaPlayer scene on your device?

**Comment by Adz10kvtech** [comment]
Just built the Demo_MediaPlayer scene built to Xcode then pushed to iPhone 

Same error

2021-05-17 12:15:52.457295+0100 CregoTools-Presence[5332:689788] [Player] Creating display link
[AVProVideo] Initialising AVPro Video v2.1.3 (native plugin v2.1.1-core build 582) on Apple A13 GPU/Metal (MT True) on IPhonePlayer
[AVProVideo] Opening /private/var/containers/Bundle/Application/954ECFC1-6392-43E2-8812-441B49DBB355/CregoTools-Presence.app/Data/Raw/AVProVideoSamples/RenderHeads-1080p30-H264.mp4 (offset 0) with API 
2021-05-17 12:15:52.469741+0100 CregoTools-Presence[5332:689788] -[AVProVideo.Player openURL:]: unrecognized selector sent to instance 0x1165f7240
2021-05-17 12:15:52.533025+0100 CregoTools-Presence[5332:689788] Uncaught exception: NSInvalidArgumentException: -[AVProVideo.Player openURL:]: unrecognized selector sent to instance 0x1165f7240
(
	0   CoreFoundation                      0x0000000181184880 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1202304
	1   libobjc.A.dylib                     0x000000019619dc50 objc_exception_throw + 60
	2   CoreFoundation                      0x000000018108b95c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 182620
	3   CoreFoundation                      0x0000000181187438 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 1213496
	4   CoreFoundation                      0x0000000181189740 _CF_forwarding_prep_0 + 96
	5   UnityFramework                      0x0000000104d35b1c AVPPlayerOpenURL + 688
	6   UnityFramework                      0x0000000104edb654 Native_AVPPlayerOpenURL_m910165AFD8A5375239B3987518DA47F4B9E3734D + 64
	7   UnityFramework                      0x0000000104edb4ec AppleMediaPlayer_OpenMedia_m3B35BF3F002FDEB4A509282A73697CD9BD19604B + 332
	8   UnityFramework                      0x0000000104ee5a08 MediaPlayer_OpenMedia_m0F71AC8636AECA07389A90371BEBA37C8E06776B + 888
	9   UnityFramework                      0x0000000104ee5620 MediaPlayer_Start_mBEC808627EF2AE8555EF9D4AA7EBCDD2864DCC89 + 68
	10  UnityFramework                      0x00000001038fb510 _Z65RuntimeInvoker_TrueVoid_t22962CB4C05B1D89B55A6E1139F0E87A90987017PFvvEPK10MethodInfoPvPS4_ + 20
	11  UnityFramework                      0x0000000104c10d14 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
	12  UnityFramework                      0x00000001043a5a3c _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 116
	13  UnityFramework                      0x00000001043b4674 _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 136
	14  UnityFramework                      0x00000001043c323c _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtrP21ScriptingExceptionPtr + 2032
	15  UnityFramework                      0x00000001043c34bc _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtr + 84
	16  UnityFramework                      0x00000001043c1dd8 _ZN13MonoBehaviour16DelayedStartCallEP6ObjectPv + 104
	17  UnityFramework                      0x0000000103f5d3dc _ZN18DelayedCallManager6UpdateEi + 764
	18  UnityFramework                      0x0000000104149a0c _ZZ23InitPlayerLoopCallbacksvEN50EarlyUpdateScriptRunDelayedStartupFrameRegistrator7ForwardEv + 80
	19  UnityFramework                      0x000000010413fcf8 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 92
	20  UnityFramework                      0x000000010413fd54 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 184
	21  UnityFramework                      0x0000000104140010 _Z10PlayerLoopv + 384
	22  UnityFramework                      0x00000001047a6b44 _ZL19UnityPlayerLoopImplb + 240
	23  UnityFramework                      0x00000001038193a0 UnityRepaint + 140
	24  UnityFramework                      0x000000010381927c -[UnityAppController(Rendering) repaintDisplayLink] + 88
	25  QuartzCore                          0x00000001844566fc 8510F139-0824-3686-A9AA-3E198539A021 + 83708
	26  QuartzCore                          0x000000018452fa80 8510F139-0824-3686-A9AA-3E198539A021 + 973440
	27  CoreFoundation                      0x00000001810dbdd0 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 511440
	28  CoreFoundation                      0x0000000181100fe8 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 663528
	29  CoreFoundation                      0x0000000181100378 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 660344
	30  CoreFoundation                      0x00000001810fa08c 727F2644-EB4E-3D57-BC2E-E6803BA92366 + 635020
	31  CoreFoundation                      0x00000001810f921c CFRunLoopRunSpecific + 600
	32  GraphicsServices                    0x0000000198cc3784 GSEventRunModal + 164
	33  UIKitCore                           0x0000000183b39ee8 8518EAE3-832B-3FF0-9FA5-9DBE3041F26C + 12357352
	34  UIKitCore                           0x0000000183b3f75c UIApplicationMain + 168
	35  UnityFramework                      0x0000000103817d3c -[UnityFramework runUIApplicationMainWithArgc:argv:] + 108
	36  CregoTools-Presence                 0x000000010065fe1c main + 68
	37  libdyld.dylib                       0x0000000180db96b0 21B19919-1334-38BC-B233-896E929945E0 + 5808
)

**Comment by MorrisRH** [comment]
Did you create a completely new project when testing or was this part of an existing project?
Is this a fresh install of the plugin or did you upgrade from version 1?
Are you using any other plugins? If so could you list them?

**Comment by Adz10kvtech** [comment]
1. This was part of my existing project, I will do a fresh project 
2. This is a fresh install of the plugin
3. Will try in a fresh project before thinking about this.

thanks for the support

**Comment by Adz10kvtech** [comment]
Ok the demo scene works fine in a fresh project on iphone which means it must be another plugin, i will investgate further.

**Comment by Adz10kvtech** [comment]
Ok this fixed itself when I deleted the plugins folder and reimported. My guess is that some files in that plugin directory where likely avPRO v 1. 

Thanks for the help guys.
