### ISSUE TITLE
PlaylistMediaPlayer audio volume/muted state gets overwritten and edge case where next video isn't shown

### ISSUE THREAD

**Issue by z79422957** [RenderHeads/UnityPlugin-AVProVideo#784]
Hi! 
There are two playlistmediaplayer(beta) script issue:
(1)It's not easy to control the player list with the function code of mute control, volume control and transition volume. And they seem to have conflicts. For example, after I modified the audio volume, the sound returns to the original value through the next video transition.
(2)Another test is that there is only a very short 4s video in the play list. When I play the list on a high frequency, the video sometimes turns white, and then I can't play it again. It's always white.is this a transition bug at openvideo?

Finally, We hope playlistmediaplayer script can be more perfect, thank you.

**Comment by kahnivore** [comment]
Hi @z79422957 

Can you please supply the following information:

1. Which version of Unity are you using?
2. Which version of AVPro are you using?
3. Which platform are you testing on? 
4. What do you mean when you play the list on high frequency? Are you speeding them up using a time scale? Or do you just mean you're looping the playlist continually?

**Comment by z79422957** [comment]
1.UnityVersion: 2019.4.17f1c1
2.AVPro Version: 2.1.2 
3.platform: Window10-64
4.My test case: There's only one 'AlphaLeftRight.mp4' video in the playlistmediaplayer script, it's looped. transition is true, duration is 1s, finally, replayed(openvideo method) every second in for loop codes.Sometimes the video will turn white, and it will stay white all the time.

**Comment by AndrewRH** [comment]
@z79422957 thanks for explaining your test case - I haven't managed to reproduce the issue where it remains white.   Could you provide as screenshot of the Inspector Window showing your exact setup?

Thanks,

**Comment by AndrewRH** [comment]
thanks for this, I think I have a fix... I will post it shortly

**Comment by AndrewRH** [comment]
For the white screen issue, please try making this change to PlaylistMediaPlayer.cs around line 245:

add 

`CurrentPlayer.MediaPath.Path = string.Empty;`

![image](https://user-images.githubusercontent.com/5418126/119092948-fa7d0700-ba06-11eb-80e2-c2813d7a1a4f.png)

As for the audio volume/muted - we have made these improvements and they will be included in the next release.   If you're looking for the fix now, I have attached the modified script files here - they will need to be copied to the relevant folders to override the old script files.

[PlaylistFixes.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6520584/PlaylistFixes.zip)

Let me know if these solve the problems for you.

Thanks,

**Comment by z79422957** [comment]
Thank you very much. I will use and test it in the next new version2.1.4.
