### ISSUE TITLE
FPS problems for Samsung galaxy Tab A since upgrade to AVPRO Android version 

### ISSUE THREAD

**Issue by LudovicWVirtysens** [RenderHeads/UnityPlugin-AVProVideo#786]
I have a problem with video player, the video lag a lot since I have upgrade from trial version to Android version.

I have test the trial version on Samsung tablet and Pico G2 4K.
The video playing correctly on both 25 FPS
When I upgrade AVPRO version from trial to Android,  the video playing correctly on pico G2 4K (25FPS) but not on Samsung galaxy Tab (5 FPS) .

 - Unity version: 2020.2.1f1
 - AVPro Video version: 2.1.3 Android version
 - Operating system version: 
 - Device model: Samsung

**Comment by RenderHeadsSte** [comment]
Do you know what version your trial version was?  Are you using the stand alone Android platform version (i.e. Core) or is it the Ultra Edition? (note that the trial is essentially a watermarked Ultra edition)

Is it possible for you to send over the video you are having problems with to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)

**Comment by LudovicWVirtysens** [comment]
I have used the trial version (watermarked Ultra edition) present on the Unity strore last week.

**Comment by RenderHeadsSte** [comment]
We will require the video at very least from you.  Are you able to email that over? (or email a WeTransfer link?)

**Comment by LudovicWVirtysens** [comment]
Yes it's done

**Comment by LudovicWVirtysens** [comment]
Have you received the video ?

**Comment by kahnivore** [comment]
Hi @LudovicWVirtysens 

We can't think of any reason why upgrading from the trial version would cause a drop in frame rate. Could you possibly start a fresh project using the trial version, and test this same video on your tablet again? If it is something in the core version causing this, we'd need to investigate it, but we need to make sure what's happening first. 

Regarding your video, the resolution and bitrate are quite high for your tablet - it's possible that the low framerate is a case of your tablet not being powerful enough for the video in question. Have you tried any lower res videos in the same project?

**Comment by LudovicWVirtysens** [comment]
Hi

I have already create a new scene with only player and very simple code 

   ```
 private SceneMgr _mgr;
    public MediaPlayer _mediaplayer;
    // Start is called before the first frame update
    void Start()
    {
       _mgr = GameObject.FindObjectOfType<SceneMgr>();
        _mediaplayer.OpenMedia(MediaPathType.AbsolutePathOrURL, _mgr._moviePath, false);
        _mediaplayer.Play();

    }

```
SceneMgr is a gameobject from the last scene (don’t destroy)

Result : Same problem 6 FPS after upgrade and 25 before

BR
Ludovic

**Comment by kahnivore** [comment]
Hi that's quite strange. Do you think you could do two tests (we don't have an equivalent tablet to test on):

Test 1: 
Fresh project, import AVPro Video **trial**. Using our demo scene and your video.

Test 2:
Fresh project, import AVPro Video **core**. Using our demo scene and your video. 

Could you please send camera phone footage of these two tests?

**Comment by RenderHeadsSte** [comment]
Can you also check to see if there are any differences in the the 'Audio Output' option?  I would suggest for best performance it should be set to 'System Direct'

![image](https://user-images.githubusercontent.com/46531149/119006013-e47c3180-b987-11eb-9be7-05ce5ae12b5a.png)

**Comment by LudovicWVirtysens** [comment]
I have already set "System Direct"

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by LudovicWVirtysens** [comment]
Hi there

I have create a new project , using « DemoMediaPlayer » scene


Just add in start :
   void Start()
    {
        var path = Path.Combine(directoryPath, "VirtysensExperiences/Fleurs/100 Fleurs_FLAT.mp4");
       _mediaplayer.OpenMedia(MediaPathType.AbsolutePathOrURL, path, true);

    }

I have check on 3 Videos


  *   Belgique ( flat screen H264 MPEG4 AVC 25 FPS 3840*2160) 1.85 Go
  *   Venise (180 H264 MPEG4 AVC  30 FPS 2880*2880) 416 Mo
  *   Fleurs  ( flat screen H264 MPEG4 AVC 30 FPS 3840*2160)  2.66 Go


With trial version

2 are OK betwen 25 and 30 FPS Belgique and Fleurs
1 is slow (6FPS) Venise

After update AVPRO

1 is OK betwen 25 and 30 FPS Fleurs
2 are slow (6FPS) Venise and Belgique

You can find in attachment the print screen.

Best regards

Ludovic

**Comment by LudovicWVirtysens** [comment]
Hi 
Somme news about this issue ?

**Comment by RenderHeadsSte** [comment]
There really is no reason why the trial version would offer any performance increase in performance compared to the full packages.  In fact, the trial version will be ever so slightly more taxing on the hardware due to the extra overheads of the watermarking process.

There seems to be no logical reason why 'Belgique' would perform worse than 'Fleurs' given they are the same resolution 'Belgique' is a lower frame rate!  IF there are no encoding differences, then that just leaves bitrate.  What are the bitrates of the three videos?

**Comment by RenderHeadsSte** [comment]
Now it makes even less sense!  The highest bitrate video (by some margin) plays back the best.  Are they all encoded exactly the same?

**Comment by RenderHeadsSte** [comment]
One thing you could try to increase performance in the full version...is to use OES mode (enable the option in the Android settings in the MediaPlayer component and use the appropriate OES shader).

**Comment by LudovicWVirtysens** [comment]
I don't understand how I can chose the appropriate OES Shader.

**Comment by LudovicWVirtysens** [comment]
no changes with oes checked

**Comment by LudovicWVirtysens** [comment]
Hi,
It seem the only one difference is the version of AVPRO.
The Trial version is the "UltraCore  Edition" and now I'm using the Android version.
Do you have any idea about this ?

**Comment by LudovicWVirtysens** [comment]
Hi,

Do you have some Idea ?
Is it possible to have a "UltraCore Edition" to check ?

BR Ludovic

De : ludovic WIART
Envoyé : vendredi 21 mai 2021 17:04
À : RenderHeads/UnityPlugin-AVProVideo ***@***.***>; RenderHeads/UnityPlugin-AVProVideo ***@***.***>
Cc : Mention ***@***.***>
Objet : RE: [RenderHeads/UnityPlugin-AVProVideo] FPS problems for Samsung galaxy Tab A since upgrade to AVPRO Android version (#786)

Hi there

I have create a new project , using « DemoMediaPlayer » scene


Just add in start :
   void Start()
    {
        var path = Path.Combine(directoryPath, "VirtysensExperiences/Fleurs/100 Fleurs_FLAT.mp4");
       _mediaplayer.OpenMedia(MediaPathType.AbsolutePathOrURL, path, true);

    }

I have check on 3 Videos


  *   Belgique ( flat screen H264 MPEG4 AVC 25 FPS 3840*2160) 1.85 Go
  *   Venise (180 H264 MPEG4 AVC  30 FPS 2880*2880) 416 Mo
  *   Fleurs  ( flat screen H264 MPEG4 AVC 30 FPS 3840*2160)  2.66 Go


With trial version

2 are OK betwen 25 and 30 FPS Belgique and Fleurs
1 is slow (6FPS) Venise

After update AVPRO

1 is OK betwen 25 and 30 FPS Fleurs
2 are slow (6FPS) Venise and Belgique

You can find in attachment the print screen.

Best regards

Ludovic

**Comment by LudovicWVirtysens** [comment]
Hi,

no news since 10 days, can you help me to find a solution please ?

**Comment by RenderHeadsSte** [comment]
We are still waiting camera phone footage of the two tests asked for by @kahnivore 18 days ago.  Could you provide these please so we can see exactly what you are seeing.

**Comment by LudovicWVirtysens** [comment]
Hi,

You can find a video here : https://wetransfer.com/downloads/b6e49844d970abe746237cb13e02bdad20210607115816/c11df08d117fb8425439fe0a9dea71f420210607115834/146c56
I see only my video is very slow and the the FPS is under 7 FPS
Sometime the video stop and the spinner appear.

BR
Ludovic

**Comment by RenderHeadsSte** [comment]
And the video of the trial version running at a higher frame rate on the same device?

**Comment by LudovicWVirtysens** [comment]
No the same video on a same device.
the only difference is the update of AVRPRO (Trial to Android)

**Comment by RenderHeadsSte** [comment]
Sure, but I am asking for a video of just like the one you sent today.

> Test 1:
> Fresh project, import AVPro Video trial. Using our demo scene and your video.

> Test 2:
> Fresh project, import AVPro Video core. Using our demo scene and your video.

> Could you please send camera phone footage of these two tests?

'Test 2' you sent to us earlier today, but we have not seen a video of 'Test 1'

**Comment by RenderHeadsSte** [comment]
> Sometime the video stop and the spinner appear.

Is the video being loaded off a remote server, or off the local device?

**Comment by LudovicWVirtysens** [comment]
The video is on SDcard in the device slot

**Comment by LudovicWVirtysens** [comment]
You can find the test1 video here : 
https://wetransfer.com/downloads/15917713a4a2c4b6905db5529cf3d50120210607162237/99bbef0be805477ece92964d812a2c2520210607162254/167e80

**Comment by RenderHeadsSte** [comment]
Are those two videos running on the same tablet?  There look to be differences between the two videos.

**Comment by LudovicWVirtysens** [comment]
no it's the same device (galaxy TabA) I have just remove the cover

**Comment by RenderHeadsSte** [comment]
What version of the Tab A are you testing on?  Could you send a screen shot/camera phone picture of the Settings->System page?

**Comment by LudovicWVirtysens** [comment]
![Uploading IMG_20210609_212754.jpg…]()
This is the settings

**Comment by AndrewRH** [comment]
@LudovicWVirtysens  i'm afraid the image didn't come through - could you send again please?

**Comment by LudovicWVirtysens** [comment]
![IMG_20210609_212754](https://user-images.githubusercontent.com/69161239/121510852-5cb69f80-c9e8-11eb-970e-26c21c794764.jpg)

**Comment by LudovicWVirtysens** [comment]
Is it ok for you ?

**Comment by kahnivore** [comment]
Yes, thanks. Just testing this.

**Comment by kahnivore** [comment]
Hi @LudovicWVirtysens 

We tested your video (results attached below) on a Tab A and are seeing the same performance from both the Core and Trial editions i.e. a very low framerate. There is really no reason why the trial would outperform the core edition of the plugin in this case. It seems like the device can't really handle the media you're trying to play - as you say, it's working fine on the Pico and not the Samsung which suggests it isn't really something we can fix on the plugin side. Have you looked into optimising the media for your device at all?  

https://user-images.githubusercontent.com/44468274/122068756-f620ef80-cdf4-11eb-9995-0301baeed98c.mp4
https://user-images.githubusercontent.com/44468274/122068707-eb665a80-cdf4-11eb-8fb0-f7713690201e.mp4

**Comment by LudovicWVirtysens** [comment]
Hi,
I will try to modify the video but I don't understand why this video works fine on this device with VLC or AVPro trial and doesn't works with Android version.

Is it possible to have a full version to try ? If it works I will buy the full version to be sure to have the good performance.

**Comment by RenderHeadsSte** [comment]
I am afraid we cannot do that.

There should be zero performance difference between the Core and Ultra versions.  The Trial version is the Ultra version with watermarking, which has an extra blit and so would actually be ever so slightly less performant.

We have tested v2.1.4 Trial and Core on the exact same device you are saying you see the issue, and we indeed get the same issue.  But we get it in all editions of AVPro Video.  The device is just not powerful enough to give more than ~7fps with that video.

Can you confirm you are using the exact same physical device for your testing of the two versions?  The reason I ask is because there is what looks like a difference in the device between the two videos you sent over (not the case seen in one of the videos).

**Comment by LudovicWVirtysens** [comment]
You can trust me, it's exactly the same device, the only one différence is I have remove the case between the 2 videos

**Comment by kahnivore** [comment]
@LudovicWVirtysens not sure what more we can do here as it seems to come down to the device performance.
