### ISSUE TITLE
what is the differences between Core Android Edition and Ultra Edition?

### ISSUE THREAD

**Issue by MengYuChuan** [RenderHeads/UnityPlugin-AVProVideo#788]
**Question**
what is the differences between Core Android Edition and Ultra Edition? The  Core Android Edition doesn't be useful for IOS or windws?

**Comment by kahnivore** [comment]
Hi @MengYuChuan 

We have two main feature divides in AVPro Video 2 - the core and ultra editions. The ultra edition is only available as a single package for all platforms. The core edition is available as a full package for all platforms, or as a single platform-specific package. The Core Android edition will allow you to build for all platforms, but building for iOS or Windows will be watermarked. Please see [this table](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions) for an overview of which features are available for each edition. 

Thanks

**Comment by MengYuChuan** [comment]
Thanks!
