### ISSUE TITLE
Android player freezes at first frame using URLs

### ISSUE THREAD

**Issue by kfaber33** [RenderHeads/UnityPlugin-AVProVideo#79]
I’m working on a unity+vuforia app for Android/iOS using your amazing AVPro full component to reproduce videos from the web using URLs.
It was working very fine until I updated the version 1.9.12 with 1.9.16, getting the android version no more able to play any video.
The problem is that after running MPlayer.OpenVideoFromFile(MediaPlayer.FileLocation.AbsolutePathOrURL, "<video url>", true); the media player freezes on the first frame, no errors, no problems with the video source (iOS works fine), all events are fired correctly as before and even using your demo scenes the problems persists!
In particular I'm using the uGUI component to render the videos on a panel within a canvas.
I’m using unity 2019.1.1f5 + vuforia 8.1.7

**Comment by AndrewRH** [comment]
A couple of things to try:

1) Try switching the video API (in MediaPlayer > Platform Specific > Android) - does that help?
2) Try removing Vuforia, we've heard in the past that Vuforia can cause problems - does that help?

Otherwise, if you email us your PDF invoice, or invoice number, then we can send you the old 1.9.12 version to downgrade to while we investigate.

**Comment by pedrovf** [comment]
I got the same problem here, but without  Vuforia. I'm using VR (oculus GO, with Exoplayer), and if a play a video, it freezes on the first frame!! It was working with the Trial Version(1.9.14), but yesterday I bought the full version for Android (v 1.9.16) and it stopped working!!! And 1 more thing, it only works if I restart the Oculus, but just for 1 time! If I close the app and then open it again, it just stops working! Can you guys please send me the 1.9.14 version? I need to finish this quick!!!

**Comment by kfaber33** [comment]
Yesterday I tried changing some setting, at the end it seems that switching
Exoplayer to Mediaplayer (AVPRO Android specific setting) do the trick! Let
me know if this works also for you!

*Fabrizio D'Aura*
CEO I Vantage Partners <https://www.vantagepartners.ch/>
T. +41 (0)912257459 I M. +41 (0)76 526 1803 - +39 335 83 177 22
f.daura@vantagepartners.ch


Il giorno ven 7 giu 2019 alle ore 10:59 pedrovf <notifications@github.com>
ha scritto:

**Comment by kfaber33** [comment]
Yesterday I tried changing some setting, at the end it seems that switching
Exoplayer to Mediaplayer (AVPRO Android specific setting) do the trick! Let
me know if this works also for you!

**Comment by pedrovf** [comment]
Ohh I already did that! It worked but I would prefer if it works with Exoplayer, cuz before (v 1.9.14) it was working with Exo.
Conclusion: Exoplayer is the problem! Changing to MediaPlayer seems to be the workaround for now

**Comment by kfaber33** [comment]
I would prefer to use Exoplayer too :)

**Comment by kfaber33** [comment]
BTW the issue with exoplayer seems to persist even without Vuforia

**Comment by pedrovf** [comment]
Yep, and my left eye (Oculus GO) is flickering is Mediaplayer :/

**Comment by AndrewRH** [comment]
pedrovf, so with 1.9.16 Oculus Go left eye is flickering?  It was working in 1.9.14?
Hmm..is this with our example stereo scene?   Do you have the UpdateStereoMaterial in your scene?  Are you using single or multi-pass VR?
I'll reply to your email now.
Thanks :)

**Comment by pedrovf** [comment]
Well, I kinda fixed it by setting the eyeTextureResolutionScale to 1.5f, but I don't know why! It was flickering when I was using 1.25f, but with Exoplayer it wasn't flickering. I tested with single and multi-pass (same result), but I'm using the unity Skybox/Panoramic material because if I use the sphere, the bottom and top sides of the video will be distorted. I didn't need the UpdateStereoMaterial to be able to make it work...It was working perfectly with the 1.9.14

**Comment by pedrovf** [comment]
So, I downloaded the 1.9.14 version you guys sent me, and it worked flawlessly!! Using exoplayer, and without flickering! Thanks for the amazing support @AndrewRH !! I'll answer your email with more details about the problem! :D

**Comment by kfaber33** [comment]
Dear Andrew, please can you share AVPro 1.9.14 also with me? I would like to test if I can have exoplayer working in my project too :)

**Comment by AndrewRH** [comment]
kfaber33, please email unitysupport@renderheads.com and invoice your PDF purchase invoice and we'll organise 1.9.14 for you.

Thanks,

**Comment by RenderHeadsSte** [comment]
We have just released Version 1.9.17, which includes some fixes in the ExoPlayer API path.  Please do grab it and let us know if the problems you were encountering with 1.9.16 have been addressed.

**Comment by AndrewRH** [comment]
We'll close this issue in a couple of days, as we've proposed a solution (new plugin version) but haven't heard anything back.  

Thanks,

**Comment by AndrewRH** [comment]
Closing this issue - presumed fixed
