### ISSUE TITLE
Will AvPro supports urls of videos uploaded from Vimeo and Youtube ?

### ISSUE THREAD

**Issue by sathishkntrj** [RenderHeads/UnityPlugin-AVProVideo#790]
**Question**
Will AvPro supports urls of videos uploaded from Vimeo and Youtube ?
We are trying to play url videos which are taken from youtube and vimeo which are uploaded in our account respectively.

**Comment by kahnivore** [comment]
Hi @sathishkntrj,

Please see the following notes on [Youtube support](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#youtube-support) and [Vimeo support](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#vimeo-support) in our docs. 

Thanks!
