### ISSUE TITLE
Unable to open media from byte[]

### ISSUE THREAD

**Issue by mikemilla** [RenderHeads/UnityPlugin-AVProVideo#792]
Unable to play `byte[]` from file:

    using System.IO;    

    string filePath = "Assets/media_0.mp4";
    byte[] videoFileBytes = File.ReadAllBytes(filePath);
    mediaPlayer.PlatformOptionsWindows.videoApi = Windows.VideoApi.DirectShow;
    mediaPlayer.OpenMediaFromBuffer(videoFileBytes);

Results in error:

    [AVProVideo] Failed to open buffer

My Environment:

Unity `2019.4.17` & AVProVideo `2.1.3`
I am targeting Windows but will also be using this on WebGL

My goals:

1. Get audio and video from `mediaplayer` on a server build of my game
2. Pass raw byte[] in chunks to clients running the game
3. Play the raw bytes on the client game `mediaplayer`s

The ideal solution:

If the media player had a `mediaplayer.streamRawBytes((byte[]) => { })` and also a `mediaplayer.playRawBytesFromStream(byte[])`

**Comment by kahnivore** [comment]
Hi @mikemilla 

Struggling to reproduce this error - is there any chance you could send a sample reproducible case to unitysupport@renderheads.com please? 

Thanks.

**Comment by mikemilla** [comment]
@kahnivore here are some updates to this issue:

1. This is the original video I am try, but for some reason doesn't work. https://firebasestorage.googleapis.com/v0/b/killamikemilla-fec64.appspot.com/o/media_0.mp4?alt=media&token=c3146b03-b25b-4e54-b520-58b1bad87f81

2. I managed to get this video working, but I get some add artifacts on the video when it is rendered (bars that go up and down the texture) https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_20MB.mp4

**Comment by kahnivore** [comment]
Regarding 2. - are you using the trial version?

**Comment by mikemilla** [comment]
@kahnivore Yes, I am using the trial version

**Comment by kahnivore** [comment]
Upgrading to a licensed version will remove the bars. Please see [this table](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions) for details on watermarked editions.

**Comment by kahnivore** [comment]
Hi @mikemilla 

Did you come right with this?

**Comment by AndrewRH** [comment]
Also note that loading from a buffer is a windows only feature - it will not work in WebGL

**Comment by mikemilla** [comment]
@kahnivore @AndrewRH thanks for the tips. I have not tried these because I decided to go a different direction with my project.

Thanks for the help tho!
