### ISSUE TITLE
Unable to play local video (h265) in win10

### ISSUE THREAD

**Issue by lhmgithub** [RenderHeads/UnityPlugin-AVProVideo#795]

**Comment by kahnivore** [comment]
HEVC requires Windows 10 for native support, but the codec no longer ships with Windows and requires a [download from Microsoft Store](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7#activetab=pivot:overviewtab). Otherwise DirectShow API can be used with LAV Filters.

**Comment by RenderHeadsSte** [comment]
Closing due to lack initial detail and response
