### ISSUE TITLE
Error message save as a string c#

### ISSUE THREAD

**Issue by serversdz** [RenderHeads/UnityPlugin-AVProVideo#797]
hello, i am trying to save any error message that occurs on avpro media player 1x in a string so if a file URL is missing for instance I can fix the problem
how to do that in c#?
thanks in advance

**Comment by kahnivore** [comment]
Hi @serversdz 

You could listen for the error event, example below: 

`//Add the event listener (can also do this via the editor GUI)
MediaPlayer mp;
mp.Events.AddListener(OnVideoEvent);

//Callback function to handle events
public void OnVideoEvent(MediaPlayer mp, MediaPlayerEvent.EventType et, ErrorCode errorCode)
{
switch(et)
{
case MediaPlayerEvent.EventType.Error:
//Do something
break;
}
}


`

**Comment by kahnivore** [comment]
Hey @serversdz 

You could listen out for the error event as below:

`//Add the event listener (can also do this via the editor GUI)
	MediaPlayer mediaPlayer;
	mediaPlayer.Events.AddListener(OnVideoEvent);

	//Callback funtion to handle events
	private void OnVideoEvent(MediaPlayer arg0, MediaPlayerEvent.EventType et, ErrorCode errorCode)
	{
		switch (et)
		{
			case MediaPlayerEvent.EventType.Error:
				//Do Something
				break;
		}
	}`

Does this help? 

Thanks.

**Comment by kahnivore** [comment]
@serversdz did this answer your question? Will assume we can close this issue if we don't hear back.
