### ISSUE TITLE
Video not play on iOS, PC!

### ISSUE THREAD

**Issue by SonAVR** [RenderHeads/UnityPlugin-AVProVideo#8]
I have a video that AVPro can play without issues on Android, Mac but does not work on PC, iOS! I cannot share the video, but here are some info that might help

Video Codec: H.264
Resolution : 2160x2160
Bitrate: 12031kbps

I suspect the bitrate might be the culprit. 

Tested using latest version of AVPro 1.9.10

**Comment by MorrisRH** [comment]
The resolution is well within most device capabilities, so bitrate is the likely culprit. Unfortunately
without access to the video we're not likely to be much more help at this point.
