### ISSUE TITLE
[#sx6z6] Non multiple of 16 videos display seam on Android OES mode

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#80]
**Describe the bug**
When playing a non-multiple of 16 video on OES mode, the edge of the video is padded, which causes seams when wrapping a 360 video to a sphere.

This doesn't happen in non-OES mode, presumably because the texture transform during the blit handles any cropping and scaling that is needed.

**Your Setup (please complete the following information):**
 - Unity version: any
 - AVPro Video version: 1.9.16
 - Operating system version: Android
 - Device model: any

**To Reproduce**
1. Author a video that is a non-multiple of 16 (eg 3800x3800)
2. Set it to play using OES and wrapped to a sphere.  

![seam](https://user-images.githubusercontent.com/5418126/59119844-c3ada380-894b-11e9-82ce-077e96dfafb0.jpg)

**Comment by RenderHeadsSte** [comment]
We have tracked the issue and are working on a fix.

**Comment by RenderHeadsSte** [comment]
A fix for this will be presented in v 1.11.1 and onward.  Please do re-open the issue if the fix does not solve the issue for you
