### ISSUE TITLE
Streaming jitters/stalls first few seconds, works fine in inspector playback

### ISSUE THREAD

**Issue by shubhank008** [RenderHeads/UnityPlugin-AVProVideo#801]
**Describe the issue**
I am facing a very weird problem where when streaming a video, it stalls/jitters first few seconds even though that part of it has buffered already (from my trial and errors its almost always first 20-30 seconds) but as soon as I seek it past first 30 seconds it plays smooth.
I have added debug logs in _segmentsBuffered to make sure first 10-30 secs are buffered when player tries to play the video but it still jitter/stalls.

Now the surprising thing is, same video, same url with same settings when playing in MediaPlayer in inspector streams smoothly from start to finish.
This first few seconds stall issue happens only in actual video player, tried the same in Demo Scene too using multiple videos/urls but same thing, plays smoothly if test in inspector but stalls in actual video player.

Tried seeking to any moment before 30 seconds, stalls. Seek any moment after 30 second, plays smoothly.

PS: 30 second is just a guess mark of the point before which it stalls and after which its smooth, its not accurate and can be 28 or 25 secs, etc.

Normal x264 mkv video, Windows 10, Media Foundation, Unity 2020

**Your Setup (please complete the following information):**
 - Unity version:  2020
 - AVPro Video version:  2.1.0
 - Operating system version:  Windows 10 x64
 - Device model:  Desktop/PC
 - Video specs (resolution, frame-rate, codec, file size):   1080p/720p, x264, 8bit, mkv

**To Reproduce**
1.  Try playing the video as a stream/url whether in self-code or demo scene  
2.  Video starts playing but stalls/jitters from 0 second mark continuously, even if you pause it to so it can buffer a bit and play again, same behavior.  
3.  Try seeking it a bit, still same, but seek it somewhere middle (in 20 mins video I seek after 30 secs and always works) and it will work.  Then if you try to seek it back to start where it was stalling before, it will play smooth.  
4.  When it stalls, fps drops to 0-5 in video player while Unity fps is 100+. Buffer playback is available even for the stalled part of video as confirmed by adding debug logs in a loop to get buffered time ranged.  

**Logs**
Nothing in logs

Example links - https://store.animewat.ch//OP/OP[1080pp][][RapidBot].mkv

**Comment by shubhank008** [comment]
I was wrong, the problem is not first 30 seconds related but initial first few seconds itself.
The playback seems fine but its more like the player/video stalls at initial frames/seconds only.

Earlier I was testing 20 mins video and came to the 30 second conclusion but now I tested 90 second video and faced similar problem.
However, I noticed if I seek it to any point which has buffered, it plays smooth and then if I seek it backward to start then also it plays smooth now.
But if I pause the video for 4-5 seconds at start itself to let it buffer completely (yes 100% buffered), then also it will have the stall/jittery frame problem until I seek it forward/backward a bit (when playing it initially).

I have noticed that during this jitter/stall problem the fps of mediaplayer drops to either 0 or 0-5fps while Unity fps are still 120~

Or I don't know maybe it really is not buffering very first few seconds of the video again and again and instead buffering from random points, but I don't feelt his is the case as in your _segmentsBuffered I did a debug log and it reported GetBufferedTimes from 0-5 and 0-10 continuously (I believe its seconds ?)
  

```
if (_segmentsBuffered)
            {
                RenderHeads.Media.AVProVideo.TimeRanges times = AVProManager._instance._mediaPlayer.Control.GetBufferedTimes();
                float[] ranges = null;
                if (times.Count > 0 && timelineRange.duration > 0.0)
                {
                    ranges = new float[times.Count * 2];
                    for (int i = 0; i < times.Count; i++)
                    {
                        ranges[i * 2 + 0] = Mathf.Max(0f, (float)((times[i].StartTime - timelineRange.startTime) / timelineRange.duration));
                        ranges[i * 2 + 1] = Mathf.Min(1f, (float)((times[i].EndTime - timelineRange.startTime) / timelineRange.duration));
                        //Debug.Log(times[i].StartTime + " - " + times[i].EndTime + " -- "  + timelineRange.startTime + " --- " + timelineRange.duration);
                    }
                }
                _segmentsBuffered.Segments = ranges;
            }
```

**Comment by shubhank008** [comment]
> As a starting point, which video API are you using? Testing the link you've provided I get smooth playback on Media Foundation and WinRT, but some buffering with Direct Show.

MediaFoundation.  
Is your initial start/playback also smooth ? I am getting smooth playback when trying in inspector's video player preview module but stutter in actual video player (through code).

**Comment by shubhank008** [comment]
This problem is still there and not resolved.

**Comment by kahnivore** [comment]
Hey @shubhank008 

Both links play smoothly for me, no stutter. I've just tested on our latest release, 2.1.4, so potentially worth updating if you haven't already.

If you download the video and play it locally, do you still get the same stutter? 

Could you tell me a bit more about your hardware specs, graphics card in particular? 

Thanks

**Comment by kahnivore** [comment]
Any word on this @shubhank008?
