### ISSUE TITLE
Opening AVPro video does not show first frame

### ISSUE THREAD

**Issue by nirharpaz** [RenderHeads/UnityPlugin-AVProVideo#804]
I have an issue where images are assigned to be given an absolut URL and are shown the 1st frame.
In some occations it seems like the 1st frame is not presented, does it have anything to do with the Open?
is there a way you would recommend to play the 1st frame?

**Comment by kahnivore** [comment]
Which platform is this for? Could you paste the code you're using to play the video?

**Comment by kahnivore** [comment]
Closing this as no more information has been provided.
