### ISSUE TITLE
IAudioTracks APIs return incorrect info on android

### ISSUE THREAD

**Issue by siyu-he** [RenderHeads/UnityPlugin-AVProVideo#805]
Hello,

**Describe the issue**
In the test content we have two audio tracks, on an android device that does not have the capability to decode the first track (#0:1 eac3) but can decode the second track( #0:2 aac). 
```
  Duration: 00:01:03.55, start: 0.000000, bitrate: 12207 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 11187 kb/s, 24 fps, 24 tbr, 24 tbn, 48 tbc (default)
    Metadata:
      creation_time   : 2021-05-30T17:43:07.000000Z
      handler_name    : video handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: eac3 (ec-3 / 0x332D6365), 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
    Metadata:
      creation_time   : 2021-05-30T17:43:07.000000Z
      handler_name    : sound handler
    Side data:
      audio service type: main
    Stream #0:2(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 255 kb/s
    Metadata:
      creation_time   : 2021-05-30T17:43:07.000000Z
      handler_name    : sound handler
```
When playing this content using AVProVideo, we can see ExoPlayer under the hood checks device capability and choose to play the second track (from logcat, aac decoder is initialized). We can hear the audio being played, but when using IAudioTracks APIs, we are seeing:
[GetActiveAudioTrack()](https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.IAudioTracks.html#RenderHeads_Media_AVProVideo_IAudioTracks_GetActiveAudioTrack) returns null
[GetAudioTracks()](https://www.renderheads.com/content/docs/AVProVideo/api/RenderHeads.Media.AVProVideo.IAudioTracks.html#RenderHeads_Media_AVProVideo_IAudioTracks_GetAudioTracks).Count returns 0

If we play this content on a device that has eac3 capability, we can see the info being returned correctly.

**Your Setup (please complete the following information):**
AVProVideo 2.1.3
Test device: Pixel 2xl running android 11 

Would it be possible to have a fix? 
Thank you.

**Comment by kahnivore** [comment]
Hi @siyu-he 

Could you possibly send us some media to test this with? You can send to unitysupport@renderheads.com, with #805 included in the subject line.

Thanks!

**Comment by siyu-he** [comment]
Hi @kahnivore ,

Thanks for the quick response!
We are checking internally to get a shareable mp4 file.

**Comment by siyu-he** [comment]
Test content was sent to unitysupport@renderheads.com. Thanks.

**Comment by RenderHeadsSte** [comment]
Thanks for sending your video over.  I am looking at why there is no information returned now...

**Comment by RenderHeadsSte** [comment]
Found the problem and will be including a fix in the next release.

The issue was showing up due to the 1st audio track (with 5.1 channels) being unsupported.  As a quick fix before the next release, you could try swapping the audio tracks around in your source video.

**Comment by siyu-he** [comment]
Great, thanks @RenderHeadsSte for the prompt fix! 
As the order of the tracks are rather essential to us for keeping the behavior aligned between android and iOS devices, we can't wait to try 2.1.4.

**Comment by RenderHeadsSte** [comment]
With 2.1.4 released now, please do let us know how you get on with the fix @siyu-he

**Comment by RenderHeadsSte** [comment]
@siyu-he ?
