### ISSUE TITLE
Error sideloading subtitles on Android

### ISSUE THREAD

**Issue by SuwasSVR** [RenderHeads/UnityPlugin-AVProVideo#806]
Error loading subtitles on Android. 

 - Unity version: 2020.3.9f1
 - AVPro Video version:  v2.1.3f1-core
 - Operating system version: Android 11
 - Device model: Pixel 4

- Error loading subtitles ...
- Failed to load subtitlesjar:file
![Capture](https://user-images.githubusercontent.com/50114742/120391701-087b3380-c2f5-11eb-9056-0153b4cb697a.PNG)

**Comment by kahnivore** [comment]
The player is most likely struggling to extract the SRT from the JAR file. Could you try extracting the SRT and setting it as the subtitle path?

**Comment by SuwasSVR** [comment]
How do I extract the the SRT from the JAR file? Where should I look for the JAR file? Thanks

**Comment by kahnivore** [comment]
You extract it using an archive utility or using commands in Java (see [here](https://docs.oracle.com/javase/tutorial/deployment/jar/unpack.html)). And location should be the path you've set the subtitles to be.

**Comment by SuwasSVR** [comment]
Thanks! I've set the subtitles to be in the streaming assets folder. I don't see any JAR file in there?

**Comment by kahnivore** [comment]
@SuwasSVR sorry maybe I'm missing something. Is there any chance you could send the subtitle file over to unitysupport@renderheads.com so we can test it for you?

**Comment by AndrewRH** [comment]
i'm surprised to hear that the SRT file placed inside StreamingAssets cannot be loaded by MediaPlayer component - it has code in there to load them, even from inside JAR file I believe (using WWW class, or it's equivalent in later Unity versions)...

**Comment by RenderHeadsSte** [comment]
Thanks for sending over your SRT files.  I have tested both.  The test.srt file loads just fine.  I believe your issue might be an error in your 2020BoardGamesCC.srt file.  There is a double line space between 57 and 58.  I removed one of them and the SRT loads and does it's job just fine here on my test device.

Hope this helps.  Do let us know.

**Comment by SuwasSVR** [comment]
That's very strange because both the files aren't working on my end on the Android device mentioned above. It seems like I might be missing something on my end. I've sent a Test project with just AVPro in it on the same email thread. I'd appreciate it of you guys could check it out and let me know what's missing.

Worth noting..it is working on the editor and it was working on the older versions (1.x) of AVPro.

**Comment by SuwasSVR** [comment]
Thanks for looking into it. Do you guys have any updates on this yet?

**Comment by RenderHeadsSte** [comment]
We have tracked this down to a script bug that we will fix in the next version.

Until then, you could make the simple change you side.  If you open MediaPlayer_Subtitles.cs and go to line 101 you will find the 'if' statement:

if (www.result == UnityEngine.Networking.UnityWebRequest.Result.ConnectionError)

...if you change this to:

if (www.result == UnityEngine.Networking.UnityWebRequest.Result.Success)

...then the issue you are seeing should be fixed.

Thanks for reporting this.

**Comment by SuwasSVR** [comment]
Thanks. That worked!

**Comment by kahnivore** [comment]
2.1.5 has now been released and includes this fix.
