### ISSUE TITLE
Problem for reading video

### ISSUE THREAD

**Issue by LudovicWVirtysens** [RenderHeads/UnityPlugin-AVProVideo#807]
Why I can't read this video  360 8K

https://drive.google.com/file/d/1w7AmxSYnap1XcD_OIinCY6_wAZnbFBb1/view?usp=sharing

 - Unity version:  2020.2.1f1
 - AVPro Video version: Android V2
 - Operating system version: 
 - Device model: Pico G2 4K

**Comment by kahnivore** [comment]
Pico G2 4K doesn't support 8k. See [here](https://headjack.io/knowledge-base/best-video-resolution-for-pico-headsets/). Have you tried your media at a lower resolution?

**Comment by LudovicWVirtysens** [comment]
Hi,
Thanks for this information, It's very interesting help for me.
