### ISSUE TITLE
android ,avprovideo version2.0.11, no sound ,GetDurationMs  return wrong value..runs ok in editor

### ISSUE THREAD

**Issue by 15989766280** [RenderHeads/UnityPlugin-AVProVideo#808]
**Describe the issue**
platform android ,avprovideo version2.0.11,play absolute url video like ****.mpeg...........it plays no sound....GetDurationMs() returns 9.22E+18 and when i called Seek(1000000),the video plays from the begining of the vieo.....when running in windows editor mode,,it runs ok.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.26
 - AVPro Video version: 2.0.11
 - Operating system version: editor in windows,,running in android
 - Device model: android huawei p30
 - Video specs (resolution, frame-rate, codec, file size): 1920*1080,MPEG-2 TS (.ts),25frame/second,4.8 GB

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
http://112.17.52.41/110000000108/00600637000000020000000025381937/29666.ts?AuthInfo=cC4TcDJPbdaBKl6GOM1k9%2BSDvhyZovLSYF4YT6nvpF2VzJ1aRgpCMDLadHbBdhZy4%2BtVUeUiEFY6iJFvjjPGWp8w8l%2F9%2F8zqqw4YWe3bXbuo9HiQOmEMEu%2Fspb08k%2Fbj8vAL1geKq9iASMGGfNvZYw%3D%3D&version=null&netType=Wifi&clientType=Android&isVr=0&zjDownLoadFlag=0&zjAppOfType=3&is5G=0&zjTerType=PC

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by 15989766280** [comment]
copy that link to browser or to the avpro path for test

**Comment by kahnivore** [comment]
Hi,

Are you sure this link is correct? It doesn't open in browser or load in editor. 

It'd be useful to know which audio codec your media is encoded with and which API you are using (ExoPlayer or Android Media Player) as they both have constraints regarding audio codecs that may be causing this, as well as limitations with seeking using MPEG-TS. Please see Android Media Player supported media [here](https://developer.android.com/guide/topics/media/media-formats), and ExoPlayer [here](https://exoplayer.dev/supported-formats.html). 

Thanks

**Comment by kahnivore** [comment]
Also please see [this note](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#streaming) on HTTP streaming in Android 9 and above.
