### ISSUE TITLE
IOS Autoplay not working after first time opening media

### ISSUE THREAD

**Issue by ASquareDevs** [RenderHeads/UnityPlugin-AVProVideo#812]
**Describe the issue**
A clear and concise description of what the issue is.

Calling OpenMedia(MediaPathType.AbsolutePathOrURL, videoPath, true) does not auto play after the first time calling it from Mac IOS Editor and in an IOS build. If I want to play a different video I actually have to call play. The same logic on android will auto play every time. AutoOpen and AutoStart are set to true as well.

**Your Setup (please complete the following information):**
 - Unity version:  2021.1.1f1
 - AVPro Video version: AVPro Video 2.0
 - Operating system version:  IOS 14.4.2 
 - Device model: IPhone SE 
 - Video specs (resolution, frame-rate, codec, file size): 1280x720, 30FPS, H264 - MPEG-4 AVC ,112MB
 
**To Reproduce**
1. On IOS devices only, open a video using OpenMedia with autoplay set to true.
2. Stop the video and open a second video any video after the first one will not auto play after calling Open Media the first time
3. These videos do load and will play if I where to call play but will not auto start after loading 

**Logs**
If applicable, add error logs to help explain your problem.
No errors return I only get a log that says it is opening the video

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL
https://bxr-uat.s3.us-east-2.amazonaws.com/youtube-video/60b564c3153d7f5a6462ef44.mp4 ,

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
I'm unable to reproduce this, my setup is as follows:
- Unity 2019.4.28f1
- AVPro Video 2.1.3 Trial
- iPad Pro (10.5") iOS 14.4.2

I've attached the script I'm using to test, you just need to attach it to a Quad instance in your scene.
[Issue812.cs.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6610575/Issue812.cs.zip)

If you can provide more details we can investigate further.

**Comment by ASquareDevs** [comment]
I was opening MediaPathType.AbsolutePathOrURL links and I wasn't using the same version exactly I was using 2.0. My code is also calling stop first then opening the new video.

**Comment by MorrisRH** [comment]
Please update to the latest version, there have been many fixes applied since 2.0 including some related to starting to playback.

**Comment by kahnivore** [comment]
@ASquareDevs can you let us know if updating to the latest version solves your issue? 

Thanks

**Comment by ASquareDevs** [comment]
Updating to he newest version did fix the problem thank you.
