### ISSUE TITLE
Getting HLS streams playing again in W10 & Unity 2018.4.20f1.

### ISSUE THREAD

**Issue by tw1l1ght** [RenderHeads/UnityPlugin-AVProVideo#813]
Dear RenderHeads-Team,

not sure if you are the right point of contact for this, as its most likely a filter/merit/codec issue... but who if not the creators of the tool being used might be able to help me solve this?

I reinstalled my win10 system a couple of weeks ago, to get me a clean & slim system for vr & vrchat (I'm clubbing in vrc).
The usual vrclub world has a media-player where either a livestream gets played or you throw some nonlive files at it.
So far so good... most of the different worlds & their avpro-implementation work fine... but all HLS-streams getting started out of unity via an m3u8 playlist containing mostly some .ts filefragments wont play for me - whatever I do.

All I'm getting is a white screen and errors in vrchats logfile like the ones I pasted further down.
I'm actually pretty sure media foundation is trying to play the stream but doesn't support hw-acc for this type of video (h264?) and thus bails out.

Easy solution in theory: don't use mediafoundation for these streams, use directshow instead!

And exactly that is what I cannot get working for the life of me...
I tried installing/removing countless codec-packs, codec tweak-tools etc pp... no dice.
And to get deeper into the meaty details of merits & stuff I don't have the needed knowledge...

Actually I'm pretty sure by now w10 & unity are dead set to drive me mad.... ;)

So here's me reaching out for help:
How do I get my HLS streams back working?

Thank you SO much in advance for helping me out! <3
Raphael

```
[AVProVideo] Error: Decode failed. Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources.

[USharpVideo] Video failed: https://www.twitch.tv/thedefreeze

NativeProcess.HasExited: process exited with code 0, took 2329 ms. Command line: C:/Users/raphael/AppData/LocalLow/VRChat/VRChat\Tools/youtube-dl.exe (...)

[Video` Playback] URL 'https://www.twitch.tv/thedefreeze' resolved to 'https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CqcEhXRCAKk712sE5ySVkYTTsfZP1ab2vgsdNILfBluzZbxQT5IajovS5Sa7qnaTgiYWsaF7e-81wRRwhfGwoYFyEguohvlIqxUfz_GZSeA2RG2ac6NHRzOhtVETjJPaz7wCEsWIaoeIUQfJ6i8cOcomAZ-Kwj1pPddzglHVywdMi_OIN0odeTb9SX3yfx7Glyip69SwK3vEHiDTKYG486fUTOH8viHZzJG9ywlKgQduiakKdSuqCj6ZfanXOlCF85E4WSWGrf99RhThTidaw6jfoPOJ3p7ZYUqVU-Mhi4eQroAbvgEF02uVvMMyuBu9YsghaMNoxZBH2Zn8hKyD5WhIz6Uu0OVHA1ndBw6cm5O_JKDNZdmo0nJOGNvIVCk1DXw8sfojAQfY8AhzFsa9pkfrrCZEIE5ZBcQsYD-JESSnySrNqG9r7Uwyj0h88cwzmEtzOLqJ2Od_bF00GIf5CprIdPKoZs3aom9XXmpFpO3Qrg-WF8HDRcAOr1xhjqbgEAnP-yw-YiHawV_2L-9o_VknvKjaqXqc7Mc5HVRkjti9TIO9qvpa7XLTmFxAbgNULOhvO0bsIGG0Nn0bK5OA_RErTZv0ZB3hajVU4YwjCoFuWhM8w5E75HJmnHbZBBJflBZ92ea26chNMhWb5hBOK782_L-ywlv-rdtca6oGdrC2_Bq3zcxq7F8eRnpIKtZT27I-EPzKwBqCNZmzpWSaB7GARF1pFC4aeTISEMjEwNwTif0__ISM0N_6Y5UaDCAPDnCPnRm0KA20BA.m3u8'

[AVProVideo] Opening https://video-eaver.fra02.hls.ttvnw.net/ |snip| 6Y5UaDCAPDnCPnRm0KA20BA.m3u8 (offset 0) with API MediaFoundation

[AVProVideo] Error: Decode failed. Possible codec not supported, video resolution/bit-depth too high, or insufficient system resources.
```

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.20f1.
 - AVPro Video version: not sure which the worlds use
 - Operating system version: w10 pro
  - Video specs (eg: 1080p/60, avc1, .ts fragments):  

![image](https://user-images.githubusercontent.com/3396758/120881549-2933d980-c5d2-11eb-96ed-9c17f6502514.png)
The white space usually plays the video

**Videos**
pretty much every twitch hls-livestream

Playing these streams via windows mediaplayer morks perfectly fine btw...

**Comment by tw1l1ght** [comment]
These are the logs of a successfull played stream (from a friend):

```
2021.06.05 08:10:06 Log        -  [USharpVideo] Started video load

2021.06.05 08:10:06 Log        -  [Video Playback] Attempting to resolve URL 'https://www.twitch.tv/d4rkcide'

2021.06.05 08:10:06 Log        -  NativeProcess.Start: started process id [15312]: C:/Users/<my_name>/AppData/LocalLow/VRChat/VRChat\Tools/youtube-dl.exe (...)

2021.06.05 08:10:06 Log        -  [USharpVideo] Playing synced https://www.twitch.tv/d4rkcide

<lots of stuff related to avatars loading in>
```
```
2021.06.05 08:10:08 Log        -  NativeProcess.HasExited: process exited with code 0, took 2138 ms. Command line: C:/Users/<my_name>/AppData/LocalLow/VRChat/VRChat\Tools/youtube-dl.exe (...)

2021.06.05 08:10:08 Log        -  [Video Playback] URL 'https://www.twitch.tv/d4rkcide' resolved to 'https://video-weaver.ams03.hls.ttvnw.net/v1/playlist/CpwEGFePfHhg08d8iQRFiHDfucqwbIh3Fm4T7SL_tfc6KxgOVBbvTfQqtNPdRo7YZXP5947wU677cSVp1isfqtva4QU8ahL3N6r8NSE4-_Iqu40Mj6ELBfMAZaNEE8SSxD42KobO5kfL5mLvk3fLHHSJCPwkbaSAcdxP9NUQpansTrRM5_CFUOae4w56FO5s5fZoq6cf7LuFMsyf7Eunk6kgkdLdxUQVD5Sv5HgL_rKmCXcDGoQhI4qesR1uXemxIqj9GwsP5NL9PQzCvV_AWXEKtQf38PMfROo_Q3kNmIaf6sl3u-7PbUN9ErwRm644YA7LHQ-vDC_NW0cSCZ31BkqvLOKgq5GpKtcGHAXbb26iwBWSYec8zYAlUnk3rqwCMenBbnv0HU1p1kYqtsmZQoO9G5Ruqv26W0yUPj09Z6gYW0nkwoUNifW5C1eQ2hTe7r_jWDxgBP4aFlQ11h8RaPO4UMTqskVH8I6przftG9-7DOvOYTH3Mx7qWVdW23bkYyZY5MC_M85jpqUYYFc46KEBO4Yqc9P2jpVjv4Z9Zn-JIuGE2iKY_ojU5VlmUMks0XyISMJmEznNpntHZoFo2yAvKSrtDnhVBMxGgAJbLJExaTzIqgzcQppPGy-4gA5JjXy-4GMX9SixPVvEDcJ1H-f5GqKtZpLcqUkndAV0zHtbipfoxdZK7my1HpQw9HjhQF9J7ZR87EMQmsttCU3aEhBNhx1IZ3NIp8rB0MQ-vUMBGgyrvawYLZFNMjO66FA.m3u8'

2021.06.05 08:10:08 Log        -  [AVProVideo] Opening https://video-weaver.ams03.hls.ttvnw.net/v1/playlist/<very_long_string_of_code> (offset 0) with API MediaFoundation


```

**Comment by kahnivore** [comment]
Hi @tw1l1ght 

It's pretty straightforward to select the Direct Show API in our plugin, but not sure about VR Chat's implementation of it. Have you tried contacting them about this? We can only really support AVPro Video as a direct product.

**Comment by kahnivore** [comment]
Closing as this is not directly about our plugin

**Comment by tw1l1ght** [comment]
Thx anyway guys =) 
...totally getting its not your thing!

Incase anyone should stumble about this having the same issue, I got it solved by trail & error.
It all reduced down to "logout vrc, clear cache/profile, login again"
