### ISSUE TITLE
AV Pro Splash Screen?

### ISSUE THREAD

**Issue by dariusjulian** [RenderHeads/UnityPlugin-AVProVideo#816]
**Describe the issue**
We're building a multi-display app using AV Pro Video.  The other day we launched the app and in place of some of the videos there was an AV Pro image.  It's only happened the one time so we aren't sure what caused it or what it might mean.  Attached is a picture from the issue.

**Your Setup (please complete the following information):**
 - Unity version: 19.3.12f
 - AVPro Video version:  1.11.5
 - Operating system version: Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size):  .mp4 680x1040 24fps

**To Reproduce**
1. ?
2. 
3. 
![chemlife](https://user-images.githubusercontent.com/25442059/121424156-a777df00-c936-11eb-98cb-79847b327732.jpg)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @dariusjulian 

Will need a bit more information from you to figure out what's going wrong here. 

1. Do you mean the videos play fine in the editor and aren't playing in the build? 
2. When you see the AVPro image rendered can you hear any audio playing (if the videos in question have audio)?
3. Are you playing videos locally or from a server? 
4. Can you send a bit more info about the videos that are failing? Video and audio codecs in particular. If not, could you send a sample to unitysupport@renderheads.com so we could have a look for you? 

Thanks.

**Comment by AndrewRH** [comment]
@dariusjulian that image appears when AVPRo Video is run on a platform that is not supported (it is the NullMediaPlayer class which is basically a dummy media player which creates a placeholder for non-supported platforms), or when the supported platform can not initalise the underlying video playback system for some reason (eg using Vulkan on Android).
Perhaps check the log file to see what warning/error messages it has?

**Comment by kahnivore** [comment]
Hi @dariusjulian

Any word on this?
