### ISSUE TITLE
iOS OpenMedia Crash upon loading file multiple times

### ISSUE THREAD

**Issue by skooby** [RenderHeads/UnityPlugin-AVProVideo#820]
**Describe the issue**
Using a derivative of the Demo_MediaPlayer sample
Have an app that loads videos in a list of icons/buttons when clicked it opens loads media via OpenMedia call.

If I call too many times it will crash after like 10 times
Only happening on iOS not Editor/Windows/Android/Mac/etc

**Your Setup (please complete the following information):**
 - Unity version: 2020.3
 - AVPro Video version: 2.1.3
 - Operating system version: iOS
 - Device model: iOS anything
 - Video specs (resolution, frame-rate, codec, file size): N/A

**To Reproduce**
1. Call OpenMedia multiple times for different video files
2. Crashes with UnityGfxDeviceWorker EXC_BAD_ACCESS
3.

**Comment by MorrisRH** [comment]
I've set up a simple test case playing our sample videos back to back. It's run fine for over 30 minutes without incident.
I'm using:
* Unity 2020.3.11f1
* AVPro Video 2.1.4 Trial
* iPad Pro (10.5") running iOS 14.6

Are you able to provide any further information about how you're using the media player, what modifications you've made to it, the kind of videos you're playing (local or streamed)?

**Comment by skooby** [comment]
They are local videos.  They are .mov files that are looping.
I changed my video player to utilize PlayListMediaPlayer to switch between MediaPlayers when I load a new video. This seems to help. It is still crashing in xCode however. 

It is giving this info when it crashes:.
Assertion failed: (*buffer != ((void*)0) && "buffer must not be a pointer to NULL"), function AudioCaptureBufferRelease, file /Users/morris/RenderHeads/Dev/AVProVideo/NativePlugins/Xcode/AVProVideo/AudioCapture/Sources/AudioCapture/AudioCaptureBuffer.c, line 67.

**Comment by MorrisRH** [comment]
I'm afraid I am totally unable to reproduce the issue. Are you able to share your project? If so please send it unitysupport@renderheads.com with "iOS OpenMedia Crash upon loading file multiple times #820" as the subject, thanks!

**Comment by skooby** [comment]
Can you give me an idea of what I could try to resolve this? The PlayListMediaPlayer stuff did not resolve it and it is back to crashing every 6 or so presses. It does appear that some of the video samples do not have audio tracks could that cause this assert?

**Comment by skooby** [comment]
I changed the **MediaPlayer** > **Platform Specific** > **iOS** > **AudioMode** to **System Direct** from **Unity** and that appears to have fixed it.

**Comment by MorrisRH** [comment]
Well... avoided it anyway ;)
What happens when a user loads a new video? I'm assuming whatever sequence of calls you make is leading to the crash so it would be good to have an idea of what they are.

**Comment by skooby** [comment]
Since this problem wasn't appearing on any other platform other than iOS it must be an issue with the Unity Audio Mode. 
Since all I am doing is calling OpenMedia.

FYI, I think that setting for AudioMode in the documentation says that System Direct is the default. I based my code on the samples that shipped with the package and it was set to Unity for iOS.

Thanks for your help!

**Comment by MorrisRH** [comment]
> They are local videos. They are .mov files that are looping 6 seconds/360 degree videos of products. The user can click on a new button to load an additional video.
> 
> UPDATE: I changed my video player to utilize PlayListMediaPlayer to switch between MediaPlayers when I load a new video. This seems to help. It is still crashing in xCode however.
> 
> It is giving this info when it crashes:.
> Assertion failed: (_buffer != ((void_)0) && "buffer must not be a pointer to NULL"), function AudioCaptureBufferRelease, file /Users/morris/RenderHeads/Dev/AVProVideo/NativePlugins/Xcode/AVProVideo/AudioCapture/Sources/AudioCapture/AudioCaptureBuffer.c, line 67.

I've removed the assertion causing the crash in the latest build (2.1.5) which I'm hoping will fix the issue you're seeing when using Unity for the audio mode. Still no idea on how you managed to make it happen though ;)
