### ISSUE TITLE
Unity 2020 IOS Build issue "_UnityEndCurrentMTLCommandEndEncoder"

### ISSUE THREAD

**Issue by Archi97** [RenderHeads/UnityPlugin-AVProVideo#821]
I trying to upgrade my Project from Unity 2018.4.23 to Unity 2020.3.4: 
Fixed all warning,errors, etc. Now Unity builds Xcode project.  But when trying to Build App in Xcode project, im getting this error, and Build Failed. 

Undefined symbols for architecture arm64:
  "_UnityEndCurrentMTLCommandEncoder", referenced from:
      _AVPPluginUnityRegisterRenderingPlugin in libAVProVideoiOS.a(AVProPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

AVPro Version 1.7.3(scripts 1.7.4) 
Also Unity crashes when im adding Media Player component on the object in Unity

Android works great.

**Comment by MorrisRH** [comment]
Unity changed the graphics API for Metal quite some time ago and removed the ```UnityEndCurrentMTLCommandEncoder()``` function from their interface so you need to add the following stub function to AVProVideoUnityRegisterRenderingPluginV5.c (which can be found in the Assets/Plugins/iOS folder) to resolve the issue:
```
#if UNITY_VERSION >= UNITY_2018_1_0

void UnityEndCurrentMTLCommandEncoder()
{
	// Empty
}

#endif
```

**Comment by Archi97** [comment]
Solved. Thank you.
