### ISSUE TITLE
Memory leak on finished playback when output audio to Unity on Windows

### ISSUE THREAD

**Issue by zLucPlayZ** [RenderHeads/UnityPlugin-AVProVideo#822]
**Describe the issue**
While using AVPro 2.1.4 we encountered issues regarding memory management. On video end memory seems to not be cleared properly, while pausing the video before end seems to have fixed the issue temporarily. We utilize AVPro Core for Windows and can confirm that the issue persists even in the latest version. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.13f
 - AVPro Video version: 2.1.4
 - Operating system version:  Windows 10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 1920 x 1080, 24 fps, av01.0.08M@1575k (mp4), 35.64MiB 

**To Reproduce**
1. Open any video stream using Open Media on windows using media foundation
2. Wait until the video finished playing / or skip to end (doesnt matter, only thing that matters is when it reaches the end of the current video)
3. Done, ram usage increased by ~50 Mb and is not collectable.

GC.Collect(); and Resources.UnloadUnusedAssets(); does not do anything. Even loading an entirely different scene without an avpro player in it, does not free up the ram again!

As mentioned, this only happens when the video reaches its end. Our working workaround is, to stop and close the media one second prior to the end, effectively shortening the video by 1 second.

**Logs**
Log containing, everything from start to finish of our game, including triggering the memory leak a couple of times.
[Player.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6670229/Player.log)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

We were told to open an issue by the support team.

**Comment by AndrewRH** [comment]
thanks @zLucPlayZ, a few questions:

1) are you using 'Unity' as the setting for 'Audio Output'?
2) are you able to reproduce this using our demo mediaplayer scene?
3) how are you measuring the RAM increase?
4) each time you play the video and it ends, does the RAM continue to increase forever?

Thanks,

**Comment by zLucPlayZ** [comment]
Hi @AndrewRH,

1. yes we do use Unity as output, we set it with the following on Start()
   `videoPlayer.PlatformOptionsWindows.audioOutput = Windows.AudioOutput.Unity;`
2. Yes I was able to reproduce the issue in the "Demo_MediaPlayer" Scene.
3. Im measuring it with 3 different "tools". 1. Unity Profiler 2. Task Manager 3. dotMemory (jetbrains memory profiler)
    This is not only an issue on my machine, it was brought to my attention by our users/players in the first place. They also identified the issue as only occurring on video end.
4. Yes, each time the video ends, the ram increases. Even with the same media stream open. For some of our users it used all of their memory, e.g. 25 Gb of ram, caused while using the avpro mediaplayer.
Everytime the video reaches it end, it increases the ram by ~50 Mb. Easiest way to reproduce the issue would be to skip to the last few seconds in a video and watch the memory usage go up by ~50 Mb in the exact moment the video reaches it end.

**Comment by AndrewRH** [comment]
Thanks, I have reproduced this - it seems to be related to having the audio output mode set to "Unity"..I've only seen the memory usage increase by maximum 6MB each play though.    I will investigate further..

**Comment by AndrewRH** [comment]
The bug has been patched and the fixed version will be 2.1.5 which should be released today or in the next few days.

Thanks for reporting this!

**Comment by kahnivore** [comment]
2.1.5 has been released! Please let us know if the patch fixes your issue. 

Thanks!

**Comment by zLucPlayZ** [comment]
@kahnivore @AndrewRH, seems like its fixed, no memory issues what so ever. Even for our specific use case no issues.

Thanks for the really fast fix and keep up the great work! 
Cheers
