### ISSUE TITLE
iOS Crash

### ISSUE THREAD

**Issue by AntonioStissi** [RenderHeads/UnityPlugin-AVProVideo#823]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.11
 - AVPro Video version: 2.1.3
 - Operating system version: iOS 14.5.1
 - Device model: iphone 12 mini
 - Video specs (resolution, frame-rate, codec, file size): 2K 360 video

**To Reproduce**
1. Simply opening a media in iOS
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

2021-06-17 15:38:42.052344+0200 WarpVR[9178:2040729] Uncaught exception: NSInvalidArgumentException: -[AVProVideo.Player openURL:]: unrecognized selector sent to instance 0x126977490
(
	0   CoreFoundation                      0x00000001a7ae25c8 58500388-BF36-397C-84CF-17315A3445B6 + 1217992
	1   libobjc.A.dylib                     0x00000001bc5617a8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a79e5a9c 58500388-BF36-397C-84CF-17315A3445B6 + 182940
	3   CoreFoundation                      0x00000001a7ae510c 58500388-BF36-397C-84CF-17315A3445B6 + 1229068
	4   CoreFoundation                      0x00000001a7ae76b0 _CF_forwarding_prep_0 + 96
	5   UnityFramework                      0x000000010899bf38 AVPPlayerOpenURL + 348
	6   UnityFramework                      0x00000001089cb14c Native_AVPPlayerOpenURL_mC9046F4BF3B7243740E14BE6C87683399D39AFA1 + 64
	7   UnityFramework                      0x00000001089b3410 AppleMediaPlayer_OpenMedia_m05FD22694B89379FD51BE3F2F6D54E521404E9CD + 424
	8   UnityFramework                      0x00000001089bcf14 MediaPlayer_OpenMedia_mE35FF534F57A2E2BB75E4CD3C2743AE7036282A7 + 816
	9   UnityFramework                      0x0000000108a8f5b0 MediaHandler_LoadAndPlayVideoFromSceneInfo_mBF01DF928EBAF95902E7EB75B34E85148AD5C4CD + 612
	10  UnityFramework                      0x0000000108b7500c ScenarioManager_LoadSceneFromSceneInfo_m7AB731BCAD7F908217C77AA07039020F51B80364 + 288
	11  UnityFramework                      0x0000000108b74eb0 ScenarioManager_LoadFirstScene_mD31827E46074AB2969C81B02D35EB352ACC95617 + 172
	12  UnityFramework                      0x0000000108cd99c0 U3CLoadFirstSceneAfterTimeU3Ed__30_MoveNext_mE337E224749D3061AD7597A6C6ECC09D12AB4428 + 164
	13  UnityFramework                      0x0000000109709824 SetupCoroutine_InvokeMoveNext_m036E6EE8C2A4D2DAA957D5702F1A3CA51313F2C7 + 204
	14  UnityFramework                      0x00000001078d2b2c _Z89RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5_RuntimeObject_IntPtr_tPFvvEPK10MethodInfoPvPS4_ + 28
	15  UnityFramework                      0x00000001087381d8 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 116
	16  UnityFramework                      0x0000000107e4f1f0 _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 124
	17  UnityFramework                      0x0000000107e5b478 _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 120
	18  UnityFramework                      0x0000000107e66710 _ZN9Coroutine14InvokeMoveNextEP21ScriptingExceptionPtr + 168
	19  UnityFramework                      0x0000000107e662c0 _ZN9Coroutine3RunEPb + 52
	20  UnityFramework                      0x0000000107c87a50 _ZN18DelayedCallManager6UpdateEi + 536
	21  UnityFramework                      0x0000000107d55264 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 100
	22  UnityFramework                      0x0000000107d552a4 _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 164
	23  UnityFramework                      0x0000000107d55570 _Z10PlayerLoopv + 272
	24  UnityFramework                      0x0000000108243120 _ZL19UnityPlayerLoopImplb + 112
	25  UnityFramework                      0x0000000107817ed0 -[UnityAppController(Rendering) repaint] + 108
	26  UnityFramework                      0x0000000107817e38 -[UnityAppController(Rendering) repaintDisplayLink] + 108
	27  QuartzCore                          0x00000001aad38eb8 B5B69CA2-65B2-359F-BCFF-24FD57D1EBF7 + 85688
	28  QuartzCore                          0x00000001aae17eb8 B5B69CA2-65B2-359F-BCFF-24FD57D1EBF7 + 999096
	29  CoreFoundation                      0x00000001a7a378bc 58500388-BF36-397C-84CF-17315A3445B6 + 518332
	30  CoreFoundation                      0x00000001a7a5d0d4 58500388-BF36-397C-84CF-17315A3445B6 + 671956
	31  CoreFoundation                      0x00000001a7a5c454 58500388-BF36-397C-84CF-17315A3445B6 + 668756
	32  CoreFoundation                      0x00000001a7a56038 58500388-BF36-397C-84CF-17315A3445B6 + 643128
	33  CoreFoundation                      0x00000001a7a551c0 CFRunLoopRunSpecific + 600
	34  GraphicsServices                    0x00000001bf03d734 GSEventRunModal + 164
	35  UIKitCore                           0x00000001aa4c37e4 186C18FD-1082-3811-A761-88E8376C7E69 + 12363748
	36  UIKitCore                           0x00000001aa4c9054 UIApplicationMain + 168
	37  UnityFramework                      0x0000000107817908 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 108
	38  WarpVR                              0x00000001043d3d70 main + 68
	39  libdyld.dylib                       0x00000001a7711cf8 B08AB7C2-64E8-3937-9487-C33D0175FD34 + 7416
)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hey @AntonioStissi 

How are you opening media? Also, have you tested this with any of our demo scenes?

**Comment by AntonioStissi** [comment]
I am using this:
mediaPlayer.OpenMedia(MediaPathType.AbsolutePathOrURL, pathToVideoToLoad,
true);
No I havent tried the demo, but the app works on Android Windows and MacOS.

Thanks,

Antonio
[image: Warp Industries]Antongiuseppe StissiTech Lead VR App+31 6 305 208 88
[image: Facebook] <https://www.facebook.com/warpindustries/> [image: Medium]
<https://medium.com/warp-industries> [image: LinkedIn]
<https://www.linkedin.com/company/10780715/> [image: Twitter]
<https://twitter.com/WarpVR> [image: Youtube]
<https://www.youtube.com/channel/UCpXmC1NyDYnmDmWpdaVGs8w> [image: Website]
<https://warp.industries/>

This message is confidential. If you have received this message in error,
please let us know and delete this email.

Warp is not liable if this message has been modified and/or sent without
permission. Warp Industries | KvK: 68335458
Molengraaffsingel 12, 2629 JD Delft, the Netherlands
<https://maps.google.com/?q=Molengraaffsingel+12,+Delft,+the+Netherlands&entry=gmail&source=g>

**Comment by kahnivore** [comment]
Is there any chance you could send us the media you're struggling to open? You can send to unitysupport@renderheads.com with the subject line #823 if it's of sensitive nature.

**Comment by kahnivore** [comment]
It's also possible that it's related to #783 i.e. there might be another plugin causing trouble.

**Comment by AntonioStissi** [comment]
I have several video, none of them open now after updating to avpro 2 (they
used to work in avpro 1).
I attach one as example.
Antonio

https://drive.google.com/file/d/173xE9JooY7dfdFZuRMERvTYhuEUeqaqJ/view?usp=sharing

[image: Warp Industries]Antongiuseppe StissiTech Lead VR App+31 6 305 208 88
[image: Facebook] <https://www.facebook.com/warpindustries/> [image: Medium]
<https://medium.com/warp-industries> [image: LinkedIn]
<https://www.linkedin.com/company/10780715/> [image: Twitter]
<https://twitter.com/WarpVR> [image: Youtube]
<https://www.youtube.com/channel/UCpXmC1NyDYnmDmWpdaVGs8w> [image: Website]
<https://warp.industries/>

This message is confidential. If you have received this message in error,
please let us know and delete this email.

Warp is not liable if this message has been modified and/or sent without
permission. Warp Industries | KvK: 68335458
Molengraaffsingel 12, 2629 JD Delft, the Netherlands
<https://maps.google.com/?q=Molengraaffsingel+12,+Delft,+the+Netherlands&entry=gmail&source=g>

**Comment by MorrisRH** [comment]
@AntonioStissi It does look like the AVPro Video 1.x plugin is still in your project. Specifically you need to remove libAVProVideo.a and AVProVideoUnityRegisterRenderingPluginV5.c, although I would also be concerned that some of the old C# scripts are also still present. It's probably worth making a new project, importing AVPro Video 2 and comparing with your existing project.

**Comment by kahnivore** [comment]
@AntonioStissi did this help?

**Comment by AntonioStissi** [comment]
Yes, I deleted the whole folder and re imported AVPro v2 and that fixed it.
