### ISSUE TITLE
ios AVQueuePlayer Crash

### ISSUE THREAD

**Issue by killsoon** [RenderHeads/UnityPlugin-AVProVideo#824]
**Describe the issue**
A clear and concise description of what the issue is.

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.30f1
 - AVPro Video version: 2.x
 - Operating system version: 
 - Device model: ipad air 4
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
An instance 0x174e3e3c0 of class AVQueuePlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x1752228c0> ( <NSKeyValueObservance 0x12f45df20: Observer: 0x12b406e20, Key path: status, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170c44dd0> <NSKeyValueObservance 0x12f7254d0: Observer: 0x1390a1b80, Key path: rate, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x174a4b3a0> <NSKeyValueObservance 0x177a49540: Observer: 0x132015e50, Key path: timeControlStatus, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170c44ef0> <NSKeyValueObservance 0x177a41860: Observer: 0x177a41320, Key path: externalPlaybackActive, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x170c45010> <NSKeyValueObservance 0x177a4f3c0: Observer: 0x177a488e0, Key path: currentItem, Options: <New: NO, Old: YES, Prior: NO> Context: 0x0, Property: 0x170c45100> )

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @killsoon 

Could you please provide a description of your issue?

**Comment by MorrisRH** [comment]
Could you also provide the following:
- specific version of AVPro Video (e.g. 2.1.4),
- specific version Xcode used to build the project (e.g. 12.4)
- specific version of iOS on the device you're using (e.g. 14.4)

**Comment by killsoon** [comment]
AVPro Video version: 2.1.3
Xcode version: 12.5
ios version: 10.1.1

**Comment by MorrisRH** [comment]
I'm a bit confused as the iPad Air (4th gen) comes with iOS 14. Also...
* At what point does the crash occur?
* Are you playing a specific video when it happens?

I'm unable to reproduce this in any of our tests so any further information you can provide would go along way in helping us to find what is causing this issue.

**Comment by killsoon** [comment]
sorry, device model is iPad 4,1  
1、it occurs when launch game
2、no

**Comment by MorrisRH** [comment]
I'm afraid the iPad 4 isn't supported by AVPro Video 2.x as hardware that supports the Metal rendering API is required.
We are investigating the cause of the crash though, although currently we can't reproduce it.

**Comment by killsoon** [comment]
ok，thx

**Comment by MorrisRH** [comment]
Unable to reproduce on an iPhone 5c running iOS 10.3.4 using Unity 2018.4.36f1 and AVPro Video 2.1.7.
