### ISSUE TITLE
Demo UI

### ISSUE THREAD

**Issue by mrtnRitter** [RenderHeads/UnityPlugin-AVProVideo#825]
I'm looking for this Unity UI demo project of AVProVideo:
https://www.renderheads.com/content/docs/AVProVideo/articles/usage-demos.html#media-player-ui-demo

Expected a link to a download or something. Maybe I'm just stupid...

Thank you!

**Comment by kahnivore** [comment]
Hi @mrtnRitter 

You're probably not stupid ;). No separate download required - it ships with the package. Once you've imported AVPro Video you can find it in your project under Assets > AVProVideo > Demos > Scenes. 

Hope that helps!

**Comment by mrtnRitter** [comment]
Hi @kahnivore , 
I've seen the other demos but somehow missed this particular scene. 

Thank you very much!
