### ISSUE TITLE
Preview AVPro Video in-editor (without going into Play mode)

### ISSUE THREAD

**Issue by M4Eelements** [RenderHeads/UnityPlugin-AVProVideo#826]
**Question**
Hello!

I was wondering if it was possible to preview a single video frame (not even necessarily play the video itself) in the scene view or game view, without going into play mode?
My use case for this is that I'm trying to adjust the scale of the video contents according to its surroundings but currently, I have to go into play mode to see the content, adjust the scale and then go back out of play mode and re-do adjustments since they don't get saved in-between steps which makes for a lot of back & forth.

Thanks for any help on this matter!!

P.S.: My apologies if this was asked before, I did my best to find an answer but no luck!

**Comment by kahnivore** [comment]
Hi @M4Eelements 

You could write an editor script that takes the texture from the render preview in the MediaPlayer inspector and assigns it to the DefaultTexture slot of your display component (make sure 'No Default Display' is unticked).

Does this help?

**Comment by M4Eelements** [comment]
Hey @kahnivore , Thanks for the quick reply!

What you said made sense, but I couldn't make it work.
When you said to take the "texture from the render preview", are you referring to the `_previewTexture` variable from the custom editor `MediaPlayerEditor_Player.cs`? (see image below)

![avpro_image](https://user-images.githubusercontent.com/86266353/122985428-2d9b1900-d36c-11eb-92f3-1700b06761a2.png)

If so, how can I get hold of it, since it's a private variable?

Also, what are you referring to when you mentioned `DefaultTexture`? I found it in AVPro's `Apply To Mesh` component, but there is no "No Default Display" check box.
Or are you referring to the Shader's `_MainTexture`?

Thanks again!

**Comment by M4Eelements** [comment]
Nevermind, I managed to make it work! I don't know if this is what you were talking about, but I'll leave the code here:
```C#
[CustomEditor(typeof (Billboarding))]
public class VideoPreviewEditor: UnityEditor.Editor {
  private Billboarding _billboarding;
  private MediaPlayer _mediaPlayer;
  private Material _material;
  private Texture _initialTexture;

  private void OnEnable() {
    _billboarding = target as Billboarding;
    _mediaPlayer = _billboarding.GetComponent < MediaPlayer > ();
    _material = _billboarding.GetComponent < Renderer > ().sharedMaterial;
    _initialTexture = _material.GetTexture("_MainTex");
  }

  public override void OnInspectorGUI() {
    base.OnInspectorGUI();
    if (_mediaPlayer.TextureProducer != null) {
      ITextureProducer textureSource = _mediaPlayer.TextureProducer;
      Texture texture = textureSource.GetTexture(0);
      if (texture != null) {
        _material.SetTexture("_MainTex", texture);
      }
    }
  }

  private void OnDisable() {
    _material.SetTexture("_MainTex", _initialTexture);
  }
}
```
