### ISSUE TITLE
How to know type of 360 stereoscopic video?

### ISSUE THREAD

**Issue by TaysonKR** [RenderHeads/UnityPlugin-AVProVideo#833]
**Describe the issue**
I was developing HMD 360 movie player by user can any 360 video to play. (maximum 8k)
But, I don't want to use a AVPro Auto Stereo Detection feature.
How can I know stereo packing type from any 360 video? (like topbottom, side by side)

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.3f1
 - AVPro Video version: 2.1.0 trial version
 - Operating system version: Windows 10 21H2
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 6k, 30fps, mp4, 500mb ~ 600mb

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hey @TaysonKR 

Once the video is prepared and ready to play you could use:

`StereoPacking videoStereoPacking = _mediaPlayer.TextureProducer.GetTextureStereoPacking();`

Does that help?

**Comment by TaysonKR** [comment]
Thank you for your reply.
Editor works that code. But, build apk push to HMD then not working.
I setting Android Platform video API is Android.VideoApi.ExoPlayer...
So... I think there is no clue using by avpro...
My opinion is create buttons to set stereo packing type by manualy click or getting type from video file name.

**Comment by kahnivore** [comment]
@TaysonKR could you test this in your app with the stereo video included in the AVPro Video sample videos please?

**Comment by TaysonKR** [comment]
@kahnivore I already do that.. but everything is same. Debug.Log to show the StereoPackingType. but, it's always same result "None".

**Comment by kahnivore** [comment]
@TaysonKR when are you calling _mediaPlayer.TextureProducer.GetTextureStereoPacking();? The call will only work if the video has been loaded and is ready to play.

**Comment by TaysonKR** [comment]
@kahnivore I called that when MediaPlayerEvent.EventType.ReadyToPlay event. and... This is worked on Windows(Editor), but Android platform not working...

**Comment by kahnivore** [comment]
Is there a chance you could send the video in question to unitysupport@renderheads.com please so we could test it?

**Comment by TaysonKR** [comment]
Ok. I will.

**Comment by TaysonKR** [comment]
Um... this problem may my platform is Android on HMD?

**Comment by kahnivore** [comment]
@TaysonKR did you ever send us a video to test with? Have you tried any other Android devices?

**Comment by TaysonKR** [comment]
my boss OK to make UI for user can choose stereo scopic type. thank you for support!
