### ISSUE TITLE
WebGL m3u8 plays for a few seconds then freezes

### ISSUE THREAD

**Issue by dplanz** [RenderHeads/UnityPlugin-AVProVideo#835]
When trying to play a stream using AVPro w/ hls.js, it loads the videos in the first manifest, but doesnt seem to update to get the new stream information and freezes. I have the loop setting checked and the persistant setting unchecked. it works fine in the debugger but when i build the webgl it does this.

![image](https://user-images.githubusercontent.com/2752146/123463344-67ad2a80-d5b9-11eb-9e2b-6c0b655e5550.png)

**Comment by dplanz** [comment]
AVPro Video - Core Edition 2.1.5

**Comment by kahnivore** [comment]
Would it be possible to send a stream over to unitysupport@renderheads.com?
