### ISSUE TITLE
Error：Loading failed. File not found, codec not supported

### ISSUE THREAD

**Issue by XuDaFei** [RenderHeads/UnityPlugin-AVProVideo#836]
**Describe the issue**
We use AVProVideo as our video playback plug-in for our game, its a awesome plug and we use it to play some mv in our game
 without a hitch.
Everything seems to be ok on our test machine. But after we push our game to players, we got some error report and cant not found out why it happens. Its doesnt like what report in errors log .
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
RenderHeads.Media.AVProVideo.MediaPlayer.UpdateErrors()
RenderHeads.Media.AVProVideo.MediaPlayer.Update()

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.35f1
 - AVPro Video version: 2.1.3
 - Operating system version: Android/IOS(10,13,14,15)
 - Device model: iPhone6s-iPhone12 or low to high Android Phone(Different kinds of machines，both Android and IOS has this error)
 - Video specs (resolution, frame-rate, codec, file size): 1080P, 24fps, mp4, 13M

**To Reproduce**
load prefab include Mediaplayer and DisplayUGUI
use OpenMedia(MediaPathType pathType, string path, bool autoPlay = true) to load mv form  Local storage
use CloseMedia() and destory the prefab
Is it some call timing problem that causes this error ？
Or just that the machine is out of memory

**Logs**
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
RenderHeads.Media.AVProVideo.MediaPlayer.UpdateErrors()
RenderHeads.Media.AVProVideo.MediaPlayer.Update()

or：
[AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
RenderHeads.Media.AVProVideo.MediaPlayer.UpdateErrors()
RenderHeads.Media.AVProVideo.MediaPlayer.Update()
RenderHeads.Media.AVProVideo.MediaPlayer.OnDisable()
RenderHeads.Media.AVProVideo.MediaPlayer.AllPlayersDispose()
RenderHeads.Media.AVProVideo.MediaPlayer.OnApplicationQuit()

**Comment by kahnivore** [comment]
Hi @XuDaFei 

Would it be possible to send some sample media to unitysupport@renderheads.com please? 

What is your test machine? 

Do you know at which point these players get these errors? Is it when a particular video starts?

**Comment by XuDaFei** [comment]
We tested most of the popular mobile phones on the market, but we didn't find any problems  about AVProVideo.
This seems to be an occasional problem. We want to know why this error may be caused, It will helpful
We only use AVProVideo to  play 1080P MP4 video in the game,  and There is no detailed context so we also didnt know this erro happends in which point or video.
And Thank a lot !!

**Comment by kahnivore** [comment]
This is simply a generic error thrown if AVPro cannot play the video that it has been set to play. This could be because the file is not found or because various details about the video are unsupported by the platform or hardware. We can help diagnose why a specific video is not playing on a specific platform/device, but it's impossible to say in a general way, because there could be a lot of different reasons.

**Comment by AndrewRH** [comment]
@XuDaFei we have a FAQ about why videos won't play:
https://www.renderheads.com/content/docs/AVProVideo/articles/faq.html

For Android/iOS it would be great if we could get the log as there may be some clues in there why it's failing sometimes / on some devices...

It may also be worthwhile upgrading to the latest version of AVPro Video (2.1.5)

Thanks,

**Comment by XuDaFei** [comment]
Thanks for your response！！
Here's a more verbose log~


`
<html>
<body>


02219 E ExoPlayerImplInternal: Caused by: com.google.android.exoplr2avp.h.i$a: Decoder init failed: c2.qti.avc.decoder, Format(1, null, null, video/avc, avc1.640020, -1, null, [750, 1624, 23.976023], [-1, -1])
--
106-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1018)
206-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.E(MediaCodecRenderer.java:578)
306-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1420)
406-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.video.f.a(MediaCodecVideoRenderer.java:694)
506-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.d(MediaCodecRenderer.java:965)
606-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:811)
706-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.n.m(ExoPlayerImplInternal.java:947)
806-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.n.handleMessage(ExoPlayerImplInternal.java:477)
906-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: ... 3 more
1006-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CodecException: start failed
1106-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at android.media.MediaCodec.native_start(Native Method)
1206-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at android.media.MediaCodec.start(MediaCodec.java:2235)
1306-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.m.a(SynchronousMediaCodecAdapter.java:66)
1406-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1113)
1506-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1011)
1606-28 22:08:39.012 19582 2219 E ExoPlayerImplInternal: ... 10 more
1706-28 22:08:39.014 19582 2261 I VideoBox: VideoBox::~VideoBox
1806-28 22:08:39.014 19582 2271 I hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
1906-28 22:08:39.020 19582 19685 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
2006-28 22:08:39.025 19582 19685 I System.out: AVProVideo error MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640020, -1, null, [750, 1624, 23.976023], [-1, -1]), format_supported=YES
2106-28 22:08:39.041 19582 19685 E Unity : [AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.
2206-28 22:08:39.041 19582 19685 E Unity : RenderHeads.Media.AVProVideo.MediaPlayer:UpdateErrors()
2306-28 22:08:39.041 19582 19685 E Unity : RenderHeads.Media.AVProVideo.MediaPlayer:Update()
2406-28 22:08:39.041 19582 19685 E Unity :
2506-28 22:08:39.041 19582 19685 E Unity : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
2606-28 22:08:39.041 19582 19685 E Unity :


</body>
</html>` 
report by XiaoMi 11   Android 11,level 30

`
<html>
<body>


10806-29 10:18:35.328 32627 32734 I AVProVideo: Video Loading: jar\|zip\|obb
--
10906-29 10:18:35.348 32627 3485 D MediaCodecInfo: AssumedSupport [sizeAndRate.rotated, 750x1624x23.976022720336914] [OMX.qcom.video.decoder.avc, video/avc] [PD1415A, vivo X6A, vivo, 21]
11006-29 10:18:35.348 32627 3485 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640020, video/avc] [OMX.google.h264.decoder, video/avc] [PD1415A, vivo X6A, vivo, 21]
11106-29 10:18:35.348 32627 3485 D MediaCodecInfo: AssumedSupport [sizeAndRate.rotated, 750x1624x23.976022720336914] [OMX.qcom.video.decoder.avc, video/avc] [PD1415A, vivo X6A, vivo, 21]
11206-29 10:18:35.348 32627 3485 D MediaCodecInfo: AssumedSupport [sizeAndRate.rotated, 750x1624x23.976022720336914] [OMX.qcom.video.decoder.avc, video/avc] [PD1415A, vivo X6A, vivo, 21]
11306-29 10:18:35.348 32627 3485 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640020, video/avc] [OMX.google.h264.decoder, video/avc] [PD1415A, vivo X6A, vivo, 21]
11406-29 10:18:35.348 32627 3485 D MediaCodecInfo: AssumedSupport [sizeAndRate.rotated, 750x1624x23.976022720336914] [OMX.qcom.video.decoder.avc, video/avc] [PD1415A, vivo X6A, vivo, 21]
11506-29 10:18:35.358 32627 3485 D MediaCodecInfo: AssumedSupport [sizeAndRate.rotated, 750x1624x23.976022720336914] [OMX.qcom.video.decoder.avc, video/avc] [PD1415A, vivo X6A, vivo, 21]
11606-29 10:18:35.358 32627 3485 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640020, video/avc] [OMX.google.h264.decoder, video/avc] [PD1415A, vivo X6A, vivo, 21]
11706-29 10:18:35.358 32627 3493 I OMXClient: Using client-side OMX mux.
11806-29 10:18:35.358 32627 3493 W ACodec : Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
11906-29 10:18:35.358 32627 3493 E ACodec : Unable to instantiate codec 'OMX.qcom.video.decoder.avc'.
12006-29 10:18:35.358 32627 3493 E ACodec : signalError(omxError 0x80001003, internalError -2147483648)
12106-29 10:18:35.358 32627 3492 E MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
12206-29 10:18:35.358 32627 3485 W MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
12306-29 10:18:35.358 32627 3485 W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
12406-29 10:18:35.368 32627 3485 W MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc
12506-29 10:18:35.368 32627 3485 W MediaCodecRenderer: java.lang.IllegalArgumentException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffffe
12606-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at android.media.MediaCodec.native_setup(Native Method)
12706-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at android.media.MediaCodec.<init>(MediaCodec.java:486)
12806-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
12906-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1097)
13006-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1011)
13106-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.h.i.E(MediaCodecRenderer.java:578)
13206-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1420)
13306-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.video.f.a(MediaCodecVideoRenderer.java:694)
13406-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.h.i.d(MediaCodecRenderer.java:965)
13506-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:811)
13606-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.n.m(ExoPlayerImplInternal.java:947)
13706-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at com.google.android.exoplr2avp.n.handleMessage(ExoPlayerImplInternal.java:477)
13806-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at android.os.Handler.dispatchMessage(Handler.java:98)
13906-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at android.os.Looper.loop(Looper.java:135)
14006-29 10:18:35.368 32627 3485 W MediaCodecRenderer: at android.os.HandlerThread.run(HandlerThread.java:61)
14106-29 10:18:35.368 32627 3485 D MediaCodecInfo: AssumedSupport [sizeAndRate.rotated, 750x1624x23.976022720336914] [OMX.qcom.video.decoder.avc, video/avc] [PD1415A, vivo X6A, vivo, 21]
14206-29 10:18:35.368 32627 3485 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.640020, video/avc] [OMX.google.h264.decoder, video/avc] [PD1415A, vivo X6A, vivo, 21]
14306-29 10:18:35.368 32627 3485 D MediaCodecInfo: AssumedSupport [sizeAndRate.rotated, 750x1624x23.976022720336914] [OMX.qcom.video.decoder.avc, video/avc] [PD1415A, vivo X6A, vivo, 21]
14406-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: Playback error
14506-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: com.google.android.exoplr2avp.k: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640020, -1, null, [750, 1624, 23.976023], [-1, -1]), format_supported=YES
14606-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.n.handleMessage(ExoPlayerImplInternal.java:554)
14706-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at android.os.Handler.dispatchMessage(Handler.java:98)
14806-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at android.os.Looper.loop(Looper.java:135)
14906-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at android.os.HandlerThread.run(HandlerThread.java:61)
15006-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: Caused by: com.google.android.exoplr2avp.h.i$a: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.640020, -1, null, [750, 1624, 23.976023], [-1, -1])
15106-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1018)
15206-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.E(MediaCodecRenderer.java:578)
15306-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1420)
15406-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.video.f.a(MediaCodecVideoRenderer.java:694)
15506-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.d(MediaCodecRenderer.java:965)
15606-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:811)
15706-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.n.m(ExoPlayerImplInternal.java:947)
15806-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.n.handleMessage(ExoPlayerImplInternal.java:477)
15906-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: ... 3 more
16006-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: Caused by: java.lang.IllegalArgumentException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffffe
16106-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at android.media.MediaCodec.native_setup(Native Method)
16206-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at android.media.MediaCodec.<init>(MediaCodec.java:486)
16306-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
16406-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1097)
16506-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: at com.google.android.exoplr2avp.h.i.a(MediaCodecRenderer.java:1011)
16606-29 10:18:35.368 32627 3485 E ExoPlayerImplInternal: ... 10 more
16706-29 10:18:35.418 32627 32734 I System.out: AVProVideo error MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640020, -1, null, [750, 1624, 23.976023], [-1, -1]), format_supported=YES
16806-29 10:18:35.428 32627 32734 E Unity : [AVProVideo] Error: Loading failed. File not found, codec not supported, video resolution too high or insufficient system resources.


</body>
</html>`
vivo X6A  Android 5.0.2 level 21

**Comment by AndrewRH** [comment]
@XuDaFei  any chance you could send us a reproducible project for this issue?

**Comment by AndrewRH** [comment]
@XuDaFei Hi, did you send us your project / video file?

Thanks,

**Comment by XuDaFei** [comment]
Sorry for the inconvenience of sending you our project. Because we have our exclusive  sdk during the loading game which is difficult to simplify by deleting asset. In addition, this project is confidentially owned. Thanks !

**Comment by AndrewRH** [comment]
> r the inconvenience of sending you our project. Because we have our exclusive sdk during the loading game which is difficult to simplify by deleting asset. In addition, this project is confidentially owned. Thanks !

Okay I understand.

Are you able to replicate the error using a empty unity project with the AVPro Video demo scene and media files?

Thanks,

**Comment by XuDaFei** [comment]
Its ok, but But the problem may not recur
I can send a project  if need !

**Comment by AndrewRH** [comment]
@XuDaFei Yes that'd be helpful

How often does this happen?  Is the issue the same on iOS as on Android?

The more details you can give us the better the chance of us being able to reproduce and fix it.

Thanks,

**Comment by XuDaFei** [comment]
@AndrewRH 
Yes, This error also happen on iOS and with similar times as on Android, the probability is about 1%.And The types of mobile phones involved are also very different, both high-performance and low-performance phones.
And It does not seem to have much impact on the player.
I have sent a simple demo, including the video we used and a similar loading process.
Hope this is helpful for you to analyze the problem, Thanks

**Comment by RenderHeadsSte** [comment]
@XuDaFei 

I have tried to replicate the issue on Android using a Xiaomi Mi 10T here with the sample project you sent.

I could not find a scene in your project other than the sample scene, and our AVPro Video demo scenes.  I used the AVPro Video MediaPlayer demo scene and set it to load your video.  It loaded and played perfectly.  Am I missing something here in trying to reproduce this issue?

How many videos do you have open when you see this issue?  Because the decoder only has a finite resource pool, and this will be different per device.

**Comment by XuDaFei** [comment]
scene is here.
And we also didnt replicate the issue, its just a simple demo that&nbsp;shows how we use avpro, and maybe you can find some bug




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RenderHeads/UnityPlugin-AVProVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RenderHeads/UnityPlugin-AVProVideo] Error：Loading failed. File not found, codec not supported (#836)





 
@XuDaFei
 
I have tried to replicate the issue on Android using a Xiaomi Mi 10T here with the sample project you sent.
 
I could not find a scene in your project other than the sample scene, and our AVPro Video demo scenes.  I used the AVPro Video MediaPlayer demo scene and set it to load your video.  It loaded and played perfectly.  Am I missing something here in trying to reproduce this issue?
 
How many videos do you have open when you see this issue?  Because the decoder only has a finite resource pool, and this will be different per device.

**Comment by RenderHeadsSte** [comment]
Scene is where sorry?

I am afraid without a project that shows off the the problem, we will struggle to offer any specific solution.

**Comment by AndrewRH** [comment]
@XuDaFei  if you email files to github they will not appear - you need to email files to unitysupport@renderheads.com with this issue number #836 in the subject

Or you can log into github and attach your files to the thread, but please do not include AVPro Video in your attachment.

Thanks,
