### ISSUE TITLE
Neither RTMP nor RTSP streams play as expected

### ISSUE THREAD

**Issue by TheloTheGreat** [RenderHeads/UnityPlugin-AVProVideo#839]
On a Windows machine with LAV filters installed, and OBS Studio as a stream source, neither an RTMP local stream nor a RTSP local stream play in AVPro 2.1.5 as expected. The RTMP stream "fails to open" with an explicit error, while the RTSP stream stays stuck at the "opening" step and never displays any video, but does download video data from the stream somehow.

These same streams play fine in VLC.

*******************
For RTSP:

RTSP stream source setup:
1) Install OBS Studio: https://obsproject.com
2) Install the obs-rtspserver plugin: https://github.com/iamscottxu/obs-rtspserver/releases
3) Open OBS Studio, add a scene with any source (ex: "Window Capture"). The selected window will appear in the preview pane. Leave all settings to their defaults otherwise.
4) In OBS Studio: Tools > RTSP Server > [Start]. The RTSP stream is now running at the default URL of rtsp://localhost/live
5) To confirm that the RTSP stream is running correctly, open VLC, then Media > Open Network Stream > "rtsp://localhost/live" > [Play]. You should now see the stream from OBS.

AVPro repro setup:
1) Open the AVPro demo scene Demo_MediaPlayer.
2) Edit the MediaPlayer in that scene:
-- Media Source: Absolute path or URL: rtsp://localhost/live
-- The following results will vary depending on which video API is selected in: Platform Specific > Windows > Video API...
3) Play the scene.

Expected result: The video stream starts playing.
Actual result: The video stream does not start playing. Clicking the play button in the UI shows a quick "play button clicked" animation, but nothing else happens. The console displays the following, depending on Video API, after a long full editor freeze:

DirectShow:
[AVProVideo] Initialising AVPro Video v2.1.5 (native plugin v2.1.5f1-core) on NVIDIA GeForce GTX 1050 Ti/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor
[AVProVideo] Opening rtsp://localhost/live (offset 0) with API DirectShow

WinRT:
[AVProVideo] Initialising AVPro Video v2.1.5 (native plugin v2.1.5f1-core) on NVIDIA GeForce GTX 1050 Ti/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor
[AVProVideo] Opening rtsp://localhost/live (offset 0) with API WinRT

Media Foundation:
[AVProVideo] Initialising AVPro Video v2.1.5 (native plugin v2.1.5f1-core) on NVIDIA GeForce GTX 1050 Ti/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor
[AVProVideo] Opening rtsp://localhost/live (offset 0) with API MediaFoundation
[AVProVideo] Using playback path: MF-MediaEngine-Hardware (1280x720@30.00)

Notes: 

- In all three cases, the RTSP server in OBS does show "Total data output" increasing over time while Demo_MediaPlayer is playing, and AVPro is presumably loading the stream, but AVPro still does not actually show any video.

- When using Media Foundation, the AVPro UI does show a permanent swirling "loading" icon. When using WinRT or DirectShow, it does not.

- The results are the same regardless of these stream settings in OBS Studio:
-- Hardware encoder NVENV or software encoder x264
-- Encoder preset "Quality" or "Performance"
-- Rescale output 1280x720 or 464x260
-- Disabling all audio sources or not

- I have tried everything described here on two different machines, without any apparent difference in results.

*******************

For RTMP:

RTMP stream source setup:
1) Start with the RTSP stream source setup above in OBS Studio. Stop the RTSP server if it's running, through Tools > RTSP Server > [Stop].
2) Download rtsp-simple-server to act as the RTMP server: https://github.com/aler9/rtsp-simple-server#installation
3) Run rtsp-simple-server.exe in a command prompt. Somewhere in its output, confirm that this is displayed:
[RTMP] listener opened on :1935
4) In OBS Studio, [Settings] > Stream:
- Service: Custom
- Server: rtmp://localhost:1935
- Stream Key: "live"
- Do not check [ ] Use authentication
5) In OBS Studio: [Start Streaming]. Confirm that lines similar to the following appears in the output of rtsp-simple-server:
2021/06/29 18:13:59 I [0/0] [RTMP] [conn 127.0.0.1:52165] opened
2021/06/29 18:13:59 I [1/0] [RTMP] [conn 127.0.0.1:52165] is publishing to path 'live', 2 tracks
6) To confirm that the RTMP stream is running correctly, open VLC, then Media > Open Network Stream > "rtmp://localhost:1935/live" > [Play]. You should now see the stream from OBS.

AVPro repro setup:
1) Open the AVPro demo scene Demo_MediaPlayer.
2) Edit the MediaPlayer in that scene:
-- Media Source: Absolute path or URL: rtmp://localhost:1935/live
-- Platform Specific > Windows > Video API: DirectShow
3) Play the scene.

Expected result: The video stream starts playing.
Actual result: The video stream does not start playing. The console displays the following, ending in an error:

[AVProVideo] Initialising AVPro Video v2.1.5 (native plugin v2.1.5f1-core) on NVIDIA GeForce GTX 1050 Ti/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor
[AVProVideo] Opening rtmp://localhost:1935/live (offset 0) with API DirectShow
[AVProVideo] Failed to open rtmp://localhost:1935/live

Note: Here, rtsp-simple-server does not show any connection attempt from AVPro. (When using VLC to test, it does show the connection attempt.)

**Comment by TheloTheGreat** [comment]
As an update, this RTSP public test stream also fails to play in basically the same way, and works fine in VLC:

rtsp://demo:demo@ipvmdemo.dyndns.org:5541/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast

**Comment by TheloTheGreat** [comment]
Second update: This other RTSP public test stream _does_ work as expected:

rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream

I have no idea why that new RTSP stream works, but none of the others do. Any ideas?

**Comment by AndrewRH** [comment]
Interesting..

Can you try setting "LAV Video Decoder" in the DirectShow Windows settings for Preferred Filters?
![image](https://user-images.githubusercontent.com/5418126/123980705-a841e500-d9b9-11eb-85a0-1c8551bbea7a.png)

Then make sure the Video API is set to DirectShow.

With this setup I was able to get this stream:
rtsp://demo:demo@ipvmdemo.dyndns.org:5541/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast

to play - does it work for you?

**Comment by TheloTheGreat** [comment]
I forgot to mention it, but this whole time I did have "LAV Video Decoder" active when testing with DirectShow.

I tried that RTSP test stream again just now to see if anything changed, but same results: it works in VLC but does not work in AVPro ("Failed to open").

**Comment by kahnivore** [comment]
@TheloTheGreat any word on this? a similar issue regarding m3u8 was mentioned on the forums if you wanted to detail it here.
