### ISSUE TITLE
VideoPlayer can't play RTSP On Windows UnityEditor and Android

### ISSUE THREAD

**Issue by ppengotsu** [RenderHeads/UnityPlugin-AVProVideo#84]
**Describe the bug**
I can't play RTSP Movie on Windows UnityEditor and Android.
I can play local movie file.
RTSP Server is TouchDesigner

VLC Player on iPhone can play RTSP Movie 
This iPhone is same network as RTSP Server PC
PC's firewall is off.

**Your Setup (please complete the following information):**
 - Unity version: 2018.2.21f1
 - AVPro Video version: 1.9.17
 - Operating system version: Windows10
 - Device model: Alieanware 
 - Video specs (resolution, frame-rate, codec, file size): RTSP Movie(1920x1080)

**To Reproduce**
1. "Mediplayer" And "Apply To Material" Add To PlaneObject
2. "MediaPlayer" And "Apply To Material" link config
3. "rtsp://192.168.1.64:4554/asdf" input Source Path
4. Unity Play

**Logs**

```
[AVProVideo] Failed to open rtsp://192.168.1.64:4554/asdf
UnityEngine.Debug:LogError(Object, Object)
RenderHeads.Media.AVProVideo.MediaPlayer:OpenVideoFromFile() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:906)
RenderHeads.Media.AVProVideo.MediaPlayer:Start() (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:520)

```

**Videos**
rtsp://192.168.1.64:4554/asdf

**Comment by AndrewRH** [comment]
RTSP is not a protocol that AVPro Video strongly supports.  On Windows it isn't really supported, only in some special cases.  On Android, it might be supported but there are a few things you have to do:

1) Change the video API from ExoPlayer to MediaPlayer (in Platform Specific > Android section)
2) Make sure you set the internet permission in player settings to Required

Does that help?

**Comment by ppengotsu** [comment]
Thank you.

I completed the above two tasks.
But, I cloud not play RTSP Movie On Android Device..

Do you have other things to play RTSP movie ?

**Comment by AndrewRH** [comment]
I'm afraid not...We'll keep this open as a feature request

**Comment by RenderHeadsSte** [comment]
@ppengotsu We have made some improvements in the ExoPlayer API path with respect to playback of RTMP and RTSP..  Whilst we are still not officially supporting these protocols, RTMP should playback in most to all cases, and RTSP should playback in some cases.  This will be available in version >= 1.9.18.

**Comment by aliahmad11403** [comment]
Is there any chance that you guys have planned to support this? RTSP Protocol with android.

**Comment by dpradell360** [comment]
it's supported now.

**Comment by ppengotsu** [comment]
@dpradell360 
Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
