### ISSUE TITLE
Transparent Videos overlay generates artefacts

### ISSUE THREAD

**Issue by technsmile** [RenderHeads/UnityPlugin-AVProVideo#840]
**Describe the issue**
Artefacts appears while overlapping 2 x 360 videos 

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.1
 - AVPro Video version: 2.1.3
 - Operating system version: 10 Latest
 - Device model: PC (Works in editor), Oculus Quest 2 (Shows artefacts)
 - Video specs (resolution, frame-rate, codec, file size): 
   > Skybox Video : 360 stereo video H265 5760 x 5760, 738 Mo (problem appears with all videos tested)
   > Sphere Video : 360 video alpha packed H265 5760 x 5670, 483 ko

**To Reproduce**
1. Use background video on a skybox
2. Use transition video on a sphere
3. Play both on Oculus Quest 2
4. Artefacts appear on playing and remain over time

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**
![20210630-082937](https://user-images.githubusercontent.com/22969357/123913122-254f6900-d97e-11eb-8a41-269adac94e0c.jpg)

**Videos**

https://user-images.githubusercontent.com/22969357/123913894-0d2c1980-d97f-11eb-8abd-27234979cdb6.mp4

If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Are you using OES shader?

If so, please try the shader attached to this thread as it may fix your issue:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/780

Also please try upgrading to the latest version of AVPro Video (2.1.5)

Thanks,

**Comment by technsmile** [comment]
Hello Andrew,

Thank you for coming back to me with tips.

We do not use OES Shader because we do not have performance issues.

The AVPro Video has been updated to latest version but problem remains.

Actually we use AlphaPacking as suggested per the doc.
We can move from AlphaPacking to a codec that supports transparency.
On Oculus Quest 2, do you know such codec / movie file format ?

Have a good day.
