### ISSUE TITLE
Seamlessly loop a large video

### ISSUE THREAD

**Issue by Barbelot** [RenderHeads/UnityPlugin-AVProVideo#841]
**Describe the issue**
Hello,

I am trying to seamlessly loop a large video file with resolution 4654x1080 and duration around 5 minutes.

I tried using an H264 codec. The playback is fine, however their is a short freeze/stutter every time the video loop back to the beginning.
To avoid this I tried using an HAP codec but the hap video files are not reading properly. I get no image and a lagging sound with a 10 sec extract of my video in HAP. If I try to load the whole video in HAPQ the editor crashes with the attached error log below.

What would be the best option to read this video in a seamlessly looping manner ? 
Would it be possible in H264 ?
If not, would it be possible in HAP ? Do I need to encode HAP in a specific way to get it working ? Will the big file size not be an issue ?

Thanks for your help

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.12f1
 - AVPro Video version: Ultra edition 2.1.5
 - Operating system version: Windows 10 Home, 64 bit, DirectX 12.0
 - Device model: Gaming laptop with i7-9750H CPU, 16Go RAM, GPU Nvidia GeForce RTX 2060
 - Video specs (resolution, frame-rate, codec, file size): 4654x1080, 50f/s, H264 or HAP, 723Mo in H264, between 25 and 50Go in HAP

**To Reproduce**
1. 
2. 
3. 

**Logs**
Log of the crash when opening the large HAPQ video : [error.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6740007/error.log)

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @Barbelot 

The best way would be to optimise your video by encoding with all keyframes. See the note in our docs about it [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-seeking-playbackrate.html#optimal-encoding). This should allow your video to loop/seek seamlessly.

**Comment by kahnivore** [comment]
Regarding HAP, please see [this page](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-hap-codec.html) for details regarding encoding and platform specifics. Let us know if you need further help with this.

**Comment by Barbelot** [comment]
Hello,

Thank you for your answer. I tried re-encoding my video using the command line from the docs [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-seeking-playbackrate.html#optimal-encoding) but I still get a stutter when the video loops.

Reading the doc about the HAP codec you say the video resolution should be a multiple of 4. Does this mean I cannot use this codec if my desired resolution is not a multiple of 4 ?

Thanks for your help.

**Comment by Barbelot** [comment]
To update on HAP, I managed to get the HAP playing by changing the resolution to be a multiple of 4 but it it starts lagging after a few seconds of playback as my disk usage and gpu usage get to 100%.

**Comment by AndrewRH** [comment]
Hi,

I'm surprised Hap playback causes high GPU usage.  Disk usage I can understand...

Does your video contain an audio track (even a silent one)?  Audio track can cause looping problems...

Another option may be to try using HEVC encoding...

I'm not sure what else to suggest at this point...

**Comment by kahnivore** [comment]
Which video API are you using? This resolution is quite high for h.264 so HEVC is a good option in that regard.

**Comment by Barbelot** [comment]
Yes my video contains an audio track. I am using the Media Foundation API.

I tried encoding my video in HEVC but I get the same stutter when looping. It also degrades the image quality even when I put the highest bitrate possible in Premiere (25 Mb/s).

**Comment by kahnivore** [comment]
Could you send the original video to unitysupport@renderheads.com please?

**Comment by Barbelot** [comment]
Sure, I mailed you a link to the original H264 video.
Thank you for your help.

**Comment by AndrewRH** [comment]
Thanks we'll take a look

**Comment by kahnivore** [comment]
Hi @Barbelot 

Sorry for the delay on this - finally had a chance to look at this video. 

I solved the slow seeking problem by using the following FFmpeg command (as linked in our docs above):

`ffmpeg -hide_banner -y -i input.mp4 -pix_fmt yuv420p -c:v libx264 -crf 18 -tune fastdecode -x264-params "keyint=1" output-h264.mp4`

As for the loop, this doesn't seem to be a playback problem - but rather the video frames don't match up to loop correctly which makes it look like a stutter. Take a look at the first and last frames and note that they don't match up. You'll notice this behaviour is the same when looped in 3rd party players such as Windows Media Player etc. 

![firstframe](https://user-images.githubusercontent.com/44468274/124902361-2407e700-dfe3-11eb-9c0d-9c1c0671a19e.png)
![lastframe](https://user-images.githubusercontent.com/44468274/124902438-37b34d80-dfe3-11eb-9f1a-cc22e819038d.png)

**Comment by Barbelot** [comment]
Hello,

Thank you for your answer. I noticed the frames of the video where not
perfectly looping but I still had a stutter in AVPro that I did not see in
other software.
Could you send me the video you used and what API you used in AVPro so I
can try it in my setup ?

Have a nice day,
Benoit

**Comment by kahnivore** [comment]
Sent you the all-keyframes video. Please note this won't fix the loop - you will need to edit the video itself in order to make it loop smoothly.
