### ISSUE TITLE
Unity Editor Hard Crashes when URL entered as Streaming path

### ISSUE THREAD

**Issue by FABuster** [RenderHeads/UnityPlugin-AVProVideo#843]
**Describe the issue**
The Unity Editor will hard crash if the Media Source is set to Path Relative to Streaming Assets Folder and your path is a URL (ie, includes "http" etc).

NOTE: I'm aware there is a warning in the inspector when you have the wrong type of path assigned.  This was missed by us originally as we were assigning the path by code.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.1
 - AVPro Video version: tested in both 2.1.5 Trial and bought version 2.0.10
 - Operating system version: OSX Big Sur 11.2.3 (tested on Windows, no crash there and just error with invalid path [good!])
 - Device model: 2018 15" MacBook Pro
 - Video specs (resolution, frame-rate, codec, file size): unsure, they're all streaming paths.  but we tried these ones for reference:

https://rh-testmedia.s3-eu-west-1.amazonaws.com/Samples/BigBuckBunny-360p30-H264.mp4
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8
http://amssamples.streaming.mediaservices.windows.net/634cd01c-6822-4630-8444-8dd6279f94c6/CaminandesLlamaDrama4K.ism/manifest(format=m3u8-aapl)

**To Reproduce**
1. Open clean Unity project, install AVPro
2. In MediaPlayer, set source to Path and Relative to Streaming Assets Folder, then put any URL into the text field.
3. Play Editor, it will hard crash the moment it tries to load the video.

**Logs**
If applicable, add error logs to help explain your problem.
[AVPro Unity Editor Hard Crash.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6745073/AVPro.Unity.Editor.Hard.Crash.txt)

**Screenshots**
![Screen Shot 2021-07-01 at 12 39 00 pm](https://user-images.githubusercontent.com/86697224/124057827-915bcb00-da6b-11eb-91af-1d27f22541e0.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by FABuster** [comment]
Hi.  We just discovered that it looks to be caused by having spaces in your folder path.  I have spaces in my project's application path, but a co-worker on OSX does not and didn't get the hard crash.  Window is fine either way (spaces or not)

**Comment by MorrisRH** [comment]
Reproduced and fixed. The fix will be in the next release (2.1.6).

**Comment by AndrewRH** [comment]
2.1.6 has been released with this fix - please let us know if you have any further issues
