### ISSUE TITLE
Several videos at the same time in scene dontt open

### ISSUE THREAD

**Issue by Angellourido** [RenderHeads/UnityPlugin-AVProVideo#844]
**Describe the issue**
I'm creating a unity experience with 10 360 videos 6k stereo in the same scene  for oculus quest 2 so when I try to open them I take a black screen

**Your Setup (please complete the following information):**
 - Unity version: 2020.13
 - AVPro Video version: core androide version
 - Operating system version: android
 - Device model: oculus ques 2
 - Video specs (resolution, frame-rate, codec, file size): 
 - videos 6k stereo 30 ou 60fps 1.40 Go each

**To Reproduce**
1. i put the files in the QUEST2/..... / com.XXX.yy / files/Movies/videos360
2. I lunch the apk
3. the scene have the spheres when you click in the spheres the videos dont load on ly black screen

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @Angellourido 

Having 10 6k videos playing at once in a single scene would be very taxing on memory and performance. This is probably a limitation of the hardware. Could you try with fewer videos to confirm? If so you'll need to optimise this scene by downscaling the videos.

**Comment by Angellourido** [comment]
The videos are not playing at the same time , they are in the scene at the same time but I try to play one and is black 
I f I have only one sphere so it works

Angel Lourido
Eclox
Tlf. +33 6 31 38 94 03
***@***.***

eclox.net




De : kahnivore
Envoyé le :jeudi 1 juillet 2021 12:04
À : RenderHeads/UnityPlugin-AVProVideo
Cc : Angellourido; Mention
Objet :Re: [RenderHeads/UnityPlugin-AVProVideo] Several videos at the sametime in scene dontt open (#844)

Hi @Angellourido
Having 10 6k videos playing at once in a single scene would be very taxing on memory and performance. This is probably a limitation of the hardware. Could you try with fewer videos to confirm? If so you'll need to optimise this scene by downscaling the videos.

**Comment by kahnivore** [comment]
Could you please send one of the videos that isn't playing over to unitysupport@renderheads.com? 

Are they playing in the editor?

**Comment by Angellourido** [comment]
In the editor there is no problem 

The only thing is that I have a core android license and in the editor it shows the watermark 


Get Outlook for Android

**Comment by RenderHeadsSte** [comment]
Can you post a logcat output please?

**Comment by Angellourido** [comment]
I just find the solution for this issue.

The problem was a bad path when I changed the name of the project.

But I have a issue with the quality of the pictures. I have videos 6k3d and when I watch the videos directly with the Oculus TV app are good but when I watch the videos with the apk avpro it's bad quality.

The videos are located in the headset so  it should be good 


Get Outlook for Android

**Comment by RenderHeadsSte** [comment]
What version of AVPro Video are you using?  Are you using OES mode?

**Comment by Angellourido** [comment]
La version c’est 2.1.5. Android core edition 
    	
    	Téléchargez Outlook pour iOS
    
  
 De : Ste Butcher ***@***.***>Envoyé : vendredi, juillet 2, 2021 3:20 PMÀ : RenderHeads/UnityPlugin-AVProVideoCc : Angellourido; MentionObjet : Re: [RenderHeads/UnityPlugin-AVProVideo] Several videos at the same time in scene dontt open (#844) 
What version of AVPro Video are you using?  Are you using OES mode?

**Comment by AndrewRH** [comment]
>  But I have a issue with the quality of the pictures. I have videos 6k3d and when I watch the videos directly with the Oculus TV app are good but when I watch the videos with the apk avpro it's bad quality. The videos are located in the headset so  it should be good

Could you provide screenshots for comparison?

**Comment by Angellourido** [comment]
This is one of the videos I put in the unity proyect  is locate in the headset oculus quest 2
So the questio is how to configure the AVpro for to have the best quality. The second question is. If its posible to put the videos in the folder Movies of the oculus quest and not in the androide apk videos folder.


ormat                    : MPEG-4
Format profile            : Base Media
File size                 : 1.40 GiB
Duration                  : 2 min 0 s
Overall bit rate          : 100 Mb/s
Encoded date              : UTC 2021-05-16 11:58:45
Tagged date               : UTC 2021-05-16 11:58:45

Video
ID                        : 1
Format                    : HEVC
Format/Info               : High Efficiency Video Coding
Format profile            : Main
Format level              : 6.1
Format tier               : High
Codec ID                  : hvc1
Duration                  : 2 min 0 s
Bit rate                  : 96.4 Mb/s
Width                     : 5 760 pixels
Height                    : 5 760 pixels
Display aspect ratio      : 1.000
Frame rate mode           : Constant
Frame rate                : 60.000 FPS
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Bits/(Pixel*Frame)        : 0.048
Stream size               : 1.35 GiB (96%)
Encoded date              : UTC 2021-05-16 11:58:45
Tagged date               : UTC 2021-05-16 11:58:45
Color range               : Limited
Color primaries           : BT.709
Transfer characteristics  : BT.709
Matrix coefficients       : BT.709
Codec configuration box   : hvcC

Angel Lourido
Eclox
Tlf. +33 6 31 38 94 03
***@***.***

eclox.net




De : Andrew
Envoyé le :vendredi 2 juillet 2021 19:38
À : RenderHeads/UnityPlugin-AVProVideo
Cc : Angellourido; Mention
Objet :Re: [RenderHeads/UnityPlugin-AVProVideo] Several videos at the sametime in scene dontt open (#844)

But I have a issue with the quality of the pictures. I have videos 6k3d and when I watch the videos directly with the Oculus TV app are good but when I watch the videos with the apk avpro it's bad quality. The videos are located in the headset so  it should be good
Could you provide screenshots for comparison?

**Comment by kahnivore** [comment]
Hey @Angellourido 

Are you still having trouble with picture quality? It's difficult to know what to recommend because it could be caused by a variety of things. If you like, you could send one of the videos to unitysupport@renderheads.com and we could help figure it out.

**Comment by Angellourido** [comment]
Problem description:

with the new update to 2.2.0 my stereo videos dont play correctly there is a problem its like its play one eye un the other one out of sync

Device (which devices are you having the issue with - model, OS version number):

oculus quest 2 

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):

MPEG-4 (Base Media): 1.40 GiB, 2 min 0 s
1 Video stream: HEVC.  96.4 Mb/s, 5760*5760 (1.000), at 60.000 FPS, HEVC (Main)  Overall bit rate: 100 Mb/s


System Information:

AVPro Video: v2.2.0 (plugin v2.2.0f1-trial)
Target Platform: Android
Unity: v2021.1.18f1 WindowsEditor
OS: Desktop - GL702VI (ASUSTeK COMPUTER INC.) - Windows 10  (10.0.19043) 64bit - French
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz - 8 threads - 16342KB
GPU: NVIDIA GeForce GTX 1080 - NVIDIA - Direct3D 11.0 [level 11.1] - 8079KB - 16384


Angel Lourido
Tlf. +33 6 31 38 94 03
***@***.***
eclox.net

real emotions



De : Andrew
Envoyé le :vendredi 2 juillet 2021 19:38
À : RenderHeads/UnityPlugin-AVProVideo
Cc : Angellourido; Mention
Objet :Re: [RenderHeads/UnityPlugin-AVProVideo] Several videos at the sametime in scene dontt open (#844)

But I have a issue with the quality of the pictures. I have videos 6k3d and when I watch the videos directly with the Oculus TV app are good but when I watch the videos with the apk avpro it's bad quality. The videos are located in the headset so  it should be good
Could you provide screenshots for comparison?

**Comment by AndrewRH** [comment]
Hi,

This issue is closed.  It's confusing to add new problems to existing issues - please create a new issue so we can investigate your new problem.

Thanks,
