### ISSUE TITLE
AVPro doesn't work with Unity Device Simulator v3

### ISSUE THREAD

**Issue by ImmotionPeterL** [RenderHeads/UnityPlugin-AVProVideo#845]
Opening a new issue because I think this requires attention and being fixed - and might be different cause from the closed issue. I was having issues playing any video with v2.1.5 of the Ultra version. Investigating I found this issue report: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/690#issuecomment-872105644

Trying to fix the issue, I've descovered that Device Simulator v3 returns the SystemInfo.graphicsDeviceType as the device being simulated, however earlier versions of Device Simulator return Direct3D11 (for me on Windows).

I'm now using v2.2.4 of Device Simulator so that I can carry on using it and have AVPro work. Moving on though, it's not viable to remain on this old version, and hope AVPro can be updated to work with the latest vesrions of Device Simulator.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.12 (doesn't matter though)
 - Device Simulator version: v3.0.1
 - AVPro Video version: 2.1.5
 - Operating system version: Windows 10 (10.0.19041)
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): Reproducible with the included demo videos

**To Reproduce**
1. Open the device simulator
2. iPhone XR and Google XL were used to test
3. Attempt to run a video in one of the demo scenes
4. Observe error in console

**Comment by AndrewRH** [comment]
Yes we have replicated this.   

It seems that Device Simulator 3.0.0-Preview changes the graphics API returned from SystemInfo

You can disable this by disabling the SystemInfo overrrides:

![image](https://user-images.githubusercontent.com/5418126/124489846-575f3180-dda9-11eb-917c-2c9b94cd7232.png)

We have no way to detect whether Device Simulator is running, and this package is still in Preview so it's not really a feature we can support yet.

I hope this helps
