### ISSUE TITLE
[iOS] Failure to set execute permissions on the plugin binary when AVPro is packaged

### ISSUE THREAD

**Issue by midiphony** [RenderHeads/UnityPlugin-AVProVideo#846]
**When AVPro is packaged and put in the Packages folder, Unity fails to give the actual path of the iOS plugin framework. Therefore, AVPro doesn't set the execute permission on the plugin binary.**

 - Unity version: 2020.2.6f1
 - AVPro Video version: 2.1.4
 - Operating system version: macOS BigSur

______________________________________________

Steps to reproduce :
- Make AVProVideo as a package (everything inside one folder, with a package.json) and put it in the Packages folder 
- If the AVProVideo package folder is under other folders (for example, Packages/Externals/[AVProPackageFolder]), the following error is logged :

[AVProVideo] Failed to set execute permissions on the plugin binary, error: chmod: Packages/[AVProPackageFolderName]/Runtime/Plugins/iOS/AVProVideo.framework/AVProVideo: No such file or directory

______________________________________________

**Potential fix**

We added that to PostProcessBuild_iOS to fix the issue on our side :
```

		// Helper to set the file execute bits
		private static void SetFileExecutePermission(string path)
		{
			// CUSTOM FIX (the Unity relative path of the framework is not valid)
			// For example, Unity returns Packages/com.company.avpro instead of Packages/Externals/com.company.avpro...
			path = Path.GetFullPath(path);
```

**Comment by MorrisRH** [comment]
This was changed with version 2.1.5 to fix up the plugin in the generated Xcode project instead.

**Comment by kahnivore** [comment]
@midiphony please let us know if upgrading fixes the issue for you.

**Comment by midiphony** [comment]
It does fix the issue :)
Thanks.
