### ISSUE TITLE
The Android platform is slow when loading large local video files

### ISSUE THREAD

**Issue by 3493000** [RenderHeads/UnityPlugin-AVProVideo#848]
**Describe the issue**
When the Android platform plays a video with a relatively large file size in the SD card, it will be loaded tens of seconds before it can be played. Is there any way to play the video quickly

 - Unity version: 2020.1.6
 - Operating system version: android 11
 - Device model: huawei mate30
 - Video specs (resolution, frame-rate, codec, file size): 3GSize  .mkv

**Comment by AndrewRH** [comment]
Is the file included in your StreamingAssets folder?

If it is then it will be slow to load because the file has to be uncompressed before playback can begin.

We recommend storing large video files not in StreamingAssets, but instead downloading it from somewhere to: https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html

**Comment by 3493000** [comment]
The file is not included in my StreamingAssets folder，It's in the storage directory of my phone
，If I open hundreds of megabytes of video files in the same directory, it will be faster.

**Comment by 3493000** [comment]
![image](https://user-images.githubusercontent.com/43593494/124532090-68a84c80-de42-11eb-9d65-1161bb6c993c.png)
![image](https://user-images.githubusercontent.com/43593494/124532361-f3894700-de42-11eb-8d46-744d9038dd29.png)

When I open this 3.93GB movie, the speed is very slow, it takes half a minute

**Comment by 3493000** [comment]
The opening method I use is:
 MediaPlayer.FileLocation m_Loc = MediaPlayer.FileLocation.AbsolutePathOrURL;
m_Player.OpenVideoFromFile(m_Loc, m_VideoModel.Path, false);

**Comment by 3493000** [comment]
Similarly, I use the same API to open the same relatively large movie stored in the C drive location under the Unity editor, which is also very slow.

**Comment by 3493000** [comment]
已解决，打开前我调用了MD5方法导致时间慢，不是你们的原因。
