### ISSUE TITLE
Demo scene fails to build for the Android Platform due to 64K limit

### ISSUE THREAD

**Issue by knightcube** [RenderHeads/UnityPlugin-AVProVideo#851]
**Describe the issue**
I was trying to use the AVPro Video Free Trial Plugin for one of my projects but each time I try to build the apk for my Android phone the build fails. As soon as I remove the plugin from the project, I don't face any problems with the build.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.0f1
 - AVPro Video version: v2.1.5
 - Operating system version: Windows 10

**To Reproduce**
1. Download the Free Trial Unity package from [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases) 
2. Try building one of the demo scenes for Android Platform
3. Build fails due to the 64K method limit in Unity

**Logs**
D8: Cannot fit requested classes in a single dex file.

**Comment by AndrewRH** [comment]
There's a solution proposed here which may solve your issue:
https://stackoverflow.com/questions/62223356/d8-cannot-fit-requested-classes-in-a-single-dex-file

**Comment by knightcube** [comment]
Yeah I had checked this out earlier. The thing is enabling multidex will lead to increased build times as well as increased app size which I am trying to avoid. Was just wondering if there is a better solution available?

**Comment by kahnivore** [comment]
Hey @knightcube 

What else is in your project? If you remove something other than AVPro does it work?

Have you tried upgrading to a later version of Unity? The .0 releases tend to have a lot more bugs than the others.

**Comment by knightcube** [comment]
@kahnivore  Sorry for the late reply. There are some other bulky assets and plugins. I tried out enabling multidex and it works fine in Unity 2020.
