### ISSUE TITLE
[2.1.5] Does not work with Quest2

### ISSUE THREAD

**Issue by cevanno** [RenderHeads/UnityPlugin-AVProVideo#854]
**Describe the issue**
The AVPro materials are not rendering in a Quest2 but they work fine in Unity editor.  

**Your Setup (please complete the following information):**
 - Unity version: 2021.1.13
 - AVPro Video version: Trial 2.1.5
 - Operating system version: Windows 10 H2
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
Install the Oculus Integration and then the AVPro Trial.

I need to play a 360 video in Quest2. Your docs say quest2 is supported but as soon as I replace the MainCamera with the OVRCameraRig in the Hierarchy, all the avp materials seem to stop working. To reproduce something similar, open your Demo_DisplayComponents and replace the MainCamera with OVRCameraRig and you see the skybox texture disappear and the cube turns black. Just to verify this is confined to AVP, I added a new 3d object (sphere) with the standard shader and made it blue and this appears in the quest and appears alongside the black avp cube where the materials don't work in quest. 

To reproduce the skybox error I have  a video player object with both the unity native video player and the AVP media player on it.  Enabling one or the other (never both) I have proven the native player works but AVPro does not while in the same project. 
 The avp Apply To Material will show the Default Texture but does not play the video that plays in the media player.  The material uses the avpro skybox sphere shader.
For the native video player I set it to play to a render texture and create a skybox material using the built in Skybox/panoramic shader.

Surprisingly, all these tests work fine in Editor play but not in the quest2. Can you point me to documentation or a demo that works?

**Logs**
There are no errors in editor so the logs don't matter.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by imsumittyagi** [comment]
Hi, I am also working on quest2 and 360 8K Video, and my video works fine, It may be the Unity version issue Unity 2021 is quite new have you tested it with Unity 2020 and lower?

**Comment by AndrewRH** [comment]
@cevanno could you send us a scene that is set up to show this issue please?  unitysupport@renderheads.com with this issue number (854) in the topic.  Then we will be able to investigate this faster.

Thanks,

**Comment by kahnivore** [comment]
@cevanno are you still experiencing this issue?

**Comment by RenderHeadsSte** [comment]
@cevanno did you solve this issue or are you still requiring support from us?

**Comment by RenderHeadsSte** [comment]
Closing due to lack of response
