### ISSUE TITLE
ios cannot play video

### ISSUE THREAD

**Issue by 3023992558** [RenderHeads/UnityPlugin-AVProVideo#856]
**Describe the issue**
ios cannot play video. the error message:
[Player] failed to load key playable, error: Cannot Open

**Your Setup (please complete the following information):**
 - Unity version: unity2018.4.26f1
 - AVPro Video version: v2.1.5
 - Operating system version: ios14.0.1
 - Device model: iphone x
 - Video specs (resolution, frame-rate, codec, file size): 
326 * 720 mp4 aac

**Comment by MorrisRH** [comment]
From the error message I can see the player is unable to open the file or URL that is being passed in. Where are you trying to play the file from? On iOS you can only playback videos from the Streaming Assets folder or via http.

**Comment by 3023992558** [comment]
[AVProVideo] Opening /private/var/containers/Bundle/Application/E8A98CB4-3DF0-4EE3-AABD-04EA210680DC/gmmx_innertest.app/Data/Raw/58f0e57eb90c4a1a363b773b181c90b5.ast  

this is my video path. it's in streamingAssetsPath

**Comment by 3023992558** [comment]
[AVProVideo] Opening /private/var/containers/Bundle/Application/E8A98CB4-3DF0-4EE3-AABD-04EA210680DC/gmmx_innertest.app/Data/Raw/58f0e57eb90c4a1a363b773b181c90b5.ast  

this is my video path. it's in streamingAssetsPath

**Comment by MorrisRH** [comment]
The extension ".ast" won't be being recognised, it needs to be mp4 for an mp4 video file.

**Comment by 3023992558** [comment]
ok, thanks. i'll try it.

**Comment by 3023992558** [comment]
it's work. thanks!!!
