### ISSUE TITLE
iOS turn Ring/Silent mode on or off on your iPhone  the audio is abnormal

### ISSUE THREAD

**Issue by zhuxianzhiniko** [RenderHeads/UnityPlugin-AVProVideo#857]
**Describe the issue**
Switching to Ring mode is also silent.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.16f
 - AVPro Video version: 2.1.0
 - Operating system version: IOS 14
 - Device model: iphone 12
 - Video specs (resolution, frame-rate, codec, file size): 
 720P, 30FPS, mp4, 60M

**To Reproduce**
1. Play a video
2. Switch Ring/Silent mode

PS：If you don't switch the Ring/Silent mode, the video will play normally and the sound will be normal.

**Comment by MorrisRH** [comment]
If you want the video's audio to be heard when the device is in silent mode you will need to change the ```AVAudioSession``` category to ```AVAudioSessionCategoryPlayback``` (see here: https://developer.apple.com/documentation/avfaudio/avaudiosession/category).
We do not modify the audio session within the plugin, so you will need to add some native code in order to do this, an example of how to do this can be found here: https://forum.unity.com/threads/setting-mediaplayback-audio-session-category.206958/#post-1396250

**Comment by MorrisRH** [comment]
Actually that's not the best resource as it's a bit dated.
Here's some scripts you can just drop into your project. Just attach ```ZZZSetAudioSessionCategory``` to a game object and change ```Audio Session Category``` to ```Playback```.

[ZZZSetAudioSessionCategory.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6790880/ZZZSetAudioSessionCategory.zip)

**Comment by zhuxianzhiniko** [comment]
> Actually that's not the best resource as it's a bit dated.
> Here's some scripts you can just drop into your project. Just attach `ZZZSetAudioSessionCategory` to a game object and change `Audio Session Category` to `Playback`.
> 
> [ZZZSetAudioSessionCategory.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6790904/ZZZSetAudioSessionCategory.zip)

Thanks for the reply, I will give it a try.

**Comment by kahnivore** [comment]
@zhuxianzhiniko let us know if you come right

**Comment by zhuxianzhiniko** [comment]
> @zhuxianzhiniko let us know if you come right

Sorry, I forgot to reply, AVPro Video is already working normally.

**Comment by demetio-tungvt1** [comment]
> zhuxianzhiniko

hello, I try with IOS 14, 16, and Unity 2020.3 LTS but not work, do you have any specific setting with xCode?

**Comment by demetio-tungvt1** [comment]
> In the Xcode project built by Unity, find and open the file `UnityAppController.mm`.
> 
> Find the the following line (it's at line 134 for me):
> 
> ```objc
> AVAudioSession *audioSession = [AVAudioSession sharedInstance];
> ```
> 
> add the following two lines after it:
> 
> ```objc
> [audioSession setCategory:AVAudioSessionCategoryPlayback error:nil];
> [audioSession setActive:YES error:nil];
> ```
> 
> This will put the audio session into the playback category which will keep audio playing when silent mode is activated.

Thank you so much for the reply, I tested and it worked. but by this way , the file UnityAppController.mm only gen after build xcode, it means for each build, we need modify that file. I think we should control from unity,  Do you have any suggestion? Thanks

**Comment by demetio-tungvt1** [comment]
> In the Xcode project built by Unity, find and open the file `UnityAppController.mm`.
> 
> Find the the following line (it's at line 134 for me):
> 
> ```objc
> AVAudioSession *audioSession = [AVAudioSession sharedInstance];
> ```
> 
> add the following two lines after it:
> 
> ```objc
> [audioSession setCategory:AVAudioSessionCategoryPlayback error:nil];
> [audioSession setActive:YES error:nil];
> ```
> 
> This will put the audio session into the playback category which will keep audio playing when silent mode is activated.

I found the solution, I used your zip file above, then I delay the method call native after Start() then it worked. Thank you so much.

**Comment by LeifHalvorsen** [comment]
> I found the solution, I used your zip file above, then I delay the method call native after Start() then it worked. Thank you so much.

I'm having the same problem. Can you elaborate on what "delay the method call native after Start() " means?

**Comment by ReetiMauryaCrest** [comment]
> I found the solution, I used your zip file above, then I delay the method call native after Start() then it worked. Thank you so much.

Can you explain it a little? I am having a issue where music doesn't work on the first try when iPhone is on silent mode, but starts working on second try.
