### ISSUE TITLE
Cannot get the right audio channel count and output to Unity

### ISSUE THREAD

**Issue by cross6180** [RenderHeads/UnityPlugin-AVProVideo#858]
**Problem description**
Playing in the original Demo_MediaPlayer scene without any changes, the audio seems not output to unity.
The channel number gets from mediaPlayer.Control.GetAudioChannelCount() in AudioOutputManager.cs line 51 always returns 0 and thus did NOT run all the codes below it and cannot get the right audio data from AVPro.
Please help with this issue, thank you.

**Your Setup (please complete the following information):**
 - Unity version:  v2019.4.10f1 WindowsEditor
 - AVPro Video: v2.1.5 (plugin v2.1.5f1-trial)
 - Target Platform: Standalone
 - OS: Desktop - Z97M-D3H (Gigabyte Technology Co., Ltd.) - Windows 10  (10.0.0) 64bit - English
 - CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz - 8 threads - 16286KB
 - GPU: NVIDIA GeForce GTX 980 - NVIDIA - Direct3D 11.0 [level 11.1] - 4053KB - 16384
 - Video specs (resolution, frame-rate, codec, file size): Just the sample video in the trial package, RenderHeads-1080p30-H264

**Screenshots**
![image](https://user-images.githubusercontent.com/12931387/125019968-8546bd80-e0aa-11eb-8fab-f11887cc6844.png)

**Comment by AndrewRH** [comment]
Hmm I can't reproduce that.

Here's how it looks for me:

![image](https://user-images.githubusercontent.com/5418126/125059311-14e86e00-e0a3-11eb-819f-66855bc92d90.png)

Things to check: 
1) the console window to make sure the plugin version numbers are correct
2) that your audio output device isn't set up strangely

I'm not sure what else to suggest, that's very strange...perhaps you could try it on another system too?

Thanks,

**Comment by cross6180** [comment]
Thank you, Andrew. Here are my console and audio settings screenshots. 
Still don't have any luck making it works. I will try another system later.
![image](https://user-images.githubusercontent.com/12931387/125080395-5571d700-e0f7-11eb-9a2e-88328c09584e.png)
![image](https://user-images.githubusercontent.com/12931387/125080486-6de1f180-e0f7-11eb-9d49-299ae1fe9f99.png)

**Comment by cross6180** [comment]
Hi Andrew,
I just test this on another PC, which works perfectly fine.
Probably there is some problem with the audio output device setup with my last PC. I'll try to figure it out.
Thanks so much for your help.

**Comment by kahnivore** [comment]
@cross6180 thanks for letting us know
