### ISSUE TITLE
Can not play color4:4:4 video on NVIDIA RTX4000 with AVPro

### ISSUE THREAD

**Issue by keitasumiya** [RenderHeads/UnityPlugin-AVProVideo#86]
**Describe the bug**
I can not play a 8K color4:4:4 video fluently on windows UnityEditor via AVPro. 

- First of all, I tried to play my 8K color4:4:4 video on windows UnityEditor via AVPro but it didn't work and a white board was just displayed. 
- Therefore, I installed [LAVFilters](https://github.com/Nevcairiel/LAVFilters) to my windows PC. 
- After installing LAVFilters, 8K color4:4:4 video was displayed in windows UnityEditor via AVPro but it's not fluent. 

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.1f1
 - AVPro Video version: 1.9.17
 - Operating system version: Windows 10 pro
 - Device model: 
   - desktop pc 
   - intel xeon E5-2680 v4
   - memory 128GB
   - GPU: NVIDIA RTX4000
 - Video specs (resolution, frame-rate, codec, file size): 
   - mp4
   - color4:4:4
   - H265
   - 8K
   - 60fps
   - 168MB/60sec

**To Reproduce**
1. open "04_Demo_uGUi.unity"
2. select "AVPro Media Player"
3. select "BROWSE" to change a video
4. select my video (8K-60fps-60sec-h265-444.mp4)
5. select "Platform Specific" 
6. select "Windows" 
7. select "Direct Show" at Preferred Video API
8. Unity Play

**Logs**

**Screenshots**

**Videos**
https://youtu.be/6pLY7FxKmwY

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
We had some chats over email about this, so i'll paste them here as it may be of interest to others:

Hi Keita Sumiya,

Thanks for getting in touch with us.

Wow 8K 4:4:4 is very high.  

I would have expected the Media Foundation API to play the video and use GPU decoding.  DirectShow can play it (using LAV) but it will only be using CPU decoding, so it isn't the optimal.  You could try to encode the video using a "-tune fastdecode" option in FFMPEG to try to make it play back smoother.

We don't have an RTX 4000, and we have not tested this video format before.

Perhaps you could try a few things to work out what the problem is.  Try:

1) Changing to 4:2:0
2) Changing to 30fps
3) Changing to a lower bit-rate
4) Update GPU driver
5) Disable on-board GPU (Intel) if there is one

Let me know how this goes.

Thanks,

**Comment by AndrewRH** [comment]
Hi Andrew,

Thank you so much  for your reply. 

As you suggested, 
I tried as follows: 
0) remaked a video with "-tune fastdecode"  (= 8K 60fps h265 color444 fastdecode)
NG: The video were able to play but it's not fluent. 

1) Changing to 4:2:0 (= 8K 60fps h265 color420)
OK: The video were played fluently. 

2) Changing to 30fps (= 8K 30fps h265 color444)
NG: The video were able to play but it's not fluent. 

3) Changing to a lower bit-rate
I am sorry. I didn't understand the way to try this suggestion. 

4) Update GPU driver (= 8K 60fps h265 color444)
NG: 
I updated GPU drive as follows: 
OLD: 425.31-quadro-desktop-notebook-win10-64bit-international-whql.exe
NEW: 431.02-quadro-desktop-notebook-win10-64bit-international-whql.exe
After that, the video were able to play but it's not fluent. 

5) Disable on-board GPU (Intel) if there is one

NG: 

I set GPU settings in NVIDIA control panel forcing to use the RTX4000. 
Moreover, I watched the GPU using via task manager and I checked that RTX4000 only was used in Unity app actually. 
After that, the video were able to play but it's not fluent. 

----

Best regards,
Keita Sumiya

**Comment by AndrewRH** [comment]
Hi Keita,

Thanks for getting in touch.

I guess 4:4:4 8K60 might just not be possible to play back smoothly.  Even if the GPU can handle it, Unity itself adds extra overheads......

There are a few other things you could try:
1) Make sure to run the EXCLUSIVE fullscreen setting (in Player Settings), as this will give you full usage of the GPU
2) Make sure in Nvidia driver settings, the performance option is set to Maximum Performance

What I meant by "change to a lower bit-rate", is that when you encode the video, you can set the quality level. This affects the file size of the video.
You can usually specify this as a bitrate (in Mbps or MB/s format) value, or as a CRF value.  Using a lower value might help the decoder to process the video quicker.

I'm all out of ideas.   I hope this has helped you.

**Comment by keitasumiya** [comment]
Hi AndrewRH,

I am so sorry for my late reply. 

I tried your two suggestions but it wasn't improved: 
https://www.youtube.com/watch?v=rr1Czs00ULE&feature=youtu.be

Especially, for your second advice, 
I set up as follows:
global settings of Manage 3D settings in NVIDIA control panel:
- CUDA - GPUs - All
- OpenGL rendering GPU - Quadro RTX 4000
- Antialiasing FXAA - Off
- Antialiasing gamma - Off
- Antialiasing Transparency - Off
- Antialiasing Mode - Off
- Antialiasing Setting - control by an application
- Ambient oculusion - performance
- Exported pixel type - color index overlay (8bpp)
- Enable overlay - off
- Shader Cache - On
- Stereo - swap eye - off
- Stereo - display mode - on board DIN connector
- Stereo - enable - off
- Threaded Optimization - On 
- Triple Buffering - Off
- buffer flip mode - auto select
- Maximum pre-rendered frames - 4
- multi fralme sampling AA (MFAA) - off
- refresh rate - control by applicaytion
- Vertical Sync - Off
- Anisotropic Filtering - control by applicaytion
- Power Management Mode - Prefer Maximum Performance


Moreover, I picked up a fact that Video Decode in task manager is 0% while I had played the builded app made by Unity and AVPro with 8K video. Is this no problem? I thought that my builded app doesn't use GPU to decode the 8K video and it is the problem. 

I would appreciate it if I could get that reply from you.

Best regards, 
Keita

**Comment by fingerx** [comment]
Very useful information. Looking forward to avpro 2.0 hap optimization release.
