### ISSUE TITLE
Scaling portrait orientation uGUI display on Android

### ISSUE THREAD

**Issue by ReallyRad** [RenderHeads/UnityPlugin-AVProVideo#861]
The scaling to fit mode of uGUI doesn't work properly when building to Android. It is stuck to a landscape format scaling.
It works fine in "stretch to fill" mode, so can do for now, but that was a pain to figure out.

 - Unity version: 2020.1.16f1
 - AVPro Video version: 2.15 trial version
 - Operating system version: windows 10
 - Device model: Samsung Galaxy s8
 - Video specs: 608x1080@30, mp4 format

**To Reproduce**
1. Open demo display components scene. Set game window in some portrait format.
2. adjust uGUI display transform to stretch with 0 margin
3. load a portrait format video instead of the default landscape one
4. Set "Scale to Fit" mode

This is in the editor
![image](https://user-images.githubusercontent.com/996367/125496731-a616790d-6f58-4669-bb15-c93be86ef41a.png)

This is on the device
![image](https://user-images.githubusercontent.com/996367/125496867-d8048548-9492-42cd-a9e6-95f20388be31.png)

Thanks!

**Comment by ReallyRad** [comment]
Actually, the problem persists in "stretch to fill" mode. I think the issue is with avpro/android  not parsing properly the video dimensions. I am actually working with videos from mobile phones, and some appear to have a  1:1 aspect ratio although they are in portrait mode

for instance :

![image](https://user-images.githubusercontent.com/996367/125616298-d551b97f-77ad-458f-8076-2d165272bd13.png)

It is unclear to me why it's processed differently in the editor than on the phone.

**Comment by AndrewRH** [comment]
@kahnivore are you able to get / recreate a scene showing this issue?  If so then you pass it on to @RenderHeadsSte  to investigate

@ReallyRad if you could send us your project or a cut down reproducible scene that would really help us to solve this issue.  Please send to unitysupport@renderheads.com  

I suspect this is because the video has rotation metadata...We do have some sample media with the different rotations that can be used to test this.

Thanks,

**Comment by kahnivore** [comment]
https://user-images.githubusercontent.com/44468274/126820930-39230746-1729-40b8-8d78-4be1f05b385c.MOV

Hi @ReallyRad 

The attached video is a test using ExoPlayer, it seems to behave as expected. 

Some questions:

1. Could you send a screenshot of your 'Resolution and Presentation' Player settings page?
2. Do you have 'Lock Orientation' enabled or disabled on your device?
3. Could you perhaps send your video so we can test it? To unitysupport@renderheads.com with the subject line #861. Suspect your issue might have something to do with the rotation metadata so a video would help us verify this. 

Thanks!

**Comment by kahnivore** [comment]
Closing this issue as we haven't heard back. Feel free to reopen if the problem persists.
