### ISSUE TITLE
AES-128 HLS playback with overrideDecryptionKey doesn't work on Android

### ISSUE THREAD

**Issue by NigelMorgan** [RenderHeads/UnityPlugin-AVProVideo#862]
Using overrideDecryptionKey for decrypting a AES-128 HLS video on Android doesn't playback video. No errors reported.

Trying to provide offline HLS AES-128 playback of local video file on Android. Using Trial version (I was told it's full functionally, just with the renderheads logo watermark)

Setup:

Unity version: 2019.1.11f1
AVPro Video version: AVPro Video v2.1.6
Operating system version: Windows 10.

Reproduce:

1. Use ffmpeg to create a HLS video. No encryption. Same video plays back correctly on Windows & on Android device.
2. Use ffmpeg to create an encrypted HLS video. Set overrideDecryptionKey for both platforms. Plays back correctly on Windows (thanks to https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/850). On Android nothing plays & no error messages are reported.

Same encrypted video on both platforms.

I'm setting the encryption password with this code:

private void SetAVProDecryptionPassword(string password)
{
	Library.Logging.Assert(mediaPlayer != null, "Error: MediaPlayer is null");
        Library.Logger.Log("Setting AVPro password to " + password);						// TODO remove this
	
	// Set the decryption password for each platform.
	byte[] passwordBytes = Encoding.ASCII.GetBytes(password);
	mediaPlayer.PlatformOptionsWindows.keyAuth.overrideDecryptionKey = passwordBytes;
	mediaPlayer.PlatformOptionsAndroid.keyAuth.overrideDecryptionKey = passwordBytes;
	mediaPlayer.PlatformOptionsIOS.keyAuth.overrideDecryptionKey = passwordBytes;
}

I have set the Android Specific Video API to Exo Player like the docs mention.

Any suggestions on what I might be doing wrong? or is this a bug like I suspect?

**Comment by kahnivore** [comment]
Hey @NigelMorgan 

Would it be possible for you to share your video with us? You can send to unitysupport@renderheads.com. 

Thanks!

**Comment by AndrewRH** [comment]
@NigelMorgan Thanks for bringing this to our attention.

We need to update the documentation to make it clearer that the ```overrideDecriptionKey``` feature isn't currently supported on Android.  

@RenderHeadsSte any idea whether this is something we can support and i can make a feature request for this?

Thanks,

**Comment by NigelMorgan** [comment]
Any plans to add support this? Seems you have done 99% of the work without the 1 final step. ie android online HLS AES-128 playback is supported, but offline playback isn't.

**Comment by RenderHeadsSte** [comment]
Last time I investigated being able to support this, we could not on Android.  I will make this an enhancement in case this changes in the future.

**Comment by NigelMorgan** [comment]
ok, cheers.

**Comment by Rex-121** [comment]
> Last time I investigated being able to support this, we could not on Android. I will make this an enhancement in case this changes in the future.
> 
> Sorry about that, it bugs me too! :/

Need this feature too.

**Comment by RenderHeadsSte** [comment]
There is now a possibility we might be able to support this for offline playback. Can you email over a video/details as a test use case? Send it to unitysupport@renderheads.com and put #862 in the subject line.

**Comment by Rex-121** [comment]
@RenderHeadsSte 
I'm able to send you a video next week.

Actually I want iOS can do the same way(playback local decryption .m3u8 file), do we have a plan to support in the feature?

And Your product is amazing!

Unity version: 2020.3.21(lts)
AVPro Video version: AVPro Video Ultra
Operating system version: iOS, Android
