### ISSUE TITLE
Can I rotate the sphere onto which my 360 video is being projected?

### ISSUE THREAD

**Issue by Nikkhil16** [RenderHeads/UnityPlugin-AVProVideo#864]
I just started with development in Unity. I need to build a 360 video player that is capable of playing an 8k video and a friend pointed me to this plugin. 

Can I rotate the sphere onto which my 360 video is being projected, so that the user gets a feeling of 'turning' in the world?

**Comment by kahnivore** [comment]
Hey @Nikkhil16 

In case you haven't found it already, we offer a free trial of our plugin (find the latest [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases)) so you can test your use-case. You could have a look at the Demo_360 seen and build on that. 

No reason why you couldn't rotate the sphere. 

Let us know if that answers your question.
