### ISSUE TITLE
Add option to disable keyboard shortcuts in MediaPlayerUI

### ISSUE THREAD

**Issue by athreatt07** [RenderHeads/UnityPlugin-AVProVideo#866]
I have the mixed reality toolkit installed because this project will be deployed to the HoloLens2.   
I am currently playing around with the demo scene and have added object manipulator, near interaction grabbable and the collider scripts to interact with the video player.  
I cant use them in play mode because the spacebar is programmed to start and stop the movie.  How can I get the mixed reality controls working with this player

**Comment by AndrewRH** [comment]
The MediaPlayer UI is just one of the demos and not a core part of AVPRo Video.   You're free to take it and change it as you need.

In your case you can comment out lines 808-840 in MediaPlayerUI.cs and this will remove all the keyboard shortcuts.  We will make this a selectable option in the component in the next release.

Does that help?

Thanks,

**Comment by athreatt07** [comment]
Thanks :)

**Comment by athreatt07** [comment]
Hi Andrew

What do I have to do to make this work with mixed reality inputs?

Kind Regards,

Alicia Threatt
ID: 216198027
B Computer Science <https://www.deakin.edu.au/current-students/courses/course.php?course=S306&year=2016>

**Comment by kahnivore** [comment]
Hi @athreatt07,

What are you struggling to make work exactly?

**Comment by athreatt07** [comment]
I would like to know a checklist of what needs to be done to make this video plugin work with HoloLens


  1.  Make all the buttons / slider HoloLens interactable objects.
  2.  comment out lines 808-840 in MediaPlayerUI.cs

Is there anything else that I need to do to make this plugin work for the HoloLens?

Kind Regards,

Alicia Threatt
ID: 216198027
B Computer Science <https://www.deakin.edu.au/current-students/courses/course.php?course=S306&year=2016>

**Comment by athreatt07** [comment]
Thanks

Sent from my iPhone

On 25 Jul 2021, at 12:32 am, Andrew ***@***.***> wrote:

﻿

Closed #866<https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/866>.
