### ISSUE TITLE
XCode iOS Crash: dyld: Library not loaded: @rpath/AVProVideo.framework/AVProVideo

### ISSUE THREAD

**Issue by JayKrikey** [RenderHeads/UnityPlugin-AVProVideo#869]
Hi,

We have recently purchased AVPro Core Edition and followed the steps mentioned in the troubleshoot documentation, however, as soon as the XCode build completes and the app launches, we are seeing an immediate crash with the following error:
**dyld: Library not loaded: @rpath/AVProVideo.framework/AVProVideo**

**Crash screenshot:**
<img width="1680" alt="Crash" src="https://user-images.githubusercontent.com/42521944/126251219-dbe12257-21a0-4833-9968-9c24c8437e8d.png">

**Troubleshoot Documentation:** https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html

**Here are the steps:**
1. Fresh Install of AVPro Core Edition version **2.1.6**

2. Install the plugin at the default factory directory
![AVProPath](https://user-images.githubusercontent.com/42521944/126250337-fae5ff3d-ac36-4ee6-a5d6-059efb1852f8.png)

3. Check **AVProVideo.framework** is set to **Embed & Sign** in the **Frameworks, Libraries and Embedded** Content section of the General pane for the Unity-iPhone. This was already set.
**Note:** The AVProVideo folder on the left pane is showing as red, so I assume there is an issue with finding the plugin
<img width="1680" alt="Screenshot" src="https://user-images.githubusercontent.com/42521944/126250088-9f0ae909-cbfa-4d8f-a046-3d108da19fe3.png">

We have attempting to reimport the plugin from scratch with same results. Any help would be appreciated, thanks!

**Comment by MorrisRH** [comment]
It looks like the UnityFramework is trying to load AVProVideo.framework, make sure AVProVideo.framework is set to "Do Not Embed" under the UnityFramework target in Xcode.

Can you provide the output from Unity's console when making the build, the PostProcessBuild_iOS script is quite verbose so we should be able to see if it is running correctly.

It would also be good to know the versions of Unity and Xcode you are using so we can try to figure out why things aren't working correctly for you.

**Comment by JayKrikey** [comment]
@MorrisRH This issue was unrelated to AVPro and it has been resolved internally, thank you.

**Comment by Rex-121** [comment]
> @MorrisRH This issue was unrelated to AVPro and it has been resolved internally, thank you.

I got the same issue, how do you solve this problem? Thank you.

**Comment by MorrisRH** [comment]
@Rex-121 please read our documentation [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html#troubleshooting)

I'm curious as to why it happens so if you can provide some details that would be great:
* Unity version
* AVPro Video version
* Xcode version
* Did you relocate the plugin within your project? If so, to where

**Comment by Rex-121** [comment]
* Unity version
  2020.3.15f1c1

* AVPro Video version
  UnityPlugin-AVProVideo-v2.2.0-Trial

* Xcode version
  Xcode 13.0

* Did you relocate the plugin within your project? If so, to where
  Yes, but I create a new project without relocate the plugin, still went wrong.

<img width="1205" alt="截屏2021-09-29 下午5 07 55" src="https://user-images.githubusercontent.com/16833393/135243942-1048acbd-d7a6-4aa1-92dd-ff20f7ce2dac.png">

<img width="1205" alt="截屏2021-09-29 下午5 07 45" src="https://user-images.githubusercontent.com/16833393/135243969-c78d09c0-3c89-4806-baf9-f382026fd68e.png">


I’m trying to integrating Unity into native iOS/Android applications following the [doc](https://docs.unity3d.com/Manual/UnityasaLibrary-iOS.html) that unity provided. 


 Error loading /var/containers/Bundle/Application/74C3BD61-D1C3-44F2-A7BF-C658CAFC9954/NativeiOSApp.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/74C3BD61-D1C3-44F2-A7BF-C658CAFC9954/NativeiOSApp.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/AVProVideo.framework/AVProVideo
  Referenced from: /private/var/containers/Bundle/Application/74C3BD61-D1C3-44F2-A7BF-C658CAFC9954/NativeiOSApp.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found

**Comment by MorrisRH** [comment]
@Rex-121 I think you'll need to make the AVProVideo.framework "Embed & Sign" in your NativeiOSApp target (you may need to add it first).
This isn't something we can account for in our post-process script as we just don't know what your target is if you're not using the default Unity-iPhone target.
If this works for you then let us know and we'll update the documentation accordingly.

**Comment by Rex-121** [comment]
@MorrisRH Thanks! Now it works just fine for me on iOS Platform.
I'm trying to embed the project as a framework which generated by Unity into my origin project.
Here is the solution you just said.
![截屏2021-10-01 上午11 05 40](https://user-images.githubusercontent.com/16833393/135560374-cb10be9d-678a-488c-be4c-387db76c6148.png)
Don't forget to delete the AVProVideo.framework in BuildPhase.Link-Binary-With-Libraries Section.

**Comment by RojanStha** [comment]
How did you added the AVProVideo.framework on NativeIOSApp?? in my case this is not showing on the frameworks, libraries and embedded content section. please let me know the solution it would be appreciated thanks.

**Comment by RojanStha** [comment]
> @MorrisRH This issue was unrelated to AVPro and it has been resolved internally, thank you.

How did you solved this problem? help will be appreciated
