### ISSUE TITLE
Request video url with header

### ISSUE THREAD

**Issue by syedali1621** [RenderHeads/UnityPlugin-AVProVideo#87]
My videos are stored on AWS S3 bucket with security. To access my videos i need to send request with header can anyone please let me know how can i send request to my video with my secret header using avprovideoplayer unity ?

**Comment by RenderHeadsSte** [comment]
Thanks for getting in touch.  Whilst sending request headers is something we partially support (see platform list below), playing directly out of an AWS S3 bucket is something we have not tried.

To send send the data you will need to use the following 'open' function call:

bool OpenVideoFromFile(string path, long offset, string httpHeaderJson, uint sourceSamplerate = 0, uint sourceChannels = 0, int forceFileFormat = 0)

This can be used as follows:  MediaPlayer.Control.OpenVideoFromFile(...)

The header information (httpHeaderJson) is structured as JSON data pairs.  For example:

{
   "param1": "hello",
   "param2": "world"
}

Do let us know how you get on, and if we can help further.


Currently supported platform list:

Apple platforms: yes
Android MediaPlayer API path: yes
Android ExoPlayer API path: no (adding support is being looked into currently)
Windows: no

**Comment by syedali1621** [comment]
i tried different ways in avpro simple controller script but it is not working and also this below function is not available. can you please share example code so i can better understand how to call video with header in avpro player ?
Thank you
MediaPlayer.Control.OpenVideoFromFile(...)

**Comment by AndrewRH** [comment]
You can also add the JSON via the UI here:

![image](https://user-images.githubusercontent.com/5418126/60083308-6710fd80-972d-11e9-94e3-8240c7e53a4c.png)

In the simpleController script you can also set this field via:

_mediaPlayer.PlatformOptionsAndroid.httpHeaderJson = myJson;
_mediaPlayer.PlatformOptionsIOS.httpHeaderJson = myJson;
_mediaPlayer.PlatformOptionsMacOSX.httpHeaderJson = myJson;

After that, any time the video URL is opened on those platforms it use your json for custom HTTP headers.

**Comment by syedali1621** [comment]
I tried to add header via UI as you mentioned but still it is not playing my video. Below is my video url and my header.

https://dahajiexknxpy.cloudfront.net/Bear.mp4
["mysupersecretheader":"MySuperSecretHeaderValue"]

**Comment by AndrewRH** [comment]
@syedali1621  which platform is this on?
Also, shouldn't the JSON be:
{ "mysupersecretheader":"MySuperSecretHeaderValue" }

**Comment by RenderHeadsSte** [comment]
As far as Android is concerned...

I have just tested your video using the header: { "mysupersecretheader":"MySuperSecretHeaderValue" }

I can playback your video on Android using the MediaPlayer API path, and also with a code fix using the ExoPlayer API path.  The fix for ExoPlayer API path will be version >= 1.9.18

**Comment by syedali1621** [comment]
yes it is playing  with header in unity for android and iphone.

Thank you

**Comment by incursion45** [comment]
Is there a solution for webGL player for requesting URL with http headers
