### ISSUE TITLE
AvPro Android 2.1.6 Watermark is not removed after buying from asset store 

### ISSUE THREAD

**Issue by hassanrazakhalid** [RenderHeads/UnityPlugin-AVProVideo#870]
**Describe the issue**
I just bought the AvPro Android and re downloaded the package. Its still in trial version.

**Your Setup (please complete the following information):**
 - Unity version: 
 - 2019.4.21f1
 - AVPro Video version: 
 - 2.1.6
 - Operating system version: 
 - windows
 - Device model: 
 - Android
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. First download trial AvPro Android 
2. Buy paid version
3. Re download asset
4. Its still in trail version

Expected: watermark should get removed after buying asset.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @hassanrazakhalid 

Have you tested this on your Android device? The Android-only version will still show the watermark on your Windows device, but it should be removed in your Android build.

**Comment by hassanrazakhalid** [comment]
Yes it is working fine on android device. Thank you.
