### ISSUE TITLE
Stalled/Unstalled events do not fire on Android when playing video off a server and the connection is cut

### ISSUE THREAD

**Issue by Ste-RH** [RenderHeads/UnityPlugin-AVProVideo#874]
- Play back a HLS video from a server
- Disable the wi-fi on the device
- Notice that no stalled event/situation occurs

I believe we need to catch this in the native plugin and pass it back up to c#.

**Comment by NoahHahm** [comment]
same problem occurs. Unusually, no events are received.

**Comment by dr-formalyst** [comment]
Same issue here. In fact, when playing on android device Stalled/Unstalled events do not fire at all, like they don't exist.

**Comment by ct21690801** [comment]
The android device Stalled/Unstalled events do not be call when the live stream connection is cut,but windows event  can be executed. the avpro version is 2.7.3

**Comment by SwenRanj** [comment]
We're noticing the exact same issue on Android devices. Reproducible by the same steps mentioned in the top message on Android only. On iOS it does work.

@Ste-RH Any updates on this issue?
We would like to use the 'stalled' event to show user feedback. Telling the user that their connectivity is gone for example. 
Any other ways we could realize this feature?

**Comment by ct21690801** [comment]
> We're noticing the exact same issue on Android devices. Reproducible by the same steps mentioned in the top message on Android only. On iOS it does work.
> 
> @Ste-RH Any updates on this issue? We would like to use the 'stalled' event to show user feedback. Telling the user that their connectivity is gone for example. Any other ways we could realize this feature?

the code could be help to you;
 private int _textureFrameCount = 0;
        private float _stallDetectionTimer;
        private int _stallDetectionGuard;
		private void CheckStreamingStall(){
		float STALL_DETECTION_DURATION = 0.5f;
		int frameCount = mediaPlayer.TextureProducer.GetTextureFrameCount();
        if (_textureFrameCount != frameCount)
        {
            _stallDetectionTimer = 0f;
            _textureFrameCount = frameCount;
        }
        else
        {            
            if (_stallDetectionGuard != Time.frameCount)
            {
                _stallDetectionTimer += Time.deltaTime;
            }
        }
        _stallDetectionGuard = Time.frameCount;

        float thresholdDuration = STALL_DETECTION_DURATION;

        thresholdDuration = Mathf.Max(thresholdDuration / Mathf.Abs(mediaPlayer.Control.GetPlaybackRate()), STALL_DETECTION_DURATION);

        float fps = mediaPlayer.Info.GetVideoFrameRate();
        if (fps > 0f && !float.IsNaN(fps))
        {
            thresholdDuration = Mathf.Max(thresholdDuration, 2f / fps);
        }

        if (_stallDetectionTimer > thresholdDuration)
        {
            mediaPlayer.Events.Invoke(mediaPlayer, MediaPlayerEvent.EventType.Stalled, ErrorCode.None);
            _stallDetectionTimer = 0;            
        }
		}

**Comment by ReneB** [comment]
We tried checking `mediaPlayer.Info.IsStalled` in an `Update()` loop and alas, that does not seem to work either.

**Comment by GabrielRosenberg** [comment]
I can't get the code above to work, the player crashes and becomes unresponsive. Is there any other suggestions on how to solve this? This can't be the accepted behaviour of a video player.

**Comment by GabrielRosenberg** [comment]
> > We're noticing the exact same issue on Android devices. Reproducible by the same steps mentioned in the top message on Android only. On iOS it does work.
> > @Ste-RH Any updates on this issue? We would like to use the 'stalled' event to show user feedback. Telling the user that their connectivity is gone for example. Any other ways we could realize this feature?
> 
> the code could be help to you; private int _textureFrameCount = 0; private float _stallDetectionTimer; private int _stallDetectionGuard; private void CheckStreamingStall(){ float STALL_DETECTION_DURATION = 0.5f; int frameCount = mediaPlayer.TextureProducer.GetTextureFrameCount(); if (_textureFrameCount != frameCount) { _stallDetectionTimer = 0f; _textureFrameCount = frameCount; } else { if (_stallDetectionGuard != Time.frameCount) { _stallDetectionTimer += Time.deltaTime; } } _stallDetectionGuard = Time.frameCount;
> 
> ```
>     float thresholdDuration = STALL_DETECTION_DURATION;
> 
>     thresholdDuration = Mathf.Max(thresholdDuration / Mathf.Abs(mediaPlayer.Control.GetPlaybackRate()), STALL_DETECTION_DURATION);
> 
>     float fps = mediaPlayer.Info.GetVideoFrameRate();
>     if (fps > 0f && !float.IsNaN(fps))
>     {
>         thresholdDuration = Mathf.Max(thresholdDuration, 2f / fps);
>     }
> 
>     if (_stallDetectionTimer > thresholdDuration)
>     {
>         mediaPlayer.Events.Invoke(mediaPlayer, MediaPlayerEvent.EventType.Stalled, ErrorCode.None);
>         _stallDetectionTimer = 0;            
>     }
> 	}
> ```

I implemented this suggestion but it does not help. The stalled event needs to be triggered before the error event is triggered, and the error event is triggered directly when the next frame is not available. So such a function needs to trigger the stalled event while new frames are still available. Any suggestions?

**Comment by supermoos** [comment]
Same issue here, however with a regular mp4 not a live stream.

**Comment by paulrinaldi** [comment]
Similar issue here; though, instead of killing wifi, the player just needs to be in the background and hit the end of a loaded playable duration.

**Comment by TorbenDalgaard** [comment]
@Ste-RH Any updates on this issue?

**Comment by Ste-RH** [comment]
> @Ste-RH Any updates on this issue?

This issue was opened for v2.x of AVPro Video.  We have not checked if this is still the case in v3.x.  My hunch is that it still behaves as reported.  We will add it to the list to check.

**Comment by Ste-RH** [comment]
I think we have managed to implement a fix for this.  It will be included in the next release (v3.1.3).

**Comment by Chris-RH** [comment]
AVPro Video version 3.1.3 has been released. Please let us know if it has not fixed your issue.
