### ISSUE TITLE
Is there a way to switch a stereoscopic video to monoscopic during runtime?

### ISSUE THREAD

**Issue by mrtnRitter** [RenderHeads/UnityPlugin-AVProVideo#876]
I have a VR video player created with AVPro. 

The UI of the player is not shown all the time, but only on user action.
Because of the different depth levels of the video, the UI appears "in between" of everything but in the same time, "in front" of everything, which looks wrong in certain situations. 

The PicoXR videoplayer solves this issue by putting the 3D video to 2D mode, so the UI is just in front of a background video. Is there any way to get something similar with AVPro? 

Thanks very much!

**Comment by kahnivore** [comment]
Hey @mrtnRitter 

You could try forcing it onto a material as written [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html#forcing-stereo-eye-mode).

Let us know if this works for you?

**Comment by mrtnRitter** [comment]
Hey @kahnivore

Thank you very much - it works like charm and totally neatness!

It just needed two basic functions:

		public void force2D()
		{
			VideoRender.SetupStereoEyeModeMaterial(forcematerial, StereoEye.Left);	
		}
		
		public void force3D()
		{
			VideoRender.SetupStereoEyeModeMaterial(forcematerial, StereoEye.Both);	
		}

Great work!
