### ISSUE TITLE
DisplayUGUI not showing correct last frame when video was played with some hard lags using NotchLC codec

### ISSUE THREAD

**Issue by Crazy-BAD** [RenderHeads/UnityPlugin-AVProVideo#877]
**Describe the issue**
We using RGBA video for ui background. On some hard workload (for example app start) video was freezed not on last frame which difenetly incorrect. Also i was tryed to subscrive media to player events and seek to last frame after video playback finished. This also not solwed issue.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.11
 - AVPro Video version:  AVPro Video v2.1.3 (native plugin v2.1.3f1-ultra) on NVIDIA GeForce GTX 1080 Ti/Direct3D 11.0 [level 11.1] (MT True) on WindowsEditor
 - Operating system version: W10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): Video: NCLC 800x800 29.97fps 19297kbps

**To Reproduce**
1. play video without loop. last frame fully clear - i.e. all content removed by alpha channel.
2. make script with random hard lags.
3. sometames vide was stopped with image on screen (non last frame)

script that was used to attempt to fix issue (but unsuccessful)
  public class MediaPlayerEndFrameFix : MonoBehaviour
    {
        private void Start()
        {
            var meidaPlayers = gameObject.GetComponentsInChildren<MediaPlayer>(true);
            foreach (var mp in meidaPlayers)
            {
                mp.Events.AddListener(OnMediaPlayerEvent);
            }
        }

        private void OnMediaPlayerEvent(MediaPlayer sender, MediaPlayerEvent.EventType ev, ErrorCode code)
        {
            if ( ev == MediaPlayerEvent.EventType.FinishedPlaying )
            {
                var totalTime = sender.Info.GetDurationFrames() / sender.Info.GetVideoFrameRate();
               UnityEngine.Debug.LogWarningFormat("Force seek form [{0} to {1}] - [{2}]", sender.Control.GetCurrentTime(), totalTime, sender.gameObject.GetPathInScene() );
                sender.Control.SeekToFrame(sender.Info.GetMaxFrameNumber());
            }
        }
    }

![00](https://user-images.githubusercontent.com/87861885/126789801-97ad7d12-e6a5-4531-a3d3-108726a96f5f.png)
![01](https://user-images.githubusercontent.com/87861885/126789808-2f5a1467-40a5-44a6-87d4-d2220c12bd04.png)
![02](https://user-images.githubusercontent.com/87861885/126789810-bce767dd-f130-4d5f-a92e-87bce32304f1.png)

**Comment by Crazy-BAD** [comment]
as you can see, same video in same (end) position showing different image, which difenetly wrong.

**Comment by AndrewRH** [comment]
Could you please send us this video file to unitysupport@renderheads.com or attache it here if it's not too large.

This seems to be a bug.  We will investigate this.

Thanks,

**Comment by Crazy-BAD** [comment]
hires video. other video also sometimes caused same behavior.

https://user-images.githubusercontent.com/87861885/126826130-77d1ff8a-2d96-47d7-b55d-a106997a8941.mov

**Comment by Crazy-BAD** [comment]
simple way to reproduce - in update use Sleep(x), x is public variable in monobeh (checkd in range 1000-10000)  to allow change delays without player restart. in this case i also saw other different bugs, every playback (manual press pause\play) in editor - even with normal fps (>60, delay was removed) video ended incorrectly not with last frame, until video manually was reloaded (in editor\player by pressing button). but this case reproduce not checked.

**Comment by AndrewRH** [comment]
Thanks for the video and the reproduction steps.  This seems like a genuine bug so we should be able to fix it pretty fast.

**Comment by Crazy-BAD** [comment]
thanks, we need this fix, i hope you can fix this fast.

**Comment by AndrewRH** [comment]
While we look into it, coudl you try enabling the Low Latency option, and make sure you have Use Custom Mov Parser disabled?

![image](https://user-images.githubusercontent.com/5418126/126881712-77b8736d-f54d-4e0b-baae-3862348fc929.png)

Does this workaround solve your issue?

Meanwhile we'll continue to look into the root cause..

Thanks,

**Comment by AndrewRH** [comment]
We have reproduced the problem and have a fix for it.  We will try to get this next release out very soon for you.

Thanks for reporting the issue and for your patience while we fixed it.

**Comment by AndrewRH** [comment]
Version 2.1.8 should be released tomorrow (Tuesday) with this fixed, and other NotchLC improvements.

When you test it, please let us know if this fixes this issue for you.

Thanks,

**Comment by AndrewRH** [comment]
@Crazy-BAD version 2.1.8 is available now

**Comment by kahnivore** [comment]
@Crazy-BAD did this fix your issue?

**Comment by AndrewRH** [comment]
I am closing this issue as we have not heard back and believe that the issue has been resolved with the 2.1.8 version.

Thanks,
