### ISSUE TITLE
Adjusting playback rate changes pitch on DirectShow

### ISSUE THREAD

**Issue by long597957111** [RenderHeads/UnityPlugin-AVProVideo#878]
**Your Setup (please complete the following information):**
 - Unity version: 2019.2.3
 - AVPro Video version: 2.1.7
 - Operating system version: windows7 ultimate

**To Reproduce**
In windows7,usage rate function,the tone of the audio changes.
In windows10,not have this problem.

**Comment by kahnivore** [comment]
Hi @long597957111 

Not sure exactly what you mean - could you provide some more context about your use-case please? Are you able to reproduce this with one of the demo scenes?

**Comment by long597957111** [comment]
When I used PlayBack() in windows7, the pitch changed if I set the value to a value other than 1, but not in windows10
<img width="406" alt="84b61e5f840907854c8be6c24ffe2e7" src="https://user-images.githubusercontent.com/87122350/127294320-028a34e7-1e61-48b3-b9a5-cf0072d3152d.png">
"The pitch" acts like the "pitch" of the Audiosource  
<img width="423" alt="b0c7d1700ba18236ffa3b720ed1cad6" src="https://user-images.githubusercontent.com/87122350/127294846-e3bd075e-aa29-4118-806a-2036ed115bf5.png">

**Comment by kahnivore** [comment]
Are you using DirectShow API on your Windows 7 test? Each API behaves differently when adjusting playback rate. DirectShow changes the pitch and Media Foundation applies a filter to keep the pitch constant. 

Could you try switching to Media Foundation and let us know if that fixes your problem?

**Comment by long597957111** [comment]
Yeah,i use the Media Foundation mode,it worked in win10,not win7,so i want to konw whether or not and "Audio output" the relevant.

**Comment by kahnivore** [comment]
Actually, MF isn't available in Windows 7, so it's defaulting to DirectShow, which is why the pitch is changing.

**Comment by long597957111** [comment]
Do you have a solution?

**Comment by kahnivore** [comment]
We don't have a solution, unfortunately it's just the nature of the DirectShow API.

**Comment by long597957111** [comment]
Thanks, i go to try.
