### ISSUE TITLE
Demo360_stereo is not stereo

### ISSUE THREAD

**Issue by ljDevelopment** [RenderHeads/UnityPlugin-AVProVideo#879]
We are evaluating buying this asset to our project, but... we cannot see the example  in stereo mode (Android)

Documentation doesn't say anything about any step to run Demo360_stereo; only one eye is being rendered. We also need to change VR <--> no VR. Is that possible?

We have managed to compile the project with Google Cardboard, but there is no head movement.

![image](https://user-images.githubusercontent.com/6762583/127470235-8ac59cff-afe0-41be-9da3-dbb9dfff3cc7.png)

The image seems to be the same one in both eyes.
Do we have to control head rotation?
Is it easy to disable VR?
Is it compatible with ARFoundation?

Luis

llopez @ Many - Worlds.es

**Comment by kahnivore** [comment]
Hi @ljDevelopment 

You'll probably need to add the Update Multi-Pass Stereo component and assign your camera to view in both eyes. 

What exactly do you mean by change VR to non-VR?

**Comment by JRMany-Worlds** [comment]
Hi, I'm in charge of this task of @ljDevelopment in the company. We are checking your recommendation. Thank you.

**Comment by AndrewRH** [comment]
@ljDevelopment it would also be useful to know how your scene is set up - are you using a camera per eye for example?

Also which version of Unity are you using?

Have you tried setting the media stereo mode?  See the documentation here to see how to do that:
https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html

Does that help?

Thanks,

**Comment by JRMany-Worlds** [comment]
@ljDevelopment is on holiday. Looks like we were able to make it work no need to use Multi-Pass component. We have stereo split screen and we can activate or deactivate. We are using Unity 2020.3.14f1

As soon as @ljDevelopment comes back we will confirm that this is all we want in our project and we will buy. 

Thanks for your prompt support. Regards!

**Comment by ljDevelopment** [comment]
Hi,

This is Luis, and I am testing this issue back. We still don't know how to make a proper setup to see stereoscopic video 360.

### Status

We are working for **Android and iOS** devices.

https://www.renderheads.com/content/docs/AVProVideo/articles/component-update-multipass-stereo.html
`This component is used for VR devices running in multi-pass mode instead of single-pass mode. In multi-pass mode AVPro Video needs to know which eye is currently rendering, and this component works that out and sets up the shader variables appropriately.`

We are opening the scene "Demo_360Stereo". I has integrated the component "UpdateMultiPassStereo" and this component has a reference to te main camera (we haven't changed anything in the scene)
![image](https://user-images.githubusercontent.com/6762583/129540694-4fbb4577-ec73-447d-b362-6ea9e3d2fd66.png)

The MediaPlayer component in the demo scene doesn't allow us to choose VR mode:
![image](https://user-images.githubusercontent.com/6762583/129540894-1f740ab8-d15b-4273-b01a-a368c5cfe79e.png)

Only after changing the source to Path, VR options appear:
![image](https://user-images.githubusercontent.com/6762583/129540982-7f790ee6-9968-4852-9968-e62f099328a9.png)

Installing XR Plug-In Management gives us some options, none of them works
![image](https://user-images.githubusercontent.com/6762583/129541793-baa5ed1e-b7bc-435d-baa6-6c856341a334.png)

### Questions
How do we setup multi-pass rendering?
![image](https://user-images.githubusercontent.com/6762583/129541309-43ddd052-d344-4bf8-8844-3a847013c89a.png)

What XR plug-in do you use for your tests Android / iOS?
Do we need more than one camera? How each eye rendering is configured?

**Comment by kahnivore** [comment]
Hi there,

For Google Cardboard you'll need to import the relevant SDK. There are setup guidelines detailed [here](https://developers.google.com/cardboard/develop/unity/quickstart). 

Does this help?

**Comment by ljDevelopment** [comment]
Hi,

As you can see on the capture in the first post of this thread, we have tried Google Cardboard but no stereoscopic view is provided (both eye images are the same).

So,

How do we get each eye image rendered correctly with Google Cardboard?
Do we have to use Google Cardboard?
Is there any alternative without Google Cardboard?

Thank you

Luis

**Comment by ljDevelopment** [comment]
Hi there,

We are still at the same point. We don't know why we see the same image in both eyes.

Can you propose any alternative to Google Cardboard?
In fact, we are having a lot of problems making Google Cardboard work with ARFoundation (https://forum.unity.com/threads/switching-arfoundatin-arcore-arkit-google-cardboard-doesnt-work.1164104/)

Can we get rid off Google Cardboard?

Best regards.

Luis

**Comment by kahnivore** [comment]
Hi, 

There are many alternatives to Google Cardboard - not sure exactly what you mean. 

We mostly test VR on the Quest 2, but that's just the hardware we have access to.

**Comment by ljDevelopment** [comment]
Hi,

Thanks for the quick answer.

We are developing for Android and iOS. We would like to evaluate feasibility before purchasing PRO version, but we found these two issues: same image in both eyes (no stereoscopic), and compatibility cardboard - ar foundation (required by our client).

Thanks.

**Comment by ljDevelopment** [comment]
This gifs demonstrates that both eyes render same image of the video. 

![ezgif-2-c6ff7c642657](https://user-images.githubusercontent.com/6762583/131666638-2b785d46-f3fe-4797-9afc-14f37ba7161c.gif)

The url of the video (top-bottom stereo) is: https://d2j1hl0hnnqsiz.cloudfront.net/551_corregido_orig.mp4

And this is the configuration of the Media Player:

**Comment by ljDevelopment** [comment]
Hi there,

He managed to solve one of our stoppers to use Google Cardboard in our project.

The only thing that blocks us to purchase  AVProVideo is this one, both eyes render the same image.

Please, do you need any further information from us to guess what is happening? Could you provide us with a project configured where a stereoscopic video is correctly rendered using Google Cardboard?

Thank you.

Luis

**Comment by kahnivore** [comment]
Hi Luis, 

Could you perhaps send a copy of your video you are using to test with to unitysupport@renderheads.com?
