### ISSUE TITLE
Error: loading failed due to different types of internet connection

### ISSUE THREAD

**Issue by Redeemer87** [RenderHeads/UnityPlugin-AVProVideo#88]
**Describe the bug**
I'm trying to show a youtube live stream on a mobile app. In order to use AVPro I'm converting, through another Unity plugin, the youtube live in an m3u8 type. The problem is that when I try this process at my office or my home everything works fine, when I try it through hotspot or my colleagues' home I receive each time the same error:

_[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources._

I made sure that all the Wi-Fi signals used are very good.

**Your Setup (please complete the following information):**
 - Unity version: 2018.1.0f2 or 2018.2.5f1
 - AVPro Video version: 1.9.17
 - Operating system version: Android 7 or higher
 - Device model: Galaxy SJ7, Asus X008d or Xiaomi Redmi Note 7
 - Video specs (resolution, frame-rate, codec, file size): Youtube Live Video, hls

**Logs**

> [AVProVideo] Opening https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1561305088/ei/oEsPXY-9IozIgAfFwqbgCQ/ip/54.78.155.188/id/lrX6ktLg8WQ.2/source/yt_live_broadcast/requiressl/yes/tx/23722139/txs/23722138%2C23722139/hfr/1/maudio/1/gcr/ie/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cmaudio%2Cgcr%2Cgo%2Citag%2Cplaylist_type/sig/ALgxI2wwRAIgPY5jrl5No2Mp5kFZm_yllbZxW2--Z2KxrJI8ry2O4_MCIFFaSPdRL1PTqcAHdAGBhxUsKxNmc4dxQxlyFmYP75gO/file/index.m3u8?disable_polymer=true (offset 0)
> 
> Couldn't open https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1561305088/ei/oEsPXY-9IozIgAfFwqbgCQ/ip/54.78.155.188/id/lrX6ktLg8WQ.2/source/yt_live_broadcast/requiressl/yes/tx/23722139/txs/23722138%2C23722139/hfr/1/maudio/1/gcr/ie/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cmaudio%2Cgcr%2Cgo%2Citag%2Cplaylist_type/sig/ALgxI2wwRAIgPY5jrl5No2Mp5kFZm_yllbZxW2--Z2KxrJI8ry2O4_MCIFFaSPdRL1PTqcAHdAGBhxUsKxNmc4dxQxlyFmYP75gO/file/index.m3u8?disable_polymer=true: java.io.FileNotFoundException: No content provider: https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1561305088/ei/oEsPXY-9IozIgAfFwqbgCQ/ip/54.78.155.188/id/lrX6ktLg8WQ.2/source/yt_live_broadcast/requiressl/yes/tx/23722139/txs/23722138%2C23722139/hfr/1/maudio/1/gcr/ie/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cmaudio%2Cgcr%2Cgo%2Citag%2Cplaylist_type/sig/ALgxI2wwRAIgPY5jrl5No2Mp5kFZm_yllbZxW2--Z2KxrJI8ry2O4_MCIFFaSPdRL1PTqcAHdAGBhxUsKxNmc4dxQxlyFmYP75gO/file/index.m3u8?disable_polymer=true
> 
> [create]line:623 Create new client(12) from pid 7031, uid 10003, 
> [setDataSource]line:1084 [12] setDataSource(https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1561305088/ei/oEsPXY-9IozIgAfFwqbgCQ/ip/54.78.155.188/id/lrX6ktLg8WQ.2/source/yt_live_broadcast/requiressl/yes/tx/23722139/txs/23722138%2C23722139/hfr/1/maudio/1/gcr/ie/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cmaudio%2Cgcr%2Cgo%2Citag%2Cplaylist_type/sig/ALgxI2wwRAIgPY5jrl5No2Mp5kFZm_yllbZxW2--Z2KxrJI8ry2O4_MCIFFaSPdRL1PTqcAHdAGBhxUsKxNmc4dxQxlyFmYP75gO/file/index.m3u8?disable_polymer=true)
> 
> setDataSource_drm_preCheck: isFDDrm 0 fd -1 url 0xe8ae20ac
> [ERROR]isDcf() : failed to dup fd, reason [No such file or directory]
> [setDataSource]line:1126 player type = 4
> disable trackId:0
> [setDataSource]line:1136 setDataSource(https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1561305088/ei/oEsPXY-9IozIgAfFwqbgCQ/ip/54.78.155.188/id/lrX6ktLg8WQ.2/source/yt_live_broadcast/requiressl/yes/tx/23722139/txs/23722138%2C23722139/hfr/1/maudio/1/gcr/ie/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cmaudio%2Cgcr%2Cgo%2Citag%2Cplaylist_type/sig/ALgxI2wwRAIgPY5jrl5No2Mp5kFZm_yllbZxW2--Z2KxrJI8ry2O4_MCIFFaSPdRL1PTqcAHdAGBhxUsKxNmc4dxQxlyFmYP75gO/file/index.m3u8?disable_polymer=true) done
> 
> [setVideoSurfaceTexture]line:1243 [12] 
> [SurfaceTexture-24-7031-1](this:0xdd4fd000,id:1,api:3,p:446,c:7031) connect(P): api=3 producer=(446:???) producerControlledByApp=true
> [setVideoSurfaceTextureAsync]line:367 Set new surface
> [prepareAsync]line:1376 [12] prepareAsync
> onConnect https://<suppressed>
> [custom_prop]custom_get_string->module[http_streaming],key[UserAgent]
> user-agent:stagefright/1.2 (Linux; Android 7.0)
> [custom_prop]custom_get_string->module[http_streaming],key[UAProfileURL]
> [~MediaHTTP]line:53 
> [custom_prop]custom_get_string->module[http_streaming],key[UserAgent]
> user-agent:stagefright/1.2 (Linux; Android 7.0)
> [custom_prop]custom_get_string->module[http_streaming],key[UAProfileURL](this:0x7a23500000,id:131,api:1,p:7031,c:253) queueBuffer: fps=26.78 dur=1008.14 max=85.07 min=20.40
> 
> failed to fetch .ts segment at url 'https://r4---sn-25ge7nls.googlevideo.com/videoplayback/id/lrX6ktLg8WQ.2/itag/91/source/yt_live_broadcast/expire/1561305088/ei/oEsPXY-9IozIgAfFwqbgCQ/ip/54.78.155.188/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D139/sgovp/gir%3Dyes%3Bitag%3D160/hls_chunk_host/r4---sn-25ge7nls.googlevideo.com/gcr/ie/playlist_type/DVR/initcwndbps/1850/mip/37.160.183.83/mm/44/mn/sn-25ge7nls/ms/lva/mv/m/pl/14/keepalive/yes/mt/1561283361/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,gcr,playlist_type/sig/ALgxI2wwRQIhAMLPYncJ_bYkpam7fUTGmMbCU4hoawCjpDDLPf1qQPN8AiBZ6DDlUxhKdWDRm92T3kjDIzfPAsSK4lCxJ_H6U1MSrA%3D%3D/lsparams/hls_chunk_host,initcwndbps,mip,mm,mn,ms,mv,pl/lsig/AHylml4wRQIhALoQ8YHUbeHjzSfQQssxNO4tRkNX_s--k01G2AVX5wG3AiBFDcQ5DLZAXsuAd0FlkqYFO3Rd1EmwHpjmaZWtpwPmjA%3D%3D/playlist/index.m3u8/sq/1307522/goap/clen%3D31389%3Blmt%3D1561283480792475/govp/clen%3D85066%3Blmt%3D1561283480792475/dur/5.000/file/seg.ts'
> 
> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Videos**
this is the original video:

_https://www.youtube.com/watch?v=lrX6ktLg8WQ_

this is an example of the converted URL:

_https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1561308569/ei/OVkPXYWFHpbT7gPDspugDg/ip/54.78.155.188/id/lrX6ktLg8WQ.2/source/yt_live_broadcast/requiressl/yes/hfr/1/maudio/1/gcr/ie/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cmaudio%2Cgcr%2Cgo%2Citag%2Cplaylist_type/sig/ALgxI2wwRAIgTWRyudGJGjkJfOoS_n9l6UhrBadfSJK8I3b0E7uvZxMCIDGDBSu5qJa88CKP0sfVqfZb3tCwCgTs8rRppH8ZQ_fF/file/index.m3u8?disable_polymer=true_

**Comment by AndrewRH** [comment]
Ummm...I'm really not sure what the issue could be.
We don't officially support YouTube streams (it is against their T&C's), but I'm still curious what the issue could be.....

**Comment by RenderHeadsSte** [comment]
@Redeemer87 The link you posted appears to be dead (404).  We are happy to take a look to see if there is a simple fix for your issue if you can provide a stable URL.  If not, then we will be closing the issue in a few days time.

**Comment by Redeemer87** [comment]
Thank you both for your help. After a little research I think that the problem is not related to AVPro plugin, but should be related to the external service, that provide the converted URL, and is connected to the other plugin that I've used. I'm not sure of it yet. Unfortunately now I don't have my pc to take another stable URL. I will post it tomorrow

**Comment by Redeemer87** [comment]
A new URL:

https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1561748127/ei/Pw4WXZXCCcKV1gLtlpOgDA/ip/54.216.175.92/id/lrX6ktLg8WQ.2/source/yt_live_broadcast/requiressl/yes/hfr/1/maudio/1/gcr/ie/go/1/keepalive/yes/dover/11/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cmaudio%2Cgcr%2Cgo%2Citag%2Cplaylist_type/sig/ALgxI2wwRQIgRHJmqN0mjnqKXZlLK5R4CzbgUU8Z9vzv_ZeDJGEV5ZgCIQDHBMwleh-fipj3TofEEM9hP0HBMBsqNUwuYliePwCixA%3D%3D/file/index.m3u8?disable_polymer=true (offset 0)

**Comment by RenderHeadsSte** [comment]
The link has expired again :(

**Comment by AndrewRH** [comment]
@Redeemer87  please try with the latest version of AVPro Video (1.10.0) that was just released.  Does that helps?  Or you could supply a new link?

**Comment by Redeemer87** [comment]
Thank you @AndrewRH I'll try with this new version and I'll let you know asap

**Comment by RenderHeadsSte** [comment]
@Redeemer87 How did you get on?

**Comment by Redeemer87** [comment]
Unfortunately, something seems to be changed on Youtube side, so the process that gives me the manifest URL doesn't work anymore, and I can't test the new version of AVPro. I don't know if and when I can test the new version, so don't worry if you think is better to close the issue.

**Comment by RenderHeadsSte** [comment]
Oki.  Please do open it if and when.
