### ISSUE TITLE
Application freezes frequently after update v2.1.6. 2.1.5 Trial version is Okay.

### ISSUE THREAD

**Issue by breadceo** [RenderHeads/UnityPlugin-AVProVideo#882]
**Describe the issue**
Unity Player freezes after update v2.1.6. Even though I upgrade to v2.1.8, problem still exists.
There is no certain step to reproduce this, and devices are so vary.
However, I downgrade to v2.1.5 Trial version. There is no problem.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.21f1
 - AVPro Video version: 2.1.6~2.1.8
 - Operating system version: macOS, Windows
 - Device model: various devices (M1 MacMini, 2019-Mid Mac book pro, many windows notebooks i5~i7)
 - Video specs (resolution, frame-rate, codec, file size): Vimeo X540p

**To Reproduce**
1. Just play vimeo videos with AV Pro Video.
2. Switch application to other program. I mean change app focus.
3. Suddenly Application freezes and Not responding.

**Logs**
If applicable, add error logs to help explain your problem.
[Player.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6914971/Player.log)

**Screenshots**
![photo_2021-08-02 16 01 46](https://user-images.githubusercontent.com/12538999/127818022-6d311082-5146-43e0-a4ad-dbc8d702adfe.jpeg)

**Videos**
https://vimeo.com/560212911/53bfe0e39f

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @breadceo 

Have you seen this note on Vimeo streaming? See [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#vimeo-support). 

If you use the 2.1.8 trial version does it make a difference? Perhaps you are using some of the ultra features listed [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions)? 

Are you sure that there isn't another plugin in your project causing the app to freeze? It looks that way in the player log.

**Comment by kahnivore** [comment]
2.1.5 package sent via keeping.

**Comment by breadceo** [comment]
I have updated to 2.1.5 core edition and send to users for testing.
They said that app freezes again. 
At that moment, Developer tools access pops up on macOS.
![image](https://user-images.githubusercontent.com/12538999/128279626-1597bfb1-291e-4f23-84cc-4a1e7690100b.png)

I don't use any high level features like Hap Codec, NotchLC Codec, Spatial Audio, etc. I just want to remove watermarks.
Is there any point to investigate more?

**Comment by breadceo** [comment]
Sorry for confusion. After upgrade 2.1.5 core edition, there is no freezing at all.

**Comment by kahnivore** [comment]
Hi @breadceo 

We'd really like to figure out why 2.1.5 fixed your problem. It'd be a lot better if you could keep up to date with future updates. 

It'd be useful to know what method you are using to stream from Vimeo?

Is there any chance you could send us a sample reproducible project of your issue so we could do some testing?
