### ISSUE TITLE
PlayListMediaPlayer.AudioVolume Problem

### ISSUE THREAD

**Issue by z79422957** [RenderHeads/UnityPlugin-AVProVideo#883]
void VolumeUp()
{
_playListMediaPlayer.AudioVolume += 0.1f;
}
void VolumeDown()
{
_playListMediaPlayer.AudioVolume -= 0.1f;
}
Hi,When the VolumeDown method is executed several times, when _playListMediaPlayer.AudioVolume is reduced to 0, its values will appear '1.490116E-08' and '-0.09999999'.
![audioVolume](https://user-images.githubusercontent.com/16982190/127993648-825d9a15-8e57-4b46-812f-305c3a9da6f9.jpg)

**Comment by AndrewRH** [comment]
You can try changing line 228 of PlaylistMediaPlayer to:

`			set { _playlistAudioVolume = Mathf.Clamp01(value); if (!IsTransitioning() && CurrentPlayer != null) CurrentPlayer.AudioVolume = _playlistAudioVolume; }`

Does the help?

Thanks,

**Comment by AndrewRH** [comment]
Please be aware that  '1.490116E-08' and '-0.09999999' are normal due to the way floating point works.  '1.490116E-08' basically means zero.

Anyway, if you add the Clamp01 above it should prevent it from becoming negative which is incorrect.

Thanks,

**Comment by kahnivore** [comment]
Hi there,

A little confused - you say it's working if you limit the fadeout with an if statement - what is the problem?

**Comment by z79422957** [comment]
(2)This is my code. Negative values exist:
float curVolume = 0.5f;
if (curVolume < 10) curVolume += 0.1f;
else if (curVolume > 0) curVolume -= 0.1f;//Without this if judgment, the volume will become negative, as shown in the figure below.
_playListMediaPlayer.AudioVolume = curVolume ;
————————————————————————————————————
If I do not add this if judgment and execute volumeDown, this _playListMediaPlayer.AudioVolume will is negative.

**Comment by AndrewRH** [comment]
Hi,

I'm not sure what value you're logging.   

Maybe try adding clamping to the MediaPlayer.cs where it's setting the AudioVolume property (around line 64)

change

`_audioVolume = value;`

to

`_audioVolume = Mathf.Clamp01(value);`

does that helps?  If not, please make sure that in the version of PlaylistMediaPlayer.cs the AudioVolume property does have the Clamp01(value) code as well eg around line 228: it should have 

`_playlistAudioVolume = Mathf.Clamp01(value);  `

Thanks,

**Comment by z79422957** [comment]
Hi,

I modified these two pieces of code, but the problem is still not solved.

_playListMediaPlayer.AudioVolume += 0.1f
![A](https://user-images.githubusercontent.com/16982190/129019099-6bb659d1-127a-496f-a813-cbece44eeb02.png)

_playListMediaPlayer.AudioVolume -= 0.1f
![B](https://user-images.githubusercontent.com/16982190/129019116-e8344d98-91b3-42bd-8be1-0b91ba67eb1b.png)

**Comment by z79422957** [comment]
Hi,@AndrewRH  @kahnivore
Will this problem be fixed in 2.1.9?

**Comment by AndrewRH** [comment]
Fixed in 2.2.0
