### ISSUE TITLE
Demo 360 MKV cannot be played

### ISSUE THREAD

**Issue by dun82** [RenderHeads/UnityPlugin-AVProVideo#886]
I found the following problem when I had a test on V2 Ultra trail. Thank you very much for your help.

Problem description:

While running the demo in Unity Editor, an error pops up.
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
Video API: Media Foundation
Audio Output: Facebook Audio 360

Device (which devices are you having the issue with - model, OS version number):
Windows 10 with HEVC support installed

Media (tell us about your videos - number of videos, resolution, codec, frame-rate, example URLs):
Using demo sample mkv (FantasyStereoFB360.mkv)

System Information:
AVPro Video: v2.1.6 (plugin v2.1.6f1-trial)
Target Platform: Standalone
Unity: v2020.1.17f1 WindowsEditor
OS: Windows 10  (10.0.0) 64bit - English
CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz - 4 threads - 16286KB
GPU: Intel(R) Iris(TM) Graphics 6100 - Intel - Direct3D 11.0 [level 11.1] - 8143KB - 16384

**Comment by kahnivore** [comment]
Hi @dun82 

That's strange - it works this side on Media Foundation using Facebook Audio 360 as the audio output. 

Does it work for you with WinRT and/or DirectShow?

Something to try is re-encoding the video to H.264 to try and ascertain if it's the HEVC or the MKV giving you the issue.

Perhaps you could try reinstalling the HEVC extensions and/or upgrading your GPU drivers?

Let us know

**Comment by dun82** [comment]
Hi @kahnivore 

Thank you for your feed. 

I try all Media Foundation / WinRT / DirectShow to load the file "FantasyStereoFB360.mkv" but fail. 
But the other sample files from the package work fine!

Converting the MKV to H.264 is fine but I want to maintain the 360 Audio feature. 

With HEVC extension reinstalled, GPU driver updated, the result remains the same. 

Next I am going to test my own generated MKV, will keep this post updated if any.

**Comment by dun82** [comment]
I cannot figure out why the sample clip "FantasyStereoFB360.mkv" from V1 failed to be loaded in V1/V2 package

Meanwhile, I generate my own audio 360 MKV, it can be loaded and played correctly on my desktop but not my laptop.
I guess it is hardware performance issue?

**Comment by kahnivore** [comment]
Can the FantasyStereoFB360.mkv also be played on your desktop but not on your laptop?

**Comment by dun82** [comment]
@kahnivore No,  "FantasyStereoFB360.mkv" cannot be played on my desktop as well.

**Comment by kahnivore** [comment]
Can you provide more details about the mkv's you've created? What codec are they, what resolution?

Could you also try play this stream here: [https://rh-testmedia.s3-eu-west-1.amazonaws.com/Samples/Cones-360Stereo-2K30-HEVC.mp4](https://rh-testmedia.s3-eu-west-1.amazonaws.com/Samples/Cones-360Stereo-2K30-HEVC.mp4). Just want to make sure it's not HEVC that is giving you issues.

**Comment by dun82** [comment]
I tried the stream on the desktop, with AVPro Video v2.1.8 (native plugin v2.1.8f1-ultra) on NVIDIA GeForce GTX 1070/Direct3D 11.0 [level 11.1] (MT True) it works fine in editor/builds! 

With the new package re-installed, I can even have "FantasyStereoFB360.mkv" loaded correctly on the desktop

Will have a test on notebook later.

Thank you again @kahnivore

**Comment by RuudvanReenen** [comment]
Same issue here, with AVPro Ultra 2.6.6 on Windows 10 x64. 

Trying to play the FantasyStereoFB360.mkv file (not in play mode, in Editor by clicking on Load) in the Unity Editor 2021.3.12f1 results in: 
[AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

Tried with Media Foundation, Direct Show and Win RT, same result.
Audio Output is set in inspector to Facebook Audio 360, and Channel Mode to TBE_8_2.
Same problem with the HansVoice file.

The link https://rh-testmedia.s3-eu-west-1.amazonaws.com/Samples/Cones-360Stereo-2K30-HEVC.mp4 can be played perfectly fine.
