### ISSUE TITLE
Seek to the current 'live' time for a live stream 

### ISSUE THREAD

**Issue by JayCashLive** [RenderHeads/UnityPlugin-AVProVideo#887]
Hello,

We have a game made on Unity (version 2020.3.15f2) and our game has a live streaming show, with a host calling the actions in the game.

We had the deprecated AVPro version and we want to buy the latest version, so we have integrated the lates AVPro core trial version. 

Everything seems to be working fine when we start the Media Player. Both devices have similar latency.

The issue is that when we call the function Seek (to Seek to the current 'live' time for a live stream) we are having different latency for iOS and Android. **Android is ahead in about 5-6 seconds under the same wifi connection.**

We call "seek to live" after suspending the app ("OnApplicationFocus").

Here's the code to start the Player:

     if (player != null && player.Control != null)
      {
        player.Control.MuteAudio(false);
        player.Control.SetPlayWithoutBuffering(true);
         player.Control.Play();
         receivedPlayCommand = true;
       }
                   
Here's the code to "seek to live":

       private void SeekToLive()
        {
            if (player != null && player.Control != null)
            {
                // Seek to the current 'live' time for a live stream
                TimeRange seekableRange = Helper.GetTimelineRange(player.Info.GetDuration(), player.Control.GetSeekableTimes());
                player.Control.Seek(seekableRange.EndTime);
            }
        }

And here is where we call "seek to live":

      private void OnApplicationFocus(bool focus)
        {
            if (focus)
            {
                SeekToLive();
            }
        }

Are we missing something? How come under the same network we have different "seekable times"?

Thanks in advance!

**Comment by kahnivore** [comment]
Hi @JayCashLive 

It might be useful to try the built-in function we have for live seeking in MediaPlayer.cs -> SeekToLiveTime. An offset of 0 should set it to the current 'live' time. 

Not sure if this will solve the difference - basically a lot of this comes down to the different ways each OS handles this. 

Do you need both platforms to be in sync?

**Comment by JayCashLive** [comment]
Hello, 

Thanks for the reply. I will try it the MediaPlayer SeekToLiveTime. I just noticed it's private, so I will make it public, if that's ok.

We need both platforms to be sync, cause the host call the actions live in the game. 

Currently when we suspend the app, we are closing and reopening the player:

1. player.CloseMedia();
2. player.OpenMedia(MediaPathType.AbsolutePathOrURL, videoURL, false);
3.  player.Control.SetPlayWithoutBuffering(true);
     player.Control.Play();

That seems to get a similar latency on both iOS and Android. I'm just not sure if it could cause memory issues in the device.

Thank you!

**Comment by kahnivore** [comment]
Yeah, it's private now - we will change it to public in the next release, so go ahead and change it in the meantime! 

Are you seeing any spikes in memory with the above steps?

**Comment by JayCashLive** [comment]
Hello,

The SeekToLiveTime method seems to work way better! Both devices are now with similar latency. The only thing I am noticing is that Android starts right away and iPhone has around 4 seconds frozen before start playing. 

Is there anything I could do to avoid that?

Thanks in advance!

**Comment by kahnivore** [comment]
Great! Glad the SeekToLiveTime method was helpful. 

Not sure how big of a difference this would make but you could try out Y'CBCr output mode, see [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-ios.html#ycbcr-video-output-mode). 

There could be workarounds depending on your context but would need to know more details. Is it 'freezing' after you call the SeekToLiveTimeMethod? Or more generally when you play the stream.

**Comment by JayCashLive** [comment]
OK. 

Thanks!

I will try out the Y’CBCr output mode.

To answer your question, The stream is playing fine. It is freezing after call SeekToLive for 3 to 5 seconds on iOS only.

--
Juliano Gauciniski | SE
website: Cash.Live
Email: ***@***.*** ***@***.***> 
Vancouver, Canada 
Innovating Social Casino with Livestream Technology

**Comment by JayCashLive** [comment]
Hello again,

Just to give you a feedback. I tested setting the Texture Format to Y'CbCr420 under iOS (Platform Specific) and it does not do any difference regarding -> "It is freezing after calling SeekToLive for 3 to 5 seconds on iOS and Unity Editor only."

Android works fine after SeekToLive, refreshing the streaming right away with no "freezing".

Thanks,

**Comment by MorrisRH** [comment]
We exposed ```Preferred Forward Buffer Duration``` recently which allows a degree of control over how much of the video is buffered on iOS, see the documentation [here](https://www.renderheads.com/content/docs/AVProVideo/articles/component-media-player.html#platform-specific---ios).

```MediaPlayer.SetPlayWithoutBuffering``` currently has no effect on iOS so we'll look into getting support for that added to the plugin.

**Comment by JayCashLive** [comment]
Hello,

Would that do the same as “Buffer For Playback MS” under Android, which has the default value to 2500? Should I change “Preferred Buffer Duration” under iOS from 0 to 2500 as well?

--
Juliano Gauciniski | SE
website: Cash.Live
Email: ***@***.*** ***@***.***> 
Vancouver, Canada 
Innovating Social Casino with Livestream Technology

**Comment by MorrisRH** [comment]
It’s similar (not quite the same as the platform APIs are quite different). 
Preferred Forward Buffer Duration is in seconds on iOS so you would set it to 2.5.

**Comment by JayCashLive** [comment]
Alright.

Thanks!

It didn’t change much, as I can still see the freezing for 2-5 seconds while seeking to live, but I will keep iOS set to 2.5 seconds.

Please let us know when MediaPlayer.SetPlayWithoutBuffering  is ready for iOS.

Thank you very much!

--
Juliano Gauciniski | SE
website: Cash.Live
Email: ***@***.*** ***@***.***> 
Vancouver, Canada 
Innovating Social Casino with Livestream Technology

**Comment by MorrisRH** [comment]
```MediaPlayer.Control.SetPlayWithoutBuffering``` is currently not implemented for any platform (it's a hangover from version 1.x) so we've deprecated it and will likely remove it at some point in the future.

I've added a new option to the network section of the iOS platform specific options, "Play Without Buffering". Enabling this will cause playback to begin as soon as possible, however if network conditions are poor and it stalls it will then buffer up enough to continue.

This will make it into the next release.

**Comment by JayCashLive** [comment]
Thank you very much!

**Comment by AndrewRH** [comment]
Version 2.2.0 of AVPro Video has been released now and should resolve this issue.  Please let us know if you have any more problems.

**Comment by JayCashLive** [comment]
Thank you very much!

--
Juliano Gauciniski | SE
website: Cash.Live
Email: ***@***.*** ***@***.***> 
Vancouver, Canada 
Innovating Social Casino with Livestream Technology
