### ISSUE TITLE
[2.1.8] Video rendered only in left eye - hololens 2 

### ISSUE THREAD

**Issue by ediatreyu** [RenderHeads/UnityPlugin-AVProVideo#888]
When we play a video with alpha tranparency including the video that 
comes with avpro examples Cones-Transparent-2K60-H264.mp4 with the fall back
media hints as follows:

Tranparency: Tranparent, Alpha packing: top bottom, Stereo packing: none 
Tested it on unity 2019.4.21.f1 and 2020.3.8f1
UWP SDK Version: 10.0.19041.0
AVPro plugin version: 2.1.8 and also tested with the one before the realese of the laltest.
Result: video rendered only on the left eye hololens display

If we play the videos with no transparency or  without any packing it plays in bouth eyes:
Tranparency: Opaque, Alpha packing: none, Stereo packing: none

**Comment by kahnivore** [comment]
Hi @ediatreyu 

Have you tried forcing the stereo eye mode to both as detailed [here](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html#forcing-stereo-eye-mode)?

**Comment by kahnivore** [comment]
Do you have steps to reproduce? Is it reproducible in one of the demo scenes?

**Comment by AndrewRH** [comment]
@ediatreyu please try replacing the shader attached in issue #893 to see if that solves it.

**Comment by ediatreyu** [comment]
@kahnivore @AndrewRH thanks for your reply

Following the instructions on the unity documentation yesterday  I found a bug in the shader, I just added the next line:

**UNITY_VERTEX_OUTPUT_STEREO** 

 in the AVProVideo-Unlit-Transparent.shader at the end of **struct v2f**

https://docs.unity3d.com/Manual/SinglePassInstancing.html?_gl=1*1562kdb*_ga*MTE3MDM2NDcuMTU4NTY2NjM2Ng..*_ga_1S78EFL1W5*MTYyODUxOTA3Ny4xLjAuMTYyODUxOTA3Ny42MA..&_ga=2.55613099.1013069164.1628519078-11703647.1585666366

**Comment by AndrewRH** [comment]
Version 2.2.0 of AVPro Video has been released now and should resolve this issue.  Please let us know if you have any more problems.
