### ISSUE TITLE
Problem streaming from StreamingAssets when building AppBundle [android]

### ISSUE THREAD

**Issue by LuisCRSousa** [RenderHeads/UnityPlugin-AVProVideo#89]
AVPro video android fails to get the video from StreamingAssets folder when building AppBundle (.aab). It works when building normal .apk

- Info Unity: [AVProVideo] Opening jar:file:///data/app/com.karmakai.loulera-QasTxPmH9A22XnEf2IWn9Q==/split_config.armeabi_v7a.apk!/assets/figurantes_o3.mp4 (offset 0)

- Error Unity: [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

Replicated this problem using the AVProVideo Android demos without any modification.

This is a major issue as my app on google play is not working due to this problem

**Comment by LuisCRSousa** [comment]
The problem persists if I have external write permissions enabled or not.

Image with all errors: https://imgur.com/llINOWc

**Comment by RenderHeadsSte** [comment]
Thanks for reporting this issue.  We have reproduced and, if possible, will look into providing a solution.

**Comment by RenderHeadsSte** [comment]
Am I correct in saying you are using the ExoPlayer API path?  The MediaPlayer API path appears to not suffer this issue, so you could switch to using that.

**Comment by LuisCRSousa** [comment]
> Am I correct in saying you are using the ExoPlayer API path? The MediaPlayer API path appears to not suffer this issue, so you could switch to using that.

It works using Mediaplayer. But this API makes my videos to loose some initial frames.

**Comment by RenderHeadsSte** [comment]
I would love to hear more about your missing initial frames issue when using MediaPlayer API path.

We have a fix coming for your issue playing back videos from Streaming-Assets/App-Bundles when using the ExoPlayer API path.  I hope it will make version >= 1.9.18
