### ISSUE TITLE
Sometimes video texture does not play but audio does. Quest 2

### ISSUE THREAD

**Issue by tripdragon** [RenderHeads/UnityPlugin-AVProVideo#890]
On the Oculus Quest 2 sometimes when changing a video via a single event trigger the video will not play or just renders black, while the audio does play reliably. This is SUPER hard to reproduce when debugging but its frequent when its necessary, oh bother....

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.20f1 I can also do a build for 2020 lte if you need
 - AVPro Video version: 2.0.11f1-ultra
 - Operating system version: windows 10 but its not played in windows, its a full Android build on the headset disconected from the computer
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 4k various mp4's
 -  Video is loading from StreamingAssets folder

**To Reproduce**
1. Trigger Play() from some button event
I tried spamming the button or swapping from a playlist its around then then I can get it to break but not always. In the cause for the users its more frequent when they are multi playing via network, but you have to ask each player if they see something on each video change. Each player is viewing the video playing in the headset not getting a streaming video from a server. The networking tool we are using is NormCore. But the networking is not issue.

I will try spamming the Play() for a few seconds to see if that could fix it.

The question I guess I have is, Is there a function to check if the Video is returning a texture not fully blank or black? I guess I could compare all pixels at one second in after any fadeins but that seems expenssive

**Comment by kahnivore** [comment]
Hi @tripdragon 

If you're using 2.0.11 it would be a good idea to upgrade as a lot of changes have been made since then. We're currently on 2.1.8. 

Is there a chance you could send a sample reproducible project to unitysupport@renderheads.com? 

Is it always the same videos that don't render?

**Comment by tripdragon** [comment]
Ok, will update and send results in a few days. Its any video and its not reliable at which will trigger it nor when but its always at the start of the video when it does, nor is it persistent. I can not send a sample, its IP code and making a smaller demo in this case is super nontrivial  due to the layers of network and VR input to replicate it.

Thank you!
