### ISSUE TITLE
8k video - play local in android and Oculus quest2

### ISSUE THREAD

**Issue by sunilsingha** [RenderHeads/UnityPlugin-AVProVideo#891]
Hi,

we are converting our existing UWP VR app to Oculus quest platform. It has a cube like room where we play 8k videos on the wall (4 videos). Since Oculus Quest has its own storage/processor/ram, will it be able to play 4 videos of 8k resolution locally at a time?
Scaling down the resolution is not possible since those videos are downloaded from CMS. 
Could you please guide me here?

thanks
Sunil

**Comment by kahnivore** [comment]
Hard to say without trying it. It'd also depend on the rest of the specs of your media and how long the media/application is going to be running for. 

Have you tested this with out free trial? See [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases).
