### ISSUE TITLE
[2.1.3] AVProVideo-Unlit-Transparent.shader only renders for left eye on VR devices

### ISSUE THREAD

**Issue by aherbig** [RenderHeads/UnityPlugin-AVProVideo#893]
**Describe the issue**

The Shader "AVProVideo/Unlit/Transparent (texture+color+fog+stereo+alpha)" does not produce an image for the right eye.
Seems like it is missing these lines inside the 'struct v2f':
`
#ifdef UNITY_STEREO_INSTANCING_ENABLED
`
`
UNITY_VERTEX_OUTPUT_STEREO
`
`
#endif
`

When I add those lines there, everything works properly.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.7f1
 - AVPro Video version: 2.1.3
 - Operating system version: 
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by aherbig** [comment]
I did not see any changes mentioned in regard to this issue on the newer versions - I have not tried updating to 2.1.8 yet and see if this bug still exists

**Comment by kahnivore** [comment]
Thanks this seems like a bug and will perhaps solve #888.

**Comment by AndrewRH** [comment]
For reference here is the fixed shader.  We will include this in the next release of the plugin - thanks for telling us about this!

[AVProVideo-Unlit-Transparent.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/6983287/AVProVideo-Unlit-Transparent.zip)

**Comment by aherbig** [comment]
You're welcome - glad I could be of help.

**Comment by AndrewRH** [comment]
Version 2.2.0 of AVPro Video has been released now and should resolve this issue.  Please let us know if you have any more problems.
