### ISSUE TITLE
Can I feed Time into the MediaPlayer and get audio as well?

### ISSUE THREAD

**Issue by tripdragon** [RenderHeads/UnityPlugin-AVProVideo#894]
**Question**
I will preface that im sure this I can not do, cause the actual individual frames never actually are read.

I would like to try feeding the playback of the MediaPlayer video with a network roomtime stopwatch while also driving the audio to play. The only function I see is .Seek(t) and .FastSeek(t) and those work with the videos compressed keyframes not actual frames. My initial sample project tells me this is a no.

I totes get it if this is not doable. Ill try implementing Streaming instead

**Comment by kahnivore** [comment]
Sorry for the slow response. Unfortunately not possible as you suspected. Audio will not play while seeking.
