### ISSUE TITLE
Can AVProVideo load files whose name lacks a file extension?

### ISSUE THREAD

**Issue by jeffrson** [RenderHeads/UnityPlugin-AVProVideo#897]
**Question**

I need to load files via database out of an cache folder structure. Files have been stored without a file extension in the name.

Unity's VideoPlayer cannot load these files - can AVProVideo?

I'm running on Windows, if that matters.

Thanks!

**Comment by kahnivore** [comment]
On Windows it could work without a file extension, I think not on Mac/Android.

We offer an unlimited, watermarked trial if you'd like to test this. You can find the latest [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/releases).
