### ISSUE TITLE
AVProVideo.framework within UnityFramework.framework in XCode

### ISSUE THREAD

**Issue by MephestoKhaan** [RenderHeads/UnityPlugin-AVProVideo#898]
**Describe the issue**
Trying to embed the AVProVideo framework properly within the UnityFramework.framework so they can be exported together into a native iOS app.

I added it to the UnityFramework and marked it as Embed and Sign but most of the time I am getting this error when building the UnityFramework.framework target: 
```
[...]Libraries/AVProVideo/Runtime/Plugins/iOS/AVProVideoBootstrap.m:1:9: fatal error: 'AVProVideo/AVProVideo.h' file not found
```

I tried adding it to the UnityFramework.h as well with no luck.

I am following this: https://github.com/CocoaPods/Xcodeproj/issues/408#issuecomment-249347379 in order to automate the linking of the framework within the framework. I have played around with some things but cannot make it work either this way or manually.

**Your Setup (please complete the following information):**
Unity Version 2020 LTS

**Comment by kahnivore** [comment]
Which version of AVPro Video are you using?

**Comment by MephestoKhaan** [comment]
Latest in the store. We updated less than a week ago.

**Comment by MephestoKhaan** [comment]
To clarify the project works fine if I send the native iOs project both frameworks and I import them there. But ideally I want to send just the a unity Framework with avpro embedded.

I am using this : https://docs.unity3d.com/Manual/UnityasaLibrary-iOS.html to generate the library.

**Comment by MorrisRH** [comment]
We don't currently support this use case.
I've marked this issue as an enhancement and will investigate whether or not it is possible at some point in the (not too distant) future.

**Comment by MephestoKhaan** [comment]
Understood. Thabks though!

**Comment by MorrisRH** [comment]
The compilation issue can be fixed by replacing the following line in AVProVideoBootstrap.m:
```
#import "AVProVideo/AVProVideo.h"
```
with:
```
extern void AVPPluginUnityRegisterRenderingPlugin(void *registerRenderingPluginFunction);
```
This will get you a build, however I haven't figured out how to fix the runtime issue with loading the framework.

**Comment by AndrewRH** [comment]
@MorrisRH not sure if there's been any progress on this with the latest changes/fixes?

**Comment by MorrisRH** [comment]
As @ZimM-LostPolygon says, there is no official support for nested frameworks on iOS/tvOS so it's not really something we can implement. Because of this I will close this issue. We may look into this again in the future.
