### ISSUE TITLE
Use two Webcams,Only can save one File

### ISSUE THREAD

**Issue by wangguank** [RenderHeads/UnityPlugin-AVProVideo#9]
I use WebcamCaptureDemo . I got two cameras,and all of them display normally .

but when i save them , I only got video files that can be used.

![20190128181502](https://user-images.githubusercontent.com/35138737/51829566-cad2fe00-2328-11e9-9424-a564ffcad852.png)
![201901281815021](https://user-images.githubusercontent.com/35138737/51829568-cad2fe00-2328-11e9-9e06-e95e7ff51b94.png)
![201901281815022](https://user-images.githubusercontent.com/35138737/51829570-cb6b9480-2328-11e9-8615-1006783a9835.png)
![201901281815023](https://user-images.githubusercontent.com/35138737/51829571-cb6b9480-2328-11e9-8d3b-acc36a29ac10.png)
![201901281815024](https://user-images.githubusercontent.com/35138737/51829572-cc042b00-2328-11e9-927a-0c2c1221f6e8.png)

**Comment by AndrewRH** [comment]
Please post this to the AVPro Movie Capture issues page:
https://github.com/RenderHeads/UnityPlugin-AVProMovieCapture

We also need details like version numbers etc (use the bug report template).

Thanks,
