### ISSUE TITLE
cant build APK to oculus quest - Unity

### ISSUE THREAD

**Issue by maorBit** [RenderHeads/UnityPlugin-AVProVideo#90]
hello we purchased AVpro services to use it for 360 video in VR oculus quest for unity , unfortunately  the latest version  1.9.17b  isn't working on build and run, it gives a lot of errors  (merging dex archives errors)  ,  and it took us a lot of time trying to fix those errors , even when we did , it coused a lot of other errors , we tried to locate another release version to download but we couldn't find any . 

we plaid a lot of money for this service , please help us out to fix this problem or maybe send us a download link for another version that it isnt beta version. 
there is a screenshot of the errors attached to this email. 
i hope you can help us out.

 - Unity version: 2019.1.2f
 - AVPro Video version: 1.9.17b 
 - Device model: Oculus Quest

thanks.

**Comment by AndrewRH** [comment]
Hi,
Thanks for getting in touch.
This isn't a beta version.  I suspect there are issues with the Java JRE version you have installed.  Please could you elaborate on the errors that you're having?
Thanks,

**Comment by maorBit** [comment]
hello thank you for answer.
i attach screenshots to show you the errors, i dont really know what are
they , only says: "Error while merging dex archives".
which version of Java JRE you recommend? i just tried to update to the
newest version and its still not working.


‫בתאריך יום ב׳, 24 ביוני 2019 ב-18:42 מאת ‪Andrew‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by AndrewRH** [comment]
Okay thanks, 
Have you tried the solution mentioned here:
https://stackoverflow.com/questions/56623107/unity-gradle-build-error-while-merging-dex-archives

I believe we're using jre1.8.0_151

Let me know if this helps at all.

**Comment by maorBit** [comment]
thanks, but i think i just solved the problem finally, there is a plugins
folder there were duplicate exo files, one with exo 25 and other exo 28 , i
deleted the 25 , and now its working.
if you want add it to your solve problems it will help other people i saw
they having the same issue.
thanks a lot for help i appreciate it!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫בתאריך יום ג׳, 25 ביוני 2019 ב-11:39 מאת ‪Andrew‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by AndrewRH** [comment]
Glad it's fixed :)
