### ISSUE TITLE
PlaylistMediaPlayer Bugs

### ISSUE THREAD

**Issue by michelepanegrossi** [RenderHeads/UnityPlugin-AVProVideo#903]
**Describe the issue**
A clear and concise description of what the issue is.

I am trying to have a plylist where I can occasionally pause one video and scrub it using a slider.

I am experiencing the follwoing bugs when using the PlaylistMediaPlayer component:

- Volume of first item is zero when application started. Same as #880 
- When calling `_playlist.Pause()` the video stops but the audio doesn't. Calling _playlist.Control.Pause() seems to stop the audio as well but I read it is not the recommended practice?
- Calling _playlist.Control.Pause() OR _playlist.Pause() from scripts only works occasionally. At times either the video or the audio keep playing. Calling _playlist.Pause() also produces a black screen occasionally and the video cannot be seen.
- When scrubbing with _playlist.Control.Seek() sometimes the scrubbing (with a slider component) works smoothly only when going forwards, when going backwards it works only when the slider is released.

It could be an issues with my test.mp4 video (included in emailed project) (HEVC HLG HDR format) or it could be an issue with my graphics card being too old. Or is this a bug?

My code here:

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RenderHeads.Media.AVProVideo;
using UnityEngine.UI;

public class testPlay : MonoBehaviour
{
    public PlaylistMediaPlayer pmp;
    int frame = 0;

    public Slider _slider;

    bool scrubbing = false;

    private void Update()
    {
        
        if(scrubbing)
        {
            float frameRate = pmp.Info.GetVideoFrameRate();
            float totalFrames = pmp.Info.GetMaxFrameNumber();
            double time = Helper.ConvertFrameToTimeSeconds(frame, frameRate);

            pmp.Control.Seek(time);
            frame = (int)(_slider.value * totalFrames);
        }

    }
    
    //This functon is called from UI buttons
    public void PlayVideoAtPosition(int position)
    {
        
        if (pmp.CanJumpToItem(position))
        {
            pmp.JumpToItem(position);
        }

        if (position == 2)
        {
            frame = 0;
            _slider.value = 0f;
            pmp.Control.Pause();
            scrubbing = true;
        }
        else
        {
            pmp.Control.Play();
            scrubbing = false;
        }
    }
}
`

**Your Setup (please complete the following information):**
 - Unity version:  2020.3.12f
 - AVPro Video version: AVPro core edition 2.1.8
 - Operating system version: Mac osx 11.4
 - Device model: Macbook pro 15" late 2013, i7 quad core 4th gen, NVIDIA GeForce GT 750M.
 - Video specs (resolution, frame-rate, codec, file size): test.mp4 video provided with emailed project, 1x 2160p HEVC HLG HDR file.

**To Reproduce**
1. Project has been emailed as requested
2. Open AvPro Video -> Demos -> Scenes -> Test
3. Use buttons 0,1,2 to jump through the playlist. Only video 2 can be scrubbed. Use the slider to scrub. Jumping a few times between videos highlights the issues described above, as they do not happen every time.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

I am using AVPro provided videos apat from one video which is included in project streaming assets folder and it is called test.mp4. Project has been emailed as requested.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
Hi @michelepanegrossi 

Yes, the first issue regarding the volume of the first item of playlist being zero has been confirmed and will be fixed in our next release 2.1.9 which should be out soon. 

Haven't managed to reproduce the second issue regarding pause() - both playlist.Pause() and playlist.Control.Pause() pause the audio in my test project. 

Will have at the project you sent regarding issue 2 and 3.

**Comment by Ste-RH** [comment]
AVPro Video v2.5.3 has just been released and includes fixes for this issue.
