### ISSUE TITLE
AVPro crashing for certain videos on Quest 2

### ISSUE THREAD

**Issue by Kevinsomnia** [RenderHeads/UnityPlugin-AVProVideo#906]
**Describe the issue**
Playing a video on a Oculus Quest 2 would cause the device to crash eventually. This does not happen for every video, but a specific client of ours encountered this issue. There would be a few stutters that occur before the crash, about 90 seconds in. Additionally, there were about 10 other videos in the room, but all except 1 were paused, which we expect to not consume any resources.

Switching over to Unity's `VideoPlayer` component resolved this issue.

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.17f1
 - AVPro Video version: Core 2.1.5
 - Operating system version: 31.1
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 3m06s, 1920x1080, 29.97 FPS, H264 - MPEG-4 AVC (part 10) (avc1), 18487 kbps, 412 MB

**To Reproduce**
1. Import a video as close to the provided specs as possible.
2. There were also 10 or so other videos that were paused, but only 1 of them were playing.
3. Let the video play for about 1 min and 30 seconds.
4. There are occasional stutters that last for a second or so, growing more frequent, and eventually crashing the app completely.

**Logs**
If applicable, add error logs to help explain your problem.
Stacktrace of the crash seems to point towards a ExoPlayer OOM issue.
```
--------- beginning of crash
08-04 16:44:55.232 21543 21918 E AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Loader:ProgressiveMediaPeriod
08-04 16:44:55.232 21543 21918 E AndroidRuntime: Process: com.Spatial.Spatial, PID: 21543
08-04 16:44:55.232 21543 21918 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 5464 byte allocation with 2008 free bytes and 2008B until OOM, target footprint 268435456, growth limit 268435456
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3257)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:541)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:176)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.lang.String.replace(String.java:2381)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at com.google.android.exoplr2avp.util.Log.appendThrowableString(Log.java:176)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at com.google.android.exoplr2avp.util.Log.e(Log.java:138)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:445)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-04 16:44:55.232 21543 21918 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

**Videos**
Currently requesting permission from the video's owner to share. Would probably prefer to share via email. Also trying to create a separate, generic video that is able to reproduce this issue if the owner denies our permission to share their video.

**Request/Ask**
- If possible, we hope at the very least that this error can be caught wherever ExoPlayer is wrapped by AVPro, so that the app no longer crashes.
- Alternatively, a bigger ask would be: is there any way to access source code to dive into this issue ourselves? From what I can tell, there is pretty limited information regarding the errors. The `ErrorCode` only tells us whether the loading/decoding failed, but no stacktraces to help us pinpoint playback issues in general.
- But otherwise if the root crashing issue is fixed on the ExoPlayer side, then that's great! We're just worried a different type of fatal exception will happen again.

**Comment by mikejurka** [comment]
there seemed to be a similar issue hit by another user here: https://github.com/google/ExoPlayer/issues/7354

in that case, calling `setPrioritizeTimeOverSizeThresholds` resolved it for them, can we pass this to exoplayer through avpro somehow?
```
 SimpleExoPlayer player = new SimpleExoPlayer.Builder(MainActivity.this,
        new DefaultRenderersFactory(MainActivity.this))
    .setLoadControl(new DefaultLoadControl.Builder()
        .setPrioritizeTimeOverSizeThresholds(false)
        .createDefaultLoadControl())
    .build();
```

**Comment by Kevinsomnia** [comment]
I updated the video metadata information in the original post. It seems like higher bitrate videos reproduces the crashes more often. There are about 4 ~18000 kbps videos in the background that are paused (I'm guessing they're still buffering in the background). It stutters every 10 seconds or so and then finally crashes about a minute in.

**Comment by kahnivore** [comment]
Sorry that it's taken us so long to get back to you - do you have permission to share the test video yet? That would be really helpful in us reproducing the issue. You can send the video or alternatively a Unity project that demonstrates the above.

**Comment by kahnivore** [comment]
Actually, looking closer at this - 10 videos loaded at once would almost certainly overload the quest 2. You could try lowering the buffer demands in each video - see Android-specific settings in the MediaPlayer component. 

It'd probably be better to concatenate the videos into one single video and play a portion of it on each display, if that's an option?

**Comment by Kevinsomnia** [comment]
> Sorry that it's taken us so long to get back to you - do you have permission to share the test video yet? That would be really helpful in us reproducing the issue. You can send the video or alternatively a Unity project that demonstrates the above to unitysupport@renderheads.com.

No problem at all! We haven't received explicit permission for the video files yet, but should be able to get a test video up later this week.

> It'd probably be better to concatenate the videos into one single video and play a portion of it on each display, if that's an option? This is your best bet.

That is an interesting solution which we'll keep in mind for some special cases, but most of the time this is going to affect the end-user who will be uploading the video to our application. Ideally, we want to leave their videos separate to avoid unnecessary complexity and for other various reasons.

> You could try lowering the buffer demands in each video - see Android-specific settings in the MediaPlayer component.

We'll try this! There's a "minimum/maximum buffer ms" and "buffer for playback ms" setting. Which one should we be changing? The "minimum/maximum buffer ms" sticks out to me since those are set to 50 seconds, as opposed to the "buffer for playback ms" that is already pretty low (set to 2500 ms).

> Also a good idea to keep up to date with the AVPro Video versions as we keep up to date with the latest ExoPlayer versions.

We have recently updated to 2.1.8 already since it was released, but will keep on the lookout for releases that include ExoPlayer updates.

**Comment by AndrewRH** [comment]
@Kevinsomnia AVPro Video  2.2.0 was just released and includes a big ExoPlayer update

Also I'm not sure whether you're using the OES rendering path - that can save memory and improve performance.

Thanks,

**Comment by RenderHeadsSte** [comment]
@Kevinsomnia Did the last update address your issue?

**Comment by Kevinsomnia** [comment]
> @Kevinsomnia Did the last update address your issue?

We upgraded the version and reduced the min and max buffer duration and it seemed to reduce crashing frequency. I think it can still crash in some scenarios where the use r wants to play many HD videos at once, but we're also working on mitigating this on our client. I will let you know if we encounter any issues. Thanks!
