### ISSUE TITLE
Player freezes on iOS when app loses and regains focus

### ISSUE THREAD

**Issue by zorusantos** [RenderHeads/UnityPlugin-AVProVideo#91]
When the app goes to the background while a video is playing, it pauses like it should. But when the app regains focus, the video does not resume playing on iOS only. The app is still running fine, I can close the video via a skip button. Both the 'Pause media' and 'Play Media' check boxes are checked. I've even manually called 'play()' via script when the app unpauses. It doesn't happen all of the time but it's likely to happen if you go all the way back to the os, tap some other things. Works on android and windows.

 - Unity version: 2019.1.6f1
 - AVPro Video version: 1.9.17
 - Operating system version: iOS 12 to 10
 - Device model: iPhone 6 to latest
 - Video specs (resolution, frame-rate, codec, file size):  1 video, loaded from disk. 1920x1080, 30fps, mp4 H264, 40 seconds long

**To Reproduce**
1. With 'Pause media' and 'Play Media' checked in media player, Start playing video
2. Switch app to background during playback. Go all the way back to os, tap something else, slide screen or anything.
3. Go back to app. May have to repeat a couple of times, not 100%

**Logs**
Console output shows logs from media player saying player is paused and player started playing from the 'Pause media' and 'Play Media' checkboxes.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by zorusantos** [comment]
Using Display_UGUI component.

**Comment by AndrewRH** [comment]
@MorrisRH any feedback?

**Comment by MorrisRH** [comment]
The default behaviour on iOS is to pause playback when an application enters the background state. Unfortunately the pause media on app pause code does not still well with this.

A fix will be available in the next release.

**Comment by zorusantos** [comment]
Thanks,
That's great, we look forward to the next release. Any estimates as to when that will be?

**Comment by zorusantos** [comment]
My work around fix on iOS is to cache the current location in the video when the app is paused and close it. When the app is unpaused I load the video again and seek to the cached position. This causes a white screen to flash for a second or two but it works. Is there any chance an official release is coming in the next week or so?

**Comment by MorrisRH** [comment]
I'm not sure when the next release will be (it should be soon). You can implement the fix yourself by editing MediaPlayer.cs as follows:
Find the OnApplicationPause method, it should be around line 1989.
Replace the call to m_Control.Pause() with:
```
#if !UNITY_IPHONE
						m_Control.Pause();
#endif
```

**Comment by MorrisRH** [comment]
Next release should be this Friday (5th July).

**Comment by zorusantos** [comment]
Awesome! Thanks!
