### ISSUE TITLE
[2.1.6] Using GrabAudio() in AudioOutputManager to obtain 6 channel audio data is orderless in Android

### ISSUE THREAD

**Issue by cross6180** [RenderHeads/UnityPlugin-AVProVideo#910]
**Describe the issue**
I am trying to get all audio raw data in the Android platform. I get all the 6 channels raw data by the GrabAudio() function in the AudioOutputManager.cs, but find out that the data array is orderless shown in the log. However, it works normally in Windows. Is there something I missed? Thank you.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.10f1
 - AVPro Video version: v2.1.6 trial version
 - Operating system version: Android 10
 - Device model: VR HMD
 - Video specs (resolution, frame-rate, codec, file size):  mp4 video container with H.264 codec and a single 6-channel audio track

**Logs**
[log_6channel_audiodata_orderless.txt](https://drive.google.com/file/d/17wZITJIpvkWx8mP4xy5MBqPYaJw3zEVf/view?usp=sharing)

**Screenshots**
![image](https://user-images.githubusercontent.com/12931387/130949926-8b384452-3da0-49c7-8091-993c02401d4a.png)

**Comment by cross6180** [comment]
Hi,

Attached the [video file](https://drive.google.com/file/d/1t6JM9jmAqcHvpOmhFnOGCVtSf7sJDuP9/view?usp=sharing)
If you need any other information, please let me know.
Any suggestion would be much appreciated. Thank you.

**Comment by shazamk** [comment]
This was something I was experiencing back in April but didn't get a chance to report it. We were attempting to playback certain channels from a 6 channel audio stream on Android and it sounded terrible. After taking a closer look it seemed like overtime the samples we received from GrabAudio() would shift similar to what was described above. Hopefully a solution can be found as it would be great to have this functionality!

**Comment by RenderHeadsSte** [comment]
Thanks for reporting this issue.  Sorry it has taken a while to get to looking into it.  I have reproduced it here using your sample and think I have a fix to offer.  Will hopefully include it in the next release (likely to be v2.2.0)

Here are screenshots of what I get logged in the editor and what I get from an Android device...

![image](https://user-images.githubusercontent.com/46531149/132326849-0586400e-2a20-419f-9c36-87981b88c586.png)
![image](https://user-images.githubusercontent.com/46531149/132326899-e15923d9-abfd-4e81-8056-bd4a084c651f.png)

**Comment by cross6180** [comment]
Hi @RenderHeadsSte,

Thank you so much. Could I get the fix to try first?
And when are you going to release v2.2.0?
Thank you.

**Comment by RenderHeadsSte** [comment]
We are aiming to release in the coming days.  As the timeframe is short, we would not be able to do you a pre-release in this instance.  Sorry!

**Comment by AndrewRH** [comment]
Version 2.2.0 of AVPro Video has been released now and should resolve this issue.  Please let us know if you have any more problems.

**Comment by cross6180** [comment]
Just tested the v2.2.0 and it's resolved. Thank you.
