### ISSUE TITLE
some android device can't play video

### ISSUE THREAD

**Issue by 3023992558** [RenderHeads/UnityPlugin-AVProVideo#911]
**Describe the issue**
oppo find2 can't play video. the screen is black. but other device is ok

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.26f1
 - AVPro Video version: v2.1.6
 - Operating system version: android 11
 - Device model: oppo
 - 

**Logs**
I/Unity: s_Interface UnityEngine.AndroidJavaObject
W/ogame.gmmx.tes: Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)

I/ExoPlayerImpl: Init 7faf349 [ExoPlayerLib/2.14.0] [OP4A7A, PDEM30, OPPO, 30]
D/AudioManager: getStreamVolume packageName=com.hariogame.gmmx.test, index=7, streamType=3

I/Unity: m_Video UnityEngine.AndroidJavaObject

I/Unity: [AVProVideo] Creating player 0

I/Unity: [AVProVideo] Initialising AVPro Video v2.1.6 (native plugin v2.1.4f1-core) on Adreno (TM) 650/OpenGL ES 3.2 V@0495.0 (GIT@927834c376, I46bb81ccf7, 1596634087) (Date:08/05/20) (MT True) on Android

I/Unity: [AVProVideo] Opening jar:file:///data/app/~~gDG7Vuel3OBuVWISW5eJHA==/com.hariogame.gmmx.test-sNQqp9rCGr6jXlqpelM1Xg==/base.apk!/assets/jar:file:///data/app/~~gDG7Vuel3OBuVWISW5eJHA==/com.hariogame.gmmx.test-sNQqp9råCGr6jXlqpelM1Xg==/base.apk!/assets/58f0e57eb90c4a1a363b773b181c90b5.mp4 (offset 0) with API ExoPlayer

W/ogame.gmmx.tes: Accessing hidden method Ljava/nio/NIOAccess;->getBaseArray(Ljava/nio/Buffer;)Ljava/lang/Object; (greylist,core-platform-api, JNI, allowed)
W/ogame.gmmx.tes: Accessing hidden method Ljava/nio/NIOAccess;->getBaseArrayOffset(Ljava/nio/Buffer;)I (greylist,core-platform-api, JNI, allowed)

**Comment by 3023992558** [comment]
it's cause by android 11? do you have any tips, thank you

**Comment by kahnivore** [comment]
Hi, yes please see [here ](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#plugin-specs)for supported Android API levels.

**Comment by 3023992558** [comment]
Hi

Sorry for the late reply.

My Device is oppo find x2 pro(PDEM30, cpu: Snapdragon 865， mem:12G). system: coloros11/android11. Other Device is fine. I test many kinds of devices. It's all fine. event low config than this one.

My Video Params is:
format : AVC
格式/信息 : Advanced Video Codec
format quality : High@L5.1
format param, CABAC : No
format param, ReFrames : 4 frames
time : 38s 600ms
Duration_LastFrame : 67ms
ratio mode : VBR
ratio : 4 416 Kbps
ratio avg : 4 701 Kbps
width : 720 pixels
height : 1 280 pixels
fps : 30.000 fps
color space : YUV
color bit : 8 bits
resolution : 720x1280(0.563)

do you need any other infomation.

thanks!

**Comment by AndrewRH** [comment]
If you try to play a video that contains audio - do you hear the audio?

Also, could you post the full log?

Thanks,

**Comment by 3023992558** [comment]
Hi

The video is no audio.

the full log see the attach file

Thanks
[logcat.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7127529/logcat.log)

**Comment by 3023992558** [comment]
do u have any suggest?

**Comment by RenderHeadsSte** [comment]
How strange,  That device should eat that video up for breakfast!  It is more than capable.

Do other videos play on the device?  Have you tried the sample videos included in the AVPro Video package?

**Comment by RenderHeadsSte** [comment]
Also, we are running random spot checks on support tickets.  I wonder if you would be so kind as to provide the invoice number that is printed on your PDF invoice?  IF you would rather not make this public you can sent it to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) with the subject line #911.  Thanks

**Comment by 3023992558** [comment]
i'll try the sample video. it's so stange. no any error in log

**Comment by 3023992558** [comment]
the demo video can't play too😂

**Comment by 3023992558** [comment]
i find the root cause

i change android platform options. from `exoplayer` -> `mediaplayer`.  then it's work!
