### ISSUE TITLE
Cannot render UI text over video

### ISSUE THREAD

**Issue by FlyingFlambe** [RenderHeads/UnityPlugin-AVProVideo#916]
A client requested that we display banner text over the video being played (not a subtitle), as well as an in-game text console that can be used during the video.

The issue is that anything that is enabled in the scene, such as the UI, is covered up by the video. Changing the layer order of the video (via Display IMGUI's Use Depth / Depth value) and the UI canvas (Canvas's sort order) also has no effect.

**Comment by kahnivore** [comment]
Hi there,

See [this note](https://www.renderheads.com/content/docs/AVProVideo/articles/component-display-imgui.html#display-imgui) on IMGUI, it is always rendered last (on top of everything else) - it uses the legacy IMGUI rendering system.

The [Display UGUI](https://www.renderheads.com/content/docs/AVProVideo/articles/component-display-ugui.html) uses the Unity UI system and should be placed under a canvas. This will work with sort order etc.

**Comment by FlyingFlambe** [comment]
Thanks! This is working as expected.
