### ISSUE TITLE
Error trying to play 8K video on Quest

### ISSUE THREAD

**Issue by spustlik** [RenderHeads/UnityPlugin-AVProVideo#917]
**Describe the issue**
I get this error while playing VR video on Oculus Quest, but it is ok on Oculus Quest 2 (owned, primary development platform).
Error is too general and It is not simple for me to do some more investigation with hands on Oculus Quest (not owning any).
My guess is that my video resolution (8Kx4K) is too high for Oculus Quest, my resolution goes from some recommendation from web, and our observation of best visual experience on Quest 2.

**Your Setup (please complete the following information):**
 - Unity version: 2020.2.6f1 
 - AVPro Video version: AVPro Video - Core Android Edition 2.1.0
 - Operating system version: Android 10 (from Quest specification)
 - Device model: Oculus Quest
 - Video specs (resolution, frame-rate, codec, file size): 8000x4000, 25, H264, 5MB, Equirectangular projection

**To Reproduce**
1. Use MediaPlayer unity component to show attached video in VR mode
https://user-images.githubusercontent.com/1135561/131536221-68fd292a-69a4-43c1-bc90-4609a2ec7a0f.mp4

Thank you for any help, or any settings of AVPro to get more detailed info about this error.

**Comment by kahnivore** [comment]
This sounds like a hardware issue most likely related to the high resolution of your video - especially if it plays on Quest 2 and not Quest. 

There are some things you could try to optimise your video/environment:

1. Use OES playback- see [here ](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#oes-playback-path)
2. Re-encode your video - H.264 is not meant to cater for such high resolutions. Furthermore, Quest does not support 8k. See [here ](https://creator.oculus.com/blog/encoding-high-resolution-360-and-180-video-for-oculus-go/) for specific encoding recommendations for Quest and Quest 2.

**Comment by spustlik** [comment]
Reencoding video to lower resolution helped, but of course quality is much worse. Now we will try to find best resolution to work on both devices.
Thank you, Jan
