### ISSUE TITLE
Multiple players setup crash on iOS (EXC_BAD_ACCESS) on video switch

### ISSUE THREAD

**Issue by thomasglitchr** [RenderHeads/UnityPlugin-AVProVideo#918]
**Describe the issue**
I get a EXC_BAD_ACCESS crash on iOS when I switch media reference on a player. My scene has 4 MediaPlayer that are synced together. Videos are displayed with 4 DisplayUGUI components. When you swipe on a displayugui component, you can change the mediareference of the corresponding player.
If you repeat the switch video several times, the app crashes with a EXC_BAD_ACCESS on iOS. It works fine on Android build.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.16f
 - AVPro Video version: 2.1.8
 - Operating system version: iOS 14.7.1
 - Device model: iPhone XR
 - Video specs (resolution, frame-rate, codec, file size): 4 videos, 25, 1080x480, h264, < 1MB per file 

**To Reproduce**
1. Setup 4 MediaPlayer on your scene
2. Place an overlay canvas with 4 DisplayUGUI components attached to each player
3. Add buttons to be able to switch mediareference on each player
4. Spam mediareference switch

**Logs**
No logs available, only thread crash
<img width="1420" alt="Capture d’écran 2021-09-01 à 10 55 30" src="https://user-images.githubusercontent.com/84090677/131642581-c54359a6-2140-4ab7-8c95-a76e465d6502.png">

**Comment by devgl** [comment]
I am experiencing the similar problem after some frequent OpenMedia/CloseMedia operations on my iMac.
The Unity Editor log file reports EXC_BAD_ACCESS(read NULL) after this Metal call : CVMetalTextureCacheCreateTextureFromImage.

**Comment by thomation** [comment]
Crash after call Native.AVPPlayerClose(_player);

**Comment by MorrisRH** [comment]
This has been fixed and will be available in the next release, version 2.2.0

**Comment by AndrewRH** [comment]
Version 2.2.0 of AVPro Video has been released now and should resolve this issue.  Please let us know if you have any more problems.

**Comment by efeurun** [comment]
Seems like an escalating issue at Version 3.0.2;

https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1880
