### ISSUE TITLE
May cause problems when playing back loops.

### ISSUE THREAD

**Issue by YonahaShota** [RenderHeads/UnityPlugin-AVProVideo#919]
**Describe the issue**
Streaming playback is used.
When looping the video, there will be a slight gap between the video and audio after the second loop.

(Machine translation was used. We apologize for any errors.)

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.15f1
 - AVPro Video version: 2.1.4
 - Operating system version: Android 11
 - Device model: Pixel 3a 
 - Video specs (resolution, frame-rate, codec, file size): 1920 × 888, 59.94 fps, H.264, 1.9mb

**To Reproduce**
1. Check the Loop checkbox in the MediaPlayer.
2. Set MediaPlayer.AudioOutput to Unity.
3. Execute.  OpenMedia(MediaPathType.AbsolutePathOrURL, the path where the video is located, false)

**Videos**
The second and subsequent times, the audio will be played before the video.

https://user-images.githubusercontent.com/59715982/131686663-4535533b-28fd-4368-8e5e-e5df5edefdfa.mp4

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by YonahaShota** [comment]
Also.When looping iOS using the same playback procedure, the first few frames of the video may be skipped or the audio may not play in the second and subsequent playback.

iPhone 12(14.7.1) 
AVProVideo(2.1.8)

**Comment by kahnivore** [comment]
Hi,

Could you please try/let us know the following:

1. Have you tried setting the Android -> Audio Output in your Media Player component to 'System Direct'? 
2. What is the audio codec of your media?
3. Would it possible to send your video to unitysupport@renderheads.com?

**Comment by YonahaShota** [comment]
Hello, thanks for replying!

> 1. Have you tried setting the Android -> Audio Output in your Media Player component to 'System Direct'?

I tried 'System Direct' and had the same problem on Android and iOS.

I’m implementing a screen capture feature based on NatCorder right now, which requires audio output from an AudioSource, so the Audio Output should be 'Unity'.

> 2. What is the audio codec of your media?

aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 120 kb/s (default)

> 3. Would it possible to send your video to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com)？

Yes, I sent you an email with the same subject as the title of this one, with the video I used for the sample attached.

**Comment by YonahaShota** [comment]
Hello.
While testing to work around the problem, we observed a strange behavior on iOS.

iPhone 12(14.7.1)
iPhone 8(12.1.4)

 1. Control.GetCurrentTime() retrieved by Update shortly after playing the video had a negative value.
I am using it to find out the playing time of a video, but I cannot figure out why the value is negative.
Is there a more appropriate way?

2. When the above problem occurred during loop playback, the playback was paused and then restarted.
When I did so, the value of GetCurrentTime() became larger than Info.GetDuration(), and the playback resumed from frame 0.

3. When I do streaming playback, I can play the video perfectly once, but after the second time, the video does not play when I run Rewind or Play.
This has only been confirmed on the iPhone 8.

It would be best to fix the loop problem, but if there is a workaround, please let me know.

**Comment by kahnivore** [comment]
Are you streaming the video from a server? Or are you playing it locally.

**Comment by YonahaShota** [comment]
Streaming from S3.
URL: https://dev.s3.ap-northeast-1.amazonaws.com/avprovideos/AvProVideo2test.mp4

**Comment by kahnivore** [comment]
Thanks. Still not managing to reproduce this. Can you try setting the path of the media player to your video in the Demo_MediaPlayer scene and testing to see if the problem persists?

**Comment by YonahaShota** [comment]
Thank you for confirming this.
I tested it by editing the path in the Demo_MediaPlayer scene.
If the AudioOutput is set to 'Unity', there will be a sound gap during loop playback.

**Comment by kahnivore** [comment]
This is a long shot but have you tested it without the screen recording setup you have? Wondering if there's a chance that that is interfering somehow.

**Comment by ArakakiYuki** [comment]
This issue is still occurring.
In the following combinations, there will be a gap between the video and sound even if you have not captured the screen or played it for a long time.

-Play the sound source from Unity
-Enable for loop playback
