### ISSUE TITLE
Stereo Mode(T/B) Issue

### ISSUE THREAD

**Issue by wolrdboss** [RenderHeads/UnityPlugin-AVProVideo#92]
**Describe the bug**
Hello Support Team

How are you ? I have one problem on Stereo Player Mode.

I used AV Pro (Windows) shader for playing 360 Stereo Images.

But I knew it was normal 360 Degree mode and no stereo mode.
Please help me how to play Stereo (T/B) mode. I selected T/B mode on shader for stereo mode.

**Your Setup (please complete the following information):**
 - Unity version: 5.6.1
 - AVPro Video version: 1.9.17b 
 - Operating system version:  Windows 10
 - Device model:  Oculus Rift
 - Video specs (resolution, frame-rate, codec, file size): 
Resolution : 5760 X 5760, 3840 X 2160

http://traveltimevr.com/Admin/uploads/picture/1559298491.jpg
http://traveltimevr.com/Admin/uploads/picture/1559298491.jpg

**Screenshots**
![image](https://user-images.githubusercontent.com/17884465/60086738-3bface00-976e-11e9-92f6-ff79eeac7341.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
I'm not totally sure what your issue it, but if you're using stereo and our shaders, you need to have the UpdateStereoMaterial component in your scene.  On it you need to set the meshrenderer and the camera (main camera, or central eye camera if using a dual camera rig).

Does that helps?

**Comment by wolrdboss** [comment]
Thanks very mush. I fixed
