### ISSUE TITLE
GetDuration and GetDurationFrames return 0 on Android (Pico G2 4K)

### ISSUE THREAD

**Issue by mbzworld** [RenderHeads/UnityPlugin-AVProVideo#921]
**Describe the issue**
I had a project where everything worked fine. I copied the project into a new folder, for some reason GetDuration and GetDurationFrames always return 0 in Pico G2 4K.
The video playback is normal. It opens, play, seek and pause. No issues at all.

**Your Setup (please complete the following information):**
 - Unity version:  2019.4.25f1
 - AVPro Video version:  2.1.1
 - Operating system version: Window 10 Home
 - Device model: Pico G2 4K
 - Video specs (resolution, frame-rate, codec, file size): 4096x4096 30 fps, H265, MP4
The issue also happened while trying to GetDuration for an mp3 file. 

The issue does NOT exist in my previous project that I took copy from using exactly the same Unity/AVPro versions. I suspect that copying the project/folder into another one caused this issue but I am too deep in the new project to start from scratch.

**Comment by kahnivore** [comment]
Would you be able to try GetDuration/GetDurationFrames in one of the demo scenes in your new project? It'd be useful to know if that's returning 0 as well.

**Comment by mbzworld** [comment]
Thanks for getting back to me. 
I tried your 360 demo scene and GetDuration() also resulted in 0, the video played normally. 
I also noticed that the GetDuration() has returned 0 also inside the Editor so this issue is NOT specific to Android.

I tried upgrading into 2.1.8 following the steps you provided but it didn't resolve the issue.

Now, I tried to insert a delay of half a second then use GetDuration() again and it worked!
Please note that I've been using your assets for years now and on several projects, I never had to use a delay for this to work, 
only on this project, which is in fact, a copy made of another project with several adjustments. I can't think how any of these adjustments caused this issue.

**Comment by AndrewRH** [comment]
Functions like GetDuration() only return valid values once the media has loaded the 'metadata'.  Loading is asynchronous (except in DirectShow API), so you can either poll it using mediaPlayer.Info.HasMetaData() or you can subscript to an event to know when metadata is available.

I hope this helps?

**Comment by mbzworld** [comment]
Thanks Andrew! I didn't know that before. What threw me off here is that I didn't have to poll it first in my previous project on the very same device. 
But that was helpful!
