### ISSUE TITLE
Spatial sound problem in Oculus Quest 2

### ISSUE THREAD

**Issue by dh7300** [RenderHeads/UnityPlugin-AVProVideo#924]
**Describe the issue**
[Spatial sound problem in Oculus Quest 2]

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.13f1
 - AVPro Video version: v2.1.8f1-ultra
 - Operating system version: 
 - Device model: oculus quest2
 - Video specs (resolution, frame-rate, codec, file size): 3840x2160 / 30fps / ffmpeg / 1.47GB

**To Reproduce**
1. refer to the document Converting existing ambisonic videos 
2. This mkv video confirms that the spatial sound comes out well in the Oculus TV app 
3. However, when built as an app, there is no spatial sound, and the sound from the left comes out as it is on the left when the user turns back. 

**Logs**

**Screenshots**
<img width="520" alt="mkv" src="https://user-images.githubusercontent.com/69621922/132610724-7cd41d4c-3b2b-4872-b43b-ee800b556b63.png">

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Have you tried other videos?  Maybe try this one, it also has orientation in the video to help.

[ComplexAudio02-Opus-10Ch-FB360.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7135136/ComplexAudio02-Opus-10Ch-FB360.zip)

**Comment by dh7300** [comment]
Thank you very much.

We used the XR Interaction Toolkit, which had an XR Rig instead of the main camera in the Head Transform.

It was a stupid mistake.

Thanks again.
