### ISSUE TITLE
Custom Http Cookie Header for CloudFront protected HLS stream not working in Unity Editor 2020.3.14f1

### ISSUE THREAD

**Issue by smuscroft** [RenderHeads/UnityPlugin-AVProVideo#927]
We are currently evaluating AVPro in order to access our secure library of secure surgical video streams in HLS format hosted on AWS. I have downloaded the latest trial version and I have tried setting the custom http headers field both in the inspector and programmatically to no avail using the instructions provided here :

https://www.renderheads.com/content/docs/AVProVideo/articles/feature-content-protection-ultra.html

Interestingly if I follow the instructions for the inspector provided, the text field turns red and is in an invalid string format. If I remove all new lines and carriage returns it will parse but does not work in editor. If I script in the suggested format it doesn't work either.  

Do I need to purchase the ultra edition for this to work or will it work in the trial version>?

**Your Setup (please complete the following information):**
 - Unity version = 2020.3.14f1
 - AVPro Video version: v2.1.8
 - Operating system version: Windows 10 
 - Device model: PC / Unity Editor
 - Video specs : HLS 1080p 

**To Reproduce**
1.  Run AVPro sample media player scene add HLS url  path and supply cookie string in suggested format.
2.  Receive [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by kahnivore** [comment]
It should work in the trial edition. 

Have you set your API in the Media Player component -> Platform Specific -> Windows -> Video API to WinRT?

**Comment by smuscroft** [comment]
Yes it is set to WinRT. I have managed to get it to work in Editor now by
changing the way in which I obtain the cookie data and build the cookie
string. Next step is to test on Android.
