### ISSUE TITLE
Ambisonics spatial audio format

### ISSUE THREAD

**Issue by plmayer** [RenderHeads/UnityPlugin-AVProVideo#93]
It would be great if the AVPro Video could support the Ambisonics standard on Windows 10 and Android (in particular the Oculus Go and Quest) in mp4 containers.

https://en.wikipedia.org/wiki/Ambisonics
https://support.google.com/youtube/answer/6395969?hl=en

**Comment by AndrewRH** [comment]
Yup :)  We currently only support spatial audio (including ambisonics) on Windows and Android, and only via MKV files with Opus encoded audio.
Hopefully with a bit more time we can extend the support.

**Comment by AndrewRH** [comment]
Actually I think in Windows we might support MP4 - but the audio still needs to be encoded using Opus

**Comment by plmayer** [comment]
Ok, good to know, thanks for responding. We'll check whether we can adapt the workflow to mkv in the meantime.

**Comment by AndrewRH** [comment]
Closing this as it's basically a dup of #62
