### ISSUE TITLE
Non-filtered Video Texture at first OpenMedia after instantiate

### ISSUE THREAD

**Issue by c0ffeeartc** [RenderHeads/UnityPlugin-AVProVideo#930]
Hello, we have an issue on iOS - video looks aliased at first OpenMedia after instantiate.

**Project setup:**
  - There is a prefab with MediaPlayer UGUI with filterMode = Bilinear
  - Prefab is instantiated, half second passes, then MediaPlayer opens streaming media
  - later same MediaPlayer opens other video links

**Setup:**
 - Unity version: 2020.3.9f1
 - AVPro Video version: 2.1.8
 - Operating system version:  Windows10
 - Device model: iPad7 iOS 14.7.1
 - Video specs (resolution, frame-rate, codec, file size): 1920x1080, streaming from Vimeo service, adaptive resolution

**To Reproduce**
1. On iOS
2. Instantiate AvPro mediaPlayer UGUI
3. Open remote streaming video with adaptive resolution
4. Observe jagged alias lines not matching filterMode = bilinear
5. Open other video within same mediaPlayer instance
6. Observe smooth image quality filterMode = bilinear 

FilterMode gets fixed when listening to `MediaPlayerEvent.EventType.MetaDataReady` and `MediaPlayerEvent.EventType.FirstFrameReady` and setting `mediaPlayer.TextureFilterMode = FilterMode.Bilinear` when those events are triggered.

Also if video starts at lower resolution and looks blurry and pixelated then gets to higher resolution - above hack fix doesn't work, and video again looks aliased.

**Comment by MorrisRH** [comment]
Are you able to provide example images of what you mean by aliased?
There is no difference in how the textures are produced between the first frame and the last frame so not quite sure what is happening here.

**Comment by c0ffeeartc** [comment]
Hello, thanks for answering.
 By "Aliased" I mean Point filtering without antialiasing.  I'll provide image example in few days during work hours.

It's not related to first or last frame.
In iOS `MediaPlayer.TextureFilterMode` is set to Point disregarding settings, and remains so until next video is opened, then TextureFilterMode gets set to correct value.

Since video resolution is adaptive this may or may not be related to switching from one video resolution to another.
Another place of interest is assigning value to `MediaPlayer.TextureFilterMode` won't apply to texture if `MediaPlayer.Control == null`(please correct if recalled wrong)

**Comment by MorrisRH** [comment]
A fix will be provided in the next release.

**Comment by AndrewRH** [comment]
@c0ffeeartc the new release 2.2.1 is out with this fix - please let us know whether this resolves the issue for you.

Thanks,

**Comment by AndrewRH** [comment]
Closing this issue - assume fix worked
