### ISSUE TITLE
Manifest and segments are downloaded twice for short HLS streams after upgrading AVPro from v1.10.x to v2.2.0.

### ISSUE THREAD

**Issue by PhannGor** [RenderHeads/UnityPlugin-AVProVideo#931]
Manifest and segments are downloaded twice for short HLS streams after upgrade from AVPro Video v1.10.x to v2.2.0.
Reproducible on both iOS and Mac OS.

**Setup:**
 - Unity version: 2019.4.23f1
 - AVPro Video version: 2.1.8, 2.2.0
 - Operating system version: Mac OS BigSur 11.5.2, iOS 14.7.1
 - Device model: MB Pro 2017, iPhone X
 - Video specs (resolution, frame-rate, codec, file size): 
 (issue present)
 https://content-test.frever-content.com/Assets/TestVideo/1/Thumbnail/video_HD.m3u8
(no issues)
 https://content-test.frever-content.com/Assets/TestVideo/2/Thumbnail/video.m3u8

**Steps to reproduce**
1. Setup simple project with MediaPlayer and DisplayUGUI
2. Set the following source (or any short HLS stream with 1-3 segments):
 https://content-test.frever-content.com/Assets/TestVideo/1/Thumbnail/video_HD.m3u8
3. Run Telerik Fiddler or another network debugging tool

On version 1.10.x only 3 requests will be shown:
One for *.m3u8 file and two for 2 correspondings *.ts segments

On version 2.10.x 6 requests will be shown:
Two for *.m3u8 file and four for 2 correspondings *.ts segments

Note: with longer HLS streams (for example: https://content-test.frever-content.com/Assets/TestVideo/2/Thumbnail/video.m3u8) all seem to work OK.

**Comment by MorrisRH** [comment]
This is correct. To improve looping performance we have two instances of the asset loaded and then switch between the two as this is significantly faster than a seek to time 0.

**Comment by PhannGor** [comment]
@MorrisRH is there a way to disable this behaviour? It has significant impact for our app, because we're loading loot of small videos in a feed when app starts. In case of low speed connection difference could be significant.

**Comment by MorrisRH** [comment]
Currently there is no way to disable this. We'll look into implementing something for the next release.
Are the videos you're playing back looping?

**Comment by PhannGor** [comment]
Thank you for response, we'll wait for next release then. Yes, those videos are looping but looping performance is less important for us than bandwidth.

**Comment by PhannGor** [comment]
And another idea, even in case of two instances of player for better looping performance - maybe it is possible to reuse already dowloaded segments? Is there a real need to do additional requests for same manifest and segment files?

**Comment by MorrisRH** [comment]
Unfortunately the requests are part of the low-level player and not something we have direct control over.

We're adding a flag to the platform specific settings for macOS and iOS to allow for looping to just use a single player with a seek to 0 when playback completes. There will be a slight stutter at the loop point.

**Comment by MorrisRH** [comment]
The new option is in the platform specific settings for iOS, macOS and tvOS, look for ```Use single player item```.
This will be available in the next release, version 2.2.1

**Comment by AndrewRH** [comment]
@PhannGor the new release 2.2.1 is out - please let us know whether this resolves the issue for you.

Thanks,

**Comment by PhannGor** [comment]
@AndrewRH Thank you! Just installed new version, enabled "single player" option and all works like charm now.
