### ISSUE TITLE
Video stereo bad quality and stops after 10 seconds

### ISSUE THREAD

**Issue by Angellourido** [RenderHeads/UnityPlugin-AVProVideo#935]
**Describe the issue**
Video stereo bad quality and stops after 10 seconds I can't find the good config after the update of avpro fot Android
what I need is the correct configuration of the new version

**Your Setup (please complete the following information):**
 - Unity version: 2021
 - AVPro Video version: 2.2.0
 - Operating system version: windows10
 - Device model: oculus quest
 - Video specs (resolution, frame-rate, codec, file size): 
MPEG-4 (Base Media): 1.40 GiB, 2 min 0 s
1 Video stream: HEVC.  96.4 Mb/s, 5760*5760 (1.000), at 60.000 FPS, HEVC (Main)  Overall bit rate: 100 Mb/s

**To Reproduce**
1. 
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Angellourido** [comment]
Xith the update of the version all videos 360 become Blue[](url)
![avproblue](https://user-images.githubusercontent.com/86773188/134766998-1afc5191-92b1-4ac8-93dd-f72b549700ad.JPG)

**Comment by Angellourido** [comment]
The videos are the same than I used in the previws version.
Its the samething for Mono or Stereo videos.

**Comment by kahnivore** [comment]
Could you please send the video you're testing with to unitysupport@renderheads.com with "#925" in the subject line?

**Comment by kahnivore** [comment]
Are you building for Quest or Quest 2?

**Comment by Angellourido** [comment]
Hi I’m building in Quest 1 and 2



I can send you a video if you want.



 



The videos are perfect in the oculus Tv player



Here you have the mediainfo for two videos



 



One video mediainfo



General



Complete name                            : D:\FILES-ECLOX-VIDEOS-AUDIOS-LANGUAGES\Movies\Video360Stereo\en\1.mp4



Format                                   : MPEG-4



Format profile                           : Base Media / Version 2



Codec ID                                 : mp42 (isom/iso2/mp41)



File size                                : 1.40 GiB



Duration                                 : 2 min 0 s



Overall bit rate                         : 100 Mb/s



Encoded date                             : UTC 2021-05-16 11:58:45



Tagged date                              : UTC 2021-05-16 11:58:45



Writing application                      : HandBrake 1.3.3 2020061300



 



Video



ID                                       : 1



Format                                   : HEVC



Format/Info                              : High Efficiency Video Coding



Format profile                           : ***@***.***@High



Codec ID                                 : hvc1



Codec ID/Info                            : High Efficiency Video Coding



Duration                                 : 2 min 0 s



Bit rate                                 : 100 Mb/s



Width                                    : 5 760 pixels



Height                                   : 5 760 pixels



Display aspect ratio                     : 1.000



Frame rate mode                          : Constant



Frame rate                               : 60.000 FPS



Color space                              : YUV



Chroma subsampling                       : 4:2:0



Bit depth                                : 8 bits



Bits/(Pixel*Frame)                       : 0050



Stream size                              : 1.40 GiB (100%)



Encoded date                             : UTC 2021-05-16 11:58:45



Tagged date                              : UTC 2021-05-16 11:58:45



Color range                              : Limited



Color primaries                          : BT.709



Transfer characteristics                 : BT.709



Matrix coefficients                      : BT.709



Codec configuration box                  : hvcC



 



Audio



ID                                       : 2



Format                                   : AAC LC



Format/Info                              : Advanced Audio Codec Low Complexity



Codec ID                                 : mp4a-40-2



Duration                                 : 2 min 0 s



Bit rate mode                            : Constant



Bit rate                                 : 319 kb/s



Channel(s)                               : 2 channels



Channel layout                           : L R



Sampling rate                            : 48.0 kHz



Frame rate                               : 46.875 FPS (1024 SPF)



Compression mode                         : Lossy



Stream size                              : 4.57 MiB (0%)



Title                                    : Stereo



Language                                 : English



Default                                  : Yes



Alternate group                          : 1



Encoded date                             : UTC 2021-05-16 11:58:45



Tagged date                              : UTC 2021-05-16 11:58:45



 



Second video



 



 



General



Complete name                            : D:\FILES-ECLOX-VIDEOS-AUDIOS-LANGUAGES\Movies\Video360Stereo\en\8.mp4



Format                                   : MPEG-4



Format profile                           : Base Media / Version 2



Codec ID                                 : mp42 (isom/iso2/mp41)



File size                                : 1.75 GiB



Duration                                 : 2 min 30 s



Overall bit rate                         : 100 Mb/s



Encoded date                             : UTC 2021-05-16 11:24:25



Tagged date                              : UTC 2021-05-16 11:24:25



Writing application                      : HandBrake 1.3.3 2020061300



 



Video



ID                                       : 1



Format                                   : HEVC



Format/Info                              : High Efficiency Video Coding



Format profile                           : ***@***.***@High



Codec ID                                 : hvc1



Codec ID/Info                            : High Efficiency Video Coding



Duration                                 : 2 min 30 s



Bit rate                                 : 100 Mb/s



Width                                    : 5 760 pixels



Height                                   : 5 760 pixels



Display aspect ratio                     : 1.000



Frame rate mode                          : Constant



Frame rate                               : 60.000 FPS



Color space                              : YUV



Chroma subsampling                       : 4:2:0



Bit depth                                : 8 bits



Bits/(Pixel*Frame)                       : 0050



Stream size                              : 1.75 GiB (100%)



Encoded date                             : UTC 2021-05-16 11:24:25



Tagged date                              : UTC 2021-05-16 11:24:25



Color range                              : Limited



Color primaries                          : BT.709



Transfer characteristics                 : BT.709



Matrix coefficients                      : BT.709



Codec configuration box                  : hvcC



 



Audio



ID                                       : 2



Format                                   : AAC LC



Format/Info                              : Advanced Audio Codec Low Complexity



Codec ID                                 : mp4a-40-2



Duration                                 : 2 min 30 s



Bit rate mode                            : Constant



Bit rate                                 : 319 kb/s



Channel(s)                               : 2 channels



Channel layout                           : L R



Sampling rate                            : 48.0 kHz



Frame rate                               : 46.875 FPS (1024 SPF)



Compression mode                         : Lossy



Stream size                              : 5.70 MiB (0%)



Title                                    : Stereo



Language                                 : English



Default                                  : Yes



Alternate group                          : 1



Encoded date                             : UTC 2021-05-16 11:24:25



Tagged date                              : UTC 2021-05-16 11:24:25



 



 



 



 



 



 



Envoyé à partir de Courrier pour Windows



 




Obtener Outlook para Android

**Comment by kahnivore** [comment]
Hi @Angellourido 

Could you please answer the following questions (reposting from above). It's a little difficult to know how to assist without having enough detail about the problem. 

1. Which version of Unity exactly are you using?
2. "Video stereo bad quality and stops after 10 seconds I can't find the good config after the update of avpro fot Android
what I need is the correct configuration of the new version" < could you clarify what you mean? what do you mean by a "good config"? Was the issue caused by upgrading? If so, which version did you upgrade from?
3. Do you have a screenshot of the issue?
4. Please send a log from Android around the time when it stops playback.
5. Have you tried re-encoding the video at a lower resolution / bit-rate?
6. Have you tried using OES mode?

Thanks!
