### ISSUE TITLE
iOS 14: Returning from background while running video can crash app on certain devices with AVPro 2.2.0

### ISSUE THREAD

**Issue by Marcurion** [RenderHeads/UnityPlugin-AVProVideo#936]
**Describe the issue**
While AVPro is playing, when entering the background and returning, the app will crash.
We observed this on several devices . We noticed on one device this issue appeared after upgrading to iOS 14 (it was not an issue with iOS 13) 

**Your Setup (please complete the following information):**
 - Unity version: 2020 LTS
 - AVPro Video version: 2.2.0
 - Operating system version: iOS
 - Device model: iPad (2018), iPad Pro 9.7"
 - Video specs (resolution, frame-rate, codec, file size): AVPro example file

**To Reproduce**
You can use the linked project and .ipa at https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/853#issuecomment-925565459

Start the video with the PlayAgain button or set the Restart toggle and wait for the video to play.
Switch to another app e.g. iOS Settings.
Switch back to the Unity app.
The app will crash.

We encountered this behavior on all our 2 GB Ram Apple devices with iOS 14. Strangely this was not observed on an iPhoneX with iOS 14.

**Comment by dalkia** [comment]
I can second this issue. It also happens to me in my iPad Pro iOS 15.0

**Comment by MorrisRH** [comment]
Currently unable to reproduce this with the soon to be released version 2.2.4.
I suspect that the fix for #853 and #1000 has also resolved this issue.

**Comment by AndrewRH** [comment]
@Marcurion  AVPro Video 2.2.4 has just been released and should resolve the issue you reported.  Thanks,
