### ISSUE TITLE
Render quality difference between Trial edition and Core edition

### ISSUE THREAD

**Issue by cross6180** [RenderHeads/UnityPlugin-AVProVideo#937]
**Question**
I am encountering a render thread loading issue (GPU bound) when playing 6k 360 videos using the v2.0.9 core edition.
However, when playing with the v2.0.9 and v2.2.0 trial editions, this issue does not exist.
Is there a texture resolution limit with the trial edition? Or any other possible reasons for this happening?
Thank you.

**Comment by AndrewRH** [comment]
Could you let us know  which platform you're seeing this on?  Also could you give more details on the issue you're having exactly.

The trial version is effectively the Ultra Edition but with a watermark applied.  There is no resolution limit.  However Core Edition is slightly different as it doesn't have some features such as Hap/NotchLC decoding so there's a chance that this could affect things.  

If you can give more details and an example then we'll be able to dig further.

Thanks,

**Comment by cross6180** [comment]
I am using the Android platform and in VR HMD. 
The issue I encountered is that there are white noises in the final rendering texture on HMD.
I played the 360 videos with the Demo_360Stereo scene, this issue only happens with 6k. 4k is fine.
From the Unity profiler, the CPU is waiting for the rendering thread.
![image](https://user-images.githubusercontent.com/12931387/134649360-d38cedbe-f98f-4471-8a57-a219896e3e83.png)

**Comment by AndrewRH** [comment]
did you try using OES rendering mode (in Platform Specific > Android settings?

white noise?  could you show us?

**Comment by cross6180** [comment]
No, I didn't try the OES rendering mode.

I will show you a screenshot or video with white noise next week. In the meanwhile, I will try the OES, thank you.

**Comment by cross6180** [comment]
Hi,

I tried the OES rendering mode but only gets a black screen with sound. Not sure if it is because I am using the Unity XR instead of the legacy VR?

And for some reason, sorry I cannot get you a screenshot or video with white noises now. Will the video itself help?
I am still trying to figure out what happened. The only clue I have is that this does not happen in the trial edition and is probably caused by GPU. Is the GPU usage different from the core edition and trial(ultra) edition? Thank you.

**Comment by kahnivore** [comment]
You're welcome to send the video. You can attach it here or send to unitysupport@renderheads.com with "#937" included in the subject line. 

It'd be very useful to see a screenshot of the noise though as if it's device-specific we won't be able to reproduce it. Which Android HMD device are you using exactly?

When you tried the OES mode did you switch the shader to one of the ones that supports OES? See notes on OES mode [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-android.html#oes-playback-path).

**Comment by cross6180** [comment]
Sorry for the late update.
I am using the Vive Focus 3, and still cannot find a way to get a screenshot.
However, I finally got the OES mode to work, and the noise disappear. Thank you.

**Comment by cross6180** [comment]
Yes, I'll close this, thank you.
