### ISSUE TITLE
Unity UI Objects rendering differently in each "eye" in 3d Stereoscopic AV PRO vidoes

### ISSUE THREAD

**Issue by downkirkland** [RenderHeads/UnityPlugin-AVProVideo#939]
**Describe the issue**
A clear and concise description of what the issue is.
When using the 3D Sample from AV PRO, if you do an Unity->UI->Canvas and Unity->UI->Button
The button will render differently in each eye, giving the user a blurry image.  

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.17d1 personal
 - AVPro Video version: 2.2.0 trial build 771
 - Operating system version: MAC 10.14
 - Device model: Oculus Quest 2
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Leverage 360 Demo 
2. Unity->UI->Canvas
3. Unity->UI->Button

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

Are you saying that the button UI element renders differently?  I'm not sure how a button relates to AVPro Video?  Unless you're applying a Material to that button element which is updated by the MediaPlayer?

The only GUI element we support natively is our own [DisplayUGUI ](https://www.renderheads.com/content/docs/AVProVideo/articles/component-display-ugui.html)component.  This is what you should use if you want to display video in the Canvas GUI.

If you're not talking about video but just normal Unity UI then this is not an issue with our plugin.  I suspect you may need to change the Canvas mode from Overlay to World Space and make sure the button isn't too close to the camera.

Does that help?

Thanks,

**Comment by downkirkland** [comment]
Thanks Andrew for the fast response.  Correct the canvas is set to World Space and there is no material to the "button" just an image.  I believe this is how unity is displaying differently in each eye, stereoscopically and when it renders the 2d image it puts in the same world coordinates for left/right eye.  It needs to have an offset.  I believe I will have to write a custom shader that offsets one of the eyes locations.  I was unable to find a shader or blog on this.  Thanks for the help.

**Comment by kahnivore** [comment]
Closing this as it does not seem to be an AVPro Video issue.
