### ISSUE TITLE
[1.9.12] No video only audio, when built on for Android and running on android tv

### ISSUE THREAD

**Issue by optical002** [RenderHeads/UnityPlugin-AVProVideo#945]
I have an empty scene with "Media player" and "Display uGUI". I play from URL where .mkv is served.
I use exo player in media player. I can see the default logo and hear the sound, but no video is displayed. As well everything seems to work fine in editor and 

 - Unity version: 2020.3.16f1
 - AVPro Video version: 1.9.12
 - Operating system version: Android 7
 - Device model: Tcl tv
 - Video specs (resolution, frame-rate, codec, file size): .mkv 1080p

I'm asking to know if there is maybe a solution already to my problem, or some settings used wrong.
Thank you!

**Comment by AndrewRH** [comment]
Hi 1.9.12 is a very old version of AVPro Video - please upgrade to that latest 1.x release which was 1.11.8

Also, Unity 2020 isn't offically supported in AVPro Video 1.x so you may want to try the new AVPro Video 2.x

Thanks,

**Comment by optical002** [comment]
Hello,
Which unity version was supported in 1.9.12?

**Comment by kahnivore** [comment]
1.9.12 was released in January 2019. It'd be worth your while to update to 1.11.7.
