### ISSUE TITLE
Water mark appears when publishing to android

### ISSUE THREAD

**Issue by conan1987** [RenderHeads/UnityPlugin-AVProVideo#95]
I am supposed to have AVPRO 1.9.12 Full Edition and it works fine when publishing to windows but renderhead watermark appears when publishing to android ? how can i fix this and how can i check the version of AVPRO because i work on a laptop belongs to a company not mine so i am not sure about asset version ?
**Your Setup (please complete the following information):**
 - Unity version: 2018.1
 - AVPro Video version: Supposed to be Full 
 - Operating system version: Android
 - Device model:

**Comment by AndrewRH** [comment]
Try reimporting the unitypackage.   I can only imagine that it didn't upgrade to the full package correctly for some reason.
You should probably upgrade anyway as 1.9.12 is quite old now and 1.9.17 is the latest.
Also you can give us your invoice number - then we can verify that it is the full and not just Windows version that was purchased.
To check versions you have to look at the log/console output.  On Windows you can look in the Unity console window when the app runs.  This will only give you the version number for Windows though.  On Android you would need to look at the Android ABD LOG CAT to get the version number as the plugin is loaded.  If the version number ends with a "t" then it is the trial version for that platform.

**Comment by conan1987** [comment]
[log.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/3335891/log.txt)
I attached the log file could you help me in finding the version and know if it is a trial ?

**Comment by AndrewRH** [comment]
The log file is too late, it doesn't include the earlier line where AVPro Video logs the version number.
Regardless - if you're seeing the watermark on Android then it will be using the trial version for Android.  Please try upgrading to the latest version.

Thanks,

**Comment by conan1987** [comment]
after several time of trying to remove old package and re import , it works

**Comment by syedali1621** [comment]
I am facing the similar issue i just bought an ios version but when i run a demo scene logo still on screen. I tried to import and delete project many times but still logo on screen.
