### ISSUE TITLE
[2.2.1] Android build error, conflict due to multiple Guava JAR files 

### ISSUE THREAD

**Issue by oviebd** [RenderHeads/UnityPlugin-AVProVideo#950]
**When I Try to integrate the preview version in my project it can not build the project on Android Platform. But an empty project it will build**

I have tried to implement your plugin in my existing project. It works fine on Editor. But when I try to build it in android it throws some error. I have shared the editor log and a screenshot here. 

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.2f1
 - AVPro Video version: UnityPlugin-AVProVideo-v2.2.1-Trial.unitypackage
 - Operating system version: Windows 10
![error_1](https://user-images.githubusercontent.com/24547882/136322217-f4947f2d-9fe8-446a-a443-31e134c51d95.PNG)
[Editor.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7298837/Editor.log)

**Comment by oviebd** [comment]
Hi, Thanks a lot for your quick response.
I have tried with your instructions but it gives the same error. Would you please guide me again.

**Comment by oviebd** [comment]
Yes. There is jar file named **guava-27.1-android.jar** . What should I do now?

**Comment by LILQK** [comment]
Is there a solution to fix the conflict with guava in other packages? I want to use EXO player in cardboard but cardbord has his own guava, and causes a conflict. Thanks
