### ISSUE TITLE
Video stuttering on Android with URP MSAA enabled

### ISSUE THREAD

**Issue by thomasglitchr** [RenderHeads/UnityPlugin-AVProVideo#952]
**Describe the issue**
All videos are stuttering on Android devices when you build a Unity Project with URP and MSAA 2x enabled. The same build works fine on iOS. If you disable MSAA in your URP asset, it works as expected on Android.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.16f1
 - AVPro Video version: 2.2.0
 - Operating system version: Android 11
 - Device model: Pocophone F1
 - Video specs (resolution, frame-rate, codec, file size): BigBuckBunny-360p30-H264.mp4 (provided sample)

**To Reproduce**
1. Create a new Unity project with Universal Render Pipeline template
2. Setup your URP asset settings with Anti Aliasing x2 (see attached screenshot)
3. Create an overlay canvas with a DisplayuGUI component and a MediaPlayer (auto open, loop), assign a MediaReference
4. Build the scene on Android device
5. The playing video should stutter

**Logs**
No logs available

**Screenshots**
![image](https://user-images.githubusercontent.com/84090677/136523879-d68b3ac5-936a-4d4e-9bc3-d6440229ef26.png)

**Videos**
[Android Capture](https://drive.google.com/file/d/1D6NrHHzqi8K1BwX0etPVXzQrIQNCUaDv/view?usp=sharing)

**Comment by thomasglitchr** [comment]
Hello did you manage to reproduce the issue with the Unity project I've sent you by email last week? It's a major issue for our project right now which makes AV Pro unusable on our scene.

**Comment by kahnivore** [comment]
Thanks for your response.

OES is fine to use - better, even. It's easier on battery use, lower heat, more optimal on GPU etc. 

We'll investigate whether we can reproduce this on Android 11 and keep you posted.

**Comment by AndrewRH** [comment]
@kahnivore 
I've written a version of the Unlit OES shader that support transparent packing - could you test it with no packing, top-bottom packing, and left-right packing please?

[AVProVideo-Unlit-Transparent-AndroidOES.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7372358/AVProVideo-Unlit-Transparent-AndroidOES.zip)

Thanks,

**Comment by RenderHeadsSte** [comment]
@thomasglitchr Give one or both of these a whirl (According to your needs...

[Android_OES_Shaders.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7504939/Android_OES_Shaders.zip)

**Comment by RenderHeadsSte** [comment]
And a small update to the VR shader I sent with a fix for  #968 

[Android_OES_VR_Shaders.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7506486/Android_OES_VR_Shaders.zip)

**Comment by RenderHeadsSte** [comment]
Anything to report @thomasglitchr ?
