### ISSUE TITLE
DllNotFoundException in AVPro Core demo projects in Unity

### ISSUE THREAD

**Issue by drew-512** [RenderHeads/UnityPlugin-AVProVideo#955]
Guys, what the heck.. 

I spent $$$ on this, import AVPro (Core Ed, 2.2.1) into a fresh Unity 2021.1.24 URP project and I get the below DllNotFoundException (below).  Not exactly inspiring me with confidence here...

DllNotFoundException: AVProVideo
RenderHeads.Media.AVProVideo.AppleMediaPlayer..ctor (RenderHeads.Media.AVProVideo.MediaPlayer+OptionsApple options) (at Assets/AVProVideo/Runtime/Scripts/Internal/Players/AppleMediaPlayer.cs:98)
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer (RenderHeads.Media.AVProVideo.MediaPlayer+OptionsApple options) (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1176)
RenderHeads.Media.AVProVideo.MediaPlayer.CreateMediaPlayer () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:1208)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:270)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at Assets/AVProVideo/Runtime/Scripts/Components/MediaPlayer.cs:318)

**Comment by drew-512** [comment]
Unity 2021.1.24 on macOS High Sierra (10.13)

If I were to guess, I but y'all are linking you're macOS against something needed past 10.13.

**Comment by RenderHeadsSte** [comment]
This is covered in the documentation. You can find that in pdf form bundled in the package, or online [here](https://www.renderheads.com/content/docs/AVProVideo/articles/platform-macos.html#plugin-fails-to-load-when-using-macos-versions-older-than-1044-high-sierra-and-mojave).

Please do let us know if this addresses your issue.

**Comment by aalionline** [comment]
hi, 

I am facing DLLNotFound Exception with the following log trace.

`DllNotFoundException: AVProVideo assembly:<unknown assembly> type:<unknown type> member:(null)
RenderHeads.Media.AVProVideo.OSXMediaPlayer.Initialise () (at Assets/AVProVideo/Scripts/Internal/OSXMediaPlayer.cs:397)
RenderHeads.Media.AVProVideo.OSXMediaPlayer..cctor () (at Assets/AVProVideo/Scripts/Internal/OSXMediaPlayer.cs:429)
Rethrow as TypeInitializationException: The type initializer for 'RenderHeads.Media.AVProVideo.OSXMediaPlayer' threw an exception.
RenderHeads.Media.AVProVideo.MediaPlayer.CreatePlatformMediaPlayer () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:1906)
RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:779)
RenderHeads.Media.AVProVideo.MediaPlayer.Start () (at Assets/AVProVideo/Scripts/Components/MediaPlayer.cs:825)`

Unity Version: 2021.3.35f1
Apple mac OS : Sonoma 14.3
Chip: Apple M1 Pro


Please suggest a solution
