### ISSUE TITLE
Inconsitent delay/lag on play command.

### ISSUE THREAD

**Issue by TheDevTom** [RenderHeads/UnityPlugin-AVProVideo#962]
**Describe the issue**
We're developing a system to sync up video playback over several android devices. We've confirmed the LAN latency is sub-2ms and its not the root cause of the issue, however, when hitting play on the master device, all devices de-sync and we have determined this to be inconsistent buffering of the video before it starts playing.

Is there a way to pre-buffer the video or reduce the "lag" when first playing the film, it basically needs to be instananeous or at least consistent so we can account for it, the goal is to have playback across all devices to be sub 45ms (or 1 frame) I have played with some of the playback/start buffer MS timings to no avail.

**Your Setup (please complete the following information):**
 - Unity version:  2019.4.24
 - AVPro Video version:  V2
 - Operating system version: Android 10 
 - Device model:  S21 Ultra
 - Video specs (resolution, frame-rate, codec, file size):  4k VR, 5gb~

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by TheDevTom** [comment]
Hey,

I tried this and theres still discrepancies in how the headset loads, sometimes its perfectly in sync and others its 50-100ms behind!

**Comment by kahnivore** [comment]
What do you mean loads? Do you mean play? It should already be loaded at this point.

**Comment by TheDevTom** [comment]
I mean play sorry, basically, theres a slight difference in the time it plays the first frame when hitting play on the phones (ie i hit play then it doesnt play for 30-40ms, other times it instant, and other times its 75ms+)  I really need this to be as consistant as possible

**Comment by kahnivore** [comment]
Strange - we will try to reproduce this and get back to you.

**Comment by TheDevTom** [comment]
Thanks if theres anything required from my end let me know.
