### ISSUE TITLE
What is the license of AVProVideo itself?

### ISSUE THREAD

**Issue by tylkomat** [RenderHeads/UnityPlugin-AVProVideo#963]
**Question**
What is the license of AVProVideo itself? I only found license information of the software that is used by AVProVideo, but not about the AVProVideo itself.

**Comment by kahnivore** [comment]
Our license matches the Unity Eula (see [here](https://unity3d.com/legal/as_terms)) as we sell our plugins through the Asset Store. 

The one exception is the Enterprise edition (see a breakdown of the different editions [here](https://www.renderheads.com/content/docs/AVProVideo/articles/download.html#editions)), which uses a custom Eula and is sold separately from the store.
