### ISSUE TITLE
Android OES Shader + High Quality checked on Material renders upside down

### ISSUE THREAD

**Issue by downkirkland** [RenderHeads/UnityPlugin-AVProVideo#968]
**Describe the issue**
Leveraging either EOS shader, if you playback the video leveraging your applytomesh, 360 material and shader it will playback but not at same quality.  If you then select "high quality" in your 360-demo material, it displays upside down.  I notice posts on verticalflip.  Is there an easy way to turn on/off verticalflip?  

*Unity version: 2020.3.17f1
AVPro Video version: Android 2.2.1
Operating system version: Mac
Device model: Quest 2
Video specs (resolution, frame-rate, codec, file size): 5.7k 30fps h264 360 stereo

**To Reproduce**
See above.

**Comment by downkirkland** [comment]
(note OES Shader)

**Comment by kahnivore** [comment]
Confirmed regression in 2.1.0, for a combination of OES mode and high quality checked.

**Comment by RenderHeadsSte** [comment]
@downkirkland Here are some early release OES VR shaders with, I hope, a fix for this issue.  Do let us know if this works as you expect.

[Android_OES_VR_Shaders.zip](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7506477/Android_OES_VR_Shaders.zip)

**Comment by AndrewRH** [comment]
@downkirkland AVPro Video 2.2.4 has just been released and should resolve the issue you reported.  Thanks,
