### ISSUE TITLE
Setting negative playback rate causes error to log when using Hap/NotchLC video

### ISSUE THREAD

**Issue by AndrewRH** [RenderHeads/UnityPlugin-AVProVideo#969]
Playback continues though at the previous rate

Perhaps SetRate/IsRateSupported should just return S_OK but not do anything instead of returning unsupported?

This happens with/without Custom MOV Parser

With normal H264 MP4 playback setting negative rate has no effect other than playback stalling

**Comment by Ste-RH** [comment]
Closing due to age of issue.
