### ISSUE TITLE
video texture not release on ios

### ISSUE THREAD

**Issue by jackeypool** [RenderHeads/UnityPlugin-AVProVideo#97]
I am using avpro in my game for video playback.  
I met with a problem on ios, after a video playback some video texture still in video ram even when MediaPlayer is Destroyed.
Can i have anyway to Destroy all texture after the playback is done?

**Comment by MorrisRH** [comment]
Hi!
Can I get a little more information from you:
- Unity version
- AVPro Video version
- iOS version
- iOS device type
- Renderer type (OpenGL/Metal)
Also, how are you determining that the texture hasn’t been freed?
Thanks!

**Comment by jackeypool** [comment]
Thanks for responde so quickly.
As for the info you want:

Unity 5.6.4

Avpro versin 1.8.7

iOS version 12.3.1

iphone6s plus

Renderer type (OpenGL/Metal)   try them both , same result



------------------ 原始邮件 ------------------
发件人: "Morris Butler"<notifications@github.com>;
发送时间: 2019年6月29日(星期六) 下午4:59
收件人: "RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com>;
抄送: "859868203"<859868203@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] video texture not release onios (#97)




Hi!
 Can I get a little more information from you:
  
Unity version
 
AVPro Video version
 
iOS version
 
iOS device type
 
Renderer type (OpenGL/Metal)
 Also, how are you determining that the texture hasn’t been freed?
 Thanks!

**Comment by jackeypool** [comment]
Thanks for responde so quickly.
As for the info you want:

Unity 5.6.4

Avpro versin 1.8.7

iOS version 12.3.1

iphone6s plus

Renderer type (OpenGL/Metal)   try them both , same result

I use xcode to capture a gpu frame and many CoreVideo* texture in video memory



------------------ 原始邮件 ------------------
发件人: "Morris Butler"<notifications@github.com>;
发送时间: 2019年6月29日(星期六) 下午4:59
收件人: "RenderHeads/UnityPlugin-AVProVideo"<UnityPlugin-AVProVideo@noreply.github.com>;
抄送: "859868203"<859868203@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [RenderHeads/UnityPlugin-AVProVideo] video texture not release onios (#97)




Hi!
 Can I get a little more information from you:
  
Unity version
 
AVPro Video version
 
iOS version
 
iOS device type
 
Renderer type (OpenGL/Metal)
 Also, how are you determining that the texture hasn’t been freed?
 Thanks!

**Comment by MorrisRH** [comment]
AVPro Video version 1.8.7 is over a year old now so I would recommend that you upgrade as there have been many improvements.

The CoreVideo* textures you mention are part of a caching scheme. They are just handles that get reused as the video plays back and not bound memory.

**Comment by jackeypool** [comment]
Should CoreVideo* textures be free when MediaPlayer is Destroyed?

**Comment by MorrisRH** [comment]
Would it be possible for you to upgrade to the latest and confirm that you still have this problem?

**Comment by MorrisRH** [comment]
It does appear that the cache isn't clearing itself up correctly, sorry for any confusion on my part.
A fix will be available in the next release.

**Comment by AndrewRH** [comment]
I'm closing this issue now as the fix will be in AVPro Video 1.10.0
