### ISSUE TITLE
Dynamically change adaptive resolution settings on Android

### ISSUE THREAD

**Issue by ondevChrisD** [RenderHeads/UnityPlugin-AVProVideo#970]
**Describe the issue**
Android adaptive resolution & bitrate does not work.
The iOS adaptive resolution & bitrate works well.

**Your Setup:**
 - Unity version: 2021.1.21f1 & 2020.3.19f1 LTS
 - AVPro Video version: 2.2.1 ultra build 815, Ultra Paid version.
 - Operating system version: MacOS 11.6
 - Device model: Samsung S8, SM-G950F, Android 9
 - Video specs (resolution, frame-rate, codec, file size): HLS Multibitrate, 30fps, H.264, 240x240 up to 3860x3860, see HLS URL.

**To Reproduce**
1. Setup Player with:

                    // ANDROID Start adaptive stream using the lowset resolution - ExoPlayer only
```
                    player.PlatformOptionsAndroid.videoApi = Android.VideoApi.ExoPlayer;
                    player.PlatformOptionsAndroid.startWithHighestBitrate = false;
                    player.PlatformOptionsAndroid.minBufferMs = 2000;
                    player.PlatformOptionsAndroid.maxBufferMs = 5000;
                    player.PlatformOptionsAndroid.bufferForPlaybackMs = 2000;
                    player.PlatformOptionsAndroid.bufferForPlaybackAfterRebufferMs = 4000;

                    player.PlatformOptionsAndroid.preferredMaximumResolution = OptionsAndroid.Resolution.NoPreference;
                    player.PlatformOptionsAndroid.preferredPeakBitRate = 40.0f; 
                    player.PlatformOptionsAndroid.preferredPeakBitRateUnits = OptionsAndroid.BitRateUnits.Mbps;
```

2. Start Player with source: 
https://gms001.s3.ap-southeast-2.amazonaws.com/video/hls/360/iiv/001/source/source_03/playlist.m3u8

3. When playing Set Params:

```
                        player.PlatformOptionsAndroid.preferredMaximumResolution = OptionsAndroid.Resolution.NoPreference;
                        player.PlatformOptionsAndroid.preferredPeakBitRate = 40.0f; 
                        player.PlatformOptionsAndroid.preferredPeakBitRateUnits = OptionsAndroid.BitRateUnits.Mbps;
```
  OR
```
                        player.PlatformOptionsAndroid.preferredMaximumResolution = OptionsAndroid.Resolution._480p;
                        player.PlatformOptionsAndroid.preferredPeakBitRate = 0.1f;
                        player.PlatformOptionsAndroid.preferredPeakBitRateUnits = OptionsAndroid.BitRateUnits.Mbps;
```

**Comment by RenderHeadsSte** [comment]
This may not be possible but I will investigate

**Comment by ondevChrisD** [comment]
Dynamically changing adaptive resolution or Dynamically changing PeakBitrate it's very important for us.
We have previously purchased the Video edition and now purchased the Ultra Edition. 
We also considering purchasing the Enterprise Edition​ (depending it has the features we need. )

**Comment by RenderHeadsSte** [comment]
I think I have found a way this can be achieved on Android.  The (possible) problem is...that I think that if you set the preferred resolution/bitrate to something lower than what is currently being played, you will get a hard 'cut' down to a stream that fits to your new lower parameters.

This will hopefully make it into the next release.

**Comment by ondevChrisD** [comment]
Great, can't wait to see the results.
At the end of the day, it works for the iOS player, so we have something to compare it with.

**Comment by RenderHeadsSte** [comment]
Word of warning.  We will unlikely be able able to match Android to iOS exactly.

Currently looking at an option that would allow seamless transitions.  Downside is that the switch will only happen when the current downloaded buffer has been exhausted.  Lowering the buffer values should allow for quicker switching.  However, those values are not changeable on the fly.  Currently this is not working due to something odd happening in ExoPlayer that I do not fully understand yet.

**Comment by acgourley** [comment]
We'd be interested in being able to set the maximum resolution for the HLS ladder on Android as well, although we don't need it during playback, as simply being able to change it before playing a new video would be fine. In my testing so far, it seems like maximum resolution only is used if it's set before the AndroidMediaPlayer constructor runs.

**Comment by Ste-RH** [comment]
With the changes we were able to make to Android in v3.x, we can finally deliver this on Android and bring it into line with iOS.

To do this you will need to do something like the following:

```csharp
PlatformOptions platformOptions = myMediaPlayer.GetCurrentPlatformOptions();
OptionsAndroid optionsAndroid = (OptionsAndroid)( platformOptions );

optionsAndroid.preferredMaximumResolution = MediaPlayer.PlatformOptions.Resolution._480p;

OR

optionsAndroid.preferredMaximumResolution = MediaPlayer.PlatformOptions.Resolution.Custom;
optionsAndroid.customPreferredMaximumResolution = new Vector2Int( 800, 600 );
```

You can also change 'preferredPeakBitRate'.

The only gotcha is that the API will use up whatever it has already buffered, and so any change would not be instant.

This will be available in the next release - which will be either 3.0.12 or 3.1.0 and should be released in the next few weeks.

**Comment by Ste-RH** [comment]
AVPro Video v3.1.0 has just been released. Please do report back if the fixes in the version address the issue.
