### ISSUE TITLE
Stereoscopic 360 video not working in Android (Quest 2)

### ISSUE THREAD

**Issue by RuudvanReenen** [RenderHeads/UnityPlugin-AVProVideo#971]
**Describe the issue**
I'm using a mediaplayer object (A) with the following components:
- A MediaPlayer:
  Visual > Layout Mapping: Equi Rectangular 360
  Video API: Exo Player
  Platform Specific > Windows > Use Stereo Detection: unchecked, I'm forcing TB by setting it in Apply To Mesh and in the shader
  Platform Specific > Android > OES Rendering: unchecked
- Apply To Mesh: 
  Automatic Stereo Packing: unchecked
  Override Stereo Packing: Top Bottom
  Stereo Red Green Tint: checked
  Renderer Target: a sphere object (B)
- Update Multi Pass Stereo: camera set to the OVRCameraRig CenterEyeAnchor camera

Sphere object (B) with the following components:
- Mesh Filter: OctahedronSphere (from Demos) 
- Mesh Renderer with 1 material: Sphere360-AVPro-TB (C)
 
Material Sphere360-AVPro-TB (C):
- Shader: AVProVideo/VR/InsideSphere Unlit (stereo+fog) with:
  Stereo Mode: Top_Bottom
  Stereo Debug Tinting: checked

Result when playing in Editor on Windows with Oculus Link: only one part of the video (top or bottom) is projected (monoscopic with correct mapping) onto the sphere, and there's no color tinting while it's set in both Apply To Mesh and Shader settings.
When changing Platform Specific > Windows> Use Stereo Detection: checked, the video is correctly mapped, is stereoscopic and with correct color tinting.

It looks like the Top/Bottom override settings of Apply To Mesh and of the shader itself are ignored, the video only shows correctly when  'Use Stereo Detection' is enabled in the Windows Platform settings.

Also, this only works for Windows, when building for Android and running on the Quest:
Video shows with incorrect mapping (top and bottom are squashed onto the sphere as if the video is a monoscopic 360 video: left eye video shown above the horizon, right eye video shown below the horizon, also no color tinting.

Any ideas how this can be solved?

**Your Setup (please complete the following information):**
 - Unity version: 2018.4.22f1
 - AVPro Video version: 2.2.2
 - Operating system version: Windows 10 x64
 - Device model: Quest 2 on Android 
 - Video specs (resolution, frame-rate, codec, file size): MP4, H265, 4096x4096, 30fps, 40Mbit/s

**Comment by kahnivore** [comment]
Sounds like the decoder isn't auto detecting it then?
