### ISSUE TITLE
iOS Simulator support

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [RenderHeads/UnityPlugin-AVProVideo#972]
**Describe the issue**
It seems like AVProVideo framework doesn't include support for x86_64 and arm64 iOS simulators. This effectively results in only being able to debug the app on real devices, which slows down development significantly.

Is this is a bug? I can see iOS simulator listed as supported in this old manual:
https://usermanual.wiki/Document/AVProVideoUserManual.1161305271/view

But I can't find anything else about iOS simulator support in any of changelogs otherwise.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.20
 - AVPro Video version: 2.2.2
 - Operating system version: 

**To Reproduce**
1. Create a new Unity project, switch to iOS, import AVProVideo
2. In iOS Player Settings, set `Target SDK` to `Simulator SDK`
3. Attempt to build & run the Xcode project.
4. Observe the build failure.

**Logs**
```
# file AVProVideo

AVProVideo: Mach-O universal binary with 2 architectures: [arm_v7:Mach-O dynamically linked shared library arm_v7] [arm64]
AVProVideo (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
AVProVideo (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Screenshots**
![image](https://user-images.githubusercontent.com/928550/137519505-4c6229e0-b57a-43a2-b25f-539050acf527.png)

**Comment by ZimM-LostPolygon** [comment]
Thank you. Even if you re-introduced simulator support just for the `x86_64` platform (which you can still do with a single framework) that would be enough for most cases - after all, Apple Silicon Macs can run x86_64-based simulators, even though under emulation.

**Comment by InvivoLuke** [comment]
Thanks, @MorrisRH, our team would also benefit greatly from running being able to run our QA pipelines with iOS Simulator.
Consider this my 👍, for re-introducing simulator support!

**Comment by lourd** [comment]
Hi @MorrisRH and @AndrewRH! We at Spatial are also keenly interested in getting a version of the framework that runs in the simulator. It looks like the Unity issue you linked was resolved in 2021.2. Hopefully that means this is possible to get done in the near term? This would be a really big boost for our team. Please let us know if we can help out in any way!

**Comment by MetaBenji** [comment]
Hey @MorrisRH and @AndrewRH if there's anything I can do to help with iOS simulator support let me know!  Your plugin is fantastic and it would be so helpful to get it working on the iOS simulator!

**Comment by dw8869** [comment]
@MorrisRH 
any update?

**Comment by MorrisRH** [comment]
Simulator support for iOS and tvOS will be available from v3 onwards. Just need Unity to support the simulator on Apple Silicon.
