### ISSUE TITLE
[2.2.2] Volume property is ignored after first runtime load on iOS & MacOS

### ISSUE THREAD

**Issue by ewout-create** [RenderHeads/UnityPlugin-AVProVideo#977]
**Describe the issue**
When loading videos from a file at runtime, AVPro doesn't allow me to change the volume after the first time. The AudioVolume property does nothing and neither does SetVolume.

I have even tried assigning a value to the volume on each event the media player fires and this doesn't even work. The sample code & steps work fine on Windows but on MacOS & iOS nothing I do seems to work.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.20f
 - AVPro Video version: 2.2.1, 2.2.2
 - Operating system version: MacOS 11.4, iOS 15.0.1
 - Device model: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports), iPad (8th generation)
 - Video specs (resolution, frame-rate, codec, file size): sample file included in plugin RenderHeads-1080p30-H264.mp4

**To Reproduce**
1. Set up a new Unity 2020.3.20f project on a MacBook. 
2. Set the build target to iOS.
3. Add this component to your project
```
using RenderHeads.Media.AVProVideo;
using System;
using System.IO;
using UnityEngine;
using UnityEngine.UI;

public class VideoVolumeInput : MonoBehaviour
{
	[SerializeField] private MediaPlayer _mediaPlayer;
	[SerializeField] private Slider _volumeSlider;
	[SerializeField] private Button _playButton, _clearButton, _applyVolumeButton;

	private void Start()
	{
		_volumeSlider.minValue = 0f;
		_volumeSlider.maxValue = 1f;

		_playButton.onClick.AddListener(OnPlayClicked);
		_clearButton.onClick.AddListener(OnClearClicked);
		_applyVolumeButton.onClick.AddListener(OnApplyVolumeClicked);
	}

    private void OnApplyVolumeClicked()
    {
		_mediaPlayer.AudioVolume = _volumeSlider.value;
    }

    private void OnClearClicked()
    {
		_mediaPlayer.CloseMedia();
    }

    private void OnPlayClicked()
    {
		_mediaPlayer.OpenMedia(MediaPathType.RelativeToStreamingAssetsFolder, Path.Combine("AVProVideoSamples", "RenderHeads-1080p30-H264.mp4"));
	}
}
```
4.  Put it in your scene along with: 3 buttons, a slider, a media player component.
5.  Add references to the VideoVolumeComponent in the scene to the buttons, slider & media player.
6. Press the play button.
7. Drag the slider all the way to the left.
8. Press the apply volume button.
9. At this point changing the volume works.
10. Press the clear button.
11. Press the play button again.
12. The video starts playing and reverts its volume back to a default.
13. Now we have no way of changing the volume anymore, the slider & the apply button don't function anymore.

**Videos**
I've added a video (without sound unfortunately) to illustrate how to use the test.

This is a small and easily reproducible sample, this issue occurs in a much larger project. So if there are some issues with the sample I've provided, I'll gladly provide more information or expand the reproduction step

https://user-images.githubusercontent.com/10611478/138073376-faa6b745-2141-4521-ab19-0c1ba07f6ac0.mov

**Comment by MorrisRH** [comment]
A fix will be available in the next release
