### ISSUE TITLE
Error loading and running 360 videos in new Unity

### ISSUE THREAD

**Issue by michael-gonzalez** [RenderHeads/UnityPlugin-AVProVideo#98]
**Describe the bug**
After porting our project from 2017.2.0f3 to 2019.1.8f1, we can no longer play any 360 video due to the below error. I have tried to create a new empty scene in our project, put a 360 video player in the scene, pre load one of our videos and run the application. Doing this I still get the error. But if i create a completely new project, create the same scene in the same way, i get no errors and everything works fine. If i port my project over to 2018.4 3f1 i have no issues either. 
Stereo or mono videos it doesnt matter. 

I have also tried the steps in a similar report and it hasnt worked.
 https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/50 

**Your Setup (please complete the following information):**
 - Unity version: 2019.1.8f1
 - AVPro Video version: 1.9.17
 - Operating system version: Android 8.1.0
 - Device model: Samsung Galaxy Tablet S4
 - Video specs (resolution, frame-rate, codec, file size): 
Stereo: 3840x2160
Mono: 3840x1920

**To Reproduce**
1. Port a project from 2017.2.0f3 to 2019.1.8f1
2. Create an empty scene
3. Drop 360 video prefab into scene
4. Preload video from streaming assets folder into the prefab
5. Set media player to auto open and play.
6. Build and run the application

**Logs**
2019-07-02 15:36:55.277 15328-15343/? E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo
    java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:78)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.RenderHeads.AVProVideo.AVProMobileVideo" on path: DexPathList[[zip file "/data/app/com.Company.PulseIQ-5C--oyVR33UmxABAfQwIYA==/base.apk"],nativeLibraryDirectories=[/data/app/com.Company.PulseIQ-5C--oyVR33UmxABAfQwIYA==/lib/arm, /data/app/com.Company.PulseIQ-5C--oyVR33UmxABAfQwIYA==/base.a

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
I know you already said you looked at the ARM64 issue, but that's the only thing I can think of at the moment, since it says "ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo"

Could you check whether it's trying to do a ARM 64-bit build?  Check in Player Settings.  That could be the problem.  

Also go to /Assets/Plugins/Android/libs/arm64-v8a and click on each file and make sure it is assigned the correct platform+architecture

Does that help?

**Comment by michael-gonzalez** [comment]
> I know you already said you looked at the ARM64 issue, but that's the only thing I can think of at the moment, since it says "ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo"
> 
> Could you check whether it's trying to do a ARM 64-bit build? Check in Player Settings. That could be the problem.
> 
> Also go to /Assets/Plugins/Android/libs/arm64-v8a and click on each file and make sure it is assigned the correct platform+architecture
> 
> Does that help?

I have rechecked the files and all are arm64 and android is ticked.

I also checked the build settings and target to arm64 is not available at all so its not possible.

Im not sure what else to do because if i start a new project and try to load a video, it works fine. Could it be some left over data/metadata from the old version when we imported the new version of AVPro?

**Comment by jaymie-timperley** [comment]
I just had the same issues. You also need to change the CPU to ARM64 this fixed it for me.
![screenshot_arm64](https://user-images.githubusercontent.com/13405318/60725527-300ec900-9f31-11e9-9626-bafa636e6a33.jpg)

**Comment by AndrewRH** [comment]
@michael-gonzalez  does the above help at all?  Sorry if we're repeating the same thing...I'm just not sure what else to suggest at this point.

As for leftover files - check the Android folder and make sure you have:
audio360-exo28.jar  and delete any other audio360-exo*.jar

**Comment by michael-gonzalez** [comment]
Yep i tried all of the above and it didn't work.

BUT i did end up getting it to work. These are the steps i took, I'm guessing it came down to meta file issues.

1. Deleted the project and pulled a clean build from our repo.
2. Converted the project to 2019.1.2f1 (Changed to this as Oculus recommended this version).
3. Deleted AVPro from the project.
4. Reimported AVPro.
5. Remade our media player prefabs with the updated AVPro prefabs.
5. Closed Unity, deleted the Library folder and reopened the project. 

After all these steps it is now working. Im not sure what exactly solved the problem, but hopefully this could help someone down the track
