### ISSUE TITLE
CloseMedia takes about a second hanging the main thread

### ISSUE THREAD

**Issue by patrikmrazek** [RenderHeads/UnityPlugin-AVProVideo#983]
When closing a video on Android, calling `MediaPlayer.CloseMedia()`, the operation sometime (I would say with 33% probability) takes over a second for some videos, freezing the main thread, which is unacceptable for our VR app. Profiler says that this single line in `AndroidMediaPlayer::CloseMedia()` takes the whole processing time.
`m_Video.Call("CloseVideo");`

We have tried multiple setups using both MediaPlayer and ExoPlayer, we tried AVPro1 paid and a trial version of AVPro2. It's all the same. Any help would be much appreciated.

Thank you.

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.14f
 - AVPro Video version (literally any, last try on trial 2.2.1): 
 - Operating system version:  Android 10
 - Device model: Oculus Quest 2
 - Video specs (resolution 3840*780@50fps, codec H264 - MPEG-4 AVC (part 10) (avc 1), file size 3.1MB):

**Comment by patrikmrazek** [comment]
Yes, as stated in the original post we have tried to upgrade to 2.2.1 trial version - it also hangs for about a second on the same line.
The media is stored locally in `Application.persistentDataPath` subfolder.
I am sending an example video to the unitysupport email in a minute.

Thank you for the support!

**Comment by RenderHeadsSte** [comment]
This does not sound right at all.  I will run some timing analysis on various aspects of the close process and see if I can narrow down what might be causing it.  Have you profiled your close/open procedure at all?  IF so, anything to report?

**Comment by patrikmrazek** [comment]
From the Unity profiler the application hangs the whole time on this line `m_Video.Call("CloseVideo");` from `AndroidMediaPlayer::CloseMedia()`. This however does not happen every time I close a video but like on every third one aprox.

**Comment by RenderHeadsSte** [comment]
I have looked into the close routine in our MediaPlayer API path and narrowed down the culprit to I think a single call:

m_MediaPlayer.reset();

This, however, is essential.  Without resetting the player it will not be possible to open another video on that player.  See [here](https://developer.android.com/reference/android/media/MediaPlayer) for an explanation.

I have looked at possible spinning the reset up on a thread, and so far not seen any bad results - though that is not to say it is thread safe.  Moving this call to a thread would also likely require deeper changes (e.g. defer opening a video if the reset has not completed yet).

I will look into the ExoPlayer path next.

**Comment by patrikmrazek** [comment]
Thank you for narrowing that down. I tried to create a prototype of CloseMediaAsync method. I used the body of CloseMedia and called `m_Video.Call("CloseVideo");` on a separate thread. I used a coroutine to check when the thread has finished and tried continuing with `base.CloseVideo();` on the main thread from the coroutine. Loading of next video was supposed to start after the `base.CloseVideo();` However the only thing I got was a crash so I guess that was not probably the right way to go :)

**Comment by RenderHeadsSte** [comment]
I have offloaded the expensive reset in the close onto a thread, and also moved almost the entire open'
the above approach in the MediaPlayer API path as it appears to be thread safe. I guess time will tell!

ExoPlayer is a different animal and such a change will not be quick and quite a bit architecture change.  I am putting into the 'more thought required' category of our roadmap.

Hopefully, all being well, this change should make it into v2.2.4.  It is unfortunately not possible to back-port this to v1 even if we were still adding features/fixes and so will be v2 only.

**Comment by patrikmrazek** [comment]
So glad to hear that. This solution will do for us. Many thanks!

**Comment by AndrewRH** [comment]
AVPro Video 2.3.0 has been released and includes a fix for this issue.  Thanks,

**Comment by patrikmrazek** [comment]
Thank you!
