### ISSUE TITLE
On version 2 the TextureProducer does not generate the texture on Android (but it works on iOS). It used to work on version 1.

### ISSUE THREAD

**Issue by AntonioStissi** [RenderHeads/UnityPlugin-AVProVideo#985]
In AVPro version 1 I used to do the following in order to keep the last frame visible during a transition between two videos.

```
Texture2D currentFrame = (Texture2D)mediaPlayer.TextureProducer.GetTexture();
Graphics.Blit(currentFrame, TransitionRenderTexture);
TransitionScreenMeshRenderer.material.SetTexture("_MainTex", TransitionRenderTexture);
```

This method still works fine on version 2 when I build for iOS but it doesnt work when building for Android (both Exoplayer and Mediaplayer). A black frame is shown instead.

This is my setup:
 - Unity version:  2020.3.13
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.2.3 (core)
 - Operating system versions: Android for PicoVR, Android for OculusQuest, Android 7.0
 - Device model: Pico VR / Oculus / smartphones
 - Video specs (resolution, frame-rate, codec, file size): 4k 360 video ( 3840 x 1920 ) H.264

**Comment by AntonioStissi** [comment]
Hi, I checked and the texture count is equal to 1 before i read the texture. I am not using OES rendering.
Any other things I could check?

**Comment by AntonioStissi** [comment]
Hi, I finally found the issue, updating from v1 to v2 broke a link to the shader on the sphere screen so that's why it was not showing up. Now my guess is that on iOS the frame persist automatically in the player that's why it was working fine there.

**Comment by AntonioStissi** [comment]
Thank you a lot for the help!

**Comment by kahnivore** [comment]
Glad it's sorted, thanks for letting us know!
