### ISSUE TITLE
World space canvas in front of 3D video causes ghost image at canvas edges in VR

### ISSUE THREAD

**Issue by blevok** [RenderHeads/UnityPlugin-AVProVideo#987]
Hi, i'm using AVPro 1.11.7 in Unity 2019.4.23f1 and building for Oculus Quest 2.
I did buy version 2 a few months ago, but it seems there's some things that version 1 could do that version 2 can't, and they're important for my app, so i guess i have to roll with version 1 for this, which is fine, but i'm having an issue with 3D video.

I have a sphere where i'm displaying a 360 degree 3D top/bottom video on the inside surface using ApplyToMesh and the InsideSphere Unlit Transparent shader. Inside the sphere i have a camera at (0,0,0), and a world space canvas in front of it.

When i look at the scene in the headset, the video on the sphere appears slightly offset to the right in the left eye, and slightly left in the right eye, in relation to the canvas, which creates a sort of ghosting effect along the right and left edges of the canvas.

The canvas also shows video, but it really doesn't matter what is on it. Even with just a UI panel on it, the ghosting issue is always noticeable. However if the video on the sphere is 2D then the issue doesn't happen, so i'm guessing it has something to do with a setting in the shader, but i'm not sure what to change.

The attached pic shows the world space canvas and the sphere with the 3D video behind it, and how it looks in the left and right eyes. You can see that the video appears in a different position in each eye, but only when the video on the sphere is 3D. When it's 2D, it lines up normally.

How can i fix this?
Thanks

![3d-perspective-issue](https://user-images.githubusercontent.com/13594103/139347948-cc7699ef-9b76-4ac0-9f9b-74d95161d18b.png)

**Comment by blevok** [comment]
> Hi there,
> 
> It's a bit difficult to understand the issue from the screenshots - not sure what is canvas and what is sphere in those images.

Thank you for the reply.
The square shape at the top left is the canvas. The red circle is pointing out the bottom right corner of the canvas. Everything else in the image is displayed on the sphere. The image shows that the right side of the canvas covers more of the sphere in the right eye than it does in the left eye. Look at the light behind the guitar amp, and notice that the corner of the canvas covers part of the light in the right eye, but it does not cover the light at all in the left eye. So basically i see something in one eye that i don't see in the other eye, making it impossible to focus my vision on the edge of the canvas. It's the same thing happening in reverse on the left side of the canvas, which is not shown in the image.

> 
> Also interested to know which features of version 1.x you're relying on that aren't in version 2.x?

It's mainly 2 things.
First, i need to prevent it from automatically detecting 3D videos and changing packing settings, so that i can explicitly control those things in code at all times. My app is marketed toward advanced users that want full control over all settings, without the app automatically doing anything for them.
And second, i need to show a default image in 3D, before a video is loaded. The UI has buttons to select the stereo packing format for both the canvas and the sphere. I have a default image set in ApplyToMesh/DisplayuGUI, which is just the logo for my app. When the app starts, stereo packing for both surfaces is set to none, and the default images for both surfaces is normal 2D. When the user changes the stereo mode of one of the surfaces, say from 2D to 3D left/right for example, if there is no video open, the default image is replaced with one that is 3D, matching the packing format that they selected. This is a visible indication to the user that the video surface is displaying in 3D. If a video is currently playing, then obviously they will see the video in 3D when they press the button, but if no video is open, then seeing the logo image become 3D is the indication that the setting has been applied.

When i posted about this on the forum, i was told that the only way to control the stereo packing is to switch to a shader that doesn't know anything about 3D. This seems to only be a partial solution, allowing the user to see the video either in 2D, or in the correct version of 3D. But it does not allow the user to select the wrong version of 3D, or to see the default image in 3D.

Note that it's been months since i discovered the issues and decided to switch back to version 1. If these capabilities have been added since then, then i'm unaware, but i would gladly switch again if i can make these things work. I have been watching the patch notes though and i haven't seen anything about it, though it's possible i could have missed it.

> 
> Perhaps the sphere is too close, and what you're seeing is the stereo of the geometry as well as the video. What scale is the sphere currently? Perhaps you could try scaling it a lot bigger and seeing if that makes a difference. In theory we want the sphere to appear infinitely far away so that we don't see any parallax.

The sphere scale is 7. The user can control the position of the canvas inside the sphere. Whether the canvas is moved close to the edge of the sphere, or close to the camera, the issue remains the same. The camera is in the center of the sphere, with a fixed FOV, and can only rotate, it cannot move its position, so there is no parallax effect happening. I do have a bit of parallax in the android version of the app, which i think is because i allow the user to change the FOV of the camera. But this is not allowed on Oculus Quest, which is why the canvas can move instead.

**Comment by kahnivore** [comment]
Hi there,

Regarding not seeing the same thing in each eye - that sounds correct for stereo?

Have you tried [forcing the eye mode](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html#forcing-stereo-eye-mode) by using VideoRender.SetupStereoEyeModeMaterial(material, StereoEye.Left);  (from the version 2.x docs)?

**Comment by blevok** [comment]
> Hi there,
> 
> Regarding not seeing the same thing in each eye - that sounds correct for stereo?

Technically yes, seeing a different perspective in different eyes is normal, but it's not behaving in the way that i would expect when another object is introduced. Any 3D object that is in the scene will be seen from a slightly different perspective, as expected, and if i put one 3D object in front of another, the different perspectives give me a sense of depth, and i can tell that they exist at different distances from the camera. The difference is that i can clearly focus on both objects, but for some reason it's not working the same way when 3D video is involved. When a 3D video is in view, it becomes impossible to focus on the left and right edges of anything else.

Maybe this is just impossible to work around, i don't know, it's a very complicated problem to wrap my head around. It just seems like the 3D video somehow isn't acting like "part of the scene". I was just hoping that someone who fully understands how the shaders work could explain what's happening and why it happens, which could trigger a light bulb in my head to come up with a fix.

> Have you tried [forcing the eye mode](https://www.renderheads.com/content/docs/AVProVideo/articles/feature-stereo-video.html#forcing-stereo-eye-mode) by using VideoRender.SetupStereoEyeModeMaterial(material, StereoEye.Left); (from the version 2.x docs)?

I've seen this in the docs, but i haven't tried it. I ran into the other limitations with version 2 before i got that far. If it's also in version 1 then i'll give it a try and see what happens. As it stands right now, the 3D issue is the only problem i'm having with version 1, and it's only a minor problem, while the issues with version 2 are actually deal breakers, so i figured it's better to try to work out 1 small problem than 2 major ones.

**Comment by kahnivore** [comment]
Do you have a sample reproducible project you could send to us? 

You can send to unitysupport@renderheads.com with "#987". 

Still think it would be more worth your while to make it work in 2.x - but as you say, if it's just this tiny problem let's try fixing that first.

**Comment by blevok** [comment]
Thanks, i'll put together a sample project that shows the issue as soon as i can.
