### ISSUE TITLE
AVPro Video Windows Edition Livestream HLS Latency

### ISSUE THREAD

**Issue by KasperSeas** [RenderHeads/UnityPlugin-AVProVideo#989]
**Describe the issue**
When receiving a livestream as HLS, there's a delay of about ~32 sec and we're looking for the lowest delay possible. I tried the offset solution found here: https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/741.
The lowest latency I got was about ~25 sec using the seek method that was proposed. Both with WinRT and MediaFoundation Low Live Latency and Low Latency checked.
We noticed that when the Unity instance is played right after the stream goes live for 6 seconds, that there's only a 6 second delay. If the Unity instance is played any time after 6 seconds, the delay accumulates all the way up to ~32sec.
The 6 second delay seems achievable but it's impractical for our application because we cant time to launch the stream right before a unity instance launches. How could we get that 6 second delay after a stream has launched after a while? Thanks!

**Your Setup (please complete the following information):**
 - Unity version: Unity 2021.1.26f1 and Unity 2021.2.0f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro Video - Core Windows Edition v2.2.3
 - Operating system version: Windows
 - Device model: Desktop
 - Video specs (resolution, frame-rate, codec, file size): HLS livestream

**To Reproduce**
1. Go to AVProVideo demo scene "Demo_MediaPlayer"
2. Add livestream HLS url .m3u8 as source
3. Choose Media Foundation video api with "Use Low Latency" checked or WinRT video api with "Low Live Latency" checked
*To reproduce 6 second delay:
4. Start stream (on OBS for example)
5. Wait close to 6 seconds (I play the scene right away because it takes about 6 seconds to load and play anyways)
6. Start "Demo_MediaPlayer" scene
7. Should see a minimum of 6 seconds of delay depending on timing of starting the stream and scene

![Delay9sec](https://user-images.githubusercontent.com/13711663/139489866-a9103bfb-cf6c-434a-94db-75db5fb022e1.png)
*Notice the live time on OBS. 15 seconds of being live - 6 second buffer = 9 second delay

*To reproduce up to ~30 seconds delay:
4. Start stream (on OBS for example)
5. Wait for 30 seconds
6. Start "Demo_MediaPlayer" scene
7. Should see maximum 30 seconds of delay depending on timing of starting the stream and scene.

![Delay30sec9](https://user-images.githubusercontent.com/13711663/139489917-531d689a-1164-4680-8217-4efd04737e02.png)

**Comment by skewerb** [comment]
Bumping this issue to prevent it from closing

**Comment by KasperSeas** [comment]
Bumping to remove stale mark
