### ISSUE TITLE
Event Can not be trigger when open file next time.

### ISSUE THREAD

**Issue by wangyanmeego** [RenderHeads/UnityPlugin-AVProVideo#99]
**Describe the bug**
I want to extract many video's thumbnails, i use the same gameobject with a Mediaplayer compoent, i use Mediaplayer.OpenVideoFromFile() to open a video file, and then add an event listtener, the first time it can trigger th event, after i finished deal with the extracted frame texture, i continued to call the function to open next video file, but this time the event can not be trigger.

**Your Setup (please complete the following information):**
 - Unity version: 2017.1.0f3 personal(64bit)
 - AVPro Video version: 1.6.14
 - Operating system version: win10
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. 
2. 
3. 

**Logs**
no logs
![图片](https://user-images.githubusercontent.com/13783955/60501290-5ee92d00-9cee-11e9-9598-12a3c35e34bb.png)

**Screenshots**

![图片](https://user-images.githubusercontent.com/13783955/60501061-f8fca580-9ced-11e9-9031-94b81be25aae.png)
![图片](https://user-images.githubusercontent.com/13783955/60501259-5133a780-9cee-11e9-89d2-5a1b8e99d8c5.png)

**Comment by RenderHeadsSte** [comment]
I notice you are using a quite old version. The latest published version of AVPro Video is 1.9.17. Could you try updating to the latest version to see if you still see this issue?

**Comment by AndrewRH** [comment]
@wangyanmeego  could you try with the latest version of AVPro Video (1.10.0)?

Thanks,

**Comment by RenderHeadsSte** [comment]
Closing issue due to lack of response.
