### ISSUE TITLE
Can I get video format information?

### ISSUE THREAD

**Issue by cseheon** [RenderHeads/UnityPlugin-AVProVideo#990]
**Question**
Hello.
I am making an app that supports Windows, Mac, Android, and iOS using AVPro.
Each platform app will play the same video.
I know that the video format that can be played on all platforms is H.264 mp4.
When a user tries to play an arbitrary video file, is there a way to check if the video to be played is h.264 mp4 using MediaPlayer?

**Comment by kahnivore** [comment]
Hi there,

Unfortunately there currently no way to retrieve that kind of information from within the plugin. It is however something we are looking to add in the future. I've added a feature request (#997) that you can follow if you'd like to receive updates.

In terms of your specific question - H264 is widely supported, but it still doesn't account for every video - some H264 videos won't play. Perhaps in your case it would be best to play the video in the background and check if there's an error - and if so, don't play it/report to user etc.
