### ISSUE TITLE
[2.2.2] Incorrect date returned on HLS live streaming's #EXT-X-PROGRAM-DATE-TIME through mediaPlayer.Control.GetProgramDateTime() API.

### ISSUE THREAD

**Issue by kodai100** [RenderHeads/UnityPlugin-AVProVideo#991]
**Describe the issue**
Cannot get value of HLS live streaming's #EXT-X-PROGRAM-DATE-TIME through `mediaPlayer.Control.GetProgramDateTime()` API.

https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html
In the document, clearly we can get a #EXT-X-PROGRAM-DATE-TIME tag value through `mediaPlayer.Control.GetProgramDateTime()` API.

**Your Setup (please complete the following information):**
 - Unity version: Unity2021.1.24f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): 2.2.2 Ultra
 - Operating system version: Windows10 Home 19042.1288
 - Device model: Intel Core i7-8700K, NVIDIA GeForce GTX 1080Ti
 - any resolution (HLS streaming)

**To Reproduce**
1. Setup AWS IVS live stream and go live (AWS IVS can have #EXT-X-PROGRAM-DATE-TIME tags every segment)
2. Enter a m3u8 address to MediaPlayer
3. call mediaPlayer.Control.GetProgramDateTime(); and always returns initial value of DateTime type (0001/01/01 0:00:00).

**Logs**
```
void Update() {
    Debug.Log(mediaPlayer.Control.GetProgramDateTime());
    // always 0001/01/01 0:00:00
}
```

**Screenshots**
Here is get a video stream of AWS IVS on AVProVideo MediaPlayer (logging 0001/01/01 0:00:00)
![2021-10-31_153802](https://user-images.githubusercontent.com/20334444/139571447-516aa919-2cd6-4983-8075-51dd0e654452.png)

And here is AWS IVS's m3u8 index file (clearly included #EXT-X-PROGRAM-DATE-TIME tags)
![2021-10-31_154113](https://user-images.githubusercontent.com/20334444/139571521-d69f155b-ad58-4e6f-bcc8-46960bca8b8d.png)

**Videos**
it will be reproduce any live streaming video.

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Can you try switching the Video API to WinRT instead of the default Media Foundation?

Thanks,

**Comment by kodai100** [comment]
Thank you for your reply.

I switched the video API to WinRT and it seems to work!

However, the year parsing seems to be wrong like as follows.
(2021 is expected, but displayed 2390)

this is unity's log

![2021-11-01_001058](https://user-images.githubusercontent.com/20334444/139590362-a37cb8ee-40b4-4faf-9789-15acf2c1b4a6.png)

and this is AWS's m3u8 file detail

![2021-11-01_001420](https://user-images.githubusercontent.com/20334444/139590399-8c721926-7549-48d5-9d8d-cd853bb6815f.png)

Thanks,

**Comment by AndrewRH** [comment]
OH that's interesting...we'll take a look

**Comment by AndrewRH** [comment]
Our date-time conversion calculate was off by 11644473600 seconds (approx 369 days) due to using the Windows NT epoch date 1601 instead of Unix epoch 1970.

This has now been fixed and will be in the next release.

Thanks for submitting this issue report.

**Comment by kodai100** [comment]
Thank you for your quick support !

**Comment by AndrewRH** [comment]
@kodai100 AVPro Video 2.2.4 has just been released and should resolve the issue you reported.  Thanks,

**Comment by guerwan** [comment]
@AndrewRH we have the same issue on macOS/iOS with the latest version (2.6.3): [Issue](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1305#issue-1387747225)
