### ISSUE TITLE
Player zoom out

### ISSUE THREAD

**Issue by LudovicWVirtysens** [RenderHeads/UnityPlugin-AVProVideo#992]
**Question**
Hi,
When I 'm using VLC player in my computeur, I can zoom out the video whith mouse wheel.
Is it possible to change the zoom with AVPRO ?
BR
Ludovic

**Comment by kahnivore** [comment]
Hi, 

There's no built-in feature like this but no reason why you couldn't implement something like this yourself, say by scaling the display component. 

Hope that helps!
