### ISSUE TITLE
Signed version of AVProVideo.dll

### ISSUE THREAD

**Issue by ColinYaoH1** [RenderHeads/UnityPlugin-AVProVideo#993]
Hi,

I am a current customer of AVPro. Firstly, thank you for the wonderful asset. I am wondering if it is possible to provide signed versions of the AVProVideo.dll file in future packages (for security review purposes)? 

Thanks for your consideration!

**Comment by AndrewRH** [comment]
@ColinYaoH1 
Could you please explain more about this requirement?  What is the reason for needing this?

Thanks,

**Comment by ColinYaoH1** [comment]
Hi Andrew,

Yes of course. Our unity application goes through a security review process from an external partner before being released and that review body has asked that we request from third party plugin authors to supply signed .dlls (only if its possible from their end).

Kind regards,
Colin

**Comment by kahnivore** [comment]
Yeah, this isn't something we've done before, nor have we had a lot of requests for it. If it was something many users wanted we'd consider it, but at this point it doesn't seem to be the case. 

Let us know if this becomes urgent for you and we could look into it further.

**Comment by ColinYaoH1** [comment]
Ok thanks for the reply!
