### ISSUE TITLE
Problems Playing Facebook Mpeg Dash LiveStreaming

### ISSUE THREAD

**Issue by gmgm4321** [RenderHeads/UnityPlugin-AVProVideo#994]
**Describe the bug**
As the title.

**Your Setup (please complete the following information):**

Unity version: 2019.4.16f1
UnityPlugin-AVProVideo-v2.2.3-Trial.unitypackage
Operating system version: Window10
Device model: PC
Video specs (resolution, frame-rate, codec, file size): MpegDash

**To Reproduce**
I use youtube-dl to get the streaming URL of Facebook,use AVProVideo-v2.2.3-Trial to play the URL.
Play for a few seconds and then stop

**Logs**
No error.

**Screenshots**

**Videos**
Record Video URL:
https://drive.google.com/file/d/16_nfbQ7PdmRTWhq1gCopjOzVPtgp4j_y/view

**Comment by AndrewRH** [comment]
Try using the WinRT API (in MediaPlayer > Platform Specific > Windows > Video API)

I wouldn't be surprised though if it's due to FB taking measures to prevent easy streaming...

Thanks,

**Comment by gmgm4321** [comment]
> Try using the WinRT API (in MediaPlayer > Platform Specific > Windows > Video API)
> 
> I wouldn't be surprised though if it's due to FB taking measures to prevent easy streaming...
> 
> Thanks,

I tried it and the same situation will happen....:(
