### ISSUE TITLE
Issue with variable uninitialized on iOS in AppleMediaPlayer

### ISSUE THREAD

**Issue by Mildebug** [RenderHeads/UnityPlugin-AVProVideo#995]
**Describe the issue**
Hello ! 

We've got an error in the console panel of Unity when we target the iOS platform with Unity 2021.2.0f1. We can't run the editor in play mode with this error.
The error is just a variable that is not initialized. We didn't have this error with Unity 2021.1.12f1.

The variable is localized in AppleMediaPlayer.cs in the "AddMediaToCache" function : 
![image](https://user-images.githubusercontent.com/90604952/140297137-30745734-2fde-4194-9372-239d43d9c932.png)

We just replace "GCHandle artworkHandle" to "GCHandle artworkHandle = new GCHandle();" and the error disappear.

Is it possible to patch this ?

**Your Setup (please complete the following information):**
 - Unity version: Unity 2021.2.0f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): v2.1.6 trial
 - Operating system version: MacOS Big Sur
 - Device model: Unity Editor
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Launch AVPro on Unity 2021.2
2. Error
3. 

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by MorrisRH** [comment]
A fix will be in the next release, version 2.2.4

**Comment by AndrewRH** [comment]
@Mildebug AVPro Video 2.2.4 has just been released and should resolve the issue you reported.  Thanks,
