### ISSUE TITLE
Best Ffmepg render settings for 8k VR video in AVPro for Unity

### ISSUE THREAD

**Issue by Lucaskexcom** [RenderHeads/UnityPlugin-AVProVideo#996]
Hello,
I'm working on a VR experience in unity and I'm trying to get the best quality out of the footage versus file size. I am developing on a HP reverb g2 headset.

Is there a list of recommended ffmpeg commands that I could use that is best optimized for the AVPro unity plugin?

Thanks

**Comment by kahnivore** [comment]
Hi there,

Please see our [encoding notes](https://www.renderheads.com/content/docs/AVProVideo/articles/encoding-notes.html).

There isn't really a one-size-fits-all though, best to play around and see what's giving you the best quality/performance for your headset/application.

**Comment by kahnivore** [comment]
Also a good idea to check your headset resolution - I think the one you've mentioned is 4k, so 8k would be wasted on it.

**Comment by kahnivore** [comment]
Closing this due to lack of response
