### ISSUE TITLE
AVPro Finishes buffering after first HLS chunk, Never Loads Additional Chunks

### ISSUE THREAD

**Issue by tsi25** [RenderHeads/UnityPlugin-AVProVideo#998]
Our project is in 2018 LTS, targeting android, and we are using the trial version of AVPro 2.X. We are encountering an issue where once the first portion of the HLS stream finishes buffering, it fires the FinishedBuffering event and then never seems to load additional portions of the video from the remote endpoint. It seems almost as if the stream is being interrupted. Once it reaches the end of the buffered content, no further events are fired - it just sort of hangs. If we programmatically pause and resume it from that point it will fire the Stalled video event but it will never seem to Unstall itself. Notably, when we play cached HLS streams from a local directory such as the persistent data path we don't see this same issue - the video loads chunk by chunk as expected. 

We are using the Exo Player video API, although we have tried using the Media Player API without any better results.  

I've also tried altering the Adaptive Stream settings available in the Android section of the Platform specific settings, however it always seems to load in the same amount of content - 120000ms (2 minutes). I've also tried streaming a variety of videos, they all seem to load only up to that same length.

We are passing custom HTTP headers including an Authorization token and a Cookie returned from login in order to prove to the backend that we are an authenticated user, but if this were an issue I'm not sure why it would successfully play a portion of the video as opposed to none of it. 

The endpoint we are hitting is an https endpoint, so I don't think we are hitting the cleartext support issue mentioned in the documentation.

I've tried both Mono and IL2CPP scripting backends but I haven't noticed any significant behavioral differences either way.

I'm sort of out of ideas for what else to try and would appreciate any help or input I can get.

**Comment by kahnivore** [comment]
Have you tried with any other streams? 

Would it be possible to get a sample reproducible project from you? If so, please send to unitysupport@renderheads.com with "#998" in the subject line.

Thanks!

**Comment by tsi25** [comment]
It looks like our dev-ops guy figured it out, there was an issue on the backend causing the cookie and/or bearer token to get expired when they shouldn't have been which was causing the stream to cut out shortly after it started. That is all to say our issue was unrelated to AVPro. Thank's so much for getting back to us so quickly!
