### ISSUE TITLE
Problem playing encrypted HLS fmp4 stream

### ISSUE THREAD

**Issue by qar3ee** [RenderHeads/UnityPlugin-AVProVideo#999]
**Describe the issue**
Hello, I'm currently testing AVPro (trail version) for playing encrypted videos hosted on a web server.
The test video is HEVC/AAC encoded with 5760x2880 resolution.

I tried to create several HLS variants:
Trying to use encrypted hvc1 HLS with TS segments, resulted in iOS not playing due to (for my understanding) lack of support for hvc1 in TS based HLS (only support fMP4 based HLS for HEVC).

So I was trying to use fMP4 based HSL - 
Using **non-encrypted hvc1 fMP4** based HLS (with m4s segments), results in **iOS and Android playing as expected**. However since I have to deliver the content encrypted, I tried to use the same HLS (hvc1, fMP4) **with encryption** - just to see that it's **not playing at all on both Android and iOS**. However it is playing as expected on PC Unity editor and VLC (PC).

Just for the sake of trying to figure out if the encryption is not working - trying to convert to h264 codec and encrypting HLS (with TS segments), results in iOS and Android playing as expected.

Is AVPro player support encrypted fMP4 HLS or is this a bug?

Thanks!

**Your Setup (please complete the following information):**
 - Unity version: 2020.3.20f
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): AVPro 2.2.3 trial
 - Operating system version: Windows 10, Android 11, iOS 15.1
 - Device model: Samsung Galaxy Note 10, iPhone 7
 - Video specs (resolution, frame-rate, codec, file size):  5760x2880, 30fps, 17mbps, hvc1/aac, 580MB

**Comment by kahnivore** [comment]
Not sure if this is supported - could you send the streams you've mentioned to us to test with? 

You're welcome to send to unitysupport@renderheads.com with "#999" in the subject line.

**Comment by qar3ee** [comment]
Thanks, I've sent the link to the stream via email as suggested.

**Comment by MorrisRH** [comment]
The stream was created using an older version of FFmpeg (3.5.1) that supported generating encrypted HLS.

The issue is that the generated manifest places the ``#EXT-X-MAP`` line after the ``EXT-X-KEY`` line. According to the current HLS specification this requires that the map file is encrypted which isn't the case.

The solution is to swap the order of those two lines in the manifest such that the ``#EXT-X-MAP`` line comes before the ``EXT-X-KEY`` line.
